### ISSUE TITLE
USB power properties for laptop.

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#1001]
https://github.com/acidanthera/OpenCorePkg/blob/830f90da82f5fa4e19057cc85d04d7b3c6e27a5c/Docs/AcpiSamples/SSDT-EC-USBX.dsl#L69-L76

Shouldnt we use these below power properties for Laptop ? As this is what injected by USBX device on original macbook* DSDT.

```
                   "kUSBSleepPortCurrentLimit",
                   0x0BB8,
                   "kUSBWakePortCurrentLimit",
                   0x0BB8
```

**Comment by rektimus** [comment]
where did you get these values from?

If you check ACPI dumps, find DSDT for SMBIOS model, it will show expected values. However, these are for real Mac. Ideally you should adjust them specifically for your system.

**Comment by naveenkrdy** [comment]
these are taken from macbookpro16,1 but i believe they are same on all version of macbook's.
adjust specifically for your own system ? i dont know how one can calculate that value ?

**Comment by rektimus** [comment]
you need a USB power meter and to test devices (ideally from windows) and get the mAh (decimal) and convert to hex. 0x0BB8 is 3000mAh. Values from Macs are typically lower than PC.

This will most likely be closed as it's support issue. SSDT is provided as example.

**Comment by vit9696** [comment]
The values are indeed sample there, and they will depend on the hardware. For instance, for my Z87 I definitely need much lower values. One of the good ways to "test" things is to connect an iPad or a similar device in power consumption, and check whether it charges. If the values are too low, then it will not charge, and if they are too high it will constantly reconnect every half a second.
