### ISSUE TITLE
big sur update

### ISSUE THREAD

**Issue by scalpelxxx** [acidanthera/bugtracker#1002]
![11593143304_ pic](https://user-images.githubusercontent.com/64622405/85818352-09314e80-b7a3-11ea-8084-718237f45998.jpg)
report an error about smc

**Comment by scalpelxxx** [comment]
opencore, lilu and its sons are the latest build

**Comment by nieaowei** [comment]
同样的问题0.0

**Comment by scalpelxxx** [comment]
These files were built by myself from the latest update, not released
