### ISSUE TITLE
[Whatevergreen.kext] MacOS crashes randomly upon using igfxfw=2

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#1004]
As the title says, macos is crashing randomly whenever i use igfxfw=2 flag or use it through device injection. 

here are the crash reports :
[crashlog1.txt](https://github.com/acidanthera/bugtracker/files/4836426/crashlog1.txt)
[crashlog2.txt](https://github.com/acidanthera/bugtracker/files/4836428/crashlog2.txt)

Specs :
Dell XPS 7590
i7-9750H 
UHD630
FHD Screen

-Thanks !

**Comment by vit9696** [comment]
Well, yes? We do not plan to look at it though. Could be a good issue for https://github.com/dortania/bugtracker/issues though in case somebody wants to investigate it. @khronokernel, could you move it?

**Comment by 07151129** [comment]
@naveenkrdy do you have kernel log prior to the panic?

**Comment by naveenkrdy** [comment]
> @naveenkrdy do you have kernel log prior to the panic?

hi ! you mean without the flag ?
[kernel_log.txt](https://github.com/acidanthera/bugtracker/files/4842388/kernel_log.txt)

**Comment by 07151129** [comment]
No, I mean with the flag

**Comment by naveenkrdy** [comment]
> No, I mean with the flag
here you go.
igfxfw injected through device properties.
[kernel_boot_log_withflag.txt](https://github.com/acidanthera/bugtracker/files/4842399/kernel_boot_log_withflag.txt)
and btw ! rn using latest whatevergreen from master.

**Comment by 07151129** [comment]
I am asking for a log _prior to_ the panic, not just any log.

**Comment by naveenkrdy** [comment]
> I am asking for a log _prior to_ the panic, not just any log.

oh ok ! sorry i dont have it .
any other way i can get it ?

**Comment by naveenkrdy** [comment]
crashed again today !
[crash.txt](https://github.com/acidanthera/bugtracker/files/4847386/crash.txt)

**Comment by 07151129** [comment]
Those panic logs are all the same and not very useful. If you check kernel log for, say, last three hours (`log show --predicate 'process == "kernel"' --last 3h --style syslog`), do you get kernel log of the boot session when it crashed?

**Comment by naveenkrdy** [comment]
@07151129 hi !
it crashed 5 min back 
generated log using the above command.

[log_.txt](https://github.com/acidanthera/bugtracker/files/4873009/log_.txt)
apart from this i have a question . am i suppose to use pavp flag too ?

**Comment by 07151129** [comment]
Unfortunately it still has nothing useful. Can you test if this PR https://github.com/acidanthera/WhateverGreen/pull/49 helps?

**Comment by naveenkrdy** [comment]
> Unfortunately it still has nothing useful. Can you test if this PR [acidanthera/WhateverGreen#49](https://github.com/acidanthera/WhateverGreen/pull/49) helps?
yup ! compiled it and its been 2 hours and no panic till now . will test it for few more hours and see .
Thanks !
