### ISSUE TITLE
WhateverGreen: bug with -wegnoepu and Intel onboard HDMI

### ISSUE THREAD

**Issue by tylernguyen** [acidanthera/bugtracker#1005]
Hello, thank you for all the work you guys are doing for the community, first off.

My framebuffer patches for HDMI have worked perfectly in the past. Though I rarely use HDMI so I cannot pinpoint when exactly this issue occurred, be it with macOS or Lilu/WEG.
Currently, onboard Intel HDMI will not work unless `disable-external-gpu` or `-wegnoegpu` is added.
**Without** the properties above, HDMI will connect and will output with sound. However, internal display will be black. On a second unplug/plug, HDMI will not output.
I had initially thought it was framebuffer patching on my part. However, after many repeated attempts at redoing patches. **With** the properties above and all else equal, HDMI will output and hotplug normally without issues.

Here are my logs:
**With `disable-external-gpu`**
[Lilu_1.4.5_19.5 with -disable-egpu.txt](https://github.com/acidanthera/bugtracker/files/4837213/Lilu_1.4.5_19.5.with.-disable-egpu.txt)
[OCwith -disable-external-gpu.txt](https://github.com/acidanthera/bugtracker/files/4837221/OCwith.-disable-external-gpu.txt)

**Without `disable-external-gpu`**
[Lilu_1.4.5_19.5 withOUT -disable-egpu.txt](https://github.com/acidanthera/bugtracker/files/4837210/Lilu_1.4.5_19.5.withOUT.-disable-egpu.txt)
[OC withOUT -disable-external-gpu.txt](https://github.com/acidanthera/bugtracker/files/4837219/OC.withOUT.-disable-external-gpu.txt)

Interestingly, 
This is the IOReg **with** the property applied:
<img width="2160" alt="Screenshot_2020-06-26 08 16 20_vLGRnN" src="https://user-images.githubusercontent.com/3349081/85863302-96b37500-b788-11ea-923a-fddfa0c75eb7.png">
and this is with it **NOT** applied:
<img width="2160" alt="Screenshot_2020-06-26 08 19 03_xFIp01" src="https://user-images.githubusercontent.com/3349081/85863409-b9458e00-b788-11ea-87ae-818c86225fc5.png">

Again, the weird thing is that without the properties applied, the HDMI display is not detected under framebuffer 1 but will output for the first plug.

I have also been able to find **similar reports of my issue** here: https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/post-2138892

```
Catalina 10.15.5
OpenCore 0.5.9
Lilu 1.4.5
WhateverGreen 1.4.0
```
My framebuffer patches are here:
**Current EFI: https://github.com/tylernguyen/x1c6-hackintosh**
Intel i7-8650U, UHD 620 Kaby Lake-R
Further spec and info can be found on my repo.

Screenshot of my framebuffer for quick reference:
![Screenshot_2020-06-26 08 47 27_maeb8M](https://user-images.githubusercontent.com/3349081/85864143-bd25e000-b789-11ea-89d8-5370d5623f08.png)

I really hope this is a simply an issue with my framebuffer patching than with WEG. But I'm inclined to suspect the latter.

Thanks again

**Comment by Andrey1970AppleLife** [comment]
Use forums for support. Dortania and other.
