### ISSUE TITLE
SMCBatteryManager causes panics on macOS Big Sur

### ISSUE THREAD

**Issue by CoronaHack** [acidanthera/bugtracker#1006]
Using the latest master of VirtualSMC https://github.com/acidanthera/VirtualSMC/commit/6c5cf92522078830b77fe2127f830790aea7cdec, SMCBatteryManager causes a panic when macOS Big Sur boots.

macOS Version: `20A4299v`
Battery Manufacturer: ASUS

Panic Log:

```log
panic(cpu 10 caller 0xffffff801c5e16a6): Kernel trap at 0xffffff7f9fbe841d, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x0000000000000000, CR3: 0x00000001f1411046, CR4: 0x00000000003626e0
RAX: 0xffffff86cdfb0501, RBX: 0x0000000000000002, RCX: 0xffffff801d069080, RDX: 0x0000000000000002
RSP: 0xffffffa0ad69bbe0, RBP: 0xffffffa0ad69bc10, RSI: 0x0000000000000000, RDI: 0x0000000000000000
R8:  0xffffff86cf1d0730, R9:  0x0000000000000001, R10: 0x0000000000000000, R11: 0xffffff8032b085f0
R12: 0x0000000043483042, R13: 0xffffff86cb1c1720, R14: 0xffffff86cba80800, R15: 0x00000000e00002c2
RFL: 0x0000000000010246, RIP: 0xffffff7f9fbe841d, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0xa, PL: 0, VF: 0

Backtrace (CPU 10), Frame : Return Address
0xffffffa0ad69b600 : 0xffffff801c4b200d mach_kernel : _handle_debugger_trap + 0x3dd
0xffffffa0ad69b650 : 0xffffff801c5eff03 mach_kernel : _kdp_i386_trap + 0x143
0xffffffa0ad69b690 : 0xffffff801c5e12da mach_kernel : _kernel_trap + 0x55a
0xffffffa0ad69b6e0 : 0xffffff801c457b2f mach_kernel : _return_from_trap + 0xff
0xffffffa0ad69b700 : 0xffffff801c4b184d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffa0ad69b820 : 0xffffff801c4b1b43 mach_kernel : _panic_trap_to_debugger + 0x273
0xffffffa0ad69b890 : 0xffffff801ccac87a mach_kernel : _panic + 0x54
0xffffffa0ad69b900 : 0xffffff801c5e16a6 mach_kernel : _sync_iss_to_iks + 0x2c6
0xffffffa0ad69ba80 : 0xffffff801c5e138d mach_kernel : _kernel_trap + 0x60d
0xffffffa0ad69bad0 : 0xffffff801c457b2f mach_kernel : _return_from_trap + 0xff
0xffffffa0ad69baf0 : 0xffffff7f9fbe841d com.apple.driver.AppleSmartBatteryManager : __ZN17AppleSmartBattery17modifyChargeStateEbh + 0x59
0xffffffa0ad69bc10 : 0xffffff7f9fbe882d com.apple.driver.AppleSmartBatteryManager : __ZN17AppleSmartBattery18setPropertiesGatedEP8OSObjectP12OSDictionary + 0x131
0xffffffa0ad69bc90 : 0xffffff801cc0830e mach_kernel : __ZN10IOWorkLoop9runActionEPFiP8OSObjectPvS2_S2_S2_ES1_S2_S2_S2_S2_ + 0x3e
0xffffffa0ad69bcd0 : 0xffffff7f9fbe93cc com.apple.driver.AppleSmartBatteryManager : __ZN17AppleSmartBattery13setPropertiesEP8OSObject + 0x1d2
0xffffffa0ad69bd10 : 0xffffff801cc3dfdd mach_kernel : _is_io_registry_entry_set_properties + 0x15d
0xffffffa0ad69bd60 : 0xffffff801c59a8fa mach_kernel : _iokit_server_routine + 0x1eca
0xffffffa0ad69bd90 : 0xffffff801c4b7ef7 mach_kernel : _ipc_kobject_server + 0x337
0xffffffa0ad69be00 : 0xffffff801c48e691 mach_kernel : _ipc_kmsg_send + 0x111
0xffffffa0ad69be60 : 0xffffff801c4a56f5 mach_kernel : _mach_msg_overwrite_trap + 0x2e5
0xffffffa0ad69bef0 : 0xffffff801c5c62c3 mach_kernel : _mach_call_munger64 + 0x273
0xffffffa0ad69bfa0 : 0xffffff801c458316 mach_kernel : _hndl_mach_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.driver.AppleSmartBatteryManager(161.0)[3221CA90-1FB2-335C-B1C1-2375D894622A]@0xffffff7f9fbe6000->0xffffff7f9fc03fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[593AE8E6-8DF6-3911-B2C3-6A30430ED6A7]@0xffffff7f9cf1f000->0xffffff7f9cf2bfff
            dependency: com.apple.iokit.IOSMBusFamily(1.1)[E5FC11EC-45B0-36DD-8115-4FE83BE482DF]@0xffffff7f9d92f000->0xffffff7f9d938fff
            dependency: com.apple.driver.AppleSMC(3.1.9)[E9607AD0-3F90-3D94-8D29-ED63EEF0327D]@0xffffff7f9cfdc000->0xffffff7f9cffcfff

Process name corresponding to current thread: PowerUIAgent
Boot args: keepsyms=1 debug=0x100 -v

Mac OS version:
20A4299v

Kernel version:
Darwin Kernel Version 20.0.0: Sat Jun 13 17:58:16 PDT 2020; root:xnu-7090.0.0.111.5~1/RELEASE_X86_64
Kernel UUID: 8A20D5DC-6ED7-31BE-8E81-A5ADCBC358D7
Kernel slide:      0x000000001c200000
Kernel text base:  0xffffff801c400000
__HIB  text base: 0xffffff801c300000
System model name: MacBookPro15,1 (Mac-937A206F2EE63C01)
System shutdown begun: NO
Panic diags file available: NO (0xe00002bc)

System uptime in nanoseconds: 22862683936
``` 

I can't get VirtualSMC logs since I couldn't boot into the system with it, if there's anyway I could get the logs, please let me know.

Thanks in advance.

**Comment by vit9696** [comment]
Please upload AppleSmartBatteryManager.kext.

**Comment by CoronaHack** [comment]
[AppleSmartBatteryManager.kext-19F2200.zip](https://github.com/acidanthera/bugtracker/files/4839966/AppleSmartBatteryManager.kext-19F2200.zip)
[AppleSmartBatteryManager.kext-20A4299v.zip](https://github.com/acidanthera/bugtracker/files/4839967/AppleSmartBatteryManager.kext-20A4299v.zip)

**Comment by Andrey1970AppleLife** [comment]
I have no panic with SMCBatteryManager from the master, but information about battery doesn't show in Big Sur.

**Comment by vit9696** [comment]
`__ZN17AppleSmartBattery17modifyChargeStateEbh + 0x59` attempts to call `AppleSMCFamily` method to read `CH0B` key, but it cannot do that, because AppleSMC is not yet loaded. The call to read state comes from userspace, so that's pretty much a bug (race condition) in AppleSmartBattery source code.

**Comment by CoronaHack** [comment]
I randomly get this panic (actually very rare) so I certainly agree with your explanation, I hope Apple will figure out this issue soon, thanks.

SMCBatteryManager also fails to handle battery percentages even it's loaded, but that's a separate issue.

**Comment by vit9696** [comment]
Better keep it open, because if Apple does not we might have to think of some workaround.

**Comment by rektimus** [comment]
do you mind if I ask what's the fundamental difference between SMCBatteryManager and ACPIBatteryManager as I'm using RehabMan's as a temporary solution and it works

**Comment by vit9696** [comment]
The fundamental difference is that we emulate the original Apple SmartBattery, and let macOS implement power management on its own assuming that it works with SmartBattery. This provides better compatibility, but is prone to implementation errors in Apple stack if they exist.

**Comment by Mateo1234454545** [comment]
We now can boot/install Big Sur. 
The only thing that doesn't work is smcbatterymanager kext , which is not loaded.
Hope omeone solve this issue soon.

**Comment by Sher1ocks** [comment]
in big sur beta2
there is this log

2020-07-08 19:56:19.948000+0900  localhost kernel[0]: (AppleSmartBatteryManager) <AppleSmartBatteryManager`AppleSmartBattery::incompleteReadTimeOut()> Failed to complete polling of all data within 10000 ms
2020-07-08 19:56:19.948004+0900  localhost kernel[0]: (AppleSmartBatteryManager) <AppleSmartBatteryManager`AppleSmartBattery::handlePollingFinishedGated(bool, unsigned short)> SmartBattery: abort polling
2020-07-08 19:56:19.948007+0900  localhost kernel[0]: (AppleSmartBatteryManager) <AppleSmartBatteryManager`AppleSmartBattery::pollBatteryState(int)> Starting poll type 1
2020-07-08 19:56:19.948008+0900  localhost kernel[0]: (AppleSmartBatteryManager) <AppleSmartBatteryManager`AppleSmartBattery::transactionCompletionGated(transactionCompletionGatedArgs*)> Restarting poll type 1
2020-07-08 19:56:19.948033+0900  localhost kernel[0]: (AppleSmartBatteryManager) <AppleSmartBatteryManager`AppleSmartBattery::copySMCAdapterInfo(unsigned char)> Failed to read nominal voltage rating key     . voltage:0 rc:0x84
2020-07-08 19:56:19.948050+0900  localhost kernel[0]: (AppleSmartBatteryManager) <AppleSmartBatteryManager`AppleSmartBattery::handlePollingFinishedGated(bool, unsigned short)> SmartBattery: finished polling type 1

**Comment by ameenjuz** [comment]
i have same issue SMCBatteryManager.kext do not work and do not show battery status

**Comment by Mateo1234454545** [comment]
Could someone build and upload latest branche :https://github.com/acidanthera/VirtualSMC/tree/smcbat_bigsur_adaptation , to check if it works under Big Sur ?

**Comment by Ab2774** [comment]
I've tried both branches and I can confirm you that smcbat_bigsur_adaptation branch works for both Catalina and Big Sur, but I had a bit of latency while booting unlike the master branch VirtualSMC

**Comment by Mateo1234454545** [comment]
> I've tried both branches and I can confirm you that smcbat_bigsur_adaptation branch works for both Catalina and Big Sur, but I had a bit of latency while booting unlike the master branch of VirtualSMC

Could you upload the  smcbat_bigsur_adaptation branch. I cannot built it.

**Comment by vit9696** [comment]
We added workarounds for SMCBatteryManager. On both this issue and the other issue.
