### ISSUE TITLE
WEG not loading properly on macOS 10.16, stalls right after verbose ends

### ISSUE THREAD

**Issue by brian105** [acidanthera/bugtracker#1007]
Hello, I have an issue with WhateverGreen.kext in 10.16. The issue comes up right after verbose ends, where the Apple logo appears with a progress bar. The progress bar never changes and stays empty. When I try booting with -igfxvesa, I get the same issue, but it does not go to the Apple logo (just stalls right after verbose finishes). I am using the boot arguments -lilubetaall and -wegbeta to make Lilu and WhateverGreen load on 10.16, otherwise I get a panic related to the HD 5000 framebuffer kext.

My hardware: HP Envy x360, i7-4510U, HD 4400 iGPU, 8GB RAM, using an external hard drive to boot 10.16 (I verified that the install is good by booting it in a virtual machine with no problems).

I have attached my EFI folder, the Lilu logs with -liludbgall, and OC logs.

[Lilu_1.4.5_20.0.txt](https://github.com/acidanthera/bugtracker/files/4838748/Lilu_1.4.5_20.0.txt)
[OC.zip](https://github.com/acidanthera/bugtracker/files/4838767/OC.zip)
[opencore-2020-06-26-175607.txt](https://github.com/acidanthera/bugtracker/files/4838817/opencore-2020-06-26-175607.txt)

**Comment by Andrey1970AppleLife** [comment]
Add necessary variables NVRAM for 10.16 according to https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Errata/Errata.pdf
Installed system start only. Installation isn't possible.
Use forums for support.

**Comment by vit9696** [comment]
You have outdated Lilu as seen by the garbage in your log:

```
Lilu   patcher: @ (DBG) last kext is 0xC83911A797A3E227 and its name is 
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) last kext is 0x0000000000000000 and its name is ‚
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) last kext is 0x000000006C6F7274 and its name is 
```
