### ISSUE TITLE
Lilu does not seem to execute "onPatcherLoadForce" on certain Macs

### ISSUE THREAD

**Issue by alphanull** [acidanthera/bugtracker#1008]
So I tried to get the Innie plugin to run on my MP7,1 in order to make my NVME drive seen as internal. However while both Lilu and Innie are loaded, nothing happened. I then dug into the Innie sources and discovered that apparently the main function `internalizeDevices` does not seem to be called from the `onPatcherLoadForce` callback. I had added more debug messaged to this code to confirm:

    void INNIE::init() {
        DBGLOG("innie", "Init");
        lilu.onPatcherLoadForce([](void *user, KernelPatcher &patcher) {
            DBGLOG("innie", "onPatcherLoadForce");
            static_cast<INNIE *>(user)->internalizeDevices();
        }, this);
    }

So in my logs, I can see the `init` Message, but the `onPatcherLoadForce` message is **not** displayed. Next, I checked if the actual code would be running by just calling `internalizeDevices` **directly** (by renaming it to `init` and remove the original function) instead of using the callback. And well, then it worked (kinda, still no dice with SIP enabled and apparently this patch does not work not for everyone).

So, it **looks** like the problem is not with Innie itself, but rather with Lilu, i.e. not executing this callback. What makes this even more strange is that apparently not all MP7,1s are affected, but maybe only some special configurations. And this issue is also not tied to the MP alone: on my old Hackintosh (running 10.13.6) it just works without those modifications, but I get exactly the same symptoms on my MBP 16" (also running 10.15.5 like my MP 7,1).

**Comment by vit9696** [comment]
Could you provide us a log by adding `liludump=60 -liludbgall` to boot arguments and then uploading a log file from `/var/log/Lilu_x.x.x.txt`. This file will be created 60 seconds after booting. You will need DEBUG versions of all the Lilu-related kexts.

**Comment by alphanull** [comment]
Yeah, I already did this before, basically when using this method I get the same results compared to what I get when using `log show`:

    Lilu    config: @ (DBG) version DBG-145-2020-06-01, args: disabled 0, debug 1, slow 0, decompress 1
    Lilu       dev: @ (DBG) detected 1 firmware
    Lilu       dev: @ (DBG) got MacPro7,1 model from /efi/platform
    Lilu       dev: @ (DBG) got Mac-27AD2F918AE68F61 board-id from /efi/platform
    Lilu    config: @ (DBG) initialising policy
    Lilu    policy: @ (DBG) init bsd
    Lilu       api: @ (DBG) got load request from Innie (121)
    Innie      init: @ (DBG) Innie bootstrap DBG-121-2020-06-27
    Innie     innie: @ (DBG) Init

So it just stops at `Init` instead of continuing with `onPatcherLoadForce` (see my code snippet above)

**Comment by vit9696** [comment]
The reason for that is secure boot. On Macs with T2 you cannot install kernel extensions to `/Library/Extensions` and let them load before late kernel initialisation due to the way Apple designed secure boot loading. Basically Lilu starts after all the drivers have already loaded and cannot do any patches.

I think that even if you disable secure boot it may still fail to work, but that needs checking. Also, starting with macOS 11 installing Lilu into /Library/Extensions is not possible for any machine, including the older ones, as the T2 behaviour is now enforced in all machines due to the way new KEXT loading is designed.

Your best choice will be to use OpenCore and inject Lilu and the plugins through the bootloader.

**Comment by alphanull** [comment]
Well, that sounds like bad news. But actually, you can still get Innie to load if you execute it's main function directly, and you still can patch the ioRegistry. All you have to do is disable SIP for kext signing. (i.e. `csrutil enable --without kext`).

But will OpenCore actually work on a MP7,1?

**Comment by vit9696** [comment]
Yes, but for "real" Lilu plugins, i.e. those that actually rely on patching, this will unfortunately not work. I expect OpenCore to work just fine on MP7,1 as it is a pretty normal UEFI-compatible machine. After all OpenCore basically does nothing unless you ask.

**Comment by alphanull** [comment]
OK, so I will see how this plays out in the future and use my patched version as a workaround. One last thing: why does Innie then work one _some_ 7,1 (but not mine)? I mean all of them must run Cataline already, so are there different revisions of the T2 chip?

**Comment by vit9696** [comment]
I *think* it may be because of disabled secure-boot and/or specialised CSR settings. If you force your MP to use prelinkedkernel instead of immutablekernel it will work just like a mac without T2.

**Comment by alphanull** [comment]
Yeah, I already tried disabling secure boot, but it does not change anything. What only seems to be effective is disabling SIP (at least the kext part), maybe this is also interfering with the T2? I heard the T2 will also check the kernel, not only the boot drive. And how would I force the MP to load the prelinked kernel, other than with disabling SIP?

Pretty interesting how all this works. Coming from hackintosh, and now I beginn hacking my MP ;)

**Comment by alphanull** [comment]
And I have an idea: so you say: "Basically Lilu starts after all the drivers have already loaded and cannot do any patches."

The point with Innie ist that - despite only modifying ioreg - it needs to be executed late, or it does not work on older machines. What you said would explain why it still works on mine, because it is also executed late, but not due to the `onPatcherLoadForce` callback, but actually due to secure boot!

Now, would it make sense if Lilu would also execute `onPatcherLoadForce` even on T2 macs? By this way, at least plugins using this hook - but not doing actual kernel patches - would still be able to run.

**Comment by vit9696** [comment]
I would say it is better for Innie to be rewritten so that it will use I/O Kit startup rather than `onPatcherLoadForce` callback, which is meant to be used for patches, which Innie does not need.

**Comment by alphanull** [comment]
OK, thanks!
