### ISSUE TITLE
WEG's enable-dpcd-max-link-rate-fix doesn't work properly in macOS 10.16

### ISSUE THREAD

**Issue by WildBeastRouen** [acidanthera/bugtracker#1009]
My laptop is Dell XPS 15 7590 which needs enable-dpcd-max-link-rate-fix to brighten up internal 4k screen, and it works perfectly in 10.15.5.

However, after updated to macOS 10.16 with latest OpenCore, Lilu, Whatevergreen and VirtualSMC master, the screen went black after Apple logo.

Now it can only change AAPL,ig-platform-id to 0x12345678 (eFY0Eg==) to brighten up the screen.

I've tried to add -disablegfxfirmware and also add NVRAM variables "booter-fileset-kernel" with data 00 but doesn't help.

How could I solve this problem?

Thanks!

**Comment by vandroiy2013** [comment]
No logs? Closed.

**Comment by WildBeastRouen** [comment]
> No logs? Closed.

Sorry, here's the boot log with valid platform-id (00009B3E):

[boot log.docx](https://github.com/acidanthera/bugtracker/files/4840847/boot.log.docx)

**Comment by kommtzeitkonrad** [comment]
> [boot log.docx](https://github.com/acidanthera/bugtracker/files/4840847/boot.log.docx)

http://www.goldmark.org/netrants/no-word/attach.html

**Comment by Andrey1970AppleLife** [comment]
CC @FireWolf

**Comment by Andrey1970AppleLife** [comment]
CC @0xFireWolf

**Comment by 0xFireWolf** [comment]
It seems that you are using a RELEASE version of WhateverGreen, so I am not able to find WEG’s log. However, based on your kernel log, the maximum link rate is fixed, so the patch is still working properly.

```
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] DPCD DUMP: Fb=0
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  14 14 C4 C1
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  0 0 1 C0
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  2 0 0 0
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  0 B 0 0
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0: OUI for display
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  38 EC 11 0
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  0 0 0 0
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0: Display port config ver is 1.4
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0 Maximum link rate is 0x14
kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0: Maximum lanes is 4
```

Besides, if the patch is not working, your machine will theoretically have a kernel panic due to a division-by-zero instead of a black screen. As such, my intuition is that your issue is unlikely related to this patch, and you might want to check other patched you have enabled.

Please note that since a fresh installation of macOS Big Sur is not supported by both bootloaders at this moment, I don’t have the test environment available on my laptop, so I cannot prove my hypothesis.

**Comment by WildBeastRouen** [comment]
> It seems that you are using a RELEASE version of WhateverGreen, so I am not able to find WEG’s log. However, based on your kernel log, the maximum link rate is fixed, so the patch is still working properly.
> 
> ```
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] DPCD DUMP: Fb=0
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  14 14 C4 C1
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  0 0 1 C0
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  2 0 0 0
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  0 B 0 0
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0: OUI for display
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  38 EC 11 0
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  0 0 0 0
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0: Display port config ver is 1.4
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0 Maximum link rate is 0x14
> kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0: Maximum lanes is 4
> ```
> 
> Besides, if the patch is not working, your machine will theoretically have a kernel panic due to a division-by-zero instead of a black screen. As such, my intuition is that your issue is unlikely related to this patch, and you might want to check other patched you have enabled.
> 
> Please note that since a fresh installation of macOS Big Sur is not supported by both bootloaders at this moment, I don’t have the test environment available on my laptop, so I cannot prove my hypothesis.

I've changed Lilu, WhateverGreen and VirtualSMC to DEBUG version with latest master, this time it stucked at verbose.

Here's the boot log with WhateverGreen log :
[boot log.txt](https://github.com/acidanthera/bugtracker/files/4841823/boot.log.txt)

**Comment by 0xFireWolf** [comment]
> > It seems that you are using a RELEASE version of WhateverGreen, so I am not able to find WEG’s log. However, based on your kernel log, the maximum link rate is fixed, so the patch is still working properly.
> > ```
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] DPCD DUMP: Fb=0
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  14 14 C4 C1
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  0 0 1 C0
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  2 0 0 0
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  0 B 0 0
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0: OUI for display
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  38 EC 11 0
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info]  0 0 0 0
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0: Display port config ver is 1.4
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0 Maximum link rate is 0x14
> > kernel: (AppleIntelCFLGraphicsFramebuffer) [IGFB][INFO   ] [DPCD_Info] FB0: Maximum lanes is 4
> > ```
> > 
> > 
> > Besides, if the patch is not working, your machine will theoretically have a kernel panic due to a division-by-zero instead of a black screen. As such, my intuition is that your issue is unlikely related to this patch, and you might want to check other patched you have enabled.
> > Please note that since a fresh installation of macOS Big Sur is not supported by both bootloaders at this moment, I don’t have the test environment available on my laptop, so I cannot prove my hypothesis.
> 
> I've changed Lilu, WhateverGreen and VirtualSMC to DEBUG version with latest master, this time it stucked at verbose.
> 
> Here's the boot log with WhateverGreen log :
> [boot log.txt](https://github.com/acidanthera/bugtracker/files/4841823/boot.log.txt)

Your boot log has shown that the maximum link rate fix is working properly. As such, your issue is not related to this fix.

Case closed.

**Comment by WildBeastRouen** [comment]
@0xFireWolf 

The problem might not caused by dpcd-max-link-rate, but there're some user reported that theirs laptop stucked at verbose of IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0 (same as me).
The devices they are using :
Dell XPS 15 9560
Dell XPS 15 9570
Dell XPS 15 7590
Lenovo Thinkpad P52
Lenovo Legion y9000x
Lenovo Thinkpad X1 Extreme 1st Gen

All of these devices have 4k internal screen, if OC or Clover can build the macOS 11 environment, please help us to solve this problem.

Thanks!

**Comment by gnodipac886** [comment]
@WildBeastRouen any updates on this?
