### ISSUE TITLE
OpenCanopy looking for 512px image in custom .VolumeIcon.icns when UIScale set to 02

### ISSUE THREAD

**Issue by blackosx** [acidanthera/bugtracker#1011]
Hi

Testing with PickerAttributes set to 1, UIScale set to 02 and .icns file containing two images of type ic07 and ic13.

OpenCanopy finds .VolumeIcon.icns but it's not drawn because log shows it's expecting 512x512 pixel image. OpenCanopy then reverts to the default image from /EFI/OC/Resources/Image/ which loads correctly at 256x256 pixels.

00:760 00:000 OCUI: Console attributes: 0
00:760 00:000 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
00:761 00:000 OCB: Trying to get image from .VolumeIcon.icns
00:762 00:001 OCB: Get normal icon Mojave - Success
00:764 00:002 OCUI: Expected 512x512, actual 256x256, allow less: 0
00:765 00:000 OCUI: Failed to convert icon - Unsupported

The  .VolumeIcon.icns work fine when using UIScale set to 01.

I'm attaching latest debug log and a sample icon that I'm using.
[OpenCore_Data_Hub_Log.txt](https://github.com/acidanthera/bugtracker/files/4842522/OpenCore_Data_Hub_Log.txt)
[VolumeIcon.icns.zip](https://github.com/acidanthera/bugtracker/files/4842531/VolumeIcon.icns.zip)

**Comment by Andrey1970AppleLife** [comment]
For UIScale 01 original VolumeIcon.icns doesn't contain the image 128x128 in a suitable format, OC does re-scale 256x256 to 128x128.
In yours cases for UIScale 02 try add image 512x512 In your custom VolumeIcon.icns

**Comment by vit9696** [comment]
@Andrey1970AppleLife, no, this is just a bug. The dimensions are 128x128 for 1.x and 256x256 for 2.x Fixed in master, thanks.

**Comment by markl17** [comment]
I get this I don't know why it gets stuckandrey suggests that I add a image file can you explain
 Registering entry Reset NVRAM (T:256|F:0|G:0|E:0) - <nil>
61:285 00:525 OCB: Showing menu... 
61:375 00:090 OCUI: Console attributes: 112
61:517 00:142 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
61:579 00:061 OCUI: Console attributes: 112
61:644 00:065 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
61:706 00:061 OCUI: Console attributes: 112
61:767 00:061 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
61:831 00:063 OCUI: Console attributes: 112
61:893 00:061 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
61:954 00:061 OCUI: Console attributes: 112
62:017 00:063 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
62:078 00:061 OCUI: Console attributes: 112
62:139 00:061 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
62:224 00:084 OCUI: Console attributes: 112
62:288 00:064 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
62:349 00:061 OCUI: Console attributes: 112
62:411 00:061 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
62:473 00:062 OCUI: Console attributes: 112
62:535 00:061 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
62:596 00:061 OCUI: Console attributes: 112
62:657 00:061 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
