### ISSUE TITLE
Mac boot chime only works after NVRAM reset.

### ISSUE THREAD

**Issue by mrgooge** [acidanthera/bugtracker#1012]
Boot chime issue ? Opencore DEBUG 0.6.0

 If I reset NVRAM, my Boot Chime works (chimes).

After I reboot and until I reset NVRAM, Boot Chime does not work (no chime).

 My DEBUG log shows this after NVRAM reset:

**07:832 00:004 OCAU: System volume is 98 (calculated from 70) - Success**
07:836 00:003 OCAU: Matching PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000)...
07:840 00:004 OCAU: 1/3 PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x1)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (6 outputs) - Success
07:844 00:003 OCAU: 2/3 PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (5 outputs) - Success
07:848 00:004 OCAU: Setting language to en-US:0
07:852 00:003 OCAU: Language for audio en-US:0 - Success
07:856 00:003 OC: Starting to play chime...
07:860 00:004 OC: Wave Resources\Audio\OCEFIAudio_VoiceOver_Boot.wav was requested
07:867 00:006 OCAU: File 59 for lang 7 is 32 2 2 (440576) - Success

On the next reboot (and and reboot until NVRAM reset) My DEBUG log shows this:

**07:807 00:007 OCAU: System volume is 0 (calculated from 0) - Success**
07:814 00:007 OCAU: Matching PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000)...
07:818 00:004 OCAU: 1/3 PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x1)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (6 outputs) - Success
07:822 00:004 OCAU: 2/3 PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (5 outputs) - Success
07:827 00:004 OCAU: Setting language to en:0
07:831 00:004 OCAU: Language for audio en:0 - Success

**Comment by icedterminal** [comment]
Are you using native or emulated NVRAM? By default, OC sample configs and the dortania guide have users use native. If using native, you should try using emulated after an NVRAM reset. See if the problem persists.

My experience with this feature was the same as yours until I switched to emulated. Native NVRAM for my board was not without issue.

**Comment by mrgooge** [comment]
Using native NVRAM. I set up emulated per the Dortania guides, and the boot chime persists using emulated or native. After NVRAM reset it chimes, after any reboot no chime. Same thing in the OC DEBUG log, "System volume is 0" after reboot.. I using a z370 series logic board btw.

**Comment by vit9696** [comment]
According to your log it is your operating system that sets the value of `SystemAudioVolume` variable to 0, which results in disabled boot chime. Works as designed (the way it does on Macs) in my opinion, do not mute the volume in your operating system, and it will work fine. Let me know if there is any detail I missed.

**Comment by mrgooge** [comment]
Yes, then something is broken with my operating system after restarting. I understand the volume for boot chime is set while booted, and yes, I made sure it was not muted before rebooting. I guess something is corrupt and  muting it after a restart... If you have any idea where I could look, I'd appreciate it. Thank you for your time!

**Comment by vit9696** [comment]
Well, you can use `nvram -x SystemAudioVolume | grep -vE '[<>]' | base64 --decode | xxd -i` command to inspect the saved NVRAM volume level. Otherwise I do not know. Do you use AppleHDA or VoodooHDA? This might matter.

**Comment by mrgooge** [comment]
Using AppleHDA.
nvram -x SystemAudioVolume | grep -vE '[<>]' | base64 --decode | xxd -i
  **0x46**

**Comment by vit9696** [comment]
What about next reboot?

**Comment by mrgooge** [comment]
I get the same as above when there's no chime, the only place I see System volume is 0 is the OC DEBUG log...
I used the same EFI and booted to my clone drive after a NVRAM reset, chime good, rebooted again to clone drive chime good again...
So something corrupts or makes OC think the System volume is 0 , only when rebooting on my main disk.

Not to get to far off the path, but is it possible the proboot partition could be corrupt and have this effect...?

If needed, I can send you a full Before and After OC DEBUG logs if you'd like?
I don't want to bug you too much about this...
Thanks again.

**Comment by vit9696** [comment]
That *something* can only be your NVRAM. Could you provide full OpenCore log and config.plist? I am worried if you might be overriding your SystemAudioVolume variable with some scripts or alike. Is that an old device? Might it have NVRAM issues?

**Comment by mrgooge** [comment]
Not too old, 2018 hardware. OS X Catalina 10.15.5. Attaching logs and config.plist. Thanks.
[request_files.zip](https://github.com/acidanthera/bugtracker/files/4847121/request_files.zip)

**Comment by vit9696** [comment]
You have `SystemAudioVolume` set  in config.plist. I believe it might confuse macOS. Try removing it.

**Comment by mrgooge** [comment]
I removed SystemAudioVolume set, still the same issue persists, no boot chime after reboot, only boot chime after NVRAM reset.

I did notice a new message pop up on boot, I don't know if it has anything to do with this: 
" _NVRAM log size exceeded, cannot log!_ "

I also enabled bootstrap, it made no difference.

Thanks again.

**Comment by vit9696** [comment]
Oh, lol. You are using NVRAM logging. Please disable it in Target. E.g. replace 81 with 65.

**Comment by mrgooge** [comment]
Set it at 65, that fixed the log size errors...

But, still no chime after reboot. 

Still _**something**_ is there.

**Comment by vit9696** [comment]
Did you reset NVRAM and then boot to macOS afterwards? Also, could you provide the log after this change?

**Comment by mrgooge** [comment]
Yes. 

Attached is the log from last boot:
[new_resuest_files.zip](https://github.com/acidanthera/bugtracker/files/4848197/new_resuest_files.zip)

**Comment by vit9696** [comment]
Please post current NVRAM variables by executing `dmpstore -all > file.txt` in UEFI Shell and attaching the file here.

**Comment by mrgooge** [comment]
ok, here you go:
[file.txt.zip](https://github.com/acidanthera/bugtracker/files/4848294/file.txt.zip)

**Comment by vit9696** [comment]
```
Variable NV+RT+BS '7C436110-AB2A-4BBB-A880-FE41995C9F82:SystemAudioVolume' DataSize = 0x01
  00000000: 80                                               *.*
Variable NV+RT+BS '7C436110-AB2A-4BBB-A880-FE41995C9F82:SystemAudioVolumeSaved' DataSize = 0x01
  00000000: 46                                               *F*
Variable NV+RT+BS '7C436110-AB2A-4BBB-A880-FE41995C9F82:SystemAudioVolumeDB' DataSize = 0x01
  00000000: 00 
```

Your macOS version intentionally disables the volume in UEFI. 80 value is muted, and 46 value in Saved says restore this value after booting the operating system. You may have set some setting in the operating system to disable bootchime or have some tool. Please retry with the clean macOS installation.

**Comment by mrgooge** [comment]
So I think I've tested the same scenario as a clean installation: 

When booting using this EFI, then select my external Clone drive, or a different internal Mac volume SSD drive. The boot chime works after reset NVRAM and works after reboots (chime plays). 

I got that, do you have any idea /how/who/what/why/where that _some setting_ in my current OS would be, that can disable the bootchime and make those parameters in my NVRAM?  does that make sense..?!?

**Comment by mrgooge** [comment]
I mean what else can set value 80 in my UEFI?

**Comment by vit9696** [comment]
Well, I am not sure, but Apple disabled this on newer Macs at the very least. See: https://www.macrumors.com/how-to/enable-classic-startup-chime-on-newer-macs/. In Big Sur you can also configure that in preferences: https://www.macrumors.com/2020/06/23/macos-big-sur-brings-back-startup-chime/.

**Comment by mrgooge** [comment]
Yes, thanks for that information. I appreciate your help with this. I re-installed Catalina using the Recovery partition, and that made no change with the boot chime. I don't want to deal with a clean install as I have over 900GB's of data to push around...

One last question, can you explain actually where the NVRAM variables are stored on my system? 

Thanks.

**Comment by vit9696** [comment]
The NVRAM variables are stored in your BIOS flash memory. You can use `Delete` interface in OpenCore configuration override `SystemAudioVolume` variable. Like I said, you could try the algorithm to enable boot chime used in macs as shown above. But otherwise, yes, it is more like your operating system, and reinstalling the same operating system will obviously not help.

**Comment by mrgooge** [comment]
Final rambling... I restored my drive from a clone backup from 6/19. The bootchime plays after a NVRAM reset and any subsequent reboot, so the chime is working normally now!

I may never know what I did to break the bootchime in my NVRAM, But, I hope I never do it again...

Thanks for your time, keep up the great work on Opencore and all of your software!

**Comment by antonioclb** [comment]
Hello to everybody! Just a further comment to consolidate this issue in order to mark it as [SOLVED].
Today I was just dealing with this issue on my HP Z620 Hackintosh (MacPro7,1 system model, Catalina 10.15.7, OpenCore 0.6.2).
After following Dortania's guide, the same behaviour as mrgooge's first post happened to me (boot chime only first time after NVRAM reset).
Digging into OC bootlog, I've found the following line:

00:610 00:021 OC: Setting NVRAM 7C436110-AB2A-4BBB-A880-FE41995C9F82:SystemAudioVolume - ignored, exists

The only thing I needed to do was adding a key in the "delete" section for this NVRAM variable in order to delete the macOS zero volume setting and force the 0x46 value entered in the "add" section.

Boot chime is now loudly played from my internal speaker (AudioOut 1) on every boot!

Have fun!
AC

**Comment by burrows1980** [comment]
> Hello to everybody! Just a further comment to consolidate this issue in order to mark it as [SOLVED].
> Today I was just dealing with this issue on my HP Z620 Hackintosh (MacPro7,1 system model, Catalina 10.15.7, OpenCore 0.6.2).
> After following Dortania's guide, the same behaviour as mrgooge's first post happened to me (boot chime only first time after NVRAM reset).
> Digging into OC bootlog, I've found the following line:
> 
> 00:610 00:021 OC: Setting NVRAM 7C436110-AB2A-4BBB-A880-FE41995C9F82:SystemAudioVolume - ignored, exists
> 
> The only thing I needed to do was adding a key in the "delete" section for this NVRAM variable in order to delete the macOS zero volume setting and force the 0x46 value entered in the "add" section.
> 
> Boot chime is now loudly played from my internal speaker (AudioOut 1) on every boot!
> 
> Thanks for your awesome work on OpenCore folks! Have fun!
> AC

Ace this worked for me! Thank you

**Comment by liaojack8** [comment]
> Hello to everybody! Just a further comment to consolidate this issue in order to mark it as [SOLVED].
> Today I was just dealing with this issue on my HP Z620 Hackintosh (MacPro7,1 system model, Catalina 10.15.7, OpenCore 0.6.2).
> After following Dortania's guide, the same behaviour as mrgooge's first post happened to me (boot chime only first time after NVRAM reset).
> Digging into OC bootlog, I've found the following line:
> 
> 00:610 00:021 OC: Setting NVRAM 7C436110-AB2A-4BBB-A880-FE41995C9F82:SystemAudioVolume - ignored, exists
> 
> The only thing I needed to do was adding a key in the "delete" section for this NVRAM variable in order to delete the macOS zero volume setting and force the 0x46 value entered in the "add" section.
> 
> Boot chime is now loudly played from my internal speaker (AudioOut 1) on every boot!
> 
> Thanks for your awesome work on OpenCore folks! Have fun!
> AC

Awesome! this way worked for me too.

**Comment by sandaruwan786** [comment]
Thanks man!!! worked for me too, you saved my day…

**Comment by freetextmike** [comment]
What exactly did you add in the NVRAM->delete->7C436110-AB2A-4BBB-A880-FE41995C9F82?

cause i tried NVRAM->delete->7C436110-AB2A-4BBB-A880-FE41995C9F82->SystemAudioVolume=0 but it is not working 
`
SystemAudioVolume` is Data variable

**Comment by antonioclb** [comment]
> Ok so adding `7C436110-AB2A-4BBB-A880-FE41995C9F82` as `Array` inside the Delete variable and adding a child named `0` which data type is `string` with a value of `SystemAudioVolume` did the job
> 
> sorry im just hacking like 1 week hope this help for the other people

Awesome! Thanks for the clarification!

Best regards.
AC

**Comment by Human7900** [comment]
Can anybody share a screenshot of the changes?
Thanks.

**Comment by mikebeaton** [comment]
Look at how NVRAM Add and Delete is done correctly by looking in https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Sample.plist

**Comment by Human7900** [comment]
Thank you @mikebeaton! I figured it out!

**Comment by adrianyujs** [comment]
![image](https://github.com/user-attachments/assets/79de58a2-bf73-4b54-836e-bf7c1d2c2b67)

Is this correct? Seems doesn't work.
