### ISSUE TITLE
A solution for issues 920,gen different OpenCore.efi use different config file

### ISSUE THREAD

**Issue by laozhiang** [acidanthera/bugtracker#1014]
https://github.com/acidanthera/bugtracker/issues/920
this issue is locked. I give a solution for this question
SomeBody want different OpenCore in different Directory. 
I give a script gen  different OpenCore all in OC directory.each opencore_macosX.efi use different config file
OpenCore_macos1.efi   ---->   macos1.plist
OpenCore_macos2.efi   ---->   macos2.plist
OpenCore_macos3.efi   ---->   macos3.plist
OpenCore_macos4.efi   ---->   macos4.plist
OpenCore_macos5.efi   ---->   macos5.plist
OpenCore_macos6.efi   ---->   macos6.plist
OpenCore_macos7.efi   ---->   macos7.plist
OpenCore_macos8.efi   ---->   macos8.plist
OpenCore_macos9.efi   ---->   macos9.plist
[multiOpenCore.command.zip](https://github.com/acidanthera/bugtracker/files/4846771/multiOpenCore.command.zip)

**Comment by Andrey1970AppleLife** [comment]
Unlocked, for not to create doubles, write there.
