### ISSUE TITLE
[VoodooPS2Trackpad] Touchpad Problem on HP EliteBook series. 

### ISSUE THREAD

**Issue by aleksyXI** [acidanthera/bugtracker#1015]
Keyboard and functional keys working, but touchpad physical keys doesn't work, and touchpad have very big sensitive.
In logs I can see, that EW mode disableed, buy enabling this mode in Info.plist make touchpad not working.
[debug_16162.zip](https://github.com/acidanthera/bugtracker/files/4864244/debug_16162.zip)

**Comment by vit9696** [comment]
Duplicate of https://github.com/acidanthera/bugtracker/issues/890
