### ISSUE TITLE
FadtEnableReset Quirks does not Enable Reset on certain Firmware

### ISSUE THREAD

**Issue by MacNB** [acidanthera/bugtracker#1016]
I never typed that...github bug ???

I started typing a bug report and got called away. Came back to complete my entry I see that the issue is closed .
Uhhh ?

**Comment by asgmeonerandom** [comment]
cool story bro

**Comment by MacNB** [comment]
The **FadtEnableReset** Quirk does not enable the Reset Register in FADT table.

**Symptom**: 

Restart from macOS hangs after clearing the screen. Fans continue to run. Keyboard unresponsive. Only option is a long press of the Power Button to power down.

FadtEnableReset = True in config.plist.
OC Log shows:
`01:243 00:002 OCA: FADT reset got 244 need 129`

**Problem:**

In my FADT table, the FLAGS field has the bit EFI_ACPI_6_2_RESET_REG_SUP == 1 but the all Reset Register fields are EMPTY (e.g. Reset Register Address == 0).
That is a problem because the _OcAcpiLic.c_ function **AcpiFadtEnableReset** assumes that if EFI_ACPI_6_2_RESET_REG_SUP == 1 then there's no need to patch BUT does not check if the Reset Register Address == 0 (in which case, it should patch).

I'm not sure if this is a Bug in the ACPI firmware or whether the ACPI Spec does not specify if the Reset Register needs to be populated if the Reset Flag bit is set to 1.

Current code is:

} **else if** ((Context->Fadt->Flags & EFI_ACPI_6_2_RESET_REG_SUP) == 0
    || (Context->Fadt->Flags & EFI_ACPI_6_2_SLP_BUTTON) == 0
    || (Context->Fadt->Flags & EFI_ACPI_6_2_PWR_BUTTON) != 0) {
    Fadt = Context->Fadt;
  } **else** {
    **return** EFI_SUCCESS;
  }

So in my case it always executes _return EFI_SUCCESS_ without any patching (and thus the system never restarts). 

**Solution:**

Do not assume that if EFI_ACPI_6_2_RESET_REG_SUP == 1, then there's no need to patch but also check that the _ResetReg.Address_ is NOT Zero.

One **possible** solution change is:

} **else if** ((Context->Fadt->Flags & EFI_ACPI_6_2_RESET_REG_SUP) == 0
    || (Context->Fadt->ResetReg.Address) == 0      // MacNB: Also check Reset Register Address, not just the Reset Flag 
    || (Context->Fadt->Flags & EFI_ACPI_6_2_SLP_BUTTON) == 0
    || (Context->Fadt->Flags & EFI_ACPI_6_2_PWR_BUTTON) != 0) {
    Fadt = Context->Fadt;
  } **else** {
    **return** EFI_SUCCESS;
  }


I made the change locally on my build and tested the solution. Now my system fully Restarts correctly (as the patch is applied).

Also, in my FADT Table, EFI_ACPI_6_2_SLP_BUTTON == 1 and EFI_ACPI_6_2_PWR_BUTTON == 0.

See my attached FACP.dsl file (extracted via OC SysReport.

[FACP-1.dsl.zip](https://github.com/acidanthera/bugtracker/files/4865994/FACP-1.dsl.zip)

**Comment by asgmeonerandom** [comment]
recreate the issue because they closed it

**Comment by kommtzeitkonrad** [comment]
> recreate the issue because they closed it

The proper way is to comment on a closed issue and wait. If the [bug report is valid](https://github.com/acidanthera/bugtracker/blob/master/.github/ISSUE_TEMPLATE/bug-in-opencore-or-kext.md), the issue may get reopened. See [this one](https://github.com/acidanthera/bugtracker/issues/1006#issuecomment-650553813) for example.

**Comment by MacNB** [comment]
> > recreate the issue because they closed it
> 
> The proper way is to comment on a closed issue and wait. If the [bug report is valid](https://github.com/acidanthera/bugtracker/blob/master/.github/ISSUE_TEMPLATE/bug-in-opencore-or-kext.md), the issue may get reopened. See [this one](https://github.com/acidanthera/bugtracker/issues/1006#issuecomment-650553813) for example.

Thanks. For your info, the "issue" was a technical issue with GitHub I think. I clicked on the "new issue" and Github fills the input screen with generic message with warnings and tips, etc. I started to enter my comment before deleting that message but I got called away to attend an a small emergency. By the time I came back to my system, the issue was closed even though it was not even submitted. I submitted it anyway thinking that it was a Github glitch.
Not knowing what happened,  I re-submitted a new one.

**Comment by vit9696** [comment]
You need to delete the contents you see and write yours there. Be more careful next time. I will check your FADT table.

**Comment by vit9696** [comment]
Resolved as part of #1017
