### ISSUE TITLE
FadtEnableReset Quirk does not enable the Reset patch on certain firmware

### ISSUE THREAD

**Issue by MacNB** [acidanthera/bugtracker#1017]
The **FadtEnableReset** Quirk does not enable the Reset Register in FADT table.

**Symptom**: 

Restart from macOS hangs after clearing the screen. Fans continue to run. Keyboard unresponsive. Only option is a long press of the Power Button to power down.

FadtEnableReset = True in config.plist.
OC Log shows:
`01:243 00:002 OCA: FADT reset got 244 need 129`

**Problem:**

In my FADT table, the FLAGS field has the bit EFI_ACPI_6_2_RESET_REG_SUP == 1 but the all Reset Register fields are EMPTY (e.g. Reset Register Address == 0).
That is a problem because the _OcAcpiLic.c_ function **AcpiFadtEnableReset** assumes that if EFI_ACPI_6_2_RESET_REG_SUP == 1 then there's no need to patch BUT does not check if the Reset Register Address == 0 (in which case, it should patch).

I'm not sure if this is a Bug in the ACPI firmware or whether the ACPI Spec does not specify if the Reset Register needs to be populated if the Reset Flag bit is set to 1.

Current code is:

} **else if** ((Context->Fadt->Flags & EFI_ACPI_6_2_RESET_REG_SUP) == 0
    || (Context->Fadt->Flags & EFI_ACPI_6_2_SLP_BUTTON) == 0
    || (Context->Fadt->Flags & EFI_ACPI_6_2_PWR_BUTTON) != 0) {
    Fadt = Context->Fadt;
  } **else** {
    **return** EFI_SUCCESS;
  }

So in my case it always executes _return EFI_SUCCESS_ without any patching (and thus the system never restarts). 

**Solution:**

Do not assume that if EFI_ACPI_6_2_RESET_REG_SUP == 1, then there's no need to patch but also check that the _ResetReg.Address_ is NOT Zero.

One **possible** solution change is:

} **else if** ((Context->Fadt->Flags & EFI_ACPI_6_2_RESET_REG_SUP) == 0
    || (Context->Fadt->ResetReg.Address) == 0      // MacNB: Also check Reset Register Address, not just the Reset Flag 
    || (Context->Fadt->Flags & EFI_ACPI_6_2_SLP_BUTTON) == 0
    || (Context->Fadt->Flags & EFI_ACPI_6_2_PWR_BUTTON) != 0) {
    Fadt = Context->Fadt;
  } **else** {
    **return** EFI_SUCCESS;
  }

I made the change locally on my build and tested the solution. Now my system fully Restarts correctly (as the patch is applied).

Also, in my FADT Table, EFI_ACPI_6_2_SLP_BUTTON == 1 and EFI_ACPI_6_2_PWR_BUTTON == 0.

See my attached FACP.dsl file (extracted via OC SysReport.

[FACP-1.dsl.zip](https://github.com/acidanthera/bugtracker/files/4865994/FACP-1.dsl.zip)

**Comment by MacNB** [comment]
@vit9696 Many thanks.

**Comment by ashcliff** [comment]
This problem still happens for me. I went to 0.6.7. but it looks like the patch is not applied. Please, let me know how I can try the patched code

**Comment by vit9696** [comment]
Create a new issue, attaching:

1. SysReport with original tables
2. Patched tables from MaciASL from macOS
3. OpenCore DEBUG log

**Comment by andreszerocross** [comment]
Hi @vit9696, I have similar issues in Dell Optiplex AIO 7780 Cometlake.

Restart and Shutdown just hang, black screen and fan keep spinning.

FadtEnableReset = True in config.plist

And i got logs "08:285 00:008 OCA: FADT reset got 276 need 129"

Debug files is uploaded, thank you very much

[DEBUG.zip](https://github.com/acidanthera/bugtracker/files/9539668/DEBUG.zip)
