### ISSUE TITLE
OC Boot GUI - No horizontal scrolling to off-screen entries

### ISSUE THREAD

**Issue by jjemil749** [acidanthera/bugtracker#1019]
I'm sure this what observed by many, but I didn't see anybody report this.

In OC boot GUI, when there's more entries than the screen can handle, OC boot GUI cannot scroll horizontally to off-screen entries.

In my screenshot, I'm missing NVRAM reset to the far right and can't get to it.

As a suggestion, why not also display the curent OpenCore version like Clover displays its version?

![04145756](https://user-images.githubusercontent.com/5369361/86515559-baf5fe00-bde7-11ea-999e-126e7d857273.png)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/759
