### ISSUE TITLE
IntelMausi.kext

### ISSUE THREAD

**Issue by errorexists** [acidanthera/bugtracker#1020]
it appears that IntelMausi.kext cause a kp i may have a log but for now i disabled in config plist an im still loading the installer on a asus z390-a w/ i9 9900k

**Comment by vit9696** [comment]
That was fixed some time ago for 10.15 and earlier, and a little while ago for 11.0.

**Comment by errorexists** [comment]
ok as i just built the latest commits an updated the kexts about 40 mins ago but thank you on the reply
