### ISSUE TITLE
AirportBrcmFixup not working with kernel collections

### ISSUE THREAD

**Issue by Pavo-IM** [acidanthera/bugtracker#1021]
First of all I would like to say you guys are awesome, the latest OpenCore commits allows booting the installer and pre-existing install of Big Sur with kernel collections instead of prelinkedkernel. Now this is where I have only 1 issue. When using prelinkedkernel by using the nvram booter variables method AirportBrcmFixup works fine. But when using kernel collections without the nvram booter variables method, it loads but doesn't turn on wifi like it does with prelinkedkernel method. I did use the latest commits from, OpenCore, Lilu and AirportBrcmFixup. Attached a debug log from Lilu and AirportBrcmFixup, maybe it will help identify the issue using kernel collections.
KernelCollections Debug logfile:
[Lilu_1.4.6_20.0.txt](https://github.com/acidanthera/bugtracker/files/4875921/Lilu_1.4.6_20.0.txt)
PrelinkedKernel Debug logfile:
[Lilu_1.4.6_20.0.txt](https://github.com/acidanthera/bugtracker/files/4881739/Lilu_1.4.6_20.0.txt)

**Comment by Pavo-IM** [comment]
I think the FakeBrcm is the issue, you can see that its being initialized in the prelinkedkernel log but not in the kernel collections log.
`Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
AirportBrcmFixup    BRCMFX: @ (DBG) FakeBrcm::init(): FakeBrcm disabled
AirportBrcmFixup    BRCMFX: @ (DBG) FakeBrcm::free()
AirportBrcmFixup    BRCMFX: @ (DBG) probe is called, service name is AirPort_BrcmNIC, provider name is ARPT
AirportBrcmFixup     iokit: @ (DBG) getOSData device-id has 43B1 value
AirportBrcmFixup     iokit: @ (DBG) getOSData vendor-id has 14E4 value
Lilu     iokit: @ (DBG) read pci config discovered ARPT space to be 0x00020000
Lilu     iokit: @ (DBG) read pci config discovered ARPT space to be 0x00020000
AirportBrcmFixup    BRCMFX: @ (DBG) PCIHookManager::hookProvider: hook is not required since vendor-id && device-id are the same
AirportBrcmFixup    BRCMFX: @ (DBG) probe is finished with result success
AirportBrcmFixup    BRCMFX: @ (DBG) start is called, service name is AirPort_BrcmNIC, provider name is ARPT
AirportBrcmFixup     iokit: @ (DBG) getOSData device-id has 43B1 value
AirportBrcmFixup     iokit: @ (DBG) getOSData vendor-id has 14E4 value
Lilu     iokit: @ (DBG) read pci config discovered ARPT space to be 0x00020000
Lilu     iokit: @ (DBG) read pci config discovered ARPT space to be 0x00020000
AirportBrcmFixup    BRCMFX: @ (DBG) PCIHookManager::hookProvider: hook is not required since vendor-id && device-id are the same
AirportBrcmFixup    BRCMFX: @ (DBG) siPmuFvcoPllreg2, original chip identificator = 4352
AirportBrcmFixup    BRCMFX: @ (DBG) wlc_set_countrycode_rev2 is called, a3 = -1, country_code = US
AirportBrcmFixup    BRCMFX: @ (DBG) country code is changed from US to US, result = 0
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
AirportBrcmFixup    BRCMFX: @ (DBG) wowCapablePlatform is called, change returned value to false
AirportBrcmFixup    BRCMFX: @ (DBG) newVendorString is called
AirportBrcmFixup    BRCMFX: @ (DBG) start is finished with result 1
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
Lilu   patcher: @ (DBG) invoked at kext loading/unloading
`

**Comment by lvs1974** [comment]
No, FakeBrcm is an optional step. Everything looks ok in your both logs, all patches were successfully applied:
AirportBrcmFixup    BRCMFX: @ (DBG) found com.apple.driver.AirPort.BrcmNIC
Lilu      mach: @ (DBG) found symbol __ZN15AirPort_BrcmNIC5startEP9IOService at 0xffffff80038f3b76 (non-aslr 0xffffff80038f3b76)
Lilu      mach: @ (DBG) found symbol __ZN15AirPort_BrcmNIC5probeEP9IOServicePi at 0xffffff80038f0722 (non-aslr 0xffffff80038f0722)
Lilu      mach: @ (DBG) found symbol _si_pmu_fvco_pllreg at 0xffffff8003b880a4 (non-aslr 0xffffff8003b880a4)
Lilu      mach: @ (DBG) found symbol _wlc_set_countrycode_rev at 0xffffff8003a3dd5b (non-aslr 0xffffff8003a3dd5b)
Lilu      mach: @ (DBG) found symbol __ZNK15AirPort_BrcmNIC15newVendorStringEv at 0xffffff80038ffb7e (non-aslr 0xffffff80038ffb7e)
Lilu      mach: @ (DBG) found symbol __ZN15AirPort_BrcmNIC12checkBoardIdEPKc at 0xffffff80038efe36 (non-aslr 0xffffff80038efe36)
Lilu      mach: @ (DBG) found symbol _osl_panic at 0xffffff80038eadf4 (non-aslr 0xffffff80038eadf4)
Lilu   patcher: @ (DBG) from 0xFFFFFF80038F3B76 to 0xFFFFFF8005BB24D0 diff 0x00000000022BE955 argument 22BE955
Lilu   patcher: @ (DBG) from 0xFFFFFF8005B07BC5 to 0xFFFFFF80038F3B7C diff 0xFFFFFFFFFDDEBFB2 argument FDDEBFB2
Lilu   patcher: @ (DBG) wrapped __ZN15AirPort_BrcmNIC5startEP9IOService
Lilu   patcher: @ (DBG) from 0xFFFFFF80038F0722 to 0xFFFFFF8005BB2A30 diff 0x00000000022C2309 argument 22C2309
Lilu   patcher: @ (DBG) from 0xFFFFFF8005B07BD9 to 0xFFFFFF80038F0728 diff 0xFFFFFFFFFDDE8B4A argument FDDE8B4A
Lilu   patcher: @ (DBG) wrapped __ZN15AirPort_BrcmNIC5probeEP9IOServicePi
Lilu   patcher: @ (DBG) from 0xFFFFFF8003B880A4 to 0xFFFFFF8005BB4740 diff 0x000000000202C697 argument 202C697
Lilu   patcher: @ (DBG) from 0xFFFFFF8005B07BED to 0xFFFFFF8003B880AA diff 0xFFFFFFFFFE0804B8 argument FE0804B8
Lilu   patcher: @ (DBG) wrapped _si_pmu_fvco_pllreg
Lilu   patcher: @ (DBG) from 0xFFFFFF8003A3DD5B to 0xFFFFFF8005BB4400 diff 0x00000000021766A0 argument 21766A0
Lilu   patcher: @ (DBG) from 0xFFFFFF8005B07C01 to 0xFFFFFF8003A3DD61 diff 0xFFFFFFFFFDF3615B argument FDF3615B
Lilu   patcher: @ (DBG) wrapped _wlc_set_countrycode_rev
Lilu   patcher: @ (DBG) from 0xFFFFFF80038FFB7E to 0xFFFFFF8005BB2170 diff 0x00000000022B25ED argument 22B25ED
Lilu   patcher: @ (DBG) routed __ZNK15AirPort_BrcmNIC15newVendorStringEv
Lilu   patcher: @ (DBG) from 0xFFFFFF80038EFE36 to 0xFFFFFF8005BB49D0 diff 0x00000000022C4B95 argument 22C4B95
Lilu   patcher: @ (DBG) routed __ZN15AirPort_BrcmNIC12checkBoardIdEPKc
Lilu   patcher: @ (DBG) from 0xFFFFFF80038EADF4 to 0xFFFFFF8005BB2DB0 diff 0x00000000022C7FB7 argument 22C7FB7
Lilu   patcher: @ (DBG) routed _osl_panic
AirportBrcmFixup    BRCMFX: @ (DBG) all patches are successfuly applied to com.apple.driver.AirPort.BrcmNIC
Lilu      mach: @ (DBG) found symbol __ZN15AirPort_BrcmNIC18wowCapablePlatformEv at 0xffffff80039003e4 (non-aslr 0xffffff80039003e4)
Lilu      mach: @ (DBG) found symbol _wlc_wowl_enable at 0xffffff8003b6d7cd (non-aslr 0xffffff8003b6d7cd)
Lilu   patcher: @ (DBG) from 0xFFFFFF80039003E4 to 0xFFFFFF8005BB2290 diff 0x00000000022B1EA7 argument 22B1EA7
Lilu   patcher: @ (DBG) routed __ZN15AirPort_BrcmNIC18wowCapablePlatformEv
Lilu   patcher: @ (DBG) from 0xFFFFFF8003B6D7CD to 0xFFFFFF8005BB2220 diff 0x0000000002044A4E argument 2044A4E
Lilu   patcher: @ (DBG) routed _wlc_wowl_enable
AirportBrcmFixup    BRCMFX: @ (DBG) wowl disable patch is successfuly applied to com.apple.driver.AirPort.BrcmNIC
AirportBrcmFixup    BRCMFX: @ (DBG) gIOCatalogue->startMatching(OSSymbol const*) successful
AirportBrcmFixup    BRCMFX: @ (DBG) gIOCatalogue->startMatching(OSSymbol const*) successful
AirportBrcmFixup    BRCMFX: @ (DBG) gIOCatalogue->startMatching(OSSymbol const*) successful

**Comment by lvs1974** [comment]
Can you add boot-args  wl_msg_level=0xFFFFFFFF и wl_msg_level2=0xFFFFFFFF and put here a full boot log?

**Comment by Pavo-IM** [comment]
I am not sure what you mean by full boot log but here is everything I know how to get which includes the boot-args you requested. It seems to be trying to work but doesn't enable the device after patching. Again this is only an issue when using kernel collections method of booting. All works fine with prelinkedkernel method of booting.
OpenCore Debug bootlog:
[opencore-2020-07-07-133913.txt](https://github.com/acidanthera/bugtracker/files/4885195/opencore-2020-07-07-133913.txt)
Another Lilu + AirportBrcmFixup Debug log:
[Lilu_1.4.6_20.0.txt](https://github.com/acidanthera/bugtracker/files/4885202/Lilu_1.4.6_20.0.txt)
System Log pulled from Hackintool after boot:
[systemlog.txt](https://github.com/acidanthera/bugtracker/files/4885204/systemlog.txt)
Also a screenshot of the device in IORegistryViewer:
![Screenshot 2020-07-07 09 42 40](https://user-images.githubusercontent.com/33814640/86790839-d99e0400-c036-11ea-8fe1-9bd4cf9876d4.png)

**Comment by lvs1974** [comment]
In boot-args add  -brcmfxdbg  keepsyms=1  msgbuf=1048576, use debug version of AirportBrcmFixup.
Reboot, and run in terminal: sudo dmesg > dmesg.txt, and put dmesg.txt here.

**Comment by Pavo-IM** [comment]
Yeah its weird its like it disables it or something when booting as kernel collections method. Here is the dmesg.txt you asked for.
[dmesg.txt](https://github.com/acidanthera/bugtracker/files/4885315/dmesg.txt)

**Comment by lvs1974** [comment]
@Pavo-IM, it looks like com.apple.driver.AirPort.BrcmNIC is in cache, but it is not started, there is no any attempts to start.
Can you try to run this kext manually, using kextutil -v?

**Comment by Pavo-IM** [comment]
This is the output of that command:
```
henrybrock@Henrys-iMac-Pro ~ % sudo kextutil -v /System/Library/Extensions/IO80211Family.kext/Contents/PlugIns/AirPortBrcmNIC.kext 
Defaulting to kernel file '/System/Library/Kernels/kernel'
Executing: /usr/bin/kmutil load --bundle-path /System/Library/Extensions/IO80211Family.kext/Contents/PlugIns/AirPortBrcmNIC.kext
```

**Comment by lvs1974** [comment]
And what is in dmes log after thus start?
Kext is loaded?

**Comment by Pavo-IM** [comment]
Nothing new is showing up in dmesg after running the command and not showing as loaded in kextstat command. But AirportBrcmFixup is showing in kextstat as loaded.
`   45    0 0                  0x18000    0x18000    as.lvs1974.AirportBrcmFixup (2.0.8) 0E5286B7-D6A9-38A7-867F-047BD003A590 <44 42 14 8 6 5 3 2 1>
`

**Comment by Pavo-IM** [comment]
Ok my bad it is show in kextstat I was greping for the wrong name lol. But here is the kextstat command output.
[kextstat.txt](https://github.com/acidanthera/bugtracker/files/4885574/kextstat.txt)

**Comment by Pavo-IM** [comment]
Do you want me to repeat the process of all the logs with prelinkedkernel boot method?

**Comment by lvs1974** [comment]
Yes, it would be nice.
What is your original card device ID and do you use DeviceProperties in OpenCore to inject something for this card?

**Comment by Pavo-IM** [comment]
Here is the dmesg.txt with prelinkedkernel boot method:
[dmesg.txt](https://github.com/acidanthera/bugtracker/files/4885725/dmesg.txt)
The device-id is b143 as you can see in the IORegistryViewer screenshot:
![Screenshot 2020-07-07 11 30 00](https://user-images.githubusercontent.com/33814640/86804844-49b38680-c045-11ea-9b7a-73ca754c3763.png)
And I don't use Device Properties, I do use a SSDT to make it show as internal only, I do not change the device-id.
```
DefinitionBlock ("", "SSDT", 1, "APPLE ", "ARPT", 0x00001000)
{
    External (_SB_.PCI0, DeviceObj)

    Scope (_SB.PCI0)
    {
        Device (PEG8)
        {
            Name (_ADR, 0x00100001)  // _ADR: Address
            Device (ARPT)
            {
                Name (_ADR, Zero)  // _ADR: Address
            }
        }
    }
}
```

**Comment by Pavo-IM** [comment]
I did notice one interesting thing though with kextstat. KernelCollections kextstat doesn't show addresses for anything that is getting injected with OpenCore but prelinkedkernel kextstat does.
Prelinkedkernel kextstat:
[kextstat.txt](https://github.com/acidanthera/bugtracker/files/4885802/kextstat.txt)

**Comment by Pavo-IM** [comment]
If you have the patches that you apply, I could test using Kernel > Patches in OpenCore manually if you want. I looked through the code and couldn't determine what you was patching exactly.

**Comment by lvs1974** [comment]
- Device ARPT is SSDT is not needed, AirportBrcmFixup renames provider into ARPT
- There are no any binary patches in AirportBrcmFixup, only symbol patches
- This issue can be related to Lilu (kernel patcher is ready to use when all kexts are already loaded)

**Comment by Pavo-IM** [comment]
Roger, I was thinking it was also Lilu related with the new patching for kernel collections. I agree the ARPT SSDT isn't needed but it also doesn't effect it because it still works prelinkedkernel booting.

**Comment by ameenjuz** [comment]
i have same issue wifi not detect on big sur
dell 1560 14e4 43b1 is not working but bt work fine

**Comment by bkchaw** [comment]
mine is working with kernel collections

![Screen Shot 2020-07-10 at 9 46 56 PM](https://user-images.githubusercontent.com/6147902/87161369-01bb8a80-c2f7-11ea-9ae3-55cbaa132559.png)

**Comment by Pavo-IM** [comment]
> mine is working with kernel collections.
> and I noticed that you must have BrcmBluetoothInjector.kext installed in order for it to work.

Can you upload the logs from using Debug versions like I have and BrcmBluetoothInjector is from BrcmRAMPatch repo and is working here also with kernel collections but has nothing to do with AirportBrcmFixup.

**Comment by ameenjuz** [comment]
@Pavo-IM  you are right absulotelly right
 this is only an issue when using kernel collections method of booting. All works fine with prelinkedkernel method of booting
All kexts like AppleALC SMCBatteryManager Airpotbrcmfixup.kext and other kexts work well with prelinkedkernel method 
also speedup menu bar icon boot shutdown fast
only issue with kernel collections method also slow shutdown  and menu bar icon
I think that dev will further struggle with kernel collections method to fix all above issues

**Comment by lvs1974** [comment]
Hello everybody!
Please try attached version: 
[AirportBrcmFixup.kext.zip](https://github.com/acidanthera/bugtracker/files/4906706/AirportBrcmFixup.kext.zip)

**Comment by Pavo-IM** [comment]
> Hello everybody!
> Please try attached version:
> [AirportBrcmFixup.kext.zip](https://github.com/acidanthera/bugtracker/files/4906706/AirportBrcmFixup.kext.zip)

This is working perfect @lvs1974. Here is the Lilu dump and dimes outputs.
[Lilu_1.4.6_20.0.txt](https://github.com/acidanthera/bugtracker/files/4906920/Lilu_1.4.6_20.0.txt)
[dmesg.txt](https://github.com/acidanthera/bugtracker/files/4906921/dmesg.txt)
So... whatever you did, it is working now with kernel collections boot method.

**Comment by jaburgeson** [comment]
This is working for me too!

Thanks!

**Comment by ameenjuz** [comment]
@lvs1974  great worked fine on big sur also other kexts work  no more slow menu bar icon

**Comment by Sher1ocks** [comment]
good working.
any chance like this solution for smcbatteymanager.kext of VirtualSMC?

**Comment by ameenjuz** [comment]
We hope that dev will find solution for smcbatteymanager.kext of VirtualSMC

**Comment by lvs1974** [comment]
One more version for testing: 
[AirportBrcmFixup-2.0.8-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/4907291/AirportBrcmFixup-2.0.8-DEBUG.zip)
Please pay attention to the latest commit:
Remove injectors for AirPortBrcm4360 and AirPortBrcmNIC from main Info.plist and move them into separate plugins AirPortBrcm4360_Injector and 
AirPortBrcmNIC_Injector (kexts with plist only).
Under 10.16 (Big Sur) plugin AirPortBrcm4360_Injector.kext must be blocked by MaxKernel 19.9.9 or just removed, otherwise it will block loading of AirPortBrcmNIC
since class AirPortBrcm4360 is unsupported.

So, if you need one of these injectors, add them into OpenCore:
			<dict>
				<key>BundlePath</key>
				<string>AirportBrcmFixup.kext/Contents/PlugIns/AirPortBrcmNIC_Injector.kext</string>
				<key>Enabled</key>
				<true/>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>BundlePath</key>
				<string>AirportBrcmFixup.kext/Contents/PlugIns/AirPortBrcm4360_Injector.kext</string>
				<key>Enabled</key>
				<true/>
				<key>MaxKernel</key>
				<string>19.9.9</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>BundlePath</key>
				<string>AirportBrcmFixup.kext</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/AirportBrcmFixup</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>

If you use Clover with Big Sur - remove AirPortBrcm4360_Injector.kext

**Comment by Pavo-IM** [comment]
@lvs1974 This latest one is also working as intended, thank you so much for getting this fixed as fast as you did, great job.

**Comment by Pavo-IM** [comment]
Since the issue has been fixed, I will close this bug report. Again thank you @lvs1974 for getting this fixed so fast.

**Comment by Mitsukata** [comment]
@lvs1974,Thank you again for solving the problem!

**Comment by lvs1974** [comment]
Hello everybody,
I would like to ask you to test attached version again.
I have found and fixed some issues (wi-fi stopped worked after updating to 10.15.6).
[AirportBrcmFixup-2.0.8-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/4930773/AirportBrcmFixup-2.0.8-DEBUG.zip)

**Comment by Pavo-IM** [comment]
@lvs1974 still working here with that one.
