### ISSUE TITLE
OpenCorePkg commit: 57f4824a8e4d0f8bfcadff310c58f1be6c5ea330 doesn't load USBX power properties without "booter-fileset-kernel"

### ISSUE THREAD

**Issue by dehjomz** [acidanthera/bugtracker#1022]
Hello, this is my first report of an issue for Opencore.  I'm not certain of the proper protocol on how to describe the issue or what files to provide. 

I want to start by saying thank you very much to the developers for your time and dedication.  I know Opencore 0.6.0 is a work in progress, but I wanted to somehow help the development, so by the time the final version of Big Sur is released in the fall, things are smooth for users of Opencore.  

The issue I'm having is in regards to Opencore 0.6.0 beta, the current master commit as of Monday July 6, 2020 at 1:00 pm Eastern Time New York (commit: 57f4824a8e4d0f8bfcadff310c58f1be6c5ea330). 

I know recently to boot Big Sur, we had to set "booter-fileset-kernel" to "00" in NVRAM variable 7C436110-AB2A-4BBB-A880-FE41995C9F82.  Then, with vit9696 and the gang's good hard work, with commit: 57f4824a8e4d0f8bfcadff310c58f1be6c5ea330 to master, we can now boot without it, which enables booting the installer/recovery disk.  However, upon testing, I've noticed that there's an issue injecting Device USBX power properties on Big Sur with NVRAM variable "booter-fileset-kernel" removed from the config file.  

Big Sur now boots without this variable being set (older versions of Opencore wouldn't boot Big Sur without "booter-fileset-kernel"), but the USB power properties are not being read from SSDT-USBX anymore, according to IoRegistryExplorer.  This SSDT injects values for "kUSBSleepPowerSupply", "kUSBSleepPortCurrentLimit", "kUSBWakePowerSupply", and "kUSBWakePortCurrentLimit".

The reason why this is an issue is because without the power properties being set, macOS sets the sleep current on attached USB devices to 0.  I checked this in IoRegistryExplorer.  So when the computer goes to sleep, it ejects all attached USB devices, including attached USB hard drives without unmounting them.  This can cause data loss.  Using the latest commit of Opencore 0.6.0 beta, in Catalina, and on Big Sur with NVRAM variable  "booter-fileset-kernel" set to "00," this doesn't happen.  SSDT-USBX's power properties are properly injected, and the system goes to sleep just fine, while continuing to power USB devices.

I don't know if it's a bug in macOS Big Sur beta, or in Opencore, but it is very strange that with "booter-fileset-kernel" set to 00, USBX power properties are injected (using SSDT-USBX), but without this NVRAM variable, there is no injection of USBX power properties.

Consider having a look please.  I will update this post with any files that you might need.  Thanks!  All I want is to help!

Thank you!

**Comment by Pavo-IM** [comment]
Seems to be working fine here with injecting the USBX settings in my SSDT.
![Screenshot 2020-07-06 13 48 38](https://user-images.githubusercontent.com/33814640/86623427-93da3080-bf8f-11ea-84a5-ba400a2dc582.png)
![Screenshot 2020-07-06 13 49 18](https://user-images.githubusercontent.com/33814640/86623435-976db780-bf8f-11ea-96b4-9bee53edb6d0.png)

**Comment by dehjomz** [comment]
I retested, cleared NVRAM, and seems that the issue is no longer there.  Perhaps was a config.plist error.  Thank you so much, and sorry for the confusion.
