### ISSUE TITLE
Whatevergreen Big Sur Update for internal 4k Display on Notebook

### ISSUE THREAD

**Issue by gangsterrapper22** [acidanthera/bugtracker#1024]
I know it is maybe a bit early to ask, when Big Sur is still beta. 
When I start Big Sur with the latest Whatevergreen Kext, compiled from the master Branch, then my internal Display on my Dell XPS 15 9550 is black. I only get Output via the HDMI to my external Display. My internal Display is a 4k Display. 
I think the Patch has changed on Big Sur, that will enable the 4k Display. On Catalina everything is fine.
If you need a Debug Log or something else, which I should test, please let me know.

Thank you.

**Comment by zhen-zen** [comment]
The user patcher used for Coredisplay was disabled in Lili on Big Sur. So other kexts / functions relying on it such as SystemProfilerMemoryFixup should have broken as well. Just wait a fully functional Lilu first.

**Comment by gujiangjiang** [comment]
enable-hdmi20 is unusable since user space patching is disabled. Also there's no binary﻿ at /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay

With latest lilu the enable-hdmi20 still not work and 4K display cant work.
