### ISSUE TITLE
EFI Bootloader using OpenCore in VM

### ISSUE THREAD

**Issue by twlawrenceko** [acidanthera/bugtracker#1025]
Hello,

As I further planning to use OpenCore as a bootloader in Virtual Machine (i.e. VirtualBox), it seems creating an ISO file with EFI folders included is not being detected under UEFI Shell (i.e. no FS0 under map). Is there any way to approach this?

Thanks,
twsps

**Comment by 07151129** [comment]
Does your ISO contain ESP?

**Comment by twlawrenceko** [comment]
> Does your ISO contain ESP?

How do I create an ESP on a macOS Installation ISO image?
Seems like there is no EFI partition for me to mount, is there any way to create an EFI partition to it?

Thanks,
twsps

**Comment by twlawrenceko** [comment]
With using this setting which will create a FAT32 partition, putting EFI folder in is not able to be recognized in UEFI Shell, however, FS0 does come out which leads me to put EFI folder in the big partition (i.e. disk2s2). Is there any reason disk2s1 is not being recognized in UEFI Shell?
<img width="404" alt="Screen Shot 2020-07-08 at 10 18 45 PM" src="https://user-images.githubusercontent.com/14770978/86929993-0e11dd00-c169-11ea-9bde-b953b26065da.png">


Thanks,
twsps

**Comment by vit9696** [comment]
Last time I debugged on VirtualBox I used hard-drive creation via qemu-img. I.e. I built a disk from the folder as usual via hdiutil, and then converted it with qemu-img to vmdk or vdi. I think iso support in VirtualBox is broken.

**Comment by 07151129** [comment]
Note that the ISO you posted has an apple partition map instead of GPT:

```
$ hdiutil pmap -complete Clover-v2.5k-5070-X64.iso 

MEDIA: ""; Size 10 MB [19592 x 512]; Max Transfer Blocks 2048
SCHEME: 1 ISO9660, "ISO 9660 CD Partition Scheme" [32]
SECTION: 1 Type:'MAP'; Size 10 MB [19592 x 512]; Offset 64 Blocks (19592 + 64) x 512; [Actual Blocksize 2048]
ID Type                 Offset       Size         End          Name                      (2)
-- -------------------- ------------ ------------ ------------ -------------------- --------
 0 PRIMARY VOLUME DESCR           64        19528        19591 CLOVERCD            
 0 SECONDARY VOLUME DES           64        19528        19591
   Free                        19592           64        19655

SCHEME: 2 APM, "Apple Partition Scheme" [1]
SECTION: 1 Type:'MAP'; Size 2 TB [3293052928 x 512]; Offset 1 Blocks (3293052927 + 1) x 512; [Actual Blocksize 2048]
ID Type                 Offset       Size         End          Name                      (2)
-- -------------------- ------------ ------------ ------------ -------------------- --------
 1 Apple_partition_map             1           63           63 Apple               
   Free                           64          644          707
 2 Apple_HFS                     708        18884        19591 DiscRecording 9.0.3d
   Free                        19592   3293033336   3293052927
```

**Comment by nms42** [comment]
> Note that the ISO you posted has an apple partition map instead of GPT:
> 
> ```
> $ hdiutil pmap -complete Clover-v2.5k-5070-X64.iso 
> 
> MEDIA: ""; Size 10 MB [19592 x 512]; Max Transfer Blocks 2048
> SCHEME: 1 ISO9660, "ISO 9660 CD Partition Scheme" [32]
> SECTION: 1 Type:'MAP'; Size 10 MB [19592 x 512]; Offset 64 Blocks (19592 + 64) x 512; [Actual Blocksize 2048]
> ID Type                 Offset       Size         End          Name                      (2)
> -- -------------------- ------------ ------------ ------------ -------------------- --------
>  0 PRIMARY VOLUME DESCR           64        19528        19591 CLOVERCD            
>  0 SECONDARY VOLUME DES           64        19528        19591
>    Free                        19592           64        19655
> 
> SCHEME: 2 APM, "Apple Partition Scheme" [1]
> SECTION: 1 Type:'MAP'; Size 2 TB [3293052928 x 512]; Offset 1 Blocks (3293052927 + 1) x 512; [Actual Blocksize 2048]
> ID Type                 Offset       Size         End          Name                      (2)
> -- -------------------- ------------ ------------ ------------ -------------------- --------
>  1 Apple_partition_map             1           63           63 Apple               
>    Free                           64          644          707
>  2 Apple_HFS                     708        18884        19591 DiscRecording 9.0.3d
>    Free                        19592   3293033336   3293052927
> ```
> 
> Perhaps try using APM for your image as well? I am also unsure about using UDSP instead of UDRW.

Are You discussing _Clover_ media in _OpenCore_ project?

**Comment by 07151129** [comment]
I am discussing virtualbox boot media compatibility. This is not a Clover support issue; the Clover media is merely an example.

I am also pretty sure we do not have a policy that prohibits any mention of Clover.

**Comment by twlawrenceko** [comment]
> Note that the ISO you posted has an apple partition map instead of GPT:
> 
> ```
> $ hdiutil pmap -complete Clover-v2.5k-5070-X64.iso 
> 
> MEDIA: ""; Size 10 MB [19592 x 512]; Max Transfer Blocks 2048
> SCHEME: 1 ISO9660, "ISO 9660 CD Partition Scheme" [32]
> SECTION: 1 Type:'MAP'; Size 10 MB [19592 x 512]; Offset 64 Blocks (19592 + 64) x 512; [Actual Blocksize 2048]
> ID Type                 Offset       Size         End          Name                      (2)
> -- -------------------- ------------ ------------ ------------ -------------------- --------
>  0 PRIMARY VOLUME DESCR           64        19528        19591 CLOVERCD            
>  0 SECONDARY VOLUME DES           64        19528        19591
>    Free                        19592           64        19655
> 
> SCHEME: 2 APM, "Apple Partition Scheme" [1]
> SECTION: 1 Type:'MAP'; Size 2 TB [3293052928 x 512]; Offset 1 Blocks (3293052927 + 1) x 512; [Actual Blocksize 2048]
> ID Type                 Offset       Size         End          Name                      (2)
> -- -------------------- ------------ ------------ ------------ -------------------- --------
>  1 Apple_partition_map             1           63           63 Apple               
>    Free                           64          644          707
>  2 Apple_HFS                     708        18884        19591 DiscRecording 9.0.3d
>    Free                        19592   3293033336   3293052927
> ```
> 
> Perhaps try using APM for your image as well? I am also unsure about using UDSP instead of UDRW.

Yes, that is correct. However, that is just for reference, as I wanted to implement an ISO containing ESP that can be recognized in UEFI Shell.

I also realized that with the creation of sparseimage in disk utility, it contains EFI partition, which I did put OC EFI folder in. However, when I convert to .cdr or .iso the EFI partition is not visible via the `hdiutil pmap` command.

<img width="565" alt="Screen Shot 2020-07-09 at 8 57 42 PM" src="https://user-images.githubusercontent.com/14770978/87042879-d6696a80-c226-11ea-8395-edd7e2914e23.png">

<img width="488" alt="Screen Shot 2020-07-09 at 8 58 42 PM" src="https://user-images.githubusercontent.com/14770978/87042973-f9941a00-c226-11ea-9fc3-da5c5010f6c3.png">

Thanks,
twsps

**Comment by twlawrenceko** [comment]
I would need to clarify my problem here. I am not able to export from any kind of format (i.e. sparseimage) to ISO and still retain the ESP partition. Therefore UEFI Shell are not able to recognize any EFI partition.

Thanks,
twsps
