### ISSUE TITLE
VoodooPS2 Trackpad not working correctly

### ISSUE THREAD

**Issue by cheesycod** [acidanthera/bugtracker#1026]
VoodooPS2 Trackpad not working correctly, all clicks behave like forced clicks and this causes odd behaviour (Launchpad not working, Apps don't open correctly etc.. This same trackpad works using RehabMan's VoodooPS2. Tested on Catalina and Big Sur. This is using OpenCore 0.5.9 and 0.6.0 and the latest version of Lilu. The boot args used was "-v -disablegfxfirmware -vsmcbeta -lilubetaall"

**Comment by cheesycod** [comment]
I will provide my efi in a few minutes

**Comment by marianopela** [comment]
I believe you just need to tweak the settings in Info.plist found inside VoodooPS2Trackpad (eg. setting ForceTouchMode to 0)
![Screenshot 2020-07-08 at 13 10 40](https://user-images.githubusercontent.com/42821024/86911960-6d95cb80-c11c-11ea-8d5a-72624b6927a4.png)

**Comment by obbcth** [comment]
Same problem on SYN2602 (Samsung NT900X5W-K58WS with i5 7200u)
ForceTouchMode doesn’t make changes.

**Comment by cheesycod** [comment]
Didn’t help
