### ISSUE TITLE
Lenovo ThinkBook 13s-IML, Thinkpad X1 Carbon 7th 20R1 and Yoga C640-13iml with comet lake cpu Stuck at EB # LOG:Exitbs: Start

### ISSUE THREAD

**Issue by albi74** [acidanthera/bugtracker#1027]
Hi,
I'm trying to install catalina 10.15.5 with opencore 0.5.9 or 0.6.0 on these notebooks but any configuration I try get stuck at EB # LOG:Exitbs: Start

121:609 00:288 AAPL: [EB|`LD:LKFS] } Ok(0)
121:874 00:265 AAPL: [EB|`LD:LKC] } Ok(0)
122:140 00:265 AAPL: [EB|#FWFM] 0xFF9FFF3F
122:405 00:265 AAPL: [EB|#FWFT] 0xFD8FF42E
122:670 00:265 AAPL: [EB|#CSR:IN] 0x000003E7
122:935 00:265 AAPL: [EB|#CSR:OUT] 0x000003E7
123:202 00:266 AAPL: [EB|`BST:FBS] {
123:468 00:265 AAPL: [EB|`BST:FBS] BA.ADSZ: 0
123:733 00:265 AAPL: [EB|`BST:FBS] BA.KSDSZ: 0
123:965 00:232 OCSMC: SmcReadValue Key 4D535463 Size 1
124:130 00:164 OCSMC: SmcReadValue Key 4D534163 Size 2
124:396 00:265 AAPL: [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49
124:662 00:265 AAPL: [EB|#LOG:DT] 2020-07-08T15:50:01
124:928 00:266 AAPL: [EB|#LOG:EXITBS:START] 2020-07-08T15:50:02

I have read anything about that mistake, i tried different combinations of booter and kernel quirks and all the tips to get through that state but nobody worked.

It seems that the problem is related to the comet lake cpu and to these lenovo models only, in fact this same EFI on a lenovo s145-iml and on an s540-iml works without any problem.

I remain available for any test. 
Sorry for my english

[opencore-2020-07-08-154757.txt](https://github.com/acidanthera/bugtracker/files/4891993/opencore-2020-07-08-154757.txt)

[EFI.zip](https://github.com/acidanthera/bugtracker/files/4891997/EFI.zip)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by albi74** [comment]
Sorry if I'm bored. But if I came to write here, don't you think that I first shot on all the forums followed 1000 guides and did the same tests? I have three lenovo notebooks available and they all have the same problem because they all come from the Carbon X1 with Comet Lake processor. Otherwise I wasn't bored.

**Comment by richibrics** [comment]
Same issue on my Lenovo Yoga C640

**Comment by zskyfall** [comment]
So sad, i have the same problem with my ThinkBook 15 IML :(((, I tried many config but all failed.

**Comment by wadehwd** [comment]
Did you try this:config.plist ->UEFI ->Quirks ->IgnoreInvalidFlexRatio ->True/YES?
If it doesn't work try this as well:config.plist ->Kernel ->Quirks ->AppleCpuPmCfgLock/AppleXcpmCfgLock ->True/YES.

**Comment by MuhammadAhmadChaudhary** [comment]
same issue here, have an x1c7 20R1. Still no fix found yet. stuck on the same spot

**Comment by richibrics** [comment]
Maybe it can help, I saw a Lenovo Thinkpad X1 Carbon 6th with BigSur: [Reddit](https://www.reddit.com/r/hackintosh/comments/kv3jc7/big_sur_111_on_lenovo_thinkpad_x1_carbon_6th_and/)
