### ISSUE TITLE
Black screen instead of picker being displayed

### ISSUE THREAD

**Issue by joergmaertin** [acidanthera/bugtracker#1029]
Hey :-). Thank you for OC and your work, first off. Trying OC I stumbled over a rather strange problem:

1. I was able to install and run OC 0.5.9 and even OC 0.6.0 and start my computer into Windows, Linux and macOS, each on different SSDs.
2. I needed to reinstall Windows, so I formatted the corresponding disk under macOS
3. After I did that, I was not able to boot into OC, instead of the picker menu there was only a black screen
4. After a few days I tried again, I reinstalled OC and for some reason I could boot again with OC, picker was visble again
5. I needed to reinstall Ubuntu, so I formatted the corresponding disk under macOS
6. Same problem again, no picker menu in OC, only a black screen. Even if I reinstall OC 0.5.9 or OC 0.6.0 that were previously working.

Install a new operating macOS, like big sur on my computer was ok in OC, the new system was recognized in the picker on reboot. Also formatting the new macOS disk again was also no problem, the picker was visible even after I formatted this macOS ssd. So it only happened with Windows or Linux disks that were visible and then resulted in a black screen without picker, after formatting the corresponding disks.

My question is, is that a bug in OC or a misconfiguration on my side?
Sorry I don't know how to provice the log files you asked for, only my EFI, the last one known working.

[OpenCore 0.6.0 working.zip](https://github.com/acidanthera/bugtracker/files/4893012/OpenCore.0.6.0.working.zip)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
