### ISSUE TITLE
Serial debug is not functioning in OpenCore

### ISSUE THREAD

**Issue by wangyi6854** [acidanthera/bugtracker#1032]
OpenCore version: 0.5.9 debug

I found the serial output in debug version of oc is broken.

My boot-args is -v keepsyms=1 gfxrst=1 -wegdbg debug=0x108 serial=5 msgbuf=1048576 npci=0x2000 amfi_get_out_of_my_way=1

If I set 'target' to 9, which is 1+8(enable logging and serial logging), there is nothing in serial console while oc booting. 
after oc loading, the first several messages from serial port I got were

> uSerial mode specified: 00000005 
> WARNING: Forcing uart driver to output synchronously.printf()s/IOLogs will impact kernel performance. 
> You are advised to avoid using 'drain_uart_sync' boot-arg. 

I think these messages are from os kernel.

When I change target's value from 9 to 73, which adds 64( log to file ) to 9, I can get file log from oc booting, but serial messages are still missing.

**Comment by vit9696** [comment]
Please check the master version. I remember some fixes in there for 0.6.0.

**Comment by wangyi6854** [comment]
After updated to 0.6.0, I got messages from the serial port. 

Well done.

Thanks very much!
