### ISSUE TITLE
[WhateverGreen] Netflix not working on Big Sur

### ISSUE THREAD

**Issue by JG-Park** [acidanthera/bugtracker#1034]
I use shiki=80 and spoof iMacPro's board-id.
It perfectly serves sidecars and Netflix in Catalina.
Also I use UHD630 + RX5700XT as headless.

My guess is two.

1. shiki not compatible with Big Sur.
2. Compatibility with new cross-tracking prevention features Safari 14.

Any feedback would be appreciated.

**Comment by vit9696** [comment]
Lilu has not working userspace patcher in 11.0. We are not yet positive whether we will continue supporting it at all.

**Comment by HQuest** [comment]
Hey @vit9696 is the userspace patcher still in an unknown future at this point? Sleep/wake is definitely much more doable/reliable with an iMac SMBIOS, however DRM videos doesn't work. DRM videos works under iMacPro SMBIOS but sleep/wake is way more complex and unreliable for non-Xeon CPUs.

Miss the ability of having the best of both worlds, but I see how busy you guys are and there are only so many things that can be done at a time.

**Comment by vit9696** [comment]
I think this feature may land after I upgrade to Big Sur myself, similar to how it happened with Catalina. I.e. around some point release.

**Comment by hd5970** [comment]
Really appreciated if anyone could add this support for Big Sur
