### ISSUE TITLE
CPU spoofing is breaking Docker

### ISSUE THREAD

**Issue by lucaslg26** [acidanthera/bugtracker#1035]
Hello guys, this problem was originally reported in https://github.com/docker/for-mac/issues/4654

I'm using Opencore 0.5.9 in a X99 platform with a Haswell-E/P CPU, but this isn't directly related I think.

When spoofing cpu using Cpu1IdData and Cpu1IdMask Docker breaks on pulling images due to wrong hash calculation and/or corrupting data. Removing this immediately starts working flawless (but without cpu power mgmt in my specific case).

Can this be related to some instruction set / feature being enabled that's not supported on the running CPU?

I can provide logs if needed.

**Comment by davisinfo** [comment]
Even if the if the Cpu1IdData set is the same as the CPU actually has it still breaks Docker, so the only way Docker works is not having anything set for Cpu1IdData

**Comment by lucaslg26** [comment]
@davisinfo curious thing is pulling small images like alpine sometimes works when you keep trying pull it

**Comment by davisinfo** [comment]
@lucaslg26 really? I tried multiple times, with alpine also, but never worked, even tried different versions of Docker.

**Comment by vit9696** [comment]
Sorry, but no. This cannot affect docker in any sensible manner. If you patch it with the same value no changes XNU-wise happen.

**Comment by davisinfo** [comment]
@vit9696 I have a i7 5820k CPU, CPUID is 306F2 . If I set 

`Cpuid1Data   <->  F2060300 00000000 00000000 00000000
Cpuid1Mask  <->   FFFFFFFF 00000000 00000000 00000000 ﻿`

 I cannot pull any docker image anymore, I get `filesystem layer verification failed for digest sha256:12be1dff6fcd25200728ea586d5f0a620be9a7703827ec2daf501a9fe35c42f2` . If I set Cpuid1Data and Cpuid1Mask to blank it works again. 

How do you explain this then?

![Screenshot 2020-07-13 07 59 02](https://user-images.githubusercontent.com/88761/87272858-27f04e80-c4e0-11ea-977c-2bd7e17f3045.png)
![Screenshot 2020-07-13 08 01 19](https://user-images.githubusercontent.com/88761/87272860-2a52a880-c4e0-11ea-8113-4a8757ef0706.png)
![Screenshot 2020-07-13 08 04 53](https://user-images.githubusercontent.com/88761/87272864-2de62f80-c4e0-11ea-948b-b76fce12f190.png)

**Comment by vit9696** [comment]
It is hard to be sure. My best guess is that this is coincidence. However, I have two more versions:
- microcode revision, virtualising cpuid slightly changes the codepath for its acquisition. You can could compare it for equality via `sysctl machdep` command.
- timing issues, if Docker has a race condition, reducing the amount of time needed to get the CPU info may help to trigger it.

**Comment by davisinfo** [comment]
I could reproduce it several times ( changing the setting on and off and rebooting ) and also on different machines / cpu generation so it is not a coincidence. 

I don't understand what you mean by "reducing the amount of time needed to get the CPU info". The error from Docker is a checksum error, the checksum seems to be calculated wrongly when the cpuid is faked. 

I'll check the microcode revision.

**Comment by vit9696** [comment]
> I don't understand what you mean by "reducing the amount of time needed to get the CPU info". The error from Docker is a checksum error, the checksum seems to be calculated wrongly when the cpuid is faked.

The effects of a race condition could be anything, including memory corruptions. I would say better Google for it.

**Comment by usr-sse2** [comment]
I couldn't reproduce the issue on Ivy Bridge changing CPUID from 198313 to 198312 and to 198313 itself. As I don't have a Haswell CPU, I'll test later on Kaby Lake Refresh.

**Comment by davisinfo** [comment]
> > I don't understand what you mean by "reducing the amount of time needed to get the CPU info". The error from Docker is a checksum error, the checksum seems to be calculated wrongly when the cpuid is faked.
> 
> The effects of a race condition could be anything, including memory corruptions. I would say better Google for it.

The comment was more about why would Docker need to get CPU info when pulling an image. The issue from what I've seen so far is only when trying to pull a new image that is not present locally.

**Comment by vit9696** [comment]
We personally do not have an idea either, but on macOS Docker is using VirtualBox, and given that it needs to emulate the hardware its hypervisor might rely on some relatively weird stuff. Either way, the issue is not reproducible for us, and we cannot think of anything in particular that might affect it besides the microcode thing, and even that is a "very unlikely" suspect.

Just to make it transparent on what CPUID virtualisation does, here is [the code](https://github.com/acidanthera/OpenCorePkg/blob/8a03275/Library/OcAppleKernelLib/CommonPatches.c#L1077) that is relevant to the change. Basically [the following lines](https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/osfmk/i386/cpuid.c#L563-L566) in the Apple kernel are modified from:

```C
	wrmsr64(MSR_IA32_BIOS_SIGN_ID, 0);
	cpuid_fn(1, reg);
	info_p->cpuid_microcode_version =
		(uint32_t) (rdmsr64(MSR_IA32_BIOS_SIGN_ID) >> 32);
```

to

```C
	reg[0] = (Cpuid1Data[0] & Cpuid1Mask[0]) | (CPUID[0] & ~Cpuid1Mask[0]);
	reg[1] = (Cpuid1Data[1] & Cpuid1Mask[1]) | (CPUID[1] & ~Cpuid1Mask[1]);
	reg[2] = (Cpuid1Data[2] & Cpuid1Mask[2]) | (CPUID[2] & ~Cpuid1Mask[2]);
	reg[3] = (Cpuid1Data[3] & Cpuid1Mask[3]) | (CPUID[3] & ~Cpuid1Mask[3]);

	info_p->cpuid_microcode_version =
		(uint32_t) (BIOS_VALUE_OF_MSR_IA32_BIOS_SIGN_ID >> 32);
```

The only place where this can go "different" is when the motherboard BIOS contains an outdated version of CPU microcode, and the operating system has to update the microcode on its own. In this case the microcode will be updated, but the sysctl interface may still report the [old version](https://github.com/apple/darwin-xnu/blob/a449c6a3b8014d9406c2ddbdc81795da24aa7443/osfmk/i386/ucode.c#L187). This is purely cosmetics, but I mention it to avoid any misunderstanding. Also, making the operating system update the microcode is unreliable in the first place as some security mitigations cannot be applied at a later stage, and therefore it is not recommended to rely on this.

**Comment by lucaslg26** [comment]
@vit9696 Docker Desktop uses Apple HyperKit, not VirtualBox.
Docker with docker-machine and VirtualBox just works.

**Comment by vit9696** [comment]
Well, I don't know, like I said, it works fine for us, and we do not see any technical reason for it t be broken. I gave you a recommendation, there is no reason in polemics without any further technical details.

**Comment by davisinfo** [comment]
I checked on a Coffee Lake Refresh CPU now and there are indeed differences in the microcode and features even though the same cpuid is set in the config file.

`diff machdep-nocpuid2.txt machdep-fakecpuid2.txt
11c11
< machdep.cpu.feature_bits: 9221960262849657855
---
> machdep.cpu.feature_bits: 8645499510546234367
17c17
< machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
---
> machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
22c22
< machdep.cpu.microcode_version: 198
---
> machdep.cpu.microcode_version: 184
61,63c61,63
< machdep.pmap.hashwalks: 1427947
< machdep.pmap.hashcnts: 1615134
< machdep.pmap.hashmax: 14
---
> machdep.pmap.hashwalks: 1226781
> machdep.pmap.hashcnts: 1379131
> machdep.pmap.hashmax: 19
`

**Comment by davisinfo** [comment]
@vit9696 So to be clear you are saying that with Docker for Mac ( not the older Docker Toolbox ) you can still pull new images even if cpuid is fake to the same value as the cpu actually has and the problem that myself and @lucaslg26 and some other guy that posted the same fix on the issue reported on the docker repo have is that we have an outdated bios with outdated cpu microcodes.

**Comment by vit9696** [comment]
Try using:
```
Data: <XX XX XX XX 00 00 00 00 00 00 00 04 00 00 00 00> 
Mask <FF FF FF FF 00 00 00 00 00 00 00 04 00 00 00 00>
```

**Comment by davisinfo** [comment]
@vit9696 OSXSAVE still doesn't appear, it looks the same

![Screen Shot 2020-07-14 at 9 23 09 AM](https://user-images.githubusercontent.com/88761/87391595-b1bd1c00-c5b3-11ea-929c-504b40e259ed.png)

`diff machdep-nocpuid2.txt machdep-fakecpuid3.txt
11c11
< machdep.cpu.feature_bits: 9221960262849657855
---
> machdep.cpu.feature_bits: 8645499510546234367
17c17
< machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
---
> machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
22c22
< machdep.cpu.microcode_version: 198
---
> machdep.cpu.microcode_version: 184
`

**Comment by vit9696** [comment]
Sorry, please use this one. Also, please use [three backticks](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) for code blocks on separate lines.
```
Data: <XX XX XX XX 00 00 00 00 00 00 00 08 00 00 00 00> 
Mask: <FF FF FF FF 00 00 00 00 00 00 00 08 00 00 00 00>
```

**Comment by davisinfo** [comment]
Good, the features are the same now and docker pull also works. The only difference now is the microcode version.

```
diff machdep-nocpuid2.txt machdep-fakecpuid4.txt
22c22
< machdep.cpu.microcode_version: 198
---
> machdep.cpu.microcode_version: 184
61,62c61,62
```

**Comment by vit9696** [comment]
Good, I will reopen this for tracking OSXSAVE workaround. As for Microcode version, just update your BIOS.
