### ISSUE TITLE
Aquantia AQC107 Ethernet Card Not Working in Big Sur (but works in Catalina)

### ISSUE THREAD

**Issue by dehjomz** [acidanthera/bugtracker#1036]
Not sure if there’s a problem with Opencore or Big Sur. But the issue I’m having is that an Aquantia AQC107 pcie 10gbps Ethernet card with device id 0xd107 is not loading on beta 1 or 2 of Big Sur using the latest compiled opencore beta 0.6.0 from master. This card works in Catalina without any patches. Flawlessly. However, I have another Aquantia AQC107 card  in a thunderbolt 3 enclosure (0x87b1) and it works with Big Sur on Opencore beta. 

I copied the Catalina kext to Big Sur beta install, rebuilt my kext caches and kernel collections but the Aquantia driver refuses to load for the pcie card. 

Some Other users have reported similar problems. Perhaps Opencore developers can take a look ?? Perhaps there’s a lilu plugin that might work?? Or an issue with how the pcie card is initialized? I don’t know where to start, or if it’s even an Opencore issue (it might be an Apple issue) but I just wanted to flag this here.

**Comment by Andrey1970AppleLife** [comment]
Address to the vendor of yours Ethernet Card or Apple.

**Comment by Pavo-IM** [comment]
@dehjomz Here is the patch you need for BigSur beta 3.
```
<dict>
                <key>Base</key>
		<string></string>
		<key>Comment</key>
		<string>Aquantia</string>
		<key>Count</key>
		<integer>1</integer>
		<key>Enabled</key>
		<true/>
		<key>Find</key>
		<data>D4TAAgAA</data>
		<key>Identifier</key>
		<string>com.apple.driver.AppleEthernetAquantiaAqtion</string>
		<key>Limit</key>
		<integer>0</integer>
		<key>Mask</key>
		<data></data>
		<key>MaxKernel</key>
		<string></string>
		<key>MinKernel</key>
		<string>20.0.0﻿</string>
		<key>Replace</key>
		<data>Zg8fRAAA</data>
		<key>ReplaceMask</key>
		<data></data>
		<key>Skip</key>
		<integer>0</integer>
</dict>
```

**Comment by dehjomz** [comment]
Beautiful.  Much more helpful than the dismissive invalid label.

**Comment by PMheart** [comment]
Super delayed response: I hope this would be resolved by the `ForceAquantiaEthernet` quirk.
