### ISSUE TITLE
1366X768 HD4000 screen fix

### ISSUE THREAD

**Issue by LocTran016** [acidanthera/bugtracker#1037]
Excuse me. I'm installing hackintosh on my DELL INSPIRON 3421 (MacOS Catalina 10.15.5 with OC 0.5.9 DEBUG) and I've suffered this for a long time because my laptop only have FB memory size=8mb so there is a way to modify the Capri framebuffer kext  in oder to modify the FB memory size from 16MB to 8MB for fixing  infamous screen garble when shutting down. There is a way to fix that: https://osxlatitude.com/forums/topic/11004-e6230-upgrade-to-mojave-has-anyone-had-success/page/2/?tab=comments#comment-90011 (I've get this from a man in Insanelymac.com) but it's for Clover but I think it may work on Opencore, too (just change something in the config.plist to patch that Capri frambuffer kext so I think there's still a use for that in Kernel->Patch) so I think that if it's possible, can you add it as a help for other people in your Troubleshooting page and in the sample.plist as well. Anyway, thanks a lot for reading my message

 
![DSC04356](https://user-images.githubusercontent.com/64778285/87228704-d3ba6280-c357-11ea-9f86-ca17d38a8609.JPG)
![DSC04354](https://user-images.githubusercontent.com/64778285/87228708-d61cbc80-c357-11ea-9f8d-2af375aca6aa.JPG)
![DSC04355](https://user-images.githubusercontent.com/64778285/87228710-d74de980-c357-11ea-8f78-38c27b469201.JPG)

**Comment by Andrey1970AppleLife** [comment]
Write to https://github.com/dortania/bugtracker/issues
