### ISSUE TITLE
Panic during boot with SuperIO chip issue (NVisen Y-MU01)

### ISSUE THREAD

**Issue by Bradamante3D** [acidanthera/bugtracker#1038]
Not sure if this is an issue with OpenCore (relatively new hackintosher here) but since I don't see it documented [here](https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/troubleshooting.html) I guess it it one. The hardware in question is a NVisen Y-MU01, which is a popular chinese NUC (Intel i5-8265U). The only good Google result I get for this log error is [here](https://www.insanelymac.com/forum/topic/335292-virtualsmc-%E2%80%94-smc-emulator/?do=findComment&comment=2669626). Lilu, WhateverGreen etc. are used in recent versions.

The changelog for v1.1.1 of OpenCore says:
* Fixed SMCSuperIO crashes with unsupported chips
* SMCSuperIO detected chip name to ioreg

so maybe they are using another SuperIO chip that OpenCore or VirtualSMC does not support? If I remove SMCProcessor.kext and SMCSuperIO.kext the boot sequence stops at the line above (about the Broadcom WLAN) the SuperIO problem.

I originally bought the NUC with macOS Catalina pre-installed and there macOS was working using Clover and VirtualSMC and a rather messy Clover folder. If needed I could upload that EFI folder for comparison.

[20200710_CPUZ_NVisen.txt](https://github.com/acidanthera/bugtracker/files/4907482/20200710_CPUZ_NVisen.txt)
[20200710_NVisen_EFI.zip](https://github.com/acidanthera/bugtracker/files/4907483/20200710_NVisen_EFI.zip)
![IMG_20200710_231518](https://user-images.githubusercontent.com/19214190/87231804-802d3080-c3ba-11ea-9e54-b4a35aaf6232.jpg)

**Comment by naveenkrdy** [comment]
hi !
thats not a panic.
if you are wondering why you are stuck at that point then its mostly due to either EC or RTC.
counterfiet your EC and refer SSDT-AWAC.
