### ISSUE TITLE
MacOSbigsur beta2(dw1560wifi)

### ISSUE THREAD

**Issue by Mitsukata** [acidanthera/bugtracker#1039]
Dear develops,
       Thanks for your wonderful work!DW1560&Bcm4352Wireless Network Adapter can't be driven by the latest kexts(lilu-1.4.6-debug&airportbrcmfixup-2.0.8-debug).I have downloaded the recent origional code in your repositories and compiled yesterday(Opencore bootloader 0.6.0beta).I have attempted to drive my hardware but it is still not working.  Here I have some questions as follow lists.

#1.Boot-args(-brcmfxbeta,brcmfx-driver=0|1|2|3) was added in nvram list,pci bus was also  added in device properties.Config.plist was edited by propertree !

AAPL,slot-name Internal@0,28,5/0,0 ; device_type Network controller;model BCM4352 802.11ac Wireless Network Adapter.

#2.Installation types：AirportBrcmFixup+FakePCIID+FakePCIID_Broadcom_WiFi.kext.

Forge other Bcm Wireless device.

1.Above-mentioned two methods is not working in Mac OS bigsur beta 2(20A4300b),but bluetooth is normal(BrcmBluetoothinjector+BrcmFirmwareData).Despite the kernel AirportBrcmFixup is also loaded in system,wireless network is still missing, airdrop isn't working!

2.In the old version[Mac OS Catalina(10.15.5)],DW1560 has been driven very well in the ordinary kexts(AirportBrcmFixup+BrcmBrcmPatchRAM3+BrcmBluetoothinjector+BrcmFirmwareData)

Regards, Yours Sincerely!
![Screen Shot 2020-07-12 at 7 43 35 PM](https://user-images.githubusercontent.com/61998615/87248201-c05be400-c48a-11ea-8874-31c0cc691eef.png)
![Screen Shot 2020-07-12 at 7 43 56 PM](https://user-images.githubusercontent.com/61998615/87248203-c4880180-c48a-11ea-892a-bc33289c9ca1.png)

**Comment by Andrey1970AppleLife** [comment]
Build kext from master.

**Comment by vit9696** [comment]
New airport is not a single kext. Watch out what you inject. See more details in https://github.com/acidanthera/bugtracker/issues/1021.

**Comment by Mitsukata** [comment]
Thanks!My wifi Wireless Network Adapter is identification.
