### ISSUE TITLE
BigSur Recovery does not start after selection in Menue

### ISSUE THREAD

**Issue by schmitzkatze** [acidanthera/bugtracker#1040]
After choosing in OC 0.60 Menu Recovery BigSur 10.16, the Main Menu appears again without starting the Recover Mode!
Error Message in Top of Display (OCB: LoadImage failed)

I have attached a log file

[opencore-2020-07-12-132347.txt](https://github.com/acidanthera/bugtracker/files/4908705/opencore-2020-07-12-132347.txt)

[opencore-2020-07-12-121851.txt](https://github.com/acidanthera/bugtracker/files/4908706/opencore-2020-07-12-121851.txt)

**Comment by Andrey1970AppleLife** [comment]
JumpstartHotPlug = YES

**Comment by schmitzkatze** [comment]
Thanks now is working!
