### ISSUE TITLE
Apple boot logo glitch

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#1041]
Hi ! 
i am experiencing a apple logo glitch while booting.
As soon as the apple boot loading bar reaches 50%, the whole apple logo along with the progressbar glitches.
![IMG_0700](https://user-images.githubusercontent.com/18463250/87253671-aaeeb600-c49a-11ea-8044-a78e2525993e.jpg)

[bootlog.txt](https://github.com/acidanthera/bugtracker/files/4909133/bootlog.txt)

macOS 10.15.5
Dell XPS 7590 FHD
i7-9750h
UHD 630

Regards !

EDIT : 
Upon some googling found this :
https://github.com/CloverHackyColor/CloverBootloader/blob/d36f1ae23ad1683685f0e0800dd26740a277871d/rEFIt_UEFI/Platform/kext_patcher.cpp#L1253

**Comment by Andrey1970AppleLife** [comment]
WEG fixes 8 apple glitches. 
Rebuild kext cache.

**Comment by naveenkrdy** [comment]
@Andrey1970AppleLife Tried that but still same.
Even rebuilt the dyld cache.
I am on the latest whatevergreen and lilu from master but still no luck.

**Comment by vit9696** [comment]
WEG fixes this, but there is indeed a short glitch for a frame or two, which in some cases is visible. Sometimes it happens on Apple HW too.

**Comment by naveenkrdy** [comment]
@vit9696 i read online that enabling CSM / Legacy fixes it at some extent but my laptop doesnt have legacy. so thats bummer  !
so there is no way to fix it completely through weg ?

**Comment by asgmeonerandom** [comment]
read the guide https://dortania.github.io/ it may help fix it
