### ISSUE TITLE
Make BootPicker set 'Boot0080' in '/nvram.plist'

### ISSUE THREAD

**Issue by kommtzeitkonrad** [acidanthera/bugtracker#1043]
Booting a system without hardware NVRAM with the help of `OpenDuetPkg` while having `AllowSetDefault`, `LegacyEnable`, `LegacyOverwrite` and `WriteFlash` set to `YES`.

When using Startup Disk preference pane, boot entries are set via `efi-boot-device`, `efi-boot-device-data` and `Boot0080` variables in `EFI_GLOBAL_VARIABLE_GUID`. These are then stored in `/nvram.plist` with the help of `LogoutHook` and boot entries are correctly auto-selected after reboot.

Pressing `CTRL+Enter` in Open Core boot picker only sets `Boot0080` variable, which is enough, but this will only work across reboots when booting macOS equipped with installed `LogoutHook`. The information is obviously lost when booting any other OS.

It would be nice to have Open Core boot picker immediately updating `Boot0080` in `/nvram.plist` when selecting any entry while pressing `CTRL+Enter`.

**Comment by vit9696** [comment]
I will add the removal of nvram.plist via Reset MVRAM here as well. We will unlikely work on the feature, however.

**Comment by huytbt** [comment]
Hi @vit9696,

I'm using Emulated NVRAM. I having issue Boot Picker screen does not select default disk.
I have two disks: CatalinaHD and preboot (This is Big Sur), I'm using Startup Disk preference pane. I select disk "CatalinaHD" and Restart. But Boot Picker always select preboot.
Could you please support me fix this.

Thanks,
Huy

**Comment by kommtzeitkonrad** [comment]
> Hi @vit9696,
> 
> I'm using Emulated NVRAM. I having issue Boot Picker screen does not select default disk.
> I have two disks: CatalinaHD and preboot (This is Big Sur), I'm using Startup Disk preference pane. I select disk "CatalinaHD" and Restart. But Boot Picker always select preboot.
> Could you please support me fix this.
> 
> Thanks,
> Huy

https://dortania.github.io/OpenCore-Post-Install/misc/nvram.html#enabling-emulated-nvram-with-a-nvram-plist

**Comment by huytbt** [comment]
Hi @kommtzeitkonrad,
I have enabled emulated nvram follow the guide. Then I saw Boot0080 exists in nvram.plist.
But it still has issue.
Thanks,

**Comment by huytbt** [comment]
Hi @kommtzeitkonrad,
This is my OC config https://github.com/huytbt/Hackintosh-HP-Z600-OpenCore/blob/master/EFI/OC/config.plist

**Comment by vit9696** [comment]
Implemented in master not so long ago.
