### ISSUE TITLE
Is it posible to disabling Intel HDMI Audio Entirely

### ISSUE THREAD

**Issue by valinor61** [acidanthera/bugtracker#1044]
Hi, I have Asus G531GT gaming laptop and it's HDMI output directly connected with Nvidia Graphics. There is no way to fix HDMI but HDMI audio still recognizing by macos in some boots. It can clearly shown in IOReg. I am not using any DSDT find and replace patch or SSDT for audio. Is there a flag in AppleALC or some property in opencore to disable intel hdmi audio entirely. I can't find a proper example for my case. 
I already tried -igfxnohdmi and disable-hdmi-patches bootargs but they didn't help
[IOREG Working Audio.zip](https://github.com/acidanthera/bugtracker/files/4915953/MacBook.Pro.Working.Audio.zip)
[IOREG Unrecognized Audio.zip](https://github.com/acidanthera/bugtracker/files/4915954/MacBook.Pro.Unrecognized.Audio.zip)
[OC.zip](https://github.com/acidanthera/bugtracker/files/4915955/OC.zip)

**Comment by Andrey1970AppleLife** [comment]
Only bios mod. https://applelife.ru/posts/725924
