### ISSUE TITLE
PowerTimeoutKernelPanic=true do not work properly in Big Sur 10.16

### ISSUE THREAD

**Issue by ameenjuz** [acidanthera/bugtracker#1045]
in Catalina PowerTimeoutKernelPanic work fine but in Big Sur sometime my laptop shutdown automatcally  
or get hang due to unproperly changing power
PowerTimeoutKernelPanic break in Big Sur 10.16
i get this screen shot blow
i hope that dev will be fixed PowerTimeoutKernelPanic
sorry for my poor english
![Screen Shot 2020-07-14 at 12 04 39 AM](https://user-images.githubusercontent.com/21066935/87376899-7d863300-c594-11ea-982f-7b0ae47d780f.jpg)

**Comment by Andrey1970AppleLife** [comment]
Check equivalent boot-arg: setpowerstate_panic=0

**Comment by vit9696** [comment]
Interesting note, common issue for this panic on IGPUs could be outdated BIOS and/or HDMI type on non-HDMI connector (e.g. DVI).

**Comment by ameenjuz** [comment]
@Andrey1970AppleLife @vit9696 thanks for reply
temporarily solution when i uncheck put hard to sleep when possible from system preference energy saver then problem is gone
 when i tick put hard to sleep when possible from system preference energy saver then problem reappear
I think that this PowerTimeoutKernelPanic is not work properly in big sur 10.16

**Comment by vit9696** [comment]
Closing as not reproducible.
