### ISSUE TITLE
Opencore guide bug

### ISSUE THREAD

**Issue by LocTran016** [acidanthera/bugtracker#1046]
Excuse me, I don't know why the link here is dead or it maybe shut down. If it is possible, can you please update here: https://github.com/dortania/OpenCore-Desktop-Guide/blob/master/clover-conversion/Clover-config.md. Many thanks for reading my message again

![image](https://user-images.githubusercontent.com/64778285/87514187-b07d0500-c62e-11ea-9b0f-6dda4d6d6ba0.png)

**Comment by vit9696** [comment]
Hi! SmBios header is [here](https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleSmBios.h) now. We do not maintain Dortania guides, but I will ping the right people. Please create such issues [here](https://github.com/dortania/bugtracker) next time.

**Comment by LocTran016** [comment]
Thanks a lot for giving me the direction and sorry really much about putting my issues in wrong place. Have a nice day!
