### ISSUE TITLE
AppleALC panics when alc-delay is used.

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#1048]
while trying to figure out why my sound doesn't work on cold boot and sometimes on warm reboot. i tried the `alc-delay` property to delay HDAController startup and it makes the AppleALC panics upon boot.

`alc-delay | number | 1000`

[panic.txt](https://github.com/acidanthera/bugtracker/files/4933342/panic.txt)

Dell XPS 7590 FHD
ALC 298 (0x8086A348)
10.15.6

Apart from this i observed one more thing is that, whenever i add the below kextpatch entry to my OC. my sound always works without any issue. so does this mean i do need to delay the hda controller ? or this kext patch needs to be added to Controllers.plist ?
```
Kext: com.apple.driver.AppleHDAController
Find: 709D0000
Replace: 48A30000 
```

Regards !

**Comment by Andrey1970AppleLife** [comment]
It is nonsense:
![Снимок экрана 2020-07-17 в 17 47 54](https://user-images.githubusercontent.com/17758753/87799616-1f887280-c856-11ea-937e-42cefce9c5b4.png)

**Comment by naveenkrdy** [comment]
> It is nonsense:
> ![Снимок экрана 2020-07-17 в 17 47 54](https://user-images.githubusercontent.com/17758753/87799616-1f887280-c856-11ea-937e-42cefce9c5b4.png)

i am using MacBookPro16,1 smbios 
![Screen Shot 2020-07-17 at 9 35 32 PM](https://user-images.githubusercontent.com/18463250/87807228-a3058c00-c875-11ea-883d-dd26168c5c1b.png)
so not sure why it is showing MacBookPro1. might be typo in smbios database in oc ?

**Comment by naveenkrdy** [comment]
UPDATE :

I fixed the wrong smbios issue by enabling `CustomSMBIOSGuid` and setting `UpdateSMBIOSMode` to `Custom`.
now it shows MacBookPro16,1.

Gonna retry alc-delay and share the results.

**Comment by naveenkrdy** [comment]
Update 2 :
`alc-delay` property now doesnt seem to cause panic anymore after doing the above and also sound works fine after delaying the HDAController with 200ms.

Closing issue as resolved.
Thanks !
