### ISSUE TITLE
Assert error "FileName != ((void *) 0)"

### ISSUE THREAD

**Issue by camielverdult** [acidanthera/bugtracker#1052]
Hi,

I am trying to boot the 10.15.6 installer using the debug release of OpenCore 0.5.9 as downloaded from the repo. When trying to launch OpenCore, I get debug output as expected but no output after. Monitor stays blank and the boot picker does not display. I have tried:
- HFSPlus.efi instead of VboxHFS.efi
- DisableWatchdog Disabled and Enabled (see logs: Watchdog Status 1 & 0, made no difference)

This is the last line that appears in my logs:

```
25:869 00:118 ASSERT [OpenCore] /Users/travis/build/acidanthera/OpenCorePkg/UDK/OpenCorePkg/Library/OcFileLib/OpenFile.c(41): FileName != ((void *) 0)
```

I asked @Download-Fritz about this in the Hackintosh Discord and he told me to open an issue on the bugtracker. Here is the EFI and logs:
[opencore-2020-07-21-124701.txt](https://github.com/acidanthera/bugtracker/files/4953602/opencore-2020-07-21-124701.txt)

[opencore-2020-07-21-123008.txt](https://github.com/acidanthera/bugtracker/files/4953605/opencore-2020-07-21-123008.txt)

[wtf.zip](https://github.com/acidanthera/bugtracker/files/4953601/wtf.zip)

This is on the following hardware:
Asus X99 Rampage V Extreme
Intel Core i7-5820K
32GB RAM
Asus Strix Vega 64 Gaming
Samsung 960 NVMe SSD

**Comment by vit9696** [comment]
Just in case, please reproduce it with master version of OpenCore.

**Comment by camielverdult** [comment]
@vit9696 Hi vit, this is the debug version downloaded from the master branch of the OpenCorePkg repo, I did not compile it myself/got it from 3rd party/etc.

**Comment by camielverdult** [comment]
Got output now, just have to fix some of the other configuration issues I have. Thank you for your help!

[opencore-2020-07-21-132339.txt](https://github.com/acidanthera/bugtracker/files/4953739/opencore-2020-07-21-132339.txt)
