### ISSUE TITLE
OCXmlLib should support tags in comments

### ISSUE THREAD

**Issue by 07151129** [acidanthera/bugtracker#1053]
OCXmlLib misinterprets XML containing constructs like

```
<!-- <tag ... -->
```

as malformed. This is obviously valid XML, and supporting it would make config editing more convenient.

**Comment by vit9696** [comment]
The proposed example will not be enough to trigger the bug, as the current implementation does not care about tag opening brace (`<`) but rather considers tag closing brace (`>`) the end of the comment:

```xml
<!-- whatever > no longer considered comment -->
```

**Comment by wsy** [comment]
Hi, I'm using OpenCore 0.6.0.
I encountered this bug with the following fragment. OpenCore told me my config.plist is malformed and refused to boot.
``` xml
<key>AAPL,ig-platform-id</key>
<!-- 0x01660003 -->
<!-- <data>AAAAAA==</data> -->
<!-- 0x01660009 -->
<data>AAAAAA==</data>
```

**Comment by wsy** [comment]
@vit9696 Hi, please have a look. I tried above example I provided in 0.6.1.
OpenCore 0.6.1 still fails to parse config.plist with such comment inside.
``` xml
<key>AAPL,ig-platform-id</key>
<!-- 0x01660003 -->
<!-- <data>AAAAAA==</data> -->
<!-- 0x01660009 -->
<data>AAAAAA==</data>
```
