### ISSUE TITLE
BrcmPatchRAM3.kext Kernel Panic / Instant reboot on Catalina 10.15.6

### ISSUE THREAD

**Issue by Sniki** [acidanthera/bugtracker#1054]
At early 2-5% Apple Boot Logo Progress Bar the system will kernel panic/Instant reboot due to BrcmPatchRam3.kext on macOS Catalina 10.15.6

After disabling the kext the system does boot fine.

Tested on both DW1560 and DW1820A Cards.

Here is the log i got when i booted, let me know if you need other logs.

```
0xffffff8116a33830 : 0xffffff801491a65d 
0xffffff8116a33880 : 0xffffff8014a54a75 
0xffffff8116a338c0 : 0xffffff8014a465fe 
0xffffff8116a33910 : 0xffffff80148c0a40 
0xffffff8116a33930 : 0xffffff8014919d27 
0xffffff8116a33a30 : 0xffffff801491a117 
0xffffff8116a33a80 : 0xffffff80150c1abc 
0xffffff8116a33af0 : 0xffffff8014a469aa 
0xffffff8116a33c70 : 0xffffff8014a466a8 
0xffffff8116a33cc0 : 0xffffff80148c0a40 
0xffffff8116a33ce0 : 0xffffff7f9712aa31 
0xffffff8116a33df0 : 0xffffff7f9712a96b 
0xffffff8116a33e40 : 0xffffff8015006dda 
0xffffff8116a33ef0 : 0xffffff801500649e 
0xffffff8116a33f50 : 0xffffff8015008c56 
0xffffff8116a33fa0 : 0xffffff80148c013e 
      Kernel Extensions in backtrace:
         as.acidanthera.BrcmPatchRAM3(2.5.3)[8250806A-3B84-3593-93AB-48E1703639A2]@0xffffff7f9712a000->0xffffff7f9712dfff
            dependency: as.acidanthera.BrcmFirmwareStore(2.5.3)[5E3D354B-F342-3FE2-B34C-0BA861FF7E63]@0xffffff7f97137000
            dependency: com.apple.iokit.IOUSBHostFamily(1.2)[46B74D4B-F96A-3C3D-9373-CA956389608C]@0xffffff7f9557c000

BSD process name corresponding to current thread: kernel_task

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
Kernel UUID: 783946EA-6F11-3647-BF90-787AEA14B954
Kernel slide:     0x0000000014600000
Kernel text base: 0xffffff8014800000
__HIB  text base: 0xffffff8014700000
System model name: MacBookPro11,1 (Mac-189A3D4F975D5FFC)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 1246906632
```

**Comment by vit9696** [comment]
Unclear without keepsyms=1 and debug build. Resubmit logs for reopen.

**Comment by Sniki** [comment]
> Unclear without keepsyms=1 and debug build. Resubmit logs for reopen.

Any other logs that i need to collect, any specific command/app ?

Here is what i got with keepsyms=1 and debug kexts from the notification that appears after login:

```
panic(cpu 3 caller 0xffffff8014c469aa): Kernel trap at 0xffffff7f98d3f9b3, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000014800000, CR3: 0x000000001a968000, CR4: 0x00000000001626e0
RAX: 0x0000000014800000, RBX: 0xffffff80293b9180, RCX: 0x0000000000000000, RDX: 0x0000000001000000
RSP: 0xffffff81209cbdd0, RBP: 0xffffff81209cbdf0, RSI: 0xffffff80286c4f60, RDI: 0x0000000000000000
R8:  0x0000000000000001, R9:  0x0000000000000008, R10: 0x0000000000000326, R11: 0xffffff80290dbac0
R12: 0xffffff80296b6b98, R13: 0xffffff80290d0b40, R14: 0xffffff80296b6b00, R15: 0xffffff80296b6b00
RFL: 0x0000000000010286, RIP: 0xffffff7f98d3f9b3, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000014800000, Error code: 0x0000000000000000, Fault CPU: 0x3, PL: 0, VF: 1

Backtrace (CPU 3), Frame : Return Address
0xffffff81209cb830 : 0xffffff8014b1a65d mach_kernel : _handle_debugger_trap + 0x49d
0xffffff81209cb880 : 0xffffff8014c54a75 mach_kernel : _kdp_i386_trap + 0x155
0xffffff81209cb8c0 : 0xffffff8014c465fe mach_kernel : _kernel_trap + 0x4ee
0xffffff81209cb910 : 0xffffff8014ac0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff81209cb930 : 0xffffff8014b19d27 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff81209cba30 : 0xffffff8014b1a117 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff81209cba80 : 0xffffff80152c1abc mach_kernel : _panic + 0x54
0xffffff81209cbaf0 : 0xffffff8014c469aa mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff81209cbc70 : 0xffffff8014c466a8 mach_kernel : _kernel_trap + 0x598
0xffffff81209cbcc0 : 0xffffff8014ac0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff81209cbce0 : 0xffffff7f98d3f9b3 as.acidanthera.BrcmPatchRAM3 : __ZN13BrcmPatchRAM316getFirmwareStoreEv + 0x3f
0xffffff81209cbdf0 : 0xffffff7f98d3f8ee as.acidanthera.BrcmPatchRAM3 : __ZN13BrcmPatchRAM35probeEP9IOServicePi + 0x1c0
0xffffff81209cbe40 : 0xffffff8015206dda mach_kernel : __ZN9IOService15probeCandidatesEP12OSOrderedSet + 0x7aa
0xffffff81209cbef0 : 0xffffff801520649e mach_kernel : __ZN9IOService14doServiceMatchEj + 0x2de
0xffffff81209cbf50 : 0xffffff8015208c56 mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x186
0xffffff81209cbfa0 : 0xffffff8014ac013e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         as.acidanthera.BrcmPatchRAM3(2.5.3)[39BC3C73-F279-3DA1-B294-CBE2D3039C2C]@0xffffff7f98d3e000->0xffffff7f98d4bfff
            dependency: as.acidanthera.BrcmFirmwareStore(2.5.3)[310E3D9E-2369-300E-9FFD-85507A17730D]@0xffffff7f98d4e000
            dependency: com.apple.iokit.IOUSBHostFamily(1.2)[46B74D4B-F96A-3C3D-9373-CA956389608C]@0xffffff7f95c93000

BSD process name corresponding to current thread: kernel_task
Boot args: -v keepsyms=1 -rtsx_mimic_linux rtsx_timeout_shift=2 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
Kernel UUID: 783946EA-6F11-3647-BF90-787AEA14B954
Kernel slide:     0x0000000014800000
Kernel text base: 0xffffff8014a00000
__HIB  text base: 0xffffff8014900000
System model name: MacBookPro11,1 (Mac-189A3D4F975D5FFC)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization

System uptime in nanoseconds: 2598158069

```

**Comment by vit9696** [comment]
cc @lvs1974

**Comment by kommtzeitkonrad** [comment]
No problem over here with DW1550 @ 10.15.6.

**Comment by Sniki** [comment]
> No problem over here with DW1550 @ 10.15.6.

Thanks but if you read the description, you can notice that the issue is with DW1560 and DW1820A

**Comment by kommtzeitkonrad** [comment]
> 
> 
> > No problem over here with DW1550 @ 10.15.6.
> 
> Thanks but if you read the description, you can notice that the issue is with DW1560 and DW1820A

Yeah, since DW1550 and DW1560 tend to have [more](http://en.techinfodepot.shoutwiki.com/wiki/Dell_Wireless_1550_(DW1550)) or [less](http://en.techinfodepot.shoutwiki.com/wiki/Dell_Wireless_1560_(DW1560)) similar chipsets, I thought I let you know.

**Comment by Sniki** [comment]
> > > No problem over here with DW1550 @ 10.15.6.
> > 
> > 
> > Thanks but if you read the description, you can notice that the issue is with DW1560 and DW1820A
> 
> Yeah, since DW1550 and DW1560 tend to have [more](http://en.techinfodepot.shoutwiki.com/wiki/Dell_Wireless_1550_(DW1550)) or [less](http://en.techinfodepot.shoutwiki.com/wiki/Dell_Wireless_1560_(DW1560)) similar chipsets, I thought I let you know.

Thanks again but i am very well aware of similarities,
It’s not just me, i have many other reports on our forum about same problem on similar hardware like mine.
I have this problem everytime posting an issue over here or on “other” forums, please let the appropriate people i contacted handle the issue and let me get my answer from them.
There is a reason why i reported an issue and why i did here and not somewhere else.

Thanks.

**Comment by lvs1974** [comment]
@Sniki, please try attached kext: 
[Debug.zip](https://github.com/acidanthera/bugtracker/files/4958558/Debug.zip)
If there is no panic, please attach boot log (add boot-arg msgbuf=1048576 and reboot): sudo dmesg > dmesg.txt

**Comment by Sniki** [comment]
@lvs1974 will do after work as i am in GMT+1 time zone.
Will test after i go home and provide the logs.

Thanks a lot !

**Comment by Sniki** [comment]
@lvs1974 Kernel Panic still occurs, here is the new log:

```
panic(cpu 2 caller 0xffffff801ee469aa): Kernel trap at 0xffffff7fa2f3fa8f, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x000000001ea00000, CR3: 0x0000000024b7a000, CR4: 0x00000000001626e0
RAX: 0x000000001ea00000, RBX: 0xffffff8033cab640, RCX: 0x0000000000000000, RDX: 0x0000000001000000
RSP: 0xffffff812ac73d80, RBP: 0xffffff812ac73da0, RSI: 0xffffff803295f9f0, RDI: 0x0000000000000000
R8:  0xffffff80339d9000, R9:  0x000000000000032f, R10: 0x000000000000032c, R11: 0xffffff80336979e0
R12: 0x0000000000000000, R13: 0x0000000000000000, R14: 0xffffff803396dbe0, R15: 0xffffff8033b7a700
RFL: 0x0000000000010282, RIP: 0xffffff7fa2f3fa8f, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x000000001ea00000, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 1

Backtrace (CPU 2), Frame : Return Address
0xffffff812ac737e0 : 0xffffff801ed1a65d mach_kernel : _handle_debugger_trap + 0x49d
0xffffff812ac73830 : 0xffffff801ee54a75 mach_kernel : _kdp_i386_trap + 0x155
0xffffff812ac73870 : 0xffffff801ee465fe mach_kernel : _kernel_trap + 0x4ee
0xffffff812ac738c0 : 0xffffff801ecc0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff812ac738e0 : 0xffffff801ed19d27 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff812ac739e0 : 0xffffff801ed1a117 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff812ac73a30 : 0xffffff801f4c1abc mach_kernel : _panic + 0x54
0xffffff812ac73aa0 : 0xffffff801ee469aa mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff812ac73c20 : 0xffffff801ee466a8 mach_kernel : _kernel_trap + 0x598
0xffffff812ac73c70 : 0xffffff801ecc0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff812ac73c90 : 0xffffff7fa2f3fa8f as.acidanthera.BrcmPatchRAM3 : __ZN13BrcmPatchRAM316getFirmwareStoreEv + 0x7d
0xffffff812ac73da0 : 0xffffff7fa2f3f7be as.acidanthera.BrcmPatchRAM3 : __ZN13BrcmPatchRAM35startEP9IOService + 0x56
0xffffff812ac73de0 : 0xffffff801f4075c6 mach_kernel : __ZN9IOService14startCandidateEPS_ + 0xf6
0xffffff812ac73e40 : 0xffffff801f407101 mach_kernel : __ZN9IOService15probeCandidatesEP12OSOrderedSet + 0xad1
0xffffff812ac73ef0 : 0xffffff801f40649e mach_kernel : __ZN9IOService14doServiceMatchEj + 0x2de
0xffffff812ac73f50 : 0xffffff801f408c56 mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x186
0xffffff812ac73fa0 : 0xffffff801ecc013e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         as.acidanthera.BrcmPatchRAM3(2.5.3)[A8924FAB-89D0-3A23-A8E4-E1D0497CC6FA]@0xffffff7fa2f3e000->0xffffff7fa2f4bfff
            dependency: as.acidanthera.BrcmFirmwareStore(2.5.3)[FF8CA904-B744-3398-9F1A-467E7E5C7269]@0xffffff7fa2f53000
            dependency: com.apple.iokit.IOUSBHostFamily(1.2)[46B74D4B-F96A-3C3D-9373-CA956389608C]@0xffffff7f9fe93000

BSD process name corresponding to current thread: kernel_task
Boot args: -v keepsyms=1 -rtsx_mimic_linux rtsx_timeout_shift=2 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
Kernel UUID: 783946EA-6F11-3647-BF90-787AEA14B954
Kernel slide:     0x000000001ea00000
Kernel text base: 0xffffff801ec00000
__HIB  text base: 0xffffff801eb00000
System model name: MacBookPro11,1 (Mac-189A3D4F975D5FFC)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization

System uptime in nanoseconds: 2674146212

```

**Comment by lvs1974** [comment]
```
__text:0000000000001A7F                 test    rax, rax
__text:0000000000001A82                 jz      loc_1B10
; mFirmwareStore = OSDynamicCast(BrcmFirmwareStore, tmpStore);
__text:0000000000001A88                 mov     rax, cs:off_5010
__text:0000000000001A8F                 mov     rsi, [rax]     ;  __ZN13BrcmPatchRAM316getFirmwareStoreEv + 0x7d
__text:0000000000001A92                 mov     rdi, r14
```

RAX: 0x000000001ea00000
off_5010        dq offset __ZN17BrcmFirmwareStore9metaClassE

UNDEF:0000000000006188 ; BrcmFirmwareStore::metaClass
UNDEF:0000000000006188                 extrn __ZN17BrcmFirmwareStore9metaClassE:qword

Pointer stored in off_5010 is wrong for some reason.

@Sniki, did you replace all kexts Brcm*.kext in your EFI folder with new ones from Debug.zip?
Can you show me a config.plist?

**Comment by Sniki** [comment]
Yes, will upload you the entire EFI with 1 more report, give 5 min

**Comment by Sniki** [comment]
@lvs1974 here is the use case scenario, i have the same efi on usb stick with just BrcmPatchRAM3.kext Disabled so after laptop does panic, i boot from the USB EFI to collect the logs.

Here is one more log, to re-assure i download the debug.zip again and replaced the 3 kexts:
- BrcmPatchRAM3.kext
- BrcmFirmwareData.kext
- BrcmBluetoothInjector.kext

Rebooted and same scenario again.

Here is the new log and also EFI attached with removed Resources/Audio for size reduction and generic personal infos removed from PlatformInfo.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4962790/EFI.zip)





```
panic(cpu 2 caller 0xffffff800b2469aa): Kernel trap at 0xffffff7f8f33fa8f, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x000000000ae00000, CR3: 0x0000000010f7a000, CR4: 0x00000000001626e0
RAX: 0x000000000ae00000, RBX: 0xffffff801fa33140, RCX: 0x0000000000000000, RDX: 0x0000000001000000
RSP: 0xffffff8117fbbd80, RBP: 0xffffff8117fbbda0, RSI: 0xffffff801ebff8c0, RDI: 0x0000000000000000
R8:  0xffffff801f78c000, R9:  0x000000000000031e, R10: 0x000000000000031d, R11: 0xffffff801f4495c0
R12: 0x0000000000000000, R13: 0x0000000000000000, R14: 0xffffff801f721f00, R15: 0xffffff801fa28c00
RFL: 0x0000000000010282, RIP: 0xffffff7f8f33fa8f, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x000000000ae00000, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 1

Backtrace (CPU 2), Frame : Return Address
0xffffff8117fbb7e0 : 0xffffff800b11a65d mach_kernel : _handle_debugger_trap + 0x49d
0xffffff8117fbb830 : 0xffffff800b254a75 mach_kernel : _kdp_i386_trap + 0x155
0xffffff8117fbb870 : 0xffffff800b2465fe mach_kernel : _kernel_trap + 0x4ee
0xffffff8117fbb8c0 : 0xffffff800b0c0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff8117fbb8e0 : 0xffffff800b119d27 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff8117fbb9e0 : 0xffffff800b11a117 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff8117fbba30 : 0xffffff800b8c1abc mach_kernel : _panic + 0x54
0xffffff8117fbbaa0 : 0xffffff800b2469aa mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff8117fbbc20 : 0xffffff800b2466a8 mach_kernel : _kernel_trap + 0x598
0xffffff8117fbbc70 : 0xffffff800b0c0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff8117fbbc90 : 0xffffff7f8f33fa8f as.acidanthera.BrcmPatchRAM3 : __ZN13BrcmPatchRAM316getFirmwareStoreEv + 0x7d
0xffffff8117fbbda0 : 0xffffff7f8f33f7be as.acidanthera.BrcmPatchRAM3 : __ZN13BrcmPatchRAM35startEP9IOService + 0x56
0xffffff8117fbbde0 : 0xffffff800b8075c6 mach_kernel : __ZN9IOService14startCandidateEPS_ + 0xf6
0xffffff8117fbbe40 : 0xffffff800b807101 mach_kernel : __ZN9IOService15probeCandidatesEP12OSOrderedSet + 0xad1
0xffffff8117fbbef0 : 0xffffff800b80649e mach_kernel : __ZN9IOService14doServiceMatchEj + 0x2de
0xffffff8117fbbf50 : 0xffffff800b808c56 mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x186
0xffffff8117fbbfa0 : 0xffffff800b0c013e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         as.acidanthera.BrcmPatchRAM3(2.5.3)[A8924FAB-89D0-3A23-A8E4-E1D0497CC6FA]@0xffffff7f8f33e000->0xffffff7f8f34bfff
            dependency: as.acidanthera.BrcmFirmwareStore(2.5.3)[FF8CA904-B744-3398-9F1A-467E7E5C7269]@0xffffff7f8f353000
            dependency: com.apple.iokit.IOUSBHostFamily(1.2)[46B74D4B-F96A-3C3D-9373-CA956389608C]@0xffffff7f8c293000

BSD process name corresponding to current thread: kernel_task
Boot args: -v keepsyms=1 -rtsx_mimic_linux rtsx_timeout_shift=2 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
Kernel UUID: 783946EA-6F11-3647-BF90-787AEA14B954
Kernel slide:     0x000000000ae00000
Kernel text base: 0xffffff800b000000
__HIB  text base: 0xffffff800af00000
System model name: MacBookPro11,1 (Mac-189A3D4F975D5FFC)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization

System uptime in nanoseconds: 2635219873


```

**Comment by lvs1974** [comment]
@Sniki, thanks for files.
Could you change an order of kexts in config.plist?
BrcmFirmwareData, then BrcmBluetoothInjector, and after BrcmPatchRAM3?

**Comment by Mieze** [comment]
@Sniki I checked the code and couldn't find any reason why it should fail with 10.15.6 after having worked flawlessly before. That's why I assume that this is a link error. Please clean system caches (yes system caches, not kernel caches), reboot, recreate the kernel cache after that and check if it resolves the issue.

**Comment by lvs1974** [comment]
@Mieze, I also do not see any issues in the code. The only very strange possibility: could BrcmFirmwareData.kext be uploaded?

**Comment by Sniki** [comment]
@lvs1974 @Mieze 

Sorry for the trouble, i did both of your suggestions at once so one of the two or both together could've been the problem...

It is working fine now, Thanks a lot and sorry for your valuable time.
I spend 3-4 days of scratching my head why is it happening, it was working fine on my Lenovo ThinkPad T440S, the problem started on the X240 because i just created a clean USB Installer after 10.15.6 release and then thought the problem came up from that.

However, 1 assumption that i have and want to make sure if that could've been the problem:
I had the big sur on the other flash drive, it did kernel panic when i tried to boot installer and i just didn't bother more with it and ported the EFI that was on that USB to the new 10.15.6 USB Installer as it was up to date, However, before starting the 10.15.6 installer i did reset NVRAM and started 10.15.6 installer, as soon as i choosed the Installer at OpenCanopy screen, despite the ResetNVRAM done, it showed me the message before apple boot logo that system crashed .... and then installer started, and kept panicking the same way until i figured out after disabling BrcmPatchRAm3.kext that installer finally started.

Is there some sort of possibility that EFI messed up with Kernel Cache due to that Big Sur installer boot attempt ?

Also is this message normal at verbose boot and could it have something to do about it:
![IMG_0537](https://user-images.githubusercontent.com/30008333/88234211-e5b1d480-cc78-11ea-840c-74a864b26886.png)

**Comment by lvs1974** [comment]
@Sniki, you violated one very important requirement described in Configuration.pdf:
```
Add
Type: plist array
Failsafe: Empty
Description: Load selected kernel drivers from OC/Kexts directory.
Designed to be filled with plist dict values, describing each driver. See Add Properties section below. Kernel
driver load order follows the item order in the array, thus the dependencies should be written prior to their
consumers.
```

**Comment by Sniki** [comment]
> @Sniki, you violated one very important requirement described in Configuration.pdf:
> 
> ```
> 
> Add
> 
> Type: plist array
> 
> Failsafe: Empty
> 
> Description: Load selected kernel drivers from OC/Kexts directory.
> 
> Designed to be filled with plist dict values, describing each driver. See Add Properties section below. Kernel
> 
> driver load order follows the item order in the array, thus the dependencies should be written prior to their
> 
> consumers.
> 
> ```

So every satellite/plugin/injector kext should be first in order before the main kext. Something like this:

- SMCProcessor.kext
- SMCBatteryManager.kext
- SMCLightSensor.kext
- VirtualSMC.kext

I may have missed that paragraph.
Thanks for pointing it, what about the screenshot i attached, is that message ok or indicating other issue.
Not sure if it used to show up previously.

**Comment by lvs1974** [comment]
@Sniki, just have a look at OSBundleLibraries in Info.plist. If you see non-system libraries there, they should be loaded before this Kext!

**Comment by kommtzeitkonrad** [comment]
> So every satellite/plugin/injector kext should be first in order before the main kext. Something like this:
> 
> * SMCProcessor.kext
> * SMCBatteryManager.kext
> * SMCLightSensor.kext
> * VirtualSMC.kext

It's the other way around, since _the dependencies_ (`as.vit9696.VirtualSMC`) _should be written prior to their consumers_ (`SMC*.kext`). It's the same reason you put Lilu first, because probably most of your kexts depend on `as.vit9696.Lilu`. :-)

**Comment by Amrkamel1** [comment]
@Sniki  could you share your last working EFI, since i have same issue so i can compare whats the difference
