### ISSUE TITLE
Problem audio with AppleALC.kext, Realtek alc294

### ISSUE THREAD

**Issue by serpinu** [acidanthera/bugtracker#1055]
Hi, I have a problem with my Realtek alc294, I have try all layouts that supported but when I’ll try to listen music, I don’t’ feel anything from speaker, the logo of the spekaer is avaiable for change the volume but nothing happen. I’ll try all of command (for example alc=11)that I find in internet.. but without solution. I have hackintosh with Catalina on Asus rog strix with Intel 10750h with clover and the last applealc.kext installed.
Thanks for the help

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by taqieallah** [comment]
disable asus logo sound from bios and use 28 layout id
