### ISSUE TITLE
OpenCore0.5.9 with surface pro i7 skylake 6650U ig problems

### ISSUE THREAD

**Issue by fsnfs** [acidanthera/bugtracker#1056]
I used the followings to driver the iris 540:
------
only inject:
deviceid=16590000 or 1b590000
-------
It succeed but:
1. picture in preview.app shows incorrect
2. imovie in final cut output will cause reset
3. while load the mov files in AE2020 will case panic

I try to modify the deviceid to 6th gpu such as 26190000 ect. but no succeed

the problem is that deviceid=16590000 seems to stand for 7th gpu HD620, why iris 540 can done with 16590000? why not 26190000?
Thx!

**Comment by Andrey1970AppleLife** [comment]
Your IGPU has native device-id. Remove device-d property.
Use forums for support.
