### ISSUE TITLE
Whatevergreen @40hz on Big Sur

### ISSUE THREAD

**Issue by tlefko** [acidanthera/bugtracker#1057]
Hey guys, I have a UHD display which runs at 60hz under Catalina, this is a laptop with 10th gen i7-10510u. GPU spoofed as Iris Plus 655. Under Big Sur, the display is running at only 40hz with no way to get it up to 60hz. Display is 4K res. Not really sure what logs to include for you guys (or proper problem reporting style) for an issue like this. But I thought it was worth mentioning

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by liuyishengalan** [comment]
So far as I know, the laptop with 4K display only works at 48Hz under Big Sur beta. (XPS 9560, XPS 9570, ThinkPad P52, ThinkPad P52s, Legion Y series, etc.)

**Comment by M69W** [comment]
@xxxzc 's script：https://paste.ubuntu.com/p/BNpzrQCMRg/
use python3 to run it.
