### ISSUE TITLE
Compilation errors with Xcode 12 beta

### ISSUE THREAD

**Issue by HQuest** [acidanthera/bugtracker#1059]
Lilu cannot be compiled on latest Xcode 12.0 beta3 (untested on previous 12.0 betas). Sample below:
CompileC /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/kern_ubsan.o /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/Lilu/Sources/kern_ubsan.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Lilu' from project 'Lilu')

clang: error: argument unused during compilation: '-mmmx' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-msse' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-msse2' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-msse3' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-mssse3' [-Werror,-Wunused-command-line-argument]

The following build commands failed:
        CompileC /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/umm_malloc.o /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/umm_malloc/umm_malloc.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/sha256.o /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/sha256/sha256.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/utils.o /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/capstone/utils.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/qsort.o /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/Lilu/Library/bsd/kern/qsort.cpp normal arm64e c++ com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/lzvn.o /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/lzvn/lzvn.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/kern_util.o /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/Lilu/Sources/kern_util.cpp normal arm64e c++ com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/kern_user.o /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/Lilu/Sources/kern_user.cpp normal arm64e c++ com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/kern_ubsan.o /Users/hquest/Downloads/OC-tool/resources/latestSource/Kext_builds/Lilu/Lilu/Sources/kern_ubsan.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler
(8 failures)
Previous HEAD position was b68bbd3 Added device publishing API to monitor device startup
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

Also, improvements could be made overall. Do you still support Mountain Lion?

warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no run destination to provide an active architecture; choosing first applicable architecture: arm64e (in target 'Lilu' from project 'Lilu')
warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.8, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'Lilu' from project 'Lilu')

**Comment by vit9696** [comment]
- Xcode 12 is currently unsupported and is not planned to be supported in the August release.
- 10.8 is still supported and tested, only 10.7 support was removed not so long ago.
- Lilu does not support ARM at all and will unlikely support it in the foreseeable future.

We will see what we do with Xcode 12 as it gets more mature.

**Comment by 07151129** [comment]
Should be fixable by setting `ARCHS = "x86_64"` in the pbxproj for all configs and targets. This will have to be done for every project.

**Comment by Pavo-IM** [comment]
```
Build settings from command line:
    ARCHS = x86_64
/Users/henrybrock/Downloads/Lilu-master/Lilu/Sources/kern_iokit.cpp:25:4: error: use of OSPtr outside of a return type [-Werror,-Wossharedptr-misuse]
                        auto s = OSSerialize::withCapacity(PAGE_SIZE);
                        ^~~~
/Users/henrybrock/Downloads/Lilu-master/Lilu/Sources/kern_iokit.cpp:156:3: error: use of OSPtr outside of a return type [-Werror,-Wossharedptr-misuse]
                auto entry = IORegistryEntry::fromPath(path, plane);
                ^~~~
/Users/henrybrock/Downloads/Lilu-master/Lilu/Sources/kern_iokit.cpp:175:4: error: use of OSPtr outside of a return type [-Werror,-Wossharedptr-misuse]
                        auto iterator = entry->getChildIterator(plane);
                        ^~~~
/Users/henrybrock/Downloads/Lilu-master/Lilu/Sources/kern_iokit.cpp:258:5: error: use of OSPtr outside of a return type [-Werror,-Wossharedptr-misuse]
                                auto compatibleData = OSData::withBytes(compatibleBuf, compatibleBufSz);
                                ^~~~
4 errors generated.
```

```
The following build commands failed:
    CompileC /Users/henrybrock/Downloads/Lilu-master/build/Lilu.build/Release/Lilu.build/Objects-normal/x86_64/kern_efi.o /Users/henrybrock/Downloads/Lilu-master/Lilu/Sources/kern_efi.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    CompileC /Users/henrybrock/Downloads/Lilu-master/build/Lilu.build/Release/Lilu.build/Objects-normal/x86_64/kern_iokit.o /Users/henrybrock/Downloads/Lilu-master/Lilu/Sources/kern_iokit.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
```

**Comment by HQuest** [comment]
As of today and with all recent commits pointing to improve support to Xcode12, the OTHER_CFLAGS params on the project.pbxproj file are still causing Lilu to fail compiling:

clang: error: argument unused during compilation: '-mmmx' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-msse' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-msse2' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-msse3' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-mssse3' [-Werror,-Wunused-command-line-argument]

Not sure if these can be set per compiler/Xcode version, neither if these optimizations are going to come back to Xcode 12.

**Comment by vit9696** [comment]
This works fine for me with Xcode 12 on macOS 10.15.6, so you must be choosing some kind of "upgrade" project.

**Comment by HQuest** [comment]
Then Xcode 12 behaves differently if ran from Big Sur and Catalina. I have not tested to compile any recent code on 10.15/Cata, everything has been done from macOS 11/BS.

**Comment by HQuest** [comment]
Ok, tested Xcode 12 on Catalina. Fails as of Big Sur. This is what I'm doing to fetch & compile Lilu:

% rm -fr Lilu
% git clone https://github.com/acidanthera/Lilu
Cloning into 'Lilu'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 4083 (delta 28), reused 30 (delta 16), pack-reused 4026
Receiving objects: 100% (4083/4083), 4.28 MiB | 9.70 MiB/s, done.
Resolving deltas: 100% (2480/2480), done.
% cd Lilu
% xcodebuild -version
Xcode 12.0
Build version 12A8169g
% /usr/bin/xcodebuild -config Debug build
Command line invocation:
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xcodebuild -config Debug build

note: Using new build system
note: Planning build
note: Constructing build description
warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.8, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'Lilu' from project 'Lilu')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no run destination to provide an active architecture; choosing first applicable architecture: arm64e (in target 'Lilu' from project 'Lilu')
CreateBuildDirectory /Users/hquest/Lilu/build (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    builtin-create-build-directory /Users/hquest/Lilu/build

MkDir /Users/hquest/Lilu/build/Debug/Lilu.kext (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    /bin/mkdir -p /Users/hquest/Lilu/build/Debug/Lilu.kext

MkDir /Users/hquest/Lilu/build/Debug/Lilu.kext/Contents (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    /bin/mkdir -p /Users/hquest/Lilu/build/Debug/Lilu.kext/Contents

MkDir /Users/hquest/Lilu/build/Debug/Lilu.kext/Contents/MacOS (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    /bin/mkdir -p /Users/hquest/Lilu/build/Debug/Lilu.kext/Contents/MacOS

WriteAuxiliaryFile /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-project-headers.hmap (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    write-file /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-project-headers.hmap

WriteAuxiliaryFile /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/all-product-headers.yaml (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    write-file /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/all-product-headers.yaml

WriteAuxiliaryFile /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-all-non-framework-target-headers.hmap (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    write-file /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-all-non-framework-target-headers.hmap

WriteAuxiliaryFile /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-generated-files.hmap (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    write-file /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-generated-files.hmap

WriteAuxiliaryFile /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-own-target-headers.hmap (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    write-file /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-own-target-headers.hmap

WriteAuxiliaryFile /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-all-target-headers.hmap (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    write-file /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-all-target-headers.hmap

WriteAuxiliaryFile /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu.hmap (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    write-file /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu.hmap

WriteAuxiliaryFile /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/DerivedSources/Lilu_info.c (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    write-file /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/DerivedSources/Lilu_info.c

ProcessInfoPlistFile /Users/hquest/Lilu/build/Debug/Lilu.kext/Contents/Info.plist /Users/hquest/Lilu/Lilu/Info.plist (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    builtin-infoPlistUtility /Users/hquest/Lilu/Lilu/Info.plist -producttype com.apple.product-type.kernel-extension -expandbuildsettings -platform macosx -o /Users/hquest/Lilu/build/Debug/Lilu.kext/Contents/Info.plist

WriteAuxiliaryFile /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/Lilu.LinkFileList (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    write-file /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/Lilu.LinkFileList

CompileC /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/lzvn.o /Users/hquest/Lilu/lzvn/lzvn.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Lilu' from project 'Lilu')
    cd /Users/hquest/Lilu
    export LANG\=en_US.US-ASCII
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target arm64e-apple-macos10.8 -fmessage-length\=256 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fcolor-diagnostics -nostdinc -std\=c11 -fno-builtin -Wno-trigraphs -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCAPSTONE_HAS_X86\=1 -DCAPSTONE_HAS_OSXKERNEL\=1 -DCAPSTONE_DIET\=1 -DCAPSTONE_X86_REDUCE\=1 -DCAPSTONE_STATIC\=1 -DUMM_BEST_FIT\=1 -DUMM_MALLOC_CFG_HEAP_SIZE\=0x10000 -DMODULE_VERSION\=1.4.6 -DPRODUCT_NAME\=Lilu -DDEBUG\=1 -DKERNEL -DKERNEL_PRIVATE -DDRIVER_PRIVATE -DAPPLE -DNeXT -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fstrict-aliasing -Wdeprecated-declarations -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -iquote /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-generated-files.hmap -I/Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-own-target-headers.hmap -I/Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-all-target-headers.hmap -iquote /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Lilu-project-headers.hmap -I/Users/hquest/Lilu/build/Debug/include -I/Users/hquest/Lilu/capstone/include -I/Users/hquest/Lilu/lzvn -I/Users/hquest/Lilu/Lilu -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Kernel.framework/PrivateHeaders -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Kernel.framework/Headers -I/Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/DerivedSources-normal/arm64e -I/Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/DerivedSources/arm64e -I/Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/DerivedSources -F/Users/hquest/Lilu/build/Debug -mmmx -msse -msse2 -msse3 -mfpmath\=sse -mssse3 -ftree-vectorize -fno-non-call-exceptions -fno-builtin -fno-asynchronous-unwind-tables -Wall -Wextra -Wno-unused-parameter -Wno-deprecated-register -Wno-unknown-pragmas -Wno-unknown-warning-option -Wno-ossharedptr-misuse -Wno-vla -Werror -MMD -MT dependencies -MF /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/lzvn.d --serialize-diagnostics /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/lzvn.dia -c /Users/hquest/Lilu/lzvn/lzvn.c -o /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/lzvn.o
clang: error: argument unused during compilation: '-mmmx' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-msse' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-msse2' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-msse3' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-mssse3' [-Werror,-Wunused-command-line-argument]

(error repeats for next 7 files)

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/lzvn.o /Users/hquest/Lilu/lzvn/lzvn.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/umm_malloc.o /Users/hquest/Lilu/umm_malloc/umm_malloc.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/utils.o /Users/hquest/Lilu/capstone/utils.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/qsort.o /Users/hquest/Lilu/Lilu/Library/bsd/kern/qsort.cpp normal arm64e c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/sha256.o /Users/hquest/Lilu/sha256/sha256.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/kern_util.o /Users/hquest/Lilu/Lilu/Sources/kern_util.cpp normal arm64e c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/kern_user.o /Users/hquest/Lilu/Lilu/Sources/kern_user.cpp normal arm64e c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/hquest/Lilu/build/Lilu.build/Debug/Lilu.build/Objects-normal/arm64e/kern_ubsan.o /Users/hquest/Lilu/Lilu/Sources/kern_ubsan.c normal arm64e c com.apple.compilers.llvm.clang.1_0.compiler
(8 failures)

% _

**Comment by Pavo-IM** [comment]
Builds fine here on Xcode 12 using `xcodebuild -arch x86_64 -configuration Debug`

**Comment by HQuest** [comment]
Hmm, so the -arch x86_64 param on the cmd line truly does the trick, and seems it also works on Xcode 11. Thanks Pavo.

**Comment by vit9696** [comment]
Will leave that open as it is unclear what other consequences exist, and `-arch x86_64` is not a decent solution.

**Comment by vit9696** [comment]
Compilation errors should now be resolved thanks to @Andrey1970AppleLife but keep in mind that binaries built with Xcode 12 are unsupported and will unlikely work. Do not cry about it.

**Comment by Pavo-IM** [comment]
You do realize that by doing https://github.com/acidanthera/Lilu/commit/961d066917a53eb552b4148b1a0c4fce10ca1767 is the same as using `-arch x86_64` with xcodebuild command line correct?

**Comment by vit9696** [comment]
Correct, meaning that specifying -arch externally should not be required.
