### ISSUE TITLE
[WhateverGreen] AVFoundationErrorDomain: unexpected problem with the graphics sub-system

### ISSUE THREAD

**Issue by ylluminate** [acidanthera/bugtracker#1060]
Just a quick preface: upon enabling logging + file logging, I'm getting a `/Volumes/EFI/opencore-<TIMESTAMP>.txt` full of `<NUL>` vs any actual log contents. As far as I understand the documentation I enabled both OpenCore logging and Lilu logging.  

System: 
```
MacPro5,1 + VEGA 64 + OpenCore 0.5.9 + Lilu 1.4.5﻿ + WhateverGreen﻿ 1.4.0
```
* EFI folder: [download](https://p153.p0.n0.cdn.getcloudapp.com/items/rRul81PW/2020-07-24-EFI.zip)
* Logs: _Will attach once above NULL issue's resolved._

While attempting to capture video with some screencast tools I receive errors.  One particular tool issues an unexpected problem with the graphics sub-system and their developer swears up and down that it's a hardware problem due to using a MacPro5,1:
```
Recording failed: Error Domain=AVFoundationErrorDomain Code=-11844 "Cannot Capture" UserInfo={NSLocalizedDescription=Cannot Capture, NSUnderlyingError=0x600000dc5da0 {Error Domain=NSOSStatusErrorDomain Code=-67394 "(null)"}, AVErrorRecordingSuccessfullyFinishedKey=false, NSLocalizedFailureReason=There was an unexpected problem with the graphics sub-system that prevented screen capture.}
```

I suspect there may be something going on with `WhateverGreen` and the VEGA 64 GPU on this system and would like to isolate and resolve the issue.  Are any such issues known with the `AVFoundation` subsystem?

**Comment by ZISQO** [comment]
how about changing a smbios from 5,1 to imacpro1,1?
also, it's working fine when i take it up the video screen shot and Camtasia for screen recording with RX5700XT and VEGA 64 FE

**Comment by ylluminate** [comment]
@ZISQO 	are you on a MacPro5,1? Can you try downloading and installing the free CloudApp app?: https://www.getcloudapp.com/download/mac

If so, please try to capture a video (not GIF) and use `gear > Send Logs > Show in Finder`, unzip the archive and take a peak at what you see to see if there's an error as per above  or not?

**Comment by ylluminate** [comment]
@ZISQO in your suggestion are you saying to change only the SystemProductName or more fields, currently just using: 
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/WnubLZWK/Image%202020-07-24%20at%209.36.42%20PM.png)

**Comment by ylluminate** [comment]
I went fishing and did try some suggested hybridization settings here:
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/wbuWRLX1/Image%202020-07-25%20at%202.56.30%20AM.png)

And interestingly it succeeded the first recording attempt, but all subsequent attempts failed:
```
[recorder] Recording failed: Error Domain=AVFoundationErrorDomain Code=-11844 "Cannot Capture" UserInfo={NSLocalizedDescription=Cannot Capture, NSUnderlyingError=0x600002d820d0 {Error Domain=NSOSStatusErrorDomain Code=-67394 "(null)"}, AVErrorRecordingSuccessfullyFinishedKey=false, NSLocalizedFailureReason=There was an unexpected problem with the graphics sub-system that prevented screen capture.}
```

**Comment by Rescticed** [comment]
I actually thought this was a bug tracker, not a configurator support feed.

**Comment by ylluminate** [comment]
@Rescticed correct - this is a followup for the suggestion from @ZISQO to hopefully rule out this being what he thought of the setting suggestion he offered above. I still believe this is likely an issue with `WhateverGreen` due to the adamant developer feedback that there is a hardware compatibility issue and thus it seems we should be able to track this down and resolve it thusly...

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by ylluminate** [comment]
@Andrey1970AppleLife 	I'm sorry, the forums are essentially dead. There does not appear to be anyone in the `WhateverGreen` area that participates in more technical issues such as this. The bug report readme clearly indicates that these issues are meant for the purpose for which I'm using this:
```
When to use issue tracker:
* You have new resources or patches to add but cannot make a pull request
* You have kernel panics, crashes, hangs and believe it is not a configuration issue
* You want to discuss technical or legal stuff
```

Perhaps I'm misinterpreting one of these, but I feel that I very much fall into these parameters and need to discuss the situation more deeply.
