### ISSUE TITLE
Logo use request

### ISSUE THREAD

**Issue by Juan-VC** [acidanthera/bugtracker#1063]
Hey so I created a guide for my laptop and I would like to request usage of the OpenCore icon. Probably for the advantages over clover page and maybe as a favicon as well. The guide can be found here: https://juan-vc.github.io/oc-g7-guide/

I will wait for a response, thanks!

**Comment by asgmeonerandom** [comment]
dortania guide is better

**Comment by vit9696** [comment]
Your guide has some garbage like rEFInd. Sorry, but no.

**Comment by Juan-VC** [comment]
If I switch to OC only may I use it? I haven't got my hand dirty migrating completely to OC because I am not sure how to properly adapt my ACPI tables for a fully working windows system, mostly with the ACPI renames because I can play around with if OSI = Darwin, but what about the EC rename needed for laptops using macOS? Can I get some help to migrate?

**Comment by rektimus** [comment]
> Your guide has some garbage like rEFInd. Sorry, but no.

Why do you even bother to tell people to request logo usage when you clearly have no intent of letting people use it?

**Comment by rektimus** [comment]
> Because they can, the right to decide who uses it is theirs and should be respected.

Don't bring your drama here
