### ISSUE TITLE
Docs: Issue with ProvideConsoleGop Modification

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1064]
Page 65 of Docs on ProvideConsoleGop has been changed to say:  
> This option will ensure GOP and UGA, if present, are available on the console handle

This doesn't seem accurate as it implies the quirk will ensure **both** GOP and UGA will be made available on the console handle when it is enabled but looking at the source, the quirk does not do anything regarding UGA and only addresses GOP. Attempt to make UGA available appears to be under the UgaPassThrough quirk alone.

**Comment by vit9696** [comment]
Invalid. Handled [here](https://github.com/acidanthera/OpenCorePkg/blob/badcd12/Library/OcConsoleLib/ConsoleGop.c#L76-L86) when available. ProvideConsoleGop only forwards GOP and UGA handles when either of the protocols is available. It does not generate GOP or UGA protocols (the latter is done by UgaPassThrough quirk).

**Comment by dakanji** [comment]
Still misleading. At the very least, "and" should perhaps be "or" and parenthesis used for the UGA part.
> ...when either of the protocols is available

"AND" implies both together. Also, on models that have both GOP and UGA, this will only forward GOP regardless of presence of UGA.

Wording definitely needs reconsidering ... IMO

**Comment by vit9696** [comment]
Your claim is incorrect. This will forward **both** protocols on models that have them, so the **and** is valid. `ConsoleHandleProtocol` takes current requested protocol, which is either GOP or UGA at a time.

**Comment by dakanji** [comment]
Can you clarify where both are processed?

I see...
`
If GOP
...
return
else if UGA 
...
return
End if
`

**Comment by vit9696** [comment]
The function is called sequentially with GOP and UGA.

**Comment by dakanji** [comment]
Working through the code, I see...

- OcProvideConsoleGop is called with Route = True from OpenCoreUefiInOut.c
- gBS->HandleProtocol   is set to ConsoleHandleProtocol as Route is True
- gBS->HandleProtocol (ConsoleHandleProtocol) is then run with gEfiGraphicsOutputProtocolGuid (I.e., GOP) as protocol to get &OriginalGOP on ConsoleOut Handle
- `If GOP ... elseif UGA ... End` matches GOP
- if no error and MaxMode > 0, OcProvideConsoleGop returns
- if no error and !MaxMode > 0, OcProvideConsoleGop continues
- gBS->LocateHandleBuffer is run
- A loop over handles is initiated looking for HandleBuffer not on ConsoleOutHandle
- If found, gBS->HandleProtocol (ConsoleHandleProtocol) is run with gEfiGraphicsOutputProtocolGuid (I.e., GOP) as protocol to get &Gop on GPU Firmware Handle
- If no error, Uninstall &OriginalGOP on ConsoleOut Handle
- If no error, Install &Gop on GPU Firmware Handle

Scratching my head especially since OcProvideConsoleGop is only ever called with `Route = True` only once in the code base.

**Comment by vit9696** [comment]
`gBS->HandleProtocol` is called by EfiBoot, this code is written by Apple and is not open source obviously.
