### ISSUE TITLE
Problem with my Realtek ALC294, Asus Rog Strix G512LV

### ISSUE THREAD

**Issue by serpinu** [acidanthera/bugtracker#1065]
![IMG_3082](https://user-images.githubusercontent.com/35550620/88857159-0be5f000-d1f6-11ea-8720-33052ca4714b.jpg)
hi, let me write here because I would like to report a compatibility problem between my realtek alc294 sound card and appleALC.kext.
I tried everything possible with the help of other more competent guys on appleALC configuration, using the various compatible layouts: 11,12,13,21,22,28,66, using them both with bootargs, and setting it through the section clover devices.
With all the layouts I am recognized the speaker and the microphone, (unlike the port for the jack that does not appear), but nobody can hear anything coming from the speaker. I am attaching the debug created and my efi. Thank you!
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4997657/EFI.zip)

[debug mio.zip](https://github.com/acidanthera/bugtracker/files/4997660/debug.mio.zip)

**Comment by vandroiy2013** [comment]
Hello
Use forums for support.
