### ISSUE TITLE
Early kernel panic with latest Lilu commit

### ISSUE THREAD

**Issue by ZISQO** [acidanthera/bugtracker#1066]
i've update after committing the index addition of the 
"Abort on PCI register read failure", the symptom of not being able to patch the RTC_Range.aml(SSDT) information appears.
[Commit 7620da2](https://github.com/acidanthera/Lilu/commit/7620da2ceca7d933d544a9beb0e077c6fe546979)

This result is considered to be the same as normal symptom only when patching the RTC_Range that occurred when booting the X299 motherboard for the first time with Big Sur Beta 1.

the 496213a commit is working fine on Big Sur beta 3.
[Commit 496213a](https://github.com/acidanthera/Lilu/commit/496213ab793b20b1996cedaed752bcb7005e80bc)

- my RTC_Range.aml 
<img width="574" alt="스크린샷 2020-07-31 오전 3 24 34" src="https://user-images.githubusercontent.com/50421769/88959705-61e19300-d2dd-11ea-91bf-3e00e3bcdab9.png">

- Added RTC_Range.aml in ACPI/Add
<img width="626" alt="스크린샷 2020-07-31 오후 11 11 42" src="https://user-images.githubusercontent.com/50421769/89043287-36b17f00-d383-11ea-9c83-ebefbf58b53a.png">

- Added RTC_Range.aml in ACPI/Patch
- Must be enabled both with Lilu 496213a commit was working on BS BT3 but, previous commit was just added RTC_Range.aml at ACPI and SSDT file. when i using just one of patch or ssdt won't working. just stuck at PCI Configuration Begin.
<img width="908" alt="스크린샷 2020-07-31 오후 11 12 30" src="https://user-images.githubusercontent.com/50421769/89043377-55177a80-d383-11ea-9071-c5322d463026.png">

- No need to add ncpi=0x2000 or 0x3000. just using the old commit 496213a solved the problem.
![KakaoTalk_Photo_2020-07-31-03-25-32](https://user-images.githubusercontent.com/50421769/88959781-83db1580-d2dd-11ea-9c44-1986fc56a8ca.jpeg)

- this IORegistry Explorer screen from Catalina 10.15.6 with Latest OC/Lilu + @ kexts
- RTC is Motherboard RTC and RTC0 is RTC_Range value
- but AppleRTCUserClient was not found in BS BT3. idk it's why..
<img width="911" alt="스크린샷 2020-07-31 오후 11 33 00" src="https://user-images.githubusercontent.com/50421769/89045284-3b2b6700-d386-11ea-8342-b83ecdbb4322.png">

- Debug log file from OpenCore and Lilu Debug Binaries
[opencore-2020-07-30-174238.txt](https://github.com/acidanthera/bugtracker/files/5003152/opencore-2020-07-30-174238.txt)

- ASUS X299 TUF mk1 / i7-7800X / RX 5700XT

 I really appreciate everything you’ve done. have fun!

**Comment by vit9696** [comment]
This stuff was broken everywhere, but I believe it should be fixed in master. Please note, that 11.0 (and in fact potentially older versions after the Lilu upgrade) have higher requirements to your ACPI: https://github.com/acidanthera/OpenCorePkg/commit/20fa9074e6bf3d6acad24869670626986d84ac97#diff-567688bcd4741f8bbfd57acebc9f644cR1585.

**Comment by ZISQO** [comment]
Yeah, thanks for your advice. Then I'll work on the ACPI problem in deeply and report the results.
