### ISSUE TITLE
VoodooPS2controller and Ivy Bridge

### ISSUE THREAD

**Issue by LocTran016** [acidanthera/bugtracker#1067]
Excuse me, I've used the latest release version of VoodooPS2controller.kext along with VoodooInput.kext (I've clean snap shot and double check, the order is VoodooInput->VoodooPS2controller->VoodooPS2Controller/.../VoodooInput->VoodooPS2Controller/.../Keyboard->VoodooPS2Controller/.../Mouse->VoodooPS2Controller/.../Trackpad) but my mouse didn't work because of some unknown issues. I'm using MacOS Catalina 10.15.5 with OpenCore DEBUG version 0.5.9 but I couldn't make my mouse work unless I use the [Rehabman's VoodooPS2](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller) but it can only work with some 2 fingers feature (zoom, etc don't work). For Ivy Bridge, I don't know if this is a problem with [acidanthera's VoodooPS2controller](https://github.com/acidanthera/VoodooPS2) or some others trackpad-related kext, too (include VoodooRMI by 1Revenger1 still have this problems with Ivy Bridge [here](https://github.com/VoodooSMBus/VoodooRMI/issues/33))
My DELL INSPIRON 3421 (model 2012)specs is here:
Larrytran's DELL INSPIRON 3421 (model 2012): 
CPU : Dual Core Intel Core i5-3337U, 1800 MHz
Motherboard Name: Dell Inspiron 3421 (Intel Panther Point HM76, Intel Ivy Bridge)
RAM: 3993 MB (DDR3 SDRAM)
BIOS: A13 (12/14/2015)
Graphic: Intel(R) HD Graphics 4000 (2077230 KB)
Monitor: LG Philips LP140WH2 (Dell MV65P) [14" LCD] (1366 x 768), connector LVDS
Intel Panther Point HDMI @ Intel Panther Point PCH - High Definition Audio Controller
Audio: Realtek ALC282 @ Intel Panther Point PCH - High Definition Audio Controller
HDD WDC Green 500GB
Keyboard: Standard PS/2 Keyboard
Mouse: Dell Touchpad (PS/2 Synaptics Trackpad)
Wifi card: Broadcom 802.11n Network Adapter (DW1704)

**Comment by vit9696** [comment]
I think it is part of https://github.com/acidanthera/bugtracker/issues/890.
