### ISSUE TITLE
Dell Latitude 3540 Touchpad + button issue

### ISSUE THREAD

**Issue by Revenger** [acidanthera/bugtracker#1068]
I have a Dell Latitude 3540 with a inbuilt Synaptics PS2 touchpad that has varied levels of compatability.
I tried every VoodooPS2Controller.kext I could find and having some issues.

RehabMan version works with the two physical buttons and touch, though gestures are all messed up.
Your acidanthera/VoodooPS2 kext the physical buttons don't work, the touch seemed to have been intermittant though just reset preferances in the trackpad app.

I would like to get the physical butttons working also but no idea how.
Also I will keep a check on the tap buttons but hope polish comes.

Don;'t know what changed between RehabMan's and yours to stop the buttons working.

**Comment by vit9696** [comment]
I think it is part of https://github.com/acidanthera/bugtracker/issues/890.
