### ISSUE TITLE
immutablekernel loading support

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1071]
Currently immutablekernel loading support is missing due to unimplemented Apple SecureBoot functionality in OpenCore. We need to make that available for itlwm with Black80211 bridge to work. 

A quick hack allowing this to work is implemented in https://github.com/acidanthera/OpenCorePkg/tree/itlwm branch. Attaching a NOOPT variant of this branch meant to replace the 0.6.0 binary.
[OpenCore-any-SB.zip](https://github.com/acidanthera/bugtracker/files/5015264/OpenCore-any-SB.zip)

**Comment by vit9696** [comment]
Implementing ApECID compatibility will require reworking OpenCanopy protocol and reducing the security at DMG loading, leaving open for now.

**Comment by HQuest** [comment]
Using ApECID=0 and SecureBootMode=Default (or any mode - below as iMacPro1,1), regardless of OpenCanopy or Builtin used as picker and using latest source files for OpenCore, it still causes Catalina and Big Sur B4 recovery images to fail load, with the immutablekernel files marked as "not found".

```
167:525 00:077 AAPL: [EB|#SB:MF] (boot\\System\\Library\\KernelCollections\\BootKernelExtensions.kc.j137ap.im4m)
167:597 00:071 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: boot\\System\\Library\\KernelCollections\\BootKernelExtensions.kc.j137ap.im4m, DP: 0
167:668 00:071 AAPL: [EB|`LD:OFS] Err(0xE) @ OPEN (boot\\System\\Library\\KernelCollections\\BootKernelExtensions.kc.j137ap.im4m)
167:742 00:073 AAPL: [EB|`SB:VK] Err(0xE) @ LD:LF
167:819 00:077 AAPL: [EB|`LD:LKCFFP] Err(0x1A) @ SB:SBVK
167:893 00:073 AAPL: [EB|#CS:SRBM] secure-boot
167:965 00:071 AAPL: [EB|#FWFM] 0x00000000FF9FFF3F
168:037 00:072 AAPL: [EB|#FWFT] 0x00000000FD8FF53E
168:117 00:079 AAPL: [EB|#B:RB]
168:189 00:071 AAPL: [EB|#WL|8] 0x01 0x41  19 0x0E
168:258 00:069 AAPL: [EB|#REBOOT] 1
168:333 00:074 AAPL: [EB|#LOG:RESET:RECOVERY] 2020-08-11T13:00:54
```

The install images are able to find and load the immutablekernel files however throw errors afterwards with what seems missing keys:

```
131:070 00:576 AAPL: [EB|`SB:VK] Err(0x1A) @ MKRN
131:094 00:024 AAPL: [EB|`SB:VK] Err(0x1A) @ MKRD
131:113 00:018 AAPL: [EB|`LD:LKCFFP] Err(0x1A) @ SB:SBVK
131:141 00:027 AAPL: [EB|#WL|6] 0x01 0x41  23 0x0E
131:156 00:015 AAPL: [EB|#REBOOT] 1
131:178 00:022 AAPL: [EB|#LOG:RESET:RECOVERY] 2020-08-11T13:23:51
```

Therefore the only actual way to load either Recovery or install images is to set SecureBootMode=Disabled. Unsure if these parameters are to be used only on real Apple device - this machine is not one. Happy to provide more supporting logs.

**Comment by vit9696** [comment]
Full log with within OpenCore debug log?

**Comment by HQuest** [comment]
[install macOS Big Sur b4.txt](https://github.com/acidanthera/bugtracker/files/5057437/install.macOS.Big.Sur.b4.txt)
[install macOS Catalina.txt](https://github.com/acidanthera/bugtracker/files/5057438/install.macOS.Catalina.txt)
[recovery Big Sur b4.txt](https://github.com/acidanthera/bugtracker/files/5057439/recovery.Big.Sur.b4.txt)

**Comment by vit9696** [comment]
We were able to reproduce the issues booting macOS 11 recovery, but not the issue with the macOS 11 installation. The error you see during the installation is very strange. I improved debug logging in https://github.com/acidanthera/OpenCorePkg/commit/fa58908b2697477e080ba73564a08743802de61b. Please provide the install log with it.

**Comment by vit9696** [comment]
Could you tell me how exactly did you create the install media for both Catalina and 11.0? Maybe there is something special about it…

**Comment by HQuest** [comment]
Standard createinstallmedia command. The Catalina was created with a now wiped image of Catalina 10.15.6 and while under OC 0.6.0-dev. The BS B4 was made with OC 0.6.1-dev from yesterday sources. I'm about to restart using the above code and will post the debug log in a couple minutes.

**Comment by vit9696** [comment]
Just the thing is, both your logs show immutablekernel.development successfully loading. This file is normally present exclusively in AppleInternal macOS builds. Could you tell me how did you get both images?

**Comment by vit9696** [comment]
Could you create disk images of your installation media and upload them somewhere?

**Comment by HQuest** [comment]
Debug log attached. No success.
[opencore-2020-08-11-175902.txt](https://github.com/acidanthera/bugtracker/files/5058614/opencore-2020-08-11-175902.txt)

About the images, they both were obtained via download thru the App Store. For BS, macappstores://itunes.apple.com/app/id1497794093 (or https://apps.apple.com/us/app/macos-big-sur-beta/id1497794093?mt=12) - it then directs me to SysPrefs > Software Update and asks if I want to download macOS Big Sur Beta. For Catalina, same way via App Store @ https://apps.apple.com/us/app/macos-catalina/id1466841314?mt=12

![Screen Shot 2020-08-11 at 2 06 21 PM](https://user-images.githubusercontent.com/1088309/89932574-d8369d00-dbdb-11ea-839f-9ace26e8ca52.png)

With it downloaded, standard procedure - cd /Application/Install macOS Big Sur Beta.app/Content/Resources; sudo ./createinstallmedia --volume /Volume/usbdrivevolname

**Comment by vit9696** [comment]
Whatever you downloaded, this is not really what most people get :D. It does not have the normal im4m manifest we can verify. Could you upload `System/Library/KernelCollections` from your Big Sur flash? And to be honest afterwards, I might really want the `.app` itself and the USB flash media dumps...

**Comment by HQuest** [comment]
[SLKC.tar.gz](https://github.com/acidanthera/bugtracker/files/5058692/SLKC.tar.gz)

For the app/media dumps, I can host them no problems. Give a few minutes and I'll provide a link - although I'll be more happier to share it over an email message or any way less open to the public.

**Comment by vit9696** [comment]
Thanks! Interesting this directory does not have the `.development` version. Probably buried within inner DMGs. Yes, e-mail sharing will work best. Please drop an e-mail to my account at protonmail.com, same nickname.

**Comment by vit9696** [comment]
In the meanwhile, while it is still uploading, could you please provide the output of `sudo /System/Library/PrivateFrameworks/Seeding.framework/Resources/seedutil current` on the computer you downloaded these? Maybe also via the e-mail.

**Comment by HQuest** [comment]
I’ve posted this on a public forum not so long ago.

https://www.insanelymac.com/forum/topic/344428-pre-release-macos-big-sur/?do=findComment&comment=2733047

Will get a fresh output whenever I’m back in front of the OS but last I checked (maybe a day or two ago) it was the same output.

Alex

**Comment by vit9696** [comment]
Yeah, just the ordinary thing. Really strange. Anyway, let's wait for the files and see what we get…

**Comment by HQuest** [comment]
Somehow I felt special now... ;)

E-mail sent with more details. Appreciated all your guys effort.

**Comment by vit9696** [comment]
Thanks! Checked the file. The installer is identical to the b4 I downloaded myself. Now the question is whether your USB flash with Big Sur is somehow special, or it is your system that behaves very different. Could you also upload the dumps of the USB flash? You can create them with Disk Utility or `dd`.

**Comment by vit9696** [comment]
I extended the code to save BootKernelExtensions.kc.development to the first writable filesystem found under kc.bin. Could you run this with your macOS installer and upload the file & the log?

[OC-Dump-DBG-r1.zip](https://github.com/acidanthera/bugtracker/files/5059946/OC-Dump-DBG-r1.zip)

**Comment by HQuest** [comment]
And we have a winner for the install failure issue:

Either VboxHFS.efi is incompatible or I am using an older copy of it, but HFSPlus.efi properly boot the Install image with the new secure boot turned on. Using a HFSPlus.efi file built from source resolved the above issues I was experiencing: no different behavior than from the custom debug one I was provided to test. The custom debug OpenCore.efi wasn't required and the one from source worked - yet, see the kc.bin under attached logs for future reference.

For the record and as expected, the recovery 11 image fails to load.

[logs.zip](https://github.com/acidanthera/bugtracker/files/5060191/logs.zip)

Thank you @vit9696 for your incredible guidance!

**Comment by vit9696** [comment]
Nice. I wished for a happier ending as an internal build was sounding too promising, but realising it is just the borked driver and getting things fixed is also good. At this point it is necessary to understand whether the latest VBoxHfs is affected (attached the one from master), and if it is, file a bug against it. From a user point of view it is more practical to use the HfsPlus driver, as it is more performant, but if there is an issue with VBoxHfs we should still fix it to make debugging easier when we need it.

[VBoxHfs.efi.zip](https://github.com/acidanthera/bugtracker/files/5061347/VBoxHfs.efi.zip)

CC @nms42

**Comment by HQuest** [comment]
Made an attempt with your attached VBoxHFS and is a no-no. Same error as before.

**Comment by vit9696** [comment]
Good, then this is indeed a separate issue.

**Comment by vit9696** [comment]
@HQuest please check https://github.com/acidanthera/bugtracker/issues/1097. There may have been added a fix to your issue.

**Comment by HQuest** [comment]
Will try it later in the weekend/early next week. Thank you for the heads up.

**Comment by vit9696** [comment]
Fully resolved, closing.
