### ISSUE TITLE
Last version VirtualSMC(1.1.6)

### ISSUE THREAD

**Issue by corint1** [acidanthera/bugtracker#1074]
after wake from sleep :

panic(cpu 3 caller 0xffffff800fdf1486): Kernel trap at 0xffffff800fe09f59, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000011010ba8a78, CR3: 0x0000000262855055, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0x00000000ffffffff, RCX: 0x0000018ffffffe70, RDX: 0xffffff8010ba8c00
RSP: 0xffffffb07e073d80, RBP: 0xffffffb07e073e20, RSI: 0x0000000000000000, RDI: 0x0000000000000001
R8:  0xffffff8010bae480, R9:  0x0000000000000000, R10: 0xffffff8010baee40, R11: 0x00000000000009c0
R12: 0x0000000000005754, R13: 0xffffff8010ba8d90, R14: 0x000000000057fb44, R15: 0x0000000000001d1c
RFL: 0x0000000000010002, RIP: 0xffffff800fe09f59, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000011010ba8a78, Error code: 0x0000000000000000, Fault CPU: 0x3, PL: 1, VF: 5

Backtrace (CPU 3), Frame : Return Address
0xffffffb07e0736a0 : 0xffffff800fcc048d mach_kernel : _handle_debugger_trap + 0x3dd
0xffffffb07e0736f0 : 0xffffff800fe00633 mach_kernel : _kdp_i386_trap + 0x143
0xffffffb07e073730 : 0xffffff800fdf10ba mach_kernel : _kernel_trap + 0x55a
0xffffffb07e073780 : 0xffffff8013c4b6e4 as.vit9696.VirtualSMC : __ZN18VirtualSMCProvider10kernelTrapI22x86_saved_state_1010_tEEvPT_Pm + 0x454
0xffffffb07e073800 : 0xffffff800fc65a2f mach_kernel : _return_from_trap + 0xff
0xffffffb07e073820 : 0xffffff800fcbfd2d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffb07e073940 : 0xffffff800fcc0018 mach_kernel : _panic_trap_to_debugger + 0x268
0xffffffb07e0739b0 : 0xffffff80104b8dea mach_kernel : _panic + 0x54
0xffffffb07e073a20 : 0xffffff800fdf1486 mach_kernel : _sync_iss_to_iks + 0x2c6
0xffffffb07e073ba0 : 0xffffff800fdf116d mach_kernel : _kernel_trap + 0x60d
0xffffffb07e073bf0 : 0xffffff8013c4b6e4 as.vit9696.VirtualSMC : __ZN18VirtualSMCProvider10kernelTrapI22x86_saved_state_1010_tEEvPT_Pm + 0x454
0xffffffb07e073c70 : 0xffffff800fc65a2f mach_kernel : _return_from_trap + 0xff
0xffffffb07e073c90 : 0xffffff800fe09f59 mach_kernel : _xcpm_urgency + 0x589
0xffffffb07e073e20 : 0xffffff800fdf37a3 mach_kernel : _thread_tell_urgency + 0x83
0xffffffb07e073e60 : 0xffffff800fce4bb5 mach_kernel : _thread_dispatch + 0x595
0xffffffb07e073ed0 : 0xffffff800fce44e8 mach_kernel : _thread_unstop + 0x17e8
0xffffffb07e073f40 : 0xffffff800fce5f5d mach_kernel : _thread_run + 0x5d
0xffffffb07e073f80 : 0xffffff800fce7bdb mach_kernel : _idle_thread + 0x7b
0xffffffb07e073fa0 : 0xffffff800fc6513e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         as.vit9696.VirtualSMC(1.1.6)[F2E18E74-8A94-3579-8084-535CBAC1BAD4]@0xffffff8013c3c000->0xffffff8013c62fff
            dependency: as.vit9696.Lilu(1.4.6)[C548E094-5A45-367B-BE26-2CF461660167]@0xffffff8013c11000->0xffffff8013c39fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[A4355EF9-ACA3-361C-932D-86AC22FBC5D6]@0xffffff8012238000->0xffffff801223bfff

Process name corresponding to current thread: airportd
Boot args: -v keepsyms=1 igfxonln=1 alcid=3

Mac OS version:
20A5343i

Kernel version:
Darwin Kernel Version 20.0.0: Thu Jul 30 22:49:28 PDT 2020; root:xnu-7195.0.0.141.5~1/RELEASE_X86_64
Kernel UUID: A4484A86-97DF-3675-941B-0AD00D2DB6EB
KernelCache slide: 0x000000000fa00000
KernelCache base:  0xffffff800fc00000
Kernel slide:      0x000000000fa0c000
Kernel text base:  0xffffff800fc0c000
__HIB  text base: 0xffffff800fb00000
System model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 2374091837883
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000228c2e69c29
  Sleep   : 0x00000228c00f88d9 0x00000007a1d4d133 0x0000000000000000
  Wake    : 0x00000228c27be2be 0x000000002e4b2ecb 0x00000228c116e490

**Comment by vit9696** [comment]
XCPM (`_xcpm_urgency`) crashed for you. Irrelevant for VirtualSMC.
