### ISSUE TITLE
[Question]AMD Radeon RX 5700 XT

### ISSUE THREAD

**Issue by Blurayx** [acidanthera/bugtracker#1075]
Are there any plans to support temperature monitoring for the Radeon RX 5700 XT?

Thanks

**Comment by vit9696** [comment]
No, sorry. Ask Apple for that as Polaris drivers do have temperature monitoring, and there are Macs with Radeon RX 5700 XT.

**Comment by HQuest** [comment]
Hopefully this will come up soon, as 2020 iMac 27" will ship with 5700 XT cards.

However, I deeply hope they don't take the "SMC fan controlling" approach...

**Comment by luvletter2333** [comment]
So this is Apple's driver problem?
Their driver doesn't support temperature monitor and fan speed control?

**Comment by HQuest** [comment]
Most of Apple fan related control is done over SMC. And as of Beta 4, there is no support of it for the 5700 card on its drivers - need to look into B5 to find if this got changed, but I highly doubt it, as the iMac 2020 isn't even supported by Beta 5.

**Comment by hustwyk** [comment]
So is there any solutions to support temperature monitor or fan speed control of 5700XT?
