### ISSUE TITLE
[CPU Power Management] CFG Lock and C-States option in BIOS

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1076]
Hi there,
I apologize in advance if this isn't the right place where to ask. 
I have one doubt about CFG Lock: this boolean-type variable, if set to 0x00 allows macOS to write in the MSR 0xE2 BIOS region the CPU C-States else I have to enable `AppleCpuPmCfgLock` and `AppleXcpmCfgLock` quirks under `Kernel-Quirks`. I've unlocked CFG Lock but, after digging inside my Dell Inspiron 5370 BIOS, under "Performance/CPU C-States" I left enabled "C States" as depicted below:

![image](https://user-images.githubusercontent.com/17933708/89520953-f2890900-d7de-11ea-9e86-7926c6f46245.png)

My question is: do I have to leave this option enabled, or it may conflict with macOS CPU Power Management (which should managed by AppleIntelPowerManagement afaik)? 
Many thanks and have a nice day :)

**Comment by vit9696** [comment]
I believe if 0xE2 is unlocked, it is irrelevant which BIOS power management is configured, macOS will reconfigure to its own. You can leave this option enabled for other operating systems though.
