### ISSUE TITLE
Kernel Panic : AppleALC on wake after sleep

### ISSUE THREAD

**Issue by shantur** [acidanthera/bugtracker#1082]
[AppleACL-Crash-3.txt](https://github.com/acidanthera/bugtracker/files/5042387/AppleACL-Crash-3.txt)
Facing a Kernel Panic on wakeup after sleep.

CPU : Haswell i7 4790S
Mobo : Gigabyte GA-Z97P-D3
GPU : Sapphire RX 480 Nitro 8G
OS : Catalina 10.15.6
SMBIOS : iMac14,2
OpenCore : 0.6

Status : 

1. Catalina Boots fine
2. Audio works fine.

Steps : 

1. Boot Catalina.
2. Select sleep from apple menu
3. Wait for machine to sleep
4. Wakeup with keyboard

Result : Display wakes up, login screen is visible but screen is frozen, mouse pointer doesn't move.

Next Reboot : Kernel panic details are shown.

I have tried. 

- No-hda-gfx
- PowerTimeoutKernelPanic:

[EFI.zip](https://github.com/acidanthera/bugtracker/files/5042322/EFI.zip)
[OpenCoreLogs.zip](https://github.com/acidanthera/bugtracker/files/5042324/OpenCoreLogs.zip)
[AppleACL-Crash-3.txt](https://github.com/acidanthera/bugtracker/files/5042388/AppleACL-Crash-3.txt)

Thanks for your help.

**Comment by vit9696** [comment]
Something with AppleHDA itself, not an issue with AppleALC.

**Comment by shantur** [comment]
Thanks for confirming. I saw AppleALC in stack trace so thought it might be related.
