### ISSUE TITLE
[Question]Can not unload kext which is injected by OpenCore.

### ISSUE THREAD

**Issue by zxystd** [acidanthera/bugtracker#1083]
Hi there, I found that I can't unload kext which is injected by OpenCore, If I manually load the kext that I can unload it successfully. it is a bug or an expected behavior? Thanks.

CPU: i5-10210U
macOS version: 10.15.6
OpenCore version: 0.5.9(0.6.0 is the same).
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5044549/EFI.zip)

**Comment by naveenkrdy** [comment]
Not sure if this is expected behavior or not but i can reproduce the same.
```
$ sudo kextunload -v 6 -b as.vit9696.AppleALC                                                                                                                                                                                                                   
Kext user-space log filter changed from 0xff2 to 0xfff.
Kext kernel-space log filter changed from 0xff2 to 0xfff.
Requesting unload of as.vit9696.AppleALC (with termination of IOServices).
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Unload' request from user space.
(kernel) Kext as.vit9696.AppleALC calling module stop function.
(kernel) Kext as.vit9696.AppleALC did not stop (return code 0x5).
(kernel) Kext as.vit9696.AppleALC can't unload - module stop returned 0xdc008017.
Kernel error handling kext request - (libkern/kext) kext (kmod) start/stop routine failed.
Failed to unload as.vit9696.AppleALC - (libkern/kext) kext (kmod) start/stop routine failed.
```

**Comment by vit9696** [comment]
I believe it is expected. Kext loading and unloading on the fly has been deprecated for a while by introducing various kinds of kext restrictions, and it is removed in 11.0 anyway. And in older operating systems I do not believe you can unload a kext without its ondisk presence.
