### ISSUE TITLE
ACPI tables located in the ROM mapping may not patch

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1085]
For these tables we need to perform legacy region unlock via the legacy region protocol. This mostly affects Dell firmwares running OpenDuetPkg.

**Comment by HQuest** [comment]
Unsure if related but while reviewing my UEFI environment and ACPI tables with and without OC, with the help of FWTS tool [1], there are some inconsistencies. For instance, with no ACPI injection whatsoever under OC, things like test of UEFI RT service fails and ACPI table RDSP checksum do not match whereas in the direct, non-OC results, both are passed.

[1] https://wiki.ubuntu.com/FirmwareTestSuite/FirmwareTestSuiteLive

**Comment by Goldfish64** [comment]
@HQuest There were some fixes done related to the RSDP and checksum calculation, could you recheck master?

**Comment by HQuest** [comment]
I can confirm your commit has corrected the RDSP checksum calculation, thank you.
