### ISSUE TITLE
Configuration.pdf: Misc > Tools content provided under UEFI section

### ISSUE THREAD

**Issue by HQuest** [acidanthera/bugtracker#1090]
While reviewing the OC Configuration guide, the Misc > Tools section is listed under "8. Misc" (page 32, section "8.2 Properties", item "6. Tools"), however, the tools details are provided under UEFI section (page 57, section "11.3 Tools"). Shouldn't this content be under "8. Misc" section as "8.7 Tools"?

**Comment by HQuest** [comment]
If the above is invalid, then this means Tools should be a section under UEFI and the Configuration.pdf document is correct. However the sample plist from the project has Tools under Misc. As the documentation and the sample file differs, which one is correct, then?

**Comment by Andrey1970AppleLife** [comment]
You confuse structure declaration config.plist for Tool and list UEFI Tools.

**Comment by HQuest** [comment]
Maybe I am. The Configuration.pdf file is centered around the OC config.plist file structure declaration, however 1) the Misc > Tools section is not detailed or referenced anywhere, and 2) a UEFI > Tools section that doesn't exist on the config.plist file structure is detailed.

Should the Misc > Tools configuration to be referred into the UEFI > Tools section, at a minimum a sentence should be added for clarity and consistency that this info is to be found at another location.

**Comment by Andrey1970AppleLife** [comment]
You shall understand that UEFI Tools are independent and adding of their majority in the OC menu isn't reasonable.

**Comment by vit9696** [comment]
While I agree that the things are completely independent (conceptual description of UEFI tools vs Tools configuration subsection), adding cross-reference links is honestly a good idea, as they can help one to locate related material and ease the navigation in the document. Will do.

**Comment by HQuest** [comment]
Thank you Vit. After the clarification on why Tols were where they are by Andrey, my point was that if one deletes its tools section out of the config.plist, there is zero documentation about how to get anything into it - aside of going after a sample plist file -, whereas you have everything else about the config.plist in the Configuration.pdf document.

The example tools provided are great start points for what you can use as UEFI tools - personally, I use two not listed and those work for me. However I can only use them since I went after a sample config.plist to copy how to configure them into OC’s config.plist file and hope I used each field in the right way.

I do apologize if I made this sound like an argument or insisting in a change you might not agree in full, but I’m happy I helped to improve anything to others.
