### ISSUE TITLE
Radeon PRO W5500 black screen

### ISSUE THREAD

**Issue by Frank-N-Furter** [acidanthera/bugtracker#1091]
Hello,

Radeon PRO W5500 after start drivers produce black screen, system still run. WX 5100 hasn't problem on the same hardware on MacOs 10.15.6, iMac19,1.

**Comment by 1alessandro1** [comment]
Need logs to report the issue, otherwise it will be closed as invalid

**Comment by vandroiy2013** [comment]
agdpmod=pikera

**Comment by Frank-N-Furter** [comment]
Thank you very much, perfect works.

is there some way to booz in Safe mode without black screen?


Best

Vaclav
