### ISSUE TITLE
Need fix update_products.py for four character AppleModelCode with the first character zero.

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#1092]
If the first character zero, update_products.py perceives as three character AppleModelCode.
Need fix because iMac20,2 AppleModelCode begin with zero.
https://github.com/acidanthera/OpenCorePkg/blob/master/AppleModels/DataBase/iMac/IM202.yaml#L86-L91

**Comment by matis-schotte** [comment]
So do I understand correctly that this issue can be reproduced like this:
```
% ./update_products.py 046M 046N
46M - not found
46N - not found
```

**Comment by vit9696** [comment]
Pretty much. Actually unsure how we are supposed to handle this, as we think of them as numbers.

**Comment by matis-schotte** [comment]
The real question would be are three and four zeros ('000' and '0000') the same for apple or are they different?

**Comment by vit9696** [comment]
In the past — yes, now not. 3 characters are for older serials with just 3 of them. Then 4 character ones were used. I guess that's how it is really. Need to extend the range. making 10ZZZ a thing just not printing the leading 1.

**Comment by matis-schotte** [comment]
Yeah, lots of possible approaches, we could also just have one 3-len run and then one 4-len run ;)

**Comment by matis-schotte** [comment]
Looks like I got it working:

```
% ./update_products.py 09Q 09Q  
09Q - iMac (20-inch, Mid 2007) (skip)
% ./update_products.py 046M 046N
046M - iMac (Retina 5K, 27-inch, 2020) (skip)
046N - iMac (Retina 5K, 27-inch, 2020) (skip)
% ./update_products.py ZZZ 0001 
ZZZ - pending (skip 2020-10-03)
0000 - not found (skip 2020-10-03)
0001 - not found (skip 2020-10-03)
```

**Comment by matis-schotte** [comment]
Hi @vit9696, I took the liberty to re-check the boundary-test on current master:
```
% ./update_products.py ZZZ 0001 
ZZZ - None
1000 - not found
1001 - not found
```

I think it looks like its jumping to 1000 directly and not checking 0000-0999, so that this range would be missing ...

**Comment by vit9696** [comment]
That's because 0001 is essentially 10001, so it is going after ZZZZ.

**Comment by matis-schotte** [comment]
Oh, okay - interesting! :) So then its there, but just in a different order ... Now I understand why 0ZZZ is the last code.
