### ISSUE TITLE
Laptops with 4K integrated display work @48Hz frequency (Big Sur Beta)

### ISSUE THREAD

**Issue by liuyishengalan** [acidanthera/bugtracker#1093]
Before making the internal display works, the EDID should be edited by modifying the frequency parameters. However, it seems that this issue is not caused by EDID. I suppose that the lack of functionality of the Lilu patches may trigger this issue. Is there any possibility to make the internal 4K screen works at 60 Hertz?

Any logs and files required for debugging and diagnosing, please tell me. I will upload them accordingly.

<img width="702" alt="Screen Shot 2020-08-11 at 8 47 47 AM" src="https://user-images.githubusercontent.com/41530282/89844843-634d6e00-dbaf-11ea-81a5-7d317a3ee04c.png">

**Comment by vit9696** [comment]
If you need CDF functionality, this is not available on 11.0. Closing as it is not decided whether we will pursue its implementation.

**Comment by vicjl** [comment]
#1024

**Comment by adityahota** [comment]
@vit9696 Do you know if there are any updates regarding this? I believe many with 4K eDP panels are facing this issue and was wondering if there is any way I can contribute to resolving the issue.

**Comment by liuyishengalan** [comment]
> @vit9696 Do you know if there are any updates regarding this? I believe many with 4K eDP panels are facing this issue and was wondering if there is any way I can contribute to resolving the issue.

Due to userspace patches failed functionality, 4k internal display cannot work @60Hz. No updates on it I think.

**Comment by iamsanoj1** [comment]
> Before making the internal display works, the EDID should be edited by modifying the frequency parameters. However, it seems that this issue is not caused by EDID. I suppose that the lack of functionality of the Lilu patches may trigger this issue. Is there any possibility to make the internal 4K screen works at 60 Hertz?
> 
> Any logs and files required for debugging and diagnosing, please tell me. I will upload them accordingly.
> 
> <img alt="Screen Shot 2020-08-11 at 8 47 47 AM" width="702" src="https://user-images.githubusercontent.com/41530282/89844843-634d6e00-dbaf-11ea-81a5-7d317a3ee04c.png">

Hey,

I have facing the same issue where my internal monitor is not detected in the display section. only i can use usb C HDMI. 
i have 17" 4k pannel on my MSI gs73vr. i tried the EDID patching. but i couldnt get it running. could you help me with how u have edited your EDID?
