### ISSUE TITLE
VBoxHfs returns files that do not exist ondisk

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1097]
For macOS 11 installation image the following (not existent) files are found:
System\Library\KernelCollections\BootKernelExtensions.kc.development
System\Library\KernelCollections\BootKernelExtensions.kc.development.j137ap.im4m

For macOS 10.15.6 installation image the following (not existent) files are found:
System\Library\PrelinkedKernels\immutablekernel.development
System\Library\PrelinkedKernels\immutablekernel.development.j137ap.im4m

Originally reported here https://github.com/acidanthera/bugtracker/issues/1071.

CC @nms42

**Comment by nms42** [comment]
Well,
try attached binary. For the record: NOOPT_CLANGPDB build.

[VBoxHfs.efi.zip](https://github.com/acidanthera/bugtracker/files/5078275/VBoxHfs.efi.zip)

**Comment by HQuest** [comment]
Confirmed working for BigSur 11.0b4 and Catalina 10.15.6 installers.

**Comment by nms42** [comment]
fix applied
