### ISSUE TITLE
Failed to disable  gpu at big sur

### ISSUE THREAD

**Issue by dmlzj** [acidanthera/bugtracker#1098]
- opencore: 0.6.0

Hello, my Y7000 2020 model failed to sleep after upgrading Big Sur. I found that the weg parameter could not block the independent display. I also tried many ssdt patches, but none of them worked. I hope I can get your help, thank you!

**Comment by Andrey1970AppleLife** [comment]
Check with WEG from the master.
https://github.com/acidanthera/WhateverGreen/commit/5b67774aa06695e561c5613801646be5f7c29b49

**Comment by Andrey1970AppleLife** [comment]
https://dortania.github.io/builds/?product=WhateverGreen&viewall=true&version=1.4.2&sha=5b67774aa06695e561c5613801646be5f7c29b49

**Comment by dmlzj** [comment]
@Andrey1970AppleLife 
Thank you. It's ok!
