### ISSUE TITLE
alc1150 stopped working in update 1.5.0 and 1.5.1 of AppleALC

### ISSUE THREAD

**Issue by Nosis** [acidanthera/bugtracker#1099]
in version AppleALC 1.4.9 it worked correctly but after 1.5.0 it does not detect the sinido hardware, for now. I went back to 1.4.9 to have audio with alc1150, I have catalina 10.15.6 and a motherboard asus b85 pro gamer

**Comment by Andrey1970AppleLife** [comment]
There are no changes for alc1150 in versions 1.5.0 and 1.5.1. The last change for alc1150 was 17 months ago.
