### ISSUE TITLE
bug with appleALC 1.5.0 and 1.5.1

### ISSUE THREAD

**Issue by Nosis** [acidanthera/bugtracker#1100]
I have used applealc on an ALC1150 for several versions of osx, the sound worked perfectly but with the arrival of 1.5.0 the system does not detect the sound hardware, version 1.5.1 had the same problem, and I have tried Several configuration possibilities with clover but the only solution I have found is to return to 1.4.9, I understand that despite not having modified the specific code of Alc1150, since a long time ago, with the arrival of 1.5.x something was broken not in On the other hand, I do not expect a personalized solution, but if you need feedback you can count on me.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/1099

**Comment by vit9696** [comment]
If you wrongly used `alc-layout-id`, its support was removed in 1.5.0. Otherwise there is no change.
