### ISSUE TITLE
onPatcherLoad is not working

### ISSUE THREAD

**Issue by hieplpvip** [acidanthera/bugtracker#1102]
Hi, I'm facing a problem similar to https://github.com/acidanthera/bugtracker/issues/1008. `onPatcherLoad` doesn't seem to work for me.

My laptop is Asus Zenbook UX410 running 10.15.6; everything (OpenCore, Lilu,...) is up to date. SMBIOS is MacBookPro14,1

 I use `onPatcherLoad` to call a function that would find out the patch needed to patch `SidecarCore` (similar to how `SystemProfilerMemoryFixup` works). My code is [here](https://github.com/hieplpvip/SidecarEnabler/blob/new-patch/SidecarEnabler/kern_start.cpp#L193).

Is there any way to fix this?

**Comment by vit9696** [comment]
Lilu has detailed error messages when API denies you, you are doing something wrong most likely.

**Comment by hieplpvip** [comment]
I tried `onPatcherLoadForce`. There was no kernel panic but Lilu still didn't execute the callback function.

**Comment by vit9696** [comment]
It does execute the function always. Most likely you have your logs missed if you assumed it is not executed from macOS logs. Use liludump.
