### ISSUE TITLE
AppleALC: No audio device showed up after adding pin configuration and path map

### ISSUE THREAD

**Issue by lunjielee** [acidanthera/bugtracker#1109]
Codec is ALC245, everything for bug report was attached
Opencore EFI:
[EFI.7z.zip](https://github.com/acidanthera/bugtracker/files/5093635/EFI.7z.zip)
Opencore Logs:
[opencore-2020-08-19-014901.txt](https://github.com/acidanthera/bugtracker/files/5093639/opencore-2020-08-19-014901.txt)
Lilu Logs:
[Lilu_1.4.7_20.0.txt](https://github.com/acidanthera/bugtracker/files/5093644/Lilu_1.4.7_20.0.txt)
codec file and codec pathmap:
[codec#0.svg.zip](https://github.com/acidanthera/bugtracker/files/5093648/codec.0.svg.zip)
[codec#0.txt](https://github.com/acidanthera/bugtracker/files/5093649/codec.0.txt)
ioreg dump:
[Linus's MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/5094442/Linus.s.MacBook.Pro.ioreg.zip)
Hackintool Sound Panel:
![hackintool audio](https://user-images.githubusercontent.com/32808108/90583543-6c859e80-e19e-11ea-8622-f6ffb14e428a.png)
System Information Audio:
![empty audio device](https://user-images.githubusercontent.com/32808108/90583564-7ad3ba80-e19e-11ea-83a9-4fb9664b91d8.png)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
