### ISSUE TITLE
opencore Sleep Wake issue on asus x507ua laptop

### ISSUE THREAD

**Issue by Lakshya-Pro** [acidanthera/bugtracker#1111]
my laptop specs-
name(model) - asus x507ua
processor - intel i5 quad core 1.8ghz
graphics - intel uhd 620 graphics
ram - 8gb ddr4

i have a issue with me sleep wake
when my asus notebook goes to sleep it successfully or maybe not sleep properly, the display becomes off and it works for sometime in that time if i open my lid or click on the trackpad or keyboard it wakes and ask me for the password 

can see image - ![Sleep](https://user-images.githubusercontent.com/59724159/90719377-dc487600-e2d1-11ea-94b4-f97451856679.jpg)

 

but the real thing is that aftersometime if i didnt wake it it shutsdown itself fans stops and everything and i have to shut it on again, i am ok with that but it's annoying. its weird because it does not shutsdown when it instantly goes to sleep it sleeps for sometime around 1-2minutes and then it shutsdown and when i turn it on again a error occurs   when i logges again after shut on - your computer was restarted `bec
ause` of a problem and in details it shows sleep wake failure.

image - 

<img width="646" alt="mz9uq3p03yb41" src="https://user-images.githubusercontent.com/59724159/90718771-6db6e880-e2d0-11ea-94c2-c05b5fe8cbc5.png">
please tell me what can be the issue and by the way my firmware is asus and i have wake on lid open in bios i don't think so that occurs that i have tried many things tried all power options but no luck.
everything works my notebook is one of the most successfull asus notebook with least kext i can have with pure opencore
just sleep is the `issue`

**Comment by vandroiy2013** [comment]
https://github.com/acidanthera/bugtracker/issues/817

**Comment by vandroiy2013** [comment]
https://www.reddit.com/r/MacOS/comments/dme38s/sleep_wake_failure_in_efi/

As i said earlier this problem is out of our scope.

**Comment by Lakshya-Pro** [comment]
ok

**Comment by savvamitrofanov** [comment]
Really it related to how you configure your hardware from ACPI up to bootloader configuration
