### ISSUE TITLE
When using VoodooPS2, any sort of click will not work.

### ISSUE THREAD

**Issue by Iphone5-RecoveryMode** [acidanthera/bugtracker#1112]
Things like gestures and moving the mouse works fine, but tapping, clicking, using physical buttons, etc. does not work. 

I am on a Lenovo b40-80, Heres the specs (screenshots from ubuntu included in the zip provided)

Sorry if audio codec was vague, I didn't use applealc.
[Lenovo B40-80 Specs.zip](https://github.com/acidanthera/bugtracker/files/5103049/Lenovo.B40-80.Specs.zip)

**Comment by Iphone5-RecoveryMode** [comment]
oh and;
'image' is the cpu specs
'image 2' is networking (wifi and ethernet)
'image 3' is something connected to the trackpad (prob physical buttons)
'image 4' is trackpad

**Comment by Iphone5-RecoveryMode** [comment]
![Screen Shot 0002-08-20 at 5 56 25 AM](https://user-images.githubusercontent.com/68778920/90772789-e48cbb00-e2a9-11ea-9343-aa24f135bc33.png)
Another thing is that the trackpad does not appear in prefpane
![Screen Shot 0002-08-20 at 5 57 16 AM](https://user-images.githubusercontent.com/68778920/90772896-02f2b680-e2aa-11ea-82a0-ecd10b112372.png)
and also there is nothing in accessibility

**Comment by Andrey1970AppleLife** [comment]
I don't see in you the pictogram to the battery.
The battery of the laptop has to work in macOS.
Resolve an issue with the battery first of all.
Therefore it influences on to show settings of the trackpad.

**Comment by Iphone5-RecoveryMode** [comment]
the battery works, do you mean the percentage?
I haven't patched the battery percentage.

**Comment by asgmeonerandom** [comment]
ps2 doesn't get much love, you can reverse other kexts and contribute to this
