### ISSUE TITLE
OC boot halts on empty string in SystemProductName

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1122]
commit 818f9e3f571908f6e0e6a08e09e8d84cc7c4872e added  line 161 in OcMacInfoLib.c:
```
ASSERT (ProductName != NULL);
```
If the string `SystemProductName` exists as a parameter with a NULL (empty) value OC bootloader halts on boot. This value normally is not empty, but in the case of a real mac it is not needed for booting. OpenCore configurator adds empty strings in some sections if the config file is opened and saved in the OpenCore configurator and that section is enabled:
![image](https://user-images.githubusercontent.com/7897244/91318062-d0a0f780-e788-11ea-855a-a0ac6763fe4f.png)

**Comment by Goldfish64** [comment]
@startergo Should be fixed with https://github.com/acidanthera/OpenCorePkg/commit/b217cd52d25d873c3b8e951e1b4815ecbcb258d2. Please retest.

**Comment by vit9696** [comment]
@startergo **always** provide OpenCore debug log in such cases. `OpenCore configurator` does not matter here, when the field is unused it should be set to empty (e.g. string in this case). Missing fields are undefined behaviour.

**Comment by dakanji** [comment]
Interesting. I only put the changed fields in mine and it works. 
I suppose what you is saying is that it might not work at any point in future but isn't it convention that there would be default values that are only changed when something is passed in such cases?

**Comment by vit9696** [comment]
> Interesting. I only put the changed fields in mine and it works.

I think it works incorrectly, as SMBIOS detection will be wrong, and older operating systems like 10.6 will have trouble with it. Feel free to upload the log to confirm it.

> I suppose what you is saying is that it might not work at any point in future

Pretty much.

> but isn't it convention that there would be default values that are only changed when something is passed in such cases?

No, there are no default values within OpenCore. Only failsafe, which try to reduce the harm on your system when the configuration is corrupted (i.e. when some values are missing).

```tex
\item
  \texttt{invalid\ value} --- valid \texttt{plist\ object} of
  \texttt{OC\ config} described in this document that is of other
  \texttt{plist\ type}, does not conform to additional requirements
  found in specific \texttt{plist\ object} description (e.g.~value
  range), or missing from the corresponding collection.
  \texttt{Invalid\ value} is read with or without an error message as
  any possible value of this \texttt{plist\ object} in an undetermined
  manner (i.e.~the values may not be same across the reboots). Whilst
  reading an \texttt{invalid\ value} is equivalent to reading certain
  defined \texttt{valid\ value}, applying incompatible value to the host
  system may yield to \texttt{undefined\ behaviour}.

**Comment by kommtzeitkonrad** [comment]
> Interesting. I only put the changed fields in mine and it works.
> I suppose what you is saying is that it might not work at any point in future but isn't it convention that there would be default values that are only changed when something is passed in such cases?

https://github.com/acidanthera/OpenCorePkg/blob/d2230ec7ebf4a53f192cea1c50be1e63c63d65e6/Docs/Configuration.tex#L374

**Comment by dakanji** [comment]
> No, there are no default values within OpenCore. Only failsafe

Can't these failsafe values act as defaults? 
I suppose your response would be that this view is coloured by a being a Legacy Mac user and that this might be a serious issue for Hacks which I am not considering.

**Comment by vit9696** [comment]
It was a decision we took some while ago and have no plans to change it. Requiring to specify all the fields helps the user to easily compare the configurations and find the renamed/removed fields, and it also helps us to avoid maintaining backwards compatibility. In any case, this is roughly off-topic, and I am more interested in closing the issue if it is resolved.

**Comment by startergo** [comment]
Works as designed now:
[opencore-2020-08-26-161242.txt.zip](https://github.com/acidanthera/bugtracker/files/5131097/opencore-2020-08-26-161242.txt.zip)
