### ISSUE TITLE
SandyBridge HP Laptop can't get bootpicker

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#1123]
HI. today i determined that switched Clover to OpenCore on HP 4230s sandybridge laptop.
this laptop can use both Legacy and UEFI.
i try to boot macos with normal setting.
but i can't get bootpicker.
here is opencore log
[opencore-2020-08-27-145639.txt](https://github.com/acidanthera/bugtracker/files/5137165/opencore-2020-08-27-145639.txt)

thanks in advance

**Comment by vit9696** [comment]
The manual does have explanation why the laptop does not boot.
