### ISSUE TITLE
voodoops2controller when I wake my HP Envy 17 with the keyboard it causes keys to get pressed or keyboard doesn't work

### ISSUE THREAD

**Issue by Deihmos** [acidanthera/bugtracker#1124]
When I wake my HP laptop using the keyboard it causes key spam and sometimes the keyboard stops working.

I can wake fine if I use the touchpad. I am not sure what logs I should submit or if there is something I can do to correct it. This is the first build on the laptop and everything is working fine but this. I have the most recent build of voodoops2controller and opencore 0.6. I hope I attached the correct logs. 

[Archive.zip](https://github.com/acidanthera/bugtracker/files/5145429/Archive.zip)

Thanks.

**Comment by vit9696** [comment]
I believe it is a hardware bug. Please submit a patch if you find a workaround.

**Comment by Deihmos** [comment]
I tried older versions of voodoops2. The issue started in version 2.1.5. I don't have the same problem in 2.1.4. Thanks.
