### ISSUE TITLE
Relocation block support for safe mode and macOS without KASLR

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1125]
For booting macOS on UEFI firmwares with used lower memory areas (i.e. on systems where booting with `slide=0` is impossible) we need to either specify a custom slide location, or use a relocation block.

It is not possible to use a custom slide location with operating systems that do not support KASLR, such as 10.7 or older. It is also not possible to use slide in safe mode. Although we do have a workaround named `EnableSafeModeSlide`, it constantly breaks with operating system updates.

**Comment by HQuest** [comment]
Some of these changes somehow affected newer OS such as Big Sur b5 as well. I'm now getting random "OC: Boot failed - Aborted" messages from the past 2 day master changes on my systems, in a similar behavior of what would be caused by a bad slide value. The OS fails to load and I'm automatically sent back to picker for a retry. So far, it seems it works on every 2nd attempt.

[opencore-2020-08-30-132135.txt](https://github.com/acidanthera/bugtracker/files/5146866/opencore-2020-08-30-132135.txt)

**Comment by vit9696** [comment]
The log is incomplete.

**Comment by HQuest** [comment]
That's the untouched file as generated by OC. Matches what I have on disk. Let me know what's missing, I can generate a new one and look for this content before reposting.

**Comment by vit9696** [comment]
Well, you rebooted too early according to the log. Just try redoing it.

**Comment by HQuest** [comment]
I have not rebooted during this log capture; after it loaded first time, I selected the Big Sur partition, it errored out, I waited and was greeted by picker a second time, then it booted Big Sur properly.

**Comment by vit9696** [comment]
> I selected the Big Sur partition, it errored out

Right, this was not obvious that you have two run attempts for Big Sur. I was looking at a different place. According to the log you have a MemoryMap:AppleKernelMemory allocation failure around 0x116D1000:

```
43:953 00:069 AAPL: [EB|#STOP|`BST:FBS] ! @ MM:AKM 292360192 @ 'RT
```

However, you have disabled `ProvideCustomSlide` and several other quirks `Booter` that may be relevant for your platform at the very least:

```
01:552 00:039 OCABC: FEXITBS 0 PRMRG 0 CSLIDE 0 MSLIDE 0 PRSRV 0 RBMAP 1 VMAP 1 APPLOS 0 RTPERMS 1
```

To summarise, your issue is triggered every time EfiBoot picks an unlucky slide and is unrelated to this issue, where we discuss the possibility to boot older operating systems with 0 slides. For you the fix is to update your configuration correctly. I will keep this issue private to the team to avoid unrelated problems being discussed, thank you for understanding.
