### ISSUE TITLE
boot failure when SystemProductName=iMacPro1,1

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1127]
![image](https://user-images.githubusercontent.com/7897244/91647296-4924e400-ea27-11ea-93ab-19bddf0b53f0.png)
![image](https://user-images.githubusercontent.com/7897244/91647312-7ffafa00-ea27-11ea-8b06-828191cd336a.png)
[opencore-2020-08-29-191627.txt](https://github.com/acidanthera/bugtracker/files/5146069/opencore-2020-08-29-191627.txt)

**Comment by BooBerry** [comment]
I'm getting this too with a fresh build of the latest commits, and I'm also using iMacPro1,1. If I revert to a build from the commits from 15+ hours ago, it works fine again. My log shows more-or-less the same as yours, including this part (which is also in your log) when trying to boot verbose;

![Mac_Boot_Failure](https://user-images.githubusercontent.com/5448916/91647618-5b505380-ea22-11ea-8c0b-16cba2a45e57.jpg)

Out of curiosity I've tried changing SecureBootModel, DmgLoading and FuzzyMatch but no change.

**Comment by startergo** [comment]
I tried different OSX: Catalina, HS, Mojave same error. Only Windows 10 works but MFC found an error in the SMC iMacPro1,1. None of SecureBootModel, DmgLoading, FuzzyMatch and KernelArc make any difference.

**Comment by Goldfish64** [comment]
Please retest with latest commits.

**Comment by BooBerry** [comment]
Yep, working fine here now.

Thank you very much kind sir, keep up the good work! 👍

**Comment by Goldfish64** [comment]
Leaving open due to issues with 10.6 and/or 10.7 and iMacPro1,1.

**Comment by Goldfish64** [comment]
Fixed in https://github.com/acidanthera/OpenCorePkg/commit/bda3750d07473d5a1af75c9e827088340fd618ea

**Comment by startergo** [comment]
Yep, it works now.
