### ISSUE TITLE
Unable To View Bootloader (Picker)

### ISSUE THREAD

**Issue by xLidoni** [acidanthera/bugtracker#1129]
Hello!

I have a particular problem!  
I'm using OC 0.6.0 and can't boot via UEFI in any way.  
I tried to change USB, 2.0 and 3.0  
Furthermore, the problem also occurs with other USB's with efi working in other systems.

In practice, when I try to boot it finds the "OpenCore" Entry or UEFI:" USB" but when I try to access the bootloader, it stays still on the blackscreen.  
I tried to wait but nothing, completely black screen.

No LOGS are generated

OC tested versions

0.5.8 | 0.5.9 | 0.60

Thanks!

Config:x79 jingsha Dual S8  
2x Xeon E5 2650  
64GB Samsung ECC 1333  
RX 470 Gigabyte  
NVMe Sunbow 256GB  
UEFI SUPPORTED

**Comment by vit9696** [comment]
You can try running a DEBUG build through Shell and use onscreen logging to troubleshoot your configuration if the logs are not created.

**Comment by xLidoni** [comment]
Thanks dir tour reply @vit9696 

There is my SysLog here 

https://drive.google.com/file/d/13KkLoEvB-VJOt4oYTXAlkYgXU3lWuXxh/view?usp=drivesdk


With DEBUG version, i can view BootPicker in UEFI ! but not works with RELEASE.

**Comment by vit9696** [comment]
Interesting, could you tell us which exact DEBUG binary resolves the problem for you (i.e. try replacing DEBUG binaries one by one with RELEASE ones until it stops booting)? I personally do not believe there is a real difference between DEBUG and release.

**Comment by xLidoni** [comment]
Hello, With the new version, the problem magically **disappeared**. But now I have other very strange problems.

Specs: X79 | 2x E5 2658v2 | 64GB RAM |RX 460 |0C 0.6.2 Mojave

I've a strange problem, If i try to boot with USB 2.0 ports, i get:

**AppleUSBHostPort::disconnect: persistent enumeration failures or prohibited sign.**

But if i try to boot with a 3.0 PORT , im able to view Installer. But keyboard & mouse, are OFF (no lights).

I tried USB Inject all and XHCI unsupported, but the result doesn't change

Rename EUSB to EH01 & Rename USBE to EH02 etc etc... Same issue.

This is a video, you can see that I arrive at the installer, but I am not able to use the mouse and the keyboard. During the verbose they go out. : https://www.youtube.com/watch?v=4qNXtvbCoGs&feature=youtu.be

I cannot find a possible solution, I am aware that it is strange.

Thanks ;)

**Comment by xLidoni** [comment]
Hello, With the new version, the problem magically **disappeared**. But now I have other very strange problems.

Specs: X79 | 2x E5 2658v2 | 64GB RAM |RX 460 |0C 0.6.2 Mojave

I've a strange problem, If i try to boot with USB 2.0 ports, i get:

**AppleUSBHostPort::disconnect: persistent enumeration failures or prohibited sign.**

But if i try to boot with a 3.0 PORT , im able to view Installer. But keyboard & mouse, are OFF (no lights).

I tried USB Inject all and XHCI unsupported, but the result doesn't change

Rename EUSB to EH01 & Rename USBE to EH02 etc etc... Same issue.

This is a video, you can see that I arrive at the installer, but I am not able to use the mouse and the keyboard. During the verbose they go out. : https://www.youtube.com/watch?v=4qNXtvbCoGs&feature=youtu.be

I cannot find a possible solution, I am aware that it is strange.

Thanks ;)
