### ISSUE TITLE
Documentation update for removed article

### ISSUE THREAD

**Issue by HQuest** [acidanthera/bugtracker#1130]
Under Booter > Quirks > DisableSingleUser, there is a reference to an Apple article. This article https://support.apple.com/HT201573 has been moved/removed by Apple, hence making the current link invalid. Appreciated for a review of the link/quirk description to accommodate the change.

**Comment by CoronaHack** [comment]
https://web.archive.org/web/20200517125051/https://support.apple.com/en-us/HT201573

You can see the original content here but I don't think it's a good idea to have web achieve links in docs.

**Comment by vit9696** [comment]
Fine to me, fixed.
