### ISSUE TITLE
KP in VirtualSMC when booting with acpi_layer=0x0001FFFF

### ISSUE THREAD

**Issue by benbender** [acidanthera/bugtracker#1132]
While booting with boot-arg "acpi_layer=0x0001FFFF", as per documentation, there seems to be a recursion in VirtualSMC which leads to the KP seen in the screenshot below.

I can't say what's causing the bug originally, as no .panic-dump is written and because of the recursion I can't spot the beginning.

Without that boot-arg, the system boots fine.

OC & VirtualSMC are latest builds via dortania-builds. 

If I can provide any additional info, please ask! Thank you so much for your valuable work!

![virtualsmc-bug](https://user-images.githubusercontent.com/462455/91764733-18d07780-ebd8-11ea-9211-172a60594d94.jpg)

**Comment by vit9696** [comment]
VSMC is in the panic trace as it hooks the kernel_trap method called at pagefault. This bug is in AppleACPIPlatform.
