### ISSUE TITLE
ASUS X99-A / Instant Kernel Panic (FAULT CR2)

### ISSUE THREAD

**Issue by Chibibowa** [acidanthera/bugtracker#1134]
Hi

When attempting to boot MacOS Big Sur, I get an instant kernel panic after PCI Configuration begin/end, the error in cause is CR2. I attached a screenshot for you to see what is going on.

My EFI Folder is attached here: https://mega.nz/folder/3oUzhApZ#eapJoPVOv00u-tJWo3GZLg

I tried using the RTC0 Range file but it still doesn't work. Here is what my motherboard returns to me:

				Device(RTC)
				{
					Name(_HID, EISAID("PNP0B00"))
					Name(_CRS, ResourceTemplate()
					{
						IO(Decode16, 0x0070, 0x0070, 0x01, 0x02)
						IO(Decode16, 0x0074, 0x0074, 0x01, 0x04)
						IRQNoFlags() {8}
					})
				}

I believe the RTC file from Opencore is incompatible with the X99 platform (More specifically, ASUS motherboards). It seems I'm not the only one stuck at this problem.

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
