### ISSUE TITLE
Fix yellow screen in WhateverGreen on Ryzen systems when mtrr_update_action (fix PAT) is disabled

### ISSUE THREAD

**Issue by HoshiYamazaki** [acidanthera/bugtracker#1137]
Hiya, I use OpenCore 0.6.0 (yes, I know I will test today release too) and we finally found culpirit in GPU performance on Ryzentoshes, the problem is in old patch called `algrey - mtrr_update_action - fix PAT`.
Also I know I shouldn't describe issue here, but maybe it fits and can be fixable in WhateverGreen.
![image](https://user-images.githubusercontent.com/21007545/92365565-49427500-f0f4-11ea-9e3a-debad7b4abf3.png)
![image](https://user-images.githubusercontent.com/21007545/92365569-4ba4cf00-f0f4-11ea-975d-c64cd36d05c0.png)

So, basically this patch probably breaks MTRR caching causing some desync beetwen threads and slowdowns perf even about 500%:
https://github.com/AMD-OSX/bugtracker/issues/5

BUT, if we disable the patch, people on discord (and me) are getting black screen, and after minute or two it becomes yellow (on system boot/startup). For some reason (probably not all) TRX40 systems does not need this patch anyway which was confirmed by Pavo-IM (this is why we know that this is the problem).
We are not sure what causes the yellow screen, so I will try to post logs when I will come to home from work. If this is not fixable in kexts/OC we gonna investigate patches probably.

AMD OSX patches:
https://github.com/AMD-OSX/AMD_Vanilla/blob/opencore/17h/patches.plist

Specific patch HEX override corresponds to:
![image](https://user-images.githubusercontent.com/21007545/92365642-65dead00-f0f4-11ea-9476-5351a24881e9.png)
![image](https://user-images.githubusercontent.com/21007545/92365662-6d9e5180-f0f4-11ea-95a9-063aa6d1e404.png)

Resources:
https://en.wikipedia.org/wiki/Memory_type_range_register
https://forums.developer.nvidia.com/t/mtrr-performance-gains-are-impressive-but-hard-to-achieve/31931
https://askubuntu.com/questions/48283/poor-graphics-performance-due-to-wrong-mtrr-settings

**Comment by HoshiYamazaki** [comment]
[opencore-2020-09-07-133725.txt](https://github.com/acidanthera/bugtracker/files/5183377/opencore-2020-09-07-133725.txt)
[opencore-2020-09-07-133418.txt](https://github.com/acidanthera/bugtracker/files/5183378/opencore-2020-09-07-133418.txt)
[opencore-2020-09-07-133156.txt](https://github.com/acidanthera/bugtracker/files/5183379/opencore-2020-09-07-133156.txt)
[opencore-2020-09-07-132933.txt](https://github.com/acidanthera/bugtracker/files/5183380/opencore-2020-09-07-132933.txt)
[opencore-2020-09-07-132616.txt](https://github.com/acidanthera/bugtracker/files/5183381/opencore-2020-09-07-132616.txt)
[opencore-2020-09-07-132354.txt](https://github.com/acidanthera/bugtracker/files/5183382/opencore-2020-09-07-132354.txt)

This are my log files after disabling/enabling various options in BIOS, including:
* Changing CSM to UEFI and otherwise
* Disabling/Enabling IOMMU, NX Pages and AMD-SVM
* Enabling Above 4G CryptoMining
* Changing GPU connection from/to Gen 2 from/to Gen 3

Not really sure which options are connected to which log, first log (see date in filename) is from my default config. Seems that errors are similar, everything is about `GV wake failure`.

**Comment by HoshiYamazaki** [comment]
[opencore-2020-09-07-172256.txt](https://github.com/acidanthera/bugtracker/files/5184251/opencore-2020-09-07-172256.txt)

Log from 0.6.1

**Comment by tomnic79** [comment]
Hi HoshiYamazaki, I can boot when mtrr_update_action (fix PAT) is disabled (3950X with ASRock X570 Steel Legend) I need to wait some minutes to have a usable GUI and get some graphical glitches, but OpenGL test in Cinebench 15 went up at 130 fps as in proxmox, Minecraft works at 300 fps, just like in proxmox... this is the right direction to investigate!!!

**Comment by tomnic79** [comment]
![IMG_20200908_144743](https://user-images.githubusercontent.com/49807536/92486593-930e8680-f1ec-11ea-811e-f811ad03f80f.jpg)

**Comment by tomnic79** [comment]
![IMG_20200908_142534](https://user-images.githubusercontent.com/49807536/92486998-01534900-f1ed-11ea-819d-fa6706662387.jpg)
![1](https://user-images.githubusercontent.com/49807536/92487128-2a73d980-f1ed-11ea-9c6a-347d84ed49ad.png)

**Comment by Andrey1970AppleLife** [comment]
We don't support AMD CPU, though we empathy with its problems.
