### ISSUE TITLE
[Apple SecureBootModel] Your firmware is not supported

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1138]
Hi there,
today I've updated to OpenCore 0.6.1 stable release as long as the kexts and I wanted to enable Apple SecureBootModel.
Standing to Configuration.pdf, in order to enable Apple SecureBootModel I need to:

- Set config.plist/Misc/Security/SecureBootModel to the string corresponding to my wanted SMBIOS
 (e.g. MBP15,2) or Default, which basically is j137, also known as iMacPro1,1
- Set ApECID to a random 64bit digit by using `python3 -c 'import secrets; print(secrets.randbits(64))'` 
- Run the bless command from a Recovery image in order to boot macOS: 

`bless bless --folder "/Volumes/Macintosh HD/System/Library/CoreServices" \ --bootefi --personalize`

- Open "Startup Disk Utility" and check the SecureBootModel status

I've tried the above steps without success, as I see "Your firmware is not supported". 

![image](https://user-images.githubusercontent.com/17933708/92409918-92b9b100-f142-11ea-8e32-795aeb92a9fa.png)

I've supposed that this is due to the absence of T2 chip on the chosen SecureBootModel string. Is this hypothesis totally wrong? If not, what else is wrong? 

I attach my [censored_config.plist.zip](https://github.com/acidanthera/bugtracker/files/5184352/censored_config.plist.zip) hoping that it can be helpful.

Thank you so much for your work and have a nice day

**Comment by vit9696** [comment]
This is expected as Startup Security Utility uses T2 to control Apple Secure Boot settings, and in our case it is controlled in OpenCore's `config.plist`.

**Comment by dreamwhite** [comment]
> This is expected as Startup Security Utility uses T2 to control Apple Secure Boot settings, and in our case it is controlled in OpenCore's `config.plist`.

Okay, so how can I confirm that Apple SecureBootModel is fully working as expected since I see the above message? 
If there's no solution it's not a problem to disable SecureBootModel and setting ApECID to 0.

**Comment by vit9696** [comment]
Well, the real confirmation is usually enabling UEFI Secure Boot and ensure that you can still boot. This kind of makes sure your setup is secure. Other than that you can use I/O Registry and EfiBoot log to see that it is using Secure Boot manifests.

**Comment by dreamwhite** [comment]
Thank you so much: I'll let you know if the Secure Boot works or not :)

**Comment by dreamwhite** [comment]
> Thank you so much: I'll let you know if the Secure Boot works or not :)

After setting ApECID+SecureBootModel and enabling Secure Boot from BIOS settings, I can't boot OpenCore. 
Below the message I receive right when I try to boot OpenCore.

![photo_2020-09-08_09-35-53](https://user-images.githubusercontent.com/17933708/92446861-c1716f00-f1b6-11ea-89bb-f917bc81d194.jpg)

At this point I think that this issue is firmware-related. Am I wrong? 
Thank you

**Comment by vit9696** [comment]
Well, sort of. You did not read the documentation about setting up the UEFI Secure Boot keys.

**Comment by perez987** [comment]
Sorry for this delayed question but when you say "documentation about setting up the UEFI Secure Boot keys" are you talking about generic instructions or one related to OpenCore and UEFI BIOS secure boot specifically? Thanks.

**Comment by mikebeaton** [comment]
OpenCore

**Comment by perez987** [comment]
Thanks. I've read the UEFI secure boot part of OpenCore pdf, also this [article](https://github.com/dortania/OpenCore-Post-Install/blob/c0e7f282975f7d6224878b71648c27ce0ed304e6/universal/security/uefisecureboot.md) by @khronokernel and some other texts about signing boot loader files and shoving keys into the firmware from Linux systems. They all shows that the process seems very hard and away from the knowledge of an average user (like me). It's easy to get macOS secure boot (full security) and vault in OpenCore thanks to your work but I can't go any further.
So for now, secure boot mode in BIOS will remain disabled since it is not essential for windows 10 either.
Anyway thanks for your work and for the answer.
