### ISSUE TITLE
APFS volumes not detected on some laptops - part 2

### ISSUE THREAD

**Issue by maxhartung** [acidanthera/bugtracker#1139]
Hi,

vit9696 I think there was a little misunderstanding regarding what works and what not in which way in the last thread:

https://github.com/acidanthera/bugtracker/issues/1128

Let me please clarify, APFS volumes showed up **only** when I replaced the OpenCore.efi file with the one that you gave me: **"OpenCore-ocjs-r3.zip"**

This is your post from which I used the file:

https://github.com/acidanthera/bugtracker/issues/1128#issuecomment-687805552

Thanks !

So maybe, ApfsDriverLoader should init eariler for some laptops ?

**Comment by Download-Fritz** [comment]
Discussion to be continued in the original ticket.
