### ISSUE TITLE
Stuck trying to upgrade to OC 0.6.1

### ISSUE THREAD

**Issue by seathasky** [acidanthera/bugtracker#1141]
Struggling to upgrade from 0.5.8 to 0.6.1 on Skylake. My 0.5.8 config works flawlessly. I followed the guide to upgrade to 0.6.1 to a T ( I think i've retried doing the config from scratch 8 times now) and still getting error mesasge:

https://imgur.com/a/WICPVi5

OCB: StartImage Failed - Unsupported

Halting on critical error

I've tried different scan policy's as well starting with 0 to a few others ones and still a no go.

I've used https://opencore.slowgeek.com/ sanity checker and my config is perfect according to it.

https://opencore.slowgeek.com/?file=skylake061b55ff8&rs=skylake061

My config.plist: https://drive.google.com/file/d/1QHzF1BPzLzf07hgnWD8UBlF17s9HUE_x/view?usp=sharing

I'm truly at a loss here. Does 0.6.1 not work for Skylake? Did I miss something?

Any help is greatly appreciated!

**Comment by vandroiy2013** [comment]
Hi. 0.6.1 works as before on Skylake. Read about SecureBootModel and use forums for support.

**Comment by seathasky** [comment]
I have securebootmodel disabled my dude, a little help would go a long way. I've been at this for 2 days with no luck.

**Comment by seathasky** [comment]
Whatever, I figured it out.

**Comment by seathasky** [comment]
The config guide say to use "Default" setting instead of disabled. I'm not using nvidia so I just followed the guide but as it turns out "Default" doesnt work for a lot of people. That should probably be fixed in the guide as its misleading. I got it working, but I think the guide needs some tweaking so people dont go a forum rabbit hole.

**Comment by asgmeonerandom** [comment]
> The config guide say to use "Default" setting instead of disabled. I'm not using nvidia so I just followed the guide but as it turns out "Default" doesnt work for a lot of people. That should probably be fixed in the guide as its misleading. I got it working, but I think the guide needs some tweaking so people dont have to go down a forum rabbit hole like I did.

how did you get it working? what did you do to make it to work?

**Comment by seathasky** [comment]
> how did you get it working? what did you do to make it to work?
SecureBootModel = Disabled in config.plist
