### ISSUE TITLE
OC 0.6.1 causes Aquantia AQC107 driver not to load

### ISSUE THREAD

**Issue by gxsolace** [acidanthera/bugtracker#1142]
Tried with OC 0.6.1 and latest AALC 1.5.2, WG 1.42, Lilu 1.4.7 and VirtualSMC 1.1.6: "Driver Installed: No"
Switched to OC 0.6.0 and latest above kexts OR previous August 3 release of above kexts: "Driver installed: Yes"

So it appears it's not the new Kexts released Sept 7, but going from OC 0.6.0 to 0.6.1 impacts Aquantia driver.

(As a side note, also seems to cause Time Machine to ask for inherit existing Time Machine backup, and 2 apps, Owly and 1Password to not load and display a corrupt, redownload message. Rolling back to OC 0.6.0 fixes these problems as well)

**Comment by vit9696** [comment]
Apple Secure Boot prohibits loading unsigned or patched kexts, and you will also need to reinstall previously installed kexts after enabling Apple Secure Boot. Refer to OpenCore reference manual for more details.

**Comment by gxsolace** [comment]
@vit9696 but the driver for it is Apple's. I didn't install any patches or kexts of my own for the AQ card to work natively.

**Comment by vit9696** [comment]
I do not believe it is Apple's. It is externally installed and thus not compatible with Apple Secure Boot as is. The issue is similar to how SoftRAID drivers work (https://www.softraid.com/faq/secureboot), except you need to disable Secure Boot in config.plist.

**Comment by vit9696** [comment]
If you mean the one bundled with the operating system, which you patched before, it may not be present in immutablekernel, and thus will not patch. Your options here are to disable Apple Secure Boot or to use Force injection (but it defeats the purpose of Apple Secure Boot).

**Comment by gxsolace** [comment]
Yeah it is the one bundled with the OS. Was a fresh install of latest Catalina on 0.6.0. Card had worked OOB and I didn't install any 3rd party kexts or patches for it, as it was never required.

**Comment by vit9696** [comment]
Checked immutablekernel, it does have Acquantia drivers. I don't know why it does not work for you, but in any case, it is an Apple problem, not OpenCore's at this point. So, I guess, disabling the secure boot is the only option.

**Comment by gxsolace** [comment]
@vit9696 Okay thank you. I'll give that a shot and report back to you.

**Comment by gxsolace** [comment]
@vit9696 Hi just wanted to followup. Disabling Secure boot fixes all the above issues in my original post. So strange given it's just the bundled driver that came with the system untouched.

**Comment by flipphos** [comment]
> @vit9696 Hi just wanted to followup. Disabling Secure boot fixes all the above issues in my original post. So strange given it's just the bundled driver that came with the system untouched.

I just went exact what you had been through, as well as 1Password to not load and display a corrupt.
I did the same as you pointed out:
Go to Misc - Security, set SecureBootModel to Disabled.
Reboot and now my AQC-107 work OOB again.

Thank you!

**Comment by klebba** [comment]
@gxsolace @vit9696 thank you! Setting SecureBootModel worked for me too: my ACQ107 is now working again after upgrading to OC 0.6.6
