### ISSUE TITLE
DVMT Patch Bug

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#1143]
I am using WEG version 1.4.2 and got this log when boot "Lilu) WhateverGreen      igfx: @ DVMT: This fix is not available on the current platform and has been disabled". However no problem to boot into my system. Just curious about this log
![image](https://user-images.githubusercontent.com/9614101/92473674-1b992100-f205-11ea-8717-e43dc1c3c96e.png)

My specifications 
Intel Core i7 6700
Z170X Gaming 7
No GPU Discrette (Only IGPU),

And i didn't set any DVMT patch in Graphics Properties (config.plist or DSDT/SSDT), and i didn't use and DVMT patch boot argumen too.

Is it bug or not??

**Comment by Andrey1970AppleLife** [comment]
This fix for ICL platforms.
