### ISSUE TITLE
Sample SSDT-PNLF and SSDT-PNLF-CFL do not have macOS-only code, might affect other OS's?

### ISSUE THREAD

**Issue by PhantomR** [acidanthera/bugtracker#1144]
I noticed these two SSDT sources (mentioned in the Dortania guide) do not actually have any code that only runs when macOS is detected as the OS. I must confess I do not understand the meaning of the code in any of them, but many of the other SSDT's I've read did actually contain some macOS-only code (filtered with "if _OSI("Darwin")" or something) . Couldn't these patches affect other OS's if left in this form?

EDIT: Same holds for this: https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-PLUG.dsl

Affected DSDT source files:
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/SSDT-PNLF.dsl
https://github.com/dortania/Getting-Started-With-ACPI/blob/master/extra-files/decompiled/SSDT-PNLF-CFL.dsl.zip

**Comment by Andrey1970AppleLife** [comment]
These ACPI tables have no problems with others OS, therefore the filtration for "Darwin only" is absent.
