### ISSUE TITLE
iasl spits warnings when compiling specific DSDTs

### ISSUE THREAD

**Issue by PhantomR** [acidanthera/bugtracker#1145]
1. When compiling [DSDT-PLUG.dsl](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-PLUG.dsl) I get the following warnings (which definitely look non-harmful since it's probalby just the compiler considering the args not used since the method call is in an if block (my guess)):
![image](https://user-images.githubusercontent.com/15891467/92481977-c1da2c00-f1ef-11ea-90db-a1a1ecd3d5ad.png)

2. When compiling [SSDT-PNLF-CFL.dsl](https://github.com/dortania/Getting-Started-With-ACPI/blob/master/extra-files/decompiled/SSDT-PNLF-CFL.dsl) (and probably also [SSDT-PNLF.dsl](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/SSDT-PNLF.dsl), though I have not tried it) I get a warning that a device object should contain exactly one of _HID and _ADR, but the one indicated has both:

![image](https://user-images.githubusercontent.com/15891467/92482062-db7b7380-f1ef-11ea-91ed-92a21abf687d.png)

**Comment by Andrey1970AppleLife** [comment]
> 2. When compiling [SSDT-PNLF-CFL.dsl](https://github.com/dortania/Getting-Started-With-ACPI/blob/master/extra-files/decompiled/SSDT-PNLF-CFL.dsl) (and probably also [SSDT-PNLF.dsl](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/SSDT-PNLF.dsl), though I have not tried it) I get a warning that a device object should contain exactly one of _HID and _ADR, but the one indicated has both:

This new ACPI specification has appeared recently. You can leave as was or to correct, but in any cases your hardware will normally work.
