### ISSUE TITLE
Incorrect cpu description when PlatformInfo-->Automatic=true and ProcessorType=0

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1149]
System: Mac Os Catalina 10.15.6 (19G2021) virtual machine running on qemu 5.1.0-1 (cpu: host-passthrough)
Opencore updated with commit 0d8cbe0

PlatformInfo-->Automatic=true
ProcessorType: 0
From Apple menu --> System information: Processore: 2 x 3,1 GHz (?WRONG?)
IoRegistry Explorer: cpu-type: 03 09 --> integer 2307 (0x0903)

PlatformInfo-->Automatic=true
ProcessorType: integer 2561 (0x0a01)
From Apple menu --> System information: Processore: 2 x 3,1 GHz Intel Xeon E5 8 core (OK)
IoRegistry Explorer: cpu-type: 01 0a --> integer 2561 (0x0a01)

PlatformInfo-->Automatic=false
ProcessorType: integer 2561 (0x0a01)
From Apple menu --> System information: Processore: 2 x 3,1 GHz Intel Xeon E5 8 core (OK)
IoRegistry Explorer: cpu-type: 01 0a --> integer 2561 (0x0a01)

My CPUs:
2x Intel Xeon E5-2687w (Sandy Bridge, first version): these are engineering (quality) samples stepping C0 (QB7R).
I think the correct description in System information should be "3,1 GHz Intel Xeon E5 8 core", so I'm injecting 2561.

As suggested also with commit 78f0907 PlatformInfo --> Automatic=true should be preferred without changing ProcessorType, so I'm attaching dmidecode output, machdep.cpu output and CPUID dump.

Thanks
[machdep.cpu-output.txt](https://github.com/acidanthera/bugtracker/files/5207261/machdep.cpu-output.txt)
[dmidecode-output.txt](https://github.com/acidanthera/bugtracker/files/5207262/dmidecode-output.txt)
[CPUID-dump.txt](https://github.com/acidanthera/bugtracker/files/5207667/CPUID-dump.txt)

**Comment by vit9696** [comment]
Well, engineering sample CPU detection without the brandstrings is really hard to be accurate. I believe there was some room for improvement and fixed it, but I cannot say that for all such CPUs we can provide a fix in the future. Please report.

**Comment by 82ghost82** [comment]
Working good here vit9696.
I perfectly understand what you say, there are so many engineering samples, some differ also with the same stepping.
And not so many people have engineering samples, and of these people not all are running opencore :D
I wasn't sure to open this "bug", as this is not really a bug, and can be bypassed with the processortype injection, so I thank you very much for this commit.

**Comment by CrazyHulk** [comment]
> Working good here vit9696.
> I perfectly understand what you say, there are so many engineering samples, some differ also with the same stepping.
> And not so many people have engineering samples, and of these people not all are running opencore :D so it's more difficult to have dumps.
> I wasn't sure to open this "bug", as this is not really a bug, and can be bypassed with the processortype injection, so I thank you very much for this commit.

Did u make it works as u expect? I  have a wrong description in System information with engineering sample CPU.

**Comment by vit9696** [comment]
If it is not an engineering sample — submit a new issue withe the files included as above.

**Comment by AYastrebov** [comment]
Hello @vit9696 
I've purchased another unknown CPU [QQLT](https://aliexpress.ru/item/QQLT-000-2-4G-6C12T-BGA-CPU-TO-LGA1151-CPU-Modified-Laptop-CPU-TO-LGA1151-CPU/4001201791037.html)

Basically, it's a Coffee Lake laptop cpu, but unfortunately, it's recognized as unknown. Attaching some dumps, hope they can help. Maybe you'll be able to add it for future versions. Thanks!

[dmidecode.txt](https://github.com/acidanthera/bugtracker/files/5770259/dmidecode.txt)
[machdepcpu.txt](https://github.com/acidanthera/bugtracker/files/5770260/machdepcpu.txt)

**Comment by 1alessandro1** [comment]
There's the option to specify processor:

![image](https://user-images.githubusercontent.com/46293832/103662269-05f7f600-4f70-11eb-8601-00859841487b.png)


Read configuration.pdf, can be found [here](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf)

Use CMD+F to filter your search
