### ISSUE TITLE
AppleALC distorts audio when using DAW software.

### ISSUE THREAD

**Issue by zJustSimple** [acidanthera/bugtracker#1150]
Hello, fiddled around with AppleALC to fix my ALC233. Sound works after switching out the Catalina's AppleHDA.kext to a Mojave one but there's one issue: It doesn't seem to like DAW's in general (which is the main reason I built this hackintosh for). Tested with Logic Pro X and FLStudio 20 at the moment: After setting up the DAW, setting the output device to "Built in Output" any sound from the DAWs get's distorted and that persists even after closing the DAW until I restart the machine. I'm running stock Catalina, AppleALC 1.5.2 and Lilu 1.4.7.

**Comment by Andrey1970AppleLife** [comment]
We aren't engaged in editing of resources for HDA. We accept PR with resources from users.
Send PR with good resources for your codec if you find the solution.
