### ISSUE TITLE
WhateverGreen: Support for Coffee Lake and Comet Lake Xeon iGPUs

### ISSUE THREAD

**Issue by XStylus** [acidanthera/bugtracker#1151]
In version 1.4.0 of WhateverGreen, support for Comet Lake and Coffee Lake iGPU Device IDs was added for the Core series processors, though the Xeon series would benefit from being added as well:

`{ 0x9BC6, 0x9BC4, "Intel UHD Graphics P630" },`
`{ 0x9BC6, 0x0000, "Intel UHD Graphics 630" },`
`{ 0x9BE6, 0x0000, "Intel UHD Graphics 630" },`
`{ 0x3E94, 0x3E91, "Intel UHD Graphics P630" },`
`{ 0x3E94, 0x0000, "Intel UHD Graphics 630" },`
`{ 0x3E9A, 0x3E91, "Intel UHD Graphics P630" },`
`{ 0x3E9B, 0x3E91, "Intel UHD Graphics P630" },`
`// Note, on some CPUs Intel uses the same DevID between the P630 and 630.`

0x9BC6 - Intel UHD Graphics P630 - Comet Lake
Xeon W-1270
Xeon W-1250P
Xeon W-1290T
Xeon W-1250
Xeon W-1290P
Xeon W-1290
Xeon W-1270P
Xeon W-1290TE

0x9BC6 - Intel UHD Graphics 630 - Comet Lake
Xeon W-1290E
Xeon W-1270E
Xeon W-1270TE

0x9BE6 - Intel UHD Graphics 630 - Comet Lake
Xeon W-1250E
Xeon W-1250TE

0x3E94 - Intel UHD Graphics P630 - Coffee Lake
Xeon E-2276ME
Xeon E-2276ML
Xeon E-2254ME
Xeon E-2254ML
Xeon E-2276M
Xeon E-2286M

0x3E9A - Intel UHD Graphics 630 - Coffee Lake
Xeon E-2278GEL
Xeon E-2278GE
Xeon E-2226GE

0x3E9A - Intel UHD Graphics P630 - Coffee Lake
Xeon E-2288G
Xeon E-2278G

0x3E9B - Intel UHD Graphics P630 - Coffee Lake
Xeon E-2176M
Xeon E-2186M

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/WhateverGreen/commit/8eac7ce307297abc8bc7cb1d279e8d861c23ad05

**Comment by XStylus** [comment]
There was a typo in my report. I'm not sure if this make a difference, but I figured I'd mention anyway:

`{ 0x9BC6, 0x9BC4, "Intel UHD Graphics P630" },` should be `{ 0x9BC6, 0x9BC5, "Intel UHD Graphics P630" },` 
and
`{ 0x9BE6, 0x9BC4, "Intel UHD Graphics P630" },` should be `{ 0x9BE6, 0x9BC5, "Intel UHD Graphics P630" },`

This is because 0x9BC5 is a natively supported DevID in Catalina 10.15.6, whereas 0x9BC4 is not.
