### ISSUE TITLE
Docs: bootercfg serial= numbering confusion

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#1153]
NVRAM->Other Variables lists range (0 .. 4) for bootercfg serial=, while Troubleshooting->Debugging (section 2) lists serial=5.

**Comment by vit9696** [comment]
These are different things. `serial` in `Troubleshooting` is a boot argument, and `serial` in `NVRAM` is a variable. I will add an extra `boot` prefix to make it clear.
