### ISSUE TITLE
Request Whatevergreen Intel 1065g7 backlight

### ISSUE THREAD

**Issue by thefiredragon** [acidanthera/bugtracker#1157]
Dear all for this nice work over all the time,
I have a little question here, is there also an support forum for whatevergreen or opencore specially? 

I owned a new yoga slim 7 with an Intel 1065g7 & Intel Iris GT7 Graphic Card,
the ig-platfrom-id 0000528A is the only one which is working better with external screen.

Backlight level is to low at maximal position of the backlight slider in settings prefpane.
I read under releases I could adjust these values:
Added applbkl aliases to IORegistry (data, 32-bit)
Added applbkl-name and applbkl-data IORegistry data keys to provide custom backlight data

But first I would like to know how I could determinate the right pwm max values and name for these patches or are these patches deprecated?

best Regards, Dan

**Comment by vit9696** [comment]
Well, um, I think we just borrowed these from the legacy generation, and the PWM MAX values come from Intel manuals and Linux drivers. I do not think we have stuff nearby, as it was mostly contributed externally. Perhaps you will find more luck if you consult to the origin of this data.

**Comment by Andrey1970AppleLife** [comment]
For CFL+ use SSDT-PNLFCFL https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#adjusting-the-brightness-on-a-laptop
