### ISSUE TITLE
Capslock LED problems

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#1158]
Hi found capslock led issue.

Capslock led issue summary 

**#1.turn on option. "Use The Caps Lock key to switch to and ABC"**
1 case. -> only english, everything fine.
-> after boot, default capslock led is off.
-> default english, capslock led is no problem. turn on/off is good.
2 case. -> both EN and KR
-> after boot, default capslock led is off.
-> default english, change en to kr, capslock led is gone. never capslock led on again.
3 cases. -> both EN and KR
-> after boot, default capslock led is off.
-> default english, press capslock(led on), then change en to kr, always capslock led is on.

as result, when using two language, capslock led is not properly working.

**#2. turn off option. "Use The Caps Lock key to switch to and ABC"**
-> everything is good. No problem if you use both languages.

thanks in advance

**Comment by Mateo1234454545** [comment]
Same here

**Comment by vit9696** [comment]
Closing as a duplicate. Continue in #753
