### ISSUE TITLE
[KBL-R, UHD 620] Colour banding

### ISSUE THREAD

**Issue by EETagent** [acidanthera/bugtracker#1159]
> In macOS 10.14 оn some laptops with KBL graphics one may face visual artifacts on the gradients. For a temporary solution try to fake IGPU to use SKL drivers.

Hello, thanks for your hard work on OpenCore and Lilu/WEG. I would like to resurrect old issue with colour banding on Kaby Lake Refresh GPUs. Tried many KBL-R ig-platform-id's `00001659`, `0000C087`, etc. but they are useless as still only working solution for this problem is to spoof Skylake's HD520, which fixes this issue for me and others. That's apparently not optimal as there are quite a big differences in codec support between these GPUs, Lilu must be also configured for Skylake with `lilucpu=8`, and HEVC encoding does not work completely right. This problem is not exactly that rare as for example many T480 ThinkPads with stock Full HD screen are affected by this, machines upgraded with T490 FHD screen apparently not though. Because some time has passed since this was reported on Mojave, was there any progress on this front? It's possible to fix it while preserving UHD 620? Will provide WEG logs if necessary. Thanks for your time.

```
<key>AAPL,ig-platform-id</key>
<data>AAAWWQ==</data>
<key>device-id</key>
<data>FlkAAA==</data>
<key>framebuffer-fbmem</key>
<data>AACQAA==</data>
<key>framebuffer-patch-enable</key>
<data>AQAAAA==</data>
<key>framebuffer-portcount</key>
<data>AwAAAA==</data>
<key>framebuffer-stolenmem</key>
<data>AAAwAQ==</data>
<key>framebuffer-unifiedmem</key>
<data>AAAAgA==</data>
```

OC 0.6.1 | WhateverGreen 1.4.2 | Lilu 1.4.7
macOS 11 Beta, macOS 10.15.6 Catalina

**Comment by Andrey1970AppleLife** [comment]
No progress

**Comment by benbender** [comment]
may those errors related or are they expected in that context?

```
[   10.881894]: WhateverGreen       weg: @ (DBG) failed to obtain display mode
[   10.881912]: WhateverGreen       weg: @ (DBG) failed to obtain display mode
[   10.881915]: WhateverGreen       weg: @ (DBG) failed to obtain display mode
[   10.881918]: WhateverGreen       weg: @ (DBG) failed to obtain display mode
[   10.980874]: WhateverGreen       weg: @ (DBG) fb info 1: -2147479552:0 7680:0:32
[   10.980878]: WhateverGreen       weg: @ (DBG) fb info 2: 3:8 --------RRRRRRRRGGGGGGGGBBBBBBBB 0:1920:1080
```

**Comment by brkbrlz16** [comment]
Can we revive this thread? Since SKL kexts are gone on Ventura we're not able to spoof KBL as SKL aynmore. It's gonna be either use newer macOS with horrible display quality or stay on Monterey until it gets discontinued situation after October. Same colour banding is present on regular HD620 with the device id 5916 and this is another Lenovo laptop. @Andrey1970AppleLife
