### ISSUE TITLE
OpenCore and UEFI boot priority

### ISSUE THREAD

**Issue by mishurov** [acidanthera/bugtracker#1160]
I use grub as my primary bootloader and for MacOS I use a custom grub entry, with Clover everything works fine. OpenCore, though, always sets itself as a first entry in the UEFI boot order. And instead of grub it loads first at boot so I basically can't boot into Linux unless I change UEFI settings back. I tried various settings in config.plist nothing seems to affect that behaviour. Is it intended or I can prevent somehow OpenCore from modifying UEFI boot order?

Tried OpenCore 0.6.0 and 0.6.1, both behave similarly.

**Comment by khronokernel** [comment]
See BootProtect quirk in the docs:
* https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf

**Comment by mishurov** [comment]
Thank you. Now it works as expected. Strangely enough, I skimmed through this pdf earlier, didn't come to mind to look into the Docs directory now.

**Comment by nickthewitcher** [comment]
Hi @mishurov , how did you make it? What did you change to fix the problem?

**Comment by mishurov** [comment]
@nickthewitcher see BootProtect quirk in the docs:

- https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf

**Comment by MikeBeaton** [comment]
`BootProtect` has been replaced, see 0.6.6 changes in Changlog.md.

**Comment by mishurov** [comment]
@MikeBeaton I have `LauncherOption` set to `Disabled`. And I put `BOOTx64.efi` into `EFI/OC` together with `OpenCore.efi`, so it doesn't interfere with Debian, grub entry has this line `chainloader /EFI/OC/BOOTx64.efi`
