### ISSUE TITLE
[AirportBrcmFixup] CoreWlan version "((null))"

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1161]
Hi there,
I own a DW1830 wifi card, which is fully working on macOS (WiFi 2.4/5 GHz, BT and Airdrop). 
I noticed that under SystemReport/Network/WiFi, `CoreWLAN`, `CoreWLANKit` and `Menu Extra` version value are "((null))". Is this even normal? 

Below a screenshot for better understanding

![image](https://user-images.githubusercontent.com/17933708/93356287-49065000-f83f-11ea-9d4d-557b087ab8f6.png)

Please note that I'm using AirportBrcmFixup v2.0.9 with `brcmfx-country=#a`.
I apologize if this isn't even an issue but I'd like to understand if this is fine or not.
Thanks

**Comment by Andrey1970AppleLife** [comment]
It is normal

**Comment by dreamwhite** [comment]
Perfect, thank you so much! :)
