### ISSUE TITLE
[SMBIOS] MSI Dragon Center not detecting motherboard

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1162]
Hi there,
I'm helping a user with the following components:

- **CPU**: RYZEN 1600X 
- **GPU**: ASUS STRIX 580 TOP EDITION
- **MOBO**: MSI X370 PRO CARBON

Everything is working fine with OpenCore except MSI Dragon Center if the user boots Windows from OpenCore.
Below a screenshot of Speccy when Windows is booted without OpenCore...

![image](https://user-images.githubusercontent.com/17933708/93359535-02b2f000-f843-11ea-8c40-3334b68ea3ad.png)

... and with OpenCore:

![image](https://user-images.githubusercontent.com/17933708/93359614-178f8380-f843-11ea-9940-7f74fd73b877.png)

![msi](https://user-images.githubusercontent.com/17933708/93359914-66d5b400-f843-11ea-8159-d6a84c022712.png)

I know that OpenCore injects SMBIOS and ACPI to every OS booted from it but we can't figure out how to fix this issue.
Do you have any advice? 
Thanks in advance

**Comment by Andrey1970AppleLife** [comment]
Use forums for support

**Comment by asgmeonerandom** [comment]
Use clover then?
https://github.com/CloverHackyColor/CloverBootloader/issues/238

**Comment by dreamwhite** [comment]
> Use clover then?
> [CloverHackyColor/CloverBootloader#238](https://github.com/CloverHackyColor/CloverBootloader/issues/238)

Thank you so much. It's working :)
