### ISSUE TITLE
More unique GUID OC log protocol

### ISSUE THREAD

**Issue by cecekpawon** [acidanthera/bugtracker#1164]
Change / replace OC_LOG_PROTOCOL_GUID / gOcLogProtocolGuid to more unique GUID to avoid confusion / internal error with Ozmosis / maybe other project. 

```
D:\src\Work\Source\Acidanthera\OpenCorePkg\Include\Acidanthera\Protocol\OcLog.h:
   41  **/
   42  #define OC_LOG_PROTOCOL_GUID      \
   43:   { 0xDBB6008F, 0x89E4, 0x4272,   \
   44      { 0x98, 0x81, 0xCE, 0x3A, 0xFD, 0x97, 0x24, 0xD0 } }
   45  

D:\src\Work\Source\Acidanthera\OpenCorePkg\OpenCorePkg.dec:
  485  
  486    ## Include/Acidanthera/Protocol/OcLog.h
  487:   gOcLogProtocolGuid                         = { 0xDBB6008F, 0x89E4, 0x4272, { 0x98, 0x81, 0xCE, 0x3A, 0xFD, 0x97, 0x24, 0xD0 }}
  488  
  489    ## Include/Acidanthera/Protocol/OcAfterBootCompat.h
```

**Comment by vit9696** [comment]
This protocol originates from the original OpenCore and in fact even shares some code portions. Since there are drivers that rely on this protocol being present and functional changing the GUID will require recompiling these drivers, I do not believe the change is practical.
