### ISSUE TITLE
MacOS partition not visible with 0.6.1

### ISSUE THREAD

**Issue by prabs77** [acidanthera/bugtracker#1165]
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5249111/EFI.zip)
[opencore-2020-09-19-044007.txt](https://github.com/acidanthera/bugtracker/files/5249112/opencore-2020-09-19-044007.txt)

I have a working setup with 0.6.0 on my HP 840 G1 laptop, but I have to use the apfsdriverloader.efi to make the MacOS partition or the recovery partition to be visible. I tried to upgrade to 0.6.1 today; but even apfsdriver, the MacOS partition is not visible. I downgraded back to 0.6.0 and everything works. Any ideas?

**Comment by 1alessandro1** [comment]
https://github.com/acidanthera/bugtracker/issues/1128

**Comment by singhalrishi27** [comment]
Bro try opencore 0.6.2 unreleased/beta(was fixed in it)
And make sure
Unblockfsconnect=true
ConnectDrivers=True
