### ISSUE TITLE
Big sur installation relies on working nvram, internet recovery can't reach phase 2

### ISSUE THREAD

**Issue by s0ullight** [acidanthera/bugtracker#1167]
Unlike Catalina, istalling Big Sur on a system with broken nvram fails. OpenCore fails to boot macOS Installer (phase 2) after internet recovery.

Using the beta install app macOS Installer boots fine if Catalina was setup with emulated nvram.

Since phase 2 can't modify nvram, phase 3 results in a bootloop. My initial guess is that it is related to "patchd: patchd_block_invoke(640): Unable to attempt update: target volume uuid not set in nvram".

This is all using OpenCore 0.6.1 and the latest kexts.

**Comment by OmerFlame** [comment]
Finally, someone having the same issue.

I have been struggling.

**Comment by vit9696** [comment]
Well, it is not a problem of OpenCore that your NVRAM is broken.

**Comment by s0ullight** [comment]
May that as it be, should this not be verified and documented?

**Comment by vit9696** [comment]
Documenting beta behaviour is out if our concern.

**Comment by andreszerocross** [comment]
Yes,, it's happened here.

Try to use MacPro6,1 as SMBIOS in system Dell Dell Optiplex 790 SFF SandyBridge (legacy Boot),, 

Can pass second phase installation, always reboot with this error. Non working NVRAM.
