### ISSUE TITLE
Lilu and whatevergreen are missing executable on Dortania precompiled

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1170]
With recent commits to lilu and whatevergreen  I downloaded precompiled kexts from Dortania:
https://dortania.github.io/builds/

Rebooted and the system hanged on critical error.
Further investigation pointed that lilu executable was missing in Contents/MacOS folder

Same issue for Whatevergreen, it's missing executable file.
AppleALC and virtualSMC seem ok.

Affected versions I checked (there can be others, I didn't check):
Lilu debug commit 2b88157
Whatevergreen debug f31896e

**Release versions are not affected**

![weg](https://user-images.githubusercontent.com/18054052/93853130-91949200-fcb3-11ea-92c7-b00dd5638478.png)
![lilu](https://user-images.githubusercontent.com/18054052/93853131-922d2880-fcb3-11ea-8f4a-603afdcff32b.png)

**Comment by 82ghost82** [comment]
Not sure, but I downloaded again and all it's ok now...

**Comment by vit9696** [comment]
Dortania issues should be reported to dortania/bugtracker.
