### ISSUE TITLE
VirtualSMC: Can't update macos Big Sur Beta without vsmcgen=1 on macmini8,1 model

### ISSUE THREAD

**Issue by pavelchup** [acidanthera/bugtracker#1171]
Hello, the issue is i can't install update on macmini8,1 model, in ioreg version of SMC is missing, with vsmcgen=1 boot argument, version of SMC coming back, and then a can update, on different mac model no problem

![Снимок экрана 2020-09-22 в 11 30 07](https://user-images.githubusercontent.com/38374292/93860469-d3c7ce80-fcc7-11ea-8907-3f5eb97abba0.png)

**Comment by vit9696** [comment]
Is that the latest VSMC version? Not reproducible here. Please provide the debug logs of VirtualSMC startup via serial. Also check other models T2 (e.g. iMacPro1,1 or MacPro7,1) and non-T2 (e.g. iMac19,1).

**Comment by pavelchup** [comment]
I use the latest VSMC, no problem with iMac19,2

**Comment by vit9696** [comment]
Please read carefully what I said. Testing just mm8,1 from the T2 model list is not enough to be sure. It is also not possible to tell what is broken without the kernel log and a broader description of what exactly happens.

**Comment by pavelchup** [comment]
Here is kernel log and OC boot log
[opencore-2020-09-22-090727.txt.zip](https://github.com/acidanthera/bugtracker/files/5260359/opencore-2020-09-22-090727.txt.zip)
[kernel_log.zip](https://github.com/acidanthera/bugtracker/files/5260361/kernel_log.zip)

**Comment by vit9696** [comment]
Is that the log during macOS when it froze or what? If not, that's what I need.

**Comment by pavelchup** [comment]
Yes this is regular kernel log during boot 10.15.6

**Comment by pavelchup** [comment]
> Is that the log during macOS when it froze or what? If not, that's what I need.

Yes this is kernel log from 10.15.6, i can also boot Big Sur without vsmcgen=1 after update, it's needed only when install update.

**Comment by vit9696** [comment]
Well, regular kernel log is useless. Need the one during updating to 11.0. You might have to do serial capturing or screen capturing with `-liludbgall`.

**Comment by pavelchup** [comment]
Maybe when next update coming, i remember when try to update, it stop to boot at line **We don't support smc on this platform** and then reboots, i searched the forum, and finded same screen here

https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2728809

**Comment by pavelchup** [comment]
Hi, today I tried to upgrade to Big Sur Beta 8 with kexts and OC from master, and update going smooth, without vsmcgen=1... so I think the problem is gone, I did screen capturing with -liludbgall to log, maybe it helps others
[Lilu_1.4.8_20.1.txt.zip](https://github.com/acidanthera/bugtracker/files/5266329/Lilu_1.4.8_20.1.txt.zip)
