### ISSUE TITLE
High Sierra - Opencore Boot loop after 2020-004 Security Update

### ISSUE THREAD

**Issue by Chibibowa** [acidanthera/bugtracker#1172]
Hello, when I install High Sierra (on a laptop), all goes well and boots fine. But at the moment I make the latest security update (combo or MAS, doesn't matter). There is a boot loop with Opencore and it fails to initiate the booting process. The installation of the update worked but when it's time to boot again like normal, it fails. Just to be clear, it does not fail to boot when it's time to reboot to update, it fails AFTER the update completed.

Here is a quick video of what is happening: https://cdn.discordapp.com/attachments/757762783742787716/757763098018054164/video0.mov

USB Boot demo (works fine, same EFI folder of course): https://cdn.discordapp.com/attachments/757762783742787716/757765758595104939/video0.mov

The target is a SATA SSD using APFS.

**Comment by vit9696** [comment]
Please attach the OpenCore debug log. Maybe it is a secure boot issue? Did you try disabling secure boot and/or copying the updated manifests?
