### ISSUE TITLE
BT4LEContinuityFixup: "FeatureFlags" is not changed after patch

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [acidanthera/bugtracker#1173]
Hi,

I'm on 10.15.6 (19G2021), using latest Lilu and latest BT4LEContinuityFixup(Downloaded and built from source).

I was trying to resolve continuity only works single direction, and I noticed Continuity Activation Tool is checking `FeatureFlags` to see whether it is `15`. It also contains `7`, and it means not fully activated. 

On my machine, I have a BCM20704 (BT851 USB Dongle), and the raw `FeatureFlags` is 7 before patching.

With BT4LEContinuityFixup enabled, I can see:

```
kernel: (Lilu) BT4LEContinuityFixup      init: @ (DBG) BT4LEContinuityFixup bootstrap DBG-116-2020-09-23
kernel: (Lilu) BT4LEContinuityFixup   bt4lefx: @ (DBG) com.apple.iokit.IOBluetoothFamily
kernel: (Lilu) BT4LEContinuityFixup   bt4lefx: @ (DBG) routed __ZN25IOBluetoothHostController25SetControllerFeatureFlagsEj
```

Which means the patch has been applied successfully, however, I see no invoke for the patched method. Moreover, `FeatureFlags` remains to be 7 so Continuity still works partially.

I tried to patch `__ZN36AppleBroadcomBluetoothHostController25SetControllerFeatureFlagsEj` in the same way, and even force `__ZN25IOBluetoothHostController25GetControllerFeatureFlagsEv` to return 15, no luck. These two method are not called either.

```
kernel: (Lilu) BT4LEContinuityFixup      init: @ (DBG) BT4LEContinuityFixup bootstrap DBG-116-2020-09-23
kernel: (Lilu) BT4LEContinuityFixup   bt4lefx: @ (DBG) com.apple.iokit.IOBluetoothFamily
kernel: (Lilu) BT4LEContinuityFixup   bt4lefx: @ (DBG) routed __ZN25IOBluetoothHostController25SetControllerFeatureFlagsEj
kernel: (Lilu) BT4LEContinuityFixup   bt4lefx: @ (DBG) routed __ZN36AppleBroadcomBluetoothHostController25SetControllerFeatureFlagsEj
kernel: (Lilu) BT4LEContinuityFixup   bt4lefx: @ (DBG) routed __ZN25IOBluetoothHostController25GetControllerFeatureFlagsEv
```

What I did is just duplicate the code and modify the symbol:

```c++
int BT4LEFX::newIOBluetoothHostController_SetControllerFeatureFlags(void *that, unsigned int)
{
	DBGLOG("bt4lefx", "IOBroadcomBluetoothHostController::SetControllerFeatureFlags is called");
	int result = FunctionCast(newIOBluetoothHostController_SetControllerFeatureFlags,
							  callbackBT4LEFX->orgIOBluetoothHostController_SetControllerFeatureFlags)(that, 0x0F);
	DBGLOG("bt4lefx", "IOBluetoothHostController::SetControllerFeatureFlags returned %d", result);

	return result;
}

int BT4LEFX::newAppleBluetoothHostController_SetControllerFeatureFlags(void *that, unsigned int)
{
	DBGLOG("bt4lefx", "AppleBroadcomBluetoothHostController::SetControllerFeatureFlags is called");
	int result = FunctionCast(newAppleBluetoothHostController_SetControllerFeatureFlags,
							  callbackBT4LEFX->orgAppleBluetoothHostController_SetControllerFeatureFlags)(that, 0x0F);
	DBGLOG("bt4lefx", "AppleBluetoothHostController::SetControllerFeatureFlags returned %d", result);

	return result;
}

unsigned int BT4LEFX::newIOBluetoothHostController_GetControllerFeatureFlags(void *that, unsigned int)
{
	DBGLOG("bt4lefx", "IOBroadcomBluetoothHostController::GetControllerFeatureFlags is called");
	DBGLOG("bt4lefx", "IOBluetoothHostController::GetControllerFeatureFlags returned 0x0f");

	return 0x0f;
}



void BT4LEFX::processKext(KernelPatcher &patcher, size_t index, mach_vm_address_t address, size_t size)
{
	if (kextIOBluetooth.loadIndex == index) {
		DBGLOG("bt4lefx", "%s", kextIOBluetooth.id);
		
		const char* symbol = (getKernelVersion() > KernelVersion::Yosemite) ?
			"__ZN25IOBluetoothHostController25SetControllerFeatureFlagsEj" :
			"__ZN24IOBluetoothHCIController25SetControllerFeatureFlagsEj";

		KernelPatcher::RouteRequest request {
				symbol,
				newIOBluetoothHostController_SetControllerFeatureFlags,
				orgIOBluetoothHostController_SetControllerFeatureFlags
		};
		patcher.routeMultiple(index, &request, 1, address, size);
		if (patcher.getError() == KernelPatcher::Error::NoError) {
			DBGLOG("bt4lefx", "routed %s", symbol);
		} else {
			SYSLOG("bt4lefx", "failed to resolve %s, error = %d", symbol, patcher.getError());
			patcher.clearError();
		}
		
		const char* symbol2 = "__ZN36AppleBroadcomBluetoothHostController25SetControllerFeatureFlagsEj";

		KernelPatcher::RouteRequest request2 {
				symbol2,
				newAppleBluetoothHostController_SetControllerFeatureFlags,
				orgAppleBluetoothHostController_SetControllerFeatureFlags
		};
		patcher.routeMultiple(index, &request2, 1, address, size);
		if (patcher.getError() == KernelPatcher::Error::NoError) {
			DBGLOG("bt4lefx", "routed %s", symbol2);
		} else {
			SYSLOG("bt4lefx", "failed to resolve %s, error = %d", symbol2, patcher.getError());
			patcher.clearError();
		}
		
		const char* symbol3 = "__ZN25IOBluetoothHostController25GetControllerFeatureFlagsEv";

		KernelPatcher::RouteRequest request3 {
				symbol3,
				newIOBluetoothHostController_GetControllerFeatureFlags,
				orgIOBluetoothHostController_GetControllerFeatureFlags
		};
		patcher.routeMultiple(index, &request3, 1, address, size);
		if (patcher.getError() == KernelPatcher::Error::NoError) {
			DBGLOG("bt4lefx", "routed %s", symbol3);
		} else {
			SYSLOG("bt4lefx", "failed to resolve %s, error = %d", symbol3, patcher.getError());
			patcher.clearError();
		}
		
		
	}
}
```

**Comment by usr-sse2** [comment]
Confirm, also have 7.

**Comment by lvs1974** [comment]
Unfortunately I don't have any devices to check this feature.
And as far as I remember I just adapted this fix, but I have no idea what it does.
Can somebody find out when exactly this kexts stopped working?

**Comment by usr-sse2** [comment]
`__ZN25IOBluetoothHostController25GetControllerFeatureFlagsEv` is routed incorrectly: the function should be `unsigned int BT4LEFX::newIOBluetoothHostController_GetControllerFeatureFlags(void *that)`

**Comment by lvs1974** [comment]
@jqqqqqqqqqq: could you try to fix routing for GetControllerFeatureFlags and chek, please?

**Comment by usr-sse2** [comment]
If it's not called, it won't help. And also it won't change in the ioreg and in the private field, so probably this won't work.

**Comment by jqqqqqqqqqq** [comment]
According to the log it is not called. I’ll try the fix you suggested in the weekend.

BTW it is weird on my native BCM94360, even feature flag is 15, I still need this kext otherwise unlock with apple watch just timeouts. With this it works nearly 100% times

**Comment by usr-sse2** [comment]
I’ll look more deeply into this issue during next few days. Have one idea

**Comment by usr-sse2** [comment]
The issue is that BT4LEContinuityFixup applies the patches after IOBluetoothFamily has already started and `SetControllerFeatureFlags` executed. You can verify that by unplugging and replugging your Bluetooth module, if it's external, or sleeping and waking the computer. After reconnection, the patched method will be executed and `FeatureFlags` will become 15.
The temporary workaround is to move Lilu to the first position and BT4LEContinuityFixup to the second position in OpenCore, so they would load earlier. However, this should not be reliable: this is still a race between BT4LEContinuityFixup and IOBluetoothFamily. The actual solution will be implementing a fake driver that attaches to the device and prevents IOBluetoothFamily from attaching too early, like it's done in AirPortBrcmFixup.

**Comment by usr-sse2** [comment]
About unlock with Apple Watch, for me it worked once (Bluetooth: BCM20702A3, Wi-Fi: Intel 8265 with modified AirportItlwm that I've not yet published) after I added BrcmPatchRAM3, but after sleep it stopped working and then never worked again. It successfully enables but doesn't send the unlock request to Apple Watch.

**Comment by lvs1974** [comment]
@usr-sse2: it seems you are right:
![Screenshot 2020-09-30 at 10 49 09](https://user-images.githubusercontent.com/27740976/94663958-93410400-030a-11eb-8f2f-d821496d69e1.png)

The question is: how can we implement a fake device postponing loading of IOBluetoothHCIController?
In AirportBrcmFixup we can use score since the same vendor & device ids matched, but IOBluetoothFamily is loaded unconditionally.

**Comment by lvs1974** [comment]
I think we could get a reliable solution using __ZN25IOBluetoothHostController25GetControllerFeatureFlagsEv (if it works somehow). I mean a kernel patch in OpenCore using Base = _ZN25IOBluetoothHostController25GetControllerFeatureFlagsEv and Replace = code just returning 15!

**Comment by lvs1974** [comment]
In 10.14.6:
```
__text:00000000000433F2 ; Attributes: bp-based frame
__text:00000000000433F2
__text:00000000000433F2 ; __int64 __fastcall IOBluetoothHostController::SetControllerFeatureFlags(IOBluetoothHostController *__hidden this, unsigned int)
__text:00000000000433F2                 public __ZN25IOBluetoothHostController25SetControllerFeatureFlagsEj
__text:00000000000433F2 __ZN25IOBluetoothHostController25SetControllerFeatureFlagsEj proc near
__text:00000000000433F2                                         ; DATA XREF: __const:00000000000A47E0↓o
__text:00000000000433F2                                         ; __const:00000000000A6130↓o
__text:00000000000433F2                                         ; __const:00000000000A9460↓o
__text:00000000000433F2                                         ; __const:00000000000AAD70↓o
__text:00000000000433F2                 push    rbp
__text:00000000000433F3                 mov     rbp, rsp
__text:00000000000433F6                 mov     [rdi+38Ch], esi
__text:00000000000433FC                 mov     edx, esi
__text:00000000000433FE                 mov     rax, [rdi]
__text:0000000000043401                 mov     rax, [rax+280h]
__text:0000000000043408                 lea     rsi, aFeatureflags ; "FeatureFlags"
__text:000000000004340F                 mov     ecx, 20h ; ' '
__text:0000000000043414                 pop     rbp
__text:0000000000043415                 jmp     rax
__text:0000000000043415 __ZN25IOBluetoothHostController25SetControllerFeatureFlagsEj endp
```

**Comment by lvs1974** [comment]
Can somebody try the following kernel patch in OpenCore:
Arch = x86_64
Base = __ZN25IOBluetoothHostController25GetControllerFeatureFlagsEv
Find (must be empty)
Identifier = kernel
Enabled = YES
Replace = b8 0f 00 00 00 c3

**Comment by jqqqqqqqqqq** [comment]
> Can somebody try the following kernel patch in OpenCore:
> Arch = x86_64
> Base = __ZN25IOBluetoothHostController25GetControllerFeatureFlagsEv
> Find (must be empty)
> Identifier = com.apple.iokit.IOBluetoothFamily
> Enabled = YES
> Replace = b8 0f 00 00 00 c3
> 
> BT4LEContinuityFixup must be turned off in config.plist.
> 
> UPD: Fixed `Identifier` (_by vit9696_)

@lvs1974 Seems not effective, I still see 0x7. Guess this method is not called? Logs from my BCM94360NG (which is actually a BCM94360CD) with BT4LEContinuityFixup has logs on booting shows setfeatureflags has been called three times.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/12872927/94759017-cae09800-036c-11eb-8a78-727f012b764f.png">

Here is my bluetooth info, is it possible that calling this method has some prerequisites? (Just a wild guess, assuming default value is 0x7)

BTW tried using injector to change IOBluetoothHostControllerUSBTranport to Broadcom one, no difference.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/12872927/94759060-e5b30c80-036c-11eb-8f45-c32d62deacdd.png">

**Comment by jqqqqqqqqqq** [comment]
> About unlock with Apple Watch, for me it worked once (Bluetooth: BCM20702A3, Wi-Fi: Intel 8265 with modified AirportItlwm that I've not yet published) after I added BrcmPatchRAM3 (and I wasn't using BT4LEContinuityFixup), but after sleep it stopped working and then never worked again. It successfully enables but doesn't send the unlock request to Apple Watch.

Unlock with Apple Watch seems to be working for the first unlock on some third party WiFi/bluetooth and then timeouts forever. For Apple WiFi/bluetooth it works fine as long as the bluetooth signal is strong enough.

**Comment by jqqqqqqqqqq** [comment]
@lvs1974 That patch doesn't work because I think it didn't call getfeatureflags to read, but they just read `[rdi+0x38c]`.

I tried this patch (inspired by the patch above), and it works. So it is indeed caused by race condition.

Arch = x86_64
Base = __ZN25IOBluetoothHostController25SetControllerFeatureFlagsEj
Find (must be empty)
Identifier = com.apple.iokit.IOBluetoothFamily
Enabled = YES
Replace = BA0F0000 0089978C 03000048 8B07488B 80800200 00488D35 AF010300 B9200000 009090

Which is actually replacing 
```asm
0:  55                      push   rbp
1:  48 89 e5                mov    rbp,rsp
4:  89 b7 8c 03 00 00       mov    DWORD PTR [rdi+0x38c],esi
a:  89 f2                   mov    edx,esi
c:  48 8b 07                mov    rax,QWORD PTR [rdi]
f:  48 8b 80 80 02 00 00    mov    rax,QWORD PTR [rax+0x280]
16: 48 8d 35 9f 01 03 00    lea    rsi,[rip+0x3019f]        # 0x301bc
1d: b9 20 00 00 00          mov    ecx,0x20
22: 5d                      pop    rbp
```

to 

```asm
0:  ba 0f 00 00 00          mov    edx,0xf
5:  89 97 8c 03 00 00       mov    DWORD PTR [rdi+0x38c],edx
b:  48 8b 07                mov    rax,QWORD PTR [rdi]
e:  48 8b 80 80 02 00 00    mov    rax,QWORD PTR [rax+0x280]
15: 48 8d 35 af 01 03 00    lea    rsi,[rip+0x301af]        # 301cb <_main+0x301cb>
1c: b9 20 00 00 00          mov    ecx,0x20
21: 90                      nop
22: 90                      nop
```

**Comment by lvs1974** [comment]
@jqqqqqqqqqq, @PMheart : looks very good!
It would make sense to check this patch for 10.8 - 11.0. 
Probably we could remove BT4LEContinuityFixup and publish this patch in OC SampleCustom.plist.

**Comment by PMheart** [comment]
Well, I doubt the patch remains stable throughout versions. Is it better to resolve the symbol and hook the function?

**Comment by lvs1974** [comment]
@PMheart: how can we hook the function if IOBluetoothFamily is patched too late with Lilu & BT4LEContinuityFixup?

**Comment by PMheart** [comment]
@lvs1974 Hmm. Makes sense. In this case binary patching can be the very only option…

**Comment by lvs1974** [comment]
@jqqqqqqqqqq: could you try OC Kernel -> Block Properties: and here we could try to block com.apple.iokit.IOBluetoothFamily. As far as I know blocking works not for all kexts, but it can postpone kext loading.

**Comment by jqqqqqqqqqq** [comment]
> @jqqqqqqqqqq: could you try OC Kernel -> Block Properties: and here we could try to block com.apple.iokit.IOBluetoothFamily. As far as I know blocking works not for all kexts, but it can postpone kext loading.
> Probably BT4LEContinuityFixup will work in this case!

@lvs1974 Unfortunately Bluetooth stops working. The blocking is permanent

**Comment by lvs1974** [comment]
So, we have only one stable option: binary patch!

**Comment by jqqqqqqqqqq** [comment]
Yeah, but good part is this patch seems to be static unless the offset is changed. It targets the starting bytes of the symbol.

**Comment by PMheart** [comment]
Just in case - how about masking out those irrelevant bytes?

**Comment by usr-sse2** [comment]
> > Can somebody try the following kernel patch in OpenCore:
> > Arch = x86_64
> > Base = __ZN25IOBluetoothHostController25GetControllerFeatureFlagsEv
> > Find (must be empty)
> > Identifier = com.apple.iokit.IOBluetoothFamily
> > Enabled = YES
> > Replace = b8 0f 00 00 00 c3
> > BT4LEContinuityFixup must be turned off in config.plist.
> > UPD: Fixed `Identifier` (_by vit9696_)
> 
> @lvs1974 Seems not effective, I still see 0x7. Guess this method is not called?
> One proof might be my previous problematic patch shall make the stack unbalanced and panic.
> 
> Logs from my BCM94360NG (which is actually a BCM94360CD) with BT4LEContinuityFixup has logs on booting shows setfeatureflags has been called three times.
> 
> <img alt="image" width="468" src="https://user-images.githubusercontent.com/12872927/94759017-cae09800-036c-11eb-8a78-727f012b764f.png">
> 
> Here is my bluetooth info, is it possible that calling this method has some prerequisites? (Just a wild guess, assuming default value is 0x7)
> 
> BTW tried using injector to change IOBluetoothHostControllerUSBTranport to Broadcom one, no difference.
> 
> <img alt="image" width="336" src="https://user-images.githubusercontent.com/12872927/94759060-e5b30c80-036c-11eb-8f45-c32d62deacdd.png">

Of course you see 7. `FeatureFlags` in the ioreg are filled in `SetControllerFeatureFlags` by calling `setProperty("FeatureFlags", value)`. So if you patch `GetControllerFeatureFlags`, then it will still be 7 in the ioreg and in the local variable but those who use `GetControllerFeatureFlags` will see 15.

**Comment by lvs1974** [comment]
@usr-sse2: you are right, but unfortunately IOBluetoothFamily kext internally uses [reg+38Ch] to check controller flags.

**Comment by lvs1974** [comment]
@jqqqqqqqqqq: did you try to put BT4LEContinuityFixup before BrcmPatchRAM in config.plist?
Probably it can work.

**Comment by lvs1974** [comment]
And could somebody check another simplified version of binary patch:
Arch = x86_64
Base = __ZN25IOBluetoothHostController25SetControllerFeatureFlagsEj
Find (must be empty)
Identifier = com.apple.iokit.IOBluetoothFamily
Enabled = YES
Replace = 55 83 CE 0F
So, we don't use offset at all here.


```
55 			push    rbp
48 89 E5	mov     rbp, rsp

55			push    rbp
83 CE 0F	or esi, 0xf
```

**Comment by PMheart** [comment]
Yes, this patch is also compatible with 11.0!

**Comment by lvs1974** [comment]
So, please test these patches, somebody!
If everything is fine - BT4LEContinuityFixup can be archived.

**Comment by lvs1974** [comment]
Just in case I want to attach all these kexts:
[IOBluetoothFamily-10.8.5.zip](https://github.com/acidanthera/bugtracker/files/5311644/IOBluetoothFamily-10.8.5.zip)
[IOBluetoothFamily-10.9.5.zip](https://github.com/acidanthera/bugtracker/files/5311645/IOBluetoothFamily-10.9.5.zip)
[IOBluetoothFamily-10.10.5.zip](https://github.com/acidanthera/bugtracker/files/5311646/IOBluetoothFamily-10.10.5.zip)
[IOBluetoothFamily-10.11.6.zip](https://github.com/acidanthera/bugtracker/files/5311647/IOBluetoothFamily-10.11.6.zip)
[IOBluetoothFamily.kext-10.12.6.zip](https://github.com/acidanthera/bugtracker/files/5311649/IOBluetoothFamily.kext-10.12.6.zip)
[IOBluetoothFamily-10.13.6.zip](https://github.com/acidanthera/bugtracker/files/5311652/IOBluetoothFamily-10.13.6.zip)
[IOBluetoothFamily-10.14.6.zip](https://github.com/acidanthera/bugtracker/files/5311653/IOBluetoothFamily-10.14.6.zip)
[IOBluetoothFamily-10.15.7.zip](https://github.com/acidanthera/bugtracker/files/5311654/IOBluetoothFamily-10.15.7.zip)

**Comment by PMheart** [comment]
OK, I added [some notes](https://github.com/acidanthera/BT4LEContinuityFixup/commit/81d26432f67299d58071a48308c678cdb567863a) to BT4LEContinuityFixup to encourage further testing. As well, IOBluetoothFamily for Big Sur 11.0 beta 9 has been [attached](https://github.com/acidanthera/bugtracker/issues/1173#issuecomment-702077491).

**Comment by lvs1974** [comment]
In BootKernelExtensions.kc I have found the following strings:
```
com.apple.iokit.IOBluetoothFamily
<key>com.apple.iokit.IOBluetoothFamily</key>
<string>com.apple.iokit.IOBluetoothFamily</string>
<string>/System/Library/Extensions/IOBluetoothFamily.kext</string>
<string>Contents/MacOS/IOBluetoothFamily</string>
```

@vit9696: is it enough to patch IOBluetoothFamily from OpenCore?

**Comment by vit9696** [comment]
Yes, should be.

**Comment by PMheart** [comment]
Implemented as quick named `ExtendBTFeatureFlags` in OpenCore master.
