### ISSUE TITLE
Apple ALC mic with IDT

### ISSUE THREAD

**Issue by singhalrishi27** [acidanthera/bugtracker#1175]
Hello open core team I'm having issues with appleALC
at first after installing Catalina sound was not working so I switched to voodoohda after that it somewhat worked but it had crappy audio.
then I found a DSDT which had my pin configurations so I switched to apple alc problem with alc is microphone it is really noisy.
I want you to add pin configurations of my codec from DSDT.aml given also please fix microphone issue Thankyou.

Laptop HP Foilo 9470m
Codec IDT92HD91BXX 111d76e0
Please Help me
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5267444/EFI.zip)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by singhalrishi27** [comment]
> Use forums for support.

Which fourms
