### ISSUE TITLE
Opencore halting on critial error for big sur, Failed to determine kernel version

### ISSUE THREAD

**Issue by kocoman1** [acidanthera/bugtracker#1176]
Big Sur beta, oc 0.6.1
When fail
How can I diagnois it? thanks

16:610 00:062 OC: Result of 64-bit XNU hook on boot\System\Library\KernelCollections\BootKernelExtensions.kc (00000000) is Success

16:618 00:007 OCAK: Failed to determine kernel version

16:621 00:003 OCAK: KC symtab failed locating inner 0 0 (0)

16:624 00:003 OC: Kernel patcher kernel init failure - Invalid Parameter

-----
When success

22:743 00:303 OC: Result of 64-bit XNU hook on boot\System\Library\KernelCollections\BootKernelExtensions.kc (00000000) is Success

22:763 00:020 OCAK: Read kernel version 20.0.0 (200000)

22:799 00:035 OCAK: PanicKextDump replace count - 1

22:807 00:007 OCAK: Patch success kext dump

**Comment by vit9696** [comment]
This looks like filesystem or hdd failure. You will have to reinstall the operating system or try rebuilding the preboot. Unfortunately it is not too stable yet.
