### ISSUE TITLE
Big Sur Shows Generic AHCI Controller

### ISSUE THREAD

**Issue by ameenjuz** [acidanthera/bugtracker#1177]
OpenCore team know why my SATA Controller shows Generic AHCI Controller in Big Sur
in Catalina shows Intel 10 Series Chipset
i was waiting to fix from big sur beta 1 to 8 but no luck still my sata controller shows Generic AHCI Controller
i couldn't find any solution
the other hand i have missing option (put hard disk sleep when possible ) in system preference under Energy saver
attached screenshot
Catalina
![Screen Shot 2020-07-21 at 1 52 30 AM](https://user-images.githubusercontent.com/21066935/94078609-e563c000-fe06-11ea-8c7c-68952a200cc0.jpg)
Big Sur
![Screen Shot 2020-09-23 at 4 43 43 AM](https://user-images.githubusercontent.com/21066935/94078853-f4e30900-fe06-11ea-8f81-5a31d37a7a37.jpg)
Missing (put hard disk sleep when possible)
![Screen Shot 2020-09-23 at 4 46 42 AM](https://user-images.githubusercontent.com/21066935/94078959-fdd3da80-fe06-11ea-8590-558c2988fc22.jpg)

**Comment by chromer030** [comment]
@ameenjuz
Hi , on my Skylake system with h110 chipset i have this condition too , have you found any solution ?
I think that's due the outright removal of AppleIntelPchSeriesAHCI class from AppleAHCIPort.kext by Apple.
There is a way : use Catalina patched kext , but that's not good !

**Comment by chromer030** [comment]
https://github.com/acidanthera/bugtracker/issues/1051#issuecomment-660958487
