### ISSUE TITLE
DW1820A not working on 5Ghz Networks

### ISSUE THREAD

**Issue by frbuccoliero** [acidanthera/bugtracker#1178]
Hello everyone. I'm on a Dell XPS 9570 with 10.15.5 , my EFI is this repo: https://github.com/jaromeyer/XPS9570-Catalina
I switched the default not supported Killer Wifi/BT card with a new DW1820A. As stated in the repo i disabled active state power management:

The only change that has to be done is disabling “Active State Power Management”. This can be done by inserting the following entry under ```Root/DeviceProperties/Add```.

```
<key>PciRoot(0x0)/Pci(0x1c,0x0)/Pci(0x0,0x0)</key>
<dict>
    <key>pci-aspm-default</key>
    <integer>0</integer>
</dict>
```

Everything works fine except 5Ghz networks, i can connect to them but after a while it gets no more internet connection, same behavior after shutdown/sleep. I updated to the last AirportBRCMFixup but with no results. I also tried adding brcmfx-aspm=255 as stated in the changelog (i honestly don't know what it does) but no results.

**Comment by stevezhengshiqi** [comment]
What about adding `brcmfx-country=#a` to boot-args? I had the same problem before, and I found out that the country code of my wireless card sometimes becomes `X0`, which is invalid to connect certain 5G channels.

**Comment by frbuccoliero** [comment]
Already added. 

![Schermata 2020-09-25 alle 18 48 42](https://user-images.githubusercontent.com/14348908/94294183-bd3ba480-ff5f-11ea-92dc-1eb3d3871e13.png)

**Comment by lvs1974** [comment]
Hello, 
I have a Dell Inspiron 7590 and DW1820A.

Please take a look at my settings:
![Screenshot 2020-09-25 at 18 57 30](https://user-images.githubusercontent.com/27740976/94295053-f9bbd000-ff60-11ea-92b8-5a8be55c3724.png)

I use brcmfx-aspm=255 since I use a native power management fow DW1820a (I isolated pins).
You should remove brcmfx-aspm, and AirportBrcmFixup will turn off ASPM automatically.

**Comment by frbuccoliero** [comment]
I added all this properties and looks like it's working. One thing i'm noticing is that now the country code is set to US (i removed the boot flag brcmfx-country=#a in the boot args since i added it in the properties above) . Idk.

**Comment by lvs1974** [comment]
@frbuccoliero: I see the same country code which is set in DeviceProperties:
![Screenshot 2020-09-25 at 19 22 21](https://user-images.githubusercontent.com/27740976/94297211-713f2e80-ff64-11ea-90bd-f53bf6c41b2e.png)

**Comment by frbuccoliero** [comment]
I don't.

![Schermata 2020-09-25 alle 19 26 10](https://user-images.githubusercontent.com/14348908/94297552-f9253880-ff64-11ea-9d03-a6768b8e6996.png)

![Schermata 2020-09-25 alle 19 27 36](https://user-images.githubusercontent.com/14348908/94297859-7d77bb80-ff65-11ea-8850-a7aea8ac9078.png)

Btw while i was writing this comment, the "Blackout" happened again. Nothing looked strange, no disconnections, still hooked on 5Ghz, but suddenly no internet connection. :(

**Comment by frbuccoliero** [comment]
Sidenote: to fix this and switch to 2,4Ghz i have to press Alt(option) key + Wifi Logo and press "Disconnect from <wifi name> then connect again. This brings me to 2.4 but this lasts until reboot/sleep

**Comment by lvs1974** [comment]
@frbuccoliero: I noticed that you just copied PciRoot(0x0)/Pci(0x1D,0x6) from config.
But this key can be different for your system.
You should use gfxutil to find out yours!

**Comment by frbuccoliero** [comment]
Oh that might be a problem then :D

gfxutil returns me this:

```
00:00.0 8086:3ec4 /PCI0@0/MCHC@0 = PciRoot(0x0)/Pci(0x0,0x0)
00:01.0 8086:1901 /PCI0@0/PEG0@1 = PciRoot(0x0)/Pci(0x1,0x0)
00:02.0 8086:3e9b /PCI0@0/IGPU@2 = PciRoot(0x0)/Pci(0x2,0x0)
00:04.0 8086:1903 /PCI0@0/B0D4@4 = PciRoot(0x0)/Pci(0x4,0x0)
00:08.0 8086:1911 /PCI0@0/pci8086,1911@8 = PciRoot(0x0)/Pci(0x8,0x0)
00:12.0 8086:a379 /PCI0@0/pci8086,a379@12 = PciRoot(0x0)/Pci(0x12,0x0)
00:14.0 8086:a36d /PCI0@0/XHC@14 = PciRoot(0x0)/Pci(0x14,0x0)
00:14.2 8086:a36f /PCI0@0/pci8086,a36f@14,2 = PciRoot(0x0)/Pci(0x14,0x2)
00:15.0 8086:a368 /PCI0@0/I2C0@15 = PciRoot(0x0)/Pci(0x15,0x0)
00:15.1 8086:a369 /PCI0@0/I2C1@15,1 = PciRoot(0x0)/Pci(0x15,0x1)
00:16.0 8086:a360 /PCI0@0/IMEI@16 = PciRoot(0x0)/Pci(0x16,0x0)
00:17.0 8086:a353 /PCI0@0/SAT0@17 = PciRoot(0x0)/Pci(0x17,0x0)
00:1b.0 8086:a340 /PCI0@0/RP17@1B = PciRoot(0x0)/Pci(0x1B,0x0)
00:1c.0 8086:a338 /PCI0@0/RP01@1C = PciRoot(0x0)/Pci(0x1C,0x0)
00:1c.4 8086:a33c /PCI0@0/RP05@1C,4 = PciRoot(0x0)/Pci(0x1C,0x4)
00:1f.0 8086:a30e /PCI0@0/LPCB@1F = PciRoot(0x0)/Pci(0x1F,0x0)
00:1f.3 8086:a170 /PCI0@0/HDEF@1F,3 = PciRoot(0x0)/Pci(0x1F,0x3)
00:1f.4 8086:a323 /PCI0@0/SBUS@1F,4 = PciRoot(0x0)/Pci(0x1F,0x4)
00:1f.5 8086:a324 /PCI0@0/pci8086,a324@1F,5 = PciRoot(0x0)/Pci(0x1F,0x5)
3c:00.0 10ec:525a /PCI0@0/RP05@1C,4/PXSX@0 = PciRoot(0x0)/Pci(0x1C,0x4)/Pci(0x0,0x0)
3b:00.0 14e4:43a3 /PCI0@0/RP01@1C/ARPT@0 = PciRoot(0x0)/Pci(0x1C,0x0)/Pci(0x0,0x0)
```
How do i know what is my card? If it can help, as i said i applied the ```pci-aspm-default property```  to  ```PciRoot(0x0)/Pci(0x1c,0x0)/Pci(0x0,0x0)```

**Comment by lvs1974** [comment]
Yes, PciRoot(0x0)/Pci(0x1C,0x0)/Pci(0x0,0x0) is correct.

**Comment by frbuccoliero** [comment]
So should i add all the properties under the pci-aspm-default one inside PciRoot(0x0)/Pci(0x1C,0x0)/Pci(0x0,0x0) or make a separate one?

**Comment by M69W** [comment]
Some DW1820A don't work in Wi-Fi Channel 36.

**Comment by lvs1974** [comment]
@frbuccoliero: yes, put everything into PciRoot(0x0)/Pci(0x1C,0x0)/Pci(0x0,0x0), and pci-aspm-default you can remove.

**Comment by lvs1974** [comment]
@M69W: correct, I had to change channel in my router to 40.

**Comment by frbuccoliero** [comment]
Ok rebooted, the properties look injected since country code is now #a. Problem is that now the card hooked up the 2.4ghz and not the 5ghz network

**Comment by lvs1974** [comment]
@frbuccoliero: try to change channel.

**Comment by frbuccoliero** [comment]
In my router i can choose channel from 1-13 or Auto. Atm it was on Auto and it automatically picked 6. What should i put?

**Comment by frbuccoliero** [comment]
Nevermind. That was about 2.4Ghz , for 5Ghz i can choose from 36 40 44 etc.. atm it's picked 52. I'm putting 40 as you did

**Comment by frbuccoliero** [comment]
Ok i'm currently over 5GHZ on channel 40. Working atm updating in a while

**Comment by GuaiYiHu** [comment]
> Some DW1820A don't work in Wi-Fi Channel 36.

awesome, f*** redmi router.
