### ISSUE TITLE
New version of CpuTscSync not work with my i7-7500U

### ISSUE THREAD

**Issue by anonymous-writer** [acidanthera/bugtracker#1179]
New version of CpuTscSync not work with my i7-7500U.
Version 1.0.2 works perfekt.
Version 1.0.3 make kernel panic directly on startup.

**Comment by ameenjuz** [comment]
i have same problem 
my laptop do not boot with CpuTscSync.kext
i m running i5-7200 kabylake

**Comment by vit9696** [comment]
No panic, no logs. I do not think there were any changes between 1.0.2 and 1.0.3. Closing.

**Comment by anonymous-writer** [comment]
Unfortunately for me that's the problem. I only changed the Kext CpuTscSync.kext from 1.0.2 and 1.0.3 > Kernel panic. 
Back to 1.0.2 and everything is working again.
![IMG_2484](https://user-images.githubusercontent.com/35840715/94396298-ea57a500-0161-11eb-9c76-3b43b9d5fc59.JPG)

**Comment by vit9696** [comment]
keepsyms=1?
