### ISSUE TITLE
[NVMeFix] How to inject ps-max-latency-us property on Real Macs?

### ISSUE THREAD

**Issue by mo5214** [acidanthera/bugtracker#1181]
As a follow up from #973 (Apologies if this is the wrong place to put this issue)

Apologies for trying to resurrect a 'closed' issue. But I don't know how to inject the ps-max-latency-us property on vanilla Macs. 
Also, with the default value that NVMEFix would use, Will it enable those extra (s3 and s4/ non-active) power states?

I understand if this might be a 'dumb' question (I'm not very familiar with this). But I have been looking around and found no resource on how to inject IODevice property on vanilla macs. (That or I'm not looking hard enough) If you have a good resources to read, feel free to include it in the reply.

Again, thank you in advance for your help.

**Comment by 07151129** [comment]
You need to use a third-party bootloader to inject a device property.

With the default max latency value, the deeper power states are likely to be turned on. You can check the log of DEBUG build to see what states are configured.
