### ISSUE TITLE
10200H ，UHD630 core graphics card cannot be driven normally！

### ISSUE THREAD

**Issue by FJ-L** [acidanthera/bugtracker#1182]
Intel official website introduces this is a new nuclear display id.The official website link is as follows. https://ark.intel.com/content/www/us/en/ark/products/208016/intel-core-i5-10200h-processor-8m-cache-up-to-4-10-ghz.html. 
It is 0x9BA4.
When I drive the core graphics card, the screen does not display properly.If the core display card is not driven, the screen displays normally.I have tried many core graphics card IDs but cannot solve this problem.The attachment is the picture when it is not displayed normally.
![Photo1](https://user-images.githubusercontent.com/68631832/94355373-33521f80-00b6-11eb-89ab-c8f54b80138f.png)
![photo2](https://user-images.githubusercontent.com/68631832/94355375-351be300-00b6-11eb-9225-3ade3969f764.png)
![photo3](https://user-images.githubusercontent.com/68631832/94355378-364d1000-00b6-11eb-8f61-9541ac62a761.png)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by TianSir854** [comment]
Is there no way to solve it？

**Comment by FJ-L** [comment]
> 有没有办法解决？

Yes，the problem is still that.

**Comment by TianSir854** [comment]
> > 有没有办法解决？
> 
> 是的，问题仍然存在。

когда - нибудь решить этот вопрос？
