### ISSUE TITLE
[Possible regression] OpenCore 0.6.1 (or some of the kexts) break functionality of High Sierra IO80211 and/or AirPortAtheros40 causing kernel panic

### ISSUE THREAD

**Issue by HoshiYamazaki** [acidanthera/bugtracker#1183]
At first I want to tell that I used High Sierra kexts to provide backward compatibility of DW1515 Atheros card.

So, I own Thinkpad X230 and previously, before installing any upgrade on Catalina, I needed to blacklist both of kexts I listed in the issue title. I found solution on reddit:
https://www.reddit.com/r/hackintosh/comments/grn6om/kernel_panic_when_trying_to_update_to_10155/

OK, but after upgrade to 0.6.1 I have constant kernel panic even after macOS upgrade, after straight boot to normal install partition. I am not sure if Apple security update broke something, I did some mistake in upgrade process, or the issue is in Acidanthera code.

This is my OpenCore log:
[opencore-2020-09-27-171346.txt](https://github.com/acidanthera/bugtracker/files/5288555/opencore-2020-09-27-171346.txt)

I will upload soon EFI. Yeah, I know, I should update my Thinkpad to better Wi-Fi card, but I will do later, now I want to have working macOS with Wi-Fi installation.

**Comment by vit9696** [comment]
Apple secure boot immutablekernel includes io80211. Either disable or do not use this hardware. Check the docs.
