### ISSUE TITLE
New version of CpuTscSync not work with my i7-7500U

### ISSUE THREAD

**Issue by anonymous-writer** [acidanthera/bugtracker#1185]
If allowed, I would like to come back to this topic again.

![Text vorher](https://user-images.githubusercontent.com/35840715/94396723-d6607300-0162-11eb-840a-d49f08f168cc.jpg)

Unfortunately for me that's the problem. I only changed the Kext CpuTscSync.kext from 1.0.2 to 1.0.3 > Kernel panic.
Back to 1.0.2 and everything is working again.
I would help with additional information if I know what is needed.

![IMG_2484](https://user-images.githubusercontent.com/35840715/94396601-8da8ba00-0162-11eb-9fa1-5e3c2e51aa79.JPG)

[opencore-2020-09-28-063807_Kernel_Panik_1_0_3.txt](https://github.com/acidanthera/bugtracker/files/5290344/opencore-2020-09-28-063807_Kernel_Panik_1_0_3.txt)

[EFI.zip](https://github.com/acidanthera/bugtracker/files/5290378/EFI.zip)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/1179#issuecomment-699793858

**Comment by anonymous-writer** [comment]
Thank you, you are the greatest. Problem solved.
