### ISSUE TITLE
Apply acidanthera/VoodooPS2#27 to BrightnessKeys

### ISSUE THREAD

**Issue by usr-sse2** [acidanthera/bugtracker#1187]
acidanthera/VoodooPS2#27

**Comment by Sniki** [comment]
Is brightness keys going to be a Plugin kext for VoodooPS2 (bundled with VoodooPS2) similarly how VoodooInput is ?

**Comment by vit9696** [comment]
It will be a separate kext, which can be used with both VoodooPS2 and other kexts like VoodooI2C or VoodooSMBus. That is the primary reason for separation.

**Comment by usr-sse2** [comment]
Another reason is that users can decide to continue using ACPI patches with VoodooPS2.
