### ISSUE TITLE
[VoodooPS2] Not an ALPS device: Error getting E6 & E7/EC Report.

### ISSUE THREAD

**Issue by dazzaXx** [acidanthera/bugtracker#1188]
OpenCore 0.6.1 - Catalina 10.15.7 - Dell Latitude E5450

Upon updating AppleALC, Lilu, WhateverGreen, VirtualSMC (with its respective plugins) and VoodooPS2Controller to the latest versions, the trackpad in the system disables every so often when booted and throws out these errors (obtained through the log, using SSDT-GPI0 patch, previously used SSDT-XOSI patch and had the same outcome.):

> (VoodooPS2Trackpad) VoodooPS2TouchPad Base Driver loaded...
2020-09-28 19:05:59.158880+0100  localhost kernel[0]: (VoodooPS2Controller) ApplePS2Controller: Timed out on mouse input stream.
2020-09-28 19:05:59.264049+0100  localhost kernel[0]: (VoodooPS2Controller) ApplePS2Controller: Timed out on mouse input stream.
2020-09-28 19:05:59.495010+0100  localhost kernel[0]: (VoodooPS2Trackpad) ALPS: identify: not an ALPS device. Error getting E6 report
2020-09-28 19:05:59.495013+0100  localhost kernel[0]: (VoodooPS2Trackpad) ALPS: identify: not an ALPS device. Invalid E6 report
2020-09-28 19:05:59.635355+0100  localhost kernel[0]: (VoodooPS2Controller) ApplePS2Controller: Timed out on mouse input stream.
2020-09-28 19:05:59.635359+0100  localhost kernel[0]: (VoodooPS2Trackpad) ALPS: identify: not an ALPS device. Error getting E7/EC report

The touchpad works most of the time perfectly, this can happen at any random time when booted, does not happen during use and does not halt or panic the booting process. What ususally fixes it is 1 or 2 reboots and it detects it and works again with the message:

> (VoodooPS2Trackpad) VoodooPS2TouchPad Base Driver loaded...
2020-09-28 19:38:17.149199+0100  localhost kernel[0]: (VoodooPS2Controller) ApplePS2Controller: Timed out on mouse input stream.
2020-09-28 19:38:17.253595+0100  localhost kernel[0]: (VoodooPS2Controller) ApplePS2Controller: Timed out on mouse input stream.
2020-09-28 19:38:17.547841+0100  localhost kernel[0]: (VoodooPS2Trackpad) ALPS: Found a V7 TouchPad with ID: E7=0x73 0x03 0x0a, EC=0x88 0xba 0x2a
2020-09-28 19:38:17.589547+0100  localhost kernel[0]: (VoodooPS2Trackpad) ALPS: TrackStick detected... (WARNING: V7 TrackStick disabled)
2020-09-28 19:38:17.589550+0100  localhost kernel[0]: (VoodooPS2Trackpad) ALPS: TouchPad driver started...

EDIT: The GPI0 stub is not the issue, as the keyboard works all of the time using the same Voodoo kext driver, it is only the touchpad that does this.

**Comment by dazzaXx** [comment]
UPDATE: It seems to be an issue within 1.1.6 of VirtualSMC, i have tested each kext before i updated them and narrowed it down to VirtualSMC or it's plugins.

**Comment by hieplpvip** [comment]
Hi,

I don't think there is any problem with VirtualSMC. Based on your log, you're not using Acidanthera's VoodooPS2. It seems that you're using [this one](https://osxlatitude.com/forums/topic/8285-refined-alps-touchpad-driver/), which hasn't been updated for three years.

I do understand that you have to use that kext because Acidanthera's VoodooPS2 doesn't have multitouch support ALPS yet. I'm willing to fix it, but as I don't have ALPS touchpad, I will need you to help with debugging. If you agree, feel free to contact me via Discord hieplpvip#4788

**Comment by dazzaXx** [comment]
I am currently using 2.1.6 of Acidanthera's VoodooPS2 kext. All of my kexts besides one are from Acidanthera's github. For some reason it's version reports as 6.0.0, had a look in it's info.plist and it has been set to 6.0.0, maybe from the older version Rehab used to make before Acidanthera's team made an updated version, as it still has his ID as well still stored in the .plist.

**Comment by hieplpvip** [comment]
No, you're not using Acidanthera's VoodooPS2. It doesn't have code for printing those log (e.g. `Found a V7 TouchPad`).

**Comment by dazzaXx** [comment]
Apologies, i do see the differences in the info.plists of the one i have installed vs. Acidanthera's. Seems i am using the old one made by Rehab a few years ago, which has made me genuinely confused as to how i got it in the first place, i never even downloaded the old version and Hackintool reports the source url as being from here. Sorry for wasting people's time. I understand as to why the issue was closed now.
![Screenshot 2020-09-30 at 11 29 52](https://user-images.githubusercontent.com/48131734/94674600-57a93880-0310-11eb-8cc5-9c0a23932c1a.png)

**Comment by kommtzeitkonrad** [comment]
https://github.com/1Revenger1/VoodooPS2-Alps

**Comment by dazzaXx** [comment]
> https://github.com/1Revenger1/VoodooPS2-Alps

Thanks for the link! Does this work properly with Catalina? I read the readme and it says up to 10.12, but I assume that's because it was forked from the original repo that was last updated in 2017.

**Comment by vit9696** [comment]
@1Revenger1 can we get ALPS eventually adopting VoodooInput and being merged with our master version?

**Comment by 1Revenger1** [comment]
To be frank, I don't think most of the ALPs PS2 protocols would benefit from VoodooInput. Most only report the position of one finger, with a bitmap of the X and Y axis, making it hard to do anything related to multi touch. Version 7/8 look feasible, but I don't have a touchpad which uses that protocol. For older versions, I suppose I could try to get 2 and 3 fingers gestures working...sort of? I'm not sure how to handle 2 finger rotate or pinch/zoom. The bitmap given for the x/y axis is super low resolution too. Four finger gestures would be impossible.

**Comment by vit9696** [comment]
Well, one of the reasons to bother is for unification, so that we could maintain a single codebase for all PS/2 kexts. With ELAN support merged and eventually getting more stable I believe it is only ALPS that is left. As long as we do not lose the features it could be the way to go really.

As for 2-finger rotate one could theoretically make alternative gestures (I think @usr-sse2 did something for 4-finger ones on synaptics to get the notifications panel work) but I do know much of the details.

**Comment by 1Revenger1** [comment]
I suppose for unification, it wouldn't be bad. I do think there are a couple outstanding things which don't work, like the trackstick for V7/8 I think? I can finish those up and clean it up a bit before doing a PR. Would VoodooInput support be a requirement for it to be merged?

**Comment by vit9696** [comment]
It will be great if we could really route it with VoodooInput. Last time we cleaned the codebase from pre-VoodooInput code it got a lot better. However, if you want to approach that separately i.e. firstly have a version without VoodooInput and later with so that we could do regression testing it may do too. I will ask for as much code reuse as possible though.

**Comment by usr-sse2** [comment]
> To be frank, I don't think most of the ALPs PS2 protocols would benefit from VoodooInput. Most only report the position of one finger, with a bitmap of the X and Y axis, making it hard to do anything related to multi touch. Version 7/8 look feasible, but I don't have a touchpad which uses that protocol. For older versions, I suppose I could try to get 2 and 3 fingers gestures working...sort of? I'm not sure how to handle 2 finger rotate or pinch/zoom. The bitmap given for the x/y axis is super low resolution too. Four finger gestures would be impossible.
> 
> Edit: More documentation on the various protocols: https://www.kernel.org/doc/html/latest/input/devices/alps.html

Do ALPS touchpads report finger count? If so, two finger tapping and scrolling, three finger drag and three/four finger swipes will work by simply assigning all fingers coordinates to the primary finger coordinates, so VoodooInput is still useful.
(I haven't read the documentation yet).

**Comment by 1Revenger1** [comment]
> Do ALPS touchpads report finger count? If so, two finger tapping and scrolling, three finger drag and three/four finger swipes will work by simply assigning all fingers coordinates to the primary finger coordinates, so VoodooInput is still useful.
> (I haven't read the documentation yet).

*most* (wtf?) of the protocols do have finger count.
Thanks for the tip, is there any gestures which won't work by doing that? Sounds like a good first step to getting things mostly working.
