### ISSUE TITLE
Exiting Update Preboot operation with overall error=(ZeroMeansSuccess)=-69572

### ISSUE THREAD

**Issue by imotoboy** [acidanthera/bugtracker#1190]
-bash-3.2# diskutil apfs updatePreboot disk2s1
Started APFS operation
UpdatePreboot: Commencing operation to update the Preboot Volume for Target Volume disk2s1 Macintosh HD - Données
UpdatePreboot: The Target Volume is part of APFS Container disk2
UpdatePreboot: The Target Volume's OpenDirectory (non-special kind) user count is 0 and the Recovery (any of 4 kinds) user count is 0
UpdatePreboot: The Target Volume is part of APFS Volume Group 4F8ABAC2-2A4B-40B1-8D61-E3FDB603BBCD
UpdatePreboot: Custom OD and macOS source paths have both been specified
UpdatePreboot: Sourcing VAR directory relative to source macOS
UpdatePreboot: Sourcing USR directory relative to source macOS
UpdatePreboot: Search Path For macOS Source Files = (nil=NotMounted) = /Volumes/Macintosh HD
UpdatePreboot: Directory That macOS "var" Is Searched To Be In = (nil=NoMacOS) = /Volumes/Macintosh HD
UpdatePreboot: Directory That macOS "usr" Is Searched To Be In = (nil=NoMacOS) = /Volumes/Macintosh HD
UpdatePreboot: Open Directory Database Search Path = (nil=MacOSSearchPathNotMounted) = /Volumes/Macintosh HD - Données/private/var/db/dslocal/nodes/Default
UpdatePreboot: Preserve EncryptedRootPList When No-OD = 0
UpdatePreboot: Successfully opened Open Directory database; setting AuthODNodeOrNil accordingly
UpdatePreboot: Mounting and ensuring as mounted the related Preboot Volume
UpdatePreboot: Releasing mount hold on Preboot Volume
UpdatePreboot: Doing memory releases
UpdatePreboot: Exiting Update Preboot operation with overall error=(ZeroMeansSuccess)=-69572
Error: -69572: The Subject Volume UUID directory was not found on the APFS Preboot Volume

**Comment by vit9696** [comment]
Apple bug, report it via Feedback Assistant I guess.
