### ISSUE TITLE
SMCSuperIO dies due to spinlock acquisition

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1191]
@vandroiy2013 got an early startup crash in SMCSuperIO within `GeneratedNuvotonDevice_12::updateVoltage`. More precisely in `NuvotonDevice::voltageRead` on the following line:

```C
float value = readByte(NUVOTON_VOLTAGE_REGS[index]) * 0.008f;
```

The value is already read and is being converted to float:

```NASM
__text:0000000000004B50 EC                   in      al, dx
__text:0000000000004B51 0F B6 C0             movzx   eax, al
__text:0000000000004B54 0F 57 C0             xorps   xmm0, xmm0  ; here we die
__text:0000000000004B57 F3 0F 2A C0          cvtsi2ss xmm0, eax
__text:0000000000004B5B F3 0F 59 05 91 1D 00+mulss   xmm0, cs:dword_68F4
__text:0000000000004B5B 00
__text:0000000000004B63 0F 57 C9             xorps   xmm1, xmm1
__text:0000000000004B66 F3 0F 5F C1          maxss   xmm0, xmm1
```

The root cause seems to be holding a spinlock when reading the voltages, which takes too long to complete:

```C
void SuperIODevice::update() {
	IOSimpleLockLock(getSmcSuperIO()->counterLock);
	updateTachometers();
	updateVoltages();
	IOSimpleLockUnlock(getSmcSuperIO()->counterLock);
	updateIORegistry();
}
```

I wonder if we actually need to run `updateTachometers()` and `updateVoltages()` under spin separately to let the scheduler kick in inbetween or even let them work over a temp buffer without global locks and then update the SMC values under a spinlock.

[panic_spinlock.txt](https://github.com/acidanthera/bugtracker/files/5303958/panic_spinlock.txt)

CC @joedmru

**Comment by joedmru** [comment]
Should be fixed by this https://github.com/acidanthera/VirtualSMC/commit/752fcc27007fe253c42cfef558c092085ff627b3

**Comment by vit9696** [comment]
Assuming fixed.
