### ISSUE TITLE
Intermittent Panics During Sleep, Related to AppleALC?

### ISSUE THREAD

**Issue by rkc2003** [acidanthera/bugtracker#1194]
Unfortunately, having a difficult to replicate issue. Device is intermittently failing to sleep - display sleep starts with system itself not sleeping (LEDs and fans stay on). I'm unable to get any signal with wake, and on restart I'm getting the below attached kernel panic message. 

- Using AppleALC 1.3.2, Lilu 1.4.7
- Lilu+AppleALC+Opencore debug logs are shown below
- config.plist in plain text
- System Info
Asrock Z390ITX Phantom Gaming
i5-9600k (w/headless UHD 630 iGPU)
AMD 5700XT (w/display via DP)

[opencore-2020-10-02-123526.txt](https://github.com/acidanthera/bugtracker/files/5320772/opencore-2020-10-02-123526.txt)
[Panic.txt](https://github.com/acidanthera/bugtracker/files/5320774/Panic.txt)
[config.txt](https://github.com/acidanthera/bugtracker/files/5320782/config.txt)
[LiluAppleALCDebug.txt](https://github.com/acidanthera/bugtracker/files/5320780/LiluAppleALCDebug.txt)

Thanks in advance for any insight.

**Comment by vit9696** [comment]
AppleALC 1.3.2? I guess you meant 1.5.2. You seem to have some weird code that loads/unloads AppleHDA in userspace or does some other weirdness. Another possibility is that you have too many Lilu plugins. You could try this workaround, but there is no evidence of an AppleALC bug, so we see little reason for investigation.

[AppleALC-1.5.3-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/5322319/AppleALC-1.5.3-DEBUG.zip)
