### ISSUE TITLE
`Hfsplus.efi` made OC stuck on blackscreen before picker on some CPU

### ISSUE THREAD

**Issue by LemoFire** [acidanthera/bugtracker#1200]
_config based on dortania.github.io._

Problem:
B75 (My two motherboards: MSI B75+i3 3210 and Asrock N75+G1610 have same problems) can't boot OC , which stuck on blackscreen when the following file is added to the EFI folder.
`https://github.com/acidanthera/OcBinaryData/blob/master/Drivers/HfsPlus.efi` (37kb)
The log of the debug version of OC is as follows:
```
S:Starting OpenCore...
BS: Booter Path - \EFI\BOOT\BOOTX64.EFI
.....................
......................
OC:Loaded configuration of 27424 bytes
OC:Watchdog status is 1
```
It doesn't continue to boot（Asrock） or restart（MSI） all the time.

When I change another Hfsplus.efi (25kb, from other people's EFI). the problem will be solved.

There is also an interesting phenomenon: when I use i5-3470, the Hfsplus.efi（37kb）is Working normally, until I change my CPU to i3 or G1610.

**Comment by 1Revenger1** [comment]
Those are both older systems, which both likely don't support the RDRAND instruction found in newer HFSPlus drivers. You likely want this one instead: https://github.com/acidanthera/OcBinaryData/blob/master/Drivers/HfsPlusLegacy.efi

**Comment by LemoFire** [comment]
> Those are both older systems, which both likely don't support the RDRAND instruction found in newer HFSPlus drivers. You likely want this one instead: https://github.com/acidanthera/OcBinaryData/blob/master/Drivers/HfsPlusLegacy.efi

Thank you. Although it's not the same file I used, it seems that both of them work properly
