### ISSUE TITLE
AMD GPU fails to initialize under VMWare ESXI

### ISSUE THREAD

**Issue by kokozaurz** [acidanthera/bugtracker#1201]
Hello! 

First of all - thanks for the amazing tools you guys are creating. 

I've been having issues initializing AMD GPU in a MacOS system running in a VMWare ESXI Hypervisor. Since I'm seeing references to vmware within the documentation my assumption is that it's supported, at least at some level. I had very limited success finding any particular guides for vmware, especially ESXI so was hoping you could help me with this issue. 

Configuration: 
- Opencore 0.6.2
- Lilu 1.4.8
- Whatevergreen 1.4.3
_it wasn't working in the previous versions either so this report is not only affecting the latest_
- SMBIOS: iMacPro1,1
- macOS 10.15.7
- 2x E5-2680 v2 CPU'S (VM configured with 6 cores each)
- 16GB RAM
- MSI ARMOR AMD RX580 8GB (0x67df1002)

I read in KVM guide that there might be issues with different bus settings, however that's not the case. As you can see, in the esxi it's under the same bus: 

<img width="1655" alt="Screen Shot 2020-10-03 at 3 41 22 PM" src="https://user-images.githubusercontent.com/6368786/95142229-33e75780-0741-11eb-9dbe-1f812477f6b9.png">
<img width="1653" alt="Screen Shot 2020-10-03 at 3 41 28 PM" src="https://user-images.githubusercontent.com/6368786/95142232-33e75780-0741-11eb-8967-bdd769954d7c.png">

I've tried multiple different configurations with no luck. 
Whatevergreen + Lilu makes the card appear as RX580 in display settings however it doesn't have any properties attached to it. 

<img width="589" alt="Screen Shot 2020-10-05 at 7 31 05 PM" src="https://user-images.githubusercontent.com/6368786/95142287-51b4bc80-0741-11eb-9622-dedd83626665.png">

The first display is VMware svga adapter for remote console.

I've tried to add virtualsmc kext, or without it. No difference. Tried different boot args, also no difference. It doesn't have any hardware acceleration and doesn't seem to react at all when the display gets connected to it. 

In IORegistry, it seems that it adds the AMD drivers to the device, but it doesn't make it available. 
<img width="1724" alt="Screen Shot 2020-10-05 at 7 39 11 PM" src="https://user-images.githubusercontent.com/6368786/95142763-73627380-0742-11eb-97ed-e68c1d327e76.png">

Couple of pointers where the problem might be from logs:
After lilu patches it, theconfiguration fails?
<img width="2508" alt="Screen Shot 2020-10-05 at 7 35 57 PM" src="https://user-images.githubusercontent.com/6368786/95142572-ffc06680-0741-11eb-9519-e21e76a35ca1.png"> 
Could unsupported CPU might be causing this? 
<img width="2482" alt="Screen Shot 2020-10-05 at 7 37 28 PM" src="https://user-images.githubusercontent.com/6368786/95142665-35654f80-0742-11eb-9886-041e496c7087.png">

unauthorized client of perfpowerservice
<img width="2474" alt="Screen Shot 2020-10-05 at 7 43 08 PM" src="https://user-images.githubusercontent.com/6368786/95142996-000d3180-0743-11eb-8be0-cfa67afa1273.png">
which is followed by:
<img width="1958" alt="Screen Shot 2020-10-05 at 7 43 48 PM" src="https://user-images.githubusercontent.com/6368786/95143033-17e4b580-0743-11eb-9967-2e813d587acc.png">

I'm not sure if either of those problems is the root of the cause, but hoping you could give some insight on why this might be happening and how we could fix it. 

Here are the logs and EFI folder:
[Lilu_1.4.8_19.6.txt](https://github.com/acidanthera/bugtracker/files/5330638/Lilu_1.4.8_19.6.txt)
[fullbootlog.txt](https://github.com/acidanthera/bugtracker/files/5330640/fullbootlog.txt)
[opencore-2020-10-05-223411.txt](https://github.com/acidanthera/bugtracker/files/5330643/opencore-2020-10-05-223411.txt)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5330645/EFI.zip)

Thank you.

**Comment by vit9696** [comment]
To be honest, I do not know what can cause it. This does look like a problem in the AMD GPU drivers in macOS refusing to use your GPU (perhaps, due to some PCI configuration issues), but the actual support request should be forwarded to VMware, as it works e.g. in KVM.
