### ISSUE TITLE
BrightnessKeys not working OOTB, missing PS2K addresses?

### ISSUE THREAD

**Issue by manz4rk** [acidanthera/bugtracker#1203]
Tried to use the BrightnessKeys kext but unfortunately it does not work in my case:
* Dell XPS 13 (9350)
* Intel i5-6200U, Skylake
* macOS 10.15.7 (19H2)
* OpenCore 0.6.2
* Lilu 1.4.8

Here's the working SSDT I've been using:
```
DefinitionBlock ("", "SSDT", 2, "hack", "BRT6", 0x00000000)
{
    External (_SB_.PCI0.GFX0, DeviceObj)
    External (_SB_.PCI0.GFX0.LCD_, DeviceObj)
    External (_SB_.PCI0.LPCB.PS2K, DeviceObj)

    Scope (_SB.PCI0.GFX0)
    {
        Method (BRT6, 2, NotSerialized)
        {
            If ((Arg0 == One))
            {
                Notify (^LCD, 0x86) // Device-Specific
                Notify (^^LPCB.PS2K, 0x10) // Reserved
                Notify (^^LPCB.PS2K, 0x0406)
            }

            If ((Arg0 & 0x02))
            {
                Notify (^LCD, 0x87) // Device-Specific
                Notify (^^LPCB.PS2K, 0x20) // Reserved
                Notify (^^LPCB.PS2K, 0x0405)
            }
        }
    }
}

```

I had a look in the source code and couldn't find anything similar to 0x0405 or 0x0406, so I'm assuming the general (most probable) case is just hardcoded, without any option or automatic assignment depending on the hardware. Please let me know if there's anything I could provide you with to make it work automagically. 

Also big thanks to the whole team – Hackintosh experience today is so much more straighforward and stable than it was all those years ago. Amazing effort!

**Comment by vit9696** [comment]
CC @zhen-zen

**Comment by al3xtjames** [comment]
@manz4rk Can you confirm that BrightnessKeys has loaded? Use `kextstat | grep as.acidanthera.BrightnessKeys` to check.

**Comment by manz4rk** [comment]
@al3xtjames It is:
```
$ kextstat | grep as.acidanthera.BrightnessKeys
   59    0 0xffffff7f845f8000 0x9000     0x9000     as.acidanthera.BrightnessKeys (1.0.0) BE8FC800-1834-3284-9E24-98B49B05226B <58 44 12 8 6 5 3 1>
```

**Comment by zhen-zen** [comment]
Have you removed the old `BRT6` patches completely? The original one shouldn't notify `PS2K`. iirc it's tested on other Dell laptops with vanilla `BRT6`.

**Comment by zhen-zen** [comment]
And specific for your hack SSDT, device `LCD` should be under the same scope of `_SB_.PCI0.GFX0`. The original implementation is as follow instead of `Notify (^LCD, 0x86)` at upper scope.

```
        Method (BRT6, 2, NotSerialized)
        {
            If ((Arg0 == One))
            {
                Notify (LCD, 0x86)
            }

            If ((Arg0 & 0x02))
            {
                Notify (LCD, 0x87)
            }
        }
```

**Comment by manz4rk** [comment]
That was it, it works brilliantly now. Sorry for bothering you with such a stupid question which turned out to be a botched config on my end. Thanks for help!

**Comment by MuntashirAkon** [comment]
It's not working for me either.
- Dell Inspiron 15 5567
- Intel i3-7200U

The rests are similar to the author.

Here's the working SSDT that I was using:
```dsl
// BrightKey for dell
// In config ACPI, BRT6 to XRT6(dell)
// Find:     42 52 54 36 02 A0 0B 93
// Replace:  58 52 54 36 02 A0 0B 93
//
DefinitionBlock("", "SSDT", 2, "ACDT", "BrightFN", 0)
{
    External(_SB.PCI0.GFX0, DeviceObj)
    External(_SB.PCI0.LPCB.PS2K, DeviceObj)
    External(_SB.PCI0.GFX0.XRT6, MethodObj)

    Scope (_SB.PCI0.GFX0)
    {
        Method (BRT6, 2, NotSerialized)
        {
            If (_OSI ("Darwin"))
            {
                If ((Arg0 == One))
                {
                    Notify (\_SB.PCI0.LPCB.PS2K, 0x0406)
                    Notify (\_SB.PCI0.LPCB.PS2K, 0x10)
                }

                If ((Arg0 & 0x02))
                {
                    Notify (\_SB.PCI0.LPCB.PS2K, 0x0405)
                    Notify (\_SB.PCI0.LPCB.PS2K, 0x20)
                }
            }
            Else
            {
                \_SB.PCI0.GFX0.XRT6(Arg0, Arg1)
            }
        }
    }
}
```
