### ISSUE TITLE
AirportBrcmFixup - Since 2.0.9, WiFi sometimes doesn't reconnect on boot

### ISSUE THREAD

**Issue by Andrw0830** [acidanthera/bugtracker#1204]
I am running macOS Big Sur (Build 20A5384c), but ever since AirportBrcmFixup was updated to 2.0.9, WiFi doesn't always reconnect on booting OpenCore 0.6.2. No WiFi networks will be listed when this happens and System Information > Wi-Fi shows no interfaces as well. I have checked kextstat which does show the kext has loaded. It doesn't seem to matter what OpenCore or macOS Big Sur version is installed as been having the issue since 2.0.9 release.

My OC config.plist does have both the AirportBrcmFixup.kext and the AirPortBrcmNIC_Injector.kext defined while the AirPortBrcm4360_Injector.kext is not added. When using version 2.0.8 with everything remaining the same, it works perfectly on each boot. My Wifi Adapter is the Dell 1560 Broadcom 4352 (43b1). I am also using the latest kexts provided on these repos for my Dell Inspiron 7567 laptop.

Please let me know if you need further details and thanks for the work!

**Comment by vit9696** [comment]
Please report which exact commit causes this. See:
https://dortania.github.io/builds/?product=AirportBrcmFixup&viewall=true

**Comment by lvs1974** [comment]
Please attach boot logs for working and not-working wi-fi.
To get logs use debug build of AirportBrcmFixup with boot-arg **-brcmfxdbg** and **msgbuf=1048576**
Use the following command in terminal: sudo dmesg > ~/Desktop/dmesg.txt

**Comment by Andrw0830** [comment]
> Please attach boot logs for working and not-working wi-fi.
> To get logs use debug build of AirportBrcmFixup with boot-arg **-brcmfxdbg** and **msgbuf=1048576**
> Use the following command in terminal: sudo dmesg > ~/Desktop/dmesg.txt
> Please run this command ASAP after login into system.

Thanks for providing the instructions to provide logs. I have collected 2 dmesg logs (1st working Wi-Fi, 2nd broken Wi-Fi). 

[dmesg.txt](https://github.com/acidanthera/bugtracker/files/5351795/dmesg.txt)
[dmesg2.txt](https://github.com/acidanthera/bugtracker/files/5351796/dmesg2.txt)

**Comment by lvs1974** [comment]
@Andrw0830: thank you for logs, the main issue I have found there is " AirportBrcmFixup    BRCMFX: @ timerEventSource failed". It means postponed matching function cannot be run later by timer event.
Could you try again with attached kext, please?
[AirportBrcmFixup-2.1.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/5356216/AirportBrcmFixup-2.1.1-DEBUG.zip)

**Comment by Andrw0830** [comment]
> @Andrw0830: thank you for logs, the main issue I have found there is " AirportBrcmFixup BRCMFX: @ timerEventSource failed". It means postponed matching function cannot be run later by timer event.
> Could you try again with attached kext, please?
> [AirportBrcmFixup-2.1.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/5356216/AirportBrcmFixup-2.1.1-DEBUG.zip)

Thanks man! Just applied this and did a couple reboots and so far Wi-Fi connected both times! Will give this a few days to see if the issue is fixed and report back.

**Comment by Andrw0830** [comment]
I was able to continue testing this and Wi-Fi is still working! Thanks again! Was wondering if before you close this, if it's possible to get the Release version with this commit attached here? Tried building the source myself and having build errors with Xcode 12.0.1 and Big Sur. Just trying to clean up my OpenCore and no biggy if have to wait for the direct Release to be officially posted. Just wanted to ask:)

**Comment by lvs1974** [comment]
@Andrw0830: you are welcome, here is the release version:
[AirportBrcmFixup-2.1.1-RELEASE.zip](https://github.com/acidanthera/bugtracker/files/5363207/AirportBrcmFixup-2.1.1-RELEASE.zip)
The same issue was reported by user @bravoserg on applelife.ru:
https://applelife.ru/threads/opencore-obsuzhdenie-i-ustanovka.2944066/page-435#post-901585
