### ISSUE TITLE
VoodooPS2: Timed out on mouse input stream

### ISSUE THREAD

**Issue by prabs77** [acidanthera/bugtracker#1208]
Using the latest version of VoodooPS2, with Opencore 0.6.2. I get the error about mouse input stream and "Identify Touchpad command returned incorrect byte". Version 1.9.2 works.

![vlcsnap-2020-10-08-22h04m24s002](https://user-images.githubusercontent.com/56230686/95546042-677de800-09b4-11eb-888e-83ba027086a4.png)

[opencore-2020-10-09-042303.txt](https://github.com/acidanthera/bugtracker/files/5352657/opencore-2020-10-09-042303.txt)

**Comment by vit9696** [comment]
VoodooPS2 1.9.2 is not made by us. Please point to the source code where the working version exists and include a kernel log with it. I am not positive your touchpad is even supported by our VoodooPS2, so I am closing the issue until further notice.

**Comment by prabs77** [comment]
The sourcecode for the one I am using is here.
[https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller](url)
I will post a kernel log shortly.

**Comment by prabs77** [comment]
Here is the kernel logs with both the 2.1.7 version and the 1.9.2 rehabman version.
[KernelLog_v1.9.2.txt](https://github.com/acidanthera/bugtracker/files/5361707/KernelLog_v1.9.2.txt)
[KernelLog_v2.1.7.txt](https://github.com/acidanthera/bugtracker/files/5361710/KernelLog_v2.1.7.txt)
