### ISSUE TITLE
Kaby Lake-R CPU incorrectly recognized as Coffee Lake

### ISSUE THREAD

**Issue by hieplpvip** [acidanthera/bugtracker#1209]
Hi, the CPU in question is [i7-8550u](https://ark.intel.com/content/www/us/en/ark/products/122589/intel-core-i7-8550u-processor-8m-cache-up-to-4-00-ghz.html). Intel classifies it as Kaby Lake-R, but Lilu recognizes it as Coffee Lake.

Here is the CPUID info:
```
CPU vendor: Intel
CPU max level: 0x16
CPU max level (ext): 0x80000008
CPU brand: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
CPU family: 6
CPU model: 142
CPU stepping: 0xa
CPU generation: 10 (Coffee Lake)
```

So it has a stepping of 0xa, which makes Lilu recognize it as Coffee Lake, according to [this](https://github.com/acidanthera/Lilu/blob/3b302dc0d972b8cf89c19569dfbea75a16b3c51a/Lilu/Sources/kern_cpu.cpp#L107-L113).

**Comment by benbender** [comment]
Same "problem" for i7-8650U

````
CPU vendor: Intel
CPU max level: 0x16
CPU max level (ext): 0x80000008
CPU brand: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
CPU family: 6
CPU model: 142
CPU stepping: 0xa
CPU generation: 10 (Coffee Lake)
````

**Comment by Mateo1234454545** [comment]
@hieplpvip , same problem with my i5-8250u. 
Setting lilucpu=9 doesn't solve the problem.

**Comment by vit9696** [comment]
Well, stepping 0xA is Coffee Lake. It happened that Intel later made these Kaby Lake R CPUs, which are essentially Coffee Lake, but are named Kaby Lake R. They even use Coffee Lake IGPU drivers and so on. I believe it behaves correctly as Kaby Lake != Kaby Lake R.

**Comment by benbender** [comment]
So it is correct that the CPU is essentially Coffee Lake and the iGPU (UHD620/5917) essentially KabyLake?

If yes, it might be good at least to put a note in the documentation and a note nearby the cpu-detection in the code to avoid confusion. Backstory of the bug was that @hieplpvip relied on the cpu detection to get the framebuffer kext which failed in this case.

**Comment by vit9696** [comment]
Not quite that. It may even have Coffee Lake-_compatible_ IGPU as well. What @hieplpvip does is reimplementing functionality that should be WhateverGreen and as a result he hits all the previously resolved issues on his own. For instance, in WhateverGreen a CFL generation may work with both KBL and CFL drivers:

```C
		case CPUInfo::CpuGeneration::CoffeeLake:
			supportsGuCFirmware = true;
			currentGraphics = &kextIntelKBL;
			currentFramebuffer = &kextIntelCFLFb;
			// Allow faking ask KBL
			currentFramebufferOpt = &kextIntelKBLFb; ///< This line
			// Note, several CFL GPUs are completely broken. They freeze in IGMemoryManager::initCache due to incompatible
			// configuration, supposedly due to Apple not supporting new MOCS table and forcing Skylake-based format.
			// See: https://github.com/torvalds/linux/blob/135c5504a600ff9b06e321694fbcac78a9530cd4/drivers/gpu/drm/i915/intel_mocs.c#L181
			forceCompleteModeset.supported = forceCompleteModeset.enable = true;
			RPSControl.available = true;
			ForceWakeWorkaround.enabled = true;
			disableTypeCCheck = true;
			break;
```

You could submit a PR with a comment that KBL-R CPUs will be treated CFL CPUs as there is no way to distinguish them from each other.
