### ISSUE TITLE
OC: Request for separate NVRAM <Persist> section

### ISSUE THREAD

**Issue by MikeBeaton** [acidanthera/bugtracker#1212]
I am aware of #575 which asked for a way to persist nvram options, and aware that this was provided in https://github.com/acidanthera/OpenCorePkg/commit/125c1847d1709a3ff3d8b27ecfbd3f079979e0c4 .

I think there still might be a case for an additional `<Persist>` section, in addition to the already available fix above of combining the `<Add>` section with `WriteFlash: true`.

I am using a [configured OC made by jackluke](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/page-179?post=28952250#post-28952250) (I'm NOT asking for support with that, I'm just using it as an example of why this might be useful!). This configures various settings, including, in NVRAM:

```
<key>Add</key>
<dict>
	...
	<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
	<dict>
		<key>boot-args</key>
		<string>-no_compat_check amfi_get_out_of_my_way=1 agdpmod=pikera</string>
		<key>csr-active-config</key>
		<data>dwkAAA==</data>
		<key>run-efi-updater</key>
		<string>No</string>
	</dict>
</dict>
<key>Delete</key>
<dict>
	...
	<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
	<array>
		<string>boot-args</string>
		<string>csr-active-config</string>
		<string>run-efi-updater</string>
	</array>
</dict>
``` 

My request is that it be possible to add an additional section to this region as follows:

```
<key>Persist</key>
<dict>
	...
	<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
	<dict>
		<key>boot-args</key>
		<string>-no_compat_check</string>
	</dict>
</dict>
```

The aim of this would be to specify how OC should leave the nvram after it has finished up. I do not want the settings specified in `Add`, which I believe I have understood correctly is what I could get with `WriteFlash`.

I don't know if this only makes sense to me because I'm in an unusual use-case? It seems quite like what the OP of #575 was mentioning.

The use-case here is that the customised OpenCore fakes the ID for any existing, working Mac, so that you can boot up the OS using this OC and be offered (e.g.) Big Sur on machines that do not officially support it, or you can boot up Big Sur install media and have it run successfully, also on machines that do not support it.

I have a Mac that's new enough, and physically updated enough, that it can run a completely unpatched version of Big Sur, once it's been persuaded to install using the above technique - the only option it requires, to boot and run, is `boot-args="-no_compat_check"`.

So what I'd like is to be able to use the customised OC bootloader whenever I want (for the above, but also e.g. to see the full list of all bootable partitions, and select between them).

The present behaviour - which I hope I have understood correctly is NOT specific to the particular config I'm using - is that OC leaves `boot-args` cleared, even if it was previously set in nvram. So basically each time I use OC, I then have to boot all the way into recovery just to manually set `boot-args="-no_compat_check"` again, to make Big Sur work without OC again.

What I'd like is to either have the option for OC to not permanently change the state of nvram at all (which would be a completely different request, but would also achieve what I'm asking for, and perhaps some of what #575 was originally asking for - but I understand [this might defeat its whole purpose](https://github.com/acidanthera/bugtracker/issues/575#issuecomment-554522261)), or else (as above) at least be able to optionally specify how OC should leave things after it has finished.

Is this possible? Reasonable?

**Comment by vit9696** [comment]
If you do not specify `boot-args` in `Delete`, then the boot-args will be intact. Is not that the behaviour you want?

**Comment by MikeBeaton** [comment]
Okay, I must have been confused by the documentation in `Configuration.pdf`, I read p.48 where it says

> Variables will only be set if not present or deleted. I.e. to overwrite an existing variable value add the variable
name to the Delete section. This approach enables to provide default values till the operating system takes the lead.

and I assumed this means that the Delete section (in the config which I'm using) has only been put there to make sure that the values in the Add section are respected. Apologies that it seems I'm somehow confused there, I'll try removing the Delete in a simpler test config and report back if I believe it still wouldn't do what I need.

Many thanks for the v. swift response.

**Comment by MikeBeaton** [comment]
@Andrey1970AppleLife Would you be willing to re-open this? I've done my promised investigations and I believe there is a genuine issue here - though it's not quite as I originally thought, and I no longer believe a `<Persist>` section is required.

I previously assumed that the relevant existing behaviour of OC must be correct in all circumstances, and that I needed to ask for a way to work round it. Now I believe that the existing behaviour around nvram deletes has a bug (it can only affect software booting via a bootloader other than OpenCore, after OpenCore has been used on the same machine - which explains why it's relevant to my issue and to #575, and perhaps also explains why it may not have been flagged up before).

Specifically, I do not think that any deletes specified in the NVRAM `<Delete>` section should persist in nvram, except when `WriteFlash` is `true` (i.e. except when `<Add>` changes would be persistent too), but they do, and I believe always have.

I can happily update the title and description and give clear examples, here in this issue, if you think it's best to re-open it, or (since I currently do believe there's something genuine going on!) in a new issue.

**Comment by vit9696** [comment]
We could continue the discussion here. Due to the way UEFI is designed it is not possible to delete variables without removing them from flash. So it is correct that when WriteFlash is NO, they are still permanently removed.

**Comment by MikeBeaton** [comment]
I was wondering if you'd say that!

So then, I wonder, is it possible to non-persistently _change_ (not delete) an existing variable? I would guess not, but if so then when there is an add plus a delete, and when `WriteFlash` is `false`, then the add and delete could be combined into a single, non-persistent change. And then the only combination which needs to be wrong/problematic (for software running outside the context of OC, but after OC has run) is a delete on it's own when `WriteFlash` is `false`.

But I suspect a non-persistent _change_ would equally be not possible? In which case I do after all revert to my initial request for a `<Persist>` section, precisely as a way to work round this.

---

More detail (possibly unnecessary/already obvious):

Say I set `nvram my-var="os_value"` from outside the context of OC, and say I have an OC boot config which sets `my-var` to `oc_value` (optionally, depending on the test case listed below, with or without the corresponding delete, and with or without `WriteFlash: true), then I boot into OC, examine the variable value within the OC boot, then leave OC and examine the value from outside OC again, here are the possible combinations:

|Delete|WriteFlash|Value seen in OC|Value seen after OC|Notes|
|---|---|---|---|---|
|false|false|os_value|os_value|Working correctly (respects OS default)|
|true|false|oc_value|[not present]|Correct inside OC context; problem for software running outside/after OC|
|false|true|os_value|os_value|Works fine (and would have worked fine even if my-var was _not_ present initially, correctly resulting in `oc_value` in both cases)|
|true|true|oc_value|oc_value|Working to spec for software inside and outside of OC context|

Rows 1 and 2 were the only ones that existed before `WriteFlash` was added. Rows 1, 3 & 4 behave correctly. You can see why, from the point of view of something which uses OC and another bootloader on the same machine, row 2 is a problem.

**Comment by vit9696** [comment]
Well, I understand your pain, but not much we can do here. It is not possible to override a variable without making flash modifications. My best recommendation is to always use OC.

**Comment by startergo** [comment]
> If you do not specify `boot-args` in `Delete`, then the boot-args will be intact. Is not that the behaviour you want?

So I tested this and my NVRAM boot-args are not persistent if I don't boot with OC. Is this due to the RequestBootVarRouting set to TRUE in the OC config? 
"then the boot-args will be intact" means that the values previously set through OC should have persisted, right?
