### ISSUE TITLE
[OpenCore 0.6.2] BOOTx64.efi or BOOTX64.efi

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1214]
Hi there,
after switching to OpenCore 0.6.2 I noticed that `BOOTx64.efi` is renamed into `BOOTX64.efi`. Is there any reason behind this choice? If I boot OpenCore 0.6.2 with `BOOTX64.efi` the USB drive doesn't detect at all OpenCore executable, until I create a custom UEFI entry that points to it. At the moment I fixed by making the `X` letter lowercase, so the USB can be correctly detected by the BIOS without creating a custom UEFI entry.
Also, in Configuration.pdf there's clearly no mention to `BOOTX64.efi` but only to `BOOTx64.efi`. Should this be corrected or whatelse?
Thank you so much and have a great day

**Comment by vit9696** [comment]
This is an overlook, but it normally should not affect any firmwares. Fixed in master.
