### ISSUE TITLE
VoodooPS2: Trackpad not recognized

### ISSUE THREAD

**Issue by prabs77** [acidanthera/bugtracker#1215]
I was using Rehabmans VoodooPS2 kext (v1.9.2) (source code [https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller](url). Everything works great. But I cannot use my trackpad with v 2.1.7.

I previously posted a bugtracker [https://github.com/acidanthera/bugtracker/issues/1208#issuecomment-706698435](url) but was requested kernel logs.

[KernelLog_v1.9.2.txt](https://github.com/acidanthera/bugtracker/files/5361728/KernelLog_v1.9.2.txt)
[KernelLog_v2.1.7.txt](https://github.com/acidanthera/bugtracker/files/5361729/KernelLog_v2.1.7.txt)

**Comment by Xpl0itU** [comment]
stick to rehabman's version, I have to use that one too because the buttons that the trackpad has only work with it

**Comment by Andrey1970AppleLife** [comment]
Duplicate https://github.com/acidanthera/bugtracker/issues/1208
