### ISSUE TITLE
virtual IOReturn / IOKit Daemon 'X86PlatformPlugin'

### ISSUE THREAD

**Issue by rezarg-dev** [acidanthera/bugtracker#1216]
I have an issue with big sur beta 9 
I’m installed big sur beta 9 successfully Now sometimes mac os booting Receive these five logs and stuck for 3 minutes and then boot into the desktop
In Catalina, I have no issue, and this issue happened after big sur beta 5
Also if I get this issue, my other partitions by default are unmounted And  audio no longer working and  I'm should restart the system to fix them
my hardware: Acer aspire E5-575G --> i76500U - 8gig DDR4 - HD520 - SATA SSD(os installed in SSD) - SATA HDD
OC 0.6.2 and latest kexts
logs ::
1- virtual IOReturn
CoreAnalyticsUserClient::clientMemoryForType(UInt32, IOOptionBits *, IOMemoryDescriptor **)::269: got memory descriptor with 16432
 
2- IOKit Daemon (kernelmanagerd) stall[0], (60s): 'X86PlatformPlugin'

3- tx_flush:1075: disk2 xid 25794 tx stats: # 40 finish 40 enter 326 wait 1 536us close 0us flush 5402us

4- tx_flush:1075: disk2 xid 25814 tx stats: # 60 finish 60 enter 223 wait 10 735us close 577us flush 4413us

5- tx_flush:1075: disk2 xid 25834 tx stats: # 80 finish 80 enter 173 wait 10 735us close 432us flush 3810us
[files.zip](https://github.com/acidanthera/bugtracker/files/5362237/files.zip)

**Comment by Andrey1970AppleLife** [comment]
You shouldn't add OEM ACPI tables.

**Comment by rezarg-dev** [comment]
Okay thank you

**Comment by rezarg-dev** [comment]
well I'm tryed with hot patch and removed OEM ACPI(this ACPI already fully patched and prepared for mac os) but nothing changed and received the same result and same log

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
