### ISSUE TITLE
build_oc does not support unattended AUDK updates

### ISSUE THREAD

**Issue by mhaeuser** [acidanthera/bugtracker#1217]
build_oc currently has no mechanism to silently (and properly) upgrade AUDK. The reason is that custom OpenCore patches are applied to the tree and, when a new release lands, git cannot fast-forward pull the changes and instead asks the user to merge the changes.

Unfortunately, a solution to this is currently out of scope for us because CI is not affected by this issue.

**Workaround**: Delete the AUDK directory and re-run the tool.

**Possible solutions**:
- Let build_oc delete the AUDK directory (this of course would be very unconvenient for local setups that build often)
- Revert and re-apply patches around pulling (this sounds dirty to implement)
- Rebase-pull to avoid the creation of a merge commit (I don't know whether this works with shallow commits, feel free to try and report)

**Comment by Matgen84** [comment]
Thanks. I delete the AUDK directory and re-run the tool. I can compile again.
