### ISSUE TITLE
voodoops2elan is loaded on Elan v4 but no move or click

### ISSUE THREAD

**Issue by Mkhairy0100** [acidanthera/bugtracker#1220]
my laptop ASUS TP500LN Haswell
appleps2elan is loaded
Elan v 4, fw: 381f17, bus: 0
IOService:/AppleACPIPlatformExpert/PS2M/ps2controller/ApplePS2Controller/ApplePS2MouseDevice/ApplePS2Elan
trackpad preferences is loaded
but no move nor click
it was working fine using smart touchpad kext

on kernel log
2020-10-12 21:08:09.123073+0200 localhost kernel[0]: (kernel) VoodooPS2Trackpad: Identify TouchPad command returned incorrect byte 2 (of 3): 0x04

2020-10-12 21:08:09.200205+0200 localhost kernel[0]: (kernel) ApplePS2Controller: Notification consumer published: ApplePS2Elan

any help thanks on advance

![Screen Shot 2020-10-12 at 10 22 31 PM 1](https://user-images.githubusercontent.com/72765111/95787309-8c869980-0cd9-11eb-868c-889cea8335a2.png

**Comment by IFierta** [comment]
Try loading with argument:  ps2rst = 0

**Comment by Mkhairy0100** [comment]
> Try using bootarg: ps2rst = 0

tried this boot arg but no change no move no click

**Comment by Deeka0** [comment]
I have the same issue with my Elan v4 trackpad. Voodoo input and VoodooPS2Elan are loaded in IOReg.
My laptop is AsusPro P2540UA.
Any help would be appreciated. Thank you.

@usr-sse2 @hieplpvip

**Comment by Mkhairy0100** [comment]
any help ?
