### ISSUE TITLE
FrameBufferInfo->PixelFormat Error

### ISSUE THREAD

**Issue by arrmo** [acidanthera/bugtracker#1221]
Hi,

Thinking I followed all the right rules, and have the correct files attached ... 😆.

The core error message I'm seeing is as follows,
```
01:954 00:016 ASSERT [OpenCore] /Users/travis/build/acidanthera/OpenCorePkg/UDK/MdeModulePkg/Library/FrameBufferBltLib/FrameBufferBltLib.c(133): FrameBufferInfo->PixelFormat != PixelBltOnly
```

To try to explain,
- I have a Radeon HD 6670 set up for GPU Passthrough. Remove it from the VM, and all is good (boots file, no issues).
- While the boot fails, I did connect an HDMI cable out of the GPU to a monitor, and that is working (woohoo!) ... up to the point of lockup of course (and not so woohoo ... LOL!).
- Just add the GPU, and I lock up, at the message above.
- I have -wegoff on the command line (trying to step back to get it working with the device connected, just not using it) ... no help
- I disabled Lilu and WhateverGreen, no difference ... seems to hang before it gets to that point

I admit, it's possible that there is a config option to address this. I have searched, can't find it - but that doesn't mean it doesn't exist! I may just not be smart enough 😞.

Any pointers or debug versions / things you want me to try would be greatly appreciated. Thanks!
[opencore-2020-10-14-010941 (failed).txt](https://github.com/acidanthera/bugtracker/files/5374996/opencore-2020-10-14-010941.failed.txt)

**Comment by arrmo** [comment]
OK, slight update (and progress 😃. I disabled DirectGopRendering (it was there to fix the "blocky" FileVault login), and two things,
1) I get much further in the boot. Now seem to be stuck at ```OCSMC: SmcReadValue Key 4D534163 Size 2``` (or just after this really, but I see this many places). Not fixed even by disabling weg egpu fully (boot arg)
2) I don't see the blocky login from the video card, only KVM. Interesting.

So the crash above seems to be related to DirectGopRendering.

**Comment by vit9696** [comment]
Your GOP protocol does not support direct rendering (i.e. it has no framebuffer mapped), so `DirectGopRendering` cannot be used with your GPU. The assertion is fixed, so that it does not die, but `DirectGopRendering` will spill a warning in the log and do nothing.

The issue with the GOP protocol means that you will not see any XNU output during booting either, so your kernel most likely panics somewhere, but you simply do not see that onscreen. You can try serial logging, but all of this is clearly out of the scope of the bugtracker.

**Comment by arrmo** [comment]
Thanks for the update! And it may be a compatibility vs. specific hardware - understood. Let me hunt around, try to find a supported hardware list.

Thanks again.

**Comment by arrmo** [comment]
FYI, figured it out! Wanted to let you know, in case you hear about this again - it's due to the version of OVMF included in https://github.com/foxlet/macOS-Simple-KVM/tree/master/firmware. With a newer OVMF, the issue is resolved! And that's good, as it also "broke" the GUI.

Thanks!
