### ISSUE TITLE
[OC] OpenCore 0.6.2 can't shutdown on ryzen.

### ISSUE THREAD

**Issue by Cememer** [acidanthera/bugtracker#1223]
OpenCore 0.6.2 can't shutdown on ryzen.

OpenCore 0.6.1 can normals shutdown. but in 0.6.2, When I select shutdown, computer is going to reboot:(

I don't change preference.(Of course, DummyPowerManagement has been moved to where it should be in 0.6.2.)

My PC:

- CPU:AMD Ryzen 7 3700X

- MotherBoard: ASRock X570 Pro4

- GPU: Radeon RX 580 8GB

**Comment by Andrey1970AppleLife** [comment]
We don't support AMD CPU. Use forums for support.
