### ISSUE TITLE
Direction problem with Lenovo Trackpoint + Cursor speed inside texts

### ISSUE THREAD

**Issue by antoniomcr96** [acidanthera/bugtracker#1226]
Good evening, thanks for all your work. I'll talk about two different problems that both concern the same kext: VoodooPS2.

Since @BAndysc 's contribution my Elan touchpad works great, but I have a problem with my trackpoint. 
If I keep the central button clicked and I move the trackpoint the page scrolls, as it should, but with a direction problem: if I move the trackpoint to the right the page scrolls down, If I move the trackpoint to the left the page scrolls up. Nothing happens if I move the trackpoint up or down.

The other problem affects the keyboard: inside a text, if I hold down the left/right arrow key on the keyboard, the cursor moves slowly and reaching the end of a text line takes a lot of time. Is it possible to manually change this speed or does it require a deeper fix?

I can provide logs, video or whatever you want to explain better these problems.

Thanks in advance!

**Comment by antoniomcr96** [comment]
I write again because I’m trying to do some debugging related to reactivating black screen (and probably waking from sleep).
Clicking the keyboard or a button of the trackpad reactivates the screen, touching the trackpad doesn’t have any effect. It isn’t absolutely a major problem, though.

I tried to use the debug version to see if the trackpad sends anything with black screen. 
I found out instead that at the moment the debugging version (both 2.1.6 and 2.1.7) don’t send any message in my logs about the keyboard. If I touch the trackpad I have logs, if I press a key I don’t see anything.
I wanted to remap some keys but at the moment I don’t have any sign of life of the keyboard in the logs.

**Comment by vit9696** [comment]
> The other problem affects the keyboard: inside a text, if I hold down the left/right arrow key on the keyboard, the cursor moves slowly and reaching the end of a text line takes a lot of time. Is it possible to manually change this speed or does it require a deeper fix?

That should be configurable inside macOS. As for trackpoint moved to a meta issue.
