### ISSUE TITLE
Add AppleBoot:StartupMute to Google Drive NVRAM Variables doc

### ISSUE THREAD

**Issue by MikeBeaton** [acidanthera/bugtracker#1227]
Just spotted that AppleBoot:StartupMute (UINT8, %00 or not present to play boot chime, %01 to disable boot chime) isn't in the Google Drive NVRAM Variables doc - might be worth adding?

**Comment by Andrey1970AppleLife** [comment]
Use **MinimumVolume** Audio Properties.

**Comment by MikeBeaton** [comment]
?!

Thanks for the info on another way to do it. I wasn't asking how to do it. I was suggesting adding a missing variable to the document! https://docs.google.com/spreadsheets/d/1HTCBwfOBkXsHiK7os3b2CUc6k68axdJYdGl-TyXqLu0

That Google document is linked to from within the current OpenCore `Configuration.pdf`, so shouldn't its contents be considered official and definitive and part of the documentation of *known* NVRAM variables?

**Comment by Andrey1970AppleLife** [comment]
CC @vit9696
