### ISSUE TITLE
[SecureBootModel] Can't boot macOS vanilla installer

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1229]
Hi there,
I'm using the latest release of OpenCore (0.6.2) and yesterday I was trying to boot my PC via a freshly created macOS Catalina 10.15.7 USB installer.
After selecting the OpenCore boot-entry and booting "install macOS Catalina (external)", the PC rebooted itself instantly in the pre-verbose strings.
After hours while trying to fix this problem I found the "workaround". Setting `SecureBootModel` to `Disabled` + `ApECID` to `Zero` made the installer boot.
The BIOS settings are fine (unlocked CFG Lock and custom DVMT settings (64MB Pre-allocated and Max Total Gfx)
My EFI is available [here](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/)
TIA and let me know if you need any type of debugging file and how to obtain them :) 
Have a nice day

**Comment by Download-Fritz** [comment]
The issue is known and will be explored soon.

**Comment by dreamwhite** [comment]
### Update

I managed to fix this issue by disabling temporarily `SecureBootModel` and `ApECID`:

- `config.plist/Misc/Security/SecureBootModel` = `Disabled`
- `config.plist/Misc/Security/ApECID` = `0`

The installer successfully booted and I was able to restore my Time Machine backups from a network server :D
After restoring everything on the new SSD I enabled `SecureBootModel` and `ApECID:

- `config.plist/Misc/Security/SecureBootModel` = `Default`


###### as written in Configuration.pdf, in order to set `ApECID` you need to generate a random 64bits string and put that value in `config.plist/Misc/Security/ApECID`:

`python3 -c 'import secrets; print(secrets.randbits(64))'`

**Comment by vit9696** [comment]
I believe @Download-Fritz misunderstood the nature of the issue. You had personalised secure boot in your configuration according to [this changeset](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/commit/4924c66d720c75b4de06b4c5fad7cd520d7c7bc2#diff-18ce8f2001c3c18075dbf54219a44cbfbc93fc79f0f2ab519305ed1bcd16112eL724). However, your macOS installer was **not** personalised for your system. To resolve this you need to either `bless` or use DMG recovery. Refer to `Configuration.pdf` for more details.

The only known issue with macOS Secure Boot is currently is with Big Sur b10. It does not boot with and without `ApECID` unless `SecureBootModel` is set to `Disabled`. But this is a separate issue.

**Comment by 1alessandro1** [comment]
Thanks @vit9696 for your clarifications, seems like that in the `Configuration.pdf` file there's only the way to `bless` the volume from a previous installation (hence you have the path `/Volumes/Macintosh\ HD/System/Library/CoreServices`) - but instead, if one starts from scratch (from a full `Install*OS*.app/`) I couldn't find any way to boot the installer with a value of `ApECID` !=0 (full installer, not DMG recovery, where it works) 

How do we personalize the installer itself? Is this even possible?

**Comment by vit9696** [comment]
For the installer it is `/Volume/InstallationMedia/System/Library/CoreServices` I believe.

**Comment by 1alessandro1** [comment]
ok, so the ApECID value can be arbitrary (even different from the one used in the OS you're blessing the installer from)

Also, the directory `InstallationMedia` that you mentioned is just a placeholder or that path is exactly it?
Because when createinstallmedia finishes its process, all the directories are located after:


```
/Volumes/Install\ macOS/Catalina/Install\ macOS\ Catalina.app/`
                                                            │   sampledir
                                                            │   samplefile    
                                                            │
                                                            └───folder1
                                                            │   │   file011.txt
                                                            │   │   file012.txt
                                                            │   │
                                                            │   └───subfolder1
                                                            │       │   file111.txt
                                                            │       │   file112.txt
                                                            │       │   ...
                                                            │   
                                                            └───folder2
                                                                │   file021.txt
                                                                │   file022.txt
```

**Comment by vit9696** [comment]
It is the root of the installation volume you created with createinstallmedia. System folder will likely be hidden.

**Comment by dreamwhite** [comment]
> It is the root of the installation volume you created with createinstallmedia. System folder will likely be hidden.

@vit9696 I was doing a few researches about SecureBootModel and tried to bless a freshly created macOS Installer on a thumb drive. After creating the installer, I followed your advice in order to bless the installer but it fails unexpectedly with the following error:

Command: `sudo bless bless --folder "/Volumes/Install macOS Big Sur/System/Library/CoreServices" --bootefi --personalize`
Output: `Can't load /Volumes/Install macOS Big Sur/usr/standalone/i386/boot.efi`

Do you have any idea of why this happens? How should I boot macOS Installer with ApECID + SecureBootModel enabled? 
Many thanks and have a great day :")

**Comment by vit9696** [comment]
Unsure, to be honest. This stuff is not documented. I believe automatic blessing happens when you run it form macOS, but otherwise I don't know.

**Comment by dreamwhite** [comment]
> Unsure, to be honest. This stuff is not documented. I believe automatic blessing happens when you run it form macOS, but otherwise I don't know.

Alright, so what you suggest in order to bless my drive? Install macOS with `SecureBootModel` set to `Disabled` and `ApECID` to `0` and then enable and bless them from recovery?

**Comment by vit9696** [comment]
Use dmg install or do not use ApECID.

**Comment by dreamwhite** [comment]
> Use dmg install or do not use ApECID.

Alright many thanks for the reply ^^
