### ISSUE TITLE
GTX 960, Reported as "NVIDIA Chip Model"

### ISSUE THREAD

**Issue by arrmo** [acidanthera/bugtracker#1231]
Hi,

I admit, not 100% sure what logs to attach to this one, as not sure where it the process it's happening. But let me try to explain, and I can capture what you need 😄. 

I have an Nvidia GTX 960 in PCI passthrough mode to my qemu/kvm machine. That part is working, and in High Sierra I have the Nvidia Web Drivers installed. But, no video output, and in macOS if I run ```system_profiler SPDisplaysDataType```, I get,
```
Graphics/Displays:

    NVIDIA Chip Model:

      Chipset Model: NVIDIA Chip Model
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x16
      VRAM (Dynamic, Max): 256 MB
      Vendor: NVIDIA (0x10de)
      Device ID: 0x1401
      Revision ID: 0x00a1
      ROM Revision: preset 1.0.0
      Metal: Supported
```
This does seem to be a problem (and some of the data is incorrect, like VRAM and ROM Revision for example), at least from some searching around (and I don't have a video output, thinking this is related). If I swap to Clover (just as a test, trying to debug!), I instead get,
```
Graphics/Displays:

    MSI GeForce GTX 960:

      Chipset Model: MSI GeForce GTX 960
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x16
      VRAM (Dynamic, Max): 2048 MB
      Vendor: NVIDIA (0x10de)
      Device ID: 0x1401
      Revision ID: 0x00a1
      ROM Revision: 84.06.0D.00.F1
      Metal: Supported
```

It could be that I'm missing a configuration setting (there are lots of them ... LOL), or it may be that this card is not supported in OC? But does seem like something isn't quite right - of course it may be me.

Thanks!

**Comment by vit9696** [comment]
The reason for this is that Clover automatically injects `DeviceProperties` for your NVIDIA card including the name (`MSI GeForce GTX 960`). OpenCore does not have GPU database, therefore you need to inject keys like `model` on your own. The issue is outside of the scope of OpenCore, but you can refer to other sources for more information. For example, check https://github.com/dortania/bugtracker/issues/82 for more details.

**Comment by arrmo** [comment]
NP, that makes sense - thanks! Reported it as I wasn't sure if it was a bug or not, but not it seems.

Thanks again.

**Comment by arrmo** [comment]
BTW, just to let you know (in case you get asked again down the road 😄. Yep, this does work, quite easy actually. Still no video output though, seems that's not really related. Dang it!

**Comment by arrmo** [comment]
And one more - just FYI, in case you hear about it down the road ... never was able to get the GTX 960 working 😞. But, put in a (very old) HD 6670, and it worked ... even with the device settings for the GTX 960. LOL! Not sure why, but to keep you informed.

**Comment by briheart** [comment]
have you solved it?I'v got the same problem here.3q
