### ISSUE TITLE
EHC(1,2) to EH0(1,2) rename failing - OpenCore 0.6.2

### ISSUE THREAD

**Issue by tombrown** [acidanthera/bugtracker#1233]
I am trying to replace Clover with OC 0.6.2 on a legacy bios platform. To get my USB ports recognised i need to rename them from EHC(1,2) to EH0(1,2) but this is failing for me even though i have read the manual on this.

Attached is my boot log, an IOreg of the system booted with OC but no USB ports and my EFI. I believe this is a bug but any thoughts would be useful for me.

[EFI.zip](https://github.com/acidanthera/bugtracker/files/5432735/EFI.zip)
[opencore-2020-10-20-182610.txt](https://github.com/acidanthera/bugtracker/files/5432739/opencore-2020-10-20-182610.txt)
[imac14-opencore.ioreg.zip](https://github.com/acidanthera/bugtracker/files/5432740/imac14-opencore.ioreg.zip)

**Comment by vit9696** [comment]
You specify `TableSignature` DSDT, but there is no guarantee that your USB devices are declared exclusively in DSDT. TableSignature for your case should be empty. If it still fails it may be due to legacy region protection, but that should have been resolved earlier. CC @Goldfish64

**Comment by tombrown** [comment]
I made it empty and I have the same issue so I think this could still be a bug.

**Comment by Goldfish64** [comment]
@tombrown Please upload the log from the following test build.
[OpenCore-0.6.3-ACPI.efi.zip](https://github.com/acidanthera/bugtracker/files/5455483/OpenCore-0.6.3-ACPI.efi.zip)

**Comment by tombrown** [comment]
Log is attached

[opencore-2020-10-30-175639.txt](https://github.com/acidanthera/bugtracker/files/5466894/opencore-2020-10-30-175639.txt)

**Comment by whatnameisit** [comment]
On macOS ACPI changes are correctly applied, but not on Windows. Is this a similar case, or should I open a separate issue, or is it user error?

**Comment by vit9696** [comment]
We are currently preparing a fix for the issue discovered by @tombrown, I would suggest to wait until it lands in master and recheck whether the problem still exists. Afterwards — create a separate issue most likely.

**Comment by Goldfish64** [comment]
@tombrown Please retest with latest master.

**Comment by tombrown** [comment]
Do you have a link of a compiled version please?

**Comment by Goldfish64** [comment]
@tombrown https://github.com/dortania/build-repo/releases/download/OpenCorePkg-13ec6ae/OpenCore-0.6.4-DEBUG.zip

**Comment by tombrown** [comment]
Success - rename works and USB ports are active.

Log attached

[opencore-2020-11-09-102016.txt](https://github.com/acidanthera/bugtracker/files/5509751/opencore-2020-11-09-102016.txt)
