### ISSUE TITLE
ScanPolicy doesn't recognise NVMe on Mac Pro 5,1 

### ISSUE THREAD

**Issue by AbdulHadiParsdorfer** [acidanthera/bugtracker#1234]
Hi, 

I tried to find help for this problem in the MacRumors forum but they told me it is likely a bug and I should report it.
I made initial tests with OpenCore 0.6.2 and ScanPolicy with the EFI package on an external USB drive. I used ScanPolicy 0x10F0103 (17760515) and the NVMe on a PCI adapter (Angelbird Wings PX1) with a Dosdude Catalina install showed up in the boot picker. After this I reformatted the NVMe and put the EFI package on it and made a clean install of the original Catalina 10.5.6 and updated it to 10.5.7. After this I applied again the ScanPolicy 0x10F0103 (17760515) but the NVMe didn't show up anymore. The NVMe shows only up with ScanPolicy 0.

Thank you and sorry for my unprofessional report.

**Comment by vit9696** [comment]
Need a debug log for this with ScanPolicy set to `0x10F0103` and `0` on the same machine. Given that this device is an external adapter it might be correct that it is not classified as an NVMe device, however, a log is still needed to explain the behaviour and/or correct it.

**Comment by AbdulHadiParsdorfer** [comment]
Thank you. Hope the logs are right.

[ScanPolicy_17760515_opencore-2020-10-24-134306.txt](https://github.com/acidanthera/bugtracker/files/5432977/ScanPolicy_17760515_opencore-2020-10-24-134306.txt)
[ScanPolicy_0_opencore-2020-10-24-133202.txt](https://github.com/acidanthera/bugtracker/files/5432978/ScanPolicy_0_opencore-2020-10-24-133202.txt)

**Comment by vit9696** [comment]
Should be fixed in master. Please report that the issue is now resolved. You may have to wait for the CI to push [the build](https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true) unless you can build on your own. Post the logs if it is still unresolved with the `a9af4ab` commit.

**Comment by AbdulHadiParsdorfer** [comment]
Great! Thank you so much. It's working now.

May I ask you another question? Sorry to bother you. I don't know if it has anything to do with OpenCore. I didn't get any answer in the forum. My Apple Magic Mouse is most of the time freezing at the login screen to the FileVault. Then only a wired mouse works. Sometimes the Magic Mouse works fine and sometimes not. Could it be a bug? Thank you.

**Comment by vit9696** [comment]
That's likely your BT driver bug. Not much we can do.

**Comment by AbdulHadiParsdorfer** [comment]
Okay. Thank you so much!
