### ISSUE TITLE
SecureBootModel conflicts with Big Sur beta 10

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1235]
Booting Big Sur b10 causes a kernel panic in apfs.kext with the `Rooting from the live fs of a sealed volume is not allowed on a RELEASE build` message.

**Comment by rjsoftwares** [comment]
A quick elaboration for newbies like myself: setting SecureBootModel to Disabled prevents the kernel panic and allows regular operation.

**Comment by billzhong** [comment]
After changing `SecureBootModel` to `Disabled` in `config.plist` I successful upgrade to beta 10.
