### ISSUE TITLE
Whatevergreen Big Sur 4K Display Clock Support

### ISSUE THREAD

**Issue by thefiredragon** [acidanthera/bugtracker#1237]
Dear all, I followed this thread here :
https://github.com/jardenliu/XPS15-9560-Catalina/issues/157

And would like ask if the -cdfon bootarg will work on big sur in future?

On my yoga 730 with catalina and internal 4K panel its working fine, on big sur I had no chance to get internal display working 

Best Regards
Dan

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/1093

**Comment by thefiredragon** [comment]
Patching edid Workshop, 
Perhaps this could be added to the Dokumentation ?

https://gist.github.com/xxxzc/032bf9eef2f217bc7d60f087e25555e1
