### ISSUE TITLE
TextRender fails on Classic MacPros

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1238]
MacPro5,1 always returns "Device Error" when TextRender is set.

Debug log from two different machines attached. Both are with TextRenderer set to BuiltinGraphics
[opencore-2020-08-30-161426.txt](https://github.com/acidanthera/bugtracker/files/5436737/opencore-2020-08-30-161426.txt)
[opencore-2020-10-25-014531.txt](https://github.com/acidanthera/bugtracker/files/5436738/opencore-2020-10-25-014531.txt)

It works however on MacPro3,1
[opencore-2020-10-20-022332.txt](https://github.com/acidanthera/bugtracker/files/5436780/opencore-2020-10-20-022332.txt)

**Comment by vit9696** [comment]
Did you investigate it why it happens and where exactly does the device error come from?

**Comment by dakanji** [comment]
> Did you investigate it why it happens and where exactly does the device error come from?

Actually collected a few log files while trying to investigate another issue ... why "unsupported" Nvida Cards known to have GOP, do not show bootscreens in OpenCore on MacPros (ProvideConsoleGop error) but similar "unsupported" AMD Cards do (ProvideConsoleGop success). 

Looking at the log files, this was the only "odd" item that jumped out although it may not be the root cause as this passes on 3,1 but the Nvidia cards don't work on those either.

Have not been able to fully investigate this issue as I don't have a MacPro5,1 and asked for tests by owners over a period of time.

Unfortunately, the function where this comes from is a very loose in terms of returning statuses with multiple different conditions returning the exact same status and it is not possible to improve specificity to nail things down as this apparently violates some spec item.

> Also, does it have any negative impact on the machine functioning?

It doesn't seem to be as no one is complaining about issues but I don't know the exact implications. Apparently this failure is not supposed to happen and in normal circumstances, further processing would have been halted afterwards.

**Comment by vit9696** [comment]
Right.

> Unfortunately, the function where this comes from is very loose in terms of returning statuses with multiple different conditions returning the exact same status and it is not possible to improve specificity to nail things down as this apparently violates some spec item.

I.e. you did not try testing it with your patch changing the error codes? If you did, you should be able to know the exact location, and I believe that is what would be necessary to understand whether the behaviour is correct or not.

> > Also, does it have any negative impact on the machine functioning?

> It doesn't seem to be as no one is complaining about issues but I don't know the exact implications. Apparently this failure is not supposed to happen and in normal circumstances, further processing would have been halted afterwards.

Regarding that. Negative impact means e.g. no video output, i.e. I wanted to know whether the machine had GOP available and screen visible menu despite the error. To clarify what I meant under "should not fail" is `RenderResync` should not fail once the console mode is set, but currently it does not seem to be, so until the builtin console mode is actually initialised with `OcSetConsoleMode` I think it is plausible that resetting will actually fail. We might want to rework this, but I will need more details on the behaviour.

**Comment by dakanji** [comment]
> you did not try testing it with your patch changing the error codes? If you did, you should be able to know the exact location, and I believe that is what would be necessary to understand whether the behaviour is correct or not.

This was just noticed while trying to look into another issue by checking old log copies. Not yet really gotten logs with the patch as I actually don't have a MacPro5,1 myself and my MacPro3,1 does not appear to have this issue.

I have been working on and using a modified Refind that calls on OpenCorePkg as an external library and the patch would be added to the next version due on the first Monday of November. OpenCorePkg is planned to be upgraded to v0.6.3 and would have preferred that the changes are made upstream in OpenCorePkg so as not to have to patch but I plan to patch if needed. After this, I would hopefully get log files that would help ID exactly where the failure is happening. The only disadvantage is that this would not be coming from OpenCore logging. 

> Regarding that. Negative impact means e.g. no video output, i.e. I wanted to know whether the machine had GOP available and screen visible menu despite the error. 

I understood. It seems there is none as AMD GPUs apparently have video regardless. However, needs information collection as you mentioned and that is what I was hoping for in proposing changes to OpenCorePkg so that logs could be gathered to this end.

**Comment by vit9696** [comment]
What about doing the following:
- Change `RenderResync` function to return different values for all cases
- Change functins calling `RenderResync` to always return device error on its failure
- Make a separate `AsciiTextResetEx` function that will take a `Verbose` to do logging on failure.
- Call `AsciiTextResetEx` from `AsciiTextReset` with FALSE.
- Call `AsciiTextResetEx` from  `OcUseBuiltinTextOutput` with TRUE.

That's slightly more work but it will improve the logging. (We cannot log on error unconditionally as it may cause recursion.)

If it works for you, can you submit a patch? I am a bit overloaded these days.

**Comment by dakanji** [comment]
Will have a stab at it.
Can you reopen the PR?

**Comment by dakanji** [comment]
Found a MacPro3,1 log with it failing.
Not mine so not sure what settings they had.

**Comment by vit9696** [comment]
> Can you reopen the PR?

Thought you can. Done.

**Comment by dakanji** [comment]
It turns out that this issue is linked to a failure to find "valid" GOP with Nvidia GPUs.
Essentially, Nvidia GPUs with factory GOP seem to end up with the following (on Classic MacPros at least):
```
03:042 00:050 OCC: Alternative GOP status is - Not Found
03:100 00:057 OCC: Missing compatible GOP - Not Found
```

The Text Render bit then later fails this condition in the RenderResync function:
```
  if (Info->HorizontalResolution < TGT_CHAR_WIDTH * 3
    || Info->VerticalResolution < TGT_CHAR_HEIGHT * 3) {
```

Self flashed ones do not seem to have this issue.

Perhaps the Nvidia thing should be a separate specific issue as the PR will close this issue?

**Comment by vit9696** [comment]
For NVIDIA — I think the issue was that there was no GOP protocol installed by the GPU, unlike AMD, where there was one, but it was not properly registered.
