### ISSUE TITLE
maciASL : Tools becomes too slow to respond when SSDT is big once adding GPU rom to it.

### ISSUE THREAD

**Issue by shantur** [acidanthera/bugtracker#1241]
I am using maciASL to create SSDT for GPU bios injection.

Once GPU Bios is injected every move away from maciASL window and coming back to it just becomes too slow. It seems as if it tries to compile everytime i focus the window and becomes really slow to work with.

Attaching my SSDT to test with.

[SSDT-GPU-BIOS.zip](https://github.com/acidanthera/bugtracker/files/5439801/SSDT-GPU-BIOS.zip)

**Comment by Andrey1970AppleLife** [comment]
Yours SSDT contains very long hex data, I think in it the reason.

CC @Moorre, @vit9696

**Comment by vit9696** [comment]
CC @usr-sse2

**Comment by shantur** [comment]
I had a look at the code and it seems to be compiling and decompiling every time I am doing away from the maciASL window
