### ISSUE TITLE
OC0.6.2 Macmini7,1 SMBIOS, You need update firmware of your Mac.

### ISSUE THREAD

**Issue by hectorskypl** [acidanthera/bugtracker#1243]
When I tries install clean macOS 10.15.7 on APFS volume I received message to update my Mac firmware.

**Comment by Andrey1970AppleLife** [comment]
Be convinced that you use Automatic=Yes

**Comment by hectorskypl** [comment]
Hey Andrey,
I have enabled Automatic.

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ACPI</key>
	<dict>
		<key>Add</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>SSDT-PLUG.aml</string>
				<key>Path</key>
				<string>SSDT-PLUG.aml</string>
				<key>Enabled</key>
				<true/>
			</dict>
		</array>
		<key>Delete</key>
		<array>
		</array>
		<key>Patch</key>
		<array>
		</array>
		<key>Quirks</key>
		<dict>
			<key>FadtEnableReset</key>
			<false/>
			<key>NormalizeHeaders</key>
			<false/>
			<key>RebaseRegions</key>
			<false/>
			<key>ResetHwSig</key>
			<false/>
			<key>ResetLogoStatus</key>
			<false/>
		</dict>
	</dict>
	<key>Booter</key>
	<dict>
		<key>MmioWhitelist</key>
		<array>
		</array>
		<key>Quirks</key>
		<dict>
			<key>AvoidRuntimeDefrag</key>
			<true/>
			<key>DevirtualiseMmio</key>
			<false/>
			<key>DisableSingleUser</key>
			<false/>
			<key>DisableVariableWrite</key>
			<false/>
			<key>DiscardHibernateMap</key>
			<false/>
			<key>EnableSafeModeSlide</key>
			<true/>
			<key>EnableWriteUnprotector</key>
			<true/>
			<key>ForceExitBootServices</key>
			<false/>
			<key>ProtectMemoryRegions</key>
			<false/>
			<key>ProtectSecureBoot</key>
			<false/>
			<key>ProtectUefiServices</key>
			<false/>
			<key>ProvideCustomSlide</key>
			<true/>
			<key>ProvideMaxSlide</key>
			<integer>0</integer>
			<key>RebuildAppleMemoryMap</key>
			<false/>
			<key>SetupVirtualMap</key>
			<true/>
			<key>SignalAppleOS</key>
			<false/>
			<key>SyncRuntimePermissions</key>
			<false/>
		</dict>
	</dict>
	<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1b,0x0)</key>
			<dict>
				<key>layout-id</key>
				<integer>1</integer>
			</dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>AwAiDQ==</data>
				<key>framebuffer-patch-enable	</key>
				<data>AQAAAA==</data>
			</dict>
		</dict>
		<key>Delete</key>
		<dict/>
	</dict>
	<key>Kernel</key>
	<dict>
		<key>Add</key>
		<array>
			<dict>
				<key>Comment</key>
				<string></string>
				<key>MaxKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
				<key>Enabled</key>
				<true/>
				<key>MinKernel</key>
				<string></string>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/Lilu</string>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>Lilu.kext</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string></string>
				<key>MaxKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
				<key>Enabled</key>
				<true/>
				<key>MinKernel</key>
				<string></string>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VirtualSMC</string>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VirtualSMC.kext</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string></string>
				<key>MaxKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
				<key>Enabled</key>
				<true/>
				<key>MinKernel</key>
				<string></string>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/AppleALC</string>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>AppleALC.kext</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string></string>
				<key>MaxKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
				<key>Enabled</key>
				<true/>
				<key>MinKernel</key>
				<string></string>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/IntelMausi</string>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>IntelMausi.kext</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string></string>
				<key>MaxKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
				<key>Enabled</key>
				<true/>
				<key>MinKernel</key>
				<string></string>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/SMCProcessor</string>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>SMCProcessor.kext</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string></string>
				<key>MaxKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
				<key>Enabled</key>
				<true/>
				<key>MinKernel</key>
				<string></string>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/SMCSuperIO</string>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>SMCSuperIO.kext</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string></string>
				<key>MaxKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
				<key>Enabled</key>
				<true/>
				<key>MinKernel</key>
				<string></string>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/WhateverGreen</string>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>WhateverGreen.kext</string>
			</dict>
		</array>
		<key>Block</key>
		<array>
		</array>
		<key>Emulate</key>
		<dict>
			<key>DummyPowerManagement</key>
			<false/>
		</dict>
		<key>Patch</key>
		<array>
		</array>
		<key>Quirks</key>
		<dict>
			<key>AppleCpuPmCfgLock</key>
			<true/>
			<key>AppleXcpmCfgLock</key>
			<true/>
			<key>AppleXcpmExtraMsrs</key>
			<false/>
			<key>AppleXcpmForceBoost</key>
			<false/>
			<key>CustomSMBIOSGuid</key>
			<false/>
			<key>DisableIoMapper</key>
			<true/>
			<key>DisableRtcChecksum</key>
			<false/>
			<key>ExternalDiskIcons</key>
			<false/>
			<key>IncreasePciBarSize</key>
			<false/>
			<key>LapicKernelPanic</key>
			<false/>
			<key>PanicNoKextDump</key>
			<true/>
			<key>PowerTimeoutKernelPanic</key>
			<true/>
			<key>ThirdPartyDrives</key>
			<false/>
			<key>XhciPortLimit</key>
			<false/>
			<key>LegacyCommpage</key>
			<false/>
		</dict>
	</dict>
	<key>Misc</key>
	<dict>
		<key>BlessOverride</key>
		<array>
		</array>
		<key>Boot</key>
		<dict>
			<key>ConsoleAttributes</key>
			<integer>0</integer>
			<key>HibernateMode</key>
			<string>None</string>
			<key>HideAuxiliary</key>
			<false/>
			<key>PickerAttributes</key>
			<integer>1</integer>
			<key>PickerAudioAssist</key>
			<false/>
			<key>PickerMode</key>
			<string>Builtin</string>
			<key>PollAppleHotKeys</key>
			<true/>
			<key>ShowPicker</key>
			<true/>
			<key>TakeoffDelay</key>
			<integer>0</integer>
			<key>Timeout</key>
			<integer>5</integer>
		</dict>
		<key>Debug</key>
		<dict>
			<key>AppleDebug</key>
			<false/>
			<key>ApplePanic</key>
			<true/>
			<key>DisableWatchDog</key>
			<true/>
			<key>DisplayDelay</key>
			<integer>0</integer>
			<key>DisplayLevel</key>
			<integer>2147483650</integer>
			<key>SerialInit</key>
			<false/>
			<key>SysReport</key>
			<false/>
			<key>Target</key>
			<integer>0</integer>
		</dict>
		<key>Entries</key>
		<array>
		</array>
		<key>Security</key>
		<dict>
			<key>AllowNvramReset</key>
			<true/>
			<key>AllowSetDefault</key>
			<true/>
			<key>AuthRestart</key>
			<true/>
			<key>BootProtect</key>
			<string>Bootstrap</string>
			<key>ExposeSensitiveData</key>
			<integer>6</integer>
			<key>HaltLevel</key>
			<integer>2147483648</integer>
			<key>ScanPolicy</key>
			<integer>0</integer>
			<key>Vault</key>
			<string>Optional</string>
			<key>ApECID</key>
			<integer>0</integer>
			<key>DmgLoading</key>
			<string>Signed</string>
			<key>EnablePassword</key>
			<false/>
		</dict>
		<key>Tools</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>CleanNvram.efi</string>
				<key>Name</key>
				<string>CleanNvram.efi</string>
				<key>Enabled</key>
				<true/>
				<key>Arguments</key>
				<string></string>
				<key>Path</key>
				<string>CleanNvram.efi</string>
				<key>Auxiliary</key>
				<true/>
			</dict>
			<dict>
				<key>Comment</key>
				<string>OpenShell.efi</string>
				<key>Name</key>
				<string>OpenShell.efi</string>
				<key>Enabled</key>
				<true/>
				<key>Arguments</key>
				<string></string>
				<key>Path</key>
				<string>OpenShell.efi</string>
				<key>Auxiliary</key>
				<true/>
			</dict>
		</array>
	</dict>
	<key>NVRAM</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
			<dict>
				<key>DefaultBackgroundColor</key>
				<data>AAAAAA==</data>
				<key>UIScale</key>
				<data>AQ==</data>
			</dict>
			<key>4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102</key>
			<dict>
				<key>rtc-blacklist</key>
				<data></data>
			</dict>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				<key>SystemAudioVolume</key>
				<data>Rg==</data>
				<key>boot-args</key>
				<string>keepsyms=1</string>
				<key>run-efi-updater</key>
				<string>No</string>
				<key>csr-active-config</key>
				<data>AAAAAA==</data>
				<key>prev-lang:kbd</key>
				<string>pl-PL:30788</string>
			</dict>
		</dict>
		<key>Delete</key>
		<dict>
			<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
			<array>
				<string>UIScale</string>
				<string>DefaultBackgroundColor</string>
			</array>
			<key>4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102</key>
			<array>
				<string>rtc-blacklist</string>
			</array>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<array>
				<string>boot-args</string>
			</array>
		</dict>
		<key>LegacyEnable</key>
		<false/>
		<key>LegacyOverwrite</key>
		<false/>
		<key>LegacySchema</key>
		<dict>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<array>
				<string>EFILoginHiDPI</string>
				<string>EFIBluetoothDelay</string>
				<string>LocationServicesEnabled</string>
				<string>SystemAudioVolume</string>
				<string>SystemAudioVolumeDB</string>
				<string>SystemAudioVolumeSaved</string>
				<string>bluetoothActiveControllerInfo</string>
				<string>bluetoothInternalControllerInfo</string>
				<string>flagstate</string>
				<string>fmm-computer-name</string>
				<string>nvda_drv</string>
				<string>prev-lang:kbd</string>
			</array>
			<key>8BE4DF61-93CA-11D2-AA0D-00E098032B8C</key>
			<array>
				<string>Boot0080</string>
				<string>Boot0081</string>
				<string>Boot0082</string>
				<string>BootNext</string>
				<string>BootOrder</string>
			</array>
		</dict>
		<key>WriteFlash</key>
		<true/>
	</dict>
	<key>PlatformInfo</key>
	<dict>
		<key>Automatic</key>
		<true/>
		<key>Generic</key>
		<dict>
			<key>AdviseWindows</key>
			<false/>
			<key>MLB</key>
			<string>x</string>
			<key>ROM</key>
			<data>ACMkZxqi</data>
			<key>SpoofVendor</key>
			<true/>
			<key>SystemProductName</key>
			<string>Macmini7,1</string>
			<key>SystemSerialNumber</key>
			<string>x</string>
			<key>SystemUUID</key>
			<string>x</string>
			<key>SystemMemoryStatus</key>
			<string>Auto</string>
		</dict>
		<key>UpdateDataHub</key>
		<true/>
		<key>UpdateNVRAM</key>
		<true/>
		<key>UpdateSMBIOS</key>
		<true/>
		<key>UpdateSMBIOSMode</key>
		<string>Create</string>
		<key>SMBIOS</key>
		<dict>
			<key>BIOSVersion</key>
			<string>MM71.88Z.F000.B00.2006111040</string>
			<key>BIOSReleaseDate</key>
			<string>06/11/2020</string>
		</dict>
	</dict>
	<key>UEFI</key>
	<dict>
		<key>APFS</key>
		<dict>
			<key>EnableJumpstart</key>
			<true/>
			<key>GlobalConnect</key>
			<false/>
			<key>HideVerbose</key>
			<true/>
			<key>JumpstartHotPlug</key>
			<false/>
			<key>MinDate</key>
			<integer>0</integer>
			<key>MinVersion</key>
			<integer>0</integer>
		</dict>
		<key>Audio</key>
		<dict>
			<key>AudioCodec</key>
			<integer>0</integer>
			<key>AudioDevice</key>
			<string>PciRoot(0x0)/Pci(0x1b,0x0)</string>
			<key>AudioOut</key>
			<integer>0</integer>
			<key>AudioSupport</key>
			<false/>
			<key>MinimumVolume</key>
			<integer>20</integer>
			<key>PlayChime</key>
			<false/>
			<key>VolumeAmplifier</key>
			<integer>0</integer>
		</dict>
		<key>ConnectDrivers</key>
		<true/>
		<key>Drivers</key>
		<array>
			<string>AudioDxe.efi</string>
			<string>HFSPlus.efi</string>
			<string>NvmExpressDxe.efi</string>
			<string>OpenRuntime.efi</string>
			<string>Ps2KeyboardDxe.efi</string>
			<string>Ps2MouseDxe.efi</string>
		</array>
		<key>Input</key>
		<dict>
			<key>KeyFiltering</key>
			<false/>
			<key>KeyForgetThreshold</key>
			<integer>5</integer>
			<key>KeyMergeThreshold</key>
			<integer>2</integer>
			<key>KeySupport</key>
			<true/>
			<key>KeySupportMode</key>
			<string>Auto</string>
			<key>KeySwap</key>
			<false/>
			<key>PointerSupport</key>
			<false/>
			<key>PointerSupportMode</key>
			<string>ASUS</string>
			<key>TimerResolution</key>
			<integer>50000</integer>
		</dict>
		<key>Output</key>
		<dict>
			<key>ClearScreenOnModeSwitch</key>
			<false/>
			<key>ConsoleMode</key>
			<string></string>
			<key>DirectGopRendering</key>
			<false/>
			<key>IgnoreTextInGraphics</key>
			<false/>
			<key>ProvideConsoleGop</key>
			<true/>
			<key>ReconnectOnResChange</key>
			<false/>
			<key>ReplaceTabWithSpace</key>
			<false/>
			<key>Resolution</key>
			<string>Max</string>
			<key>SanitiseClearScreen</key>
			<false/>
			<key>TextRenderer</key>
			<string>BuiltinGraphics</string>
			<key>UgaPassThrough</key>
			<false/>
		</dict>
		<key>ProtocolOverrides</key>
		<dict>
			<key>AppleAudio</key>
			<false/>
			<key>AppleBootPolicy</key>
			<false/>
			<key>AppleDebugLog</key>
			<false/>
			<key>AppleEvent</key>
			<false/>
			<key>AppleFramebufferInfo</key>
			<false/>
			<key>AppleImageConversion</key>
			<false/>
			<key>AppleKeyMap</key>
			<false/>
			<key>AppleRtcRam</key>
			<false/>
			<key>AppleSmcIo</key>
			<true/>
			<key>AppleUserInterfaceTheme</key>
			<false/>
			<key>DataHub</key>
			<false/>
			<key>DeviceProperties</key>
			<false/>
			<key>FirmwareVolume</key>
			<true/>
			<key>HashServices</key>
			<true/>
			<key>OSInfo</key>
			<false/>
			<key>UnicodeCollation</key>
			<false/>
			<key>AppleImg4Verification</key>
			<false/>
			<key>AppleSecureBoot</key>
			<false/>
		</dict>
		<key>Quirks</key>
		<dict>
			<key>DeduplicateBootOrder</key>
			<false/>
			<key>ExitBootServicesDelay</key>
			<integer>0</integer>
			<key>IgnoreInvalidFlexRatio</key>
			<true/>
			<key>ReleaseUsbOwnership</key>
			<false/>
			<key>RequestBootVarRouting</key>
			<true/>
			<key>TscSyncTimeout</key>
			<integer>0</integer>
			<key>UnblockFsConnect</key>
			<false/>
		</dict>
		<key>ReservedMemory</key>
		<array>
			<dict>
				<key>Address</key>
				<integer>268435456</integer>
				<key>Comment</key>
				<string>HD3000: IGPU memory corruption errata</string>
				<key>Enabled</key>
				<false/>
				<key>Size</key>
				<integer>268435456</integer>
			</dict>
		</array>
	</dict>
</dict>
</plist>
`

**Comment by Andrey1970AppleLife** [comment]
Check the special version for you [OpenCore-0.6.3-RELEASE_MM71_test.zip](https://github.com/acidanthera/bugtracker/files/5450872/OpenCore-0.6.3-RELEASE_MM71_test.zip)
Pay attention that in 0.6.3 there are some changes in config.plist

**Comment by hectorskypl** [comment]
> Check the special version for you [OpenCore-0.6.3-RELEASE_MM71_test.zip](https://github.com/acidanthera/bugtracker/files/5450872/OpenCore-0.6.3-RELEASE_MM71_test.zip)
> Pay attention that in 0.6.3 there are some changes in config.plist

Hey Andrey, i tested your special version and it worked fine

**Comment by Andrey1970AppleLife** [comment]
Fixed in master https://github.com/acidanthera/OpenCorePkg/commit/1e8f75ee8dcd2eaf9f97d1f9fbe6edfe8833bc10
