### ISSUE TITLE
Failure with com.apple.iokit.IONDRVSupport patching

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#1244]
Except from debug log

```
19:213 00:012 OC: Prelinked injection VoodooPS2Controller.kext\Contents\PlugIns\VoodooPS2Keyboard.kext (Keyboard) - Success
19:283 00:069 OCAK: Local relocs 1716 on FFFFFF800422F000
19:314 00:031 OC: Prelinked injection WhateverGreen.kext () - Success
19:320 00:005 OC: Prelink size 68624384 kext offset 65114112 reserved 3510272
19:328 00:007 OCAK: KC TEXT is 65536 bytes with 50560 Mach-O headers need 848
19:479 00:151 OCAK: Failed to pk find com.apple.iokit.IONDRVSupport - Not Found
19:486 00:007 OC: Prelinked patcher result 0 for com.apple.iokit.IONDRVSupport (Suppress noisy logging of _doControl(23) a.k.a. _doControl(setCursor....)) - Not Found
19:510 00:024 OCAK: Patching invalid size 18000 with 18B5000 for com.apple.iokit.IOAHCIBlockStorage
```
config.plist entry for the patch
```
		<key>Patch</key>
		<array>
			<dict>
				<key>Arch</key>
				<string>x86_64</string>
				<key>Base</key>
				<string>__ZN17IONDRVFramebuffer10_doControlEPS_jPv</string>
				<key>Comment</key>
				<string>Suppress noisy logging of _doControl(23) a.k.a. _doControl(setCursor....)</string>
				<key>Count</key>
				<integer>1</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>
				wOgKiAAA65U=
				</data>
				<key>Identifier</key>
				<string>com.apple.iokit.IONDRVSupport</string>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data>
				</data>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>Replace</key>
				<data>
				wJCQkJCQ65U=
				</data>
				<key>ReplaceMask</key>
				<data>
				</data>
				<key>Skip</key>
				<integer>0</integer>
			</dict>
		</array>
```

**Comment by vit9696** [comment]
IONDRVSupport does not exist in the KC, so it cannot be patched. I believe force-injection is also not possible on Big Sur as EfiBoot (and the rest of UEFI) cannot access macOS root volume due to encryption and/or the way the boot flow is designed. All this should present in the pdf. Closing since we cannot really help here. The only workaround might be to inject IONDRVSupport manually, but I don't know whether this is not going to break things.

**Comment by nms42** [comment]
```
sudo kextcache -U /
```
would not bring it there?

**Comment by nms42** [comment]
Does the line
```
19:328 00:007 OCAK: KC TEXT is 65536 bytes with 50560 Mach-O headers need 848
```
relates to WhateverGreen.kext or to IONDRVSupport.kext?

**Comment by vit9696** [comment]
Updating kextcache will not bring it there are the kernel caches are now separated in 3 files (kernel collections): boot kernel extensions, auxiliary kernel extensions, and user kernel extensions. First two are built by Apple and are never modified by the end user. Last two are loaded by the kernel and thus are unavailable during boot. All GPU drivers belong to auxiliary kernel collection, making the only possible way to patch them is via Lilu and friends.

The line you mentioned relates to kernel injection in regards to kernel collection header size reservation, so it is rather WEG.
