### ISSUE TITLE
Wake up issuse on the hardware without Intel management engine interface

### ISSUE THREAD

**Issue by countrysideboy** [acidanthera/bugtracker#1245]
I have two mini fanless pcs, the manufacturer disable Intel me region according some hardware method.I cannot find the PCI devices of Intel management engine interface, and one can find the HECI devices in the ACPI table, while the other one has no any IMEI in ACPI. 

When I make the pc into sleep state and then wake up, some apps, such as chrome and hackintool, will be stucked until I reboot the computer.I have spent a lot of time to modify the bios but I could not make the Intel me enabled.

Is there any solution on a computer that does not have the Intel me function? I'm looking forward to a solution for this special situation.Thank you very much.

Opencore 0.6.2
Lilu 1.4.8
WhateverGreen 1.4.3
Intel i7-4650u
Intel i7-7500u

**Comment by vit9696** [comment]
Unfortunately not as we know. ME is required for proper IGPU functioning.
