### ISSUE TITLE
Brightness FN key(Up/Down) isn't working after hibernation wakeup

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#1246]
hi. i found one issue.
Brightness FN key(Up/Down) isn't working after hibernation wakeup

OC version: 0.6.3 last commit.
Hibernationfixup: last commit.
Hibernation Mode: NVRAM.
with _QXX Brightness key patched

long time ago, when used Clover, i had experienced same issue.

Brightness key is not working process.
Boot: brightness key works -> go into hibenation mode 3 -> press power button -> 
                       go macOS partition -> get desktop -> brightness key is not working(add. sound mute/play key is no problem)

thanks in advance.

**Comment by zhen-zen** [comment]
Could be some kind of broken EC firmware? So far I know another ThinkPad model suffered from similar issue.

**Comment by Sher1ocks** [comment]
> Could be some kind of broken EC firmware? So far I know another ThinkPad model suffered from similar issue.

i think it is yes.
battery indictor(icon) was changed. from charging to unplug adaptor.

boot - hibernation(3) and proximilty(1) mode with hibernation mode(NVRAM) In OC- wakeup problem(Backlight key and Battery indicator) - normal sleep - after wakeup,  there is no problem.

**Comment by zhen-zen** [comment]
I suppose the only possible fix is to examine your DSDT for `_PTS` and `_WAK` and find out the difference between argument 3 (S3 Sleep) and 4 (S4 Hibernation). Or maybe check corresponding Linux drivers for some vendor specific access.

**Comment by Sher1ocks** [comment]
> I suppose the only possible fix is to examine your DSDT for `_PTS` and `_WAK` and find out the difference between argument 3 (S3 Sleep) and 4 (S4 Hibernation). Or maybe check corresponding Linux drivers for some vendor specific access.

[DSDT.aml.zip](https://github.com/acidanthera/bugtracker/files/5475289/DSDT.aml.zip)
here is dsdt file. if you have time, please check it

**Comment by vit9696** [comment]
I do not think there is a definite bug in the PS2 driver but rather it is some sort of ACPI issue. For now I will close this.
