### ISSUE TITLE
OpenCore 0.6.3 [9a6d202] / Penryn X64 Exception

### ISSUE THREAD

**Issue by John-Jelatis** [acidanthera/bugtracker#1247]
*Since OC 0.6.3 is technically not released, if you remove this issue under this point:
- Only the latest released versions of OpenCore, Lilu, and other KEXTs are supported.
I won't blame you.
--

!!!X64 Exception Type - ... !!!
ERR: https://cdn.discordapp.com/attachments/250798964549484545/771915261666132008/image0.jpg
LOG: https://cdn.discordapp.com/attachments/250798964549484545/771918414117076992/message.txt

System in question has a Core 2 Duo E8600, GT 720 [1GB], 8GB DDR2 and otherwise is a standard Optiplex 760 motherboard/all.

**Comment by John-Jelatis** [comment]
Goldfish64 pointed out that it was my mistake - I accidentally used the wrong PartitionDxe, I needed PartitionDxeLegacy of course, but dragged in the wrong file. Sorry for the false alarm, and thanks a lot for the bootloader!

**Comment by NekoNya333** [comment]
i have the same error
![IMG_20210517_211651.jpg](https://user-images.githubusercontent.com/70910071/118537217-5e78a480-b755-11eb-884a-c1653ab9fe3a.jpg)
