### ISSUE TITLE
[OpenCore 6.2] My desktop is not respond when I upgraded to version 6.2

### ISSUE THREAD

**Issue by oo00spy00oo** [acidanthera/bugtracker#1248]
I was using version 6.1 normally. After that, I upgraded to version 6.2 and my desktop was not responded after login into the OS (after 30s or 1 minute). I tried many times with the same issue.
I must revert to the previous version (6.1).

**Comment by vit9696** [comment]
This issue does look like a support request. Please ask on the forums. If there is any evidence of a bug, come back with a different description.
