### ISSUE TITLE
Glitch on IGPU of i5-10200H

### ISSUE THREAD

**Issue by Xhichn** [acidanthera/bugtracker#1249]
The IGPU id is **0x9ba4**. After spoofed the IGPU with Coffee Lake’s device-id, I got GPU acceleration but there is a **glitch** like this on the screen. 

![IMG_0386](https://user-images.githubusercontent.com/30743533/97775305-8f6b0080-1b9a-11eb-9f6c-071dfc7bf31a.JPG)

I have changed multiple platform-ids but the results are the same, still a glitch. The same ids working well on other Comet Lake-H IGPU cause glitch on **10200H’s.**

The logs of OpenCore and Lilu and EFI are attached. 

[opencore-2020-10-31-083858.txt](https://github.com/acidanthera/bugtracker/files/5468799/opencore-2020-10-31-083858.txt)

[Lilu_1.4.8_20.1.txt](https://github.com/acidanthera/bugtracker/files/5468801/Lilu_1.4.8_20.1.txt)

[EFI.zip](https://github.com/acidanthera/bugtracker/files/5468803/EFI.zip)

**Comment by 10200H** [comment]
Me too

**Comment by vit9696** [comment]
Sorry to hear that. We do not have this GPU and have no plans to investigate the issue though.

**Comment by badstorm** [comment]
I understand you don't have the hardware to be able to test yourself, but do you have any suggestions, based on your experience, of where to try to investigate? 

I am a programmer and I would love to help you, but I need some guidance. Could the problem be in WhateverGreen or other plugin?

Thanks in any case for your work!

**Comment by Xhichn** [comment]
Thanks for your reply.

For this laptop, I have turned to forum for help and they told me this is related to an incorrect platform id setting. But after I have tested all the mobile Coffee Lake id, the problem still exists. I also tried to expand the VRAM to 2048MB or 3072MB but nothing changed. The Metal and QE/CI acceleration work well but the screen doesn't. 

I didn't test the HDMI output but I would do that later.

Maybe the GPU of i5-10200H isn't a UHD630 or UHD620 so the framebuffer patches don't work well on it. Could it be a low-end GT1 graphics card? (Though GPU-Z reports it as a GT2) 

The IGPU of 10300H works well on MacOS by faked as 0x3E9B, while the GPU of **i5-10200H (0x9BA4)** and **i5-10300H (0x9BC4)** look the same at [https://ark.intel.com/](https://ark.intel.com/content/www/us/en/ark/compare.html?productIds=201839,208016) except for their device ids. I think we need more details to identify the difference between them and find out the reason.

I never try to get GPU acceleration work without WhateverGreen. And I don't think this is caused by WhateverGreen and other plugins but a new issue they should fix it in the future.

**Comment by vit9696** [comment]
Last time I saw something like that was with AMD GPUs. I added some links below including a technical writeup, perhaps this could help you. However, you will most likely have to reverse-engineer quite a lot of system libraries to understand what is going on.

https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
https://github.com/osy86/HaC-Mini/issues/346
https://github.com/osy86/HaC-Mini/issues/7

**Comment by Xhichn** [comment]
> Last time I saw something like that was with AMD GPUs. I added some links below including a technical writeup, perhaps this could help you. However, you will most likely have to reverse-engineer quite a lot of system libraries to understand what is going on.
> 
> https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
> [osy86/HaC-Mini#346](https://github.com/osy86/HaC-Mini/issues/346)
> [osy86/HaC-Mini#7](https://github.com/osy86/HaC-Mini/issues/7)

Thanks for your providing information. I am sorry to reply you so late since I am quite occupied. 

Actually, I don't think it is the same issue as you mentioned. I tested the Metal support by running a Xcode sample and it looks well. Besides, my screen doesn't flicker and the resolution is right, 

It is interesting that when I attempt to make a screenshot, the output picture is broken. And when I  use the framebuffer platform id  0x3EA50000, the CoffeeLake one and check the IGPU info via Hackintool, it reports that the Metal device is **KabyLake Unknown**. However, when I switch to a KabyLake's platform id, such as 0x591B0000, I got a blackscreen. Could you provide any advice for me?

**Comment by Xhichn** [comment]
Maybe this problem is unsolvable because the IGPU is actually a low-end GT1.

I check the document from [Intel Graphics for Linux](https://01.org/linuxgraphics/documentation/code-documentation). And it seems like the IGPU of i5-10200H (0x9BA4) is the same as **Pentium's and Celeron's**. As the [document](https://01.org/sites/default/files/documentation/intel-gfx-bspec-osrc-cml-configurations.pdf) mentions, an Intel GT2 GPU should have 24 CUs while this one only has 12. 

So I think this problem is unsolvable.

**Comment by ManoChina** [comment]
same problem here, anybody got any solution?

**Comment by n-WN** [comment]
> 

solve? I have the same problem

**Comment by MahmaodRad** [comment]
Hi guys 
Fix it by  using skylake gpu id and install sequoia and using oclp got it to work but low Brightness 
![IMG_20241030_023241](https://github.com/user-attachments/assets/51891a43-2ef5-430e-b7de-4cfdf2895189)
![IMG_20241030_022327](https://github.com/user-attachments/assets/d60367a0-ba04-4e0e-bee5-842d9f024b3f)

**Comment by Bearsetsail** [comment]
> Hi guys Fix it by using skylake gpu id and install sequoia and using oclp got it to work but low Brightness ![IMG_20241030_023241](https://github.com/user-attachments/assets/51891a43-2ef5-430e-b7de-4cfdf2895189) ![IMG_20241030_022327](https://github.com/user-attachments/assets/d60367a0-ba04-4e0e-bee5-842d9f024b3f)

Hello, can you share your solution?

**Comment by MahmaodRad** [comment]
> > Hi guys Fix it by using skylake gpu id and install sequoia and using oclp got it to work but low Brightness ![IMG_20241030_023241](https://github.com/user-attachments/assets/51891a43-2ef5-430e-b7de-4cfdf2895189) ![IMG_20241030_022327](https://private-user-images.githubusercontent.com/98706620/381342209-d60367a0-ba04-4e0e-bee5-842d9f024b3f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ4OTM2ODEsIm5iZiI6MTc0NDg5MzM4MSwicGF0aCI6Ii85ODcwNjYyMC8zODEzNDIyMDktZDYwMzY3YTAtYmEwNC00ZTBlLWJlZTUtODQyZDlmMDI0YjNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE3VDEyMzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MTVjYmY0OTRiZmUwOWJjZjJhMmY1YmQ5Y2I5Yjg4MzcxNDZiN2ZiZjUwMmQxMTI0NzRjY2U3OGFmYTFhNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VYBl6hDOZkLA6GhkT3keGfu2yiUCkgmaTryc3u2TLS0)
> 
> Hello, can you share your solution?

i scrap this solution because it not using metal and it just the same as no igpu 
i think it a whatevergreen issue because it have to patch the excution unit   and the L3 Cache 
   L3 Cache Size**: 384 KB
     GT1 GPUs have a smaller L3 cache compared to GT2 (768 KB) or higher tiers.

 and Threads
   - **Threads per EU**: 7
     - Each EU can handle 7 threads simultaneously.
   - **Total Threads**: 84
     - Calculated as: `Total EUs (12) x Threads per EU (7) = 84 threads`.
     - the 630 have more from that

**Comment by kaiyuan12345678** [comment]
https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=2064099&highlight=10200
0x3EA50009
0x19160000
