### ISSUE TITLE
Preloaded Driver Causes Abrupt Crash on Classic MacPros with FileVault

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1250]
OpenCore crashes abruptly on attempts to boot into FileVault encrypted Mac OS instances when the OsxAptioFix3Drv driver is loaded before OpenCore is initiated. 

Unencrypted instances are not affected.

[opencore-2020-10-31-090836.txt](https://github.com/acidanthera/bugtracker/files/5468903/opencore-2020-10-31-090836.txt)

**Comment by vit9696** [comment]
If anything OsxAptioFix3Drv cannot be used with OpenCore regqrdless of the settings. Booter quirks replace it in a better fashion.

**Comment by dakanji** [comment]
Understood.

As a technical discussion, in the case where this might be needed outside OpenCore, can you shed any light on why the Halt happens if the user subsequently loads OpenCore and whether there is any quirk that can be changed to avoid this? One of "ProtectMemoryRegions", "ProtectSecureBoot" and "ProtectUefiServices" perhaps?
