### ISSUE TITLE
VoodooPS2: Sometimes trackpad doesn't work after sleep

### ISSUE THREAD

**Issue by maxhartung** [acidanthera/bugtracker#1252]
Hi guys,

The trackpad on HP EliteBook 840 G2, sometimes doesn't work after sleep. This mostly happens when I close it via the lid and it also takes more time to sleep compared to manually pressing on the sleep button via the Mac menu. The cursor doesn't move, I tried the key on the keyboard which enables and disables the touchpad but nothing.

I am using macOS 10.15.7 with Voodoo SMBus, VoodooRMI, VoodooPS2 - all the latest public versions.

The platformInfo was altered to remove personal informations and the ApCCID was cleared.

[EFI.zip](https://github.com/acidanthera/bugtracker/files/5471398/EFI.zip)

If you need any logs, I am happy to help.

**Comment by Andrey1970AppleLife** [comment]
It is necessary for you will address to authors VoodooSMBus, VoodooRMI
