### ISSUE TITLE
[REQUEST] Provide Option to Advertise/Provide SSE4.2 Support 

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1253]
Can an option be added to OpenCore to advertise SSE 4.2 support even if the CPU does not actually support this?

As you may know, there a kext (MouSSE) used to provide SSE4.2 support on units such as the MacPro3,1.

This works as a kind of emulation layer and transparently intercepts SSE 4.2 commands to provide the requested feature. (A subset of the features but most things only actually use one or two items)

It works very well when software, including some of Apple's internal stuff, **ASSUME** that SSE 4.2 is available and issue the commands. They are supposed to actually check for support but they have just been assuming this.

MouSSE does not actually change the CPU parameters as said and now, some software, such as Photoshop 21, are now actually **CHECKING** for SSE 4.2 and failing if not the CPU itself does have this capability.

If there was a way to send a response that was support was available, then the software would presumably proceed and   MouSSE would do its thing as normal.

Would be even nicer if the MouSSE capability could be incorporated into OpenCore

**Comment by vit9696** [comment]
Just set bit 20 in ecx (third dword) via CPUID virtualisation as explained in Intel SDM.

**Comment by dakanji** [comment]
For those of us for whom vit9696's advice might as well have been written in Martian, this works to spoof SSE4.2 support:
```
<key>Cpuid1Data</key>
<data>AAAAAAAAAAAAABAAAAAAAA==</data>
<key>Cpuid1Mask</key>
<data>AAAAAAAAAAAAABAAAAAAAA==</data>
```
