### ISSUE TITLE
Ice Lake Brightness

### ISSUE THREAD

**Issue by thefiredragon** [acidanthera/bugtracker#1256]
Sorry for creating a new issue,

I located that on my lenovo Slim 7 (Ice Lake) my Display values are different, so under linux I get:

echo $(cat brightness) $(cat actual_brightness) $(cat max_brightness)
96000 96000 96000

At the moment the PNFL patches uses for ice lake at this time.
65535 (0xffff)

So sorry again for reopen this here, I only noticed this, and I used before the PNLF-CFL.aml patch, best regards Dan

At the moment this Display is to dark at the max bright level to work with it. 
And there's no option to change the value, 'cause it's hard coded in whatevergreen or not?

**Comment by Andrey1970AppleLife** [comment]
Use https://github.com/acidanthera/WhateverGreen/blob/master/Manual/SSDT-PNLFCFL.dsl

**Comment by thefiredragon** [comment]
I think, you don't understand me, or you want that you do not understand me, I'm using exact this file and it's working, I have a brightness slider and it's working, BUT The Display is to dark at the highest level.

Under Linux I cut out the lmax variable, you are using here for ice lake 0xffff 
My machine has a higher value for the main display, it used 9600.
So I need to change 0xffff to 0x17700 But how I can do this?

**Comment by Andrey1970AppleLife** [comment]
CC @0xFireWolf, @hieplpvip

**Comment by thefiredragon** [comment]
Thank you, I'm not stupid, I'm using well patched tables, only want a little bit help here at this point.
Also I could provide pictures of this.

For better understanding, under Linux the lmax values can be found under /sys/class/backlight/intel_backlight    which I had provide for the yoga slim 7 here. And compared these values with the presets for kaby lake and coffee lake in whatevergreen,
Perhpas this is a manufactur thing and not happend to all ice lake devices.

**Comment by hieplpvip** [comment]
@thefiredragon The value `0xffff` that you see in WhateverGreen belongs to the old patch. With the new patch, WhateverGreen automatically rescaled the value to match the PWMMAX set by firmware, which should be `0x17700` in your case. WhateverGreen doesn't change PWMMAX.

See https://github.com/acidanthera/WhateverGreen/blob/80f47277/WhateverGreen/kern_igfx.cpp#L891-L932

**Comment by thefiredragon** [comment]
Okay thank you, but it does not do it.. 
Then I'm sadly out of my knowledge..
 it's not working at my point. But thank you for make this clearly

**Comment by Lorys89** [comment]
[video_2020-11-09_19-59-28.mp4.zip](https://github.com/acidanthera/bugtracker/files/5512691/video_2020-11-09_19-59-28.mp4.zip)
[video_2020-11-09_20-00-02.mp4.zip](https://github.com/acidanthera/bugtracker/files/5512694/video_2020-11-09_20-00-02.mp4.zip)

I uploaded the videos of my problem on ice lake, after 3 minutes from power on then the brightness starts and works

**Comment by thefiredragon** [comment]
@Lorys89  For me the brightness adjustment work fine, but it's too dark, I noticed sometimes when the laptop went to sleep and wake the display has full brightness but not all time this is happend.


[IMG_0148.mp4.zip](https://github.com/acidanthera/bugtracker/files/5516969/IMG_0148.mp4.zip)
