### ISSUE TITLE
Installation of AppleALC.kext 1.5.4 results in warning "relocation failed"

### ISSUE THREAD

**Issue by TonyC5** [acidanthera/bugtracker#1257]
When installing AppleALC.kext 1.5.4 in /Library/Extensions (using Hackintool 3.4.0), 'sudo kextcache -i /' produces the following warning (repeated 4 times):

kxld[as.vit9696.AppleALC]: Warning: relocation failed because some class in this kext didn't use the OSDeclareDefaultStructors and OSDefineMetaClassAndStructors, or didn't export all vtable symbols, so it still references IOService::_RESERVEDIOService0(), which has been patched with another symbol for binary compatibility. Please make sure all classes that inherit from OSObject use these macros.

This warning is not issued when installing AppleALC.kext 1.5.3 in /Library/Extensions.

My system is as follows:

- MacOS: Catalina 10.15.7
- SMBIOS MacModel: MacMini8,1
- Bootloader: CLOVER r5122

**Comment by Andrey1970AppleLife** [comment]
First, we don't support CLOVER and Hackintool.
Secondly, we don't recommend to set kexts in system. Use the bootloader for an kexts infection.

**Comment by TonyC5** [comment]
@Andrey1970AppleLife That's fine and I understand.  Regardless, the warning demonstrates that something may not be built correctly with AppleALC.kext 1.5.4.

**Comment by vit9696** [comment]
Worth checking. I will explore and provide a verdict when I can. Reopened for now.

**Comment by shrubberies** [comment]
AppleALC 1.5.4 doesn't load for me resulting in no sound device. Reverting to 1.5.3 works as expected.

**Comment by vit9696** [comment]
I was unable to identify any real issue in the builds, but I did find an issue with exporting class names that may have caused issues on 10.8. This one I fixed. If the issue persists — migrate to OpenCore from Clover. We do not support legacy bootloaders since last year.

**Comment by TonyC5** [comment]
@vit9696 I don't believe that this issue has anything to do with my selected Bootloader, but I will certainly test OC.  The warning appears during installation of AppleALC.kext 1.5.4 in /Library/Extensions (I know - you don't recommend kext installation in /L/E) when "kextcache -i /" is executed.

When you say the issue was with 10.8, I noticed that the Xcode Deployment Target for AppleALC.kext is 10.8.  Is the Xcode Deployment Target of 10.8 related to your fix?

**Comment by vit9696** [comment]
It was rather missing exports than the deployment target. Older os may not like it. For OC it is irrelevant.

**Comment by TonyC5** [comment]
@shrubberies Despite the warnings, AppleALC.kext 1.5.4 does appear to work fine for me.  Audio outputs are properly detected and auto sensing / port switching works fine.  Audio quality is still excellent (as I've always experienced with AppleALC).  I have installed AppleALC.kext in /Library/Extensions because that is my preferred kext installation methodology.  You may want to look for another reason why AppleALC.kext 1.5.4 is not working for you.

**Comment by TonyC5** [comment]
@vit9696 It appears that your fix of the "missing exports" has resolved this issue.  With a newer build of AppleALC.kext, I am no longer seeing the relocation failed errors when installing AppleALC.kext in /Library/Extensions.  I know that you don't condone/support the installation of kexts in /Library/Extensions, but I thought you'd like to know that your fix did resolve this issue.

**Comment by shrubberies** [comment]
I never identified why 1.54 failed for me but updating to 1.55 resolved my issue.
