### ISSUE TITLE
SMCDellSensors v1.1.8 makes kernel panic when booting macOS

### ISSUE THREAD

**Issue by gujiangjiang** [acidanthera/bugtracker#1258]
I'm using DELL XPS 15 9550 Laptop with OpenCore 0.6.3

Today i update the **VirtualSMC v1.1.8 contain SMCDellSensors** then it cant boot anymore and always kernel panic.

When delete SMCDellSensors it boot fine.

PS:SMCDellSensors v1.1.7 have **no problem with** booting macOS.

**Comment by gujiangjiang** [comment]
panic(cpu 6 caller 0xffffff800b9ee996): Kernel trap at 0xffffff800f573b15, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffff800eddd130, CR3: 0x000000002401a000, CR4: 0x00000000003626e0
RAX: 0x0000000000000050, RBX: 0xffffff800ef502e0, RCX: 0x0000000000000051, RDX: 0xffffffa0c4e4bb90
RSP: 0xffffffa0c4e4ba80, RBP: 0xffffffa0c4e4bac0, RSI: 0xffffff800facd6bd, RDI: 0xffffff800facd6bd
R8:  0x00000000000006fa, R9:  0x0000000000027000, R10: 0x0000000000000001, R11: 0x0000000000000000
R12: 0xffffff800f4f8f9c, R13: 0xffffff800eddd140, R14: 0xffffff937e7f75c0, R15: 0x0000000000000000
RFL: 0x0000000000010206, RIP: 0xffffff800f573b15, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0xffffff800eddd130, Error code: 0x0000000000000000, Fault CPU: 0x6, PL: 0, VF: 2

Backtrace (CPU 6), Frame : Return Address
0xffffffa0c4e4b4a0 : 0xffffff800b8bc65d 
0xffffffa0c4e4b4f0 : 0xffffff800b9fdba3 
0xffffffa0c4e4b530 : 0xffffff800b9ee5ca 
0xffffffa0c4e4b580 : 0xffffff800b861a2f 
0xffffffa0c4e4b5a0 : 0xffffff800b8bbefd 
0xffffffa0c4e4b6c0 : 0xffffff800b8bc1e8 
0xffffffa0c4e4b730 : 0xffffff800c0ba3ca 
0xffffffa0c4e4b7a0 : 0xffffff800b9ee996 
0xffffffa0c4e4b920 : 0xffffff800b9ee67d 
0xffffffa0c4e4b970 : 0xffffff800b861a2f 
0xffffffa0c4e4b990 : 0xffffff800f573b15 
0xffffffa0c4e4bac0 : 0xffffff800f564131 
0xffffffa0c4e4bb30 : 0xffffff800f56400e 
0xffffffa0c4e4bb60 : 0xffffff800fac9b4e 
0xffffffa0c4e4bc60 : 0xffffff800f56992d 
0xffffffa0c4e4bca0 : 0xffffff800f5627ed 
0xffffffa0c4e4bce0 : 0xffffff800bf81782 
0xffffffa0c4e4bd40 : 0xffffff800bf813bf 
0xffffffa0c4e4bda0 : 0xffffff800bf9599d 
0xffffffa0c4e4bdf0 : 0xffffff800c00bdae 
0xffffffa0c4e4be40 : 0xffffff800bfeb23b 
0xffffffa0c4e4bef0 : 0xffffff800bfeac6f 
0xffffffa0c4e4bf50 : 0xffffff800bfed9e6 
0xffffffa0c4e4bfa0 : 0xffffff800b86113e 
      Kernel Extensions in backtrace:
         as.vit9696.Lilu(1.4.9)[6E38576B-9675-3D9E-9763-5B0F9DA1B098]@0xffffff800f561000->0xffffff800f588fff
         as.lvs1974.SMCDellSensors(1.1.8)[3CF613AD-8611-3E70-9ECB-1F2F7CD87EE3]@0xffffff800fac9000->0xffffff800fad4fff
            dependency: as.vit9696.Lilu(1.4.9)[6E38576B-9675-3D9E-9763-5B0F9DA1B098]@0xffffff800f561000->0xffffff800f588fff
            dependency: as.vit9696.VirtualSMC(1.1.8)[3BC5157C-7E87-31A4-8C61-3770E078BA73]@0xffffff800f598000->0xffffff800f5adfff

Process name corresponding to current thread: kernel_task
Boot args: agdpmod=vit9696 

Mac OS version:
20A5384c

Kernel version:
Darwin Kernel Version 20.1.0: Thu Sep 24 20:22:06 PDT 2020; root:xnu-7195.40.89.100.3~1/RELEASE_X86_64
Kernel UUID: F53CBFCA-438C-30C2-BFD7-5D0588C5CD5F
KernelCache slide: 0x000000000b600000
KernelCache base:  0xffffff800b800000
Kernel slide:      0x000000000b610000
Kernel text base:  0xffffff800b810000
__HIB  text base: 0xffffff800b700000
System model name: MacBookPro13,3 (Mac-A5C67F76ED83108C)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 29206335516
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000006ccd5532d
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000e3ae46e18 0x0000000000000000
last started kext at 29205472199: @vecLib.kext	1.2.0 (addr 0xffffff800ea69000, size 700416)
loaded kexts:
as.acidanthera.BrcmPatchRAM3	2.5.5
me.kishorprins.VoodooInput	1.0.8
com.alexandred.VoodooI2CHID	1
as.acidanthera.voodoo.driver.PS2Keyboard	2.1.8
org.rehabman.driver.FakePCIID	1.3.15
com.alexandred.VoodooI2C	2.5.2
ru.joedm.SMCSuperIO	1.1.8
as.acidanthera.voodoo.driver.PS2!C	2.1.8
as.lvs1974.RTCMemoryFixup	1.0.7
org.coolstar.VoodooGPIO	1.1
as.vit9696.SMCProcessor	1.1.8
com.alexandred.VoodooI2CServices	1
as.lvs1974.SMCDellSensors	1.1.8
ru.usrsse2.SMCLightSensor	1.1.8
ru.usrsse2.SMCBatteryManager	1.1.8
as.vit9696.VirtualSMC	1.1.8
xyz.racermaster.NoTouchID	1.0.4
as.lvs1974.HibernationFixup	1.3.7
as.lvs1974.AirportBrcmFixup	2.1.1
as.acidanthera.BrcmFirmwareStore	2.5.5
com.hieplpvip.!ABacklightSmoother	1.0.0
as.acidanthera.BrightnessKeys	1.0.1
as.vit9696.WhateverGreen	1.4.4
org.acidanthera.NVMeFix	1.0.4
as.vit9696.!AALC	1.5.4
as.vit9696.Lilu	1.4.9
>!A!ISlowAdaptiveClocking	4.0.0
>ACPI_SMC_PlatformPlugin	1.0.0
>!A!IPCHPMC	2.0.1
>!A!ISKLGraphicsFramebuffer	16.0.0
>!AFIVRDriver	4.1.0
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.40.4
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ASmartBatteryManager	161.0.0
>!ATopCaseHIDEventDriver	4000.23
@filesystems.apfs	1677.40.35
@private.KextAudit	1.0
>AirPort.BrcmNIC	1400.1.1
>!AAHCIPort	346
>!AACPIEC	6.1
>!ARTC	2.0
>!AACPIButtons	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
|IOSlowAdaptiveClocking!F	1.0.0
|IONDRVSupport	585
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
|IOAccelerator!F2	439.35.2
@!AGraphicsDeviceControl	6.1.24
|IOGraphics!F	585
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|Broadcom!BHost!CUSBTransport	8.0.0d54
|IO!BHost!CUSBTransport	8.0.0d54
|IO!BHost!CTransport	8.0.0d54
>!UMergeNub	900.4.2
>!ABSDKextStarter	3
|IOSurface	289.3
@filesystems.hfs.encodings.kext	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AActuatorDriver	4400.23
>!AMultitouchDriver	4400.23
>!AInputDeviceSupport	4400.28
>!AHS!BDriver	4000.23
>IO!BHIDDriver	8.0.0d54
>!AXsanScheme	3
|IO80211!F	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
|IOAHCI!F	294
>!A!ILpssI2C	3.0.60
|IONVMe!F	2.1.0
>!AEFINVRAM	2.1
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFIRuntime	2.1
$!AImage4	3.0.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.0d54
|IOReport!F	47
|IO!BPacketLogger	8.0.0d54
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.40.3
|IOUSBMass!SDriver	184.40.5
|IOSCSIBlockCommandsDevice	436.40.5
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.5
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by vit9696** [comment]
keepsyms=1.
