### ISSUE TITLE
ice lake brightness and other

### ISSUE THREAD

**Issue by Lorys89** [acidanthera/bugtracker#1261]
I open this issue from my smartphone, soon I will upload the required debug files, for now I dont have the efi and ioreg available, è un laptop ice lake, Dell vostro 5401, i7 1065g7, 32gb ram ddr4 3200, 2 nvme of 500gb, igpu iris plus, the problem I encounter are:
the igpu if I do not use ssdt pnlf starts at brightness 0, and after 5 minutes alone switches to correct brightness, if I use apple blacklight smoother kext the brightness works but does not result at the maximum value, maybe I can not explain.
the power/sleep button doesn't work, ioreg sees them and they should work, i2c works and handles as well, but the pointer moves abnormally, and I can't map hdmi output.
[Dell Vostro 5401 - i7 1065G7.zip](https://github.com/acidanthera/bugtracker/files/5503925/Dell.Vostro.5401.-.i7.1065G7.zip)

**Comment by Lorys89** [comment]
I put my notebook at your disposal, so that I can test the various fixes for ice lake, I hope you do not close this issue, since on ice lake there is still a lot to be fixed, thank you and I await news.

**Comment by Lorys89** [comment]
other oddity, it shows up as soon as you start, you see desktop for 1 second, then black screen, and after 20 seconds desktop reappears, I use smbios macbook pro 16,2.
in bios the Dvmt is set to 64mb.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/1256
