### ISSUE TITLE
Unable to find disk for 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1264]
commit 409ec8c20fbd2f07d6a7db63aad3168877bde66e
```
u=$(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path | sed 's/.*GPT,\([^,]*\),.*/\1/'); \
  if [ "$u" != "" ]; then sudo diskutil mount $u ; fi
zsh: command not found:  
Password:
Unable to find disk for 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path	\EFI\OC\OpenCore.efi%00

```

**Comment by vit9696** [comment]
Please provide `nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path` output.

**Comment by startergo** [comment]
```
nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path
4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path	\EFI\OC\OpenCore.efi%00
```
It worked in the previous commits. That is how I mounted the EFI.

**Comment by vit9696** [comment]
Should be resolved.

**Comment by startergo** [comment]
Sure. Works now. 
I tried edit.efi tool and I set it up as running in text mode in the config, but it jumped back to the main menu.

**Comment by vit9696** [comment]
I do not know what does this tool do and you did not provide any logs. I assume it is a mistake on your side, because here tools work just fine in text mode.

**Comment by startergo** [comment]
It is the "edit" text function in Shell built as an efi binary. I am not sure if it can be launched as a tool or from within shell only. I was trying to test the new text mode. Certainly BootKicker.efi did not work on the cMP because of the broken text mode.

**Comment by vit9696** [comment]
* edit text function is not working on Mac Pro and will unlikely ever be due to https://github.com/acidanthera/bugtracker/issues/1080. It simply has no compatible input driver.
* BootKicker does not work on Mac Pro due to some other issue in the understanding of how Apple Boot Picker works. Boot Picker always runs in graphics mode, so it is not related either.
