### ISSUE TITLE
Patch VBIOS

### ISSUE THREAD

**Issue by pratiknborkar** [acidanthera/bugtracker#1265]
Hey guys is there any way to use Patch VBIOS in opencore like we do in Clover because my OC boot screen will always in 1024x786 it shoud be native like 1366x786.

Due to that always getting stretch Logo while boot also tried **-igfxvesa** but same result.

![OC Image](https://user-images.githubusercontent.com/48144872/98440165-239a1200-211d-11eb-823a-927367e38263.jpg)

[OC.zip](https://github.com/acidanthera/bugtracker/files/5504686/OC.zip)

**Comment by vit9696** [comment]
For OpenDuet and Intel GPUs there is ForceResolution. Please do not post support requests in the bugtracker. CC @Goldfish64
