### ISSUE TITLE
Ice Lake GPU work QE/CI but continuous flashes and glitch mouse pointer

### ISSUE THREAD

**Issue by badstorm** [acidanthera/bugtracker#1266]
I success install last Catalina and last Bug Sur on my Surface Pro 7 with i5 IceLake with Iris Plus using:
- OC 0.63
- Lilu 1.4.9
- WhateverGreen 1.4.4 (with -igfxcdc and -igfxdvmt)
following the last[Dortania documentation](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/icelake.html).

All works great except for continuous flashes and the mouse pointer icon that is glitched. There is a solution about that problem? Can be related to SSDT-PNLF-CFL?

I also attached a second monitor through HDMI and works without flashes, but the mouse pointer disappears and reappears only on the Surface screen.

I attach some examples to better understand:
![IMG_20201107_184446 2](https://user-images.githubusercontent.com/230256/98448437-44b62f00-212c-11eb-8098-2d887e86f205.jpg)
![surface-flashes](https://user-images.githubusercontent.com/230256/98448560-1edd5a00-212d-11eb-8870-c1f3111eccc0.gif)

Thanks in advance.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/1249

**Comment by badstorm** [comment]
If anyone has the same problem I have solved with this GPU configuration for glitches and change resolution for flashing:

- AAPL,ig-platform-id: **0000528A** 
- AAPL,slot-name: **Internal@0,2,0**
- AAPL00,override-no-connect: **00FFFFFF FFFFFF00 30E45505 A1000010 001A0104 A51A1178 03EE95A3 544C9926 0F505400 00000101 01010101 01010101 01010101 01013F7F B0A0A020 34703020 3A0004AD 10000019 000000FD 00303C00 0021040A 14141414 14140000 00FE004C 47445F4D 50302E32 5F0A2020 000000FE 004C5031 32335751 31313236 3034003F** 
- device-id: **528A0000** 
- framebuffer-fbmem: **00000003** 
- framebuffer-patch-enable: **1**
- framebuffer-stolenmem: **0000B003** 
- framebuffer-unifiedmem: **00000080**
