### ISSUE TITLE
NUC 8 appleALC issue after version 1.49

### ISSUE THREAD

**Issue by richtw370** [acidanthera/bugtracker#1267]
I 
[configs.zip](https://github.com/acidanthera/bugtracker/files/5506573/configs.zip)

am running a nuc8i5beh, with catalina 10.15.6. I use kext updater to periodically check and copy any updates to the efi partition on my drive. That has not been giving me troubles till recently. When I copied over appleALC 1.50 and rebooted I no longer had sound and it looks like the internal sound was not recognized. I copied back appleALC 1.49 and the sound worked fine.

I set up a USB drive with a full copy of my EFI file to see if I can setup config.plist to work with an updated version of the kext. I went through the Idiot’s guide to Lilu and its plugins, but so far I have not been successful. I tried all of the ID variations that Hackintool allows, but none of them work.

As soon as I revert to my old config file and kext version, the sound is back.

The attached zip has both the old config that works with 1.49 of appleALC, and the new one that I tried for the latest versions.

**Comment by Andrey1970AppleLife** [comment]
You shall an injection layout-id any method. In new config file it isn't present. The simplest method to add a bootargument: alcid=11
