### ISSUE TITLE
[Feature Request] Different icons for APFS volumes on the same container

### ISSUE THREAD

**Issue by juanjonol** [acidanthera/bugtracker#1270]
Hello,

First of all, thank you for the amazing work you do with OpenCore!

After reading the docs, I think there is no way to set a different icon for each APFS volume on an APFS container: we can add a `.VolumeIcon.icns` to the root of the `Preboot` volume, but then that same icon is applied to all volumes that share this `Preboot` volume (please correct me if I've missed anything).

I think it would made sense to be able to set different icons for each of this volumes.

The implementation I'd suggest is checking for a `.VolumeIcon.icns` on the folder of each bootable APFS volume in the `Preboot` volume, and only if this icon is not present, fallback to the icon on the `Preboot` root for that volume (or the generic icon if neither is found). This is consistent with the way it currently works, and it gracefully fallbacks to the current implementation if the icon is not present.

**Comment by vit9696** [comment]
This sounds about right to me, but is not supported by Apple. Could you file an issue about it in the Apple Feedback Assistant and include the identifier here?

I believe we can implement this for OC despite Apple not having it though.

**Comment by juanjonol** [comment]
Sure thing! The id is FB8892605.
