### ISSUE TITLE
ScanPolicy for Windows' BitLocker

### ISSUE THREAD

**Issue by juanjonol** [acidanthera/bugtracker#1271]
Hello,

Currently, to use `ScanPolicy` and a Windows partition with BitLocker the `OC_SCAN_ALLOW_FS_ESP` bit must be set, but this also means that all other EFI partitions are shown. Would it made sense to add a new flag for this, or maybe to expand the `OC_SCAN_ALLOW_FS_NTFS` to also include BitLocker-protected partitions?

**Comment by vit9696** [comment]
It is not possible to reliably distinguish Windows ESP partition from any other without accessing the files on it, which defeats the purpose. For this very reason this option cannot be offered.

My best suggestion is to use device type blacklisting for your purpose.
