### ISSUE TITLE
After removing OpenCore, Laptop Stuck at OEM Screen

### ISSUE THREAD

**Issue by talhabalaj** [acidanthera/bugtracker#1272]
So, I noticed that If I boot via OpenCore with `BootProtect -> Bootstrap`, It will set OpenCore to be the default Boot entry which is fine, But if I remove the OpenCore from my USB drive or just unplug the USB drive. My laptop will be stuck on the Lenovo Screen. I won't be able to open BIOS Setup or Boot options. If I plug the USB again, It will work. My guess is that default OpenCore entry is trying to find `boostrap.efi` and it can't find it (bc it doesn't exist) & gets stuck in on the Screen. It should just boot the second entry in the boot options but it doesn't. 

The problems gets bigger if I have OpenCore in my drive & I remove OpenCore for any purpose. I will have to remove the hard drive and use another computer to install OpenCore back.

Yes, Setting `BootProtect -> None` solves the problem, No entry? No Problem. But In this case, There is no entry in the boot options, So I have to open Boot options each time and select my drive which is the reason you guys added this behavior. 

Hope, I explained my issue good. Some research on the Internet tells me that this is only issue with older boards.

Model: Lenovo ideapad v570
CPU: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz 
GPU: Intel HD 3000 
WiFi: Intel Corporation Centrino Wireless-N + WiMAX 6150 [Not Supported] 
Ethernet: Realtek RTL8111/8168/8411 
RAM: 8GB 
SDD: SAMSUNG 840 PRO 128GB

**Comment by vit9696** [comment]
Well, we cannot help you with the boot failure issue as OpenCore is not present in the system when it happens. The general advice is not to use Bootstrap with OpenCore on USB.

**Comment by talhabalaj** [comment]
That's okay. I just wanted to inform you guys of the issue.
