### ISSUE TITLE
AppleALC 1.5.5 build error mach/mach_types.h

### ISSUE THREAD

**Issue by cowpod** [acidanthera/bugtracker#1275]
Latest version of AppleALC (1.5.5) fails to build on Xocde 12.1 and 12.2RC. The error is 

Lexical or Preprocessor Issue
'mach/mach_types.h' file not found
AppleALC_info.c

Did an OS reinstall and redownloaded Xcode (12.1 first, 12.2 the second time). Lilu headers are latest version.

**Comment by vit9696** [comment]
Use MacKernelSDK.

**Comment by chadify** [comment]
@vit9696 I'm still getting this error even after using MacKernelSDK.
