### ISSUE TITLE
[macrecovery.py] Downloading Big Sur recovery is not possible

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1277]
Goodmoning everyone, I was trying to download the latest BigSur Recovery since blessing the USB installer from an OS version previous than 11.0 does not work, and the source code confirms it:

![image](https://user-images.githubusercontent.com/46293832/98815130-0029dc80-2427-11eb-9d31-dbed89a9cc47.png)

But from macrecovery there is still no way of obtaining it. 

Maybe it is going to be available tomorrow (as "latest recovery") when we run:

![image](https://user-images.githubusercontent.com/46293832/98815259-251e4f80-2427-11eb-9cb7-8f78f1f140b9.png)

since as the time of writing this the latest "stable" version is 10.15.7 19H15?

The file in question is called handleFolder.c, source here: 

https://opensource.apple.com/source/bless/bless-105/handleFolder.c

**Comment by vit9696** [comment]
I don't know if it is going to be supported, but currently there is no way to download Big Sur Recovery OS from Apple servers. At least I know of none. Feel free to send a PR when this becomes available to update the README or just reply in this issue. Your current only option is to take the Recovery OS from the existing installation and copy it.

**Comment by 1alessandro1** [comment]
Thanks @vit9696, I managed to extract the recovery manually from the .app mounting the sharedsupport.dmg and using pacifist to analyze the 11.20GB+ zip file

Steps to reproduce:

Download the .app and search the SharedSupport.dmg image
![image](https://user-images.githubusercontent.com/46293832/98927057-59057d80-24d8-11eb-918f-c257bf4b33eb.png)


Mount the SharedSupport.dmg image and look for the biggest zip file in there

![image](https://user-images.githubusercontent.com/46293832/98927115-691d5d00-24d8-11eb-99c6-180c99627692.png)



Use [Pacifist](https://www.charlessoft.com) to extract the BaseSystem.dmg and BaseSystem.chunklist

![Screenshot 2020-11-12 at 11 12 36](https://user-images.githubusercontent.com/46293832/98927580-024c7380-24d9-11eb-9d48-020ec097f68e.png)


Follow the [dortania guide](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#downloading-macos-legacy-os) to create a `FAT32` volume and the folder `com.apple.recovery.boot` and copy BaseSystem.dmg and BaseSystem.chunklist inside

**Comment by Andrey1970AppleLife** [comment]
Simply wait release Big Sur, it wait not long.
In the presents time last os = Catalina.

**Comment by Andrey1970AppleLife** [comment]
Now you can download latest BigSur Recovery using command:
`./macrecovery.py -b Mac-E43C1C25D4880AD6 -m 00000000000000000 -os latest download`

**Comment by cheesycod** [comment]
it does not work anymore

**Comment by 1alessandro1** [comment]
> Thanks @vit9696, I managed to extract the recovery manually from the .app mounting the sharedsupport.dmg and using pacifist to analyze the 11.20GB+ zip file
> 
> Steps to reproduce:
> 
> Download the .app and search the SharedSupport.dmg image
> ![image](https://user-images.githubusercontent.com/46293832/98927057-59057d80-24d8-11eb-918f-c257bf4b33eb.png)
> 
> Mount the SharedSupport.dmg image and look for the biggest zip file in there
> 
> ![image](https://user-images.githubusercontent.com/46293832/98927115-691d5d00-24d8-11eb-99c6-180c99627692.png)
> 
> Use [Pacifist](https://www.charlessoft.com) to extract the BaseSystem.dmg and BaseSystem.chunklist
> 
> ![Screenshot 2020-11-12 at 11 12 36](https://user-images.githubusercontent.com/46293832/98927580-024c7380-24d9-11eb-9d48-020ec097f68e.png)
> 
> Follow the [dortania guide](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#downloading-macos-legacy-os) to create a `FAT32` volume and the folder `com.apple.recovery.boot` and copy BaseSystem.dmg and BaseSystem.chunklist inside

@cheesycod if necessary, use the method mentioned above to download the recovery if macrecovery doesn't work for you. 

I experienced very slow download speeds with the macrecovery tool compared to installinstallmacos.py from munki
