### ISSUE TITLE
Big Sur: 2nd Stage Installation loop

### ISSUE THREAD

**Issue by dylanwyoung** [acidanthera/bugtracker#1278]
Myself and a few other people are experiencing a loop while attempting to install Big Sur. This issue seems rare and is unique to a few of us. I experienced the issue in October while trying to install a beta. The other person I am in contact with has experienced it since before then, and is still experiencing it on the latest RC that was released following Apple's ARM event.

We are able to successfully begin the installation. About halfway through the install during one of the reboots during the installation process the system will go as follows: 
1. Installer is working
2. Restart, as expected
3. Select boot from 'MacOS Installer' to continue the installation
4. verbose boot, as expected
5. Apple Logo loading screen, reaches about 20% and stops
6. Verbose boot appears again. Blinking cursor shows for a moment. Then there is text for a split second.
7. instant shutdown/restart

Another user I am in contact with, [Narcyzzo](https://github.com/narcyzzo) describes the process as such: 
1. I boot the installer, pick disk to install
2. After 6 or 7 minutes of the installer copying files to disk, then 2nd stage begins (the system reboots)
3. I choose boot from "macos installer" 
4. Verbose boot begins, and then the apple logo appears
5. After a moment on this screen, the screen flashes to verbose for a split second, and the machine instantly restarts 

We have had no success in resolving this issue. We were all running Catalina with no issues prior to attempting install.

Some things we share in common (at least three of us confirmed):
- We all have Haswell machines
- We all have Z97 chipsets

We are not sure if this is a MacOS issue or an OpenCore issue.

Here is a link to my [Google Drive](https://drive.google.com/drive/folders/1HDhgszlHVswBmGER8oSusrzkNJ-UZuvB?usp=sharing). In that drive folder I have included a video of the install loop that I recorded, some screenshots, and the EFI folder I was using at that time. Please note that this was from October 11th while trying to install a beta, I believe it was beta 10. 

In the same folder is a video from Narcyzzo, showing his boot process from start to shutdown. Narcyzzo's video was recorded on November 11th while trying to install the latest RC.

I am also attaching the log Narcyzzo provided: [opencore-2020-11-11-230740.txt](https://github.com/acidanthera/bugtracker/files/5527551/opencore-2020-11-11-230740.txt)

Narcyzzo's specific hardware is:
- CPU: I5-4440
- MOBO: ASUS Z97 PRO GAMER
- GPU: GIGABYTE GTX660 OC
- AUDIO: ALC1150
- LAN: I218V2

I have not attempted this again myself with the newest RC but my experience is the same.

My hardware is:
- CPU: Intel Core i5-4690K 3.5 GHz Quad-Core Processor
- Motherboard: Asus Z97-AR ATX LGA1150 Motherboard
- Memory: (2) Crucial Ballistix Sport 8 GB (1 x 8 GB) DDR3-1600 Memory
- Storage: (Primary install drive) ADATA XPG GAMMIX S11 Pro 512 GB M.2-2280 NVME Solid State Drive 
- Storage: Samsung 850 EVO-Series 250 GB 2.5" Solid State Drive 
- Video Card - Radeon RX 580 8 GB

Please let me know if there is any additional information that would be helpful in solving this issue. I would be happy to help, as would [Narcyzzo](https://github.com/narcyzzo).

**Comment by vit9696** [comment]
Hi.

I checked the files and do not have a clue unfortunately. The log on the video is obviously not complete, and to be able to say anything I will need a complete one, which can be obtain via serial logging enabled with `debug=8 serial=5` boot arguments.

The reboot you see looks normal I would say. If you experience such issues my first idea would be a bug in Big Sur indeed. Otherwise things to check are:

* SATA controller compatibility issues. I think @khronokernel knows more about it.
* Faulty installer and/or faulty SSD. Unlikely but still possible.
* Some bug with Apple Secure Boot. Again unlikely, but you could try disabling it or using `x86legacy` model.
* Older kexts (I do not see them attached, so just make sure they are latest).
* Some weird SMC issue. You could try running with vsmcgen=1.

If nothing from this helps, try to get the serial log. It is not really possible to say what is going on otherwise.

**Comment by dylanwyoung** [comment]
Thank you for the reply! Narcyzzo tried your suggestions with no success. 

I posted about the issue on [Reddit.](https://www.reddit.com/r/hackintosh/comments/jt5pjx/z97_chipset_haswell_users/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) This user [replied](https://www.reddit.com/r/hackintosh/comments/jt5pjx/z97_chipset_haswell_users/gc3mgls/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3) with the following: 
"Serial will not help imo. This issue occurs on some LGA775 systems as well and dracoflar (aka Slav) used serial on his machine to see that it doesn't detect the update volume for some reason. I don't think there's anymore info to get from serial unfortunately, though confirming this would be helpful."

Narcyzzo spoke with Slav on Discord and his [response](https://ibb.co/ZfRQXwF) was: 
"Oh that bug, I already looked into it a long time ago. A slav I know has the same bug on X299 and my core2 Quad machine has the bug, we looked into it however me and Vit concluded it was a bug on Apple's end"

He also mentioned that he may look into it later. Based on this information it sounds like we would gather no new information from using a serial cable. If you deem it worthy of an attempt, I will be glad to get one and try it. 

Hopefully this information will at least help establish this as a new issue with Big Sur and could be added to the guide if you deem it necessary. We will wait for updates in the meantime. If I find anymore information that could be valuable in solving the problem I will respond here. Thank you again.

**Comment by maddie** [comment]
Having the exact same issue here, thought I was alone.

Asus Z97-A with 4790K, RX580.

Experienced something similar in previous macOS versions, which was caused by the 2nd monitor being connected to the GPU. Disconnecting the 2nd monitor always worked for me, so I thought this was the problem. But it seems for 11.0.1 it wasn't the case.

Gonna keep an eye on this issue and the Reddit thread 👀.

**Comment by stychos** [comment]
Having the same issue on Haswell-EP / x99 even with working NVRAM and with all mandatory ACPI patches (according to Dortania guides). Another machine with Broadwell-EP / C612 works well btw. Looks like some real macs affected too, there are numerous topics on Apple's Discussions.

**Comment by gulfik** [comment]
ASUS X99 DELUXE II 
Use UEFI Tool and replace 0F 84 B3 00 00 00 41 F6 to 90 E9 B3 00 00 00 41 F6 for NVRAM whitelist unlock.
This solves the problem of installing Big Sur. I think it works for other similar motherboards too.

**Comment by 1alessandro1** [comment]
> ASUS X99 DELUXE II
> Use UEFI Tool and replace 0F 84 B3 00 00 00 41 F6 to 90 E9 B3 00 00 00 41 F6 for NVRAM whitelist unlock.
> This solves the problem of installing Big Sur. I think it works for other similar motherboards too.

Everyone be careful with such tools, you can do serious damage to your motherboard's BIOS

**Comment by markoman78** [comment]
Finally I found ppl with same issue! Any solutions good solutions for this? Read about enabling native NVRAM but how to do this?

ASUS Z97, 4790K, RX570

**Comment by dylanwyoung** [comment]
> Finally I found ppl with same issue! Any solutions good solutions for this? Read about enabling native NVRAM but how to do this?
> 
> 
> 
> ASUS Z97, 4790K, RX570

Yep! Here is what worked for me and many others. Credit goes to the OP of the thread. 

https://www.insanelymac.com/forum/topic/345793-asus-maximus-vii-z97-hero-big-sur-open-core-guide/?do=findComment&comment=2745962

**Comment by markoman78** [comment]
> > Finally I found ppl with same issue! Any solutions good solutions for this? Read about enabling native NVRAM but how to do this?
> > ASUS Z97, 4790K, RX570
> 
> Yep! Here is what worked for me and many others. Credit goes to the OP of the thread.
> 
> https://www.insanelymac.com/forum/topic/345793-asus-maximus-vii-z97-hero-big-sur-open-core-guide/?do=findComment&comment=2745962

Just awesome! Didn't go that path tho, I installed BigSur on another computer, moved SSD to my main and then used Carbon Copy Cloner to clone that SSD to my main SSD. Bypassed NVRAM fix and system is working finally!! :)

Reason why I didn't try this method before is that didn't know what cause this issue. As soon as I read this NVRAM + Z97-PRO mobo fail, i got it..

Thanks!

**Comment by dylanwyoung** [comment]
> > > Finally I found ppl with same issue! Any solutions good solutions for this? Read about enabling native NVRAM but how to do this?
> 
> > > ASUS Z97, 4790K, RX570
> 
> > 
> 
> > Yep! Here is what worked for me and many others. Credit goes to the OP of the thread.
> 
> > 
> 
> > https://www.insanelymac.com/forum/topic/345793-asus-maximus-vii-z97-hero-big-sur-open-core-guide/?do=findComment&comment=2745962
> 
> 
> 
> Just awesome! Didn't go that path tho, I installed BigSur on another computer, moved SSD to my main and then used Carbon Copy Cloner to clone that SSD to my main SSD. Bypassed NVRAM fix and system is working finally!! :)
> 
> 
> 
> Reason why I didn't try this method before is that didn't know what cause this issue. As soon as I read this NVRAM + Z97-PRO mobo fail, i got it..
> 
> 
> 
> Thanks!

No problem! Just know that you will run into the same issue should you try to update. The bug affects both fresh installs and OS updates. You will need to repeat the same process for updates or perform the fix.

**Comment by markoman78** [comment]
> No problem! Just know that you will run into the same issue should you try to update. The bug affects both fresh installs and OS updates. You will need to repeat the same process for updates or perform the fix.

Well actually, Big Sur 11.2.1 updated just fine, suprisingly. Rebooted few times and done! Then I thought, was it NVRAM issue at all which caused that I didn't get the initial installation go through. Anyway, all good now.

**Comment by legale** [comment]
> ASUS X99 DELUXE II
> Use UEFI Tool and replace 0F 84 B3 00 00 00 41 F6 to 90 E9 B3 00 00 00 41 F6 for NVRAM whitelist unlock.
> This solves the problem of installing Big Sur. I think it works for other similar motherboards too.

I got asus x99-e with xeon e5-2678v3.
Asus x99-e bios 2101 with nvram unlocked and cfg unlocked. (i have replaced 0F84B300000041F6 with 90E9B300000041F6 and 0FBA6C24400F with 0FBA7424400F). Trying to pass big sur 11.2.2 installation second stage with no luck.
