### ISSUE TITLE
GOP boot screen with Nvidia videocards on EFI1.1 platforms

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1280]
@vit9696 as you know the Nvidia cards do not produce boot screen in OC on EFI 1.1 platforms like cMP. Lately we have been working on this issue. @joevt created a driver FakeEdk2Driver [joevtApps.zip](https://github.com/acidanthera/bugtracker/files/5530894/joevtApps.zip) to hack the EFI version to be 2.x and add the CreateEventEx function to boot services. Then we put the FakeEdk2Driver.efi in the drivers folder of  @dakanji  [RefindPlus](https://github.com/dakanji/RefindPlus) to load first and we put the extracted uncompressed NVIDIA [GOP EFI ROM](https://www.win-raid.com/t892f16-AMD-and-Nvidia-GOP-update-No-requests-DIY.html) loading as a second driver to load (in order) there. As a result the NVIDIA boot screen appeared at boot. See the attached log file.
[20v12d2308.txt.zip](https://github.com/acidanthera/bugtracker/files/5530943/20v12d2308.txt.zip)
Can this functionality be integrated in OC?

**Comment by joevt** [comment]
Setting the ST->Hdr.Revision is a hack. We might want a UnfakeEdk2Driver to load after the EFI drivers that require the hack are loaded.

Only the BS is modified. We might want to do Runtime Services as well, maybe make QueryVariableInfo and QueryCapsuleCapabilities functions that return an error (the former is rarely used by drivers and the latter is not supposed to be used by drivers).

The option roms that are not loaded because of an incompatible version check (as happens without the hack) exist in RAM pointed to by fields in the PciIo protocol. I have a ReloadPCIRom driver that can load from that RAM image (as long as the RAM image is not modified by the driver - some roms may erase the EFI image from RAM after it's decompressed, loaded, and started).

Ultimately, I would like to see boot screen before even the Mac Startup Manager is supposed to appear, using the Driver#### and DriverOrder nvram variables to load the FakeEdk2Driver, ReloadPCIRomDriver, a UGA on top of GOP driver (since Startup Manager probably uses UGA) and a Screenshot driver that doesn't require SimpleTextInEx protocol so a screenshot of the Startup Manager can be taken. With the drivers loaded this way, OpenCore and RefindPlus don't need to do that work.

**Comment by vit9696** [comment]
I believe it is ok to bump the BS version to 2.x without the ability to revert as it is really unlikely that anybody will real behave incorrectly with this change. I believe that it should become a quirk in OpenCore named `UpgradeBootServices` or something like that. Similarly I believe it is ok to add another UEFI quirk `ReloadOptionRoms` to reload the NVIDIA drivers.

I am not sure I have time to work on this, but if patches are submitted it will be great to merge them. I do not believe it is possible to do it better as `Driver####` is not supported by Mac EFI (from what I know).

**Comment by joevt** [comment]
I use Driver#### to load apfs.efi instead of apfs ROM patch or dosdude1 apfs patch. I can also use it to load nvme.efi and even ntfs.efi though I don't believe its a good idea to boot Windows EFI on MacPro3,1 - but maybe it can be made safe by doing whatever OpenCore does to make it safe for MacPro5,1?

With Driver####, I can see APFS partitions in the built-in Mac Startup Manager (hold option key at boot).
https://forums.macrumors.com/threads/macos-10-14-mojave-on-unsupported-macs-thread.2121473/post-29153786
https://forums.macrumors.com/threads/mac-pro-3-1-nvme-support-upgrade-guide-questions.2194878/post-28956730

Some other misc stuff:

Here's an example of booting the Startup Manager directly (aka BootPicker):
https://forums.macrumors.com/threads/updating-a-mac-pro-s-cpu-microcode.2114187/post-28956775
It uses a similar Device Path that the Boot Camp boot would use (when you select a Windows partition in the Startup Disk preferences panel).

There's a way to run either app (BootPicker or Boot Camp) from the EFI Shell:
https://forums.macrumors.com/threads/updating-a-mac-pro-s-cpu-microcode.2114187/post-28964173

rEFInd boots BIOS Boot Camp on old Macs by looking for certain known device paths.

**Comment by vit9696** [comment]
I guess in older Mac EFI Boot#### paths were indeed supported. That was dropped in 2015 or so due to security reasons. Perhaps MacPro3,1 firmware was simply left not updated.

In any case my points hold mostly. Ideally we get a patch for these in time for 0.6.4. Similarly for MBR booting.

**Comment by joevt** [comment]
I think I've only heard from one other person using my Driver#### info. Maybe you're right and newer Macs don't support it. I can test on a Mac mini 2018, or MacBook Pro 2015, but I don't think there's a point if they support GOP etc (except, a screenshot driver might be nice to get a screenshot of the Startup Manager).

I guess while we're talking about different boot methods, have you ever found a protocol that deals with the macOS HFS+ Finder Info record (seen using the `bless --info` command)? An HFS+ partition has a record with a file ID for a boot file. I haven't checked if there's a file system protocol function to convert file id to device path. The file ID usually points to /System/Library/CoreService/boot.efi but it could point to any file. This is one feature of the macOS Startup Manager that is missing from rEFInd and OpenCore. I believe APFS volumes have a similar Finder Info record.

**Comment by vit9696** [comment]
I am pretty sure it is not possible to set it from UEFI, but most likely bless is able to do it somehow. Have never investigated the exact steps needed, however.

**Comment by startergo** [comment]
@vit9696 Are the drivers loaded in specific alphabetic/numeric order or randomly? How do we define the loading order?

**Comment by startergo** [comment]
I [created an FFS driver module](https://github.com/pbatard/efifs/wiki/Adding-a-driver-to-a-UEFI-firmware) from the FakeEdk2Driver and inserted it as a second to load driver in the firmware and flashed the firmware:

![image](https://user-images.githubusercontent.com/7897244/99159216-902a8900-26a8-11eb-89ce-75df68a09ab7.png)
![image](https://user-images.githubusercontent.com/7897244/99159145-f82c9f80-26a7-11eb-944d-b16860309c63.png)
Upon boot the OC boot screen was visible on the NVIDIA Titan
[opencore-2020-11-14-232945.txt](https://github.com/acidanthera/bugtracker/files/5541591/opencore-2020-11-14-232945.txt)
This means that if only the code from the FakeEdk2Driver is loaded early enough OC should find a GOP replacement.

**Comment by vit9696** [comment]
Well, in this case you could just update your firmwares maybe?

**Comment by startergo** [comment]
I can but the average user may not be able. Some of them for sure will go for a brick. Also I use pluggable chip which can be easily reprogrammed in case of a brick.

**Comment by joevt** [comment]
> I [created an FFS driver module](https://github.com/pbatard/efifs/wiki/Adding-a-driver-to-a-UEFI-firmware) from the FakeEdk2Driver and inserted it as a second to load driver in the firmware and flashed the firmware:
> 
> This means that if only the code from the FakeEdk2Driver is loaded early enough OC should find a GOP replacement.

Is Driver#### not early enough to get the same behaviour?

**Comment by startergo** [comment]
> Is Driver#### not early enough to get the same behaviour?

I tried only the 2 drivers loading consecutively with  Driver####. Never tried FakeEdk2/FakeUEFI2 on its own through Driver####.

**Comment by vit9696** [comment]
Well, if there are no plans to upstream it can I just close the issue? Or did I misunderstand the situation?

**Comment by startergo** [comment]
We are still testing it so it is not ready for upstreaming. This make take a while.

**Comment by joevt** [comment]
The main issue is: while we can make RefindPlus or OpenCore appear on GOP display, the macOS stage 1, etc. booters may not appear (although I haven't tried OpenCore yet). Well, maybe getting the boot loader to appear is good enough. I don't know enough about the old Mac Pro boot procedure to understand what needs to be changed. Do we need AppleFramebufferInfo modifications (is that a thing on MacPro3,1 - I guess I should look to see if it exists - examine the current values - modify the values)? I don't think RefindPlus has the AppleFramebufferInfo option.

**Comment by vit9696** [comment]
10.4 EfiBoot uses AppleFramebufferInfo to get the framebuffer base address, which UGA protocol does not offer. I don't know about BootPicker. As for the changes it is really all about merging your driver into OpenCore or not, we can have that for easier maintenance. We do not see much value in making the boot screen available at pre-OpenCore stage.

Actually, keep in mind that we believe it is a good idea to eventually start flashing OpenCore into the firmwares when we get things sorted out here and there.

**Comment by startergo** [comment]
> As for the changes it is really all about merging your driver into OpenCore or not

Do you mean as a driver binary or inside the code?

**Comment by vit9696** [comment]
I do not think having it merged as a driver is idiomatic for OpenCore, so as a quirk, yes.

**Comment by dakanji** [comment]
Implementations from RefindPlus:
1. [AmendSysTable.c](https://github.com/dakanji/RefindPlus/blob/GOPFix/EfiLib/AmendSysTable.c) : Call `AmendSysTable()` to change HDR Revision and provide CreateEventEx
2. [AcquireGOP.c](https://github.com/dakanji/RefindPlus/blob/GOPFix/EfiLib/AcquireGOP.c) : Call `AcquireGOP()` to reload OptionROM and reinstall GOP

**Comment by vit9696** [comment]
Until there is going to be a PR for this or any further discussion I am closing it. Current solution to embed a firmware driver seems to be more or less ok, and there is not much desire to merge this stuff to OpenCore on your side from what it seems.

**Comment by dakanji** [comment]
A lot more difficult to incorporate into OC and whether the effort of an attempt is worth it is debatable. 

I personally think at this time that it is best to roll the two actions into one driver which those that need this, Kepler users on cMP, can add to OC as needed. Actual full incorporation into OC can be revisited later.

Just my own thoughts.

**Comment by vit9696** [comment]
Implemented, make sure to test it.

**Comment by startergo** [comment]
Does not even create a log file:
![image](https://user-images.githubusercontent.com/7897244/114486669-4c4a9a00-9bdc-11eb-8f2a-ad8227f62596.png)

**Comment by vit9696** [comment]
Yes, that should be fixed in master. EDK II is borked beyond salvation sometimes.

**Comment by startergo** [comment]
[opencore-2021-04-13-110919.txt](https://github.com/acidanthera/bugtracker/files/6303291/opencore-2021-04-13-110919.txt)
Stuck at the beginning.

**Comment by vit9696** [comment]
Do not see any issue on our end and the new code is not even able. Must be some issue at yours. E.g. corrupted ESP.

**Comment by startergo** [comment]
If I disable ```ForgeUefiSupport``` and ```ReloadOptionRoms``` it boots normally.
[opencore-2021-04-13-171026.txt](https://github.com/acidanthera/bugtracker/files/6305473/opencore-2021-04-13-171026.txt)

**Comment by vit9696** [comment]
Which of the two causes it?

**Comment by startergo** [comment]
I don't think the OpenCanopy issue is related to the GOP reload change it happened before that.

**Comment by vit9696** [comment]
OpenCanopy could be related to resource updates.

**Comment by startergo** [comment]
That was first thing I tried. Resource updates did not help (actually did not see them updated either)

**Comment by vit9696** [comment]
cc @mhaeuser

**Comment by mhaeuser** [comment]
> That was first thing I tried. Resource updates did not help (actually did not see them updated either)

They will help when you properly overwrite all files. :)

**Comment by startergo** [comment]
Just replaced the whole directory and it worked. Apparently update newer files does not work here.

**Comment by dakanji** [comment]
@startergo ... is RP in the picture?

You might want to soft bless OC and boot directly if so (to make sure RP is not impacting anything ... thinking about the ReloadGOP bit which it also does)

**Comment by startergo** [comment]
> @startergo ... is RP in the picture?
> 
> You might want to soft bless OC and boot directly if so (to make sure RP is not impacting anything ... thinking about the ReloadGOP bit which it also does)

I disabled that feature in RP.

**Comment by vit9696** [comment]
You were ask to report which of the two quirks causes a hang. Also, disabling RP is a requirement at least during the tests.

**Comment by startergo** [comment]
I thought both of them have to be enabled?

**Comment by vit9696** [comment]
Correct. But that does not change my question.

**Comment by startergo** [comment]
Anyway it is the ```ForgeUefiSupport``` which hangs. RP or no RP it does not matter.
[opencore-2021-04-13-195157.txt](https://github.com/acidanthera/bugtracker/files/6306403/opencore-2021-04-13-195157.txt)
[opencore-2021-04-13-200007.txt](https://github.com/acidanthera/bugtracker/files/6306406/opencore-2021-04-13-200007.txt)

**Comment by vit9696** [comment]
Thx, please recheck master. I believe I identified and fixed at least one issue.

**Comment by startergo** [comment]
[opencore-2021-04-13-225912.txt](https://github.com/acidanthera/bugtracker/files/6307131/opencore-2021-04-13-225912.txt)
Another error

**Comment by vit9696** [comment]
This one is fixed in master. Was pushed some time after the message.

**Comment by vit9696** [comment]
@dakanji did you have any issues with driver connection after enabling NVIDIA Option ROM loading? Seems to hang there…

**Comment by startergo** [comment]
Works now. I had some kernel panics with Big Sur, but HS booted fine and OpenCanopy was working always
[Archive.zip](https://github.com/acidanthera/bugtracker/files/6307268/Archive.zip)

**Comment by priezz** [comment]
@startergo, trying the same and I am stuck on "Connecting drivers...". Please advice, how many graphics cards do you have installed and if the cable is connected to the unflashed nvidia or to the one with the Apple firmware?

**Comment by dakanji** [comment]
> did you have any issues with driver connection after enabling NVIDIA Option ROM loading?

Don't actually use these GPU but got no reports so far.
@startergo was a tester at the time (I believe still uses this) and can chime in.

BTW, "MyFreePool" is a convenience function that always checks if the pointer is NULL and only applies "FreePool" when it is not NULL. So there is some laziness in using it that needs checking if using FreePool directly.

**Comment by startergo** [comment]
> @startergo, trying the same and I am stuck on "Connecting drivers...". Please advice, how many graphics cards do you have installed and if the cable is connected to the unflashed nvidia or to the one with the Apple firmware?

I have 2 or 3 cards, but only the unflashed NVIDIA was connected to a display. I may have connected GT-120 at some point to select OC. There is something odd though, because I can't boot BS as it panics. I can boot HS (which is HFS+).

**Comment by startergo** [comment]
When I disabled the 2 quirks it boots normally to Big Sur, so it is definitely related.

**Comment by priezz** [comment]
Well, I could successfully launch OpenCore with the output to the unflashed Nvidia card, but I also have the issue booting Big Sur (from SATA), so I think it could be connected with some changes in 0.6.9.

**Comment by vit9696** [comment]
Well, any panic log?

**Comment by priezz** [comment]
There was just one panic and in all the other cases OS is just stuck on the boot (the bar is about 30% long). The odd thing is that `com.apple.driver.AppleIntelMCEReporter` is being loaded when it should not (`AppleMCEReporterDisabler.kext` is enabled in the config). So here is the panic log, two OC logs and the OC config.

[panic-2021-04-14-005158.txt](https://github.com/acidanthera/bugtracker/files/6309132/panic-2021-04-14-005158.txt)
[opencore-2021-04-14-005152.txt](https://github.com/acidanthera/bugtracker/files/6309134/opencore-2021-04-14-005152.txt)
[opencore-2021-04-14-004549.txt](https://github.com/acidanthera/bugtracker/files/6309135/opencore-2021-04-14-004549.txt)
[config.plist.txt](https://github.com/acidanthera/bugtracker/files/6309173/config.plist.txt)

**Comment by vit9696** [comment]
I do not know about `AppleMCEReporterDisabler.kext`, but there is a boot argument (`-nehalem_error_disable`) to reliably turn it off.

**Comment by priezz** [comment]
> I do not know about `AppleMCEReporterDisabler.kext`, but there is a boot argument (`-nehalem_error_disable`) to reliably turn it off.

The [doc](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.tex) gives an advice that this param disables `AppleTyMCEDriver`. Is `AppleIntelMCEReporter` a part of that?

**Comment by vit9696** [comment]
Oh, I thought you meant the other one. Then it is quite strange. No, these are entirely separate drivers.

According to the log you have no kext injection at all.

**Comment by priezz** [comment]
> Are you sure you have kexts enabled?
They are enabled in the config (attached in the prev post). The same config works well with 0.6.8, which knows nothing about the two new quirks.

**Comment by vit9696** [comment]
Right, I think I know the reason. Please try https://github.com/acidanthera/OpenCorePkg/commit/3bcd69da2ea7dfc1f40b5ae378bf00c54dddeb06 once it builds.

**Comment by priezz** [comment]
I have just tried the most recent build (#9ca899d). Here are the findings:
1. Still no video when the other card (GT 120) is installed. I have tried 3 scenarios:
  a) cable plugged to the card with metal support (GTX 780 Ti)
  b) cable plugged to GT 120
  c) cable plugged to GT 120 and re-plugged to GTX 780 before pressing the return key on the EFI choice at the native boot menu;
2. Big Sur hanged at the bootscreen on the first try (waited > 30 min) but booted normally on the second one.

The logs are attached.
[novideo-2021-04-15-142112.txt](https://github.com/acidanthera/bugtracker/files/6319468/novideo-2021-04-15-142112.txt)
[novideo-2021-04-15-143141.txt](https://github.com/acidanthera/bugtracker/files/6319469/novideo-2021-04-15-143141.txt)
[novideo-2021-04-15-143552.txt](https://github.com/acidanthera/bugtracker/files/6319470/novideo-2021-04-15-143552.txt)
[hanged-on-bootscreen-2021-04-15-144130.txt](https://github.com/acidanthera/bugtracker/files/6319471/hanged-on-bootscreen-2021-04-15-144130.txt)
[normal-2021-04-15-160200.txt](https://github.com/acidanthera/bugtracker/files/6319472/normal-2021-04-15-160200.txt)

**Comment by vit9696** [comment]
Well, there is no plan to support GT 120 and GTX 780 at the same time. The firmware does not play all too well in this case, and there is little reason for us to debug. Does it work fine with just the GTX 780 installed with Big Sur?

**Comment by startergo** [comment]
> 1. Still no video when the other card (GT 120) is installed.

If there is an EFI card installed, but not connected to a display it will not work. It never did even with AMD. If there are 2 AMD's one with EFI vbios and one without the boot screen will always appear on the EFI card and if it is not connected to a display it will not boot. If there are no EFI cards installed disconnecting the display will leave that card in dormant state and the initialization will occur on the card connected to a display.

**Comment by vit9696** [comment]
@startergo does BS work for you with the latest build on an NVIDIA GPU?

**Comment by startergo** [comment]
Big Sur and Catalina boot without a problem

**Comment by priezz** [comment]
@vit9696 , is it possible to ignore/disable the installed GT 120? It is not likely to remove it completely from the system as soon as at the moment it is the only way to have the native boot menu.

**Comment by joevt** [comment]
> @vit9696 , is it possible to ignore/disable the installed GT 120? It is not likely to remove it completely from the system as soon as at the moment it is the only way to have the native boot menu.

I suppose any action that has an "apply to all" semantic, such as loading GOP from all GPUs that don't have GOP, should have an ability to ignore specific cases - either by device location (EFI device path) or IDs (vendor/product combo) or whatever.

**Comment by startergo** [comment]
> is it possible to ignore/disable the installed GT 120?

Can you please elaborate what are you trying to achieve? If you want to disable the GT-120 while booted to OSX that is possible. It will still be active for the Apple and Opencore bootpickers, but will be disabled half way during boot from the bootpicker to the login screen. You can either disable the driver in the device properties:
https://forums.macrumors.com/threads/opencore-on-mac-pro-7-1.2283835/post-29590262
or through SSDT:
https://forums.macrumors.com/threads/opencore-on-mac-pro-7-1.2283835/post-29726901

**Comment by vit9696** [comment]
I do not think GT 120 gets its Option ROM reloaded. Rather it dies for another reason. Since the Option ROM loading code checks for child handles if I remember correctly.

**Comment by priezz** [comment]
> > is it possible to ignore/disable the installed GT 120?
> 
> Can you please elaborate what are you trying to achieve?

For some reason there is no video output to my GTX 780 when GT 120 is installed (even when HDMI cord is plugged into 780 only). So I want OpenCore to ignore 120. Ideally OpenCore could ignore all cards with no display connected.

**Comment by vit9696** [comment]
It is not about OpenCore, it is about your firmware, I am afraid.

**Comment by startergo** [comment]
> For some reason there is no video output to my GTX 780 when GT 120 is installed

As I said it will not happen. The boot screen will be on the GT-120. GT-120 must be connected to a display.

**Comment by dakanji** [comment]
There is a potential issue as this creates an  incomplete UEFI 2.x implementation and users will have issues if they chainload anything that may try to use UEFI 2.x specific functionality from OC.

OC basically needs to restore things back to the original setup before it boots anything so as not to pass an essentially broken table on.

**Comment by vit9696** [comment]
I do not believe there is any real situation as CreateEventEx is the only function added, and we implemented it to a certain level.

**Comment by dakanji** [comment]
As an example, rEFInd (and variants) will test for UEFI 2.x. If detected, they will try to use `gRT->QueryVariableInfo` which will not be present. 

Some, such as MacPro3,1 users, may chain-load rEFInd so as to boot into Legacy Windows. They should chain-load OC from RP of course, but people are stubborn ;-) 

Seems there is a potential for other situations to arise.

**Comment by vit9696** [comment]
`gRT` has HeaderVersion field. rEFInd should check it instead.

**Comment by dakanji** [comment]
> PS: Situation in this case arises because the tools would have queried the revision on gBS or gST earlier, stashed the result then use this to decide on a gRT call later but it is not unreasonable to expect that the revisions would be the same.

That is just an example btw. Point is that OC is changing something fundamental which something downstream will not be expecting to be changed.

**Comment by mhaeuser** [comment]
> That is just an example btw. Point is that OC is changing something fundamental which something downstream (not necessarily rEFInd) will not be expecting to be changed.

@dakanji It is a rarely needed quirk, and only broken code dies. If you give us an example where it is non-trivial to just update downstream, we may adapt it.
