### ISSUE TITLE
HEVC is missing on UHD 630 after sleep

### ISSUE THREAD

**Issue by phucnguyen2411** [acidanthera/bugtracker#1282]
i'm using the latest version of WEG with internal graphic card UHD 630 only. After sleep the system and wake again, HEVC is missing and can't open any application related to graphic works. 
My macos version is 11.0.1 and i'm using WEG without any flag extra too.

**Comment by vit9696** [comment]
I guess it is a driver bug, not WEGs. Sorry.

**Comment by phucnguyen2411** [comment]
thanks, i have finger out this issue.
