### ISSUE TITLE
AppleALC cause kernel panic when plug into an HDMI display.

### ISSUE THREAD

**Issue by kingo132** [acidanthera/bugtracker#1283]
I'm using
AppleALC version: 1.5.4 DEBUG
CPU: Icelake i5-1035g7
My sound card: ALC269
My Device info and EFI can be found here: https://github.com/kingo132/GPD-Win-Max-Hackintosh

Things happen after I successfully injected my sound card with AppleALC and layout-id 100. Before this, I'm using VoodooHDA. The system crash every time when I plug an HDMI display. Here is the panic log:

[crash.202011112227.applealc.txt](https://github.com/acidanthera/bugtracker/files/5535730/crash.202011112227.applealc.txt)

I have to add No-hda-gfx to DeviceProperityes to work around this problem.
My framebuffer configuration looks like this. However, I found all framebuffer-conn-type doesn't take effect. No matter I set the type to 00040000 or 00080000, all I see in IORegistryExplorer is 00040000. Maybe WhatEverGreen currently not support ice lake very well.
![Screen Shot 2020-11-13 at 4 56 39 PM](https://user-images.githubusercontent.com/46492291/99049129-70746180-25d1-11eb-9d5d-b8ed3669e6dd.png)

**Comment by vit9696** [comment]
That's not AppleALC but rather AppleHDA driver, see the stacktrace.

**Comment by bohenao** [comment]
I have a same problem. it shows appleHDA in kernel panic log, but when I add boot-args: -alcoff then display works. (without digi-sound)

**Comment by kingo132** [comment]
> I have a same problem. it shows appleHDA in kernel panic log, but when I add boot-args: -alcoff then display works. (without digi-sound)

You completely disabled AppleALC with alcoff ... You can just add No-hda-gfx option to work around this. However, it will disable the audio of the external display completely.

**Comment by bohenao** [comment]
> > I have a same problem. it shows appleHDA in kernel panic log, but when I add boot-args: -alcoff then display works. (without digi-sound)
> 
> You completely disabled AppleALC with alcoff ... You can just add No-hda-gfx option to work around this. However, it will disable the audio of the external display completely.
> From what I discovered so far, the cause of this panic may be related to Apple Icelake Graphic driver was not patched properly by WhatEverGreen. That dp->hdmi patch does not work very well with Apple Icelake Graphic driver.

Thanks, I tried on IGPU, but hda-gfx and No-hda-gfx existe the same time. the same in HDEF.

<img width="678" alt="Screen Shot 2020-12-16 at 4 06 48 pm" src="https://user-images.githubusercontent.com/26623937/102307639-0298cc80-3fb9-11eb-9c7d-1bd4c206648a.png">

**Comment by kingo132** [comment]
> > > I have a same problem. it shows appleHDA in kernel panic log, but when I add boot-args: -alcoff then display works. (without digi-sound)
> > 
> > 
> > You completely disabled AppleALC with alcoff ... You can just add No-hda-gfx option to work around this. However, it will disable the audio of the external display completely.
> > From what I discovered so far, the cause of this panic may be related to Apple Icelake Graphic driver was not patched properly by WhatEverGreen. That dp->hdmi patch does not work very well with Apple Icelake Graphic driver.
> 
> Thanks, I tried on IGPU, but hda-gfx and No-hda-gfx existe the same time. the same in HDEF.
> 
> <img alt="Screen Shot 2020-12-16 at 4 06 48 pm" width="678" src="https://user-images.githubusercontent.com/26623937/102307639-0298cc80-3fb9-11eb-9c7d-1bd4c206648a.png">

I think you should leave only No-hda-gfx = "onboard-1".
Both the igpu and your sound card should have this No-hda-gfx property.

**Comment by bohenao** [comment]
> > > > I have a same problem. it shows appleHDA in kernel panic log, but when I add boot-args: -alcoff then display works. (without digi-sound)
> > > 
> > > 
> > > You completely disabled AppleALC with alcoff ... You can just add No-hda-gfx option to work around this. However, it will disable the audio of the external display completely.
> > > From what I discovered so far, the cause of this panic may be related to Apple Icelake Graphic driver was not patched properly by WhatEverGreen. That dp->hdmi patch does not work very well with Apple Icelake Graphic driver.
> > 
> > 
> > Thanks, I tried on IGPU, but hda-gfx and No-hda-gfx existe the same time. the same in HDEF.
> > <img alt="Screen Shot 2020-12-16 at 4 06 48 pm" width="678" src="https://user-images.githubusercontent.com/26623937/102307639-0298cc80-3fb9-11eb-9c7d-1bd4c206648a.png">
> 
> I think you should leave only No-hda-gfx = "onboard-1".
> Both the igpu and your sound card should have this No-hda-gfx property.

Thanks, will give a try.

**Comment by kingo132** [comment]
I can confirm this panic is caused by this modification which introduces a new patch to fix the audio issue for ice lake CPUs.
https://github.com/acidanthera/AppleALC/pull/615
After I rollback this patch to the old one (which has two patches for ice lake), then the panic disappears. But it comes out another issue that the sound device is recognized, but no sound is output.

**Comment by kingo132** [comment]
Speaking of this patch in AppleALC for ice lake CPU
```
find：0E0000BE020000004889DF
Replace：0E0000B8709D0000EB0690
```
I compared AppleHDA.kext before and after the patch
![image](https://user-images.githubusercontent.com/46492291/115713894-1b6f1f80-a3a9-11eb-806f-257d093d002d.png)
It is just replacing some sort of device id to 0x9D70. I find these device ids here.
https://cateee.net/lkddb/web-lkddb/SND_HDA_INTEL.html
They can be summarized here.
```
vendor: 8086 ("Intel Corporation"), device: 02c8 ("Comet Lake PCH-LP cAVS")
vendor: 8086 ("Intel Corporation"), device: 06c8 ("Comet Lake PCH cAVS")
vendor: 8086 ("Intel Corporation"), device: 080a ("Moorestown Audio Ctrl")
vendor: 8086 ("Intel Corporation"), device: 0a0c ("Haswell-ULT HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 0c0c ("Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 0d0c ("Crystal Well HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 0f04 ("Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 160c ("Broadwell-U Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 1a98
vendor: 8086 ("Intel Corporation"), device: 1c20 ("6 Series/C200 Series Chipset Family High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 1d20 ("C600/X79 series chipset High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 1e20 ("7 Series/C216 Chipset Family High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 2284 ("Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 2668 ("82801FB/FBM/FR/FW/FRW (ICH6 Family) High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 269a ("631xESB/632xESB High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 27d8 ("NM10/ICH7 Family High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 284b ("82801H (ICH8 Family) HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 2911
vendor: 8086 ("Intel Corporation"), device: 293e ("82801I (ICH9 Family) HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 293f
vendor: 8086 ("Intel Corporation"), device: 3198 ("Celeron/Pentium Silver Processor High Definition Audio")
vendor: 8086 ("Intel Corporation"), device: 34c8 ("Ice Lake-LP Smart Sound Technology Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 38c8
vendor: 8086 ("Intel Corporation"), device: 3a3e ("82801JI (ICH10 Family) HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 3a6e ("82801JD/DO (ICH10 Family) HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 3b56 ("5 Series/3400 Series Chipset High Definition Audio")
vendor: 8086 ("Intel Corporation"), device: 3dc8
vendor: 8086 ("Intel Corporation"), device: 43c8 ("Tiger Lake-H HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 490d
vendor: 8086 ("Intel Corporation"), device: 4b55
vendor: 8086 ("Intel Corporation"), device: 4b58
vendor: 8086 ("Intel Corporation"), device: 4dc8
vendor: 8086 ("Intel Corporation"), device: 51c8
vendor: 8086 ("Intel Corporation"), device: 5a98 ("Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster")
vendor: 8086 ("Intel Corporation"), device: 7ad0
vendor: 8086 ("Intel Corporation"), device: 811b ("US15W/US15X/US15L/UL11L SCH [Poulsbo] HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 8c20 ("8 Series/C220 Series Chipset High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 8ca0 ("9 Series Chipset Family HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 8d20 ("C610/X99 series chipset HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 8d21 ("C610/X99 series chipset HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 9c20 ("8 Series HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 9c21 ("8 Series HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 9ca0 ("Wildcat Point-LP High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: 9d70 ("Sunrise Point-LP HD Audio")
vendor: 8086 ("Intel Corporation"), device: 9d71 ("Sunrise Point-LP HD Audio")
vendor: 8086 ("Intel Corporation"), device: 9dc8 ("Cannon Point-LP High Definition Audio Controller")
vendor: 8086 ("Intel Corporation"), device: a0c8 ("Tiger Lake-LP Smart Sound Technology Audio Controller")
vendor: 8086 ("Intel Corporation"), device: a170 ("100 Series/C230 Series Chipset Family HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: a171 ("CM238 HD Audio Controller")
vendor: 8086 ("Intel Corporation"), device: a1f0
vendor: 8086 ("Intel Corporation"), device: a270
vendor: 8086 ("Intel Corporation"), device: a2f0 ("200 Series PCH HD Audio")
vendor: 8086 ("Intel Corporation"), device: a348 ("Cannon Lake PCH cAVS")
vendor: 8086 ("Intel Corporation"), device: a3f0
vendor: 8086 ("Intel Corporation"), device: f0c8
vendor: 8086 ("Intel Corporation"), device: f1c8
```
In order to do a detailed test, I tested all of these ids, by replacing the XXXX in 0E0000B8XXXX0000EB0690 with these device ids. And here is the test result
```
These ids won't crash, and everything seems fine
0c0c
1c20
1d20
1e20
8c20
8ca0
9c20
9ca0
a170
a348
These ids will crash (in my device, which is GPD WinMax)
9c70
9c71
```
So if you encounter problems using this patch in AppleAlc. Try to modify the patch to another device id.
I'm using a348 now, and everything seems fine. So the patch in AppleALC should be modified to this
```
find：0E0000BE020000004889DF
Replace：0E0000B848A30000EB0690
```

**Comment by Jarvay** [comment]
> Speaking of this patch in AppleALC for ice lake CPU
> 
> ```
> find：0E0000BE020000004889DF
> Replace：0E0000B8709D0000EB0690
> ```
> 
> I compared AppleHDA.kext before and after the patch
> ![image](https://user-images.githubusercontent.com/46492291/115713894-1b6f1f80-a3a9-11eb-806f-257d093d002d.png)
> It is just replacing some kind of device id with 0x9D70. I find these device ids here.
> https://cateee.net/lkddb/web-lkddb/SND_HDA_INTEL.html
> They can be summarized as follows.
> 
> ```
> vendor: 8086 ("Intel Corporation"), device: 02c8 ("Comet Lake PCH-LP cAVS")
> vendor: 8086 ("Intel Corporation"), device: 06c8 ("Comet Lake PCH cAVS")
> vendor: 8086 ("Intel Corporation"), device: 080a ("Moorestown Audio Ctrl")
> vendor: 8086 ("Intel Corporation"), device: 0a0c ("Haswell-ULT HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 0c0c ("Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 0d0c ("Crystal Well HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 0f04 ("Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 160c ("Broadwell-U Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 1a98
> vendor: 8086 ("Intel Corporation"), device: 1c20 ("6 Series/C200 Series Chipset Family High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 1d20 ("C600/X79 series chipset High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 1e20 ("7 Series/C216 Chipset Family High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 2284 ("Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 2668 ("82801FB/FBM/FR/FW/FRW (ICH6 Family) High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 269a ("631xESB/632xESB High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 27d8 ("NM10/ICH7 Family High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 284b ("82801H (ICH8 Family) HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 2911
> vendor: 8086 ("Intel Corporation"), device: 293e ("82801I (ICH9 Family) HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 293f
> vendor: 8086 ("Intel Corporation"), device: 3198 ("Celeron/Pentium Silver Processor High Definition Audio")
> vendor: 8086 ("Intel Corporation"), device: 34c8 ("Ice Lake-LP Smart Sound Technology Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 38c8
> vendor: 8086 ("Intel Corporation"), device: 3a3e ("82801JI (ICH10 Family) HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 3a6e ("82801JD/DO (ICH10 Family) HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 3b56 ("5 Series/3400 Series Chipset High Definition Audio")
> vendor: 8086 ("Intel Corporation"), device: 3dc8
> vendor: 8086 ("Intel Corporation"), device: 43c8 ("Tiger Lake-H HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 490d
> vendor: 8086 ("Intel Corporation"), device: 4b55
> vendor: 8086 ("Intel Corporation"), device: 4b58
> vendor: 8086 ("Intel Corporation"), device: 4dc8
> vendor: 8086 ("Intel Corporation"), device: 51c8
> vendor: 8086 ("Intel Corporation"), device: 5a98 ("Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster")
> vendor: 8086 ("Intel Corporation"), device: 7ad0
> vendor: 8086 ("Intel Corporation"), device: 811b ("US15W/US15X/US15L/UL11L SCH [Poulsbo] HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 8c20 ("8 Series/C220 Series Chipset High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 8ca0 ("9 Series Chipset Family HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 8d20 ("C610/X99 series chipset HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 8d21 ("C610/X99 series chipset HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 9c20 ("8 Series HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 9c21 ("8 Series HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 9ca0 ("Wildcat Point-LP High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 9d70 ("Sunrise Point-LP HD Audio")
> vendor: 8086 ("Intel Corporation"), device: 9d71 ("Sunrise Point-LP HD Audio")
> vendor: 8086 ("Intel Corporation"), device: 9dc8 ("Cannon Point-LP High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: a0c8 ("Tiger Lake-LP Smart Sound Technology Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: a170 ("100 Series/C230 Series Chipset Family HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: a171 ("CM238 HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: a1f0
> vendor: 8086 ("Intel Corporation"), device: a270
> vendor: 8086 ("Intel Corporation"), device: a2f0 ("200 Series PCH HD Audio")
> vendor: 8086 ("Intel Corporation"), device: a348 ("Cannon Lake PCH cAVS")
> vendor: 8086 ("Intel Corporation"), device: a3f0
> vendor: 8086 ("Intel Corporation"), device: f0c8
> vendor: 8086 ("Intel Corporation"), device: f1c8
> ```
> 
> In order to do a detailed test, I tested all of these ids, by replacing the XXXX in 0E0000B8XXXX0000EB0690 with these device ids. I'm testing with my icelake device: GPD WinMax. And here is the test result
> 
> ```
> These ids won't crash, and everything seems fine
> 0c0c
> 1c20
> 1d20
> 1e20
> 8c20
> 8ca0
> 9c20
> 9ca0
> a170
> a348
> These ids will crash
> 9c70
> 9c71
> Other ids either have no sound device or no sound output.
> ```
> 
> So if you encounter problems using this patch in AppleAlc. Try to modify the patch to another device id.
> I'm using a348 now, and everything seems fine. So the patch in AppleALC should be modified to this
> 
> ```
> find：0E0000BE020000004889DF
> Replace：0E0000B848A30000EB0690
> ```

Maybe different laptop needs different device id. 
I tried `a348`, speaker works but headphone not.
Both work with `a170`.

**Comment by DottiestDuke47** [comment]
Could you post the plist section of your patch please?

**Comment by Jarvay** [comment]
> Could you post the plist section of your patch please? @Jarvay

![image](https://user-images.githubusercontent.com/16760347/122754374-2ae5e880-d2c6-11eb-9114-d4de989133f3.png)

You can find that in Resource/Controllers.plist

**Comment by phuminsingla** [comment]
> Speaking of this patch in AppleALC for ice lake CPU
> 
> ```
> find：0E0000BE020000004889DF
> Replace：0E0000B8709D0000EB0690
> ```
> 
> I compared AppleHDA.kext before and after the patch ![image](https://user-images.githubusercontent.com/46492291/115713894-1b6f1f80-a3a9-11eb-806f-257d093d002d.png) It is just replacing some kind of device id with 0x9D70. I find these device ids here. https://cateee.net/lkddb/web-lkddb/SND_HDA_INTEL.html They can be summarized as follows.
> 
> ```
> vendor: 8086 ("Intel Corporation"), device: 02c8 ("Comet Lake PCH-LP cAVS")
> vendor: 8086 ("Intel Corporation"), device: 06c8 ("Comet Lake PCH cAVS")
> vendor: 8086 ("Intel Corporation"), device: 080a ("Moorestown Audio Ctrl")
> vendor: 8086 ("Intel Corporation"), device: 0a0c ("Haswell-ULT HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 0c0c ("Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 0d0c ("Crystal Well HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 0f04 ("Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 160c ("Broadwell-U Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 1a98
> vendor: 8086 ("Intel Corporation"), device: 1c20 ("6 Series/C200 Series Chipset Family High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 1d20 ("C600/X79 series chipset High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 1e20 ("7 Series/C216 Chipset Family High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 2284 ("Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 2668 ("82801FB/FBM/FR/FW/FRW (ICH6 Family) High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 269a ("631xESB/632xESB High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 27d8 ("NM10/ICH7 Family High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 284b ("82801H (ICH8 Family) HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 2911
> vendor: 8086 ("Intel Corporation"), device: 293e ("82801I (ICH9 Family) HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 293f
> vendor: 8086 ("Intel Corporation"), device: 3198 ("Celeron/Pentium Silver Processor High Definition Audio")
> vendor: 8086 ("Intel Corporation"), device: 34c8 ("Ice Lake-LP Smart Sound Technology Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 38c8
> vendor: 8086 ("Intel Corporation"), device: 3a3e ("82801JI (ICH10 Family) HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 3a6e ("82801JD/DO (ICH10 Family) HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 3b56 ("5 Series/3400 Series Chipset High Definition Audio")
> vendor: 8086 ("Intel Corporation"), device: 3dc8
> vendor: 8086 ("Intel Corporation"), device: 43c8 ("Tiger Lake-H HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 490d
> vendor: 8086 ("Intel Corporation"), device: 4b55
> vendor: 8086 ("Intel Corporation"), device: 4b58
> vendor: 8086 ("Intel Corporation"), device: 4dc8
> vendor: 8086 ("Intel Corporation"), device: 51c8
> vendor: 8086 ("Intel Corporation"), device: 5a98 ("Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster")
> vendor: 8086 ("Intel Corporation"), device: 7ad0
> vendor: 8086 ("Intel Corporation"), device: 811b ("US15W/US15X/US15L/UL11L SCH [Poulsbo] HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 8c20 ("8 Series/C220 Series Chipset High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 8ca0 ("9 Series Chipset Family HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 8d20 ("C610/X99 series chipset HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 8d21 ("C610/X99 series chipset HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 9c20 ("8 Series HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 9c21 ("8 Series HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 9ca0 ("Wildcat Point-LP High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: 9d70 ("Sunrise Point-LP HD Audio")
> vendor: 8086 ("Intel Corporation"), device: 9d71 ("Sunrise Point-LP HD Audio")
> vendor: 8086 ("Intel Corporation"), device: 9dc8 ("Cannon Point-LP High Definition Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: a0c8 ("Tiger Lake-LP Smart Sound Technology Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: a170 ("100 Series/C230 Series Chipset Family HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: a171 ("CM238 HD Audio Controller")
> vendor: 8086 ("Intel Corporation"), device: a1f0
> vendor: 8086 ("Intel Corporation"), device: a270
> vendor: 8086 ("Intel Corporation"), device: a2f0 ("200 Series PCH HD Audio")
> vendor: 8086 ("Intel Corporation"), device: a348 ("Cannon Lake PCH cAVS")
> vendor: 8086 ("Intel Corporation"), device: a3f0
> vendor: 8086 ("Intel Corporation"), device: f0c8
> vendor: 8086 ("Intel Corporation"), device: f1c8
> ```
> 
> In order to do a detailed test, I tested all of these ids, by replacing the XXXX in 0E0000B8XXXX0000EB0690 with these device ids. I'm testing with my icelake device: GPD WinMax. And here is the test result
> 
> ```
> These ids won't crash, and everything seems fine
> 0c0c
> 1c20
> 1d20
> 1e20
> 8c20
> 8ca0
> 9c20
> 9ca0
> a170
> a348
> These ids will crash
> 9c70
> 9c71
> Other ids either have no sound device or no sound output.
> ```
> 
> So if you encounter problems using this patch in AppleAlc. Try to modify the patch to another device id. I'm using a348 now, and everything seems fine. So the patch in AppleALC should be modified to this
> 
> ```
> find：0E0000BE020000004889DF
> Replace：0E0000B848A30000EB0690
> ```

![Screen Shot 2565-11-24 at 18 43 17](https://user-images.githubusercontent.com/5608098/203778081-1bd24211-f8fb-4631-beab-64d171a80a72.png)
![Screen Shot 2565-11-24 at 18 43 09](https://user-images.githubusercontent.com/5608098/203778311-86efcd84-14c0-49c5-9ae4-0ca5301dc510.png)
![Screen Shot 2565-11-24 at 18 42 54](https://user-images.githubusercontent.com/5608098/203778341-7a9f179e-b952-4703-bbb7-2ef19d1b7cd7.png)

Infinix X2 i3-1005g1 not show audio. Please help me.

**Comment by Vorshim92** [comment]
Hello everyone and happy holidays! It's been a few years now... has a solution been found to make HDMI audio work together with AppleALC? I know the only way is to disable AppleALC and using just AppleGFXHDA with only a patch for renaming HDAS to HDEF to make it work, but doing so results in the loss of speakers/headphones. Isn't there a way to integrate this AppleGFXHDA solution inside appleALC? :)

**Comment by m0d16l14n1** [comment]
> Hello everyone and happy holidays! It's been a few years now... has a solution been found to make HDMI audio work together with AppleALC? I know the only way is to disable AppleALC and using just AppleGFXHDA with only a patch for renaming HDAS to HDEF to make it work, but doing so results in the loss of speakers/headphones. Isn't there a way to integrate this AppleGFXHDA solution inside appleALC? :)

Nope
