### ISSUE TITLE
Touchpad sometimes doesn't work when Filevault enabled

### ISSUE THREAD

**Issue by josemmc95** [acidanthera/bugtracker#1284]
I realized that with Filevault enabled, sometimes the touchpad doesn't work when the system is ready.

It's a I2C Elan.

I first noticed a few days ago when upgrading to the latest Catalina suplemental update.

Is it a known bug and is there a solution?

Thank you in advanced!

**Comment by Andrey1970AppleLife** [comment]
Address to the author I2C Elan kext.
