### ISSUE TITLE
Kernel Panic on first reboot installing Big Sur

### ISSUE THREAD

**Issue by josemmc95** [acidanthera/bugtracker#1285]
I'm having this kernel panic when trying to update to Big Sur.

I'm using OC 0.6.3 with all kexts updated.

Could it be related with secure boot and ApECID?

![IMG_1297](https://user-images.githubusercontent.com/62221854/99073607-845e9a00-25b6-11eb-8f15-fc789ee6ad7c.jpg)

Edit: I've tried making an usb installer (kernel panic when booting Install macOS Big Sur), disabling secure boot and ApECID, and all of them throws the same kernel panic.

Edit 2: I've uploaded EFI and OC log.

[EFI.zip](https://github.com/acidanthera/bugtracker/files/5537197/EFI.zip)

[opencore-2020-11-13-135440.txt](https://github.com/acidanthera/bugtracker/files/5537198/opencore-2020-11-13-135440.txt)

**Comment by khronokernel** [comment]
https://github.com/dortania/bugtracker/issues/105
