### ISSUE TITLE
Any fix for Intel 600p NVMe Drive?

### ISSUE THREAD

**Issue by antoniomcr96** [acidanthera/bugtracker#1286]
As I previously reported in my (wrong) AppleALC issue ( https://github.com/acidanthera/bugtracker/issues/1262 , sorry in the end it wasn't related to applealc itself) this SSD doesn't seem to work well with MacOS.

Basically sometimes, especially when rebooting from Windows, MacOS runs this disk well with correct speed: 600MB/s write; 1400MB/s read. System works perfectly. After some random work the speed of the disk suddenly decreases (150MB/s r/w) and the system suffers from freezing and bad performance (and so does the audio) when accessing the disk. The disk temperature is ok.

Rebooting and Shutdown usually doesn't solve the problem and almost always results in the same kernel panic:
```
 panic(cpu 2 caller 0xffffff8004346cde): nvme: "Fatal error occurred. CSTS=0xffffffff US[1]=0x0 US[0]=0x14d VID=0x8086 DID=0xf1a5
. FW Revision= PSF109C\n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-557.40.10/Common/IONVMeController.cpp:5471
Backtrace (CPU 2), Frame : Return Address
0xffffffa0779eb990 : 0xffffff8001cbc65d mach_kernel : _handle_debugger_trap + 0x3dd
0xffffffa0779eb9e0 : 0xffffff8001dfdba3 mach_kernel : _kdp_i386_trap + 0x143
0xffffffa0779eba20 : 0xffffff8001dee5ca mach_kernel : _kernel_trap + 0x55a
0xffffffa0779eba70 : 0xffffff8001c61a2f mach_kernel : _return_from_trap + 0xff
0xffffffa0779eba90 : 0xffffff8001cbbefd mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffa0779ebbb0 : 0xffffff8001cbc1e8 mach_kernel : _panic_trap_to_debugger + 0x268
0xffffffa0779ebc20 : 0xffffff80024ba3ca mach_kernel : _panic + 0x54
0xffffffa0779ebc90 : 0xffffff8004346cde com.apple.iokit.IONVMeFamily : __ZN16IONVMeController14CommandTimeoutEP16AppleNVMeRequest.cold.1
0xffffffa0779ebcb0 : 0xffffff800432b407 com.apple.iokit.IONVMeFamily : __ZN16IONVMeController13FatalHandlingEv + 0x1af
0xffffffa0779ebe10 : 0xffffff800432f2d5 com.apple.iokit.IONVMeFamily : __ZN16IONVMeController24HandleControllerPowerOffEv + 0x5b
0xffffffa0779ebe40 : 0xffffff800432b133 com.apple.iokit.IONVMeFamily : __ZN16IONVMeController11ThreadEntryEv + 0x215
0xffffffa0779ebe80 : 0xffffff8001d00ff5 mach_kernel : _thread_call_delayed_timer + 0x4a5
0xffffffa0779ebef0 : 0xffffff8001d01f04 mach_kernel : _thread_call_delayed_timer + 0x13b4
0xffffffa0779ebfa0 : 0xffffff8001c6113e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[62375F02-FA66-340F-9AE9-21C5E02E3200]@0xffffff8004324000->0xffffff800434dfff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[453E94EB-6952-35D1-9048-531216A59600]@0xffffff8003030000->0xffffff8003039fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[AE7667C9-F66A-3159-BB9F-382D50A192C7]@0xffffff80031d7000->0xffffff80031ebfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[18E1EFFB-84A7-3440-B547-E789CDDF154C]@0xffffff80045df000->0xffffff8004606fff
            dependency: com.apple.iokit.IOReportFamily(47)[CA61C5AE-5FC0-3924-86D7-694C4FEE5F02]@0xffffff8004615000->0xffffff8004617fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[AE3C8EC0-2E3A-3E72-97AA-006BDD90FB18]@0xffffff80046ff000->0xffffff8004710fff
```
Sleep suffers also from the same kp.
The count of _Unsafe Shutdowns:_ from `smartctl`increase.
Tried NVMeFix with and without APST but it doesn't fix. Here is reported the same experience: https://jiashun-zheng.medium.com/hackintosh-journey-on-a-lenovo-yoga-720-81d3f0717922 (section "Poor NVME performance")

I'm opening this issue to ask if NVMeFix could fix this kind of problem or at least avoid the kernel panic. Or, instead, the advice is to replace (again) the drive and maybe put Intel 600p In the blacklist of drives for macOS in the interest of other users who own / plan to use the same disk.

Thanks as always.

**Comment by vit9696** [comment]
Last similar thing I saw is https://github.com/acidanthera/bugtracker/issues/1193. No plans to really work on the issue due to no hardware.

**Comment by antoniomcr96** [comment]
Thanks for your reply, I had already seen that post and I tried to set `forceRenderStandby=0` in my boot args with no benefits.
Don’t worry, i give up on sleep and force-shutdown the laptop when needed until, probably, a new ssd.
Keep up all the good work. Have a nice weekend
