### ISSUE TITLE
No bootloader  - have to boot from BIOS-BOOT-BOOTx64.efi

### ISSUE THREAD

**Issue by lonewulfeu** [acidanthera/bugtracker#1287]
I have trouble getting the bootloader to show in Legacy. Basically I am landing on the screen below and have to go to Boot Maintenance Manager - Boot from file and select EFI/BIOS/BOOT/BOOTx64.efi to boot which starts up correctly (I am coming from Clover). Any ideas about what I am missing?

Seems like my boot exec is failing, I used this method to make it (legacy bios) but still not working - can someone provide the exec for me? Screenshots attached - thanks for your work!

https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#legacy-setup

EDIT: I found this shell command that remakes the bios boot partition but mine gets emptied with each reboot:
https://github.com/socheatsok78/MSI-GP62MVR-7RF-OpenCore-EFI/blob/master/README.md#troubleshooting

![Screen Shot 2020-11-13 at 21 18 45](https://user-images.githubusercontent.com/29228761/99126560-14c8c900-260f-11eb-8421-4619f7650535.png)

![image0](https://user-images.githubusercontent.com/29228761/99126535-0aa6ca80-260f-11eb-8e01-e842e45a22f9.jpg)

![C1A3BB62-B0EE-4494-BD64-AD3BDD0ECAB4](https://user-images.githubusercontent.com/29228761/99126623-36c24b80-260f-11eb-81f8-faa1210714c0.jpeg)

**Comment by vit9696** [comment]
Use LegacyBoot utility coming with the package. Only the Duet coming from OpenCore is supported and it has no Boot Manager.
