### ISSUE TITLE
Kext stall X86PlatformPlugin and missing AGPM

### ISSUE THREAD

**Issue by thainhan07103** [acidanthera/bugtracker#1288]
OC 0.6.3 of me work great on 10.15.7 and Big Sur beta 6
After update Big Sur 20B29 stuck Kext stall: X86PlatformPlugin 3-5 minutes after that boot successful
I create ssdt and CPU Friends but not work

**Comment by thainhan07103** [comment]
![FB_IMG_1605324674355](https://user-images.githubusercontent.com/71615879/99138629-94cd4e00-2664-11eb-91d4-c71fb8163f03.jpg)
![FB_IMG_1605324652218](https://user-images.githubusercontent.com/71615879/99138634-99920200-2664-11eb-8e97-3c38d4688e8a.jpg)
![FB_IMG_1605324643198](https://user-images.githubusercontent.com/71615879/99138637-9c8cf280-2664-11eb-8125-6f2302ef6833.jpg)

**Comment by thainhan07103** [comment]
![Uploading FB_IMG_1605324741275.jpg…]()

**Comment by thainhan07103** [comment]
![FB_IMG_1605324643198](https://user-images.githubusercontent.com/71615879/99138664-cd6d2780-2664-11eb-8134-88de7e441a04.jpg)
![FB_IMG_1605324652218](https://user-images.githubusercontent.com/71615879/99138667-d0681800-2664-11eb-8450-2bda9592176f.jpg)
![FB_IMG_1605324674355](https://user-images.githubusercontent.com/71615879/99138668-d2ca7200-2664-11eb-8969-49f1446f6336.jpg)
![FB_IMG_1605324741275](https://user-images.githubusercontent.com/71615879/99138669-d52ccc00-2664-11eb-892f-d9dd9d7294ef.jpg)

**Comment by vit9696** [comment]
No support requests here.

**Comment by josineiaraujo** [comment]
> OC 0.6.3 of me funciona muito bem no 10.15.7 e Big Sur beta 6
> Após a atualização Big Sur 20B29 travou Kext stall: X86PlatformPlugin 3-5 minutos após a inicialização bem-sucedida,
> eu crio ssdt e CPU Friends, mas não trabalho

I have the same problem, how did you manage to solve it?

**Comment by thainhan07103** [comment]
You remove all opencore and recreate it

Vào 21:34, Th 2, 21 thg 12, 2020 josineiaraujo <notifications@github.com>
đã viết:
