### ISSUE TITLE
OSC text on screen before give boot disks

### ISSUE THREAD

**Issue by crushers** [acidanthera/bugtracker#1290]
I try to found fix but don't have a luck.
Who can say me where is the error in config.plist
**OCS: Failed to parse string field as value with type data and <5D943F1C2559> contenst, context <ROM>!**

**Comment by nms42** [comment]
Your config is incorrect.

**Comment by crushers** [comment]
Maybe, but I can booted every system. Just have a this msg and I don't know where is the problem in config.plist.

**Comment by nms42** [comment]
Utilities/.../ocvalidate is your best friend

**Comment by crushers** [comment]
![Screenshot 2020-11-14 at 16 04 03](https://user-images.githubusercontent.com/7488776/99150187-0fad5d80-2693-11eb-934f-8d49165d3992.png)
Just different numbers

**Comment by Andrey1970AppleLife** [comment]
ROM type **data**
https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Sample.plist#L965-L966

**Comment by crushers** [comment]
Thank you. ROM was in string no on Data.
