### ISSUE TITLE
[Big Sur] FileVault UI not fully loading

### ISSUE THREAD

**Issue by bpresles** [acidanthera/bugtracker#1292]
After having upgraded successfully to Big Sur and booted the first time without entering password thanks to the AuthRestart option, I’ve been unable to enter the filevault password because the FileVault UI doesn’t fully load (see picture attached).

I’ve tried with either AppleUITheme quirk enabled or not, without success. 
I’ll provide the config.list used in the coming hour (my computer is not accessible right now).

![531FCDE2-A9ED-4C6F-8C27-3071AB7A587D](https://user-images.githubusercontent.com/220623/99149962-9d884900-2691-11eb-9bf5-bd9320744db4.jpeg)

My setup is based on a Gigabyte GA-Z87N-WIFI motherboard with AMD Vega56 graphic card and 16 GB of RAM.

**Comment by bpresles** [comment]
Here the config.plist used.
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/5541357/config.plist.zip)

**Comment by vit9696** [comment]
Hrm. Does anybody else have it? CC @khronokernel

**Comment by bpresles** [comment]
Here some opencore log of a fail filevault start (I think).

[opencore-2020-11-13-153303.txt](https://github.com/acidanthera/bugtracker/files/5542399/opencore-2020-11-13-153303.txt)

 I provide a full archive of logs of the day I experienced it in case this one is not enough. Some of them are boot to Recovery:
[OpenCoreLogs.zip](https://github.com/acidanthera/bugtracker/files/5542400/OpenCoreLogs.zip)

**Comment by vit9696** [comment]
It is full of `RETURN_ACCESS_DENIED`. Something is weird. I do not know whether anybody tried FV2 on Big Sur yet, and I do not plan upgrading in the nearest future myself. Does updating preboot volume help through the recovery? Something like `diskutil apfs updatePreboot /path/to/mounted/root/volume`?

**Comment by khronokernel** [comment]
For reference, I've tested 2 machines with FileVault in Big Sur:

* HP Elite X2 G1(Skylake M7 6Y75, HD 515)
* Dell Optiplex 7020 SFF(Haswell i5 4570, HD 4600)

Both models worked correctly as well, no issues on my end.

**Comment by vit9696** [comment]
I would assume it is something special, so let the discussion continue in a closed issue.

**Comment by bpresles** [comment]
Applying updatePreboot did fix the issue, I can now type the password. Strangly the background image doesn't load while it does on a clean install with FileVault enabled.

**Comment by bpresles** [comment]
I discovered that the lack of background image on FileVault Login UI was due to bad assets on the Recovery partition. I managed to have a complete login UI by doing the updatePreboot from my external HD clean installed Big Sur.

Is there a way to fully restore the Recovery partition safely on Big Sur ?
