### ISSUE TITLE
[AirportBcrmFixup] No 5Ghz on DW1820A

### ISSUE THREAD

**Issue by maxhartung** [acidanthera/bugtracker#1293]
Hi,

I recently bought a DW1820A, I don't have any problems with freezing or anything but the card doesn't recognize 5 GHz band at all, 

I tried:

- Set country code to "#a" 
- Tried only with Device Properties without AirportBcrmFixup
- Tried without both  Device Properties and AirportBcrmFixup -> kernel panic - > 32KHz LPO Clock not running
- Reset NVRAM

The chipset seems to be BCM94356 not 350. I have uploaded the logs using the debug version of OpenCore, Lilu and AirportBcrmFixup

SecureBoot is configured, ApCCID set to a random number.

[EliteBook840G2_DEBUG_WIFI.zip](https://github.com/acidanthera/bugtracker/files/5541476/EliteBook840G2_DEBUG_WIFI.zip)

Specs:

HP EliteBook 840 G2
Intel Core i5 5500U
16 GB RAM
Transcend SSD
Samsung SSD
DW1820A (BCM94356)
macOS 10.15.7

Note: all kexts are the latest versions, OpenCore is at 0.6.3 public version

BIOS:

- Fastboot disabled
- SecureBoot disabled
- UEFI native boot without CSM
- USB Legacy disabled
- Latest UEFI version

**Comment by Andrey1970AppleLife** [comment]
40 MHz on 2.4 GHz isn't supported in macOS.

**Comment by maxhartung** [comment]
> 40 MHz on 2.4 GHz isn't supported in macOS.

Then we shall see why 5 GHz isn't detected. I tried looking at the logs but nothing useful found for my perspective.

**Comment by lvs1974** [comment]
DW1820a is the cheapest solution for hackintosh (and most problematic). It does not support quite many channels in 5 Ghz band, some of them can work with issues. For example, channel 36 does not work for me.
You have to play with channel number in your router and find the most stable one. And check whether a new channel can work with your other devices (in my case Amazon Fire TV 4k stopped working on some channels}.

**Comment by maxhartung** [comment]
> DW1820a is the cheapest solution for hackintosh (and most problematic). It does not support quite many channels in 5 Ghz band, some of them can work with issues. For example, channel 36 in my router does not work with dw1820a. 
> 
> You have to play with channel number in your router and find the most stable one. And check whether a new channel can work with your other devices (in my case Amazon Fire TV 4k stopped working on some channels}.
> 
> 
> 
> I don't think a root cause can be found in logs. 
> 
> Usually it looks like 5 Ghz network is not available at all. 

Thanks for the explanation. I will try switching the channels but I will sell it in the end. I will get the DW1560 when I will found it locally. 

If you have a solution, let me know and I will test it if I don't sell the Wi-Fi card in the meantime.
