### ISSUE TITLE
ACPI changes not getting applied on Windows

### ISSUE THREAD

**Issue by whatnameisit** [acidanthera/bugtracker#1294]
ACPI changes are applied on macOS, but not on Windows.
Below are the logs produced with the latest debug of OpenCore 0.6.4 found at Dortania builds.
macOS log: 
[opencore-2020-11-15-082051.txt](https://github.com/acidanthera/bugtracker/files/5542009/opencore-2020-11-15-082051.txt)
Windows log: 
[opencore-2020-11-15-082208.txt](https://github.com/acidanthera/bugtracker/files/5542010/opencore-2020-11-15-082208.txt)
My EFI: 
[Desktop.zip](https://github.com/acidanthera/bugtracker/files/5542011/Desktop.zip)
On macOS I looked at MaciASL tables, and on Windows 10 the ACPI menu output on RW Everything.
If this is relevent, I have three other hacks. Two of them have this same issue. The other one has correct ACPI changes across OS's. If more logs are needed, please let me know.
Thanks.

**Comment by vit9696** [comment]
Could it be that your tool extract tables from the BIOS and shows the tables not actually used by the operating system? I have seen that many times with Windows utilities. Is there a practical guess that the patching is unsuccessful?

**Comment by nms42** [comment]
I learned years ago that windows cache acpi tables in registry. I have no idea how windows update that cache. Most of utilities on windows extract tables from that cache.

**Comment by whatnameisit** [comment]
On one hackintosh, RW Everything shows updated ACPI tables with changes applied from OpenCore. On three hacks, RW Everything shows the tables are not changed.
I just assumed this tool reads actual tables Windows has booted with.
And the guess was wrong. Changes show up if I use a different tool to read tables. I guess the cache has not yet been updated on the three hacks.
Closing...Thanks!

**Comment by whatnameisit** [comment]
Sorry I thought it was OK back then, but I applied https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/Source/SSDT-EHCx-DISABLE.dsl and the device is recognized in Windows Device Manager. It does not show up in IOReg.
[ioreg.zip](https://github.com/acidanthera/bugtracker/files/7273452/ioreg.zip)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/7273453/EFI.zip)
[opencore-2021-10-03-133723.txt](https://github.com/acidanthera/bugtracker/files/7273451/opencore-2021-10-03-133723.txt)
![Device Manager](https://user-images.githubusercontent.com/47713349/135757062-d38c484e-9331-4a97-a170-954cf206d52c.PNG)
I'm guessing I could delete all ACPI tables and boot Windows fine on this machine...

**Comment by Andrey1970AppleLife** [comment]
> Sorry I thought it was OK back then, but I applied https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/Source/SSDT-EHCx-DISABLE.dsl and the device is recognized in Windows Device Manager. It does not show up in IOReg.

So shall be, because action of this SSDT is restricted only for Darwin.

**Comment by whatnameisit** [comment]
Right, I forgot to mention that I deleted the Darwin condition to make it apply to all OS.

**Comment by whatnameisit** [comment]
Do you need more examples? I have two laptops that ACPI changes do not apply in non-darwin OS.

**Comment by vit9696** [comment]
From what I know, Windows sometimes caches ACPI tables. Try a fresh install.

**Comment by whatnameisit** [comment]
I could do that.
While I go do that, could you please examine what else might be wrong with below? All tested in Windows. 
I have five machines total.
Two machines immediately get ACPI changes. I tried rewriting ACPI battery methods and one mistake leads to failed battery in Windows.
Three machines do not seem to immediately get ACPI changes. If I add or delete SSDTs it does not seem to matter. But if I add an empty DSDT table they fail to boot.
