### ISSUE TITLE
VirtualSMC and SMCDellSensors 1.1.8 KP without keepsyms=1 boot flag

### ISSUE THREAD

**Issue by planvin** [acidanthera/bugtracker#1295]
Big Sur 11.0.1 public release
I get KP during boot with latest SMCDellSensors (1.1.8) if I don't include keepsyms=1 as a boot flag.
1.1.7 is working fine without the boot flag.
System is a Dell 9570 with 4K screen incl. EDID patch.
See attached KP log.
[panic-2020-11-14-105824.txt](https://github.com/acidanthera/bugtracker/files/5542188/panic-2020-11-14-105824.txt)

**Comment by vit9696** [comment]
Make sure to have DisableLinkeditJettison enabled.

**Comment by zearp** [comment]
I'm getting a panic with builds after 1a2d842, no issues when booting but after a few minutes sitting idle macOS panics and reboots. Build 1a2d842 works fine as do any builds before it. DisableLinkeditJettison  is enabled. I've attached the panic log, please let me know if more logs are required.

[panic_log.txt](https://github.com/acidanthera/bugtracker/files/5574417/panic_log.txt)

**Comment by walle0207** [comment]
would u
pls send to me about   “SMCDellSensors.kext” ，email：1280086792@qq.om  thx

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/VirtualSMC/suites/2304676584/artifacts/48351886
