### ISSUE TITLE
OpenCore causes BIOS corruption on ASUS TUF Z390 PRO Gaming 

### ISSUE THREAD

**Issue by peppeuz** [acidanthera/bugtracker#1296]
Trying to boot from OpenCore (from USB) causes BIOS corruption: everytime I try to boot, I can't access my BIOS anymore pressin Canc on startup. It just go to a blank screen and dies there.

I tought the issue was caused by BootStrap, so I set BootProtect to None, but this didn't help.

The only way to get the BIOS back is flashing it again from Windows.

MOBO: ASUS TUF Z390 PRO Gaming
CPU: Intel i5-9600K.

Other PC parts > https://pcpartpicker.com/user/peppeuz/saved/FM3rVn
config.plist > https://pastebin.com/bnp7gZZC
EFI folder > https://ibb.co/cDRVyzH

**Comment by vit9696** [comment]
Thats's a bug in your BIOS, not OpenCore. See https://github.com/acidanthera/bugtracker/issues/1222. We do not have any workarounds for you at the moment. Write to ASUS support.

**Comment by corint1** [comment]
> The only way to get the BIOS back is flashing it again from Windows.

how boot windows  or start any other os , if youe BIOS is broken and mobo dont start ? I'm very currios ...

**Comment by peppeuz** [comment]
> > The only way to get the BIOS back is flashing it again from Windows.
> 
> how boot windows or start any other os , if youe BIOS is broken and mobo dont start ? I'm very currios ...

As I said, I was trying to boot OpenCore from USB.
I can't access UEFI BIOS, but mobo starts and load default bootloader, which is my EFI partition with Clover.

**Comment by corint1** [comment]
no make sens ... or your explication is wrong ... or is corrupt or not ... leave this ...
