### ISSUE TITLE
Big Sur & WEG - 5700XT Black Screen & Partial output

### ISSUE THREAD

**Issue by theomacx86** [acidanthera/bugtracker#1297]
I'm a 5700XT user, and some issues are being reported with NAVI GPUs, the issue is:
On both Catalina and Big Sur, multi monitor, or even sometimes single monitor, requires to restart the monitors multiple times, sometimes even after that no output appears on the screen.
Mixing outputs (DP and HDMI) doesn't help, sometimes Big Sur doesn't want to show any display output at all.
On Catalina the issue seems less present, WEG and "agdpmod=pikera" often help and rebooting the monitors once allows to get a video output. On Big Sur, most of the time no output is shown, the system however is running and accessible via SSH.
On the IOreg all framebuffers are shown with what seems to be all the correct connectors. Tho even if a display is detected and shown in the IOreg, no output will be shown, which lead to think about an initialization issue or some sort.

I tested with WEG + "agdpmod=pikera" and no WEG at all, the issue still persists. I'm using a NITRO+ which have a different port layout (DP DP HDMI HDMI) than the stock PCB (DP DP HDMI DP). Along with an I7 6700 on a MSI Z170-A PC MATE, with 32Gb of 3000Mhz RAM.

I joined both my OC files (serial removed) and Lilu & WEG debut output. If needed I can provide additional informations.

[Lilu WEG Logs.zip](https://github.com/acidanthera/bugtracker/files/5542622/Lilu.WEG.Logs.zip)
[OC Boot files.zip](https://github.com/acidanthera/bugtracker/files/5542623/OC.Boot.files.zip)

**Comment by mihaistefan88** [comment]
I have the same problem. The GPU is a gigabyte 5700xt oc, on a z270 gigabyte motherboard with a i7 7700k. The system boots, but there is no video output. I can only access it with vnc. The port layout is DP DP DP HDMI. I have tried agdpmod=pikera or ignore, and tried disabling weg, nothing works. I also tried changing the SMBIOS information using iMac, iMacPro or MacPro, after which video output was OK until the first restart.

**Comment by vit9696** [comment]
Not reproducible on our hardware, so we cannot help really aside from suggesting to try different agdpmod configuration. Make sure the ACPI devices for the GPUs exist. This is a new requirement in Big Sur.

**Comment by wmchris** [comment]
i can confirm, same problem. on catalina this issue was not as persistent and could've been mitigated, when no DP cable was plugged in on boot. 

BigSur broke completly. I tried by removing the DP/HDMI cables, after 30 minutes continuuous re-plugging the display went on. 

This issue is well known and reported a lot on the internet. So far no real fix is known. @vit9696 maybe we can hope on a little help from someone with more insight in whats going on?

**Comment by vit9696** [comment]
We saw some funny stuff with LG screens waking and AMD GPUs but these issues were specific to the screens, not AMD drivers. Perhaps it is your screen that is having issues?

**Comment by wmchris** [comment]
i have this issue with three different screens (Samsung, Acer and HP), so i doubt that.

**Comment by vit9696** [comment]
Quite sad. Well, at the very least you can disable Serial Port manually via a modded grub shell. For that check `AppleCpuPmCfgLock` description in OpenCore reference manual, and apply it to a setting related to Serial Port enablement. You can ensure that the serial port is disabled via I/O Registry (you will not find the driver attached to it).

**Comment by wmchris** [comment]
i'll try to look for anything on the net. i dont have any experience with such kind of configurations and i dont know if this really fixes the problem. so i dunno if i succeed.

**Comment by theomacx86** [comment]
Can confirm, disabling serial & parallel ports helps mitigating the issue, Big Sur now display an image more often, on DisplayPort it still needs to restart the monitor, a fix was : switching to all HDMI, it's not the most convenient fix for high definition/high refresh rates monitor, but it allows to get an output on all monitors at first try.

**Comment by wmchris** [comment]
so it seems like there are two distinct bugs:
* Bug 1: a serial console seems to break display output on a smaller range of navi cards, mostly build by sapphire and one other vendor i forgot
* Bug 2: general framebuffer problems when using DP connection on a wide range of navi cards - which results in many "i gave up" threads on the internet.

As this seems like a general problem which needs a lot of skill and knowledge to debug, i'm willing to offer a commission for a fix.

**Comment by wmchris** [comment]
> Quite sad. Well, at the very least you can disable Serial Port manually via a modded grub shell. For that check `AppleCpuPmCfgLock` description in OpenCore reference manual, and apply it to a setting related to Serial Port enablement. You can ensure that the serial port is disabled via I/O Registry (you will not find the driver attached to it).

@vit9696 i tried to find a way, but i'm totally puzzled where to start. the reference manual only explains a quirk which changes a kext. Can you tell me what kind of mod for grub i have to look for? and use the shell for what exactly? Which setting shall i set?

**Comment by vit9696** [comment]
Starting from

```
  As modern firmware provide a \texttt{CFG Lock} setting that allows configuring the
  \texttt{PKG\_CST\_CONFIG\_CONTROL} MSR register lock, this option should be avoided
  whenever possible. On APTIO firmware that do not provide a \texttt{CFG Lock}
  setting in the GUI, it is possible to access the option directly:

**Comment by wmchris** [comment]
@vit9696 i did it, but the value seems a lil bit off. maybe i read the tutorial wrong? Can i request a little bit help here? 
i doubt that the offset is really 0x0 - especially as there are more than one entry with this offset in the output file - it is used for the system language and network config.

```
0x28AE5 	Form: NCT6791D Super IO Configuration, FormId: 0x274C {01 86 4C 27 6A 00}
0x28AEB 		Suppress If {0A 82}
0x28AED 			QuestionId: 0x255 equals value 0x0 {12 06 55 02 00 00}
0x28AF3 			Gray Out If {19 82}
0x28AF5 				QuestionId: 0x1DC equals value 0x1 {12 06 DC 01 01 00}
0x28AFB 				Checkbox: Serial Port, VarStoreInfo (VarOffset/VarName): 0x0, VarStore: 0x17, QuestionId: 0x65 {06 8E 4C 04 58 04 65 00 17 00 00 00 10 00}
0x28B09 					Default: DefaultId: 0x0, Value (8 bit): 0x1 {5B 06 00 00 00 01}
0x28B0F 					Default: DefaultId: 0x1, Value (8 bit): 0x1 {5B 06 01 00 00 01}
0x28B15 				End {29 02}
0x28B17 			End If {29 02}
0x28B19 		End If {29 02}
0x28B1B 		Suppress If {0A 82}
0x28B1D 			QuestionId: 0x65 equals value 0x0 {12 06 65 00 00 00}
0x28B23 			Gray Out If {19 82}
0x28B25 				QuestionId: 0x1DC equals value 0x1 {12 06 DC 01 01 00}
0x28B2B 				One Of: Serial Port Address, VarStoreInfo (VarOffset/VarName): 0x1, VarStore: 0x17, QuestionId: 0x66, Size: 1, Min: 0x2, Max 0x4, Step: 0x0 {05 91 6E 00 6F 00 66 00 17 00 01 00 10 10 02 04 00}
0x28B3C 					One Of Option: 3F8h/IRQ4, Value (8 bit): 0x2 (default) {09 07 70 00 30 00 02}
0x28B43 					One Of Option: 3E8h/IRQ4, Value (8 bit): 0x4 {09 07 72 00 00 00 04}
0x28B4A 				End One Of {29 02}
0x28B4C 			End If {29 02}
0x28B4E 		End If {29 02}
0x28B50 	End Form {29 02}
```

**Comment by wmchris** [comment]
i'll answer my question by myself. @datasone released a modified version, which can write in different data storages.
https://github.com/datasone/grub-mod-setup_var/issues/5#issuecomment-612967491

changing my variable should be done by `setup_var 0x0 0x0 PNP0501_0_NV`
i'll report back when i tested it.
