### ISSUE TITLE
CrScreenshotDxe doesn't work on MacPro3,1

### ISSUE THREAD

**Issue by joevt** [acidanthera/bugtracker#1299]
CrScreenshotDxe.efi can work on MacPro3,1 (when GOP is available) if the APPLE_EVENT_PROTOCOL_REVISION is set to 6 instead of 7 in OpenCorePkg/Include/Apple/Protocol/AppleEvent.h

I do not know if there is a significant difference in the Apple Event Protocol between version 6 and 7.
I do not know where the information for the Apple Event Protocol came from (reverse engineered?)

I guess AppleEvent in ProtocolOverrides Properties in OpenCore could work around this issue, however, it would be useful for CrScreenshotDxe to work without OpenCore.

Also, allowing version 6 means increasing compatibility.

**Comment by vit9696** [comment]
If you lower it to 6, does it work? We indeed reverse-engineered this protocol and do not quite know about the difference. In general you should always replace the outdated AppleEvent, since at least FV2 will crash otherwise.

**Comment by joevt** [comment]
When it is lowered to 6, I can take screenshots of the EFI 1.1 Shell. It creates .png files when I press the F10 key (uses minimum bits per pixels and compression?). RefindPlus creates BMP files that are a 500 times larger in size (uncompressed using 48 bit color).

I am currently not using File Vault 2.

**Comment by vit9696** [comment]
Could submit a patch then. Make an extra define for the legacy version (6) in a protocol header and change the check in the driver.

**Comment by dakanji** [comment]
Can the same define be used for the only other check which is under `GuiPointerConstruct` in `Platform/OpenCanopy/Input/InputSimAbsPtr.c`?

I don't use OpenCanopy so can't actually check myself.
