### ISSUE TITLE
Stuck before login (tx_flush...., IOkit Daemon (kernelmangered) stall(0), (60s): 'X86Platformplugin'

### ISSUE THREAD

**Issue by nikhil19rathore99** [acidanthera/bugtracker#1301]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

- Only the latest released versions of OpenCore, Lilu, and other KEXTs are supported.
- Bugreports involving Chameleon, Clover, Ozmozis or alike are not accepted.
- Include your your `EFI` directory with OpenCore.
- Include OpenCore DEBUG log (refer to `Target` in Configuration.pdf).
- Include Lilu DEBUG log (refer to `-liludbgall liludump=60` boot arguments in README).

Issue tracker is _not_ a support forum, and if you have installation or usage problems, try asking your questions on [InsanelyMac.com](https://www.insanelymac.com/forum/73-developers-corner/) or [AppleLife.ru](https://applelife.ru/forums/xakintosh.67/). There could also be local communities providing Acidanthera Project support in your native language.

For example, if you have an issue with AppleALC and you have not working sound, and you **cannot** offer new resources that fix the problem for you, you should go to the **support forums**. Here there are no people who create custom audio resources, or who deal with installation issues.

When to use issue tracker:
* You have new resources or patches to add but cannot make a pull request
* You have kernel panics, crashes, hangs and believe it is not a configuration issue
* You want to discuss technical or legal stuff

_If you have a kernel panic, please ensure that you have a DEBUG version of the extension and you have `-v keepsyms=1 debug=0x100` boot arguments added. On 10.13 or higher to avoid kext names scrolling over the panic log you should also set `PanicNoKextDump=YES` in OpenCore. Use `ApplePanic=YES` for write a kernel panic log to file._
![WhatsApp_Image_2020-11-16_at_15 52 14](https://user-images.githubusercontent.com/32436513/99268520-475f0580-284b-11eb-9c5b-0ac16fd9738c.jpg)
OpenCore: 0.6.3
Asus X556UQK Laptop
i5-7200U
Ram: 8GB
OS : BigSurr 11.0.1 (final release)
All kexts are updated to last version

**Comment by 1alessandro1** [comment]
Please close this and post your issue in the correct form

**Comment by nikhil19rathore99** [comment]
> Please close this and post your issue in the correct form

Thanks but solved with clover and find the cause of the problem I.e voodoo input.kext from voodooI2C 
It's solved by removing voodoinput.kext from voodooi2c and keep voodoo input.kext in voodoops2
Thanks now you can close the issue.

**Comment by marianopela** [comment]
> It's solved by removing voodoinput.kext from voodooi2c and keep voodoo input.kext in voodoops2

Actually, the right way is to inject the VoodooInput coming from VoodooI2C, not the other way around

**Comment by nikhil19rathore99** [comment]
> > It's solved by removing voodoinput.kext from voodooi2c and keep voodoo input.kext in voodoops2
> 
> Actually, the right way is to inject the VoodooInput coming from VoodooI2C, not the other way around

I've done it but didn't work that way so above listed works oob..
