### ISSUE TITLE
EXC_Resource - exceeded mem limit

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1302]
With the latest updates from Catalina, and even on BigSur 11.0.1 20B29 with the latest OpenCore 0.6.4 [commit](https://github.com/acidanthera/OpenCorePkg/commit/53ec8e923cc5bed6d575278c8ea81a09b5125db0) seems like booting both systems causes a delay of 10+ seconds on this line:

![2020-11-16 17 20 10](https://user-images.githubusercontent.com/46293832/99279516-99def880-2830-11eb-9ff8-57e57749de03.jpg)

This issue is persistent across reboots, I can provide logs if required.

**Comment by nikhil19rathore99** [comment]
> With the latest updates from Catalina, and even on BigSur 11.0.1 20B29 with the latest OpenCore 0.6.4 [commit](https://github.com/acidanthera/OpenCorePkg/commit/53ec8e923cc5bed6d575278c8ea81a09b5125db0) seems like booting both systems causes a delay of 10+ seconds on this line:
> 
> ![2020-11-16 17 20 10](https://user-images.githubusercontent.com/46293832/99279516-99def880-2830-11eb-9ff8-57e57749de03.jpg)
> 
> This issue is persistent across reboots, I can provide logs if required.

remove the voodooinput from voodooi2c and keep voodooinput in voodoops2

**Comment by 1alessandro1** [comment]
This has nothing to do with my issue. And also, I don't have an I2C trackpad.

**Comment by vit9696** [comment]
Well, this is not an OC problem, but rather something with macOS itself.

**Comment by 1alessandro1** [comment]
@vit9696 executing this command from macOS recovery removes the hang, any idea why?

`csrutil enable --without kext`

**Comment by vit9696** [comment]
Well, if you believe it is a regression, tell me the commit it happened in. Do you have enough RAM? Anything below 8 GB may be problematic.

**Comment by Brax84** [comment]
![2D7CF34D-2921-45BE-A42D-1BBDF07D85B0](https://user-images.githubusercontent.com/22413640/100603151-fe0bbd00-3304-11eb-92d4-90f8513a3cc2.jpeg)

Same problem using OC 0.6.3 after enabling igpu in bios for hw acceleration. 
Haswell cpu ....nvidia card ...16GB ram ...gigabyte z97

**Comment by 1alessandro1** [comment]
Interestingly, macOS Catalina 19H2 doesn't have this hang. (With fixed OC version, stable, 0.6.3 - the testing conditions are the same as before)

I've even tried the latest BigSur (release, 20B50 on a clean install with an external SSD) + OpenCore and Kexts 0.6.4 (latest builds from [dortania](https://dortania.github.io/builds)) but the hang of about 10 seconds persists.

**Comment by 1alessandro1** [comment]
What could `MRT[74]` mean?

**Comment by smcinerney** [comment]
> What could `MRT[74]` mean?

'MRT' is just MacOS's Malware Removal Tool, and 74 is the PID of that running MRT process.
Whenever you install or update software, [MacOS (XProtect I think) is simply supposed to briefly run and confirm it's not malware](https://eclecticlight.co/2018/01/20/just-what-do-xprotect-and-mrt-protect-your-mac-from/). But in some scenarios, MRTgets launched, hangs the CPU and overheats and only gives this warning; this has been happening at least as far back as 10.14.x. I get this too with different root-cause, on different software, and different version of MacOS.
