### ISSUE TITLE
WhateverGreen support to force-enable DSC compression

### ISSUE THREAD

**Issue by v10x** [acidanthera/bugtracker#1303]
With MacOS Big Sur, there have been multiple reports of DSC not being enabled, for example using the AMD W5700 Pro with USB-C and a Pro Display XDR causes the display to run at 4K instead of the native 6K resolution. 

Would it be possible for WhateverGreen to force enable DSC compression for us?

More information here https://forums.macrumors.com/threads/amd-radeon-pro-w5700s-usb-c-port-and-pro-display-xdr.2222125/page-5

**Comment by vit9696** [comment]
Thanks for the signal. We have no plans working on this, but a good idea will be to report it to Apple.

**Comment by steffen-klein** [comment]
Is there any news on this topic? It would be really great to have an option to enable DSC, as it seems that Apple will not do it for Intel-based machines. For the new M1 MacBooks DSC seems to be fixed.
