### ISSUE TITLE
Synaptic SMBus TouchPad movement not responsive

### ISSUE THREAD

**Issue by projectoneuniverse** [acidanthera/bugtracker#1304]
![Untitled-1](https://user-images.githubusercontent.com/50221511/99325193-617b0100-28a8-11eb-944e-1a19f39dda63.png)

Thank you for the hard work of the team for presenting this kext.
I'm using VoodooPS2 version 2.0.8 kext. Using this multi gesture works well using Opencore 0.6.3, but the trackpad movement is not responsive, sometimes the cursor doesn't move and doesn't smooth. Is this really commonplace at Synaptic?

I attached a picture of the synaptic device used

**Comment by vit9696** [comment]
Quite possible. See the other issues in https://github.com/acidanthera/bugtracker/labels/project%3Aps2 I believe https://github.com/VoodooSMBus might be more performant for you. CC @usr-sse2

**Comment by projectoneuniverse** [comment]
Yes!! it works use VoodooRMI
 Thanks a bunch for make my day
