### ISSUE TITLE
Some settings in CMOS get reset after restart - EliteBook 840 G2

### ISSUE THREAD

**Issue by maxhartung** [acidanthera/bugtracker#1305]
Hi,

I have OpenCore 0.6.3 Debug version running below Big Sur 11.0.1. After I restart, my time get reseted every time. I have DisableRTCChecksum quirk enabled but seems to not work or maybe I need other offsets.

For the moment, I can only observe that my time got reset but maybe there are other CMOS settings that are reset.

[Archive.zip](https://github.com/acidanthera/bugtracker/files/5554683/Archive.zip)

I have uploaded a full log including a SysReport.

RTCMemoryFixUp:

```
[    0.775004]: RTCMemoryFixup     RTCFX: @ (DBG) RTCMemoryFixup::init()
[    0.777501]: RTCMemoryFixup     RTCFX: @ failed to load rtc-blacklist config from UEFI nvram
[    0.777510]: RTCMemoryFixup     RTCFX: @ (DBG) RTCMemoryFixup::hookProvider for ioRead8 was successful
[    0.777517]: RTCMemoryFixup     RTCFX: @ (DBG) RTCMemoryFixup::hookProvider for ioWrite8 was successful
[    0.777528]: RTCMemoryFixup     RTCFX: @ (DBG) RTCMemoryFixup::probe()
[    0.777534]: RTCMemoryFixup     RTCFX: @ (DBG) RTCMemoryFixup::probe(): service provider is RTC
[    0.777557]: RTCMemoryFixup     RTCFX: @ (DBG) RTCMemoryFixup::start()
```

Later findings:

I tried excluding the entire region with rtcfx_exclude=00-FF but my time is still reset. The battery holds the charge well.

**Comment by vit9696** [comment]
Could be EfiBoot doing this. I would suggest using rtc-blacklist instead. Not a support forum, closing.
