### ISSUE TITLE
voodoops2contoller 2.1.8 trackpad not working

### ISSUE THREAD

**Issue by kyeng-vis** [acidanthera/bugtracker#1306]
After updating VoodooPS2Controller from 2.1.5 to 2.1.8, trackpad stop working

<img width="1440" alt="Screenshot 2020-11-18 at 2 32 32 PM" src="https://user-images.githubusercontent.com/22570843/99494492-1518e980-29ac-11eb-83aa-7c56f2e8451e.png">
<img width="1440" alt="Screenshot 2020-11-18 at 2 28 38 PM" src="https://user-images.githubusercontent.com/22570843/99494513-1a763400-29ac-11eb-854e-a6ef44d3f7b9.png">

[kernel_v2.1.5.txt](https://github.com/acidanthera/bugtracker/files/5558225/kernel_v2.1.5.txt)
[kernel_v2.1.8.txt](https://github.com/acidanthera/bugtracker/files/5558226/kernel_v2.1.8.txt)

**Comment by vit9696** [comment]
This looks like some kext installation issue. Assuming support request.
