### ISSUE TITLE
Elan touchpad does not work after sleep.

### ISSUE THREAD

**Issue by IFierta** [acidanthera/bugtracker#1307]
The touchpad does not work after sleeping. Doesn't react to any actions. Tried all versions with Elan support, no one works after waking up from sleep. On Catalina, I did not encounter this problem, since only hibernation was configured, I did not use sleep. After upgrading to Big Sur, I began to use sleep. Kext from github.com/BAndysc version 2.1.5 works after sleep.

Elan v4, fw: 381f00, bus: 0
macOS Big Sur
[kernel_log.txt](https://github.com/acidanthera/bugtracker/files/5559033/kernel_log.txt)

What logs are required from me?

**Comment by vit9696** [comment]
I am afraid only @BAndysc or @hieplpvip know about it. Let's handle as a part of https://github.com/acidanthera/bugtracker/issues/1192.
