### ISSUE TITLE
BrightnessKeys not working

### ISSUE THREAD

**Issue by m0d16l14n1** [acidanthera/bugtracker#1309]
Hello! My laptop is Ice Lake based one and i have a problem. 

Previously i was using SSDT to setup brightness keys and rename patch (SSDT is included in EFI folder and patches too *SSDT and patches are disabled while using BrightnessKeys.kext*)

I don't know if that kext supposed to work OOTB, but it's not working in my case and i don't know why. I was trying to get dmesg logs, but they are empty, nothing appeared about BrightnessKeys. I will attach my EFI folder and my *clean without patches* DSDT in case it can help to fix that. If you need something special to attach - tell me please, i will add that too. Thanks!

[SSDT-BrightFN.zip](https://github.com/acidanthera/bugtracker/files/5567292/SSDT-BrightFN.zip)
[DSDT aml-dsl.zip](https://github.com/acidanthera/bugtracker/files/5567293/DSDT.aml-dsl.zip)
[Full EFI.zip](https://github.com/acidanthera/bugtracker/files/5567294/Full.EFI.zip)

**Comment by marianopela** [comment]
You're gonna need `-brkeysdbg` as a boot-arg

**Comment by m0d16l14n1** [comment]
> You're gonna need `-brkeysdbg` as a boot-arg

Thanks! Now I see the log. 

[bkeys.log](https://github.com/acidanthera/bugtracker/files/5567456/bkeys.log)

**Comment by zhen-zen** [comment]
In this case, your brightness keys is handled by `HIDD` (Intel HID event driver) instead of notifying graphics devices, 0x13/0x14 is documented here: https://github.com/torvalds/linux/blob/master/drivers/platform/x86/intel-hid.c#L46. You can also try `YogaSMC`, I ported that part but haven't tested it extensively.

**Comment by m0d16l14n1** [comment]
> In this case, your brightness keys is handled by `HIDD` (Intel HID event driver) instead of notifying graphics devices, 0x13/0x14 is documented here: https://github.com/torvalds/linux/blob/master/drivers/platform/x86/intel-hid.c#L46. You can also try `YogaSMC`, I ported that part but haven't tested it extensively.

Wow, so it's should be okay to check YogaSMC, i will check it, thanks!

**Comment by m0d16l14n1** [comment]
> In this case, your brightness keys is handled by `HIDD` (Intel HID event driver) instead of notifying graphics devices, 0x13/0x14 is documented here: https://github.com/torvalds/linux/blob/master/drivers/platform/x86/intel-hid.c#L46. You can also try `YogaSMC`, I ported that part but haven't tested it extensively.

Tried YogaSMC, have the same problem here: Fn+F5/F6 are not responsive, only Fn+F11 working for lowering brightness. Fn+Space is working (disabling touchpad) 
Here is the log: 

```
[    2.386962]: YSMC - Debug: YogaHIDD::(null) Initializing
[    2.386968]: YSMC - Debug: YogaHIDD::HIDD Probing
[    2.387025]: YSMC - Debug: YogaHIDD::HIDD PNP0C09 available at H_EC
[    2.387265]: YSMC - Debug: YogaHIDD::HIDD Starting
[    2.387288]: YSMC - Debug: YogaHIDD::HIDD powerState 1 : on
[    2.387896]: YSMC - Debug: YogaHIDD::HIDD Notification consumer published: YogaHIDD
[    2.387913]: YSMC - Info: YogaHIDD::HIDD Failed to acquire fn mask
[    3.461321]: YSMC - Debug: YogaHIDD::HIDD Notification consumer published: VoodooI2CPrecisionTouchpadHIDEventDriver
[    3.946455]: YSMC - Debug: YogaHIDD::HIDD Notification consumer published: ApplePS2Controller
[    4.036271]: YSMC - Debug: YogaHIDD::HIDD Notification consumer published: ApplePS2Keyboard
```

**Comment by zhen-zen** [comment]
BrightnessKeys should never work with incompatible layout. And in your DSDT there's no method notifying `DD1F` or other video output devices. The driver will only add property like `BrightnessPanel` - `DD1F` in ioreg if the key event went through. You got brightness- on scr lk because it's mapped to F14 (0x6b), which is the same code of BRIGHTNESS_DOWN, see https://github.com/acidanthera/VoodooPS2/blob/master/VoodooPS2Keyboard/ApplePS2ToADBMap.h#L119.

For YogaSMC, you got "Failed to acquire fn mask", which seems to be old generation methods. Please open an issue there and I will follow it.

**Comment by m0d16l14n1** [comment]
@zhen-zen So, i should open an issue on YogaSMC repository, even if i have not Lenovo-branded laptop? Right?

**Comment by zhen-zen** [comment]
> @zhen-zen So, i should open an issue on YogaSMC repository, even if i have not Lenovo-branded laptop? Right?

Sure, that word is not restricted to that brand.

**Comment by mddarsh** [comment]
the brightness of my keyboard is working but it stopping after around 3 seconds if I did not use it, can i change it to work all the time and stop it from (Fn+F9)?

**Comment by zhen-zen** [comment]
Backlit keyboards are controlled with vendor specific methods and not covered by BrightnessKeys. You will need to dig into that on yourself.
