### ISSUE TITLE
[build tools] writing OC specific tools (mtoc,iasl) into (semi)system folders considered harmful

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#1312]
Why not just create project bin folder and use edk2 *_PREFIX trick or proper env PATH setting?
/usr/local/bin for unmodified tools, I guess.

**Comment by vit9696** [comment]
Why is /usr/local/bin is considered system directory? It is intended for user tools.

**Comment by nms42** [comment]
(semi) was written for that. IMHO, that folder intended for unmodified (for particular project) tools. OC, on the other hand, employs fine tuned for OC only versions.

Ears of single shot build environment are visible.

**Comment by vit9696** [comment]
Not really. nasm is unmodified and you can install it with macports or brew as well. mtoc is what we maintain now, and our patches are also upstreamed to brew — https://github.com/Homebrew/homebrew-core/blob/master/Formula/mtoc.rb#L17

**Comment by nms42** [comment]
Installing only to /usr/local/bin does that? Still missing the point of separate folder for very special tools?

Well, it is not a big deal either, so I would craft my own build environment for test builds.

**Comment by vit9696** [comment]
Sorry? But what separate folder? All the tools are installed exactly to /usr/local/bin. I do not understand what you mean.

**Comment by nms42** [comment]
For example,
```
mkdir $(WORKSPACE)/bin
...install special_tools there
(PATH=$(WORKSPACE)/bin:$PATH; run_special_tools)
```

**Comment by vit9696** [comment]
No, I think I got the request. You wanted the build system not to write anything to semi-system folders. What I did not get is the following:

> Still missing the point of separate folder for very special tools?

Because we do not use separate folders for special tools. Did you mean that installing special tools NOT to separate folders is what your point is?

**Comment by nms42** [comment]
Yep, that is the point. In /usr/local/bin lives iasl, mtoc, ... That ones would be suddenly overwritten by OC tailored.

**Comment by vit9696** [comment]
"Suddenly overwritten"? Why? OC uses the ones provided by the system and suggests (interactively, with user input confirmation) to automatically install the ones it can find ONLY when nothing is found. In fact, this only happens on some operating systems, i.e. macOS. On other systems it simply suggests to use a package manager. I get a feeling you either miss the point or misuse the OC build system.

**Comment by nms42** [comment]
On my system OC build_* tool tried to replace (wrong checksum) mtoc.

**Comment by vit9696** [comment]
It did not. It warned you that the one you have is not tested and suggested you to either set a variable to ignore this or use a supported version. Please do not misinform us.

**Comment by nms42** [comment]
I do not like when any project litter and|or modify anything beyond its borders. In monoproject case it's not a problem.

**Comment by nms42** [comment]
My rant is lament only.
