### ISSUE TITLE
[NVMeFix.kext] Can not boot with unsupported ssd( Intel P4500).

### ISSUE THREAD

**Issue by CrazyHulk** [acidanthera/bugtracker#1313]
It can not boot aside with Intel P4500 SSD(which used for windows) on big sur.

OpenCore 0.6.3
NVMeFix.kext 1.0.4

It stuck at here.

![3451605875766_ pic_hd](https://user-images.githubusercontent.com/13976375/99801338-dd0ed380-2b70-11eb-8f9e-a110452c913b.jpg)

I must disable P4500 with ssdt if boot normaly.

**Comment by vit9696** [comment]
Means it is unsupported I guess.

**Comment by CrazyHulk** [comment]
Yes, u r right.
I just want to keep it when I boot big sur with another ssd.
