### ISSUE TITLE
Add BLCM value to VirtualSMC

### ISSUE THREAD

**Issue by EugeneSnikhovskiy** [acidanthera/bugtracker#1314]
BLCM value is used to limit battery charge level in [osx_battery_charge_limit software](https://github.com/DevNulPavel/osx_battery_charge_limit/issues/3) and in [AlDente](https://github.com/davidwernhart/AlDente#how-does-it-work) and, probably, in other apps

**Comment by vit9696** [comment]
Mentioned once. Have a look https://github.com/acidanthera/bugtracker/issues/1211.
