### ISSUE TITLE
igfx: @ failed to route IsTypeCOnlySystem on KBL-R

### ISSUE THREAD

**Issue by stevezhengshiqi** [acidanthera/bugtracker#1316]
Tested macOS versions: 10.14.6 & 10.15.6+
UHD620 (ig-platform-id: 00001659) KabyLake

Hi, thank you so much for all the efforts. After https://github.com/acidanthera/WhateverGreen/commit/677b48631a5c904c4b74bcc40ec6e12cb27e2179, I have these error messages in my system log:
```
2020-10-25 06:10:30.944449-0400  localhost kernel[0]: (Lilu) Lilu   patcher: @ failed to solve __ZN31AppleIntelFramebufferController17IsTypeCOnlySystemEv, err 2
2020-10-25 06:10:30.944453-0400  localhost kernel[0]: (Lilu) WhateverGreen      igfx: @ failed to route IsTypeCOnlySystem﻿
```

Also, I posted this issue on insanelymymac at [here](https://www.insanelymac.com/forum/topic/325987-whatevergreen-support-topic/?do=findComment&comment=2742079), and I also see other people have the same problem.

Thanks for PMHeart for pointing out that err 2 in Lilu means symbol not found. I searched for the symbol `AppleIntelFramebufferController::IsTypeCOnlySystem`, and I didn't find any match in `AppleIntelKBLGraphicsFramebuffer`. Only `AppleIntelCFLGraphicsFramebuffer` and `AppleIntelICLLPGraphicsFramebuffer` have the `IsTypeCOnlySystem` function.

Please have a check and thank you guys so much.

**Comment by vit9696** [comment]
It does not matter too much, i.e. this warning is harmless. Are you sure the symbol is not present in later versions of Kaby Lake framebuffer? Like Big Sur.

**Comment by stevezhengshiqi** [comment]
@vit9696 Just tested on 11.0.1, and I found the symbol in KBLFB, but 10.15.7 not.

**Comment by vit9696** [comment]
Fixed in master.
