### ISSUE TITLE
Arch key missing from AMD_Vanilla/17h_19h/patches.plist -> Kernel -> Patch -> Comment | algrey cpuid_set_cache_info .. 10.13/10.14

### ISSUE THREAD

**Issue by andistern** [acidanthera/bugtracker#1319]
( cosmetic )
Line 254
regards

**Comment by andistern** [comment]
accuracy / reliability of documentation ? - regards

**Comment by Andrey1970AppleLife** [comment]
We don't support AMD on macOS
Go to https://github.com/dortania/bugtracker/issues

**Comment by andistern** [comment]
sorry & thank you

**Comment by Andrey1970AppleLife** [comment]
> sorry & thank you, somebody might perhaps change the link on https://github.com/AMD-OSX/bugtracker accordingly ;-))

CC @naveenkrdy
