### ISSUE TITLE
external-audio flag broken with macOS 11

### ISSUE THREAD

**Issue by ninjuan11** [acidanthera/bugtracker#1320]
Hello,
it seems like the external-audio flag is broken with OSX 11.0.1, with latest opencore and lilu.
ioregistryexplorer identifies the device as HDEF again, having correctly assigned external-audio using:
```
<key>external-audio</key>
<data>AQ==</data>
```

Reference to #1000

**Comment by ninjuan11** [comment]
@vit9696 is it possible to disable the renaming to HDEF from applealc, so i can patch it myself? correct device is initialized as AZAL, i can manually rename it to HDEF. then the other soundcard would not be visible. This should work, am i right?

**Comment by vit9696** [comment]
Need logs. Also, you say that it does not work with macOS 11, but does it work with other versions of macOS on the exact same configuration?

**Comment by ninjuan11** [comment]
it worked with the exact same configuration before i upgraded to Big Sur. 
Only thing i changed before was: i updated the kexts.

**Comment by ninjuan11** [comment]
is possible that https://github.com/acidanthera/Lilu/blame/575bd85c759fcec66c02a0ab960b5d8dad095c69/Lilu/Sources/kern_devinfo.cpp#L215 gets triggered before https://github.com/acidanthera/Lilu/blame/575bd85c759fcec66c02a0ab960b5d8dad095c69/Lilu/Sources/kern_devinfo.cpp#L268 - so it will never get checked for external-audio ? maybe easy fixable?

**Comment by ninjuan11** [comment]
@vit9696 is possible that https://github.com/acidanthera/Lilu/blame/575bd85c759fcec66c02a0ab960b5d8dad095c69/Lilu/Sources/kern_devinfo.cpp#L215 gets triggered before https://github.com/acidanthera/Lilu/blame/575bd85c759fcec66c02a0ab960b5d8dad095c69/Lilu/Sources/kern_devinfo.cpp#L268 - so it will never get checked for external-audio ? maybe easy fixable?

**Comment by ninjuan11** [comment]
@vit9696 it has nothing to do with the L215, i tested it by removing line and recompile. It has something to do with L268. External-audio is ignored. My soundcard comes first, then my internal - so i removed `!audioBuiltinAnalog` from Line 263. Now it is working again - but this is not a solution for everybody. It seems like `getProperty("external-audio")` is not available at runtime with new OpenCore/Lilu/OS11

Would be very happy if there could be a fix available.

**Comment by Andrey1970AppleLife** [comment]
Add to boot arguments: liludump=60 -liludbgall, use DEBUG AppleALC and Lilu, attach the file at /var/log/Lilu_x.x.x.txt directory 60 seconds after booting.

**Comment by ninjuan11** [comment]
@Andrey1970AppleLife got the log, but as i fixed it on my system by modifying sourcecode, the logfile is of no help. 

strange thing is, it only finds one entry now
```Lilu       dev: @ (DBG) found audio device AZAL at GP13 by 1022
Lilu       dev: @ (DBG) marking audio device as HDEF at AZAL
```
should be two times for two cards?  my workaround is doing its job - i have sound - but there is something absolutely broken with this IF statement.

**Comment by vit9696** [comment]
Could you provide IOReg? Device properties will not inject into devices without paths in ACPI. See these lines in the docs and a little above. https://github.com/acidanthera/OpenCorePkg/blob/0.6.3/Docs/Configuration.tex#L1640-L1645 I think that is your issue. Your external audio card has no name in ACPI and is not detected. You need a dummy SSDT for it starting with Big Sur.

**Comment by ninjuan11** [comment]
image: https://user-images.githubusercontent.com/67441126/99919320-f2c0fc00-2d1c-11eb-8c07-7ab787fca253.png
and
https://user-images.githubusercontent.com/67441126/99919269-aa094300-2d1c-11eb-9893-567b82cd1fa8.png

Path is _SB.PCI0.BXBR.BYUP.BYD4.BYS4 for the PCIe lane, then the sound-blaster is there as a bare pcixxxx,xxxx device. I tried to create an injector, but as it gets renamed i dont know how to do this with a bare pcixxxx,xxxx device.

**Comment by vit9696** [comment]
That means you do not have a device in the ACPI, yeah. Follow the example in OpenCore docs to create a dummy device.

**Comment by ninjuan11** [comment]
@vit9696 any chance for some help with this when it has a name like pcixxxx,xxxx?

**Comment by vit9696** [comment]
Well, you need to create two brudge devices in BYOP, and then your device in the second bridge device. The example is very similar, just makes one bridge. https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-BRG0.dsl

**Comment by ninjuan11** [comment]
but how does the system know, that these two dummy devices correspond to the device?

**Comment by vit9696** [comment]
By ADR, which is 0.

**Comment by ninjuan11** [comment]
ah. okay, now i understand. so when the device path is PCI0.BXBR.BYUP.BYD4.pci-bridge@4.pci-bride@0.pci1102.10 the SST would be:

```
DefinitionBlock ("", "SSDT", 2, "ACDT", "STH0", 0x00000000)
{
    External (_SB_.PCI0.BYBR.BYUP.BYD4, DeviceObj)

    Scope (\_SB_.PCI0.BYBR.BYUP.BYD4)
    {
        Device (STH4)
        {
            Name (_ADR, Four)

            Device (BRD0)
            {
                Name (_ADR, Zero)  // _ADR: Address
                Device (STH5)
                {
                    Name (_ADR, Zero)  // _ADR: Address
                }
             }
        }
    }
}
```

is that correct?

(STH = something)

**Comment by Andrey1970AppleLife** [comment]
Name (_ADR, 0x04)

**Comment by vit9696** [comment]
Actually looks plain wrong to me. At least compared to the screenshot [here](https://user-images.githubusercontent.com/67441126/99919320-f2c0fc00-2d1c-11eb-8c07-7ab787fca253.png).  Why the scope is set to `\_SB_.PCI0.BYBR.BYUP.BYD4` when it really is `\_SB.PCI0.BXBR.BYUP`? Then Andrey is correct, it should be `0x4` instead of `Four`.
