### ISSUE TITLE
AppleALC.kext: Microphone does not work in any Conexant CX20632 layout-ids

### ISSUE THREAD

**Issue by TonyC5** [acidanthera/bugtracker#1321]
When using AppleALC.kext versions 1.5.3 and 1.5.4 (and probably earlier versions, but not tested), the microphone does not work with Conexant CX20632.  I have tested layout-ids 20, 23 and 28 with a stand-alone microphone and a CTIA-style (4-connector) headset.

With layout-id 20 and AppleALC.kext 1.5.4, Hackintool (I know, Hackintool is unsupported) detects two audio inputs

- NID 26 (0x1A), PinDefault 018B1030, Device: Line In
- NID 29 (0x1D), PinDefault 01A11111, Device: Mic In

Is there anything that I can capture / provide to fix the microphone for this CODEC/layout-id?  Thank you.

My system is as follows:

- HP EliteDesk 800 G4 Mini, i7-8700, UHD630 (Microphone enabled in BIOS)
- OpenCore 0.6.3
- Catalina 10.15.7.03 and Big Sur 11.0.1
- AppleALC.kext 1.5.4, WhateverGreen.kext 1.4.4, Lilu.kext 1.4.9
- IRQ patches for HPET, RTC and TIMR are implemented and enabled

Note that with AppleALC.kext 1.5.4 and layout-id 20, macOS audio device properties display the microphone Input volume (with a slider that can be adjusted) and show the input level meter (which remains blank, regardless of the Input volume setting).

Also, the microphone works with VoodooHDA.kext 2.9.2, so I don't believe it's a hardware issue.

**Comment by vandroiy2013** [comment]
>Is there anything that I can capture / provide to fix the microphone for this CODEC/layout-id? Thank you.

You can ask authors of this layouts. Wen do not provide support here for custom user layouts. 
<img width="692" alt="Снимок экрана 2020-11-23 в 10 26 02" src="https://user-images.githubusercontent.com/8144780/99941285-72c78000-2d76-11eb-9582-8411ef6831d7.png">

**Comment by TonyC5** [comment]
Thank you.  I will contact the layout authors.
