### ISSUE TITLE
Fixing RTC writes not working properly

### ISSUE THREAD

**Issue by kecinzer** [acidanthera/bugtracker#1322]
Hello acidanthera team,
I'm currently using old way of RTC writes fix that including ACPI rename () and DisableRtcChecksum set to true.
Everything works great.
But I found this [GUIDE](https://dortania.github.io/OpenCore-Post-Install/misc/rtc.html) claiming, that my method is old and this way is better. So according this guide I found my bad regions (58-59 + DE-DF). So I add RTCMemoryFixup.kext and set this regions for blacklist. It seems to work, but after some time I got sometimes BIOS RTC error.
Also I noticed, that I got this error every time when I updated my macOS installation during every reboot within installer.

According this I think this FIX is less permanent and don't work for installer or recovery? Or I simply did something wrong in my procedure. There is old commit, that I reverted - https://github.com/kecinzer/hpelitebook850g5-opencore/commit/130521a7277413c3c7abb1de1861f4679eeb3ea4

I can attach my DSDT etc, but I don't think it's need. I have proper RTC device in my DSDT. Every other files is in my [REPO](https://github.com/kecinzer/hpelitebook850g5-opencore)

**Comment by khronokernel** [comment]
Very likely you have multiple bad regions, and OS updates trigger them as well. boot.efi can write to RTC which I assume is the same issue, for example `5859DEDF` aligns with my HP Elite X2's bad RTC regions but only for regular operations. Deep sleep will write to other regions and as well as boot.efi, so my total blacklisted regions are `58597F80818283B0B1B2B3DEDF`. Unfortunately it's not easy, and will take quite a bit of time. I spent about an evening testing all the regions trying to get every scenario fixed

**Comment by kecinzer** [comment]
@khronokernel thanks you for explanation. I will try you regions. I discovered my for one day. How you can discover all yours only on one evening? I tought, that there must be more regions that is related to other type of sleep or statuses.

**Comment by kecinzer** [comment]
@khronokernel  So I tried hibernation get to work and another RTC error occurred, so your range seems to not complete for my laptop. Anyways, after reboot of this RTC message, it seems system wake up normaly, but then there was sudden reboot. I need to investigate more.
Are you use hibernation or just sleep?
