### ISSUE TITLE
OC: 0.6.4/current master branch build reports missing file

### ISSUE THREAD

**Issue by MikeBeaton** [acidanthera/bugtracker#1323]
I get the following error when using `build_oc.tool` to build the current `master` branch:

``Building ... /Users/mjsbeaton/OpenSource/OpenCorePkg/UDK/OpenCorePkg/Library/OcAfterBootCompatLib/OcAfterBootCompatLib.inf [X64]
make: *** No rule to make target `/Users/mjsbeaton/OpenSource/OpenCorePkg/UDK/OpenCorePkg/Library/OcAfterBootCompatLib/X64/ContextSwitch.h', needed by `/Users/mjsbeaton/OpenSource/OpenCorePkg/UDK/Build/OpenCorePkg/DEBUG_XCODE5/X64/OpenCorePkg/Library/OcAfterBootCompatLib/OcAfterBootCompatLib/OUTPUT/CustomSlide.obj'.  Stop.``

This is in a Mac XCODE5 command line environment which builds 0.6.3 perfectly.

**Comment by vit9696** [comment]
That's a bug with EDK II build system. Simply reclone the repo.
