### ISSUE TITLE
Problem with sound with AppleALC

### ISSUE THREAD

**Issue by m0d16l14n1** [acidanthera/bugtracker#1325]
I am not sure, if there previously were the same problems with some hardware, but i didn't find the problem like mine. 

In two words: i can't get my headphones working, and that's not resources problem. I will explain it (i mean i try, English is not native for me, so if there will be any problem with understanding my phrases - i can describe them on Russian better, heh. Actually i mentione about that case on AppleLife at some topics)

So, i have Ice Lake laptop with ALC256 codec. And it's really close to MateBook and other Huawei laptops with ALC256 (same nodes for speakers/headphones and etc). The problem is that i can get only: 

 1) 4 speakers working at the same time and no headphones (speakers node 20/27 (0x14/0x1b), headphones 33 (0x21)
or 
2) 2 speakers + headphones 

Mics are working okay (internal and jack seems to work too, i tested it once i got headphones and 2 speakers working)

The kinda same problem i got on Linux - i got only 2 speakers + headphones working, but i used hdajaretask tool and enabled back speakers node (0x1b) and now it's working like it's working on Windows. 

What i tried to fix that problem: checked all the layouts / changed some layouts from MateBook [(i mentioned my problem here too)](https://github.com/profzei/Matebook-X-Pro-2018/issues/71) (here you can find the codec dump from Matebook and compare it to codec dump from my laptop) to get them indentical to my codec setup (layout 76 or 97) / build my own "layout". I still can't get 4 speakers + headphones working. I am not sure, but maybe it's related somehow to previous Ice Lake problem (it wasn't properly supported before). How i can debug that and find the issue? I can't find the reason why it's not working

I will attach dumps of codec from Windows with plugged and unplugged headphone + compatible and tested layouts from AppleALC. If i need to attach something more - tell me please. Logs from AppleALC are clear. 

[RtHDDump-WITHheadphones.txt](https://github.com/acidanthera/bugtracker/files/5583868/RtHDDump-WITHheadphones.txt)
[RtHDDump-WITHOUT-headphones.txt](https://github.com/acidanthera/bugtracker/files/5583870/RtHDDump-WITHOUT-headphones.txt)
[layouts-platforms.zip](https://github.com/acidanthera/bugtracker/files/5583884/layouts-platforms.zip)
[Here](https://github.com/Ardentwheel/OpenCore-Hasee-X57S1/tree/master/Tools/Audio) is all the files related to codec (dumps/pinconfig/route)

**Comment by m0d16l14n1** [comment]
By the way, with VoodooHDA by default only 2 speakers + headphones working. I find that out while was trying to make my own layout with "special" version of VoodooHDA  (GetdumpXML).

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by m0d16l14n1** [comment]
@Andrey1970AppleLife That's not the support question. Reasources (layout and platform) are correct, but still not headphones
