### ISSUE TITLE
[OpenDuet] DEBUG target compiled with -lto act weird

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#1326]
The same sources compiled without -lto are sane and binaries act as expected. BOOT MISMATCH! gone without -lto.

Same happens with NOOPT target. Did not checked RELEASE one.

**Comment by vit9696** [comment]
Does it reproduce with prebuilt binaries? Are you doing a clean rebuild between the builds?

**Comment by nms42** [comment]
Weird behavior or sane?
Precompiled binaries from github and|or dortania are bad ones. What kind of compilations at least should I do?

**Comment by vit9696** [comment]
The weird behaviour. This is surprising as precompiled binaries work for for us. We tried updating boot file from https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true&version=0.6.4&sha=3be03979a806855757a879ff0622afcbde60b278, and it worked without issues. Could you try that build as well and also check which exact binary is the cause. I.e. is it boot or anything else?

**Comment by nms42** [comment]
![IMG_20201122_142352](https://user-images.githubusercontent.com/3739370/100078928-1f782f00-2e55-11eb-9b0d-3c519df1e465.jpg)
(1) BOOT MISMATCH! message with boot media made accordingly to documents. That message happens at random on my comps. But one, where it's steady.

(2) When inserted message
```
gST->ConOut->OutputString (gST->ConOut, L"CHECK ENTER\r\n");
gBS->Stall (3000000);
```
to Legacy/BootPlatform/BdsDxe/BdsEntry.c BdsCheckSignature()
the resulting binary (bootX64) just crashed with RSOD (Red Screen Of Despaire)
with weird numbers. Image attached.

I do my compiles with Xcode 12.2.

**Comment by nms42** [comment]
Well, after some googling I tried
```
-lto=thin
```
DEBUG binary (OpenDuet) did not exhibit weird behavior after quick test. Size of it roughly the same.

**Comment by vit9696** [comment]
Could you try to locate the exact module where it happens and then the exact line? We cannot reproduce it here, but it is very important to fix the code with LTO, as it will break sooner or later without it, since such an error really means an undefined behaviour somewhere.

**Comment by nms42** [comment]
Will do. It takes time.

**Comment by nms42** [comment]
Well, sometimes long memory is good. I incorporated this patch years ago in bareBoot project.
With attached patch OpenDuet binary LGTM (Looks Good To Me).

[lbt.diff.txt](https://github.com/acidanthera/bugtracker/files/5591017/lbt.diff.txt)

**Comment by nms42** [comment]
Anyway field test needed.

**Comment by vit9696** [comment]
Hrm. That change makes some sense, however, it is worrying to simply null the flags including IF and such:

```
+  // Clear the eflags value that will be popped when the legacy BIOS code
+  // executes IRET to return control to the caller. It is important that
+  // trap flag is not set in this value because the resulting INT1 will
+  // stop execution.
+  Stack16 [0] = 0;
```

Are we sure it should directly assign 0 here? If so, which flags does it reset in the field?

**Comment by nms42** [comment]
There is no BIOS interrupt used in (Open)Duet, where information conveyed to BIOS via flags. Direct assign of zero clear all flags.

Word 'field' was used as short form of 'on real users'

**Comment by vit9696** [comment]
From what I understand OpenDuet pops rflags from that field after exiting from 16-bit mode. I am worried whether the return code might override currently enabled flag bits if zero them all. Or is it OR'ing them?

**Comment by nms42** [comment]
Actually memory used for Stack16 is allocated without zeroing (InitializeBiosIntCaller()). So patch just overwrites garbage.

**Comment by vit9696** [comment]
Geez. In this case maybe a much better solution is to actually zero the memory right at the allocation? In both BiosVideo and CpuDxe? I would also suggest moving LegacyBiosThunk.c code to a library, so tat CpuDxe and BiosVideo can use it. But for an immediate solution we can add ZeroMemory to both function. Could you test whether it works for you? If so, submit a PR. Tyvm for spotting this.

**Comment by nms42** [comment]
The location for LegacyBiosThunk stuff (*.h & *.c) in OpenCore source tree?

**Comment by nms42** [comment]
Glance at CpuDxe code: in cpudxe case flags are handled, thunk code a little bit different. For BiosVideo, IMHO, 
```
Stack16[0] = 0;
```
is enough.

What would be gained by having one thunk code?

**Comment by nms42** [comment]
By the way, audk/UefiCpuPkg/CpuDxe brings MP (multiprocessing). On the other hand, concurrency can reveal some hidden **sweet** bugs in OC.

**Comment by nms42** [comment]
May be use in OC project legacy bios stuff from audk/OvmfPkg?

I love code maintained by someone else. (-;

**Comment by vit9696** [comment]
Should be in in Library/SmthLib. E.g. OcLegacyBiosLib. Currently I see `InitializeBiosIntCaller` being present in `Legacy/BootPlatform/CpuDxe/CpuDxe.c` and `Legacy/BootPlatform/BiosVideo/LegacyBiosThunk.c`. Its implementation is the same except the argument presence. Not all the code from OvmfPkg can be used in OpenDuet, I migrated a lot myself, but some code needs extensive adoption.

I suggesting zeroing the memory [here](https://github.com/acidanthera/OpenCorePkg/blob/52d5f1486bfdd6a106e97a61a6848ac2f3df0d28/Legacy/BootPlatform/BiosVideo/LegacyBiosThunk.c#L45) instead of `Stack16[0] = 0;`. This looks like a more natural solution to me given that the issue is uninitialised memory. Same for [CpuDxe](https://github.com/acidanthera/OpenCorePkg/blob/cbd60d9662cdcc9d6036bd28dcec524dbbf84a84/Legacy/BootPlatform/CpuDxe/CpuDxe.c#L1164).

**Comment by nms42** [comment]
Pull request submitted.
