### ISSUE TITLE
Since the Big Sur safemodeslide fix, OpenCore doesn't boot Mac OS version below High Sierra

### ISSUE THREAD

**Issue by tahsinahmed2** [acidanthera/bugtracker#1327]
The testet OpenCore build is the latest build at the moment (Commit:3be0397, OcPngLib: Use Standard OpenCore Function Name Format)

Since the commit: e8cc05f, OcAfterBootCompatLib: Fixed `EnableSafeModeSlide` on macOS 11.0,
OpenCore can't boot versions below High Sierra or Sierra (Can't test Sierra, because currently I doesn't have the installer).
So Mavericks, Yosemite, El Capitan, Mountain Lion and Lion doesn't boot anymore, didn't test Snow Leopard or version below Snow Leopard.

But if I disable SafeModeSlide then it can boot all version's again, but then I can't boot to SafeMode, also tested on the latest build.

SecureBootModel is on disabled, and dmgLoading is on Any.

For reference I will include my config.plist and the Debug logs.
One log with successful bootet Catalina, one log with non-successful bootet Mavericks, and one version with successful bootet Mavericks (SafeModeSlide disabled)
I had to change the .plist to .txt, so I can upload it here.

btw. sorry for my bad english, and when it's my fault that it doesn't work.

https://mega.nz/folder/CR40BQqY#7JCzUz5BVT5GYthQIuKXuw

[config.plist.txt](https://github.com/acidanthera/bugtracker/files/5586444/config.plist.txt)

[Catalina opencore-2020-11-23-230758.txt](https://github.com/acidanthera/bugtracker/files/5586447/Catalina.opencore-2020-11-23-230758.txt)

[mavericks opencore-2020-11-23-231142.txt](https://github.com/acidanthera/bugtracker/files/5586449/mavericks.opencore-2020-11-23-231142.txt)

[mavericks without safemodeslide opencore-2020-11-23-231924.txt](https://github.com/acidanthera/bugtracker/files/5586451/mavericks.without.safemodeslide.opencore-2020-11-23-231924.txt)

[Catalina SysReport.zip](https://github.com/acidanthera/bugtracker/files/5586454/Catalina.SysReport.zip)

[SysReport mavericks.zip](https://github.com/acidanthera/bugtracker/files/5586456/SysReport.mavericks.zip)

[SysReport mavericks without safemodeslide.zip](https://github.com/acidanthera/bugtracker/files/5586457/SysReport.mavericks.without.safemodeslide.zip)

![20201123_230007](https://user-images.githubusercontent.com/30934904/100031477-0ab87e80-2df6-11eb-9998-5d72b8d4f500.jpg)

![20201123_225959](https://user-images.githubusercontent.com/30934904/100031486-0ee49c00-2df6-11eb-97fa-9e6118eaa491.jpg)

**Comment by vit9696** [comment]
Please report.

**Comment by tahsinahmed2** [comment]
Yes, now everything boots again with SafeModeSlide activated except EL Capitan.
But I think that El Capitan doesn't boot have something to do with my config, not OpenCore.
btw. The SafeMode with BigSur is still working, was just an irrelevant extra test.

[opencore-2020-11-30-225209.txt](https://github.com/acidanthera/bugtracker/files/5619224/opencore-2020-11-30-225209.txt)

[SysReport.zip](https://github.com/acidanthera/bugtracker/files/5619226/SysReport.zip)

**Comment by vit9696** [comment]
10.11 may have been our bug. Check master again.

**Comment by tahsinahmed2** [comment]
Now El Capitan also boots again with SafeModeSlide, thanks.

**Comment by vit9696** [comment]
So do all the other including Big Sur?

**Comment by tahsinahmed2** [comment]
Yes everything now works.
But I didn't tested the SafeMode with BigSur, will test it later, when I'm home again.

**Comment by tahsinahmed2** [comment]
Sadly the SafeMode is broken on BigSur again, get always a StartImage failed message.

btw. for reference I will also upload the config with the the SMBIOS for booting BigSur in SafeMode (It is the same config, just another SMBIOS)

[opencore-2020-12-01-113005.txt](https://github.com/acidanthera/bugtracker/files/5622286/opencore-2020-12-01-113005.txt)


[config.plist.txt](https://github.com/acidanthera/bugtracker/files/5622290/config.plist.txt)


[SysReport.zip](https://github.com/acidanthera/bugtracker/files/5622287/SysReport.zip)

**Comment by vit9696** [comment]
Yes, noticed. Please retest everything again now. Sorry for inconvenience.

**Comment by tahsinahmed2** [comment]
No problem at all, and thanks for fixing it.

And yes now everything boots just fine, also BigSur boots just fine, and BigSur boots now also in SafeMode again.
