### ISSUE TITLE
Black screen on boot / Some weird glitch

### ISSUE THREAD

**Issue by m0d16l14n1** [acidanthera/bugtracker#1329]
I will upload video of that bug. Laptop is Ice Lake (and just to be sure - my brightness is fully okay, i don't have any issue related to brightness like some guys with Ice Lake have). I checked if there are any similar problems like - the most common with Ice Lake brightness bug, but i am not sure if it's related to it too. 

I am using debug version of OC 0.6.3 / latest version of debug kexts

I will try to explain in words: after booting in verbose or not, after Apple logo with progress bar i got black screen for 10 seconds, after that login screen will appear. But one day i just clicked on NumPad and right after boot i got my screen working, but it will get again black, if won't click my NumPad, until 10 seconds or less is gone. In some rare cases i got login screen blink for a second after Apple logo, but it's dissapears and i get black screen, until 10 seconds gone. 

I am not sure how to properly debug that problem, because logs of WhateverGreen seems to be okay. If you need any logs or files - tell me please, i will upload them

The video file is big, so i can upload it only to Yandex.Disk, idk if it's okay, but you can preview files there without downloading them - https://yadi.sk/i/lhkeHBw8rMkEjg

**Comment by m0d16l14n1** [comment]
Will upload a couple of debug logs. 

[green.log](https://github.com/acidanthera/bugtracker/files/5600694/green.log)
[green2.log](https://github.com/acidanthera/bugtracker/files/5600695/green2.log)
[green3.log](https://github.com/acidanthera/bugtracker/files/5600696/green3.log)

**Comment by vit9696** [comment]
@usr-sse2 @lvs1974 @0xFireWolf @hieplpvip @zhen-zen @osy86 did not you have anything similar? If so, could you post the details?

@m0d16l14n1, this sounds like a bug in the driver, but I am not positive we will debug Ice Lake as there is no hardware here and the problem is not widely reproducible. Sorry.

**Comment by 0xFireWolf** [comment]
I am aware of this issue. A short period of black screen due to eDP link training failures happens on ICL-based laptops with 4K display, while a short period of glitches occurs while users stay at the login window on laptops with 1080p display. However, I don't own ICL laptops myself, so it's hard for me to analyze these issues in depth.

**Comment by m0d16l14n1** [comment]
> I am aware of this issue. A short period of black screen due to eDP link training failures happens on ICL-based laptops with 4K display, while a short period of glitches occurs while users stay at the login window on laptops with 1080p display. However, I don't own ICL laptops myself, so it's hard for me to analyze these issues in depth.

I have 1080p screen and i have no glitches on login screen. Just that issue with black screen

**Comment by 0xFireWolf** [comment]
> I have 1080p screen and i have no glitches on login screen. Just that issue with black screen

My hypothesis is that your black screen issue is inherently the same as the glitch one, because the symptom disappears when a key is pressed but immediately reappears after the key is released.

**Comment by m0d16l14n1** [comment]
> > I have 1080p screen and i have no glitches on login screen. Just that issue with black screen
> 
> My hypothesis is that your black screen issue is inherently the same as the glitch one, because the symptom disappears when a key is pressed but immediately reappears after the key is released.

Okay, got it

**Comment by m0d16l14n1** [comment]
> @m0d16l14n1, this sounds like a bug in the driver, but I am not positive we will debug Ice Lake as there is no hardware here and the problem is not widely reproducible. Sorry.

@vit9696 простите за пинг, просто забыл задать вопрос по поводу этого бага в драйвере. А вообще как-то можно отследить обновляются ли дрова под графику Эплом или нет? На бетках биг сюра у меня просто был другой баг (яблоко загружалось до половины и потом все уходило в черный экран). На стабильной же изменилось - яблоко грузится полностью и потом черный экран. Писал об этом на [AppleLife](https://applelife.ru/threads/hasee-kingbook-x57s1.2945175/)

Понимаю, что немного оффтоп, не не могли бы вы глянуть вот эту [тему](https://github.com/acidanthera/bugtracker/issues/1325) тоже? Я уже все варианты перепробовал - наушники не алло все равно. (в теме на AppleLife тоже описывал). Я просто то ли косячу сам где-то, то ли это какая-то беда с Ice Lake или именно моим кодеком (что тоже возможно, конечно). Проблему описывал тоже на AppleLife в темах по VoodooHDA/и теме связанной с подготовкой своих ресурсов для AppleALC.

Извиняюсь, что на русском, просто не очень легко на английском пояснять все.

**Comment by m0d16l14n1** [comment]
> I am aware of this issue. A short period of black screen due to eDP link training failures happens on ICL-based laptops with 4K display, while a short period of glitches occurs while users stay at the login window on laptops with 1080p display. However, I don't own ICL laptops myself, so it's hard for me to analyze these issues in depth.

It's seems that with external screen connected that issue is fixed (both monitors will light up after 1 second).

The most interesting that in first (with external screen) log you can see "Link Training successful" for both sreens (internal and external)

But in second one - you won't find that line
It's even not starting (?) without external screen connected
Also you won't find "Begin link training", "Attempt link training", "End link training" in log without external screen connected

I will attach logs, in case it can help

[logIGFBwithEXTERNALscreenCONNECTED.log](https://github.com/acidanthera/bugtracker/files/6087020/logIGFBwithEXTERNALscreenCONNECTED.log)
[IGFBwithoutEXTERNALscreen.log](https://github.com/acidanthera/bugtracker/files/6087021/IGFBwithoutEXTERNALscreen.log)

**Comment by xzz024** [comment]
Hello, the same situation, and I found that the mouse pointer is not displayed at this time, in the state of flower screen, if you move the mouse will also be black screen flashing. But the mouse pointer will return to normal after 10 seconds when the screen returns to normal display, I guess whether it is related to this, thanks for browsing.
