### ISSUE TITLE
[VoodooPS2] Palm Rejection Issue or Disable by PrtScr

### ISSUE THREAD

**Issue by twlawrenceko** [acidanthera/bugtracker#1330]
Hello,

I have been using the latest version of VoodooPS2 with VoodooI2C to support multi-gesture on my laptop. However, when typing a document, the palm rejection does not work where if my palm touches the trackpad while typing, the cursor does not even show up but only changed the typing location (i.e. the 'I' sign). Is there any way to set a higher delay time for palm rejection?

Also, as I can recall before, PrtScr key used to work to disable trackpad but it does not work now. However, with Cmd+PrtScr, keyboard gets disabled.

Thank you,
twsps

**Comment by zhen-zen** [comment]
Personally I suppose there's issue with your VoodooI2C satellite kext. Please try earlier VoodooPS2 releases and report on which version did that break.

**Comment by twlawrenceko** [comment]
> Personally I suppose there's issue with your VoodooI2C satellite kext. Please try earlier VoodooPS2 releases and report on which version did that break.

Palm rejection issue always occur, tracking back to 2019..
However, if you mean PrtScr disabling trackpad, then it breaks when I update to new VoodooPS2 without updating to latest VoodooI2C as latest VoodooI2C seems to change some configuration that a new SSDT is needed.

**Comment by 1Revenger1** [comment]
These are issues with VoodooI2C - afaik the team for VoodooI2C haven't written in support for any sort of palm rejection.
For the prtscr issue, probably best to specifically say in which version it specifically broke, and which version specifically worked. ie 2.1.8 worked but 2.1.7 didn't work. We have no clue what version your upgrading from, and knowing which version broke it helps to narrow down changes/commits.
