### ISSUE TITLE
WhateverGreen - KabyLake Platform is detected as CFL Platforms

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#1332]
I try to install in "EVE V Notebook" with "i7-7Y75 Procsssor with Intel HD 615". The generation of this processor is KabyLake.

But when i use "-wegdbg" with "latest DEBUG WEG" i saw this Logs.
![photo_2020-11-26_11-05-50](https://user-images.githubusercontent.com/9614101/100309021-6c3a4200-2fdc-11eb-9ded-f1590df7b8d1.jpg)

Found CFL Platform - Will setup the fix for the CFL - Graphics Driver
(CFL) - Function have been routed successfully

Is it normal???

**Comment by 0xFireWolf** [comment]
Those lines in your red rectangle are produced by my maximum link rate fix.   
It says `Found CFL- platforms`, and `CFL-` means that platforms <= Coffee Lake.  
That being said, you don't need to worry about it.
