### ISSUE TITLE
Opencore brokes Bios gigabyte z87-d3h

### ISSUE THREAD

**Issue by Bradipi15** [acidanthera/bugtracker#1333]
Hi i have a problem with Opencore. When i boot from opencore realease or debug too, i don't know how, it brokes my bios. In fact when i reboot i can't acces bios anymore...i have to reset bios using a jumper on Mbios

Doesn't need to have other hard drives connected, if i boot with ONLY a pendrive with opencore, it brokes my bios.
Please help me to understand what is happening and why.

Firmware version OC is 0.6.3 and Bios firmware is F9 for Gigabyte z87-d3h Dual boot
My hardware is Cpu i5 4670k gpu HD4600 Gpu RX570 4gb Ram 8gb kingston Ssd Kingston 480gb

**Comment by 1Revenger1** [comment]
https://github.com/acidanthera/bugtracker/issues/1222
Turn off BootProtect

**Comment by Bradipi15** [comment]
It works! Thanks so much!
