### ISSUE TITLE
CI Notices Appearing in Forked Repos 

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1336]
The recent change to the CI is propagating to forked repos which are now getting notices about CI runs on the main.

**Comment by dakanji** [comment]
Found a workaround but should really be taken care off at source:
![Screen Shot 2020-11-28 at 18 13 18](https://user-images.githubusercontent.com/1128876/100518883-8410f200-31a5-11eb-81ea-f039ee09c830.jpg)

**Comment by dhinakg** [comment]
Did this not occur with Travis CI (if you had it enabled for your account)? I did some testing with @khronokernel and it appears so.

**Comment by dakanji** [comment]
> Did this not occur with Travis CI (if you had it enabled for your account)?

Don't know. I didn't have Travis enabled for this repo. Actions are apparently enabled by default unlike and unless you specifically turn it off as I did above, you are swamped with emails.

Anyway, please see the PR which resolves this by limiting the scope of the action to the acidanthera/OpenCorePkg repo.

**Comment by vit9696** [comment]
Disagree as this makes CI explicitly unavailable for forked repos and makes external patch testing much harder. I believe having CI work on external repos is the desired behaviour.

**Comment by dakanji** [comment]
Bad call IMO.

A forked repo can/would do its own CI for things the repo owner wants to do them on and how they want this.
They shouldn't have to be bothered with what is basically spam but it's your call at the end of the day!

**Comment by vit9696** [comment]
Maybe I do not understand something? For me once you fork you get working CI builds whenever you commit. What spam are you talking about? Are there any particular issues?

**Comment by dakanji** [comment]
With the current setup, you get notices of **ALL** CI builds from **ALL** commits to the main branch.

If you refer to the image I posted above, you will see that two notices appearing on my fork (along with emails) before I disabled the action are not from commits that I made but from commits made by others to the Main Repo. I am sure you can understand that one doesn't typically want to be receiving emails on every commit to a main repo just because you forked that repo.

In terms of working CI builds on a fork, you commit and wait 30 mins for CI on your fork, make a PR and wait another 30 mins for CI on the Main Repo. I would personally just have it done once on the Main Repo myself and deal with any issues that come up.

Actions are great but needs to be targeted but it is currently not the case.

Having said all that, it's not a big deal. I will just keep the actions disabled on my end and sure most of your forks will soon be like that. 

On the other hand, if you applied some discrimination to the actions, they would stay active and you could target some actions to be run on both the Main and Forked Repos (by not having that `If` statement on such specific actions) or have some specifically targeted at Forked Repos (by using `if: github.repository != 'acidanthera/OpenCorePkg'`)

The current broad brush will most likely lead to the whole thing being switched off.

I can imagine there are various things to consider beyond the above but then, you are the one in the hot seat!

**Comment by vit9696** [comment]
On your screenshot I only see your commits, so I am not positive it runs CI jobs and posts notification for anything but your commits. I.e. commits to the master branch of the main repo should not cause CI jobs or notifications on the forked repo. 

The only thing I am worried about is Coverity. This thing can only run in our repository due to the secrets, and it will cause CI jobs to fail in the forked repos. Could that be a thing you confused your issue with?

@dhinakg can we add an if to coverity task, so that it does not run not only for pull requests but also for anything but `acidanthera/OpenCorePkg`? For Travis we did have that. Coverity was restricted to master branch (which was a bit too much) of the main repository and did not get triggered anywhere else.

**Comment by dakanji** [comment]
> On your screenshot I only see your commits

I didn't make the commits:
- [Database: Update Apple Locations](https://github.com/acidanthera/OpenCorePkg/pull/158) was by @denskop
- [Build: Switch CI to Github Actions](https://github.com/acidanthera/OpenCorePkg/pull/160) was by @dhinakg

**Comment by CoronaHack** [comment]
> Found a workaround but should really be taken care of at source:
> ![Screen Shot 2020-11-28 at 18 13 18](https://user-images.githubusercontent.com/1128876/100518883-8410f200-31a5-11eb-81ea-f039ee09c830.jpg)

Looks like you enabled it manually. Just did a fresh fork to my account.

![image](https://user-images.githubusercontent.com/61421774/100590363-4213b780-332f-11eb-920d-4a84b6124182.png)

**Comment by dakanji** [comment]
> Looks like you enabled it manually. Just did a fresh fork to my account.

Read the message you got. If you do a fresh fork, it is not enabled. If you have an existing fork, it is enabled automatically.
Suppose I can delete my fork and do it again.

**Comment by CoronaHack** [comment]
> But then, if it is not enabled by default on fresh forks, the stated aim of providing something on forks falls down a bit.

https://github.com/acidanthera/OpenCorePkg/blob/master/.github/workflows/main.yml#L5

Pull requests are still on, the CI will run as expected as long as someone makes a PR. This is the expected behavior.

**Comment by dakanji** [comment]
> Pull requests are still on, the CI will run as long as someone makes a PR.

It will run on the Main Repo, yes. talking about the Forked Repo. Nothing runs on the Forked Repo since the actions are disabled.

**Comment by vit9696** [comment]
> > Looks like you enabled it manually. Just did a fresh fork to my account.
> 
> Read the message you got. If you do a fresh fork, it is not enabled. If you have an existing fork, it is enabled automatically.
> Suppose I can delete my fork and do it again.
> 
> But then, if it is not enabled by default on fresh forks, the stated aim of providing something on forks falls down a bit.

Right, in this case you should report it to Microsoft.

**Comment by CoronaHack** [comment]
> > Pull requests are still on, the CI will run as long as someone makes a PR.
> 
> It will run on the Main Repo, yes. talking about the Forked Repo. Nothing runs on the Forked Repo since the actions are disabled.

You could always enable it if you need to. I don't see any problem here.

**Comment by dakanji** [comment]
> You could always enable it if you need to.

Exactly the point!

> Right, in this case you should report it to Microsoft.

Will just keep the actions disabled since that is the behaviour with new forks anyway.

**Comment by dhinakg** [comment]
> @dhinakg can we add an if to coverity task, so that it does not run not only for pull requests but also for anything but `acidanthera/OpenCorePkg`? For Travis we did have that. Coverity was restricted to master branch (which was a bit too much) of the main repository and did not get triggered anywhere else.

Sure, I can do that.

@dakanji, running CI on any pushed commits (whether you authored them or not) is the intended and expected behavior, whether you are using Travis CI or GitHub Actions. Preexisting forks are not going to have GitHub Actions without pulling the new commits (which many forks do not do), and as @CoronaHack said, new forks have Actions opt-in by default, so the scope of this issue is not as big as you claim. I do not see why we should intentionally make CI more difficult to set up on forks for the majority when the minority could just disable Actions in repo settings or adjust their [email preferences](https://github.com/settings/notifications), which is easy enough.

**Comment by dakanji** [comment]
Thanks for the note ... Much appreciated.
Think differently but moved on already.
