### ISSUE TITLE
OC: auto-generate plist boilerplate

### ISSUE THREAD

**Issue by MikeBeaton** [acidanthera/bugtracker#1337]
I'm working on a small Python script to generate the boilerplate parts of (i.e. most of) `OcConfigurationLib.c` and `OcConfigurationLib.h` from a template plist file. To explain how it can work from a plist file when this doesn't have quite enough data per se to reverse the mapping: I am using slightly munged plist element names (e.g. `<dict-as-map>` instead of `<dict>`, `<data-as-unit32-4>` or `<data-as-blob>` instead of `<data>`) to override reasonable default interpretations of elements, where needed, which is actually only occasionally. So far, I think it's looking promising.

As previously, FYI, my reason for working on this is that I am writing a small separate util which I am currently linking to OC libraries for plist support and this will help me generate my own different (much smaller!) plist definition.

**Comment by MikeBeaton** [comment]
Minor update: No reason why elements in a plist file can't use attributes AFAIK, so will use that (again, only where needed, which is occasionally, with sensible defaults taken from the data itself the rest of the time) instead of previous, baroque idea of renaming elements!

**Comment by vit9696** [comment]
Unsure what you mean. Plist files should be editable in plist editors like Xcode. This is the reason we stick to this format and will not change it.

**Comment by MikeBeaton** [comment]
Hi - apologies if I was unclear.

I'm implementing what I take (took?) to be implied by this: https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Acidanthera/Library/OcTemplateLib.h#L112-L113

In more detail, I would like to use the OC plist support in my own project, but it is rather fiddly to specify the structure of a plist file in OC. Not least, but not only, because the entire plist structure is specified effectively twice over, once in `OcConfigurationLib.c` and `OcConfigurationLib.h`.

So my proposal, initially just for my own use, but I hoped it might be useful to the project as a whole, is to generate the vast majority of the content of these two files automatically, from a template `config.plist` file. Looking at it, the template file can almost be just be one of the existing sample `config.plist` file - you can work out almost everything from that - with some very light additions to its markup where needed.

There is no intention at all to change what end users use. The intention is to make it easier for the developers to add to or modify the plist layout. And specifically, my use case, to make it *much* easier to specify a completely new plist layout from scratch, for use in a different app which just wants to leverage the OC plist file support.

I hope that makes some kind of sense.

Thanks, again, for this very useful - and high quality - project!

**Comment by vit9696** [comment]
The point of not using a separate tool is to reduce the dependencies on the other languages. There is also no duplication: .h file describes the internal structure, and .c file maps external plist structure to the internal structure. It is done in a way that .h file may contain more fields than .c file, and this is actually used at the moment for storing extra data as needed.

If you want to generate a thing from a schema, it is best to use something standard like https://en.wikipedia.org/wiki/XML_schema.

**Comment by MikeBeaton** [comment]
Okay, sure, I wasn't introducing a new dependency, in that Python is
clearly already used in various places! (Hence why I thought it should be
fine to use it.) (Also, FWIW, I was not thinking of this as a build step,
but rather as something that might be done occasionally, to update two
files which *are* used in the build - but anyway that's too much detail and
might not have been the right decision even if the rest of this approach
did work.)

For your other comments, fair enough, of course.

I will continue to play around with this for my own use. It is definitely
cumbersome (seems cumbersome, to me) to generate a new plist definition
without some tool to help.

That said, it sounds like I'm going to run up against the problem of not
being able to generate the extra, hidden fields which you're mentioning,
pretty soon.

If I do get something which works - i.e. can regenerate your exact layout,
and can generate new layouts for me - then perhaps I can drop a line back
here, just FYI?

Thank you.

**Comment by vit9696** [comment]
Sure, regardless of whether we merge it or not, I am interested in the results.
