### ISSUE TITLE
OC loading issue before Boot Pickup Screen (During OCII --> OCABC Phase) on Haswell (4th Gen) Laptop

### ISSUE THREAD

**Issue by attlaflagello** [acidanthera/bugtracker#1340]
The OC loading process stops in first phases (during OCII and OCABC) without any clear message.
Including EFI Folder and OC Log. Not necessary to put Lilu Log, since the issue is previous to any KEXT Loading

Check of config.plist on Sanity Check Website is all Green [Sanity Check Link](https://opencore.slowgeek.com/?file=laptophaswell063y15beH&rs=laptophaswell063)

**Attachments:**
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5611831/EFI.zip)
[opencore-2020-11-28-202626.txt](https://github.com/acidanthera/bugtracker/files/5611832/opencore-2020-11-28-202626.txt)

Please help is needed to understand which is the cause of this freeze.
Thanks,

attilaflagello

**Comment by vit9696** [comment]
I do not see OCABC here, why did you mention it? The freeze, if the log is complete and it never goes further, possibly relates to Input settings like unlucky timers or input overriding.

**Comment by attlaflagello** [comment]
OCABC is mentioned because I've seen a lot of others logs, and next step in start procedure is OCABC.
The log is complete, and I've tried also to add efi drivers for ps2 keyboard (native on laptop), or used an usb keyboard connected to the laptop itself. Nothing changes.
From log it seems impossible to detect which timer could be the problem.
Any help it's appreciated.
Thank and Regards,

attlaflagello

**Comment by vit9696** [comment]
Well, try to fiddle with Input parameters. Most likely the issue is somewhere in them.

**Comment by attlaflagello** [comment]
Doing some testing... it's possible to display the Boot Pickup menu by Forcing KeySupportMode. However the keyboard is not working.
Tried multiple ways to let it work:

1) Set KeySupportMode=V1 (not work as Auto)
2) Set KeySupportMode=V2 (KB not works, but it display Boot Menu)
3) Set KeySupportMode=AMI (KB not works, but it displays Boot Menu)
4) Added Ps2KeyboardDxe.efi to Drivers Dir, and Set KeySupport=False (KB not works, but it displays Boot Menu)
5) Tested different values of TimerResolution={50000, 600000, 0}
6) Disabled ACPI\Patch entries (these was generated by SSDTTime)

Any other solution?

Nothing seems to work

**Comment by vit9696** [comment]
That means

**Comment by attlaflagello** [comment]
Thank you for fast reply.
Following punctual replies>

1) I don't know how to load Openshell.efi without passing through Boot Pickup Menu. Please send reference on how to perform this action.
2) Enabling KeySupport=True with Ps2KeyboardDxe.efi hangs the system anyway, but now the logs stops @ OCABC (there is an additional row on the log vs. before)
[opencore-2020-12-03-092320.txt](https://github.com/acidanthera/bugtracker/files/5634686/opencore-2020-12-03-092320.txt)
3) My laptop is a Toshiba Portege z30a (Intel i5-4310U with Intel HD4400). I've replaced the Intel Wifi Card with a Broadcomm one.

Best Regards,

attlaflagello

**Comment by vit9696** [comment]
Could you try moving the trackpad actively while letting OpenCore boot? For like a minute or two. Let me know if it works.

**Comment by attlaflagello** [comment]
It doesn`t work, and the log stops at last OCII step, as before, without arriving at forst OCABC step.
[opencore-2020-12-05-143141.txt](https://github.com/acidanthera/bugtracker/files/5647145/opencore-2020-12-05-143141.txt)

**Comment by attlaflagello** [comment]
Tested again without playing with touchpad and trackpad during OpenCore startup and the log stops at first step of OCABC
[opencore-2020-12-05-144034.txt](https://github.com/acidanthera/bugtracker/files/5647150/opencore-2020-12-05-144034.txt)

P.S.: Keyboard, TouchPad and Trackpad works well in BIOS and Win10 Installed in a dedicated partition.

Just for info, please find attached the log when forcing KeySupportMode=V2
[opencore-2020-12-03-210639.txt](https://github.com/acidanthera/bugtracker/files/5647156/opencore-2020-12-03-210639.txt)

**Comment by vit9696** [comment]
Alright, I will prepare a few test builds to try to understand the exact location of the issue and upload it here. Will you be available for testing for the next couple of hours or so?

**Comment by attlaflagello** [comment]
Sure! Available for testing in next couple of hours!

**Comment by vit9696** [comment]
1. Set Input preferences to the following values:

KeyFiltering - NO
KeyForgetThreshold — 5
KeyMergeThreshold — 2
KeySupport — YES
KeySupportMode — Auto
KeySwap — NO
PointerSupport — NO
PointerSupportMode - <empty>
TimerResolution — 0

2. Drop PS/2 or USB drivers from Drivers if any.

3. Create a log with this OpenCore build (requires config compatible with master version).

[OpenCore-input-r1.zip](https://github.com/acidanthera/bugtracker/files/5647190/OpenCore-input-r1.zip)

**Comment by attlaflagello** [comment]
Please find changes applied on Config.plist:
![config_plist](https://user-images.githubusercontent.com/75198289/101245943-7a8d0a00-3710-11eb-908f-53b53e50ee19.png)

Replacement of Opencore.efi Custom version:
![OpenCoreSubstitution](https://user-images.githubusercontent.com/75198289/101245958-91336100-3710-11eb-8815-8b97d5839dee.png)

And relative Log:
[opencore-2020-12-05-144034.txt](https://github.com/acidanthera/bugtracker/files/5647228/opencore-2020-12-05-144034.txt)

I`ve restarted the laptop after 30 secs of inactivity (black screen with toshiba logo only)
Please note that while laptop is hanged up, I see HDD led blinking at regular interval.

**Comment by attlaflagello** [comment]
Additional info:
I have Win10 installed on the laptop, and possibility to run a live version of Ubuntu, if some check on the hardware is necessary.

P.S: Keyboard trackpad and Touchpad works also on UBUNTU

**Comment by vit9696** [comment]
The log shows that you booted with an old OpenCore.efi version:
00:000 00:000 OC: OpenCore DBG-063-2020-11-02 is loading in Optional mode (0/0)…

Not the one I built for you and attached above.

**Comment by attlaflagello** [comment]
You are right... I've attached an old log (from 2.40PM... because the new version has not generated any log.
In addition I see no blinking HDD led on laptop.

The Opencore.efi version used is 1.280kb:
![ModifiedVersion](https://user-images.githubusercontent.com/75198289/101246763-a959af00-3715-11eb-9b70-99f70921a69d.png)

 vs. 746kb 0.6.3 Debug Original one:
![Original_Debug](https://user-images.githubusercontent.com/75198289/101246767-ae1e6300-3715-11eb-8277-f4ca32c09262.png)

**Comment by vit9696** [comment]
Hrm. You will need to update your configuration to 0.6.4 master first to be able to use that new OpenCore version. Can grab it from https://github.com/acidanthera/OpenCorePkg/suites/1613845093/artifacts/29579443.

**Comment by attlaflagello** [comment]
Sorry for long waiting.
Please find attached the log:
[opencore-2020-12-05-182918.txt](https://github.com/acidanthera/bugtracker/files/5647546/opencore-2020-12-05-182918.txt)

**Comment by vit9696** [comment]
[OpenCore-input-r2.zip](https://github.com/acidanthera/bugtracker/files/5647574/OpenCore-input-r2.zip)
Please try this one.

**Comment by attlaflagello** [comment]
Boot Pickup Menu Shown... but keyboard (Up/Down Keys) not working... not tried numbers... testing now... 
Attached log:
[opencore-2020-12-05-184838.txt](https://github.com/acidanthera/bugtracker/files/5647593/opencore-2020-12-05-184838.txt)

**Comment by attlaflagello** [comment]
Even numbers does not work

**Comment by vit9696** [comment]
That is expected. Please provide log with this one. Try to press some arrows, but expect the response to be very slow if at all. 
[OpenCore-input-r3.zip](https://github.com/acidanthera/bugtracker/files/5647620/OpenCore-input-r3.zip)

**Comment by attlaflagello** [comment]
Please find it here:
[opencore-2020-12-05-193058.txt](https://github.com/acidanthera/bugtracker/files/5647684/opencore-2020-12-05-193058.txt)

Process not shown the output on screen and also the Bott Pickup screen... it stops at black screen with toshiba logo

**Comment by vit9696** [comment]
Surprising, try this.
[OpenCore-input-r4.zip](https://github.com/acidanthera/bugtracker/files/5647694/OpenCore-input-r4.zip)

**Comment by attlaflagello** [comment]
I see "success" when pressing arrow key while loading... and "Not Ready" when not pressing... but after the loading... the keys does nothing on the menu.
Following the log:
[opencore-2020-12-05-195212.txt](https://github.com/acidanthera/bugtracker/files/5647714/opencore-2020-12-05-195212.txt)

I Think we're almost there :)

**Comment by vit9696** [comment]
Try this
[OpenCore-input-r5.zip](https://github.com/acidanthera/bugtracker/files/5647716/OpenCore-input-r5.zip)

**Comment by attlaflagello** [comment]
Keyboard is working in boot pickup menu.
It was possible to select "(External)" option.
The Display Output stopped at "release USB - Not Found" or something like that... but it not appears in log:
[opencore-2020-12-05-200846.txt](https://github.com/acidanthera/bugtracker/files/5647736/opencore-2020-12-05-200846.txt)

**Comment by attlaflagello** [comment]
Here the display screenshot:
![P_20201205_202043_vHDR_Auto.jpg](https://user-images.githubusercontent.com/75198289/101261445-77f1db00-3737-11eb-8308-bdda877c2130.jpg)

**Comment by vit9696** [comment]
Booter or kernel quirks, most likely. The use thing is about ReleaseUsbOwnership that you do not need. Pushed the changes to master, download from artifacts when finishes building. Top right corner here: https://github.com/acidanthera/OpenCorePkg/runs/1504314049

**Comment by attlaflagello** [comment]
Thanks for assistance! Happy to collaborate about improvements.
