### ISSUE TITLE
Discourage ExternalDiskIcons and related patches

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1341]
As discussed in https://github.com/acidanthera/OpenCorePkg/pull/162, it is possible to make both SATA and NVMe controllers show as built-in by injecting `built-in = <00>` into a dedicated device via DeviceProperties. This makes builtin quirks for patching the icons not only ugly (as they do not actually make the controller internal but are limited to the icon display) but also redundant as there are better ways to achieve this.

I suggest dropping `ExternalDiskIcons` quirk entirely and do not add the `ExternalDiskIconsNVMe` (proposed [here](https://github.com/acidanthera/OpenCorePkg/compare/master...1880709588665eb7bafc8556caffd1542d28334d)) and widely recommend using `built-in`. Also, for the compatibility purposes we could include the patches for both AHCI and NVMe in this issue in case anybody needs them for whatever reasons.

CC @Andrey1970AppleLife

**Comment by roddy20** [comment]
I don't know about NVMe, but built-in = <00> does not work with SATA, icons are yellow and DVD drive not found

**Comment by dreamwhite** [comment]
> I don't know about NVMe, but built-in = <00> does not work with SATA, icons are yellow and DVD drive not found

@vit9696 shouldn't `built-in` value be `01`?

**Comment by roddy20** [comment]
no difference, it must be key with any value

**Comment by dreamwhite** [comment]
> no difference, it must be key with any value

Uhm, have you tried setting it to `01`? I haven't found any documentation about this value and thought that `00` stands for False

**Comment by roddy20** [comment]
it is not boolean value
01 does not work exactly as 00

but ethernet is built in both with 00 and 01

**Comment by startergo** [comment]
> it is not boolean value

It works here:
![image](https://user-images.githubusercontent.com/7897244/100548829-04cefd00-323d-11eb-9be8-c01eb395d98b.png)

![image](https://user-images.githubusercontent.com/7897244/100548852-3051e780-323d-11eb-99d0-f2e3b3d08e37.png)

**Comment by vit9696** [comment]
Most likely it depends on the case, because on older boards it was indeed not possible to override this other than patching the kext or updating AHCI controller registers early at boot, which would require [patching BIOS](https://applelife.ru/posts/217249). You can sometimes fake ICH9 as ICH6 by injecting device-id <81260000>, but that also only works for some.

All in all, for SATA there are cases where only External → Internal patch can work, and thus we have a quirk for that (took me some time to refresh my memory). And for NVMe just injecting the device property always works, thus we have no quirk.
