### ISSUE TITLE
SecureBootModel must set to  Disable

### ISSUE THREAD

**Issue by amervelic** [acidanthera/bugtracker#1342]
after security update 2020-005 (high sierra 10.13.6) I had to turn off the security model (from Default to Disable) because macOS won't boot. OpenCore 6.3 latests kexts.

**Comment by vit9696** [comment]
We have instructions in the pdf for copying the manifests in such cases.

**Comment by dreamwhite** [comment]
> We have instructions in the pdf for copying the manifests in such cases.

Excuse me @vit9696, may you gently tell what PDF are you talking about? Is it Configuration.pdf or whatelse? 
I don't wanna get in trouble ^^

**Comment by vit9696** [comment]
Yes
