### ISSUE TITLE
[REQUEST] Rename FirmwareFeaturesMask

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1344]
The Docs suggest that "FirmwareFeatures" deals with the lower 32 bits while "FirmwareFeaturesMask" deals with the extended features in the upper 64 bits ... why is it not named appropriately as "ExtendedFirmwareFeatures"?

The current name gives the impression it masks "FirmwareFeatures" similar to how Cpuid1Mask masks Cpuid1Data but this does not seem to be the case.

**Comment by vit9696** [comment]
Because it is too long, and ExtendedFirmwareFeatures is just a hack for new firmwares.

**Comment by dakanji** [comment]
FirmwareFeaturesMask
ExtraFirmwareFeatures
... 
Same length and not misleading

**Comment by vit9696** [comment]
I believe you misunderstand how it works. Firmware features (also firmware-features in macOS) is a 64-bit number containing flags. It can be retrieved from multiple places, namely two NVRAM variables. On newer firmwares ExtendedFirmwareFeatures (64-bit) is used. On older FirmwareFeatures (32-bit) is used. For compatibility reasons newer firmwares (and OpenCore) expose both variables.

**Comment by dakanji** [comment]
> I believe you misunderstand how it works

Indeed. My question was actually purely about the name but your response, which initially totally confused me, made me look deeper including in the Apple Database Files and I can now see that renaming as I had thought is not appropriate. It was however based on the impression given by the docs and you might want to take another look at the documentation for the FirmwareFeatures and FirmwareFeaturesMask items which are very very opaque.
