### ISSUE TITLE
Showing Auxiliaries Triggers Halt on Critical Error

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1345]
Build of WIP v0.6.4 codebase results in a "Halt on Critical Error" when attempting to show auxiliaries.
- Selecting a boatloader directly without trying to show auxiliaries works fine.
- OC Instance is in a custom folder "EFI\OC_DEV" 
- Log: [opencore-crash.txt](https://github.com/acidanthera/bugtracker/files/5622416/opencore-crash.txt)
- The efi seems to be trying to link to my local system at the crash point

**Comment by vit9696** [comment]
Could you trace the line location with debug prints? It asserts when calling FreePool I believe inside `RunShowMenu` or even `OcShowSimpleBootMenu` (called via `BootContext→PickerContext->ShowMenu`).

**Comment by dakanji** [comment]
Crashes on `FreePool (BootEntries);` in `Library/OcBootManagementLib/OcBootManagementLib.c`

[opencore-crash-01.zip](https://github.com/acidanthera/bugtracker/files/5624050/opencore-crash-01.zip)

**Comment by vit9696** [comment]
Hmmm, I think it cannot be, because `BootEntries = OcEnumerateEntries (BootContext);` always allocates from pool, and it is checked for NULL right afterwards. I would rather expect `RunShowMenu` to terminate and it die much later. Do you manage to choose a boot entry?

**Comment by dakanji** [comment]
OK. Will add more flags

**Comment by dakanji** [comment]
Apologies ... The issue was due to a flaw in my build script.

**Comment by vit9696** [comment]
Good to hear. By the way, modern OpenCore supports starting from any directory.
