### ISSUE TITLE
[Boot process] Ignoring kextcache invocation from early boot

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1346]
Hi there,
I don't even know if this can be considered as an issue, but I've noticed that while booting macOS Big Sur 11.0.1 (20B29) on my Dell Inspiron 5370 with OpenCore 0.6.3 and latest kexts ([EFI](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/)), the boot process hangs itself for circa 5 seconds on the string `Ignoring kextcache invocation from early boot`. I don't care too much about boot-times since 20 seconds is a reasonable time, but wanted to elaborate on that """bug""". Do you have any idea? 
Thank you so much and have a nice day ^^

**Comment by telepati** [comment]
I have that too. Mine taking 10 sec. But, I am not sure this is related to OC. 
ASUS TUF Z390, 9900K, ASUS RX 560
OC 0.6.4, macOS Big Sur 11.1

**Comment by zhen-zen** [comment]
Have the same issue with a partition from beta 1 to 10. After that I did a clean install for the release and it disappears. Are yours upgraded from beta as well?

**Comment by dreamwhite** [comment]
> Have the same issue with a partition from beta 1 to 10. After that I did a clean install for the release and it disappears. Are yours upgraded from beta as well?

I've dirty upgraded from Catalina 10.15.7 (19H2) to Big Sur 11.0.1 (20B25)

**Comment by nikhil19rathore99** [comment]
> I have that too. Mine taking 10 sec. But, I am not sure this is related to OC.
> ASUS TUF Z390, 9900K, ASUS RX 560
> OC 0.6.4, macOS Big Sur 11.1

I think u haven't enable trim thats why it takes 10 sec otherwise it takes 20+ sec

**Comment by telepati** [comment]
> > I have that too. Mine taking 10 sec. But, I am not sure this is related to OC.
> > ASUS TUF Z390, 9900K, ASUS RX 560
> > OC 0.6.4, macOS Big Sur 11.1
> 
> I think u haven't enable trim thats why it takes 10 sec otherwise it takes 20+ sec

TRIM is auto-enable on NVME. You don't need an extra step for TRIM on Catalina and Big Sur. But this problem is not related to TRIM.

**Comment by dreamwhite** [comment]
> I think u haven't enable trim thats why it takes 10 sec otherwise it takes 20+ sec

I don't think that TRIM is the cause of that issue, since NVMe, as @telepati said have TRIM enabled OOB.
Below my System Report infos about NVMe drives attached on my laptop ._. 

![image](https://user-images.githubusercontent.com/17933708/101243025-af439600-36fd-11eb-8b7c-f245c6a25f0d.png)

**Comment by telepati** [comment]
Could this problem be due to different APFS driver values and required values?

<img width="1000" alt="Screen Shot 2020-12-06 at 19 36 49" src="https://user-images.githubusercontent.com/3812286/101288296-e3ef4480-3806-11eb-909e-95baf3be5c83.png">

**Comment by dreamwhite** [comment]
> Could this problem be due to different APFS driver values and required values?
> 
> <img alt="Screen Shot 2020-12-06 at 19 36 49" width="1000" src="https://user-images.githubusercontent.com/3812286/101288296-e3ef4480-3806-11eb-909e-95baf3be5c83.png">

I don't think so. If you look at the highlighted string it says:

`Found APFS driver vXXXXXXX/20201123`

2020-11-23 is the release date of the driver you're using.
If we have to apply that logic, then the string after `required 11111111111111/` can be interpreted as "the minimum version of apfs.efi driver is the one release on 2018-06-21. That condition is true so allow the boot, else fail"

**Comment by seungjunProgramming** [comment]
Me too.
I'm not using nvme, so I think it's not 'cause nvme drives.
I'm having this problem with m.2 sata3 ssd

**Comment by dreamwhite** [comment]
# Update

After upgrading to OpenCore 0.6.4 (as well as the kexts) I'm still experiencing a break of a few seconds on the string `Ignoring kextcache invocation from early boot. 

However, compared to OpenCore 0.6.3, the interruption takes a few seconds less

**Comment by seungjunProgramming** [comment]
> # Update
> After upgrading to OpenCore 0.6.4 (as well as the kexts) I'm still experiencing a break of a few seconds on the string `Ignoring kextcache invocation from early boot.
> 
> However, compared to OpenCore 0.6.3, the interruption takes a few seconds less

Me too.
It takes less time than 0.6.3

**Comment by seungjunProgramming** [comment]
> # Update
> After upgrading to OpenCore 0.6.4 (as well as the kexts) I'm still experiencing a break of a few seconds on the string `Ignoring kextcache invocation from early boot.
> 
> However, compared to OpenCore 0.6.3, the interruption takes a few seconds less

However, still taking about 5~10secs

**Comment by telepati** [comment]
> I'm not using nvme, so I think it's not 'cause nvme drives.

I am using NVME and I still have this issue. It takes about 10/15 sec. But this issue not related to Hard Drive (SSD or NVME).

**Comment by vit9696** [comment]
The issue looks like a bug on Apple side. Please report to Apple.

**Comment by telepati** [comment]
Setting "SetApfsTrimTimeout" to 999 disables this problem and shortens the boot time.

**Comment by dreamwhite** [comment]
> Setting "SetApfsTrimTimeout" to 999 disables this problem and shortens the boot time.

Sorry for the late reply: I tried this trick but nothing changed. The boot process still hangs for a few seconds before proceeding.
Again, I don't care much about this but just wanted to get why it hangs

**Comment by McDonnellTech** [comment]
> Setting "SetApfsTrimTimeout" to 999 disables this problem and shortens the boot time.

This solution did the trick for me. No longer any hang at all at "Ignoring kextcache invocation from early boot"

**Comment by YaPaY** [comment]
> Setting "SetApfsTrimTimeout" to 999 disables this problem and shortens the boot time.

nothing changes by me

**Comment by dreamwhite** [comment]
> > Setting "SetApfsTrimTimeout" to 999 disables this problem and shortens the boot time.
> 
> nothing changes by me

Neither do I. I simply swapped the NVMe from a Sabrent Rocket NVMe to a Western Digital Black SN750 and the boot-process is definitely faster, despite still hanging for a few seconds on `Ignoring kextcache invocation from early boot`

**Comment by 1alessandro1** [comment]
I think all of this is TRIM related. Setting 999 on SetApfsTrimTimeout disables TRIM since it's a very short timeout, so the SSD can behave differently (hanging or not hanging) due to the supported/unsupported nature in IONVMeFamily....

Before making any future purchase, I recommend everybody to check [this post](https://github.com/dortania/bugtracker/issues/192)
