### ISSUE TITLE
[MAT Support] Clarifications

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1348]
Hi there,
first of all this isn't properly an issue, but a clarification about issue #491.
After reading it, I decided to make some experiments in order to get my Dell Inspiron 5370 boot with `SyncRuntimePermissions`, `RebuildAppleMemoryMap` enabled and `EnableWriteUnprotector` disabled, since `MAT Support` status is `1`. Below the generated log from OpenCore 0.6.3 DBG

[opencore-2020-11-03-033054.txt](https://github.com/acidanthera/bugtracker/files/5643341/opencore-2020-11-03-033054.txt)

I couldn't pass "pre-verbose" phase and I was stucked on `[EB|#LOG:EXITBS:START]`.
After investigating, I finally managed to get it working by enabling `DevirtualiseMmio` and adding in `MmioWhitelist` a region which was causing those issues.

I extracted the region by editing `config.plist` as explained in @dortania 's [guide](https://dortania.github.io/OpenCore-Install-Guide/extras/kaslr-fix.html#using-devirtualisemmio)

Hope that this can be useful for those who are experiencing some weird issues with the quirks mentioned above (e.g. on Asus ROG Strix Z270-F, `MAT Support` is `1` but if you enable the quirks and try to boot macOS, the PC shuts down ._.)

Many thanks for your contribute in hackintosh community and have a nice day ^^

**Comment by Andrey1970AppleLife** [comment]
Your message for forums.
