### ISSUE TITLE
Update OpenCanopy iCNS at BootPicker BigSur

### ISSUE THREAD

**Issue by singhalrishi27** [acidanthera/bugtracker#1351]
I was able to Update disk icon within binary Resources but i was unable to find any other icon like recovery...

Please Refresh BootPicker icns in Binary Resources....

**Comment by vit9696** [comment]
The icons are up to date. We do not include icons that look the same.

**Comment by singhalrishi27** [comment]
But it shows old catalina drive icons and recovery icon

**Comment by vit9696** [comment]
Due to .VolumeIcon.icns. Read the docs.

**Comment by singhalrishi27** [comment]
@vit9696 
![Uploading Screenshot_20201206-
![Uploading Screenshot_20201206-090807_YouTube_Vanced~2.png…]()
090756_YouTube_Vanced~2.png…]()
Look at this

**Comment by singhalrishi27** [comment]
@vit9696 
![Screenshot_20201206-090756_YouTube_Vanced~2](https://user-images.githubusercontent.com/67616808/101270872-7e1da100-37a3-11eb-9ca8-9645b2a717d3.png)
![Screenshot_20201206-090807_YouTube_Vanced~2](https://user-images.githubusercontent.com/67616808/101270874-81189180-37a3-11eb-84ad-ed718ff0d942.png)

**Comment by Andrey1970AppleLife** [comment]
Icons RecoveryHD doesn't exist in real Mac.
In a firmware real Mac icons of a ApplePiker didn't change, it doesn't depend on the version macOS. Look firmware iMac20,1
Icons are given as an example. You can independently create any.

**Comment by Andrey1970AppleLife** [comment]
https://www.insanelymac.com/forum/topic/344251-opencanopy-icons/?do=findComment&comment=2729742

**Comment by vit9696** [comment]
Should eventually merge it with https://github.com/khronokernel/OpenCanopy-Big-Sur and put to the gallery on dortania.github.io along with the other themes. CC @dhinakg @khronokernel

**Comment by Andrey1970AppleLife** [comment]
> Should eventually merge it with https://github.com/khronokernel/OpenCanopy-Big-Sur and put to the gallery on dortania.github.io along with the other themes. CC @dhinakg @khronokernel

1. There it is badly made Ext TM icon, Clock shall be white.
2. Recovery icons not from M1.
3. Tools icon isn't updated
4. Name of a repository not correctly, shall be OpenCanopy-Apple Silicon.
5. Pictures aren't optimized.

**Comment by singhalrishi27** [comment]
> 4\. repository

if you guys will be updating icons with Big Sur version please reopen issue
