### ISSUE TITLE
Kernel panic caused by SMCDellSensors.kext

### ISSUE THREAD

**Issue by lisai9093** [acidanthera/bugtracker#1353]
My system is Dell XPS 8930 with opencore 0.6.4, macOS Big Sur released 11.0.1. I have kernel panic due to SMCDellSensors since 1.1.8 or 1.1.7 I think. I was hoping 1.1.9 could solve it but still get the same result.
Here is kernel panic report:
`panic(cpu 4 caller 0xffffff8002defa76): Kernel trap at 0xffffff80069b9794, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffff800621c100, CR3: 0x0000000007c20000, CR4: 0x00000000003626e0
RAX: 0x0000000000000051, RBX: 0x0000000000000000, RCX: 0xffffff937b156f40, RDX: 0xffffffc10664bb70
RSP: 0xffffffc10664ba60, RBP: 0xffffffc10664baa0, RSI: 0xffffff8006a8c64d, RDI: 0xffffff8006a8c64d
R8: 0x00000000000006fa, R9: 0x0000000000027000, R10: 0x0000000000000001, R11: 0x0000000000000000
R12: 0xffffff800621c110, R13: 0xffffff937b156f40, R14: 0xffffff800693cca3, R15: 0xffffff800638f9c8
RFL: 0x0000000000010206, RIP: 0xffffff80069b9794, CS: 0x0000000000000008, SS: 0x0000000000000010
Fault CR2: 0xffffff800621c100, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 0, VF: 2

Backtrace (CPU 4), Frame : Return Address
0xffffffc10664b480 : 0xffffff8002cbc66d
0xffffffc10664b4d0 : 0xffffff8002dff073
0xffffffc10664b510 : 0xffffff8002def6aa
0xffffffc10664b560 : 0xffffff8002c61a2f
0xffffffc10664b580 : 0xffffff8002cbbf0d
0xffffffc10664b6a0 : 0xffffff8002cbc1f8
0xffffffc10664b710 : 0xffffff80034bee1a
0xffffffc10664b780 : 0xffffff8002defa76
0xffffffc10664b900 : 0xffffff8002def75d
0xffffffc10664b950 : 0xffffff8002c61a2f
0xffffffc10664b970 : 0xffffff80069b9794
0xffffffc10664baa0 : 0xffffff80069a897a
0xffffffc10664bb10 : 0xffffff80069a885e
0xffffffc10664bb40 : 0xffffff8006a888ee
0xffffffc10664bc40 : 0xffffff80069af2bd
0xffffffc10664bc80 : 0xffffff80069a6e8f
0xffffffc10664bce0 : 0xffffff80033847c2
0xffffffc10664bd40 : 0xffffff80033843ff
0xffffffc10664bda0 : 0xffffff80033989dd
0xffffffc10664bdf0 : 0xffffff800340eebe
0xffffffc10664be40 : 0xffffff80033ee39b
0xffffffc10664bef0 : 0xffffff80033eddcf
0xffffffc10664bf50 : 0xffffff80033f0b46
0xffffffc10664bfa0 : 0xffffff8002c6113e
Kernel Extensions in backtrace:
as.vit9696.Lilu(1.5)[EC77F3DD-6CAD-3A51-9C5F-A5424F852100]@0xffffff80069a5000->0xffffff80069cefff
as.lvs1974.SMCDellSensors(1.1.9)[F75F296C-6819-39B0-9370-428A398E9155]@0xffffff8006a88000->0xffffff8006a93fff
dependency: as.vit9696.Lilu(1.5.0)[EC77F3DD-6CAD-3A51-9C5F-A5424F852100]@0xffffff80069a5000->0xffffff80069cefff
dependency: as.vit9696.VirtualSMC(1.1.9)[A05D183D-9D34-31C8-8D55-8FE54DCE6C44]@0xffffff80069d1000->0xffffff80069e7fff

Process name corresponding to current thread: kernel_task
Boot args: shikigva=16 brcmfx-country=#a chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20B29

Kernel version:
Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
Kernel UUID: 84C6DC45-6B02-335F-9439-5D2A9BC385A4
KernelCache slide: 0x0000000002a00000
KernelCache base: 0xffffff8002c00000
Kernel slide: 0x0000000002a10000
Kernel text base: 0xffffff8002c10000
__HIB text base: 0xffffff8002b00000
System model name: iMac19,1 (Mac-AA95B1DDAB278B95)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 21628082382
Last Sleep: absolute base_tsc base_nano
Uptime : 0x0000000509225c93
Sleep : 0x0000000000000000 0x0000000000000000 0x0000000000000000
Wake : 0x0000000000000000 0x000000090a0af4be 0x0000000000000000
`

I tried generating debug log with opencore. The interesting thing is, there is no more kernel panic when I add "keepsyms=1" boot-arg. So I only use "debug=0x100", target set to 67, AppleDebug and ApplePanic set to true. Here is the log file:
[opencore-2020-12-07-191345.txt](https://github.com/acidanthera/bugtracker/files/5654797/opencore-2020-12-07-191345.txt)
*I don't get anything beyond #[EB|LOG:EXITBS:START], is it normal?

If I enable verbose mode with command+v, I got stucked here:
![1](https://user-images.githubusercontent.com/3047171/101395888-c910e480-3887-11eb-98e5-b3e33a7e1e39.jpg)

Without entering verbose mode, the system just restart.

**Comment by vit9696** [comment]
First of all, it is not a good idea to wait for a release hoping it will fix your issue. If the issue exists and it is not getting to be fixed, it means you are the only one with it. Report as early as possible. We will need the panic with `keepsyms=1` in boot-args.

**Comment by lisai9093** [comment]
> First of all, it is not a good idea to wait for a release hoping it will fix your issue. If the issue exists and it is not getting to be fixed, it means you are the only one with it. Report as early as possible. We will need the panic with `keepsyms=1` in boot-args.

But if I add `keepsyms=1`, I could not get kernel panic at all. Once I remove it without changing anything else, the kernel panic is back..... Maybe I will just live with keepsyms=1 from now on....

**Comment by vit9696** [comment]
You have `DisableLinkeditJettison` disabled, but it is required for Lilu functioning on 11.x. Symbolicated panic kpdescribe:

```
panic(cpu 4 caller 0xffffff8002defa76): Kernel trap at 0xffffff80069b9794, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffff800621c100, CR3: 0x0000000007c20000, CR4: 0x00000000003626e0
RAX: 0x0000000000000051, RBX: 0x0000000000000000, RCX: 0xffffff937b156f40, RDX: 0xffffffc10664bb70
RSP: 0xffffffc10664ba60, RBP: 0xffffffc10664baa0, RSI: 0xffffff8006a8c64d, RDI: 0xffffff8006a8c64d
R8: 0x00000000000006fa, R9: 0x0000000000027000, R10: 0x0000000000000001, R11: 0x0000000000000000
R12: 0xffffff800621c110, R13: 0xffffff937b156f40, R14: 0xffffff800693cca3, R15: 0xffffff800638f9c8
RFL: 0x0000000000010206, RIP: 0xffffff80069b9794, CS: 0x0000000000000008, SS: 0x0000000000000010
Fault CR2: 0xffffff800621c100, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 0, VF: 2

Slide: 0x0000000002a10000
Backtrace [addr unslid symbol]:
0xffffff8002cbc66d  0xffffff80002ac66d  handle_debugger_trap (in kernel) + 989
0xffffff8002dff073  0xffffff80003ef073  kdp_i386_trap (in kernel) + 323
0xffffff8002def6aa  0xffffff80003df6aa  kernel_trap (in kernel) + 1370
0xffffff8002c61a2f  0xffffff8000251a2f  0xffffff8000251a2f (in kernel) + 38
0xffffff8002cbbf0d  0xffffff80002abf0d  DebuggerTrapWithState (in kernel) + 173
0xffffff8002cbc1f8  0xffffff80002ac1f8  panic_trap_to_debugger (in kernel) + 616
0xffffff80034bee1a  0xffffff8000aaee1a  panic (in kernel) + 84
0xffffff8002defa76  0xffffff80003dfa76  0xffffff80003dfa76 (in kernel) + 502
0xffffff8002def75d  0xffffff80003df75d  kernel_trap (in kernel) + 1549
0xffffff8002c61a2f  0xffffff8000251a2f  0xffffff8000251a2f (in kernel) + 38
0xffffff80069b9794  0x0000000000014794  MachInfo::solveSymbol(char const*) (in Lilu) (kern_mach.cpp:330)
0xffffff80069a897a  0x000000000000397a  KernelPatcher::routeMultipleInternal(unsigned long, KernelPatcher::RouteRequest*, unsigned long, unsigned long long, unsigned long, bool, bool, KernelPatcher::JumpType) (in Lilu) (kern_patcher.cpp:582)
0xffffff80069a885e  0x000000000000385e  KernelPatcher::routeMultiple(unsigned long, KernelPatcher::RouteRequest*, unsigned long, unsigned long long, unsigned long, bool, bool) (in Lilu) (kern_patcher.cpp:561)
0xffffff8006a888ee  0xffffff80040788ee  0xffffff8006a888ee
0xffffff80069af2bd  0x000000000000a2bd  LiluAPI::processPatcherLoadCallbacks(KernelPatcher&)::$_0::__invoke(KernelPatcher::KextHandler*) (in Lilu) (kern_api.cpp:307)
0xffffff80069a6e8f  0x0000000000001e8f  KernelPatcher::onKextSummariesUpdated() (in Lilu) (kern_patcher.cpp:741)
0xffffff80033847c2  0xffffff80009747c2  OSKext::load(unsigned char, unsigned char, OSArray*) (in kernel) + 1890
0xffffff80033843ff  0xffffff80009743ff  OSKext::load(unsigned char, unsigned char, OSArray*) (in kernel) + 927
0xffffff80033989dd  0xffffff80009889dd  OSKext::loadKextWithIdentifier(OSString*, OSObject**, bool, bool, unsigned char, unsigned char, OSArray*) (in kernel) + 429
0xffffff800340eebe  0xffffff80009feebe  IOCatalogue::isModuleLoaded(OSDictionary*, OSObject**) const (in kernel) + 238
0xffffff80033ee39b  0xffffff80009de39b  IOService::probeCandidates(OSOrderedSet*) (in kernel) + 1083
0xffffff80033eddcf  0xffffff80009dddcf  IOService::doServiceMatch(unsigned int) (in kernel) + 783
0xffffff80033f0b46  0xffffff80009e0b46  _IOConfigThread::main(void*, int) (in kernel) + 390
0xffffff8002c6113e  0xffffff800025113e  call_continuation (in kernel) + 46

**Comment by lisai9093** [comment]
Thanks it works now!
