### ISSUE TITLE
Random crash related WEG, OC or not?

### ISSUE THREAD

**Issue by telepati** [acidanthera/bugtracker#1356]
After the latest update OC, I starting to get random crashes. What happening when a crash happens. I am losing screen, no cursor or anything, I am seeing just random block color (grey, blue, pink, green, light blue, lately just grey), but my case, fans everything working but no screen. I tried to remove the display cable and put it again, also power off the display and open again didn't make any difference. Just one thing works Force Restart. But when this happens doesn't give a crash report each time. If this is not related to WEG or OC please ignore and closed the issue report. Here is the crash report;

ASUS TUF Z390, 9900K, RX560

`panic(cpu 6 caller 0xffffff800d96da25): userspace watchdog timeout: no successful checkins from com.apple.WindowServer in 120 seconds
service: com.apple.logd, total successful checkins since load (4510 seconds ago): 452, last successful checkin: 0 seconds ago
service: com.apple.WindowServer, total successful checkins since load (4480 seconds ago): 436, last successful checkin: 120 seconds ago

Backtrace (CPU 6), Frame : Return Address
0xffffffc1aaa83670 : 0xffffff800a6b9aed mach_kernel : _handle_debugger_trap + 0x3dd
0xffffffc1aaa836c0 : 0xffffff800a7fc6e3 mach_kernel : _kdp_i386_trap + 0x143
0xffffffc1aaa83700 : 0xffffff800a7ecd1a mach_kernel : _kernel_trap + 0x55a
0xffffffc1aaa83750 : 0xffffff800a65ea2f mach_kernel : _return_from_trap + 0xff
0xffffffc1aaa83770 : 0xffffff800a6b938d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffc1aaa83890 : 0xffffff800a6b9678 mach_kernel : _panic_trap_to_debugger + 0x268
0xffffffc1aaa83900 : 0xffffff800aebe434 mach_kernel : _panic_with_thread_context
0xffffffc1aaa83970 : 0xffffff800d96da25 com.apple.driver.watchdog : __ZN10IOWatchdog14userspacePanicEP8OSObjectPvP25IOExternalMethodArguments.cold.1 + 0x27
0xffffffc1aaa83980 : 0xffffff800d96d678 com.apple.driver.watchdog : __ZN10IOWatchdog35userspaceDisableUserspaceMonitoringEP8OSObjectPvP25IOExternalMethodArguments
0xffffffc1aaa839a0 : 0xffffff800ae4569e mach_kernel : __ZN12IOUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x1de
0xffffffc1aaa839f0 : 0xffffff800d96cab4 com.apple.driver.watchdog : __ZN20IOWatchdogUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x7c
0xffffffc1aaa83b20 : 0xffffff800ae4f86b mach_kernel : _is_io_connect_method + 0x35b
0xffffffc1aaa83c80 : 0xffffff800a7a7d81 mach_kernel : _iokit_server_routine + 0x4d81
0xffffffc1aaa83d90 : 0xffffff800a6bf0e7 mach_kernel : _ipc_kobject_server + 0x337
0xffffffc1aaa83e00 : 0xffffff800a695905 mach_kernel : _ipc_kmsg_send + 0x115
0xffffffc1aaa83e60 : 0xffffff800a6ad012 mach_kernel : _mach_msg_overwrite_trap + 0x2d2
0xffffffc1aaa83ef0 : 0xffffff800a7d0ec3 mach_kernel : _mach_call_munger64 + 0x273
0xffffffc1aaa83fa0 : 0xffffff800a65f216 mach_kernel : _hndl_mach_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[C1A64FD7-AD16-37E0-8FA1-A78A8E91D9FF]@0xffffff800d96c000->0xffffff800d96dfff

Process name corresponding to current thread: watchdogd
Boot args: keepsyms=1 debug=0x100 -raddvi -rad4200

Mac OS version:
20C5061b

Kernel version:
Darwin Kernel Version 20.2.0: Mon Nov 23 05:24:51 PST 2020; root:xnu-7195.60.74~7/RELEASE_X86_64
Kernel UUID: 1DCC1F01-821E-36A7-BAED-6B8548ECD80E
KernelCache slide: 0x000000000a400000
KernelCache base:  0xffffff800a600000
Kernel slide:      0x000000000a410000
Kernel text base:  0xffffff800a610000
__HIB  text base: 0xffffff800a500000
System model name: iMac19,1 (Mac-AA95B1DDAB278B95)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 4528658183420
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000041e690ff91d
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000b389bb8ee 0x0000000000000000`

**Comment by vit9696** [comment]
Not really possible to say what exactly it is, but it seems that your videodrivers hung. It does not look like a WEG issue.
