### ISSUE TITLE
Update from 0.6.3 to 0.6.4 results in OC being unable to load configuration file

### ISSUE THREAD

**Issue by bakedpotato191** [acidanthera/bugtracker#1357]
After updating OC from 0.6.3 to 0.6.4 it is unable to find config.plist on boot. 
The exact error is: "OC: Failed to load configuration"
Is reproducible on both Release and Debug versions. 
No such issue when downgrading back to 0.6.3.
Note: This only happens when booting from SSD EFI, not when booting from USB.

**Comment by nms42** [comment]
Subject of this issue says -- unable to find, while text -- failed to load.

So, file was found but with incorrect format, I presume. Validate it with Utilities/ocvalidate from 0.6.4 version.

**Comment by bakedpotato191** [comment]
> 
> 
> Subject of this issue says -- unable to find, while text -- failed to load.
> 
> So, file was found but with incorrect format, I presume. Validate it with Utilities/ocvalidate from 0.6.4 version.

Config file passes validation without any errors. Once again, there is no issue loading the same config file on OC 0.6.3 and older.

**Comment by hwhh** [comment]
+1 also seeing the "OC: Failed to load configuration" error, and have checked the config is valid using the `ocvalidate` tool.

**Comment by dreamwhite** [comment]
> +1 also seeing the "OC: Failed to load configuration" error, and have checked the config is valid using the `ocvalidate` tool. 

I had the same issue. Please double check that BOOTx64.efi, Opencore.efi, bootstrap.efi and the drivers are updated to 0.6.4

**Comment by hwhh** [comment]
Ah for me I didn't change the `bootstrap. efi`. Sorry was following the instruction [Replace the OpenCore files with the ones you just downloaded](https://dortania.github.io/OpenCore-Post-Install/universal/update.html#_3-replace-the-opencore-files-with-the-ones-you-just-downloaded). @dreamwhite thank you!

![Uploading image.png…]()

**Comment by bakedpotato191** [comment]
I am confident that I've replaced all files listed above. As I said before, That does not happen when I boot from USB.

**Comment by bakedpotato191** [comment]
UPD: I was using GRUB's chainloader to boot OC, it was pointing to OpenCore.efi, but now that I changed it to BOOTx64.efi, the issue is no longer there.

**Comment by mishurov** [comment]
@bakedpotato191 thank you very much, you are a saviour. I, too, had been chainloading OpenCore.efi directly from GRUB, it worked well until 0.6.4. I have debian and OC directories in EFI, I just put BOOTx64.efi into the OC directory, so as to don't create a useless BOOT directory in the root, and pointed the entry to /EFI/OC/BOOTx64.efi, works charmingly.
