### ISSUE TITLE
Scrambled screen on Catalina/Big Sur installer only, on Zen and Navi

### ISSUE THREAD

**Issue by Litarvan** [acidanthera/bugtracker#1358]
On both Big Sur and Catalina installer, during graphical startup (after gIOLockScreen thing) instead of graphics actually showing up, I get a completely scrambled screen:

![Big Sur installation crash](https://cdn.discordapp.com/attachments/447725868140331019/786339249103568946/unknown.png)

On the top, we can see the debug logs that were printed before the """crash""" happening, duplicated three times. Last lines are the gIOLockScreen line, followed by the CS_RUNTIME thing line if on Big Sur, which afaik are the last things displayed before graphics startup.

On the green area (which is sometimes black), text can be noticed on the back (we can see it clearly on the right). This text is actually what my screen last displayed **on the last boot** (in the screenshot above, it's the systemd shutdown logs of my Linux setup). The thing is, I completely powered off my computer after that before booting macOS, so I don't know how it has been "memorized" somehow but it did.
At the center, we can also see part of the installer window being displayed at the right place, and sometimes (not on this screenshot but still) I can see parts of the menu bar, and I can even click on menus (because as you can see on the screenshot my mouse is displayed and working) and it will show them but only a very small part of them (like with the installer window). 

This only happens in the installer, by booting on my old Big Sur installation using the same EFI (from the same device) on the same computer, everything works. The only difference being the drive : a hard drive for the working installation, my USB-C 3.1 Gen 1 Key for the installer (the key which have my EFI and on which I boot on in both cases). If I was able to get a working installation, It's because I made it on my old computer with an Intel CPU and ofc a different motherboard and different RAM, but I kept my drives and my graphical card.

My setup is:
| Part | Model |
| --- | --- |
| **Motherboard** | Gigabyte B550M AORUS PRO-P Micro ATX AM4 Motherboard |
| **CPU**| AMD Ryzen 7 3800X 3.9 GHz 8-Core Processor |
|  **Video Card** | Sapphire Radeon RX 5600 XT 6 GB PULSE Video Card |
| **Memory** | Crucial Ballistix 16 GB (2 x 8 GB) DDR4-3600 CL16 Memory (XMP enabled) |
| **Storage** | Gigabyte AORUS Gen4 1 TB M.2-2280 NVME Solid State Drive |
| **Storage** | Crucial P2 1 TB M.2-2280 NVME Solid State Drive |
| **Monitor** | Samsung U28E590D 28.0" 3840x2160 60 Hz Monitor |

(I tested plugging in the monitor with either DisplayPort or HDMI, nothing changed).

Note that, my setup was affected by the #1297 issue. After switching to AMD CPU, I'm not affected anymore, probably because I disabled the Serial Port (which is required for an AMD CPU setup), which is apparently a workaround for this bug. But still I mention it, because it looks related: happens at the same time, graphical issue too, **and there doesn't seem to be a difference whether WhateverGreen is enabled or not (exact same issue)**.

Attached you'll find my EFI folder that I used both for booting the Catalina and Big Sur installer (encountering the issue), but also my working Big Sur installation (without issue). There's also the OpenCore debug logs. But I can't get more since it only happens on the installer and I can't really get a user interface.

I thought I had to open an issue because I feel it could be a problem with WhateverGreen (but I hope it comes from what I've did instead).

EFI folder: [EFI.zip](https://github.com/acidanthera/bugtracker/files/5668802/EFI.zip)
OpenCore debug logs: [opencore-2020-12-09-205940.txt](https://github.com/acidanthera/bugtracker/files/5668803/opencore-2020-12-09-205940.txt)

**Comment by Andrey1970AppleLife** [comment]
We don't support AMD CPU.
Use forums for support.
