### ISSUE TITLE
[BlacklistAppleUpdate + run-efi-updater] Clarifications

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1359]
Dear all,
I was wondering why OpenCore 0.6.4 has both `BlacklistAppleUpdate` and `run-efi-updater`.
According to Configuration.pdf 0.6.4:

> This option exists due to some operating systems, namely macOS Big Sur, being incapable of disabling firmware updates with the NVRAM variable (run-efi-updater).

Wouldn't it be better to integrate `run-efi-updater` into a single quirk (in this case `BlacklistAppleUpdate`) and consequently remove the variable from `NVRAM/Add/7C436110-AB2A-4BBB-A880-FE41995C9F82`?
Many thanks and have a nice day ^_^

**Comment by vit9696** [comment]
`run-efi-updater` handling is currently unsupported in Big Sur, and neither we want to write to NVRAM from the UEFI quirk, nor we want to make it mandatory since it is not supported anyway (and possibly will never be in future versions).
