### ISSUE TITLE
AppleALC 1.5.5 causes boot to be stuck

### ISSUE THREAD

**Issue by osy** [acidanthera/bugtracker#1360]
This is a bizarre issue people have reported to me that I’m forwarding along. I personally have not run into this issue but some of the users of HaC Mini reported that boot freezes at PCI configuration after updating from the 11.2020 to 12.2020 acidanthera KEXTs. After some debugging it seems like AppleALC is the culprit. It’s possible that it somehow affects boot from NVMe although I’m only speculating here because I don’t have an NVMe (and don’t have this issue) but people who are running into this do have NVMe.

https://github.com/osy/HaC-Mini/issues/461#issuecomment-742503687

**Comment by vit9696** [comment]
Could you try serial logging?

**Comment by keatliang2005** [comment]
> Could you try serial logging?

how to do that ?

**Comment by vit9696** [comment]
The algorithm is described in OpenCore pdf.

**Comment by keatliang2005** [comment]
After lot's of gotcha i finally got something for logging, i hope this is what you looking for

[opencore-2020-12-11-150220.txt](https://github.com/acidanthera/bugtracker/files/5679917/opencore-2020-12-11-150220.txt)

**Comment by vit9696** [comment]
No, I mean kernel serial logging via UART.

**Comment by vit9696** [comment]
If this is difficult for you, please at least try to provide the exact commit it broke for you:
https://dortania.github.io/builds/?product=AppleALC&viewall=true

**Comment by keatliang2005** [comment]
> If this is difficult for you, please at least try to provide the exact commit it broke for you:
> https://dortania.github.io/builds/?product=AppleALC&viewall=true

after multiple try on boot with each build incrementally 

this build https://github.com/acidanthera/AppleALC/commit/3708e1ceabe590a8ea7a13f8d0447cbaaadecb49
stalled and not proceed further

this build https://github.com/acidanthera/AppleALC/commit/12430d5de049736894b16adbac872c199fc610b9
was able to boot normally

all tested under RELEASE build 

as @goodbest predicted 3708e1c commit breaks on my machine.

**Comment by vit9696** [comment]
Quite strange, are you sure this is not a kernel panic but a stall? If you have debug=0x100 (or anything else, let me know) in your boot arguments, what does happen if you remove it?

**Comment by vit9696** [comment]
@osy this does not look like an issue on our end. However, what I can suspect is some misconfigured HDA/GPU device. Do you disable any GPU or HDA device in your configuration in kernelspace?

**Comment by vit9696** [comment]
Just in case, I moved the availability checks to ::probe to match Apple guidelines in:
```
[master f73b904] Move alc-verb availability check to probe
 3 files changed, 16 insertions(+), 12 deletions(-)
```

**Comment by keatliang2005** [comment]
here the boot arguments

```
alcid=11 agdpmod=ignore -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 igfxmetal=1 -v
```

Here's the ACPI
https://github.com/osy/HaC-Mini/tree/master/ACPI

MY EFI
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5684836/EFI.zip)

**Comment by keatliang2005** [comment]
Tried the latest one still stuck at this page 

![IMG_20201213_234816.jpg](https://user-images.githubusercontent.com/473990/102016901-5a0f2080-3d9e-11eb-8cb0-ac487da40395.jpg)

**Comment by vit9696** [comment]
Hmmm, I can give you a couple of test builds, will you try?

**Comment by vit9696** [comment]
Your OpenCore configuration is broken, and your kernel quirks do not make sense to me. For example, DisableLinkeditJettison must be enabled in Big Sur. I get dozens of warnings when I execute `ocvalidate config.plist`.

<img width="642" alt="Снимок экрана 2020-12-13 в 19 05 52" src="https://user-images.githubusercontent.com/4348897/102017156-39cb6b80-3d76-11eb-83aa-b4294f56f59f.png">

**Comment by keatliang2005** [comment]
Sure I can try those and see what happens

**Comment by keatliang2005** [comment]
Like this ?
![Screenshot 2020-12-14 at 12 28 17 AM](https://user-images.githubusercontent.com/473990/102017676-4914de00-3da3-11eb-8b5d-b4292efbcfb8.png)

**Comment by vit9696** [comment]
Well, this is a thing that should definitely be there, but I cannot tell you whether this is enough. The configuration violates OpenCore requirements specified in Configuration.pdf. CC @osy

**Comment by keatliang2005** [comment]
I will look into the missing keys, then I will observe. 

Thanks, I was not aware of the utility ocvalidate before

**Comment by osy** [comment]
@keatliang2005 let’s take the conversation to https://github.com/osy/HaC-Mini/issues/461

**Comment by greenish-guy-tech-1-h33aha-777555378477** [comment]
@osy b!g π𝓖ƛ
