### ISSUE TITLE
CPUFriend: ResourceConverter.sh Usage printout incorrect

### ISSUE THREAD

**Issue by MacNB** [acidanthera/bugtracker#1361]
Currently it shows :
...
	echo "-a, --acpi file Create ${kextName} with information provided by file."
	echo "-k, --kext file Create ${ssdtName} with information provided by file."
...

It should be:

...
	echo "-a, --acpi file Create ${ssdtName} with information provided by file."
	echo "-k, --kext file Create ${kextName} with information provided by file."
...

that is, **kextName** and **ssdtName** should be swapped.

The error does not affect the functionality .... just cosmetic

**Comment by PMheart** [comment]
Thanks for pointing the typo out! Fixed.
