### ISSUE TITLE
Hiding Entries

### ISSUE THREAD

**Issue by mrTwice** [acidanthera/bugtracker#1364]
I am using OpenCore 0.6.4 on my MacBookPro 16" to run UHD 630 on Windows.
OpenCore is installed on the EFI partition of the system drive. Bootx64.efi from Windows is replaced with one from OpenCore.
I launch OpenCore by holding down the option key and then choosing Efi Boot.
After running Gui OpenCore, I have several entries for running OsX, Recovery, Windows, and OpenShell.
I would like to hide unused, leaving Windows only and set a timeout to start automatically.

The discussion of such functionality was here https://applelife.ru/threads/opencore-obsuzhdenie-i-ustanovka.2944066/page-488#post-914068

**Comment by Andrey1970AppleLife** [comment]
Для скрытия Tools и Recovery все уже давно есть.
Чтобы было только Windows, настрой ScanPolicy чтобы сканировало только ESP FA32.

**Comment by vit9696** [comment]
Вообще мысль хорошая, работать будет. Тогда можно ничего не менять.
