### ISSUE TITLE
ALPS Trackpad recognised as Mouse by VoodooPS2 (Laptop Toshiba z30a)

### ISSUE THREAD

**Issue by attlaflagello** [acidanthera/bugtracker#1365]
Hi,

I have almost fully configured a copy of Catalina on my Laptop.
Almost because the only not working hardware seems the Trackpad, fully working in Windows and Ubuntu.
The trackpad is an ALPS Pointing Device, composed by a Touchpad and a TrackPad Stick.
Probably I need addition of an ACPI AML file, but from info on the net I found some guides for Synaptics Touchpads, and old branches for VoodooPS2 Kext based on Rehabman version (some of these blocks the startup of MacOS, others do nothing different)
Here some screenshots taken from Windows Device Manager:
![Alps_Driver_Win10](https://user-images.githubusercontent.com/75198289/101994915-763f8e80-3cc6-11eb-80ee-807ad6d72241.png)

![Alps_Resources_Win10](https://user-images.githubusercontent.com/75198289/101994924-80618d00-3cc6-11eb-87aa-375e2fda880e.png)

![Alps_ACPI_Win10](https://user-images.githubusercontent.com/75198289/101994933-8bb4b880-3cc6-11eb-87b8-52fe99868d2b.png)

Here attached the LOG from Opencore (I don't see any issues with it...):
[opencore-2020-12-12-155818.txt](https://github.com/acidanthera/bugtracker/files/5683766/opencore-2020-12-12-155818.txt)

Can someone drive me in solving this last issue with my Installation?
Thanks in advance.

Attlaflagello

**Comment by vit9696** [comment]
Well, ALPS touchpads are not supported by our VoodooPS2 I believe.
