### ISSUE TITLE
Extreme low SSD write speed with NVMeFix on PM981

### ISSUE THREAD

**Issue by buyddy** [acidanthera/bugtracker#1367]
I have NVMeFix working with PM981 as my second SSD (non-system) in BigSur. No additional kext patched were applied. It seems that the write speed is extremely strange. If I switch to the hackNVMeFamily kext then the write speed is normal so it ruled out hardware issues. 

<img width="562" alt="1607 00" src="https://user-images.githubusercontent.com/64387298/102125039-a72adb00-3e0e-11eb-900b-dc1613c45050.png">

On my system SSD the write speed seems normal too.

**Comment by buyddy** [comment]
Both the released 1.0.4 version and the 1.0.5 version I complied myself have the same problem. When Queue >=4, it becomes extremely slow. Queue =1 or 2 have the normal speed.

**Comment by vit9696** [comment]
What is hackNVMeFamily? Also what is the Queue parameter?

**Comment by buyddy** [comment]
HackrNVMeFamily is basically a patched IONVMeFamily from 10.12.6 in the past to allow PM981 to work. 
https://github.com/RehabMan/patch-nvme

I have tried sequential queue depth of 4, 8, 16, and all the way to 64, normal read speed but strangely low write speed. The file size is 512MB.

**Comment by vit9696** [comment]
Right, in this case there is nothing new to the issue (see https://github.com/acidanthera/bugtracker/issues?q=is%3Aissue+PM981+is%3Aclosed), but thx for mentioning. I will close this as we do not plan on improving PM981 support.

**Comment by buyddy** [comment]
> Right, in this case there is nothing new to the issue (see https://github.com/acidanthera/bugtracker/issues?q=is%3Aissue+PM981+is%3Aclosed), but thx for mentioning. I will close this as we do not plan on improving PM981 support.

Is it possible for NVMeFix to run with HackrNVMe load from EFI? It is a modified version of IONVMeFix. 

	const char* kextPath {
		"/System/Library/Extensions/IONVMeFamily.kext/Contents/MacOS/IONVMeFamily"
	};

	KernelPatcher::KextInfo kextInfo {
		"com.apple.iokit.IONVMeFamily",
		&kextPath,
		1,
		{true},
		{},
		KernelPatcher::KextInfo::Unloaded
	};

If I simply modify this section to match HackNVMeFamily, will this work?

**Comment by buyddy** [comment]
Also, it seems that the debug info cannot be output with OC? I have added "keepsyms=1 -liludbg -nvmefdbg" to the boot arg. However, there is nothing related to NVMe or Lilu when I examine with: sudo dmesg |grep NVMe or log show --last boot |grep NVMe, there is no information at all. Even grep Lilu gives no debug information. Hackintool has empty log for Lilu as well. I even go to the debug version of OC and still got nothing. 

It seems to be the issue for other people as well. 

https://www.insanelymac.com/forum/topic/341984-nvmefix/?do=findComment&comment=2725687

**Comment by vit9696** [comment]
Could you attach the kext that works for you (unmodified) and tell us the minimal amount of patches that make it work? I.e. from here https://github.com/RehabMan/patch-nvme/blob/master/config_patches.plist

**Comment by buyddy** [comment]
> Could you attach the kext that works for you (unmodified) and tell us the minimal amount of patches that make it work? I.e. from here https://github.com/RehabMan/patch-nvme/blob/master/config_patches.plist

After several tests, I think I can get a stable version for PM981 with normal read/write speed on the vanilla kext from 10.14.0. The only patch needed is:

      <dict>
        <key>Comment</key>
        <string>IONVMeFamily: Ignore FLBAS bit:4 being set - for Plextor/LiteOn/Hynix﻿</string>
        <key>Disabled</key>
        <false/>
        <key>Name</key>
        <string>IONVMeFamily</string>
        <key>Find</key>
        <data>ikga9sEQ﻿﻿</data>
        <key>Replace</key>
        <data>ikga9sEA﻿</data>
      </dict>

from here:

https://www.insanelymac.com/forum/topic/312803-patch-for-using-nvme-under-macos-sierra-is-ready/?do=findComment&comment=2617639

The Kext from 10.14.4 and its new patch results in slow QD8 write. There is another patch that works for 10.15 and 11.1 but that would all result in very slow high Queue Depth slow write.

I have attached the vanilla 10.14.0 kext. I would like to know how to make NVMeFix run with a patched kext that is loaded from EFI.

Thanks!
[IONVMeFamily_10.14.kext.zip](https://github.com/acidanthera/bugtracker/files/5718689/IONVMeFamily_10.14.kext.zip)

**Comment by vit9696** [comment]
Right, do you have the earliest kext where it broke? This patch basically fixes device initialisation in 10.14.0 kext by removing an unthoughtful check. However, this check was already removed in 10.14.2, so the patch for it does nothing for 10.14.2 and newer at least. What did change in newer NVMeFamily kexts is that they removed the check that caused problems for you, but broke something else in the flow that started to cause slow speeds.

To determine what exactly happened we need the earliest possible kext, newer than 10.14.0 and likely older than 10.14.2, which has the low speed problem. Could you find it?

**Comment by vit9696** [comment]
Got all the kexts for 10.14.x from combo updates. Also included yours from 10.14.0.

Please test all these starting with .1 with and without the patch you mentioned until it breaks, and let me know their statuses (performance, kext loading, etc).

[NVMe-10.14.x.zip](https://github.com/acidanthera/bugtracker/files/5719835/NVMe-10.14.x.zip)

**Comment by buyddy** [comment]
> Got all the kexts for 10.14.x from combo updates. Also included yours from 10.14.0.
> 
> Please test all these starting with .1 with and without the patch you mentioned until it breaks, and let me know their statuses (performance, kext loading, etc).
> 
> [NVMe-10.14.x.zip](https://github.com/acidanthera/bugtracker/files/5719835/NVMe-10.14.x.zip)

I actually have tested 10.14.4, 10.14.5 and 10.14.6 yesterday before I reported the findings. The 10.14.4 has a check patch, but it has horrible speed after the patch. 

10.14.5 all the way up to 11.1 has the following possible patch (not sure what they do but the pattern exists):

https://www.insanelymac.com/forum/topic/312803-patch-for-using-nvme-under-macos-sierra-is-ready/?do=findComment&comment=2700046

After applying patches to the kext, they seem to be stable, but still very slow.

So I think only 10.14.1-10.14.3 needs to be tested to see if there is a speed issue. My guess is 10.14.3 should be the last version that can perform well.

**Comment by vit9696** [comment]
Alright, let me know when you test them. Thanks!

**Comment by buyddy** [comment]
> Alright, let me know when you test them. Thanks!

I have tested 10.14.1 to 10.14.3, they behave more or less the same. With AmorphousDiskmark, the speed for 512M file sequential write is normal half of the time and fail in half of the time. However none can pass the black magic disk speed test (including the 10.14.0 version). Also for 2G files, all version have super slow write speed. I think it is not worth the effort. Decided to get a 970 Evo instead.

**Comment by vit9696** [comment]
I.e. you get low speeds with all NVMe kexts 10.14.0-10.14.4, correct? Just sometimes less often, sometimes more often. In this case it is indeed not worth the effort.

**Comment by buyddy** [comment]
> I.e. you get low speeds with all NVMe kexts 10.14.0-10.14.4, correct? Just sometimes less often, sometimes more often. In this case it is indeed not worth the effort.
> 
> What is BlackMagic test? Could you tell us?

I was originally using AmorphousDiskmark, and it lets you specify the file size and the queue depth for the test. I think 10.14.0 was doing ok with file size 512MB with large queue size. However once I change to bigger file sizes, the write speed is down to 10M (I suspect it has something to do with the cache on the ssd). 10.14.1-10.14.3 was a hit and miss for size 512M. >10.14.4 is horrible. 

Blackmagic Disk Speed Test is another disk speed test app in Mac. With that app, all versions have horrible write speed. The EVO 970 works great with Mac and perform well with both test apps.

**Comment by jamesst20** [comment]
@buyddy @vit9696 

Hi,

I currently have an Hynix SSD which seems to be fixed by the same patch as the PM981. I couldn't find any information on how to 'downgrade' the IONVMeFamily kext from the Big Sur installer in favor for the provided 10.14 kext of this thread. Would you happen to have a tip for me ? It used to be simple because I could just replace the kext in S/L/E.
