### ISSUE TITLE
SMCBatteryManager.kext battery Connect the power supply without charging low pwer

### ISSUE THREAD

**Issue by wings110** [acidanthera/bugtracker#1368]
my laptop run macos 10.15.7 ,use the SMCBatteryManager.kext   can show battery status, connect power supply  no lightning icon ,connect power supply a little while will show low power(battery should be fully ), i try to use ACPIBatteryManager.kext (version 1.81.4) all work well ,newer version ACPIBatteryManager.kext  have the same problem with SMCBatteryManager.kext, please help fix this problem, big thx.

**Comment by vit9696** [comment]
Sounds like ACPI issues. SMCBatteryManager plugin is more restrictive in regards to incorrect configuration.
