### ISSUE TITLE
AppleALC 1.5.5 regression bug?  Conflict with CPU temperature sensor

### ISSUE THREAD

**Issue by gvkt** [acidanthera/bugtracker#1370]
Not sure why AppleALC should conflict with sensor availability.

MSI Z-370M Mortar with i5-9600k 

Edited to add: Big Sur 11.1

Isolated the problem to just updating AppleALC 1.5.4 to 1.5.5 and is consistent and reproducible. With AppleALC 1.5.4, the CPU temp sensor is available to Mac Fan Control. 

With AppleALC 1.5.5, everything else remaining the same, MAC Fan Control no longer sees the CPU temperature. 

Audio works fine, no issues there.

Using latest opencore, lilu, whatevergreen and VirtualSMC kexts as attached. Same issue with previous versions of these other kexts as well. AppleALC 1.5.5 is the only thing that triggers this. AppleALC 1.5.4 works fine with any of those versions.

If you need any specific debug logs, will figure out how to get them.

[EFI.zip](https://github.com/acidanthera/bugtracker/files/5699819/EFI.zip)

**Comment by vit9696** [comment]
@gvkt could you provide with AppleALC 1.5.4 and AppleALC 1.5.5:

- the output of `sudo /path/to/smcread -s` (can be found in VSMC package)
- I/O Registry dumps (via I/O Registry Explorer)

Also check if it works with AppleALC 1.5.3 and whether AppleALC from master changes anything.

@zhen-zen this may be related to another issue with MAC Fan Control app you mentioned in the PR.

**Comment by gvkt** [comment]
[ioReg_smcread.zip](https://github.com/acidanthera/bugtracker/files/5706306/ioReg_smcread.zip)

Contains ioreg dumps and smcread -s output with AppleALC 1.5.4 (cpu sensor available) and Apple ALC 1.5.5 (cpu sensor not available)

Will try AppleALC 1.5.3 and report

**Comment by gvkt** [comment]
No CPU sensor with AppleALC 1.5.3 same as 1.5.5. Only AppleALC 1.5.4 works.

**Comment by vit9696** [comment]
From the log it is clear that with AppleALC 1.5.4 the order of the SMC keys is different. I believe this is the culprit: `MAC Fan Control` does not expect that they SMC keys may not be sorted. Please report this bug to Mac Fan Control developer.

**Comment by gvkt** [comment]
Thanks. Loos like the discussion with the developer is already underway. So closing this.
