### ISSUE TITLE
Please add Infinitive scroll/swipe in OpenCanopy/OpenCore 

### ISSUE THREAD

**Issue by WPL1999** [acidanthera/bugtracker#1373]
The problem is if you have too many bootable drives, the following ones are cut and not displayed anymore.
So can I ask that you implement support to scroll/swipe through the device list in OpenCanopy?

![17003539](https://user-images.githubusercontent.com/75899172/102423668-d6596c00-4009-11eb-914b-bd4cc2cf92c3.png)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/759
