### ISSUE TITLE
reboot after plugging power cord(type-c) on my laptop which waked up just now

### ISSUE THREAD

**Issue by HeartAndSoul001** [acidanthera/bugtracker#1374]
my laptop EFI is OC 0.6.4, system version is Big Sur 11.1. 
my laptop is x1 carbon 2017(5th), which has two thunderbolt on type-c plug
After one-night hibernation, I plug the power cord on type-c. And then it reboot right now, which never happened before.
I doubt that if there is a bug on new SMCBatteryManager.kext(which updated on December) or Big Sur 11.1(the newest macOS version). More details are showed below:

panic(cpu 0 caller 0xffffff80197fd817): "AppleHDAHDMI_DPDriver::setPowerState(0xffffff9374d13000 : 0xffffff7fb8046348, 0 -> 1) timed out after 10172 ms"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.60.75/iokit/Kernel/IOServicePM.cpp:5382
Backtrace (CPU 0), Frame : Return Address
0xffffffb0a9a8bac0 : 0xffffff80190b9aed 
0xffffffb0a9a8bb10 : 0xffffff80191fc6e3 
0xffffffb0a9a8bb50 : 0xffffff80191ecd1a 
0xffffffb0a9a8bba0 : 0xffffff801905ea2f 
0xffffffb0a9a8bbc0 : 0xffffff80190b938d 
0xffffffb0a9a8bce0 : 0xffffff80190b9678 
0xffffffb0a9a8bd50 : 0xffffff80198be3ca 
0xffffffb0a9a8bdc0 : 0xffffff80197fd817 
0xffffffb0a9a8be10 : 0xffffff80197fd139 
0xffffffb0a9a8be20 : 0xffffff8019815bee 
0xffffffb0a9a8be60 : 0xffffff80197fbeb8 
0xffffffb0a9a8be80 : 0xffffff80190fe6b5 
0xffffffb0a9a8bef0 : 0xffffff80190ff5c4 
0xffffffb0a9a8bfa0 : 0xffffff801905e13e 

Process name corresponding to current thread: kernel_task

Mac OS version:
20C69

Kernel version:
Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
Kernel UUID: 82E2050C-5936-3D24-AD3B-EC4EC5C09E11
KernelCache slide: 0x0000000018e00000
KernelCache base:  0xffffff8019000000
Kernel slide:      0x0000000018e10000
Kernel text base:  0xffffff8019010000
__HIB  text base: 0xffffff8018f00000
System model name: MacBookPro14,2 (Mac-CAD6701F7CEA0921)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 126286867754951
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000072db73e47f1a
  Sleep   : 0x000072b5ba778acc 0x00000000715d18f2 0x000050697a112b87
  Wake    : 0x000072b5c261dc4a 0x000000006f68bcbd 0x000072b5bbea7260
last started kext at 126127990475136: |IO!BUSBDFU	8.0.2f9 (addr 0xffffff801b65d000, size 8192)
last stopped kext at 126200120100126: ru.joedm.SMCSuperIO	1.1.9 (addr 0xffffff801ce2d000, size 77824)
loaded kexts:
com.astrill.macproxy.kext	2.0.9
com.astrill.astrill.kext	1.0
com.intel.driver.EnergyDriver	3.7.0
me.kishorprins.VoodooInput	1.0.9
as.acidanthera.voodoo.driver.PS2Keyboard	2.1.9
as.acidanthera.voodoo.driver.PS2Trackpad	2.1.9
as.acidanthera.mieze.!IMausi	1.0.4
ru.joedm.SMCSuperIO	1.1.9
as.lvs1974.RTCMemoryFixup	1.0.7
as.acidanthera.voodoo.driver.PS2!C	2.1.9
as.vit9696.SMCProcessor	1.1.9
as.lvs1974.HibernationFixup	1.3.8
org.acidanthera.NVMeFix	1.0.4
org.vanilla.driver.CPUFriend	1.2.2
as.vit9696.!AALC	1.5.5
as.vit9696.WhateverGreen	1.4.5
ru.usrsse2.SMCLightSensor	1.1.9
ru.usrsse2.SMCBatteryManager	1.1.9
as.vit9696.VirtualSMC	1.1.9
as.vit9696.Lilu	1.5.0
@filesystems.smbfs	3.4.1
>AudioAUUC	1.70
>AGPM	119
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@fileutil	20.036.15
@filesystems.autofs	3.0
>!AUpstreamUserClient	3.6.8
>!AGraphicsDevicePolicy	6.2.2
>!ABacklight	180.3
@AGDCPluginDisplayMetrics	6.2.2
>pmtelemetry	1
>LuaHardwareAccess	1.0.16
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
|IO!BSerialManager	8.0.2f9
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>!AHDA	283.15
>!A!IKBLGraphics	16.0.1
>!A!ISlowAdaptiveClocking	4.0.0
>eficheck	1
>!ASMCLMU	212
>!A!IKBLGraphicsFramebuffer	16.0.1
>!A!IPCHPMC	2.0.1
>!AMCCSControl	1.14
>!ATopCaseHIDEventDriver	4020.6
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.60.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ASmartBatteryManager	161.0.0
@filesystems.apfs	1677.60.23
@private.KextAudit	1.0
>AirPort.BrcmNIC	1400.1.1
>!ARTC	2.0
>!AHPET	1.8
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@kext.triggers	1.0
>!AGraphicsControl	6.2.2
>!ABacklightExpert	1.1.0
>X86PlatformPlugin	1.0.0
|IOSerial!F	11
|IOAVB!F	900.12
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
@!AGPUWrangler	6.2.2
|IOSlowAdaptiveClocking!F	1.0.0
>!ASMBusPCI	1.0.14d1
|IOAccelerator!F2	439.52
@!AGraphicsDeviceControl	6.2.2
>IOPlatformPlugin!F	6.0.0d8
>!AHDA!C	283.15
|IOHDA!F	283.15
|IONDRVSupport	585
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
|IOGraphics!F	585
>!ASMBus!C	1.0.18d1
>!AActuatorDriver	4400.28
>!AMultitouchDriver	4400.28
>!AInputDeviceSupport	4400.35
>!AHS!BDriver	4020.6
>IO!BHIDDriver	8.0.2f9
|Broadcom!BHost!CUSBTransport	8.0.2f9
|IO!BHost!CUSBTransport	8.0.2f9
|IO!BHost!CTransport	8.0.2f9
>usb.!UHub	1.2
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!UMergeNub	900.4.2
>!ABSDKextStarter	3
|IOSurface	289.3
@filesystems.hfs.encodings.kext	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
|IONVMe!F	2.1.0
|IO80211!F	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOSMBus!F	1.1
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.2f9
|IOReport!F	47
|IO!BPacketLogger	8.0.2f9
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.60.2
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1

**Comment by vit9696** [comment]
While there was a quirk to disable this panic in OpenCore, I believe in general this is a configuration issue that needs to be addressed on the user level. I do not quite remember the exact workarounds used.

CC @khronokernel perhaps we need a better section for this issue if there was any?

**Comment by HeartAndSoul001** [comment]
thanks a lot @vit9696, I found a quirk named PowerTimeoutKernelPanic and modified it after reading the doc file in OC.
