### ISSUE TITLE
[PRE-PULL REQUEST] Fix for physical synaptic pad buttons

### ISSUE THREAD

**Issue by Luca1991** [acidanthera/bugtracker#1376]
Ok so, this is not a "support request", I already fixed this issue on my end, and I'd like to send a PR to VoodooPS2 repo as soon as possibile, but I need to be sure to do that in the cleanest way possibile.

Long story short: My laptop (Lenovo Z70-80) have a synpatic pad, touchpad is working perfectly, but physical buttons wasn't working at all. After some debugging I figured out that just setting "isthinkpad" variable to 1 is enough to make the buttons work.

Now of course I can't send a PR with this dirty hack, and I'm trying to understand where the "isthinkpad" varible is actually set. Sadly I'm not able to figure this out, as it looks like it is always 0 (how is this possible?! Surely, I'm missing something here).

If someone is able to tell me where (and how) this variable is set, I'll be able to send a PR to fix this issue for this laptop.

Thanks,
Luca

**Comment by zhen-zen** [comment]
You can just set it in the VoodooPS2 configuration SSDT.
Ref:
https://github.com/acidanthera/VoodooPS2/blob/6d3b230ad57cddf2a49e71773abd94b0265bbb1d/Docs/ACPI/SSDT-Thinkpad_Clickpad.dsl#L36
https://github.com/acidanthera/VoodooPS2/blob/6d3b230ad57cddf2a49e71773abd94b0265bbb1d/VoodooPS2Trackpad/VoodooPS2SynapticsTouchPad.cpp#L2188

**Comment by Luca1991** [comment]
@zhen-zen Thank you. Ok, but I was hoping that there were another "more generalized" way to do that. For example by adding something in the the trackpad info plist. I don't know.

I don't use that ssdt in my hackintosh anyway.

**Comment by zhen-zen** [comment]
Info.plist property is parsed under the same name but that entry is not for everyone. If you modify Info.plist, you will need to do it again after updating the kext.

**Comment by vit9696** [comment]
Unfortunately it is much easier to maintain a list of configurable parameters than to have touchpad product detection. For you it is the correct way to specify a customised SSDT.

**Comment by Luca1991** [comment]
@zhen-zen yeah that's why I was hoping to send a PR to the VoodooPS2 repository. This "fix" would help everyone that have my laptop. 

I mean, it is ok for me to update that plist at each future kext update, but I think that others can benefit from this.

**Comment by Luca1991** [comment]
> Unfortunately it is much easier to maintain a list of configurable parameters than to have touchpad product detection. For you it is the correct way to specify a customised SSDT.

But then why there is a list of "LENOVO" laptops in the voodootrackpad info plist?

**Comment by vit9696** [comment]
Because for some trackpads we have a list of already set overrides. Eventually we got tired of maintaining it. It also did not work quite right, as for some models you may need different configurations depending on the form-factor and such. You can contribute a patch for your model, but obviously not in the global namespace.

**Comment by Luca1991** [comment]
@vit9696 so your are telling me that this list isn't used anymore? Because my hope was to add my laptop model to that list. 

If I understood correctly (so that list isn't used anymore) then that's make dense and I have to build by myself the kext at each update :/

Thanks for your time and patience anyway

**Comment by vit9696** [comment]
Sorry, but you do not need to build the kext after every update. Info.plist must not be edited by any user. To configure the parameters you can use the SSDT @zhen-zen linked you to. Your intent to avoid it is understandable but it is the only supported way.

You may send a PR with your laptop and we will likely accept. The point was rather that we do not monitor the situation ourselves and do not add such entries personally.

**Comment by vit9696** [comment]
@Luca1991 Happy New Year, any chance you send the PR before the window closes for this release schedule (today or early tomorrow)?

**Comment by Luca1991** [comment]
Hi @vit9696 I eventually solved by using the clickpad ssdt. So you all were right, no need to create a specific patch ;)

Happy new year :)

**Comment by Overc1ocker** [comment]
Hi @vit9696. The SSDT worked! If @Luca1991 does not want to submit a PR, is it possible that we can note somewhere that certain other brands may use a trackpad configuration similar to Lenovo's and that you may need to try one of the Lenovo SSDTs? My Laptop is a hp 15-Da0014DX and the Lenovo patches fixed the buttons!

**Comment by Luca1991** [comment]
@Overc1ocker I can't send a PR because there is nothing to fix really. As noted before using the SSDT is the only supported way. I'm not aware of any other way to set the "isThinkpad" variabile to true without that SSDT. So, it is not me that "don't want to send a PR" :)

**Comment by GuaiYiHu** [comment]
My Fujitsu S935 has the same issue and the thinkpad ssdt doesn't work.
Physical buttons work with ApplePS2SmartTouchPad.kext.
