### ISSUE TITLE
[Feature Request] for Open Canopy --> Rounded Selection M1 Style

### ISSUE THREAD

**Issue by telepati** [acidanthera/bugtracker#1379]
First of all sorry to writing here cause the Open Canopy title locked by developers.

I just wondering is possible to add a rounded selection to Open Canopy like real M1 macs?

![selectionpng](https://user-images.githubusercontent.com/3812286/102698219-e44aff00-424c-11eb-88ca-304e23a72f2a.png)

**Comment by vit9696** [comment]
You can try to do something close with a custom theme.

**Comment by Andrey1970AppleLife** [comment]
https://www.insanelymac.com/forum/topic/344251-opencanopy-icons/?do=findComment&comment=2729742
