### ISSUE TITLE
cant download recovery image

### ISSUE THREAD

**Issue by The1PRimeYT** [acidanthera/bugtracker#1380]
![CMD](https://user-images.githubusercontent.com/21149526/102703553-346e9500-423e-11eb-91e1-0a4f509a5000.PNG)

I keep getting this issue I had python 3 and read that it didn't work now that I have python 2 it doesn't work either any suggestion that could help me get the recovery image thanks

**Comment by stevezhengshiqi** [comment]
Already fixed. Please check https://github.com/acidanthera/bugtracker/issues/1371
