### ISSUE TITLE
[Linux Request] OpenCore ocvalidate not working

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1382]
Hi there,
I don't know if this issue will be even considered in the future, but I'd like to use OpenCore Utilities like `ocvalidate` in Linux environments.
At the moment, if I even try to execute it, I get a ``bash: /home/ivan/Desktop/Utilities/ocvalidate/ocvalidate: cannot execute binary file: Exec format error`

Will this tool (and future ones) be ever supported on Linux environments, or we have to launch them directly from a macOS environment? 
Many thanks and have a nice day ^^

**Comment by vit9696** [comment]
There is no way to easily cross-compile to Linux on macOS, and this is where OpenCore release binaries are built. However, you can compile OpenCore on Linux, and in this case ocvalidate will be available.

You can get prebuilt builds as well, but they are only saved for 30 days:

<img width="774" alt="Снимок экрана 2020-12-21 в 03 23 29" src="https://user-images.githubusercontent.com/4348897/102728267-e6d85200-433b-11eb-9389-6dbd2501f8d3.png">
<img width="510" alt="Снимок экрана 2020-12-21 в 03 23 14" src="https://user-images.githubusercontent.com/4348897/102728264-de801700-433b-11eb-8e89-62b57cd42377.png">

**Comment by dreamwhite** [comment]
> There is no way to easily cross-compile to Linux on macOS, and this is where OpenCore release binaries are built. However, you can compile OpenCore on Linux, and in this case ocvalidate will be available.
> 
> You can get prebuilt builds as well, but they are only saved for 30 days:
> 
> <img width="774" alt="Снимок экрана 2020-12-21 в 03 23 29" src="https://user-images.githubusercontent.com/4348897/102728267-e6d85200-433b-11eb-9389-6dbd2501f8d3.png">
> <img width="510" alt="Снимок экрана 2020-12-21 в 03 23 14" src="https://user-images.githubusercontent.com/4348897/102728264-de801700-433b-11eb-8e89-62b57cd42377.png">
> 

Wow! Really thanks for the fast reply. I'll let you know tomorrow if the tools works or not.
Have a good night (in italy it's 1:26 AM 🥱)
