### ISSUE TITLE
[Lilu] Lilu Debug output isn't available in syslog with latest Big Sur

### ISSUE THREAD

**Issue by shantur** [acidanthera/bugtracker#1384]
I am trying to enable Lilu Debug logs with latest Big Sur.

I have double checked the following things

1. Using Debug version of Lilu and WhateverGreen
2. Added `-v -liludbg -liludbgall -wegdbg` in the boot-args
3. Booting using the correct EFI.
4. Both Lilu and WhateverGreen kexts are loaded in `kextstat`

**Actual Behaviour :** 

I could see Lilu output is visible in the onscreen console. As I am trying to debug blank screen bootup after sometime the onscreen console is lost. I am not able to see anything being printed from WhateverGreen.

Trying to see boot log using

`log show --predicate 'process == "kernel"' --style syslog  --debug --info --backtrace --loss --signpost --last boot`

Doesn't print anything from Lilu or WhateverGreen.

**Expect behaviour:**

Lilu and plugins are able to print debug output.

More Info

OpenCore version : 0.6.4 (tried both Debug and Release)
Attached : My EFI folder
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5725581/EFI.zip)

**Comment by Andrey1970AppleLife** [comment]
Use liludump=N https://github.com/acidanthera/Lilu

**Comment by shantur** [comment]
Thanks @Andrey1970AppleLife for pointing out liludump.

Just to ask is this an expected behaviour with newer version of MacOS / Lilu?
I have seen it working as expected in Catalina.

**Comment by shantur** [comment]
@Andrey1970AppleLife : I gave `liludump=1` a try and it didn't work too. `/var/log/LILU*` wasn't created.

**Comment by vit9696** [comment]
Your system does not start in less than 1 second. 1 is not valid.
