### ISSUE TITLE
Issue #1371 was closed without any information WHY?

### ISSUE THREAD

**Issue by MichiganBroadband** [acidanthera/bugtracker#1389]
Seriously... tutorial and instructions are based on this actually working as expected.

**Comment by vit9696** [comment]
The tool was fixed, thus the issue was closed.

**Comment by MichiganBroadband** [comment]
Thanks for the reply.   
I had just downloaded the tool last night and getting the problem.  
Is the problem back or do I need to somehow find a newer version than what I thought was the latest?

**Comment by vit9696** [comment]
You need to use nightly builds available e.g. on https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true

**Comment by MichiganBroadband** [comment]
Thanks!  
And yeah all set now.
