### ISSUE TITLE
[WhateverGreen 1.4.5]

### ISSUE THREAD

**Issue by MysticalOS** [acidanthera/bugtracker#1390]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

Updating WG to 1.4.5 caused major issues with getting nVidia gpu to work correctly. Runnin 10.13.6 with nvidia 1080ti on web driver was flawless on 1.4.4 but upgrading to 1.4.5 it kept booting into black screen on display port 1. I could switch to DP2 to get it to work then ironically when i rebooted DP2 would be black screen until i switched to DP1. I tried numerous different things and issue persisted, until I downgraded WG to 1.4.4 and problem was totally cured.

I realize nvidia support is in a pretty dead spot but I'm just holding out as long as I can for 11.x to give us some good working support for big navi. Downgrading gpu to something slower that worked not ideal. Anyways I'm content staying on WEG 1.4.4 for now but thought I'd report the issue none the less.

**Comment by vit9696** [comment]
There were no nvidia-related changes in 1.4.5. There is a race-condition bug with nvidia driver startup, most likely it just got worse due to unlucky timing.
