### ISSUE TITLE
OpenCore: Drop empty string support in config.

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#1392]
Currently there are entries accepting empty strings to be failsafe. However, the meaning can be confusing as empty strings in each section may indicate different behaviours. Instead of supporting such, we should drop the support and explicitly state the failsafe. As a preparation stage, new ocvalidate has already denied most empty strings.

While functional empty strings should be dropped, some literal ones may not. Current entries with empty string support will be listed below, and further discussion might be required prior to removal/behaviour change.

- [ ] TODO

**Comment by vit9696** [comment]
I am not sure it is a good idea to change OpenCore behaviour in that regard, but we definitely should correct the documentation when necessary. I can think of the following values:

- `KernelArch`
- `Arch`
- `KernelCache`
- `Vault`
- `BootProtect`
- `HibernateMode`
- `PickerMode`
- `DmgLoading`
- `SecureBootModel`
- `KeySupportMode`
- `TextRenderer`
- `PointerSupportMode` (when enabled)
-

**Comment by Andrey1970AppleLife** [comment]
@PMheart 
Many strings, such as `ExecutablePath` and others, shall allow the empty.

**Comment by PMheart** [comment]
> @PMheart
> Many strings, such as `ExecutablePath` and others, shall allow the empty.

Correct. That’s what I meant. Anyway, I will try evaluating which should be removed empty string support, and which should not.

**Comment by dakanji** [comment]
Can you kindly spell out implications of this change?

Will this break shedloads of configs out there?

In particular on Legacy Macs, most only specify needed changes (particularly SMBIOS Stuff) and leave the rest to be read. Is this going to knacker such setups? Do we now need to go full hackintosh to use OC?

**Comment by stevezhengshiqi** [comment]
As I suggested to @PMheart , I personally recommend reserve empty string support for `PlatformInfo` section, such as SystemUUID, SystemSerialNumber, MLB. These values won't affect OpenCore functionality, and might be easier for testers to analyze other's config that Serial Numbers have been wiped out.

**Comment by vit9696** [comment]
PlatformInfo is not a thing this should change. The changes mentioned here should not really be code changes, but rather specification updates.

**Comment by PMheart** [comment]
Sorry for the late response.

Let me be clear again: ***Only empty strings for functional usage will no longer be supported. Support for empty values will remain there.***

This means, only keys posted [here](https://github.com/acidanthera/bugtracker/issues/1392#issuecomment-750932569) will no longer support empty strings.

**Comment by PMheart** [comment]
@vit9696 I took a look at Configuration.tex describing properties at https://github.com/acidanthera/bugtracker/issues/1392#issuecomment-750932569, and it looks like we only need to clarify `PointerSupportMode`, which was done at https://github.com/acidanthera/OpenCorePkg/commit/cb6bb3dba59746549958b44addfd6488ed176a38.

I will now take a look at ocvalidate and see whether we should prevent empty strings for these properties.

**Comment by vit9696** [comment]
Also AudioDevice, PlayChime (failsafe value), KeySupportMode (failsafe value), no?

**Comment by PMheart** [comment]
Fixed `PlayChime` and `KeySupportMode` (https://github.com/acidanthera/OpenCorePkg/commit/a34dda548eb1cc766248fa648e54a15454246cc8). As for `AudioDevice`, I understand that its value cannot be empty, but I am not sure what to set by default. How about `PciRoot(0x0)/Pci(0x1b,0x0)`?

**Comment by vit9696** [comment]
It can be empty (by default) just not when AudioSupport is enabled. The rest seems fine. I guess we shall close this.
