### ISSUE TITLE
AppleALC HDMI as an output stopped after v1.4.9 for ALC256

### ISSUE THREAD

**Issue by mrgatesjunior** [acidanthera/bugtracker#1393]
AppleALC issue.  It was detecting HDMI as an output for audio prior to version 1.5.0, verified this twice.  After that version it never shows up as an option for output for the audio.

**Comment by vit9696** [comment]
Pretty sure there was no regression. Usually the issue is with ACPI (missing device in ACPI) or quirks (e.g. DisableLinkeditJetisson). 1.5.0 changed the boot flow a bit, so improper configurations become more apparent.
