### ISSUE TITLE
 Issue with installation big sur Thinkpad e15 

### ISSUE THREAD

**Issue by mohamed-s-elgohary** [acidanthera/bugtracker#1394]
Lenovo thinkpad e15 i7 10510u , intel graphic , amd rx 640
 
 i try to install big sur and catalina with Open Core and clover both stuck on this screen can you help me 
[Pic ](https://drive.google.com/file/d/1ryP4qbYK31P7JOI3PeUFjNWN6gR8NmpB/view?usp=drivesdk)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support

**Comment by mohamed-s-elgohary** [comment]
can i get any solution to fix it
