### ISSUE TITLE
MaciASL on M1 Mac

### ISSUE THREAD

**Issue by kecinzer** [acidanthera/bugtracker#1395]
I'm so sorry for writing here as this issue is not related to OC etc., but I wanted to make some DSL and AML files with MaciASL on my new MacBook Air with Apple M1 and I can't launch it.
I tried few things like adding app to quarentine white list, chmod 755 for it etc. but nothing worked.
When I launch it from Terminal I got this error:

The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2508, NSUnderlyingError=0x12bf06360 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x12bf04750 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 153}}}}}

Is there someone who run MaciASL on M1 already?

**Comment by vit9696** [comment]
Did you try `xattr -cr /path/to/MaciASL.app`? We used MaciASL on T2 Macs without issues.

**Comment by kecinzer** [comment]
Thank you a lot @vit9696, xattr not work, but codesign seems to help 👍
