### ISSUE TITLE
Clarification on error message <OCS: No schema for xxx>

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#1396]
Some users report that [this message](https://github.com/acidanthera/OpenCorePkg/blob/8ee217afbc12fc5ffb6b860996cb88633c71400f/Library/OcSerializeLib/OcSerializeLib.c#L133) might lead to confusions, particularly when checking config.plist using ocvalidate. While we do have schema for serialisation and thus rewriting this message may not be a good idea, clarification on the meaning of `<OCS: No schema for xxx>` can be done instead. It should land in either the README of ocvalidate, or Configuration.pdf. Further discussion may be required.

Also, currently there is no indication that which version of OpenCore is compatible with only a binary distribution of ocvalidate, so I think it can be a good idea to print `OPEN_CORE_VERSION` (EDIT: Done in https://github.com/acidanthera/OpenCorePkg/commit/4b33c0ee48e0c2b4f7390e1aa24c9bbf93d3fa50). Or we can even build some scripts to include commit.

**Comment by vit9696** [comment]
Configuration.pdf should not have it as it describes the behaviour of missing keys as undefined. Could put it to the ocvalidate README. I do not mind the `OPEN_CORE_VERSION` printing, but please make do it only when running with `--version` argument or when executing without arguments. Little sense to print it unconditionally all the time.

**Comment by telepati** [comment]
is it possible to add the "How to Use" section to the Read Me?

**Comment by PMheart** [comment]
> is it possible to add the "How to Use" section to the Read Me?

The usage is simple - just pass config.plist to ocvalidate. `path/to/ocvalidate path/to/config.plist`
And if you do not pass any arguments, ocvalidate will also show this info. So, I don’t think there is any need to explicitly state that in README.

**Comment by telepati** [comment]
Why is this note still showing even we are already working on v0.6.5?

<img width="682" alt="Screen Shot 2020-12-29 at 21 25 49" src="https://user-images.githubusercontent.com/3812286/103305618-aa33e700-4a1c-11eb-8d71-5e481cec7c5a.png">

**Comment by PMheart** [comment]
> Why is this note still showing even we are already working on v0.6.5?
> Wouldn't it be more correct if this note is not shown when working with v0.6.5 and future release?
> 
> <img alt="Screen Shot 2020-12-29 at 21 25 49" width="682" src="https://user-images.githubusercontent.com/3812286/103305618-aa33e700-4a1c-11eb-8d71-5e481cec7c5a.png">

As @vit9696 said, we really should not always print the version supported. Instead, a new argument `--version` is introduced to print this info. Thanks for the report.

**Comment by davids74** [comment]
What does index in OCValidate messages mean? How to understand what does e.g. Force in Kernel means?

```
OCS: No schema for Force at 6 index, context <Patch>!
OCS: Missing key Force, context <Kernel>!
```

Could dear devs add some info to the message showing what it actually refers to?
