### ISSUE TITLE
AppleXcpmCfgLock not working on Comet Lake Thinkpads

### ISSUE THREAD

**Issue by hagenest** [acidanthera/bugtracker#1397]
Hey there :)

First off all, I'm not sure how the AppleXcpmCfgLock-patch works exactly, so feel free to close this issue if it is unfixable.

It seems no one is able to install macOS with OpenCore on a Thinkpad (or Thinkbook) with a Comet Lake CPU.
The installation stops at `AAPL: [EB|#LOG:EXITBS:START]`
I carefully followed the official guide and was not able to fix it, even though I tried every combination of possible fixes.

It seems like it's impossible to deactivate cfg-lock on modern Thinkpads and AppleXcpmCfgLock (or related legacy-fixes) doesn't work either.

I'm by no means the only one with this problem:
- https://github.com/hagenest/thinkpad-l13-yoga-hackintosh (my repo)
- https://github.com/bomdurup/x1c7_2020_hacintosh
- https://www.reddit.com/r/hackintosh/comments/jl4ki7/cannot_get_past_aapl_eblogexitbsstart/
- https://github.com/acoutts/x1c7-hackintosh/issues/1
- https://www.hackintosh-forum.de/forum/thread/46023-lenovo-thinkpad-l13-yoga-catalina-installation/?pageNo=4 (german)
- https://www.olarila.com/topic/8117-thinkpad-x1-c7-comet-lake-gets-stuck-right-after-clover-selection/
- https://www.hackintosh-forum.de/forum/thread/48908-lenovo-thinkpad-e15-ist-der-laptop-hackintosh-tauglich-fazit-nein-ist-es-nicht/?pageNo=2 (german)
- https://www.reddit.com/r/hackintosh/comments/fwj25y/thinkpad_x1_c7_with_comet_lake_booting_issue/

I know there were already issues that got closed with the comment we should go to forums for support, like #1394 #1027 #851
but I do think this is a problem with OpenCore, that would need to be patched. No hackintosh community seems to be able to fix this by themselves. I wasn't able to find a single person who could get this to work.

Nevertheless, thank you all for your hard work and I understand if fixing a comparatively small subset of notebooks is not high on your to-do-list.

**Comment by vit9696** [comment]
Hi, we checked `AppleXcpmCfgLock` on Big Sur here, and it works fine. I do not believe the issue you see is caused by `AppleXcpmCfgLock`. Try playing with `Booter` quirks, I remember there were quite unusual configurations needed for some laptops to work.

CC @kprinssu, did not you have Lenovo actually where we spent quite some time understanding a similar issue?

**Comment by hagenest** [comment]
I got it now. I didn't understand that `AppleXcpmCfgLock` works independent of the used hardware. Around 6 additional hours of playing with booter quirks sadly didn't help. 
Thanks for the fast reply though

**Comment by kprinssu** [comment]
@vit9696 It ended up being a hardware issue in the end; needed to replace the wireless card.

**Comment by richibrics** [comment]
Maybe it can help, I saw a Lenovo Thinkpad X1 Carbon 6th with BigSur: [Reddit](https://www.reddit.com/r/hackintosh/comments/kv3jc7/big_sur_111_on_lenovo_thinkpad_x1_carbon_6th_and/)

**Comment by hagenest** [comment]
Thank you for trying to help @richibrics, but that one's using a 8th gen CPU. There a quite a few people who got it to run on them. It seems like Lenovo broke something specifically with the 10th Gen on Thinkpads (+ Thinkbooks).
