### ISSUE TITLE
OpenCore 0.6.4 influences USB support in Catalina 10.15.7 19H114

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1398]
When booting with OpenCore v0.6.4, the devices shown in IORegistry are different than the ones which appear in Clover, especially USB controllers (`EUSB` and `USBE`) as shown in ioreg logs below. 

Instead with the latest clover r5127, USB controllers are recognized with no issues (it is also important to mention for this older board that there's no XHCI controllers/handoffs in bios settings)

I can attach more logs, just ask what's required

## Hardware info:
* CPU: i3 540, Clarkdale, legacy boot
* Motherboard: imedia S3810, Chipset H57
* GPU: GT710

## Software info:
* OpenCore version: 0.6.4
* Boot type: Legacy
* OpenCore [EFI](https://github.com/acidanthera/bugtracker/files/5753996/EFI-OpenCore-0.6.4.zip) + [OpenCore ioreg](https://github.com/acidanthera/bugtracker/files/5753978/iMac_OpenCore_0.6.4.zip)
* Clover [EFI](https://github.com/acidanthera/bugtracker/files/5753997/EFI-Clover.zip) + [Clover ioreg](https://github.com/acidanthera/bugtracker/files/5753974/iMac_Clover_5127.zip)
* Original [OEM ACPI tables](https://github.com/acidanthera/bugtracker/files/5753959/origin.zip)

**Comment by vit9696** [comment]
That would be something with ACPI I fear, but I am unsure we are ready to investigate as not guaranteed bugs are found from the description.

**Comment by 1alessandro1** [comment]
Which logs can be helpful to investigate?

**Comment by 1alessandro1** [comment]
Is it possible to extract what's working with clover and what could be the differences?
