### ISSUE TITLE
Dell XPS13 smbios has probelm

### ISSUE THREAD

**Issue by Chiloy** [acidanthera/bugtracker#1399]
I used the latest version of OC, selected CustomSMBIOSGuid, and set Updatesmbiosmode to Custom. The model and manufacturer displayed normal under Mac, but it was displayed as Dell XPS13 under OC boot to Windows, so bootcamp could not be installed because of the wrong model.
Later, I cancelled CustomSMBIOSGuid, set Updatesmbiosmode to create, and selected the model with short product name, such as iMac16,1. The model displayed normally in Mac and Win, but the model with long product name displayed incomplete, such as MacBookPro13,1 displayed as MacBookPro1.

**Comment by Andrey1970AppleLife** [comment]
msiexec /i Bootcamp.msi
