### ISSUE TITLE
APFS Volumes not seen in OC 0.6.4

### ISSUE THREAD

**Issue by gandalf239** [acidanthera/bugtracker#1401]
I've an older Sandy Bridge-based HP EliteBook 2560P. While it has UEFI, it seems that it's vers. 2.0. And while I can manually load relevant apfs drivers via the shell, this doesn't work, instead resulting in a security error. I read about a very similar issue with another HP laptop that was corrected by updating the opencore.efi and enabling a couple of options. There was GlobalConnect, FSUnlock something or other, etc. In any case,, I think my HP BIOS has the same bug and is disallowing the driver from loading.

**Comment by vit9696** [comment]
Well, enable these options in the configuration? Closing as a configuration issue.
