### ISSUE TITLE
Stuck at IOConsoleUsers: gIOScreenLockState 3 

### ISSUE THREAD

**Issue by geticus** [acidanthera/bugtracker#1402]
Hi all and Happy New Year
I'm trying to boot an existing High Sierra system on my new JINGSHA X99 D8 motherboard with an E5 2678 v3 using Open Core with no succes for the moment. I'm stuck on IOCConsoleUsers. I followed the Dortania guide, I'm not a complete novice on hackintosh-OC, I've already installed with Opencore this HG partition with an i7 7700k, but I can't do it this time.
Thanks for your help.
My graphic card is a GTX 1060.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5758898/EFI.zip)

**Comment by usr-sse2** [comment]
Bugtracker is for bug reports, not a support forum. You can ask at e.g. InsanelyMac

**Comment by geticus** [comment]
I understand, thank you!
