### ISSUE TITLE
CpuTscSync doesn't load in High Sierra

### ISSUE THREAD

**Issue by usr-sse2** [acidanthera/bugtracker#1403]
Probably the release is built for newer macOS, didn't check the logs.

**Comment by vit9696** [comment]
@usr-sse2 you mentioned that this was an Info.plist configuration overlook and that you resolved this privately, can we close this?

**Comment by usr-sse2** [comment]
The reason was too old Lilu (1.2.7). OSBundleLibraries allows 1.2.0, but it doesn't contain `_lilu_os_log`.
