### ISSUE TITLE
[BUG] BrightnessKeys.kext | HP 15-DA0014DX

### ISSUE THREAD

**Issue by Overc1ocker** [acidanthera/bugtracker#1405]
Hello! I have a HP 15 laptop with a PS2 keyboard and I cannot get the brightness keys to work. I have tried both this kext and the _Qxx to _xQxx rename + SSDT patch. BetterTouchTool does not recognize either keystroke so the keys are handled by the EC.  Backlight does work with SSDT-PNLF via system preferences. Here is the relevant piece from my DSDT if that helps.
```
                 Method (_Q11, 0, NotSerialized)  // _Qxx: EC Query, xx=0x00-0xFF
            
{
                Debug = "=====QUERY_11====="
                P80H = 0x11
                If (IGDS)
                {
                    Notify (^^^GFX0.DD1F, 0x87) // Device-Specific
                }
                Else
                {
                }
            }

            Method (_Q12, 0, NotSerialized)  // _Qxx: EC Query, xx=0x00-0xFF
            {
                Debug = "=====QUERY_12====="
                P80H = 0x12
                If (IGDS)
                {
                    Notify (^^^GFX0.DD1F, 0x86) // Device-Specific
                }
                Else
                {
                }
```

EFI folder:

https://github.com/Overc1ocker/HP-15-DA0014DX-Hackintosh

Would love to have brightness keys working! Let me know if I can debug further! Thanks!

**Comment by vit9696** [comment]
Hi, check where IGDS is enables, perhaps some kind of OSI patching is necessary for macOS. If that still does not help, you could always do it the old way: inserting the keyboard notifications in Q11/Q12. CC @zhen-zen

**Comment by Overc1ocker** [comment]
Thank you! I completely missed the IGDS part. I’ll reply if I there are still issues after I take a look.

**Comment by Overc1ocker** [comment]
I took another look at my DSDT and IGDS is enabled at the very beginning. `    External (IGDS, UnknownObj)` It is referenced four more times with `If (IGDS)`, just like in the sample I pasted. Any ideas? I also tried the OSI XOSI patch.

**Comment by vit9696** [comment]
If you drop the `If`, does it work?

**Comment by Overc1ocker** [comment]
How would I go about doing that? I know patching DSDTs are not recommended. Would I need to create a SSDT or add an entry to ACPI > patch

**Comment by vit9696** [comment]
For a test you could always simply load a custom DSDT. If it does not work, the issue is elsewhere.

**Comment by Overc1ocker** [comment]
Ok thanks!

**Comment by Overc1ocker** [comment]
That did not work, however do I need to block the OEM HP DSDT from loading first? How would I do that?

**Comment by vit9696** [comment]
You do not need to block the OEM DSDT (see Configuration.pdf for the explanation). As for the case, I am unsure what is going on. It does not seem to justified enough that there is an issue with BrightnessKeys, but in either way you should be able to set buttons up via ACPI. Consult to the external guides on this matter.

**Comment by Overc1ocker** [comment]
Awesome! Thank you for all the help! I will leave you alone now as this is not a bug in BrightnessKeys. Have a nice 2021 and thank you for all the amazing tools that make hackintoshing so easy!

**Comment by zhen-zen** [comment]
Please always attach you DSDT and SSDTs dump for debugging those issues. Usually `IGDS` is defined in a separate SSDT for IGPU device and it means "IGD state (primary = 1)". ref: https://github.com/coreboot/coreboot/blob/e0183d6540b8e8a8281f4317b881dfbc57f12bc4/src/southbridge/intel/lynxpoint/acpi/globalnvs.asl#L74

Some vendors failed to initialize those fields correctly and it's not likely to add a workaround in the driver. Possibly the optimum hack here is to add a `Name (IGDS, One)` at the same scope of your `_Qxx` methods.

**Comment by Overc1ocker** [comment]
I tried this:
```
/*
 * Intel ACPI Component Architecture
 * AML/ASL+ Disassembler version 20200925 (64-bit version)
 * Copyright (c) 2000 - 2020 Intel Corporation
 * 
 * Disassembling to symbolic ASL+ operators
 *
 * Disassembly of iASL0vVYMM.aml, Mon Jan 31 17:16:33 2022
 *
 * Original Table Header:
 *     Signature        "SSDT"
 *     Length           0x00000043 (67)
 *     Revision         0x02
 *     Checksum         0xA1
 *     OEM ID           "DRTNIA"
 *     OEM Table ID     "IGDS"
 *     OEM Revision     0x00000000 (0)
 *     Compiler ID      "INTL"
 *     Compiler Version 0x20200925 (538970405)
 */
DefinitionBlock ("", "SSDT", 2, "DRTNIA", "IGDS", 0x00000000)
{
    External (IGDS, FieldUnitObj)

    If (_OSI ("Darwin"))
    {
        IGDS = One
    }
}

```
That did not work.

I also checked for ssdts containing IGDS and none of them had anything except for this

**Comment by Overc1ocker** [comment]
```

    OperationRegion (SANV, SystemMemory, 0x8AF6A018, 0x01F7)
    Field (SANV, AnyAcc, Lock, Preserve)
    {
        ASLB,   32, 
        IMON,   8, 
        IGDS,   8, 

```

**Comment by Overc1ocker** [comment]
Update: Turns out I never enabled my EC. this now works
