### ISSUE TITLE
Shutdown restarts macOS

### ISSUE THREAD

**Issue by izo1** [acidanthera/bugtracker#1408]
Is there a way to allow Shutdown to completely shutdown instead of Restart?

This MAY be related to S5 power features, but in Catalina and Big Sur (both latest) Shutdown reboots the system.

Is there a way to add a new quirk to allow it to shut down properly?

**Comment by 1alessandro1** [comment]
Please test your NVRAM, usually shutdown problems are related to the experiences you're having, where in the case of a complete shoudown, the pc reboots.

The steps are here:

`sudo nvram MyVar=TestValue `

You can check if the created variable is available with this command:

`nvram -p`

Then reboot, and if the value is still present, then your NVRAM is native. Otherwise if you're on a 300series board or similar, check the dortania guides [here](https://dortania.github.io/OpenCore-Install-Guide)

**Comment by izo1** [comment]
hi @1alessandro1 here's the log:

efi-boot-device	<array><dict><key>IOMatch</key><dict><key>IOProviderClass</key><string>IOMedia</string><key>IOPropertyMatch</key><dict><key>UUID</key><string>C2E4D197-F14F-4F74-9AE7-DA0B6121B3E6</string></dict></dict><key>BLLastBSDName</key><string>disk4s3</string></dict><dict><key>IOEFIDevicePathType</key><string>MediaFilePath</string><key>Path</key><string>\4A05275A-02A2-409F-AA29-D73DDD7E6BEE\System\Library\CoreServices\boot.efi</string></dict></array>%00
boot-args	keepsyms=1
efi-backup-boot-device-data	%02%01%0c%00%d0A%03%0a%00%00%00%00%01%01%06%00%04%1b%01%01%06%00%00%00%03%16%10%00%01%00%00%00%00%258[%01%9e)%fa%04%01*%00%02%00%00%00(@%06%00%00%00%00%00`-jt%00%00%00%00%25%d5%1d:%a5%0aPB%b1%e2%91SP%b5w$%02%02%04%03$%00%f7%fct%be|%0b%f3I%91G%01%f4%04.hB%97%d1%e4%c2O%f1tO%9a%e7%da%0ba!%b3%e6%04%04%9a%00\%004%00A%000%005%002%007%005%00A%00-%000%002%00A%002%00-%004%000%009%00F%00-%00A%00A%002%009%00-%00D%007%003%00D%00D%00D%007%00E%006%00B%00E%00E%00\%00S%00y%00s%00t%00e%00m%00\%00L%00i%00b%00r%00a%00r%00y%00\%00C%00o%00r%00e%00S%00e%00r%00v%00i%00c%00e%00s%00\%00b%00o%00o%00t%00.%00e%00f%00i%00%00%00%7f%ff%04%00
efi-backup-boot-device	<array><dict><key>IOMatch</key><dict><key>IOProviderClass</key><string>IOMedia</string><key>IOPropertyMatch</key><dict><key>UUID</key><string>C2E4D197-F14F-4F74-9AE7-DA0B6121B3E6</string></dict></dict><key>BLLastBSDName</key><string>disk2s3</string></dict><dict><key>IOEFIDevicePathType</key><string>MediaFilePath</string><key>Path</key><string>\4A05275A-02A2-409F-AA29-D73DDD7E6BEE\System\Library\CoreServices\boot.efi</string></dict></array>%00
bluetoothActiveControllerInfo	%94%82%ac%05%00%00%00%00 %14(%f0v%00Q%dd
bluetoothInternalControllerInfo	%94%82%ac%05%00%00 %14(%f0v%00Q%dd
prev-lang:kbd	en:0
run-efi-updater	No%00
SystemAudioVolumeDB	%e4
MyVar	TestValue
fmm-computer-name	Mac Pro
efi-boot-device-data	%02%01%0c%00%d0A%03%0a%03%00%00%00%01%01%06%00%00%00%01%01%06%00%00%00%03%16%10%00%01%00%00%00%00%258[%01%9e)%fa%04%01*%00%02%00%00%00(@%06%00%00%00%00%00`-jt%00%00%00%00%25%d5%1d:%a5%0aPB%b1%e2%91SP%b5w$%02%02%04%03$%00%f7%fct%be|%0b%f3I%91G%01%f4%04.hB%97%d1%e4%c2O%f1tO%9a%e7%da%0ba!%b3%e6%04%04%9a%00\%004%00A%000%005%002%007%005%00A%00-%000%002%00A%002%00-%004%000%009%00F%00-%00A%00A%002%009%00-%00D%007%003%00D%00D%00D%007%00E%006%00B%00E%00E%00\%00S%00y%00s%00t%00e%00m%00\%00L%00i%00b%00r%00a%00r%00y%00\%00C%00o%00r%00e%00S%00e%00r%00v%00i%00c%00e%00s%00\%00b%00o%00o%00t%00.%00e%00f%00i%00%00%00%7f%ff%04%00
csr-active-config	%ff%0f%00%00
SystemAudioVolume	1
EFIBluetoothDelay	%b8%0b
LocationServicesEnabled	%01




I have a X299 board which supports native NVRAM, honestly this issue started happening back in Catalina 10.15.6 and .7, it used to work ok. I have tried Dortania's guide and it doesn't help.

**Comment by vit9696** [comment]
I heard it may be related to AsMedia USB controller on X299, but to be honest, in either case this sounds like a support issue. Not much we can do from our side. Closing.

**Comment by izo1** [comment]
@vit9696 a new feature needs to be added to fix this issue, am not technically savvy to figure it out, but I can provide my DSDT.
