### ISSUE TITLE
Please add license to gfxutil

### ISSUE THREAD

**Issue by fmunteanu** [acidanthera/bugtracker#1409]
I want to add [gfxutil](https://github.com/acidanthera/gfxutil) to Homebrew and adding a formula requires a license definition. Can you please add one or let me know which license should I use?

**Comment by vit9696** [comment]
gfxutil is not really licensed, best we have from http://forum.netkas.org/index.php?topic=64.0 is `You are free to use it and whatever you do please keep the result free for community`. Technically I can include this in a LICENSE file. While not perfect in law terms, it does state the things clearly at least. Will it work for brew?
