### ISSUE TITLE
ALC1220 blown out audio on headphone

### ISSUE THREAD

**Issue by izo1** [acidanthera/bugtracker#1410]
Hello, using AppleALC, with ALC1220 using the front headphone jack port, the audio sounds blown out in a sense that it sounds too bright and doesn't sound dynamic enough.

Booting into Windows, the audio sounds fine. Also in Windows we have the option to use "Performance" mode which sends more impedence to the headphone. Most likely the AppleALC is using this mode automatically with no way to change it?

**Comment by Andrey1970AppleLife** [comment]
In macOS you hear a original sound, not spoiled by improvers.

**Comment by izo1** [comment]
@Andrey1970AppleLife I understand, but it sounds muddy and not correct. I tried 3 headphones.

Bluetooth headphones work fine and are clean.

**Comment by Andrey1970AppleLife** [comment]
If you are sure that a problem of Resources for your codec, address for support on forums.
