### ISSUE TITLE
Request: linux build of macserial

### ISSUE THREAD

**Issue by tandy-1000** [acidanthera/bugtracker#1411]
I saw an issue in the old MacInfoPkg repo which said this was solved but there is not linux build for macserial in the new release.
If this is possible I think it would be helpful and would save linux users time.
Thank you.

**Comment by dreamwhite** [comment]
Have you tried downloading the latest Linux artifacts available from OpenCorePkg? 

Basically you need to open the Actions page of OpenCorePkg, select the latest commit build and at the bottom of the page select your desired build type (in your case `Linux CLANGPDB/GCC5 Artifacts` or  `Linux CLANG38 Artifacts`).

![image](https://user-images.githubusercontent.com/17933708/103697808-baaa0b80-4fa0-11eb-8fe0-7e02b8cdf597.png)
