### ISSUE TITLE
[WhateverGreen] macOS Big Sur HEVC encoder

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1412]
Hi there,
I don't know if this can be considered as a bug, but today I noticed that on macOS Big Sur, HEVC encoder doesn't work if I specify `AAPL,slot-name` property on my iGPU patch.

![image](https://user-images.githubusercontent.com/17933708/103690586-3dc56480-4f95-11eb-9b13-3d010936f464.png)

The only way to get HEVC encoder work is removing the above property:

![image](https://user-images.githubusercontent.com/17933708/103690712-6c433f80-4f95-11eb-8c5c-136db43bb2c5.png)

Is this a bug of WhateverGreen that handles differently HEVC on Big Sur?
Given that I don't care much about it, but I'm just curious about this strange bug.
Thanks for any clarifications

**Comment by vit9696** [comment]
AAPL,slot-name is for external GPUs only I believe.
