### ISSUE TITLE
[Question] OpenCore ACPI quirk

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1413]
Why since the latest 0.6.5 this quirk: `ResetLogoStatus`
Is set to True by default, while in the previous releases it was not?

**Comment by 1alessandro1** [comment]
Same question for `FirmwareVolume` in `ProtocolOverrides`

**Comment by vit9696** [comment]
There is no such thing as default in OpenCore. This is just a sample file. Both quirks were enabled because they are commonly needed though.
