### ISSUE TITLE
Can't boot BOOTx64.efi

### ISSUE THREAD

**Issue by tandy-1000** [acidanthera/bugtracker#1414]
I am making this issue as I think there may be a bug.
- I am using OpenCore 0.6.5 DEBUG release and have adjusted the config.plist as explained in `Target` in Configuration.pdf, there is no log as OpenCore cannot be booted.
- I am trying to install Big Sur
- I have followed everything in Dortania's guide relevant to my setup.
- The SSDT-EC.aml was generated using SSDTime and the SSDT-USBX.aml is from [here](https://github.com/dortania/Getting-Started-With-ACPI/tree/master/extra-files/compiled).
- The SMBios was generated using `iMacPro1,1` and GenSMBIOS.
- BIOS settings are adjusted (4G decoding on, CSM, secure / fast boot off).
- I have tried using both the Mac and Linux method to create installation media, problem persists.
- I have tried using `efibootmgr` in linux / `bcfg` in efi shell to create BIOS boot entries to test if this is a BIOS firmware problem.

Specs:
- AsRock B550M ITX/ac (latest BIOS P1.50)
- Ryzen 3600
- 2x8GB Crucial Ballistix 3600
- RX570

EFI partition directory structure:
├── EFI
│   ├── BOOT
│   │   └── BOOTx64.efi
│   └── OC
│       ├── ACPI
│       │   ├── SSDT-CPUR.aml
│       │   ├── SSDT-EC.aml
│       │   └── SSDT-USBX.aml
│       ├── Bootstrap
│       │   └── Bootstrap.efi
│       ├── config.plist
│       ├── Drivers
│       │   ├── HfsPlus.efi
│       │   └── OpenRuntime.efi
│       ├── Kexts
│       │   ├── AirportItlwm.kext
│       │   ├── AppleALC.kext
│       │   ├── AppleMCEReporterDisabler.kext
│       │   ├── Lilu.kext
│       │   ├── RealtekRTL8111.kext
│       │   ├── VirtualSMC.kext
│       │   └── WhateverGreen.kext
│       ├── OpenCore.efi
│       ├── Resources
│       │   ├── Audio
│       │   ├── Font
│       │   ├── Image
│       │   └── Label
│       └── Tools
│           └── OpenShell.efi
└── shellx64.efi

**Comment by vit9696** [comment]
This is not a support forum. Please ask for help in an appropriate place. Thank you.

**Comment by tandy-1000** [comment]
I wasn't asking for support, I thought there may be a problem :/
