### ISSUE TITLE
MaciASL: in versions newer than 1.5.6 error "_UID inside processor declaration must be an integer (found a string)"

### ISSUE THREAD

**Issue by Drovosek01** [acidanthera/bugtracker#1416]
On a computer with a QIYIDA x79 LGA2011 motherboard and an E5-2670v2 processor, I tried extracting DSDT using Hackintool and just running maciasl (as I understood at startup, it displays the real system DSDT).

I used the latest version 1.5.9 to compile to a .aml file and was getting **"_UID inside processor declaration must be an integer (found a string)"** errors.

While searching for a fix for these errors, I found (https://www.insanelymac.com/forum/topic/342153-question-about-a-maciasl-157-release/) that if you use an older version of maciasl 1.5.6, then these errors are not present in DSDT.

**Comment by vit9696** [comment]
Newer ACPI compilers detect more errors. You can either fix the error or downgrade the compiler (e.g. through settings). Works as intended.
