### ISSUE TITLE
BrightnessKeys doesn't work on ASUS Laptop

### ISSUE THREAD

**Issue by bakedpotato191** [acidanthera/bugtracker#1417]
The laptop model is  **ASUS N550JV**. And BrightnessKeys kext does not make FN+F5 or FN+F6 keys functional.
It uses methods _Q0E and _Q0F in it's ACPI for brightness down and brightness up respectively.

Here is the DSDT if that's of any help.
[DSDT.zip](https://github.com/acidanthera/bugtracker/files/5778271/DSDT.zip)

Edit: I should have noted that I tried it in combination with AsusSMC, not sure if they can conflict with each other.

**Comment by nikhil19rathore99** [comment]
Use brightnesskeys.kext from the repo

**Comment by vit9696** [comment]
There is an `MSOS ()` method in this DSDT, which depends on Windows. You need to add `OSI` patches to your DSDT for BrightnessKeys to work. Closing as this is not a support forum.

**Comment by zhen-zen** [comment]
Please always attach you DSDT and SSDTs dump for debugging those issues. `_OSI` patch should guide it to execute `DWBL` method defined in a separate SSDT. Variables there like `BRNC` may block the method like the Thinkpad case but it depends on your specific model.

**Comment by bakedpotato191** [comment]
[acpi.zip](https://github.com/acidanthera/bugtracker/files/5780656/acpi.zip)
Above I have attached my DSDT and SSDTs. And [this](https://github.com/dortania/Getting-Started-With-ACPI/blob/master/extra-files/decompiled/SSDT-XOSI.dsl) is the SSDT-XOSI that I have included in my ACPI folder.

**Comment by zhen-zen** [comment]
Please use MaciASL to obtain current loaded SSDT (SaSsdt) and verify whether it's patched. Double check the `TableSignature` and `OemTableId`.

**Comment by Andrey1970AppleLife** [comment]
> [acpi.zip](https://github.com/acidanthera/bugtracker/files/5780656/acpi.zip)
> Above I have attached my DSDT and SSDTs. And [this](https://github.com/dortania/Getting-Started-With-ACPI/blob/master/extra-files/decompiled/SSDT-XOSI.dsl) is the SSDT-XOSI that I have included in my ACPI folder.
Use patch _OSI -> XOSI and SSDT-XOSI
5F4F5349 -> 584F5349
[SSDT-XOSI.aml.zip](https://github.com/acidanthera/bugtracker/files/5784287/SSDT-XOSI.aml.zip)

**Comment by bakedpotato191** [comment]
Yes, I have both SSDT-XOSI and acpi rename already included.
I've indicated both TableSignature and OemTableId this time, and can confirm that the rename is successful, and yet brightness keys do not work. 
[System_SSDT-4.zip](https://github.com/acidanthera/bugtracker/files/5787672/System_SSDT-4.zip)

**Comment by zhen-zen** [comment]
Sorry for the late reply, can you attach a copy of IOReg as well?

**Comment by bakedpotato191** [comment]
> Sorry for the late reply, can you attach a copy of IOReg as well?

[MacBook Pro 2.zip](https://github.com/acidanthera/bugtracker/files/5824166/MacBook.Pro.2.zip)

**Comment by zhen-zen** [comment]
Things gets confusing here. If you are still interested in further debugging, can you rename the `DWBL` method in `SaSsdt` to `XWBL` and add the following code to a ssdt? After that, please upload the log from debug version of BrightnessKeys and upload its log after pressing `Brightness-`.

```
DefinitionBlock ("", "SSDT", 2, "Debug", "DWBL", 0x00000000)
{
    External (_SB_.CSTE, FieldUnitObj)
    External (_SB_.PCI0.GFX0, DeviceObj)
    External (_SB_.PCI0.GFX0.BRNC, IntObj)
    External (_SB_.PCI0.GFX0.D2AF, MethodObj)
    External (_SB_.PCI0.GFX0.GCDD, MethodObj)
    External (_SB_.PCI0.GFX0.LCDD, DeviceObj)

    Scope (_SB.PCI0.GFX0)
    {
            Method (DWBL, 0, NotSerialized)
            {
                If (BRNC)
                {
                    GCDD ()
                    Local0 = (D2AF (\_SB.CSTE) & One)
                    If ((Local0 == Zero))
                    {
                        Notify (LCDD, 0x02)
                        Return (Zero)
                    }

                    Notify (LCDD, 0x87)
                }
                Else
                {
                    Notify (LCDD, 0x01)
                }

                Return (Zero)
            }
    }
}

```

**Comment by bakedpotato191** [comment]
Before I do that, where is the log file being saved?

**Comment by zhen-zen** [comment]
Also thank you for the feedback.

Actually there are various vendor specific approaches instead of just notifying ACPI device simply. Yours and Thinkpad ones are two typical cases. Under some circumstances, those methods or variables are not configured properly and cause issues. However, for their application in macOS, the `_Qxx` methods rename could just do the job after figured out. This driver is just meant to provide oobe for people with less knowledge in ACPI.
