### ISSUE TITLE
Login window may take a long time to appear with WhateverGreen 1.4.6

### ISSUE THREAD

**Issue by kidonng** [acidanthera/bugtracker#1418]
After upgrading WhateverGreen from 1.4.5 to 1.4.6, the login window may take a long time to appear. After the progress bar goes about a half, the screen turns black and the login window only shows after about two mintues later.

- `EFI` directory with OpenCore

  https://github.com/kidonng/HP-Pavilion-13-Hackintosh/tree/2fe52a7b51dd8433839fc0c43b35e08cc407f5bb/EFI

- OpenCore DEBUG log

  [opencore-2021-01-07-033844.txt](https://github.com/acidanthera/bugtracker/files/5779434/opencore-2021-01-07-033844.txt)

- Lilu DEBUG log

  [Lilu_1.5.0_20.2.txt](https://github.com/acidanthera/bugtracker/files/5779437/Lilu_1.5.0_20.2.txt)

Occasionally the issue doesn't occur. I managed to get OpenCore DEBUG log during a normal boot with WhateverGreen 1.4.6, not sure if it's helpful.

[opencore-2021-01-07-033302.txt](https://github.com/acidanthera/bugtracker/files/5779443/opencore-2021-01-07-033302.txt)

**Comment by vit9696** [comment]
WhateverGreen 1.4.6 changes how backlight management works. Very likely you did not add `enable-backlight-registers-fix` device property (or `-igfxblr`) boot argument when updating.
