### ISSUE TITLE
AppleALC 3223 is not working with BigSur. Please help

### ISSUE THREAD

**Issue by Abbasm234** [acidanthera/bugtracker#1420]
I have AppleALC 3223 and i tried all layout ids but its not working. I checked forums and its not supported. is there any way you can work around and make it supportive? I have 15 dell 7537's and it will be a big help if it works?

**Comment by m0d16l14n1** [comment]
Read AppleALC FAQ section

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by Abbasm234** [comment]
can u tell me how i can use support

**Comment by Abbasm234** [comment]
can u tell me how i can use supprt? any link? > Use forums for support.
