### ISSUE TITLE
Can't build ocvalidate on ARM linux

### ISSUE THREAD

**Issue by AYastrebov** [acidanthera/bugtracker#1421]
Hello @PMheart 

I've tried to build `ocvalidate` util on arm debian and seems like it's not possible at the moment

`
➜  ocvalidate git:(e9325e4) make
cc -c -fshort-wchar -Wall -Wextra -D EFIUSER -Wno-unused-parameter -Wno-implicit-fallthrough -Wno-strict-aliasing -Wno-address -D ENTRY_POINT=main -O3 -I../../User/Include -I../../Include/Acidanthera -I../../Include/Apple -I../../Include/Apple/X64 -I../../Include/Generic -I../../Include/Intel -I../../Include/Microsoft -D NO_MSABI_VA_FUNCS -D OC_TARGET_DEBUG -I../../UDK/MdePkg/Include -I../../UDK/MdePkg/Include/Library -I../../UDK/MdePkg/Include/X64 -I../../UDK/MdePkg/Library/BaseLib -I../../UDK/MdeModulePkg/Include -I../../UDK/UefiCpuPkg/Include -include ../../User/Include/UserPcd.h -include ../../User/Include/UserGlobalVar.h ../../User/Library/UserMisc.c -o Linux_X64/UserMisc.o
../../User/Library/UserMisc.c: In function ‘AsmCpuid’:
../../User/Library/UserMisc.c:57:3: error: impossible constraint in ‘asm’
   asm (
   ^~~
make: *** [../../User/Makefile:230: Linux_X64/UserMisc.o] Error 1
`

I've google aboit it and found, that some assembly inline functions wouldn't work on arm. And here is one:

`
  asm (
    "cpuid\n"
    : "=a" (eax), "=b" (ebx), "=c" (ecx), "=d" (edx)
    : "0" (Index)
    );
  asm("cpuid" : "=a" (max_level), "=b" (ebx), "=c" (ecx), "=d" (edx) : "a" (0));
`

One of the solutions I've found is to use `__get_cpuid` function from `cpuid.h`, but this also seems not valid on arm.

Another option is to adopt google's cpu_features https://github.com/google/cpu_features

As for now, I've just commented this asm code, and `ocvalidate` compiled with no issues

**Comment by PMheart** [comment]
Fixed. Thanks!
