### ISSUE TITLE
BrcmPatchRAM 

### ISSUE THREAD

**Issue by roddy20** [acidanthera/bugtracker#1424]
![Снимок экрана 2021-01-10 в 12 25 20](https://user-images.githubusercontent.com/5681302/104120595-a79c9000-5340-11eb-84c5-ea67c687186b.png)
is it Codeless Kext or not? seems to be working without this binary

**Comment by vit9696** [comment]
It is codeless, just Xcode is bugged and creates dummy files. You do not need to add this binary.

**Comment by Andrey1970AppleLife** [comment]
In codeless kexts in project https://github.com/acidanthera/AirportBrcmFixup there is no such bug.
@lvs1974, maybe you will be able fix building BrcmBluetoothInjector.kext ?

**Comment by roddy20** [comment]
why do we need to build it? it can be edited like a text file or any plist

**Comment by lvs1974** [comment]
@Andrey1970AppleLife: codeless kexts in AirportBrcmFixup are not built, existing folders just included as plugins.

**Comment by vit9696** [comment]
Example thread about the bug: https://developer.apple.com/forums/thread/663739
