### ISSUE TITLE
[OemTableId] Value type clarifications

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1426]
Hi there,
first of all this is not a proper issue, but a doubt I had while analyzing my config.plist.
I was just wondering why can't `OemTableId` value (under `config.plist/ACPI/Delete/0` type can't be a `string` type. 
Is there any reason behind the choice of setting it as a `data` type? How is the field handled while it's a `data` or when it's a `string`? 

I tried booting by changing the type into `string` but I get a loop circa my WiFi card (I read behind tons of lines errors related to `ARPT`).

Can you gently give me explanation behind this weird behavior? 
Thank you so much and have a nice weekend ^^

**Comment by Andrey1970AppleLife** [comment]
Use type specified in Configuration.pdf

**Comment by vit9696** [comment]
Using string will always add trailing `\0` as per OC spec, this is undesired for fixed-size fields.
