### ISSUE TITLE
Work-around to BIOS updates with macOS Big Sur

### ISSUE THREAD

**Issue by khronokernel** [acidanthera/bugtracker#1427]
With macOS Big Sur, Apple will now apply BIOS updates regardless of `run-efi-updater` variable presence. For PCs, [we simply block MultiUpdater.efi](https://github.com/acidanthera/bugtracker/issues/1255) however on legacy Macs running OpenCore with SMBIOS spoofing this is not enough. For some machines, they'll simply soft brick them where a battery removal will easily resolve. With iMac14,x machines, setting a new SMBIOS will actually apply this update and succeed ending with a bricked Mac.

To work around this, setting `BIOSVersion` to `999.000.000` works well enough. Would be ideal to add a new entry to `PlatformInfo -> Generic` for users to easily set custom values without having to build an entirely new SMBIOS table

**Comment by 1alessandro1** [comment]
> With macOS Big Sur, Apple will now apply BIOS updates regardless of run-efi-updater variable presence.

Setting this variable is irrelevant from macOS 11.0 and newer, is this safe to remove if one is willing to use only Big Sur?

**Comment by vit9696** [comment]
Yes.
