### ISSUE TITLE
100% CPU Usages on Lilu 1.5.0

### ISSUE THREAD

**Issue by jk-codes** [acidanthera/bugtracker#1428]
High CPU Usages on Lilu 1.5.0, kernel task 100% all time. on Skylake CPU. 

Tried Reseting NVRAM, Still same issue, but working normal on Lilu 1.4.9..

**Comment by vit9696** [comment]
I believe something is just not loading correctly due to a configuration issue. Check kextstat | grep -v apple and make sure all the kexts display correctly and have latest versions. If still broken, send a commit causing the regression for you.

**Comment by jk-codes** [comment]
Everything loaded.. still same,,

Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
   48   13 0                  0x2d000    0x2d000    as.vit9696.Lilu (1.5.1) E8AA3018-59BE-3280-BF1F-29D3FF01D255 <8 6 5 3 2 1>
   49    0 0                  0xd000     0xd000     org.acidanthera.NVMeFix (1.0.5) CEFD71D7-1311-3FA5-ACA8-CF68934D1F78 <48 8 6 5 3 2 1>
   50    0 0                  0x82000    0x82000    as.vit9696.WhateverGreen (1.4.7) 0FF618EF-5B25-31B4-84A7-0748D475F871 <48 14 8 6 5 3 2 1>
   51    0 0                  0x16e000   0x16e000   as.vit9696.AppleALC (1.5.6) E98A728B-43D0-35F0-9AA7-F0020EA6D466 <48 14 8 6 5 3 2 1>
   52    0 0                  0xd000     0xd000     as.lvs1974.AirportBrcmFixup (2.1.2) 8B211103-C85B-3B86-A2C0-49EE207531DF <48 14 8 6 5 3 2 1>
   53    0 0                  0x10000    0x10000    org.vanilla.driver.CPUFriend (1.2.4) 21554D8E-7174-3628-819D-C7356A2D67F1 <48 13 8 6 5 3 2 1>
   54    0 0                  0x10000    0x10000    as.lvs1974.HibernationFixup (1.3.8) A50EAB27-B7A8-38F0-86E7-B18F3D74BD34 <48 8 6 5 3 2 1>
   55    0 0                  0xc000     0xc000     xyz.racermaster.NoTouchID (1.0.4) 6F5D0FD5-E29E-3C2C-8260-EA011DF02D3B <48 8 6 5 3 2 1>
   56    0 0                  0x10000    0x10000    com.rehabman.driver.USBInjectAll (0.7.5) 4AD4F393-AEA2-37D8-BB1A-96837900DE2A <14 13 5 3>
   57    0 0                  0xc000     0xc000     as.lvs1974.BT4LEContinuityFixup (1.1.6) 8E1089B3-1B80-387F-99ED-761068CD3F6B <48 8 6 5 3 2 1>
   58    3 0                  0x1a000    0x1a000    as.vit9696.VirtualSMC (1.2.0) 28E5BE19-2EBB-32A2-B7C6-7A27EFFF0F3D <48 13 8 6 5 3 2 1>
   60    0 0                  0x13000    0x13000    ru.usrsse2.SMCBatteryManager (1.2.0) 95984C99-92A3-3808-A5F1-A229AC9BA3D1 <59 58 48 13 8 6 5 3 2 1>
   61    0 0                  0xf000     0xf000     as.vit9696.SMCProcessor (1.2.0) 097BF571-3449-35D2-95C1-BEAD5CDD3348 <58 48 13 8 6 5 3 2 1>
   70    0 0                  0xa000     0xa000     as.lvs1974.RTCMemoryFixup (1.0.7) 4617D854-A3CA-30A5-8A7C-B51B3D97D789 <48 8 6 5 3 2 1>
   73    0 0                  0xb000     0xb000     org.rehabman.driver.NullEthernet (1.0.6) A38D6C66-B66F-35B8-A11F-29995B4834CD <46 13 6 5 3 1>
   75    2 0                  0x19000    0x19000    as.acidanthera.voodoo.driver.PS2Controller (2.1.8) D337F6C2-74AC-33AC-B960-5955ABFC0324 <13 8 6 5 3 1>
   77    0 0                  0x14000    0x14000    ru.joedm.SMCSuperIO (1.2.0) 76E123B9-2C18-3173-BA48-B0B9A02CC9E7 <58 48 13 8 6 5 3 2 1>
   83    0 0                  0x1b000    0x1b000    com.insanelymac.AtherosE2200Ethernet (2.3.2) D9259D7D-FA6D-340E-BA2E-74BC0B760527 <46 14 6 5 3 1>
  102    0 0                  0xd000     0xd000     as.acidanthera.voodoo.driver.PS2Keyboard (2.1.8) BAB8B0A2-BE4F-39A0-B270-8547B4F3F166 <75 66 8 6 5 3 1>
  103    0 0                  0xb000     0xb000     as.acidanthera.voodoo.driver.PS2Mouse (2.1.8) EB62FE85-CA08-3152-B127-D74AAA58914F <75 66 6 5 3>
  104    0 0                  0xecc000   0xecc000   com.zxystd.IntelBluetoothFirmware (1.1.2) 3BD877FB-7CD5-3E57-A9E8-A0F07BF78140 <22 6 5 3>
  122    0 0xffffff7fa2329000 0x2000     0x2000     com.intel.driver.EnergyDriver (3.7.0) 35E739F9-BF6C-3024-A67C-750711B3FB64 <8 6 5 3>
  157    0 0xffffff7fa240d000 0x5b000    0x5b000    com.paragon-software.kext.VDMounter (1370.2) B5F56D88-1A9D-3ED3-BA4A-AEF9F318AA54 <30 6 5 3 1>
  164    0 0xffffff7fa2497000 0x40000    0x40000    com.paragon-software.filesystems.ntfs (106.5.15) 4575C073-7080-3B2F-AF62-A365668ACD34 <8 6 5 1>
  169    0 0xffffff7fa246f000 0x1f000    0x1f000    com.intel.kext.intelhaxm (7.6.1) 3CCC6557-CCBD-37CA-8AC4-271686ADAD2F <8 6 5 3 1>

**Comment by vit9696** [comment]
Like I said please find the commit of the relevant kext that causes issues for you. You can find binary builds here https://dortania.github.io/builds/.

**Comment by jk-codes** [comment]
this commit.
https://dortania.github.io/builds/?product=Lilu&viewall=true&version=1.5.1&sha=d107554ba778009afee29a255cc40637de5cce9d

**Comment by vit9696** [comment]
I.e. `2c1c67e0f0aee648d11f69dbec70605f12b504de` works fine?

**Comment by jk-codes** [comment]
no. 
its working fine. https://dortania.github.io/builds/?product=Lilu&viewall=true&version=1.4.9&sha=7310c23f1f97b35e70e864a0b8f0c282f6617dfd

**Comment by vit9696** [comment]
In case it is not clear, I am asking you to find a first not working commit, and a last working one.

**Comment by jk-codes** [comment]
tried all latest...
this is the last working..
https://github.com/acidanthera/Lilu/commit/63f37bfe62a927da2b601e0c0df769f9446af6d2

**Comment by vit9696** [comment]
- Right, so https://github.com/acidanthera/Lilu/commit/d70aa5a237742a655ad2a706f490f1de85fe55e4 is the first one that breaks things?
- Are you sure that all plugins load with this one and the one before?
- Is it both on Big Sur and Catalina?
- Are the installed plugins relevant? I.e. if you like just Lilu and VirtualSMC kext, will it cause high CPU usage?

**Comment by jk-codes** [comment]
- yes @d70aa5a is the first breaking. 
- Only On big sur, No problem in high sierra. 
- Only Lilu making this issue.

**Comment by jk-codes** [comment]
still no changes.. tried both...
i notice something on every breaking commit stuck/delay on something at startups.

-busy timeout[0], (60s): 'IODisplayWrangler'
tx_flush:1074: disk1............
- busy timeout[1], (60s): 'IODisplayWrangler'
- busy timeout[2], (60s): 'IODisplayWrangler'

**Comment by vit9696** [comment]
1. You did not answer my first question.
2. Also try these. [Lilu-1.5.1-DEBUG-r2.zip](https://github.com/acidanthera/bugtracker/files/5820691/Lilu-1.5.1-DEBUG-r2.zip) [Lilu-1.5.1-RELEASE-r2.zip](https://github.com/acidanthera/bugtracker/files/5820694/Lilu-1.5.1-RELEASE-r2.zip)
3. Create debug log via `liludump=60 -liludbgall` with https://github.com/acidanthera/Lilu/commit/63f37bfe62a927da2b601e0c0df769f9446af6d2 and https://github.com/acidanthera/Lilu/commit/d70aa5a237742a655ad2a706f490f1de85fe55e4

**Comment by LeBobPoilu** [comment]
Sorry to write here - but same issue with Lilu 1.5 on my laptop : Big Sur boot
very slow (busy timeout[1], (60s): 'IODisplayWrangler') and CPU running at max frequency -
Ok when revert to 1.4.9

Here is  Lilu-1.5.1-DEBUG-r2.zip  log in case this is the same issue
[Lilu_1.5.1_20.2.txt](https://github.com/acidanthera/bugtracker/files/5820913/Lilu_1.5.1_20.2.txt)

**Comment by jk-codes** [comment]
Here is my  Lilu-1.5.1-DEBUG-r2.zip  log>
 
[Lilu_1.5.1_20.3 debug.txt](https://github.com/acidanthera/bugtracker/files/5821131/Lilu_1.5.1_20.3.debug.txt)

Debug of @63f37bf > 
[Lilu_1.5.0_20.3bf_not_working.txt](https://github.com/acidanthera/bugtracker/files/5821136/Lilu_1.5.0_20.3bf_not_working.txt)

Suddenly again **63f37bf** not working this time.
so i took previous one. **575bd85** Debug log>
[Lilu_1.5.0_20.3_working.txt](https://github.com/acidanthera/bugtracker/files/5821153/Lilu_1.5.0_20.3_working.txt)

**Comment by vit9696** [comment]
Right, what we have here is basically a race condition, sometimes your video kexts seem start earlier, sometimes they start later, and very possibly Lilu patches apply after the code actually executed. The issue is more apparent with the latest Lilu version, but there is no direct change here. It is just that the code executes at different speed due to the changes rather than the issue in Lilu itself.

The initialisation order depends on the kexts injected and their order, logging/verbosity, devices present, ACPI tables, etc. I suspect you have something wrong with ACPI indeed. Perhaps the IRQs or device naming. Hard to say to be sure. I am afraid you will have to explore it on your own.

I wonder if trying to add a workaround on WEG side to process kexts earlier would actually work, but I would not have too many hopes about it. Please try (with the latest Lilu) [WhateverGreen-1.4.7-RELEASE.zip](https://github.com/acidanthera/bugtracker/files/5822893/WhateverGreen-1.4.7-RELEASE.zip)

**Comment by LeBobPoilu** [comment]
Have tried WhateverGreen-1.4.7-RELEASE with Lilu 1.5 -> same issues
Big Sur graphics are worst : freezes and lags when opening / moving the finder

**Comment by vit9696** [comment]
Hmm… I *think* it really is a configuration issue on your side. Still, can you update all the kexts to master version and upload the EFI folder?

**Comment by LeBobPoilu** [comment]
Hardware is Dell Inspiron 5379 - i5-8250U - UHD 620 
Attached a archive with : EFI , pci list devices info, intel power gadget and activity monitor screenshots, OpenCore debug log 
[Archive.zip](https://github.com/acidanthera/bugtracker/files/5824931/Archive.zip)
CPU takes around 1 minute to run at max frequency with Lilu 1.5 after login screen, seems linked to kernel task
Have no program opened by default but dropbox and pcloud drive on session

**Comment by vit9696** [comment]
Hmmm. This looks very involved. BT4LEContinuityFixup.kext is definitely no longer supported and is replaced by a quirk in OpenCore (`ExtendBTFeatureFlags`). There also is an absolutely bizarre amount of kexts, ACPI tables, and patches.

I suggest you:
- to disable all kexts but Lilu.kext, WhateverGreen.kext, and VirtualSMC.kext, then boot and see if you get the high CPU usage issue (you can also leave VoodooPS2Controller.kext and VoodooPS2Keyboard.kext if you have no external USB keyboard).
- to disable all ACPI tables but SSDT-EC-USBX.aml and perhaps SSDT-PNLF.aml if it does not work at all otherwise.
- to disable all ACPI patches

It will then be good to see if the issue persists and try to track it down to a particular element.

**Comment by LeBobPoilu** [comment]
Thanks for your feedback, BT4LEContinuityFixup.kext was the issue
Big Sur boot and CPU frequency are now OK with Lilu 1.5.1 when :
- BT4LEContinuityFixup.kext disable 
- ExtendBTFeatureFlags enable

It is probably the same issue for @jk-codes as the kext appears loaded in post 3

One last question for helping me to understand, is why the issue did not shown up with Lilu 1.4.9  ?

**Comment by vit9696** [comment]
No idea unfortunately, we think something is broken in your setup, and BT4LEContinuityFixup.kext is just a trigger for it. The issue is probably elsewhere, but you will have to debug it on your own if you want.

**Comment by luvletter2333** [comment]
> still no changes.. tried both...
> i notice something on every breaking commit stuck/delay on something at startups.
> 
> -busy timeout[0], (60s): 'IODisplayWrangler'
> tx_flush:1074: disk1............
> 
> * busy timeout[1], (60s): 'IODisplayWrangler'
> * busy timeout[2], (60s): 'IODisplayWrangler'

Exactly the same problem with this log and 100% CPU usage by kernel_task, I found the following information in OpenCorePkg's change log.

This problem occurs when I was doing a routine OpenCore update, OpenCore and all other kexts were updated and Luli was updated from 1.4.9 to the latest (1.5.1).

> Thanks for your feedback, BT4LEContinuityFixup.kext was the issue
> Big Sur boot and CPU frequency are now OK with Lilu 1.5.1 when :
> 
> * BT4LEContinuityFixup.kext disable
> * ExtendBTFeatureFlags enable
> 
> It is probably the same issue for @jk-codes as the kext appears loaded in post 3
> 
> One last question for helping me to understand, is why the issue did not shown up with Lilu 1.4.9 ?

And I will reboot now to see what will happen.

**Comment by luvletter2333** [comment]
FIXED, I don't know why it works at all.

Now my configuration is working flawlessly, and I am trying to undo these actions to see what will happen:

> BT4LEContinuityFixup.kext disable
> ExtendBTFeatureFlags enable

**Comment by luvletter2333** [comment]
![image](https://user-images.githubusercontent.com/31475650/106769766-47b3b380-6678-11eb-8733-e157d06ff31b.png)

![image](https://user-images.githubusercontent.com/31475650/106770118-9bbe9800-6678-11eb-8fd8-d8da082fc33f.png)

reproduced

**Comment by luvletter2333** [comment]
There are also some weird behaviors before I fix it:

1. Lock Screen and then press Esc to close displays. Then press any keys to "wake" it, NO UI but a cursor. Key password in and press Enter, the UI comes back as normal.
2. No password is required when waking from sleep.

I don't know whether they are really related to BT4LEContinuityFixup and Lilu 1.5.0+, but these weird behaviors are gone when removing BT4LEContinuityFixup and enable Quirk.

These two behaviors are not tested in reproduction because I forgot it :(
