### ISSUE TITLE
Trackpad not responsive (VoodooPS2)

### ISSUE THREAD

**Issue by projectoneuniverse** [acidanthera/bugtracker#1429]
Has anyone found a suitable driver for synaptic pointing devices? I have tried the latest voodooPS2 in the opencore configuration OpenCore 0.6.5 , all multi gestures are working fine, but not responsive, then I tried 2018 version of voodooPS2 it runs quite responsive, but the multi-gesture doesn't work.

and thank you for developing this driver

Notebook:
Model: MSI GP62MVR Leopard
Core i7 - 7700HQ
Intel HD630& GTX 1060 6gb

Below are the specifications of my trackpad:

![image](https://user-images.githubusercontent.com/50221511/104311908-74a4f880-5508-11eb-8f71-47aa4e27348c.png)

**Comment by vit9696** [comment]
This is not a support forum, closing.
