### ISSUE TITLE
emulated NVRAM does save nvram.plist anymore

### ISSUE THREAD

**Issue by punjabigator** [acidanthera/bugtracker#1431]
I have tried running command as described [Here](https://dortania.github.io/OpenCore-Post-Install/misc/nvram.html#verifying-if-you-have-working-nvram). It used to work in 0.63, however, stopped working in 0.65. I re-ran the logouthook command but no success. Currently, no NVRAM.plist is saved or created during shutdown. Any solution or support will be greatly appreciated.

**Comment by vit9696** [comment]
Run `xattr -cr /path/to/OpenCore.zip` before using the utilities from it maybe. Make sure that you copied all the utilities from LogoutHook directory to the installation folder if you do that manually. You can also check the output and return code of LogoutHook.command by running it in terminal. Closing as support request, saving NVRAM works fine. CC @khronokernel

**Comment by punjabigator** [comment]
thank you vit9696, and I was missing NVRAMDUMP and readme file. I copied both files to the folder and reran the command, and I believe nvramdump was the culprit. NVRAM.plist was created during shutdown. Appreciated a quick response very much.
