### ISSUE TITLE
Ice Lake questions and problems.

### ISSUE THREAD

**Issue by m0d16l14n1** [acidanthera/bugtracker#1432]
Hello! 
I have an Ice Lake laptop, "supported" one - i7 with G7 graphics. I found out that -igfxmlr and -igfxblr are working strangely. With latest one - i am not sure if i really need that, because i previously have no problems with brightness (some guys with Ice Lake had issues with dimming screens on first boot before sleep). So, that -igfxblr is not the case for, so i will just ignore that and delete boot-arg. 

So, i have two questions-issues related to Ice Lake. 

But with MLR i find some strange stuff. On some ig-platform-ids it won't boot at all (reboots before Apple logo appears), on some of them it will boot to black screen (the screen is just off, because i was trying to see something using flashlight, but the screen seems to be totally off). And on some ids it will actually boot, but logs are strange. 

Just an example from log. 
`[   46.144240]: WhateverGreen      igfx: @ (DBG) MLR: [COMM] wrapReadAUX() Maximum link rate 0x00 has been set in the DPCD buffer.
[   46.144253]: WhateverGreen      igfx: @ (DBG) MLR: [ICL+] wrapReadAUX() Called with port at 0xffffff937e3ab000.
[   46.144257]: WhateverGreen      igfx: @ (DBG) MLR: [COMM] orgReadAUX() Routed to ICL IMP with Address = 0x400; Length = 12.
[   46.145220]: WhateverGreen      igfx: @ (DBG) MLR: [ICL+] wrapReadAUX() Called with port at 0xffffff937e3ab000.
[   46.145225]: WhateverGreen      igfx: @ (DBG) MLR: [COMM] orgReadAUX() Routed to ICL IMP with Address = 0x0; Length = 6.
[   46.145462]: WhateverGreen      igfx: @ (DBG) MLR: [COMM] GetFBIndex() Port at 0xffffff937e3ab000; Framebuffer at 0xffffffa03f1f1000.
[   46.145468]: WhateverGreen      igfx: @ (DBG) MLR: [COMM] wrapReadAUX() Will probe the maximum link rate from the table.
[   46.145472]: WhateverGreen      igfx: @ (DBG) MLR: [COMM] orgReadAUX() Routed to ICL IMP with Address = 0x700; Length = 1.
[   46.145709]: WhateverGreen      igfx: @ MLR: [COMM] ProbeMaxLinkRate() eDP version is less than 1.4. Aborted.
[   46.145713]: WhateverGreen      igfx: @ (DBG) MLR: [COMM] wrapReadAUX() Maximum link rate 0x00 has been set in the DPCD buffer.`

I also see that in log:

`[   28.679430]: WhateverGreen      igfx: @ FCM: Failed to route the function hwRegsNeedUpdate.
[   28.721381]: WhateverGreen      igfx: @ BSF: Failed to route the function ComputeLaneCount.
`

I will attach logs of WEG and Lilu, in case it might help. 
Also will attach gen_debug/darwin dumper logs.

[DarwinDumper_3.1.1_2021.01.14_00.39.39_MacBookAir9,1_Opencore_4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version	DBG-066-2021-01-09_Unknown_20D5029f_b0ltun.zip](https://github.com/acidanthera/bugtracker/files/5809242/DarwinDumper_3.1.1_2021.01.14_00.39.39_MacBookAir9.1_Opencore_4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102.opencore-version.DBG-066-2021-01-09_Unknown_20D5029f_b0ltun.zip)
[debug_27340.zip](https://github.com/acidanthera/bugtracker/files/5809241/debug_27340.zip)
[weg+lilu.zip](https://github.com/acidanthera/bugtracker/files/5809243/weg%2Blilu.zip)

The second one is about that "boot screen" glitch (i have already opened issue about that). I was just playing around AppleIntelICLLPGraphicsFramebuffer.kext and was trying to capture logs to get that issue properly. So, on boot, while screen is black (or glitching), i can see that in logs: 

`2021-01-11 21:45:39.12 kernel[0]: (AppleIntelICLLPGraphicsFramebuffer) [IGFB][LOG  ][DISPLAY   ] hwEnableUnderrunInterrupts: Enabling underrun interrupts
2021-01-11 21:45:40.12 kernel[0]: (AppleIntelICLLPGraphicsFramebuffer) [IGFB][LOG  ][DISPLAY   ] hwEnableUnderrunInterrupts: Enabling underrun interrupts
2021-01-11 21:45:41.60 kernel[0]: (AppleIntelICLLPGraphicsFramebuffer) [IGFB][LOG  ][DISPLAY   ] hwEnableUnderrunInterrupts: Enabling underrun interrupts
2021-01-11 21:45:42.66 kernel[0]: (AppleIntelICLLPGraphicsFramebuffer) [IGFB][LOG  ][DISPLAY   ] hwEnableUnderrunInterrupts: Enabling underrun interrupts
2021-01-11 21:45:44.16 kernel[0]: (AppleIntelICLLPGraphicsFramebuffer) [IGFB][LOG  ][DISPLAY   ] hwEnableUnderrunInterrupts: Enabling underrun interrupts
2021-01-11 21:45:46.48 kernel[0]: (AppleIntelICLLPGraphicsFramebuffer) [IGFB][LOG  ][DISPLAY   ] hwEnableUnderrunInterrupts: Enabling underrun interrupts
2021-01-11 21:45:48.28 kernel[0]: (AppleIntelICLLPGraphicsFramebuffer) [IGFB][LOG  ][DISPLAY   ] hwEnableUnderrunInterrupts: Enabling underrun interrupts`

Also i see something similar too when i enabled HiDPi and screen is blinking if i don't put laptop on sleep-wake cycle. After that it's working with HiDPi with no issues at all. 

`Display Pipe Underrun occurred on pipe`

That's what i found in kext itself. 

```
AppleIntelFramebufferController::hwEnableUnderrunInterrupts
AppleIntelFramebufferController::hwDisableUnderrunInterrupts
AppleIntelFramebufferController::checkForDisablingUnderrunInterrupt
```

Except that i also found this: 

`"[IGFB][LOG  ][%-10s] Underrun boot flag is set . Underruns are enabled \n",
      "DISPLAY"`

Is it correct, that there is some "boot flag" which can enable those underruns? I am just trying to find that boot flag for testing purposing, i didn't find it myself actually. 
I am not a programmer, so sorry if it looked for you stupidly.  I just took kext from system, "decompiled" it and just was looking for something similar in it from my logs.

**Comment by vit9696** [comment]
> Is it correct, that there is some "boot flag" which can enable those underruns? I am just trying to find that boot flag for testing purposing, i didn't find it myself actually.

It is `ig` boot argument parsed in `__ZN31AppleIntelFramebufferController5startEP9IOService`. Needs to have any of the `0x30` bits set to enable underruns.

I assume this is rather a discussion, so closing. CC @0xFireWolf

**Comment by m0d16l14n1** [comment]
> > Is it correct, that there is some "boot flag" which can enable those underruns? I am just trying to find that boot flag for testing purposing, i didn't find it myself actually.
> 
> It is `ig` boot argument parsed in `__ZN31AppleIntelFramebufferController5startEP9IOService`. Needs to have any of the `0x30` bits set to enable underruns.
> 
> I assume this is rather a discussion, so closing. CC @0xFireWolf

So, it should be something like `ig=48` or `ig=0x30`? Sorry for that stupid question

**Comment by vit9696** [comment]
Correct, but I don't know if that is going to help any of your issues.

**Comment by m0d16l14n1** [comment]
> Correct, but I don't know if that is going to help any of your issues.

Yep. It seems not to wok, heh. After verbose Apple logo appears and laptop is rebooting

**Comment by m0d16l14n1** [comment]
> Correct, but I don't know if that is going to help any of your issues.

Seems that i used wrong way. Now it's panicking on `Display pipe underrun occurred`

[panic.zip](https://github.com/acidanthera/bugtracker/files/5814714/panic.zip)

**Comment by m0d16l14n1** [comment]
> Also i see something similar too when i enabled HiDPi and screen is blinking if i don't put laptop on sleep-wake cycle. After that it's working with HiDPi with no issues at all.

@vit9696 Sorry for pinging you. Just want to share that HiDPI issues are gone after injecting all that [values](https://github.com/khronokernel/DarwinDumped/blob/master/MacBookAir/MacBookAir9%2C1(2)/Device%20Properties/device-properties.plist) in iGPU path >

[Blank screen on boot](https://github.com/acidanthera/bugtracker/issues/1329) is still not fixed with that :(

**Comment by m0d16l14n1** [comment]
> > Also i see something similar too when i enabled HiDPi and screen is blinking if i don't put laptop on sleep-wake cycle. After that it's working with HiDPi with no issues at all.
> 
> @vit9696 Sorry for pinging you. Just want to share that HiDPI issues are gone after injecting all that [values](https://github.com/khronokernel/DarwinDumped/blob/master/MacBookAir/MacBookAir9%2C1(2)/Device%20Properties/device-properties.plist) in iGPU path >
> 
> [Blank screen on boot](https://github.com/acidanthera/bugtracker/issues/1329) is still not fixed with that :(

Only **AAPL,GfxYTile** needed to get HiDPI working properly
