### ISSUE TITLE
Stuck at Console relocated to

### ISSUE THREAD

**Issue by josemmc95** [acidanthera/bugtracker#1433]
I don't know what's happening. I tried disabling some "extra" kexts like usbinjectall, nullethernet, notouchid, ...

I also added SSDT-CPUR.aml, changed SMBios, and none of them worked.

I leave you here my EFI without kexts and resources folder. All kext are updated to latest version.

It's a Huawei Matebook D 14" with Intel Core i5-10210U and Intel UHD Graphics 620.

Thank you in advanced.

![104190576-92952f00-541c-11eb-8d23-0a99f5b5acbb](https://user-images.githubusercontent.com/62221854/104477771-cc536a80-55c1-11eb-9db9-748655a92154.jpg)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5809720/EFI.zip)

**Comment by telepati** [comment]
Check this Repo;
https://github.com/daliansky/Hackintosh/blob/master/README_en.md#huawei-%E5%8D%8E%E4%B8%BA

**Comment by vit9696** [comment]
This is not a bringup support forum, sorry.
