### ISSUE TITLE
100% CPU Usages on Lilu 1.5.1 

### ISSUE THREAD

**Issue by jk-codes** [acidanthera/bugtracker#1435]
High CPU Usages on Lilu 1.5.0/1.5.1, kernel task 100% all time. on Skylake CPU.

Tried Reseting NVRAM, Still same issue, but working normal on Lilu 1.4.9..

weg, lilu updated  to latest version.

log here all kext loaded. Still broken..

Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
Index Refs Address Size Wired Name (Version) UUID
48 13 0 0x2d000 0x2d000 as.vit9696.Lilu (1.5.1) E8AA3018-59BE-3280-BF1F-29D3FF01D255 <8 6 5 3 2 1>
49 0 0 0xd000 0xd000 org.acidanthera.NVMeFix (1.0.5) CEFD71D7-1311-3FA5-ACA8-CF68934D1F78 <48 8 6 5 3 2 1>
50 0 0 0x82000 0x82000 as.vit9696.WhateverGreen (1.4.7) 0FF618EF-5B25-31B4-84A7-0748D475F871 <48 14 8 6 5 3 2 1>
51 0 0 0x16e000 0x16e000 as.vit9696.AppleALC (1.5.6) E98A728B-43D0-35F0-9AA7-F0020EA6D466 <48 14 8 6 5 3 2 1>
52 0 0 0xd000 0xd000 as.lvs1974.AirportBrcmFixup (2.1.2) 8B211103-C85B-3B86-A2C0-49EE207531DF <48 14 8 6 5 3 2 1>
53 0 0 0x10000 0x10000 org.vanilla.driver.CPUFriend (1.2.4) 21554D8E-7174-3628-819D-C7356A2D67F1 <48 13 8 6 5 3 2 1>
54 0 0 0x10000 0x10000 as.lvs1974.HibernationFixup (1.3.8) A50EAB27-B7A8-38F0-86E7-B18F3D74BD34 <48 8 6 5 3 2 1>
55 0 0 0xc000 0xc000 xyz.racermaster.NoTouchID (1.0.4) 6F5D0FD5-E29E-3C2C-8260-EA011DF02D3B <48 8 6 5 3 2 1>
56 0 0 0x10000 0x10000 com.rehabman.driver.USBInjectAll (0.7.5) 4AD4F393-AEA2-37D8-BB1A-96837900DE2A <14 13 5 3>
57 0 0 0xc000 0xc000 as.lvs1974.BT4LEContinuityFixup (1.1.6) 8E1089B3-1B80-387F-99ED-761068CD3F6B <48 8 6 5 3 2 1>
58 3 0 0x1a000 0x1a000 as.vit9696.VirtualSMC (1.2.0) 28E5BE19-2EBB-32A2-B7C6-7A27EFFF0F3D <48 13 8 6 5 3 2 1>
60 0 0 0x13000 0x13000 ru.usrsse2.SMCBatteryManager (1.2.0) 95984C99-92A3-3808-A5F1-A229AC9BA3D1 <59 58 48 13 8 6 5 3 2 1>
61 0 0 0xf000 0xf000 as.vit9696.SMCProcessor (1.2.0) 097BF571-3449-35D2-95C1-BEAD5CDD3348 <58 48 13 8 6 5 3 2 1>
70 0 0 0xa000 0xa000 as.lvs1974.RTCMemoryFixup (1.0.7) 4617D854-A3CA-30A5-8A7C-B51B3D97D789 <48 8 6 5 3 2 1>
73 0 0 0xb000 0xb000 org.rehabman.driver.NullEthernet (1.0.6) A38D6C66-B66F-35B8-A11F-29995B4834CD <46 13 6 5 3 1>
75 2 0 0x19000 0x19000 as.acidanthera.voodoo.driver.PS2Controller (2.1.8) D337F6C2-74AC-33AC-B960-5955ABFC0324 <13 8 6 5 3 1>
77 0 0 0x14000 0x14000 ru.joedm.SMCSuperIO (1.2.0) 76E123B9-2C18-3173-BA48-B0B9A02CC9E7 <58 48 13 8 6 5 3 2 1>
83 0 0 0x1b000 0x1b000 com.insanelymac.AtherosE2200Ethernet (2.3.2) D9259D7D-FA6D-340E-BA2E-74BC0B760527 <46 14 6 5 3 1>
102 0 0 0xd000 0xd000 as.acidanthera.voodoo.driver.PS2Keyboard (2.1.8) BAB8B0A2-BE4F-39A0-B270-8547B4F3F166 <75 66 8 6 5 3 1>
103 0 0 0xb000 0xb000 as.acidanthera.voodoo.driver.PS2Mouse (2.1.8) EB62FE85-CA08-3152-B127-D74AAA58914F <75 66 6 5 3>
104 0 0 0xecc000 0xecc000 com.zxystd.IntelBluetoothFirmware (1.1.2) 3BD877FB-7CD5-3E57-A9E8-A0F07BF78140 <22 6 5 3>
122 0 0xffffff7fa2329000 0x2000 0x2000 com.intel.driver.EnergyDriver (3.7.0) 35E739F9-BF6C-3024-A67C-750711B3FB64 <8 6 5 3>
157 0 0xffffff7fa240d000 0x5b000 0x5b000 com.paragon-software.kext.VDMounter (1370.2) B5F56D88-1A9D-3ED3-BA4A-AEF9F318AA54 <30 6 5 3 1>
164 0 0xffffff7fa2497000 0x40000 0x40000 com.paragon-software.filesystems.ntfs (106.5.15) 4575C073-7080-3B2F-AF62-A365668ACD34 <8 6 5 1>
169 0 0xffffff7fa246f000 0x1f000 0x1f000 com.intel.kext.intelhaxm (7.6.1) 3CCC6557-CCBD-37CA-8AC4-271686ADAD2F <8 6 5 3 1>

**Comment by vit9696** [comment]
Please do not create duplicate reports and reply in the original one (https://github.com/acidanthera/bugtracker/issues/1428). Next time you do it, you will be banned permanently from accessing acidenthera.
