### ISSUE TITLE
Opencore 0.6.5 stuck on [EB|#LOG:EXITBS:START] on Surface Pro 7 after the recent system firmware update of Surface

### ISSUE THREAD

**Issue by Xiashangning** [acidanthera/bugtracker#1436]
Hello guys, I have been using Big Sur on my sp7 for quite a while and it functions almost perfectly, so I have NOT changed anything in the efi files recently. However, on January 7 Microsoft has released the new firmware updates for Surface Pro 7 and right after the firmware updates, I can no longer boot into Big Sur. I switched to the debug version of OC and it showed that it has stuck on [EB|#LOG:EXITBS:START]... but I didn't changed anything, so I took a look into the Microsoft update information and found that there is an update of Surface UEFI firmware. I guess that is the reason? I have consulted your Troubleshooting part and tried all possible fixes as well as their combinations, none of them worked. I went into the stupidly simple Surface UEFI BIOS and found nothing new nor changed. 
As I haven't changed anything of OC but applied serval firmware updates for my Surface Pro 7, I think maybe this is a problem of incompatibility between Opencore and Microsoft Surface Pro with new firmware? I know this problem is so particular and sorry if my post is inappropriate here. Anyway, I will be very grateful if you guys could spare little time to take a look at this. My EFI file and the boot log are attached below. I am willing to test anything if you could propose any solution.
Thanks!
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5826244/EFI.zip)
[opencore-2021-01-17-213902.txt](https://github.com/acidanthera/bugtracker/files/5826209/opencore-2021-01-17-213902.txt)

**Comment by vit9696** [comment]
The log implies it dies in the kernel. You will have to try different Kernel and Booter quirks to get it work again I am afraid.
