### ISSUE TITLE
Unknown CPU for QQLT and QTJ2

### ISSUE THREAD

**Issue by AYastrebov** [acidanthera/bugtracker#1437]
Similar to https://github.com/acidanthera/bugtracker/issues/1149

Hello! QQLT (engineer coffee lake intel cpu) and QTJ2 (engineer comet lake intel cpu) are recognized as unknown. Maybe it's possible to add them in a list?

The nearest serial equivalent of QTJ2 is i7-10750H
The nearest serial equivalent of QQLT is i7-9750H

[dmidecode_QQLT.txt](https://github.com/acidanthera/bugtracker/files/5826615/dmidecode_QQLT.txt)
[dmidecode_QTJ2.txt](https://github.com/acidanthera/bugtracker/files/5826616/dmidecode_QTJ2.txt)
[machdep_QTJ2.txt](https://github.com/acidanthera/bugtracker/files/5826617/machdep_QTJ2.txt)
[machdep_QQLT.txt](https://github.com/acidanthera/bugtracker/files/5826618/machdep_QQLT.txt)

**Comment by vit9696** [comment]
Nope, not possible. Use `ProcessorType`.
