### ISSUE TITLE
Laptop turns off when the first battery is discharged

### ISSUE THREAD

**Issue by mhl221135** [acidanthera/bugtracker#1438]
Hello i am using this efi <a href="https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/">ThinkPad-T460s-macOS-OpenCore by @simprecicchiani</a> from <a href="https://github.com/simprecicchiani/">@simprecicchiani</a>

My Laptop is t460s/i5 6300u/12gb/Western Digital Black SN750 with dual batteries
I also using <a href="https://github.com/acidanthera/NVMeFix/releases">NVMeFix 1.0.4</a>

My Laptop turns off when the first battery is discharged and then when i power on it again its use second battery

My knowlage in DSDT and SSDT editing is very bad so i asked <a href="https://github.com/simprecicchiani/">@simprecicchiani</a> to implement BATX in his efi

But this problem still exist for me like it be when i use BATC and BATX patches

Now i am testing latest ACPIbattery manager and today this is not troubles with battery so i think maybe its trouble in SMCBatteryManager kext

There is my EFI folder i bad in debugging but if you tell me which steps or logs i should give you i did it, thank you.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5826980/EFI.zip)

Maybe you can help me please, sorry for wrong issue format

**Comment by vit9696** [comment]
SMCBatteryManager, unlike ACPIBattery, does not handle several mistakes in the configuration. See https://github.com/acidanthera/VirtualSMC/blob/master/Docs/Dual%20Battery%20Support.md
