### ISSUE TITLE
BS: Unsupported bootstrap protocol 5 vs 6

### ISSUE THREAD

**Issue by albertofustinoni** [acidanthera/bugtracker#1440]
Updated a one year old installation to release 0.6.5 (redoing config.plist from scratch) and now OpenCore does not even get to the picker.
 
I get the following error messages instead:
```
OC: Setting NVRAM 7C436110-AB2A-4BBB-A880-FE41995C9F82:prev-lang:kbd - Not Found
BS: Unsupported bootstrap protocol 5 vs 6
OC: Boot failed - Unsupported
OCB: StartImage failed - Unsupported
Halting on critical error
```

Double and triple checked to make sure `Boot/BOOTx64.efi`, `OC/OpenCore.efi` and `Bootstrap/Bootsrtap.efi` as well as `Drivers/OpenRuntime.efi` are all from the 0.6.5 release already.

System is an i7 Haswell Chromebox (Asus CN60) with latest MrChromebox firmware installed.

**Comment by vit9696** [comment]
Might be loaded from different folder/drive. The error means booter and opencore have different versions.

**Comment by paulomcnally** [comment]
@vit9696 what is booter? Is a file?

I have same error with 7 vs 6

**Comment by vit9696** [comment]
Booter is e.g. BOOTx64.efi.

**Comment by mikebeaton** [comment]
It's probably completely clear already, but you have not updated _all_ the files, only some of them.

Normally, you can just completely copy the entire directory `X64/EFI` from the unzipped release files (DEBUG or RELEASE version as needed) straight over your `{bootvolume}/EFI` directory (e.g. `/Volumes/efi/EFI` if your boot volume is mounted at `/Volumes/efi`) and this does not overwrite any configuration which you have set up, e.g. `cp -r ~/Downloads/OpenCore-0.7.6-Release/X64/EFI /Volumes/efi`.

You then need to update `config.plist` appropriately, e.g. run `~/Downloads/OpenCore-0.7.6-Release/Utilities/ocvalidate/ocvalidate {bootvolume}/EFI/OC/config.plist` to find out what needs to be changed.
