### ISSUE TITLE
Black screen randomly, login not appear WEG 1.4.6

### ISSUE THREAD

**Issue by baronerosso** [acidanthera/bugtracker#1443]
Black screen randomly, login not appear, PC is working, I can access through SSH.
Ryzentosh AMD 5900x, AsRock x570 Taichi, AMD Sapphire Pulse Radeon RX 5700 XT

In hackintool, when randomly I can login, I can see video card, but not HDMI connector

After login all is working good.

agdpmod=pikera added, but not resolve.

Trying with gfxrst=1, gfxrst=4, igfxonln=1 without success.
[EFI DEBUG.zip](https://github.com/acidanthera/bugtracker/files/5835000/EFI.DEBUG.zip)
[Lilu_1.5.0_20.2.txt](https://github.com/acidanthera/bugtracker/files/5835003/Lilu_1.5.0_20.2.txt)
[opencore-2021-01-19-091143.txt](https://github.com/acidanthera/bugtracker/files/5835005/opencore-2021-01-19-091143.txt)

**Comment by Andrey1970AppleLife** [comment]
We don't support AMD CPU. Use forums for support.
