### ISSUE TITLE
HDACodecDump.efi - wrong node numbers in ConnectionList

### ISSUE THREAD

**Issue by roddy20** [acidanthera/bugtracker#1448]
Linux Dump
Node 0x23 [Vendor Defined Widget] wcaps 0xf00100: Mono
  Connection: 18
     0x11* **0x12 0x13 0x14 0x15 0x16 0x17 0x18** 0x24 0x25 0x38 **0x39 0x3a 0x3b 0x3c 0x3d** 0x20 0x21

HDACodecDump.efi
Node 0x23 [Vendor Defined Widget] wcaps 0xF00100: Mono
  Connection: 8
     0x11 **0x98** 0x24 0x25 0x38 **0xBD** 0x20 0x21

all the other nodes are OK, only 2 or 3 seem to be wrong

[Codec1-hex.txt.zip](https://github.com/acidanthera/bugtracker/files/5843551/Codec1-hex.txt.zip)
[codec_dump_analog_7.1.txt.zip](https://github.com/acidanthera/bugtracker/files/5843553/codec_dump_analog_7.1.txt.zip)

CC @GoldFish64

**Comment by vit9696** [comment]
Related discussion in https://github.com/acidanthera/OpenCorePkg/commit/c6509d41c4d00e09c7a772ed64cc82f39fd16f42

**Comment by Goldfish64** [comment]
@roddy20 Please test with this build of the driver:
[AudioDxe.efi.zip](https://github.com/acidanthera/bugtracker/files/5861486/AudioDxe.efi.zip)

**Comment by roddy20** [comment]
Thanks
with this build of the driver:

Node 35 [Vendor Defined Widget] wcaps 0xF00100: Mono
  Connection: 8
     17 18 19 20 21 22 23 24

[codecdump.txt.zip](https://github.com/acidanthera/bugtracker/files/5861684/codecdump.txt.zip)

**Comment by roddy20** [comment]
> @roddy20 Please test with this build of the driver:
> [AudioDxe.efi.zip](https://github.com/acidanthera/bugtracker/files/5861486/AudioDxe.efi.zip)

seems to be OK
my layout does not use Vendor Widget, so I cannot check if it really works
but now it is connected to nodes listed in the datasheet

**Comment by Goldfish64** [comment]
Can you upload a dump with the new driver?

**Comment by roddy20** [comment]
> Can you upload a dump with the new driver?

[codecdump.txt.zip](https://github.com/acidanthera/bugtracker/files/5862463/codecdump.txt.zip)

**Comment by Goldfish64** [comment]
Please test with the following build. There should be some extra debug output from the driver during load.

[AudioDxe.efi 2.zip](https://github.com/acidanthera/bugtracker/files/5862567/AudioDxe.efi.2.zip)

**Comment by roddy20** [comment]
> Please test with the following build. There should be some extra debug output from the driver during load.
> 

[driverload.txt.zip](https://github.com/acidanthera/bugtracker/files/5862612/driverload.txt.zip)
[hdacodecdump_01.txt.zip](https://github.com/acidanthera/bugtracker/files/5862613/hdacodecdump_01.txt.zip)

**Comment by Goldfish64** [comment]
Please test with the following OpenCore.efi and AudioDxe.efi using the SysReport function.

[Archive.zip](https://github.com/acidanthera/bugtracker/files/5862694/Archive.zip)

**Comment by Goldfish64** [comment]
Fixed in https://github.com/acidanthera/OpenCorePkg/commit/9a2c42e825cefbd53ea30166939fd80560edb726.
