### ISSUE TITLE
ThinkPad X240 ClickPad/TrackPoint buttons not working

### ISSUE THREAD

**Issue by itsmevjnk** [acidanthera/bugtracker#1449]
I just installed macOS Big Sur (11.1 20C69) on my ThinkPad X240 (with the evil ClickPad that is a giant touchpad with what seems to be a single button underneath for everything). With the ClickPad SSDT everything is working relatively nice, however, all the buttons (including the top 3 buttons for TrackPoint and the bottom 2 for the touchpad) are not working. When I click on them to open apps in the Dock, I would get a "No Available Windows" screen.
I am currently on the latest (2.2.0) release of VoodooPS2. I've tried using [another version of VoodooPS2](https://github.com/acidanthera/bugtracker/files/4146635/VoodooPS2Controller.kext.zip) as suggested in #690 but to no avail.

**Comment by 1alessandro1** [comment]
have you tried to enable tap to click instead of pressing (which can trigger Exposé)?

![image](https://user-images.githubusercontent.com/46293832/105418673-cdc60800-5c3d-11eb-980b-de1a9119c245.png)

**Comment by itsmevjnk** [comment]
Tap to click is working, but I want to be able to press for left and right click and scroll with TrackPoint like on Windows.

**Comment by mirifi2k** [comment]
Similar issue here, trackpad buttons (2 buttons) are not working on my laptop (Lenovo G50-70). Other than that, everything seems to work.

**Comment by vit9696** [comment]
Usually needs a configuration profile in ACPI. Check docs.

**Comment by itsmevjnk** [comment]
> Usually needs a configuration profile in ACPI.
Yep, I have done that (otherwise TrackPoint wouldn't even work). That didn't fix the issue.

**Comment by Lorys89** [comment]
> > Usually needs a configuration profile in ACPI.
> 
> Yep, I have done that (otherwise TrackPoint wouldn't even work). That didn't fix the issue.
use this https://github.com/VoodooSMBus/VoodooRMI and solve your problem ;)
