### ISSUE TITLE
Smart Sound Technology Audio Controller not work in comet lake

### ISSUE THREAD

**Issue by Speeedo83** [acidanthera/bugtracker#1451]
In the Dell Inspiron 5491 2 in 1 i7 10510u no internal microphone Smart Sound Technology Audio Controller works.
Send my dump audio from linux and my EFI.
Codec ALC236 And Intel smart sound technology
[codec dump mario.txt](https://github.com/acidanthera/bugtracker/files/5860809/codec.dump.mario.txt)
[EFI Dell 5491.zip](https://github.com/acidanthera/bugtracker/files/5860811/EFI.Dell.5491.zip)

**Comment by vandroiy2013** [comment]
Use forums for support. We are not making or fixing resources.

**Comment by Speeedo83** [comment]
I don't see a link to the forum, can you tell me? Thanks

**Comment by vandroiy2013** [comment]
[https://github.com/acidanthera/AppleALC#support-and-discussion](url)
