### ISSUE TITLE
OpenCore install stuck on restart loop for big sur

### ISSUE THREAD

**Issue by Amrkamel1** [acidanthera/bugtracker#1453]
HI there, i have been trying to install big sur on my acer helios 300 2020, for over a week now but no success, i have followed the opencore latest version guide step by step and i dont know what im missing there that keep the log going fast then restart without catching the error with my eyes

You can find my EFI in the attachment below
https://www.mediafire.com/file/nsgna6s22o8lfxv/EFI.zip/file

here you can find my laptop specs

Acer helios 300 2020 📷redator PH315-53
Product Type Killer E2600 Gigabit Ethernet Controller
Nvidia RTX 2060
Product Type Killer(R) Wi-Fi 6 AX1650i 160MHz Wireless Network Adapter 
USB 3.1 eXtensible Host Controller - 1.10 (Microsoft)
Processor Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)

![image](https://user-images.githubusercontent.com/32042806/105745668-d15bd680-5f3e-11eb-9dc4-b7507867ac77.png)

**Comment by meteoro** [comment]
I have changed: SecureBootModel to Disabled and loop stop.

**Comment by vit9696** [comment]
Need to format the drive in APFS first.

**Comment by Amrkamel1** [comment]
> Need to format the drive in APFS first.
I have set sb to be Disabled restart loop stopped but now im getting this

![Uploading 20210127_134101.jpg…]()

**Comment by Nader27** [comment]
@Amrkamel1 did you manage to install it ?!
