### ISSUE TITLE
Request: boot arg to disable AirPortBrcm4360_Injector: -ArPrtBrcm4360njctrOff (more straight forward & user-friendly)

### ISSUE THREAD

**Issue by LeeBinder** [acidanthera/bugtracker#1454]
Hi acidanthera. First of all a big THANK YOU for all your marvelous work!!

I'm writing to you in regards to https://github.com/acidanthera/AirportBrcmFixup#please-pay-attention

Yes, the 'MaxKernel 19.9.9' hack in OC works. My kind proposal to you would be to make this less geeky/ awkward, also in line with how you already handle switching the entire kext off via -brcmfxoff

How about that? Makes sense/ feasible :) ?

Take care
Lee

**Comment by 1alessandro1** [comment]
What about deleting the injector?

**Comment by vit9696** [comment]
Not a hack, in line with the design.

**Comment by LeeBinder** [comment]
OK, fair enough.
