### ISSUE TITLE
Null config

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1455]
Is there any way that it would make sense to look for a 'null' config for OpenCore?

I'm specifically thinking of running OpenCore on Apple hardware, where logically the Apple bootloader has already run and so the hardware and firmware is already in a state where at least a supported OS can run immediately with no kexts or patches, and no quirks modifications.

Is there such a thing as a 'null' config of OC that would reflect that - i.e. meaning "boot through OC but don't change anything"? The way I'm thinking about this, the purpose of this would be to then apply just a little bit of the (very useful!) OpenCore magic (specifically, of course, for the purpose of booting a newer OS on older hardware) - e.g. on some machines this might be just upgrading the product and board id and nothing else, or just upgrading those two and adding a Wi-Fi patch, but nothing else. Is it possible to do this, or do I basically have to configure all the other aspects, even though - in some sense - they are already correctly configured before OC starts, when I'm on Apple hardware?

**Comment by vit9696** [comment]
If you mean automated, then no, sorry. We can consider making something like SampleNull.plist, where all the preferences will be set to failsafe, however. For this to happen we would request a PR.

**Comment by Bmju** [comment]
Many thanks. I wasn't clear if leaving all the preferences at their failsafe values _would_ effectively give the result I'm asking for. (Whether it would be safe, whether it would boot as I intended - or whether some of the failsafes would probably result in different behaviour from what the BIOS would have done with no OC inserted.) If "all failsafes" (intentionally? officially?) does what I want, then that would be the answer I needed.

**Comment by vit9696** [comment]
Failsafe values are meant to do nothing to your system, but certain security settings are intentionally chosen for maximum security.

**Comment by 1alessandro1** [comment]
>  We can consider making something like SampleNull.plist, where all the preferences will be set to failsafe, however. 

* Is this lean `config.plist` (with everything absolutely necessary) planned to be released?
* Are there somewhere the minimum required fields required by OpenCore for a config to be valid?

**Comment by vit9696** [comment]
- Hard to say, more I think of it, more I am not sure whether this concept works at all. Perhaps it is best o leave this to third-party projects.
- Configuration.pdf and ocvalidate. Nothing better as it is all subjective.

**Comment by Bmju** [comment]
In case anybody else turns up here looking for this, the first page of [this Macrumors thread](https://forums.macrumors.com/threads/opencore-on-the-mac-pro.2207814/) (which is already linked from the main OpenCore [README](https://github.com/acidanthera/OpenCorePkg)) gives pretty much exactly what I was looking for when asking about this.

Part I - Basic Installation gives an OC config which (at least as I currently understand it) works, is safe and importantly doesn't add anything, on any Mac (not just a Mac Pro, as you might think from an initial reading). Aspects of Part II onwards (especially the specific patches applied) are specific to the Mac Pro, but a lot of it still isn't.
