### ISSUE TITLE
OC: PlatformInfo/Generic/MLB + SystemSerialNumber undocumented 'OEM specified' behaviour

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1456]
When using `PlatformInfo/Automatic` = `true`, if `PlatformInfo/Generic/MLB` or `PlatformInfo/Generic/SystemSerialNumber` are missing then they behave as expected, and as explicitly described in `Configuration.pdf`, namely the runtime values are the expected failsafes `OPENCORE_MLB_SN11` and `OPENCORE_SN1`.

However, apparently undocumented, but highly useful, is that if either of the above is set to an empty string (`<string></string>`) rather than missing, then the runtime value ends up being the original OEM specified value for the respective id.

This is similar to (and perhaps related to) the explicitly documented behaviour for missing values for `PlatformInfo/SMBIOS/BoardSerialNumber` and `PlatformInfo/SMBIOS/SystemSerialNumber`, but I cannot see anything in the documentation for this specific behaviour with empty strings for the `Generic` settings, nor for the fact that different (and both useful) failsafes can be obtained by missing key vs. empty string in the `Generic` settings.

If it comes to it, I would definitely vote to document and keep rather than remove this behaviour on empty string values. It is in use in at least one active (and useful) config in the wild, namely @jacklukem 's sideloader.

**Comment by Bmju** [comment]
Full relevant config section below; on looking at this again, I'm noting that `BoardProduct` is being used from this config (i.e. it is specified and it works), even though the current documentation seems to state that the `SMBIOS` section is not used if `Automatic` = `true`.

Without being too speculative, if - as it seems? - the `SMBIOS` section is being read and used after the `Generic` section in this case then FWIW may I note again that the current behaviour is in use (not just by me!) and useful.

I do understand that if this is all built on undocumented behaviour then it is _caveat emptor_, on the other hand the following features would remain useful:

 - Officially be able to use OEM specified MLB and SystemSerialNumber in `Generic` section (via blank string as now?)
 - Officially be able to specify `BoardProduct` when using `Automatic` = `true` (which is currently possible using the `SMBIOS` section, but the docs as I am reading them imply this should not work)

```
        <key>PlatformInfo</key>
        <dict>
                <key>Automatic</key>
                <true/>
                <key>UpdateDataHub</key>
                <false/>
                <key>UpdateNVRAM</key>
                <false/>
                <key>UpdateSMBIOS</key>
                <true/>
                <key>UpdateSMBIOSMode</key>
                <string>Create</string>
                <key>Generic</key>
                <dict>
                        <key>MaxBIOSVersion</key>
                        <true/>
                        <key>MLB</key>
                        <string></string>
                        <key>SystemProductName</key>
                        <string>iMac15,1</string>
                        <key>SystemSerialNumber</key>
                        <string></string>
                </dict>
                <key>DataHub</key>
                <dict/>
                <key>PlatformNVRAM</key>
                <dict/>
                <key>SMBIOS</key>
                <dict>
                        <key>BoardProduct</key>
                        <string>Mac-42FD25EABCABB274</string>
                </dict>
        </dict>
```

**Comment by vit9696** [comment]
Consistency is kind of important here, but I agree that the behaviour is indeed useful. I dropped it the other way around: if the values are not set (undefined behaviour, invalid configuration) or set to empty/all zero, then the original values are left unmodified.

@khronokernel I wonder if this may be useful for https://github.com/dortania/Opencore-Legacy-Patcher
