### ISSUE TITLE
Documentation Note

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1461]
Section 3.4 has a new entry as follows:
`Do not prefix private static functions, but use Internal for non-static.`

There are two phrases: ("We/Us" = Your Readers)
* "Do not prefix private static functions"
  * Clearly sets the subject and we know you are talking about "STATIC" functions that are "PRIVATE"
  * Side issue: Are some "STATIC" functions "NON-PRIVATE"?
* "but use Internal for non-static"
  * You are talking about "NON-STATIC" functions that are not clearly stated to be "PRIVATE" or "NOT PRIVATE"
  * We just know they are "NON-STATIC" functions
  * We can "ASSUME" you mean "PRIVATE" but this technical document should not require us to assume intention.

Secondary Issue is that "INTERNAL" should be quoted or somehow emphasised ... Also applies to "OC" earlier.

Side question on my part is what exactly is a Private Function?
Would have expected that all such would need to be "STATIC" but reading between the lines, it appears some may not be so and that some "STATIC" functions are "NON-PRIVATE". Might be off topic but lost on that.

**Comment by vit9696** [comment]
* Private function is a function local to the module. I.e. not exposed as an interface. Can be both static (local to file) and non-static (local to a set of files).
* Static functions can be non-private, e.g. when they are declared in the interface header (usually static inline). Should not be allowed in EDK II, but the doc make things extra clear.

Feel free to let me know if anything is still unclear.
