### ISSUE TITLE
Lost HDMI audio after hibernation in 10.14+

### ISSUE THREAD

**Issue by leon9078** [acidanthera/bugtracker#1462]
So I have working hibernation with RTC (both 2 banks of memory available), and I can succesfully resume without facing a black screen by patching IOPCIFamily.kext. The only issue I found since 10.14 and later (Catalina included) is that HDMI audio is lost when exit hib. I have no sound output. This behaviour does not exist with 10.13. HDAU comes from a NVIDIA GTX 770 card.

The HDMI output is still visible after waking
![Screenshot 2021-01-31 at 11 04 54](https://user-images.githubusercontent.com/42963618/106380687-46eafb00-63b4-11eb-8dd4-50dbe0c7bbcd.png)

~~Could be an issue of AppleALC/WhateverGreen or maybe Apple changed something to IOPCIFamily from Mojave+~~

EDIT: Ok, so I have found that this issue only happens when using my NVIDIA card (and not the IGPU only setup), so it's definitely an issue with AppleALC/WEG!

Here is the log

[EFI.zip](https://github.com/acidanthera/bugtracker/files/5899485/EFI.zip)
[opencore-2021-01-31-092509.txt - before hibernation](https://github.com/acidanthera/bugtracker/files/5899488/opencore-2021-01-31-092509.txt)
[opencore-2021-01-31-092712.txt - after hibernation](https://github.com/acidanthera/bugtracker/files/5899489/opencore-2021-01-31-092712.txt)
[Lilu_1.5.0_18.7.txt](https://github.com/acidanthera/bugtracker/files/5899490/Lilu_1.5.0_18.7.txt)

**Comment by vit9696** [comment]
No bug with ALC/WEG here. It is your hardware that fails to reinitialise. Usually that means issues in your BIOS.
