### ISSUE TITLE
KeySupportMode V2 causes freezing in Bootpicker

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#1463]
Hi. i want to report issue.

# Issue
 - if use KeySupportMode V2, system will be freeze after cursor moved 3 times or over quickly or normally in bootpicker

# Detail
- Auto : probably my system chosen V2. but cursor is freeze after cursor moved 3 times over quickly or normally. 
             both ctrl + index and enter is working.
- V1: cursor is not freeze everytimes, both ctrl + index and enter isn't working. 
- V2: cursor is freeze after cursor moved 3 times over quickly or normally. both ctrl + index and enter is working. 
         it is same like "Auto"
- AMI: everything is not working. i can't type any keys in bootpicker.

# Setup
- PollAppleHotkeys True
- Picker Mode External
- AllowSetDefault True
- KeyForgetThreshold 5
- KeyMergeThreshold 2
- KeySupportMode Auto(system choice V2)
- TimerResolution 50000
- KeySupport True
- KeySwap False
- PointerSupport False
- KeyFiltering False

# Point
1.  V1(no freezing) and AllowSetDefault(not working) with ctrl+index or enter?
2.  V2(freezing) and AllowSetDefault(working) without freezing?

# Attach
[opencore-2021-01-17-020803.txt](https://github.com/acidanthera/bugtracker/files/5899577/opencore-2021-01-17-020803.txt)

thanks in advance

**Comment by vit9696** [comment]
"cursor moved" — is that mouse/trackpad? I recommend not doing that, and in fact not using mouse at all :) Laptop drivers are trash, not much we can do on our side.

**Comment by Sher1ocks** [comment]
> "cursor moved" — is that mouse/trackpad? I recommend not doing that, and in fact not using mouse at all :) Laptop drivers are trash, not much we can do on our side.

PS2 keyboard on laptop.
V1 doesn't have freezing. also fast moving in bootpicker.
but V2 is slow and highly happen freezing.

**Comment by vit9696** [comment]
So, then which cursor do you mean? Do you mean the selected entry in the picker? I.e. OpenCanopy or builtin? That you switch with arrows. If so, which picker is affecred? Both?

**Comment by Sher1ocks** [comment]
> So, then which cursor do you mean? Do you mean the selected entry in the picker? I.e. OpenCanopy or builtin? That you switch with arrows. If so, which picker is affected? Both?

![0_b-Dz-6_PAaKDLc2N](https://user-images.githubusercontent.com/2107738/106438413-d0d0bc00-64b9-11eb-82d4-76fcb5d19e15.jpeg)
cursor is "<" in picker.
several times up and down key on keyboard.
"<" is freezing. i have to press ctrl + alt + delete key or power button.
both builtin and external(openocanopy) has freezing.

**Comment by Andrey1970AppleLife** [comment]
Try without AudioDxe.

**Comment by Sher1ocks** [comment]
> Try without AudioDxe.

there is still same problem.

**Comment by vit9696** [comment]
We will investigate through test builds some time later after 0.6.6 release. I will ping you when I get free time.

**Comment by Sher1ocks** [comment]
> We will investigate through test builds some time later after 0.6.6 release. I will ping you when I get free time.

thank you. i will wait

**Comment by Bmju** [comment]
I've been working on candidate [updated kb support](https://github.com/acidanthera/OpenCorePkg/pull/217) for a separate [issue](https://github.com/acidanthera/bugtracker/issues/1526) with some feedback from @vit9696 and @mhaeuser.

@vit9696 has asked me to suggest that you try this [alpha build](https://github.com/MikeBeaton/OpenCorePkg/releases/download/0.6.7-kb-alpha1/OpenCore-0.6.7-DEBUG-kb-alpha1.zip) of the new support, to see if it helps with your issue.

It would be interesting to know if this works better for you in either V1 or V2 `KeySupportMode`.

**Comment by Sher1ocks** [comment]
@Bmju 
wow. thanks V2(Auto) is no freezing. it is fixed. thank you so much!

Summary
V1: no freeze. but ctrl+enter is not working. it means no save default boot partition
V2(Auto): no freeze. ctrl+enter is working.
AMI: every keys is not working.

**Comment by vit9696** [comment]
- Does key repeat work? I.e. if you hold a key? Did it work previously?
- Can you enter a password in FV2 UI with that build (without issues)?

**Comment by Sher1ocks** [comment]
> * Does key repeat work? I.e. if you hold a key? Did it work previously?
=  repeat is reworking. if hold right arrow key, continuously moving to right end. previously it was works with sometime freeze.
    Bmju fix's everything is perfect.

> * Can you enter a password in FV2 UI with that build (without issues)?
yes. now i tested it.!! perfect.

**Comment by Bmju** [comment]
@Sher1ocks It would be very helpful to understand how the raw input behaves on your system. Do you know how to enable OpenShell.efi as a boot option in OC (or would you be happy to follow some quick instructions for doing so)? I'd like to know, if you enter the OpenShell command prompt and start typing, is the key repeat behaviour on your system basically normal?

**Comment by Sher1ocks** [comment]
Do you know how to enable OpenShell.efi as a boot option in OC (or would you be happy to follow some quick instructions for doing so)? I'd like to know, if you enter the OpenShell command prompt and start typing, is the key repeat behaviour on your system basically normal?

--> yes. if i press on "a" key on OpenShell, show aaaaaaaaaa. it is no problem. also normal type any keys. everything is fine.

**Comment by Bmju** [comment]
I think that even with old kb handler OpenShell would have worked just the same - and it would be helpful to know this (for improving this kb support for all users) - if you have time to go back to the old config quickly to test that?

E.g. With previously broken V2 support, and Builtin bootpicker, you should be able to press up arrow (twice?) i.e. to wrap from top to bottom of list and then press Enter to start OpenShell and test, before the bootpicker freezes.

**Comment by Sher1ocks** [comment]
> I think that even with old kb handler OpenShell would have worked just the same - and it would be helpful to know this (for improving this kb support for all users) - if you have time to go back to the old config quickly to test that?

--> you are right. OpenShell is work without freeze in old kb handler.

> E.g. With previously broken V2 support, and Builtin bootpicker, you should be able to press up arrow (twice?) i.e. to wrap from top to bottom of list and then press Enter to start OpenShell and test, before the bootpicker freeze

--> after enter OpenShell, i never get freeze. just only happen freeze in bootpicker.

hope your fix commit for master OC soon.

**Comment by Bmju** [comment]
Thank you very much for doing these tests. That's very helpful!

Would you be willing to share your full config.plist file? Not recommended to post publicly unless you manually react any machine serial numbers (if present) and password hash (if present). If so, feel free to redact (if needed) and post here, or just email me directly mjsbeaton [@] gmail.com.

**Comment by Sher1ocks** [comment]
> Thank you very much for doing these tests. That's very helpful!
> 
> EDIT: Actually, scratch that last bit, you already gave all the relevant settings. 👍

thank you for your hard work :)

**Comment by MikeBeaton** [comment]
E.g.:
![plus-sign](https://user-images.githubusercontent.com/11946605/110317687-6654f380-8004-11eb-9faa-fa808fd5283a.jpeg)

**Comment by Sher1ocks** [comment]
> Hi @Sher1ocks - I am still working on trying to make a version of this which can be rolled out to all machines.
> 
> Would you be willing to test a new version: https://github.com/MikeBeaton/OpenCorePkg/releases/tag/0.6.8-kb-beta1 ?
> 
> Assuming key repeat is still under control for you then I am particularly interested to know if another new feature works properly on your setup, as follows: in the Builtin picker (only, for now; so not Canopy), the 'cursor' indicating the selected item should change from '>' to '+' all the time CTRL key is held down. (Similar to how it changes from a straight to a round arrow while holding CTRL key, to indicate persistent change of boot selection if you go on to press Return, on Apple's own bootpicker.)
> 
> Is possible that this will only flicker on and off, rather than staying set on, on your setup.

hi. i tested your beta1 build.
1. very fast. i love it. because there was lag when moving cursor in bootpicker until test your build.
2. when hold down ctrl key, cursor is filcker repeatly "<", "+", "<", "+",~

do you need log?

**Comment by MikeBeaton** [comment]
1. Yes, there was! :)
2. No, not for now, just that result is helpful. Ty!

**Comment by Sher1ocks** [comment]
> 1. Yes, there was! :)
> 2. No, not for now, just that result is helpful. Ty!

i have a time. it is 9:18 PM in korea.  if you need test, i will help your test.

**Comment by MikeBeaton** [comment]
Okay, thank you, I'll send you something. Give me a minute.

**Comment by MikeBeaton** [comment]
Hi - Thanks again - can you try this: https://github.com/MikeBeaton/OpenCorePkg/releases/download/0.6.8-sher1ocks-1/OpenCore-0.6.8-DEBUG-sher1ocks-1.zip

Set `Misc/Debug/Target=67` in your `config.plist`, all other config whatever you were using (obv. `Builtin` picker).

After the picker appears, It will print a complete load of rubbish on your screen and mess up the picker.

Please can you boot it; once the Builtin menu appears (and then my new debug text starts scrolling down the screen) please press and hold down the CTRL key for five to ten seconds (just once for 5-10 seconds, no release and repress for this test, pls) then release. That's the test done. Then, you try to press _and hold_ Enter (which _should_ boot your default OS). If it does not you may have to force reboot. (WARNING: If it does this, you will need a way to restore OC without booting through this version!!!!) Then please send me OC log. Tyvm!

**Comment by Sher1ocks** [comment]
> Hi - Thanks again - can you try this: https://github.com/MikeBeaton/OpenCorePkg/releases/download/0.6.8-sher1ocks-1/OpenCore-0.6.8-DEBUG-sher1ocks-1.zip
> 
> Set `Misc/Debug/Target=67` in your `config.plist`, all other config whatever you were using (obv. `Builtin` picker).
> 
> After the picker appears, It will print a complete load of rubbish on your screen and mess up the picker.
> 
> Please can you boot it; once the Builtin menu appears (and then my new debug text starts scrolling down the screen) please press and hold down the CTRL key for five to ten seconds (just once for 5-10 seconds, no release and repress for this test, pls) then release. That's the test done. Then, you can try to press _and hold_ Enter (which _should_ boot your default OS). If it does not you may have to force reboot. (WARNING: If it does this, you will need a way to restore OC without booting through this version!!!!) Then please send me OC log. Tyvm!

strange i have a black screen now

**Comment by MikeBeaton** [comment]
? How far does it get? (PS This is pretty experimental - no results guaranteed at all on these tests!)

**Comment by Sher1ocks** [comment]
> ? How far does it get? (PS This is pretty experimental - no results guaranteed at all on these tests!)

just black screen. seems 67 debug option causes to blackscreen.
do you have discord?

**Comment by MikeBeaton** [comment]
element.io @bmju:matrix.org

**Comment by MikeBeaton** [comment]
Oh - I've thought of something - look at the last line of the log file which you (probably) did get...

**Comment by Sher1ocks** [comment]
> Oh - I've thought of something - look at the last line of the log file which you (probably) did get...

this is log with black screen.
[opencore-2021-03-08-130126.txt](https://github.com/acidanthera/bugtracker/files/6101573/opencore-2021-03-08-130126.txt)

**Comment by MikeBeaton** [comment]
@Sher1ocks - ping back on element.io for another follow up q, if you're still available. Thx!

**Comment by MikeBeaton** [comment]
https://github.com/acidanthera/OpenCorePkg/pull/238
