### ISSUE TITLE
[maciASL] Device tree showing commented code

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1464]
Hi there,
I don't know if this issue can be considered as a bug but today I've noticed a possible bug in maciASL while I was editing an SSDT.
More precisely, if you comment a device in maciASL, it still shows in the device tree left-pane.
Below an image which may clarify the doubts:

![Screenshot 2021-01-31 at 21 50 32](https://user-images.githubusercontent.com/17933708/106398319-729cce00-6412-11eb-8870-5c91a4955ca5.png)

Why is the device showed into the device tree left-pane? Is this a bug or can be ignored?
Thank you so much for any clarifications
Regards
dreamwhite

**Comment by vit9696** [comment]
https://github.com/acidanthera/bugtracker/issues/1089
