### ISSUE TITLE
Change ocvalidate to return exit code other than 0 when any of the checks fail

### ISSUE THREAD

**Issue by teosoft123** [acidanthera/bugtracker#1467]
In order to improve use if the ocvalidate tool in scripts and makefiles, it should return a non-zero error code in case it detects errors in configuration.

**Currently it's not the case:**

[prompt] Utilities/ocvalidate/ocvalidate src/OC/config.plist
OCS: Missing key SetApfsTrimTimeout, context <Quirks>!
OCS: Missing key LauncherOption, context <Boot>!
OCS: Missing key LauncherPath, context <Boot>!
OCS: No schema for BootProtect at 5 index, context <Security>!
OCS: Missing key MaxBIOSVersion, context <Generic>!
OCS: Missing key UseRawUuidEncoding, context <PlatformInfo>!
OCS: Missing key DisableSecurityPolicy, context <Quirks>!

OpenCanopy.efi is loaded at UEFI->Drivers, but Misc->Boot->PickerMode is not set to External!
CheckMisc returns 1 error!

Done checking src/OC/config.plist in 1 ms, but it has 1 error to be fixed

[prompt] echo $?
0

**Expectations**: returned non-zero exit code

**Comment by PMheart** [comment]
In addition to checks that ocvalidate perform, serialisation errors are checked by calling `OcConfigurationInit` which does not return error counts. CC @vit9696 

For the rest, I simply changed retval to the number of errors detected. (https://github.com/acidanthera/OpenCorePkg/commit/1d74b6fa3e095857d7c6a8b977eb72be3e853d78)

**Comment by teosoft123** [comment]
@PMheart Please take into account that on Unix platforms, exit code is limited to 0..255 (i.e. one unsigned byte range) and if the number returned is, say 256 == 0x100 it will be interpreted as 0, i.e. no errors.


> For the rest, I simply changed retval to the number of errors detected. ([acidanthera/OpenCorePkg@1d74b6f](https://github.com/acidanthera/OpenCorePkg/commit/1d74b6fa3e095857d7c6a8b977eb72be3e853d78))

**Comment by PMheart** [comment]
Right. Thanks for pointing it out. Fixed in master. (https://github.com/acidanthera/OpenCorePkg/commit/cb5f497a04f960f5b176f37edd87b43d40965a9d)
