### ISSUE TITLE
OC: UpdateDataHub will add but not overwrite variables

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1468]
Using OC on Apple hardware, MacBookPro10,2 - I noticed that when using PlatformInfo/UpdateDataHub, OC can add new values to the data hub, but apparently cannot modify any pre-existing values.

Not sure if the images below add much to this short description, but have included them to show it happening.

------

Here is IORegistryExplorer IODeviceTree:/efi/platform on my machine without OC:

<img width="586" alt="Screenshot 2021-02-03 at 00 42 38" src="https://user-images.githubusercontent.com/25643187/106690910-81c67c00-65ca-11eb-83a5-6376df748b95.png">

Here is IORegistryExplorer IODeviceTree:/efi/platform with OC PlatformInfo Automatic=true and UpdateDataHub=true (not overriding datahub protocol):
(note: system-id, model, system serial are not updated in data hub, even though board-id has been successfully added.)

<img width="582" alt="Screenshot 2021-02-03 at 00 29 16" src="https://user-images.githubusercontent.com/25643187/106690964-9a369680-65ca-11eb-9891-fe0d5ce8e0e3.png">

System Information within the same boot, showing the model and serial number which are set, and which I would have expected to appear in DataHub:

<img width="448" alt="Screenshot 2021-02-03 at 02 45 05" src="https://user-images.githubusercontent.com/25643187/106690677-27c5b680-65ca-11eb-9826-c0a2dc811f0c.png">

<img width="458" alt="Screenshot 2021-02-03 at 00 50 14" src="https://user-images.githubusercontent.com/25643187/106690744-4035d100-65ca-11eb-977d-3e3711e409e5.png">

OC log shows that it thinks the values were written:

```
06:289 00:039 OCDH: Setting DataHub 64517CC8-6561-4051-B03C-5964B60F4C7A:name (9) - Success
06:332 00:042 OCDH: Setting DataHub 64517CC8-6561-4051-B03C-5964B60F4C7A:Model (30) - Success
06:375 00:043 OCDH: Setting DataHub 64517CC8-6561-4051-B03C-5964B60F4C7A:board-id (21) - Success
06:418 00:043 OCDH: Setting DataHub 64517CC8-6561-4051-B03C-5964B60F4C7A:StartupPowerEvents (8) - Success
06:461 00:043 OCDH: Setting DataHub 64517CC8-6561-4051-B03C-5964B60F4C7A:InitialTSC (8) - Success
06:504 00:042 OCDH: Setting DataHub 64517CC8-6561-4051-B03C-5964B60F4C7A:FSBFrequency (8) - Success
06:546 00:042 OCDH: Setting DataHub 64517CC8-6561-4051-B03C-5964B60F4C7A:DevicePathsSupported (4) - Success
06:590 00:043 OCDH: Setting DataHub 64517CC8-6561-4051-B03C-5964B60F4C7A:REV (6) - Success
06:632 00:042 OCDH: Setting DataHub 64517CC8-6561-4051-B03C-5964B60F4C7A:RBr (8) - Success
06:673 00:041 OCDH: Setting DataHub 64517CC8-6561-4051-B03C-5964B60F4C7A:RPlt (8) - Success
```

**Comment by vit9696** [comment]
This is due to the implementation of your DataHub protocol coming from Apple EFI firmware. We cannot do much with this. DataHub protocol design allows you to add properties, but it does not allow you to overwrite them. As a workaround You can set ProtocolOverrides → DataHub to YES, but then you will lose all the data in DataHub.

**Comment by Bmju** [comment]
Cool - I thought it might be known - as a small request - not urgent - is there any chance at all to mention this in the docs?

**Comment by Bmju** [comment]
(Not sure it's confusing just me - current implementation of OCLP for instance has UpdateDataHub set, and I'm not at all sure they're aware that the faked serials which they are setting are NOT getting written to the data hub - but that it still contains the machines original values - because of this.)

**Comment by vit9696** [comment]
Yes, fair suggestion. Could you please send a PR in UpdateDataHub covering that? Both the fact that the new entries cannot be overridden, and instead they are added to the end with macOS ignoring them, and the fact that you can workaround this by reinstalling DataHub protocol.
