### ISSUE TITLE
Single-User command starts Verbose is this a bug?

### ISSUE THREAD

**Issue by telepati** [acidanthera/bugtracker#1470]
Command+S or -s boot argument directly starts the Verbose command. Is this a bug or is the Single User mode not available after Big Sur? Because all other commands are working.

**Comment by vit9696** [comment]
Apple Secure Boot prohibits Single User mode. There was a KB page earlier[1]. Perhaps Big Sur killed it entirely.

[1] https://web.archive.org/web/20200517125051/https://support.apple.com/en-us/HT201573
