### ISSUE TITLE
WEG: IsTypeCOnlySystem var routing failed in Mac OS Recovery environments, which results in kernel panic

### ISSUE THREAD

**Issue by Ubsefor** [acidanthera/bugtracker#1472]
Issue persists after this [commit](https://github.com/acidanthera/WhateverGreen/commit/d97085fb9c720e4fa7a3bcb9b512840a0bb5cdda) on Kaby Lake Refresh laptop systems, only in Recovery environment, actually panics at boot process thus preventing OS update/install

Example of this and actual boot log (photographed) can be found at [reddit post](https://www.reddit.com/r/hackintosh/comments/ifnqjr/help_with_yoga_c930_i78550uuhd620/)

Will try to collect more precise kernel logs later.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5925247/EFI.zip) – EFI configuration
[panic.log](https://github.com/acidanthera/bugtracker/files/5925329/panic.log) – Mac OS log after booting into OS normally

**Comment by Andrey1970AppleLife** [comment]
You use Automatic equipment, but Generic is empty.
![Снимок экрана 2021-02-04 в 14 25 09](https://user-images.githubusercontent.com/17758753/106886661-31980880-66f5-11eb-83b1-e6369d2fc033.png)

**Comment by Ubsefor** [comment]
> You use Automatic equipment, but Generic is empty.
> ![Снимок экрана 2021-02-04 в 14 25 09](https://user-images.githubusercontent.com/17758753/106886661-31980880-66f5-11eb-83b1-e6369d2fc033.png)

It is not empty but purposely removed before uploading to GitHub. Everything of PlatformInfo configuration is actually present

**Comment by dreamwhite** [comment]
Dear @Ubsefor,
as @vit9696 and @zhen-zen stated in issue #1471, it seems that the kernel panic is caused by AppleBacklightSmoother. Try removing it and see if you no longer experience a kernel panic.

**Comment by Andrey1970AppleLife** [comment]
You shall provide panic log with boot-arg keepsyms=1
https://github.com/acidanthera/bugtracker/blob/master/.github/ISSUE_TEMPLATE/bug-in-opencore-or-kext.md

**Comment by Ubsefor** [comment]
> You shall provide panic log with boot-arg keepsyms=1
> https://github.com/acidanthera/bugtracker/blob/master/.github/ISSUE_TEMPLATE/bug-in-opencore-or-kext.md

There is actually no need to maintain this issue any longer as it is the problem not with WEG, but with [AppleBacklightSmoother](https://github.com/hieplpvip/AppleBacklightSmoother) kext by [hieplpvip](github.com/hieplpvip). As stated in above [reply](https://github.com/acidanthera/bugtracker/issues/1472#issuecomment-773244814) – I need to remove BacklightSmoother as it works perfectly fine without it. Will possibly update my opened issue at the author’s repo.

So I guess it is solved for now.
