### ISSUE TITLE
ASSERT [OpenCore] IoLibGcc.c(152): (Port & 3) == 0

### ISSUE THREAD

**Issue by phony-bread** [acidanthera/bugtracker#1475]
OpenCore 0.6.6 DEBUG
Using DuetPkg legacy boot

AMD FX-6100, ASRock 960GM-GS2 Mobo, BIOS P1.30

Booting from USB, before boot-picker can load, hangs on message:
`ASSERT [OpenCore] IoLibGcc.c(152): (Port & 3) == 0`

No logs available, it hasn't even booted far enough to generate any.
[EFI.tar.gz](https://github.com/acidanthera/bugtracker/files/5936485/EFI.tar.gz)

**Comment by phony-bread** [comment]
After investigating the problem myself, it seems that this is actually an assertion from the UEFI Development Kit that was used to build the release of OpenCore, and as such isn't an issue directly related to this project.

Still, if anyone has any suggestions for fixing this, I'm all ears.

**Comment by phony-bread** [comment]
For anyone interested, looks like the issue is with attempting to read a 32-bit I/O port using a function from https://github.com/tianocore/edk2.

**Comment by vit9696** [comment]
Well, try to find the place where the read happens, by inserting prints for instance. We can create a patch for EDK II to workaround it afterwards.
