### ISSUE TITLE
about context  in ocvalidate

### ISSUE THREAD

**Issue by btwise** [acidanthera/bugtracker#1479]
@PMheart 
A config config error has been detected in Ocvalidate. can  specify the location of the error, such as the location shown in the screenshot, as `context Kernel-->Add-->Quirks <SetApfsTrimTimeout>`

![image](https://user-images.githubusercontent.com/38809560/107136066-259d8800-693b-11eb-9165-6f928ca412a5.png)

**Comment by vit9696** [comment]
Will require a lot of rework, which will slowdown OC. Nope.
