### ISSUE TITLE
WhateverGreen DRM Compatibility Chart Query

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1481]
The [WhateverGreen DRM Compatibility Chart ](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md) mentions `Select AMD GPUs` several times but there is no indication what these are.

Should there not be some sort of list or indication of family etc for completeness?

**Comment by vit9696** [comment]
It is a total mystery in general. Most modern ones (Polaris+) work, yet there are random exceptions. There also were certain 7xxx GPUs with DRM support at least. Easier not to specify this.
