### ISSUE TITLE
OpenCore new boot method maybe incompatible with some ASRock motherboards

### ISSUE THREAD

**Issue by JayMonkey** [acidanthera/bugtracker#1482]
Hi,

With the latest version of OpenCore I see that Acidanthera have ditched the old method of using BOOTX64.efi to bootstrap OpenCore as detailed in the latest version of the install guide here : -

https://dortania.github.io/OpenCore-Post-Install/multiboot/bootstrap.html

This unfortunately causes a problem with some ASRock motherboards due to the way UEFI is implimented in the ASRock BIOS. The only way to get these motherboards to boot a foreign efi loader/booter such as Clover or OpenCore is to copy BOOTX64.efi to the root of the EFI partition and rename to SHELLX64.efi.

So far this has worked well for all Clover releases and to date also for OpenCore up to 0.6.5

However no matter what I do I can not get my ASRock system to boot OC 0.6.6, i've tried the official guide and of course copying BOOTX64.efi to the root of the EFI partition and renaming as SHELLX64.efi. but in all cases it fails to load and run OC 0.6.6.

Kind Regards
Jay

**Comment by vit9696** [comment]
Please show us the output from a debug build of BOOTX64.efi and OpenCore.efi when renamed to SHELLX64.efi and run on such a board. This configuration should still be supported, but perhaps there a nuance we need to address.

**Comment by nms42** [comment]
Would be nice to see list of such boards.

**Comment by JayMonkey** [comment]
> Please show us the output from a debug build of BOOTX64.efi and OpenCore.efi when renamed to SHELLX64.efi and run on such a board. This configuration should still be supported, but perhaps there a nuance we need to address.

Hi Vit ...

I'm not convinced that the system is even getting far enough for OC to start logging anything as selecting the OC entry from the UEFI boot devices picker results in a quick flash of the screen but the system remains in the boot devices picker. At no point have I been able to get as far as seeing OC 0.6.6 running.

However I will download the debug versions and give it a go and update this thread with any new info.

Cheers
Jay

**Comment by JayMonkey** [comment]
> Would be nice to see list of such boards.

The two motherboards that I own that require the SHELLX64.efi workaround are : -

ASRock Z97 Extreme 6 / 3.1
ASRock Z97E-ITX/ac

I also know that the ASRock H97 Pro 4 also suffers from this UEFI oddity as it is detailed in the following guide : -

https://www.insanelymac.com/forum/topic/302041-guide-asrock-h97-pro4-yosemite-with-clover-uefi-installation/

Move down to section 4 - Post Installation, and you can see the instructions to copy BOOTX64.efi to the root fo the EFI partition and rename as SHELLX64.efi.

I'm sure there are others but only know the above for sure ...

Based on teh above I thought that maybe this issue is limited to just ASRock Z97 based systems but doing a quick google search i found the following : -

http://forum.asrock.com/forum_posts.asp?TID=10481&title=how-to-launch-efi-shell

Which apparently shows the need to use the method on a ASRock Taichi z390 Ultimate motherboard.

Hopefully other OpenCore / ASRock users will find this thread and post details of other hardware that suffers the problem so we can get a better picture of how extensive the problem is.

Cheers
Jay

**Comment by vit9696** [comment]
Debug BOOTx64.efi performs onscreen logging till it starts OpenCore.efi. Same for OpenCore.efi itself.

**Comment by vit9696** [comment]
As for the guides, it looks borked, because Z97 boards have UEFI compatibility, and they must run EFI\BOOT\BOOTx64.efi. Something is likely wrong on your end if it does not happen.

**Comment by JayMonkey** [comment]
Hi Vit,

> Debug BOOTx64.efi performs onscreen logging till it starts OpenCore.efi. Same for OpenCore.efi itself.

Ok understood ... that should help to debug the issue ....

> As for the guides, it looks borked, because Z97 boards have UEFI compatibility, and they must run EFI\BOOT\BOOTx64.efi. Something is likely wrong on your end if it does not happen.

Yup, i've always known that and up until now have never had an issue running Clover or OpenCore ... it just that on some ASRock motherboards you need to copy EFI\BOOT\BOOTx64.efi to to root of the EFI partition and rename as SHELLX64.efi. I suspect that the UEFI on effected motherboards has some kind of white list for EFI\BOOT as there is no problem booting Windows in UEFI mode from EFI\BOOT\BOOTIA32.efi ... so I think the SHELLX64.efi method is some sort of workaround for getting around the EFI\BOOT white list.

I will dome some testing with the debug versions and report my findings ...

Cheers
Jay

**Comment by vit9696** [comment]
It could be that you need to somehow disable Secure Boot or similar stuff, as it may expect `EFI\BOOT\BOOTx64.efi` to be signed. Yet I am pretty sure no rename is needed. Even so, if the thing fails to run, it is unlikely related to the renaming issue, so all my previous requests about logs hold.

**Comment by Mieze** [comment]
I've got an Asrock H97M Pro 4 which I switched from Clover r5105 to OC 0.6.6 last weekend but I haven't observed the problem you are describing with this MB. The transition went smooth but I had to set SecureBootModel to Disabled in order to make it work.

**Comment by JayMonkey** [comment]
> I've got an Asrock H97M Pro 4 which I switched from Clover r5105 to OC 0.6.6 last weekend but I haven't observed the problem you are describing with this MB. The transition went smooth but I had to set SecureBootModel to Disabled in order to make it work.

> It could be that you need to somehow disable Secure Boot or similar stuff, as it may expect `EFI\BOOT\BOOTx64.efi` to be signed. Yet I am pretty sure no rename is needed. Even so, if the thing fails to run, it is unlikely related to the renaming issue, so all my previous requests about logs hold.

There is no Secure Boot feature in the BIOS on either of my two Z97 ASRock motherboards, so its not a secure boot issue, both systems are running the most up-to-date version of the BIOS but 

I have made some progress though ...

Using some of the tips from the guide II created a Bootstrap sub folder in the OC folder and copied Bootx64.efi from the OC Boot folder and renamed it to Bootstrap.efi, this has allowed me to get OC 0.6.6 running and it boots MacOS fine so that a good step forwards.

Clearing NVRAM and following the instructions to get it running with the new OC native boot method has so far not worked, however It's possible that the UEFI/BIOS/CMOS data on my mobo has maybe got corrupted and its not allowing OC to create the new native OC boot entry. I'm going to try clearing the CMOS and will try again ....

Cheers
Jay

**Comment by vit9696** [comment]
Any board should have Secure Boot settings. For ASRock I believe they are here:

![BB6A3C26-61C3-47E5-BD35-B8D6134B730B](https://user-images.githubusercontent.com/4348897/107402107-aa8fc980-6b14-11eb-9f9c-df2923e386d1.png)

**Comment by vit9696** [comment]
Closing until further notice of an actual issue found.

**Comment by JayMonkey** [comment]
I realise that this case is closed but i have a small update which may help others.

I was able to use Clovers EFI Shell to manually add a UEFI entry for /EFI/OC/OpenCore.efi using the **bcfg** command and after this i was able to boot OC directly.

Interesting I could not use OC's EFI shell to do this as there seems to be an incompatibility with OC's EFI shell and the BIOS/UEFI on my ASRock Mobo (Safe mode is disabled).

Executing the bcfg commands in OC's shell produced results but not on the actual UEFI boot entries. For example executing "**bcfg boot dump**" would only list **one** EFI entry called "Mac OS" where as executing the same command in Clovers EFI shell listed **all** of the actual UEFI boot entires (of which there are many and no "MacOS"). The same was true when using **rm** and **add** to remove or add a UEFI entry. The command executed in OC's shell and did indeed add an entry when confirmed by executing the dump command but the changes where not reflected within the BIOS/UEFI once the system was rebooted.

However using Clovers EFI shell everything worked just fine.

Maybe this will helps someone else ...

Cheers
Jay

**Comment by vit9696** [comment]
To be able to access UEFI boot options from OpenCore (e.g. from OpenShell launched from OpenCore) you should use OpenControl. It allows you to unlock the access to UEFI boot options. Refer to Configuration.pdf or run OpenControl.efi from Shell without arguments for more details.

**Comment by JayMonkey** [comment]
Thanks for the heads-up upon having to use OpenControl  .. i was not aware of this.
I will test OC's shell again with OpenControl loaded ...

**Comment by vit9696** [comment]
It is not loadable (as a driver). It is an app you run in Shell to enable/disable UEFI boot options access.

**Comment by JayMonkey** [comment]
> It is not loadable (as a driver). It is an app you run in Shell to enable/disable UEFI boot options access.

Understood ... so i just run it from within OpenShell ... got it.

Many thanks for your advice and heaps of respect to the whole acidanthera team for your amazing work.

Cheers
Jay
