### ISSUE TITLE
[Question] How to obtain verbose debug boot logs in Catalina / Big Sur

### ISSUE THREAD

**Issue by sztupy** [acidanthera/bugtracker#1483]
I'm trying to debug some issues related to VoodooPS2 and BrcmPatch I'm having. I'm using the debug kexts however the debug logs only appear on the screen during verbose boot, but are mostly missing from the syslog after boot. I've seen with Lilu there's an option to get these logs written to the disk here https://github.com/acidanthera/bugtracker/issues/1384 but I can't seem any similar option for VoodooPS2 or BrcmPatch. 

The only thing I can do right now is to use a camera to record the boot to get the logs, which is tedious and hard to do especially for fast-scrolling contents on a screen with a bad refresh rate.

This issue appears already in Catalina, but it seems to be even worse on Big Sur (on Big Sur I get around 50% less logs in the boot syslog than I get during Catalina). I have tested on a real Mac and the issue is present there as well so it's likely to be a bug in the system and not OpenCore, however it does make debugging issues with kexts during boot much harder.

One specific example I have is:

VoodooPS2 ELAN touchpad initialisation on boot screen:

![Screenshot 2021-02-08 at 16 07 02](https://user-images.githubusercontent.com/96418/107246368-18aa9280-6a28-11eb-8468-8de77b4a3ffc.png)

Touchpad logs in syslog:

```
2021-02-08 14:37:30.985912+0000  localhost kernel[0]: (VoodooPS2Trackpad) VoodooPS2Elan: Version 2.2.0 starting on OS X Darwin 19.6.
2021-02-08 14:37:31.028871+0000  localhost kernel[0]: (VoodooPS2Trackpad) ApplePS2Elan::probe entered...
2021-02-08 14:37:31.133824+0000  localhost kernel[0]: (VoodooPS2Trackpad) VoodooPS2Elan: send magic knock to the device.
2021-02-08 14:37:31.197987+0000  localhost kernel[0]: (VoodooPS2Trackpad) VoodooPS2Elan: Elantech version query result 0x45, 0x0f, 0x01.
```

As shown only the four lines underlined on the image are present in the logs after boot, the rest, including the large debug details on the capabilities are missing fully. This is from Catalina. On Big Sur even the four lines that are present in the Catalina logs are fully missing and only appear on the bootup screen.

I'm thinking of rebuilding the kexts with some added delay to see if that helps, but that would not be a good long-term solution I believe.

**Comment by vit9696** [comment]
You can try using https://github.com/acidanthera/DebugEnhancer and `sudo dmesg` command. CC @lvs1974 @usr-sse2

**Comment by sztupy** [comment]
Thanks, let me see if that one works
