### ISSUE TITLE
OC: FSBFrequency calc. is variable (by ~1s/day), OEM value cannot be used instead with recommended Automatic=true

### ISSUE THREAD

**Issue by ghost** [acidanthera/bugtracker#1484]
When updating the Data Hub using `Automatic=true` with `UpdateDataHub=true` and `ProtocolOverrides/DataHub=true`, the `FSBFrequency` written to the Data Hub is variable. My default OEM specified frequency is 0x05f268ed. Values written on typical runs range from 0x05f26aff to 0x05f26c42 - variable, and in my case always slightly higher than OEM value. If I haven't misunderstood, this has no effect on the actual CPU clock rate, but (on processors older than Skylake, which would apply to legacy Macs older than around 2016 or even newer in some cases) it will affect the OS time-of-day clock. By my calculations this range of values would amount to ~1s/day change.

I have only just understood that the OC docs strongly recommend AGAINST using `Automatic=false` in most cases. (I  previously misread the double-negative in the warning here in the docs, mainly based on my incorrect assumption that, here as elsewhere, you were likely to be telling people that they _should_ understand and manually take charge of all settings in most cases. Whereas here the Warning if I understand is saying that here it's too risky to try to specify everything, and that normally they should let OC deal with correctly propagating values from Generic to where they belong.)

However, the only workaround to apply the original OEM `FSBFrequency` that I am aware of would be to switch to `Automatic=false` and manually type in the OEM value (therefore necessarily also expanding out the Generic values one was using into all other sections and entering into the risky to maintain/debug territory, if I now correctly understand the Warning). Therefore it does seem to matter, at least somewhat, that there is no way to preserve the OEM value for `FSBFrequency` while still using the recommended `Automatic=true` approach.

This only applies to legacy Macs, which have an OEM specified `FSBFrequency` value to work with. (And then, only if you have a reason to want to actually update some other pre-existing value in the Data Hub, otherwise you can just leave the Data Hub alone.) I understand that this also interacts with the [existing OC logic](https://github.com/acidanthera/bugtracker/issues/1468) whereby either no pre-existing OEM values on the Data Hub can be overwritten, or else a new Data Hub is created with with no legacy values to keep (any original values are not copied into it).

**Comment by Bmju** [comment]
For anyone else perhaps coming to this issue, see https://github.com/acidanthera/bugtracker/issues/1469#issuecomment-777247176 .

**Comment by vit9696** [comment]
Latest master version provides hand-crafted TSC calculation code [written in assembly](https://github.com/acidanthera/OpenCorePkg/commit/a62cdf2e26c5b504165f6196020ba0909f0c1a65). The standard deviation over 5 tests from master  vs new code shows double improvement:

```
Master
fe59f20500000000 99768830
045af20500000000 99768836
d259f20500000000 99768786
f259f20500000000 99768818
165bf20500000000 99769110

Test nop
665af20500000000 99768934
195af20500000000 99768857
ab5af20500000000 99769003
7a5af20500000000 99768954
aa5af20500000000 99769002
```

We wondered whether we can improve it further, and tried hand-crafting changes like below. Unfortunately the changes did not provide clear results, and do not have resources to fine-tune it further. Feel free to participate if you want.

```nasm
global ASM_PFX(AsmMeasureTicks)
ASM_PFX(AsmMeasureTicks):
  ; Push preserved registers.
  push       rsi
  push       rdi
  push       rbx

  ; Preserve TimerAddr in esi as rdtsc overrides edx.
  mov        esi, edx

  ; Read AcpiTicks0 into ebx.
  in         eax, dx
  mov        ebx, eax

  ; Read Tsc0 into r10.
  rdtsc
  shl        rdx, 32
  or         rax, rdx
  mov        r10, rax

  ; Store MAX_UINT32 - AcpiTick0 into r11d.
  mov        r11d, ebx
  not        r11d

  ; Store MAX_UINT24 - AcpiTick0 into edi.
  mov        edi, 0x00ffffff
  sub        edi, ebx

  ; Move TimerAddr back to edx.
  mov        edx, esi

CalculationLoop:
  nop ; or pause.

  ; Read AcpiTicks1 into esi.
  in         eax, dx
  mov        esi, eax

  ; Calculate AcpiTicks0 - AcpiTicks1 into eax.
  mov        eax, ebx
  sub        eax, esi
  jbe short  NoOverflow

  ; Check for 32-bit overflow.
  ; This is essentially cmp eax, 0x00ffffff ; ja short  Overflow32.
  shr        eax, 24
  jnz short  Overflow32

Overflow24:
  ; AcpiCurrentDelta (esi) = AcpiTicks1 (esi) + MAX_UINT24 - AcpiTick0 (edi)
  add        esi, edi
  jmp short  ContinueLoop

NoOverflow:
  ; AcpiCurrentDelta (esi) = AcpiTicks1 (esi) - AcpiTicks0 (ebx)
  sub        esi, ebx
  jmp short  ContinueLoop

Overflow32:
  ; AcpiCurrentDelta (esi) = AcpiTicks1 (esi) + MAX_UINT32 - AcpiTick0 (r11d)
  add        esi, r11d

ContinueLoop:
  cmp        esi, ecx
  jb  short  CalculationLoop

  ; Read Tsc1 into rax.
  rdtsc
  shl        rdx, 32
  or         rax, rdx

  ; Calculate TscDelta into rax.
  sub        rax, r10

  ; Store TscDelta and AcpiDelta.
  mov        qword [r9], rax
  mov        dword [r8], esi

  ; Pop preserved registers & return.
  pop        rbx
  pop        rdi
  pop        rsi
  ret
```

```nasm
global ASM_PFX(AsmMeasureTicks)
ASM_PFX(AsmMeasureTicks):
  ; Push preserved registers.
  push       rsi
  push       rdi
  push       rbp
  push       rbx

  ; Preserve TimerAddr in ebp as rdtsc overrides edx.
  mov        ebp, edx

  ; Read AcpiTicks0 into ebx.
  in         eax, dx
  mov        ebx, eax

  ; Read Tsc0 into r10.
  rdtsc
  shl        rdx, 32
  or         rax, rdx
  mov        r10, rax

  ; Store MAX_UINT32 - AcpiTick0 into r11d.
  mov        r11d, ebx
  not        r11d

  ; Store MAX_UINT24 - AcpiTick0 into edi.
  mov        edi, 0x00ffffff
  sub        edi, ebx

CalculationLoop:
  nop ; or pause.

  ; Read AcpiTicks1 into esi.
  mov        edx, ebp
  in         eax, dx
  mov        esi, eax

  ; Read Tsc1 into rax.
  rdtsc
  shl        rdx, 32
  or         rdx, rax

  ; Calculate AcpiTicks0 - AcpiTicks1 into eax.
  mov        eax, ebx
  sub        eax, esi
  jbe short  NoOverflow

  ; Check for 32-bit overflow.
  ; This is essentially cmp eax, 0x00ffffff ; ja short  Overflow32.
  shr        eax, 24
  jnz short  Overflow32

Overflow24:
  ; AcpiCurrentDelta (esi) = AcpiTicks1 (esi) + MAX_UINT24 - AcpiTick0 (edi)
  add        esi, edi
  jmp short  ContinueLoop

NoOverflow:
  ; AcpiCurrentDelta (esi) = AcpiTicks1 (esi) - AcpiTicks0 (ebx)
  sub        esi, ebx
  jmp short  ContinueLoop

Overflow32:
  ; AcpiCurrentDelta (esi) = AcpiTicks1 (esi) + MAX_UINT32 - AcpiTick0 (r11d)
  add        esi, r11d

ContinueLoop:
  cmp        esi, ecx
  jb  short  CalculationLoop

  ; Calculate TscDelta into rax.
  sub        rdx, r10

  ; Store TscDelta and AcpiDelta.
  mov        qword [r9], rdx
  mov        dword [r8], esi

  ; Pop preserved registers & return.
  pop        rbx
  pop        rbp
  pop        rdi
  pop        rsi
  ret
```

**Comment by Bmju** [comment]
Hi @vit9696 - after seeing @cdf's issue https://github.com/acidanthera/bugtracker/issues/1521 I thought of yet another possible wrinkle here: much as I would very much like to have my processor speed info unchanged and read from existing BIOS settings (as I think you are considering doing?) rather than measured on the fly (with its slight; and now, even slighter) variability, obviously if I *had* [upgraded my processor](https://github.com/acidanthera/bugtracker/issues/1521#issuecomment-782965791), then I would no longer want that!

Or at least, I'm assuming that the OEM BIOS CPU frequency settings would not reflect the physically installed processor if one changes it? But then seeing as the [Apple BIOS clearly does notice changes](https://github.com/acidanthera/bugtracker/issues/1521#issuecomment-782965791), I guess I just don't really know how this works...

**Comment by vit9696** [comment]
I believe Apple currently does detect frequencies for all the supported CPUs. If you install an unsupported one, however, that might fail. But so far I have not seen any examples.

**Comment by vit9696** [comment]
I wonder whether we should actually use Apple Platform Info protocol on Macs. Like AppleSmBios does (we [reversed it here](https://github.com/acidanthera/mac-efi-firmware/blob/development/EfiPkg/Universal/AppleSmbiosDxe/AppleSmbios.c)). See `InternalGetFsbFrequency`.

**Comment by Bmju** [comment]
Put in simple terms (i.e. at the level of my current understanding!), if that's the bit that's correctly reflecting changed frequencies for different installed processors and which is (directly or indirectly) responsible for the correct, changing info which @cdf is seeing in his 'About This Mac' as he puts different processors in it (for example), then that definitely sounds right (at that level of understanding of the issues!).

**Comment by vit9696** [comment]
Yes, that's basically what MacEFI uses as a source of many platform values including CPU frequency.

**Comment by Bmju** [comment]
Can I run through what I think is involved, and see if I'm in the right ballpark?

The main difficulty (which would have applied equally if taking the FSBFrequency value from the Data Hub, and which you discussed in point 4 of [your comment here](https://github.com/acidanthera/bugtracker/issues/1469#issuecomment-777247176)) is that currently OpenCore measures the CPUFrequency, then calculates everything else from that; whereas in the proposed new Apple OEM-only codepath, the idea is to look up FSBFrequency, and then reverse the calculations, to derive everything else about frequency from that? So that a bunch of stuff in ScanIntelProcessor in OcCpuLib.c would need to be modified, and correct (i.e. valid; applicable to all available h/ware; and to all necessary values, incl. TSCFrequency which you mentioned might be problematic?) reverse calculations put in place.

But also, that other (non-frequency related) parts of ScanIntelProcessor, like num. cores detection, would need to stay the same (i.e. these would not be detected in any new, equivalent way)?

Also, finally, that there needs to be an equivalent change (and way of getting hold of the Apple value) for machines which don't have FSBFrequency - I guess there would be an equivalent ARTFrequency lookup instead? Though again (_if_ I've understood that part of the code right, from just a quick look at it again, just now) an Apple provided ARTFrequency value could slot in where the existing value is measured? (So no reversing existing calculations in this case, just feeding in a value from a different source?)

**Comment by vit9696** [comment]
If ART frequency is calculated, then it is always valid. No rounding involved there. I believe it has higher priority than any Apple values. Next to use is probably VMT (hypervisor), then Apple, then PM Timer. For OpenCore there are two places to calculate CPU frequency:

- `OcGetTSCFrequency`, which goes through all the available methods and must always give valid value.
- `InternalCalculateXXXFrequencyYYY`, which get called from OcCpuLib

For Apple we would need a new `InternalCalculateTSCFromApplePlatformInfo` function, called when `InternalCalculateVMTFrequency` fails in `OcGetTSCFrequency`. You are right that it needs to convert FSB Frequency to TSC Frequency. This means that `MaxBusRatio` calculation code should be moved to a separate function calculating Min, Max, Current based on CPU Model. Avoiding code duplication and doing the necessary multiplication inside `InternalCalculateTSCFromApplePlatformInfo`.

For `OC_CPU_INFO` you would add `CPUFrequencyFromApple` field, and then modify the part near `Calculate the TSC frequency only if ART frequency is not available` to try Apple before trying PM Timer. The recalculate part there is for debugging, so you would always calculate PM Timer frequency in DEBUG builds but do not do that if Apple frequency is available in RELEASE builds.

Hope it helps.

**Comment by Bmju** [comment]
It does help - but also wasn't the part of the codebase I had my eye on next to do something useful... and does indeed continue to look fairly far from trivial. ;)

Can I just confirm, my current understanding is that none of these values affect very much at all, OS or machine behaviour-wise: only known one being FSBFrequency (definitely) and ARTFrequency (possibly, or can that not be wrong?) in Data Hub affecting system time-of-day clock slightly?

Certainly, none of it affects the _actual_ speed at which the processor runs, even if there is adaptive frequency control (or whatever that is properly called), correct?

**Comment by vit9696** [comment]
OpenCore relies on `CPUFrequency` in many ways, the operating system indeed does only need `FSBFrequency` and `ARTFrequency`. I am not positive whether OpenCore can affect the operating system due to incorrect `CPUFrequency`, some say it might.

**Comment by PMheart** [comment]
@MikeBeaton Hello, I made an initial progress on this. Could you please try it? You may find artifacts in GitHub Actions [here](https://github.com/acidanthera/OpenCorePkg/actions/runs/634301200).
