### ISSUE TITLE
Touchpad not working HP Envy x360 13-ar0014nw 

### ISSUE THREAD

**Issue by snakus** [acidanthera/bugtracker#1485]
VooDoo detects touchpad but not working.
Here's my efi folder https://www.mediafire.com/file/4npoi63pztyxcx6/EFI.zip/file
System log and aida log in attachments
[aida.txt](https://github.com/acidanthera/bugtracker/files/5950880/aida.txt)
[logsystem.txt](https://github.com/acidanthera/bugtracker/files/5951208/logsystem.txt)

**Comment by Andrey1970AppleLife** [comment]
Write to developer VoodooI2C
