### ISSUE TITLE
Cannot boot MacPro7,1

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1487]
If the security is disabled it halts at IOBCC- timeout (see panic log), if it is enabled it boots to recovery only
![IMG_0327](https://user-images.githubusercontent.com/7897244/107407751-0ab44a80-6ad8-11eb-9b1b-37a7f532c513.jpg)
[config-2.plist.zip](https://github.com/acidanthera/bugtracker/files/5953335/config-2.plist.zip)

[opencore-2021-02-09-175221.txt.zip](https://github.com/acidanthera/bugtracker/files/5953318/opencore-2021-02-09-175221.txt.zip)

**Comment by startergo** [comment]
Link to the tests:
https://forums.macrumors.com/threads/opencore-on-mac-pro-7-1.2283835/

**Comment by vit9696** [comment]
Well, the error says it basically. macOS cannot connect to the bridge. This looks like some macOS init bug, which I have not seen happening on T2 MBP models. Not sure whether it is a configuration issue, but you can consider trying to disable `AppleSecureBoot` override or perhaps other overrides.

**Comment by startergo** [comment]
Why is it always booting to recovery when security is enabled? Is it for the same reason?

**Comment by vit9696** [comment]
Most likely because OpenCore is not signed by Apple, and Mac EFI cannot boot anything else.

**Comment by trus0und** [comment]
Hey @vit9696 - Thanks for looking at this (this is my MacPro7,1 I am trying to get going). Are there any specific overrides you think would be neccesary here in the config, or should OpenCore be able to boot macOS provided Secure Boot is set to 'No Security' and 'Allow booting of external media' in the firmware settings?

**Comment by vit9696** [comment]
I do not know of anything special at the very least :x

**Comment by startergo** [comment]
> I do not know of anything special at the very least :x

Vit so rEFInd boots the OS. Shouldn't it be affected too?

**Comment by vit9696** [comment]
Should be the same. If OC does not, then config.plist is wrong.

**Comment by startergo** [comment]
> Should be the same. If OC does not, then config.plist is wrong.

It works now. Set these to False:
```
<key>DisableIoMapper</key>
			<false/>
<key>EnableJumpstart</key>
			<false/>
```
Most probably is ```DisableIoMapper```. What do you think?

**Comment by vit9696** [comment]
Huh? What do I *think* should you disable? I do not have a crystal ball here. If you want my opinion, activating DisableIoMapper is absolutely bizarre, why turn off the IOMMU if your system works fine with it enabled? It strongly enhances security. As for JumpStart, I don't know, T2-based Macs always have latest APFS driver bundled in them, not sure there is a big reason to use a JumpStart-based solution.

**Comment by startergo** [comment]
I was just trying to understand what prevented the Mac from booting. Never mind apparently both settings are not appropriate for MP7,1
