### ISSUE TITLE
System Update Always Shows Your Mac Is Up to Date

### ISSUE THREAD

**Issue by singhalrishi27** [acidanthera/bugtracker#1488]
Hello Dev's,
 I'm using Big Sur Beta since 11 Beta 2 has been out..
Surprisingly and Annoyingly I was not able to see any updates in system preferences it always says Your Mac is up to date even on Catalina Big Sur update is not visible to me which was used to visible in the past. 

So I used to download full installer from App Store and reinstalled whole os but it is painfully expensive process if anyone knows what to do please help

Now 11.2 Update was still not visible so I downloaded full package from app store

To escalate the issue I tried full format and reinstallation of whole os all kext and open core has been updated to latest version..

I don't what is the issue 
First I thought it's SMBIOS so I changed it still didn't work
So I thought HD 4000 is not natively Supported and apple is checking other parameters to deliver updates. Then I asked reddit and many people had same issue even with 8th Gen CPUs and completely different specs.

I have latest opencore 0.6.6 and latest kexts from acidanthera repo

**Comment by singhalrishi27** [comment]
https://www.icloud.com/iclouddrive/0qCp2FTz7LVCwRPgMTk2g19ZA#EFI

My efi

**Comment by vit9696** [comment]
I do not believe OpenCore has any effect on this. `MacBookPro11,1` had Big Sur rollup delays due to early Big Sur updates causing [boot failures](https://www.macrumors.com/2020/11/15/macos-big-sur-update-bricking-some-macbook-pros/) on these machines. Perhaps it is still not resolved.

**Comment by singhalrishi27** [comment]
> I do not believe OpenCore has any effect on this. `MacBookPro11,1` had Big Sur rollup delays due to early Big Sur updates causing [boot failures](https://www.macrumors.com/2020/11/15/macos-big-sur-update-bricking-some-macbook-pros/) on these machines. Perhaps it is still not resolved.

Other people are having same issues with completely different systems

**Comment by singhalrishi27** [comment]
@vit9696 
You closed my issue without even checking or verifying anything I disabled blacklist apple update changed smbios to 2015 formatted my drive then reinstalled macos without logging in to apple account tried duplicate apple account still can't see any updates in system preferences

**Comment by vandroiy2013** [comment]
<img width="677" alt="Снимок экрана 2021-02-10 в 10 24 48" src="https://user-images.githubusercontent.com/8144780/107483877-558e9a80-6b8a-11eb-8ea8-5c03eb6ab654.png">

It should be 00000000 as in sample.config
By the way bugtracker is not a support forum! That's why @vit9696 closed your issue.

**Comment by singhalrishi27** [comment]
@vit9696 
![Screenshot 2021-02-10 at 2 31 57 PM](https://user-images.githubusercontent.com/67616808/107488036-d6f72480-6bac-11eb-84a9-028358f87f59.png)
