### ISSUE TITLE
Underscore after restarting but not after a cold start

### ISSUE THREAD

**Issue by izo1** [acidanthera/bugtracker#1489]
Hello, I have a X299 build with OpenCore 0.6.6, after restarting, there is an underscore (or dash) in the OC menu with nothing else on. We have to hard reboot (turn off power/on) and it goes back to normal.

This has gotten worse over the various version of OpenCore and now it happens after system updates multiple times as it reboots.

There are many others who have the same issue.

**Comment by vit9696** [comment]
From what I heard it is related to some ASMedia USB controller issue and Big Sur drivers. Yet I do not know much about it. The issue is not related to OpenCore, as the freeze happens before OC menu.
