### ISSUE TITLE
Tools' names won't display in OpenCanopy if OC_ATTR_USE_POINTER_CONTROL is disabled

### ISSUE THREAD

**Issue by derbalkon** [acidanthera/bugtracker#1491]
I have been using `<integer>15</integer>` for `PickerAttributes` to use modern icon set and avoid displaying cursor. However, I recently found that all tools I added display only "Tool" in OpenCanopy, instead of displaying the specific name I wrote in config.plist. I further investigated this issue by changing `PickerAttributes` to `<integer>25</integer>` (all enabled) and tools displayed the correct name I desired. 

The only thing I have changed is to toggle value `0x0010` `OC_ATTR_USE_POINTER_CONTROL`. As described in manual, `OC_ATTR_USE_POINTER_CONTROL` is used for pointer control support in `PickerAttributes`. Is this a bug or is this by design not to display the names of tools?

**Comment by Andrey1970AppleLife** [comment]
Invalid bit mask.
