### ISSUE TITLE
M.2 Nvme Speed Problem

### ISSUE THREAD

**Issue by furkanmermi07** [acidanthera/bugtracker#1492]
Hi. I am sorry for my bad english. I have Asus Rog Strix z490-E Gaming and Kingston SKC2500M81000G

Kingston has 2900mb/s write speed, 3400mb/s read speed but I see a 1600mb/s value with hackintosh.

I have Lilu(1.5.1) and NVMeFix(1.0.5)

Is there a solution for the speed problem?

I use Opencore(0.6.6)

my efi: [EFI.zip](https://github.com/acidanthera/bugtracker/files/5961245/EFI.zip)

![Ekran Resmi 2021-02-10 22 53 04](https://user-images.githubusercontent.com/78877434/107565681-f9ad2b80-6bf4-11eb-98ef-d79e8e7b5074.png)

**Comment by vit9696** [comment]
No, sorry, you get different speeds and support level depending on the driver.
