### ISSUE TITLE
DOCS: Current build broken

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1494]
@dakanji - Sorry, it looks like unintentionally removing `\end{itemize}` from `Configuration.tex` L6314 in https://github.com/acidanthera/OpenCorePkg/commit/bf999acf6e04efda9780a1099648bd5ce393774c has broken the current docs build (i.e. running `./BuildDocs.tool` from within `Docs` now gives errors!).

Additional info: the itemized list at that point has also changed to an itemized list of one item, which seems likely wrong? Anyway I do not feel able to see what it was meant to be well enough to offer a quick-fix PR.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/OpenCorePkg/commit/d11b92f6d45c3604644719bb97f9a015e08982d8

**Comment by Bmju** [comment]
@Andrey1970AppleLife - many thanks for the correct fix to get the build working, but I am pretty unsure that the remaining docs changes made at that point were intended.

Before:

<img width="867" alt="Screenshot 2021-02-11 at 13 41 56" src="https://user-images.githubusercontent.com/25643187/107644215-0ec6a080-6c6f-11eb-8f96-a1f04be455b9.png">

After:

<img width="861" alt="Screenshot 2021-02-11 at 13 43 21" src="https://user-images.githubusercontent.com/25643187/107644290-27cf5180-6c6f-11eb-8cc3-42b0fa0ad93e.png">

Looking at the content, I am pretty unsure that the remaining two bullet points should have been merged into one and I am also pretty unsure if the middle bullet point should even have been removed here at all?

**Comment by Andrey1970AppleLife** [comment]
CC @vit9696

**Comment by Bmju** [comment]
@vit9696 - Am very happy to revise quickly if @dakanji not free right now?

It looks very likely to me that items in list should go back to separate items, and also (since nothing at all about it was mentioned in description or discussion of earlier PR, I believe) that "Set to empty string not to change screen resolution." was removed in error and can be reinserted?

Or can happily leave for @dakanji to check and confirm (but maybe Issue should stay open?)

**Comment by dakanji** [comment]
> "Set to empty string not to change screen resolution." was removed in error and can be reinserted?

No. That is taken care of under the failsafe definition. Should just be two bullet points

**Comment by Bmju** [comment]
@dakani - not sure, apologies but I still think something necessary may have been removed: https://github.com/acidanthera/OpenCorePkg/pull/204#issuecomment-777639654

**Comment by Bmju** [comment]
> No. That is taken care of under the failsafe definition. Should just be two bullet points

Okay, I see it now!
