### ISSUE TITLE
PS2 Keybaord not working in OpenCore Picker with X64 Legacy BIOS

### ISSUE THREAD

**Issue by trueToastedCode** [acidanthera/bugtracker#1495]
- (Keybaord is definitely PS2 / Confirmed by Windows / Working with PS2 Kext's in macOS)
- No UEFI support on target device (Medion x6815)

Drivers:
```
Ps2KeyboardDxe.efi
Ps2MouseDxe.efi
```
Input:
`KeySupport: False` (Turning it to True does not change anything)

Notice: It does work in Clover

---
Version:  OpenCore-0.6.6-RELEASE
[config.plist.txt](https://github.com/acidanthera/bugtracker/files/5967497/config.plist.txt)

**Comment by vit9696** [comment]
KeySupport must be True for PS/2. Without the device it is not really possible to resolve the problem. CC @Goldfish64 

I am closing this in favour of a parent issue. https://github.com/acidanthera/bugtracker/issues/1236

**Comment by vit9696** [comment]
CC @Goldfish64 @nms42
