### ISSUE TITLE
Random Black-Screen at OC Boot Picker on Haier Y11C

### ISSUE THREAD

**Issue by chilledHamza** [acidanthera/bugtracker#1496]
GUI enabled with OpenCanopy & `PickerMode : External`, Sometimes picker is shown and system boots up fine. But randomly it gets stuck at black screen and once it's black rebooting doesn't change anything, this makes it even worse and black-screen becomes permanent now (instead of random), each boot Picker won't show up. only Boot Chime is played (never ending loop of boot chime*s).

With CSM from BIOS, Boot Picker is always visible. but loading animation of Boot Picker is slow/laggy. after the animation everything is fine.

Note : `PickerMode : Builtin` have no issue at all, and works perfectly fine.

My other laptops work fine with OpenCanopy, but I always had this issue whenever I tried OpenCore GUI on Haier Y11C (from the day I migrated to OpenCore), I remember earlier it was always a black screen (around v0.5.9). on OC v0.6.5 setting the Resolution property to `1366x768` worked and I got GUI working. but now with 0.6.6 issue is back again and Resolution value have no effect anymore either.

Here a few logs that I dumped using Debug Version of OC v0.6.6

`CSM : Disabled`, Outcome : Black-Screen
Log : [opencore-2021-02-11-001157.txt](https://github.com/acidanthera/bugtracker/files/5967666/opencore-2021-02-11-001157.txt) & [opencore-2021-02-11-004547.txt](https://github.com/acidanthera/bugtracker/files/5967667/opencore-2021-02-11-004547.txt)

`CSM : Disabled`, Outcome : Boot Picker Displayed, booted up
Log : [opencore-2021-02-11-005450.txt](https://github.com/acidanthera/bugtracker/files/5967683/opencore-2021-02-11-005450.txt)

`CSM : Enabled`, Outcome : Boot Picker Visible, initial animation little slow. but over all it works
Log : [opencore-2021-02-11-004808.txt](https://github.com/acidanthera/bugtracker/files/5967693/opencore-2021-02-11-004808.txt)

@vit9696 `ASSERT_EFI_ERROR (Status = Invalid Parameter)` issue that I had the other day (it's gone) and I cannot reproduce it anymore. you said the it's not in the log and we need a photo. In [opencore-2021-02-07-214439.txt](https://github.com/acidanthera/bugtracker/files/5967828/opencore-2021-02-07-214439.txt) last two lines are : 
```
ASSERT_EFI_ERROR (Status = Invalid Parameter)
ASSERT [OpenCore] MemoryAllocationLib.c(813): !EFI_ERROR (Status)
```
![PXL_20210208_130835637](https://user-images.githubusercontent.com/32929979/107687924-e23f7280-6cc8-11eb-9c2c-cdc20f4b2ef6.jpg)
Just as it says, system halts and is stuck here afterwards (and no more logs either).
but I don't have this error anymore, so I'm not sure what's was the actual cause behind it.

**Comment by vit9696** [comment]
Are you sure you waited long enough? "Failed" logs, especially the first one, show slower boot time. The first one is at least twice slower.

**Comment by chilledHamza** [comment]
> Are you sure you waited long enough?

Just waited about 3 minutes (Release version, no logging), and it's still black. normally when it works picker is shown in about 10 seconds. an [audio recording](https://github.com/acidanthera/bugtracker/files/5968749/recording.zip) of system stuck on black screen with boot chime loop.

With Debug (logging enabled, Target : 83) waited about 15 minutes, and same black screen. the only difference is Boot Chime, with debug it's only played once (unlike the loop of release version) [opencore-2021-02-11-213241.txt](https://github.com/acidanthera/bugtracker/files/5968733/opencore-2021-02-11-213241.txt)

Anther debug boot, this time it worked and booted successfully (Target : 127) [opencore-2021-02-11-220511.txt](https://github.com/acidanthera/bugtracker/files/5968737/opencore-2021-02-11-220511.txt)


> "Failed" logs, especially the first one, show slower boot time. The first one is at least twice slower.

That is possibly due to debug version, takes a lot more time than release. With debug boot time basically depends on Target value.

**Comment by vit9696** [comment]
> with debug it's only played once (unlike the loop of release version) opencore-2021-02-11-213241.txt

According to this log the UI started, had timeout, then tried booting from the first available option, which was one of the OpenCore installations:

```
229:445 00:027 OCB: Perform boot EFI to dp PciRoot(0x0)/Pci(0x17,0x0)/Sata(0x1,0xFFFF,0x0)/HD(1,GPT,43441B85-D890-4F4D-B72A-2CF260571658,0x28,0x64000)/\EFI\BOOT\BOOTX64.EFI (0/0)
```

What makes it weird is the time spent to reach this:

```
22:645 00:023 OCB: Showing menu... (polling hotkeys)
22:669 00:024 OCUI: Console attributes: 0
223:889 201:219 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
```

It took over 3 minutes to execute three lines that do roughly nothing:

```C
  DEBUG ((DEBUG_INFO, "OCUI: Console attributes: %d\n", Context->ConsoleAttributes));

  UseVolumeIcon   = (Context->PickerAttributes & OC_ATTR_USE_VOLUME_ICON) != 0;
  UseDiskLabel    = (Context->PickerAttributes & OC_ATTR_USE_DISK_LABEL_FILE) != 0;
  UseGenericLabel = (Context->PickerAttributes & OC_ATTR_USE_GENERIC_LABEL_IMAGE) != 0;

  DEBUG ((DEBUG_INFO, "OCUI: UseDiskLabel: %d, UseGenericLabel: %d\n", UseDiskLabel, UseGenericLabel));
```

From this I can conclude the following:

- Your USB storage is likely dying or at the very least it is not well-compatible with the UEFI firmware on this laptop. The latter is actually possible and not too uncommon, especially with USB 2.0 flash. It may cause random delays when storing logs that are minutes long per message. Thus the severe delay till startup time.

I am not positive your screen actually failed to initialise, as you may have simply missed the time it showed OpenCanopy for a short amount of time and failed to boot. According the log the framebuffer is working fine and is already at 1366x768:

```
07:557 00:235 OCC: Installing GOP (Unsupported) on ConsoleOutHandle...
07:582 00:025 OC: Requested resolution is 0x0@0 (max: 1, force: 0) from Max
07:605 00:022 OCC: Requesting 0x0@0 (max: 1) resolution, curr 0, total 4
07:627 00:022 OCC: Current FB at 0xC0000000 (0x408000), format 1, res 1366x768 scan 1376
07:650 00:022 OCC: Mode 0 - 1366x768:1
07:673 00:022 OCC: Mode 1 - 640x480:1
07:696 00:022 OCC: Mode 2 - 800x600:1
07:721 00:025 OCC: Mode 3 - 1024x768:1
07:743 00:022 OCC: Current mode matches desired mode 0
07:766 00:022 OC: Changed resolution to 0x0@0 (max: 1, force: 0) from Max - Already started
```

Please replace your USB, and next time issue occurs, make sure that you can see BIOS logo on startup but OpenCanopy actually shows nothing even after 10 minutes, confirm that with logs.

**Comment by chilledHamza** [comment]
> Your USB storage is likely dying or at the very least it is not well-compatible with the UEFI firmware on this laptop. The latter is actually possible and not too uncommon, especially with USB 2.0 flash. It may cause random delays when storing logs that are minutes long per message. Thus the severe delay till startup time.

I'm not certain about the dying part, I tried different USBs, same results. I have OC Release version in EFI partition on my SATA SSD (doesn't support NVMe) and black screen happens with that as well. so is that supposed to mean my SSD is dying as well?
I haven't tried Debug version from EFI partition because it's easier to copy/view logs from USB on my other laptop.

> I am not positive your screen actually failed to initialise, as you may have simply missed the time it showed OpenCanopy for a short amount of time and failed to boot. According the log the framebuffer is working fine and is already at 1366x768:

Won't it boot to my default volume from NVRAM (after that short amount of time)?

>Please replace your USB, and next time issue occurs, make sure that you can see BIOS logo on startup but OpenCanopy actually shows nothing even after 10 minutes, confirm that with logs.

>> Anther debug boot, this time it worked and booted successfully (Target : 127) [opencore-2021-02-11-220511.txt](https://github.com/acidanthera/bugtracker/files/5968737/opencore-2021-02-11-220511.txt)

This log was generated from different USB, but I didn't try to get black screen. It takes about 2/3 reboots to go black, BIOS logo is always shown but Picker visibility is complicated. It's easier to spot (if it will show up or not) with Debugging disabled (with boot chime loop), but takes minutes with debugging enabled.

**Comment by vit9696** [comment]
> I'm not certain about the dying part, I tried different USBs, same results. I have OC Release version in EFI partition on my SATA SSD (doesn't support NVMe) and black screen happens with that as well. so is that supposed to mean my SSD is dying as well?

Different logs may have different failure scenarios. It is likely that SATA SSD and USB flash have different issues. It is not really possible to say for sure without logs, and even from the logs it cannot be observed with good certainty. I know that several BIOSes simply do not work with many USB flashes, and this is especially the case with USB 2.0 flashes. With them it may take over 20 minutes to boot OpenCore (literally) with the flash itself being perfectly fine.

> Won't it boot to my default volume from NVRAM (after that short amount of time)? and what about endless loop of boot chime?

For some reason you do not have the default volume in NVRAM:

```
19:706 00:023 OCB: Dumping BootOrder
19:730 00:023 OCB: 0 -> Boot0001 = BBS(0x81,,0x0)
19:755 00:025 OCB: 1 -> Boot0002 = BBS(0x82,,0x0)
19:778 00:023 OCB: 2 -> Boot0003 = BBS(0x83,,0x0)
```

All these entries are invalid as you can see. Therefore the default entry is chosen on "first discovered" bases, and it happened to be OpenCore installation on your SSD (most likely).

> This log was generated from different USB, but I didn't try to get black screen. It takes about 2/3 reboots to go black, BIOS logo is always shown but Picker visibility is complicated. It's easier to spot (if it will show up or not) with Debugging disabled (with boot chime loop), but takes minutes with debugging enabled.

Could you disable boot chime? I wonder if it is related. Also, we have `DirectGopRendering` option. Try it.
