### ISSUE TITLE
DOCS: Warnings against using "Apple Inc." as vendor

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1497]
At `PlatformInfo/Generic/SpoofVendor`,  `PlatformInfo/SMBIOS/BIOSVendor` and  `PlatformInfo/SMBIOS/SystemManufacturer` there are warnings against using "Apple Inc." as the vendor &/or against including the word "Apple" in these vendor strings.

I wonder if the docs here should be updated to indicate that it IS okay to leave these values unchanged if working with unchanged serial numbers on legacy Mac hardware?

If so, this would again raise the question of what _is_ safe to change in these cases: https://github.com/acidanthera/bugtracker/issues/1469#issuecomment-778325679

**Comment by Andrey1970AppleLife** [comment]
I don't think that owners real Macs the silly.
Rather attentively to read the document.

**Comment by Bmju** [comment]
Wha?

**Comment by Bmju** [comment]
I _think_ you're saying that owners of real Macs are not that silly, and that if they read the docs properly they will understand what to do?

But the docs say:

"OEM manufacturer of the particular board. Shall not be specified unless strictly required. Should not contain Apple Inc., as this confuses numerous services present in the operating system, such as firmware updates, eficheck, as well as kernel extensions developed in Acidanthera, such as Lilu and its plugins. In addition it will also make some operating systems like Linux unbootable."

As far as I can see honestly NOTHING on there (or anywhere else that I have found) makes it at all clear that "none of these warnings apply on real Mac hardware"!

Is it even true that none of them apply? I'm _genuinely_ not sure! And I genuinely am sure that if none of them apply, the wording should be amended.

There are widely used projects out there now, faking everything, including the vendor, on real Mac hardware. If this warning does not apply there, it should be changed!!

**Comment by Bmju** [comment]
Based on your response plus re-reading, I think I now see what it is meant to mean. I believe it is not really clearly written now! I'll propose be a PR -with some *small* change to make it more clear.

Something like "... Use failsafe unless strictly required. Do not override to contain *Apple inc.*, ..."

Thanks.

**Comment by vit9696** [comment]
You can add something here if you want, yes, but in general Apple hw may be left Apple of course.

**Comment by Bmju** [comment]
I would have thought it was "of course" too - but it seems to be the opposite of what is done by OCLP?

[config](https://github.com/dortania/Opencore-Legacy-Patcher/blob/74c0e9e71703038013aa4e8d5dc267901bd24e1c/payloads/Config/v0.6.6/config.plist#L822-L835)
[serial gen](https://github.com/dortania/Opencore-Legacy-Patcher/blob/74c0e9e71703038013aa4e8d5dc267901bd24e1c/Resources/BuildOpenCore.py#L304-L336)
[comment](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/page-356?post=29600514#post-29600514)
