### ISSUE TITLE
OC: NVRAM SSN/HW_SSN never set to SystemSerialNumber

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1500]
Variables `SSN`, `ROM` and `MLB` exist by default (pre-OS boot, after NVRAM reset, no OC) in NVRAM section 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14 on my late 2012 13" retina display MacBookPro10,2. (None of `HW_SSN`, `HW_ROM` and `HW_MLB` exist by default, as expected for my system's age.)

The existing default values make it apparent that these values correspond to `PlatformInfo/Generic` as follows: `SSN` -> `SystemSerialNumber`, `ROM` -> `ROM`, `MLB` -> `MLB`.

When I configure values for these `PlatformInfo/Generic` settings in OC, along with `UpdateNVRAM=true`, OC writes the `PlatformInfo` `ROM` and `MLB` values to  NVRAM `ROM` and `MLB` as expected (and sometimes, also as expected, and depending on details of settings, to `HW_ROM` and `HW_MLB`).

However, OC never updates `SSN` and never writes to `HW_SSN`. I would expect it to populate these two NVRAM variables following the same pattern shown for `ROM`, `HW_ROM`, `MLB` and `HW_MLB` in [this comment](https://github.com/acidanthera/bugtracker/issues/1469#issuecomment-778855042) from a related issue. Note also that `SSN` and `HW_SSN` are documented in [this list of NVRAM vars linked from Configuration.pdf](https://docs.google.com/spreadsheets/d/1HTCBwfOBkXsHiK7os3b2CUc6k68axdJYdGl-TyXqLu0/edit#gid=0), along with the MLB and ROM values.

**Comment by vit9696** [comment]
Please confirm that it works correctly.

**Comment by Bmju** [comment]
Apologies for the slight delay - I've now had a chance to check. Yes, it's working. Thanks!

<table>
<tr><th>NVRAM var</th><th>Explicit user value 0.6.7</th><th>New `OEM` value 0.6.7</th><th>Empty string value 0.6.7</th></tr>
<tr><td>SSN</td><td>User</td><td>OEM</td><td>OEM</td></tr>
<tr><td>HW_SSN</td><td>User</td><td>OEM</td><td>Not present</td></tr>
</table>
