### ISSUE TITLE
Docs/terminology: 'plist multidata' preferable to 'plist metadata'?

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1501]
In https://github.com/acidanthera/bugtracker/issues/1469#issuecomment-778850549 @vit9696 referred to `PlatformInfo/Generic/ROM` as being of type `plist multidata`. This sounds reasonable to me.

However, in `Configuration.pdf` that and all of the few other variables of the same type are referred to as being of type `plist metadata`.

Having seen both options,`plist multidata` reads to me as a significantly better name for the type.

I could offer the following post hoc justifications for this feeling...

 - `plist metadata` _means_ that it is data about data, or data about plists, which it is not
 - `plist metadata` sounds (to me) more as if it is probably some built in, known feature of plists, whereas `plist multidata` sounds (at least to me) much more as if it is very probably something added by OC
 - `plist multidata` admittedly does sound as if it might be a type of data allowing multiple data elements - but it also sounds reasonably as if it might correspond (as it does) to a data field which can be in multiple different formats

Put another way, I think if I saw `plist multidata` as the type of some particular variable which I was looking at, I would have a much more immediate sense of what I was looking at, and why it might matter to me.

Is there any scope for a PR globally changing the four occurrences of `plist metadata` in the docs to `plist multidata` - which obviously is, thereby, a request to change the doc (and project?) terminology? If not a lot rides on this, perhaps it would be okay to change, though I understand - of course - if you either disagree with my sense of the better term, or if it is too late for a change. If not either of these, can I seriously propose this as a possible worthwhile change?

**Comment by vit9696** [comment]
I do not mind changing this if a PR is sent. I would request to also rename PlistMetaXXX methods in OcXmlLib accordingly.

**Comment by Bmju** [comment]
If this is not urgent, this may be in a day or two. Many thanks.
