### ISSUE TITLE
Unable to boot OC on MBP5,3 due to "Switch to application type for better FW compatibility"

### ISSUE THREAD

**Issue by kommtzeitkonrad** [acidanthera/bugtracker#1502]
As already issued in https://github.com/dortania/Opencore-Legacy-Patcher/issues/59 it is not possible to boot the latest release of OpenCore on an MacBookPro5,3. The commit that introduced this bug is https://github.com/acidanthera/OpenCorePkg/commit/1c445a99d653a510b5561b2995735db2d7b3d611.

EFI files and log from last working commit (https://github.com/acidanthera/OpenCorePkg/commit/dc1a0d8a2227e99eeecae82a8a466f42575599b4):

- [MBP5,3-EFI-OC-DBG-066-2021-01-26.zip](https://github.com/acidanthera/bugtracker/files/5979445/MBP5.3-EFI-OC-DBG-066-2021-01-26.zip)
- [opencore-2021-02-15-040627.txt](https://github.com/acidanthera/bugtracker/files/5979448/opencore-2021-02-15-040627.txt)

**Comment by vit9696** [comment]
This will happen when OpenCore.efi is launched with an outdated booter (BOOTx64.efi, Bootstrap.efi).

**Comment by kommtzeitkonrad** [comment]
> This will happen when OpenCore.efi is launched with an outdated booter (BOOTx64.efi, Bootstrap.efi).

Booter files are of course updated with the ones from [the respective artifact](https://github.com/acidanthera/OpenCorePkg/suites/1904237618/artifacts/37368773).

**Comment by kommtzeitkonrad** [comment]
The problem can easily be reproduced when using [Opencore-Legacy-Patcher 0.0.9](https://github.com/dortania/Opencore-Legacy-Patcher/releases/tag/0.0.9) (uses https://github.com/acidanthera/OpenCorePkg/commit/f32fdd186e0a82fed428b6cf65ff5b6bc9b996f3, will boot) and [version 0.0.10](https://github.com/dortania/Opencore-Legacy-Patcher/releases/tag/0.0.10) (uses https://github.com/acidanthera/OpenCorePkg/commit/43f53398b1d178a12d2f2d97afbdd4c85ee99d7e, will NOT boot). Behaviour should be the same on similar older Apple firmwares.

**Comment by vit9696** [comment]
@kommtzeitkonrad yeah, that's why I said the issue is on your side. We have many native Mac users, including some right on this bugtracker, who report bugs on master version, and [MP51 owners](https://forums.macrumors.com/threads/opencore-on-the-mac-pro.2207814/), who updated to OpenCore 0.6.6 with no issues.

OpenCore 0.6.6 dropped Bootstrap.efi support, the most likely situation with your setup is that whatever updated your OpenCore, neither deleted Bootstrap.efi, nor copied BOOTx64.efi from OpenCore 0.6.6 to Bootstrap.efi. As a result OpenCore 0.6.6 is started with Bootstrap from 0.6.5, and shows the error you see.

**Comment by kommtzeitkonrad** [comment]
@vit9696, I would not post this, if I haven't quadruple-checked it a dozen times. Let me try to show this with files from OpenCorePkg repository only while building the EFI folder from scratch every time (no Bootstrap.efi at any time):

On a system running 10.15.7 (19H524) download 0.6.6 release of OpenCore:
```
gh release --repo acidanthera/OpenCorePkg download 0.6.6
unzip OpenCore-0.6.6-DEBUG.zip
```
Then prepare a USB drive with the bare minimum to boot OpenCore and OpenShell afterwards:
```
sudo diskutil eraseDisk JHFS+ UntitledHFS disk3
sudo diskutil mount disk3s1

mkdir -p /Volumes/EFI/EFI/BOOT /Volumes/EFI/EFI/OC/ACPI /Volumes/EFI/EFI/OC/Drivers /Volumes/EFI/EFI/OC/Kexts /Volumes/EFI/EFI/OC/Resources /Volumes/EFI/EFI/OC/Tools
cp -p X64/EFI/BOOT/BOOTx64.efi /Volumes/EFI/EFI/BOOT
cp -p X64/EFI/OC/Drivers/OpenRuntime.efi /Volumes/EFI/EFI/OC/Drivers
cp -p X64/EFI/OC/Tools/OpenShell.efi /Volumes/EFI/EFI/OC/Tools
cp -p X64/EFI/OC/Tools/ResetSystem.efi /Volumes/EFI/EFI/OC/Tools
cp -p X64/EFI/OC/OpenCore.efi /Volumes/EFI/EFI/OC/

cp -p Docs/Sample.plist /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Delete ':#WARNING - 1'" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Delete ':#WARNING - 2'" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Delete ':#WARNING - 3'" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Delete ':#WARNING - 4'" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Booter:Quirks:AvoidRuntimeDefrag' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Booter:Quirks:EnableSafeModeSlide' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Booter:Quirks:EnableWriteUnprotector' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Booter:Quirks:ProvideCustomSlide' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Booter:Quirks:SetupVirtualMap' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Delete ':DeviceProperties:Add:PciRoot(0x0)/Pci(0x1b,0x0)'" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Kernel:Add:0:Enabled' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Kernel:Add:1:Enabled' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Kernel:Add:2:Enabled' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Kernel:Add:3:Enabled' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Kernel:Add:4:Enabled' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Kernel:Add:5:Enabled' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Kernel:Add:6:Enabled' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Misc:Debug:Target' 115" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Misc:Security:SecureBootModel' Disabled" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Misc:Security:Vault' Optional" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Misc:Tools:0:Enabled' true" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':Misc:Tools:2:Enabled' true" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':NVRAM:Add:7C436110-AB2A-4BBB-A880-FE41995C9F82:prev-lang\:kbd' de:3" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':PlatformInfo:Automatic' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':PlatformInfo:UpdateDataHub' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':PlatformInfo:UpdateNVRAM' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':PlatformInfo:UpdateSMBIOS' false" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':UEFI:Drivers:0' #HfsPlus.efi" /Volumes/EFI/EFI/OC/config.plist
/usr/libexec/PlistBuddy -c "Set ':UEFI:ProtocolOverrides:FirmwareVolume' false" /Volumes/EFI/EFI/OC/config.plist
```
Running `ocvalidate` tool reports no errors:
```
% Utilities/ocvalidate/ocvalidate /Volumes/EFI/EFI/OC/config.plist

Done checking /Volumes/EFI/EFI/OC/config.plist in 1 ms
```
Afterwards inserting this USB drive ([EFI-MBP5_3-OC-DBG-066-2021-02-02.zip](https://github.com/acidanthera/bugtracker/files/5992601/EFI-MBP5_3-OC-DBG-066-2021-02-02.zip)) into a MacBookPro5,3 running `MBP53.88Z.00AC.B03.0906151647` firmware with blank drives which has SMC and NVRAM/PRAM reset will not boot, but only show a drive icon with a question mark.

Now deleting all files and starting again from scratch with the 0.6.5 release of OpenCore:
```
gh release --repo acidanthera/OpenCorePkg download 0.6.5
unzip OpenCore-0.6.5-DEBUG.zip
```
For the preparation of the USB drive the exact same commands as above to prepare the drive from scratch are used and `ocvalidate` tool again shows no errors. The resulting USB drive ([EFI-MBP5_3-OC-DBG-065-2021-01-04.zip](https://github.com/acidanthera/bugtracker/files/5992605/EFI-MBP5_3-OC-DBG-065-2021-01-04.zip)) will successfully boot (log: [opencore-2021-02-17-011521.txt](https://github.com/acidanthera/bugtracker/files/5992607/opencore-2021-02-17-011521.txt)).

Thanks to GitHub Actions and the resulting build artifacts it was relatively easy to find the commit that introduced the inability to boot OpenCore on a MacBookPro5,3.

Downloading the `macOS XCODE5 Artifacts.zip` file from https://github.com/acidanthera/OpenCorePkg/runs/1771404161 (commit https://github.com/acidanthera/OpenCorePkg/commit/dc1a0d8a2227e99eeecae82a8a466f42575599b4 from Jan 26, 2021), unzipping it and afterwards running the same commands as above to prepare the USB drive from scrach ([EFI-MBP5_3-OC-DBG-066-2021-01-26-dc1a0d8.zip](https://github.com/acidanthera/bugtracker/files/5992732/EFI-MBP5_3-OC-DBG-066-2021-01-26-dc1a0d8.zip)) will result in a successful boot (log: [opencore-2021-02-17-020309.txt](https://github.com/acidanthera/bugtracker/files/5992735/opencore-2021-02-17-020309.txt)).

Doing the same procedure with the `macOS XCODE5 Artifacts.zip` file from https://github.com/acidanthera/OpenCorePkg/runs/1771723274 (the next commit https://github.com/acidanthera/OpenCorePkg/commit/1c445a99d653a510b5561b2995735db2d7b3d611 from Jan 26, 2021) will result in an unsuccessful boot as described above (EFI files: [EFI-MBP5_3-OC-DBG-066-2021-01-26-1c445a9.zip](https://github.com/acidanthera/bugtracker/files/5992772/EFI-MBP5_3-OC-DBG-066-2021-01-26-1c445a9.zip)).

**Comment by vit9696** [comment]
I guess we can try dumping some logs to diagnose it.

**Comment by vit9696** [comment]
Provide all onscreen logs via a photo and/or a video. Bootstrap.efi needs to be renamed to BOOTx64.efi. Thanks!

[test-r1.zip](https://github.com/acidanthera/bugtracker/files/5993406/test-r1.zip)

**Comment by kommtzeitkonrad** [comment]
The following output is looped:

```
BS: Starting OpenCore application…
BS: Booter path - \EFI\BOOT\BOOTX64.efi
OCFS: Trying to locate filesystem on AC821698 AC05EE98
OCFS: Filesystem DP - \EFI\BOOT\BOOTX64.efi
BS: Trying to load OpenCore image…
BS: Relative path - EFI
BS: Startup path - EFI\OpenCore.efi (0)
BS: Fallback to absolute path - EFI\OC\OpenCore.efi
BS: Read OpenCore image of 1241088 bytes
OCM: Loaded image at AC395C98 handle
OC: Starting OpenCore…
OC: Missing boot device
OCM: Failed to start image - Invalid Parameter
BS: Failed to start OpenCore image - Invalid Parameter
BS: Failed to load OpenCore from disk - Invalid Parameter
```

https://user-images.githubusercontent.com/42938101/108290631-15827580-7191-11eb-9a3d-ef203c59f4a6.mov

![test-r1](https://user-images.githubusercontent.com/42938101/108290888-92155400-7191-11eb-96e6-86885b1c6cc7.png)

**Comment by vit9696** [comment]
Thank you! I pushed a commit to master (it is referenced right above). Tell me if it fixes the problem, and if not, provide a screenshot with the same logging.

**Comment by kommtzeitkonrad** [comment]
Works! :-)

[opencore-2021-02-18-191404.txt](https://github.com/acidanthera/bugtracker/files/6005276/opencore-2021-02-18-191404.txt)
