### ISSUE TITLE
Setting nvram variable fa4ce28d-b62f-4c99-9cc3-6815686e30f9 - Invalid Parameter

### ISSUE THREAD

**Issue by jacksonium** [acidanthera/bugtracker#1505]
This is a re-open of issue #928. 

I also want to achieve the same but ran into the same problem. I tried to create a Dictionary fa4ce28d-b62f-4c99-9cc3-6815686e30f9 under NVRAM ADD in config.plist, then create a child gpu-power-prefs with type DATA and <01000000> and it didnt work and it always has "Invalid Parameter"

However, I could do either one of the following to get this nvram set:

1) I could boot MacOS via Command + S and then type: nvram fa4ce28d-b62f-4c99-9cc3-6815686e30f9:gpu-power-prefs=**%01%00%00%00** (NOTE: nvram -p wont show this variable for some reason, I can see this if i boot up linux to confirm successful boot)
2) Linux: printf "**\x07\x00\x00\x00\x01\x00\x00\x00**" > gpu-power-prefs-fa4ce28d-b62f-4c99-9cc3-6815686e30f9

But I want to do this in Opencore so in case nvram get zapped Opencore can put this back on prior to any OS booting.

**This is important for those of us that has a defective AMD GPU on the Macbook Pro 2011. Setting this variable will tell the machine to use iGPU instead of the AMD GPU.** 

Is there a way to do this at all?

_Originally posted by @jacksonium in https://github.com/acidanthera/bugtracker/issues/928#issuecomment-779327390_

**Comment by jacksonium** [comment]
i understand this is a duplicate but i provided more information.

**Comment by Andrey1970AppleLife** [comment]
You can write to the closed
