### ISSUE TITLE
VirtualSMC Problem

### ISSUE THREAD

**Issue by VinylNerd** [acidanthera/bugtracker#1507]
Hello,

I'm trying to switch from FakeSMC to VirtualSMC, however im having an issue thats stopping me.

if i unplug the power to the laptop while in clamshell mode connected to external display, the laptop automatically sleeps.

FakeSMC does not exhibit this behaviour, however VirtualSMC does, if anyone knows how i could fix it that would be great.

for reference, a real macbook pro will behave exactly how VirtualSMC is, they absolutely refuse to allow use in clamshell mode without power connected (you used to be able to solve this but in catalina apple completely locked it out). This feature alone is a MAJOR upside to hackintosh for me. as sometimes i need to move power around while using the laptop and i don't want it autosleeping in the middle of a video playing or something.

thanks!

**Comment by Andrey1970AppleLife** [comment]
> a real macbook pro will behave exactly how VirtualSMC

**Comment by VinylNerd** [comment]
> You need to find as solve it on real macbook pro.

not possible because of how apple locks down there hardware

also this behaviour is complete undesireable

there is no reason if my laptop is beside me and connected to external display i can use it when open, with power or unplugged, however if i want to use it closed power is required? there is absolutely no logic to this, please correct me if i'm missing something
