### ISSUE TITLE
OC: Remove misleading (?) statement within warning about using Automatic=false

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1508]
Hi - I was planning to raise this, it is somewhat related to https://github.com/acidanthera/bugtracker/issues/1506, and so I felt I should raise it sooner rather than later, as I would also like to give @cdf the chance to comment, if they would like to.

As of not so long ago, the docs included:
<img width="811" alt="Screenshot 2021-02-17 at 07 15 29" src="https://user-images.githubusercontent.com/25643187/108169158-46f73480-70f0-11eb-8942-00508e0e22eb.png">
<img width="470" alt="Screenshot 2021-02-17 at 07 15 43" src="https://user-images.githubusercontent.com/25643187/108169163-478fcb00-70f0-11eb-87a0-e2bab4cdc7e1.png">
<img width="466" alt="Screenshot 2021-02-17 at 07 15 53" src="https://user-images.githubusercontent.com/25643187/108169166-48286180-70f0-11eb-9782-0276c2f20f0f.png">
<img width="585" alt="Screenshot 2021-02-17 at 07 16 47" src="https://user-images.githubusercontent.com/25643187/108169168-48286180-70f0-11eb-88b8-549ea771d782.png">
<img width="595" alt="Screenshot 2021-02-17 at 07 17 42" src="https://user-images.githubusercontent.com/25643187/108169169-48c0f800-70f0-11eb-8299-9d6160c8d3d3.png">

Therefore, previously:

- The as-documented behaviour of the Generic section values read as if it was impossible to obtain auto-detected OEM values for certain system ids (incorrectly, it was possible: https://github.com/acidanthera/bugtracker/issues/1456)
- The as-documented behaviour of the SMBIOS section made it sound (correctly) that this was possible using the SMBIOS section
- The warning about Automatic mode made it sound as if it was safe to do minor SMBIOS fixes using the SMBIOS section, with `Automatic=false`

The first point is now all fixed by https://github.com/acidanthera/OpenCorePkg/commit/8d4981514163fa3d526dfb1c26c190c53c06abb1 . Nothing needs changing about the second point. But the warning mentioned at the third point I believe still remains misleading (if not plain wrong).

If a technique is safe (or even just appropriate) for "_minor_ correction of the SMBIOS", you might very reasonably expect that if you use it to correct the values you need to correct (e.g. `BoardProduct` id, and perhaps `BIOSVersion`...) and use failsafe values for everything else then you will get reasonable and not unexpected behaviour for everything else.

But this is not true, if you do that then (for example...) the `FirmwareFeatures` and `FirmwareFeaturesMask` end up zeroed in the SMBIOS even though present and normal if you check the NVRAM. (Which behaviour, I agree, is correct and to current spec.)

However, as I am understanding it, that is also *exactly* the kind of hard to debug error which the warning against using `Automatic=false` is talking about.

So it seems to me that the part of the Automatic mode warning, which is still unchanged, and which apparently quite clearly entails that using `Automatic=false` is safe for making minor correction to the SMBIOS (etc.?) is misleading, at least.

For that reason, I suggest that that part of the warning should be removed, and the whole warning changed to read (something like):

```
  It is strongly discouraged set this option to \texttt{false}
  when intending to update platform information. Not using
  \texttt{Automatic} mode may lead to hard to debug errors caused
  by inconsistent values between the sections.
```

**Comment by vit9696** [comment]
Probably fine to me…

**Comment by Bmju** [comment]
I don't think this additional info directly impacts on the decision above, but I do think it's probably worth adding, now that I'm sure of the info, if only the make the issues involved more concrete.

So, when posting the Issue above I was already in the middle of confirming for myself that a specific (hard to debug!) issue (shown in the image below) is indeed caused by using the SMBIOS section for 'light' spoofing but leaving `FirmwareFeatures` and `FirmwareFeaturesMask` at failsafe values.

![firmware-update](https://user-images.githubusercontent.com/25643187/108184964-ae6aaf80-7103-11eb-93e6-d0b1b981c7f0.jpeg)

Pretty clearly, the Big Sur installer is reading the relevant bits from the SMBIOS values and so deciding that the Mac cannot read APFS disks. This is resolved by configuring the correct values for my Mac for SMBIOS `FirmwareFeatures` and `FirmwareFeaturesMask`. (Thanks to @Ausdauersportler for spotting the issue, and being helpful enough to mention it to me in a discussion we were having about OC spoofing options - I deduced (for myself, though I'm not suggesting that others were not already aware!) the probable cause, and have just had a chance to do enough testing to replicate the issue and confirm the cause for myself.)

The only correct fix for this, if you are trying to create a `PlatformInfo` section which is safe for multiple Macs, is to use the correct firmware features values _specific to each Mac_. Which requires additional tooling to detect and modify the config file per machine, or else using an OC auto-detect feature. Of which the latter is preferable certainly.

This can already be done (i.e. already 'just works') when using the `Generic` section, although @cdf gives plausible reasons as to why the values generated that may not be ideal for some purposes in #1506. So I leave for discussion in that other issue the question of whether a couple of additional auto-detection features could usefully be added to the `SMBIOS` section, to provide more different spoofing options, for those that want to use them.

**Comment by Bmju** [comment]
It seems we've clarified the main issue which affects this in #1506, and that it's probably most appropriate to eventually upgrade the 'problem' statement to make clear that minor upgrades to SMBIOS _are_ safe after all (in some situations...) - but only as and when whoever can do so takes on the work needed at #1506.

Therefore, minor choice point (to close out this issue):

1. Either, remove the statement I've put into question, in the interim (i.e. until it is safe again); using e.g. wording as proposed at end of Issue statement above; and with the intention (already recorded at #1506) to restore it, reworded slightly as appropriate, as part of the work needed to address #1506
1. Or (simpler, but a little misleading...) just leave it as is for now, even though it is kind of promising a safety which is not really there any more, as of right now...

Happy to do tiny PR for arguably more accurate interim option 1 (recording for posterity, right here, that the explicit intention is to bring it back when ready), or just leave it! (Perhaps rather depends on how long it will take to address #1506!)

@cdf @vit9696?

**Comment by Bmju** [comment]
Tbh I think leave it alone for now, and have everything that needs doing recorded in #1506
