### ISSUE TITLE
"EL[0] was invalidated!!" KP

### ISSUE THREAD

**Issue by jackjack1-su** [acidanthera/bugtracker#1510]
This KP 100% happens when I'm playing Minecraft; and randomly happens when using FCP.
Log is here; (as same as #1343 )
[crash.202010310952.randomcrash.txt](https://github.com/acidanthera/bugtracker/files/6001564/crash.202010310952.randomcrash.txt)
Also tried all of the useable FB.
EFI is [https://github.com/jackjack1-su/SP7config](url)

**Comment by vit9696** [comment]
Well, looks like an issue in the ICL drivers again. Help wanted.

CC @lvs1974 @0xFirewolf @osy
