### ISSUE TITLE
Coverity issues that need attention

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#1513]
Currently there are several code-wise design deficiencies discovered by Coverity. Some of them deserve attention, which are listed below by CID:

- [x] 290217
- [x] 298845
- [x] 302189
- [x] 302190
- [x] 302191
- [x] 302192

CC @mhaeuser @vit9696

**Comment by mhaeuser** [comment]
About half of them were False Positives, though one was close to an actual issue. I added comments to all of them, please check.
