### ISSUE TITLE
i5-8250U 1.60GHz CPU in 'About this Mac' & Sys Profiler displayed as i7 1.8GHz

### ISSUE THREAD

**Issue by LeeBinder** [acidanthera/bugtracker#1515]
- latest OC 0.6.6 stable - same with latest 0.6.7
- correct SMBIOS sys def MacBookPro15,4 for Asus Vivobook S15
- Apple never used the KabyLake-R i5-8250U (closest neighbor is `i5 8259U` in MacBookPro15,2, but that sys def is inferior to MBP 15,4 with these Vivobooks)
- Hackintool correctly displays `Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz`
- only FYI, booted via Clover, i5 is displayed properly in 'About this Mac', but frequency is also wrong 1.8GHz
- via PlatformInfo/ ProcessorType: `609` as per [AppleSmBios.h/i5 8259U](https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleSmBios.h#LC199) -> 50% success: at least the i5 is now correctly displayed, but still 1.8GHz.

Requests:
1. can you please include the `i5-8250U 1.60GHz` in your database to be correctly detected and displayed?
2. can you add an option to overwrite CPU Mhz/ speed in config.plist?

Let me know if you need any more info from me, and how to obtain it. Thank you.

**Comment by dreamwhite** [comment]
> - Apple never used the KabyLake-R i5-8250U (closest neighbor is `i5 8259U` in MacBookPro15,2, but that sys def is not compatible with Big Sur)

May I ask you why that SMBIOS isn't compatible with Big Sur? On my Dell Inspiron 5370 I'm using MBP15,2 and I'm running macOS Big Sur 11.2.1 (20D74).
What you mean by "that sys def is not compatible"? Did you found any issue when using it?
Thanks

**Comment by LeeBinder** [comment]
You are right - I corrected that part. Thanks for pointing this out, dreamwhite 👍

**Comment by Andrey1970AppleLife** [comment]
Configurable TDP-up Frequency 1.80 GHz
https://ark.intel.com/content/www/us/en/ark/products/124967/intel-core-i5-8250u-processor-6m-cache-up-to-3-40-ghz.html

**Comment by LeeBinder** [comment]
@Andrey1970AppleLife so you're saying the 1.8Ghz in About this Mac and Sys Profiler are correct because they always prefer displaying the TDP rather than CPU base frequency?

**Comment by dreamwhite** [comment]
> Configurable TDP-up Frequency 1.80 GHz
> https://ark.intel.com/content/www/us/en/ark/products/124967/intel-core-i5-8250u-processor-6m-cache-up-to-3-40-ghz.html

Thank you so much for the reply.
So if I correctly understood, the Intel Core i5-8250U, despite has a 1.6GHz base clock, is configured, due to TDP-up Frequency, to 1.8GHz, and this shouldn't worry us, right?

**Comment by vit9696** [comment]
Where is log?

**Comment by LeeBinder** [comment]
@vit9696 I have set

```
<key>AppleDebug</key>
	<true/>
```
but no opencore log file generated where it's supposed to be. Do I need the OC debug version for that key to have an effect? I thought the debug version generates a log regardless of that key, and the debug key is for the release version? hmm..

I attach what I have for now :
[debug log via terminal.txt.zip](https://github.com/acidanthera/bugtracker/files/6009139/debug.log.via.terminal.txt.zip)
[EssentialsList-2021-02-19 10.54.15.zip](https://github.com/acidanthera/bugtracker/files/6009140/EssentialsList-2021-02-19.10.54.15.zip)
[hackintool boot log.txt.zip](https://github.com/acidanthera/bugtracker/files/6009142/hackintool.boot.log.txt.zip)
[Send me MacBook-Pro.fritz.box.zip](https://github.com/acidanthera/bugtracker/files/6009143/Send.me.MacBook-Pro.fritz.box.zip)

BTW, even though for this boot I reset back to default

```
<key>ProcessorType</key>
	<integer>0</integer>
```
in 'About this Mac' it still shows i5 now - as if my setting the type to i5 manually before carved that value into NVRAM or so? Beats me...

**Comment by vit9696** [comment]
> in 'About this Mac' it still shows i5 now

Then it is correct.

As for frequency, it is your OEM vendor that packaged the CPU with higher frequency. Closing as resolved.

**Comment by LeeBinder** [comment]
- still no opencore log file even with latest debug version + AppleDebug set to true
- still shows up as i5 in Ab.th.Mac with ProcessorType back to default 0 even after NVRAM reset

I feel double-bummed now :(

**Comment by LeeBinder** [comment]
@vit9696 I see you closed this issue, but how do you explain what I just wrote in the comment above?

**Comment by Andrey1970AppleLife** [comment]
1. Your CPU i5, why there shall be another?
2. Misc Debug Target 67

**Comment by LeeBinder** [comment]
@Andrey1970AppleLife LOL c'mon, you know exactly what I mean: why did Ab.th.Mac with macOS booted via OC display my i5 as i7 to begin with so I had to manually set ProcessorType to 609? And why did it NOT go back to i7 with PT set back to default?

Anyway, I guess it must have been some twisted value in NVRAM, because after resetting NVRAM the CPU type is now displayed correctly even when I boot from my backup volume, so it can't be some file in the macOS file system the ProcessorType setting changed. What actually happens when a value is set there - only direct write to NVRAM?

Thanks for the pointer with Misc Debug Target 67 - log attached for completion:

[opencore-2021-02-19-115820.txt](https://github.com/acidanthera/bugtracker/files/6009498/opencore-2021-02-19-115820.txt)

PS: does that setting `Misc Debug Target 67` + `AppleDebug true` make even the release version of OC create a log, or is the debug version required for that to work?

**Comment by LeeBinder** [comment]
Figured the part with the log out.
