### ISSUE TITLE
Hmmm... Another issue for the ICL Platform Graphics

### ISSUE THREAD

**Issue by jackjack1-su** [acidanthera/bugtracker#1516]
The problem is that screen is blinking when using 1368x912 resolution.
Tried to inject EDIDs and apply any useable patches. Also tried to change different versions of WEG. None of them works.
After updated the macOS, it stops blinking; but it blinks again after a reboot.
(P.S. The System Information Pages shows that my computer is 1.5GHz qual-core i7, but in fact my computer is 1.1GHz i5. Uncertain whether the two are associated.)
EFI is here [https://github.com/jackjack1-su/SP7config](url)

**Comment by m0d16l14n1** [comment]
Can you check already created issues before creating new one? All Ice Lake problems already mentioned 
Just examples: 
https://github.com/acidanthera/bugtracker/issues/1432
https://github.com/acidanthera/bugtracker/issues/1329
https://github.com/acidanthera/bugtracker/issues/1343
https://github.com/acidanthera/bugtracker/issues/1207

**Comment by m0d16l14n1** [comment]
If you want to use HiDPi: currently there are two ways to get rid of blinking - 

1) Change resolution > put laptop to sleep > wake it. Blinking will gone, until you reboot
2) Use external screen connected with HiDPi enabled

**Comment by m0d16l14n1** [comment]
@jackjack1-su 

Hello! To fix HiDPI blinking (in my case it works well, still untested on other laptop) you can use that [way](https://github.com/Ardentwheel/OpenCore-Hasee-X57S1/issues/3#issuecomment-790013456)

With that device-properties for iGPU I currently have no issues with HiDPI.
