### ISSUE TITLE
DMG has been altered

### ISSUE THREAD

**Issue by afzl-wtu** [acidanthera/bugtracker#1518]
After following fully open core guide and making mac os installer on windows pc on hp EliteBook 8470p, it just shows the boot menu of OpenCore, and when I select booting from the USB drive it just says:
DMG has been altered
**LoadImage failed - Unsupported**
                   and then return back to opencore boot menu. I have tried downloading recovery of **Catalina** and Big Sur but in vain. I have seen many posts on the internet where hp laptops have the same issue with Opencore.
  I have attached debug log file, my system specs and config.plist file.
[Debug+ Data.zip](https://github.com/acidanthera/bugtracker/files/6014945/Debug%2B.Data.zip)
![Annotation 2021-02-20 173834](https://user-images.githubusercontent.com/64379149/108595588-864cac00-73a2-11eb-8786-54fe782c9a23.jpg)

**Comment by vit9696** [comment]
Does the SHA-256 digest match between the log and the file you download? E.g. you have the following in the log:
```
37:819 00:113 OCRAM: Extent allocation of 498626206 bytes (A) gave 100000000
90:829 53:009 OCRAM: SHA-256 Digest is: E6D96994B792A3A2F94F53BA46B3D1583A24BFB855E7752A1F7EB776D889D93A
```

Could you run `shasum -a 256 /path/to/BaseSystem.dmg` in your operating system and compare the values? Better firstly download, then calculate the hash and save it, then run OpenCore, and compare afterwards.

I suspect that your USB stack is somehow faulty. Either the USB flash itself or the USB driver. This often happens with the laptops.

**Comment by afzl-wtu** [comment]
> 
> 
> Does the SHA-256 digest match between the log and the file you download? E.g. you have the following in the log:
> 
> ```
> 37:819 00:113 OCRAM: Extent allocation of 498626206 bytes (A) gave 100000000
> 90:829 53:009 OCRAM: SHA-256 Digest is: E6D96994B792A3A2F94F53BA46B3D1583A24BFB855E7752A1F7EB776D889D93A
> ```
> 
> Could you run `shasum -a 256 /path/to/BaseSystem.dmg` in your operating system and compare the values? Better firstly download, then calculate the hash and save it, then run OpenCore, and compare afterwards.
> 
> I suspect that your USB stack is somehow faulty. Either the USB flash itself or the USB driver. This often happens with laptops.

Thanks a lot for replying. Surely, I will try another USB and get in touch with you here. I compared SHA-256, it is not equal.

**Comment by Andrey1970AppleLife** [comment]
Try other options **DmgLoading**

**Comment by vit9696** [comment]
@Andrey1970AppleLife while it may let the boot process continue, the advice itself will only hide the error and will not have anything to do with the fact that the image already is corrupted when we start to use it.

**Comment by afzl-wtu** [comment]
By using another USB solved the issue, Thanks a lot.
