### ISSUE TITLE
[Kernel/Block] Is the kext blocked?

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1519]
As dortania guide reports, for those who haven't got any support from Big Sur's AppleAHCIPort.kext it is recommended to:

![image](https://user-images.githubusercontent.com/46293832/108599725-2c90b580-7393-11eb-80d7-c957e0f64a90.png)

Thus, these are the changes I applied: 

![image](https://user-images.githubusercontent.com/46293832/108599794-97da8780-7393-11eb-8153-1ad497c52331.png)
(Adding the specified kext in the `Block` section ^) 

![image](https://user-images.githubusercontent.com/46293832/108599835-c22c4500-7393-11eb-9ee2-44494fca0388.png)
(Adding the kext that the guide recommends in the `Add` section ^) 

Then checking results with `kmutil showloaded | grep AHCI`

![image](https://user-images.githubusercontent.com/46293832/108599861-f1db4d00-7393-11eb-9cea-d923f34ac4fc.png)

I know that logs are very welcome: [opencore-2021-02-20-143253.txt](https://github.com/acidanthera/bugtracker/files/6015208/opencore-2021-02-20-143253.txt)

Seems like even if the log reports that the kext is successfully blocked, `kmutil` can still se it.

However there are some numbers (since the kext CtlnaAHCIPort was taken from an older version of the Big Sur's one) which correspond at the end:

![image](https://user-images.githubusercontent.com/46293832/108599949-69a97780-7394-11eb-83e7-29971912fd38.png)

Is there a reason why those are the same? Is this related to unsuccessful blocking somehow?
If OpenCore uses that identifier to block the kext, maybe that could be the reason `kmutil` still sees that?

What can I do to prevent this kext from loading?

```
   76    0 0xffffff8001323000 0x9000     0x9000     com.apple.driver.AppleAHCIPort (346) DCA877E5-438B-3EA5-8538-7BB255F2D1F3 <75 14 6 5 3 1>
```

**Comment by vit9696** [comment]
- You do not need to block the original kext.
- Blocking kexts does not always work (there is a separate issue on it).
- Numbers are kext dependency indices, both kexts have the same dependencies.

**Comment by 1alessandro1** [comment]
> You do not need to block the original kext.

I think I should make a PR for dortania then...

Thanks
