### ISSUE TITLE
100% use SSD disk on ivybridge desktop at last version

### ISSUE THREAD

**Issue by enckyridion** [acidanthera/bugtracker#1520]
Hello, I have my disk at 100% recording usage when using the latest version of open core on my IvyBridge Desktop ...

B75-D3H
I5 3570K
RX 560 SAPPHIRE
8 RAM
128 GB SSD.

I even noticed that in just 2 minutes with the system idle, the disk had a recording of 5 GB ... When looking at the disk manager, there is no process consuming disk band. NOTE: Clean installation done.

**Comment by vit9696** [comment]
Unrelated to OC.
