### ISSUE TITLE
Rounding of Processor Speed in SMBIOS

### ISSUE THREAD

**Issue by cdf** [acidanthera/bugtracker#1521]
Certain legacy Macs present processor speed in **About This Mac** with two decimal places. But modifying the SMBIOS with OpenCore results in rounding to the nearest tenth. Although such rounding conforms to what Apple currently does, it may leave some users perplexed.

Original:
<img src="https://user-images.githubusercontent.com/63161650/108625862-2219fe80-741b-11eb-9d1e-538c00b5ef7c.png" alt="Unrounded"  width="698" height="463">

Rounded:
<img src="https://user-images.githubusercontent.com/63161650/108625835-ff87e580-741a-11eb-9fed-c012ce25a87e.png"  alt="Rounded" width="698" height="463">

The pertinent SMBIOS values can be observed with **dmidecode**. Note the difference in `Max Speed` and `Current Speed`.

Original:
```
Version: Intel(R) Xeon(R) CPU           X5680  @ 3.33GHz
Voltage: 1.2 V
External Clock: 133 MHz
Max Speed: 3330 MHz
Current Speed: 3330 MHz
```
Rounded:
```
Version: Intel(R) Xeon(R) CPU           X5680  @ 3.33GHz
Voltage: 1.2 V
External Clock: 133 MHz
Max Speed: 3300 MHz
Current Speed: 3300 MHz
```

The code responsible for the rounding is found in [SmbiosPatch.c](https://github.com/acidanthera/OpenCorePkg/blob/8db317ca841403d7b5464c13514a51dbf0c657ac/Library/OcSmbiosLib/SmbiosPatch.c#L352):
```c
if(Table->CurrentPtr.Standard.Type4->MaxSpeed % 100 != 0) {
  Table->CurrentPtr.Standard.Type4->MaxSpeed = (UINT16) (((Table->CurrentPtr.Standard.Type4->MaxSpeed + 50) / 100) * 100);
}
```
What I would like to propose is that on Apple hardware the original value be kept provided that it is within the rounding error of the OpenCore value. Recent Apple-specific additions to OpenCore make this seemingly innocuous change quite simple. Essentially: 
```c
if(HasAppleSMBIOS && (ABS(Original.Standard.Type4->MaxSpeed - Table->CurrentPtr.Standard.Type4->MaxSpeed) <= 50)) {
  Table->CurrentPtr.Standard.Type4->MaxSpeed = Original.Standard.Type4->MaxSpeed;
} else if(Table->CurrentPtr.Standard.Type4->MaxSpeed % 100 != 0) {
  Table->CurrentPtr.Standard.Type4->MaxSpeed = (UINT16) (((Table->CurrentPtr.Standard.Type4->MaxSpeed + 50) / 100) * 100);
}
```
I've tested this code with success on the Mac Pro 5,1 and believe that it would work in general. Would a PR be accepted? Or have I missed something important?

**Comment by vit9696** [comment]
Could you provide the boot log and FSBFrequency value without OC? I am not sure what should the right approach be here.

**Comment by cdf** [comment]
Log: [opencore-2021-02-21-191839.txt](https://github.com/acidanthera/bugtracker/files/6018349/opencore-2021-02-21-191839.txt)

FSBFrequency (as reported in the I/O Registry without OC): `FSBFrequency   Data   <2f 6b ed 07 00 00 00 00>`

**Comment by vit9696** [comment]
Hmm, are there CPUs with two digit frequencies today? I wonder if we should just round some numbers more precisely. Like print two digits when the fractional part second digit is within [2,8] and its first is [1,9]?

**Comment by cdf** [comment]
Many processors that are compatible with the Mac Pro 5,1 have two digits. The most popular upgrades are the Xeon X5680 and Xeon X5690. Here are examples of how these processors are seen in OpenCore:

X5680: `CPUFrequency  3324999977Hz  3324MHz`

X5690: `CPUFrequency  3457999888Hz  3457MHz`

Without OpenCore, the X5680 appears in **About this Mac** as 3.33 GHz and the X5690 as 3.46 GHz. With OpenCore, they currently appear as 3.3 GHz and 3.5 GHz, respectively. Notice that for the X5680, rounding to the nearest hundredth would actually give 3.32 not 3.33.

There is also the X5675 (which was available stock). Without OpenCore, it appears as 3.06 GHz. The first fractional digit is 0!

Building onto what you proposed, perhaps we could do this: 

- If the second fractional digit is in [2,8], then keep two digits by rounding the second digit up (increasing it by 1) if the third is in [4,9] and rounding it down (leaving it the same) if the third is in [0,3].

- Otherwise, keep one digit by rounding to the nearest tenth.

**Comment by Bmju** [comment]
Is there a potential for interaction here with the [existing OC approach](https://github.com/acidanthera/bugtracker/issues/1484) whereby CPU frequency is _always measured_ when on auto-detect, even on legacy Apple hardware with existing OEM frequency info in the BIOS?

If I am right (that this is relevant and applies on your setup, @cdf) then the detailed reported frequency of your CPU would currently vary *slightly* between runs with OC, but would be fixed without OC. And although the variation is small, it looks like it might just be relevant as to whether the X5680 rounds to 3.32GHz or 3.33GHz?

**Comment by vit9696** [comment]
The variation would be a second issue, and yet I believe it should not vary that much. I fixed the rounding in master. Please confirm that I did not break anything.

**Comment by Bmju** [comment]
I know the variation is tiny compared to these large numbers, but just to be explicit in my sums,

X5680: CPUFrequency 3324999977Hz 3324MHz -> 3.32GHz (not 3.33GHz, as pointed out by @cdf)

But add just _23Hz_ (!) to this, to get

X5680: CPUFrequency 3325000000Hz 3325MHz -> 3.33GHz

Still not sure if that is relevant, but just to be clear why I thought the issues might interact.

**Comment by vit9696** [comment]
3324999977 Hz should be rounded to 3325, no? The new algorithm does round things. Current issue with the algorithm is that 2.6666666 becomes 2.67 though.

**Comment by vit9696** [comment]
Added another workaround for 2.66 GHz CPUs.

**Comment by cdf** [comment]
I can confirm that the new approach works as expected with the X5680.
