### ISSUE TITLE
Suggestion: Installing mac without foramting the whole hardrive

### ISSUE THREAD

**Issue by afzl-wtu** [acidanthera/bugtracker#1522]
Sorry I don't know much about Github so I am posting an efficient and fast method of installing **Mac on a Windows PC**.

No need to install on another hard drive or wipe the current hard drive. You can install Mac along with Windows 10 or/and Linux. These are steps:
1. Download and Install Paragon Partition Manager in Windows.
2. Open it and format the partition in which you want to install Mac with HFS+. (Tip you can shrink a partition if you don't have free partition to format with Disk Management tool (Can be opened by right-clicking the Start button on Windows 10).
3. Now restart the System and boot from you Open Core Mac Install USB.
4. When Installing screen show, just launch the Apple Disk Utility. It will show all partitions on the Disk.
5. Just right-click the partition and convert it to APFS. You are done. Just quit the disk utility and start installing the Mac.
6. When it will ask you where to install just point it to that partition. It will automatically create recovery and System partition there.
                  So basically we have installed mac on 1 partition without wiping and formating whole disk.

**Comment by singhalrishi27** [comment]
It's not a support fourm post this on reddit
