### ISSUE TITLE
About MacBook pro 2018  smbios

### ISSUE THREAD

**Issue by fangf2018** [acidanthera/bugtracker#1523]
I tried to modify SMBIOS in MacBook pro2018, but the board ID didn't change

**Comment by fangf2018** [comment]
![image](https://user-images.githubusercontent.com/19627926/108635749-0ca8e100-74bc-11eb-97be-bb6dff1fcaf7.png)

[Config.plist.zip](https://github.com/acidanthera/bugtracker/files/6018313/Config.plist.zip)

**Comment by fangf2018** [comment]
![image](https://user-images.githubusercontent.com/19627926/108635821-7628ef80-74bc-11eb-991d-bd0ce2158533.png)

I guess the board ID didn't change ，causes the display icon to lose.
Thank you for your contribution to hackintosh and look forward to your recovery

**Comment by fangf2018** [comment]
OpenCORE is not used
![image](https://user-images.githubusercontent.com/19627926/108636184-9f4a7f80-74be-11eb-81c5-b2110d989d15.png)

**Comment by vit9696** [comment]
Not a support forum, sorry.

**Comment by fangf2018** [comment]
the board ID didn't change
