### ISSUE TITLE
[DisableWatchDog and debug=0x100] Clarifications and differences

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1524]
Hi there,
I was reading OpenCore Configuration.pdf about `config.plist/Misc/Debug/DisableWatchDog`.
According to it:

![image](https://user-images.githubusercontent.com/17933708/108637735-24687100-748c-11eb-9045-9ffa9bd231a0.png)

In section `12.5 Tips and Tricks` it's suggested to the end user, in order to debug boot failure, to enable `DisableWatchDog` feature to prevent automatic reboot.

![image](https://user-images.githubusercontent.com/17933708/108637753-45c95d00-748c-11eb-83a5-20385c24d92e.png)

At this point I'm asking my self: what's the purpose of `debug=0x100` boot-arg which prevents automatic reboot (the most reliable source is dortania's guide), when `DisableWatchDog` (at least according to Configuration.pdf) does the same job? Am I missing something?
Thank you so much for the clarifications

**Comment by vit9696** [comment]
There are many watchdogs. This one is for UEFI, debug=0x100 is for SMC/XNU.

**Comment by dreamwhite** [comment]
> There are many watchdogs. This one is for UEFI, debug=0x100 is for SMC/XNU.

Alright, so how can I choose whether should I use or not `config.plist/Misc/Debug/DisableWatchDog`? Is there a list of particular firmwares that may require this option to be enabled?

**Comment by vit9696** [comment]
Watchdog interface is standardised by the UEFI spec. Most firmwares have a value configured between 3 and 10 minutes. I would say it is safe to disable watchdog unless you really need it for whatever reasons.
