### ISSUE TITLE
Verified Boot

### ISSUE THREAD

**Issue by anon-lestat** [acidanthera/bugtracker#1525]
So currently with OpenCore there are 2 ways to get EFI verified. Vaulting and UEFI SecureBoot. Both are quite flawed. UEFI SecureBoot only verifies .efi files and vaulting is trivial to remove. So an idea I would like to propose is custom keys. e.g: a question while running sign.command "Do you want to use your own keys?". With this you could add the keys to bios secureboot which would prevent opencore.efi from being messed with and that prevents vaulting from being removed. We would finally get a full chain of: Firmware verifies .efi > vault verifies EFI directory > OC verifies MacOS (and with that we would have full verified boot like MacOS on macs does)

Sadly I haven't done much else than some C for a few years and i haven't looked into opencore and CreateVault code so I think its for the better if i don't mess with its code.

**Comment by vit9696** [comment]
Sorry, but I am afraid you do not understand how OpenCore trusted bootchain works. Please check the `12.2 UEFI Secure Boot` section of the reference manual. It explains how to do exactly what you want: create vault to verify the EFI directory, and then sign OpenCore with custom UEFI Secure Boot keys. We indeed do not offer scripts and tools to sign OpenCore, but standard ones should work just fine and the section I mentioned does link to some articles explaining how to do that. Hope it helps!

**Comment by anon-lestat** [comment]
@vit9696 actually i did read it already. However the problem is you also need to sign the drivers with a custom key. Which makes Vault shit itself because it also signs and checks the drivers.

**Comment by anon-lestat** [comment]
@vit9696 actually i did read it already. However the problem is you also need to sign the drivers with a custom key. Which makes Vault shit itself because it also signs and checks the drivers.

**Comment by vit9696** [comment]
Hrm, I am afraid you did not read it carefully. In section 12.2 it says:

> 6. Sign all the installed drivers and tools with the private key. Do not sign tools that provide administrative access to the computer, such as UEFI Shell.
> 7. Vault the configuration as explained Vaulting section.

I.e. you sign the drivers first, and then create a vault second. I do not see a reason why you should intentionally do it in reverse order when the documentation says exactly the opposite, and thus has no such issue.

**Comment by anon-lestat** [comment]
Oh i think i just realised my mistake...Sign drivers, create vault THEN sign opencore.efi...Im gonna try this in 5min and ill lwt you know

**Comment by anon-lestat** [comment]
Oh i think i just realised my mistake...Sign drivers, create vault THEN sign opencore.efi...Im gonna try this in 5min and ill lwt you know

**Comment by anon-lestat** [comment]
Ah sick! Its working! Thank you very much and sorry for wasting your time.
