### ISSUE TITLE
[ReleaseUsbOwnership] Weird behaviour on Dell firmwares

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1528]
Hi there,
I was digging in my Dell Inspiron 5370 BIOS settings, when I found that `XHCI Hand-off` is enabled by default.
According to Configuration.pdf:

![image](https://user-images.githubusercontent.com/17933708/108829760-ddcc6100-75c8-11eb-8ebd-5247d3ea57c1.png)

I can't manage to boot without `ReleaseUsbOwnership` enabled despite the BIOS setting is already flipped on.
I have a vague memory of a discussion with @vit9696 somewhere, where he explained that some firmwares, despite the BIOS setting is enabled, may still fail booting without the quirk. This "problem" appears even on other Dell firmwares, so I think that it's a common issue of those boards. Is this right?
Should I worry about this, like possible consequences, or can I simply ignore that?
Eventually, is there any kind of log I can provide you using OpenCore DBG binaries, so we can try to get a better overview of the problem? 
If needed, I can provide a picture of the frozen boot-process.
Have a nice day

**Comment by vit9696** [comment]
Well, if the system boots without issues when this quirk is enabled and fails otherwise, you are exactly in the situation when the quirk is required :) I do not see any issue with enabling it.

**Comment by dreamwhite** [comment]
> Well, if the system boots without issues when this quirk is enabled and fails otherwise, you are exactly in the situation when the quirk is required :) I do not see any issue with enabling it.

Alright, I was just wondering if the use of this quirk may have negative side-effects, and possibly how can I find them, if they even exist but, I trust your words ahah
