### ISSUE TITLE
OpenCore: Core2Quad with non-integer ratio 8.5

### ISSUE THREAD

**Issue by roddy20** [acidanthera/bugtracker#1529]
00:000 00:000 OC: OpenCore DBG-066-2021-02-02 is loading in Optional mode (0/0)...
00:040 00:040 OC: Boot timestamp - 2021.02.23 17:47:50
00:081 00:040 OCCPU: No MP services - Not Found
00:083 00:002 OCCPU: Found Intel(R) Core(TM)2 Quad CPU Q9550 @ 2.83GHz
00:123 00:039 OCCPU: Signature 1067A Stepping A Model 17 Family 6 Type 0 ExtModel 1 ExtFamily 0 uCode A07
00:126 00:002 OCCPU: EIST CFG Lock 0
00:166 00:039 OCCPU: Ratio Min 0 Max 6 Current 0 Turbo 0 0 0 0
00:168 00:002 OCCPU: Timer address is 808 from LPC
00:309 00:141 OCCPU: Detected Apple Processor Type: 04 -> 0402
00:332 00:023 OCCPU: CPUFrequencyFromTSC 2838578775Hz 2838MHz
00:376 00:044 OCCPU: CPUFrequency 2838578775Hz 2838MHz
00:421 00:044 OCCPU: FSBFrequency 473096462Hz 473MHz
00:423 00:002 OCCPU: Pkg 1 Cores 4 Threads 4
more logs and discussion https://applelife.ru/threads/asus-p5k.6131/page-49#post-927330

**Comment by roddy20** [comment]
MSR data
Brand String:Intel(R) Core(TM)2 Quad CPU Q9550 @ 2.83GHz
Model:23
Core 2
Cpu ACPI Name:CPU1
Number of CPUs: 4
TDP=95
IA_32_MISC_ENABLE=0x4062972489
MSR_IA32_EXT_CONFIG=0x86791b00
MSR_FSB_FREQ=0x80000a04
MSR_IA32_PERF_STATUS=0x615481f0600481f
FSBFrequency from IOReg=354159822
FSBFrequency from MSR =333330000
DynamicFSB: no
Initial control=0x481F
Maximum control=0x481F
UnderVoltStep=1
PLimitDict=0
PStates count=6

**Comment by roddy20** [comment]
Clover:
000 === [ GetCPUProperties ] ========================
3:153 0:000 CPU Vendor = 756E6547 Model=1067A
3:153 0:000 The CPU supported SSE4.1
3:153 0:000 BrandString = Intel(R) Core(TM)2 Quad CPU Q9550 @ 2.83GHz
3:153 0:000 got cores from CPUID_1 = 4
3:153 0:000 The CPU not supported turbo
3:153 0:000 MSR dumps:
3:153 0:000 @0x00CD=80000a04
3:153 0:000 @0x0198=615481f0600481f
3:153 0:000 FSBFrequency = 448 MHz, DMI FSBFrequency = 333 MHz, Corrected FSBFrequency = 333 MHz
3:153 0:000 MaxDiv/MinDiv: 8.5/6
3:153 0:000 Turbo: 9/0/0/0
3:153 0:000 Features: 0x408E3FDBFEBFBFF
3:153 0:000 Threads: 4
3:153 0:000 Cores: 4
3:153 0:000 FSB: 333 MHz
3:153 0:000 CPU: 3800 MHz
3:153 0:000 TSC: 3800 MHz
3:153 0:000 PIS: 1333 MHz
3:153 0:000 ExternalClock: 333 MHz

**Comment by vit9696** [comment]
REF:

```
int cpu_noninteger_bus_ratio = ((MSR_IA32_PERF_STATUS & (1ULL << 46)) != 0)?1:0;
