### ISSUE TITLE
How to Correctly Generate password hash and salt?

### ISSUE THREAD

**Issue by wqhqq1** [acidanthera/bugtracker#1530]
I tried following python code to generate them, but never works.
Can anybody help me or give me some suggestion?
Thanks a lot.
```
import hashlib
import binascii

def sha512(hash, password, salt):
    hashObject = hashlib.sha512()
    hashObject.update(hash)
    hashObject.update(password)
    hashObject.update(salt)
    return hashObject
def saltGen():
    import random
    import string
    salt = "".join(random.sample(string.ascii_letters + string.digits, 20))
    salt = salt.encode("ascii")
    salt = binascii.hexlify(salt)
    return salt

password = input("Enter password you wanna to encrypt:").encode("utf-8")
salt = saltGen()
hashObject = hashlib.sha512()
hashObject.update(password)
hashObject.update(salt)
hash = hashObject.digest()
print("Encrypting...")
i = 0
while i<5_000_000-1:
    hash = sha512(hash, password, salt).digest()
    i+=1

print("sha512:", sha512(hash, password, salt).hexdigest())
print("salt:", salt)
```

**Comment by wqhqq1** [comment]
I think it'll be a good idea to write about how to generate them in docs.

**Comment by wqhqq1** [comment]
@vit9696

**Comment by wqhqq1** [comment]
At last I modified OpenCore and ask it to print SHA-512 hash for me when I entered password.
Then I use that hash in config, it works well.
The modified OpenCore is at [here](https://github.com/wqhqq1/OpenCorePkg).

**Comment by vit9696** [comment]
We will provide a userspace utility soon, stay tuned.

**Comment by wqhqq1** [comment]
Thanks for your work.

> We will provide a userspace utility soon, stay tuned. Your code above contains a mistake I believe. And using SHA-512 just once without salt is prone to password leakage, thus your change is literally harmful.

**Comment by vit9696** [comment]
Utility is provided as of https://github.com/acidanthera/OpenCorePkg/commit/c98ffeb3788df029bd35fc9952461d76db8a9005
