### ISSUE TITLE
[acdtinfo] SMCBatteryManager not detected

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1531]
I've tested the tool and works perfectly, except for SMCBatteryManager which is loaded but the release version is not detected:

![image](https://user-images.githubusercontent.com/46293832/109040307-0d18c600-76ce-11eb-8f76-bf73a67a574d.png)

**Comment by Gengik84** [comment]
https://github.com/acidanthera/VirtualSMC/commit/155a85446869a57406763719a15c093930a5e1d0

**Comment by 1alessandro1** [comment]
Thanks. Rebooted with the latest version of VirtualSMC, now it works perfectly 👍

![image](https://user-images.githubusercontent.com/46293832/109049859-080d4400-76d9-11eb-9077-c6615f5aa012.png)
