### ISSUE TITLE
CPU "Unknown"

### ISSUE THREAD

**Issue by sfalatko** [acidanthera/bugtracker#1534]
I have an Intel Xeon W3690 installed in my MacPro5,1. Using OC 0.6.6 (may have happened before but I did not notice) my CPU is identified as "Unknown".  Attached is a screen shot and the output of sysctl machdep.cpu and dmidecode as well as my config.plist.
[dmidecode output.txt](https://github.com/acidanthera/bugtracker/files/6054582/dmidecode.output.txt)
[sysctl output.txt](https://github.com/acidanthera/bugtracker/files/6054584/sysctl.output.txt)
[configplist.txt](https://github.com/acidanthera/bugtracker/files/6054592/configplist.txt)

![Screen Shot 2021-02-27 at 8 49 32 AM](https://user-images.githubusercontent.com/17544913/109389197-7c163a80-78d9-11eb-86a1-63f1def0f43e.png)

**Comment by vit9696** [comment]
Need DEBUG log from OpenCore with 0.6.7 (master).

**Comment by Andrey1970AppleLife** [comment]
Is absent much 
![Снимок экрана 2021-02-28 в 12 48 32](https://user-images.githubusercontent.com/17758753/109414333-68470300-79c3-11eb-93ce-6e37ca99c528.png)

**Comment by sfalatko** [comment]
When 0.6.7 is released I will update, confirm it is still an issue with my machine, and then run the debug.

As to "Is absent much" I am using the basic config.plist provided in the "OpenCore on the Mac Pro" thread on MacRumors.com with only the addition of OpenCanopy and BoardID spoofing to enable updates on BigSur.

**Comment by Andrey1970AppleLife** [comment]
Here you have a nonsense.
![Снимок экрана 2021-02-28 в 16 28 30](https://user-images.githubusercontent.com/17758753/109420209-414bf980-79e2-11eb-8c55-7069494f1586.png)

**Comment by sfalatko** [comment]
Adding entries for FirwareFeatures and FirmwareFeaturesMask per the Wiki post on MacRumors -

<key>FirmwareFeatures</key>
<data>A1QM4A==</data>
<key>FirmwareFeaturesMask</key>
<data>P/8f/w==</data>

does not change the outcome - my Processor is still declared "3.5 GHz Unknown". I will see what 0.6.7 and debug brings in the next few days.

Regards

**Comment by Bmju** [comment]
> Here you have a nonsense.
> ![Снимок экрана 2021-02-28 в 16 28 30](https://user-images.githubusercontent.com/17758753/109420209-414bf980-79e2-11eb-8c55-7069494f1586.png)

Using failsafe for these two values in OC SMBIOS section produced zeros as shown (rather than preferred result of keeping OEM values) until recent https://github.com/acidanthera/OpenCorePkg/pull/215 .

**Comment by Andrey1970AppleLife** [comment]
> > Here you have a nonsense.

> 
> Using failsafe for these two values in OC SMBIOS section produced zeros as shown (rather than preferred result of keeping OEM values) until recent [acidanthera/OpenCorePkg#215](https://github.com/acidanthera/OpenCorePkg/pull/215) .

I know. I didn't ask a question.

**Comment by vit9696** [comment]
> When 0.6.7 is released I will update, confirm it is still an issue with my machine, and then run the debug.

File a new issue if it is.
