### ISSUE TITLE
ocvalidate: Allow Cpuid1Data bit of 1 with corresponding Cpuid1Mask bit of 0

### ISSUE THREAD

**Issue by cdf** [acidanthera/bugtracker#1535]
ocvalidate will detect an error if a `Cpuid1Data` bit is 1 and the corresponding `Cpuid1Mask` bit is 0:

>Kernel->Emulate->Cpuid1Data requires Cpuid1Mask to be active for replaced bits!
>CheckKernel returns 1 error!

However, according to the reference manual:

>When each Cpuid1Mask bit is set to 0, the original CPU bit is used, otherwise set bits take the value of Cpuid1Data.

What I understand from this specification is that if a `Cpuid1Mask` bit is 0, then the original CPU bit is used regardless of the corresponding `Cpuid1Data` bit. Indeed, a user may set a `Cpuid1Data` bit to 1 and the corresponding `Cpuid1Mask` bit to 0 only to later toggle the bit by setting the `Cpuid1Mask` bit to 1. Therefore, it seems that ocvalidate is detecting an error for something that has a well-defined behavior.

**Comment by vit9696** [comment]
> What I understand from this specification is that if a Cpuid1Mask bit is 0, then the original CPU bit is used regardless of the corresponding Cpuid1Data bit.

This behaviour is not specified in the documentation and thus shall not be relied on.

For example, with the binary patches it works exactly the opposite the way. All the patches with set but not masked bits will fail to apply. As a result, ocvalidate forbids it for all.

The behaviour is correct.

**Comment by cdf** [comment]
>This behaviour is not specified in the documentation and thus shall not be relied on.

In that case, the "otherwise" in the specification is misleading:

>When each Cpuid1Mask bit is set to 0, the original CPU bit is used, **otherwise** set bits take the value of Cpuid1Data.

Logically, "otherwise" is the negation of the antecedent "When each Cpuid1Mask bit is set to 0." That negation does not preclude `Cpuid1Data` from being 1. Therefore, the documentation should be amended to read something like this:

_If a Cpuid1Mask bit is set to 1, then the corresponding Cpuid1Data bit is used, but if a Cpuid1Mask bit is set to 0 and the corresponding Cpuid1Data is also set to 0, then the original bit is used._

This description effectively leaves unspecified the behavior of when a `Cpuid1Mask` bit is set to 0 and the corresponding `Cpuid1Data` bit is set to 1.

**Comment by vit9696** [comment]
The documentation does not _need_ to specify every corner case behaviour. It defines the limits.

**Comment by dakanji** [comment]
> It defines the limits

Unfortunately, "otherwise", as used in the documentation, totally misleads the user about where those limits are.
