### ISSUE TITLE
Report actual MemoryFormFactor in SMBIOS

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1537]
Currently for `Automatic` mode we use `MemoryFormFactor` based on the value from Mac model we mimic to. This is not helpful as it essentially replaces the actual form factor most of the time, making it harder to figure out the memory installed in the computer when a replacement is necessary.

I request to change the logic and make `Automatic` mode preserve the `MemoryFormFactor` if it exists in SMBIOS table (i.e. it has non-zero value). For that we should:

1. Introduce a `ForceMemoryFormFactor` `BOOLEAN` in `OC_SMBIOS_DATA`, which would be set to `TRUE` for `non-automatic` mode and to `FALSE` for `Automatic`.
2. Update `PatchMemoryDevice` to use the original `FormFactor` value if it exists, has non-zero (zero is invalid) value, and `Data->ForceMemoryFormFactor` is set to `FALSE`.

**Comment by Bmju** [comment]
Will look, yes?
