### ISSUE TITLE
stuck on a black screen after this pic shows up

### ISSUE THREAD

**Issue by opsnite** [acidanthera/bugtracker#1538]
Stuck on the black screen.

CPU:AMD 2600x
GPU:RX580
Motherboard: B450m Mortar Max
RAM: 16GB

![41614602994_ pic](https://user-images.githubusercontent.com/24548110/109499765-4a1af900-7ad0-11eb-9d03-13e3482b0594.jpg)
Here is my logs.
[opencore-2021-03-01-102421.txt](https://github.com/acidanthera/bugtracker/files/6061699/opencore-2021-03-01-102421.txt)
here is my efi files. 
[EFI.zip](https://github.com/acidanthera/bugtracker/files/6061702/EFI.zip)

**Comment by vandroiy2013** [comment]
Use forums for support.
