### ISSUE TITLE
[OpenCorePkg] Wrong opencore-version reporting

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1539]
Hi there,
today I've successfully updated to OpenCore 0.6.7 my Dell Inspiron 5370 EFI.
After fixing and checking the config with ocvalidate utility, I successfully booted without any error.
Sadly, today I've noticed that executing `nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version` which should tell the OpenCore booted version, reports the wrong version of OpenCore.
How can I tell that? Right after booting OpenCore, I can see the version number which is correct.

Above you can see the OpenCore boot-screen and the terminal output:
 
![image](https://user-images.githubusercontent.com/17933708/109639649-b6890d00-7b4f-11eb-8810-417126659f4b.png)

![image](https://user-images.githubusercontent.com/17933708/109639754-d9b3bc80-7b4f-11eb-89d1-a031005db3c4.png)

Am I missing anything?
I don't wanna point the finger to anyone, but "probably" with this update of OpenCore,

> Fixed `opencore-version` reporting the incorrect version in rare cases

created a bug rather than fixing it.

I double checked the SHA512 hashes and I have those:

* 0.6.6 RELEASE hash
    * `BOOTx64.efi` ==> `30e8c37d4fb19f669cc8510a6e5fe13cd15b520f009f8bb7af7d1388da460a125c1b8b0ecf214c361e7c4aac6a37c84e83688b10f0234fcd4bef07e5de74b241`
    * `OpenCore.efi` ==> `1f7bdb1deed285af88fbbe22bb501f17e11fb1fb3e13c81e8801d34e30324c126dc53043dd0497973d42bcf8ae39976f506601f6fc202ccc6c419edfc58e67b8`

* 0.6.7 RELEASE hash
    * `BOOTx64.efi` ==> `1b77c253d25463d7373710b061bae9698fbabb802eea9271b9db2f4aae668cb226613a6e7ad47437a63d6c5bf385714db4493640a7e96bac5b49d60e6721480f`
    * `OpenCore.efi` ==> `af19cc9bca1184f16c3d6b85c83cd3c33f1e0a037b36ff15e8979151b4f4bc10e78e5ed33f73678fcad229650cc76eac5f55ef98e2164216cf9839d2cb0c60b1`

I'm gonna repeat the booting using the debug binaries and provide the necessary logs using Target 67

**Comment by dreamwhite** [comment]
# Update

It seems that resetting the NVRAM is necessary to update the version reporting.
As far as I remember, when I updated from 0.6.2 to 0.6.3, or from 0.6.5 to 0.6.6 I never needed to reset NVRAM.
Probably the wisest choice is resetting NVRAM even if OpenCore reports the correct version in the boot-menu.
Am I wrong?

**Comment by vit9696** [comment]
There was a bug in OpenCore versions prior to 0.6.7 causing incorrect version being reported through NVRAM. After updating to OpenCore 0.6.7 you may have to reset NVRAM to resolve the issue.

**Comment by dreamwhite** [comment]
> There was a bug in OpenCore versions prior to 0.6.7 causing incorrect version being reported through NVRAM. After updating to OpenCore 0.6.7 you may have to reset NVRAM to resolve the issue.

Alright, thank you so much and have a nice day ^^
