### ISSUE TITLE
SKHynix NVMe kernel panic during installer boot

### ISSUE THREAD

**Issue by DanWillans** [acidanthera/bugtracker#1540]
Hi all,

I've successfully made a hackintosh with my EFI configuration on a Samsung SM951 256GB NVMe. I then tried to swap this to a larger 1TB SKHynix and I'm getting a kernel panic. Picture is attached. 

Hardware:
Laptop Model - Lenovo T590
CPU - i7-8665U Whiskey Lake
GPU - no dGPU just iGPU
Storage Device - SKHynix_HFS001TD9TNG-L5B0B
Ethernet Chipset - Intel Ethernet Connection I219-LM
Bluetooh/Wireless Chipset - Intel Wireless-AC 9560 160Mhz

I've checked the NVMe firmware is up to date. I also noticed that the picture says FW Revision not available when other NVMe kernel panics normally include this.

If I run with nvme=-1 in the bootargs everything is fine but obviously the nvme isn't mounted to install. 

Happy to help try new kexts or debug this.  

EFI 7zip upload link ->https://we.tl/t-pv5dOJYWnO

![20210225_224035](https://user-images.githubusercontent.com/56385219/109648150-2ef0cd80-7b52-11eb-8bbe-bf8d223719c1.jpg)

**Comment by vit9696** [comment]
1TB SKHynix is not supported by macOS.
