### ISSUE TITLE
HdaCodecDump.efi not packaged since OC v0.6.6 without any documented reason for removal

### ISSUE THREAD

**Issue by mackonsti** [acidanthera/bugtracker#1541]
Hello to everyone in OpenCore team, I hope you are well and safe.

The packaged releases since v0.6.6 do not contain any more `HdaCodecDump.efi` in the zip file in `/X64/EFI/OC/Tools/` path and the last one to include this EFI tool is v0.6.5. However, unless I missed it, the release notes do **not** include the removal of this driver in the Releases points: https://github.com/acidanthera/OpenCorePkg/releases

I have looked everywhere for a note or indication that `HdaCodecDump.efi` is dumped for a reason (and to find out why) before posting an issue here in the bugtracker. There's no reference in `Changelog.md` inside the zip file, either.

Can you please confirm the removal as intended action and kindly update the release notes or is it missed in the ZIP by accident? 

**Thank you** and apologies for posting this here but it kind of relates to packaging the files for a release, not sure where else to address this.

**Comment by 1alessandro1** [comment]
Hdacodecdump is bundled in SysReport debug feature since 0.6.6

**Comment by vit9696** [comment]
Basically it, sorry for not writing it more explicitly in:

```
- Added audio codec dumping to SysReport
```

**Comment by mackonsti** [comment]
Thank you @vit9696 and @1alessandro1 for your reply. Please can you kindly mention this in the Releases notes/points as well as the main page? I have not used SysReport ever, so it may be useful to other people too. Thanks again! Keep up the good work.
