### ISSUE TITLE
Opencore hangs chain loaded trough RefindPlus with UGA cards

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1542]
There has been recent change which closed this issue:
https://github.com/acidanthera/bugtracker/issues/1498
After that, certain configurations with UGA/EFI cards on cMP5,1 prevent the OC from booting. This is the behavior:
- OC and RP boot independently. 
- OC does not boot chain loaded from RP
![image](https://user-images.githubusercontent.com/7897244/109737109-7b103200-7b93-11eb-915e-7f0e48dd3c2a.png)
 If it is a GOP card there is no problem.
[067 GT630 UGA MVC OC hung.zip](https://github.com/acidanthera/bugtracker/files/6073010/067.GT630.UGA.MVC.OC.hung.zip)

**Comment by vit9696** [comment]
Please provide the exact commit causing this.

**Comment by startergo** [comment]
Not sure about the exact commit, but I opened an issue https://github.com/dakanji/RefindPlus/issues/24
So it must be around this time. Config file will follow when I have access to my machine.

**Comment by vit9696** [comment]
Please find it via https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true

**Comment by startergo** [comment]
Ok I will find the working snapshot when I get back home (1-2) days.

**Comment by dakanji** [comment]
Wonder why all those debug log items are sent to screen instead of to the log file.
Happens on all boots of v0.6.7, when chain loaded at least, not just those that crash.

**Comment by dakanji** [comment]
Also worth noting that this issue only appears to affect the MacPro5,1 and not the MacPro3,1 (which was involved in https://github.com/acidanthera/bugtracker/issues/1498).

**Comment by vit9696** [comment]
@dakanji basically all log sent before OC logging protocol is initialised has to go onscreen currently.

- Does the issue happen exclusively with RP? I believe Mac EFI also starts OpenCore in graphics mode, so I do not expect any problem here.
- I saw something about NVIDIA hacks in the issue. What is it about?

**Comment by startergo** [comment]
> * I saw something about NVIDIA hacks in the issue. What is it about?
This is the EFI version spoofing to allow the NVIDIA GOP to initialize. This is currently implemented in RP, but not yet in OC, so if someone wants to use OC with NVIDIA, the EFI version has to be spoofed to version 2 early in the booting sequence.
But that was something else. During those tests when I removed the driver spoofing in the EFI firmware I noticed this odd behavior for chain loading. It was just coincidence for this matter so is not relevant for this issue.
RP also uses some of the OC libraries. Could it be that OC hangs because those protocols have been already initialized in RP?

**Comment by dakanji** [comment]
To clarify things.

There are two overlapping issues as follows:
1. RefindPlus not booting
2. OpenCore not booting when chain loaded

Issues 1 was the subject of the issue @startergo raised in the RP repo. This was shut down as invalid because it turned out to be related to the fix from  https://github.com/acidanthera/bugtracker/issues/1280 where he injected the drivers into his firmware (The Nvidia Hack).

Issue 1 is not relevant to this issue except that he mentioned Issue 2 in passing in the report.

@startergo had been moaning to me recently that OpenCore not booting when chain loaded from RP. I couldn't replicate his problem and others i asked to test could not either so I put it all down to his exotic setup (manifested in Issue 1) and ignored him 😉 

However, someone else I ask to test stuff, who has a basic setup, mentioned the same issue so I finally started to take @startergo serious.

After a few tests, the following same to light:
1. The issue only affects GPUs with UGA (GPUs with GOP are not affected).
2. The Issue only affects cMP5,1 (cMP 3,1 is not affected regardless of whether the GPU has GOP or UGA).

It might be related to RP only. Needs reconfirmation.

**Comment by vit9696** [comment]
Can we provide a quirk for NVIDIA inside OC to avoid potential collision between RP and OC at least for the test case? I remember the driver submitted, but no interest in upstreaming the patch.

**Comment by dakanji** [comment]
It looked like it will be an headache to incorporate but obviously not impossible.
Can have that as a separate target as the issue here seems unrelated.

**Comment by vit9696** [comment]
> Can have that as a separate target as the issue here seems unrelated.

Yes, that would do.

**Comment by vit9696** [comment]
Please do https://github.com/acidanthera/bugtracker/issues/1542#issuecomment-789363270.
The builds are here: https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true
More you postpone this, more builds you have to test.

**Comment by startergo** [comment]
I went back and tested 0.66 and 0.65. Still the same hang. I think it is safe to conclude that the problem is within RP as it used to work before.
[Archive.zip](https://github.com/acidanthera/bugtracker/files/6095654/Archive.zip)
[Archive1.zip](https://github.com/acidanthera/bugtracker/files/6095655/Archive1.zip)

**Comment by vit9696** [comment]
Right, I guess in this case I am closing this, but I will provide any help if necessary. Just respond as needed.

**Comment by dakanji** [comment]
IIRC, this was said to also be manifested while chain loading cMP5,1 from rEFInd.
Seems best to investigate that angle.

**Comment by dakanji** [comment]
@startergo ... Try this OC 0.6.8 build which has additional debug prints added and share the log.
Should help reveal exactly where the crash is happening.

[DBG-OpenCore-068[PreRelease].zip](https://github.com/acidanthera/bugtracker/files/6095976/DBG-OpenCore-068.PreRelease.zip)

**Comment by startergo** [comment]
[opencore-2021-03-06-201648.txt](https://github.com/acidanthera/bugtracker/files/6096040/opencore-2021-03-06-201648.txt)

**Comment by dakanji** [comment]
it is crashing on this `if`statement: https://github.com/acidanthera/OpenCorePkg/blob/e54b600945606d6f21909519aa43dd1b262e44fd/Library/OcDriverConnectionLib/OcDriverConnectionLib.c#L266

The `TRACER 02 c 01 a 01 a 01 a 01` print out is immediately above this after the `for` statement.
Can't say that sheds much light so far.

**Comment by startergo** [comment]
rEFInd chainloading:
[opencore-2021-03-06-205228.txt](https://github.com/acidanthera/bugtracker/files/6096166/opencore-2021-03-06-205228.txt)

**Comment by dakanji** [comment]
That one crashes here: https://github.com/acidanthera/OpenCorePkg/blob/e54b600945606d6f21909519aa43dd1b262e44fd/Library/OcDriverConnectionLib/OcDriverConnectionLib.c#L275

I think it is most likely a memory allocation issue in rEFInd that has carried over into RP.
Solution is not here in OpenCore and the breaking commit needs to be found in rEFInd.

**Comment by startergo** [comment]
> That one crashes after this line: https://github.com/acidanthera/OpenCorePkg/blob/e54b600945606d6f21909519aa43dd1b262e44fd/Library/OcDriverConnectionLib/OcDriverConnectionLib.c#L275
> 
> I think it is most likely a memory allocation issue in rEFInd that has carried over into RP. Initially seemed it might be the ReloadGOP thing but obviously not the case since this is not in rEFInd.
> 
> Solution is not here in OpenCore and the breaking commit needs to be found in rEFInd.

Something is still very inexplicable. rEFInd 0.13.1 does not boot at all (grey screen). All other before up to 0.11.4 need APFS.efi and HFS_x64.efi to display the boot partitions. Without them only tools are seen, but even then the hang is still there, whereas RP actually had a working snapshot as you can see in the other issue.

**Comment by startergo** [comment]
So commit 90a1dbd8282b814486f8b292e3c03a9a577ee45b of OC allows rEFINd 0.13.0 to chainload OC.
0.13.1 and RP still hang. So @dakanji apparently a new memory leak has been introduced between 0.13.0 and 0.13.1 ( I guess one commit), which is preventing RP and rEFInd from chainloading OC.

**Comment by dakanji** [comment]
Can you raise an issue on the RP Repo to track finding this?
