### ISSUE TITLE
Documentation clarification related to PlatformFeature key

### ISSUE THREAD

**Issue by fmunteanu** [acidanthera/bugtracker#1543]
In OC 0.6.7, you mention `PlatformFeature` key should be set to failsafe `0xFFFFFFFF` value:

![1614747598319](https://user-images.githubusercontent.com/19806136/109757158-38f8e780-7bb7-11eb-960d-3b025d438bdf.png)

Programatically, I can set `PlatformFeature` value to  `-1` (INT32 signed) or `4294967295` (INT32  unsigned). Which one is the correct value to use?

**Comment by vit9696** [comment]
Both are fine, -1 is easier for config.plist.
