### ISSUE TITLE
[BIOS Settings] Question on speedstep/speedshift/cpu c-states

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1544]
I noticed from this comment: https://github.com/acidanthera/bugtracker/issues/365#issuecomment-523303086 that the setting
- Intel(R) SpeedStep(tm) should be enabled in macOS

However ASUS BIOSes (and many others) have other settings too, such as:

- Intel(R) Speed Shift Technology
- CPU C-States (which have additional menus once enabled) 

@vit9696  Does `AppleIntelCPUPowerManagement` care about each of these settings (since Speedstep should be enabled) and could you please specify for each one if macOS wants both to be enabled or not?

Thanks in advance

**Comment by dreamwhite** [comment]
@1alessandro1 good morning :)
I had a small discussion with @vit9696 regarding "CPU C-States" BIOS option which doesn't seem to have any kind of effect on macOS if enabled or not. For other OSs however, it's better having it enabled (e.g. you have a multi-boot setup). For more infos you can check issue #1076.

**Comment by 1alessandro1** [comment]
@vit9696 What about Intel SpeedShift? 

I found a topic where PikerAlpha mentioned it, is it relevant to have it enabled in bios?

https://pikeralpha.wordpress.com/2016/04/06/macbook91-will-be-the-first-mac-ever-to-support-hwp/

**Comment by vit9696** [comment]
I would say what @dreamwhite quoted counts for everything. However, from what I also remember, some firmware settings did indeed program MSRs in a way that even macOS power management broke. For this reason my personal choice is to enable all the power management features in the firmware.
