### ISSUE TITLE
Surface Pro 7: OC hangs on EXITBS:START or EndRandomSeed

### ISSUE THREAD

**Issue by sauregurke** [acidanthera/bugtracker#1547]
****NOTE: THIS SEEMS TO BE A GENUINE FIRMWARE CONFLICT AND NOT A SIMPLE FIX, PLEASE DO NOT DISREGARD****
Specs
Microsoft Surface Pro 7
Intel Core i5-1035G4
Intel Iris Plus G4 graphics
8GB ram, 256gb ssd, yada yada
Microsoft UEFI version 9.102.140.0 (version 9.101.140.0 is what broke OC 0.6.5 entirely with the ###ACCESS DENIED error - I experimented with that a lot before arriving on versions 0.6.6 and 0.6.7)
OC version 0.6.6 (have also tried 0.6.7, both normal and debug)

After many hours of research, personal guesses based on intuition and diagnosis through the hacintosh discord, I believe I have come to the sound conclusion that there is some firmware issue preventing the handoff from iBoot to the MacOS loader. On Catalina installers, a working copy of Catalina, and Big Sur installers, the machine hangs on ###EXITBS:START. On a Mojave installer partition I had lying around, it hung on ### ExitRandomSeed. Yes, I have tried everything - including a variety of combinations of - the diagnosis section of the Dortania guide for this specific issue; no, none of them worked. Neither did any of the suggestions from a few experts on the discord server (or combinations of these - starting to see a pattern here?)

From what I can tell, this seems to be an issue of the surface firmware conflicting with OpenCore. 

Chances are, if it's a quirk or other setting somewhere in config.plist, I have tried booting the machine with just it set to yes or no, plus a combination of it and something on and/or off. I do not have a full list, unfortunately, but I have tried at least 30 or so quirks variations depending on what was suggested and what I found online. Please ask and I will get back you as soon as possible, as I have likely tried that before (assuming you are suggesting a config file fix)

I removed the kext folder to save space

[logs.zip](https://github.com/acidanthera/bugtracker/files/6086871/logs.zip)

[EFI.zip](https://github.com/acidanthera/bugtracker/files/6086887/EFI.zip)

**Comment by vit9696** [comment]
Check https://github.com/acidanthera/bugtracker/issues/1486. Enabling `SetupVirtualMap` with 0.6.7 should help.

**Comment by sauregurke** [comment]
It did not. That was tried by itself and with a variety of other combinations, such as applexcpm...., rebuildapple... and so on.

**Comment by sauregurke** [comment]
I... I suppose I did not put that fix on the right drive when I tried it. I am using two identical drives...but wow, that actually worked. Thank you
