### ISSUE TITLE
Broken cursor

### ISSUE THREAD

**Issue by jackjack1-su** [acidanthera/bugtracker#1548]
The cursor is broken when using OC.
EFI is [https://github.com/jackjack1-su/SP7config](url)

**Comment by jackjack1-su** [comment]
Can't find any solution.

**Comment by m0d16l14n1** [comment]
> Can't find any solution.

https://www.insanelymac.com/forum/topic/344939-general-discussion-intel-ice-lake-graphics-on-macos-catalina/

Read that, you will find issue about cursor broken stuff and solution to fix that

**Comment by jackjack1-su** [comment]
thx.
