### ISSUE TITLE
Setting NVRAM Variable Ignored

### ISSUE THREAD

**Issue by arrmo** [acidanthera/bugtracker#1549]
Hi,

My apologies if this is me, but I have tried to read through the docs, thinking I'm doing it correctly (and hopefully I am!), but if not - by all means just say that. My issue is getting through the actual macOS install. It keeps failing, with the message (briefly on the screen), saying "SIP IS DISABLED". So then it just reboots. But I have checked, and have tried setting csr-active-config to both 00000000 and 67000000 (base64 encoded of course, to e.g. AAAAAA==). But the problem is apparent in the log (I think ... LOL), from below,
```
12:307 00:642 OC: Not deleting NVRAM 7C436110-AB2A-4BBB-A880-FE41995C9F82:csr-active-config, matches add
...
16:163 00:642 OC: Setting NVRAM 7C436110-AB2A-4BBB-A880-FE41995C9F82:csr-active-config - ignored, exists
```

So thinking then it's not getting set correctly, hence the install error. Agreed? I have tried resetting NVRAM also, no luck. And, from the docs, it seems like I need to set LegacyOverwrite to true, and add csr-active-config to LegacySchema (under the correct key). Do I have that right? Even with that though, no luck ... and I think this is blocking the install.

FYI, this same message is showing up with boot-args, so I may not have the full debug args set up (as they are not being taken). And to confirm, I am running 0.6.7.

Just yell if anything else would help. Thanks!
[EFI.zip](https://github.com/acidanthera/bugtracker/files/6096556/EFI.zip)

**Comment by arrmo** [comment]
Doh! OK, my screw up, sorry - dumb-me 😜. Forgot to attach the OC log, adding it here. I likely am missing this, but not sure how to get the Apple log (after OC hands off => to show the SIP DISABLED message I'm getting).

Thanks!
[opencore-2021-03-07-050753.txt](https://github.com/acidanthera/bugtracker/files/6097526/opencore-2021-03-07-050753.txt)

**Comment by arrmo** [comment]
OK, this seems to be Big Sur related. I decided to give Catalina a shot ... works fine! Try the Big Sur upgrade => nope! The error above. I did try using the SIP value noted [here](https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#known-issues), so FF0F0000, but no difference. And that disables SIP ... rather, I need it enabled I think - no?

Thanks!

**Comment by vit9696** [comment]
> But I have checked, and have tried setting csr-active-config to both 00000000…

For SIP to be disabled the value should either be `<00000000>` or missing. I believe your attached configuration is correct. However, to make sure, please **delete** `csr-active-config` from `Add` section and only leave it in `Delete` section. Afterwards boot to Catalina and run `nvram -p` in Terminal. Attach the output here along with the boot log.

> It keeps failing, with the message (briefly on the screen), saying "SIP IS DISABLED". 

It is the first time I hear about this message. Please provide a screenshot and macOS installer log after you make the changes above. Here is [how](https://scriptingosx.com/2018/02/show-the-installer-log-during-high-sierra-installation/).

**Comment by arrmo** [comment]
> Afterwards boot to Catalina and run `nvram -p` in Terminal. Attach the output here along with the boot log.

You bet! Done, and `nvram -p` below, also boot log attached (no longer `csr-active-config`).
```
prev-lang:kbd   en-US:0%00
fmm-computer-name       Russell%e2%80%99s iMac
bluetoothActiveControllerInfo   %fb!\%0a%00%00%00%00%b0%14@%e20;%1e-
SystemAudioVolume       F
run-efi-updater No%00
LocationServicesEnabled %01
boot-args       keepsyms=1 shikigva=40 shiki-id=Mac-7BA5B2D9E42DDD94
```

All look OK? I can try the upgrade now, if you want. Just let me know.
[opencore-2021-03-13-180928.txt](https://github.com/acidanthera/bugtracker/files/6135297/opencore-2021-03-13-180928.txt)


And sorry that the OC log is different now, I have been messing with trying to get HEVC working, but no joy so far - actually, on that, if you don't mind a quick question ... I just found some info that says with a dGPU I should use iMac15,1 (vs. iMac14.4), but I can't see that causing h.264 to work, but not HEVC - agreed?

Thanks for the help!

**Comment by vit9696** [comment]
yes, this does look fine

**Comment by arrmo** [comment]
OK, will try the upgrade again, let you know. Thanks!

**Comment by arrmo** [comment]
OK, seem to be in an "install loop" 😞. I get the normal boot screen (Catalina background, progress bar) ... for quite a while. Then a bit of time with the Apple logo and progress bar, then a spinner => and reboot, start again.

So far, no luck with that keypress combination - dang it! Reading that thread, seems like it doesn't work anymore?
https://scriptingosx.com/2018/02/show-the-installer-log-during-high-sierra-installation/#comment-66556

Thanks,

**Comment by vit9696** [comment]
Right. To be honest, at this moment this looks like some weird configuration issue, while I feel sorry for you, bugtracker is not quite the right place to discuss it. I suggest you to e.g. ask on Reddit or similar places, there actually are more inclined users with various hardware rather than us, who only think in terms of the bootloader.

Even so, make sure you format the drive into APFS before you install Big Sur (it will fail otherwise) and also try a different USB flash.

**Comment by arrmo** [comment]
NP, understand - appreciate the pointer above about deleting `csr-active-config`.

**Comment by arrmo** [comment]
BTW, even an install to a fresh / clean drive fails. Likely config, as you say - no argument at all. But if you happen to come across a way to log (to the EFI partition perhaps?) during macOS install, I can try to capture it to see.

Thanks again for the help!
