### ISSUE TITLE
trojan on 0.6.7

### ISSUE THREAD

**Issue by rushyaa** [acidanthera/bugtracker#1550]
![Untitled](https://user-images.githubusercontent.com/15036958/110254090-a3dd6080-7fb3-11eb-8afb-d11d177ab141.png)

**Comment by 1alessandro1** [comment]
This was already discussed in https://github.com/acidanthera/bugtracker/issues/1347

**Comment by rushyaa** [comment]
You can see in above image there is something called oc password gen . Exe file

**Comment by vit9696** [comment]
Does not really change the explanation given. Usual false positive. The utility is used to generate the password for OpenCore UI access, refer to Configuration.pdf for more details.
