### ISSUE TITLE
AppleALC: HDMI audio causes a kernel panic

### ISSUE THREAD

**Issue by sauregurke** [acidanthera/bugtracker#1551]
Running AppleALC 1.5.8 on a Surface Pro 7, i5-1035g4, OC 0.6.7, causes a kernel panic when a monitor is plugged in - in my case, a Samsung SyncMaster 2494HM. Plugged in using a HDMI to USB-C adapter. It is worth mentioning that with my layout (layout id 35, this was with device properties configured to layout-id 23000000), static is audible when the headphone jack is used. It is also worth mentioning that my built-in display is almost 4k (2736x1824) which may or may not be related to the issue as this resolution is currently "broken on ice lake cpus."

(I was not running VoodooHDA at the time of discovery, however now I am, because I need an external monitor)
[AppleHDA kernel panic (HDMI audio?).txt](https://github.com/acidanthera/bugtracker/files/6098637/AppleHDA.kernel.panic.HDMI.audio.txt)
[applehda - BROKEN with external monitor.plist.zip](https://github.com/acidanthera/bugtracker/files/6098687/applehda.-.BROKEN.with.external.monitor.plist.zip)
^this is the config at the time of the incident

**Comment by sauregurke** [comment]
Adding No-hda-gfx to audio layout fixes this issue.

**Comment by Sher1ocks** [comment]
> Adding No-hda-gfx to audio layout fixes this issue.

hdmi working with hdmi audio in icelake?

**Comment by sauregurke** [comment]
No, this disables hdmi audio. By fix the issue I meant the computer doesn’t kernel panic when the monitor is hooked up.

**Comment by kingo132** [comment]
Try my solution: https://github.com/acidanthera/bugtracker/issues/1283
Using my solution, you don't need to disable hdmi audio. So you will get the audio of eGPU working, although there's no hdmi audio in icelake platform by now.
