### ISSUE TITLE
[Discussion] DeviceProperties MinKernel and MaxKernel support

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1552]
Hi there,
I was just wondering if OpenCore actually admits injecting Device-properties with a MinKernel/MaxKernel criteria, like for the kexts.

Where can be this useful? Let's suppose for example that I have a desktop with two GPUs: one NVidia (1050Ti) which works only with High Sierra, and a AMD RX5600Xt (which works only on Catalina and up to Big Sur) and therefore I can't use `-wegnoegpu` boot-arg.
If I wanna boot Catalina and disable the NVidia GPU, since I have two GPUs and wanna disable just the NVidia for power-management purposes, I need to create a custom device-properties entry which contains `disable-external-gpu` property.
Viceversa, if I wanna boot High Sierra and wanna disable the AMD RX5600Xt GPU I should repeat the above steps but for the AMD GPU.

My question is: is there any possibility to apply a DeviceProperties patch only for a particular OS version? If not, will you ever consider adding a criteria like the one I've exposed (add many quotes around exposed plz)?

A workaround I "found" is having two EFIs for the two OSs but as you may imagine, this is not a "clean" solution.
Do you have any alternative idea?
Thank you so much and have a nice day

**Comment by startergo** [comment]
There is a working solution alas not from OC (would be nice):
https://forums.macrumors.com/threads/mybootmgr-refindplus-opencore.2231693/
By the way how did you resolve NVIDIA+AMD setup? I am still fighting to find a solution with working sleep function and disabled NVIDIA?

**Comment by dreamwhite** [comment]
> There is a working solution alas not from OC (would be nice):
> https://forums.macrumors.com/threads/mybootmgr-refindplus-opencore.2231693/

Well to be fair: I gave a rapid look at the guide you gently posted but as I supposed in advance, I still need to duplicate the EFI and apply the edits, as I wrote on the issue

> By the way how did you resolve NVIDIA+AMD setup? I am still fighting to find a solution with working sleep function and disabled NVIDIA?

Despite I don't wanna derail the issue as it's not properly the topic I was looking for:

So, I don't personally own this build but I know someone who has it and has an AMD AM4+ motherboard (R5 3600), so sleep is a hit or miss. This person doesn't care much about this since, as I told him, generally sleep is broken on AMDs and may cause weird issues (at least this is what I read on the internet) like non-waking up machine.

What I can suggest you is double checking your `hibernatemode` and make sure that it's set to `0` (since `3` and `25` generally are not supported at all). Then after doing so, try putting in sleep your system and with the following command check the wake reasons:

`pmset -g log | grep -e "Sleep.*due to" -e "Wake.*due to"`

Hope that it'll be useful for your debugging session 😄

**Comment by startergo** [comment]
That was not my question. It was how did you implement NVIDIA disable? As far as the link I sent you don't need 2 EFI folders, but 2 config files in the same folder. Those config files can be arbitrarily selected from an external bootpicker.

**Comment by dreamwhite** [comment]
> That was not my question. It was how did you implement NVIDIA disable? As far as the link I sent you don't need 2 EFI folders, but 2 config files in the same folder. Those config files can be arbitrarily selected from an external bootpicker.

Oh well, I just used `disable-external-gpu` property under the desired GPU PciRoot Path for disabling the GPU.
In my case, the EFI for High Sierra has the config.plist with `disable-external-gpu` property under the AMD GPU PciRoot Path.
Viceversa, in the EFI for Catalina/Big Sur I repeated the process but for the NVidia

**Comment by startergo** [comment]
Interesting in [WEG ](https://github.com/acidanthera/WhateverGreen)I read:
```-wegnoegpu to disable external GPU (or add disable-external-gpu property to IGPU).```
So you actually add that property under the device you want to disable?

**Comment by dreamwhite** [comment]
> Interesting in [WEG ](https://github.com/acidanthera/WhateverGreen)I read:
> `-wegnoegpu to disable external GPU (or add disable-external-gpu property to IGPU).`
> So you actually add that property under the device you want to disable?

Exactly, I just add that property under the device I wanna disable. To get the PciRoot Path of the device you can use [gfxutil](https://github.com/acidanthera/gfxutil)

**Comment by startergo** [comment]
Something like:
```
<key>PciRoot(0x0)/Pci(0x7,0x0)/Pci(0x0,0x0)/Pci(0x4,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>disable-external-gpu</key>
				<data>
				AQ==
				</data>
				<key>rebuild-device-tree</key>
				<data>
				AA==
				</data>
			</dict>
```

**Comment by startergo** [comment]
Not working here. Can you share your config file?

**Comment by dreamwhite** [comment]
Wait, `disable-external-gpu` type should be `DATA` with `01000000` as value (eventually change it to `boolean` and set it to true

**Comment by startergo** [comment]
I tried that too. Still the same.

**Comment by Andrey1970AppleLife** [comment]
For adding property the device shall be enabled. It is impossible to disable itself thus, because it is impossible to add property if the device is disabled. It is a vicious circle.

**Comment by dreamwhite** [comment]
> For adding property the device shall be enabled. It is impossible to disable itself thus, because it is impossible to add property if the device is disabled. It is a vicious circle.

Ah, but wait, the device is still enabled otherwise how will `-wegnoegpu` or `disable-external-gpu` property work?
I mean, if we're talking about other properties like `device-id` my concept should work or whatever?

I know that it is a vicious circle and still don't figure out if what I tried to explain is achievable theorically or not

**Comment by vit9696** [comment]
I think there are other options to do this, but I do not have enough time to reply. Keep it open till a verdict later.

**Comment by dreamwhite** [comment]
> You can add unknown device-id, but it will simply break device work, but won't disable it.

Wait, probably there's a misunderstanding of the scope of this issue (probably caused by me haha).
My final achieve is injecting DeviceProperties using a criteria like MaxKernel/MinKernel. For example (and I wanna highlight example) you might need a particular property which works only for a specific kernel version.

e.g. You might use a custom device-id for enabling the iGPU acceleration on certain macOS versions (you know, some old OSs like first Mojave versions may not correctly recognize UHD630 iGPU) else you don't need it.
I don't know if this feature-request goes against your OpenCore/WhateverGreen project plannings and if you found it useful, but as I wrote before, in special cases (like a dual GPU system) it may be really helpful having this DeviceProperties patching criteria, as done with the kexts (e.g. see CtlnaAHCIPort.kext MaxKernel stuff):

![image](https://user-images.githubusercontent.com/17933708/110665321-8b925f00-81c8-11eb-895e-a6d848f0deb6.png)

# UPDATE

Just saw @vit9696 comment. Take your time and reply when you want, don't rush for it 😄

**Comment by vit9696** [comment]
`disable-external-gpu` disables all external GPUs. If some of your GPUs is not disabled with this, it only means that your ACPI tables are misconfigured and do not follow OpenCore spec. See [this section](https://github.com/acidanthera/OpenCorePkg/blob/0.6.7/Docs/Configuration.tex#L1757), it is particularly vital starting with GoldenGate.

The new `disable-gpu` API on the other side does exactly what you requested. Please use it.

**Comment by dreamwhite** [comment]
> `disable-external-gpu` disables all external GPUs. If some of your GPUs is not disabled with this, it only means that your ACPI tables are misconfigured and do not follow OpenCore spec. See [this section](https://github.com/acidanthera/OpenCorePkg/blob/0.6.7/Docs/Configuration.tex#L1757), it is particularly vital starting with GoldenGate.

Alright, thank you so much ^^



> The new `disable-gpu` API on the other side does exactly what you requested. Please use it.

Thank you so much for accepting my feature request. I'll do some tests in the following days and let you know if is there any kind of bug
Have a nice weekend
dreamwhite

**Comment by startergo** [comment]
I tried this, but it does not seem to have effect. First I tried ```disable-external-gpu``` as a boot argument and it did not disable the DGPU. Then I tried ```disable-gpu``` as a device property under the device to be disabled. Logs attached
[Archive.zip](https://github.com/acidanthera/bugtracker/files/6135770/Archive.zip)
[config.plist 2.zip](https://github.com/acidanthera/bugtracker/files/6135772/config.plist.2.zip)

**Comment by dreamwhite** [comment]
> I tried this, but it does not seem to have effect. First I tried `disable-external-gpu` as a boot argument and it did not disable the DGPU. Then I tried `disable-gpu` as a device property under the device to be disabled. Logs attached
> [Archive.zip](https://github.com/acidanthera/bugtracker/files/6135770/Archive.zip)
> [config.plist 2.zip](https://github.com/acidanthera/bugtracker/files/6135772/config.plist.2.zip)

I don't wanna judge your EFI, but probably you made some confusion regarding `disable-external-gpu`.
According to WeG README.md, you can achieve GPU disabling in two ways:

- boot-arg `-wegnoegpu` which disables every dGPU unconditionally
- addind property `disable-external-gpu DATA 01000000` property under `DeviceProperties/Add/PciRoot(BLABLABLA)`.

Try replacing `disable-gpu` device-property onto `disable-external-gpu` and try applying the `disable-gpu-min` (or `disable-gpu-max`) kernel version patching criteria.

Also, as  @vit9696 stated in a comment of this issue:

> `disable-external-gpu` disables all external GPUs. If some of your GPUs is not disabled with this, it only means that your ACPI tables are misconfigured and do not follow OpenCore spec. See [this section](https://github.com/acidanthera/OpenCorePkg/blob/0.6.7/Docs/Configuration.tex#L1757), it is particularly vital starting with GoldenGate.

Probably, if you tried without success `disable-external-gpu` property your ACPI tables are misconfigured and do not follow OpenCore spec :/ 

Hope that you manage to solve :)

**Comment by vit9696** [comment]
Note, `disable-gpu` must always be specified. `disable-gpu-min`/`disable-gpu-max` are only additional qualifiers that allow you to override the default values: min by default is zero and max by default equals current kernel major version. With OpenCore you can always specify all values as plist numbers.

**Comment by vit9696** [comment]
> With disable-external-gpu property added to IGPU MacBookPro11,3 does not boot.

We have no idea about Macs, sorry.

> I can't see disable-gpu property in the WEG readme. So these 3 properties have to be added under the ACPI path in device properties for the GPU which needs to be disabled?

Correct.
