### ISSUE TITLE
CPU frequency incorrectly set on X5690

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1554]
In about this Mac on cMP5,1 the frequency is set to 3.45 instead of 3.46MHZ:
```
00:000 00:000 OC: OpenCore DBG-068-2021-03-08 is loading in Optional mode (0/0)...
00:025 00:025 OC: Boot timestamp - 2021.03.09 03:01:52
00:050 00:025 OCCPU: MP services threads 24 (enabled 24) - Success
00:068 00:018 OCCPU: MP services Pkg 2 Cores 16 Threads 32 - Success
00:088 00:019 OCCPU: Found Intel(R) Xeon(R) CPU X5690 @ 3.47GHz
00:107 00:018 OCCPU: Signature 206C2 Stepping 2 Model 2C Family 6 Type 0 ExtModel 2 ExtFamily 0 uCode 1F
00:125 00:018 OCCPU: EIST CFG Lock 0
00:145 00:019 OCCPU: Timer address is 408 from LPC
00:263 00:117 OCCPU: Intel TSC: 3457999990Hz, 3457MHz; FSB: 132999999Hz, 132MHz; MaxBusRatio: 26
00:273 00:010 OCCPU: Detected Apple Processor Type: 05 -> 0501
00:295 00:021 OCCPU: CPUFrequencyFromTSC 3457999990Hz 3457MHz
00:317 00:022 OCCPU: CPUFrequency 3457999990Hz 3457MHz
00:339 00:021 OCCPU: FSBFrequency 132999999Hz 132MHz
00:361 00:021 OCCPU: Pkg 2 Cores 6 Threads 12
```
The rounding logic:
https://github.com/acidanthera/OpenCorePkg/blob/81ec3311a998585e8a5bba85def6bd330b84ee98/Library/OcSmbiosLib/SmbiosPatch.c#L416
Maybe it needs to be reset to:
```
if (MhzRemainder >= 12 && MhzRemainder < 90) {
    MhzSpeed = (MhzSpeed+5) / 10 * 10;
    } else {
    MhzSpeed = (MhzSpeed + 50) / 100 * 100;
  }
```
To correctly round?
Where does this case apply currently:
```
if (MhzRemainder >= 50 && MhzRemainder < 90) {
    MhzSpeed = (MhzSpeed) / 10 * 10;"
```
Also shouldn't ```FSB: 132999999Hz``` round to 133 actually? 133x26=3458

**Comment by startergo** [comment]
Does this help?
Post in thread 'OpenCore on the Mac Pro' https://forums.macrumors.com/threads/opencore-on-the-mac-pro.2207814/post-29670581

**Comment by anhtutran37** [comment]
I have x5675 with version 0.6.7 and it reported 3.05. I have to add 10 to correct 3.06. I will try new build 0.6.8 at tonight and will report later.
if (MhzRemainder >= 50 && MhzRemainder < 90) {
    MhzSpeed = (MhzSpeed + 10) / 10 * 10;

**Comment by vit9696** [comment]
I need a log from you.

**Comment by cdf** [comment]
> Do you have values for X5675?

`OCCPU: CPUFrequency 3058999712Hz 3058MHz`
