### ISSUE TITLE
SK Hynix - pc711 - Bootstrap / Memory partition 0, 2 KP

### ISSUE THREAD

**Issue by justice4no1** [acidanthera/bugtracker#1555]
I cant not get the log as the log is blank, 

The Dell 7501 comes with the new SK Hynix pc711 NVMe drive and it seems they are using a totally different controller that is giving a bootstrap error and a memory partition 0, 2 right before the KP.  

I changed the NVMe to an old San Disk NVMe and this is working perfectly with the same EFI config with Big Sur 11.2.2 with Intel Kext

I can send a video if needed as the log does not output anything.

**Comment by vit9696** [comment]
Unsupported SSD. Buy another.

**Comment by justice4no1** [comment]
I have changed the NVMe I just wanted to know if that NVMe will ever be supported?
