### ISSUE TITLE
IntelMausi - Big Sur 11.2.3

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1556]
Hi, today I updated macOS to 11.2.3 20B91, and the `Network` section in the finder is unable to list servers connected via LAN.

If I use the broadcom BCM94360NG (vendor 14e4 device-id 43a0) card everything works:

![image](https://user-images.githubusercontent.com/46293832/110512008-1dd12f00-8105-11eb-8fd5-9f7db1f72eb7.png)

However something happens while connecting though the Ethernet cable. What can I provide to debug this problem?

I fear the issue could me something in IntelMausi - I'm using an intel i219V2 -  which isn't working or isn't up to date with the changes made in today's update (11.2.3 20B91)

![image](https://user-images.githubusercontent.com/46293832/110512370-6d175f80-8105-11eb-9e02-c63fc6a4669d.png)

**Comment by 1alessandro1** [comment]
I fixed the problem connecting manually with `Go > Connect to Server` (or `CMD + K`) - now the `Network` section is back to normal.

However I'd like to investigate what can be related to this problem, any suggestions to investigate are very welcome

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/IntelMausi/blob/master/README.md
Do use the original version when uncertain. No support or troubleshooting provided.
