### ISSUE TITLE
NT350XCR-AD5AS: Stuck in EXITBS:START

### ISSUE THREAD

**Issue by PKRN0** [acidanthera/bugtracker#1557]
I tried plenty of configs to make this laptop boot. (Especially Kernel->Quirks, Booter->Quirks)
But all of them stopped at EXITBS:START. Recommended configs written in Opencore Guide Troubleshooting section did not work.
I'm using Big Sur 11.2.2 installer image to boot.

I saw that `Setupvirtualmap`was patched on 0.6.7, and I tried with it enabled, but did not work either.
These are my latest 6 configs with EFI folder and logs with opencore debug version.
[ConfigLog-NT350XCR.zip](https://github.com/acidanthera/bugtracker/files/6114640/ConfigLog-NT350XCR.zip)

Specifications:
NT350XCR-AD5AS(Samsing Notebook Plus)
CPU: i5-10210u
GPU: uhd620
RAM: ddr4 8gb x1
SSD1: Samsung PM991 NVME 250GB
SSD2: Micron MX500 500GB
WLAN: AC9462
LAN: RTL8168
SOUND: ALC256

I'm planning to disable pm991 and install macOS on MX500 SSD.

Bios Settings:
TPM Device: Off
Secure Boot Control: Off
Fast BIOS Mode: Off
LAN PXE OPROM: Off

Checked that it supports MATs and CFG-lock is disabled by checking the log.

Please Help!

**Comment by PKRN0** [comment]
This is another Efi and log before I tried the one in my first comment.
[EFI-NT350XCR_2.zip](https://github.com/acidanthera/bugtracker/files/6114910/EFI-NT350XCR_2.zip)

**Comment by lynxnu** [comment]
The same occurs with the model NP550XCJ-KT which has Core i3 instead of Core i5. Several people tried a lot of different configurations and no one was able to get into kernel.

**Comment by PKRN0** [comment]
These are my bios settings related to Hackintosh. 
![image](https://user-images.githubusercontent.com/17289367/110923915-c3cea480-8364-11eb-9e92-9fb086143319.png)
![image](https://user-images.githubusercontent.com/17289367/110923967-d517b100-8364-11eb-9ba7-2dabb30a4870.png)
![image](https://user-images.githubusercontent.com/17289367/110924000-dd6fec00-8364-11eb-8a8d-e18b0e097b77.png)
(Secure Boot Mode is set to Standard (Option is Standard or Custom))

**Comment by PKRN0** [comment]
I removed all drivers from the EFI [here](https://github.com/acidanthera/bugtracker/issues/1557#issuecomment-795177278), and tried to Windows 10 with it. Failed to boot with ACPI_BIOS_ERROR Bluescreen.
Here is the log.
[opencore-2021-03-12-204812.txt](https://github.com/acidanthera/bugtracker/files/6129818/opencore-2021-03-12-204812.txt)
would be glad if anyone here could help me ;D

**Comment by vit9696** [comment]
We do not provide help here. Enabling certain quirks in booter section and removing OpenRuntime.efi will break Windows. If you do not understand this, I am afraid there is no point in trying to debug this issue.

**Comment by PKRN0** [comment]
That 'help' I said is not to boot windows with OC, I just tried to provide more log to solve this issue not being able to boot into kernel. I tried to boot windows without drivers because I saw [this](https://github.com/badstorm/surface-pro-7-opencore/issues/9#issuecomment-766803946).

**Comment by lynxnu** [comment]
> That 'help' I said is not to boot windows with OC, I just tried to provide more log to solve this issue not being able to boot into kernel. I tried to boot windows without drivers because I saw [this](https://github.com/badstorm/surface-pro-7-opencore/issues/9#issuecomment-766803946).

I agree with you, Samsung's new Comet Lake BIOS Firmwares can't boot XNU kernel... Everyone that owns a Samsung 2020+ gets stuck at the EXITBS:START log, I tried to fix using DevirtualiseMmio to whitelist some parts of MMIO and I didn't get any results, if OpenCore provides more useful logs I would try to solve them, I can upload my full BIOS Dump here if it helps.

**Comment by PKRN0** [comment]
So, I think I made vit9696 totally misunderstand and looks like he will never reply this closed issue. Haha.. it's my fault.. I think I should open a new issue later with my bios dump and make everything more clear.

**Comment by lynxnu** [comment]
> So, I think I made vit9696 totally misunderstand and looks like he will never reply this closed issue. Haha.. it's my fault.. I think I should open a new issue later with my bios dump and make everything more clear.

Yes, he'll not reply. When creating an issue, create just one message, developers don't like to read issues, just send the logs... when the problem is not ours we don't care about solving it. The real problem is in SetupVirtualMap.

**Comment by vit9696** [comment]
* Firstly, I do read closed issues just like the open ones.
* Secondly, the problem like this one usually cannot be solved with logs. Extensive debugging with code knowledge is usually required to understand what is going on. Without the hardware on our side we can only work on such things given that the user is also a programmer in low-level field.
* Last but not least, developers do not need to care about the issues they do not have. Especially if these issues are bugs in third-party firmwares that need workarounds.

**Comment by PKRN0** [comment]
Okay, understood. Beacause I have the machine, and it looks like a real hardware issue, you mean I have to get dipper into debugging and give you some information that what is really causing problem or at least near that. And if it's only Samsung's Bios issue that cannot be solved or too hard to solve with editing codes of the bootloader, then I should modify it to make it work. I will try to get dipper into it and study more. Looks like a long trip for me!

**Comment by vit9696** [comment]
Basically that, yes. There is a good start with https://github.com/acidanthera/bugtracker/issues/1354#issuecomment-768124385.

**Comment by richibrics** [comment]
@PKRN0 hi, have you managed installing it ? My Lenovo yoga c640 was also stuck at EXITBS but I found a working solution [here](https://www.macos86.it/topic/4686-problema-hackintosh-per-lenovo-yoga-c640/) , maybe you’re interested in it.

However I’m interested in your solution (if you found one) because mine and yours machines have NVME PM991 that is unsupported and I can’t install macOS on the SSD (were you able installing on it ?)

Thank you

**Comment by PKRN0** [comment]
@richibrics Thanks for the comment! I will try it later. 

I didn't tried to install macOS on pm991, because it looked like there is no one managed to install and successfully boot mac on it.. Sorry for a unhelpful answer.
I'm planning to install macOS on my mx500 ssd.

**Comment by PKRN0** [comment]
@vit9696 Sorry for really late reply. I enabled early reboot and it rebooted both on the usb recovery and on ssd. 
I tried to boot 'installed' macOS from ssd(without early reboot), but it stopped at exitbs:start. Also tried exitbootservicesdelay, which did not work either.

Again, sorry for my newbie-ish question, but can you tell me how do I test the functions? [](https://github.com/acidanthera/bugtracker/issues/1354#issuecomment-768150503)

**Comment by vit9696** [comment]
You put a function into the `Base` for the patch and `Replace` it with ud2 (generate invalid opcode exception) `<0F 0B>`. Then you see where the hang happens by inspecting what reboots and what not. Checking that you can use the patch for the function can be done by running `nm` on the kernel file (`/System/Library/Kernels/kernel`), it will either print the proper function symbol or will symbol absence in this particular kernel build (e.g. due to. inlining).

**Comment by PKRN0** [comment]
Thanks! I'll try it and post results here. It might take some time..

**Comment by PKRN0** [comment]
Umm.. Well, I got some unexpected hardware issue. I just booted into Opencore 0.6.9 Debug bootpicker, and pressed tab and enter (I think it is restart or shutdown). After I did that, the power led is blinking and cannot see anything on the display. Tried soft rtc reset, pressing power button for a minute, they all did not work..

**Comment by PKRN0** [comment]
Okay, making my battery to 0% (which seems like doing same as resetting cmos) just solved it. Nevermind!

**Comment by PKRN0** [comment]
It stalls with _i386_init
![image](https://user-images.githubusercontent.com/17289367/117270011-c09ef300-ae93-11eb-96b3-f9afbda16c1c.png)
Am I doing right?

**Comment by vit9696** [comment]
More or less.

**Comment by PKRN0** [comment]
Okay. I'll try rest funcs.

**Comment by PKRN0** [comment]
Am I really doing right? Using default early reboot patch in sample.list does reboot, but when I put  _vstart in Base and 0F0B in Replace just stalls at EXITBS:START.

**Comment by PKRN0** [comment]
Tested all these funcs with Catalina HFS+ Recovery. I put `<31C0B006 BAF90C00 00EEEBFE>` in `Replace`.
_vstart - reboot
_i386_init - stall
_i386_vm_init - stall
_machine_startup - stall
_kernel_bootstrap - stall
_telemetry_init - stall
_thread_init - stall

All freezed except `_vstart`.

**Comment by vit9696** [comment]
Try different quirks, that's way too early.

**Comment by PKRN0** [comment]
Okay. May delay few days. 
Should I test all functions everytime I change some Quirks?

**Comment by vit9696** [comment]
`_vstart` calls the following functions in order:
- `_pal_serial_init`
- `_PE_init_platform`
- `_i386_init`

In my opinion, try to find whether any of these functions is called first, and then experiment with the quirks.

**Comment by PKRN0** [comment]
Alright, thanks. I cannot use my laptop for few days, so will be back with the results then.

**Comment by PKRN0** [comment]
I actually found that `_PE_init_platform` is called first. Tried combinations with `SetupVirtualMap` true/false, `EnableWriteUnprotector` true and `RebuildAppleMemoryMap` + `SyncRuntimePermissions` false(and the opposite).
However, there was no luck. They all didn't reach `_pal_serial_init`.(Didn't tried `_i386_init with all combs though) I'm thinking MMIOWhitelist for next, I have 6 regions. Do I need to test all combinations with those regions? Or any other suggestions for testing? I'm kind of wandering now..

**Comment by vit9696** [comment]
Try `_mt_early_init`. If it does not reach there, then it dies inside `_PE_init_platform` or `Idle_PTs_init` most likely. Try the functions inside `_PE_init_platform`, e.g. `_pe_identify_machine`, and inside `Idle_PTs_init` (this one is not exported), e.g. `_doublemap_init`.

**Comment by PKRN0** [comment]
Okay. Sorry for too many questions. Do I have to test with combination of quirks or chnaging one quirk at time tells me something? If I go combination, looks like there's too many of them to test all..

**Comment by vit9696** [comment]
Depends on the quirk really, generally combinations, but there is no easy table with their descriptions.

**Comment by PKRN0** [comment]
Okay. Just tested the functions you mentioned with the default quirks combination said in the Dortania's guide. Looks like the kernel dies right after reaching `_PE_init_platform`. `_pe_identify_machine`,`_doublemap_init`,`_idt64_remap` all freezed. I'll test `_pe_identify_machine`with MMIOWhitelist now.

**Comment by PKRN0** [comment]
![image](https://user-images.githubusercontent.com/17289367/117748933-dfaed380-b24b-11eb-8de4-f732159711c1.png)
I just noticed that there's nothing in my opencore log from some point.. Maybe it seems like started doing that after swapping `ProviceConsoleGop` to false? (It was True before and also set to True now) Or is it related to NVRAM or other configs? ApplePanic=True, AppleDebug=True, Target=67.. I think nothing is wrong with the config..

**Comment by vit9696** [comment]
@PKRN0, regarding your log I think it is due to having a RELEASE version of OpenCore. It logs exactly nothing if there are no errors.

As for the results:

1. Could you remind the full macOS version you try it on?
2. Could you upload your current EFI folder?
3. Inserting a reset into `_PE_init_platform` results in a reset, correct?
4. Inserting a reset into `_pe_identify_machine` results in no reset, correct? (same set of quirks with 3).
5. Does inserting reset into `_SecureDTInit` cause a reset? This is really the earliest of `_PE_init_platform`.
6. Does `_early_random` cause a reset? That's after `_PE_init_platform`, but it could be that some code is skipped in `_PE_init_platform`.

**Comment by PKRN0** [comment]
[EFI.zip](https://github.com/acidanthera/bugtracker/files/6456625/EFI.zip)
Just added MMIOWhitelist, but didn't tested any of them so disabled all.

**Comment by vit9696** [comment]
Right, so it sounds like `_early_random` dies. Since `_doublemap_init` is very close after.
1. Is CPUID supported for you?
2. Does `_PE_get_random_seed` reboot?
3. Does `_cpuid_leaf7_features` reboot?
4. Does `_cpuid_info` reboot?
