### ISSUE TITLE
OpenCore cannot determine CPU frequency on MacBook7,1

### ISSUE THREAD

**Issue by khronokernel** [acidanthera/bugtracker#1558]
When running OpenCore on a genuine MacBook7,1, it's unable to determine the CPU frequency:

```
OCCPU: Timer address is 0 from Failure
OCSMB: CPU display frequency is 0MHz
```

Test run with https://github.com/acidanthera/OpenCorePkg/commit/1ed6e7d5d00e978bc50bcb5bf0acb2a2494746db. CPU is Intel Core2 Duo P8600 2.40GHz
* [opencore-2021-03-10-211727.txt](https://github.com/acidanthera/bugtracker/files/6118966/opencore-2021-03-10-211727.txt)

**Comment by PMheart** [comment]
I wonder if https://github.com/acidanthera/OpenCorePkg/actions/runs/645927842 also solves this problem. Could you please try the artifacts?

**Comment by vit9696** [comment]
Has some special code needed due to nForce chipset. Added in https://github.com/acidanthera/OpenCorePkg/commit/5a69caa7e0c5914421cfff838b3950a545d01dba.
