### ISSUE TITLE
HibernateFixup Configuration

### ISSUE THREAD

**Issue by 1Revenger1** [acidanthera/bugtracker#1559]
I was wondering if there is any other way to configure HibernationFixup.kext beyond using boot-args? With my Lenovo X1 Extreme, the only boot-arg I need currently is [`hbfx-ahbm`](https://github.com/acidanthera/HibernationFixup/blob/master/HibernationFixup/kern_start.cpp#L56-L59), and this only really needed for hibernation with `hibernatemode=3` set in `pmset`. With most other kexts such as Whatevergreen, configuration can be done through device-properties. Would it be possible to do something similar with HibernationFixup?

Edit: Could be done with configuration through NVRAM as well since there isn't any obvious device to attach properties to (unless we create a custom device?)

**Comment by Andrey1970AppleLife** [comment]
CC @lvs1974

**Comment by lvs1974** [comment]
@1Revenger1: could you try an attached version, please?

1. remove hbfx-ahbm from boot-args
2. In OpenCore config.plist add dictionary E09B9297-7928-4440-9AAB-D1F8536FBF0A in Root->NVRAM->Add.
3. Add hbfx-ahbm (Number) with you value.

Example:
![Screenshot 2021-03-12 at 12 09 15](https://user-images.githubusercontent.com/27740976/110932427-c6f96e80-832b-11eb-805f-37e7135b0cf3.png)


[HibernationFixup-1.4.0-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/6129513/HibernationFixup-1.4.0-DEBUG.zip)

PS: frankly speaking, I don't see a big difference between using hbfx-ahbm in boot-args or in separate NVRAM variable.

**Comment by lvs1974** [comment]
This attached version supports all options in NVRAM:
[HibernationFixup-1.4.0-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/6131012/HibernationFixup-1.4.0-DEBUG.zip)

![Screenshot 2021-03-12 at 16 25 04](https://user-images.githubusercontent.com/27740976/110960885-83b0f700-834f-11eb-9969-311c25ed7bee.png)

**Comment by stevezhengshiqi** [comment]
@lvs1974 Thanks for this change! Could you explain a little bit more on features like `EnableAutoHibernation` and their difference with `hibernatemode=25`? Does the configuration in hbfx overwrites the pmset settings?

**Comment by lvs1974** [comment]
@stevezhengshiqi: EnableAutoHibernation - it is the first bit in option hbfx-ahbm, it is responsible only for turning on.
All these **hbfx-** options do not overwrite any system settings.
If you use hibernatemode=25, you don't need auto hibernation at all, since any sleep means hibernation!

**Comment by 1Revenger1** [comment]
Thanks! It's working on my machine. I appreciate the effort with HibernationFixup.kext - It's really nice having working hibernation now, since I tend to use my device pretty sporadically.
In the end, I don't think it's a big difference, you're right, but I do prefer not relying on functionality within boot-args if I can avoid it. Helps reduce human error on my end, and it was really the only thing I had to keep in my boot-args since every other kext has some additional way to configure it (including rtc blacklisting)

@stevezhengshiqi so from what I gather (atleast on my machine)
* hibernatemode=25: Does not require `EnableAutoHibernation` as it will just hibernate directly
* hibernatemode=3: Does require `EnableAutoHibernate`, as otherwise it will just sleep endlessly or causes weird behaviour (atleast on my device). This follows the settings in `pmset`, plus you can add various conditions such as hibernating at a critical battery level or only hibernating when the lid is closed.
