### ISSUE TITLE
APFS volumes aren't detected

### ISSUE THREAD

**Issue by zmlu** [acidanthera/bugtracker#1560]
Hello, 

I am trying to converting bootloader from Clover to OpenCore, every thing is ok when using Clover.
But when using OpenCore, Big Sur's APFS Volume aren't detected in boot menu.

I've already read some closed issue and followed the method in it, but they are no use for me, such as:
[https://github.com/acidanthera/bugtracker/issues/954](https://github.com/acidanthera/bugtracker/issues/954)
[https://github.com/acidanthera/bugtracker/issues/1128](https://github.com/acidanthera/bugtracker/issues/1128)

I'm using OpenCore-0.6.8-DEBUG.

**Files:**

Clover EFI：
[Clover.zip](https://github.com/acidanthera/bugtracker/files/6128994/Clover.zip)

OpenCore EFI and logs：
[EFI.zip](https://github.com/acidanthera/bugtracker/files/6128970/EFI.zip)
[opencore-2021-03-12-091111.txt](https://github.com/acidanthera/bugtracker/files/6128971/opencore-2021-03-12-091111.txt)

Thanks

**Comment by jackjack1-su** [comment]
scanpolicy
set to 0

**Comment by vit9696** [comment]
```
07:762 00:108 OCJS: Got APFS super block for F934779B-FB11-1E4F-BE86-0997910EA14C
07:863 00:101 OCJS: Block (P:1|F:0) read req 159D16B -> ACE8B58 of 1000 (mask 0, mul 8) - Success
07:971 00:107 OCJS: APFS driver 1677081001000000/20210106 found for F934779B-FB11-1E4F-BE86-0997910EA14C, required >= 748077008000000/20180621, allow
08:071 00:100 OCB: Arch filtering 0(645928)->77E3E018(645928) caps 4 - Success
08:172 00:100 OCJS: Connecting globally with disconnection APFS driver on handle 7A7C1F18
08:771 00:599 OCJS: Cannot connect, already handled
08:868 00:096 OCJS: Cannot connect, already handled
08:968 00:100 OCJS: Cannot connect, already handled
```

I am not positive you need `GlobalConnect` on your machine. Neither I believe you need `UnblockFsConnect`.

**Comment by zmlu** [comment]
Hi, in the OpenCore config above, `GlobalConnect ` and `UnblockFsConnect ` are checked.

**Comment by vit9696** [comment]
Yes, that's why I suggested to disable them, as they may cause a conflict.

**Comment by zmlu** [comment]
I tried three times with different settings, 
here are the settings and logs:

`GlobalConnect ` to NO and `UnblockFsConnect ` to NO:
[GC-off-and-UFC-off.txt](https://github.com/acidanthera/bugtracker/files/6138820/GC-off-and-UFC-off.txt)

`GlobalConnect ` to NO and `UnblockFsConnect ` to YES:
[GC-off-and-UFC-on.txt](https://github.com/acidanthera/bugtracker/files/6138821/GC-off-and-UFC-on.txt)

`GlobalConnect ` to YES and `UnblockFsConnect ` to NO:
[GC-on-and-UFC-off.txt](https://github.com/acidanthera/bugtracker/files/6138824/GC-on-and-UFC-off.txt)

The results are same, APFS volumes don't show. 
![screen](https://user-images.githubusercontent.com/16974046/111103685-f9080c00-8589-11eb-855d-5186f3122d3b.jpeg)

**Comment by vit9696** [comment]
Tell us more about your hardware. CC @mhaeuser We will need to debug it to determine the issue, likely closer to the weekend or afterwards.

**Comment by vit9696** [comment]
```
GlobalConnect to NO and UnblockFsConnect to NO:
GC-off-and-UFC-off.txt
```

This log is incomplete. Please redo.

**Comment by vit9696** [comment]
UPD: APFS volumes are detected without issues. Most likely you have your operating system installed with an unusual way. macOS Installer is the currently active boot entry on your main drive.
 (APFS).

**Comment by zmlu** [comment]
As you say, I fully reinstalled Big Sur by OpenCore and the problem solved.
Thank you, sir.
