### ISSUE TITLE
No device tree in MaciASL 1.5.9

### ISSUE THREAD

**Issue by Tyraenor** [acidanthera/bugtracker#1561]
Hi,

I noticed that I cannot apply patched with release 1.5.9, as there is no device tree, so I assume the devices are not detected correctly.

In 1.5.7 it works, but I the following lines (which I do not get in 1.5.9 or 1.5.8)

 Firmware Error (ACPI): Could not resolve symbol [^PCI0.LPCB.EC0.ECMX], AE_NOT_FOUND (20200110/dswload-496)
// Firmware Error (ACPI): Could not resolve symbol [^PCI0.LPCB.EC0.ECRG], AE_NOT_FOUND (20200110/dswload-496)
// Firmware Error (ACPI): Could not resolve symbol [^PCI0.LPCB.EC0.PSCF], AE_NOT_FOUND (20200110/dswload-496)
// Firmware Error (ACPI): Could not resolve symbol [^PCI0.LPCB.EC0.BCSC], AE_NOT_FOUND (20200110/dswload-496)
// Firmware Error (ACPI): Could not resolve symbol [^RP09.PXSX.DD1F], AE_NOT_FOUND (20200110/dswload-496)
// Firmware Error (ACPI): Could not resolve symbol [^RP09.PXSX.SVID], AE_NOT_FOUND (20200110/dswload-496)
// Firmware Error (ACPI): Could not resolve symbol [^^^IETM.DFFG], AE_NOT_FOUND (20200110/dswload-496)
// Firmware Error (ACPI): Could not resolve symbol [^PCI0.LPCB.EC0.ECMX], AE_NOT_FOUND (20200110/dswload2-477)
// Firmware Error (ACPI): Could not resolve symbol [^PCI0.LPCB.EC0.ECRG], AE_NOT_FOUND (20200110/dswload2-477)
// Firmware Error (ACPI): Could not resolve symbol [^PCI0.LPCB.EC0.PSCF], AE_NOT_FOUND (20200110/dswload2-477)
// Firmware Error (ACPI): Could not resolve symbol [^PCI0.LPCB.EC0.BCSC], AE_NOT_FOUND (20200110/dswload2-477)
// Firmware Error (ACPI): Could not resolve symbol [^RP09.PXSX.DD1F], AE_NOT_FOUND (20200110/dswload2-477)
// Firmware Error (ACPI): Could not resolve symbol [^RP09.PXSX.SVID], AE_NOT_FOUND (20200110/dswload2-477)
// Firmware Error (ACPI): Could not resolve symbol [^^^IETM.DFFG], AE_NOT_FOUND (20200110/dswload2-477)

I am not sure, if I can ignore these errors, or if you can help me with a fixed version of 1.5.9.

I need to patch my battery and do not want to add errors... ;-)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/1089

**Comment by Tyraenor** [comment]
Ok, replacing the compiler in 1.5.7 did the trick for me for now. But would be nice to get it fixed in the new versions.

**Comment by dreamwhite** [comment]
> Ok, replacing the compiler in 1.5.7 did the trick for me for now. But would be nice to get it fixed in the new versions.

I managed to fix, thanks to [this comment ](https://github.com/acidanthera/bugtracker/issues/1089#issuecomment-781979545)on issue #1089
