### ISSUE TITLE
Incorrect External Clock 100Mhz in DMI

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#1562]
- Started

HI. recently, i bought 8th laptop and tried to install macOS Big Sur 11.2.3.
now i'm trying to optimizing ACPI and etc.

- Specs
bootloader : latest OC 0.6.8
CPU : i7-8550u
RAM : LPDDR3 16GB Dual.

- Problem
External Clock is 100Mhz

- Prove
------------------- Real Mac -------------------
Processor Information
	Socket Designation: U3E1
	Type: Central Processor
	Family: Core i5
	Manufacturer: Intel(R) Corporation
	ID: E9 06 08 00 FF FB EB BF
	Signature: Type 0, Family 6, Model 142, Stepping 9
	Flags:
		FPU (Floating-point unit on-chip)
		VME (Virtual mode extension)
		DE (Debugging extension)
		PSE (Page size extension)
		TSC (Time stamp counter)
		MSR (Model specific registers)
		PAE (Physical address extension)
		MCE (Machine check exception)
		CX8 (CMPXCHG8 instruction supported)
		APIC (On-chip APIC hardware supported)
		SEP (Fast system call)
		MTRR (Memory type range registers)
		PGE (Page global enable)
		MCA (Machine check architecture)
		CMOV (Conditional move instruction supported)
		PAT (Page attribute table)
		PSE-36 (36-bit page size extension)
		CLFSH (CLFLUSH instruction supported)
		DS (Debug store)
		ACPI (ACPI supported)
		MMX (MMX technology supported)
		FXSR (FXSAVE and FXSTOR instructions supported)
		SSE (Streaming SIMD extensions)
		SSE2 (Streaming SIMD extensions 2)
		SS (Self-snoop)
		HTT (Multi-threading)
		TM (Thermal monitor supported)
		PBE (Pending break enabled)
	Version: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
	Voltage: 0.8 V
	**External Clock: 25 MHz**
	**Max Speed: 2300 MHz**
	Current Speed: 2200 MHz
	Status: Populated, Enabled
	Upgrade: Other
	L1 Cache Handle: 0x001B
	L2 Cache Handle: 0x001C
	L3 Cache Handle: 0x001D
	**Serial Number: To Be Filled By O.E.M.
	Asset Tag: To Be Filled By O.E.M.
	Part Number: To Be Filled By O.E.M.**
	Core Count: 2
	Core Enabled: 2
	Thread Count: 4
	Characteristics:
		64-bit capable
		Multi-Core
		Hardware Thread
		Execute Protection
		Enhanced Virtualization
		Power/Performance Control
------------------- OC -------------------
Processor Information
	Socket Designation: U3E1
	Type: Central Processor
	Family: Core i7
	Manufacturer: Intel(R) Corporation
	ID: EA 06 08 00 FF FB EB BF
	Signature: Type 0, Family 6, Model 142, Stepping 10
	Flags:
		FPU (Floating-point unit on-chip)
		VME (Virtual mode extension)
		DE (Debugging extension)
		PSE (Page size extension)
		TSC (Time stamp counter)
		MSR (Model specific registers)
		PAE (Physical address extension)
		MCE (Machine check exception)
		CX8 (CMPXCHG8 instruction supported)
		APIC (On-chip APIC hardware supported)
		SEP (Fast system call)
		MTRR (Memory type range registers)
		PGE (Page global enable)
		MCA (Machine check architecture)
		CMOV (Conditional move instruction supported)
		PAT (Page attribute table)
		PSE-36 (36-bit page size extension)
		CLFSH (CLFLUSH instruction supported)
		DS (Debug store)
		ACPI (ACPI supported)
		MMX (MMX technology supported)
		FXSR (FXSAVE and FXSTOR instructions supported)
		SSE (Streaming SIMD extensions)
		SSE2 (Streaming SIMD extensions 2)
		SS (Self-snoop)
		HTT (Multi-threading)
		TM (Thermal monitor supported)
		PBE (Pending break enabled)
	Version: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Voltage: 1.2 V
	**External Clock: 100 MHz**
	**Max Speed: 2000 MHz**
	Current Speed: 2000 MHz
	Status: Populated, Enabled
	Upgrade: Socket BGA1356
	L1 Cache Handle: 0x0008
	L2 Cache Handle: 0x0009
	L3 Cache Handle: 0x000A
	**Serial Number: None
	Asset Tag: None
	Part Number: None**
	Core Count: 4
	Core Enabled: 4
	Thread Count: 8
	Characteristics:
		64-bit capable
		Multi-Core
		Hardware Thread
		Execute Protection
		Enhanced Virtualization
		Power/Performance Control
------------------- Clover ------------------- 
Processor Information
	Socket Designation: U2E1
	Type: Central Processor
	Family: Core i7
	Manufacturer: Intel(R) Corporation
	ID: EA 06 08 00 FF FB EB BF
	Signature: Type 0, Family 6, Model 142, Stepping 10
	Flags:
		FPU (Floating-point unit on-chip)
		VME (Virtual mode extension)
		DE (Debugging extension)
		PSE (Page size extension)
		TSC (Time stamp counter)
		MSR (Model specific registers)
		PAE (Physical address extension)
		MCE (Machine check exception)
		CX8 (CMPXCHG8 instruction supported)
		APIC (On-chip APIC hardware supported)
		SEP (Fast system call)
		MTRR (Memory type range registers)
		PGE (Page global enable)
		MCA (Machine check architecture)
		CMOV (Conditional move instruction supported)
		PAT (Page attribute table)
		PSE-36 (36-bit page size extension)
		CLFSH (CLFLUSH instruction supported)
		DS (Debug store)
		ACPI (ACPI supported)
		MMX (MMX technology supported)
		FXSR (FXSAVE and FXSTOR instructions supported)
		SSE (Streaming SIMD extensions)
		SSE2 (Streaming SIMD extensions 2)
		SS (Self-snoop)
		HTT (Multi-threading)
		TM (Thermal monitor supported)
		PBE (Pending break enabled)
	Version: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Voltage: 1.2 V
	**External Clock: 25 MHz
	Max Speed: 2000 MHz**
	Current Speed: 1800 MHz
	Status: Populated, Enabled
	Upgrade: Socket BGA1356
	L1 Cache Handle: 0x0007
	L2 Cache Handle: 0x0008
	L3 Cache Handle: 0x0009
	**Serial Number: E0
	Asset Tag: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Part Number: None**
	Core Count: 4
	Core Enabled: 4
	Thread Count: 8
	Characteristics:
		64-bit capable
		Multi-Core
		Hardware Thread
		Execute Protection
		Enhanced Virtualization
		Power/Performance Control

**Comment by vit9696** [comment]
Without DEBUG log I cannot tell you much, yet it looks correct. External Clock equals FSBFrequency, which is FSB * MULT = TSC. Depending on the hardware FSB is either specified in QP format (quad-multiplied) or actual value. Macs generally prefer QP format, so OpenCore behaves correctly.

**Comment by Sher1ocks** [comment]
> Without DEBUG log I cannot tell you much, yet it looks correct. External Clock equals FSBFrequency, which is FSB * MULT = TSC. Depending on the hardware FSB is either specified in QP format (quad-multiplied) or actual value. Macs generally prefer QP format, so OpenCore behaves correctly.

here is log
[opencore-2021-03-14-043642.txt](https://github.com/acidanthera/bugtracker/files/6136108/opencore-2021-03-14-043642.txt)

**Comment by vit9696** [comment]
Yes, FSB frequency for you is indeed 100 MHz, thus External Clock must also be 100 MHz (in QP format). OpenCore behaviour is correct.

To repeat in case you still do not get it, 25 MHz in your OEM SMBIOS is the same as 100 MHz in updated SMBIOS, just the display formats are different. For Macs QP format must be used.

**Comment by Sher1ocks** [comment]
> Yes, FSB frequency for you is indeed 100 MHz, thus External Clock must also be 100 MHz (in QP format). OpenCore behaviour is correct.
> 
> To repeat in case you still do not get it, 25 MHz in your OEM SMBIOS is the same as 100 MHz in updated SMBIOS, just the display formats are different. For Macs QP format must be used.

okay, thanks a lot vit!
