### ISSUE TITLE
OpenCore Board-ID discrepancy for MacBookPro16,2 & MacBookPro16,3

### ISSUE THREAD

**Issue by mBilG** [acidanthera/bugtracker#1563]
**For models: MacBookPro16,2 and MacBookPro16,3**

According to OpenCore database [here](https://github.com/acidanthera/OpenCorePkg/tree/master/AppleModels/DataBase/MacBookPro) and [here](https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html#macbook-pro), the board-ids are as follows:
MacBookPro16,3 : Mac-E7203C0F68AA0004
MacBookPRo16,2 : Mac-5F9802EFE386AA28

However, according to [this page](https://mrmacintosh.com/list-of-mac-boardid-deviceid-model-identifiers-machine-models/), it should be:
MacBookPro16,3 : Mac-5F9802EFE386AA28
MacBookPRo16,2 : Mac-E7203C0F68AA0004

The 2 are swapped.. 

My questions therefore are:

1. Which one is the correct one? _Possible bug??_ or can someone who owns one of these verify that?
2. Are they hard-coded?
3. How do I change them in my config.plist?
Note: I have tried using SystemSKUNumber and BoardProduct (as they are mentioned in OC configuration pdf) under generic, both have not been successful. at boot OC returns an error saying these parameters do not exist.  _Possible bug??_
4. I suspect that this may cause certain limitations similar to how wrong SerialNumber may affect power management etc? Am I correct?

Thanks

**Comment by Andrey1970AppleLife** [comment]
> However, according to [this page](https://mrmacintosh.com/list-of-mac-boardid-deviceid-model-identifiers-machine-models/)
This site contains an error.

**Comment by vit9696** [comment]
Ours should be correct. Provide Mac dumps if you think otherwise.

**Comment by mBilG** [comment]
You guys are correct..
i just confirmed from some online geekbench results [here](https://browser.geekbench.com/v5/cpu/2066737)

Thanks for the response and sorry for the inconvenience..

Keep up the great work..
