### ISSUE TITLE
Unable to inject AppleAirPortBrcm43224.kext

### ISSUE THREAD

**Issue by khronokernel** [acidanthera/bugtracker#1565]
For many legacy Macs, El Capitan's AppleAirPortBrcm43224.kext is required to to achieve wireless networking on 10.12, Sierra and newer.

When injecting a patched IO80211Family with AppleAirPortBrcm43224.kext, OpenCore will error out:

* Following test run on both High Sierra and Big Sur

```
87:127 00:777 OC: Prelinked injection IO80211ElCap.kext () - Success
87:600 00:472 OCAK: Vtable patching failed for kext com.apple.driver.AirPortBrcm43224
87:770 00:170 OC: Prelinked injection IO80211ElCap.kext\Contents\PlugIns\AppleAirPortBrcm43224.kext () - Invalid Parameter
```

* [opencore-2021-03-15-021040.txt](https://github.com/acidanthera/bugtracker/files/6138362/opencore-2021-03-15-021040.txt)

* [10.13.6 Prelinked Kernel](https://github.com/acidanthera/bugtracker/files/6138365/prelinkedkernel.zip)

* [IO80211ElCap.kext.zip](https://github.com/acidanthera/bugtracker/files/6138387/IO80211ElCap.kext.zip)

* [OpenCore Configuration](https://github.com/acidanthera/bugtracker/files/6138375/Archive.zip)

**Comment by vit9696** [comment]
```
Patch failure __ZTV17AirPort_Brcm43224 __ZN17IO80211Controller27_RESERVEDIO80211Controller7Ev
```

AppleAirPortBrcm43224.kext references `__ZN17IO80211Controller27_RESERVEDIO80211Controller7Ev` symbol, which it is not given.
