### ISSUE TITLE
Opencanopy: mouse doesn't behave correctly

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1567]
With the latest batch of commits to Opencanopy (if needed I will find the exact commit), the mouse doesn't behave
 as expected.

Mac os Big Sur 11.2.3 20D91 running on qemu 5.2.0
usb mouse passed through
Opencore version: DBG-068-2021-03-18
All Acidanthera kexts updated
Using driver UsbMouseDxe.efi for Opencanopy

Description:
once in Opencanopy double left click on icons does nothing, double left click on arrows (below the icons) freezes the machine.

Attached opencore log: system boot, boot to opencanopy, double left click on OS drive, double left click on its arrow --> Freeze

Note: keyboard (same usb dongle) (arrows/enter) works as expected

Thanks!

[opencore-2021-03-18-065344.txt](https://github.com/acidanthera/bugtracker/files/6161956/opencore-2021-03-18-065344.txt)

**Comment by 82ghost82** [comment]
Fixed with:
https://github.com/acidanthera/OpenCorePkg/commit/bfe091c0e683a01978b4beab77d4fccd0dd9fe1e

Is it the expected behavior that clicking on the main icon does nothing? Only arrows below icons are "active"?

thanks mhauser

**Comment by Andrey1970AppleLife** [comment]
> 
> Is it the expected behavior that clicking on the main icon does nothing? Only arrows below icons are "active"?
> 

CC @mhaeuser

**Comment by Andrey1970AppleLife** [comment]
Fixed

**Comment by 82ghost82** [comment]
Hi, sorry to reopen this, but just to be sure everything works as expected:
@Andrey1970AppleLife  you wrote:
> Double click should launch the boot entry, yet this no longer happens.

Is it a double click or a click?Because in my case, now (and I think in my case was always as this) the boot entry launches with a single left click; is it the same for you and is this what is expected?

**Comment by Andrey1970AppleLife** [comment]
Double click if it isn't selected. One click if beforehand it is selected.
@mhaeuser, it is correct?

**Comment by mhaeuser** [comment]
@82ghost82 @Andrey1970AppleLife That was the old behaviour, I just pushed a commit (https://github.com/acidanthera/OpenCorePkg/commit/29b6a69845895d01d6fafa8b4771aa314bab5737) that requires it to be a double-click no matter the selection state. Was tested on QEMU, ASUS B550, and a Mac.
