### ISSUE TITLE
[SSDT BRG0] Clarifications

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1569]
Hi, today I added `SSDT-BRG0.aml` in my OC/ACPI folder and to the config.plist - I'm on a desktop with dGPU (RX590) + iGPU in headless mode, handled by `WhateverGreen.kext` for the properties.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/46293832/111675303-44861880-881d-11eb-8a36-10f296b7d0a6.png">

These are the contents of the SSDT: 

```
DefinitionBlock ("", "SSDT", 2, "ACDT", "BRG0", 0x00000000)
{
    External (_SB_.PCI0.PEG0.PEGP, DeviceObj)

    Scope (\_SB.PCI0.PEG0.PEGP)
    {
        Device (BRG0)
        {
            Name (_ADR, Zero)  // _ADR: Address
            Device (GFX0)
            {
                Name (_ADR, Zero)  // _ADR: Address
            }
        }
    }
}

```
My questions are:
- Is that normal that the device only appears under `IOACPIPlane` and `IODeviceTree` and *not* in `IOService` near GFX0 and HDAU?

  - Here's a screenshot from `IOService`
<img width="506" alt="image" src="https://user-images.githubusercontent.com/46293832/111677855-eeff3b00-881f-11eb-8bad-f10729caff9e.png">
  
   - Here's a screenshot from `IOACPIPlane`

<img width="588" alt="image" src="https://user-images.githubusercontent.com/46293832/111678315-7056cd80-8820-11eb-9c8b-2b2dc172e3ef.png">

   - Here's a screenshot from `IODeviceTree`
  
<img width="703" alt="image" src="https://user-images.githubusercontent.com/46293832/111678230-5a490d00-8820-11eb-894c-b6cc6387b19a.png">

- Is there any difference between addressing the device to  `_SB_.PCI0.PEG0.PEGP` and `_SB_.PCI0.PEG0`?
- Could you clarify the purpose of `SSDT-BRG0` and how/why affects 11.0 and newer?

Thanks for your time.

**Comment by Andrey1970AppleLife** [comment]
For RX590 isn't required SSDT-BRG0

**Comment by 1alessandro1** [comment]
> For RX590 isn't required SSDT-BRG0

Please elaborate why

**Comment by vit9696** [comment]
You do not have an intermediate bridge in your GPU, and neither does your motherboard have. For you SB.PCI0.PEG0.PEGP is exactly the video adapter (GFX0 as renamed by WEG).

SBRG is for hardware with intermediate bridges to ensure that all your devices have ACPI names. I would strongly advise injecting HDAU for your case, since otherwise HDMI audio may not work.

The explanation why generating ACPI devices is required is provided in OC DeviceProperties section and it does not relate to GPUs specifically. Also, this is not quite the right place to ask for support.

**Comment by 1alessandro1** [comment]
Thanks @vit9696 for quick response,

1) in the [dortania guide](https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#deviceproperties-injection-failing) I found that BRG0 is required when `acpi-path` is missing on any of the devices under `AppleACPIPlatform`. However, when booting BigSur without SSDT-BRG0, every device shows up with its correct `acpi-path` in `IOService` (ioreg).

2) Having said the things at (1.) is this still valid? Do you recommend to compile `SSDT-BRG0.aml` as-is and add it to ACPI since:
> You do not have an intermediate bridge in your GPU, and neither does your motherboard have. For you SB.PCI0.PEG0.PEGP is exactly the video adapter (GFX0 as renamed by WEG). 



3) Last but not least,
> SBRG is for hardware with intermediate bridges to ensure that all your devices have ACPI names. I would strongly advise injecting HDAU for your case, since otherwise HDMI audio may not work.

 In my case I can confirm I have audio working though DisplayPort - when connecting headphones to the monitor audio works. Is it the same thing for HDMI for "induction" or do I have to test HDMI audio too?

Thanks for your patience

**Comment by vit9696** [comment]
1. This is correct.
2. Does your HDAU have acpi-path? I did not notice there is one on the first screenshot, so you can disregard my comment if it does.

**Comment by 1alessandro1** [comment]
> Does your HDAU have acpi-path? I did not notice there is one on the first screenshot, so you can disregard my comment if it does.

I think it does not... I've tested both, audio though HDMI and though DisplayPort, with my QC25 headphones connected with a standard jack, and audio works.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/46293832/111705010-4c0ae900-8840-11eb-9b1f-6672eff278ae.png">


But GFX0 has its acpi-path:
<img width="1296" alt="Screenshot 2021-03-18 at 23 19 48" src="https://user-images.githubusercontent.com/46293832/111705179-9ab88300-8840-11eb-9abc-19ad6dbef90b.png">


Should I add the following (for completeness, since audio is working anyway): 


```
DefinitionBlock ("", "SSDT", 2, "ACDT", "BRG0", 0x00000000)
{
    External (_SB_.PCI0.PEG0, DeviceObj)

    Scope (\_SB.PCI0.PEG0)
    {
        Device (HDAU)
        {
            Name (_ADR, Zero)  // _ADR: Address
        }
    }
}
```

Without `Device (BRG0)` on top?

**Comment by 1alessandro1** [comment]
> edit: Name (_ADR, One) instead of Zero for HDAU

I'm wondering if there's any difference specifying `One` or `Zero`...

Now I can see the `acpi-path` for HDAU too (on the left the newest ioreg), with the SSDT above.

<img width="1920" alt="Screenshot 2021-03-18 at 23 50 34" src="https://user-images.githubusercontent.com/46293832/111707820-10265280-8845-11eb-9c66-adc44584c4e4.png">

**Comment by 1alessandro1** [comment]
Also I noticed in the ACPI Log the following, could this be related to what was discovered above?

`AGDCC: Unauthorized client 'PerfPowerService'` here's the specific part from the log:

```
2021-03-08 08:08:25.741720-0800 0xefc      Default     0x0                  0      0    kernel: (AppleGraphicsDeviceControl) AGDCC: Unauthorized client 'PerfPowerService' (IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/AMD9500ControllerWrangler)
2021-03-08 08:08:25.741755-0800 0xefc      Default     0x0                  0      0    kernel: (AppleGraphicsDeviceControl) AGDCC: Unauthorized client 'PerfPowerService' (IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebufferController/IntelFBClientControl)
```

Could this be WEG related?

**Comment by dreamwhite** [comment]
> Also I noticed in the ACPI Log the following, could this be related to what was discovered above?
> 
> `AGDCC: Unauthorized client 'PerfPowerService'` here's the specific part from the log:
> 
> ```
> 2021-03-08 08:08:25.741720-0800 0xefc      Default     0x0                  0      0    kernel: (AppleGraphicsDeviceControl) AGDCC: Unauthorized client 'PerfPowerService' (IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/AMD9500ControllerWrangler)
> 2021-03-08 08:08:25.741755-0800 0xefc      Default     0x0                  0      0    kernel: (AppleGraphicsDeviceControl) AGDCC: Unauthorized client 'PerfPowerService' (IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebufferController/IntelFBClientControl)
> ```
> 
> Could this be WEG related?

I can confirm on my side that those "errors" (?) appear on my laptop (i5-8250U - UHD 620).

From what I read online, more precisely on [this reddit answer](https://www.reddit.com/r/hackintosh/comments/g7kkof/agdcc_unauthorized_client_perfpowerservice/fxi8k10?utm_source=share&utm_medium=web2x&context=3) it seems that this check is meant to check that internal peripherals to get them ready for use (so it's a internal thing of the OS) 
@vit9696 is this assumption wrong or could this be WEG related and skipped in any way?

Many thanks and have a nice day

**Comment by vit9696** [comment]
No need to worry. Not WEG related.
