### ISSUE TITLE
[macrecovery.py] MLB Validation

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1570]
Checking the man page with `-h` for `macrecovery.py` I can see there are a few tools to validate `MLB`.

- The first one is the following: `./macrecovery.py verify -m MLB -b BOARD-ID` and for the given MLB and board-id, it returns: 
```
SUCCESS: (my_MLB) MLB looks valid and supported!
```
- The other one uses another argument, `./macrecovery.py selfcheck` which to me, is a little unclear from the man page:
```
"selfcheck" checks whether MLB serial validation is possible
```

But looking at the code:

```
if product_default[INFO_PRODUCT] != product_latest[INFO_PRODUCT]:
    # Product-only MLB must give the same value for default and latest.
    print('ERROR: Latest and default do not match for product MLB, got {} and {}'.format(
      product_default[INFO_PRODUCT], product_latest[INFO_PRODUCT]))
    return 1
```
Seems like this shouldn't return an error only if the MLB when the `default` argument is given, matches `latest` - which is valid only for the newest macs (iMac19,1, which is the one i'm currently using) has a Mojave build when using:

```
./macrecovery.py -b <my BOARD-ID> -m <real MLB> -os default download
```

and for `latest`, it downloads the latest recovery (BigSur).

Curious to `validate` with `selfcheck` the MLB I am using, the result is the following:

```
./macrecovery.py selfcheck 
ERROR: Latest and default do not match for product MLB, got 091-63921 and 071-14768
```

Is this expected since the SMBIOS and BOARD-ID in use are not the newest available or is this an issue with the  `MLB` value generated by `macserial`?

**Comment by vit9696** [comment]
Selfcheck is to check that Apple servers behave in an expectable manner.

**Comment by 1alessandro1** [comment]
This has nothing to do with the `MLB` value generated by macserial then?

Why should `macrecovery.py` return an error if this is expected? (not every `MLB` is the newest out there)

```ERROR: Latest and default do not match for product MLB, got 091-63921 and 071-14768```

Shouldn't it be something like:
```
WARN: Your MLB isn't the newest available - latest and default do not match for product MLB, got 091-63921 and 071-14768
```

**Comment by vit9696** [comment]
> This has nothing to do with the MLB value generated by macserial then?

Yes.

> Why should macrecovery.py return an error if this is expected? (not every MLB is the newest out there)

Because Apple servers behave differently now.
