### ISSUE TITLE
Broadcom bcm94350zae (dw1820a) personal hotspot not available

### ISSUE THREAD

**Issue by Hush-vv** [acidanthera/bugtracker#1571]
Broadcom bcm94350zae (dw1820a) personal hotspot is not available, prompt "failed to enable personal hotspot on 'iPhone 11 Pro Max'".But the phone is in front of the computer, Bluetooth and WiFi are both turned on, and the same Apple ID is used when logging in
<img width="340" alt="QQ20210321-171932@2x" src="https://user-images.githubusercontent.com/61744850/111900045-31688800-8a6b-11eb-9fac-7f48152b3a58.png">
<img width="450" alt="WX20210321-171323@2x" src="https://user-images.githubusercontent.com/61744850/111900048-33cae200-8a6b-11eb-9882-15819668ef2c.png">

![IMG_4578](https://user-images.githubusercontent.com/61744850/111900256-7d67fc80-8a6c-11eb-9721-6fa7de547bfd.jpg)

**Comment by vit9696** [comment]
Yeah, use original Apple modules.
