### ISSUE TITLE
cosmetics issue in MaciASL 

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#1572]
i found cosmetics issue in MaciASL

- Setting
version : 1.5.9
default(iASL Compiler : Stable)
--> i didn't touch anything

- Issue
1. before
https://github.com/RehabMan/OS-X-Null-Ethernet/blob/master/SSDT-RMNE.dsl
--> before compile it, no issue
![스크린샷 2021-03-21 오후 7 01 26](https://user-images.githubusercontent.com/2107738/111900803-e143f280-8a77-11eb-8165-ba52697f3444.png)

2. after(complie)
![스크린샷 2021-03-21 오후 7 01 37](https://user-images.githubusercontent.com/2107738/111900879-4861a700-8a78-11eb-9a66-acabbd216824.png)

have to remove "."3DUf"
![스크린샷 2021-03-21 오후 7 04 50](https://user-images.githubusercontent.com/2107738/111900893-63ccb200-8a78-11eb-9413-c965bb9b9162.png)

i don't know why make this word ."3DUf

thanks in advance.

**Comment by vit9696** [comment]
Does it reproduce with 1.6.0?

**Comment by Sher1ocks** [comment]
> Does it reproduce with 1.6.0?

fixed. thank you
![스크린샷 2021-03-21 오후 8 58 18](https://user-images.githubusercontent.com/2107738/111904066-3e47a480-8a88-11eb-9749-9b822cec9862.png)
