### ISSUE TITLE
SMCBatteryManager.kext "Service Recommended " appears in the upper left corner after use

### ISSUE THREAD

**Issue by TzeKitKwok** [acidanthera/bugtracker#1573]
Hello developer, SmcBatteryManager, after using the battery "Service recommended ", the battery health cycle number is not a problem, how to solve, see the picture
[EFI.zip](https://github.com/acidanthera/bugtracker/files/6182739/EFI.zip)
[DSDT.dsl.zip](https://github.com/acidanthera/bugtracker/files/6182742/DSDT.dsl.zip)
[SSDT-BATT.dsl.zip](https://github.com/acidanthera/bugtracker/files/6182745/SSDT-BATT.dsl.zip)
![Screen Shot 2021-03-22 at 9 36 54 PM](https://user-images.githubusercontent.com/42382226/112002142-8f27cd80-8b5a-11eb-8b98-ca88f10d7f5b.png)
![Screen Shot 2021-03-22 at 9 37 08 PM](https://user-images.githubusercontent.com/42382226/112002149-9058fa80-8b5a-11eb-8b9e-05a47440b807.png)
![Screen Shot 2021-03-22 at 9 37 22 PM](https://user-images.githubusercontent.com/42382226/112002157-9222be00-8b5a-11eb-8970-071ac74c8cef.png)
![Screen Shot 2021-03-22 at 9 37 42 PM](https://user-images.githubusercontent.com/42382226/112002160-9353eb00-8b5a-11eb-87cc-375e6c9bebcc.png)
![Screen Shot 2021-03-22 at 10 08 03 PM](https://user-images.githubusercontent.com/42382226/112002920-5b00dc80-8b5b-11eb-90a3-00046ef2c87b.png)

**Comment by vit9696** [comment]
Well, 68% health does agree with service recommended, I believe the battery should be at least 70-75% good. CC @lvs1974, @usr-sse2

**Comment by usr-sse2** [comment]
Don't know why, but on my Dell Latitude laptop it also shows 62%, it was 70% right after purchase. AIDA64 shows the same values, so the issue is not in SMCBatteryManager. Although Dell software shows the battery state as 'Excellent', but doesn't show any numeric values.
What do Linux and AIDA64 show in your case?

**Comment by TzeKitKwok** [comment]
My HP laptop is also, like you
