### ISSUE TITLE
When using HiDPI, Screen underscaled after sleep

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#1574]
## My System
- Model : Lenovo X1 Carbon 6th
- Display :  2560x1440, 2K HDR 500nits.
- OC : latest 0.6.8
- AAPL,ig-platform-id has 87C00000
- getOSData device-id has 5916 value
  IGPU has real 5917 acpi 5916 fake 5916 and model Intel UHD Graphics 620

## Reason
- i want to use HiDPI to protect eyes.

## Issue
- if i'm using normal resolution(1920x1080) with HiDPI, when the laptop wake the screen is badly underscaled and 
   it is very small in the top left corner.  The rest of the display is black. 
![KakaoTalk_Photo_2021-03-25-00-07-33](https://user-images.githubusercontent.com/2107738/112333635-20837500-8cfe-11eb-9bc6-26115d931fa1.jpeg)

## Difference
- **If i'm using normal resolution(1920x1080) without HiDPI, after wakeup, get correct resolution**

## Temporarliy fix
- semi sleep that is go sleep mode, then click mouse button, wakeup, display get correct resolution.

## Log
[lilu log.txt](https://github.com/acidanthera/bugtracker/files/6198233/lilu.log.txt)
[opencore-2021-03-24-152158.txt](https://github.com/acidanthera/bugtracker/files/6198348/opencore-2021-03-24-152158.txt)
[bootlog.txt](https://github.com/acidanthera/bugtracker/files/6198380/bootlog.txt)

thanks in advance

**Comment by telepati** [comment]
@Sher1ocks I am not sure this is a bug in WEG or OC but I fixed my Overscan/Underscan problem with this; Just check maybe it will be helped;
https://ishan.co/external-monitor-underscan

**Comment by Andrey1970AppleLife** [comment]
> AAPL,ig-platform-id has 87C00000


You not truly set a framebuffer, 0x87C00000 it is AAPL,ig-platform-id 0000C087
Your CPU is KBL-R. Why you try to use Amber Lake framebuffer 0x87C00000, instead KBL framebuffer 0x59xxxxxx ?

**Comment by Andrey1970AppleLife** [comment]
Don't edit my messages!

**Comment by Sher1ocks** [comment]
> Don't edit my messages!

sorry, my mistake

sorry, i copied "ig-platform-id has 87C00000" from log, you are right for 0000C087.
actually, both 59160000 and 87c00000 has same problem if use HiDPI mode after wake.

i think weg can fix this issue like forceonline. but not sure.

**Comment by Sher1ocks** [comment]
> @Sher1ocks I am not sure this is a bug in WEG or OC but I fixed my Overscan/Underscan problem with this; Just check maybe it will be helped;
> https://ishan.co/external-monitor-underscan
> 
> Note: Read also comments there is an automated script there.

okay i will try.

**Comment by telepati** [comment]
> > @Sher1ocks I am not sure this is a bug in WEG or OC but I fixed my Overscan/Underscan problem with this; Just check maybe it will be helped;
> > https://ishan.co/external-monitor-underscan
> > Note: Read also comments there is an automated script there.
> 
> okay i will try. but my case, my latop internal display underscaled. is it no problem?

No problem. I know the people who have Laptop also using this. Besides you can revert easily. Just backup your .plist before the try.

**Comment by stevezhengshiqi** [comment]
@Sher1ocks It's a common phonomenon for HiDPI on laptop's low resolution monitor. The optimal solution is to enable BIOS 64mb dvmt and delete `framebuffer-fbmem` and `framebuffer-stolenmem`.

**Comment by Sher1ocks** [comment]
> @Sher1ocks I am not sure this is a bug in WEG or OC but I fixed my Overscan/Underscan problem with this; Just check maybe it will be helped;
> https://ishan.co/external-monitor-underscan
> 
> Note: Read also comments there is an automated script there.

how can i edit it in big sur?



> @Sher1ocks It's a common phonomenon for HiDPI on laptop's low resolution monitor. The optimal solution is to enable BIOS 64mb dvmt and delete `framebuffer-fbmem` and `framebuffer-stolenmem`. It's not related to WhateverGreen or OpenCore, just a framebuffer restriction on the Apple side.

my laptop can't change dvmt value in bios. also my laptop has 2k display, but hidpi 192es 0x1080.
yes, OC and WEG no problem. just improve it, because, after wakeup from semi sleep, i can get normal again.

**Comment by stevezhengshiqi** [comment]
You can change dvmt by editing BIOS firmware. Actually a lot of laptops did that. After unlocking 64dvmt, hidpi is not a problem anymore. With 32 or lower dvmt, small screen with hidpi is a common problem. This problem should be solved by users themselves.

**Comment by telepati** [comment]
@Sher1ocks Before thinking about the implementation, just check the file first. Maybe you don't need this. If in the .plist pscn less than or upper 10000 means that's the problem. If already your pscn 10000 that's mean you don't need this.

**Comment by Sher1ocks** [comment]
> You can change dvmt by checking dvmt offset and editing BIOS firmware. Actually a lot of laptops did that. After unlocking 64dvmt, hidpi is not a problem anymore. With 32 or lower dvmt, small screen with hidpi is a common problem. This problem should be solved by users themselves. Apple expects their devices have 64mb dvmt according to their framebuffer definition.

i know but there is no way in myself. in internet, there is way that SPI Programmer CH341a and SOIC8 connector are needed if you are going to mod your BIOS for optimizations and a better and more native macOS experience.
but i can't do it.

> @Sher1ocks Before thinking about the implementation, just check the file first. Maybe you don't need this. If in the .plist pscn less than or upper 10000 means that's the problem. If already your pscn 10000 that's mean you don't need this.

already 10000?
<img width="763" alt="스크린샷 2021-03-28 오전 1 22 30" src="https://user-images.githubusercontent.com/2107738/112727098-1fec1800-8f64-11eb-8361-8810ffb62a96.png">

more information
  Resolution:	3360 x 1890
  UI Shape:	1680 x 945

  Resolution:	2880 x 1620
  UI Shape:	1440 x 810

1680 x 945 and 1440 x 810 are no problem after wakeup from sleep.
but i want to get more high resolution. seems research

**Comment by Sher1ocks** [comment]
> You can change dvmt by checking dvmt offset and editing BIOS firmware. Actually a lot of laptops did that. After unlocking 64dvmt, hidpi is not a problem anymore. With 32 or lower dvmt, small screen with hidpi is a common problem. This problem should be solved by users themselves. Apple expects their devices have 64mb dvmt according to their framebuffer definition.

long time ago, you wrote this
"
此问题一般出现在16:9的1080p屏幕上。如果系统版本<=10.13.6，可以参考https://github.com/zysuper/rice-cracker (鸣谢@zysuper)，制作一个守护程序，每次唤醒后强制拉伸屏幕来让分辨率正常。

然而在系统版本>=10.14情况下，唤醒后使用上述脚本虽然分辨率正常，但会出现花屏等异常情况。经测试，只能开启1424x802(2848x1604)hidpi，或者更低分辨率hidpi。
"

what is that?
1680 x 945 is good for me, but i want more resolution, i tried 1920x1080. but rare success.
seems to find between 1680x945 and 1920x1080

example
<img width="459" alt="스크린샷 2021-03-28 오전 2 10 59" src="https://user-images.githubusercontent.com/2107738/112728487-dfdc6380-8f6a-11eb-8c9f-d34db9ea3ca1.png">

how can you get 1424x802?
can you suggest some resolution between 1680x945 and 1920x1080?

**Comment by vit9696** [comment]
> zysuper/rice-cracker this script fix for every HiDPI all resolution.
> can we implement this feature in WEG?

I am afraid this is not for WEG, because it works in userspace and is not easily programmable in kernelspace.

**Comment by Sher1ocks** [comment]
okay. i resolved problem. thanks zysuper for idea(https://github.com/zysuper/rice-cracker)
here is fix file. Enjoy :)
now i'm using FHD and more resolution with HiDPI.
[one-key-hidpi-underscaled-fix.zip](https://github.com/acidanthera/bugtracker/files/6291902/one-key-hidpi-underscaled-fix.zip)
