### ISSUE TITLE
VoodooPS2 clickpad buttons not working. 

### ISSUE THREAD

**Issue by mirifi2k** [acidanthera/bugtracker#1579]
Hello, my Lenovo G50-70's trackpad buttons seems that are not working. I've also applied the SSDT-Thinkpad_Clickpad patch, but without luck.
I'll attach the debug messages (dmesg). Let me know if I should upload any debug messages in addition to these, at this point I don't know where I should look to debug this issue.
[voodoops2.txt](https://github.com/acidanthera/bugtracker/files/6217238/voodoops2.txt)

**Comment by 1alessandro1** [comment]
I've experienced a similar issue with older PS2 trackpads separate from the touchpad itself, and as a temporary fix (for an older HP laptop) I managed to get them working with the [original VoodooPS2](https://bitbucket.org/RehabMan/os-x-voodoo-ps2-controller/downloads/RehabMan-Voodoo-2018-1008.zip) could you test if it works for you?

**Comment by mirifi2k** [comment]
Yes, indeed the original VoodooPS2 does work, but gestures are not there unfortunately. :(

**Comment by nsby494** [comment]
system: Fujitsu T732 i5 3320
MacOS: Chameleon Boot 10.14.6 (18G103)
I also have the same problem. When using version 2.2.2, Trackpad working but no buttons. can achieve most of the gesture functions.
Using original VoodooPS2 (RehabMan-Voodoo-2018-1008.zip), two buttons work normally, trackpad can be clicked, two fingers slide up and down, other gestures do not work.

[DSDT.aml.zip](https://github.com/acidanthera/bugtracker/files/6257433/DSDT.aml.zip)
IOReg:[T732-Mac的MacBook Pro.zip](https://github.com/acidanthera/bugtracker/files/6257440/T732-Mac.MacBook.Pro.zip)

**Comment by Gobol** [comment]
HP Probook 450G2 here with Synaptics PS2 Trackpad (2 physical buttons + touchpad) (SYN301E) - same problems as many people, but :

Battery status must be patched.

1. with VoodooPS2Mouse.kext - trackpad works as PS2 Mouse - no scrolling, no Trackpad panel in SysPrefs
2. without VoodooPS2Mouse.kext plugin (deleted from VoodooPS2Controller.kext) - trackpad works as PS2 Trackpad - gestures works fine, but no physical buttons - eg. dragging almost impossible - renders trackpad unusable...

Trying RM's version.

**Comment by woody4165** [comment]
I'm experiencing same issue on an HP 250 G5 with trackpad and two physical buttons. Trackpad is working, the buttons aren't.
If I use the RehabMan-Voodoo-2018-1008  version, all is working fine, but then the sleep/wake does not work anymore, also closing/opening lid.

**Comment by kyeng-vis** [comment]
HP Probook 440G4 here, I also experience similar issue, on latest version shows no trackpad,
the last working version for me is 2.1.6, 
anyone mind to try 2.1.6 or older.

**Comment by Human7900** [comment]
Can confirm.Physical buttons not working on hp prebook 430 g3 also.

**Comment by Human7900** [comment]
If you want any logs tell me.

**Comment by Human7900** [comment]
Any update?

**Comment by MiddlemanTM** [comment]
If it helps, I have managed to enable the buttons and Synaptics trackpad to work fully on my Kaby Lake HP Notebook 17-x105tx using the following fix.

1) Installed SSDT-Thinkpad_Trackpad.aml into ACPI. You'll also need the SSDT-SBUS.aml.
2) Installed latest VoodooI2C.kext, VoodooI2CHID.kext & earlier 2018 version VoodooPS2Controller.kext into Kexts.
I removed VoodooInput from the VoodooPS2Controller.kext package and left Voodoo PS2 keyboard, trackpad & mouse kexts in.

[HP Synaptics trackpad fix.zip](https://github.com/acidanthera/bugtracker/files/6690680/HP.Synaptics.trackpad.fix.zip)

**Comment by andreszerocross** [comment]
> If it helps, I have managed to enable the buttons and Synaptics trackpad to work fully on my Kaby Lake HP Notebook 17-x105tx using the following fix.
> 
> 1. Installed SSDT-Thinkpad_Trackpad.aml into ACPI. You'll also need the SSDT-SBUS.aml.
> 2. Installed latest VoodooI2C.kext, VoodooI2CHID.kext & earlier 2018 version VoodooPS2Controller.kext into Kexts.
>    I removed VoodooInput from the VoodooPS2Controller.kext package and left Voodoo PS2 keyboard, trackpad & mouse kexts in.
> 
> [HP Synaptics trackpad fix.zip](https://github.com/acidanthera/bugtracker/files/6690680/HP.Synaptics.trackpad.fix.zip)

You didn't upload your IOREG Output. People can't know if your Touchpad is I2C or PS2.

Problem above is about VoodooPS2Controller.kext with PS2 Touchpad.

Upload your IOREG Output first

**Comment by MiddlemanTM** [comment]
> > If it helps, I have managed to enable the buttons and Synaptics trackpad to work fully on my Kaby Lake HP Notebook 17-x105tx using the following fix.
> > 
> > 1. Installed SSDT-Thinkpad_Trackpad.aml into ACPI. You'll also need the SSDT-SBUS.aml.
> > 2. Installed latest VoodooI2C.kext, VoodooI2CHID.kext & earlier 2018 version VoodooPS2Controller.kext into Kexts.
> >    I removed VoodooInput from the VoodooPS2Controller.kext package and left Voodoo PS2 keyboard, trackpad & mouse kexts in.
> > 
> > [HP Synaptics trackpad fix.zip](https://github.com/acidanthera/bugtracker/files/6690680/HP.Synaptics.trackpad.fix.zip)
> 
> You didn't upload your IOREG Output. People can't know if your Touchpad is I2C or PS2.
> 
> Problem above is about VoodooPS2Controller.kext with PS2 Touchpad.
> 
> Upload your IOREG Output first

Right. Well no need for the IOREG, I have checked my trackpad is PS2, is marked as PS2 mouse in Windows and yes it is a Synaptics, not Alps or Elan. Trackpad, buttons and keyboard works before logging into macOS logon screen and works with button clicking,  movement and tap clicking also after logging in. Tested in High Sierra 10.13.6.

**Comment by Muhal44** [comment]
I think Rehabman VoodooPS2Controller.kext (1.9.2) will enough. No need VoodooI2C.kext, VoodooI2CHID.kext's. You can find it in this area https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/tree/master/HP-Probook-EliteBook-Package-Creator-OC/Builder/Create-Install-Media/EFIFOLDER/EFI/OC/Kexts

**Comment by Human7900** [comment]
> I think Rehabman VoodooPS2Controller.kext (1.9.2) will enough. No need VoodooI2C.kext, VoodooI2CHID.kext's. You can find it in this area https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/tree/master/HP-Probook-EliteBook-Package-Creator-OC/Builder/Create-Install-Media/EFIFOLDER/EFI/OC/Kexts

Yeah using it the physical buttons work but no gestures :( . Will try @MiddlemanTM  suggestion and report back since mine is also PS2 synaptic.

**Comment by andreszerocross** [comment]
> > > If it helps, I have managed to enable the buttons and Synaptics trackpad to work fully on my Kaby Lake HP Notebook 17-x105tx using the following fix.
> > > 
> > > 1. Installed SSDT-Thinkpad_Trackpad.aml into ACPI. You'll also need the SSDT-SBUS.aml.
> > > 2. Installed latest VoodooI2C.kext, VoodooI2CHID.kext & earlier 2018 version VoodooPS2Controller.kext into Kexts.
> > >    I removed VoodooInput from the VoodooPS2Controller.kext package and left Voodoo PS2 keyboard, trackpad & mouse kexts in.
> > > 
> > > [HP Synaptics trackpad fix.zip](https://github.com/acidanthera/bugtracker/files/6690680/HP.Synaptics.trackpad.fix.zip)
> > 
> > 
> > You didn't upload your IOREG Output. People can't know if your Touchpad is I2C or PS2.
> > Problem above is about VoodooPS2Controller.kext with PS2 Touchpad.
> > Upload your IOREG Output first
> 
> Right. Well no need for the IOREG, I have checked my trackpad is PS2, is marked as PS2 mouse in Windows and yes it is a Synaptics, not Alps or Elan. Trackpad, buttons and keyboard works before logging into macOS logon screen and works with button clicking, movement and tap clicking also after logging in. Tested in High Sierra 10.13.6.

If your touchpad is PS2 Interface then why did you use VoodooI2C.kext and VoodooI2CHID.kext??? This's not correct configuration

**Comment by Muhal44** [comment]
> > I think Rehabman VoodooPS2Controller.kext (1.9.2) will enough. No need VoodooI2C.kext, VoodooI2CHID.kext's. You can find it in this area https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/tree/master/HP-Probook-EliteBook-Package-Creator-OC/Builder/Create-Install-Media/EFIFOLDER/EFI/OC/Kexts
> 
> Yeah using it the physical buttons work but no gestures :( . Will try @MiddlemanTM suggestion and report back since mine is also PS2 synaptics.
> EDIT: With @MiddlemanTM suggestion, trackpad works but no gestures.

Also no need SSDT-Thinkpad_Trackpad.aml and SSDT-SBUS.aml. Rmove them and try again.

**Comment by Fisummer** [comment]
msi gl62m laptop ,same issue ,click button not working

**Comment by TheHackGuy** [comment]
I had the same issue on my laptop (HP notebook x199b)
 The buttons worked fine with the RehabMan voodoops2controller.
 
 And I solved it by using the acidanthera voodoops2controller + voodooRMI + VoodooSMBus
 
 My trackpad is Synaptics SMBus according to windows device manager. But the ACPI patch is some PS2 name.
 
 I will do a couple more tests and let you guys know...

**Comment by NeoBlizzard-verbose** [comment]
Maybe it is time to close this issue, now that it is fixed. (It is fixed, right?)

**Comment by nsby494** [comment]
> Maybe it is time to close this issue, now that it is fixed. (It is fixed, right?)

Yes, it works really well. It's time to close this issue. You guys did a really good job!
