### ISSUE TITLE
OpenCore: Add CPU Info (MSRs) to SysReport

### ISSUE THREAD

**Issue by roddy20** [acidanthera/bugtracker#1580]
saving CPU registers

- [x] MSR_IA32_PERF_STATUS
- [x] MSR_PLATFORM_INFO
- [x] IA_32_MISC_ENABLE
- [x] MSR_IA32_EXT_CONFIG
- [x] MSR_FSB_FREQ
- [x] MSR_TURBO_RATIO_LIMIT

to SysReport will be useful to build SSDT-CPUPm tables

**Comment by roddy20** [comment]
before 0x1C model (Penryn etc)
  MSR_IA_32_MISC_ENABLE;
  MSR_IA32_EXT_CONFIG;
  MSR_FSB_FREQ;
  MSR_IA32_PERF_STATUS;

after (new CPUs)
MSR_PLATFORM_INFO;
MSR_TURBO_RATIO_LIMIT;
MSR_PKG_POWER_INFO (?)

**Comment by roddy20** [comment]
better format will be
MSR_IA32_PERF_STATUS: 0x61A082206000822
with 0x as HEX value
Thanks
@PMheart

**Comment by PMheart** [comment]
Hello @roddy20! Thanks for your suggestion! I will change it. Also, I believe that we should dump MSR status for all cores eventually as well - I will update the code.

**Comment by roddy20** [comment]
> Also, I believe that we should dump MSR status for all cores 
I am not sure is this needed or no
the most important part is
IA32_MISC_ENABLE: 0x4062972489
MSR_IA32_EXT_CONFIG: 0x877D5B00
MSR_FSB_FREQ: 0x804
MSR_IA32_PERF_STATUS: 0x61A082206000822
to build SSDTs for Speedstep 
I think there are the same data for each core
but maybe it will be used later for something else (?)
Thanks

**Comment by PMheart** [comment]
@vit9696 suggested so. The data can be different though, which means a borked implementation. There are also suggestions in [VerifyMsrE2](https://github.com/acidanthera/OpenCorePkg/blob/0bd7dbd5f88aec60cfc3a947237ae6aaf2357895/Application/ControlMsrE2/VerifyMsrE2.c#L75).

**Comment by roddy20** [comment]
it will be difficult to parse long strings with commas
NAME VALUE
will be easier
like this
[MSRStatus.txt.zip](https://github.com/acidanthera/bugtracker/files/6634896/MSRStatus.txt.zip)

**Comment by PMheart** [comment]
> it will be difficult to parse long strings with commas
> NAME VALUE
> will be easier
> like this
> [MSRStatus.txt.zip](https://github.com/acidanthera/bugtracker/files/6634896/MSRStatus.txt.zip)

Sorry for the bad format. I have now changed all to newlines. Please check out GitHub Actions!
