### ISSUE TITLE
OpenCore skips OpenCanopy when chain loaded from RefindPlus

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1581]
The issue is described in details here:
https://github.com/dakanji/RefindPlus/issues/41
[opencore-2021-03-28-200457.txt](https://github.com/acidanthera/bugtracker/files/6217987/opencore-2021-03-28-200457.txt)
[opencore-2021-03-28-195550.txt](https://github.com/acidanthera/bugtracker/files/6217988/opencore-2021-03-28-195550.txt)
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/6217991/config.plist.zip)

**Comment by vit9696** [comment]
Did you press `Enter` to select the OpenCore in `RefindPlus`?

**Comment by startergo** [comment]
No. It times out and continues with the default selection.

**Comment by vit9696** [comment]
Do you press any key during system boot, however?

**Comment by vit9696** [comment]
I see your `config.plist` configured to `Timeout` = 10. Perhaps it is too short? Can you change it to 0?

**Comment by startergo** [comment]
I don't press anything during boot. Changed the timeout to 0 in the OC config.plist and now the system does not boot.

**Comment by vit9696** [comment]
Ok, in this particular situation you do not have updated `OcBinaryData`, however, it should instead show the textual picker. Currently we do not understand why this happens, and request you to make a backup of your EFI folder before you update OcBinaryData. We may contact you later to DEBUG this.

**Comment by startergo** [comment]
I updated already  OC binary data, but it is still the same. Unfortunately I did not back up data. I saw your comment later. And again switched to release version which actually shows the error description, but debug does not.

**Comment by startergo** [comment]
This is how RefindPlus handled Graphics before OC loaded:
```
Initialise Screen...
 15:871   0:015  Check for Graphics:
 15:891   0:020    - Seek Console Control
 15:907   0:015      * Seek on ConsoleOut Handle ...Success
 15:923   0:016    - Assess Console Control ...ok

 15:940   0:016    - Seek Universal Graphics Adapter
 15:955   0:015      * Seek on ConsoleOut Handle ...Unsupported
 15:970   0:015      * Seek on Handle Buffer ...Success
 15:986   0:016      ** Examine Handle[00] ...Success
 15:998   0:011      *** Select Handle[00] @   640 x 480  
 16:013   0:015      ** Examine Handle[01] ...Success
 16:029   0:015      *** Select Handle[01] @  1920 x 1080 
 16:049   0:019    - Assess Universal Graphics Adapter ...ok

 16:065   0:016    - Seek Graphics Output Protocol
 16:081   0:015      * Seek on ConsoleOut Handle ...Success
 16:096   0:014    - Assess Graphics Output Protocol ...ok

 16:112   0:016  Query GOP Modes (Modes=1, FrameBuffer=0x98020000-0x98890000):
 16:127   0:014    - Mode[00] ...Success @  1920 x 1080  ( 1920 Pixels Per Scanned Line, 8bit BGR Pixel Format )

 16:158   0:030  Set Screen Resolution:
 16:179   0:021    - BestMode: GOP Mode[0] @ 1920 x 1080

 16:209   0:029  INFO: Screen Resolution Already Set

 16:224   0:015  INFO: Implement UGA Pass Through ...Success

 16:240   0:015  INFO: Graphics Available:- 'Yes'
```

**Comment by startergo** [comment]
I must add I have 2 screens connected to:
2 DP to DVI on RX-580 to 2 separate screens
1 HDMI connected via HDMI to DVI on one of the screens. The boot screen is on this port on an NVIDIA GTX Titan.

**Comment by vit9696** [comment]
@dakanji I think RefindPlus does something bad here. Here is what happens.

1. OpenCore starts and checks for GOP protocol on ConOut.
2. It discovers GOP protocol on ConOut and it exists with Mode = 0, MaxMode = 1 ([here](https://github.com/acidanthera/OpenCorePkg/blob/5d332ce/Library/OcConsoleLib/ConsoleGop.c#L123-L127)).
3. OpenCore assumes it is valid, and thus uses this this GOP ([here](https://github.com/acidanthera/OpenCorePkg/blob/5d332ce/Library/OcConsoleLib/ConsoleGop.c#L133-L136)).
4. OpenCore then tries to set resolution to max, and discovers that the GOP it found is `Not Started`, i.e. not functioning ([here](https://github.com/acidanthera/OpenCorePkg/blob/69ff426/Library/OcConsoleLib/OcConsoleLib.c#L86-L89)).

For this reason OpenCore simply cannot work as it has no way to draw anywhere. Normally on MacPro5,1 at step 2 it should detect a GOP protocol with Mode = 0, MaxMode = 0, and then decide look for another "real" GOP at step 3. This is not what happens after RefindPlus, however, and I am not sure why. (Here I assume that OpenCore works just fine without RefindPlus).

In theory I can try to workaround it, by trying to `QueryMode` in addition to checking MaxMode == 0 at step 2, but I believe this workaround should not be needed in the first place.

**Comment by dakanji** [comment]
> For this reason OpenCore simply cannot work as it has no way to draw anywhere. Normally on MacPro5,1 at step 2 it should detect a GOP protocol with Mode = 0, MaxMode = 0, and then decide look for another "real" GOP at step 3. This is not what happens after RefindPlus, however, and I am not sure why

Could it be because RefindPlus would have previously done the exact same steps to get bootscreen on a MacPro5,1 by calling OcProvideConsoleGop?

**Comment by vit9696** [comment]
That's what I also suspect, but I do not understand how can it work with `QueryMode` not started to be honest. The thing refuses any kind of rendering and stays black. I wonder if you do something to ConsoleControl, and graphics mode simply does not initialise.

@startergo do you have log with updated OcBinaryData? Also

> Here I assume that OpenCore works just fine without RefindPlus. @startergo, can you confirm and provide us with a log?

**Comment by dakanji** [comment]
> Here I assume that OpenCore works just fine without RefindPlus

Should work since the GOP would not have been 'fixed" but on the other hand, would probably not show boot screen on MacPro5,1.

@startergo ... you mentioned "Text Mode" show where in passing.can you clarify? Do you mean you set RP to Text Mode? if so, how about when you do not set it?

**Comment by startergo** [comment]
> Here I assume that OpenCore works just fine without RefindPlus. @startergo, can you confirm and provide us with a log?

You are correct. It only happens when chain loaded from RP.

**Comment by startergo** [comment]
> @startergo ... you mentioned "Text Mode" somewhere in passing.

No what I meant RP switches to text mode on boot to OC and remains with:
```RefindPlus -Loading OS``` until I see the verbose text from OS being loaded from OC.
I will test now chain loading from rEFInd, but I am pretty sure that worked.

**Comment by startergo** [comment]
rEFInd chain loads OC to OC OpenCanopy. No issues.
[refind.log.zip](https://github.com/acidanthera/bugtracker/files/6218240/refind.log.zip)

**Comment by vit9696** [comment]
It might be that GOP is unavailable till ConsoleControl switches to graphics mode, but I cannot explain why would switching it not work. @startergo may I see logs with the updated OcBinaryData?

**Comment by startergo** [comment]
Here is the debug log attached.
[opencore-2021-03-29-012610.txt.zip](https://github.com/acidanthera/bugtracker/files/6218675/opencore-2021-03-29-012610.txt.zip)

**Comment by vit9696** [comment]
And it showed you absolutely nothing till macOS boot with that log?

**Comment by startergo** [comment]
No it just skipped OpenCanopy. I think you might be missing that this is not the case with the broken GOP. GTX Titan is flashed with EFI vbios.

**Comment by dakanji** [comment]
> GTX Titan is flashed with EFI vbios

That was a blind spot but looking at the RP log, it is actually has a GOP implementation but this seems to be combined with UGA.

From early in the boot:

```
  3:688   3:563  Link Device Handles to Controllers...
  3:752   0:064  Handle 0x006 ...Bypassed [Not Linkable] - Not PCIe Device
  3:788   0:035  Handle 0x007 ...Bypassed [Not Linkable] - Not PCIe Device
  3:826   0:037  Handle 0x008 ...Bypassed [Not Linkable] - Not PCIe Device
  3:862   0:036  Handle 0x009 ...Bypassed [Not Linkable] - Not PCIe Device
  3:903   0:041  Handle 0x036 ...Bypassed [Not Linkable] - Not PCIe Device
  3:940   0:036  Handle 0x037 ...Bypassed [Not Linkable] - Not PCIe Device
  3:976   0:036  Handle 0x038 ...Bypassed [Not Linkable] - Not PCIe Device
  4:013   0:036  Handle 0x039 ...Bypassed [Not Linkable] - Not PCIe Device
  4:048   0:034  Handle 0x03A ...Bypassed [Not Linkable] - Not PCIe Device
  4:126   0:078  Handle 0x043  * Success                 - Not PCIe Device : Leverages GOP
  4:160   0:033  Handle 0x107 ...Skipped [Parent Device] - PCI(00|00:00.0)
  4:202   0:042  Handle 0x108 ...Skipped [Parent Device] - PCI(00|00:01.0)
  4:239   0:037  Handle 0x109 ...Skipped [Parent Device] - PCI(00|01:00.0)
  4:277   0:038  Handle 0x10A ...Skipped [Parent Device] - PCI(00|02:02.0)
  4:315   0:037  Handle 0x10B ...Skipped [Parent Device] - PCI(00|03:00.0)
  4:352   0:037  Handle 0x10C ...Skipped [Parent Device] - PCI(00|02:04.0)
  4:389   0:037  Handle 0x10D ...Skipped [Parent Device] - PCI(00|04:00.0)
  4:427   0:037  Handle 0x10E ...Skipped [Parent Device] - PCI(00|05:01.0)
  4:467   0:040  Handle 0x10F ...Skipped [Parent Device] - PCI(00|06:00.0)
  4:504   0:036  Handle 0x110 ...Skipped [Parent Device] - PCI(00|05:02.0)
  4:542   0:037  Handle 0x111 ...Skipped [Parent Device] - PCI(00|07:00.0)
  4:576   0:034  Handle 0x112 ...Skipped [Parent Device] - PCI(00|00:03.0) : Leverages GOP
  4:613   0:036  Handle 0x113 ...Skipped [Parent Device] - Monitor Display : Leverages GOP
```
GPU with only UGA would not show `Leverages GOP`

Then later:
```
 15:856   0:031  Initialise Screen...
 15:871   0:015  Check for Graphics:
 15:891   0:020    - Seek Console Control
 15:907   0:015      * Seek on ConsoleOut Handle ...Success
 15:923   0:016    - Assess Console Control ...ok

 15:940   0:016    - Seek Universal Graphics Adapter
 15:955   0:015      * Seek on ConsoleOut Handle ...Unsupported
 15:970   0:015      * Seek on Handle Buffer ...Success
 15:986   0:016      ** Examine Handle[00] ...Success
 15:998   0:011      *** Select Handle[00] @   640 x 480  
 16:013   0:015      ** Examine Handle[01] ...Success
 16:029   0:015      *** Select Handle[01] @  1920 x 1080 
 16:049   0:019    - Assess Universal Graphics Adapter ...ok

 16:065   0:016    - Seek Graphics Output Protocol
 16:081   0:015      * Seek on ConsoleOut Handle ...Success
 16:096   0:014    - Assess Graphics Output Protocol ...ok

 16:112   0:016  Query GOP Modes (Modes=1, FrameBuffer=0x98020000-0x98890000):
 16:127   0:014    - Mode[00] ...Success @  1920 x 1080  ( 1920 Pixels Per Scanned Line, 8bit BGR Pixel Format )

 16:158   0:030  Set Screen Resolution:
 16:179   0:021    - BestMode: GOP Mode[0] @ 1920 x 1080

 16:209   0:029  INFO: Screen Resolution Already Set

 16:224   0:015  INFO: Implement UGA Pass Through ...Success

 16:240   0:015  INFO: Graphics Available:- 'Yes'
```
MacPro5,1 would normally show `Assess Graphics Output Protocol ...NOT OK` after which the fix would kick in (it does not in this case).  Also, you see that the UGA check finds in on the GPU.

So it has both GOP and UGA. Once RP detects that GOP, it uses this

Not sure why other loader works, but the issue seems specific to the MacVidsCard GPU.
Please try something like a standard RX580 and/or some other UGA card not from MVC.

The only difference between RP and basic rEFInd I can see would be UGA Pass Thru. You also can try disabling that.

**Comment by vit9696** [comment]
Could you try this version? I will need logs whether it works or not.
[OpenCore-test-r1.zip](https://github.com/acidanthera/bugtracker/files/6219973/OpenCore-test-r1.zip)

The following change is made:
```C
  if (!EFI_ERROR (Status)) {
    DEBUG ((
      DEBUG_INFO,
      "OCC: GOP exists on ConsoleOutHandle and has %u modes, current %u\n",
      OriginalGop->Mode->MaxMode,
      OriginalGop->Mode->Mode
      ));

    //
    // This is not the case on MacPro5,1 with Mac EFI incompatible GPU.
    // Here we need to uninstall ConOut GOP in favour of GPU GOP.
    //
    if (OriginalGop->Mode->MaxMode > 0) {

      if (OriginalGop->Mode->Mode > OriginalGop->Mode->MaxMode) {
        PrevMode = OcConsoleControlSetMode (EfiConsoleControlScreenGraphics);
        DEBUG ((
          DEBUG_INFO,
          "OCC: GOP looks disabled, trying switch to graphics from cc %u, new mode %u\n",
          PrevMode,
          OriginalGop->Mode->Mode
          ));
      }

      mConsoleGraphicsOutput = OriginalGop;
      return EFI_ALREADY_STARTED;
    }

    DEBUG ((
      DEBUG_INFO,
      "OCC: Looking for GOP replacement due to invalid mode count\n"
      ));
```

**Comment by dakanji** [comment]
> OpenCanopy calls textual picker fallback. This is what I concluded from the first message.

I thought he meant he didn't see any boot picker and immediately went to the loading screen. I suppose he can clarify.

> If so, it must be RP that breaks console control

Possibly, at least would know what to look for but if that was the case, it wouldn't just be this GPU right? 
I mean the non MVC RX580 test I asked him for should also be broken. Wouldn't it?

**Comment by vit9696** [comment]
> I thought he meant he didn't see any boot picker and immediately went to the loading screen. I suppose he can clarify.

I think this is not what happens, given that setting Timeout = 0 broke the boot. I believe the picker UI loads, it is just not visible onscreen.

> Possibly, at least would know what to look for but if that was the case, it wouldn't just be this GPU right?
I mean the non MVC RX580 test I asked him for should also be broken. Wouldn't it?

Well, it may be GPU-specific indeed, but the important side is that we need to support both cases, should not we?

**Comment by dakanji** [comment]
> I believe the picker UI loads, it is just not visible onscreen.

Got it

> we need to support both cases, should not we?

Yes. Just need to see whether the issue happens on all processing tracks or just one specific track in order to isolate.

**Comment by startergo** [comment]
> Yes. Just need to see whether the issue happens on all processing tracks

It seems to be happening on EFI vbios only. It works fine on a regular card. I tested with 2 NVIDIA efi vbios cards.

**Comment by startergo** [comment]
> I thought he meant he didn't see any boot picker and immediately went to the loading screen.

Correct.
[opencore-2021-03-29-104437.txt](https://github.com/acidanthera/bugtracker/files/6221164/opencore-2021-03-29-104437.txt)

**Comment by dakanji** [comment]
> Still no OpenCanopy

I guess we need to take this back to RP based on what @vit9696 said about this beforehand.
Can return if needed.

**Comment by vit9696** [comment]
Yes, I think the issue is really on RP side, as it either puts an invalid GOP handle onto `gST->ConsoleOutHandle` or breaks `ConsoleControl`, as it returns invalid screen mode all the time. I tried adding a workaround, but even if it does work, I believe RP should also be fixed:

```C
  if (!EFI_ERROR (Status)) {
    DEBUG ((
      DEBUG_INFO,
      "OCC: GOP exists on ConsoleOutHandle and has %u modes, current %u\n",
      OriginalGop->Mode->MaxMode,
      OriginalGop->Mode->Mode
      ));

    //
    // This is not the case on MacPro5,1 with Mac EFI incompatible GPU.
    // Here we need to uninstall ConOut GOP in favour of GPU GOP.
    //
    if (OriginalGop->Mode->MaxMode > 0) {

      if (OriginalGop->Mode->Mode > OriginalGop->Mode->MaxMode) {
        PrevMode = OcConsoleControlSetMode (EfiConsoleControlScreenGraphics);
        DEBUG ((
          DEBUG_INFO,
          "OCC: GOP looks disabled, trying switch to graphics from cc %u, new mode %u\n",
          PrevMode,
          OriginalGop->Mode->Mode
          ));

        if (PrevMode == EfiConsoleControlScreenGraphics
          || PrevMode == EfiConsoleControlScreenText) {
          mConsoleGraphicsOutput = OriginalGop;
          return EFI_ALREADY_STARTED;
        }
      } else {
        mConsoleGraphicsOutput = OriginalGop;
        return EFI_ALREADY_STARTED;
      }      
    }

    DEBUG ((
      DEBUG_INFO,
      "OCC: Looking for GOP replacement due to invalid mode count\n"
      ));
```

[OpenCore-test-r2.zip](https://github.com/acidanthera/bugtracker/files/6221252/OpenCore-test-r2.zip)

**Comment by startergo** [comment]
Still no go. Even though it says success:
```
01:638 00:026 OCUI: Registered custom GUI protocol
01:665 00:027 OC: Driver OpenCanopy.efi at 6 is successfully loaded!
01:693 00:027 OC: Driver #UgaOnGop.efi at 7 is skipped!
01:720 00:027 OC: Connecting drivers...
02:406 00:686 OC: Connecting drivers done...
02:420 00:013 OCC: Found 3 handles with GOP draw
02:447 00:027 OCC: Found 1 handles with Apple Framebuffer info
02:470 00:023 OCC: AppleFramebufferInfo - Got Base 98020000, Size 8847360, RowBytes 8192, Width 1920, Height 1080, Depth 32
02:494 00:023 OCC: Found 4 handles with UGA for GOP check
02:522 00:028 OCC: Trying handle 0 - 75D33198
02:546 00:024 OCC: Skipping GOP proxying as it is already present on handle 0 - 75D33198
02:573 00:027 OCC: Trying handle 1 - 75A11C18
02:596 00:022 OCC: Skipping GOP proxying as it is already present on handle 1 - 75A11C18
02:619 00:022 OCC: Trying handle 2 - 75D61318
02:649 00:030 OCC: Skipping GOP proxying as it is already present on handle 2 - 75D61318
02:677 00:027 OCC: Trying handle 3 - 759EA198
02:704 00:026 OCC: Skipping GOP proxying as it is already present on handle 3 - 759EA198
02:727 00:023 OCC: GOP exists on ConsoleOutHandle and has 1 modes, current 65535
02:750 00:022 OCC: GOP looks disabled, trying switch to graphics from cc 0, new mode 65535
02:778 00:028 OC: Requested resolution is 0x0@0 (max: 1, force: 0) from Max
02:800 00:022 OCC: Requesting 0x0@0 (max: 1) resolution, curr 65535, total 1
02:827 00:026 OCC: Current FB at 0x0 (0x0), format 3, res 1920x1080 scan 2048
02:853 00:026 OCC: Mode 0 failure - Not started
02:890 00:036 OCC: No compatible mode for 0x0@0 (max: 1) resolution
02:917 00:027 OC: Changed resolution to 0x0@0 (max: 1, force: 0) from Max - Not Found
02:945 00:027 OCC: Found 4 handles with UGA draw
02:967 00:022 OCC: Found 3 handles with GOP for UGA check
02:990 00:022 OCC: Trying handle 0 - 75D61318
03:017 00:027 OCC: Skipping UGA proxying as it is already present on handle 0 - 75D61318
03:041 00:023 OCC: Trying handle 1 - 759EA198
03:067 00:026 OCC: Skipping UGA proxying as it is already present on handle 1 - 759EA198
03:095 00:027 OCC: Trying handle 2 - 75A11C18
03:122 00:027 OCC: Skipping UGA proxying as it is already present on handle 2 - 75A11C18
03:149 00:027 OCC: Using builtin text renderer with 1 scale
03:173 00:023 OCC: Install console control (6E887458/0/0), current - Success
03:194 00:021 OCC: Setup ASCII Output - Success
03:221 00:026 OC: Requested console mode is 0x0 (max: 0) from 
```

**Comment by vit9696** [comment]
What about this one?
[OpenCore-test-r3.zip](https://github.com/acidanthera/bugtracker/files/6221595/OpenCore-test-r3.zip)

```C
  if (!EFI_ERROR (Status)) {
    DEBUG ((
      DEBUG_INFO,
      "OCC: GOP exists on ConsoleOutHandle and has %u modes, current %u\n",
      OriginalGop->Mode->MaxMode,
      OriginalGop->Mode->Mode
      ));

    //
    // This is not the case on MacPro5,1 with Mac EFI incompatible GPU.
    // Here we need to uninstall ConOut GOP in favour of GPU GOP.
    //
    if (OriginalGop->Mode->MaxMode > 0) {

      if (OriginalGop->Mode->Mode >= OriginalGop->Mode->MaxMode) {
        PrevMode = OcConsoleControlSetMode (EfiConsoleControlScreenGraphics);
        DEBUG ((
          DEBUG_INFO,
          "OCC: GOP looks disabled, trying switch to graphics from cc %u, new mode %u\n",
          PrevMode,
          OriginalGop->Mode->Mode
          ));

        if (OriginalGop->Mode->Mode < OriginalGop->Mode->MaxMode) {
          mConsoleGraphicsOutput = OriginalGop;
          return EFI_ALREADY_STARTED;
        }
      } else {
        mConsoleGraphicsOutput = OriginalGop;
        return EFI_ALREADY_STARTED;
      }      
    }

    DEBUG ((
      DEBUG_INFO,
      "OCC: Looking for GOP replacement due to invalid mode count\n"
      ));
```

**Comment by startergo** [comment]
So I had no luck booting a system with latest OC. After that I could not boot even directly from RP. After NVRAM reset tried again chain loading and could not boot to OS. The I tried booting directly OC and it booted. Attached are all log files
[Archive.zip](https://github.com/acidanthera/bugtracker/files/6221851/Archive.zip)

**Comment by vit9696** [comment]
Right, all this looks like some bug in RP. ConsoleOutHandle GOP is borked, and I cannot make it work anyhow from this place. It simply does not render anything onscreen.
