### ISSUE TITLE
OpenCanopy: default cursor position overlaps Selector icon of centered entry

### ISSUE THREAD

**Issue by perez987** [acidanthera/bugtracker#1583]
I really like the current position of the pointer in OpenCanopy, more than in the upper left corner.
But there is a minor cosmetic problem. The mouse pointer overlaps the Selector icon when I select by keyboard the menu entry that is centered on the screen.
Can it be moved down a bit so that both icons don't overlap?
Thank you so much for your work.
Note: opencore-version REL-068-2021-03-30.
![pointer](https://user-images.githubusercontent.com/50429399/113065900-ead90300-91b9-11eb-8506-85a45b7036ea.png)

**Comment by MikeBeaton** [comment]
For info, this is the default Apple cursor position:

![apl](https://user-images.githubusercontent.com/11946605/113112169-ce13ee00-9200-11eb-9143-eb33affc816c.jpeg)

**Comment by perez987** [comment]
I see. It is exactly the same. Okay. It was only a proposal but I see that it is like in the real Macs. Thanks for the info.

**Comment by MikeBeaton** [comment]
I would say it is not _exactly_ the same - but personally I would vote for changing it, if at all, to be just like real Macs - therefore still with an overlap, I'm afraid!

**Comment by perez987** [comment]
I hadn't noticed that little shift to the right on Macs. Yes, it does seem intentional.

**Comment by MikeBeaton** [comment]
@perez987 - FYI & HTH! https://github.com/acidanthera/OpenCorePkg/commit/cdeadd305f9fd73c629b402963282dfc10f74cad

**Comment by MikeBeaton** [comment]
Post update:
![oc](https://user-images.githubusercontent.com/11946605/113177911-f114c100-9245-11eb-8626-1df9ed5a4abc.jpeg)

**Comment by perez987** [comment]
I've seen it right now. They have definitely put the cursor like Apple does. Well commented!
