### ISSUE TITLE
OpenCanopy and builtin UI revampments

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1586]
Currently there are several proposals, which I have collected below for discussion.

**Accepted**:
- [x] OpenCanopy themes should be placed to separate directories instead of prefixes. This way specifying `Modern` would mean opening `Modern/SetDefault.png`. In a way this is already supported as you can specify `Modern/` and achieve the same result, yet `/` is not added automatically and I request it is.
- [x] Pressing and holding CTRL still shows visual feedback even when `AllowSetDefault` is disabled. While this is correct, not making any visual feedback is more intuitive.
- [x] Allow selector to move off left and come on right (and vice versa), as done in at least newer versions of Apple picker.
- [x] Show OpenCore version in OpenCanopy (as well as currently in builtin picker) when corresponding `ExposeSensitiveData` bit is set
- [x] Allow to optionally run without additional Shutdown and Restart buttons.
- [x] Screen rotation support, primarily for vertical screens. On GOP & UGA level, on macOS boot level, and on picker levels with reasonable rendering acceleration. This one should be a config.plist option of course (90, 180, 270 degress).

**Undecided**:

- [ ] There is no concept of defining the properties of the theme. While the user can set the attributes, attributes are rather his preferences, and for the theme we would like to define its properties to define its visual style. I suggest to introduce an optional manifest.plist file that will contain:
    - Text colour in RGB or RGBA format independent from UITheme proto. This might want multiple colours.
    - Background colour independent from UITheme proto.
    - Font name (currently Font, but can become anything).
- [ ] Font size is currently fixed, but now that we support text scrolling we can honestly be less restrictive and allow bigger sizes to an extent.
- [ ] Basic movement animation when moving the selector left and right, particularly when reaching user-invisible area (hidden by the arrows).

**Rejected**:
- There was a report that `|` → `[` switch to highlight the builtin picker reset/shutdown buttons is not easy to spot. While I disagree with this one, I decided to still mention it for completeness reasons.
- Update both pickers so that OpenCore version is always shown in 'show auxiliary' mode (and when the corresponding exposed security bit) is set, but not otherwise

Note: I did not include hotplug as it is a separate issue, and I do not want to discuss it here.

**Comment by MikeBeaton** [comment]
I disagree with 5. too, and I have tried several alternatives - quite possibly, I think, prompted by the person who made the report ;-). But I have found nothing which does not either a) look considerably worse and/or out of style with the builtin picker (which, to be fair, has a style, even if a minimal one), or b) is extremely hard to tell which counts as selected and which as not selected (e.g. I tried `<` -> `|` and `<` -> `[`, both optionally combined with CAPS for selected - none looked as good or worked as well as existing).

**Comment by mhaeuser** [comment]
@MikeBeaton I think I have seen "[[ ]]" before, does it look too awkward?

**Comment by MikeBeaton** [comment]
@mhaeuser I'm not convinced there's a real problem here... I mean, I could try that, but I'm not convinced a change is needed at all.

**Comment by LeeBinder** [comment]
> Font size is currently fixed, but now that we support text scrolling we can honestly be less restrictive and allow bigger sizes to an extent.

superb, thank you @vit9696

May I add:
- displaying OC version and build by pressing a key, e.g. spcebar
- leaving OpenCanopy GUI back into verbose menu by pressing ESC

**Comment by mhaeuser** [comment]
> leaving OpenCanopy GUI back into verbose menu by pressing ESC

@LeeBinder Why?

**Comment by LeeBinder** [comment]
@mhaeuser e.g. when an update introduces a bug and the graphical UI doesn't work correctly

**Comment by mhaeuser** [comment]
@LeeBinder That may happen to any component, including the builtin picker itself, so I think it is better to not introduce such logic. When there is a handled error-condition in OpenCanopy, it in fact falls back to builtin.

**Comment by telepati** [comment]
I still insist on this; Larger spacing, closer to apple original design draft rather than their actual implementation

**Comment by LeeBinder** [comment]
@mhaeuser I did not have a complete error-condition in mind but rather a partial malfunction, giving the user the choice for a manual fallback. Example: the recent cursor bug making it not possible to select a wanted volume icon.

**Comment by mhaeuser** [comment]
@LeeBinder Yes, I know what you mean, and as I said, such bugs may happen with any component and having a bootable backup is expected. This really does not buy anyone much, sorry. I think in the entirety of OpenCore we had one or two regressions in total that ever reached a release version.

**Comment by LeeBinder** [comment]
Ok. "displaying OC version and build by pressing a key, e.g. space-bar" seems a feature more users might find useful.

**Comment by vit9696** [comment]
Added to the first post and stroke out 5 as we preliminarily disagreed on it. Should show the version unconditionally, however, this will match the builtin picker behaviour. Given ExposeSensitiveData bits set.

**Comment by MikeBeaton** [comment]
I'm quite taken with the idea of showing the OC version on a key - it is the sort of thing that you may well want to check occasionally, without it cluttering your screen always. (Would ofc agree that showing it at all must be conditional on the correct ExposeSensitiveData bit being set.)

**Comment by MikeBeaton** [comment]
w/ agreement from Vit and MHaeuser, updated issue list to reflect previous suggestion.

**Comment by dakanji** [comment]
Great stuff on OpenCanopy but please ensure no adverse impact on the text picker when all these stuff is being done.

With v0.6.8, you are stuck with `|Restart| |Shutdown|`with no obvious way to access the two.
It could be that tab works, but this is not intuitive in that context.
Also, there doesn't seem to be an option to hide them when using the text picker.

**Comment by cdf** [comment]
I would like to point out that perhaps the **order** of the shutdown and restart buttons could be made the same as on the modern macOS login screen: shutdown on the left and restart on the right. In fact, that order is not only used on the Big Sur login screen; it is also used on the boot picker of M1 Macs:

<img src="https://user-images.githubusercontent.com/63161650/113709697-cd6fd180-96b0-11eb-9452-f41071a33c9c.png"  alt="Login-Shut-Down-Restart" width="108.5" height="46.5"> <img src="https://user-images.githubusercontent.com/63161650/113707170-816f5d80-96ad-11eb-9110-724c33f08865.png"  alt="Picker-Shut-Down-Restart" width="97.5" height="46.5">

I would also like to add that perhaps including the **labels** "Shut Down" (Note that Apple uses _two words_ for shutdown in English) and "Restart" would be a nice for the sake of consistency. Of course, there is also the question of **localization** for these labels, which, however, also applies to the builtin picker.

**Comment by LeeBinder** [comment]
on  Apr 4, 2021, 9:54 PM GMT+2, @mhaeuser commented:

> @LeeBinder [..] This really does not buy anyone much, sorry. I think in the entirety of OpenCore we had one or two regressions in total that ever reached a release version.

.. so here's # 3, then .. -> https://github.com/acidanthera/bugtracker/issues/1592 ![default_whistle](https://user-images.githubusercontent.com/39203497/113764296-46e7de00-970a-11eb-9d2f-02a2f5881333.gif) ...

**Comment by MikeBeaton** [comment]
@dakanji - If I can just comment - of course without it implying that decisions taken were correct - that i) yes, tab works; ii) there is no way to hide the Shutdown and Restart buttons on the OpenCanopy picker either. The basic idea, ofc, was just to provide the same functionality in both. Therefore Shutdown and Restart buttons, functioning in basically the same way as in Canopy, were added to the Builtin picker.

Almost all of the key handling code is (always was) shared between both builtin and Canopy too - which has the advantage, e.g., that all hotkeys are guaranteed to work the same - and also perhaps explains why tab works to move between picker and shutdown/restart buttons on both, too.

Also (intended as!) improvements in the Builtin picker are:

 - incremental redraw, no more full redraw and major flicker on every keypress
 - new 'set default' indicator (i.e. change '>' to '+' while CTRL is held down) (also added in GUI form to Canopy)
 - from my pov (also as a user): addition of Shutdown and Restart buttons (were also added to Canopy)
 - much improved keyboard responsiveness (applied equally to Canopy and builtin) (improvements here are particularly noticeable on hardware _not_ using KeySupport, including original Macs, but are not zero even on KeySupport hardware)

**Comment by dakanji** [comment]
@MikeBeaton ... thanks for the clarification and yes, a lot of great stuff.
Design decisions are made for several reasons and I suppose there is not always one single "correct" one.

Not being able to hide those two fits with well OpenCanopy as that is also how the Apple Picker works and it does seem that decision may have been made purely on that basis.

BTW, There is a tool available in ResetSystem.efi that gives this functionality resulting in the state of play below:
![PickerOC](https://user-images.githubusercontent.com/1128876/113788822-88967a00-9746-11eb-9c5d-e48d4deb0728.png)

I suppose the team will be considering whether to retire ResetSystem.efi (or remove as a config option if it is what drives those new options) if now redundant as it seems.

I would rather keep it myself and have an option to hide those two if possible. Easier to use ResetSystem.efi in the text picker as it doesn't require changing from up/down keys. Tab is just not the best there and didn't ever occur to me as an option to use to select those two before giving up.

Aware there are various challenges and conscious that at the end of the day, the graphical picker has to take priority for various reasons but would be great if the requirements of the text picker (in its own right) are considered if possible.

Keep up the good work!

**Comment by MikeBeaton** [comment]
@dakanji - I'm honestly not sure that the graphical picker *has* taken priority in the recent updates - however it was intended, but omitted, to make Shutdown and Restart buttons optional and this will be coming your way soon.

**Comment by MikeBeaton** [comment]
@vit9696 might want to comment, but certainly it was indeed recognised that adding the shutdown and restart buttons makes ResetSystem.efi somewhat redundant - e.g. I don't think that it would now be added, if it didn't exist already! - but equally AFAIK I don't think there is any plan to drop it?

**Comment by MikeBeaton** [comment]
PPS For Vit's view with some added lolz see https://dortania.github.io/hackintosh/updates/2021/04/05/acidanthera-april.html ;)

**Comment by vit9696** [comment]
ResetSystem is useful for tests from e.g. Shell. No plans to drop it.

**Comment by dakanji** [comment]
> Shutdown and Restart buttons optional

Lovely. 

Would be yet sweeter if the default setting is not to be shown in the text picker and for them to have to be actively enabled if required (in that context).

**Comment by MikeBeaton** [comment]
> > Shutdown and Restart buttons optional
> 
> Lovely.
> 
> Would be yet sweeter if the default setting is not to be shown in the text picker and for them to have to be actively enabled if required (in that context).

Probably not going to happen that way, sorry. But optional, yes, and ResetSystem continuing to be supported if you like using it, yes.

**Comment by dakanji** [comment]
Any probability of excellence, no matter how slim, is always something to look forward to!

**Comment by MikeBeaton** [comment]
> Any probability of excellence, no matter how slim, is always something to look forward to!

As you say, all design decisions are a compromise. Having a new flag (to enable/disable these extra features) which works differently between builtin and canopy is less than excellent in many ways of looking at it. Also, for someone who _is_ using ResetSystem, I don't think that having the Shutdown and Restart icons in the picker options AND as separate buttons in Canopy, but only in the picker options in builtin, would be that excellent! 🥴

Also - rest assured that any decisions or coding additions made by any - ahem - newer members of the team are being very tightly overseen and supervised by much more senior members - who - along with said newer members - are without doubt VERY keen to maintain the ongoing excellence of the entire project.

**Comment by dakanji** [comment]
The technical excellence of the team, new or old, has never been, and will never be, in question.
In fact, some of the new the new kids are real prodigies.

Excellence in terms of UX elements is a bit like Marmite. While many vehemently hate it, a surprising number of people actually love the damn thing. 

So, the amazingly skilled chefs cooking up wondrous treats should try not to discount adding it to their lovely exotic tarts and sweetmeats ... especially when it is not one, that lovely sweet one with all the trimmings, sitting as the centre piece of the gorgeous buffet. ;)

**Comment by dakanji** [comment]
There is a disconcerting flash of text or some sort of symbol when booting with the builtin picker. It is literally there for a fraction of a second. Too short to read what it says but long enough to distract.  

After setting things up to capture this, I found it says "Timeout" in one scenario. I presume similar for other scenarios although some look to be more of a symbol (can't be sure).

Perhaps something to limit to the log?

**Comment by vit9696** [comment]
Well, if you do not press anything and then let it boot, it prints `Timeout` and boots. This is helpful in case the boot stalls (due to a bug in the OS bootloader), so that you will at least see that it happened.

**Comment by dakanji** [comment]
I see. Does still seem like a job for the debug log though.
Alternatively, maybe an artificial delay of even 1 sec so that one can actually see what it is?
Currently left wondering "what the hell was that?"

**Comment by MikeBeaton** [comment]
> I'm quite taken with the idea of showing the OC version on a key - it is the sort of thing that you may well want to check occasionally, without it cluttering your screen always. (Would ofc agree that showing it at all must be conditional on the correct ExposeSensitiveData bit being set.)

I changed my own mind about this, and with (tentative) agreement from Vit, we are showing OC version in OpenCanopy always, when the expose security bit is set; i.e. no button to toggle it. This behaviour is the same as the previous behaviour of builtin picker, which has not been changed.

**Comment by cdf** [comment]
Another detail to perhaps consider for OpenCanopy is to have an **icon for CDs**. While admittedly antiquated, CDs do, in fact, have their own icon in Apple's boot picker for current Intel Macs:

<img src="https://user-images.githubusercontent.com/63161650/118117193-4ac9e880-b3b9-11eb-80c9-2a5852771055.png"  alt="CD" width="239" height="147">

**Comment by vit9696** [comment]
Yeah, but most computers have no CD, and you often cannot distinguish them from IDE drives. Will consider, but currently undecided. Closing this issue as all the approved requests are resolved. Will continue tracking others in #1614.

**Comment by LeeBinder** [comment]
@vit9696 commented [on Apr 3, 2021](https://github.com/acidanthera/bugtracker/issues/1586#issue-849638452):

> Font size is currently fixed, but now that we support text scrolling we can honestly be less restrictive and allow bigger sizes to an extent.

Almost a year later, so I feel it's OK to ask: is this really such a huge task? Can you please give us an update on this? Thank you very much.

**Comment by mhaeuser** [comment]
@LeeBinder PRs are open, as always.

**Comment by LeeBinder** [comment]
@mhaeuser for a PR, I would need to know how to code in C, right?

**Comment by mhaeuser** [comment]
@LeeBinder Yes

**Comment by LeeBinder** [comment]
I must be one of those underdog laymen who only learned to spell A and B and missed the rest. So I guess my education must be considered poor and I don't qualify for such a task. Maybe that's why I kindly asked.

**Comment by LeeBinder** [comment]
What's most frustrating is that this worked before:

[OcFontFileGenerator](https://www.insanelymac.com/forum/topic/344251-opencanopy-icons/?do=findComment&comment=2752057) (Mar 01 2021 - Bash script with dpfb and FTNTools to create font images)
[Aug 14 2020](https://www.insanelymac.com/forum/topic/344251-opencanopy-icons/?do=findComment&comment=2734174) - Initial look at OpenCanopy's support for AngelCode BMF
[Feb 28 2021](https://www.insanelymac.com/forum/topic/344251-opencanopy-icons/?do=findComment&comment=2751998) - Revised font files with fixed kerning pairs)

Then with some OpenCanopy "update" that ability was taken - and never restored. "Update" in quotes because even though I only know basics in coding I know the correct term is **regression**. So my kind request after a year is: can you please fix that regression?

**Comment by mhaeuser** [comment]
@LeeBinder I understand subtext, there is no need to keep calling it a "kind request". Your "regression" was the fix of a memory corruption bug which should have never happened in the first place. Font size has no impact on functionality, criticial performance, or security, and will thus be addressed when the schedule allows for it, or someone else steps up and PRs it.

**Comment by LeeBinder** [comment]
At least it's not off the table. I'm sure font size scaling can be re-added without memory corruption because I doubt it depends on it. BTW, with your reasoning there wouldn't be a GUI at all because all that's "needed" is a verbose boot menu. Oh, and who "needs" macOS when we could just run Windows and Linux.

Anyway, thanks to all you devs for OC and coding it in your spare time. I'm not expecting anything but do express some thoughts.

**Comment by mhaeuser** [comment]
@LeeBinder I explained to you why the change was necessary and why it is not a regression. I am not explaining to you why despite my reasoning there is a GUI, the same way I won't ask you why you decide to waste my time rather than acquire the skills to perform this seemingly trivial change. This bugtracker is for _constructive_ conversation and contributions, and we will ensure to keep it that way. This marks the end of this discussion.

**Comment by LeeBinder** [comment]
.
