### ISSUE TITLE
ControlMsrE2.efi only works from UEFI Shell, not from OpenCore menu (0.6.8 build d3be085)

### ISSUE THREAD

**Issue by perez987** [acidanthera/bugtracker#1587]
When I run ControlMsrE2 from its icon in OpenCore menu, I get an error:

`Unable to get arguments - Not Found
Press Any Key
OC: Boot failed - Not Found
OCB: Start Image failed - Not Found`

This happens even if I write an argument into config.plist (unlock, lock, verify or interactive).

But when I run this tool from \EFI\OC\Tools\ ControlMsrE2.efi in UEFI Shell it seems to work fine.

![ControlMsrE2 efi-1](https://user-images.githubusercontent.com/50429399/113483730-3c78da80-94a5-11eb-9acf-d71790cd09f8.jpg)
![ControlMsrE2 efi-2](https://user-images.githubusercontent.com/50429399/113483736-400c6180-94a5-11eb-8091-1ec28afaf32a.png)

**Comment by mhaeuser** [comment]
Please retest with https://github.com/acidanthera/OpenCorePkg/commit/ccedcdc67264ac6f0844575d4815b45e3ef096c8 and provide: 1) config.plist (feel free to strip personalised data) 2) DEBUG log
Please test both with and without arguments, providing an image for each case.

**Comment by perez987** [comment]
**ccedcdc** build works fine. From OC menu and from UEFI Shell.
Do you want me to upload more screenshots and the config.plist file or is it enough to see the problem as solved?
Thanks for your excellent work.

![ControlMsrE2 efi-3](https://user-images.githubusercontent.com/50429399/113487766-2fb2b180-94ba-11eb-83a1-abb3133964c3.png)

**Comment by mhaeuser** [comment]
@perez987 I'm not convinced arguments are correctly recognised for you, please test + provide image.

**Comment by perez987** [comment]
Edited my previous post.

**Comment by 111juini** [comment]
我的OPENCORE菜单栏没有这项。
