### ISSUE TITLE
[MaciASL] Update to the latest iasl before release

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1588]
Current iasl-dev version present in master/Dist is 20210105, while the latest version is currently 20210331. The latest table build could be different too.

@Moorre is usually the one which deals with iasl version, I suggest him to have a look

https://github.com/acpica/acpica/commit/eb423b7d5440472d0d2115cb81b52b1b7c56d95a

**Comment by vit9696** [comment]
Well, we could, but any practical reason?

**Comment by 1alessandro1** [comment]
Nothing grand, but the March 31st release contains the changes from the updated acpi 6.4 spec, if someone encounters any kind of incompatibilities can use the stable version

**Comment by vit9696** [comment]
I think the other thing is that we should recompile iasl with Apple Silicon support.

**Comment by vit9696** [comment]
Implemented in master.
