### ISSUE TITLE
AppleALC cannot detect the codec for ALC887-VD

### ISSUE THREAD

**Issue by AEAEAEAE4343** [acidanthera/bugtracker#1590]
Please consider reading this before closing. I know I'm not supposed to ask for help here, but I've tried literally everything I could think of, and I believe there's something wrong with AppleALC.

While trying to hack Big Sur on my PC
```
MSI A78M-E35 (Linux said ALC887-VD, AudioDxe.efi states ALC888B)
AMD A10-5800K APU
GT 640 2GB
```
I got stuck on fixing audio. When using any layout compatible with ALC887/888B using either alcid=xx or in DeviceProperties in OpenCore's config.plist, the system refuses to boot. Enabling ALC debug and verbose boot I can see seemingly infinite lines stating the following and at a certain point the computer just shuts off completely. 
```
failed to find IOHDACodecVendorID, retrying xxxxx
```
While trying to find help on Reddit I came across someone with a very similar board (MSI AM1I, also ALC887-VD with same Vendor and Device ID's) who had a similar issue. After further debugging we came to the conclusion that our issue is the same. 

I went into the trouble of making a custom layout only to realise mid-way that the tutorial used the ALC887-VD as an example and the layout they created was for the exact chip! Also, I have seen many layouts for ALC887-VD in the ALC887 Info.plist so I don't believe there's no layout for this chip.

The person I met on Reddit also found out something else that might be of value. When having no GPU attached, the errors don't appear. Instead the following is output to the Lilu log:
```
AppleALC       alc: @ (DBG) missing ControllerModInfo for 0 controller
```

My hypothesis is that AppleALC is failing to figure out what chip it is and I was wondering if there's any way to maybe tell it manually, or to possibly fix it more permanently in AppleALC.

Thanks in advance!
-- Leet

Links for reference:
My reddit thread (nothing too important here): 
https://www.reddit.com/r/hackintosh/comments/mgex1q/cant_get_applealc_working_on_big_sur_voodoohda/
The other person's reddit thread (here's where most our conversation is):
https://www.reddit.com/r/hackintosh/comments/mhyvsa/alc_887_audio_problem_on_catalina_with_opencore/

**Comment by vit9696** [comment]
No AMD support, sorry.

**Comment by AEAEAEAE4343** [comment]
I don't understand the difference between an ALC887 on an Intel board or an AMD board. It's the same thing right?

**Comment by vit9696** [comment]
The HDA controller is different, and that results in the difference in the initialisation sequence. In short, it means it is not the same.
