### ISSUE TITLE
OC version in NVRam is outdated

### ISSUE THREAD

**Issue by habovh** [acidanthera/bugtracker#1591]
The OC version stored in Nvram once logged in is wrong.

I first noticed this after updating from 0.6.6 to 0.6.7, the OC version stored in NVRam is wrongly set to `REL-066-2021-02-02`. This leads tools like *Hackintool* to believe the bootloader is outdated.

From terminal, running on OC 0.6.8:
```console
$ nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version
4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version	REL-066-2021-02-02
```

Whereas the version in OpenCanopy is indeed REL-068 (and also I now have the Restart and Shutdown options, as expected since version 0.6.8)

I guess there has been something left out in the newest releases.

**Comment by 82ghost82** [comment]
I think this will be closed; there was an issue that was fixed.
You need to clear nvram, use for example ClearNvram.efi and the issue will go away.
Refer to the forum if you still have issues.

**Comment by habovh** [comment]
@82ghost82 thanks for the tip! Resetting nvram indeed fixed the issue. I'll close myself.
