### ISSUE TITLE
2 BUGS in 0.6.8 release in OpenCanopy: 1. cursor moves 4-5 steps; 2. pointer (trackpad, mouse) dead 

### ISSUE THREAD

**Issue by LeeBinder** [acidanthera/bugtracker#1592]
Thanks to tenacious debugging, narrowed bug # 1 down: it was introduced w/  commit [2d650ef](https://github.com/acidanthera/OpenCorePkg/commit/2d650eff8fb6425057d42e95c9ff89e497af124d)! Cursor movements are back to normal with the previous commit [0445d9b](https://github.com/acidanthera/OpenCorePkg/commit/0445d9b91743a9963bc9fdce00f61fbc9397096a)!

(pointer movement was still working with a younger commit I picked randomly, I think [2e8dbb1](https://github.com/acidanthera/OpenCorePkg/commit/ccedcdc67264ac6f0844575d4815b45e3ef096c8) but don't quote me on that. It was however already dead here with commit [ccedcdc](https://github.com/acidanthera/OpenCorePkg/commit/ccedcdc67264ac6f0844575d4815b45e3ef096c8). So what's important for your devs to know is that the dead pointer bug was introduced later! I ran out of time so could not continue chasing this bug down right now)

Narrowed it down even further: it's enough to just replace 0.6.8 release OpenCore.efi with the one from commit [0445d9b](https://github.com/acidanthera/OpenCorePkg/commit/0445d9b91743a9963bc9fdce00f61fbc9397096a): after restart, both cursor movement and pointer functionality using any of both, TP and mouse, are back with 0.6.8 release with its OpenCanopy.

Needless to say I do not know if the actual bug is in OpenCanopy.efi's or OpenCore.efi's code.

Asus VivoBook S15 - specs see [here](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh#system-specification). Current resources folder from [OcBinaryData/tree/master/Resources](https://github.com/acidanthera/OcBinaryData/tree/master/Resources) + my own background. PickerVariant: Modern.

[OC log with 0.6.8 release + 0445d9b OpenCore efi.txt.zip](https://github.com/acidanthera/bugtracker/files/6266834/OC.log.with.0.6.8.release.%2B.0445d9b.OpenCore.efi.txt.zip)
[OC log with 0.6.8 release.txt.zip](https://github.com/acidanthera/bugtracker/files/6266835/OC.log.with.0.6.8.release.txt.zip)
[config.plist](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/blob/main/OpenCore/OC/config.plist)

Let me know if you need any more logs or info, and how to provide them if wanted, and I'll try my best.

**Comment by Andrey1970AppleLife** [comment]
Your config.plist isn't actual for 0.6.8 release.
Pay attention to sections AppleInput and Input.

**Comment by LeeBinder** [comment]
Thank you @Andrey1970AppleLife! Took values from 0.6.8 sample.plist -> cursor back to 1:1 speed, and pointer working again, too, however very slow. Also I get `Invalid input pointer mode` in boot log, on screen and in file. There is no mention of this error in https://dortania.github.io/docs/latest/Configuration.html, and nothing to be found via Google, either. If you can give me a pointer how to get rid of this error and back to normal pointer speed, I'd be 100% back to being stoked.

**Comment by LeeBinder** [comment]
Error gone with `PointerSupportMode`: ASUS as per SampleCustom.plist. Now all that's left is increasing the pointer speed.

**Comment by Andrey1970AppleLife** [comment]
Updating Docs in progress. https://github.com/acidanthera/OpenCorePkg/commits/ae-docs

**Comment by LeeBinder** [comment]
great. PointerSpeedMul 1 -> 4 is the deal-breaker here.

BTW, I did read everything at https://github.com/acidanthera/OpenCorePkg/releases/tag/0.6.8. An additional "New Requirements" link right there would be extremely helpful.
