### ISSUE TITLE
Pressing Fn key (alone) doesn't work.

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#1593]
Hi !
I am trying to enable/trigger dictation by pressing Fn key twice but my Fn key doesn't seem to get detected when pressed alone. I installed the debug version of VoodooPS2 kext and using the below command to capture key codes :
`log stream | sed -n 's/.*\(ApplePS2Keyboard: sending key\)/\1/p'`
For some reason when i press the Fn key alone it doesn't output anything to console but when i press Fn key along with other function keys it outputs corresponding key codes to console.

Is this a bug ?

Device : Dell XPS 7590

Thanks.

**Comment by vit9696** [comment]
Must be a limitation of your particular keyboard. Nothing to do with it I am afraid.
