### ISSUE TITLE
Intent to implement Sigmatel/IDT STAC9220 in AppleALC

### ISSUE THREAD

**Issue by b-fuze** [acidanthera/bugtracker#1595]
I want to implement Sigmatel/IDT STAC9220 as it's the codec used by VirtualBox's Intel HD audio controller as [seen here](https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Devices/Audio/DevHdaCodec.cpp). I have never dabbled in low-level device drivers before, but I'd like to implement support for it. How difficult is this, and where should I be looking first?

**Comment by vit9696** [comment]
I'd say https://applelife.ru/threads/applehda-zvuk-delaem-resursy-po-dampu-voodoohda.2719529/ is a good start, but it is in Russian. As for English manuals, I am not sure where to link you to. Perhaps @roddy20, @khronokernel, or @dhinakg know.
