### ISSUE TITLE
error with opencanopy and opencore 0.6.8

### ISSUE THREAD

**Issue by Nosis** [acidanthera/bugtracker#1596]
In previous versions, it worked perfectly, but in the most recent version it no longer recognizes the pointer in the OS selection menu, and I can only select between the first OS and the last option which in my case is reset ram, in the animation select each one quickly until reaching one of the two options previously selected. In the text version it only does not recognize the direction keys, to be able to select an OS I must do it using the numerical option

**Comment by Andrey1970AppleLife** [comment]
Synchronize yours config.plist with Sample.plist
