### ISSUE TITLE
After reboot bluetooth not working until switch off/on in settings

### ISSUE THREAD

**Issue by Eldar1163** [acidanthera/bugtracker#1597]
I have DW1560 (vendor 0A5C device 216F). On cold boot bluetooth works perfectly. But after reboot bluetooth not working until switch off/on in settings.

On cold boot:
![coldboot](https://user-images.githubusercontent.com/46320217/114032630-2beda900-9885-11eb-8966-87b9302570f3.jpg)

On restart:
![restart](https://user-images.githubusercontent.com/46320217/114032763-4a53a480-9885-11eb-958a-926ff694e7b1.jpg)

**Comment by vit9696** [comment]
possible, non-apple bt is unstable.
