### ISSUE TITLE
Occasional nvme kernel panic

### ISSUE THREAD

**Issue by brucespang** [acidanthera/bugtracker#1598]
Hi!

I've been running into a kernel panic about 1-3 times per day with the message `nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0x74 VID=0x10ec DID=0x5763` [(full panic here)](https://github.com/acidanthera/bugtracker/files/6280217/panic.txt).

Just before the crash happens, macos starts hanging. Usually an application will start to hang, I'll switch to another application which will work for a few seconds, and then it will also hang. Eventually the whole machine crashes. If I wanted to guess, it seems like a process stops working when it accesses the NVMe drive. Rebooting after these crashes also feels like it takes longer than normal.

I've found one other person who coincidentally has the same motherboard (ASRock Z490M-ITX/ac) [reporting a similar issue](https://www.reddit.com/r/hackintosh/comments/lts93b/nvme_kernel_panic/). I've also tried the suggestions in [this issue](https://github.com/acidanthera/bugtracker/issues/1193), but this did not fix it.

I'm running the latest releases of OpenCore, etc…, and my EFI directory is [here](https://github.com/brucespang/bootloader). Hardware-wise, the nvme drive is an ADATA Swordfish 2 TB M.2-2280.

Here's an opencore log from a recent reboot: [opencore-2021-04-08-162832.txt](https://github.com/acidanthera/bugtracker/files/6280216/opencore-2021-04-08-162832.txt). There seems to be nothing relevant in the system.log around the last crash, and I can't find any kernel panic logs. Happy to include more debugging information if you point me in the right direction, and also would be very happy to help test things however I can.

Thanks!

**Comment by vit9696** [comment]
Basically replace your drive, it is unsupported by macOS drivers.

**Comment by brucespang** [comment]
Thanks!

**Comment by brucespang** [comment]
In case anyone else is running into this issue, using a supported drive (I went with a sabrent rocket) fixed the issue. It also seemed like the drive I had before was dying: when copying data onto the new drive, it would vanish after ~30 minutes from both Windows and Linux. In any case: replace your drive!

**Comment by blodt** [comment]
> In case anyone else is running into this issue, using a supported drive (I went with a sabrent rocket) fixed the issue. It also seemed like the drive I had before was dying: when copying data onto the new drive, it would vanish after ~30 minutes from both Windows and Linux. In any case: replace your drive!

Are you still going along ok?

I had these **exact** issues you describe a month or two back with my Intel 660p 2TB NVMe drive.

What is odd is that I used that drive for over a year with no such issues -- and then suddenly on it came.

So, I swapped out and into a new WD SN750 2TB NVMe in the same machine, did a totally fresh/clean Big Sur 11.4 installation and things were fine again -- for a few weeks.  Just this last week it all started happening again, to the point where the machine basically was unusable as it would lock up and NVMe panic so consistently.

I tried passing the boot flag of forceRenderStandby=0 to no avail.

As for now, I just started over yesterday on a SATA SSD and things are perfect as can be.
I'm sure eventually I'll miss the NVMe speed but for now I'm just happy being snappy and stable.

I don't know how or what to do if I wanted to jump back in with NVMe.

Did I really just choose the wrong NVMe stick two times?
The WD drives seem to be supported (or at least not explicitly a bad choice, no?)

If anyone has any recommendations I'd be so grateful and am **all** ears.
Thank you all!

**Comment by brucespang** [comment]
Replacing the drive fixed things completely for me, and I haven't run into any issues since then. Not sure what you have been running into

**Comment by blodt** [comment]
> Replacing the drive fixed things completely for me, and I haven't run into any issues since then. Not sure what you have been running into

Thanks for reporting back.
I also don't understand what's been the issue.

I'm on a fresh install again (11.4, OC 0.7.1) with all the boot flags and Quirks enabled I can find that seem to help others with these situations.  I'm hopeful, but I sort of dread the whole situation as I fear it will lock up again randomly yet again.

**Comment by blodt** [comment]
I thought I was fixed, but it's back doing it again with increasing frequency after a month or so of no issues..

So frustrating -- I don't know what to do
