### ISSUE TITLE
Fans go 100% speed when shutting down

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1599]
Hi, yesterday I managed to successfully use OpenCore for the HP prodesk 600g1, everything works perfectly except for the DVMT Pre allocated limited to 32MB in the BIOS which prevents me to boot with any resolution higher that 2560x1440, hence I'm not able to get a 4K screen, but that's for another issue (https://github.com/acidanthera/bugtracker/issues/1585)

I also noticed that when restarting the system everything behaves normal, macOS closes all apps and then shuts down the machine without turning off the fans, and the pc boots up normally.

However when pressing "Shut down", fans go 100% speed right after the pc goes off. At first I thought it might be a hardware issue, but this does not happen with Linux or Windows. 

Any ideas why this could happen? I'm on OpenCore 0.6.8 (RELEASE) currently

**Comment by 1alessandro1** [comment]
Update: shutting down from OpenCanopy works fine, fans turn off as expected without going full speed.

**Comment by vit9696** [comment]
Do you have `debug=0x100` in the boot arguments? That would mean if macOS panics, it will not shutdown or reboot. Otherwise I am unsure, could be an ACPI problem, so outside of the scope of OC anyway.
