### ISSUE TITLE
[Possible Feature Request] SysReport - dump LAN card infos

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1601]
Hi there,
on some boards, like Gigabyte, BIOS shows some infos about the LAN card(s) MAC Address.
Especially for fixing iServices, according to what dortania's says [in this guide](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#fixing-rom), it's necessary adding a MAC address (possibly the `en0` one).
Given that this fix must be applied during the post-install phase (you know, mapping usb, adding more kexts for peripherals and so on), can SysReport dump those infos?
Thank you so much for your time and your patience

**Comment by Andrey1970AppleLife** [comment]
It isn't required before installation macOS. You can read MAC аddress from macOS.
In many cases MAC аddress for ROM shall be from Apple.
