### ISSUE TITLE
ocvalidate extra checks

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1603]
There are several more issues still unimplemented inside ocvalidate:

- [x] All the paths relative to OpenCore root must be 128 bytes total including `\0` terminator.
- [x] Minimal kernel version must not be below macOS 10.4 (8) => https://github.com/acidanthera/OpenCorePkg/commit/eb6b52ba9440dbebfed71b829046715250405fb4

**Comment by dakanji** [comment]
> All the paths relative to OpenCore root must be 128 bytes total including \0 terminator.

Could this not give false positives when testing on the regular filesystem (before deploying)?

**Comment by vit9696** [comment]
It is unrelated to filesystem. All config.plist paths resolve to relative paths known before any i/o. These are limited.

**Comment by 1alessandro1** [comment]
I would add the fact that when using `Vault`, the config file must be called `config.plist` and not `Config.plist` otherwise it fails to load the plist

**Comment by vit9696** [comment]
Well, the file passed to ocvalidate can be anything. E.g. we pass Sample.plist to it for testing. I do not think we can add such a check.

**Comment by PMheart** [comment]
Implemented in master.
