### ISSUE TITLE
IntelMausi Internet does not work on Asus Q170S1

### ISSUE THREAD

**Issue by vannadium1788** [acidanthera/bugtracker#1605]
I would like to inform you about a problem with the Internet plant on the ASUS Q170S1 motherboard
I would like to inform you that the Intel I219LM chip

The problem is as follows.
The system does not see Etnernet. There is a constant status in the settings: the cable is disconnected

The system does not see that the cable is connected.

This problem also occurred with other users, on Mojave, Catalina and the latest version.

Used version 1.0.5 of Realsese on 11.2.3, 10.15.7 but no luck.
Also tried the DEBUG version of that logs, but I could not hook them

Please understand this situation

**Comment by vit9696** [comment]
IntelMausi comes without support. You should approach the original repo. Please provide IOReg anyway for reference.

**Comment by vannadium1788** [comment]
[asus q170s1.ioreg.zip](https://github.com/acidanthera/bugtracker/files/6292742/asus.q170s1.ioreg.zip)

**Comment by vannadium1788** [comment]
@vit9696
Are there any shifts? Can you fix the internet?
I understand that there is no support for this kekst (although I do not understand why),
but I really want the developers to fix their bug
