### ISSUE TITLE
disable-gpu flag only working with -v boog flag

### ISSUE THREAD

**Issue by Skymax1986** [acidanthera/bugtracker#1606]
I encountered a potential race condition when disabling a secondary GPU (RX 6800) with the new disable-gpu flag (OpenCore + Kexts updated to latest versions). 

With -v boot flag the GPU is disabled correctly, if -v is removed its not working, using the exact same config/efi other than that. (see attached logs) 

[EFIandLog.zip](https://github.com/acidanthera/bugtracker/files/6294681/EFIandLog.zip)

**Comment by vit9696** [comment]
Invalid ACPI: https://github.com/acidanthera/OpenCorePkg/blob/0.6.8/Docs/Configuration.tex#L1750-L1798.
