### ISSUE TITLE
Consistency: Parameters for ControlMsrE2 like ResetSystem? (or case-insensitive)

### ISSUE THREAD

**Issue by mackonsti** [acidanthera/bugtracker#1608]
Hello team and many thanks for adding _ControlMsrE2_ in the latest release.

Just a possible issue regarding case-sensitivity for the parameters of **ControlMsrE2.efi** tool.

In the OpenCore manual, section 11.3 "Tools and Applications" the parameters for **ResetSystem.efi** accepts parameters that are capitalised e.g. _ColdReset_, _Firmware_, _Shutdown_, _WarmReset_ (I never tried all lower-case to be honest).

This is somewhat contrary in the style for **ControlMsrE2.efi** tool ; the accepted parameters are lower-case `lock`, `unlock` and `interactive` instead. Should it not match the style of other tools like **ResetSystem.efi** ?

In this case e.g. if used inside **config.plist** as a tool entry, could the `Arguments` key _not_ be (and accept) _Lock_, _Unlock_ or _Interactive_ be accepted? Could you possibly consider accepting either case styles or make it case-insensitive for **ControlMsrE2.efi** tool ?

Finally please do add the available parameters for **ControlMsrE2.efi** tool in OpenCore document PDF section 11.3 that are missing, despite mentioning the tool itself at the end of the section.

Many thanks.

**Comment by mhaeuser** [comment]
In my opinion vice-versa. I never realised it was documented this way, but camel-case tool arguments look awkward. But yes, should be consistent.

**Comment by vit9696** [comment]
- Should be lower case in the docs.
- Should take case-insensitive arguments in both tools.
- ControlMsrE2 arguments already are documented, no change needed.

```
  On selected platforms, the \texttt{ControlMsrE2} tool can also change such
  hidden options. Pass desired argument: \texttt{lock}, \texttt{unlock} for
  \texttt{CFG Lock}. Or pass \texttt{interactive} to find and modify other
  hidden options.
```
