### ISSUE TITLE
[SSDT-USBX] vs _DSM XHC Clarifications

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1609]
There are a few ways to specify current limits on USB ports, one of them is using AppleUsbPower compatibility table for Skylake+ (also known as [SSDT-USBX](https://github.com/acidanthera/OpenCorePkg/blob/0f817de50626ca2b29291d713f458035f7e7b210/Docs/AcpiSamples/Source/SSDT-EC-USBX.dsl#L71-L80))

However there are some other properties that can be specified either though SSDT:

![image](https://user-images.githubusercontent.com/46293832/114541069-8a849f80-9c56-11eb-87f0-0aa184f28fe2.png)

Or though `DevicesProperties` converting the HEX values to Little Endian format:

![image](https://user-images.githubusercontent.com/46293832/114540912-5e691e80-9c56-11eb-81c7-719ec16b516d.png)

My doubts on this were:
1. **Does** specifying the properties for the XHC device or via PciRoot(0x0)/Pci(0x14,0x0) - which in the end is the same thing - **have any relevant impact/change on correct USB power management**?
2. Are these two methods doing the same thing?
3. Is SSDT-USBX enough for handling USB port currents or maybe needs some more properties?
4. If the answer for 2. is "SSDT-USBX is enough", why?

Thank you for your time and patience

**Comment by vit9696** [comment]
1. On IOUSBFamily (pre-10.11 if I remember correctly) it does and works correctly. Required to be `AAPL,`-prefixed properties. On IOUSBHostFamily these values are ignored I believe.
2. Using DeviceProperties and `_DSM` is about the same thing as long as you can specify the device path in `DeviceProperties` (for USBX you cannot for instance, since it is not a PCI device) and as long as the device exists in ACPI.
3. Depends on the hardware. For Haswell you must specify the values in the plist of the kext describing ports. For Skylake I experienced mixed results. Most likely you need to specify them in both places to get reliable behaviour. Easiest to check is to try charging an iPad.

**Comment by 1alessandro1** [comment]
Thanks a lot for making this more clear

Also I recently noticed this (AppleACPIEC) from the Kernel ACPI Log:
![image](https://user-images.githubusercontent.com/46293832/114921663-1818e880-9e2b-11eb-82c5-a7e43bbbe54f.png)


Is this USBX related? Why on laptops AppleACPI EC should be loaded and in desktops it does not?

**Comment by vit9696** [comment]
1. Not sure. It think it is about no T1/T2 support.
2. No.
3. I think it is coincidental.

**Comment by 1alessandro1** [comment]
> Depends on the hardware. For Haswell you must specify the values in the plist of the kext describing ports. 

Regarding USB mapping on firmware who have ports described only in the `DSDT`, I successfully managed to map all my ports on a Q85 chipset with a i5 4590 using a _UPC to XUPC hotpach that can be found [here](https://github.com/1alessandro1/HP-Prodesk-600-G1-SFF-macOS/blob/959f8f3eddd00b307c3fa0dc94b62c3b4ac0e11e/EFI/OC/config.plist#L114-L143) and I mapped ports though SSDT [that can be found here](https://github.com/1alessandro1/HP-Prodesk-600-G1-SFF-macOS/blob/main/EFI/OC/ACPI/SSDT-USB.aml) even if it's not Skylake which has a separate SSDT for that

I'd like to know your thoughts on this, since this is going to help me to update the PR [here](https://github.com/dortania/OpenCore-Post-Install/pull/54#discussion_r584148926), where the method I proposed currently relies on skylake and above by dropping the original OEM SSDT (hence the USB table must be separate right now) while if this rename is a viable method, this approach can be used on all firmware, replacing the kext approach which breaks when changing SMBIOS

Thanks for your time

**Comment by 1alessandro1** [comment]
tiny bump, @vit9696  ^

**Comment by vit9696** [comment]
Not sure I have a good opinion on that.
