### ISSUE TITLE
VoodooPS2Controller instant wake when lid open

### ISSUE THREAD

**Issue by TonyC5** [acidanthera/bugtracker#1610]
For tested versions of VoodooPS2Controller 2.2.2 and 2.1.8 and VoodooPS2Controller.kext/Contents/Plugins/VoodooPS2Trackpad.kext enabled, laptop wakes 1-2 seconds after sleeping when lid is open.  If laptop is put to sleep by closing lid, laptop remains asleep.  This issue can be produced with the lid open by allowing the laptop to sleep on its own or by manually Sleeping from the Apple menu.

This issue does not happen if VoodooPS2Trackpad.kext is disabled (other VoodooPS2Controller kexts enabled) (but trackpad does not work)

System Configuration is as follows:

- Laptop: HP Envy x360 15m (Kaby Lake R i5-8250U, UHD620, 12GB DDR4, Synaptics SMBUS trackpad)
- MacOS: Catalina 10.15.7 (19H524)
- Open Core: 0.6.8 Final Release
- VoodooPS2Controller Versions: 2.1.8 and 2.2.2
- Kext Injection Order: VoodooPS2Controller.kext, VoodooPS2Controller.kext/Contents/Plugins/VoodooInput.kext, VoodooPS2Controller.kext/Contents/Plugins/VoodooPS2Keyboard.kext, VoodooPS2Controller.kext/Contents/Plugins/VoodooPS2Mouse.kext, VoodooPS2Controller.kext/Contents/Plugins/VoodooPS2Trackpad.kext
- Instant wake fix (GPRW) is applied and fully tested as working properly

I have reproduced this issue with and without enabling VoodooPS2Mouse.kext in both version 2.1.8 and 2.2.2.

Reverting to Rehabman's VoodooPS2Controller 1.9.2 "fixes" this issue, but with Rehabman's version, the trackpad has issues after repeated sleep/wake cycles.

Changing Synaptics > WakeDelay (in VoodooPS2Trackpad.kext/Contents/Info.plist) does not change this instant wake issue (but it does change the delay after which both the trackpad and USB mouse are available after wake).

**Comment by vit9696** [comment]
This sounds like an ACPI issue, but I don't know much. CC @usr-sse2 @Goshin @lvs1974 @khronokernel @dhinakg

**Comment by TonyC5** [comment]
@vit9696 Did you intend to close this?

**Comment by TonyC5** [comment]
@vit9696 I have carefully reviewed my ACPI patches and have thoroughly tested patch variations.  Regardless of what I do, the instant wake behavior remains when VoodooPS2TrackPad.kext is enabled.  All other tested functions work well and sleep/wake works well as long as VoodooPS2Trackpad.kext is not enabled (not an option since I need the trackpad).

To summarize with VoodooPS2Trackpad.kext enabled...
- If laptop sleeps while lid is open (sleeps on idle or sleeps when invoked by Sleep under Apple menu), laptop wakes after a 1-2 seconds
- if I close the lid, laptop sleeps and remains asleep (laptop wakes normally when I open the lid)

If I disable VoodooPS2Trackpad.kext, laptop sleeps / wakes normally under all conditions, but trackpad does not work.

**Comment by TonyC5** [comment]
@vit9696 I have confirmed that this instant wake problem (on my HP Envy x360 15m Kaby Lake R) was introduced in VoodooPS2Controller.kext v2.0.3.  I can use v2.0.2 without the instant wake problem.  According to your change log, the following changes were made between v2.0.2 and v2.0.3:

- Use touchpad sleep mode during mainboard sleep
- Improve physical and trackpad button support

**Comment by vit9696** [comment]
Find the offending commit.

**Comment by TonyC5** [comment]
The diffs are [here](https://github.com/acidanthera/VoodooPS2/compare/2.0.2...2.0.3).  Should be simple to find.  I am trying to build VoodooPS2 2.1.2 but XCode can't find VoodooInputEvent.h.  I'll try to build again when I have more time to look for the missing headers.  I will start by commenting out the changes in ApplePS2SynapticsTouchPad::setDevicePowerState.

**Comment by vit9696** [comment]
Well, you can try reverting the changes in https://github.com/acidanthera/VoodooPS2/commit/85b9a8d5058e26529d10a5c80f76c7f666b8fd14 against the current version.

**Comment by TonyC5** [comment]
Not sure what I was thinking by trying to build 2.1.2 when 2.0.3 would do just fine.  I have confirmed that if I revert the changes in 2.0.3's ApplePS2SynapticsTouchPad::setDevicePowerState that my laptop sleeps without the instant wake problem.

**Comment by TonyC5** [comment]
@vit9696 For my laptop, these are the "offending" lines of code in 2.0.3's ApplePS2SynapticsTouchPad::setDevicePowerState
`           _touchPadModeByte |= 1 << 3;
            setModeByte(_touchPadModeByte); // Enable sleep`

If I comment out these two lines, my laptop sleeps fine without the instant wake.

**Comment by vit9696** [comment]
This change was introduced to reduce the power consumption in S3. I believe we should make this configurable. Can you submit a patch introducing a new SSDT option that will optionally disable this code (e.g. `disable-touchpad-sleep`)?

**Comment by TonyC5** [comment]
I'm not sure I understand your request.  What specifically do you want me to submit and to where should I submit?

**Comment by vit9696** [comment]
Pushed to master already. Please report whether explicitly disabling it with e.g. an SSDT works.

**Comment by TonyC5** [comment]
Ok - I'll look into this when I get some time.  In the mean time, I have rebuilt v2.2.2 with my same code change to ApplePS2SynapticsTouchPad::setDevicePowerState and sleep / wake works fine.

**Comment by TonyC5** [comment]
@vit9696 My "PS2K" and "PS2M" ACPI device paths are _SB.PCI0.LPCB.EC0.KBD0 and _SB.PCI0.LPCB.PS2M respectively.  I tried SSDT patches that defined Name (_SB.PCI0.LPCB.EC0.KBD0.RMCF) and Name (_SB.PCI0.LPCB.PS2M.RMCF).  Neither patch worked for me.  I looked at your modifications in the code and they are exactly what I'm running with in my modified v2.2.2 (I hard-coded my changes without the DeepSleep condition), so I know those changes work.  I am not renaming EC0 (I inject a Fake EC) for this test, so I'm certain of the ACPI paths.

`
DefinitionBlock ("", "SSDT", 2, "ACDT", "ps2", 0x00000000)
{
    External (_SB_.PCI0.LPCB.EC0_.KBD0, DeviceObj)

    Name (_SB.PCI0.LPCB.EC0.KBD0.RMCF, Package (0x02)
    {
        "Synaptics TouchPad", 
        Package (0x02)
        {
            "DisableDeepSleep", 
            ">y"
        }, 
    })
}
`

`
DefinitionBlock ("", "SSDT", 2, "ACDT", "ps2", 0x00000000)
{
    External (_SB_.PCI0.LPCB.PS2M, DeviceObj)

    Name (_SB.PCI0.LPCB.PS2M.RMCF, Package (0x02)
    {
        "Synaptics TouchPad", 
        Package (0x02)
        {
            "DisableDeepSleep", 
            ">y"
        }, 
    })
}
`

**Comment by TonyC5** [comment]
@vit9696 I read various docs on Synaptics Touchpad and believe that there might be a capSleep capability bit that indicates whether the Synaptics Touchpad is capable of DeepSleep.  While retaining the new SSDT DeepSleep configuration, it might be helpful to have ApplePS2SynapticsTouchPad::setDevicePowerState check the capSleep bit before attempting to enable DeepSleep.

Thanks again for this fix.  It continues to work well on my rig.
