### ISSUE TITLE
Legacy boot - OC 0.6.8 - it does not keep the boot order

### ISSUE THREAD

**Issue by Terminalstrip** [acidanthera/bugtracker#1612]
No way to set Macintosh HD as default boot option. 
I select it from System Preferences, restart = does not work
I select it from System Preferences, I turn off = does not work

I have emulated NVRAM, Legacy Bios HEDT S5520HC + 2 Xeon e5620
[opencore-2021-04-14-100040.txt](https://github.com/acidanthera/bugtracker/files/6310161/opencore-2021-04-14-100040.txt)
[Archivio.zip](https://github.com/acidanthera/bugtracker/files/6310165/Archivio.zip)

**Comment by vit9696** [comment]
Scripts are misconfigured I guess. `03:746 00:008 OCB: BootOrder/BootNext are not present or unsupported`.

CC @roddy20

**Comment by Terminalstrip** [comment]
thanx for clarify...i don't how to fix....
I know this is not a forum...please post a documentation to learn on BootOrder/BootNext on legacy system

Completed validating /Volumes/EFI/EFI/OC/Config.plist in 3 ms. No issues found.
terminal@iMac-Pro ~ %

**Comment by roddy20** [comment]
> thanx for clarify...i don't how to fix....
> I know this is not a forum...please post a documentation to learn on BootOrder/BootNext on legacy system
https://github.com/acidanthera/OpenCorePkg/tree/master/Utilities/LogoutHook
/path/to/LogoutHook.command install

**Comment by roddy20** [comment]
does your NVRAM work?
sudo nvram test=test
reboot
nvram test

**Comment by Terminalstrip** [comment]
emulated, but i find a solution from [this](https://www.insanelymac.com/forum/topic/338516-opencore-discussion/page/223/) forum

I've used this file
[LogoutHook.command.zip](https://github.com/acidanthera/bugtracker/files/6320504/LogoutHook.command.zip)

Thanx for help

**Comment by roddy20** [comment]
> I've used this file

Why? it is very old one

**Comment by Terminalstrip** [comment]
yes is a legacy Intel hedt S5520HC like i wrote in the title

**Comment by vit9696** [comment]
Rodion says that the latest OpenCore includes a much more recent version of this code, which works better in several ways.

**Comment by Terminalstrip** [comment]
sure sorry I had read too quickly.  I tried again with the latest version but it doesn't work.  tomorrow I'll do other experiments then I'll update you

**Comment by roddy20** [comment]
> but it doesn't work

what "does not work" more exactly?
run the script, it creates /tmp/nvram.plist and copies it to EFI

**Comment by roddy20** [comment]
try to compare "working" and "not working" files
diff vram1.plist nvram2.plist

**Comment by Terminalstrip** [comment]
Sorry for the delay.
I checked the script of the two commands and it is different.
In fact, if I use the old command I have errors, but the nvram.plist file is created and if I set the boot order from system preferences it works.
If I use the most recent .command the terminal gives me an error and does not create the nvram file.
Look:

OLD COMMAND:

Last login: Sat Apr 17 10:35:23 on ttys000
terminal@iMac-Pro-Terminal ~ % sudo su
Password:
sh-3.2# cd /Users/terminal 
sh-3.2# /Users/terminal/LogoutHook-OLD.command 
File Doesn't Exist, Will Create: ./nvram.plist
nvram: Error getting variable - '8BE4DF61-93CA-11D2-AA0D-00E098032B8C:BootNext': (iokit/common) data was not found
nvram: Error getting variable - '8BE4DF61-93CA-11D2-AA0D-00E098032B8C:Boot0081': (iokit/common) data was not found
nvram: Error getting variable - '8BE4DF61-93CA-11D2-AA0D-00E098032B8C:Boot0082': (iokit/common) data was not found
nvram: Error getting variable - '8BE4DF61-93CA-11D2-AA0D-00E098032B8C:Boot0083': (iokit/common) data was not found
Volume EFI on 81240322-E4F3-4E8D-8060-37594D7133E6 mounted
Volume EFI on disk1s1 unmounted
sh-3.2# 



NEW COMMAND:

Last login: Sat Apr 17 10:35:57 on ttys000
terminal@iMac-Pro-Terminal ~ % sudo su
Password:
sh-3.2# cd /Users/terminal 
sh-3.2# /Users/terminal/LogoutHook-NEW.command 
/Users/terminal/LogoutHook-NEW.command: line 24: abort: command not found
/Users/terminal/LogoutHook-NEW.command: line 33: ./nvramdump: No such file or directory
Fatal error: failed to save nvram.plist!
sh-3.2#

**Comment by vit9696** [comment]
Well, you must put nvramdump utility nearby.

**Comment by roddy20** [comment]
> ./nvramdump: No such file or directory
you did not copy all the files
copy entire LogoutHook folder from OpenCore release, not just a script

**Comment by roddy20** [comment]
[LogoutHook.zip](https://github.com/acidanthera/bugtracker/files/6329430/LogoutHook.zip)
place it to any folder, I use /Users/Shared, and install `./LogoutHook.command install`

**Comment by Terminalstrip** [comment]
you are both really very genius!
Thanks for the support and for what you do.
It worked perfect!

**Comment by roddy20** [comment]
> It worked perfect!

I know )

**Comment by Terminalstrip** [comment]
Now I have a fully working Asus Prime Z390-a system, with only IGFX.
But in my OC log i have too many errors.
I'm not able to find any documentation about this errors, on Dortania i have not found useful info about it.
How to solve?

 

00:000 00:000 AAPL: [EB|#LOG:INIT] 2021-05-17T13:09:38

00:004 00:004 AAPL: [EB|#VERSION] boot.efi 422.140.3~2 (Official), built 2020-06-07T17:22:20-0700

00:009 00:004 AAPL: [EB|#BUILD] BUILD-INFO[298]:{"DisplayName":"boot.efi","DisplayVersion":"422.140.3~2","RecordUuid":"B6FD6584-F0DA-41E8-9542-FAD5E7448407","BuildTime":"2020-06-07T17:22:20-0700","ProjectName":"efiboot","ProductName":"boot.efi","SourceVersion":"422.140.3","BuildVersion":"2","BuildConfiguration":"Release","BuildType":"Official"}

00:016 00:006 AAPL: [EB|#H:IS] 0

00:022 00:005 AAPL: [EB|#WL:MODE] 0

00:028 00:006 AAPL: [EB|#CONFIG:SRC] <default>

00:034 00:006 AAPL: [EB|#CONFIG| 0] boot-save-log : 0x0000000000000002 (0x0000000000000002 < 0xFFFFFFFFFFFFFFFF) <default>

00:041 00:007 AAPL: [EB|#CONFIG| 1] wake-save-log : 0x0000000000000002 (0x0000000000000002 < 0x0000000000000002) <default>

00:049 00:007 AAPL: [EB|#CONFIG| 2] console       : 0x0000000000000001 (0x0000000000000001 < 0x0000000000000001) <default>

00:056 00:007 AAPL: [EB|#CONFIG| 3] serial        : 0x0000000000000000 (0x0000000000000000 < 0x0000000000000000) <default>

00:065 00:008 AAPL: [EB|#CONFIG| 4] embed-log-dt  : 0x0000000000000000 (0x0000000000000000 < 0x0000000000000000) <default>

00:073 00:008 AAPL: [EB|#CONFIG| 5] timestamps    : 0x0000000000000000 (0x0000000000000000 < 0xFFFFFFFFFFFFFFFF) <default>

00:083 00:009 AAPL: [EB|#CONFIG| 6] log-level     : 0x0000000000000001 (0x0000000000000001 & 0x0000000000000001) <default>

00:092 00:009 AAPL: [EB|#CONFIG| 7] breakpoint    : 0x0000000000000000 (0x0000000000000000 & 0x0000000000000000) <default>

00:103 00:010 AAPL: [EB|#CONFIG| 8] kc-read-size  : 0x0000000000100000 (0x0000000000100000 < 0xFFFFFFFFFFFFFFFF) <default>

00:113 00:010 AAPL: [EB|#H:IS] 0

00:124 00:010 AAPL: [EB|#WL|0] 0x01 0x01   0 0x00

00:139 00:015 AAPL: [EB|#BRD:NV] Mac-AA95B1DDAB278B95

00:150 00:010 AAPL: [EB|#WL|1] 0x01 0x01   2 0x00

00:161 00:010 AAPL: [EB|`BST:IDT] {

00:172 00:011 AAPL: [EB|`BST:IDT] }

00:183 00:011 AAPL: [EB|#WL|2] 0x01 0x01   3 0x00

00:194 00:011 AAPL: [EB|#WL|3] 0x01 0x01   4 0x00

00:206 00:011 AAPL: [EB|#BRD:NV] Mac-AA95B1DDAB278B95

00:217 00:011 AAPL: [EB|#WL|4] 0x01 0x01   5 0x00

00:229 00:011 AAPL: [EB|`H:CHK] BM: 0x0000000000000000

00:241 00:012 AAPL: [EB|`H:CHK] Err(0xE) @ GV boot-signature

00:253 00:012 AAPL: [EB|#WL|5] 0x01 0x01  23 0x0E

00:266 00:012 AAPL: [EB|`H:CPM] Err(0xE), (24, 24) @ GV Persistent-memory-note

00:279 00:013 AAPL: [EB|#SB:P] 0x0

00:292 00:012 AAPL: [EB|#LIMG:DP] Acpi(PNP0A03,0)/Pci(1D|0)/Pci(0|0)/?[ 0x83 0x17 0x10 0x0 0x1 0x0 0x0 0x0 0x0 0x1B 0x44 0x4A 0x46 0x76 0x36 0x6B ]/HD(Part2,Sig1C847B02-A8B6-4539-8777-625B17813684)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842)

00:306 00:014 AAPL: [EB|#LIMG:FP] \975FDB2B-1043-498F-8EC2-70737D521EFD\System\Library\CoreServices\boot.efi

00:320 00:014 AAPL: [EB|#LIMG:OPT] ()

00:335 00:014 AAPL: [EB|`OPT:LXF] 'LF (\\975FDB2B-1043-498F-8EC2-70737D521EFD\\System\\Library\\CoreServices\\com.apple.Boot.plist)

00:349 00:014 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: \\975FDB2B-1043-498F-8EC2-70737D521EFD\\System\\Library\\CoreServices\\com.apple.Boot.plist, DP: 0

00:365 00:015 AAPL: [EB|`LD:OFS] Err(0xE) @ OPEN (\\975FDB2B-1043-498F-8EC2-70737D521EFD\\System\\Library\\CoreServices\\com.apple.Boot.plist)

00:381 00:016 AAPL: [EB|`OPT:LXF] Err(0xE) @ 'LF

00:397 00:015 AAPL: [EB|`OPT:LXF] 'LF (Library\\Preferences\\SystemConfiguration\\com.apple.Boot.plist)

00:413 00:016 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: Library\\Preferences\\SystemConfiguration\\com.apple.Boot.plist, DP: 0

00:431 00:017 AAPL: [EB:#KF] ()

00:447 00:016 AAPL: [EB|#MBA:CL] ()

00:464 00:016 AAPL: [EB|#MBA:NV] (debug=0x100 keepsyms=1 alcid=1 igfxfw=2 igfxonln=1 swd_panic=1)

00:481 00:017 AAPL: [EB|#MBA:KF] ()

00:499 00:017 AAPL: [EB|#MBA:OUT] (debug=0x100 keepsyms=1 alcid=1 igfxfw=2 igfxonln=1 swd_panic=1)

00:516 00:017 AAPL: [EB|#OPT:BM] 0x84180

00:534 00:017 AAPL: [EB|`OPT:LXF] 'LF (\\975FDB2B-1043-498F-8EC2-70737D521EFD\\System\\Library\\CoreServices\\PlatformSupport.plist)

00:553 00:018 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: \\975FDB2B-1043-498F-8EC2-70737D521EFD\\System\\Library\\CoreServices\\PlatformSupport.plist, DP: 0

00:572 00:019 AAPL: [EB|#B:VAw]

00:592 00:019 AAPL: [EB|#P:CPR] N

00:611 00:019 AAPL: [EB|#P:MPI] N

00:630 00:019 AAPL: [EB|#P:BPI] N

03:204 02:574 AAPL: [EB|`CS:CSKSD] {

03:223 00:019 AAPL: [EB|`CS:CSKSD] Err(0xE) @ GV 8D63D4FE-BD3C-4AAD-881D-86FD974BC1DF:boot-info-payload

03:243 00:019 AAPL: [EB|#WL|6] 0x01 0x01   6 0x0E

03:263 00:019 AAPL: [EB|`CS:LFC] {

03:283 00:019 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: System\\Library\\Caches\\com.apple.corestorage\\EncryptedRoot.plist.wipekey, DP: 0

03:305 00:021 AAPL: [EB|`FS:AGSVH] Err(0xE) @ LocHB 59D76AE4-37E3-55A7-B460-EF13D46E6020

03:326 00:021 AAPL: [EB|`G:CS] } Ok(0)

03:387 00:061 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: <null string>, DP: 1

03:409 00:021 AAPL: [EB|`B:SBS] SZ: 621112

03:434 00:025 AAPL: [EB|#B:SHA] f4031e1840ae80899574cd5a1feedc6b106d0f87

03:456 00:021 AAPL: [EB|`WL:PWLFNV] Err(0xE) @ GV wake-failure

03:477 00:021 AAPL: [EB|`WL:DT] Err(0xE) @ WL:PWLFNV

03:499 00:021 AAPL: [EB|`WL:PWLFRTC] ! @ RTC:R

03:521 00:021 AAPL: [EB|`WL:DT] Err(0xE) @ WL:PWLFRTC

03:543 00:022 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.0

03:565 00:022 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.1

03:587 00:022 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.2

03:610 00:022 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.3

03:633 00:022 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.4

03:656 00:022 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.5

03:679 00:022 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.6

03:702 00:023 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.7

03:725 00:023 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.8

03:749 00:023 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.9

03:772 00:023 AAPL: [EB|`LD:LKC] BPDK -> (System\Library\PrelinkedKernels\prelinkedkernel.development)

03:799 00:026 AAPL: [EB|`LD:OFS] Err(0xE) @ OPEN (System\\Library\\PrelinkedKernels\\prelinkedkernel.development)

03:824 00:024 AAPL: [EB|`LD:LKC] BPDK,!R -> (System\Library\PrelinkedKernels\prelinkedkernel)

05:223 01:399 AAPL: [EB|`LD:LKFS] } Ok(0)

05:248 00:025 AAPL: [EB|`LD:LKC] } Ok(0)

05:275 00:026 AAPL: [EB|#FWFM] 0xFFDFFF7F

05:300 00:025 AAPL: [EB|#FWFT] 0xFD8FF576

07:886 02:585 AAPL: [EB|#CSR:IN] 0x00000677

07:912 00:025 AAPL: [EB|#CSR:OUT] 0x00000667

07:937 00:025 AAPL: [EB|`BST:FBS] {

07:964 00:026 AAPL: [EB|`BST:FBS] BA.ADSZ: 0

07:990 00:026 AAPL: [EB|`BST:FBS] BA.KSDSZ: 0

08:016 00:026 AAPL: [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49

08:043 00:026 AAPL: [EB|#LOG:DT] 2021-05-17T13:09:46

08:070 00:026 AAPL: [EB|#LOG:EXITBS:START] 2021-05-17T13:09:46

**Comment by MikeBeaton** [comment]
If you just don't want the Apple log output in your OC log, you can set `AppleDebug` to false in config.plist.
