### ISSUE TITLE
[SSDT-PLUG] Clarifications and discussion

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1613]
Hi there, I opened this issue since [SSDT-PLUG](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/Source/SSDT-PLUG.dsl) is part of OpenCorePkg.
I have a simple question: why does`Method (PMPM)` contains a if statements, which returns `0x03` if `Arg2` value is `Zero`?
I'm talking about [L24-L26](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/Source/SSDT-PLUG.dsl#L24-L26).

From what I always read online, in order to enable X86PlatformPlugin and therefore having a correct power management, the only requirement is returning `plugin-type, One` as a `Package` type. (see lines [L28-L33](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/Source/SSDT-PLUG.dsl#L28-L33)).

Is there any practical reason why [L24-L26](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/Source/SSDT-PLUG.dsl#L24-L26) statement is needed? Eventually, can you give us some examples? And if not, shouldn't those lines be removed from SSDT-PLUG sample?

Just for test purposes, I made the following tests:
1. boot with standard SSDT-PLUG ======> `X86PlatformPlugin` is loaded
2. booting with a slightly modified SSDT-PLUG =====> `X86PlatformPlugin` is not loaded

Here you are two zip files each one containing the used SSDT-PLUG, the IORegistryExplorer PR00 screenshot and the kernel log.

- [TEST 1 standard_plug.zip](https://github.com/acidanthera/bugtracker/files/6331157/standard_plug.zip)
- [TEST 2 non_standard_plug.zip](https://github.com/acidanthera/bugtracker/files/6331158/non_standard_plug.zip)

Please note that I'm not an ACPI developer but I found some inconsistencies between the used SSDTs and the final result.
Let me be more clear with the above standard SSDT-PLUG snippet I took from Corpnewt's SSDTTime:

![image](https://user-images.githubusercontent.com/17933708/115144279-23972a00-a04c-11eb-8449-367af097c45c.png)

If `Arg2` is equal to `Zero` (aka false), the if statement is executed and returns a `Buffer` object type of `0x01` size containing `0x03`, otherwise it returns a `Package` object type  of `0x02` size containing `plugin-type` stuff.

Given what I wrote, why the heck, if I remove the if-statement, `X86PlatformPlugin` doesn't load at all?

Just for reference I'm on the following testing environment:

- Laptop: [Dell Inspiron 5370](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/)
- iasl version: `20200528`
- MaciASL version: 1.6.0 (april release)

Thank you so much for your great effort and have a nice sunday ^^

**Comment by vit9696** [comment]
Check `_DSM` description in [ACPI spec](https://uefi.org/specs/ACPI/6.4/09_ACPI-Defined_Devices_and_Device-Specific_Objects/ACPIdefined_Devices_and_DeviceSpecificObjects.html#dsm-device-specific-method):
> Arg2 - An Integer containing the Function Index
> Arg2: Function Index - Represents a specific function whose meaning is specific to the UUID and Revi- sion ID. Function indices should start with 1. Function number zero is a query function (see the special return code defined below).

This is part of `AppleACPIPlatform`, which comes from `DGTP` I believe. We do not know the particular meaning for that, but it is how Apple requires us to handle properties from ACPI.

**Comment by dreamwhite** [comment]
> Check `_DSM` description in [ACPI spec](https://uefi.org/specs/ACPI/6.4/09_ACPI-Defined_Devices_and_Device-Specific_Objects/ACPIdefined_Devices_and_DeviceSpecificObjects.html#dsm-device-specific-method):
> 
> > Arg2 - An Integer containing the Function Index
> > Arg2: Function Index - Represents a specific function whose meaning is specific to the UUID and Revi- sion ID. Function indices should start with 1. Function number zero is a query function (see the special return code defined below).
> 
> This is part of `AppleACPIPlatform`, which comes from `DGTP` I believe. We do not know the particular meaning for that, but it is how Apple requires us to handle properties from ACPI.

Uhm alright. I still don't get why, if a `if-statement` isn't executed at all (y'all know that everything that comes after a return statement is skipped), is still required to return other stuff that isn't even written in the if statement. In the mind of nowadays developing languages this doesn't make sense at all 😅.
Anyways, I don't care much about this weird behaviour of AppleACPIPlatform, but I wanna thank you so much for helping me trying to clarify this doubt :)
Thank you so much and have a nice day
