### ISSUE TITLE
Fn + keys only work once time on Samsung Laptop

### ISSUE THREAD

**Issue by rote66** [acidanthera/bugtracker#1615]
Hi there!
When i use the voodoops2keyboard.kext,The fn + keys only have sending key down but no sending key up.
like this:
![screenshot](https://tva4.sinaimg.cn/large/006lQHKSgy1gpsnk957lwj30nt053jss.jpg)
And only fn + volume key works normally.
How can i fix it?
Thanks.

**Comment by vit9696** [comment]
Sounds like an issue on the keyboard itself, not much we can do. CC @usr-sse2 @zhen-zen @Goshin @1Revenger1.

**Comment by rote66** [comment]
> Sounds like an issue on the keyboard itself, not much we can do. CC @usr-sse2 @zhen-zen @Goshin @1Revenger1.
Thanks.But
The Fn+keys works normally with ApplePS2SmartTouchPad.kext, but this kext nolonger update, and it's gesture not working well in my device.Is any solutions to use voodoops2?

**Comment by whatnameisit** [comment]
Hi. It's most likely that those keys are breakless. Defining them as breakless via SSDT will make them work as any other keys. https://github.com/acidanthera/VoodooPS2/blob/69c29bcf19f629df30a345bc5117c552c3b7f3ed/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp#L263

**Comment by rote66** [comment]
> Hi. It's most likely that those keys are breakless. Defining them as breakless via SSDT will make them work as any other keys. https://github.com/acidanthera/VoodooPS2/blob/69c29bcf19f629df30a345bc5117c552c3b7f3ed/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp#L263

Thanks,I tried it,and it's works now.
