### ISSUE TITLE
[Feature Request] RealPath entry for non-tools

### ISSUE THREAD

**Issue by Gouster4** [acidanthera/bugtracker#1617]
Hi, i would like to use <key>RealPath</key><false/> on my custom entries. 
Like:
<key>Path</key><string>\EFI\ARCH\bootx64.efi</string>
For files inside same partition as OC.

Thanx.

**Comment by vit9696** [comment]
That already happens out of the box.

**Comment by Gouster4** [comment]
Sorry. Didnt noticed. Maybe i did something wrong. My Bad.
