### ISSUE TITLE
[WEG] Support for 6900XT Variant (XTXH/0x73AF)

### ISSUE THREAD

**Issue by MysticalOS** [acidanthera/bugtracker#1618]
The 6900XT until now has been Navi 21 XTX with a device ID of 0x73AE

The april cards that are coming out now are actualy a variant called Navi 21 XTXH with a  device ID of 0x73AF

Apples 11.4 drivers has 0x73AE but not 0x73AF. These 0x73AF cards are still basically 0x73AE but with overclocking thresholds changed and supposedly better golden silicon.

It's unknown whether apple will add 0x73AF or not, but a possible 0x73AF to 0x73AE spoofing solution could potentially work, given that it's still a 6900XT at heart.

I know people at Tonymac are already playing with spoofing solutions but not had much success yet, but those solutions may be missing something, or just may not be low level enough as person testing on one of these 0x73AF cards is still showing 0x73AF despite the 0x73AE spoofs in place. when they look at device in macOS.

I don't know if this is outside of scope of WEG or not, but figure it's at least worth bringing to attention.

**Comment by vit9696** [comment]
Not worth investigating as Apple is writing the drivers at the moment. If basic `device-id` spoofing does not work, it is best to wait till the actual support lands.

**Comment by tomrobak** [comment]
Here is a working solution - [fix for 6900XT 0x73AF](https://www.tonymacx86.com/threads/success-radeon-rx-6800-xt-big-sur.306736/page-127#post-2257608)

**Comment by dahua910** [comment]
> This solution is trash, we implemented our own in [acidanthera/WhateverGreen@9472d77](https://github.com/acidanthera/WhateverGreen/commit/9472d772f885bf83f93a2486a0b74bb5fe0f7996). The only thing needed is to inject a device-id. You optionally need to fix the ACPI devices if they are broken. See https://www.tonymacx86.com/threads/success-radeon-rx-6800-xt-big-sur.306736/page-132#post-2264482.

thanks for that, 

is there any guide / doc how to "inject a device-id"?
plz
