### ISSUE TITLE
XhciPortLimit not work on big sur 11.3

### ISSUE THREAD

**Issue by imotoboy** [acidanthera/bugtracker#1619]
USB interface cannot be used

**Comment by vit9696** [comment]
Use plist-only kext, it is what you always should use, and this is mandatory for Z590 anyway.

**Comment by 1alessandro1** [comment]
@imotoboy you should map usb ports with Xhciportlimit disabled, you will find usbs from e.g. HS01 to SS01 since they're limited to 15. Once you disable the unnecessary ports within that range, you can go on an map the rest from SS01 to SS10 depending on your motherboard

**Comment by imotoboy** [comment]
> @imotoboy you should map usb ports with Xhciportlimit disabled, you will find usbs from e.g. HS01 to SS01 since they're limited to 15. Once you disable the unnecessary ports within that range, you can go on an map the rest from SS01 to SS10 depending on your motherboard

Thank you very much
