### ISSUE TITLE
NVMeFix broken after installing macOS Big Sur 11.3 Update

### ISSUE THREAD

**Issue by siddiqq** [acidanthera/bugtracker#1620]
The Big Sur 11.3 update seems to have broken NVMeFix for me on my MBP 2015 with Samsung Evo 970 Plus... I used to get idle **0.00 A** with both SsdPmEnabler and NVMeFix/Lilu installed on 11.2 . After the update its idle at **0.28 A** .

So I uninstalled all the kexts, then reinstalled SsdPmEnabler first, and it dropped my power consumption from **0.77 to 0.28 A**, which is great news that it still works. But when I install NVMeFix/Lilu, it makes no difference :( 

I remember on 11.2, if I install SsdPmEnabler first , it would do the same and drop from **0.77** to **0.28 A,** and then after installing NVMeFix/Lilu it would drop it even further to **0.00 A**. But its not doing that anymore, even if I install older versions of both NVMeFix and Lilu.

Anyone else experiencing something similar? Not sure why SsdPmEnabler would still work but not NVMeFix. 

Thanks

edit: sorry, I've been trying to figure out how to add the "nvme" label but can't seem to do it

**Comment by vit9696** [comment]
Log with -likudbgall liludump=60. Stored in /var/log/Lilu_x.x.x.txt 60 seconds after boot. Requires DEBUG kexts.

**Comment by siddiqq** [comment]
> Log with -likudbgall liludump=60. Stored in /var/log/Lilu_x.x.x.txt 60 seconds after boot. Requires DEBUG kexts.

thanks for your reply. okay I will install the DEBUG version. Just to clarify the steps, right after I boot I go to terminal and type -likudbgall liludump=60 , then retrieve the log?

**Comment by siddiqq** [comment]
> Log with -likudbgall liludump=60. Stored in /var/log/Lilu_x.x.x.txt 60 seconds after boot. Requires DEBUG kexts.

sorry I'm a bit of a noob with this stuff. did some research, so do I go into recovery mode, open terminal and type nvram boot-arg="-likudbgall liludump=60"  after I install the DEBUG? and then retrieve the log.

please confirm as I'm worried I might brick my Mac haha. thank you!

**Comment by vit9696** [comment]
You need to add it to boot-args.

**Comment by siddiqq** [comment]
> You need to add it to boot-args.

sorry I can't seem to find info on how to add it.

**Comment by telepati** [comment]
> Log with -likudbgall liludump=60. Stored in /var/log/Lilu_x.x.x.txt 60 seconds after boot. Requires DEBUG kexts.

Shouldn't it be "liludbgall"?

**Comment by vit9696** [comment]
Your above post is correct, though I actually made a typo when I typed you the arguments. Should be

`nvram boot-args="-liludbgall liludump=60"`

If you previously added other boot-args, add them here. You can view them by typing `nvram boot-args` in Recovery.

@khronokernel @dhinakg really need to make this instruction globally available

**Comment by siddiqq** [comment]
> Your above post is correct, though I actually made a typo when I typed you the arguments. Should be
> 
> `nvram boot-args="-liludbgall liludump=60"`
> 
> If you previously added other boot-args, add them here. You can view them by typing `nvram boot-args` in Recovery.
> 
> @khronokernel @dhinakg really need to make this instruction globally available

Hi, I finally got it. However when I open the text log all the log says is "Lilu      user: @ disabling user patcher on request!
"  

I only used 2 boot args, first is keepsyms=1, which I need otherwise Lilu/NVMeFix will cause boot loop, and the other args is the one you provided me. 

thank you

**Comment by vit9696** [comment]
That means you have RELEASE versions of the kexts.

**Comment by naveenkrdy** [comment]
@vit9696 
Hi ! can't see the `aspt` or `NVMePMProxy` entry in ioreg after update to 11.3

seems like this is the issue ?
`NVMeFix     nvmef: @ (DBG) Failed to solve symbols`
log:
[Lilu_1.5.2_20.4.txt](https://github.com/acidanthera/bugtracker/files/6394386/Lilu_1.5.2_20.4.txt)
ioreg dump:
[MacBook Pro.zip](https://github.com/acidanthera/bugtracker/files/6394428/MacBook.Pro.zip)

thanks !

**Comment by vit9696** [comment]
Thx, IONVMeFamily.kext itself?

**Comment by naveenkrdy** [comment]
> Thx, IONVMeFamily.kext itself?
Sure ! here you go .
from 11.3
[IONVMeFamily.kext.zip](https://github.com/acidanthera/bugtracker/files/6394648/IONVMeFamily.kext.zip)


Thanks !

**Comment by siddiqq** [comment]
> That means you have RELEASE versions of the kexts.

I thought it might have been because I overwritten the release with the debug versions, so I fully uninstalled Lilu/NVMeFix with cache clear, then reinstalled the DEBUG versions, but its still showing me that same message, even after restarting another 2 times... am checking nvram boot-args and it shows the command you gave me... So it definitely is working.

I have no clue what else now. Does it maybe need change from 60 seconds to 120? Very odd.

**Comment by vit9696** [comment]
@siddiqq well, I got the log thanks to @naveenkrdy, but I do not believe you do things correctly. Perhaps your kexts are installed somehow else as you cannot install them without OpenCore in Big Sur, for example.

**Comment by vit9696** [comment]
Please try https://github.com/acidanthera/NVMeFix/commit/ba44bd9996530cae4ffa3bdeae36f8464236a595. Will land to https://dortania.github.io/builds/?product=NVMeFix&viewall=true soon.

**Comment by naveenkrdy** [comment]
@vit9696 thanks but doesnt seem to fix yet with the above commit.
```
NVMeFix     nvmef: @ (DBG) processKext com.apple.iokit.IONVMeFamily
Lilu      mach: @ (DBG) found symbol __ZN16IONVMeController20IssueIdentifyCommandEP18IOMemoryDescriptorjb at 0xffffff8008aaadee (non-aslr 0xffffff8008aaadee), type f, sect 1, desc 0
Lilu      mach: @ (DBG) found symbol __ZN16IONVMeController22ProcessSyncNVMeRequestEP16AppleNVMeRequest at 0xffffff8008aaafde (non-aslr 0xffffff8008aaafde), type f, sect 1, desc 0
Lilu      mach: @ (DBG) found symbol __ZN16IONVMeController10GetRequestEj at 0xffffff8008aaeea8 (non-aslr 0xffffff8008aaeea8), type f, sect 1, desc 0
Lilu      mach: @ (DBG) found symbol __ZN16AppleNVMeRequest23BuildCommandGetFeaturesEh at 0xffffff8008ab8044 (non-aslr 0xffffff8008ab8044), type f, sect 1, desc 0
Lilu      mach: @ (DBG) found symbol __ZN16AppleNVMeRequest29BuildCommandSetFeaturesCommonEh at 0xffffff8008ab8078 (non-aslr 0xffffff8008ab8078), type f, sect 1, desc 0
Lilu      mach: @ (DBG) found symbol __ZN16IONVMeController13ReturnRequestEP16AppleNVMeRequest at 0xffffff8008aaf074 (non-aslr 0xffffff8008aaf074), type f, sect 1, desc 0
Lilu      mach: @ (DBG) found symbol __ZN16AppleNVMeRequest9GetStatusEv at 0xffffff8008ab6a08 (non-aslr 0xffffff8008ab6a08), type f, sect 1, desc 0
Lilu      mach: @ (DBG) found symbol __ZN16AppleNVMeRequest9GetOpcodeEv at 0xffffff8008ab69ee (non-aslr 0xffffff8008ab69ee), type f, sect 1, desc 0
Lilu      mach: @ (DBG) found symbol __ZN16AppleNVMeRequest20GenerateIOVMSegmentsEyy at 0xffffff8008ab71e0 (non-aslr 0xffffff8008ab71e0), type f, sect 1, desc 0
Lilu      mach: @ (DBG) found symbol __ZN16IONVMeController22FilterInterruptRequestEP28IOFilterInterruptEventSource at 0xffffff8008aad3b8 (non-aslr 0xffffff8008aad3b8), type f, sect 1, desc 0
NVMeFix    disasm: @ (DBG) Offset 0xac for result
NVMeFix    disasm: @ (DBG) Offset 0x10a for command
NVMeFix    disasm: @ (DBG) Failed to find prpDescriptor
NVMeFix    disasm: @ (DBG) Failed to find ANS2MSIWorkaround
Lilu      mach: @ (DBG) found symbol __ZTV16IONVMeController at 0xffffff8008ace640 (non-aslr 0xffffff8008ace640), type f, sect 7, desc 0
NVMeFix     nvmef: @ (DBG) Failed to solve symbols
```
[debug.txt](https://github.com/acidanthera/bugtracker/files/6395631/debug.txt)
[MacBook Pro 2.zip](https://github.com/acidanthera/bugtracker/files/6395632/MacBook.Pro.2.zip)

**Comment by siddiqq** [comment]
> Please try [acidanthera/NVMeFix@ba44bd9]

Hi, I've tried the update but still didn't fix anything :/

My method for installing the kexts is by typing  sudo cp -R ~/Downloads/Lilu.kext /Library/Extensions . This is the same method I did on Big Sur 11.2 and worked perfectly.

I even uninstalled everything, reset the Nvram and SMC, then reinstalled everything but still nothing in the logs and the power consumption not going below 0.28. Maybe Lilu needs an update as well? I'm not sure though.

Thank you for your help

**Comment by naveenkrdy** [comment]
@siddiqq should be done in this way !
```
sudo mount -uw /
sudo cp -Rf ~/Downloads/Some.kext /System/Library/Extensions/
sudo chown -R 0:0 /System/Library/Extensions/
sudo chmod -R 0755 /System/Library/Extensions/
sudo kextcache -i /
sudo kmutil install --update-all
sudo kcditto
```

**Comment by khronokernel** [comment]
@naveenkrdy Those args are partially incorrect, remember that Big Sur is snapshot based. Catalina's commands won't work unless there user has deleted all APFS snapshots and is booting a live filesystem. Otherwise no edits will be done to the root volume. 

Corrected steps for snapshot based installs:

```sh
# Find your System volume
diskutil list

# From the below list, we can see our System volume is disk5s5
/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +255.7 GB   disk5
                                 Physical Store disk4s2
   1:                APFS Volume ⁨Big Sur HD - Data⁩       122.5 GB   disk5s1
   2:                APFS Volume ⁨Preboot⁩                 309.4 MB   disk5s2
   3:                APFS Volume ⁨Recovery⁩                887.8 MB   disk5s3
   4:                APFS Volume ⁨VM⁩                      1.1 MB     disk5s4
   5:                APFS Volume ⁨Big Sur HD⁩              16.2 GB    disk5s5
   6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 16.2 GB    disk5s5s

# Mount the drive(ie. disk5s5)
sudo mount -o nobrowse -t apfs  /dev/disk5s5 /System/Volumes/Update/mnt1

# Remove old kext if present
sudo rm -R /System/Volumes/Update/mnt1/System/Library/Extensions/Example.kext

# Copy over your kext
sudo cp -R ~/Desktop/Example.kext /System/Volumes/Update/mnt1/System/Library/Extensions/

# Fix permissions
sudo chmod -R 755 /System/Volumes/Update/mnt1/System/Library/Extensions/Example.kext
sudo chown -R root:wheel /System/Volumes/Update/mnt1/System/Library/Extensions/Example.kext

# Rebuild kernel cache
sudo kmutil install --volume-root /System/Volumes/Update/mnt1/ --update-all

# Create new bootable snapshot
sudo bless --folder /System/Volumes/Update/mnt1/System/Library/CoreServices --bootefi --create-snapshot
```

**Comment by siddiqq** [comment]
> @siddiqq should be done in this way !
> 
> ```
> sudo mount -uw /
> sudo cp -Rf ~/Downloads/Some.kext /System/Library/Extensions/
> sudo chown -R 0:0 /System/Library/Extensions/
> sudo chmod -R 0755 /System/Library/Extensions/
> sudo kextcache -i /
> sudo kmutil install --update-all
> sudo kcditto
> ```

@naveenkrdy Thank you but I got this method from also installing SsdPmEnabler as described on the GitHub https://github.com/kvic-z/SsdPmEnabler 

Then I just replaced the kext name with Lilu and NVMeFix and it worked perfectly on Big Sur 11.2. Not sure what broke on 11.3, as I said before SsdPmEnabler still works on 11.3, but not NVMeFix. 

Also I am not using a hackintosh so maybe the install method can vary

**Comment by herb2k** [comment]
> > Please try [[acidanthera/NVMeFix@ba44bd9](https://github.com/acidanthera/NVMeFix/commit/ba44bd9)]
> 
> Hi, I've tried the update but still didn't fix anything :/
> 
> My method for installing the kexts is by typing sudo cp -R ~/Downloads/Lilu.kext /Library/Extensions . This is the same method I did on Big Sur 11.2 and worked perfectly.
> 
> I even uninstalled everything, reset the Nvram and SMC, then reinstalled everything but still nothing in the logs and the power consumption not going below 0.28. Maybe Lilu needs an update as well? I'm not sure though.
> 
> Thank you for your help

You will need to build the code which was checked in or wait for a new release build to be published.

**Comment by herb2k** [comment]
> Please try [acidanthera/NVMeFix@ba44bd9](https://github.com/acidanthera/NVMeFix/commit/ba44bd9996530cae4ffa3bdeae36f8464236a595). Will land to https://dortania.github.io/builds/?product=NVMeFix&viewall=true soon.

Grabbed 1.0.7 and no apst entry in IOREG. 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/55064641/116515437-2500f780-a881-11eb-8ec6-37bb3680e57c.png">
<img width="560" alt="image" src="https://user-images.githubusercontent.com/55064641/116515459-2d593280-a881-11eb-910f-bd2be0c3b385.png">
<img width="994" alt="image" src="https://user-images.githubusercontent.com/55064641/116515494-3944f480-a881-11eb-8ccf-034ce94aeaff.png">

**Comment by vit9696** [comment]
I additionally fixed the register encoding in https://github.com/acidanthera/NVMeFix/commit/4ccff54d4d947d6bef3a40e6d52e6ce723906e58. What does SsdPmEnabler do? Can incorporate it in NVMeFix.

**Comment by siddiqq** [comment]
> I additionally fixed the register encoding in [acidanthera/NVMeFix@4ccff54](https://github.com/acidanthera/NVMeFix/commit/4ccff54d4d947d6bef3a40e6d52e6ce723906e58). What does SsdPmEnabler do? Can incorporate it in NVMeFix.

Wow you read my mind haha. Was going to ask exactly if you could somehow incorporate them so I can have less kexts loaded. 

According to the SsdPmEnabler GitHub  it "can enable power saving on SSD/PCIe sockets on specific MacBook Air and Pro models manufactured between 2013 and 2015". I'm not sure exactly what this means so maybe you can contact the developer :) https://github.com/kvic-z/SsdPmEnabler

As I said before SsdPmEnabler seems to still be working after the 11.3 update. Am hoping your new build will work too, just wish I could help with getting my debug to work!

Thank you

**Comment by vit9696** [comment]
@siddiqq `-liludbgall` enables DEBUG in all kexts. Including `NVMeFix`.

Can you provide IOReg with and without SsdPmEnabler?

**Comment by siddiqq** [comment]
> @siddiqq `-liludbgall` enables DEBUG in all kexts. Including `NVMeFix`.
> 
> Can you provide IOReg with and without SsdPmEnabler?

Hey yup here you go: 
[IOReg WITHOUT SsdPmenabler.txt](https://github.com/acidanthera/bugtracker/files/6398812/IOReg.WITHOUT.SsdPmenabler.txt)
[IOReg WITH SsdPmEnabler.txt](https://github.com/acidanthera/bugtracker/files/6398813/IOReg.WITH.SsdPmEnabler.txt)

thanks

**Comment by vit9696** [comment]
@siddiqq please use IORegistryExplorer.app. https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip

**Comment by siddiqq** [comment]
> @siddiqq please use IORegistryExplorer.app. https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip

okay I downloaded it, what to do after I open the app? Just click File - Save? Gives me an "IORegistryExplorer Document"

**Comment by vit9696** [comment]
Yeah, correct.

**Comment by siddiqq** [comment]
> Yeah, correct.

here you go :)

[SsdPmEnable IOReg.zip](https://github.com/acidanthera/bugtracker/files/6398942/SsdPmEnable.IOReg.zip)

**Comment by vit9696** [comment]
Ok, that explains everything. I reverse-engineered SsdPmEnabler, and checked what it does. Essentially it forces `SSD0` and its parent bridge (`RP06` in your case) to enable ASPM L1 (0x2). For unknown reasons it also disables L0s if it was on, but so far I found no device with L0s (0x1). Perhaps on some device it was enabled and was unstable or something.

I reviewed a few hackintosh boards and there is no issue on them actually. For instance, if I check my SSD, I see `pci-aspm-default` = 0x2, which essentially is ASPM L1 by default. On yours the value is 0x100, which is ASPM disabled. This means that Macs have a bug in their firmwares or maybe a safety switch due to certain lower-end SSDs not supporting ASPM.

To be honest, there is little reason this in the kext, as you can just add `pci-aspm-default` with `<02 00 00 00>` value as a `DeviceProperty` in OpenCore. I can consider this if you give me reasons, but a simple `DeviceProperty` should be much easier.

@khronokernel I believe you should include this in your OCLP patcher at least in some models. `MacBookPro11,1` and `MacBookAir6,2` are confirmed to not be compatible by `SsdPmEnabler` author, but others hopefully are ok.

Reference code:

```C
kern_return_t __cdecl SsdPmEnabler_start()
{
  IORegistryEntry *pciRoot; // rax MAPDST
  OSIterator *pciIterator; // rax MAPDST
  const OSMetaClass *registryEntryMeta; // r12
  IORegistryEntry *bridgeDevice; // r13 MAPDST
  const char *name; // rbx MAPDST
  int nameWord; // eax
  OSIterator *bridgeIterator; // rbx
  OSObject *tmp; // rax MAPDST
  IORegistryEntry *ssdDevice; // r14 MAPDST
  UInt8 ssdStatus; // r14
  UInt8 bridgeStatus; // al

  IOLog("Copyright (c) 2020-2021 kvic (https://github.com/kvic-z/SsdPmEnabler)");
  pciRoot = IORegistryEntry::fromPath("/PCI0@0", gIODTPlane, 0LL, 0LL, 0LL);
  if ( !pciRoot )
    return 0;
  pciIterator = pciRoot->getChildIterator(pciRoot, gIODTPlane);
  if ( !pciIterator )
    goto RELEASE_ROOT;
  tmp = pciIterator->getNextObject(pciIterator);
  registryEntryMeta = IORegistryEntry::metaClass;
  bridgeDevice = (IORegistryEntry *)OSMetaClassBase::safeMetaCast(tmp, IORegistryEntry::metaClass);
  if ( !bridgeDevice )
    goto RELEASE_ITERATOR;
  while ( 1 )
  {
    name = bridgeDevice->getName(bridgeDevice, 0LL);
    if ( strlen(name) < 2 )
      goto NEXT_DEVICE;
    nameWord = *(unsigned __int16 *)name;
    if ( nameWord != 'PR' && (unsigned __int16)nameWord != 'EP' )// RP or PE to match the bridge (RPCX or PEG0)
      goto NEXT_DEVICE;
    bridgeIterator = bridgeDevice->getChildIterator(bridgeDevice, gIODTPlane);
    tmp = bridgeIterator->getNextObject(bridgeIterator);
    ssdDevice = (IORegistryEntry *)OSMetaClassBase::safeMetaCast(tmp, registryEntryMeta);
    if ( ssdDevice )
      break;
FIND_NEW_SSD:
    bridgeIterator->release_0(bridgeIterator);
NEXT_DEVICE:
    tmp = pciIterator->getNextObject(pciIterator);
    bridgeDevice = (IORegistryEntry *)OSMetaClassBase::safeMetaCast(tmp, registryEntryMeta);
    if ( !bridgeDevice )
      goto RELEASE_ITERATOR;
  }
  while ( 1 )
  {
    name = ssdDevice->getName(ssdDevice, 0LL);
    if ( strlen(name) == 4 && *(_DWORD *)name == '0DSS' )// SSD0
      break;
    tmp = bridgeIterator->getNextObject(bridgeIterator);
    ssdDevice = (IORegistryEntry *)OSMetaClassBase::safeMetaCast(tmp, registryEntryMeta);
    if ( !ssdDevice )
      goto FIND_NEW_SSD;
  }
  ssdStatus = PciLnkPm(ssdDevice);
  bridgeStatus = PciLnkPm(bridgeDevice);
  if ( ssdStatus == 2 && bridgeStatus == 2 )
    IOLog("Enabled PCIe PM on SSD");
  bridgeIterator->release_0(bridgeIterator);
RELEASE_ITERATOR:
  pciIterator->release_0(pciIterator);
RELEASE_ROOT:
  pciRoot->release_0(pciRoot);
  return 0;
}

UInt8 __fastcall PciLnkPm(IORegistryEntry *drive)
{
  IOPCIDevice *device; // rbx
  UInt16 LinkControl; // ax
  UInt8 offset; // [rsp+Fh] [rbp-11h] OVERLAPPED BYREF

  offset = 0;
  device = (IOPCIDevice *)OSMetaClassBase::safeMetaCast(drive, IOPCIDevice::metaClass);
  if ( !device->findPCICapability(device, 0x10u, &offset) )// kIOPCICapabilityIDPCIExpress
    return 0;
  LinkControl = IOPCIDevice::extendedConfigRead16(device, offset + 0x10LL);// LinkControl register
  // typedef enum {
  //     L0sAndL1EntryDisabled,
  //     L0sEntryEnabled,
  //     L1EntryEnabled,
  //     L0sAndL1EntryEnabled
  // } PCI_EXPRESS_ASPM_CONTROL;
  IOPCIDevice::extendedConfigWrite16(device, offset + 0x10LL, LinkControl & ~3 | 2);// (LinkControl & ~ASPM_MASK) | L1EntryEnabled
  return IOPCIDevice::extendedConfigRead16(device, offset + 0x10LL) & 2;
}
```

**Comment by herb2k** [comment]
> I additionally fixed the register encoding in [acidanthera/NVMeFix@4ccff54](https://github.com/acidanthera/NVMeFix/commit/4ccff54d4d947d6bef3a40e6d52e6ce723906e58). What does SsdPmEnabler do? Can incorporate it in NVMeFix.

Works!

<img width="523" alt="image" src="https://user-images.githubusercontent.com/55064641/116580510-4a652400-a8c8-11eb-852b-58a600f954f5.png">

**Comment by naveenkrdy** [comment]
> Those args are partially incorrect, remember that Big Sur is snapshot based. Catalina's commands won't work unless there user has deleted all APFS snapshots and is booting a live filesystem. Otherwise no edits will be done to the root volume.

@khronokernel yes ofc  ! its a no brainer as these commands will not work unless the user has root volume mounted after doing the snapshot part. just provided him list of commands that needed basically.
Also i see that you are not using kcditto ? without this i don't think it will update preboot volumes.

> I additionally fixed the register encoding in [acidanthera/NVMeFix@4ccff54](https://github.com/acidanthera/NVMeFix/commit/4ccff54d4d947d6bef3a40e6d52e6ce723906e58). What does SsdPmEnabler do? Can incorporate it in NVMeFix.

@vit9696 Thanks, that fixed the issue.

> To be honest, there is little reason this in the kext, as you can just add pci-aspm-default with <02 00 00 00> value as a DeviceProperty in OpenCore. I can consider this if you give me reasons, but a simple DeviceProperty should be much easier.

i second that !
But i think for users with real mac systems who dont use opencore, a mechanism to set pcie aspm for nvme through a boot arg would be preferable. Just like how AirportBrcmFixup kext does.

Thanks !

**Comment by herb2k** [comment]
> I additionally fixed the register encoding in [acidanthera/NVMeFix@4ccff54](https://github.com/acidanthera/NVMeFix/commit/4ccff54d4d947d6bef3a40e6d52e6ce723906e58). What does SsdPmEnabler do? Can incorporate it in NVMeFix.

Works!

**Comment by m0d16l14n1** [comment]
@vit9696 omg, thx for that fix. I had that issue from Big Sur first beta of Big Sur, but i managed to log it only now. I check last commit - it's working now, heh. Crucial P1 1TB NVME
[Log_2021-04-29_19-31-20.log](https://github.com/acidanthera/bugtracker/files/6400196/Log_2021-04-29_19-31-20.log)

**Comment by siddiqq** [comment]
> After some discussion I agreed to add ASPM enforcement to NVMeFix via `-nvmefaspm` boot argument in [acidanthera/NVMeFix@1ca48be](https://github.com/acidanthera/NVMeFix/commit/1ca48be6281bc5c788642dc012f113b2a90ecdc1). This may help when there is no bootloader in place. Please test and provide IOReg & logs.

Just got back from work, installed the update and it works!! Uninstalled SsdPmEnabler as well and now finally running idle at 0.00 with only Lilu and NVMeFix :D Thank you so much @vit9696 you sir are a legend!

**Comment by vit9696** [comment]
@siddiqq how do you measure NVMe power consumption, by the way?

**Comment by siddiqq** [comment]
> @siddiqq how do you measure NVMe power consumption, by the way?

I use iStat Menus from https://bjango.com/mac/istatmenus/, then unplug the charger and watch the power consumption under the "SSD 3.3V" section in the menu bar. 

By the way, I'm not sure if this is related but was hoping you could help. Ever since I updated to 11.3, I will get kernel panics when my Mac goes to sleep, apparently because I have a SD card in my card reader. 

It happens when I set my hibernation mode to 25, but when I change it to the default hibernation mode 3, I stop getting kernel panic during sleep. The sleep modes described on here https://www.lifewire.com/change-mac-sleep-settings-2260804 . I use mode '25' because it stops my battery from draining over night.

 I get this in the report from the panic every time  :

panic(cpu 2 caller 0xffffff80153d5f07): "com_apple_driver_AppleUSBCardReaderDriverNub::setPowerState(0xffffff9359293800 : 0xffffff8016396074, 1 -> 2) timed out after 30419 ms"@/System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.101.1/iokit/Kernel/IOServicePM.cpp:5382

Would you happen to know what's going on?

Thank you

**Comment by vit9696** [comment]
@siddiqq thx for the insight.

Regarding the timeout I am not sure I know any solution, trying `PowerTimeoutKernelPanic` quirk could help. There also were tools to unmount devices before going to sleep, like [Ejectify](https://ejectify.app) and [Jettison](https://stclairsoft.com/Jettison). Not sure if they can help in this particular case, but may be worth trying.

Perhaps @khronokernel knows something.

**Comment by siddiqq** [comment]
> @siddiqq thx for the insight.
> 
> Regarding the timeout I am not sure I know any solution, trying `PowerTimeoutKernelPanic` quirk could help. There also were tools to unmount devices before going to sleep, like [Ejectify](https://ejectify.app) and [Jettison](https://stclairsoft.com/Jettison). Not sure if they can help in this particular case, but may be worth trying.
> 
> Perhaps @khronokernel knows something.

thank you, I tried both apps but they both give an error message saying they couldn't eject the SD card haha. I filed a bug report with Apple so hopefully they'll fix it.

**Comment by m0d16l14n1** [comment]
@vit9696 Hello! It's seems that NVMeFix is broken on macOS Monterey Beta. I can't see apst key in IOreg. 

Do you needIONVMeFamily.kext itself from beta, like you asked previously for Big Sur?

**Comment by vit9696** [comment]
File a new issue, provide liludump log, provide NVMe kext.

**Comment by 42648594** [comment]
> @naveenkrdy Those args are partially incorrect, remember that Big Sur is snapshot based. Catalina's commands won't work unless there user has deleted all APFS snapshots and is booting a live filesystem. Otherwise no edits will be done to the root volume.
> 
> Corrected steps for snapshot based installs:
> 
> ```shell
> # Find your System volume
> diskutil list
> 
> # From the below list, we can see our System volume is disk5s5
> /dev/disk5 (synthesized):
>    #:                       TYPE NAME                    SIZE       IDENTIFIER
>    0:      APFS Container Scheme -                      +255.7 GB   disk5
>                                  Physical Store disk4s2
>    1:                APFS Volume ⁨Big Sur HD - Data⁩       122.5 GB   disk5s1
>    2:                APFS Volume ⁨Preboot⁩                 309.4 MB   disk5s2
>    3:                APFS Volume ⁨Recovery⁩                887.8 MB   disk5s3
>    4:                APFS Volume ⁨VM⁩                      1.1 MB     disk5s4
>    5:                APFS Volume ⁨Big Sur HD⁩              16.2 GB    disk5s5
>    6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 16.2 GB    disk5s5s
> 
> # Mount the drive(ie. disk5s5)
> sudo mount -o nobrowse -t apfs  /dev/disk5s5 /System/Volumes/Update/mnt1
> 
> # Remove old kext if present
> sudo rm -R /System/Volumes/Update/mnt1/System/Library/Extensions/Example.kext
> 
> # Copy over your kext
> sudo cp -R ~/Desktop/Example.kext /System/Volumes/Update/mnt1/System/Library/Extensions/
> 
> # Fix permissions
> sudo chmod -R 755 /System/Volumes/Update/mnt1/System/Library/Extensions/Example.kext
> sudo chown -R root:wheel /System/Volumes/Update/mnt1/System/Library/Extensions/Example.kext
> 
> # Rebuild kernel cache
> sudo kmutil install --volume-root /System/Volumes/Update/mnt1/ --update-all
> 
> # Create new bootable snapshot
> sudo bless --folder /System/Volumes/Update/mnt1/System/Library/CoreServices --bootefi --create-snapshot
> ```

Is this also correct for non-hackintosh installations? On the giant macrumours forum post about upgrading 2013-2015 MacBooks with NVMe drives, it seems the preferred kext location is /Library/Extensions/, not /System/Library/Extensions/. Does it make a difference?

**Comment by TechnoBento** [comment]
> @naveenkrdy Those args are partially incorrect, remember that Big Sur is snapshot based. Catalina's commands won't work unless there user has deleted all APFS snapshots and is booting a live filesystem. Otherwise no edits will be done to the root volume.
> 
> Corrected steps for snapshot based installs:
> 
> ```shell
> # Find your System volume
> diskutil list
> 
> # From the below list, we can see our System volume is disk5s5
> /dev/disk5 (synthesized):
>    #:                       TYPE NAME                    SIZE       IDENTIFIER
>    0:      APFS Container Scheme -                      +255.7 GB   disk5
>                                  Physical Store disk4s2
>    1:                APFS Volume ⁨Big Sur HD - Data⁩       122.5 GB   disk5s1
>    2:                APFS Volume ⁨Preboot⁩                 309.4 MB   disk5s2
>    3:                APFS Volume ⁨Recovery⁩                887.8 MB   disk5s3
>    4:                APFS Volume ⁨VM⁩                      1.1 MB     disk5s4
>    5:                APFS Volume ⁨Big Sur HD⁩              16.2 GB    disk5s5
>    6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 16.2 GB    disk5s5s
> 
> # Mount the drive(ie. disk5s5)
> sudo mount -o nobrowse -t apfs  /dev/disk5s5 /System/Volumes/Update/mnt1
> 
> # Remove old kext if present
> sudo rm -R /System/Volumes/Update/mnt1/System/Library/Extensions/Example.kext
> 
> # Copy over your kext
> sudo cp -R ~/Desktop/Example.kext /System/Volumes/Update/mnt1/System/Library/Extensions/
> 
> # Fix permissions
> sudo chmod -R 755 /System/Volumes/Update/mnt1/System/Library/Extensions/Example.kext
> sudo chown -R root:wheel /System/Volumes/Update/mnt1/System/Library/Extensions/Example.kext
> 
> # Rebuild kernel cache
> sudo kmutil install --volume-root /System/Volumes/Update/mnt1/ --update-all
> 
> # Create new bootable snapshot
> sudo bless --folder /System/Volumes/Update/mnt1/System/Library/CoreServices --bootefi --create-snapshot
> ```

your last line doesn’t work on Monterey, any suggestions?
