### ISSUE TITLE
[OcBinaryData] HfsPlus revisions

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1621]
Hi, today I've analyzed this `IM191.fd` file (attached below) which came from a major upgrade (macOS 11.3) and it seems like it's a ROM image from a real iMac19,1. 

Looking inside with UEFITool, there are many sections which look familiar (from OpenCore/OcBinaryData master), like `ApfsJumpStart`, `UsbKbDxe`, `UsbMouseDxe` and lastly, `HfsPlus`

My question was, extracting body from the HfsPlus section outputs a 

```Section_PE32_image_HfsPlus_HfsPlus_body.efi```

My question are:

1. Is it possible to obtain a newer version of the driver from these original BIOS images from Apple? 
2. If the above is false, what I extracted is just garbage? What was the mechanism to extract the actual `HfsPlus.efi/HfsPlus32.efi` etc?
3. Does this firmware have a PE32image section like "Setup" where in most firmware are listed every possible BIOS option once you convert the `Setup.bin` to plaintext with `Universal-IFR-Extractor`?

Thanks for your patience, feel free to respond when you can since this is not an actual issue, but a clarification

**Comment by 1alessandro1** [comment]
Forgot to attach the image, here it is

[IM191.fd.zip](https://github.com/acidanthera/bugtracker/files/6394158/IM191.fd.zip)

`SHA256: af03bfa52207207150f75a93c2b8e022fce859de93fb1a8b7a808acdeb210522`

**Comment by vit9696** [comment]
1. Yes, that's what we do ourselves from time to time in OcBinaryData.
2. You extracted the same thing we extracted ourselves and put to OcBinaryData. I think we use iMac18,3 though.
3. No, Apple does not use this mechanism.
