### ISSUE TITLE
Incorrect version of OpenCore in NVRAM

### ISSUE THREAD

**Issue by najeebanwer** [acidanthera/bugtracker#1622]
I am using OpenCore 0.6.8. According to the OpenCore Install Guide, this command shows the version of OpenCore in use.

![image](https://user-images.githubusercontent.com/34123660/116606831-e6a61f80-a8f6-11eb-9bd8-1cf5dca434d3.png)
However, this is what I get - OpenCore 0.6.6.
![image](https://user-images.githubusercontent.com/34123660/116606767-cfffc880-a8f6-11eb-9547-570343a4147f.png)

**Comment by vit9696** [comment]
Reset NVRAM.

**Comment by najeebanwer** [comment]
I wish it was that simple. I have reset NVRAM and the result is the same.

**Comment by vit9696** [comment]
Then you may have multiple OpenCore installations. You can always install a DEBUG version and see both the NVRAM reset logs and the boot logs. They could confirm you run the version you mentioned and they can also confirm that the variable containing OpenCore version was actually removed.

**Comment by najeebanwer** [comment]
I think the problem is that I am running the Release version of OpenCore and the NVRAM variable is not getting written because it is not explicitly specified in the NVRAM/Delete section of config.plist. To test this, I added the variable to this section in config.plist:
![Screen Shot 2021-05-04 at 9 50 31 PM](https://user-images.githubusercontent.com/34123660/117092164-16a05900-ad23-11eb-8812-c9ac80134131.png)
and then rebooted and printed the value of this variable:
![Screen Shot 2021-05-04 at 9 50 52 PM](https://user-images.githubusercontent.com/34123660/117092190-2e77dd00-ad23-11eb-9628-2b881e655c44.png)
It is now correct. I think this needs to be clarified in the documentation. It also makes me wonder what other variables are not being written to NVRAM correctly by the Release version of OpenCore.

**Comment by vit9696** [comment]
This explanation is wrong. Prior to 0.6.7 OC version was stored in flash (by mistake), and in 0.6.7 it is stored in RAM. You cannot replace variable storage type without explicitly removing it. This is why Reset NVRAM or direct variable removal is needed once. No idea why Reset NVRAM did not work for you, but we will never know it now anyway.

**Comment by bhagatparwinder** [comment]
I have this exact issue. OC still displays 066 when I am on 069. I have gone through three updates now and I did do NVRAM reset.

**Comment by vit9696** [comment]
Well, as long as you do not provide the DEBUG log of NVRAM reset — I cannot help you.

**Comment by najeebanwer** [comment]
> This explanation is wrong. Prior to 0.6.7 OC version was stored in flash (by mistake), and in 0.6.7 it is stored in RAM. You cannot replace variable storage type without explicitly removing it. This is why Reset NVRAM or direct variable removal is needed once. No idea why Reset NVRAM did not work for you, but we will never know it now anyway.

@vit9696, thanks for your explanation. I upgraded to OpenCore 0.6.9 and I can confirm that the opencore-version is correctly updated.

**Comment by MikeBeaton** [comment]
> I have this exact issue. OC still displays 066 when I am on 069. I have gone through three updates now and I did do NVRAM reset.

@bhagatparwinder It would be interesting to understand what is going on; if there really is an error that is affecting you both - or possibly the same user error?

i.e. You can fix it as @najeebanwer did, but it would be interesting to see the steps you are taking that are _not_ working, before you do that.

If you install a debug version of OpenCore, run reset NVRAM (and confirm that it still isn't working for you), and then post the OpenCore log file output (file produced in root of OC volume if `Misc/Debug/Target=67`) and your `config.plist` this would be useful.

**Comment by najeebanwer** [comment]
@MikeBeaton, I may be completely wrong about this, but here is the problem as I see it:
The release version of OpenCore behaves differently than the debug version in at least one aspect related to NVRAM variables:
- The debug version always overwrites the NVRAM variable regardless of whether it is also present in the NVRAM/Delete section of config.plist.
- The release version will only overwrite NVRAM variables if they are also present in the NVRAM/Delete section of config.plist.
To test this, remove, for example, boot-args from the NVRAM/Delete section of config.plist and then change the boot-args to add, for example, the -v flag for verbose output. In the release version of OpenCore, this will have no effect on the boot-args variable.
![Screen Shot 2021-05-06 at 3 33 18 PM](https://user-images.githubusercontent.com/34123660/117362229-9d1e7d00-ae80-11eb-99a7-7f85e047a242.png)
After reboot:
![Screen Shot 2021-05-06 at 3 34 40 PM](https://user-images.githubusercontent.com/34123660/117362242-a0b20400-ae80-11eb-8a93-473f729a5352.png)
I don't know if this is a feature or a bug, but I know for a fact that the debug version of OpenCore will always overwrite the NVRAM variable even when it is not specified in NVRAM/Delete.
So, the problem with using the debug version of OpenCore to diagnose the issue is that it changes the result. It's the old problem of using a tool to observe an experiment where the tool itself changes the experiment.

**Comment by vit9696** [comment]
Hm, this is not a feature. The release version should behave the same way as the DEBUG version. We will recheck, but there is almost no chance our code is broken. What it could be is your NVRAM being corrupted, causing it lose variables under different conditions. The DEBUG version may write more to NVRAM for instance. Could you upload your config?

CC @mhaeuser

**Comment by najeebanwer** [comment]
My config.plist is attached.
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/6437602/config.plist.zip)

**Comment by vit9696** [comment]
Checked, do not see anything special, should be fine. Could you download a DEBUG version, set Target to 67, and then perform Reset NVRAM? Provide a log here.

**Comment by najeebanwer** [comment]
Attached are the logs for the debug version of OpenCore:
1. macOS boot before NVRAM Reset
[opencore-2021-05-07-065211-Before NVRAM Reset.txt](https://github.com/acidanthera/bugtracker/files/6439726/opencore-2021-05-07-065211-Before.NVRAM.Reset.txt)

2. Boot to Picker for NVRAM Reset
[opencore-2021-05-07-070400-NVRAM Reset.txt](https://github.com/acidanthera/bugtracker/files/6439750/opencore-2021-05-07-070400-NVRAM.Reset.txt)

3. macOS boot after NVRAM Reset
[opencore-2021-05-07-070426-After NVRAM Reset.txt](https://github.com/acidanthera/bugtracker/files/6439756/opencore-2021-05-07-070426-After.NVRAM.Reset.txt)

**Comment by vit9696** [comment]
Ok, NVRAM reset does not work on your setup. Fixed in https://github.com/acidanthera/OpenCorePkg/commit/90e3ccadd36f2bf69f52ed6a6afab39d3972574d. There may be more issues, so please provide a new set of logs.

**Comment by najeebanwer** [comment]
Ok, I will do that sometime tomorrow. It's getting pretty late here in Texas.

**Comment by 1alessandro1** [comment]
@najeebanwer usually you can find fresh OpenCore builds [here](https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true) but if you want to build it yourself, once you are in `master` and you have `Xcode` or `Xcode command line tools` installed, just run

```
./build_oc.tool
```

And the bash script will prompt the necessary files to add if they're missing in your `$PATH` such as `nasm` and `mtoc`

**Comment by najeebanwer** [comment]
@1alessandro1, thank you.
To be clear, I only need to replace EFI/OC/OpenCore.efi and EFI/OC/Drivers/OpenRuntime.efi from this new build into my existing EFI folder. Correct?

**Comment by vit9696** [comment]
For this particular case — yes, but in general you should replace all efi drivers, resources, and make sure config.plist is up to date by running ocvalidate.

**Comment by najeebanwer** [comment]
These are the new logs:
[opencore-2021-05-07-225652-Before NVRAM Reset.txt](https://github.com/acidanthera/bugtracker/files/6444704/opencore-2021-05-07-225652-Before.NVRAM.Reset.txt)
[opencore-2021-05-07-230015-NVRAM Reset.txt](https://github.com/acidanthera/bugtracker/files/6444705/opencore-2021-05-07-230015-NVRAM.Reset.txt)
[opencore-2021-05-07-230050-After NVRAM Reset.txt](https://github.com/acidanthera/bugtracker/files/6444706/opencore-2021-05-07-230050-After.NVRAM.Reset.txt)

**Comment by vit9696** [comment]
Ok, so. ResetNVRAM does work now, but what I see is something unexpected:

> 22:467 00:043 Deleting 7C436110-AB2A-4BBB-A880-FE41995C9F82:fakesmc-key-$Adr-ui32... OK

Is created by Clover, not by OpenCore. And you apparently did not clean your system from Clover dirt. All sorts of issues may have happened due to that.

Can you now try the latest version of OpenCore (from dortania) and try to reproduce your boot-args bug? I.e. that DEBUG builds always override variables without the Delete field (this should not happen). Provide the logs for both booting with one boot-args value and then with the updated boot-args value.

**Comment by najeebanwer** [comment]
Strange; I have never installed Clover on this system. I may have tried booting from a Clover USB key once, before I moved to OpenCore.

**Comment by MikeBeaton** [comment]
@najeebanwer Thank you for your input.

@vit9696 Did it become clear why the difference between DEBUG and RELEASE builds, here?

**Comment by vit9696** [comment]
In my opinion, was a full NVRAM, can cause any effects.
