### ISSUE TITLE
"ASSERT_EFI_ERROR (Status = Invalid Parameter)" and "ASSERT [Shell] Shell.c(485): !EFI_ERROR (Status)"

### ISSUE THREAD

**Issue by johnnyryan** [acidanthera/bugtracker#1624]
The guide asked that Asserts be posted here. 

Last two lines of the log: 
01:588 00:180 ASSERT_EFI_ERROR (Status = Invalid Parameter)
01:603 00:015 ASSERT [Shell] Shell.c(485): !EFI_ERROR (Status)

[opencore-2021-05-03-202655.txt](https://github.com/acidanthera/bugtracker/files/6417790/opencore-2021-05-03-202655.txt)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/6417791/EFI.zip)

**Comment by Andrey1970AppleLife** [comment]
1:347 00:019 OC: Driver OpenShell.efi at 3 is being loaded...

OpenShell.efi it not driver.
