### ISSUE TITLE
issues using restrictedevents and Intel Bluetooth.

### ISSUE THREAD

**Issue by jumpers775** [acidanthera/bugtracker#1628]
Hi, so I have noticed that when using this kext intel bluetooth will be unavailable. this is using the latest IntelBluetoothFirmware/intelbluetoothinjector combo as well as the latest restrictedevents. when I changed the priority order to put the intel bluetooth kexts just below lilu and virtualsmc it works less than half the time. I can supply anything necessary

**Comment by vit9696** [comment]
Well, we do not do anything to Intel Bluetooth. File the bug there.
