### ISSUE TITLE
Wi-Fi table list location

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1629]
Hi, I remember that there was a google drive spreadsheet which collected all device ids and chipsets for Wi-Fi cards, similar to those that can be found here:

https://docs.google.com/spreadsheets/d/15S-ocrkm_VTUJpKxNII-YUyQFd5VYdjbe0DHlZVCQyM/ (`Kexts.md`, OpenCore Repo)
https://docs.google.com/spreadsheets/d/1HTCBwfOBkXsHiK7os3b2CUc6k68axdJYdGl-TyXqLu0/  (`Configuration.pdf`, OpenCore Repo)

Maybe it was maintained by @Andrey1970AppleLife but I'm not sure about that, it would be nice to attach that to the AirportBrcmFixup `Readme.md` for easy reach of the document

**Comment by 1alessandro1** [comment]
Ok, I found it: 

https://docs.google.com/spreadsheets/u/0/d/1Yxlvo-vK_zupMiR1Ua_NZ1X0j6BSXoICCEgB7wvAQsM/htmlview

Can this be added somewhere in the docs?

**Comment by Andrey1970AppleLife** [comment]
This table is is made on the basis of the original from Skvo. Unfortunately this updated table contains incorrect added data.
The original table from Skvo: [Таблица совместимости карт Mini PCI-Express с Mac OS X.zip](https://github.com/acidanthera/bugtracker/files/6430394/Mini.PCI-Express.Mac.OS.X.zip)

**Comment by vit9696** [comment]
@1alessandro1 have a look on https://github.com/dortania/bugtracker/issues/204, I believe I covered most of the stuff. If you want to take the initiative, that would be welcome.

**Comment by 1alessandro1** [comment]
@vit9696 Thanks for caring about this, I can help maintaining/fixing/translating the document, but additional info must come from the end-users since I can only report a handful of WiFi cards correctly.
I have collected few ideas to overcome the missing documentation for wireless devices, and posted that in https://github.com/dortania/bugtracker/issues/204 ^_^
