### ISSUE TITLE
[Warning] Opencore 0.6.9 made Virustotal alerting

### ISSUE THREAD

**Issue by hibari0614** [acidanthera/bugtracker#1630]
HI ^^

I find the OC 0.6.9 might made Virustotal trojan alerting (the package is downloaded from Github release panel).

Is it a false positive alert or ... ^^ ?

![截圖 2021-05-06 下午9 24 11](https://user-images.githubusercontent.com/1697578/117306402-3dd96080-aeb2-11eb-8f3f-a6a2a858f6c4.png)

**Comment by 1alessandro1** [comment]
https://github.com/acidanthera/bugtracker/issues/1347

https://github.com/acidanthera/bugtracker/issues/1550

https://github.com/acidanthera/bugtracker/issues/1363

**Comment by hibari0614** [comment]
@1alessandro1

Thanks your kindly reply. It seems false negative alerts.
