### ISSUE TITLE
BrightnessKeys did not work on HP Pavilion DV6 7017tx

### ISSUE THREAD

**Issue by hibari0614** [acidanthera/bugtracker#1632]
HI

I have a laptop HP Pavilion DV6 7017tx running BigSur 11.3.1 with OC 0.6.8. When I used BrightnessKeys (v1.0.1) first time it worked very will but, it did not continuity working afterward.

I try figuring the problems out, but the Lilu debug log did not have enough message (log as below) and the IORegistryExplorer shows (figure as below) the BrightnessKeys' IOService is registered and I still do not know where the problems is.

Would you might kindly help me to fix this problem  (attached the DSDT & config.pilst) ? (Brightness keys are lovely)

```
sudo cat /var/log/Lilu_1.5.3_20.4.txt| grep -E "BrightnessKeys|brkeys"
BrightnessKeys    brkeys: @ (DBG) Notification consumer published: ApplePS2Controller
BrightnessKeys    brkeys: @ (DBG) Notification consumer published: ApplePS2Keyboard
BrightnessKeys    brkeys: @ (DBG) Notification consumer published: ApplePS2SynapticsTouchPad
Lilu   patcher: @ (DBG) last kext is 0xFFFFFF80257D2000 and its name is as.acidanthera.BrightnessKeys
```
 
![截圖 2021-05-08 上午7 18 46](https://user-images.githubusercontent.com/1697578/117517173-b5e87900-afcd-11eb-958d-dc37807965de.png)

[DSDT.aml.zip](https://github.com/acidanthera/bugtracker/files/6444735/DSDT.aml.zip)
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/6444736/config.plist.zip)

**Comment by vit9696** [comment]
Can always implement manually over DSDT. No support requests here. Closing.

CC @zhen-zen

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/1631

**Comment by zhen-zen** [comment]
Please check if the function keys work in Linux. This could be a firmware issue per https://bugs.launchpad.net/ubuntu/+bug/1841039

**Comment by zhen-zen** [comment]
Please check for BIOS updates as the vendor is rolling out a potential fix:
- Enables Brightness hotkey support for the Linux operating system.
