### ISSUE TITLE
WhateverGreen "Failed to route IsTypeCOnlySystem" even after 1.4.5 update

### ISSUE THREAD

**Issue by wstroftgithub** [acidanthera/bugtracker#1633]
in 1.4.5 whatevergreen changelog:
- Fixed failed to route IsTypeCOnlySystem warning from Skylake to Ice Lake

i have 1.4.9 but it's still happening
my processor is a intel core 6200U skylake

**Comment by vit9696** [comment]
Not a bug.

**Comment by wstroftgithub** [comment]
what do you mean by that? i wanna fix it
