### ISSUE TITLE
[Feature Request]  Add option for disable ACPI patches and smbios injection on other OSes.

### ISSUE THREAD

**Issue by Aabirr** [acidanthera/bugtracker#1634]
For better dual booting experience with opencore, if it is possible to add an option to disable ACPI and other injection to other OSes would be great. as this causes performance issues(not smooth as normally etc.) and sometimes break software licence like windows activation etc. So I hope it makes sense for the devs. 

Thank you.

**Comment by vit9696** [comment]
Replied several times, this will not happen. Also, it does _not_ cause any performance issues. Last time we were bugged about it, it was due to incorrect user configuration.

See https://github.com/acidanthera/bugtracker/issues/802 for a more detailed answer.

**Comment by Aabirr** [comment]
Thank you!
