### ISSUE TITLE
SMCDellSensors.kext not loaded. Big Sur 11.3.1 /OC 0.6.9

### ISSUE THREAD

**Issue by P013onEr** [acidanthera/bugtracker#1635]
```
kextstat | grep SMC 
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
   15   13 0xffffff800194e000 0x19000    0x19000    com.apple.driver.AppleSMC (3.1.9) 406AA67A-5111-3CA1-8C7A-A95B18AF6252 <14 13 12 8 7 6 5 3 1>
   53    4 0                  0x2a000    0x2a000    as.vit9696.VirtualSMC (1.2.4) D32BD4D0-0453-3B44-A06D-22AE92F096E9 <48 13 8 6 5 3 2 1>
   55    0 0                  0x1a000    0x1a000    ru.usrsse2.SMCBatteryManager (1.2.4) F35DA103-3888-352A-A828-4D03B012FF00 <54 53 48 13 8 6 5 3 2 1>
   56    0 0                  0xb000     0xb000     ru.usrsse2.SMCLightSensor (1.2.4) 000BA03E-B386-3B3E-9C48-43BD5CCD0906 <53 48 13 8 6 5 3 2 1>
   63    0 0                  0xf000     0xf000     as.vit9696.SMCProcessor (1.2.4) 2703643F-B6C2-3DFF-8EE6-024BC15CF554 <53 48 13 8 6 5 3 2 1>
   82    0 0                  0x3d000    0x3d000    ru.joedm.SMCSuperIO (1.2.4) 4995CA31-3EC7-3E95-8D17-99DE42B6706F <53 48 13 8 6 5 3 2 1>
  125    0 0xffffff7f998f1000 0xd000     0xd000     com.apple.driver.ACPI_SMC_PlatformPlugin (1.0.0) 804AAA2B-B9DD-3B93-BD5A-149256DEE4E9 <124 122 15 14 13 8 7 6 5 3>
  139    0 0xffffff7f99492000 0x3000     0x3000     com.apple.driver.AppleSMCLMU (212) 57091753-D2EA-3FB7-9FB8-1D893F459152 <128 15 6 5 3>
➜  ~ kextstat | grep dell
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
➜  ~ kextstat | grep sensor
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
```

all kext are newest and debug version.also add them to config.list

My fan speed shows N/A ,not detect the fan. Plz help.

**Comment by vit9696** [comment]
OC DEBUG log with Target 67, also config.plist. Will reopen in case bug is found and cannot be fixed immediately.

**Comment by vit9696** [comment]
This is the release OpenCore, so it does not log much. I also do not see, you might have attached a different log.

```
0:323 00:002 OC: Prelinked injection skips SMCDellSensors.kext () kext at 10 due to version 0 <= 200400 <= 190909
```

The warning you pasted means that you disabled SMCDellSensors on macOS 11 (kernel `20.x.x`) by setting `MaxKernel` to `19.9.9`. Obviously OpenCore does exactly what you asked it to.

**Comment by P013onEr** [comment]
> This is the release OpenCore, so it does not log much. I also do not see, you might have attached a different log.
> 
> ```
> 0:323 00:002 OC: Prelinked injection skips SMCDellSensors.kext () kext at 10 due to version 0 <= 200400 <= 190909
> ```
> 
> The warning you pasted means that you disabled SMCDellSensors on macOS 11 (kernel `20.x.x`) by setting `MaxKernel` to `19.9.9`. Obviously OpenCore does exactly what you asked it to.

solved. thanks! just deleted the max kernel.
