### ISSUE TITLE
OpenCore unable to accept forward slashes as directory separators

### ISSUE THREAD

**Issue by Xefyr0** [acidanthera/bugtracker#1637]
I'm running a multiboot setup, and wanted to chainload Grub2 into OpenCore rather than the other way around so that I could avoid having any patches apply to Windows and Ubuntu. However, I ran into a roadblock: Grub2 passes the booter directory to OC with forward slashes as directory separators, but OC uses backward slashes when booting normally. Oddly enough this only affects the final directory separator, so when chainloaded from Grub2 OC lists its booter path as "\EFI\OC/Opencore.efi" and stops on the error message "OC: Failed to load configuration!"
![Failure](https://user-images.githubusercontent.com/78383477/117858368-d3cb0d80-b25b-11eb-8635-8b31390a847f.jpg)
The workaround I and others have been using is to put a copy of OpenCore.efi or BOOTx64.efi in a folder within OC, and then chainload to that instead. With that being the case, the booter path is instead listed as "\EFI\OC\GRUB2_Chainloading/BOOTx64.efi" and OC works as expected. The original guide I followed can be found at 
[https://github.com/SayantanRC/URLs/blob/master/grub_to_opencore.md](https://github.com/SayantanRC/URLs/blob/master/grub_to_opencore.md)
although, from my experience not all of the things the guide recommends are strictly necessary, just that the .efi file GRUB2 chainloads be in a folder within the OC folder.
![Success](https://user-images.githubusercontent.com/78383477/117858358-d0d01d00-b25b-11eb-87e1-47cec1aa6163.jpg)
My EFI is too large to be uploaded directly, so here's a google drive link:
[https://drive.google.com/file/d/1RnpHRz6oEoOtJRUXSWOkLzHmNqFPPYd_/view?usp=sharing](https://drive.google.com/file/d/1RnpHRz6oEoOtJRUXSWOkLzHmNqFPPYd_/view?usp=sharing)

**Comment by vit9696** [comment]
Hmmm, that sounds like a bug on grub side to be honest. `/` separators are not allowed in UEFI, I included a screenshot from the latest UEFI specification below. Taking it into consideration, we are rightful to refuse loading, and this should really be fixed on grub2 side.

I can consider adding some workaround considering that the Linux distros include prebuilt grub version and they cannot update quickly, but I will need you to do some things as well.

- Why do you need to use grub before OpenCore in the first place? It is not a great piece of software and is also very insecure. OpenCore provides full multiboot support for all the UEFI operating systems and a proper UI.
- Could you report this upstream to grub (https://www.gnu.org/software/grub/grub-bugs.html) and request them fix it?

<img width="843" alt="Снимок экрана 2021-05-11 в 20 43 11" src="https://user-images.githubusercontent.com/4348897/117860916-82417380-b299-11eb-9977-c9bfab390bcd.png">

**Comment by Xefyr0** [comment]
First off, thank you for the speedy and comprehensive reply. 

> Hmmm, that sounds like a bug on grub side to be honest. `/` separators are not allowed in UEFI, I included a screenshot from the latest UEFI specification below. Taking it into consideration, we are rightful to refuse loading, and this should really be fixed on grub2 side.

I see, I had not known the UEFI specification explicitly mandates '\' separators instead of '/'. My apologies.

> * Why do you need to use grub before OpenCore in the first place? It is not a great piece of software and is also very insecure. OpenCore provides full multiboot support for all the UEFI operating systems and a proper UI.

Two reasons: It was included in the Ubuntu installation and, as I mentioned in the first comment, OpenCore applies patches before even booting an OS. This affects Windows and Ubuntu when booting them through OC very negatively. It breaks audio, dGPU, and the fingerprint scanner as well as change the recommended GUI resolution. It is for these reasons I'm unwilling to use OC as a boot manager, so if you have any recommendations outside of that I'm all ears. 

> * Could you report this upstream to grub (https://www.gnu.org/software/grub/grub-bugs.html) and request them fix it?

Will do.

**Comment by vit9696** [comment]
Hmm, well, I know your feelings, but the way OpenCore handles user-supplied patches does not affect Windows negatively. I am saying this with Windows running in front of my eyes under OpenCore with both audio and dGPU working fine.

The reason things break for you and many others is not the "macOS patches are incompatible" but "specified patches are invalid". Just it happens that macOS is more tolerant to certain mistakes in ACPI code. For example, when you do the "renames", which are always harmful, they usually either miss things or replace too much. Most often devices would die due to their methods becoming unavailable.

It may sound annoying to fix but it is not like these patches are correct for macOS either. If you carefully inspect macOS kernel logs, you will likely find warnings. Plus macOS updates over the large timespan have shown several times that incorrect ACPI code may stop working.

Besides that, we are thinking of whether we can make Linux support nicer in OpenCore apart from custom entries, but this is not in our short list. Even so, with the use of custom entries you can already get rid of grub on Debian-based distros (including Ubuntu).

If you still want to stick with grub, well, it is your choice, but I do not think I will spend my time adding workarounds for its bugs. I can consider reviewing an OpenCore patch if it arrives though.

**Comment by vit9696** [comment]
Basically because the architecture with delayed ACPI patch application is broken design-wise and causes other issues in scenarios we rely on (e.g. chainloading). See this issue and supplied links in it for more details: https://github.com/acidanthera/bugtracker/issues/802

**Comment by MikeBeaton** [comment]
There does seem to be a bug in GRUB, they are pretty clear that you [cannot use `\`](https://www.gnu.org/software/grub/manual/grub/grub.html#File-name-syntax) in a file path spec (and you can't, `\` and `\\` are just ignored), so it seems they are definitely passing on the path incorrectly. They find they file okay themselves, but then seemingly normalise only some of the slashes correctly for FAT in the version which they pass on.

However, the key thing in the setup you're using isn't that OpenCore has been moved into a new subdirectory - it's that the GRUB entry points to OpenCore's bootstrap loader `/EFI/BOOT/BOOTx64.efi`.

So this works, to start OpenCore in its default directory layout, without the need to move any files around:

```
menuentry 'OpenCore' {
        insmod chain
        insmod part_gpt
        insmod fat
        set root=(hd7,gpt10)
        chainloader /EFI/BOOT/BOOTx64.efi
}
```

**Comment by MikeBeaton** [comment]
The fix above is fine. But the path passed in by GRUB is actually correct - despite what seems obvious from the log, it does not have '/' in it. It's a multi-node path being converted to text somewhat misleadingly (by EDK II), always with a '/' between nodes. OC required an outstanding fix to deal with multi-node boot paths. I've put up an attempted update. I am asking @vit9696 to review, but I believe it fixes this issue once and for all.

With the fix applied, I can start OC in its standard layout from GRUB with:

```
menuentry 'OpenCore' {
        insmod chain
        insmod part_gpt
        insmod fat
        set root=(hd7,gpt10)
        chainloader /EFI/OC/OpenCore.efi
}
```

**Comment by vit9696** [comment]
Ouch, that was indeed misleading. I did not realise that the `/` was coming from the printing library and not the path. Yes, that explains the issue. I checked the patch briefly and merged it. Tyvm!

**Comment by MikeBeaton** [comment]
@Xefyr0 - Am hoping (and believe) that the above work-around, and then fix, solve all your issues. Feedback welcome. ;) And feel free to spread the news to 'others' who may be interested - if you are in a position to - that no workarounds are needed any longer.

**Comment by MikeBeaton** [comment]
PS You can download "Artifacts->macOS XCODE5 Artifacts" from here https://github.com/acidanthera/OpenCorePkg/runs/2584308942 to test the updated version.

**Comment by Xefyr0** [comment]
> @Xefyr0 - Am hoping (and believe) that the above work-around, and then fix, solve all your issues. Feedback welcome. ;) And feel free to spread the news to 'others' who may be interested - if you are in a position to - that no workarounds are needed any longer.

@mikebeaton 
I understand that this is quite the late reply, but I've only now updated from OC 0.6.9->0.7.5. The fix you've provided works perfectly, except when UEFI Secure Boot is enabled. When that is the case I'm able to boot using OpenCore.efi with no issue directly from the firmware, but since Vault and UEFI Secure Boot are the last things one does to an EFI after disabling anything used for debugging, trying to chainload OpenCore.efi from GRUB resulted in the boot hanging on a black screen.

With that in mind I made a different OC folder that had a bunch of the debugging settings enabled, signed it and tried to boot it. As with before, booting directly from the firmware worked fine but booting from GRUB failed. That folder, the OC log that came from the boot attempt, my grub config entry for OpenCore and a photo of the onscreen log before it disappeared are all attached in a .zip file if you'd like to take a hack at this. If not, I understand and will continue using the workaround.
[Debug_boot.zip](https://github.com/acidanthera/bugtracker/files/7575423/Debug_boot.zip)

With that said, thank you for the fix and thank you and vit for the effort you have put into OpenCore.

**Comment by mikebeaton** [comment]
> With that said, thank you for the fix and thank you and vit for the effort you have put into OpenCore.

Thank you - though there's a large team behind Vit on OpenCore and an even larger team on the ecosystem around it, of course, and I'm just (proud to be :) ) one recent new member!

This looks like a separate issue, but worth looking at, so I've reposted it at https://github.com/acidanthera/bugtracker/issues/1874 and I'll reply there.
