### ISSUE TITLE
Alps support

### ISSUE THREAD

**Issue by SkyrilHD** [acidanthera/bugtracker#1639]
# Bug description
This issue may be closed as it could be seen as unimportant, but I will try to explain myself as best I can. I don't know if this issue appears to all ALPS users but using Rehabman's and Acidanthera's VoodooPS2 kext has always been an issue. The trackpad does not work, but the keyboard does. I currently have an ALPS v7 trackpad, so the issue might not persist with other versions. The only way to use the ALPS trackpad is to use a [four year old kext by DrHurt](https://github.com/DrHurt/OS-X-ALPS-DRIVER). There are still some issues with this kext: sometimes the keyboard and trackpad do not work after sleep (hit-and-miss situation), the kext conflicts with the VirtualSMC plugin: SMCDellSensors (should I create another bug report or should I post the logs here?), scrolling works very inconsistently and four finger gestures are defined as keyboard shortcuts: ⌃⌥. Since upgrading to Big Sur, I also begin to experience random clicks out of nowhere (I have to wait 10 seconds for the random clicks to stop). Also, sometimes (but got more frequent) while using the trackpad it does this "double-tap and drag" also out of nowhere (I don't know how to describe it). After getting very upset, I decided to report the "bug" and hope to get it fixed. Below I have posted my EFI and logs (First time doing a kext report, so bear with me), I hope it helps. Also maybe VoodooInput might be a big improvement for ALPS trackpads.

I am open and can be available as a tester if you guys want to.

# How I captured logs
First, I booted with DrHurt's kext and grabbed a boot.log with this command `sudo log show --predicate "processID == 0" --start $(date "+%Y-%m-%d") --debug > boot.log`, OpenCore log with Debug version and Lilu log with `-liludbgall liludump=60` as boot-arg and I repeated the same steps with Rehabman's and Acidanthera's kext. If I got it wrong, please tell me.

# Specs
- Model: Dell Latitude E7250
- CPU: Intel Core-i5 5300U
- RAM: 16GB 1600Mhz DDR3
- Trackpad: ALPS v7 Touchpad
- OS: macOS Big Sur 11.3.1

# EFI and Logs
- [EFI.zip](https://github.com/acidanthera/bugtracker/files/6469841/EFI.zip) [Removed SN, AirportItlwm and IntelBlueooth]
- [Bronxteck.zip](https://github.com/acidanthera/bugtracker/files/6469846/Bronxteck.zip)
- [Rehabman.zip](https://github.com/acidanthera/bugtracker/files/6469847/Rehabman.zip)
- [Acidanthera.zip](https://github.com/acidanthera/bugtracker/files/6469848/Acidanthera.zip)
- [VoodooPS2Controller-R6Bronxteck.kext.zip](https://github.com/acidanthera/bugtracker/files/6469852/VoodooPS2Controller-R6Bronxteck.kext.zip) (can also be found [here](https://osxlatitude.com/forums/topic/8285-refined-alps-touchpad-driver/))
- [VoodooPS2Controller-Rehabman-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/6469853/VoodooPS2Controller-Rehabman-DEBUG.zip)
- [VoodooPS2Controller-Acidanthera-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/6469854/VoodooPS2Controller-Acidanthera-DEBUG.zip)

**Comment by vit9696** [comment]
I am pretty sure our VoodooPS2 does not support ALPS at all, and the currently maintained version is in https://github.com/SergeySlice/VoodooPS2-for-ALPS. Does it work well for you? Perhaps @SergeySlice could consider merging this code into our branch, so that all the native gestures become supported.

**Comment by SkyrilHD** [comment]
Oh ok, I assumed your version of VoodooPS2 has support as I saw 'VoodooPS2ALPSGlidePoint.cpp' in the source. SergeySlice's kext does work but the issues/functionality still are the same (not tested broken trackpad after sleep as it happens very randomly). I made a list of working gestures in my repo [here](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/issues/8#issuecomment-669966730) in case you are interested.

**Comment by andreszerocross** [comment]
> Oh ok, I assumed your version of VoodooPS2 has support as I saw 'VoodooPS2ALPSGlidePoint.cpp' in the source. SergeySlice's kext does work but the issues/functionality still are the same (not tested broken trackpad after sleep as it happens very randomly). I made a list of working gestures in my repo [here](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/issues/8#issuecomment-669966730) in case you are interested.

Did you try VoodooPS2 for ALPS from fork of 1Revenger1??? https://github.com/1Revenger1/VoodooPS2-Alps

**Comment by SkyrilHD** [comment]
Yep, already tried. Scrolling is much better but breaks gestures.

**Comment by theroadw** [comment]
Is it possible that your trackpad is also using another transport besides PS2? My Alps V8 trackpad uses PS2 and i2C, and this last one is the better performing kext. Voodooi2C+HID

**Comment by SkyrilHD** [comment]
Nope, tried installing I2C and it did not work.

**Comment by Andrey1970AppleLife** [comment]
feel free to contribute alps support

**Comment by SkyrilHD** [comment]
The problem is that I have no knowledge of C++.  That's why I asked for help here with me providing logs, being tester, etc.  I am currently trying to port some Synaptics codes to ALPS which currently only fixed "smooth" horizontal scrolling.  Now I'm trying to back port gestures, but the end doesn't look good due to lack of knowledge.

Since the current kext doesn't support MT2 emulation, I am not allowed to make a pull request, right?

**Comment by idragon81** [comment]
I'd just like to point out that your VoodooPS2 kext is working perfectly for me in most cases and anybody else having an ALPS trackpad should definitely try out your kext.

Just wanted to put this here since I came here initially while searching for ALPS trackpad support

https://github.com/SkyrilHD/VoodooPS2-ALPS
