### ISSUE TITLE
alternative to nvram reset when OpenCore reporting wrong version

### ISSUE THREAD

**Issue by nijhawank** [acidanthera/bugtracker#1641]
Hi, I recently upgraded from OpenCore 0.6.3 to 0.6.9 and while I can clearly see at the boot screen that it is the correct version, checking via "nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version" or Hackintool v3.5.3(latest) still reports 0.6.3.

I checked the related issue https://github.com/acidanthera/bugtracker/issues/1539 and it suggested a problem in versions prior to 0.6.7 (and mine was 0.6.3) that could cause it and requires a nvram reset. However, I have a Thinkpad that has known issues with nvram reset. So what are options to resolve the version problem or similar issues resulting from lingering old nvram variables.

Can we have some instructions on list of such old /all opencore related nvram variables that we can safely remove with other utilities without performing a full nvram reset? 

Thanks for your help.

**Comment by vit9696** [comment]
Hi. You can always use `dmpstore` Shell command to dump NVRAM contents. Specify the `-all` argument to see all the variables. Afterwards you can inspect what variables do you have, find the ones that have `NV` (non-volatile) attribute and remove them manually with `nvram -d <GUID>:<name>` command in macOS. All the GUIDs OpenCore and Apple operating systems use are listed in `Configuration.pdf` manual.

For the legacy variable with OpenCore version the command should be `nvram -d 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version`. But that may not help if your NVRAM is full and is refusing to perform NVRAM I/O, which often is the case when weird things with NVRAM happen. Usually the solution is to do NVRAM reset. Is there any issue with your laptop on this?

**Comment by LeeBinder** [comment]
how likely is it that @nijhawank died within a day .. 👎
