### ISSUE TITLE
NVMeFix Pm991 support

### ISSUE THREAD

**Issue by richibrics** [acidanthera/bugtracker#1642]
Hi I have a Lenovo laptop that has a Samsung Pm991 SSD: MZALQ512HALU-000L2

Very often when I try to write/read on an APFS (or NTFS) partition on the SSD, the laptop freezes and I have to shutdown it. I installed macOS on my external HDD to work on the problem but I haven't found a solution yet.

I'm a developer so if you are interested in working at adding the support for this SSD I could help you (in NVMeFix README there's writtern "Other incompatibilities with third-party SSDs may be addressed").

I am willing to provide you all the support with logs/debugs.

You can find my Opencore EFI, Opencore log, LILU log and panic text [in this repo](https://github.com/richibrics/OC_EFI_NVMeFIxDebugging).

Thank you

**Comment by vit9696** [comment]
In short, it is not easy. We spent some time reverse-engineering Apple stack, but it was not clear what is the problem. Samsung drives have architecture issues with the APFS filesystem anyway, so to be honest a better route is not to use them. See the other issues on this repo regarding SSDs as well as https://github.com/dortania/bugtracker/issues/192.

**Comment by richibrics** [comment]
There's no chance that the solution is similar to the Pm981 one ?

**Comment by vit9696** [comment]
PM981 are also unsupported as only a small chunk of the issues is addressed.

**Comment by jadeastar** [comment]
PM981 still does not work on APFS or HFS+!
