### ISSUE TITLE
Intel Celeron J1800 support

### ISSUE THREAD

**Issue by ghost** [acidanthera/bugtracker#1643]
I'm trying to start OpenCore (0.6.9) on my PC, but it stuck before show the picker and I don't understand where is the problem. I know that my CPU is unsupported (Celeron J1800) but reading around i cloud be possibile run on it.

If I run OC debug version with Debug:Target to 67 i can get only the info below with any errors or info to understand why picker not show up. There is some settings to get more debug details?

On Screen:
```
BS: Starting OpenCore application...
BS: Booter path - \EFI\BOOT\BOOTX64.EFI
OCFS: Trying to locate filesystem on 77639298 7738A398
OCFS: Filesystem DP - \EFI\BOOT\BOOTX64.EFI
BS: Trying to load OpenCore image...
BS: Relative path - EFI
BS: Startup path - EFI\OpenCore.efi (0)
BS: fallback to absolute path - EFI\OC\OpenCOre.efi
BS: Read OpenCore image 880640 bytes
OCM: Loaded image at 76BC3898 handle
OCM: Loaded image has DeviceHandle 77639298 FilePath 76BC3818 ours DevicePath 76BC4B18
OCCPU: Failed to get FSBFrequency data using Apple Platform Info - Not Found
OC: Starting OpenCore...
OC: Booter path - EFI\OC\OpenCore.efi
OCFS: Trying to locate filesystem on 77639298 76BC3B18
OCFS: Filesystem DP - EFI\OC\OpenCore.efi
OC: Absolute booster path - EFI\OC\OpenCore.efi
OCST: Missing vault data, ignoring...
OC: OcMiscEarlyInit...
OC: Loaded configuration of 9828 bytes
OC: Watchdog status is 0
```

On Log File:
```
00:000 00:000 OC: OpenCore DBG-069-2021-05-03 is loading in Optional mode (0/0)...
00:686 00:686 OC: Boot timestamp - 2021.05.15 19:47:59
01:014 00:327 OCCPU: MP services threads 2 (enabled 2) - Success
01:350 00:336 OCCPU: MP services Pkg 1 Cores 2 Threads 1 - Success
01:635 00:284 OCCPU: Found       Intel(R) Celeron(R) CPU  J1800  @ 2.41GHz
01:968 00:332 OCCPU: Signature 30678 Stepping 8 Model 37 Family 6 Type 0 ExtModel 3 ExtFamily 0 uCode 836
02:299 00:331 OCCPU: EIST CFG Lock 0
02:548 00:248 OCCPU: Timer address is 0 from Unknown INTEL
02:951 00:403 OCCPU: Failed to get FSBFrequency data using Apple Platform Info - Not Found
03:283 00:331 OCCPU: Intel TSC:           0Hz,     0MHz; FSB:   100000000Hz,   100MHz; MaxBusRatio: 29
```

**Comment by vit9696** [comment]
Well, needs CPUID support in OpenCore as your CPU is currently undetected. It most likely dies by taking the wrong route in https://github.com/acidanthera/OpenCorePkg/blob/717ce1886166b4cc7cca6d2bf1acb8ac3749cb78/Library/OcCpuLib/OcCpuLib.c#L546. If you want to submit a patch, please introduce a BayTrail generation for your CPU and change the if I sent above.

**Comment by vit9696** [comment]
Try https://github.com/acidanthera/OpenCorePkg/commit/5c7d61f4168f1eff4167acc7d5452db8c0913325. It will still probably work weirdly, as FSB frequency detection seems to fail.

**Comment by stormenergy91** [comment]
With this build now the picker is shown , i can select the install but it stuck on [EB|LOG:EXITBS:START].
Now i think is a kernel related problem.

If you want to check the full log you can get it from here: https://drive.google.com/file/d/1S15aiyUNIovZAtYN0nBBPO0r5yJyjCh7/view?usp=sharing

**Comment by vit9696** [comment]
Actually it is still quite broken even before the kernel. The CPU frequency is wrong and the core count is also wrong (OCCPU: Pkg 1 Cores 8 Threads 16). Could you create SysReport and upload it here? Speaking of the kernel, I think you will need a virtual CPUID.

**Comment by stormenergy91** [comment]
Sure, how I can create a SysReport? For the kernel I already set this
```
<key>Cpuid1Data</key>
<data>wwYDAAAAAAAAAAAAAAAAAA==</data>
<key>Cpuid1Mask</key>
<data>/////wAAAAAAAAAAAAAAAA==</data>
<key>DummyPowerManagement</key>
<true/>
```
is this what you meaning "virtual CPUID"?

**Comment by andreszerocross** [comment]
> Sure, how I can create a SysReport? For the kernel I already set this
> 
> ```
> <key>Cpuid1Data</key>
> <data>wwYDAAAAAAAAAAAAAAAAAA==</data>
> <key>Cpuid1Mask</key>
> <data>/////wAAAAAAAAAAAAAAAA==</data>
> <key>DummyPowerManagement</key>
> <true/>
> ```
> 
> is this what you meaning "virtual CPUID"?

Use Debug version of latest OpenCore, and set SysReport=Yes in config.plist

![image](https://user-images.githubusercontent.com/9614101/118541985-92b38b80-b77c-11eb-8768-b29716525624.png)

Then reboot to GUI OC,, 

Then you can check, OC will create SysReport folder in EFI folder of your EFI partition

**Comment by stormenergy91** [comment]
Here the SysReport folder: https://drive.google.com/file/d/12CO7rLEwiNTvpSAlshzk2g--miTmYEpA/view?usp=sharing

**Comment by vit9696** [comment]
For the frequency we could either read it via ACPI PM timer:

```
[0D0h 0208  12]               PM Timer Block : [Generic Address Structure]
[0D0h 0208   1]                     Space ID : 01 [SystemIO]
[0D1h 0209   1]                    Bit Width : 20
[0D2h 0210   1]                   Bit Offset : 00
[0D3h 0211   1]         Encoded Access Width : 03 [DWord Access:32]
[0D4h 0212   8]                      Address : 0000000000000408
```

or use the Linux approach with predefined tables (https://github.com/torvalds/linux/blob/master/arch/x86/kernel/tsc_msr.c).

For the core/thread count I am still far from sure how to properly do it.
