### ISSUE TITLE
[AppleALC] alc-verb doesn't work correctly

### ISSUE THREAD

**Issue by WingLim** [acidanthera/bugtracker#1644]
Since [61e2bbf](https://github.com/acidanthera/AppleALC/commit/61e2bbfe74bf1c12ebf770ed4a9776a04a7758f2) is applied to AppleALC, we could send hda-verb command through AppleALC by adding `alcverbs=1`.

But there has a weird problem, my computer using ALC255 and I use the `layout-id` 66, then everything work except the headset micphone.

The I find a patch in [patch_realtek.c#L5026](https://github.com/torvalds/linux/blob/d07f6ca923ea0927a1024dfccafc5b53b61cfecc/sound/pci/hda/patch_realtek.c#L5026) which can make micphone work with [VerbStunb.kext](https://github.com/hackintosh-stuff/ComboJack/tree/master/ComboJack_Installer/VerbStub.kext/Contents) something like CodecCommander.

Use `hda-verb` execute the patch I mention above.

`0x500` is `SET_COEF_INDEX`
`0x400` is `SET_PROC_COEF`

```bash
hda-verb 0x20 0x500 0x45
hda-verb 0x20 0x400 0xd489

hda-verb 0x20 0x500 0x1b
hda-verb 0x20 0x400 0x0c2b

hda-verb 0x57 0x500 0x03
hda-verb 0x57 0x400 0x8ea6
```

But I can not use `alc-verb` to execute above patch, It only work by remove the verb `00` like this:

```bash
alc-verb 0x20 0x500 0x45
alc-verb 0x20 0x4d4 0x89 # here

alc-verb 0x20 0x500 0x1b
alc-verb 0x20 0x40c 0x2b # here

alc-verb 0x57 0x500 0x03
alc-verb 0x57 0x48e 0xa6 # and here
```

I try to read the AppleALC source code, but stop at [kern_alc.cpp#L332:22](https://github.com/acidanthera/AppleALC/blob/58b57ee76bcef5e976b59885463493e6b5623e36/AppleALC/kern_alc.cpp#L332:22)
```cpp
IOReturn AlcEnabler::IOHDACodecDevice_executeVerb(void *hdaCodecDevice, uint16_t nid, uint16_t verb, uint16_t param, unsigned int *output, bool waitForSuccess){
	DBGLOG("alc", "IOHDACodecDevice::executeVerb with parameters nid = %u, verb = %u, param = %u", nid, verb, param);
	return FunctionCast(IOHDACodecDevice_executeVerb, callbackAlc-&gt;orgIOHDACodecDevice_executeVerb)(hdaCodecDevice, nid, verb, param, output, waitForSuccess);
}
```

Don't know how AppleALC execute verb command, and why the problems arise.

**Comment by vit9696** [comment]
The code is provided to us by AppleHDA, so it is not open-source. We are not sure either, perhaps there is a difference in argument format or Apple implementation is more limited. As long as you have a workaround, this will probably be it.

cc @black-dragon74

**Comment by mikebeaton** [comment]
This was resolved by the commit above, and `alc-verb` now accepts exactly the Linux format without any parameter edits needed.
