### ISSUE TITLE
Wireless Network Card not recognized after S4 hibernation

### ISSUE THREAD

**Issue by antoniomcr96** [acidanthera/bugtracker#1646]
First of all, thanks for all your work.
I have some problem in resuming my laptop from state s4 (hibernation). In particular, it seems that the device and vendor id of a BCM94350ZAE network card are not recognized. I use **AirportBrcmFixup**. This is a log after resuming from hibernation:
```
[  234.201330]: ARPT: **pci restore invalid deviceid 0xffffffff**
[  234.201436]: ARPT: 154.651835: wl0: fatal error, reinitializing, total count of reinit's[1], @'wlc_verify_d3_exit':48356
[  234.201519]: ARPT: 154.651919: SMC['MSWo']: rdData[0xff] rcrd[132]
[  234.202704]: ARPT: 154.653104: wl_dump_all_hw_regs - hw_up[0] Starting dumps...
[  234.222128]: ARPT: 154.672526: wl0: fatal error, reinitializing, total count of reinit's[2], @'wl_nocard_war':6284
[  234.735255]: ARPT: 155.185654: AirPort_Brcm43xx::powerChange: System Wake - Full Wake/ Dark Wake / Maintenance wake
[  234.735278]: ARPT: 155.185677: IOPMPowerSource Information: onWake,  SleepType: Standby,  'ExternalConnected': No, 'TimeRemaining': 37, 
[  234.735317]: ARPT: 155.185716: AirPort_Brcm43xx::platformWoWEnable: WWEN[disable], in_fatal_err[0]
[  234.736688]: ARPT: 155.187087: wl0: _wlc_ioctl: dead chip, off[0] bar0[0xffffffff]
[  234.739435]: ARPT: 155.189835: wl0: wl_update_tcpkeep_seq: Original Seq: 3822268442, Ack: 3974522364, Win size: 385
[  234.739454]: ARPT: 155.189853: wl0: wl_update_tcpkeep_seq: Updated seq/ack/win from UserClient Seq 3822268442, Ack 3974522364, Win size 385
[  234.739835]: ARPT: 155.190234: AirPort_Brcm43xx::syncPowerState: WWEN[disabled]
[  234.739853]: ARPT: 155.190252: wl0: _wlc_ioctl: dead chip, off[0] bar0[0xffffffff]
[  234.739905]: ARPT: 155.190305: Clear UC AER: ffffffff
[  234.739914]: ARPT: 155.190313: Clear Corr AER: ffffffff
[  234.739920]: ARPT: 155.190319: Clear DEV_STS: ffffffff
[  234.739925]: ARPT: 155.190325: Clear CFG_STAT:     ffff
[  235.051730]: ARPT: 155.502129: VendorID check failed! vendorId[ffff] != 14e4
[  236.052752]: ARPT: pci restore invalid deviceid 0xffffffff
[  236.053012]: ARPT: 156.503409: wl0: fatal error, reinitializing, total count of reinit's[3], @'wlc_verify_d3_exit':48356
[  236.053327]: ARPT: 156.503725: wl0: fatal error, reinitializing, total count of reinit's[4], @'wl_nocard_war':6284
[  236.071318]: ARPT: 156.521718: wl0: _wlc_ioctl: dead chip, off[0] bar0[0xffffffff]
[  236.071348]: ARPT: 156.521748: wl0: _wlc_ioctl: dead chip, off[0] bar0[0xffffffff]
```

1. With normal boot, AirPortBrcmFixup correctly recognizes device and vendor id:
`[    0.842499]: AirportBrcmFixup    BRCMFX: @ (DBG) Configuration::readArguments: Broadcom BCM4350 chipset is detected, subsystem-vendor-id = 0x17aa, subsystem-id = 0x075a`
This doesn't happen after hibernation.

2. If my laptop then goes to normal sleep (S3) (also with the "dead chip" after hibernation), after resuming Wifi restarts working normally.

**Comment by vit9696** [comment]
The card looks dead, ffff means that there is no hardware. The reason may be ASPM (you may need to disable it) or some other issue in your hardware. CC @lvs1974

**Comment by antoniomcr96** [comment]
> The card looks dead, ffff means that there is no hardware. The reason may be ASPM (you may need to disable it) or some other issue in your hardware. CC @lvs1974

Yes, the problem was ASPM. When AirportBrcmFixup disables ASPM, some problems persist.

For information only, masking pin 53 as suggested here: https://github.com/acidanthera/bugtracker/issues/794#issue-591260758 solves the problem. Wifi isn't dead after s4 hibernation anymore.
This solves also the fact that wifi, if disabled before sleep, will result dead after sleep (impossible to enable it).
I used brcmfx-aspm set to 255 in deviceproperties as suggested here: https://github.com/acidanthera/AirportBrcmFixup/releases/tag/2.0.9

Hope it could be useful for someone.
