### ISSUE TITLE
no HDMI audio on HD530

### ISSUE THREAD

**Issue by hotlemon2003** [acidanthera/bugtracker#1647]
Hello! I am facing no HDMI audio over HD530 (igpu) using 1.6.0 version. It works fine in 1.5.5. Didn't try the versions in between

**Comment by andreszerocross** [comment]
@Andrey1970AppleLife  this is true,, i have checked it. With latest AppelALC.kext HDMI audio is gone, with ALC 1.5.5 HDMI audio is back.

![image](https://user-images.githubusercontent.com/9614101/119223591-833d9500-bb24-11eb-989f-dd1c1d20e83c.png)

**Comment by andreszerocross** [comment]
@Andrey1970AppleLife  start from AppleALC.kext 1.5.9, HDMI audio is gone.

My setup is 
Motherboard : Z170X Gaming 7
Processor : Intel Core i7 6700
Just use IGPU, i didn't use any dGPU.

AppleALC 1.5.5, 1.5.6, 1.5.7 and 1.5.8 are working good with HDMI Audio

**Comment by andreszerocross** [comment]
![image](https://user-images.githubusercontent.com/9614101/119223856-f72c6d00-bb25-11eb-9fd7-c518bea2008c.png)

it looks this commit cause the problem

**Comment by vit9696** [comment]
Find the exact commit, not speculate. CC @dhinakg

**Comment by andreszerocross** [comment]
> Find the exact commit, not speculate. CC @dhinakg

I have comment it "specified commit", a patch by @dhinakg  cause this problem

**Comment by vit9696** [comment]
You did not. Where is a link to the exact commit? Does reverting this change in the current version of AppleALC solve the problem?

**Comment by andreszerocross** [comment]
> You did not. Where is a link to the exact commit? Does reverting this change in the current version of AppleALC solve the problem?

Yes, revert this commit fix HDMI audio

**Comment by vit9696** [comment]
The commit is https://github.com/acidanthera/AppleALC/commit/28c1243de534abb23e38f2d53782fbf68771d554. REF: https://github.com/acidanthera/AppleALC/pull/669

**Comment by andreszerocross** [comment]
![image](https://user-images.githubusercontent.com/9614101/119224795-61dfa780-bb2a-11eb-9a70-d803476f3f85.png)

I have disabled that patch, and compile applealc and HDMI Audio is working again

**Comment by dhinakg** [comment]
What is the PCI ID of your controller? I'm guessing it's `8086:A170` but just want to check. You can check by opening IORegistryExplorer, finding `HDEF`, and then looking for the `name` property.

**Comment by andreszerocross** [comment]
> What is the PCI ID of your controller? I'm guessing it's `8086:A170` but just want to check. You can check by opening IORegistryExplorer, finding `HDEF`, and then looking for the `name` property.
> 
> Also, please report which macOS versions you've tested and your motherboard/laptop model. If this issue's just limited to desktops then I can adjust the patch to only touch laptops.

Ofcorse it A170.

![image](https://user-images.githubusercontent.com/9614101/119234742-9b7bd700-bb59-11eb-811d-cc68255b05d4.png)


![image](https://user-images.githubusercontent.com/9614101/119234754-a8002f80-bb59-11eb-9c7a-b1365c715f7a.png)

**Comment by andreszerocross** [comment]
> What is the PCI ID of your controller? I'm guessing it's `8086:A170` but just want to check. You can check by opening IORegistryExplorer, finding `HDEF`, and then looking for the `name` property.
> 
> Also, please report which macOS versions you've tested and your motherboard/laptop model. If this issue's just limited to desktops then I can adjust the patch to only touch laptops.

My setup is
Motherboard : Z170X Gaming 7
Processor : Intel Core i7 6700
OS Version : Big Sur 11.3.1

**Comment by vit9696** [comment]
I suggest restricting the patch to laptop setups only:

```diff
$ git diff
diff --git a/Resources/Controllers.plist b/Resources/Controllers.plist
index e15ebcd..fa7e667 100644
--- a/Resources/Controllers.plist
+++ b/Resources/Controllers.plist
@@ -784,6 +784,8 @@
        <dict>
                <key>Device</key>
                <integer>41328</integer>
+               <key>Model</key>
+               <string>Laptop</string>
                <key>Name</key>
                <string>100 Series (0xA170) Mobile PCH HD Audio</string>
                <key>Patches</key>
```

**Comment by andreszerocross** [comment]
> I suggest restricting the patch to laptop setups only:
> 
> ```diff
> $ git diff
> diff --git a/Resources/Controllers.plist b/Resources/Controllers.plist
> index e15ebcd..fa7e667 100644
> --- a/Resources/Controllers.plist
> +++ b/Resources/Controllers.plist
> @@ -784,6 +784,8 @@
>         <dict>
>                 <key>Device</key>
>                 <integer>41328</integer>
> +               <key>Model</key>
> +               <string>Laptop</string>
>                 <key>Name</key>
>                 <string>100 Series (0xA170) Mobile PCH HD Audio</string>
>                 <key>Patches</key>
> ```

I will try this, will report soon

**Comment by andreszerocross** [comment]
I follow that change and recompile applealc, and it's still working fine. cc @dhinakg @vit9696 @vandroiy2013 

![Screen Shot 2021-05-23 at 00 58 37](https://user-images.githubusercontent.com/9614101/119236523-147f2c80-bb62-11eb-93ab-b48f0d1d2b93.png)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/AppleALC/commit/9a3d563c49b8ead75dba306914ce1d85fce9f558
