### ISSUE TITLE
Holding Alt or Esc key on laptop keyboard not working.

### ISSUE THREAD

**Issue by b4iterdev** [acidanthera/bugtracker#1649]
My efi https://github.com/b4iterdev/opencore-dell-inspriron-14-3467.
When I set cho ShowPicker = OFF, and everytime I want to change boot option which I need to hold Alt or Esc to get the boot option, but it's working. However, holding Command + R does take me to Recovery, which is strange. 
I also tried to enable FileVault and the keyboard is fully working!
Sorry that I didn't include any logs as I'm using HDD which is really slow for me to boot it up with entire log writing to disk.

**Comment by MikeBeaton** [comment]
It is very useful - mostly indispensable - to get the log file, even if it's very slow to boot.

I believe you are right, if your system is detecting CMD+R reliably, then it should be detecting ESC or ALT reliably too.

I wonder if you can capture two logs, one while booting successfully with CTRL+R - you should only need to hold those keys near the end of the boot, but confirm that it actually got detected and tried to enter Recovery. And one showing _ESC_ not working (again you only need to be holding this key down towards the end of boot; but make sure you _are_ holding it at the right time).

**Comment by vit9696** [comment]
Many laptops cannot detect ALT without another key, e.g. ALT+letter. ESC usually works, but some laptops do intercept ESC during boot, so at the time you reach OpenCore ESC input is cleared.

Try increasing TakeoffDelay and also try pressing ESC multiple times instead of holding. This should generally work on all setups.
