### ISSUE TITLE
Kernel Panic in IONVMEController with SSD NVME M.2 KingDian 

### ISSUE THREAD

**Issue by augustoperes1** [acidanthera/bugtracker#1650]
My SSD gives a kernel panic just when I inject this kext. It is an [NVME SSD from KingDian](https://http2.mlstatic.com/D_NQ_NP_702451-MLB44909483021_022021-O.webp), purchased on AliExpress. It has a [Silicon Motion](https://www.siliconmotion.com/products/client/detail) controller, model SM2263EN/XT. Could it be incompatibility?
![Hackintool showing the identification of the PCIe hardware](https://i.imgur.com/3Xb1N4N.png)
![Picture of Kernel Panic](https://i.imgur.com/ceAyzQT.jpg)
![Picture of Kernel Panic](https://i.imgur.com/Al444N2.jpg)
![My EFI](https://i.imgur.com/nSssRbD.png)
![My config.plist](https://i.imgur.com/uIfmxYA.png)
## Log: https://drive.google.com/file/d/120LUyhoIPYpFdKRAPzXuS9DVRWLhSjCf/view?usp=sharing

**Comment by vit9696** [comment]
Does not look like your SSD is causing problems, it is more like it is a race condition. Check that you have DisableLinkeditJettison enabled.

**Comment by augustoperes1** [comment]
> Does not look like your SSD is causing problems, it is more like it is a race condition. Check that you have DisableLinkeditJettison enabled.

it's activate
