### ISSUE TITLE
When using alc-verb, the device number often switches between analog and digital

### ISSUE THREAD

**Issue by wern-apfel** [acidanthera/bugtracker#1651]
Means that analog audio is often the second device and I have to use alc-verb -d 1 to address it. When digital audio is disabled, there are no issues.

**Comment by vit9696** [comment]
You should be able to determine the device with `-l` argument though (https://github.com/acidanthera/AppleALC/commit/bdd48b9b7cc0c269afb6614dbad122209830f285).

**Comment by wern-apfel** [comment]
It doesn't work, I get this output.

alc-verb 0x0 0xf00 0x0
nid = 0x0, verb = 0xf00, param = 0x0
Failed to open ALCUserClientProvider service at IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/HDEF@1F,3/AppleHDAController@1F,3/IOHDACodecDevice@1F,3,0/ALCUserClientProvider.
0xe00002bc

**Comment by vit9696** [comment]
Yeah, sorry, already fixed in master.

**Comment by wern-apfel** [comment]
Ok, it works now. Let's see if it's still varying. Thanks.
