### ISSUE TITLE
Fix mute on Conxexant 20724

### ISSUE THREAD

**Issue by Human7900** [acidanthera/bugtracker#1652]
When you use alcid=3 or alcid=13 the audio works but mute doesn't work. So, someone on Reddit gave me a AppleALC.kext and voila, mute started working including the external mute button on my HP Probook 430 G3. So I thought if it could be included in the AppleALC. Attaching the AppleALC.kext(the one with mute working).
Regards
[AppleALC.kext with working mute.zip](https://github.com/acidanthera/bugtracker/files/6553177/AppleALC.kext.with.working.mute.zip)

**Comment by vit9696** [comment]
no source code

**Comment by Human7900** [comment]
How can I extract the source code?

**Comment by Human7900** [comment]
Please tell.

**Comment by MikeBeaton** [comment]
Using Reddit, possibly?

**Comment by Human7900** [comment]
Yeah sure,why not?

**Comment by MikeBeaton** [comment]
Oh - let us know if you track it down, would be useful.

**Comment by Human7900** [comment]
I have changed some settings myself to fix mute. Opened a PR.
