### ISSUE TITLE
OpenCanopy  support for `<TOOLPATH>.lbl`/`.l2x` pre-drawn entry labels

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1653]
Hi, today I've tested OpenCore at commit https://github.com/acidanthera/OpenCorePkg/commit/eb5cc3ee62c06f111931a5e20ed584085ac28d1f and I saw the new flavour implementation by @MikeBeaton, so after having read the docs, I could not find out how to deal with the `ResetNVRAM.icns` image that I used to copy inside `Resources/Image/Acidanthera/GoldenGate`, `Resources/Image/Acidanthera/Syrah` and `Resources/Image/Acidanthera/Chardonnay` provided by OcBinaryData.

I suppose this commit https://github.com/acidanthera/OpenCorePkg/commit/eb5cc3ee62c06f111931a5e20ed584085ac28d1f removed support for such discovery. `Entries` and `Tools` sections are empty, since the NVRAMReset tool is embedded inside OpenCore, so no path (therefore the entry/flavour) has to be specified, and in the docs this is mentioned as well: 

https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Flavours.md#nvram-tools

**ResetNVRAM:NVRAMTool**: *it is automatically used for the entry created by config setting AllowNvramReset, or to use for the CleanNvram.efi tool.*

The problem is that with the changes mentioned above, the Reset NVRAM entry does not appear anymore, while it was working perfectly at commit: https://github.com/acidanthera/OpenCorePkg/commit/acd32171f4515ca4ac31b4be117b09bc71d3cfec

I can provide logs if necessary, concerning `OCUI`

```
00:000 00:000 OC: OpenCore DBG-070-2021-05-28 is loading in Secure mode (1/1)...
03:831 00:167 OC: Driver OpenCanopy.efi at 2 is being loaded...
04:841 00:167 OC: Driver OpenCanopy.efi at 2 is successfully loaded!
04:673 00:168 OCUI: Registered custom GUI protocol
87:642 00:165 OCUI: Failed to load image (1/1) Resources\Image\Acidanthera\GoldenGate\Background.icns prefix:Acidanthera\GoldenGate icon:0 - Not Found
87:820 00:177 OCUI: Failed to load image (1/2) Resources\Image\Acidanthera\GoldenGate\Apple.icns prefix:Acidanthera\GoldenGate icon:1 - Not Found
88:000 00:179 OCUI: Failed to load image (2/2) Resources\Image\Acidanthera\GoldenGate\ExtWindows.icns prefix:Acidanthera\GoldenGate icon:1 - Not Found
88:164 00:164 OCUI: Failed to load image (1/2) Resources\Image\Acidanthera\GoldenGate\Other.icns prefix:Acidanthera\GoldenGate icon:1 - Not Found
88:330 00:165 OCUI: Failed to load image (2/2) Resources\Image\Acidanthera\GoldenGate\ExtTool.icns prefix:Acidanthera\GoldenGate icon:1 - Not Found
88:497 00:167 OCUI: Failed to load image (2/2) Resources\Image\Acidanthera\GoldenGate\ExtResetNVRAM.icns prefix:Acidanthera\GoldenGate icon:1 - Not Found
88:662 00:165 OCUI: Failed to load image (2/2) Resources\Image\Acidanthera\GoldenGate\ExtShell.icns prefix:Acidanthera\GoldenGate icon:1 - Not Found
88:829 00:166 OCUI: Info->fontSize 10 Info->bitField 192 Info->charSet 0 Info->stretchH 100 Info->aa 1
88:993 00:163 OCUI: Info->paddingUp 0 Info->paddingRight 0 Info->paddingDown 0 Info->paddingLeft 0
89:157 00:164 OCUI: Info->spacingHoriz 1 Info->spacingVert 1 Info->outline 0 Info->fontName 
120:334 00:163 OCUI: Console attributes: 0
120:336 00:001 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
120:345 00:002 OCUI: Console attributes: 0
120:347 00:001 OCUI: UseDiskLabel: 0, UseGenericLabel: 0
120:355 00:002 OCUI: Using flavour icon, custom: 0
```

**Comment by 1alessandro1** [comment]
I've also renamed the `ResetNVRAM.icns` to `NVRAMTool.icns` but this still does not fix the problem

**Comment by 1alessandro1** [comment]
Bug description can be found here:

https://github.com/acidanthera/OpenCorePkg/pull/263#issuecomment-850559315

**Comment by 1alessandro1** [comment]
Closing this, I'm going to open a better one without unnecessary details

**Comment by MikeBeaton** [comment]
It's better to carry on in this Issue, rather than comment on the pull request.

Can you clarify is it the entry that is not appearing, or just the correct icon for it that is not appearing?

Could you share the config.plist you are using? (Feel free to redact any sensitive information such as passwords and Mac serial numbers.)

You mentioned PickerVariant=Default, but the correct value should be Auto. However that doesn't seem to be the problem since it's looking in the right folder. In the OCUI: log fragment you've shared above ResetNVRAM.icns _is_ being loaded (only ExtResetNVRAM.icns is not).

**Comment by MikeBeaton** [comment]
Okay, your other issue #1654 is indeed clearer. Closing this again, and jumping to there.
