### ISSUE TITLE
[OpenCanopy] When AllowToggleSip is set to false NVRAM reset entry is not loaded

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1654]
OpenCore version (commit): https://github.com/acidanthera/OpenCorePkg/commit/eb5cc3ee62c06f111931a5e20ed584085ac28d1f

When `AllowToggleSip` set to `Disabled` and `AllowNvramReset` is set to `Enabled` the Reset NVRAM entry is not loaded.

If I enable `AllowToggleSip` OpenCanopy will load the default `Tool.icns` icon (since I have no interest of adding a specific image for the SIP tool) and now both of them show up, Reset NVRAM in OpenCanopy with the icon I've chose, with AllowToggleSIP

- Settings:
   ![image](https://user-images.githubusercontent.com/46293832/120023011-7e2d8980-bfed-11eb-9c7c-ff7fbfe11931.png)

- Result:
   ![28173515](https://user-images.githubusercontent.com/46293832/120022092-30645180-bfec-11eb-87e5-37072cbb7132.png)

To reproduce the bug one should enable only `AllowNvramReset` and disable `AllowToggleSip`, the Reset NVRAM entry does not appear anymore

- Settings:
   ![image](https://user-images.githubusercontent.com/46293832/120022982-740b8b00-bfed-11eb-961d-1f8288e7ec1b.png)

- Result:
   ![28174214](https://user-images.githubusercontent.com/46293832/120022935-62c27e80-bfed-11eb-92a2-41a82aac1fc3.png)

**Comment by 1alessandro1** [comment]
> Can you clarify is it the entry that is not appearing, or just the correct icon for it that is not appearing?

I can try to disable OpenCanopy and see if this behaviour is present in the `Builtin` picker as well (to isolate the icon problem)

> Could you share the config.plist you are using? (Feel free to redact any sensitive information such as passwords and Mac serial numbers.)

Sure, here it is:  [config.plist.zip](https://github.com/acidanthera/bugtracker/files/6562771/config.plist.zip)

> You mentioned PickerVariant=Default, but the correct value should be Auto. However that doesn't seem to be the problem since it's looking in the right folder. In the OCUI: log fragment you've shared above ResetNVRAM.icns is being loaded (only ExtResetNVRAM.icns is not).

Yeah I think so. I chose Default since I'm going to use the `GoldenGate` theme only, but I can set that to `Auto` too

Let me know if after you've followed the steps to reproduce this issue, if this is present on your side too.

**Comment by 1alessandro1** [comment]
@MikeBeaton
> I can try to disable OpenCanopy and see if this behaviour is present in the Builtin picker as well (to isolate the icon problem)

I confim this behaviour from `Builtin` picker as well, is not a problem of

- Settings:
   ![Screenshot 2021-05-28 at 20 52 54](https://user-images.githubusercontent.com/46293832/120030020-357ace00-bff7-11eb-8e0b-8f5e263c821e.png)
 the `icns` file

- Result:
   
![2021-05-28 20 55 17](https://user-images.githubusercontent.com/46293832/120030071-462b4400-bff7-11eb-989d-90976631fadc.jpg)

**Comment by MikeBeaton** [comment]
Should be fixed https://github.com/acidanthera/OpenCorePkg/commit/5a7ea942f5f6e6ad89dc191598119c51c1ff6255 - thanks again

**Comment by 1alessandro1** [comment]
Yes I confirm it's working perfectly now, thank you for your time!
