### ISSUE TITLE
Correct values to use for disable SIP

### ISSUE THREAD

**Issue by MikeBeaton** [acidanthera/bugtracker#1657]
I've got this comment from @startergo on Macrumors:

> Bmju said:
CSR_ALLOW_UNAUTHENTICATED_ROOT (0x800) is not practical as it prevents incremental (non-full) OTA updates.
I am using all the time 87F which includes 0x800 and I can update BS. Which update is prevented?
87F= csrutil disable + csrutil authenticated-root disable
Issued from recovery.

I think there's a lack of clarity as to whether what has been included in the docs is really representing people's day-to-day experience - whatever the theory (coming ofc not just from the OC team, but e.g. here too: https://osxlatitude.com/forums/topic/11553-how-do-i-disable-sip-system-integrity-protection/).

@startergo - Are you stating that you get not only _OTA_ updates, but also incremental OTA updates, running essentially all the time with 0x87F? (Just to be clear exactly what the report is.)

Would anyone else, e.g. @cdf, like to comment?

**Comment by MikeBeaton** [comment]
Relevant lines of current documentation:

https://github.com/acidanthera/OpenCorePkg/blob/36b04ca3cda8f2ca204bc2c6a23fb09fb3592dd3/Docs/Configuration.tex#L3758-L3770

> _Note2_: OC uses `0x26F` even though `csrutil disable` on Big Sur sets `0x7F`. To explain the choice:                  
• `csrutil disable --no-internal` actually sets `0x6F`, and this is preferable because `CSR_ALLOW_APPLE_INTERNAL` (`0x10`) prevents updates (unless you are running an internal build of macOS).
• `CSR_ALLOW_UNAPPROVED_KEXTS` (`0x200`) is generally useful, in the case where you do need to have SIP disabled, as it allows installing unsigned kexts without manual approval in System Preferences.
• `CSR_ALLOW_UNAUTHENTICATED_ROOT` (`0x800`) is not practical as it prevents incremental (non-full) OTA updates.

**Comment by MikeBeaton** [comment]
Got this response, over on the thread:

> I am getting OTA and incremental updates with 87F which is the Apple default SIP+authenticated-root in latest BS. When BS came out originally it was 877, but then it changed to 87F.

**Comment by MikeBeaton** [comment]
So, @startergo, I've run some tests, and I'm getting results _exactly_ in accord with what I was (apparently entirely rightly!) asked to document in the first place:

![Screenshot 2021-05-30 at 23 23 11](https://user-images.githubusercontent.com/11946605/120122408-719d6280-c1a0-11eb-9687-a823899f0ceb.png)
![Screenshot 2021-05-30 at 23 25 10](https://user-images.githubusercontent.com/11946605/120122409-73672600-c1a0-11eb-8489-d947842675da.png)
![Screenshot 2021-05-30 at 23 27 06](https://user-images.githubusercontent.com/11946605/120122411-73ffbc80-c1a0-11eb-980d-34987b510fab.png)
![Screenshot 2021-05-30 at 23 29 00](https://user-images.githubusercontent.com/11946605/120122412-74985300-c1a0-11eb-9c78-4f34963d324d.png)

I haven't been able to check the 0x800 bit yet - i.e. I haven't been able to wrangle my system into a state where it's offering me an incremental update yet.

I think I should close for now. As ever on this bugtracker closed issues _are_ monitored, and if you can provide any screenshots along the lines of the above, showing that you have a machine where the currently documented warnings do NOT apply, then you are welcome to upload them and they will be received with genuine interest.

**Comment by startergo** [comment]
![image](https://user-images.githubusercontent.com/7897244/120127670-faf76980-c18d-11eb-8828-cb9dda764c01.png)

**Comment by vit9696** [comment]
Even if it works for some, we clearly know that it did not for us. I can imagine that there are some anomalies with the matter, perhaps region-specific or model-specific. Yet I do not see a reason to investigate them as the issue manifests itself at least on some setups and even if we find a way to workaround that, it is not the smartest idea to force the end-user do something unusual.

**Comment by MikeBeaton** [comment]
@startergo In fact last night after posting, I replicated what you've seen, though on a test install of Catalina.

But I have to say, despite my own initial doubts about whether these issues (still?) applied enough for the warnings in the docs to be truly correct, the situation clearly is now, these bits are known to be harmful, and have been shown to be (again!) on recent hardware, v. recently. Therefore having the OC default of _not_ setting them is safer, and we do (ofc) have full support for setting any other value the you care to try, with valid warnings about possible side-effects if you do use either of those bits.

**Comment by startergo** [comment]
> these bits are known to be harmful

I am surprised that this is the case as 0x87F is the result of 
csrutil disable
csrutil authenticated-root disable
from the recovery partition.

**Comment by MikeBeaton** [comment]
I wouldn't expect `csrutil authenticated-root disable` to be safe or not safe, either way.

However it did confuse me, too, that `csrutil disable` doesn't set what an end user would need. The best explanation I've got is that it was never really intended as an end user tool, and so that, as it's currently written, to get a non-Apple internal setting, end users really need to type `csrutil disable --no-internal`. I totally agree that that's counterintuitive, to say the least, but apparently that is the story.

**Comment by dakanji** [comment]
> end users really need to type `csrutil disable --no-internal`.

This is equivalent to `0x0` right?

**Comment by vit9696** [comment]
You can/should use `csrutil clear`.

**Comment by dakanji** [comment]
Presumably the new the toggle thing does such a clear

**Comment by startergo** [comment]
So looking here:
https://github.com/kallsyms/apple-opensource/blob/550c6d14beeb35f893fc18fca54e05ad7f6f8a3c/src/xnu/bsd/kern/kern_csr.c#L179
```
* If the device is an Internal Use Only Unit (IUOU) or if it is running a	 
* build that is signed with the Internal Use Only Software (IUOS) tag, then	
* allow the preservation of the CSR_ALLOW_APPLE_INTERNAL bit. Otherwise,	
* forcefully remove the bit on boot.
```
It looks like this bit is removed on boot?

**Comment by MikeBeaton** [comment]
So, the test I ran was on a recently put together test non-Apple h/ware machine.

I have just tried setting 0x5F and 0x4F as test values. On my Apple h/ware, the Apple Internal status is reported by `csrutil status` both times as `disabled`. On my non-Apple h/ware, it is reported following the value of the bit in `csr-active-config` (reports `enabled` when set).

This might explain the discrepancy in reports - a difference between Macs and non-Macs. Though I've no idea what the s/ware is checking to tell if it is on a 'non-Mac'.

cc @vit9696

**Comment by MikeBeaton** [comment]
> Presumably the new the toggle thing does such a clear

The current toggle goes between 0x0 and 0x26F (0 and cleared value behave exactly the same).

(cc @vit9696)

**Comment by vit9696** [comment]
Most likely Apple firmware has something to do with it (e.g. NVRAM driver, which has an additional security layer over NVRAM), which we do not have.

**Comment by startergo** [comment]
Monterey 12.1 beta sets ```csrutil disable``` on Mac hardware like this:

```
Current Configuration:
	Kext Signing			1 	[--without kext]	CSR_ALLOW_UNTRUSTED_KEXTS
	Filesystem Protections		1 	[--without fs]		CSR_ALLOW_UNRESTRICTED_FS
	Debugging Restrictions		1 	[--without debug]	CSR_ALLOW_TASK_FOR_PID
	Kernel Debugging Restrictions	1 	<n/a>			CSR_ALLOW_KERNEL_DEBUGGER
	Apple Internal			0 	[--no-internal]		CSR_ALLOW_APPLE_INTERNAL
	DTrace Restrictions		1 	[--without dtrace]	CSR_ALLOW_UNRESTRICTED_DTRACE
	NVRAM Protections		1 	[--without nvram]	CSR_ALLOW_UNRESTRICTED_NVRAM
	Device Configuration		0 	<n/a>			CSR_ALLOW_DEVICE_CONFIGURATION
	BaseSystem Verification		0 	[--without basesystem]	CSR_ALLOW_ANY_RECOVERY_OS
	Unapproved Kexts Restrictions	1 	<n/a>			CSR_ALLOW_UNAPPROVED_KEXTS
	Executable Policy		0 	<n/a>			CSR_ALLOW_EXECUTABLE_POLICY_OVERRIDE
	Unauthenticated Root		1 	[authenticated-root disable]	CSR_ALLOW_UNAUTHENTICATED_ROOT
```

```
nvram csr-active-config
csr-active-config	%7f%0a%00%00

```
Actual:
```
System Integrity Protection value: (0x00000a6f)
```

**Comment by mikebeaton** [comment]
That's useful info, that it sets 0x200 bit Unapproved Kexts Restrictions; unlike earlier macOS, and like what was recommended to me to set for OpenCore ToggleSip. (At least it is useful/new to me, but I just wrote the code that sets them value, in OC ToggleSip and CsrUtil.efi; I'm not such an expert as many other people on here about _which_ values are best to set; especially not across multiple Apple and non-Apple systems.)

The middle value of the three in your report is not consistent with the other two (0x27f for middle, 0x26f for first and last), not sure what happened there?

**Comment by startergo** [comment]
> The middle value of the three in your report is not consistent with the other two (0x27f for middle, 0x26f for first and last), not sure what happened there?

So on Apple Hardware this is what is happening:
https://github.com/acidanthera/bugtracker/issues/1657#issuecomment-855163198
On Hacks this bit has to be removed (not set explicitly), but on Macs it is automatically removed even if it is set beforehand.

**Comment by mikebeaton** [comment]
Thank you for reminding me of that code find - very useful indeed. But I didn't understand your actual report/post above. Are they all taken on the same machine with the same setting? And which tools/commands were used? (You say for no.2, but not for no.3, and I should probably recognise which tool you have used for no.1, but don't!)

**Comment by mikebeaton** [comment]
Ah, based on your PM as well - ty - 1 & 3 are read from the syscall, 2 as I can see is direct from NVRAM. That makes sense. I need to try out your syscall program on Mac and non-Mac hardware!

(I don't think any of this is inconsistent with what OpenCore is choosing to set with ToggleSip, nor with what people who know better than me already said about these bits. But it is useful & interesting!)

**Comment by startergo** [comment]
Try [this](https://github.com/startergo/csrstat-NG/releases/tag/version_1.0.0) tool and compare the results with ```nvram csr-active-config```. You can modify and compile the source code with ```cc csrstat.c -o csrstat``` as you like. Disregard (disabled), (enabled) statements as they are most probably incorrect.

**Comment by mikebeaton** [comment]
This is useful. I can confirm that on non-Mac hardware the value reported by the `csr_get_active_config` system call - e.g. in your useful tool - is 0x27F (i.e. the same as the value I manually set in NVRAM), whereas on Mac hardware the value reported by the system call is 0x26F for the same 0x27F NVRAM setting.

Also on non-Apple hardware, `csrutil status` with this NVRAM value reports `System Integrity Protection status: disabled (Apple Internal).`, whereas on Apple hardware it is `System Integrity Protection status: disabled.` - which makes sense.

So yes, on Mac hardware the bit has indeed been filtered, and almost certainly by the specific code you linked to https://github.com/acidanthera/bugtracker/issues/1657#issuecomment-855163198 .

So the next question would be, why is non-Mac hardware reporting as an 'internal use only' unit in that area of code, such that hacks are behaving differently to Macs, about this bit?

Does anybody already know? cc @vit9696 @dhinakg

**Comment by mikebeaton** [comment]
> > The middle value of the three in your report is not consistent with the other two (0x27f for middle, 0x26f for first and last), not sure what happened there?
> 
> So on Apple Hardware this is what is happening: [#1657 (comment)](https://github.com/acidanthera/bugtracker/issues/1657#issuecomment-855163198) On Hacks this bit has to be removed (not set explicitly), but on Macs it is automatically removed even if it is set beforehand.

I'll just briefly note here that it is believed that the above-linked code is for something else, and is ARM-specific. Be that as it may, the bit is certainly being filtered - somewhere. No one has yet definitely explained what is being checked (and where) to distinguish Macs from non-Macs.

Ofc none of that affects the decision to set 0x6f rather than 0x7f, as a value which works on both Macs and non-Macs.

**Comment by mikebeaton** [comment]
> Monterey 12.1 beta sets `csrutil disable` on Mac hardware like this:
> 
> ...
> 
> ```
> nvram csr-active-config
> csr-active-config	%7f%02%00%00
> ```
> 
> Actual:
> 
> ```
> System Integrity Protection value: (0x0000026f)
> ```

@startergo: I've just had a chance to check on a Monterey machine (hack not Mac, but still) and `csrutil disable` from recovery sets NVRAM `csr-active-config` to 0x7F, not 0x27F. I understood you as reporting (amongst other useful things) that `csrutil disable` command on Monterey with no other flags specified sets 0x27F, but perhaps I misunderstood what you meant?

**Comment by startergo** [comment]
You are right. I just checked. I did csrutil enable/disable in the same run before so something got mixed. Disabled SIP in Recovery and rebooted back to Recovery and checked bypassing OC ( I only need -no_compat_check).

**Comment by mikebeaton** [comment]
It turns out there was a bug in OpenCore here. The APPLE_INTERNAL bit was being pushed through to macOS by OpenCore even though macOS boot.efi was trying to clear it, in the case where config `ProvideCustomSlide` was set (which would be true on many hacks but essentially no Macs).

This is fixed in: https://github.com/acidanthera/OpenCorePkg/commit/d51442406cb738a8db904ccfbfa0ef78569b03bc

Thank you for your persistence in tracking this down and contributing to the research that has led to the fix.

**Comment by mikebeaton** [comment]
I'll just add, to be completely clear, this now means that 0x7F will behave the same on Mac and hack (as it in fact should have done all along), and also that `csrutil disable` (with its standard value of 0x7F) and `csrutil enable` (with its standard value of 0x10) behave as expected on all systems (in particular, do not break updates). `csrutil clear` may still be used as an alternative to `csrutil enable`, but is not required.

Also a reminder that if you want to enable or disable SIP much more quickly than entering Recovery (for occasional use, when you need it, it is NOT recommended to run with SIP disabled normally) you can now use the OpenCore's `AllowToggleSip` config option, and/or the OpenCore `CsrUtil.efi` tool - see documentation.

**Comment by michael1900** [comment]
> I'll just add, to be completely clear, this now means that 0x7F will behave the same on Macs and hacks (as it in fact should have done all along), and also that `csrutil disable` (with its standard value of 0x7F) and `csrutil enable` (with its standard value of 0x10) behave as expected on all systems (in particular, do not break updates). `csrutil clear` may still be used as an alternative to `csrutil enable`, but is not required.
> 
> Also a reminder that if you want to enable or disable SIP much more quickly than entering Recovery (for occasional use, when you need it, it is NOT recommended to run with SIP disabled normally) you can now use the OpenCore's `AllowToggleSip` config option, and/or the OpenCore `CsrUtil.efi` tool - see documentation.



> Try [this](https://github.com/startergo/csrstat-NG/releases/tag/version_1.0.0) tool and compare the results with `nvram csr-active-config`. You can modify and compile the source code with `cc csrstat.c -o csrstat --verbose` as you like.
> 
> Compiling
> Disregard (disabled), (enabled) statements as they are most probably incorrect.

I have used this **0x26f** value to disable SIP on my macbook pro model MacBookPro13,3 on Ventura but i have lost the possibility to change brightness if SIP disabled. 
With other values i have System Integrity Protection status: **unknown** (Custom Configuration).
With this 0x26f i have System Integrity Protection status: **disabled**.

So i don't know what i need to do to solve this. Please help!
