### ISSUE TITLE
Issue loading kXAudioDriver.kext / dependency problem with IOAudioFamily

### ISSUE THREAD

**Issue by jackcctse** [acidanthera/bugtracker#1658]
Forgive me if this is the not right place to report it, I tried my best.

I got an issue to load kXAudioDriver.kext via OpenCore, which works if putting under /Libray/Extensions. Make it simple:

- it works before BIg Sur 11.3, with 11.3 and newer it doesn't
- tried OC 0.68 and 0.69, same issue
- disabled SIP doesn't help
- looking into OC log it says a dependency problem with IOAudioFamily

```
24:723 00:008 OCAK: Dependency com.apple.iokit.IOAudioFamily was not found for kext com.kXProject.driver.kXAudioDriver
24:738 00:015 OCAK: Vtable patching failed for kext com.kXProject.driver.kXAudioDriver
24:741 00:003 OC: Prelinked injection kXAudioDriver.kext () - Invalid Parameter
24:746 00:004 OC: Prelink size 70049792 kext offset 65900544 reserved 4538368
```

**Comment by jackcctse** [comment]
Here's the log. the EFI zip cannot be uploaded here, which web transfer service is recommended?
[opencore-2021-05-29-160730.txt](https://github.com/acidanthera/bugtracker/files/6566535/opencore-2021-05-29-160730.txt)

**Comment by Andrey1970AppleLife** [comment]
The same problem with VoodooHDA in 11.3 and newer. Use /Libray/Extensions
