### ISSUE TITLE
Lilu LookupPatch does not take effect on macOS 11.4+, but works on macOS 10.15.7

### ISSUE THREAD

**Issue by mayankk2308** [acidanthera/bugtracker#1659]
# Problem
I am writing a very simple patch to **AppleGPUWrangler.kext** for native Macs that depends on the lovely `Lilu.kext` patcher. The patch works flawlessly on macOS 10.15.7 using `LookupPatch` applied when the kext loads, i.e., `lilu.onKextLoad(...)`. **The same patch does not work/apply on macOS Big Sur**. My source code for now is bare-bones and simply adapts from the known plugin [AzulPatcher4600](https://github.com/coderobe/AzulPatcher4600). I understand this has been superseded by `WhateverGreen` but for understanding the basics, it was a perfect specimen.

My source code: https://github.com/mayankk2308/egfx-enabler
Patch in source code: https://github.com/mayankk2308/egfx-enabler/blob/main/eGFXEnabler/kern_patchset.cpp#L56

# Further Look
First, to validate that the patch in question **actually works on macOS Big Sur**, I patched the system manually. This means disabling SIP + authenticated-root and manually patching the `AppleGPUWrangler` binary on disk. I have a script that does this for me. I simply updated the patch here to what I'm using in my kext: https://github.com/mayankk2308/purge-wrangler/blob/master/purge-wrangler.sh#L53. The manual patch worked fine.

## Patch Validation
I simply plug in a supported AMD GPU (Vega 64) in my case, via Thunderbolt, to a Thunderbolt 1 or 2 Mac. If the patch is not working, the eGPU cannot be used, otherwise, the eGPU initializes correctly and is usable.

## Investigation So Far
To get appropriate logs, my `boot-args` were: `keepsyms=1 -liludbg liludump=60`, with all logs in my kext being `SYSLOG` calls. I noted the following differences:

| macOS 11.4/11.5B1 | macOS 10.15.7 |
| ------------------- | --------------- |
| `keepsyms=1` required to boot macOS with `Lilu.kext`. | Works without `keepsyms=1`. |
| Patch log: [Lilu_1.5.3_20.6.txt](https://github.com/acidanthera/bugtracker/files/6566843/Lilu_1.5.3_20.6.txt) | Patch log: [Lilu_1.5.3_19.6.txt](https://github.com/acidanthera/bugtracker/files/6566844/Lilu_1.5.3_19.6.txt) |
| Logs are different than Catalina, but look ok to my eyes. Maybe it patches the kext but that isn't what is loaded? Grasping at straws. | Logs look good to me. |

## Things I Tried for macOS Big Sur
- I read about `DisableLinkeditJettison` being an OpenCore requirement for Lilu on Big Sur so I created a minimal OC configuration to have this enabled and remove `keepsyms=1` from `boot-args`. This fixed the boot issue but the patch still failed to work.
- I tried patching directly via OpenCore, but that doesn't work probably due to #1244. Attaching the log anyway: [opencore-2021-05-30-004518.txt](https://github.com/acidanthera/bugtracker/files/6566858/opencore-2021-05-30-004518.txt).
- Compiled Lilu myself with more debug messages just to make sure the right routines were being called while patching. Logs here: [Lilu_1.5.4_20.6.txt](https://github.com/acidanthera/bugtracker/files/6566862/Lilu_1.5.4_20.6.txt). Again, looks fine to me.

While I tried OpenCore to see if I could figure out a workaround, ideally I'd only want `Lilu.kext` as a dependency.

## Things I Haven't Tried on macOS Big Sur
- An older version of Big Sur, although the patch in my script, which is the same patch just offset differently, works fine (same byte is flipped).
- A different Mac. I am testing on a Mid-2014 15" MacBook Pro as that's the only non-Thunderbolt 3 Mac I have, but all this is probably agnostic to the Mac itself.

Full disclaimer that I am a novice at this and hoping to get advice from subject matter experts on whether I've stumbled on a bug, am missing something really basic, or just general guidance on the best course of action, thanks in advance!

**Comment by vit9696** [comment]
AppleGPUWrangler is already loaded at the time you patch it, therefore the patch does apply but the code is already executed. While it is hard to say what is the exact issue for this, I believe the startup order is different in macOS 11. You can try exploring that on Lilu said or try finding a way to rework the startup code for AppleGPUWrangler somehow.

**Comment by mayankk2308** [comment]
@vit9696 Thank you for the insight. Based on that, I suspected that injecting Lilu + my kext via OpenCore would resolve the load order, and that does turn out to be the case. This allowed the patch to work appropriately on macOS Big Sur as well. Quick question though, would it be possible for Lilu to check/let us know as a debug message that the patch is not going to work as the code is already executed?

**Comment by vit9696** [comment]
Unfortunately it is impossible to understand in general case, it is mostly about seeing it in the list of "already loaded" kexts or not.
