### ISSUE TITLE
Using your LogoApprox.svg

### ISSUE THREAD

**Issue by Cokaps** [acidanthera/bugtracker#1660]
Hi there, I want to use your LogoApprox.svg for my group [viOpenCore](https://github.com/viOpenCore) (I just want to translate dortania guide into vietnamese only)

### I just have some questions to ask you about LogoApprox.svg's use:

* Can I keep the icon which I'm using in the organization and well as the [OpenCore-Install-Guide](https://github.com/viOpenCore/OpenCore-Install-Guide) (I have change the color of your icon, the README.md said that I musn't modify it, so I just want to add you for your opinion. Tell me if I have to change it)
* If I have to change to another logo, can I use this.

![LogoApprox](https://user-images.githubusercontent.com/64778285/120674140-00babb00-c4be-11eb-8c08-aa02a57bf773.png)

**Comment by Andrey1970AppleLife** [comment]
Nobody has the right to modify OpenCore logo.
You can't use OpenCore logo for the organization. Even dortania doesn't use OpenCore logo.

**Comment by Cokaps** [comment]
Thanks for letting me know. I will try to remove it as soon as possible

**Comment by blackosx** [comment]
How about his one?
https://github.com/dortania/OpenCore-Legacy-Patcher

**Comment by Andrey1970AppleLife** [comment]
> How about his one?
> https://github.com/dortania/OpenCore-Legacy-Patcher

@vit9696 approved this icon for OpenCore Legacy Patcher app.
