### ISSUE TITLE
No digital audio with the WhiskeyLake Mobile PCH controller patch

### ISSUE THREAD

**Issue by wern-apfel** [acidanthera/bugtracker#1661]
The Intel NUC8(CoffeeLake) has the same device-ID but digital audio does not work with [this commit](https://github.com/acidanthera/AppleALC/commit/35c795f265e8996064d9367e10cda736a6e9f176). We are usually patching the vendor and device-ID, the mentioned patch replaces only the device-ID with count 6. Without that patch digital audio works.

**Comment by Andrey1970AppleLife** [comment]
There four patches contain. The third and fourth patches are necessary to you only? The first and second patches break audio?

**Comment by wern-apfel** [comment]
It works if I remove the second patch(709D0000), but the third also doesn't make sense to me. 
Count 6, does that mean search and patch in 6 places?

**Comment by Andrey1970AppleLife** [comment]
Delete [both patches](https://github.com/acidanthera/AppleALC/commit/35c795f265e8996064d9367e10cda736a6e9f176) (the first and the second) and check. I wait for the answer.

**Comment by vit9696** [comment]
CC @daliansky

**Comment by wern-apfel** [comment]
@Andrey1970AppleLife Yes it works when the first and second patch is removed. I think the 8086-A348 device-ID was added later, it already exists in Mojave. 9D70 is probably needed for HighSierra. I can't access older binaries right now.

**Comment by Andrey1970AppleLife** [comment]
I'll give you controllers.plush for the test later.

**Comment by Andrey1970AppleLife** [comment]
Check 
[Controllers.plist.zip](https://github.com/acidanthera/bugtracker/files/6601229/Controllers.plist.zip)

**Comment by wern-apfel** [comment]
OK, it works.

**Comment by Andrey1970AppleLife** [comment]
Сlosed https://github.com/acidanthera/AppleALC/commit/f9afbe7eea71076c6ea56e618e3306fdae5b3748

**Comment by vit9696** [comment]
This change introduced a regression in https://github.com/acidanthera/bugtracker/issues/1667, so I temporarily reverted the patch.

My observation on the code is that `709D0000` is found 8 times in AppleHDAController, so the original patch in https://github.com/acidanthera/AppleALC/commit/35c795f265e8996064d9367e10cda736a6e9f176#diff-7ec7d0a99f0519772f966b859e7268bc36056120e0495638ebd08d8e120d8d2fR26 is incorrect, as it should have `Count` 8, not 6 for Big Sur. Perhaps this simple change is enough to fix digital audio for @wern-apfel.

If it is not the case, then we really need separate patches for laptops and desktops, however, Intel NUC is rather a laptop, but it is not Mac-model wise. To solve this we may want to provide some way to override a patchset on mobile platforms that are using desktop SMBIOS and vice-versa.

- @wern-apfel, @1alessandro1, can you both check if master works for you?
- @1alessandro1, can you check whether only first two patches (https://github.com/acidanthera/AppleALC/blob/9cbe2c5d98d9d41b367b10a5d8e14ea9c2573eb7/Resources/Controllers.plist#L818-L841) are enough for your setup?

**Comment by wern-apfel** [comment]
@vit9696 It's the same like count 6, which means it doesn't work. If it helps, I use the USB-C port, when I connect a second display via HDMI, the device appears and it works. I seems to need some sort of resync?

**Comment by vit9696** [comment]
@wern-apfel it is the 6th replacement that breaks things for you, correct?

**Comment by vit9696** [comment]
Checked, makes sense, it is audio probing code.

Please try https://github.com/acidanthera/AppleALC/commit/99f42c274bab2dcb78077df2cb4b8663795313e4. Both of you. I think that one will work correctly on both setups. There are common patches and laptop-only. Not desktop-only and laptop-only as before.

**Comment by wern-apfel** [comment]
Yes, this should work, works with a desktop SMBIOS and not while using a laptop SMBIOS.

**Comment by vit9696** [comment]
Assuming resolved.

**Comment by 1alessandro1** [comment]
Hi @vit9696, sorry for my late reply but I was able to test the latest commit now in detail.

Unfortunately, downloading the `Artifacts` of commit https://github.com/acidanthera/AppleALC/commit/99f42c274bab2dcb78077df2cb4b8663795313e4 does not fix the problem

Is there any other test I can make?

**Comment by vit9696** [comment]
Hrm, how come, but is not that patchset what you had before?

**Comment by Andrey1970AppleLife** [comment]
> Hi @vit9696, sorry for my late reply but I was able to test the latest commit now in detail.
> 
> Unfortunately, downloading the `Artifacts` of commit [acidanthera/AppleALC@99f42c2](https://github.com/acidanthera/AppleALC/commit/99f42c274bab2dcb78077df2cb4b8663795313e4) does not fix the problem
> 
> Is there any other test I can make?

Delete this patch and check
https://github.com/acidanthera/AppleALC/blob/master/Resources/Controllers.plist#L811-L846

**Comment by 1alessandro1** [comment]
> Hrm, how come, but is not that patchset what you had before?

![image](https://user-images.githubusercontent.com/46293832/120942144-2a2a4f80-c727-11eb-87ea-8d9449b7d3a1.png)

On the left you can find the previous working configuration at commit https://github.com/acidanthera/AppleALC/commit/72244b518032e5bdce289e75474dd12230d739a3 so I guess the missing ones (which were moved to NUCs) are causing the issue

> Delete this patch and check
https://github.com/acidanthera/AppleALC/blob/master/Resources/Controllers.plist#L811-L847

I guess I have to build the kext with those two lines removed? I do not have Xcode installed right now

**Comment by vit9696** [comment]
@1alessandro1 could you please try the master version? I think I found the issue in the code: it did not support patches from multiple controllers before.

**Comment by 1alessandro1** [comment]
Sure, I'll report in a minute or two

**Comment by 1alessandro1** [comment]
It works flawlessly now ^_^
Thank you guys for replying quickly and solving the issue even faster!

**Comment by vit9696** [comment]
Wait a bit, need to think about something. Might give you another test in a minute or two.

**Comment by 1alessandro1** [comment]
ok, I'm here for additional tests, ping me when you're ready

**Comment by vit9696** [comment]
Ok, check the master. Should work as well.

**Comment by 1alessandro1** [comment]
Tested https://github.com/acidanthera/AppleALC/commit/65f53049afed0f15b5ab2ed6a10d9e34b5b3a979 now, it works perfectly as expected, thanks Vit
