### ISSUE TITLE
SK Hynix P31 NVMe macOS support possible via NVMeFix? 

### ISSUE THREAD

**Issue by snarfala** [acidanthera/bugtracker#1662]
SK Hynix P31 does not work with MacOS because apparently Apple's NVMe drivers are causing the P31 firmware to timeout on a request, resulting in a kernel panic. Is this something that is fixable via NVMeFix? I don't own a P31 yet but I'm considering getting one. Please see https://twitter.com/arter97/status/1305587343017926656

**Comment by vit9696** [comment]
Unlikely. Unless anyone contributes it at least. Added to https://github.com/dortania/bugtracker/issues/192.

**Comment by amondnet** [comment]
@snarfala 
Apparently SK Hynix released a firmware update for the P31 recently that fixes the Mac issues.
Firmware update or Rev.41062C20 needed.
The software and firmware are at the bottom of their site: https://ssd.skhynix.com/

https://github.com/dhckdgjs/GIGABYTE-Z590-VISION-G-HACKINTOSH-OPENCORE-iGPU-with-dGPU-UHD630-RX580#update-210612

**Comment by snarfala** [comment]
@amondnet 
Good to know, thank you! I ended up getting a Western Digital SN750 even though it is an older design since I did not know about the recent P31 firmware update. P31 is clearly better if they have addressed the macOS compatibility issues.

**Comment by Longcoming** [comment]
How to update sk HYnix 1 tb firmware.I am getting error.

**Comment by lordersaur** [comment]
> @Amond How to update sk HYnix 1 tb firmware.I am getting error.
> 
> > @snarfala
> > Apparently SK Hynix released a firmware update for the P31 recently that fixes the Mac issues.
> > Firmware update or Rev.41062C20 needed.
> > The software and firmware are at the bottom of their site: https://ssd.skhynix.com/
> > https://github.com/dhckdgjs/GIGABYTE-Z590-VISION-G-HACKINTOSH-OPENCORE-iGPU-with-dGPU-UHD630-RX580#update-210612
> 
> on windows ı am getting error while updating the firmware.

Same. Can’t update the firmware. I’m guessing it’s because it’s either protected or it’s the boot drive of my laptop. I own the Lenovo legion 5 15arh05h.

**Comment by Longcoming** [comment]
How to be sure,it is a p31 model?
Yeah it is 1 tb but there is not enough info on sk-hynix ssd site.

**Comment by jesvijonathan** [comment]
fuck sk hynix
