### ISSUE TITLE
XhciDxe.efi driver hangs with USB3 nanoTech ExpressCard34

### ISSUE THREAD

**Issue by hvdschmitt** [acidanthera/bugtracker#1663]
Using OCLP 0.1.6 with an MBP5,2. It has a 2-port USB3 expresscard from nanotech which works well with the AppleUSBXHCIFL1100 driver in booted BS 11.5b1.

Wanted to use it also for booting with OCLP 0.1.6, but OCLP hangs early on before reaching its boot selector. 
Mykola Grymalyuk gave me a debug build of XhciDxe.efi for a closer look, and suggested I contact you directly with the results.

I looked at the OpenCore protocol written to the EFI of the OCLP stick.

- when booting while the ExpressCard is plugged in, it hangs after creating CMD ring / EVENT ring. Before it warns that it failed to enable 64-bit DMA on 64-bit capable controller (1st attachment). This happens with or without a disk connected to USB3.
- when booting with ExpressCard taken out, it proceeds normal to the OCLP boot picker and can boot my BS drive (from one of the native USB ports) (2nd attachment).

I guess this is low priority and maybe affects only my setup. If you have a hint I could look at the source myself or also use the hopper disassembler.
[opencore-2021-06-02-171256.txt](https://github.com/acidanthera/bugtracker/files/6597763/opencore-2021-06-02-171256.txt)
[opencore-2021-06-03-190755.txt](https://github.com/acidanthera/bugtracker/files/6597766/opencore-2021-06-03-190755.txt)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/6597770/EFI.zip)
![Bildschirmfoto 2021-06-01 um 18 27 02](https://user-images.githubusercontent.com/82234458/120788523-b9214700-c530-11eb-8a13-34074dd3b5ea.png)
![Bildschirmfoto 2021-05-24 um 16 56 22](https://user-images.githubusercontent.com/82234458/120788555-c3434580-c530-11eb-9166-dd8e94e690aa.png)
![Bildschirmfoto 2021-05-24 um 16 57 03](https://user-images.githubusercontent.com/82234458/120788570-c8a09000-c530-11eb-9126-ef0826770401.png)

**Comment by vit9696** [comment]
XhciDxe uses `CreateEventEx`, maybe you need `ForgeUefiSupport`. If that does not help, I am afraid you are best to DEBUG it with adding more prints, and then letting us know where it dies in particular. Will not promise to help, but can at least give it a look.

**Comment by vit9696** [comment]
cc @khronokernel
