### ISSUE TITLE
[FEATURE REQUEST] Make WriteFlash configurable per Variable

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1665]
Would it be possible to have `WriteFlash` work so that instead of acting globally, it works per NVRAM variable.
NVRAM_Variable_A = Set not to write to flash
NVRAM_Variable_B = Set to write to flash
NVRAM_Variable_C = Set to write to flash
NVRAM_Variable_A = Set not to write to flash
...
ETC?

@MikeBeaton probably didn't need to persist every variable here:  https://github.com/acidanthera/bugtracker/issues/1212#issuecomment-706561979 and with this feature, if doable, users could pick and choose and might help get around the limitation @vit9696 subsequently pointed out.

**Comment by vit9696** [comment]
The feature is impractical to implement as it is not really useful, complicates variable interaction as well as configuration. We have no plans to let this land in OC.

**Comment by mikebeaton** [comment]
Hi again @dakanji - The idea here is basically to have new config which allows blocking certain NVRAM vars from write, correct? The seems potentially a useful feature, regardless of other projects I'm working on. The final decision on this would rest with @vit9696 though.
