### ISSUE TITLE
AppleALC regression on Whiskey lake laptop [ALC295]

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1667]
Hi, I found that this commit https://github.com/acidanthera/AppleALC/commit/f9afbe7eea71076c6ea56e618e3306fdae5b3748 broke audio support from AppleALC, I tested all the previous versions and they work flawlessly.

Could it be that the additioin of [this line](https://github.com/acidanthera/AppleALC/commit/f9afbe7eea71076c6ea56e618e3306fdae5b3748#diff-7ec7d0a99f0519772f966b859e7268bc36056120e0495638ebd08d8e120d8d2fR815) broke support for my i5 8265U Whiskey Lake HDA controller? 

What logs can I provide to solve the issue?

**Comment by 1alessandro1** [comment]
I'm using `layout-id` = `0D000000` in the `PciRoot(0x0)/Pci(0x1F,0x3)`. 
Reading elsewhere I found that the same commit which broke audio for [my laptop](https://github.com/1alessandro1/HP-Pavilion-CE2072NL-macOS) solved an issue for another user in https://github.com/acidanthera/bugtracker/issues/1661

Any ideas?

**Comment by vandroiy2013** [comment]
cc @Andrey1970AppleLife

**Comment by vit9696** [comment]
Let's continue discussing that in https://github.com/acidanthera/bugtracker/issues/1661.
