### ISSUE TITLE
BootInstall_X64.tool issues

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1668]
Hi, today I've successfully managed to boot an old i3 540 with H57 chipset with OpenCore (and Catalina 10.15.7) and as you might guess, this firmware is *very* legacy (no traces of UEFI anywhere) but it works flawlessy even without `Lilu.kext` and plugins (Only FakeSMC is required and Realtek8111 for Ethernet) and obviously no native NVRAM

(I know that today there's a full release planning, no need to hurry for this issue, it can be fixed in the next release if it's too complicated)

I used `BootInstall_X64.command` to write the MBR to the USB, and the BIOS can correctly recognize the external USB drive and boot Catalina on the SSD.

The problem comes when after I booted the system I try to use `BootInstall_X64.tool` on the SATA drive, the BIOS won't recognize it anymore and refuse to boot.

Since this system was working with the Clover pkg scripts, I can say that the following procedures taken by the pkg scripts, are able to make a working MBR on both the USB ESP and SATA ESP

```
Target volume /Volumes/Catalina on disk1 is APFS on physical store disk0s2
======================================================
Backing up EFI files

Backing up stage2 file /Volumes/Catalina/Private/tmp/EFIROOTDIR/boot  to /Volumes/Catalina//Users/casa/Clover EFI Backups/r5134/2021-06-07-11h11/boot
Backing up /Volumes/Catalina/Private/tmp/EFIROOTDIR/EFI folder to /Volumes/Catalina//Users/casa/Clover EFI Backups/r5134/2021-06-07-11h11/EFI
No Active Partition

Stage 0 - Writing boot0af to /dev/rdisk0
dd if=/dev/rdisk0 count=1 bs=512 of=/tmp/origMBR
cp /tmp/origMBR /tmp/newMBR
dd if=//Private/tmp/usr/standalone/i386/boot0af of=/tmp/newMBR bs=440 count=1 conv=notrunc
fdisk -f /tmp/newMBR -u -y /dev/rdisk0

Stage 1 - Writing boot1f32 to /dev/rdisk0s1
dd if=/dev/rdisk0s1 count=1 bs=512 of=/tmp/origbs
boot volume format is FAT32
cp /tmp/boot1f32 /tmp/newbs
dd if=/tmp/origbs of=/tmp/newbs skip=3 seek=3 bs=1 count=87 conv=notrunc
dd if=/tmp/newbs of=/dev/rdisk0s1

Stage 2 - Written boot6 (x64) to /Volumes/ESP/boot

======================================================
=========== Clover EFI Installation Finish ===========
======================================================
```

Since I got everything working with OC, I wish I could make the jump, but for now my only option is to boot the system with an external USB since that's the only way the USB MBS is recognized.

What can I do to debug the issue?

**Comment by vit9696** [comment]
cc @roddy20

**Comment by roddy20** [comment]
1) what is LegacyBoot.command? OpenCore includes BootInstall_X64.tool both for USB and for SSD, not LegacyBoot.command
2) why do you show logs from Clover? please show Terminal output from BootInstall_X64.tool, are files copied with any errors or no

**Comment by roddy20** [comment]
3 try to disable SIP when installing

**Comment by 1alessandro1** [comment]
> 1. what is LegacyBoot.command? OpenCore includes BootInstall_X64.tool both for USB and for SSD, not LegacyBoot.command

Sorry, typo. Edited the message now

> 2. why do you show logs from Clover? 

I showed them to show what clover did to get a working MBR on the SATA ESP

> please show Terminal output from BootInstall_X64.tool, are files copied with any errors or no

Yes, will do in a few moments. 

> 3 try to disable SIP when installing

However I do not understand the reason for this, since for the USB thumb drive with SIP enabled creating a new MBR with `BootInstall_X64.tool` works perfectly

**Comment by roddy20** [comment]
seems to be working:
Enter disk number to install to:
0
MS-DOS FAT32
Password:
disk0s1 was already unmounted
1+0 records in
1+0 records out
512 bytes transferred in 0.001288 secs (397535 bytes/sec)
boot1f32 -> newbs
87+0 records in
87+0 records out
87 bytes transferred in 0.000434 secs (200497 bytes/sec)
14+0 records in
14+0 records out
14 bytes transferred in 0.000091 secs (154121 bytes/sec)
1+0 records in
1+0 records out
512 bytes transferred in 0.000121 secs (4227330 bytes/sec)
Volume EFI on disk0s1 mounted
bootX64 -> /Volumes/EFI/boot

**Comment by roddy20** [comment]
> However I do not understand the reason for this, since for the USB thumb drive with SIP enabled creating a new MBR with `BootInstall_X64.tool` works perfectly

I did not understand it too, but maybe USB and system drive are different (?)
I did it with SIP enabled and it works

**Comment by 1alessandro1** [comment]
```
Enter disk number to install to:
3
MS-DOS FAT32
Password:
disk3s1 was already unmounted
1+0 records in
1+0 records out
512 bytes transferred in 0.000828 secs (618337 bytes/sec)
boot1f32 -> newbs
87+0 records in
87+0 records out
87 bytes transferred in 0.000336 secs (258981 bytes/sec)
14+0 records in
14+0 records out
14 bytes transferred in 0.000071 secs (197048 bytes/sec)
1+0 records in
1+0 records out
512 bytes transferred in 0.000804 secs (636858 bytes/sec)
Volume EFI on disk3s1 mounted
bootX64 -> /Volumes/EFI/boot
```

This is the terminal output for the USB, and the MBR created works. How can I explain a process where after I click on the Crucial 120GB SSD it won't detect any valid MBR hence refusing to load anything?

**Comment by roddy20** [comment]
is the Terminal output for **not working** disk the same? we know how working one looks

**Comment by 1alessandro1** [comment]
@roddy20 here's the output for the SATA install

```
./BootInstall_X64.tool
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *120.0 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                 Apple_APFS Container disk1         119.8 GB   disk0s2

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +119.8 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume Catalina - Data         72.0 GB    disk1s1
   2:                APFS Volume Catalina                11.3 GB    disk1s2
   3:                APFS Volume Preboot                 82.2 MB    disk1s3
   4:                APFS Volume Recovery                525.9 MB   disk1s4
   5:                APFS Volume VM                      1.1 MB     disk1s5

/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *7.8 GB     disk2
   1:             Windows_FAT_32 CHIARA                  7.8 GB     disk2s1

/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *61.5 GB    disk3
   1:             Windows_FAT_32 NO NAME                 61.5 GB    disk3s1

/dev/disk4 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *7.9 GB     disk4
   1:                        EFI EFI                     209.7 MB   disk4s1
   2:                  Apple_HFS CARD                    7.6 GB     disk4s2

Enter disk number to install to:
0
MS-DOS FAT32
Password:
fdisk: /dev/rdisk0: Operation not permitted
Volume EFI on disk0s1 unmounted
1+0 records in
1+0 records out
512 bytes transferred in 0.000529 secs (967771 bytes/sec)
boot1f32 -> newbs
87+0 records in
87+0 records out
87 bytes transferred in 0.001112 secs (78239 bytes/sec)
14+0 records in
14+0 records out
14 bytes transferred in 0.000240 secs (58312 bytes/sec)
1+0 records in
1+0 records out
512 bytes transferred in 0.000261 secs (1962965 bytes/sec)
Volume EFI on disk0s1 mounted
bootX64 -> /Volumes/EFI/boot
casa@Casas-iMac LegacyBoot % sudo diskutil mount disk4s1
Volume EFI on disk4s1 mounted

```

**Comment by 1alessandro1** [comment]
It seems like it fails on executing `fdisk`:

```
# Write MBR
sudo fdisk -uy -f boot0 /dev/rdisk"${N}"
```

**Comment by roddy20** [comment]
fdisk: /dev/rdisk0: Operation not permitted
try to execute it from Terminal and disable SIP if needed
**sudo fdisk -uy -f boot0 /dev/rdiskX**

**Comment by 1alessandro1** [comment]
```
Enter disk number to install to:
0
MS-DOS FAT32
Password:
disk0s1 was already unmounted
1+0 records in
1+0 records out
512 bytes transferred in 0.000389 secs (1316667 bytes/sec)
boot1f32 -> newbs
87+0 records in
87+0 records out
87 bytes transferred in 0.001039 secs (83732 bytes/sec)
14+0 records in
14+0 records out
14 bytes transferred in 0.000159 secs (88036 bytes/sec)
1+0 records in
1+0 records out
512 bytes transferred in 0.000245 secs (2088992 bytes/sec)
Volume EFI on disk0s1 mounted
bootX64 -> /Volumes/EFI/boot
```
Here's the output with SIP disabled, now I reboot

**Comment by roddy20** [comment]
Clover uses **exactly** the same command
fdisk -f /tmp/newMBR -u -y /dev/rdisk0
with another MBR file
and it worked for you

**Comment by 1alessandro1** [comment]
Thanks that did the trick! ^_^
I set sip to 0x3E7 temporarily (`csr-active-config E7030000`) and installed with `BootInstall_X64.tool`, it worked perfectly.

**Comment by roddy20** [comment]
sometimes it works with SIP enabled, sometimes it does not
I cannot reproduce the error, but some people had the same problem

**Comment by 1alessandro1** [comment]
@roddy20 I found another issue with another Legacy tool, `LogoutHook.command` where it fails to mount the ESP to write nvram.plist, hence on this H57 platform I cannot get emulated nvram to work

This is the part of code interested.

```
UUID="$(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path | /usr/bin/sed 's/.*GPT,\([^,]*\),.*/\1/')"
if [ "$(printf '%s' "${UUID}" | /usr/bin/wc -c)" -eq 36 ] && [ -z "$(echo "${UUID}" | /usr/bin/sed 's/[-0-9A-F]//g')" ]; then
  /usr/sbin/diskutil mount "${UUID}" || abort "Failed to mount ${UUID}!"
  /bin/cp /tmp/nvram.plist "$(/usr/sbin/diskutil info "${UUID}" | /usr/bin/sed -n 's/.*Mount Point: *//p')" || abort "Failed to copy nvram.plist!"
  /usr/sbin/diskutil unmount "${UUID}" || abort "Failed to unmount ${UUID}!"
  exit 0
else
```

Is it normal that the command is executed without superuser privileges?

**Comment by 1alessandro1** [comment]
This is what happens when adding `sudo` in front of

```
  /usr/sbin/diskutil mount "${UUID}" || abort "Failed to mount ${UUID}!"
```

![image](https://user-images.githubusercontent.com/46293832/121500666-cf228200-c9de-11eb-929f-b9b602ff9c87.png)

**Comment by 1alessandro1** [comment]
@vit9696 in addition to that, this legacy firmware does not report 

`8BE4DF61-93CA-11D2-AA0D-00E098032B8C` data values when dumping NVRAM with `nvram.plist`, so now I'm unable to reboot the machine (usually caused by NVRAM problems) 

Is this assumption correct? Does macOS expect some of the missing values to be present, failing in the reboot process? (Shutdown works correctly)

![image](https://user-images.githubusercontent.com/46293832/121503854-be274000-c9e1-11eb-9aa9-826f71a720a7.png)

**Comment by roddy20** [comment]
> Is it normal that the command is executed without superuser privileges?

Real logout process will execute it WITH privileges

**Comment by roddy20** [comment]
to debug - uncomment the line here
abort() {
  echo "Fatal error: ${1}"
# echo "Fatal error: ${1}" >> error.log
  exit 1
}
it will save errors to file, for example "Fatal error: Failed to copy nvram.plist!"
maybe there are some problems with SIP Enabled in Big Sur and beta 12 (?)
Works OK to boot to Mavericks ... Catalina and Windows

**Comment by roddy20** [comment]
> @vit9696 in addition to that, this legacy firmware does not report
> 
> `8BE4DF61-93CA-11D2-AA0D-00E098032B8C` data values
nvram 8BE4DF61-93CA-11D2-AA0D-00E098032B8C:Boot0080
8BE4DF61-93CA-11D2-AA0D-00E098032B8C:Boot0080	%01%00%00%00J%00M%00a%00c%00 %00O%00S%00 %00X%00%00%00%02%01%0c%00%d0A%03%0a%00%00%00%00%01%01%06%00%02%1f%03%12%0a%00%00%00%00%00%00%00%04%01*%00%02%00%00%00(@%06%00%00%00%00%00@%93%b5%1d%00%00%00%00%80%8eM%eb%88%f7%8aO%9d%95%ba}%ae%fe%bf_%02%02%7f%ff%04%00

**Comment by 1alessandro1** [comment]
> Real logout process will execute it WITH privileges, it belongs to system, not current user
No need to execute it in another way

Ok, but upon the next shutdown - fresh boot the nvram.plist file was not generated until I manually executed LogoutHook.command adding `sudo` in front of it.

>  Works OK to boot to Mavericks ... Catalina and Windows

I'm on 10.15.7 (latest security update)

**Comment by 1alessandro1** [comment]
> to debug - uncomment the line here
abort() {
echo "Fatal error: ${1}"

@roddy20 when pressing on reboot, this is the error log generated
[error.log](https://github.com/acidanthera/bugtracker/files/6632594/error.log)

**Comment by roddy20** [comment]
can you mount 2B577EBD-CE4A-45D8-9E84-1273AB27D7D3 by diskutil and is it OpenCore EFI partition?
I tested all the available systems 
csrutil status
System Integrity Protection status: enabled.

Sierra -> Catalina OK
Catalina->Monterey OK
Monterey->Maverick OK
Maverick->Sierra   OK

no errors

**Comment by roddy20** [comment]
... and check EFI's for bad or orphaned clusters
sudo fsck_msdos -fy /dev/disk*s1

**Comment by 1alessandro1** [comment]
I rebooted to recovery and checked the filesystem with `fsck_msdos` and Disk Utility

![photo_2021-06-10_16-25-07](https://user-images.githubusercontent.com/46293832/121561902-7667df00-ca08-11eb-9f20-8443e58b257f.jpg)

![photo_2021-06-10_16-25-08](https://user-images.githubusercontent.com/46293832/121562001-8ed7f980-ca08-11eb-8c10-4e67b1551a9e.jpg)

>can you mount 2B577EBD-CE4A-45D8-9E84-1273AB27D7D3 by diskutil and is it OpenCore EFI partition?
I tested all the available systems

I always mount the ESP with `sudo diskutil mount disk0s1` with no issues. However, `sudo` is required.

The problem is still there, clicking on reboot does not mount the ESP.

**Comment by vit9696** [comment]
Whether or not you do mount with your command, you were explicitly requested to run `sudo diskutil mount 2B577EBD-CE4A-45D8-9E84-1273AB27D7D3` and check if the mounted volume is the responsible EFI partition.

**Comment by 1alessandro1** [comment]
> sudo diskutil mount `2B577EBD-CE4A-45D8-9E84-1273AB27D7D3` and check if the mounted volume is the responsible EFI partition

Yes, it is mounted correctly with that command. It's the first thing I did after I had analyzed the script, because I never mount partitions with their UUIDs. I used `diskutil info disk0s1` and I've obtained the UUID string that I later run with

`sudo diskutil mount 2B577EBD-CE4A-45D8-9E84-1273AB27D7D3`

And it was mounted successfully as it is demonstrated in the message I previously sent [here](https://github.com/acidanthera/bugtracker/issues/1668#issuecomment-858465075) 

https://user-images.githubusercontent.com/46293832/121500666-cf228200-c9de-11eb-929f-b9b602ff9c87.png

**Comment by vit9696** [comment]
Then it means your LogoutHook.command is installed incorrectly.

You are running it in this example without `sudo`, but if you do run `sudo ./LogoutHook.command`, it should work just fine. Since `LogoutHook.command` is not running with root privileges at reboot time, it is installed incorrectly or your security permissions prevent it from doing anything (check that Terminal is given full disk access in sec prefs for instance).

**Comment by 1alessandro1** [comment]
That test is old, and it was only to demonstrate that the UUID is correct.

I have restored the default LogoutHook.command later to make these tests, that was only a temporary solution where I added `sudo` in front of

```
  /usr/sbin/diskutil mount "${UUID}" || abort "Failed to mount ${UUID}!"
```

**Comment by roddy20** [comment]
as it is demonstrated in the message I previously sent [here]

as previosly. LogoutHook is designed to run by some kind of system daemon **at user logout**.  it is not designed to be started by user from Terminal

**Comment by 1alessandro1** [comment]
> as it is demonstrated in the message I previously sent [here]

as previosly. LogoutHook is designed to run by some kind of system daemon at user logout. it is not designed to be started by user from Termina

I know. But I had to debug the issue somehow to find what's wrong. First I thought it was a filesystem issue, but I was incorrect.

**Comment by roddy20** [comment]
yes, UUID seems to be OK

**Comment by 1alessandro1** [comment]
> Then it means your LogoutHook.command is installed incorrectly.

I followed [these steps](https://dortania.github.io/OpenCore-Post-Install/misc/nvram.html#enabling-emulated-nvram-with-a-nvram-plist) to enable emulated NVRAM on the system, and I copied the `LogoutHook/` folder to `/Users/$(whoami)/.LogoutHook` as a hidden folder inside `~`

**Comment by roddy20** [comment]
where is LogoutHoock.command located? the full path?
mine is /Users/Shared/LogoutHook/LogoutHook.command
maybe there are spaces, special symbols, not-english letters or some special permissions in your path?

**Comment by 1alessandro1** [comment]
where is LogoutHook.command located? the full path?

`/Users/casa/.LogoutHook/LogoutHook.command`

Even though there're not any special permissions for folders outside `~/Desktop/` `~/Documents/` `~/Downloads/`  can move it if you want

**Comment by 1alessandro1** [comment]
> Real logout process will execute it WITH privileges, it belongs to system, not current user
No need to execute it in another way

@roddy20 I suspect the problem lies in this procedure, when I click on reboot, the error.log generates that "Failed to mount ..." 
Should I set special permissions for that folder if I copy it under `/Users/Shared`?

**Comment by roddy20** [comment]
> Should I set special permissions for that folder if I copy it under `/Users/Shared`?

no
I copied folder LogoutHook (with the script and other files) to /Users/Shared/ by Finder and executed **LogoutHook.command -install**

**Comment by 1alessandro1** [comment]
Note: 
I know that some of these info should be posted on forums, but I'm adding additional context to the reason why I'm trying to enable Emulated nvram on this system.

Missing nvram support is what I think is causing these issues with the rebooting phase. Shutdown works without any issue with OC 0.7.0

This machine has been working with Clover from more than one year, and the EFI is made as lean as possible. There haven't been any of these issues since

Now, I've decided to migrate everything to OC for ease of use (since I'm using it on more than 5 different machines)

An overview of the EFI: the custom DSDT which is working correctly (with just a SBRG to LPCB rename), no Booter quirks since this is legacy stuff, no special device-properties, only FakeSMC required to boot the system (No Lilu and friends) and some addons like RTL8111. 

No kernel patches of any kind, the SMBIOS is iMac11,2 which shares exactly the same CPU (i3 540) and is the only one who is able to provide correct frequency states.

I've noticed that even though with Clover's FixOwnership is disabled, and USBs work natively (they're EUSB and USBE controllers and do not require any patches). With OpenCore instead I have to enable Releaseusbownership (and this makes me think that maybe clover might add something by itself)

Now, with the NVRAM issue which is always related to booting problems or rebooting issues, Clover does its *magic* and with a minimal config.plist (I'm going to open a repo for that EFI) manages to make the system "rebootable" while with OC I have these weird issues which I'm guessing are Nvram related (can these be related with Openruntime quirks too?), and that's why I'm here, where I stumbled upon this weird permission issue where the ESP is not mounted (hence nvram.plist is not written) when clicking on reboot.

**Comment by vit9696** [comment]
NVRAM is unrelated to reboot issues. If you insist on them, the issue is quirks or FadtEnableReset.

**Comment by 1alessandro1** [comment]
Thanks for the tip Vit 👍 
By Quirks, you mean Booter > Quirks or those are only related to UEFI services? I heard from the guides that RebuildappleMemorymap is the only one relevant for 10.8 and below, but I'm on 10.15 with that H57 chipset

**Comment by roddy20** [comment]
> sudo ./LogoutHook.command install
>  Is there a way to check if this command is correctly applied? 
sudo defaults read com.apple.loginwindow LogoutHook
answer is path to the file
/Users/Shared/LogoutHook/LogoutHook.command

**Comment by 1alessandro1** [comment]
> sudo defaults read com.apple.loginwindow LogoutHook
answer is path to the file
/Users/Shared/LogoutHook/LogoutHook.command

@roddy20 
Thanks, now it works perfectly with the stock Logouthook.command once I've put that in /Users/Shared/Logouthook, I can see `nvram.plist` on reboot

In addition to that, 

>  If you insist on them, the issue is quirks or FadtEnableReset.

@vit9696 
`FadtEnableReset` did the job. We can mark this as *definitely* solved, thanks ^^
