### ISSUE TITLE
New AppleALC.kext is using "plugin" (PinConfig.kext)

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#1671]
Just want to clarifiy. I have built latest applealc.kext with latest commit. And i found this Plugin.kext.

So we need to add this plugin kext add pin config to our codec.

But there is no information about in change log.

I set without this plugin then no audio in Big Sur and Monterey.

And if i add this kext then audio is comeback in Big Sur and Monterey.

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/9614101/121137330-bee49880-c860-11eb-99de-a1878b1cd864.png">

**Comment by andreszerocross** [comment]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/9614101/121138857-51396c00-c862-11eb-8c01-024b4c3c8fbe.png">

**Comment by vit9696** [comment]
This looks like a build bug. You should not need to inject this file.

**Comment by vit9696** [comment]
Both releases are correct. Please refrain from reporting incorrect issues with counterfeit binaries in the future.

**Comment by mikebeaton** [comment]
Do not build with Xcode app - with Lilu.kext and MacKernelSDK directories set up, local build can be `xcodebuild -jobs 1 -configuration Debug -arch x86_64`.
