### ISSUE TITLE
PowerTimeoutKernelPanic quirk broken since macOS 12.0 (21A5248p)

### ISSUE THREAD

**Issue by pavelchup** [acidanthera/bugtracker#1673]
Got kernel panic after wake from sleep.

panic(cpu 0 caller 0xffffff8017048b81): AppleHDAHDMI_DPDriver::setPowerState(0xffffff93728c4400 : 0xffffff7fad9dc070, 0 -> 1) timed out after 10168 ms @IOServicePM.cpp:5411
Panicked task 0xffffff86a693b688: 165 threads: pid 0: kernel_task
Backtrace (CPU 0), panicked thread: 0xffffff86a9b328b0, Frame : Return Address
0xffffffdc79013ab0 : 0xffffff80168b0dbd mach_kernel : _handle_debugger_trap + 0x41d
0xffffffdc79013b00 : 0xffffff8016a076f5 mach_kernel : _kdp_i386_trap + 0x145
0xffffffdc79013b40 : 0xffffff80169f70e3 mach_kernel : _kernel_trap + 0x533
0xffffffdc79013b90 : 0xffffff8016850a7f mach_kernel : _return_from_trap + 0xff
0xffffffdc79013bb0 : 0xffffff80168b118d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffdc79013cd0 : 0xffffff80168b0946 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xffffffdc79013d30 : 0xffffff801711c019 mach_kernel : _panic + 0x54
0xffffffdc79013da0 : 0xffffff8017048b81 mach_kernel : __ZN9IOService12ackTimerTickEv + 0x801
0xffffffdc79013e00 : 0xffffff8017048349 mach_kernel : __ZN9IOService21actionAckTimerExpiredEP8OSObjectPvS2_S2_S2_ + 0x9
0xffffffdc79013e10 : 0xffffff80170614ae mach_kernel : __ZN10IOWorkLoop9runActionEPFiP8OSObjectPvS2_S2_S2_ES1_S2_S2_S2_S2_ + 0x3e
0xffffffdc79013e50 : 0xffffff80170470d8 mach_kernel : __ZN9IOService17ack_timer_expiredEPvS0_ + 0x38
0xffffffdc79013e70 : 0xffffff80168ffca5 mach_kernel : _thread_call_delayed_timer + 0x4f5
0xffffffdc79013ee0 : 0xffffff8016900cf2 mach_kernel : _thread_call_delayed_timer + 0x1542
0xffffffdc79013fa0 : 0xffffff801685018e mach_kernel : _call_continuation + 0x2e

Process name corresponding to current thread (0xffffff86a9b328b0): kernel_task
Boot args: keepsyms=1 -v -lilubetaall

Mac OS version:
21A5248p

Kernel version:
Darwin Kernel Version 21.0.0: Thu May 27 21:01:58 PDT 2021; root:xnu-7938.0.0.111.2~2/RELEASE_X86_64
Kernel UUID: 338A6A5D-63E1-310A-8E0E-9721D4D78446
KernelCache slide: 0x0000000016600000
KernelCache base:  0xffffff8016800000
Kernel slide:      0x0000000016610000
Kernel text base:  0xffffff8016810000
__HIB  text base: 0xffffff8016700000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 1690713976921
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000189a667f78f
  Sleep   : 0x00000186fbf08437 0x00000007295d0506 0x0000000000000000
  Wake    : 0x0000018743fdbfac 0x0000000094fcfe70 0x000001874297bda8

**Comment by vit9696** [comment]
Please confirm the fix.

**Comment by pavelchup** [comment]
It Works like before! Thx a lot.
