### ISSUE TITLE
SidecarFixup broken on macOS 12

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#1677]
[Lilu_1.5.4_21.0.txt.zip](https://github.com/acidanthera/bugtracker/files/6634337/Lilu_1.5.4_21.0.txt.zip)

dyld_shared_cache:
https://drive.google.com/file/d/1uLVQUuB7W6Y3jyjH_Qvch3_Tx2jkYhFP/view?usp=sharing

**Comment by vit9696** [comment]
No RestrictEvents log. I would expect the patch sequence to change simply.

**Comment by Andrey1970AppleLife** [comment]
Works with 
![Снимок экрана 2021-06-11 в 03 42 02](https://user-images.githubusercontent.com/17758753/121615199-fe7dd100-ca68-11eb-832b-10c9c31749dd.png)
But BigSur broken.

**Comment by vit9696** [comment]
Should be fixed in https://github.com/acidanthera/SidecarFixup/commit/35fa25d1741a185dcd29094f423fa3261873af50. Please check. Also check RestrictEvents, which will have to change as a result of Lilu updates.
