### ISSUE TITLE
[OpenCore] Dext loading

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1678]
Hi there,
I'd like to know if OpenCore will ever support DEXT (driver extension) loading from a custom folder (such as `EFI/OC/Dexts`).
A practical usage of this could be for example, loading custom drivers for LAN adapters (such as many ASIX USB3 to LAN 1gbps adapters)
Let me know your thoughts on that
Greetings

**Comment by vit9696** [comment]
Not possible, OpenCore has no access to userspace.

**Comment by dreamwhite** [comment]
> Not possible, OpenCore has no access to userspace.

What about Lilu instead? 😅 If user-space patching will be solved on Big Sur, can it be used?

**Comment by vit9696** [comment]
Not worth the effort, which would be very high.

**Comment by dreamwhite** [comment]
Alright, thank you so much anyways ^^
