### ISSUE TITLE
Black Screen after wake up from deep idle

### ISSUE THREAD

**Issue by jackjack1-su** [acidanthera/bugtracker#1680]
The screen is black after wakes up from deep sleep with the backlight on my ICL Laptop.
My config is in my repo [https://github.com/jackjack1-su/SP7config](url)
The /var/vm/sleepimage is exist.
I've used some SSDTs to enable deep sleep with AOAC.

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
