### ISSUE TITLE
NVMeFix broken on macOS Monterey Beta

### ISSUE THREAD

**Issue by m0d16l14n1** [acidanthera/bugtracker#1682]
NVMeFix seems to be broken again (no apst in IOreg) > previously it was fixed [here](https://github.com/acidanthera/bugtracker/issues/1620)

Will attach kext from macOS, Lilu log

[Lilu_1.5.4_21.0.txt](https://github.com/acidanthera/bugtracker/files/6641991/Lilu_1.5.4_21.0.txt)
[IONVMeFamily.kext.zip](https://github.com/acidanthera/bugtracker/files/6641992/IONVMeFamily.kext.zip)

Thanks!

**Comment by vit9696** [comment]
Please retest and repeat the logs with master.

**Comment by m0d16l14n1** [comment]
Seems to be fixed! APST and quirks appeared in IONVMeController, thank you!

[Lilu_1.5.4_21.0.txt](https://github.com/acidanthera/bugtracker/files/6642489/Lilu_1.5.4_21.0.txt)
