### ISSUE TITLE
OCValidate length of path now in error for entries

### ISSUE THREAD

**Issue by Matgen84** [acidanthera/bugtracker#1683]
Hi 

I build latest commit a30fd31b and update my EFI folder. When I check my config.plist, OC Validate find an error: 
`Misc->Entries[0]->Path is too long (should not exceed 128)!
CheckMisc returns 1 error!`

My misc/entries path: PciRoot(0x0)/Pci(0x17,0x0)/Sata(0x2,0xFFFF,0x0)/HD(2,GPT,F15186C6-F501-4C1C-9BCF-990FF40BB10D,0x109000,0x31800)/\EFI\Microsoft\Boot\bootmgfw.efi

The sample.plist path: PciRoot(0x0)/Pci(0x1,0x1)/Pci(0x0,0x0)/NVMe(0x1,11-22-33-44-55-66-77-88)/HD(1,GPT,00000000-0000-0000-0000-000000000000,0x800,0x64000)/\EFI\BOOT\BOOTX64.EFI

The length seems to be the same !

**Comment by btwise** [comment]
@Matgen84 
Yes, the length of the path address will generally exceed 128, so this judgment should not be

**Comment by vit9696** [comment]
We shall not impose the path length limits on device paths, this is a false positive.

**Comment by PMheart** [comment]
Hello! Sorry for my mistake! It is fixed.
