### ISSUE TITLE
There seems to be an error in ValidateKernel.c!

### ISSUE THREAD

**Issue by btwise** [acidanthera/bugtracker#1684]
@PMheart 
In line 422 of ValidateKernel.c, is` sizeof (UserKernel->Emulate.Cpuid1Mask)`  missing? the compilation failed!
![image](https://user-images.githubusercontent.com/38809560/121801474-022c7600-cc6a-11eb-956f-812f8d40a752.png)

**Comment by PMheart** [comment]
Hello. Sorry for my ignorance! It is fixed now.
