### ISSUE TITLE
AppleXcpmForceBoost quirk doesnt work on macos 12

### ISSUE THREAD

**Issue by narcyzzo** [acidanthera/bugtracker#1685]
Cpu cores doesnt stay on highest clock, macos Monterey 12, latest commit open core compiled.

**Comment by PMheart** [comment]
Hello, please try the artifacts [here](https://github.com/acidanthera/OpenCorePkg/actions/runs/937707337) and report. Thanks!

**Comment by narcyzzo** [comment]
Fixed! Thanks:)
