### ISSUE TITLE
[ocvalidate] BluetoolFixup kext precedence

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1688]
Hi there,
I'm opening this issue since [BrcmPatchRAM commit d1378e](https://github.com/acidanthera/BrcmPatchRAM/commit/d1378ed36687aa1e1dd72b93af9a5bd57cd30ad8) introduced BluetoolFixup kext.
Is there any sort of precedence for BluetoolFixup or can it just be injected after BrcmPatchRAM3?
Let me know your thoughts

**Comment by vit9696** [comment]
Precedence is a thing defined by the dependencies. I do not understand the question: just check the Info.plist.
