### ISSUE TITLE
Bluetooth Firmware not Loaded in Hackintool

### ISSUE THREAD

**Issue by rcpag1103** [acidanthera/bugtracker#1689]
Bluetooth works in Monterey when using the BlueToolFixup.kext however below are the bugs:

Bluetooth Firmware not Loaded in Hackintool as per attached screenshot
when switching off the bluetooth, you can no longer switch it on
I also attach the normal working bluetooth in Big Sur
![Screenshot 2021-06-14 at 4 12 19 PM](https://user-images.githubusercontent.com/57674267/121862485-69f7c500-cd2d-11eb-91b0-44fef622735f.png)
![Screenshot 2021-06-14 at 4 09 32 PM](https://user-images.githubusercontent.com/57674267/121862491-6b28f200-cd2d-11eb-97e3-13c823fc7bde.png)

**Comment by vit9696** [comment]
File Hackintool bugs in Hackintool repo.

**Comment by Sosueyakiko** [comment]
> File Hackintool bugs in Hackintool repo.

Actually, I think his point was the firmware.
DId you notice that he had the wrong firmware version for DW1820A? 
I am facing the exact same situation. The Bluetooth information showed in the System Report isn't complete. And Bluetooth isn't fully functioning.
I think it should be something like this:
生产企业： Broadcom
传输： USB
芯片组： Unknown (6e)
固件版本： v7 c5799
蓝牙电源： 打开
可被发现： 打开
可连接： 是
自动寻找点： 打开
远程唤醒： 打开
供应商ID： 0x0A5C
产品ID： 0x6412
蓝牙核心规范： 4.1 (0x7)
HCI修正版： 0x16A7
LMP版本： 4.1 (0x7)
LMP子版本： 0x6607
设备类型（主要）： Computer
设备类型（完整）： Mac Portable
复合类设备： 0x38010C
设备类（主要）： 0x01
设备类（次要）： 0x03
服务类： 0x1C0
自动寻找键盘： 打开

But instead, we are getting this:
![image](https://user-images.githubusercontent.com/23533993/135962167-35f9deeb-d1c7-43f1-aaac-3fb66de013d7.png)
and nothing more.
Running log show --last boot | grep -y brcmpatchram in terminal only gets:
shinokuiwai@iwaishioMacBook ~ % log show --last boot | grep -y brcmpatchram
2021-10-05 12:30:17.394418+0800 0x512      Default     0x0                  136    0    kernelmanagerd: Received kext load notification: as.acidanthera.BrcmPatchRAM3
zsh: segmentation fault  log show --last boot | 
zsh: done                grep -y brcmpatchram

This card worked fine under High SIerra and Catalina.
