### ISSUE TITLE
IntelMausi Wake on LAN variant

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1690]
Hi, I've tested [IntelMausi-WOL](https://github.com/fischerscode/IntelMausi-WOL) fork from @fischerscode and it works very well when sending the magic packet from the S5 state with a I219-V2 on an Asus Z370 chipset. I'm asking if this variant can be merged in [acidanthera/IntelMausi](https://github.com/acidanthera/IntelMausi), possibly as a variant (such as `IntelSnowMausi.kext`)?

These are the changes from the fork, it should be a quick and easy merge (only the relevant stuff for WoL)
https://github.com/acidanthera/IntelMausi/compare/master...fischerscode:master

**Comment by vit9696** [comment]
Please confirm working.

**Comment by 1alessandro1** [comment]
Perfect, it works flawlessly
