### ISSUE TITLE
RestrictEvents CPU Name Issue with AMD Ryzen 5900X

### ISSUE THREAD

**Issue by AudioG** [acidanthera/bugtracker#1692]
RestrictEvents 1.0.3 latest commit is no longer displaying my 5900X correctly in About This Mac

@vit9696 As you requested I removed all user space plugins and also have disabled all unneeded kexts while testing.
everything else is up to its latest commits and im using OpenCore 0.7.1

[Lilu_1.5.4_20.5.txt.zip](https://github.com/acidanthera/bugtracker/files/6658620/Lilu_1.5.4_20.5.txt.zip)
[Terminal_Saved_Output.zip](https://github.com/acidanthera/bugtracker/files/6658621/Terminal_Saved_Output.zip)
[opencore-2021-06-15-204049.txt.zip](https://github.com/acidanthera/bugtracker/files/6658636/opencore-2021-06-15-204049.txt.zip)

**Comment by vit9696** [comment]
Hi, does downgrading RestrictEvents to 9227dc5 (https://dortania.github.io/builds/?product=RestrictEvents&viewall=true) solve the issue? Leaving the latest Lilu version.

**Comment by vit9696** [comment]
Also, please try https://github.com/acidanthera/Lilu/commit/96b9c3f646084f0248bfe22d1e22db782082effe with both RestrictEvents 9227dc5 and master. I believe it may fix your issue. If it does not, reopen.

**Comment by AudioG** [comment]
Lilu 96b9c3f totally Fixed it using the Latest RestrictEvents. Having AVX2 is just amazing. Thank you so much @vit9696  You're a Legend.
