### ISSUE TITLE
Installing Monterey error Attempting system restart MACH Reboot

### ISSUE THREAD

**Issue by qhdcjm** [acidanthera/bugtracker#1693]
On the x99 platform, there is no problem with macOS bigsur11.5 at present. The upgrade macOS Monterey is stuck in the position as shown in the figure below. My computer configuration: X99A-RAIDER, 5820k, gtx780 
![131151dekrtpp9oxp6teek](https://user-images.githubusercontent.com/43429413/122327229-1c16d300-cf60-11eb-9a6d-628111e000fa.jpg)

**Comment by qhdcjm** [comment]
![131151dekrtpp9oxp6teek](https://user-images.githubusercontent.com/43429413/122327347-4a94ae00-cf60-11eb-9ab8-01c92427ac86.jpg)

**Comment by MOON202** [comment]
**Put the code in config.plist**
```
<key>ACPI</key>
<key>DropTables</key>
<array>
  <dict>
    <key>Signature</key>
    <string>MATS</string>
  </dict>
  <dict>
    <key>Signature</key>
    <string>DMAR</string>
  </dict>
  <dict>
    <key>Signature</key>
    <string>BGRT</string>
  </dict>
</array>
```

**Comment by qhdcjm** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
