### ISSUE TITLE
Windows 11 Icons in OpenCanopy

### ISSUE THREAD

**Issue by Human7900** [acidanthera/bugtracker#1694]
Hi
As of now, the Windows icons for OpenCanopy are specified as `Windows.icns`.
However, I am planning to double boot Windows 10 and Windows11. So to separate Windows 11 icons from Windows 10, can the Windows 11 icons be specified as `Windows11.icns`.
Regards.

**Comment by andreszerocross** [comment]
You can use "Flavour" feature of OpenCore,,
Read this https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Flavours.md

**Comment by MikeBeaton** [comment]
No, he's right, it should be added in the flavour spec. Will do.

**Comment by vit9696** [comment]
Windows 11 is not yet even published. How can we add anything before the announcement?

**Comment by MikeBeaton** [comment]
Oh - fair point. I guess we don't know for sure what it will even be known as, by the time it goes from early rumours to release?

I've just put in Apple12 and Windows11 - how should I leave it? Roll back Windows11 and leave Apple12?

**Comment by 1alessandro1** [comment]
> How can we add anything before the announcement?

They've announced the EOL of windows10 

https://docs.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro

And online there're leaks of the Windows11 beta iso

[![1623777970-windows-11-iso-leak-story.jpg](https://i.postimg.cc/SKqShV3P/1623777970-windows-11-iso-leak-story.jpg)](https://postimg.cc/DSjkQQ2Q)

**Comment by MikeBeaton** [comment]
Yes, I believe Vit would be aware of that! Probably waiting (at least) to see exactly what is announced on 24th June.

**Comment by vit9696** [comment]
> I've just put in Apple12 and Windows11 - how should I leave it? Roll back Windows11 and leave Apple12?

Yes.

> They've announced the EOL of windows10

This only means they have some Windows 10 _builds_ supported till a certain moment.

> And online there're leaks of the Windows11 beta iso

We cannot guarantee Windows 11 is going to be called Windows 11 once released.

**Comment by 1alessandro1** [comment]
> We cannot guarantee Windows 11 is going to be called Windows 11 once released

True, personally I'd suggest @MikeBeaton to apply the modifications on a PR (if it's not too long to implement) and merge if Microsoft confirms it later

**Comment by MikeBeaton** [comment]
@vit9696 - Done

@Human7900 - There is nothing to stop you using e.g. "Windows11:Windows" as a flavour right now, with your own Windows11.icns file, but - as just decided - it is too early for us to be definitive about our recommended name for this icon, so far.

**Comment by MikeBeaton** [comment]
> > We cannot guarantee Windows 11 is going to be called Windows 11 once released
> 
> True, personally I'd suggest @MikeBeaton to apply the modifications on a PR (if it's not too long to implement) and merge if Microsoft confirms it later

@1alessandro1 - It's literally a naming recommendation, one line in a doc - it's just a matter of making sure we recommend the right name

**Comment by Andrey1970AppleLife** [comment]
Once long ago Microsoft said that the name Windows10 will forever and not change. :)

**Comment by Human7900** [comment]
> Once long ago Microsoft said that the name Windows10 will forever and not change. :)

I think they were just tired of people ranting about Windows 10 and every update that came with it.

**Comment by Human7900** [comment]
Microsoft has announced Windows 11.

**Comment by MikeBeaton** [comment]
Yes - I think I'd be happy to just make the `Windows11` icon/flavour name official in OC at this point - even though I believe there is still no official version of Windows 11 available outside MS yet, not even on any insider channel? But I would like to get the go-ahead from @vit9696 before proceeding - this time!

**Comment by vit9696** [comment]
Well, they did make an announcement, probably ok now.

**Comment by Human7900** [comment]
> Yes - I think I'd be happy to just make the `Windows11` icon/flavour name official in OC at this point - even though I believe there is still no official version of Windows 11 available outside MS yet, not even on any insider channel? 

It will be available in 2-3 days to insiders.

**Comment by MikeBeaton** [comment]
https://github.com/acidanthera/OpenCorePkg/commit/403f351da441d6eea965cb41b8701bf5a4312fb7
