### ISSUE TITLE
Inject EDID Features on the fly features

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#1695]
Several notebooks get black screen issue when using properly ig-platform-id.

This problem known as EDID problem.

In CLOVER bootloader we can use "Inject EDID" features, so we can grab "good EDID" in IOREG after reach macOS Desktop and inject it to config.plist or DSDT/SSDT later and turn off this features.

Can OpenCore add this features too??

Grab EDID from windows and inject to config.plist sometimes still give black screen, i don't know what CLOVER did with this features. But we can get good EDID value in IOREG after use this features in CLOVER.

Thanks again

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#edid

**Comment by andreszerocross** [comment]
I already know how to inject EDID with Config.plist in Opencore.

The problem is, if the notebook doesn't have anyd OS intalled. Then how can we get EDID value?? It will nice if OpenCore have this features. So we doesn't need to install Windows / Linux First to grab EDID

**Comment by vit9696** [comment]
Feel free to point to a more specific requested feature. We do not do magic here. if I remember correctly, injecting EDID some while ago injected named framebuffer on AMD, so whatever you refer to likely is unrelated to the EDID, and we are not keen on exploring Clover specifics.
