### ISSUE TITLE
Recovery 10.9 LoadImage Failed - Unsupported

### ISSUE THREAD

**Issue by krypton-kry** [acidanthera/bugtracker#1697]
Chipset : SandyBridge
OC Version : 0.7.0

Unable to boot into recovery 10.9, I've attached the logs and the EFI folder

[opencore-2005-01-01-002344.txt](https://github.com/acidanthera/bugtracker/files/6680665/opencore-2005-01-01-002344.txt)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/6680669/EFI.zip)

**Comment by 1alessandro1** [comment]
I confirm that booting recoveries before 10.11 with the folder `com.apple.recovery.boot` and the correct HfsPlus driver version presents the same problem (Loadimage failed)

**Comment by vit9696** [comment]
Please RTFM before opening issues.
REF: https://github.com/acidanthera/OpenCorePkg/blob/0.7.0/Docs/Configuration.tex#L7414-L7421
