### ISSUE TITLE
Waking laptop with keystroke causes 'stuck' key entry in password field

### ISSUE THREAD

**Issue by TonyC5** [acidanthera/bugtracker#1699]
With VoodooPS2Conroller.kext 2.2.3, waking my laptop with a key press results in a "stuck" key that inserts repeated entry in password field of the lock screen.  This "stuck" key that repeatedly "types" in the password field prevents me from entering a password at the lock screen.  The only way to recover is to press and hold the power button to force shutdown.

If I wake my laptop by pressing the power button or by opening the lid (if the lid is closed when sleeping), there are no problems.  This problem only happens when waking the laptop by pressing a key on the keyboard.  My work-around is to wake the laptop with the power button (which works fine).

My configuration is as follows:

- OpenCore 0.7.0
- SMBIOS MacBookPro 14,1
- VoodooPS2Controller.kext 2.2.3
- DisableDeepSleep enabled to workaround ACPI S3 wake in my Synaptics touchpad
- Big Sur 11.4 (problem also happens with Catalina 10.15.7)

My rig is as follows:
- HP Envy x360 15m, Kabylake Refresh i5-8250U, UHD620
- Synaptics Touchpad
- Full built-in keyboard (with number pad)
- 12GB DDR4 RAM, 512GB NVMe SSD, 1TB SATA HD
- Touchscreen (but I do not have I2C kexts installed, so touchscreen is not operational in macOS)

**Comment by vit9696** [comment]
- Which macOS is that? Are all versions affected?
- Please test master first.
- If this is a regression, please provide a working and a not working commit. Builds are here: https://dortania.github.io/builds/?product=VoodooPS2&viewall=true.
- If this is a new issue, I may have to suggest you to debug it yourself as there are way too many configurations.

cc @usr-sse2 @zhen-zen @Goshin
