### ISSUE TITLE
[RestrictEvents] eficheck spams console log only when Kext enabled

### ISSUE THREAD

**Issue by MysticalOS** [acidanthera/bugtracker#1700]
When RestrictEvents is enabled, console is spammed to death by eficheck, if I disable RestrictEvents the spam goes away. I understand RestrictEvents is supposed to stop this proccess, but how can it be done quietly?

> Jun 20 11:53:13 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[998]): Service could not initialize: 20F71: xpcproxy + 23787 [839][2E55E87B-4D87-3489-8730-FE75D5535FEA]: 0x1
> Jun 20 11:53:13 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[998]): Service exited with abnormal code: 78
> Jun 20 11:53:13 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
> Jun 20 11:53:23 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[1010]): Service could not initialize: 20F71: xpcproxy + 23787 [839][2E55E87B-4D87-3489-8730-FE75D5535FEA]: 0x1
> Jun 20 11:53:23 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[1010]): Service exited with abnormal code: 78
> Jun 20 11:53:23 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
> Jun 20 11:53:33 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[1011]): Service could not initialize: 20F71: xpcproxy + 23787 [839][2E55E87B-4D87-3489-8730-FE75D5535FEA]: 0x1
> Jun 20 11:53:33 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[1011]): Service exited with abnormal code: 78
> Jun 20 11:53:33 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
> Jun 20 11:53:43 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[1012]): Service could not initialize: 20F71: xpcproxy + 23787 [839][2E55E87B-4D87-3489-8730-FE75D5535FEA]: 0x1
> Jun 20 11:53:43 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[1012]): Service exited with abnormal code: 78
> Jun 20 11:53:43 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
> Jun 20 11:53:53 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[1013]): Service could not initialize: 20F71: xpcproxy + 23787 [839][2E55E87B-4D87-3489-8730-FE75D5535FEA]: 0x1
> Jun 20 11:53:53 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[1013]): Service exited with abnormal code: 78
> Jun 20 11:53:53 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
> Jun 20 11:54:03 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[1018]): Service could not initialize: 20F71: xpcproxy + 23787 [839][2E55E87B-4D87-3489-8730-FE75D5535FEA]: 0x1
> Jun 20 11:54:03 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck[1018]): Service exited with abnormal code: 78
> Jun 20 11:54:03 Omega-4 com.apple.xpc.launchd[1] (com.apple.driver.eficheck): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

**Comment by vit9696** [comment]
How do you reproduce this? The following gives me nothing.

```
% kextstat | grep Restric    
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
   52    0 0                  0xc000     0xc000     as.vit9696.RestrictEvents (1.0.2) 35C14FCC-917A-32E9-A189-A7D20D014E56 <48 8 6 5 3 2 1>
% log stream  | grep eficheck
``

**Comment by MysticalOS** [comment]
nothing special, OC 0.7.0, macOS 11.4, All plugins up to date. Config and SSDT patches perfect by all accounts for my gigabyte coffee lake build.

although I only recently added restrictevents, I was running fine without it but figured no harm in adding it. Adding it resulted in above error spam though. I don't have it enabled right now but if you have any debug ideas you want me to play with I can re-enable and try whatever.

**Comment by perez987** [comment]
I have RestrictEvents enabled and the behaviour is the same as @vit9696 says in his post.

Z390 Aorus Elite, Coffee Lake R, RX580, Big Sur 11.4, OpenCore 0.7.1, MacPro7,1.

**Comment by vit9696** [comment]
@MysticalOS

- do you confirm the command I pasted prints these messages for you?
- do you have `Automatic` = YES in your `OC` `PlatformInfo` settings?

**Comment by MysticalOS** [comment]
```
myst@Omega-4 ~ % kextstat | grep Restric
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
   52    0 0                  0xc000     0xc000     as.vit9696.RestrictEvents (1.0.2) FE9382AB-6BE3-3355-8FB9-13447B621DB8 <48 8 6 5 3 2 1>
```

Right now it's not spamming eficheck in logs after enabling again, since i allowed it to run earlier. It probably won't run again for 7 days if I read how it works correctly.

Guess I'll report back if it happens again. I'll leave RestrictEvents enabled of course.

**Comment by Sher1ocks** [comment]
good info. thank you!
i'm back to EFICheckDisabler.kext. no more loop log
