### ISSUE TITLE
Corrupted images, videos and animated gifs in Big Sur 11.2.3 on MacPro5,1 + RX580

### ISSUE THREAD

**Issue by ylluminate** [acidanthera/bugtracker#1701]
MacPro5,1 + Radeon RX 580 8 GB with macOS BS 11.2.3 OC installation via OCLP with OC 0.7 + Lilu 1.5.4 (06/15 build) and WhateverGreen 1.5.1 (06/08 build).

Experiencing corrupted images, video and GIFs sporadically after a few hours of operations:

Images:
![appstore](https://p153.p0.n0.cdn.getcloudapp.com/items/kpuDD7JR/0005ad28-f3e4-4108-bed6-4f1d2d6d2ccb.jpg?v=2b91748b0a929c93c6f55d35a4cd5784)

In Discord client + Chrome and Safari sometimes I get red GIFs that when you click them multiple times sometimes it tries to animate, but then fails and sometimes starts correctly and plays through - very peculiar behavior:
![red](https://p153.p0.n0.cdn.getcloudapp.com/items/kpuDD7e8/3dee47ec-0767-4c4c-81b4-88ca9ce05e94.jpg?v=16160a28ee51e57b68b417b1dcccfbf5)

I have seen this on some YouTube videos, but not others as well and it seems to be without rhyme or reason as to which ones do this.

When I attempt to do a video recording with Screenflow 9.0.7 to demonstrate the above I receive a crash:
```
Graphics kernel error: 0xfffffffc
```

EFI folder + OC debug log: [EFI_log.zip](https://p153.p0.n0.cdn.getcloudapp.com/items/WnuxxB9r/1b049bc8-ab1f-4812-a7bd-6b5dc49641af.zip)

**Comment by Andrey1970AppleLife** [comment]
Go to https://github.com/dortania/bugtracker/issues

**Comment by ylluminate** [comment]
@Andrey1970AppleLife 	I do not believe this pertains to them - I think this must have to do with WhateverGreen and GPU support in some fashion.

**Comment by vit9696** [comment]
This is a longstanding Apple bug with AMD Polaris GPUs. Unfortunately there are no solutions yet. See these links:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1711944
- https://bugzilla.mozilla.org/show_bug.cgi?id=1713230

**Comment by ylluminate** [comment]
Wow - thanks for finding this / being aware @vit9696. It appears that this may be limited to `AMDRadeonX4000` and `AppleIntelHD5000Graphics` from what you shared there (particularly [this; #1713230](https://bugzilla.mozilla.org/show_bug.cgi?id=1713230)). It would, therefore, seem that a GPU that uses `AMDRadeonX5000` instead might be less / not prone to this problem... Hmmm.  Have you seen this to be the case in your observations?

**Comment by vit9696** [comment]
Somewhat, but it really depends. I have RX 590 myself, and many people here say it has no issues, which is blatant lies. These people simply do not run macOS for weeks without reboots on 4K screens full of resource heavy applications. I have a suspect if I buy a new GPU I would have similar issues just under a different sauce :D. What I noticed is the more VRAM the better, but macOS graphics stack is so bugged that every wild thing is possible.

**Comment by ylluminate** [comment]
I put a laugh there, but it's more of a grimace... I, like you, am a heavy resource user with long uptimes. I have a VEGA 64 that I suppose I'll go back to on this machine to see if the `AMDRadeonX5000` improves the situation, but I lose a monitor this way since I cannot get DisplayLink working. It's a very frustrating situation. Even with the `AMDRadeonX5000` I still have encoding problems in some places it seems and no one is able to trace them out to the root cause.
