### ISSUE TITLE
OpenCanopy: Fade on overlong text is only correct for black background

### ISSUE THREAD

**Issue by mikebeaton** [acidanthera/bugtracker#1702]
![image](https://user-images.githubusercontent.com/11946605/122747802-61e6da80-d283-11eb-9ba7-20bc727d841f.png)

**Comment by MikeBeaton** [comment]
Have double-checked with @vit9696 and @mhaeuser and confirmed genuine issue

**Comment by mikebeaton** [comment]
![06180115](https://user-images.githubusercontent.com/11946605/140896149-a9f20527-bc04-4094-bf4b-92e3bb35e304.png)

**Comment by mikebeaton** [comment]
Ahh - that's the thumbs up I was looking for! 😉😊
