### ISSUE TITLE
KP injecting Ethernetcard Intel i210 

### ISSUE THREAD

**Issue by ornulf** [acidanthera/bugtracker#1704]
Intel i210 Ethernetcard (8086 1043) gives me KP as soon as I connect a lan-cable to any of the two ports. If I boot with any of the cables attached I get KP just before or a little bit after the login screen. Without cables connected or card disabled in bios booting works fine with both OC 0.6.9 and 0.7.0 The problem occurs only with Big Sur 11.4. Big Sur 11.3 works great with both OC 0.6.9 and 0.7.0.
Everything works fine with Clover ver. 5137

[Archive.zip](https://github.com/acidanthera/bugtracker/files/6696560/Archive.zip)

**Comment by vit9696** [comment]
May want to force-inject the kext instead of dext. But this is not a support forum.

**Comment by 82ghost82** [comment]
@ornulf 
Just to help, if you didn't read it:
https://www.insanelymac.com/forum/topic/348114-cant-update-big-sur-113-to-114/?do=findComment&comment=2761454

^
(as described by vit)
