### ISSUE TITLE
OpenCanopy: Startup sound plays twice

### ISSUE THREAD

**Issue by MysticalOS** [acidanthera/bugtracker#1705]
I have found recently that if I hit the enter key during the startup sound playing, it actually causes it to play again. I can pretty much trigger the bug by hitting enter key as soon as I hear first playback. If I hit enter after playback or toward end of it, the repeat sound doesn't happen.

I'd consider this a super minor non breaking issue, but a bug non the less. :)

**Comment by vit9696** [comment]
I think it is a known issue of some codecs we are not sure how to properly approach. Closing as a duplicate of https://github.com/acidanthera/bugtracker/issues/740.
