### ISSUE TITLE
ocvalidate fails on checking config.plist

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1706]
OpenCore version tested:  ~~master, https://github.com/acidanthera/OpenCorePkg/commit/9b3e3eeaa5bf303a7382f93064dfeebec45caf37~~ https://github.com/acidanthera/OpenCorePkg/actions/runs/963136732

When executing ocvalidate, it throws this error:

```
./ocvalidate /Users/username/config.plist
ASSERT [OpenCore] OcXmlLib.c(579): Attributes != ((void *) 0)
```

and hangs there. I can share the config.plist if required

**Comment by 1alessandro1** [comment]
I've inadvertently taken the latest builds from the PR which is currently a draft, the latest commit has no issues

**Comment by PMheart** [comment]
Hello! In spite of a draft, I think that it has been fixed in my last commit. Could you please test again if you like? Thanks!

**Comment by 1alessandro1** [comment]
@PMheart now the previous issue is gone, however it seems like it does not like the `config.plist` very much, and I've checked it with the master version too

![image](https://user-images.githubusercontent.com/46293832/123297833-392b4300-d518-11eb-996c-80cf06c3b4af.png)

**Comment by PMheart** [comment]
Hi @1alessandro1! Sorry for the late response! I have pushed new commits to the PR. Could you please test it again? Thanks!

Also, I will leave this issue open until resolved.

**Comment by PMheart** [comment]
Fixed.

**Comment by 1alessandro1** [comment]
Sorry for my late response @PMheart, it is fixed now, tested with [this build](https://github.com/acidanthera/OpenCorePkg/actions/runs/975606554)
