### ISSUE TITLE
Output text message from TpmInfo is displayed for a very short time

### ISSUE THREAD

**Issue by perez987** [acidanthera/bugtracker#1709]
First of all, thank you very much for your work.
When I run the TpmInfo tool, output info text message is displayed for such a short time that I can't read what it says.
This happens with the TextMode property false and true.
Big Sur 11.4 + OpenCore 0.7.1 build ffc3dab.

**Comment by vit9696** [comment]
Not a bug. Use UEFI Shell.

**Comment by perez987** [comment]
From UEFI Shell it works fine. Thanks.
![tpminfo](https://user-images.githubusercontent.com/50429399/123559287-60de0d80-d79b-11eb-9620-0ce1103f93bf.png)
