### ISSUE TITLE
OC keeps rebooting at line "AmiShimTimerBoostExit changed current period to 549254"

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1710]
OC keeps rebooting on Z77MX-QUO-AOS with [OC friendly bios](https://github.com/Kazbah/Z77MX-QUO-AOS-OpenCore-Migration-Kit)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/6722403/EFI.zip)
[opencore-2021-06-27-223035.txt](https://github.com/acidanthera/bugtracker/files/6722404/opencore-2021-06-27-223035.txt)

**Comment by startergo** [comment]
Enabled ```Execute Disable Bit``` and it was fixed

**Comment by adahox** [comment]
where should i enable this ?

**Comment by AndreyNag** [comment]
> 
> where should i enable this ?

in the BIOS settings!

**Comment by startergo** [comment]
>CFG Lock (MSR 0xE2 write protection)(This must be off, if you can't find the option then enable AppleXcpmCfgLock under Kernel -> Quirks. Your hack will not boot with CFG-Lock enabled)
For 10.10 and older, you'll need to enable AppleCpuPmCfgLock as well
[#](https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html#enable)
