### ISSUE TITLE
Boot Chime can only be heard using headphones on Conxexant 20724

### ISSUE THREAD

**Issue by i-do-know-who-i-am** [acidanthera/bugtracker#1711]
Boot Chime can only be heard using headphones on Conxexant 20724. The same thing happens with macOS Powerchime (the sound when you plug in the charger).

**Comment by Andrey1970AppleLife** [comment]
Specify AudioOut in config.plist

**Comment by i-do-know-who-i-am** [comment]
Hi @Andrey1970AppleLife,
Can you elaborate what I have to do? Sorry, I may appear dumb but please help me.
Regards.

**Comment by i-do-know-who-i-am** [comment]
I know this is not a support from, I would not like to waste your precious time but there is no information whatsoever regarding AudioOut in any forum. Any information would be appreciated.
Regards.

**Comment by vit9696** [comment]
Alright, but can you explain why are you looking for AudioOut information on the forums instead of the official reference manual? Here is a link for you: https://github.com/acidanthera/OpenCorePkg/blob/0.7.0/Docs/Configuration.tex#L6516

**Comment by i-do-know-who-i-am** [comment]
> Alright, but can you explain why are you looking for AudioOut information on the forums instead of the official reference manual? Here is a link for you: https://github.com/acidanthera/OpenCorePkg/blob/0.7.0/Docs/Configuration.tex#L6516

It is a little too technical for me. I couldn't understand what do to. Again, I'm sorry.
Regards.

**Comment by i-do-know-who-i-am** [comment]
@vit9696 So I did try all the values for AudioOut but it does no work.
Attaching EFI and Log. 
Regards.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/6753665/EFI.zip)
[opencore-2021-07-02-090841.txt](https://github.com/acidanthera/bugtracker/files/6753674/opencore-2021-07-02-090841.txt)

**Comment by ggoraa** [comment]
The thing is, that it is actually an issue. I also have Conexant 20724, and also can hear the chime only in headphones.

**Comment by i-do-know-who-i-am** [comment]
So this is not a invalid issue then.

**Comment by vit9696** [comment]
Well, it could be that your audio codec in particular is not properly supported by AudioDxe. However, it is not really possible to fix that without having the codec itself and the desire to improve it. You can always submit a PR with a patch if you resolve the problem.

**Comment by i-do-know-who-i-am** [comment]
This is disappointing, at least for me. Seems like Conxexant 20724 is a odd codec because mute was not supported by AppleALC until Human7900 fixed it in the latest version. Along with the bootchime, macOS Powerchime can only be heard using headphones. Anyway, thank you @vit9696, @Andrey1970AppleLife and @ggoraa for your time.

**Comment by ggoraa** [comment]
I also have a config for you to check out:
https://github.com/ggoraa/Hackintosh-840

**Comment by Human7900** [comment]
@ggoraa Did you make it work?
