### ISSUE TITLE
brcmfx-driver=2 do not work for Monterey

### ISSUE THREAD

**Issue by Matgen84** [acidanthera/bugtracker#1714]
Hi

I hope you will like to answer this issue: since Monterey, brcmfx-driver=2 do not work (Z390 config). The AirPort_Brcm4360 plugin is necessary for my other Hack under Catalina.

AirportBrcmFixup 2.1.3 Beta

Thanks

**Comment by vit9696** [comment]
I believe the support for this driver was removed in macOS 12. Not much to do here. CC @dhinakg @lvs1974 @khronokernel.
