### ISSUE TITLE
Kernel Panic if i enter macos installer without closing secureboot on monterey beta2

### ISSUE THREAD

**Issue by wqhqq1** [acidanthera/bugtracker#1715]
Will attach log file later

**Comment by nadiaholmquist** [comment]
What do you mean by "closing" secure boot?

I have the same problem here, log file: [opencore-2021-07-02-231302.txt](https://github.com/acidanthera/bugtracker/files/6757413/opencore-2021-07-02-231302.txt)

OpenCore 0.7.0
System: ASUS Z170 Pro Gaming Aura | i5-6600K | AMD RX480
SMBIOS: iMacPro1,1, SecureBootModel: j137, ApECID is nonzero

**Comment by wqhqq1** [comment]
I mean that if I disable secure boot, I could boot into installer successfully.
But when secure boot model is set to default, the installer cannot boot correctly but reboot immediately.

**Comment by vit9696** [comment]
> ApECID is nonzero

Your macOS installer has no manifests for `ApECID` 0x7FFFFFFFFFFFFFFF. The value looks strange to me in the first place, as it is clearly not random. Consider zeroing `ApECID`.

**Comment by nadiaholmquist** [comment]
That's it not actually the ApECID in my config.plist, for some reason it seems to not be picking it up right?

**Comment by vit9696** [comment]
It may overflow indeed.

**Comment by dreamwhite** [comment]
I'm not sure if I should ask there for, but despite `ApECID` value set to `0` and `SecureBootModel` set to `j185`(as well as other supported values), I can't boot macOS Monterey beta 4 installer (both when booting the dummy `Macintosh HD` entry and a freshly created installer) as it reboots immediately 😅. I thought that it was an issue on my side but `SecureBootModel` seems not working properly. Should I open another issue and send you OpenCore 0.7.1 DBG logs?
Please let me know your thoughts
Regards
dreamwhite

**Comment by wqhqq1** [comment]
Though I'm now updated to 12.3.1 (21E258), and open core 0.8.0, I'm still unable to OTA with ApECID zero and secure boot model "default". To make installation succeed without reboot loop, I must set secure boot model to "disabled" when updating macOS. It's very complex changing config every time I update macOS. Is there any solution for it?

**Comment by mikebeaton** [comment]
> Though I'm now updated to 12.3.1 (21E258), and open core 0.8.0, I'm still unable to OTA with ApECID zero and secure boot model "default". To make installation succeed without reboot loop, I must set secure boot model to "disabled" when updating macOS. It's very complex changing config every time I update macOS. Is there any solution for it?

This definitely works (e.g. I have this setup on my daily driver). In general, when raising an issue, always provide a debug log and your config.plist (from which you can/should redact serials and passwords) to give people a reasonable chance of helping. But that said, for configuration issues such as this, please use [forums](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/FORUMS.md) for support.

**Comment by wqhqq1** [comment]
I am now using the latest 0.8.0 and full security. MacOS now OTAs properly without boot loop. Thanks for answering for so much time.
