### ISSUE TITLE
OpenCore: Can't use usb keyboard on Windows BitLocker recovery menu

### ISSUE THREAD

**Issue by Halo-Michael** [acidanthera/bugtracker#1716]
I was used OpenCore 0.7.0, with TPM2.0 used BitLocker locked Operating system drive Windows11.
Today I upgraded to OpenCore 0.7.1, and I noticed a new options "SyncTableIds". I think I need that, so I added this entry and set it to "true". Unfortunately when I rebooted my computer, Windows entered into BitLocker recovery menu and it prompts I recently changed my hardware and I needs to entry my recovery code. it doesn't matter, I do have my revovery code.
But unfortunately, keyboard won't work in this menu so I can't entry my recovery code.
It's a usb keyboard connect to the usb2.0 interface on the back of the motherboard. Works on OpenCore Graphics menu but won't work on the followed by BitLocker recovery menu. The keyboard leds didn't off between the two menus. (So I think keyboard control has not yet been transferred?)

**Comment by Human7900** [comment]
Can you disable SyncTableIds and try again?

**Comment by vit9696** [comment]
You do not need this quirk I believe, it is for Windows 7 with custom SLIC.

**Comment by Halo-Michael** [comment]
> You do not need this quirk I believe, it is for Windows 7 with custom SLIC.

Well, this problem is easy to fix. I just need to start Windows directly in the bios without using OpenCore, then the keyboard works and then choose to temporarily disable bitlocker in Windows and restart.
But I think the key point is fix keyboard doesn't work on BitLocker recovery menu via OpenCore boot, not my problem.

**Comment by Halo-Michael** [comment]
I think it is common for users to change the device hardware after enabling bitlocker (even if only a USB flash drive is inserted). If this problem cannot be solved, then the user will have to use a more troublesome method to solve the problem.

**Comment by Halo-Michael** [comment]
@vit9696 so can you re-open it?

**Comment by vit9696** [comment]
Right, I think I got it. So the problem here is not how you reached bitlocker recovery menu, but the fact it is not working correctly. I.e. there are many legitimate ways to enter this bitlocker menu, and it should normally work.

Well, okay. I need the following:
- testing it on Windows 10 as we will not look on Windows 11 unless strictly required.
- a video showing how it behaves (i.e. not working keyboard)
- a video showing how it should behave (i.e. working keyboard)

**Comment by Halo-Michael** [comment]
> Right, I think I got it. So the problem here is not how you reached bitlocker recovery menu, but the fact it is not working correctly. I.e. there are many legitimate ways to enter this bitlocker menu, and it should normally work.
> 
> Well, okay. I need the following:
> 
> * testing it on Windows 10 as we will not look on Windows 11 unless strictly required.
> * a video showing how it behaves (i.e. not working keyboard)
> * a video showing how it should behave (i.e. working keyboard)
> * your EFI directory would help
> * your hardware configuration would help

Except for the first item that is difficult to implement (although this is strange, this is my main device, so I can't downgrade it to Windows 10 quickly), others should be available as soon as possible

**Comment by Halo-Michael** [comment]
> Right, I think I got it. So the problem here is not how you reached bitlocker recovery menu, but the fact it is not working correctly. I.e. there are many legitimate ways to enter this bitlocker menu, and it should normally work.
> 
> Well, okay. I need the following:
> 
> * testing it on Windows 10 as we will not look on Windows 11 unless strictly required.
> * a video showing how it behaves (i.e. not working keyboard)
> * a video showing how it should behave (i.e. working keyboard)
> * your EFI directory would help
> * your hardware configuration would help

Okey, here is the video: https://drive.google.com/file/d/1GDFxqqyQjFfxIGoRJzw11d_2VvddEYqt/view?usp=sharing
And here is my OpenCore and my hardware configurations: https://github.com/Halo-Michael/OC-GA-B250M-EVO-Hackintosh

**Comment by Halo-Michael** [comment]
It seems matter with if I enable the GUI or not...

**Comment by MikeBeaton** [comment]
Have you tried setting `KeySupport=false` and add `OpenUsbKbDxe.efi` to OC drivers list instead? (You should always use one or other of `KeySupport` and `OpenUsbKbDxe` and not both.)

**Comment by Halo-Michael** [comment]
> Have you tried setting `KeySupport=false` and add `OpenUsbKbDxe.efi` to OC drivers list instead? (You should always use one or other of `KeySupport` and `OpenUsbKbDxe` and not both.)

Same, and if I only set KeySupport to false without add OpenUsbKbDxe.efi, keyboard will not works on OpenCore GUI menu but works on BitLocker Recovery menu; if I remove OpenCanopy.efi driver(disable GUI), keyboard will works on both menu.

**Comment by MikeBeaton** [comment]
You have OpenShell.efi installed and enabled as a tool already. You can confirm that this is nothing to do with Windows 11 if you can confirm that kb input is working (or not working) in OpenShell at all the same times that is it working (or not working) in Win11 BitLocker. Could you check that and confirm the answer please?

**Comment by Halo-Michael** [comment]
> You have OpenShell.efi installed and enabled as a tool already. You can confirm that this is nothing to do with Windows 11 if you can confirm that kb input is working (or not working) in OpenShell at all the same times that is it working (or not working) in Win11 BitLocker. Could you check that and confirm the answer?

Well, it works

**Comment by Halo-Michael** [comment]
> > You have OpenShell.efi installed and enabled as a tool already. You can confirm that this is nothing to do with Windows 11 if you can confirm that kb input is working (or not working) in OpenShell at all the same times that is it working (or not working) in Win11 BitLocker. Could you check that and confirm the answer?
> 
> Well, it works

With the GUI mode

**Comment by MikeBeaton** [comment]
Can you confirm whether these are your results:
| KeySupport | OpenUsbKbDxe | OpenCanopy | BitLocker | OpenShell |
|---|---|---|---|---|
|yes|no|yes|kb does not work|works|
|no|yes|yes|kb does not work|works|
|no|no|yes|works|works|
|yes|no|no|works|works|
|no|yes|no|works|works|

**Comment by Halo-Michael** [comment]
> Can you confirm whether these are your results:
> 
> KeySupport	OpenUsbKbDxe	OpenCanopy	BitLocker	OpenShell
> yes	no	yes	kb does not work	works
> no	yes	yes	kb does not work	works
> no	no	yes	works	works
> yes	no	no	works	works
> no	yes	no	works	works

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/GIGABYTE/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/GIGABYTE/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/GIGABYTE/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=ZH-CN style='tab-interval:21.0pt;word-wrap:break-word;text-justify-trim:
punctuation'>




Conditions | Keyboard   status
-- | --
KeySupport | OpenUsbKbDxe | OpenCanopy | OpenCore | BitLocker | OpenShell
yes | no | yes | yes | no | yes
no | yes | yes | yes | no | yes
no | no | yes | no | yes | yes
yes | no | no | yes | yes | yes
no | yes | no | yes | yes | yes




</body>

</html>

**Comment by Halo-Michael** [comment]
> Can you confirm whether these are your results:
> 
> KeySupport	OpenUsbKbDxe	OpenCanopy	BitLocker	OpenShell
> yes	no	yes	kb does not work	works
> no	yes	yes	kb does not work	works
> no	no	yes	works	works
> yes	no	no	works	works
> no	yes	no	works	works

![image](https://user-images.githubusercontent.com/45062120/125204154-6284f680-e2ae-11eb-84ee-f0a913456c01.png)

**Comment by MikeBeaton** [comment]
Can you try starting Windows from OpenShell : OpenCore -> OpenShell -> Windows (e.g. `fs0:\EFI\Microsoft\Boot\bootmgfw.efi`)

**Comment by Halo-Michael** [comment]
> Can you try starting Windows from OpenShell : OpenCore -> OpenShell -> Windows (e.g. `fs0:\EFI\Microsoft\Boot\bootmgfw.efi`)

Keyboard works.

**Comment by vit9696** [comment]
Can I confirm this was OpenCanopy → OpenShell → Windows? If so, can you try creating a custom entry for Windows and choosing `Text` mode?

**Comment by Halo-Michael** [comment]
> Can I confirm this was OpenCanopy → OpenShell → Windows? If so, can you try creating a custom entry for Windows and choosing `Text` mode?

That makes keyboard works🤔

**Comment by Halo-Michael** [comment]
> > Can I confirm this was OpenCanopy → OpenShell → Windows? If so, can you try creating a custom entry for Windows and choosing `Text` mode?
> 
> That makes keyboard works🤔

Also if I set text mode to false, keyboard won’t work.

**Comment by vit9696** [comment]
Right, can you try different values for TextRenderer? I would try `BuiltinText` first and run Windows normally from OpenCanopy. Will ideally need a table with works/does not, and perhaps a list of negative side effects if any.

**Comment by Halo-Michael** [comment]
Well, I guess the key point is I used CrScreenshotDxe.efi😓. Keyboard works fine after remove the item.

**Comment by Halo-Michael** [comment]
BitLocker recovery menu due to the redundant design principle, in order to avoid being unable to enter the system when the number keys in the keyboard are damaged, the F1~F10 button (F10 is regarded as 0) is used as a substitute for the number keyboard, so it conflicts with CrScreenshotDxe.efi, I think this is the reason .😓

**Comment by Halo-Michael** [comment]
I don't think this has much to do with OpenCore itself, so I will close this issue. (Or you can continue to improve the related logic of CrScreenshotDxe.efi)

**Comment by vit9696** [comment]
I think we still need to investigate the compatibility issues, though with lower priority. Can you explain what is valid, and what is not from your previous claims? I.e. does OpenCanopy matter? Or it is it entirely CrScreeshotDxe?

cc @coderush

**Comment by Halo-Michael** [comment]
> I think we still need to investigate the compatibility issues, though with lower priority. Can you explain what is valid, and what is not from your previous claims? I.e. does OpenCanopy matter? Or it is it entirely CrScreeshotDxe?
> 
> cc @NikolajSchlej

OpenCanopy doesn't matter, only CrScreeshotDxe matter.

**Comment by Halo-Michael** [comment]
I was used switch security boot status to trigger bitlocker recovery, so drivers was disabled all and I thought it's cause the GUI -> cause OpenCanopy, but it's not right.

**Comment by Halo-Michael** [comment]
> Do we still have the datapoint that creating a manual entry for Windows with `TextMode=true` fixes the issue, even with `CrScreenshotDxe.efi` installed. Can you confirm? Thx.

Well, keyboard works, and can still get screenshots...
![12124505](https://user-images.githubusercontent.com/45062120/125290018-72eead00-e352-11eb-9a65-3ef00844cee9.png)

**Comment by MikeBeaton** [comment]
@vit9696 - It is still helpful for us if the user can carry out these tests, right? (Starting from a version which does not work, then changing `TextRenderer` to see if any values make it work.)

> Right, can you try different values for TextRenderer? I would try BuiltinText first and run Windows normally from OpenCanopy. Will ideally need a table with works/does not, and perhaps a list of negative side effects if any.

**Comment by Halo-Michael** [comment]
> @vit9696 - It is still helpful for us if the user can carry out these tests, right? (Starting from a version which does not work, then changing `TextRenderer` to see if any values make it work.)
> 
> > Right, can you try different values for TextRenderer? I would try BuiltinText first and run Windows normally from OpenCanopy. Will ideally need a table with works/does not, and perhaps a list of negative side effects if any.

I tried, so I none of those combinations makes keyboard work. This did not match the previous test results, so I finally found the real reason.

**Comment by vit9696** [comment]
So, this is interesting. For us CrScreenshotDxe would work with AppleEvent, by attaching over `AppleEvent→RegisterHandler` on `APPLE_EVENT_TYPE_KEY_UP`. That means all the key events would go to this function. Maybe it steals them from the other input handlers somehow?

CC @MikeBeaton @mhaeuser

**Comment by mhaeuser** [comment]
@vit9696 Not impossible, but should not as polling is disabled with no active handlers

**Comment by vit9696** [comment]
Well, does not CrScreenshotDxe essentially create an active handler? Causing polling to happen...

**Comment by MikeBeaton** [comment]
This is not a general problem with CrScreenshotDxe on all systems

I've been trying using it with BitLocker (both Win 10  and Win 11) on OC-d MacBook Pro and Dell hack - and there are no problems.

Well, the F10 key within BitLocker is a problem, since BitLocker wants to use it - on the hack it takes takes a screenshot of the BitLocker screen but then hangs all further kb input; on the MBP it fails to take a valid screenshot (saves a 677 byte long invalid file) but does not crash further input.

I think these are not unexpected results? Or, at least, are not the same bug as this issue.

In no case I've tested so far does having CrScreenshotDxe immediately prevent all kb input in BitLocker, as per this bug report - so the issue, whatever it is, I believe is also dependent on some firmware quirk.

**Comment by MikeBeaton** [comment]
Hi @Halo-Michael - sorry if I keep asking request questions, but since some of your data changed. Can you confirm that this issue a) requires CrScreenshotDxe.efi to be present, but b) when it is present, only happens when either KeySupport=true or OpenUsbKbDxe.efi is present.

**Comment by vit9696** [comment]
Could you please try this? Requires config.plist from master build.
[OpenCore-test-r1.zip](https://github.com/acidanthera/bugtracker/files/6806592/OpenCore-test-r1.zip)

For ref:
```diff
% git diff
diff --git a/Library/OcAppleEventLib/KeyHandler.c b/Library/OcAppleEventLib/KeyHandler.c
index 87aac0eb..8ebae15b 100644
--- a/Library/OcAppleEventLib/KeyHandler.c
+++ b/Library/OcAppleEventLib/KeyHandler.c
@@ -574,7 +574,7 @@ InternalAppleEventDataFromCurrentKeyStroke (
   UINTN                           NumberOfKeyCodes;
   EFI_CONSOLE_CONTROL_PROTOCOL    *ConsoleControl;
   EFI_CONSOLE_CONTROL_SCREEN_MODE Mode;
-  UINTN                           Index;
+  //UINTN                           Index;
 
   DEBUG ((DEBUG_VERBOSE, "InternalAppleEventDataFromCurrentKeyStroke\n"));
 
@@ -607,7 +607,7 @@ InternalAppleEventDataFromCurrentKeyStroke (
       ConsoleControl->GetMode (ConsoleControl, &Mode, NULL, NULL);
     }
 
-    if (Mode == EfiConsoleControlScreenGraphics) {
+    /*if (Mode == EfiConsoleControlScreenGraphics) {
       for (Index = 0; Index < (NumberOfKeyCodes + 1); ++Index) {
         Status = gST->ConIn->ReadKeyStroke (gST->ConIn, &InputKey);
 
@@ -615,7 +615,7 @@ InternalAppleEventDataFromCurrentKeyStroke (
           break;
         }
       }
-    }
+    }*/
 
     *Modifiers = AppleModifiers;
     Status     = InternalGetCurrentKeyStroke (
```

**Comment by Halo-Michael** [comment]
> Hi @Halo-Michael - sorry if I keep asking request questions, but since some of your data changed. Can you confirm that this issue a) requires CrScreenshotDxe.efi to be present, but b) when it is present, only happens when either KeySupport=true or OpenUsbKbDxe.efi is present.

Only happens when both KeySupport=true and OpenUsbKbDxe.efi is present.
If I set KeySupport=false and OpenUsbKbDxe.efi is present, keyboard won't work in opencore menu, but works in bitlocker menu, and F10 can't take screenshots in bitlocker menu.
If I set KeySupport=true and OpenUsbKbDxe.efi is present, with TextMode=true, keyboard will works in any menu. And if I press F10 in bitlocker menu, type 0 and screenshot will both happen.

**Comment by Halo-Michael** [comment]
> Could you please try this? Requires config.plist from master build.
> [OpenCore-test-r1.zip](https://github.com/acidanthera/bugtracker/files/6806592/OpenCore-test-r1.zip)
> 
> For ref:
> 
> ```diff
> % git diff
> diff --git a/Library/OcAppleEventLib/KeyHandler.c b/Library/OcAppleEventLib/KeyHandler.c
> index 87aac0eb..8ebae15b 100644
> --- a/Library/OcAppleEventLib/KeyHandler.c
> +++ b/Library/OcAppleEventLib/KeyHandler.c
> @@ -574,7 +574,7 @@ InternalAppleEventDataFromCurrentKeyStroke (
>    UINTN                           NumberOfKeyCodes;
>    EFI_CONSOLE_CONTROL_PROTOCOL    *ConsoleControl;
>    EFI_CONSOLE_CONTROL_SCREEN_MODE Mode;
> -  UINTN                           Index;
> +  //UINTN                           Index;
>  
>    DEBUG ((DEBUG_VERBOSE, "InternalAppleEventDataFromCurrentKeyStroke\n"));
>  
> @@ -607,7 +607,7 @@ InternalAppleEventDataFromCurrentKeyStroke (
>        ConsoleControl->GetMode (ConsoleControl, &Mode, NULL, NULL);
>      }
>  
> -    if (Mode == EfiConsoleControlScreenGraphics) {
> +    /*if (Mode == EfiConsoleControlScreenGraphics) {
>        for (Index = 0; Index < (NumberOfKeyCodes + 1); ++Index) {
>          Status = gST->ConIn->ReadKeyStroke (gST->ConIn, &InputKey);
>  
> @@ -615,7 +615,7 @@ InternalAppleEventDataFromCurrentKeyStroke (
>            break;
>          }
>        }
> -    }
> +    }*/
>  
>      *Modifiers = AppleModifiers;
>      Status     = InternalGetCurrentKeyStroke (
> ```

Well, it works:
![13072348](https://user-images.githubusercontent.com/45062120/125410273-50f73800-e3ef-11eb-9754-07ec605b9ed1.png)
But I was set PlatformInfo-Automatic as true and get this:
![E7071A53-C94E-4E76-A774-33E3D3F8262C_1_105_c](https://user-images.githubusercontent.com/45062120/125410386-6d937000-e3ef-11eb-9e79-fa4b52fe7f29.jpeg)

**Comment by mhaeuser** [comment]
@Halo-Michael Well, it tells you your config is borked.
Can you confirm it works with text mode **off** now, and did **not** before?

**Comment by Halo-Michael** [comment]
> @Halo-Michael Well, it tells you your config is borked.
> Can you confirm it works with text mode **off** now, and did **not** before (after fixing the config ofc)?

I can confirm
I means when PlatformInfo-Automatic is true, smbios dictonary shouldn't even be read? my smbios dictonary is empty and I'm using Generic dictonary, there's no such errors before.

**Comment by MikeBeaton** [comment]
> there's no such errors before

@mhaeuser - I'd just about got to that before op said it, I think separate config validation error in latest version?

**Comment by MikeBeaton** [comment]
@Halo-Michael - we're all asking you tests at once, but what happens if you press F10 now, on @vit9696 test version? It outputs 0, takes screenshot (you already said), but after that, is it fine? Kb input carries on as before? (On some of my setups, I was getting 0, takes screenshot, then kb input stops working.)

**Comment by Halo-Michael** [comment]
We fixed a bug, and then add another two :O

**Comment by MikeBeaton** [comment]
It's separate, it wasn't introduced by this fix!

**Comment by Halo-Michael** [comment]
> It's separate, it wasn't introduced by this fix!

Oh I know, it's a joke :P

**Comment by Halo-Michael** [comment]
> @Halo-Michael - we're all asking you tests at once, but what happens if you press F10 now, on @vit9696 test version? It outputs 0, takes screenshot (you already said), but after that, is it fine? Kb input carries on as before? (On some of my setups, I was getting 0, takes screenshot, then kb input stops working.)

I didn't get kb stop working
![13074747](https://user-images.githubusercontent.com/45062120/125413171-c4b9ff28-72af-4392-855f-39f8568eb740.png)
![13074756](https://user-images.githubusercontent.com/45062120/125413185-31adda00-e3f2-11eb-8ad6-4ee519795574.png)

**Comment by MikeBeaton** [comment]
@Halo-Michael - cc @mhaeuser (sorry!) - I think your config _is_ wrong - you need to not have the `<SMBIOS>` section at all, not just have it with no items in. (I've just checked, also on 0.7.1 and 0.7.0 and there is no change here.)

**Comment by Halo-Michael** [comment]
> @Halo-Michael - cc @mhaeuser (sorry!) - I think your config _is_ wrong - you need to not have the `<SMBIOS>` section at all, not just have it with no items in. (I've just checked, also on 0.7.1 and 0.7.0 and there is no change here.)

Well, I'm using 0.7.1 and there really have no errors yet

**Comment by Halo-Michael** [comment]
But okey I'll remove it.

**Comment by MikeBeaton** [comment]
@vit9696 - removing the dequeue code (as you have done in the test version above) fixes a fundamental problem on my Dell hack too.

Without the change, if I press F10 either within OpenCanopy (before entering BitLocker) or within BitLocker, then from that point onwards BitLocker accepts no key input. I already reported this above. (Before any F10 keypress, on my system unlike @Halo-Michael's, BL does accept input.)

With the change, it all just works (on my system and on @Halo-Michael 's).

There is no change to behaviour on my MBP (input is never crashed, with or without the dequeue code).

For that reason, I am wondering if removing this needs to be on a flag? Can it just die?!

**Comment by vit9696** [comment]
@MikeBeaton, I believe we should make it a flag.

As for the config, there were changes right after 0.7.1, I am worried whether they might have broken something. @Halo-Michael, can you upload your config?

**Comment by Halo-Michael** [comment]
> @MikeBeaton, I believe we should make it a flag.
> 
> As for the config, there were XMP parsing changes right after 0.7.1, I am worried whether they might have broken something. @Halo-Michael, can you upload your config?

Here is:
https://github.com/Halo-Michael/OC-GA-B250M-EVO-Hackintosh/blob/main/EFI/OC/Config.plist
And I just did some change:
https://github.com/Halo-Michael/OC-GA-B250M-EVO-Hackintosh/commit/e775318f137486f3585a270872de592cf165144a

**Comment by MikeBeaton** [comment]
@Halo-Michael - can you report behaviour of ocvalidate tool from 0.7.1 on the two different versions of SMBIOS config.plist (with SMBIOS either missing, or empty)? if it shows the errors when SMBIOS is present but empty (as I think it will) then (despite the recent parsing changes) I think it's just that Vit's copy of OpenCore.efi is compiled in such a way as to show you an error which was there anyway.

**Comment by Halo-Michael** [comment]
> @Halo-Michael - can you report behaviour of ocvalidate tool from 0.7.1 on the two different versions of SMBIOS config.plist (with SMBIOS either missing, or empty)? if it shows the errors when SMBIOS is present but empty (as I think it will) then (despite the recent parsing changes) I think it's just that Vit's copy of OpenCore.efi is compiled in such a way as to show you an error which was there anyway.

You are right, ocvalidate did report my old config have errors :o

**Comment by MikeBeaton** [comment]
Okay, this issue should be fixed in https://github.com/acidanthera/OpenCorePkg/commit/ccf5dac708677a2dc5d8b413ac0a1dc8628e1e7f .

To apply the fix you need to set `AppleEvent/GraphicsInputMirroring` to `true`.
