### ISSUE TITLE
Prebuilt binaries of the SidecarFixup (now FeatureUnlock) should be renamed to FeatureUnlock

### ISSUE THREAD

**Issue by Human7900** [acidanthera/bugtracker#1718]
I just noticed that SidecarFixup was renamed to FeatureUnlock. So, prebuilt binaries should also be renamed to FeatureUnlock. Also, the description of the repo should be updated.
Regards.

**Comment by vit9696** [comment]
Next month.

**Comment by 1alessandro1** [comment]
@Human7900 check out the `Actions` tab

https://github.com/acidanthera/FeatureUnlock/actions/runs/1008102786

P.S. you must be logged in to download them
