### ISSUE TITLE
AppleALC.kext 1.6.2 does not load anymore

### ISSUE THREAD

**Issue by kiu77** [acidanthera/bugtracker#1720]
Problem: 
With the update to Opencore from 0.7.0 to 0.7.1 I exchanged AppleALC.kext from 1.6.1 to 1.6.2 and got no audio.
With HackinTool I could see that Apple-ALC.kext has not been loaded.

Tests:
I the modified my working OC 0.7.0 Folder with using just AppleALC.kext 1.6.2 - same result: not loaded.
Then I modified the OC 0.7.1 folder and exchanged AppleALC.kext 1.6.2 with the older 1.6.1: this works w/o problems.
The I tried this with a nigthly build of AppleALC.kext 1.6.3 - same behaviour as with 1.6.2.

My system:
Gigabyte Board Z490 Aorus Elite AC with i7-11700k.

Attached:
EFI folder with OC 0.7.1 with AppleALC.kext 1.6.2 incl. config.plist

[EFI 071 GB Z490 AE AC.zip](https://github.com/acidanthera/bugtracker/files/6786499/EFI.071.GB.Z490.AE.AC.zip)

**Comment by vit9696** [comment]
Not a support thread. Only post here when you discover genuine issues.

**Comment by kiu77** [comment]
I don’t want support.
It’s just an inication for a potential bug.
Therefor I provided information.

**Comment by muli** [comment]
For what it's worth, I am having the same issue. I had to downgrade to 1.6.0 in order to have sound working again (I didn't test on 1.6.1; I skipped this version).
Motherboard: Gigabyte Z490 Vision G.
CPU: Intel i7-10700.

**Comment by kiu77** [comment]
Oh interesting. Maybe  you'll give v 1.6.1 a try. I would be pleased to hear if this is working to on your system.
And would you mind to upload your anonymised config.plist? Than I can look for similarities to help the decision if we have a problem in our configurations or if there is a bug in 1.6.2 which shows only in certain systems.

**Comment by muli** [comment]
1.6.1 doesn't work either.
I wonder whether it's the layout-id that I am using (16), although I tried 17 and 7 which didn't work either.

**Comment by kiu77** [comment]
Meanwhile I made a debug version of OC 0.7.1 with a debug version of AppleALC.kext 1.6.2.
All I get in context with AppleALC is
_[opencore-2021-07-12-120120.txt](https://github.com/acidanthera/bugtracker/files/6801288/opencore-2021-07-12-120120.txt)_
Log file is attached.

**Comment by vandroiy2013** [comment]
You must find the exact commit that broke AppleALC loading. 
Use [https://dortania.github.io/builds/?product=AppleALC&viewall=true](url)

**Comment by vit9696** [comment]
OCAK: Symbol __ZN11Compression10decompressEjPjPKhjPh has 0-value

This looks like outdated Lilu.

**Comment by kiu77** [comment]
Well, Lilu.kext is version 1.5.4.
A newer version ist not ready until now.

**Comment by muli** [comment]
> This looks like outdated Lilu.

I verified multiple times that I am using the latest (released) version of Lilu, and it's still not working for me.
Is AppleALC 1.6.2 dependent on an unreleased version of Lilu (1.5.5)?

**Comment by vit9696** [comment]
```
% nm /Users/user/Downloads/Lilu.kext/Contents/MacOS/Lilu | grep __ZN11Compression10decompressEjPjPKhjPh
00000000000253a0 T __ZN11Compression10decompressEjPjPKhjPh
```

This is from Lilu 1.5.4 downloaded from https://github.com/acidanthera/Lilu/releases/download/1.5.4/Lilu-1.5.4-RELEASE.zip. You definitely do not have Lilu 1.5.4 given the error.

**Comment by kiu77** [comment]
@vit9696 
You are completely right!
How that comes to my system, I have no idea.
I had updated with Kext Updater and that has not detected the false version
or maybe brought me exactly this build at OC 0.7.0.
The current 1.5.4 has not only a different file size, but also a different build# internally.

The mystery is solved. I must have been involved somehow and
am looking for a bigger ash heap for my head.

With the correct Lilu build 1.5.4 AppleALC 1.6.2 loads without problems!

Thanks to vit9696 and everyone who put so much effort into this!!!
<3
