### ISSUE TITLE
Skip picker when resuming from Hibernation

### ISSUE THREAD

**Issue by 1Revenger1** [acidanthera/bugtracker#1722]
On my Lenovo device, if resuming from hibernation, the firmware will lock out the BIOS and boot menu. This makes it so that you are unable to (accidentally) change BIOS settings or select to boot another operation system when trying to resume. Right now, OC always shows the picker if you have showPicker enabled. It is generally unwanted behavior to be able to select another device to boot when resuming. OC currently does select the hibernated disk as the default option in the picker, though I think it may be better to either skip the picker all together or to lock the selection.

Another option may be to mark the disk as hibernated, as we don't know how long it has been since the machine was put to sleep. This way the user still has the option to choose another option, but knows that they're doing something probably undesirable.

**Comment by Andrey1970AppleLife** [comment]
Skip picker - I consider not reasonably.
Mark the disk as hibernated - reasonably.

**Comment by vit9696** [comment]
How can we mark it though? Should this be a symbol of some kind?

**Comment by 1alessandro1** [comment]
Snowflake symbol ❄️ above the volume (or a whole volume with a symbol already therr) would be cool... Or with a letter next to the boot volume, such as: "Catalina" (H) where H stays for Hibernated (so that even users with the Built-in picker can understand)

How does Apple implement this?

**Comment by vit9696** [comment]
We are limited to 7-bit ASCII, so unicode snowflake symbol is not something we can afford. Technically it can be rendered, but we have a strict policy on the characters we use. I guess the choice can be one of the following:

1. `(*)`
2. `(H)`
3. `(Zzz)`
4. `(S4)` (ACPI term for hibernation)
5. `(x.x)`
6. `(hibernated)`
7. Your variant here.

**Comment by vit9696** [comment]
CC @mhaeuser @Andrey1970AppleLife @vandroiy2013

**Comment by mikebeaton** [comment]
Without necessarily ending up volunteering to do it, can I vote for option 6.

**Comment by mhaeuser** [comment]
Why would we mark it? Imo booting anything but the hibernated volume should be considered borked. I'd suggest a config toggle to skip UI with no way to intercept as originally intended.

**Comment by al3xtjames** [comment]
Is setting OcPickerBootApple sufficient for this? Untested patch:

```diff
diff --git a/Library/OcMainLib/OpenCoreMisc.c b/Library/OcMainLib/OpenCoreMisc.c
index b807201d..bc3c2e29 100644
--- a/Library/OcMainLib/OpenCoreMisc.c
+++ b/Library/OcMainLib/OpenCoreMisc.c
@@ -897,6 +897,10 @@ OcMiscBoot (
     PickerCommand = Context->PickerCommand = OcPickerDefault;
   }
 
+  if (OcIsAppleHibernateWake ()) {
+    PickerCommand = Context->PickerCommand = OcPickerBootApple;
+  }
+
   for (Index = 0, EntryIndex = 0; Index < Config->Misc.Entries.Count; ++Index) {
     if (Config->Misc.Entries.Values[Index]->Enabled) {
       Context->CustomEntries[EntryIndex].Name      = OC_BLOB_GET (&Config->Misc.Entries.Values[Index]->Name);
```

**Comment by mhaeuser** [comment]
@al3xtjames BootApple is for the X hotkey, we must boot the default (BootNext) entry.

**Comment by Andrey1970AppleLife** [comment]
> We are limited to 7-bit ASCII, so unicode snowflake symbol is not something we can afford. Technically it can be rendered, but we have a strict policy on the characters we use. I guess the choice can be one of the following:
> 
> 1. `(*)`
> 2. `(H)`
> 3. `(Zzz)`
> 4. `(S4)` (ACPI term for hibernation)
> 5. `(x.x)`
> 6. `(hibernated)`
> 7. Your variant here.

6.

**Comment by mikebeaton** [comment]
Is this planned to be responsive to Windows/Linux hibernation too?

**Comment by PKRN0** [comment]
Any progress on this? I would love to have this feature since I hibernate often and also switch OS often. For a seamless wakeup from S4, I use skip picker option, but when switching to WIndows, it is really hard to press option key at right timing to bring up the picker.

**Comment by mikebeaton** [comment]
@PKRN0 Off topic, but @vit9696 clarified to me that on most systems any time after the firmware has shown its logo should be safe to press OC boot keys (it does not have to be after OC itself has loaded). And ... I recently added a note to `TakeoffDelay` in the docs (see docs), if you don't mind a some extra delay in boot, you can make the boot chime itself a good signal for when to press hotkeys, as on real Mac.

**Comment by vit9696** [comment]
I would say we will not do Windows and Linux support ourselves, but anyone can contribute it. For macOS it is in master and 0.8.8.
