### ISSUE TITLE
Commit ca3fcbc breaks audio at boot with AudioDXE

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1723]
Hi,
commit [ca3fcbc](https://github.com/acidanthera/OpenCorePkg/commit/ca3fcbc42d1070eae2a582c88938860626975367) (stack canaries) seems to break the playchime at boot with audiodxe, at least for me.
In the log:
[opencore-2021-07-15-154227.txt](https://github.com/acidanthera/bugtracker/files/6824543/opencore-2021-07-15-154227.txt)

07:426 00:010 OCAU: Cannot find specified audio device - Not Found
07:437 00:010 OC: Audio connection failed - Not Found

Reverting back to [ccf5dac](https://github.com/acidanthera/OpenCorePkg/commit/ccf5dac708677a2dc5d8b413ac0a1dc8628e1e7f), without modifying the config, makes the audio working again.

**Comment by vit9696** [comment]
cc @Goldfish64 @MikhailKrichanov

**Comment by 82ghost82** [comment]
Some more data:
my config.plist with some parts redacted:
[config.txt](https://github.com/acidanthera/bugtracker/files/6824676/config.txt)

Running big sur 11.4 20F71 on qemu 6.0.0.

Audio is passed through and it's at PciRoot(0x0)/Pci(0x2,0x0)

**Comment by vit9696** [comment]
07:405 00:010 OCAU: 1/2 PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x1)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00F0CC7D) (4 outputs) - Success
07:416 00:010 OCAU: 2/2 PciRoot(0x0)/Pci(0x2,0x0)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,0050CC7D) (7 outputs) - Success

We have device paths broken, with codec index containing garbage.

**Comment by 82ghost82** [comment]
Not working:
07:395 00:010 OCAU: Matching PciRoot(0x0)/Pci(0x2,0x0)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000)...
07:405 00:010 OCAU: 1/2 PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x1)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00F0CC7D) (4 outputs) - Success
07:416 00:010 OCAU: 2/2 PciRoot(0x0)/Pci(0x2,0x0)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,0050CC7D) (7 outputs) - Success

Working:
06:828 00:006 OCAU: Matching PciRoot(0x0)/Pci(0x2,0x0)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000)...
06:835 00:006 OCAU: 1/2 PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x1)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (4 outputs) - Success
06:842 00:006 OCAU: 2/2 PciRoot(0x0)/Pci(0x2,0x0)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (7 outputs) - Success

**Comment by vit9696** [comment]
Should be addressed in https://github.com/acidanthera/OpenCorePkg/commit/f61a1a35cbd12ec3758b0d510c0aec99d665abb2.

**Comment by 82ghost82** [comment]
Superfast!
Tried, perfect, fixed!
