### ISSUE TITLE
NVMeFix.kext

### ISSUE THREAD

**Issue by steve20677** [acidanthera/bugtracker#1724]
I have installed MacOS onto an WD SN750 M.2. The kext dated April 05 works fine, the system boots up normal. The new NVMe.kext does not let the system bootup and gets stuck midway. Is it possible to fix the kext?

**Comment by 1alessandro1** [comment]
Please provide logs/screenshots with Lilu Debug and NVMeFix debug

**Comment by vit9696** [comment]
Also need the offending commit, macOS version, etc.
https://dortania.github.io/builds/?product=NVMeFix&viewall=true

**Comment by perez987** [comment]
Last build 6d4354e working ok in a WD SN750 M.2 disk. As all previous buils.
