### ISSUE TITLE
OC cannot be booted

### ISSUE THREAD

**Issue by btwise** [acidanthera/bugtracker#1725]
https://github.com/acidanthera/OpenCorePkg/commit/6b27ad1be44270bdfca85e234270b16a3ae95eff
After compiling this update, OC cannot be booted. Run bootx64.efi or opencore.efi from openshell will start without any prompt

**Comment by vit9696** [comment]
User error. The change does not contain any functional changes.

**Comment by btwise** [comment]
There is really no function change in the code. What I did today was compiled in MacOS 11.4+ Xcode12.5 environment once. Because of some error, I made "make clean" operation on Basetools, and the program ran normally after compilation. However, I returned to MacOS10.14.6 + Xcode10 and compiled it again. Basetools also needed to be cleared to pass the compilation, but the compiled binary file could not boot the system. I plan to test the compilation under BigSur again
