### ISSUE TITLE
[OpenCorePkg] CreateVault bug with Vault set to Optional

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1726]
Hi there,
with @1alessandro1 we noticed that `CreateVault` utility doesn't make any kind of check to the given EFI config.plist, more specifically to the value of `Misc/Security/Vault` and vaults the EFI even if `Vault` value is `Optional`.
Isn't this a discrepancy with the `Vault` nature? Shouldn't `CreateVault` make a check and tell the user that he has to set `Vault` to `Basic` or `Secure`?

Let me know your thoughts on that
Greetings
dreamwhite

**Comment by vit9696** [comment]
I do not believe there is any reason to complicate it. By reducing the number of actions we can ease its auditing by third-parties.

**Comment by dreamwhite** [comment]
> I do not believe there is any reason to complicate it. By reducing the number of actions we can ease its auditing by third-parties.

Uhm third parties such as?

**Comment by vit9696** [comment]
End-users with programming skills for instance.
