### ISSUE TITLE
No APFS detection with commit 9324c9e32c8b1cb714f2869b4fdde72f92d58bf4

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1729]
Everything works fine with commit d0559e4da04c45e4884b407b14ea3ffcd935a819.
Attached are the two log files
[opencore-2021-07-21-165121.No_APFS.zip](https://github.com/acidanthera/bugtracker/files/6857614/opencore-2021-07-21-165121.No_APFS.zip)

[opencore-2021-07-21-154928.APFS_detected.zip](https://github.com/acidanthera/bugtracker/files/6857662/opencore-2021-07-21-154928.APFS_detected.zip)

**Comment by 82ghost82** [comment]
change MinDate and MinVersion of apfs driver to load in config.plist, not a bug.
