### ISSUE TITLE
Security Update 2021-004 broke force loading of com.apple.iokit.IOSkywalkFamily

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#1730]
```
14:238 00:064 OCAK: Dependency com.apple.iokit.IOSkywalkFamily was not found for kext com.apple.iokit.IO80211Family
14:484 00:246 OCAK: Vtable patching failed for kext com.apple.iokit.IO80211Family
14:490 00:006 OC: Prelinked force injection System\Library\Extensions\IO80211Family.kext () - Invalid Parameter
```

[opencore-2021-07-22-012920.txt](https://github.com/acidanthera/bugtracker/files/6859540/opencore-2021-07-22-012920.txt)
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/6859544/config.plist.zip)

**Comment by vit9696** [comment]
Well, this has nothing to do with us. There is no dependency kext for the kext you are trying to force inject, thus the injection fails. Works as designed. Maybe you should also force-inject IOSkywalkFamily to workaround the issue?

**Comment by startergo** [comment]
Ah good catch. I have disabled that forcing as it was not needed before the security update. Apparently now it is needed for loading ```IO80211Family.kext```.

**Comment by stevezhengshiqi** [comment]
It happens when I inspecting itlwm's users' log. Normally, a rebuild kextcache would solve this. This issue could happen on any macOS version, and is very case-to-case.

**Comment by startergo** [comment]
> some users also have to force load corecapture.

That was necessary for HS only for me.
