### ISSUE TITLE
SMCSuperIO.kext has the problem of sudden black screen hibernation under normal use!

### ISSUE THREAD

**Issue by crazy-zxx** [acidanthera/bugtracker#1732]
SMCSuperIO.kext has the problem of sudden black screen hibernation under normal use!

The specific performance is: In the case of this driver loaded, the system will run for an indeterminate period, will suddenly black screen, and then it will enter the hibernation state, the keyboard light and power light will be turned off, even if it is playing games or processing documents tapping the keyboard.

During the period from the black screen to the power light going off, I tried tapping the keyboard and clicking the mouse, but could not interrupt the hibernation.

When the power light is off, press the power button to boot the system, it will enter the OpenCore boot interface, and then boot into the system normally, all programs are still running normally.

Since then, the problem has still recurred at uncertain times in use.

To find out where the problem lies, I have tried to reinstall the system, replace the driver version, from one driver test to another, and finally confirmed that there is a problem with this driver.

My computer model is Hasee Z7M-KP7GC, the operating system is Big Sur 11.5, using BCM94360CS2 wireless network card, using Tencent Lemon cleaning software to monitor the fan speed information.

At present, I have only tested versions 1.2.4 and 1.2.5, both of which have the problem.

Now I can only temporarily solve the black screen hibernation problem by modifying the config.plist configuration to not load the driver.

Since I don't know how to get the debug log of the driver, more detailed information cannot be provided.

**Comment by Andrey1970AppleLife** [comment]
According to your description it not hibernation, it shutdown.
Closed as there are doubtfully and no logs.
