### ISSUE TITLE
Request to implement AppleBacklightSmoother functionality.

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#1735]
Hi !
I am wondering if it would be possible to implement [AppleBacklightSmoother](https://github.com/hieplpvip/AppleBacklightSmoother) functionality in whatevergreen .

Thanks !

**Comment by vit9696** [comment]
We do not mind, but somebody needs to do it. Core team has no interest at the moment.

**Comment by Andrey1970AppleLife** [comment]
CC @hieplpvip

**Comment by Lorys89** [comment]
if it is implemented, I point out that on ice lake worked but not well, gave the brightness slightly lower, necessary that the devs fix it

**Comment by Ab2774** [comment]
I don't know what happened to @hieplpvip that made him leave the project, it hasn't been updated since November, it has some functionality issues like the lowest brightness doesn't turn the screen completely black.
Hope to see it implemented in WhateverGreen or at least getting it updated.
