### ISSUE TITLE
applbkl property is not working in WEG

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#1736]
Hi, i want to report that applbkl property is not working in WEG

i'm using latest OC and kexts. also use custom edited AppleBacklight profile,
 
i followed this instruction
"applbkl=0 boot argument (and applbkl property) to disable AppleBacklight.kext patches for IGPU. In case of custom AppleBacklight profile- read here."

1. applbkl=0 boot argument -> working
2. applbkl property -> not working
  - remove applbkl=0 boot argument
  - set applbkl=00000000 property -> not working
  - set applbkl=01000000 property -> not working

can you consider this applbkl for property like igfxagdc=0 boot argument (disable-agdc device property)
example disable-appbkl=01000000

thanks in advance

**Comment by Lorys89** [comment]
> Hi, i want to report that applbkl property is not working in WEG
> 
> i'm using latest OC and kexts. also use custom edited AppleBacklight profile,
> 
> i followed this instruction
> "applbkl=0 boot argument (and applbkl property) to disable AppleBacklight.kext patches for IGPU. In case of custom AppleBacklight profile- read here."
> 
> 1. applbkl=0 boot argument -> working
> 2. applbkl property -> not working
> 
> * remove applbkl=0 boot argument
> * set applbkl=00000000 property -> not working
> * set applbkl=01000000 property -> not working
> 
> can you consider this applbkl for property like igfxagdc=0 boot argument (disable-agdc device property)
> example disable-appbkl=01000000
> 
> thanks in advance

via DeviceProperties applbkl-name and applbkl-data

**Comment by vit9696** [comment]
Can I see IOReg with applbkl injected?

**Comment by Sher1ocks** [comment]
> Can I see IOReg with applbkl injected?

[Sherlocks의 MacBook Pro.zip](https://github.com/acidanthera/bugtracker/files/6938370/Sherlocks.MacBook.Pro.zip)

here

**Comment by vit9696** [comment]
Your value is string `"01000000"`, not data. Thus it does not work.

**Comment by Sher1ocks** [comment]
> Your value is string `"01000000"`, not data. Thus it does not work.

still not working. i tested both data and string with 01000000 or 00000000
[Sherlocks의 MacBook Pro.zip](https://github.com/acidanthera/bugtracker/files/7031625/Sherlocks.MacBook.Pro.zip)

**Comment by vit9696** [comment]
I believe I can confirm the issue. Please retest with master.

**Comment by Sher1ocks** [comment]
> I believe I can confirm the issue. Please retest with master.

it is working. thanks vit!
