### ISSUE TITLE
Problem with keyboard selection, when OpenCore’s picker is used in GUI mode

### ISSUE THREAD

**Issue by Pbryanw** [acidanthera/bugtracker#1737]
I use a Fnatic Ministreak keyboard on my PC. I’ve enabled the GUI for OpenCore’s picker by setting PickerMode to external in config.plist, and adding OpenCanopy.efi to EFI/OC/Drivers.

My issue is that when I use the arrow keys on the picker screen to select a drive, one press of the right or left key causes the selection box to get stuck in a loop. Video below:
https://1drv.ms/v/s!ArFVkgMSc1NUnP5_cT4_ePxq5_IBzw?e=jSXoUJ

This issue disappears when I disconnect my Fnatic keyboard, and instead use my wireless Logitech K360 Keyboard to control OpenCore’s picker. It can also be mitigated by enabling the Fnatic Keyboard’s BIOS mode which, according to them: “limits the number of keys that can be pressed at one time”. More information here:
https://help.fnatic.com/support/solutions/articles/77000304065-how-do-i-enter-the-bios-uefi-mode-

I believe this problem only started with the last two or three versions of OpenCore. I'm currently using OC 0.7.1. Any help appreciated.

**Comment by MikeBeaton** [comment]
Are you sure this is limited to GUI mode? What happens if you change PickerMode to Builtin and do not change anything else?

**Comment by Pbryanw** [comment]
@MikeBeaton - Hi, I've just tried it with PickerMode set to Builtin (using the same setup). 

I have 5 menu items, and with builtin mode active, my left and right arrow keys switch between options 1 & 5, while I can use the up and down arrow keys to cycle through all 5 options. However, in builtin mode, the selection indicator never gets stuck in an unattended loop, and each keypress is registered correctly. It appears this issue only occurs for me in GUI mode.

**Comment by MikeBeaton** [comment]
Can you try setting the new `GraphicsInputMirroring` setting to false, if you have it true at the moment.

**Comment by Pbryanw** [comment]
@MikeBeaton - Hi, and thanks again. I downloaded the latest OC 0.7.2 build from Github, and unfortunately even with GraphicsInputMirroring set to false, I still experience this issue. Any further help appreciated, or I might use this as an excuse to treat myself to a new keyboard 👍

**Comment by MikeBeaton** [comment]
Are you able to test and confirm that there is a specific earlier version which it worked in?

**Comment by Pbryanw** [comment]
@MikeBeaton - Thanks. I've just been going back through the previous OC builds. I started at OC 0.6.7. and keyboard selection in the GUI was working perfectly in this build. It also worked perfectly in OC 0.6.8. It's only in OC 0.6.9. that the looping behaviour (after one keypress of an arrow key) starts in the GUI picker. 

I confirmed this, by switching between the OC 0.6.8. & OC 0.6.9 builds on a USB Stick, and I could see this issue was present in OC 0.6.9., but not in OC 0.6.8. I hope this will prove of some use to you, and thanks again for your help with this.

**Comment by 82ghost82** [comment]
hi @Pbryanw 
if you want to really help since you own the hardware you should provide the exact commit which broke this.
It's really easy, even if you are not able to compile yourself the binaries.
You can go here:
https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true

and download prebuild binaries.
each version corresponds to a commit.
Since you know that it worked with 0.6.8 and it broke with 0.6.9 start by downloading a version in the middle of the 0.6.9.
If it works, download a newer version, in the middle of that you downloaded and the final 0.6.9, if it doesn't download an older version in the middle of that you downloaded and the initial of the 0.6.9
This is called bisecting, I don't know if you understand what I wrote, sorry but english is not my primary language..

This will really help the devs by identifying the exact commit.

And it will take let's say from few minutes to less than 1 hour of your time?

**Comment by MikeBeaton** [comment]
@Pbryanw - Sorry, I missed a notification for your reply. I think that is already useful. (If you are able to follow @82ghost82 's advice, that would be 'the icing on the cake'. :) )

Could you confirm that your current config file passes ocvalidate, and could you also upload your config.plist (feel free to redact any unique machine ids and especially any password hash, if you are using one, before uploading).

**Comment by Pbryanw** [comment]
@82ghost82 - Hi, thanks for your post, along with the explanation of how to identify the exact commit that caused this issue for me. I will try the bisecting method that you proposed (which I was able to understand perfectly - thank you). I will try and do this within the next couple of days, and hopefully this will help the devs narrow down this problem for me 👍 

@MikeBeaton - Hi, once I'm able to find the exact commit, I'll upload my current config.plist here, and I'll also make sure it passes ocvalidate before I post it. A big thanks to both of you.

**Comment by Pbryanw** [comment]
Hi, using the bisecting method, explained to me by @82ghost82, I was able to discover that the issue with my keyboard (the selection loop bug) started with OC 0.6.9. build a97de9c: 
https://github.com/acidanthera/OpenCorePkg/commit/a97de9c1a4dfe7c11e7ddc8ae4a825ec816feba3

The OC 0.6.9. build fa2e072, that came immediately before this, does not show this problem with my Fnatic Keyboard. 

@MikeBeaton - I've uploaded my config.plist to my Onedrive space, with the link shared below. This config is the one I'm currently using with OC 0.7.2., and it's been stripped of my SMBIOS information: 
https://1drv.ms/u/s!ArFVkgMSc1NUnqEYXmeI64ugLADpXA?e=UXzRyw

**Comment by MikeBeaton** [comment]
@mhaeuser What the heck is going on here? Your change to cursor clip code https://github.com/acidanthera/OpenCorePkg/commit/a97de9c1a4dfe7c11e7ddc8ae4a825ec816feba3 , which I agree should be nothing to do with this, is apparently causing another gfx-mode-only keyboard error!

Am remembering this recent issue https://github.com/acidanthera/bugtracker/issues/1716 which was the other gfx-mode related kb error - but the commit I made there is not the one which broke things for this user - and as tested above neither setting made available with that commit helps here.

Am happy to carry on looking into this, but any suggestions gratefully appreciated. Also cc @vit9696  - likewise!

**Comment by vit9696** [comment]
Can `MaxWidth -= DrawBaseX;` happen to overflow?

**Comment by MikeBeaton** [comment]
@Pbryanw - Please can you try using PickerAttributes=1 (i.e. disable mouse as compared to your previous value of 17) and see if this makes the problem go away?

**Comment by Pbryanw** [comment]
@MikeBeaton - Hi, sorry for the delay in getting back to you. After using PickerAttributes=1 in my config.plist, my keyboard is once again working perfectly in OC's picker (with OC 0.7.2.), and the problem has gone away for me. A big thank you for this fix 👍  Do you know now, why this problem occurred on my Fanatic keyboard in the first place?

**Comment by MikeBeaton** [comment]
We're still trying to understand exactly what in this commit has broken it.

So if you don't mind continuing to help to track it down - and get your mouse support back - could you boot OC with a DEBUG build, on any version which breaks, and with PickerAttributes=17, and send the debug log.

It is possible the system will stop completely (i.e. with a debug ASSERT message), so make sure you have a working version of OC to boot from elsewhere.

**Comment by Pbryanw** [comment]
@MikeBeaton - Hi, I've attached my debug log to this post - it was made with OC 0.7.2. I hope it will prove useful, and I think I've captured the moment the error occurs. Thanks once again. 👍 
[opencore-2021-08-08-122041.txt](https://github.com/acidanthera/bugtracker/files/6950716/opencore-2021-08-08-122041.txt)

**Comment by MikeBeaton** [comment]
It looks as if your debug version behaved exactly the same as release? i.e. Both carry on running (do not crash completely), but the keyboard repeats continuously when mouse is enabled (PickerAttributes=17), or behaves normally when it is not (PickerAttributes=1)? Is that right, or did the debug version in fact stop/crash completely?

I also wanted to ask you, how does your mouse cursor behave when mouse is enabled on the release version, when the kb problem is happening? Is it visible, and moving normally when you move the mouse?

**Comment by Pbryanw** [comment]
@MikeBeaton - Hi, yes, that's correct - both the debug and the release version carried on running (and did not crash completely) - with the keyboard repeating continuously - when the value of PickerAttributes was set to either 1 or 17, to disable or enable the mouse. I exited the debug version once the keyboard problem occurred, and didn't go as far as booting into macOS.

Mouse behaviour is exactly the same - the cursor is visible and moving normally - when the kb problem is happening, and when I move the mouse.

However, I've just noticed, while writing this reply to you, that my problem (Fnatic) keyboard is occasionally inserting extra returns, moving the cursor by itself, and missing some letters automatically, as I type this. I was able to fix this by plugging it into a different USB 3.0 port (one provided by a PCI-E card). I wonder if a keyboard or hardware issue could be behind this?

**Comment by MikeBeaton** [comment]
I think we would still be keen to understand how the PR which you identified is interacting with whatever else is going on on your system. When I get a moment on this I'll put up a test version with a couple more debug ASSERT's in it, for you to run with the original keyboard and see if it throws anything up.

**Comment by Pbryanw** [comment]
@MikeBeaton - Hi, thanks again for your reply. I'd be happy to try out any new test versions using my Fnatic keyboard, once you have some spare time to work on this.

I'm now using a Steelseries Apex 7 TKL keyboard with my macOS setup. It doesn't suffer from any issues in OC's GUI picker, and is well supported under macOS, with the Steelseries GG software working perfectly on my Hackintosh so far.

**Comment by MikeBeaton** [comment]
@Pbryanw - Do you have time to test something weird. On the version which is showing uncontrolled key repeats, can you try moving your mouse cursor to the bottom right of the screen, and see if it fixes the problem?!

**Comment by MikeBeaton** [comment]
So, a considerable amount of extra re-drawing was unintentionally introduced by the commit https://github.com/acidanthera/OpenCorePkg/commit/a97de9c1a4dfe7c11e7ddc8ae4a825ec816feba3 which you identified. It should be fixed again by https://github.com/acidanthera/OpenCorePkg/commit/82a0813b24c12130b93fb4f39fd157c012ace95c .

We are not entirely sure why that extra gfx work was interacting with your keyboard (though my guess is, it was preventing it being polled often enough) - but you should find your old kb works again now with https://github.com/acidanthera/OpenCorePkg/commit/82a0813b24c12130b93fb4f39fd157c012ace95c .
