### ISSUE TITLE
[SSDT-EC-USBX] Dynamic USBX properties 

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1740]
Since laptops do not require all the parameters on `USBX` device which are currently loaded from [SSDT-EC-USBX](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/Source/SSDT-EC-USBX.dsl#L73-L80), me and @1alessandro1 have implemented with the help of @Gengik84 - his topic can be found [here](https://www.macos86.it/files/file/84-ssdt-basic) - a dynamic inspection of the firmware's ACPI, where it basically checks battery presence and applies the correct properties afterwards.

I'll attach the patched version of `SSDT-EC-USBX`: [SSDT-EC-USBX.dsl.zip](https://github.com/acidanthera/bugtracker/files/6911930/SSDT-EC-USBX.dsl.zip)

Please note that at the moment we've added only some of the usual found battery paths, but the list may be even expanded in the future.

**Comment by andreszerocross** [comment]
Hi thanks for the information.

Can you explain what happend if we use old SSDT-EC-USBX to the system without battery??

**Comment by dreamwhite** [comment]
> Hi thanks for the information.
> 
> Can you explain what happend if we use old SSDT-EC-USBX to the system without battery??

Hi there, what do you mean with "system without battery"? Are you talking about desktops or laptop - obviously with a post-skylake CPU - without a plugged in battery?
About desktops there shouldn't be any kind of problem since desktop firmware's DSDT doesn't have any reference to batteries (pretty obvious nah?).

About laptops where no battery is plugged in honestly I don't know... Theoretically, there shouldn't be any type of firmware differences but I'll do some proper investigation before giving you an ultimatum :)

Hope I clarified every doubt

**Comment by andreszerocross** [comment]
Ok, i have give wrong question.

let me correct it. If we use Skylake or higher generation notebook with OLD SSDT-EC-USBX.aml in OpenCore sample dsl, does it will give problem???

Does ""kUSBSleepPowerSupply" and ""kUSBWakePowerSupply"" will give certain problem with notebook platform???

**Comment by dreamwhite** [comment]
> Ok, i have give wrong question.
> 
> let me correct it. If we use Skylake or higher generation notebook with OLD SSDT-EC-USBX.aml in OpenCore sample dsl, does it will give problem???
> 
> Does ""kUSBSleepPowerSupply" and ""kUSBWakePowerSupply"" will give certain problem with notebook platform???

I don't have any clue on what could happen if you try injecting the `PowerSupply` values on a laptop 😅

I based my researches on [post-Skylake Macbooks Pro dumps](https://applelife.ru/threads/dampy-originalnyx-makov.2943712/), and the only values present there are `kUSBSleepPortCurrentLimit` and `kUSBWakePortCurrentLimit`.
The only explanation I can give you is that if you try injecting the `PowerSupply` values they'll be simply ignored. If so, why adding unused stuff? Cosmetics?

**Comment by andreszerocross** [comment]
> > Ok, i have give wrong question.
> > let me correct it. If we use Skylake or higher generation notebook with OLD SSDT-EC-USBX.aml in OpenCore sample dsl, does it will give problem???
> > Does ""kUSBSleepPowerSupply" and ""kUSBWakePowerSupply"" will give certain problem with notebook platform???
> 
> I don't have any clue on what could happen if you try injecting the `PowerSupply` values on a laptop 😅
> 
> I based my researches on [post-Skylake Macbooks Pro dumps](https://applelife.ru/threads/dampy-originalnyx-makov.2943712/), and the only values present there are `kUSBSleepPortCurrentLimit` and `kUSBWakePortCurrentLimit`.
> The only explanation I can give you is that if you try injecting the `PowerSupply` values they'll be simply ignored. If so, why adding unused stuff? Cosmetics?

Yes, i have check Skylake and above of macbook device dump of ACPI. There is no PowerSupply Properties in their USBX. Just curios the real effect.

Thanks for answer my questions

**Comment by Mateo1234454545** [comment]
@dreamwhite,  looks very promising.
Want to try it out.
Could you patch it for my laptop?
Here is my dsdt.
[Uploading System DSDT.aml.zip…]()

**Comment by dreamwhite** [comment]
Sorry but that's not a support forum 😅
Since the SSDT uploaded in the first comment is a generic one, I'd rather suggest building your own custom by simply removing `PowerSupply` values.
I decided to open this issue for discussing about a generic SSDT, not a specific one. Those who want can easily generate their own. See it as a prebuilt SSDT...

**Comment by Andrey1970AppleLife** [comment]
I don't think that we shall complicate samples. Write to dortania.
