### ISSUE TITLE
Inconsistent color theme in verbose mode

### ISSUE THREAD

**Issue by cdf** [acidanthera/bugtracker#1741]
On some legacy Macs, the second-stage boot screen is not as expected when booting in **verbose mode**:

<p align="center">
<img width="512" alt="After Verbose" src="https://user-images.githubusercontent.com/63161650/127774906-cec4436a-4bb8-4c2b-90bf-0999015bf606.png">
</p>

The Apple logo is white and the background and progress bar are gray. This oddity can be observed when booting Big Sur on the Mac Pro 5,1.

[opencore-2021-08-01-142204.txt](https://github.com/acidanthera/bugtracker/files/6912905/opencore-2021-08-01-142204.txt)
[config.zip](https://github.com/acidanthera/bugtracker/files/6912929/config.zip)

---

**Remark:** The original boot screen of the Mac Pro 5,1 is gray. This default can be changed by setting `4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:DefaultBackgroundColor` to `00 00 00 00` and enabling OpenCore's built-in `AppleUserInterfaceTheme` protocol. When booting in **standard mode**, the change is indeed effective for both the first-stage and second-stage screens:

<p align="center">
<img width="512" alt="Black 1" src="https://user-images.githubusercontent.com/63161650/127775355-2a865d7e-3e7a-4e0c-940c-2a6b3ee47f4a.png">
</p>

<p align="center">
<img width="512" alt="Black 2" src="https://user-images.githubusercontent.com/63161650/127775364-b589c335-4ee1-4754-84cf-d795ecb88125.png">
</p>

However, the change is _not_ effective when booting in **verbose mode**: after the scrolling text, the second-stage screen still has the white Apple logo and gray background and progress bar as shown above. This oddity is perhaps related to a [bug or incompatibility](https://github.com/acidanthera/bugtracker/issues/774) surrounding 
`4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:DefaultBackgroundColor` in the firmware.

Admittedly, this is a very minor cosmetic issue, but I thought I'd still mention it.

**Comment by vit9696** [comment]
That looks like a bug deep in macOS, not much we can do for it unfortunately. Thanks for reporting.
