### ISSUE TITLE
Red Panic with Legacy Boot

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#1742]
Try to use Legacy Boot macOS Sierra for Toshiba L745 ( Intel Core i5-2410M + GT 525M and no IGPU)

OpenCore version : Latest Commit

I have used "BootInstall_X64.tool" and script is successful executed to internal SSD.

But after reboot i just get this screen, can't reach Boot Picker

![WhatsApp Image 2021-08-01 at 23 44 44](https://user-images.githubusercontent.com/9614101/127781410-10357f37-7111-41c3-89b4-993629f344c9.jpeg)

PS :
I have tried to change from "OpenHfsPlus.efi then HFSPlus.efi then to HfsPlusLegacy.efi but still get problem"

I just enable these drivers
1. OpenHfsPlus.efi / HFSPlus.efi / HfsPlusLegacy.efi or without these kext
2. OpenRuntime.efi
3. OpenCanopy.efi

So i am using latest CLOVER version for now with legacy boot

**Comment by vit9696** [comment]
Need OC log.

**Comment by andreszerocross** [comment]
I close the issue because my cousin happy with Current Bootloader (Legacy Boot of Clover). Very sorry, i can't provide logs
