### ISSUE TITLE
Issue with WEG 1.5.2

### ISSUE THREAD

**Issue by Eniac60** [acidanthera/bugtracker#1743]
I have a problems whit Whatevergreen version 1.5.2 . 

With this version i don't have hardware acceleration though  the GPU is recognized exactly ,  on OC 0.7.0 - 0.7.1 and 0.7.2

My graphics card is R9 270X 2gb 

 

With whatevergreen versione 1.5.1 it's work fine.

![107182674_Schermata2021-08-03alle10_27_12 thumb png f220cb183aabc1de63f30a07eec0e1e9](https://user-images.githubusercontent.com/88386077/128030656-1cc85beb-4250-4153-87a6-1b3fa37be368.png)

**Comment by vit9696** [comment]
- Is your GPU natively supported?
- Do you inject device-id?
- Do you use FakePCIID or any similar stuff?

**Comment by Eniac60** [comment]
-I don't think this card is natively supported

- Yes device-id is injected  on Device-Properties 

- i don't use FakePPIID or similar stuff

<img width="817" alt="Schermata 2021-08-03 alle 16 48 35" src="https://user-images.githubusercontent.com/88386077/128036995-10efbbba-949f-4f80-a8fd-2f83eacca6d4.png">

**Comment by vit9696** [comment]
Does it work without injecting this device-id?

**Comment by Eniac60** [comment]
No, without injecting device-id doesn't work

**Comment by vit9696** [comment]
Update to master and inject `no-gfx-spoof` = `<01 00 00 00>` (any value really).

**Comment by Eniac60** [comment]
I updated to version 1.5.3 as you suggested and added the line in device properties but on reboot it crashes after the first phase.
My card is not an X (in the first post I wrote wrong saying 270X) it has device-id 6811 so I inject the fake-id of the X (device-id 6810) which is native, and up to version 1.5.1 it has always worked perfectly.
<img width="773" alt="Schermata 2021-08-03 alle 17 49 25" src="https://user-images.githubusercontent.com/88386077/128053520-3255f087-d2e2-499f-b27c-4dfe24ba3994.png">

**Comment by vit9696** [comment]
Crashes how? This is not helpful without a symbolicated kernel panic.

**Comment by Eniac60** [comment]
The screen goes completely black and I can't photograph the verbose where it stops. How can I help you ?

**Comment by vit9696** [comment]
Hrm. Can you confirm that 31b8dd1 is broken for you and c8c0711 works fine?

See: https://dortania.github.io/builds/?product=WhateverGreen&viewall=true

**Comment by Eniac60** [comment]
No, up to version 1.5.1 it works perfectly with all other versions 1.5.2 and 1.5.3 not work . In the photo you can see exactly the versions it works well with![1243885889_Schermata2021-08-03alle12_42_35 thumb png 3c51eaaa998358d7bd8c1dc9dba6a3d6](https://user-images.githubusercontent.com/88386077/128060184-d992155e-5278-4606-a659-a14f65e0130b.png)

**Comment by vit9696** [comment]
In this case I close this is as user error, since c8c0711 changes nothing but a version number.

**Comment by Eniac60** [comment]
I humbly apologize, I was using a key with still inserted  "no-gfx-spoof = <01 00 00 00>"  now I have cleaned everything and I have tried again, with the version c8c0711 works fine.
With all other higher versions, up to 1.5.3 it always starts, the graphics card is recognized correctly but without acceleration.
**I got confused, forgive me**

**Comment by vit9696** [comment]
May I see your IOReg?

**Comment by Eniac60** [comment]
there he is..
[iMac di Eniac.zip](https://github.com/acidanthera/bugtracker/files/6927131/iMac.di.Eniac.zip)

**Comment by vit9696** [comment]
Check master.

**Comment by wangzikang-debug** [comment]
这显卡太老了吧

**Comment by keatliang2005** [comment]
I has issue on WEG 1.5.2 too but the situation is slightly different 

To what i understand, the spoofing is by SSDT
https://github.com/osy/HaC-Mini/blob/master/ACPI/SSDT-GpuSpoof.asl

and the graphic render glitch is patch via
https://github.com/osy/Polaris22Fixup

on WEG 1.5.1 it work well, but once run on WEG 1.5.2
i had this issue

https://github.com/osy/HaC-Mini/issues/614

Wonder do i need to inject device-id via device property ? since it's already spoof via SSDT
```
PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)
- device-id  : <DF670000>
```

**Comment by Eniac60** [comment]
Bingo , now work fine with versione 1.5.3 (a9741df) .
If you find it useful I am attaching the ioreg versions with and without no-gfx-spoof
[Without no-gfx-spoof.zip](https://github.com/acidanthera/bugtracker/files/6936848/Without.no-gfx-spoof.zip)
[with no-gfx-spoof.zip](https://github.com/acidanthera/bugtracker/files/6936849/with.no-gfx-spoof.zip)
![1443533639_Schermata2021-08-03alle17_49_25 thumb png 50096e34127ce36a9fee0429ad296683](https://user-images.githubusercontent.com/88386077/128310460-3a368381-0372-4d9b-82cb-3b28991bbd04.png)
<img width="1200" alt="Schermata 2021-08-05 alle 09 31 09" src="https://user-images.githubusercontent.com/88386077/128310488-1710b863-66ad-488b-80ff-34ca2043b8f5.png">

**Comment by PracticalPear413** [comment]
Please help, this is not working for me. I added no-gfx-spoof as 01000000 and deviceid as DF670000 in config.plist, with WhateverGreen 1.5.5 I'm stuck on black screen.
Using 1.5.1 results in the same problem :(

**Comment by lowercase00** [comment]
I think I have a similar problem as well. I have a R9 380 that I've used for two previous builds without problems. If using without spoof, system crashes basically in any site with a more demanding animation (simple animations really), I can only load static websites. 

When with SPOOF to the (supported) 380x, the crashes stop, but no hardware acceleration at all, sluggish performance. Tried a couple of older versions and nothing. I don't have any DeviceProperties associated with the card (with the specific codes above), any references I could consult to help troubleshoot this?

Thanks!

**Comment by lowercase00** [comment]
FUP: Tried adding the no-gfx-spoof, I get the hardware acceleration, but still crashing.
I found a thread [here](https://forums.macrumors.com/threads/constant-kernel-panics-userspace-watchdog-timeout-no-successful-checkins-from-com-apple-windowserver.2222878/page-7) that mentioned the possibility of the GPU locking up, and it seems to be my case I can see the "DumpGPURestart" a couple of minutes before the system watchdog throws the error: "no successful checkins from WindowServer in 120 seconds".

**Comment by kernelBPD** [comment]
Hello, I'm also encountering a similar issue with WEG builds where both the `device-id` (for spoofing purposes) and `no-gfx-spoof` properties were added. I would assume that the causation of the KPs/crashes is similar to that which @lowercase00 has described above. 

Here's a KP log from 2 weeks ago (Apr 30th):
[kp_30.apr.2022.txt](https://github.com/acidanthera/bugtracker/files/8693809/kp_30.apr.2022.txt)

The way this issue presents itself is that the system stops responding, and shortly after, it completely restarts on it's own – all the way to POST, I mean.


I do not encounter this issue if I use WEG v1.5.0 and use an SSDT-GPU-SPOOF patch.
