### ISSUE TITLE
OC-0.7.2: Monterey reboot triggers "failed to POST" from BIOS

### ISSUE THREAD

**Issue by HQuest** [acidanthera/bugtracker#1745]
Hey folks. Reviving my Monterey cheese install on a brand new system. Running OC release 0.7.2. Whenever I restart macOS via standard "Apple logo > Restart...", as soon as the BIOS initializes, it claims the system has failed to POST, and asks to press F1 to launch BIOS. A failure I'm pretty sure wasn't the case, as the OS ran just fine until I chose to restart it. Is this a known issue or a weird behavior of the hardware?

Relevant hardware specs: i7 10700k, Asus Prime Z590M Plus, 5700XT
SMBIOS: iMac 20,2 (as this matches both CPU and GPU)
OpenCore 0.7.2, Lilu 1.5.5, VirtualSMC 1.2.6, AppleALC 1.6.3, WEG 1.5.2, IntelMausi 1.0.7, CPUFriend 1.2.4 (still unsure if needed)
SSDTs: Plug, EC-USBX, AWAC, RHUB (modified from Dortania's premade files to match my ACPI tables)

Even with the debug version of the OC, Lilu & friends, I found zero clues. Happy to provide any other supporting files, including the horrible ACPI tables (not joking, whoever coded it was clearly on the wrong job) - just let me know which/how.

[config.plist.zip](https://github.com/acidanthera/bugtracker/files/6934587/config.plist.zip)
[opencore-2021-08-04-212259.txt](https://github.com/acidanthera/bugtracker/files/6934566/opencore-2021-08-04-212259.txt)

**Comment by Andrey1970AppleLife** [comment]
https://dortania.github.io/OpenCore-Post-Install/misc/rtc.html#finding-our-bad-rtc-region
