### ISSUE TITLE
Z590 intel 10th UHD630 acceleration ID H.264 does not work

### ISSUE THREAD

**Issue by TokiharaSay** [acidanthera/bugtracker#1746]
Z590 intel 10th UHD630 acceleration ID H.264 does not work

I have tried using the following ig-platform-id,
（0x3E920003 、0x3E910003 、0x3E980003 、0x9BC40003、0x9BC80003）
There is no way to make H.264 work, but HEVC,265 is working, 
(0x3E9B0000、0x3E9B0007 ）
 I am very confused about this, so I want to find out the reason, so I want to ask why.
This part of the motherboard supports DP IN

MSI MEG Z590I UNIFY  and Z590I VISION D （Same situation）
intel 10th  i7 10700K
HP OEM RX580 8G 2304 SP VBIOS is DELL RX580
Western Digital SN550 1T*2
KLEVV BOLT X DDR4 3200MHz 16G*2
Corsair SF600W

Mac OS Version  Big Sur11.2.3
OpenCore 0.7.2
Lilu 1.5.5
AppleALC 1.6.3
WhateverGreen 1.5.2
VirtualSMC 1.2.6

[IOREG and MY EFI.zip](https://github.com/acidanthera/bugtracker/files/6947021/IOREG.and.MY.EFI.zip)

<img width="1920" alt="Screen Shot 2021-08-06 at 11 50 01 PM" src="https://user-images.githubusercontent.com/79110394/128547655-2b0d88dc-6552-41c9-9864-af141397d087.png">
<img width="1920" alt="Screen Shot 2021-08-06 at 11 58 15 PM" src="https://user-images.githubusercontent.com/79110394/128547660-6edbd0e2-8f2f-4bc8-97f2-9963bf0463af.png">

**Comment by basett1** [comment]
I have an Asrock z590 Extreme, with i9-10850k and RX580 8gb, EFI made by @lorys89, where works everything. Maybe he can answer here to help others. Send also screen of videoproc..
![Schermata 2021-08-06 alle 23 28 33](https://user-images.githubusercontent.com/74409308/128573085-eacf8cc7-ea5e-4689-9a56-21d67d00d316.png)

**Comment by wangzikang-debug** [comment]
这跟可能软件有关系，建议换个新版本试试

**Comment by TokiharaSay** [comment]
> 我有一台 Asrock z590 Extreme，带有 i9-10850k 和 RX580 8gb，由@Lorys89制造的 EFI ，在那里可以工作。也许他可以在这里回答以帮助其他人。还发送 videoproc 的屏幕。
> ![Schermata 2021-08-06 alle 23 28 33](https://user-images.githubusercontent.com/74409308/128573085-eacf8cc7-ea5e-4689-9a56-21d67d00d316.png)

I asked Lorys89 to help me at TelegramI, but my H.246 is still unable to work

**Comment by TokiharaSay** [comment]
> 这跟可能软件有关系，建议换一个新版本的记忆

I tried 10.15.7-12bate and it was all the same and VideoProC was replaced，And turning out the same.

**Comment by dreamwhite** [comment]
> > 这跟可能软件有关系，建议换一个新版本的记忆
> 
> I tried 10.15.7-12bate and it was all the same and VideoProC was replaced，And turning out the same.

Have you tried switching to other headless ig-platform-ids?
