### ISSUE TITLE
QA testing for ACPI samples?

### ISSUE THREAD

**Issue by hacker1024** [acidanthera/bugtracker#1747]
Recently, a pull request (https://github.com/acidanthera/OpenCorePkg/pull/279) was merged updating the sample SSDT-PNLF.dsl to have support for Coffee Lake and above.
Along with this change, a notice was [added](https://github.com/Lorys89/OpenCorePkg/commit/e15e2d308dadc3c37f8064db728cf25ede77e157) to the old Coffee Lake SSDT to direct users to the new SSDT, meaning that the Dortania ACPI guide's manual backlight section directed to it without the guide even being changed.

The problem with this was that the new SSDT didn't work on Coffee Lake at all. After the merge and comments about the issue, the PR author [fixed](https://github.com/Lorys89/OpenCorePkg/commit/d63685c1f31abc5e6686eb1f119191ccaf9054a2) the problem - but this change hasn't yet been submitted or merged into OpenCorePkg.

This could have been avoided if the change was tested on Coffee Lake (which was an advertised feature in the pull request) before getting merged. Could testing be enforced for future changes?

**Comment by Lorys89** [comment]
it also worked before on all cfl +, except for some whiskey lake models, na now I create pr with fix for whiskey lake.

**Comment by hacker1024** [comment]
My bad, the commit message on the fix confused me. I think my point still stands, though.

**Comment by Lorys89** [comment]
> My bad, the commit message on the fix confused me. I think my point still stands, though.
I did the pr, but we are in the summer and I'm traveling, I did everything by phone. 
however L I tested on many PC ice lake and comet lake and coffe lake and on only one whyskey lake and on that the first version worked. but things are discovered and fixed. 
thanks for your report and served to improve
Kind regards 
Lorys

**Comment by hacker1024** [comment]
Just to be clear, I'm not blaming you, @Lorys89 - I don't expect one person to be able to test on so many architectures. It'd be better if there was a system in place to stop accidents like this happening, though, perhaps with volunteered testing before pushing to master?

**Comment by vit9696** [comment]
The rule of thumb is that the only tested code is the one that lands in master. It is sad that it did not get tested before the release, but this stuff happens. The core team basically does not support laptops at all, so we partly do not care what happens on them.
