### ISSUE TITLE
KERNEL EXTENSION IN BACKTRACE 

### ISSUE THREAD

**Issue by ChristopherLewis-004** [acidanthera/bugtracker#1748]
My system Config...
Laptop:- Dell latitude 3510 
Core I3 10th gen With intel UHD graphic 
8GB ram 
I am trying to boot opencore Big Sur 

Please Help Me out!!
![IMG_20210809_103824](https://user-images.githubusercontent.com/84517824/128663276-da522014-2e45-44a4-a4e5-c94559f6b07a.jpg)

**Comment by vandroiy2013** [comment]
This is not a support forum.
