### ISSUE TITLE
Unable to compile OpenCore on Monterey B4

### ISSUE THREAD

**Issue by HQuest** [acidanthera/bugtracker#1750]
Trying to build OpenCore, Lilu and plugins from git sources, on Monterey b4 (macOS 12 build 21A5294g), fails on UefiApplicationEntryPoint.inf module, file Canary.iii, with compiler error "Segmentation fault: 11". Tried different XCode versions, from stable 12.x to beta 13.x. Tried previous five commits, to no avail - same error message. Tried on three different macOS computers, including a real 2019 MBP. Using @rusty-bits [OC-tool ](https://github.com/rusty-bits/OC-tool) CLI building script, however there [are](https://www.insanelymac.com/forum/topic/348065-pre-release-macos-monterey/?do=findComment&comment=2764534) [reports](https://www.insanelymac.com/forum/topic/348065-pre-release-macos-monterey/?do=findComment&comment=2764535) of similar tools such as OCBuild failing as well.

**Comment by laozhiang** [comment]
Nasm in ocbuild can‘t run on monterey B4
OS:macOS Monterey 12.0 Beta4(21A5294g)
error:
./nasm
zsh: segmentation fault  ./nasm

**Comment by khronokernel** [comment]
This was an Apple bug, should be resolved with Beta 5 (21A5304g) seeded today
