### ISSUE TITLE
[Clarifications] AppleCpuPmCfgLock / Xcpm disabled and system boots even with CFG Lock

### ISSUE THREAD

**Issue by antoniomcr96** [acidanthera/bugtracker#1751]
Thanks, as always, for all your work.
I’m opening this issue to investigate why, on some laptops (especially thinkpads), system boots without cfglock kernel quirks even though cfg is locked (confirmed by opencore debug log, bios dump and cfglock.efi)

Some users have reported the fact, but I didn’t find any “official” answer. 

This happens, for example, on my laptop (thinkpad l390), and power management seems to be the same, with or without the quirks.

Sorry if this seems a question that should have been posted on forums, but I tried and I didn’t receive any answer. I also read the documentation but i didn’t find any particular detail.

Is there a preferable configuration in these cases or is it the same?

Thanks in advance for any explaination. Good evening

**Comment by Andrey1970AppleLife** [comment]
Quirk AppleCpuPmCfgLock influences on AppleIntelCPUPowerManagement.kext
AppleIntelCPUPowerManagement.kext isn't used on 10.11+ for Haswell+

**Comment by antoniomcr96** [comment]
Thanks for your reply. So, for haswell+ users with 10.11+ installed, trying to unlock cfg has no practical advantage?

Perhaps it could be specified in the documentation, in order to suggest to avoid attempts to (uselessly) mod the bios to unlock CFG without any change.

**Comment by Andrey1970AppleLife** [comment]
For Haswell+ if MSE 0xE2 locked in bios - need quirk AppleXcpmCfgLock or CFG unlock.

**Comment by antoniomcr96** [comment]
Sorry @Andrey1970AppleLife, you told that AppleIntelCPUPowerManagement.kext is not used for Haswell +

So, the quirk should be useful before haswell not for haswell+.
Otherwise this doesn’t explain why my laptop with whiskey lake boots fine without the quirks and with CFG lock

**Comment by 1alessandro1** [comment]
> Otherwise this doesn’t explain why my laptop with whiskey lake boots fine without the quirks and with CFG lock

@antoniomcr96 this is not possible if you have no kernel patches enabled (AppleXcpmCfgLock) since XNU (macOS kernel) checks with `PKG_CST_CONFIG_CONTROL` if the MSR 0xE2 register is available for writing. Otherwise you would be stuck at very early boot time

Attach your OpenCore log to demonstrate what you say, where you can boot without patches in Kernel>Quirks and with MSR 0xE2 bit to nonzero

**Comment by antoniomcr96** [comment]
```
00:000 00:000 OC: OpenCore DBG-072-2021-08-02 is loading in Optional mode (0/0)...
00:015 00:015 OC: Boot timestamp - 2021.08.06 10:47:41
00:034 00:019 OCCPU: MP services threads 8 (enabled 8) - Success
00:050 00:015 OCCPU: MP services Pkg 1 Cores 4 Threads 2 - Success
00:065 00:014 OCCPU: Found Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
00:080 00:015 OCCPU: Signature 806EB Stepping B Model 8E Family 6 Type 0 ExtModel 8 ExtFamily 0 uCode B8
00:095 00:015 OCCPU: EIST CFG Lock 1
00:110 00:014 OCCPU: TSC Adjust 0
```
[opencorelog.txt](https://github.com/acidanthera/bugtracker/files/6997804/opencorelog.txt)

![image](https://user-images.githubusercontent.com/63928525/129681193-4eaab2c0-29de-484c-8a3b-55c9f633b608.png)
Anyway, I'm not the only one

**Comment by 1alessandro1** [comment]
I would like @vit9696 opinion on this. Never heard about anybody booting without that register locked for writing, and I wonder what XNU does if this happens without any patches. Maybe @antoniomcr96 has a borked installation? Is there any way to track what's happening under the hood?

**Comment by Andrey1970AppleLife** [comment]
> Sorry @Andrey1970AppleLife, you told that AppleIntelCPUPowerManagement.kext is not used for Haswell +
> 
> > For Haswell+ if MSE 0xE2 locked in bios - need quirk AppleXcpmCfgLock or CFG unlock.
> 

I wrote about two different quirks.
**AppleCpuPmCfgLock** belongs only to AppleIntelCPUPowerManagement.kext (isn't used on 10.11+ for Haswell+)
**AppleXcpmCfgLock** need for Haswell+ on any supported macOS (isn't used on any macOS for IvyBridge and older)

Probably you use native methods for CPU, for example DummyPowerManagement or others.

**Comment by antoniomcr96** [comment]
Sorry, I didn't understand well the difference. Thanks for the explanation.

Anyway, `DummyPowerManagement` is not enabled. I followed the suggestions of the Dortania's guide and of the documentation, I didn't enable anything else that wasn't indicated. 

There are also other users on Lenovo that reported experiences similar to mine but I haven't ever find any explanation. I am available to perform any test.

Thanks for your work, good evening

**Comment by antoniomcr96** [comment]
@vit9696 do you have any idea about this "problem"? If i will find out anything about it, i will update the post

**Comment by Striker770** [comment]
@Andrey1970AppleLife 

Is this correct?
![Screen Shot 2022-05-07 at 7 21 38 PM](https://user-images.githubusercontent.com/44955309/167257272-49b08d06-000a-4660-a43b-9729a2906d40.png)

Also, on a side note, Ivy Bridge and Ivy Bridge-E are XCPM capable, so AppleXcpmCfgLock should be enabled?
