### ISSUE TITLE
I just Try latest NVMeFix.kext 1.0.9

### ISSUE THREAD

**Issue by ArchCryptonIO** [acidanthera/bugtracker#1752]
Hi there, Just try NVMeFix.kext version 1.0.9. 

![Screenshot 2021-08-15 at 5 23 57 PM](https://user-images.githubusercontent.com/86180725/129473886-f56519ea-5130-46e7-85de-c1553d3aa726.png)

![Screenshot 2021-08-15 at 5 34 15 PM](https://user-images.githubusercontent.com/86180725/129474130-c185ef5e-f7b2-4780-a499-58574d1a01ef.png)
![Screenshot 2021-08-15 at 5 34 06 PM](https://user-images.githubusercontent.com/86180725/129474133-9ba8cbb6-2a2e-4536-8490-72d45c3a9dfc.png)

Based on picture, Maxio chipset doesn't give me an issue while booting. But, Phison chipset E13 giving an issue and kernel panic while boot process. If I'm not using it. My Hack boot fine. Is it normal? 

SMBIOS: iMac20,1
macOS Version: Big Sur 11.5.2 (20G95)

**Comment by vit9696** [comment]
Feels like your phison ssd is either faulty (less likely) or has incompatibilities with macos (more likely). I do not believe we can help here.

**Comment by ArchCryptonIO** [comment]
> Feels like your phison ssd is either faulty (less likely) or has incompatibilities with macos (more likely). I do not believe we can help here.

This is new NVMe. However, Thank You so much for an explanation. 👍
