### ISSUE TITLE
OCB: Load FailedImage - Unsupported - latest Catalina w/ OpenCore 0.7.2

### ISSUE THREAD

**Issue by willydwi77** [acidanthera/bugtracker#1753]
I have an issue when selecting MacOS Installer in OpenCore bootloader. Message that appears OCB: Load FailedImage - Unsupported.

File structure in BOOT:
+ BOOTx64.efi

File structure in OC:
- ACPI
++ SSDT-AWAC.aml
++ SSDT-EC-USBX-DESKTOP.aml
++ SSDT-PLUG-DRTNIA.aml
++ SSDT-PMC.aml
- Drivers
++ HfsPlus.efi
++ OpenRuntime.efi
- Kexts
++ AppleALC.kext
++ Lilu.kext
++ RealtekRTL8111.kext
++ SMCProcessor.kext
++ SMCSuperIO.kext
++ USBInjectAll.kext
++ VirtualSMC.kext
++ WhateverGreen.kext
++ XHCI-unsupported.kext
+ config.plist
+ OpenCore.efi

These are my hardware specs:
+ CPU Core i3 9100f (Coffee Lake)
+ Mobo AsRock H310
+ Graphic Radeon RX 570 4Gb
+ LAN Realtek RTL8111
+ SSD Laxer 240Gb (Use for Catalina, APFS formatted )

And this is the result of checking config.plist https://opencore.slowgeek.com/?file=coffeelake066qZg7kB&rs=coffeelake066 I don't know why there is no version 0.7.2. And I have disabled and enabled in BIOS as suggested.

Disable:
- Secure Boot
- Fast Boot
- CSM
- VT-d
- Intel SGX
- Intel Platform Trust
- CFG Lock

Enable:
- Above 4G decoding
- EHCI/XHCI Hand-off

[opencore-2021-08-15-111609.txt](https://github.com/acidanthera/bugtracker/files/6988058/opencore-2021-08-15-111609.txt)
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/6988060/config.plist.zip)

**Comment by vandroiy2013** [comment]
This is not a support forum.

**Comment by 1alessandro1** [comment]
@willydwi77 Go to UEFI > APFS and set the following values:

`MinDate=20200306` and `MinVersion=1412101001000000` for Catalina 10.15.4 (19E287) and above

**Comment by willydwi77** [comment]
> 
> 
> @willydwi77 Go to UEFI > APFS and set the following values:
> 
> `MinDate=20200306` and `MinVersion=1412101001000000` for Catalina 10.15.4 (19E287) and above

Actually it doesn't work, I've tried it a few times. but I wrote a new post in reddit [Big Sur 11.5 Stuck at [EB|LOG:RESET:RECOVERY] use OpenCore 0.7.2](https://www.reddit.com/r/hackintosh/comments/p5hezn/big_sur_115_stuck_at_eblogresetrecovery_use/) and already solved. Thanks

**Comment by DeveloLongScript** [comment]
> This is not a support forum.

Than what is this place?
