### ISSUE TITLE
Put Machine to Sleep at Design Capacity of Low

### ISSUE THREAD

**Issue by tylernguyen** [acidanthera/bugtracker#1754]
References:
@usr-sse2 https://github.com/tylernguyen/x1c6-hackintosh/issues/126#issuecomment-833750930
https://applelife.ru/threads/hibernate-pri-razrjade-batarei.2874421/

macOS warns on low battery:
- Expected behavior: machine goes to sleep.
- Actual behavior: machine turns off.

I am aware that this is doable with some ASL. However, it seems rather redundant to do this for every hackintosh laptops instead of implementing it with `SMCBatteryManager`.

This is especially more useful for folks who do not patch battery via ACPI but uses `ECEnabler`.

**Comment by usr-sse2** [comment]
@vit9696 Do you know any kernel API to put the system to sleep or hibernate?

**Comment by vit9696** [comment]
@usr-sse2 I believe you need to send a power notification with kIOPMSleepNow or kIOPMPowerEmergency. You might also be fine with sleepSystemOptions in gIOPMRootDomain. I think there was something in HiberationFixup. Watch out for 10.4 breakage. CC @lvs1974, @Goldfish64

**Comment by mhl221135** [comment]
> @usr-sse2 I believe you need to send a power notification with kIOPMSleepNow or kIOPMPowerEmergency. You might also be fine with sleepSystemOptions in gIOPMRootDomain. I think there was something in HiberationFixup. Watch out for 10.4 breakage. CC @lvs1974, @Goldfish64

hbfx-ahbm=16

WhenBatteryIsAtWarnLevel = 16: Auto hibernation can happen when battery is at warning level (osx and battery kext are responsible for this level)

Unfortunately, its not working with this walues
https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/issues/88#issuecomment-812829801

**Comment by lvs1974** [comment]
@mhl221135: 
EnableAutoHibernation = 1 (turn on feature)
WhenLidIsClosed =2 
WhenExternalPowerIsDisconnected = 4 
WhenBatteryIsNotCharging = 8 
WhenBatteryIsAtWarnLevel = 16
WhenBatteryAtCriticalLevel = 32
DisableStimulusDarkWakeActivityTickle = 128 
RemainCapacityBit1 = 256,
RemainCapacityBit2 = 512,
RemainCapacityBit3 = 1024,
RemainCapacityBit4 = 2048

You can try 1 + 16 + 32 = 49,
But most likely  WhenBatteryIsAtWarnLevel and WhenBatteryAtCriticalLevel are not reported by battery kext, so you can use additionaly bits RemainCapacityBit1, RemainCapacityBit2, RemainCapacityBit3, RemainCapacityBit4 to specify remaining capacity value (from 0 to 15). If current capacity is less than specified remaining capacity, new version 1.4.4 HibernationFixup (see attach) will put macOS to sleep/hibernate
[HibernationFixup-1.4.4-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7186594/HibernationFixup-1.4.4-DEBUG.zip)
.

**Comment by profzei** [comment]
@lvs1974 
I'm sorry but I really do not understand how to set additionaly bits `RemainCapacityBit1`, `RemainCapacityBit2`, `RemainCapacityBit3`, `RemainCapacityBit4` to specify remaining capacity value (from 0 to 15)...

For example, if I would like to set a remaining battery capacity of 17%, how do I need to set those bits?

**Comment by whatnameisit** [comment]
@profzei 
RemainCapacityBit1 = 256,
RemainCapacityBit2 = 512,
RemainCapacityBit3 = 1024,
RemainCapacityBit4 = 2048
bits can be used to specify the battery levels from 1 to 15. Bits 1-4 are 1,2,4,8 in percentage, so for example if you want to have 10 percent level to be the point where the laptop goes into sleep/hibernation, you would add Bits 2 and 3 which would be 512+1024=1536 (2+8=10 percent) in `hbfx-ahbm`. 17 percent is not possible with these four.

@lvs1974 could you please update the README as well to announce that this new feature can be used on not just hibernation but sleep, too?
You said
> EnableAutoHibernation = 1 (turn on feature)
>new version 1.4.4 HibernationFixup (see attach) will put macOS to sleep/hibernate

However, HibernationFixup README currently reads
> EnableAutoHibernation = 1: If this flag is set, system will hibernate instead of regular sleep (flags below can be used to limit this behavior)

which had I not read this issue would assum the new feature would not work with regular sleep.

**Comment by profzei** [comment]
@whatnameisit Thank you very much for your explanation. Maybe it could be useful adding these information to the README file for `HibernationFixup.kext`...

**Comment by whatnameisit** [comment]
@lvs1974 Sorry if it was me that confused you. In my comment above I originally wrote Bits 2+3 would be 2+8=10 percent by mistake which should have been 2+4=6 percent or chosen Bits 2+4.
And I noticed you did not update EnableAutoHibernation. Does this mean regular sleep can't be forced with the kext?

**Comment by lvs1974** [comment]
@whatnameisit: you are right, without EnableAutoHibernation HibernationFixup does nothing. I can remove check for this flag and put macOS into sleep basing on battery level.

**Comment by whatnameisit** [comment]
@lvs1974 Honestly, I'm not sure where I'm right. I was asking if this kext would force the laptop to go to sleep at specified percentage.
Using https://github.com/acidanthera/HibernationFixup/commit/c8ae3f6106f7da317ac115fc9e5fb576b5067652, I included `EnableAutoHibernation`, `WhenBatteryIsAtWarnLevel`, and `RemainCapacityBit1-4` in the sum; set OpenCore `HibernateMode` to `None`; and set `pmset -a hibernatemode` to 0; but the laptop did not go to sleep and the battery drained past 15 percent. It works when I mod the `_BST` method to notify `SLPB`.
>remove check for this flag and put macOS into sleep basing on battery level.

https://github.com/acidanthera/HibernationFixup/commit/e18a425d5636e77c3be07f72f1126280cd14b01e Is this commit where you removed the check? So if I repeat this time it would go to sleep?

**Comment by lvs1974** [comment]
@whatnameisit: yes, you can repeat. Please install debug version and add into boot-args -hbfxdbg and logs.
You can install also debug version lilu and set liludump=N seconds and put lilu log here.

**Comment by profzei** [comment]
@lvs1974 

> HibernateMode and hibernatemode you can set to default values.

What do you mean?
`HibernateMode` set to `None` AND `hibernatemode` set to `3` (which is default value in macOS install)? or `HibernateMode` set to `Auto`?

**Comment by lvs1974** [comment]
HibernateMode to Auto, hibernatemode to 3.
And EnableAutoHibernation = 0.

**Comment by lvs1974** [comment]
@profzei, @whatnameisit: please check the latest commit - I created a separate timer to check a remaining battery capacity.

**Comment by whatnameisit** [comment]
@lvs1974 The laptop I'm testing doesn't hibernate well like the fans and others don't turn off, so I'm using hibernatemode 0 and regular sleep.
The laptop did indeed go to sleep at 15 percent with acidanthera/HibernationFixup@e18a425 and setup in my previous comment (minus EnableAutoHibernation), but it kept going back to sleep even though I connected power and the charge was at 40 percent. I will try the newest commit and collect logs, unless you want me to stop because I'm not on HibernateMode Auto and hibernatemode 3.

**Comment by profzei** [comment]
@whatnameisit 
Could you share, please, the command I need to run for getting something like your hbfx.txt file?
Did you set liludump=60?

**Comment by whatnameisit** [comment]
@profzei I added DebugEnhacer.kext and msgbuf=10485760 in boot-arg. Then 'sudo dmesg | grep HBFX > ~/desktop/hbfx.txt' in terminal.
The Lilu log is dumped with Debug Lilu and HibernationFixup kexts with boot-arg -liludbgall and yes liludump=60

**Comment by profzei** [comment]
@lvs1974 @whatnameisit 

My settings:
**config.plist**
```
<key>HibernateMode</key>
<string>Auto</string>
```

```
<key>boot-args</key>
<string>-v keepsyms=1 debug=0x100 msgbuf=10485760 -liludbgall liludump=60 -hbfxdbg hbfx-ahbm=3856</string>
```

**pmset -g live**
```
System-wide power settings:
Currently in use:
 standby              1
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        0
 powernap             0
 gpuswitch            2
 disksleep            10
 standbydelayhigh     300
 sleep                1 (sleep prevented by sharingd)
 hibernatemode        3
 ttyskeepawake        1
 displaysleep         3
 tcpkeepalive         0
 highstandbythreshold 50
 acwake               0
 standbydelaylow      300
```

Attached files:
[Lilu_1.5.7_20.6.txt](https://github.com/acidanthera/bugtracker/files/7274079/Lilu_1.5.7_20.6.txt)
[hbfx.txt](https://github.com/acidanthera/bugtracker/files/7274085/hbfx.txt)
[pmset_log.txt](https://github.com/acidanthera/bugtracker/files/7274092/pmset_log.txt)
[pmset_log_complete.txt](https://github.com/acidanthera/bugtracker/files/7274113/pmset_log_complete.txt)

What did it happen?
After 3 minutes my machine went to sleep fine (i.e. standby sleep... since no-one told me to disable standby feature...)
I woke up my machine pressing a key after about 13 minutes... which means that **hibernation was not triggered** otherwise I needed to press power button...
Do I need to set something in a different way?

**Comment by whatnameisit** [comment]
@lvs1974 I'm attaching logs from a different laptop. Hibernation 3 and 25 work fine with this one.
HibernateMode Auto, hibernatemode 3, and EnableAutoHibernation 0. In the logs hbfx-ahbm is reported 0 when it is set 3900 in config.plist: 4+8+16+32+256+512+1024+2048. I cleared NVRAM before doing the test.
[hbfx.txt](https://github.com/acidanthera/bugtracker/files/7277033/hbfx.txt)
[Lilu_1.5.6_20.6.txt](https://github.com/acidanthera/bugtracker/files/7277043/Lilu_1.5.6_20.6.txt)
It entered sleep with 3901. hbfx-ahbm is under Lilu NVRAM guid. I'll switch boot-arg to see if it makes any difference.

**Comment by lvs1974** [comment]
@whatnameisit: the right GUID is E09B9297-7928-4440-9AAB-D1F8536FBF0A
![Screenshot 2021-10-04 at 11 55 19](https://user-images.githubusercontent.com/27740976/135831225-322328d8-0951-448c-9380-4cf63bf58122.png)
:

**Comment by lvs1974** [comment]
@profzei: in your logs I see that HibernationFixup did its job properly.
Why machine did not go into hibernation - it is a different, there can be many reasons, full system log is needed.

**Comment by lvs1974** [comment]
@whatnameisit: regarding reading values from NVRAM, I have checked and it works:
In log I can see these lines:
```
[    0.905256]: HibernationFixup      HBFX: @ (DBG) Variable hbfx-ahbm has been read from NVRAM: 3900
[    0.906597]: HibernationFixup      HBFX: @ (DBG) Variable hbfx-disable-patch-pci has been read from NVRAM: 1
[    4.435081]: HibernationFixup      HBFX: @ (DBG) current hbfx-ahbm value: 3900
[    4.435085]: HibernationFixup      HBFX: @ (DBG) current dumpNvram value: 0
[    4.435087]: HibernationFixup      HBFX: @ (DBG) current patchPCIFamily value: 0
[    4.435089]: HibernationFixup      HBFX: @ (DBG) current ignored_device_list value: 
```

And I fixed the issue with not going to sleep when EnableAutoHibernation is 0.
Kext is attached
[HibernationFixup-1.4.4-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7277665/HibernationFixup-1.4.4-DEBUG.zip)
.

**Comment by whatnameisit** [comment]
@lvs1974 hbfx-ahbm being read as 0 is from two comments up.
https://github.com/acidanthera/bugtracker/files/7277033/hbfx.txt
I'll test the kext you attached.

**Comment by lvs1974** [comment]
@whatnameisit: OpenCore is only responsible for reading config.plist and writing those values into NVRAM.

**Comment by whatnameisit** [comment]
@lvs1974 This time laptop entered sleep with EnableAutoHibernation=0.
[Lilu_1.5.6_20.6.txt](https://github.com/acidanthera/bugtracker/files/7277950/Lilu_1.5.6_20.6.txt)
[hbfx.txt](https://github.com/acidanthera/bugtracker/files/7277949/hbfx.txt)
Still two things.
1. The laptop would like to enter sleep at 16 percent, so I have to spam keyboard until the level reaches like 17-18 percent.
```
[ 1622.963952]: HibernationFixup      HBFX: @ (DBG) Auto hibernate: capacity remaining: 15 less than minimal: 15, force to sleep
```
2. The hbfx-ahbm argument not being read correctly in Lilu NVRAM GUID.

**Comment by whatnameisit** [comment]
@lvs1974 Attaching as you requested.
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/7278217/config.plist.zip)
[hbfx.txt](https://github.com/acidanthera/bugtracker/files/7278218/hbfx.txt)
[Lilu_1.5.6_20.6.txt](https://github.com/acidanthera/bugtracker/files/7278220/Lilu_1.5.6_20.6.txt)

**Comment by lvs1974** [comment]
@whatnameisit: you forgot to add "E09B9297-7928-4440-9AAB-D1F8536FBF0A" into Root->NVRAM->Delete!
So, if hbfx-ahbm was created in this NVRAM plane, new value will not be written!

**Comment by whatnameisit** [comment]
@lvs1974 Oh, I missed that. I ran ocvalidate and it came out fine, so I thought I had everything in order. Thank you!

**Comment by lvs1974** [comment]
@whatnameisit: yes, it is correct, but it does not work.
Try to add something into 7C436110-AB2A-4BBB-A880-FE41995C9F82 and check whether it is visible in output of command nvram -p.

**Comment by whatnameisit** [comment]
> @whatnameisit: yes, it is correct, but it does not work. Try to add something into 7C436110-AB2A-4BBB-A880-FE41995C9F82 and check whether it is visible in output of command nvram -p.

Things show up with nvram -p.



> @whatnameisit: regarding reading values from NVRAM, I have checked and it works: In log I can see these lines:
> 
> ```
> [    0.905256]: HibernationFixup      HBFX: @ (DBG) Variable hbfx-ahbm has been read from NVRAM: 3900
> [    0.906597]: HibernationFixup      HBFX: @ (DBG) Variable hbfx-disable-patch-pci has been read from NVRAM: 1
> [    4.435081]: HibernationFixup      HBFX: @ (DBG) current hbfx-ahbm value: 3900
> [    4.435085]: HibernationFixup      HBFX: @ (DBG) current dumpNvram value: 0
> [    4.435087]: HibernationFixup      HBFX: @ (DBG) current patchPCIFamily value: 0
> [    4.435089]: HibernationFixup      HBFX: @ (DBG) current ignored_device_list value: 
> ```
> 
> And I fixed the issue with not going to sleep when EnableAutoHibernation is 0. Kext is attached [HibernationFixup-1.4.4-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7277665/HibernationFixup-1.4.4-DEBUG.zip) .

This one correctly reads hbfx-ahbm
[1.txt](https://github.com/acidanthera/bugtracker/files/7286182/1.txt)



> @whatnameisit: regarding reading hbfx-ahbm - please have a look at your log! You will see a lot of lines: "successful efi64 call GetVariable with response 800000000000000E" It means NVRAM was successfully read, **but variable was not found**! It is definitely something wrong with you config.plist (or NVRAM), the problem is not in kext!
> 
> Regarding entering to sleep after wake with keyboard: I have tried something - see attached kext (to fix it), but I am out of ideas why it happens.
> 
> [HibernationFixup-1.4.4-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7278151/HibernationFixup-1.4.4-DEBUG.zip)
> 
> Can you attach your config.plist?

This one doesn't.
[2.txt](https://github.com/acidanthera/bugtracker/files/7286183/2.txt)

Same config.plist, tested with both Lilu GUID and boot-arg. The most recent one you attached does not read hbfx-ahbm from neither of them.
![스크린샷 2021-10-05 오후 10 30 00](https://user-images.githubusercontent.com/47713349/136032615-4510d85e-6977-43fe-8dcc-48c2945064e8.png)

**Comment by lvs1974** [comment]
@whatnameisit: if attached version cannot read NVRAM - i don't know what to do.
You can try to install DEBUG-version of OpenCore and take a log (it will be located on EFI partition after boot).
[HibernationFixup-1.4.5-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7286352/HibernationFixup-1.4.5-DEBUG.zip)

**Comment by lvs1974** [comment]
@whatnameisit: I am sorry, but it seems threre is nothing I can do here.
```
IOPMPowerSource *power_source = callbackHBFX->getPowerSource();
	if (power_source && power_source->batteryInstalled() && !power_source->externalConnected() && !power_source->isCharging()) {
```
As you can see, before forcing macOS into sleep HBFx checks many things:
Battery is installed, external power source is not connected, and charging is not active.
Most likely power source reports wrongly the current battery charging status...

**Comment by whatnameisit** [comment]
@lvs1974 I think you may be right about wrongly reported power status because I just found out the power cable doesn't charge/power the laptop.
