### ISSUE TITLE
Compatibility issues of Vault and UEFI SecureBoot

### ISSUE THREAD

**Issue by tkkinn** [acidanthera/bugtracker#1755]
When try to run `sign.command` with my signed `OpenCore.efi`, it show:  
```
Issuing a new private key...
Getting public key based off private key...
Signing ../../EFI/OC/OpenCore.efi...
Bin-patching ../../EFI/OC/OpenCore.efi...
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Fatal error: ../../EFI/OC/OpenCore.efi is borked!
Cleaning up keys
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.
```
I try to root my computer with the vault on and it will display an error message. 

If I try to run the vault first and then run UEFI Secure Boot, it also causes an error message.

**Comment by 1alessandro1** [comment]
> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools...]

You need to install Xcode or just the Xcode command line tools 👍

**Comment by tkkinn** [comment]
The problem has been solved. Thank you, I will close this issue.
