### ISSUE TITLE
AppleALC 1.6.1 and later are associated with a boot loop problem for the Realtek ALC1220 codec.

### ISSUE THREAD

**Issue by dmcnaugh15** [acidanthera/bugtracker#1756]
AppleALC 1.6.1 and later are associated with a boot loop problem for the Realtek ALC1220 codec.

Problem resolves when replacing the newer AppleALC kext (1.6.1, 1.6.2, or 1.6.3) with 1.6.0. 
macOS version: 11.5.2
OpenCore version: 0.7.2

Hackintosh specs:
  - Motherboard: ASUS ROG MAXIMUS XI HERO (WI-FI) - chipset Z390
  - CPU: Intel(R) Core(TM) i9-9900K
  - Graphics card: Radeon RX 580 Series
  - RAM: 32 Gb

Relevant links:
    - Config file: [opencore-2021-08-20-100803.txt](https://github.com/acidanthera/bugtracker/files/7024784/opencore-2021-08-20-100803.txt)
    - EFI folder and Debug log: http://DAMDAS.myqnapcloud.com:8082/share.cgi?ssid=bb3ead008f9d442c95fc459574fcbf7b
    - Video demonstration: https://youtu.be/FIPJQRPFBPM
    - Insanelymac thread (unresolved as of 8/21/21): https://www.insanelymac.com/forum/topic/348559-applealc-161-causing-boot-loop-opencore-070-072/?tab=comments#comment-2764852

**Comment by vit9696** [comment]
Exact commit?

**Comment by dmcnaugh15** [comment]
Trying to respond best to your question, "Exact commit"... 

Best response I can think of is, this is my first comment here, and I've probably unwittingly violated a community norm.  I didn't even know what a "commit" was until it was brought to my attention; so, I googled "what is a github commit." to learn more.

In the end, I don't know if I'm in the right place, or if you'd be willing to elaborate on what specific changes, or commits, I should make - I'm not a developer.  I really just thought I was submitting a potential AppleALC kext problem, and wasn't necessarily looking for help.  I'm getting help at insanelymac (https://www.insanelymac.com/forum/topic/348559-applealc-161-causing-boot-loop-opencore-070-072/?tab=comments#comment-2764852).

**Comment by vit9696** [comment]
Check the builds here: https://dortania.github.io/builds/?product=AppleALC&viewall=true. Find the last working one and the first not working one. The alphanumeric string to the left is the commit.

**Comment by dmcnaugh15** [comment]
**The commit is: e2d0a03; Disabled kext patching for verb support and delays when no...**
  - Last working build: a5d456c; Implement AppleALCU variant
  - First not working build: e2d0a03; Disabled kext patching for verb support and delays when no...

Panic (debug) logs can be found by clicking "V05 Github_Commit" at the following url: http://DAMDAS.myqnapcloud.com:8082/share.cgi?ssid=bb3ead008f9d442c95fc459574fcbf7b

**Comment by vit9696** [comment]
Check whether https://github.com/acidanthera/AppleALC/commit/e0cdf39aa45e64c6f205b114edad65712dbc0f1a fixes it for you. Should appear soon on dortania.

**Comment by dmcnaugh15** [comment]
SUCCESS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
THANK YOU SO MUCH :)
