### ISSUE TITLE
Intel Arrandale iGPU not working with WhateverGreen

### ISSUE THREAD

**Issue by itsmevjnk** [acidanthera/bugtracker#1757]
I've been trying to get my Sony VAIO VPCEB3AFM (Intel Pentium Dual-Core P6100, iGPU PCI ID 8086:0046) to run Mac OS X Lion using the OpenCore guide. So far pretty much everything is working, with the exception of the integrated GPU, which only displays a gray color without mouse pointer, and does not output anything to any of its external outputs. I've tried changing the `framebuffer-linkwidth` property in config.plist between 1 and 4, but to no avail. The only way I can get it working is with `device-id` set to a dummy value such as 0x12345678; however, that would effectively stop QE/CI from working. The laptop uses LVDS for internal display, and since it has a 1366x768 screen, I'm fairly certain that it's using single link LVDS.
I really hope the developers will take a look at this issue. Here's the EFI I used:
[EFI.zip](https://github.com/acidanthera/bugtracker/files/7025119/EFI.zip)

**Comment by vit9696** [comment]
cc @Goldfish64. Is it supposed to work? Thought Arrandale is for desktop models...

**Comment by Goldfish64** [comment]
WhateverGreen supports laptops only, so this should be supported hardware. It's possible the patches are not yet correct for the older versions so please try a newer version like 10.11 to verify the hardware is supported.

**Comment by Goldfish64** [comment]
Some Sony laptops are unsupported for unknown reasons despite having LVDS displays (i.e. invalid EDID). Closing.
