### ISSUE TITLE
AppleALC 1.6.2 and above have no HDMI/DP audio with 8086:A171 after commit 2d777ea

### ISSUE THREAD

**Issue by goodbest** [acidanthera/bugtracker#1761]
My nuc8i7hvk connects with an LG 4k monitor via DP/HDMI. 
And the monitor connects to speaker via 3.5mm jack port on the monitor.

- With AppleALC 1.6.1, it's working with no issue.
- With AppleALC 1.6.2 (commit 2d777ea to be exactly) or higher , my machine cannot detect the monitor as a sound speaker. (DP and Type-C and HDMI are all tested).

I think that this commit saying `Fixed HDMI Audio 0xA171 for Acer VX5-591G` destroys my nuc's hdmi/DP audio.
https://github.com/acidanthera/AppleALC/pull/687

(Figure: AppleALC 1.6.2 commit 2d777ea and above, no monitor speaker is detected)
![image](https://user-images.githubusercontent.com/1118401/130449697-271fcc2d-610c-4d3e-84c0-d863e10670dd.png)

(Figure: AppleALC 1.6.1 or below commit 2d777ea, monitor speaker is working as expected.)
![image](https://user-images.githubusercontent.com/1118401/130449714-ad64bb83-746b-42a2-93de-aee6113815be.png)

It can also be observed from IORegistrythat that:
- with AppleALC 1.6.2 , the AppleHDA controller is missing for dGPU.
- with AppleALC 1.6.1, the AppleHDA exists for dGPU. (I believe the DP/HDMI connects to dGPU for this nuc model)
[Nuc_161.ioreg.zip](https://github.com/acidanthera/bugtracker/files/7032050/Nuc_161.ioreg.zip)
[Nuc_162.ioreg.zip](https://github.com/acidanthera/bugtracker/files/7032051/Nuc_162.ioreg.zip)

I'm using Hac-Mini EFI provided by @osy
some details for HDA is here: https://osy.gitbook.io/hac-mini-guide/details/hda-fix

(Figure: Screenshots of Hackintool when HDMI/DP audio is working for AppleALC 1.6.1)
<img width="532" alt="Screen Shot 2021-08-23 at 20 58 38" src="https://user-images.githubusercontent.com/1118401/130451331-5a50bc28-4647-449d-9411-3a56f8a148e3.png">
<img width="588" alt="Screen Shot 2021-08-23 at 20 58 28" src="https://user-images.githubusercontent.com/1118401/130451344-9ab35791-3c28-4313-8698-0868c2747944.png">

By the way, the speaker is always working when connects with the Nuc's own 3.5mm jack port, for both AppleALC 1.6.1, 1.6.2 and above.

**Comment by vit9696** [comment]
This was fixed in https://github.com/acidanthera/AppleALC/commit/65f53049afed0f15b5ab2ed6a10d9e34b5b3a979. See https://github.com/acidanthera/bugtracker/issues/1661.

**Comment by goodbest** [comment]
By following the solution manner in https://github.com/acidanthera/bugtracker/issues/1661, 
I've made PR for the 8086:A171 device https://github.com/acidanthera/AppleALC/pull/700

Now the DP/HDMI digital audio is working as expected with the PR
