### ISSUE TITLE
unable to  build FeaturesUnlock.kext with Xcode 

### ISSUE THREAD

**Issue by alkindivv** [acidanthera/bugtracker#1763]
![Screen Shot 2021-08-29 at 16 04 57](https://user-images.githubusercontent.com/66145311/131245024-8633c8db-56ab-4248-9875-8ec2e6f3ae75.png)
[Screenshot.zip](https://github.com/acidanthera/bugtracker/files/7072199/Screenshot.zip)

**Comment by vit9696** [comment]
Need MacKernelSDK in plugin root.
