### ISSUE TITLE
Gigabyte RX 560 - HDMI 2.0 Flickering #232

### ISSUE THREAD

**Issue by danchristian12** [acidanthera/bugtracker#1764]
Hi all, recently got a RX 560 but my second display is flickering which is a 4K@60hz running over HDMI, but it keeps flickering off then going purple slightly and turning off for 1 second then back on wondering if anyone would know a fix for this?

The Flicker only occurs when using a HDMI 2,0 port on my Samsung U28E590D 4K monitor but when using the HDMI 1.4 port its abousltely fine no flickering using a Gigabyte RX 560 4GB this issue does resolve after using the Monitor after 1 hour but it randomly tries to do the same thing inbetween being back to 'normal' It's as if theres a connector issue but the monitors are fine on my Windows Hard drive.

Below are attachments

wondering if there is any insight to fix this? as it's making it unbearable to use on my 4K monitor
opencore-2021-08-29-194005.txt
https://share.icloud.com/photos/0XjqE7P-dRL-qwMl3nD9_-x9g
https://share.icloud.com/photos/0XjqE7P-dRL-qwMl3nD9_-x9g

**Comment by danchristian12** [comment]
Little note on this: the issue can be resolved, when using a EDID patch from hackintool but this affects both monitors and only works
Up to 1440p, I do only use my 4k scaled to 1440p but I do prefer HDPI mode on this display

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by danchristian12** [comment]
Forums, Reddit and discord have been unable to help on this matter.
