### ISSUE TITLE
[Feature Request] Integrate RTCMemoryFixup in DisableRtcChecksum

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1765]
Hi there,
I wanted to ask you if in future versions of OpenCore RTCMemoryFixup functionality can be implemented in the already existing `DisableRtcChecksum` kernel quirk.

Let me be more clear: `DisableRtcChecksum` disables only primary checksum (`0x58-0x59`) writing in AppleRTC, while RTCMemoryFixup kext lets you disable whatever region you need to.

Let's suppose for example that we need to disable only primary checksum writing in AppleRTC: is there any practical difference if we use RTCMemoryFixup or `DisableRtcChecksum` to blacklist the same regions?
If not, shouldn't be better redesign `DisableRtcChecksum` with an additional field that if it's empty blacklists only primary checksum, otherwise the specified regions?

Let me know your thoughts on that and if it's accomplishable
Greetings
dreamwhite

**Comment by vit9696** [comment]
It is not technically possible as macOS performs RTC I/O on its own, and `DisableRtcChecksum` is a very small and simple hex patch.
