### ISSUE TITLE
Conexant CX20724 - OCAU: PlayFile playback setup failure - Unsupported

### ISSUE THREAD

**Issue by benjenq** [acidanthera/bugtracker#1767]
I try to Play Chime when boot up on HP Probook 430 G3, and got  "OCAU: PlayFile playback setup failure - Unsupported" in DEBUG VERSION. 

The audio Codec Name of  430G3 is "Conexant CX20724 (0x50F4)". I noticed that `OcHdaDevicesLib.c` does not contain this code in `mHdaCodecList[]`, so I add it:
```c
STATIC HDA_CODEC_LIST_ENTRY mHdaCodecList[] = {
  ...
  { HDA_CODEC (CONEXANT, 0x50F4),       0x0000, "Conexant CX20724" },
  ...
```
then build `AudioDxe.efi` DEBUG VERSION and install into EFI. Debug info seem identifiy correct:
```
02:556 00:029 HDA: Starting done for C95E8A98
02:576 00:019 HdaCodecDriverBindingSupported(): attaching to codec 0x0
02:600 00:024 Codec ID: 0x14F1:0x50F4
02:624 00:024 Codec name: Conexant CX20724
02:649 00:024 Codec contains 1 function groups, start @ 0x1, end @ 0x1
```
but still got `OCAU: PlayFile playback setup failure - Unsupported` failure:
```
07:448 00:004 OCAU: System volume is 100 (calculated from 73) - Success
07:452 00:004 OCAU: Matching PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000)...
07:456 00:004 OCAU: 1/2 PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (2 outputs) - Success
07:461 00:004 OCAU: Setting language to en-US:0
07:465 00:004 OCAU: Language for audio en-US:0 - Success
07:469 00:003 OC: Starting to play chime...
07:617 00:147 OCAU: File 59 for lang 7 is 32 2 2 (446976) - Success
07:648 00:030 OCAU: PlayFile playback setup failure - Unsupported
07:648 00:000 OC: Play chime started - Unsupported
```

Does it mean that Audio device `Conexant CX20724 ` didn't support play chime function?

**Comment by pigworlds** [comment]
I hit similar issue with `Conexant CX8200`. It turn out this audio codec doesn't support 44.1k sampling rate. It looks like support 48k only. I upsample the boot chime file to 48k and it works on my machine.
You can give a try this resampled file [OCEFIAudio_VoiceOver_Boot.mp3.zip](https://github.com/acidanthera/bugtracker/files/7088076/OCEFIAudio_VoiceOver_Boot.mp3.zip) if you hit the same problem.

**Comment by Human7900** [comment]
I second this, happens to me also on HP Probook 430 G3, the codec being cx20724.
Will try @pigworlds suggestion and report back.
Also @pigworlds do you have any idea the powerchime (the sound when plug in the charger) not playing as well?

**Comment by benjenq** [comment]
@pigworlds Great! The message "`playback setup failure - Unsupported`" was gone when I try your .mp3 file.
```
05:475 00:005 OCAU: System volume is 100 (calculated from 70) - Success
05:481 00:005 OCAU: Matching PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000)...
05:486 00:005 OCAU: 1/2 PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (2 outputs) - Success
05:492 00:005 OCAU: Setting language to en-US:0
05:498 00:005 OCAU: Language for audio en-US:0 - Success
05:503 00:005 OC: Starting to play chime...
05:778 00:274 OCAU: File 59 for lang 7 is 64 2 2 (497664) - Success
05:805 00:027 Widget @ 0x17 setting up
05:820 00:015 Widget @ 0x10 setting up
05:820 00:000 HdaCodecEnableWidgetPath(): Amp out offset 0x4A
05:825 00:005 Widget @ 0x10 output
05:835 00:010 HdaControllerHdaIoStartStream(): stream 7 DMA pos 0x0
05:835 00:000 OC: Play chime started - Success
```
The working config.plist/UEFI/Audio for Conexant CX20724 (HP Probook 430 G3) :
|Key      |Type     |Value |
|-------|--------|------|
|AudioCodec|Number|0|
|AudioDevice|String|PciRoot(0x0)/Pci(0x1F,0x3)|
|AudioOut|Number|0:headset, 1:speaker|

@pigworlds Thank you so much for your great help.

**Comment by Human7900** [comment]
Thank you so much @pigworlds,it worked!
Also, can you do me a small favor, please upsample the battery connected sound to 48k to test it if it it works?
I'll attach the sound files. I converted them to .mp3 by renaming it if you want.
Thanks.
[connect_power.mp3.zip](https://github.com/acidanthera/bugtracker/files/7096351/connect_power.mp3.zip)
[connect_power.aif.zip](https://github.com/acidanthera/bugtracker/files/7096354/connect_power.aif.zip)

**Comment by pigworlds** [comment]
@Human7900 This issue is about play audio in OC. I am not sure if this apply to the powerchime after OS is booted.
You can use audacity to resample the audio if you'd like to. Check https://superuser.com/questions/420531/audacity-resampling

**Comment by Human7900** [comment]
Oh ok, a strange thing tho, boot chime only plays hen nvram is reset.
Does this happen with yo too @pigworlds @benjenq?
