### ISSUE TITLE
HfsPlusLegacy compatibility issues

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#1768]
@Andrey1970AppleLife, please replace HfsPlusLegacy.efi with the driver from MacPro6,1 firmware. Same with ExFatDxeLegacy.efi. It seems that our HfsPlusLegacy.efi has some compatibility issues, which I do not think we can easily investigate.

Initially mentioned here https://github.com/acidanthera/OcBinaryData/pull/8.

**Comment by wy414012** [comment]
Thank you for checking the specific reasons. I tested and unloaded the driver on my laptop Lenovo ThinkPad E530, equipped with Intel Core i3 2328M processor, using the default HfsPlusLegacy.efi to add the GUI, the black screen will still be stuck, and the problem disappears after replacing the extracted one.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/OcBinaryData/commit/29b23910e5ebb6347fd287776fe79508cbbc1bfe
