### ISSUE TITLE
About the idea of automatic brightness adjustment, I hope the moderator can give whether the scheme is feasible

### ISSUE THREAD

**Issue by mjs520** [acidanthera/bugtracker#1770]
Please see if this scheme can realize indirect brightness automatic adjustment, so that computers without light sensing elements can also realize brightness adjustment by calling cameras

By calling the camera, the camera should be able to record the "voltage" and "current value". Through logical operation, compare the brightness value of the notebook with the corresponding pressure and current. If the "Brightness" value collected by the camera is greater than the "brightness value" of the computer, give the computer an instruction to increase the brightness. At the same time, according to the difference, control the span of increasing the brightness. At the same time, in order to better meet the reality, you can add a buffer needle parameter control in config to adjust the notebook brightness closer to the ambient brightness through multiple or divisor or a constant. When you check the automatic brightness adjustment option, you can call the camera. If not, you can't call it.

**Comment by khronokernel** [comment]
* [Brightness control](https://developer.apple.com/documentation/uikit/uiscreen/1617830-brightness) 
* [Camera access](https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture)

No reason you couldn't implement this, but out of scope for WhateverGreen development

**Comment by Andrey1970AppleLife** [comment]
And out of scope for SMCLightSensor development
