### ISSUE TITLE
BlueToolFixup.kext not work good on Mac OS 12 with Intel WiFi n7265 

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#1771]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

I'm update Mac OS to Mac OS 12.0 Beta (21A5304g) bluetooth work very bad

Kext Version: v2.0.0 stable and BlueToolFixup.kext
WiFi Card Model: n7265 m.2
macOS Version: 12.0 Beta (21A5304g)

nfo in System Report - Bluetooth
bluetooth work but when tern off I can't tern on need rest my laptop

![131884992-a921e528-d641-41b6-b7d1-012e380918a6](https://user-images.githubusercontent.com/35195176/131910125-4d4b9d58-996d-4f08-9689-a512f6cc43d8.png)

![131885052-fcc7da59-2086-408e-b242-bcae7768f6d4](https://user-images.githubusercontent.com/35195176/131910159-1ce55a79-069d-45cf-946d-a3d5f2cbe0de.png)

after tern off bluetooth can't tern on

![131885204-bd0fc80a-a401-49b9-8ccd-b8ac0de7385f](https://user-images.githubusercontent.com/35195176/131910181-84559593-e8fa-4b56-ac89-98ae554c7be7.png)

@dhinakg

**Comment by stevezhengshiqi** [comment]
It's a known issue mentioned in https://github.com/acidanthera/BrcmPatchRAM/pull/12#issue-668963999
