### ISSUE TITLE
Big Sur 11.5.2 seems to have broken NVMeFix

### ISSUE THREAD

**Issue by siddiqq** [acidanthera/bugtracker#1772]
Hello :)

I recently updated to 11.5.2 on my 13inch MBP 2015 with a Samsung Evo Plus 970 SSD, and my battery life seems to almost halved. Before the update I was getting about 9-10 hours on a full charge, but now its at 4 hours. 

However the weird thing is when I check iStatMenus the power draw seems to be similar at 0.02-0.03 mA at idle, where as before the update it was showing 0.00 A. Not sure if or why these 0.02 mA make a big difference but something definitely changed. I even reset SMC and PRAM, and reinstalled the kexts but nothing changed.

Also when I check the Energy Impact graph in Activity Monitor the blue lines never dip to the bottom as it should. As shown in the photo attached the "base" line stays about 1/4th way up the graph at idle, so it seems there's some kind of higher energy being drawn even though its apparently only 0.02 mA.

Hopefully its an easy fix :) Thank you
<img width="197" alt="Screen Shot 2021-09-04 at 3 03 53 PM" src="https://user-images.githubusercontent.com/30996644/132080514-f218f13b-6ec3-44d0-8cf3-6377cf614237.png">

**Comment by vit9696** [comment]
This is not a support forum.

**Comment by siddiqq** [comment]
@vit9696 Hi, sorry I thought it might be a problem with NVMeFix since the update seemed to have changed power consumption. I also had to reinstall SsdPmenabler on when I updated 11.5 because the power usage went up again, even though you seemed to implement it with NVMeFix :/ 

Im not sure where to post this. Cheers
