### ISSUE TITLE
ALC256 sound randomly gets distorted (both speaker and headphones) on all layout-id

### ISSUE THREAD

**Issue by Eldar1163** [acidanthera/bugtracker#1774]
Some time after boot sound works perfectly, but soon sound gets distorted and back to normal when I go to preferences -> sound -> input -> select line in. I don't use CodecCommander and other sound-related kexts and software. I attached AppleALC debug log and EFI Folder.
[Log_2021-09-04_13-00-03.log](https://github.com/acidanthera/bugtracker/files/7109603/Log_2021-09-04_13-00-03.log)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/7109605/EFI.zip)

**Comment by vit9696** [comment]
Contact your audio resource maintainer on this regard.

**Comment by usr-sse2** [comment]
Seems like EAPD problem (see discussion in https://github.com/acidanthera/AppleALC/pull/764) and the same as in this comment: https://github.com/acidanthera/AppleALC/pull/765#issuecomment-1058407560. Please upload the codec dump and reopen if it's still relevant.

**Comment by Eldar1163** [comment]
@usr-sse2 I attach the config in this comment. Issue still relevant.
[codec.txt](https://github.com/acidanthera/bugtracker/files/8462166/codec.txt)

**Comment by Eldar1163** [comment]
@usr-sse2 I tested layout 66 with this modified pin config, but issue still relevant.
**boot config**
01471C10 01471D01 01471E10 01471F90 **01470C02** 02171C20 02171D10 02171E2B 02171F04 **02170C02** 01271CF0 01271D00 01271E00 01271F40 01971C80 01971D10 01971E8B 01971F04 **01970725** 01371CF0 01371D00 01371E00 01371F40 01871CF0 01871D00 01871E00 01871F40 01A71CF0 01A71D00 01A71E00 01A71F40 01B71CF0 01B71D00 01B71E00 01B71F40 01D71CF0 01D71D00 01D71E00 01D71F40 01E71CF0 01E71D00 01E71E00 01E71F40
**wake config**
**01470C02 01970725 02170C02**

**Comment by savvamitrofanov** [comment]
Same problem with ALC257 , even with layout 96 from L390 https://github.com/acidanthera/AppleALC/pull/764

**Comment by juniorcaesar** [comment]
> 

have you been able to solve this problem? i created my own layout and i'm experiencing the same problem as yours. it gets fixed when i put my computer into sleep and wake it up after waiting for 4 or 5 seconds.
