### ISSUE TITLE
No Fans Monitoring or Fans Control for HP 280 G3 MT

### ISSUE THREAD

**Issue by Cuacon2004** [acidanthera/bugtracker#1775]
I'm using macOS Big Sur 11.5.2, Installed lastest version of VirtualSMC including SMCProcessor.kext and SMCSuperIO.kext.
I'm using iStat menus, MacFans Control, HWMonitor. CPU Temperature and Disk Temperature is fine. But I can't monitor CPU fans.
This is HP 280 G3 Specs: https://support.hp.com/th-en/product/hp-280-g3-microtower-pc/16110356/document/c05519863
I'm using Core i5 7500, NVIDIA GT 730(GDDR5) option

**Comment by Cuacon2004** [comment]
If anyone ask my hackintosh function status, I can say most of things work fine like CPU Power Management, Sleep, Wake, QE/CI, VDA Decoder, etc. Only Fans control are not working.
My EFI Folder: 
[EFI.zip](https://github.com/acidanthera/bugtracker/files/7109633/EFI.zip)

**Comment by vit9696** [comment]
We do not do this here. You can contribute patches yourself.
