### ISSUE TITLE
opencore 0.7.3 ROG Z390I Stuck on [EB|#LOG:EXITBS:START] But 0.7.2 starts normally

### ISSUE THREAD

**Issue by imotoboy** [acidanthera/bugtracker#1780]
![IMG_0413](https://user-images.githubusercontent.com/54018634/132273393-de26055c-a841-4d05-be0c-719863c5061f.jpg)

**Comment by imotoboy** [comment]
![IMG_0413](https://user-images.githubusercontent.com/54018634/132273463-d1ccb75b-3d71-4754-b70e-b3cf5c766399.jpg)

**Comment by vit9696** [comment]
Not a support forum. Check your config with ocvalidate.

**Comment by zhang-wenchao** [comment]
@vit9696 I have the same problem. Not ROG. 0.7.2 everything is normal. 0.7.3  Stuck on LOG:EXITBS:START. I think this is a bug, I should try how to do it.

**Comment by zhang-wenchao** [comment]
@imotoboy  Are you still trying? Looking forward to your good news.

**Comment by zhang-wenchao** [comment]
@vit9696 Sorry, it is my profile error.

**Comment by imotoboy** [comment]
> @imotoboy Are you still trying? Looking forward to your good news.

Drivers diff
<img width="613" alt="截屏2021-09-08 上午7 47 50" src="https://user-images.githubusercontent.com/54018634/132424040-46ea4e55-a65d-4475-8132-3802b297a54c.png">

**Comment by findyy99** [comment]
> @vit9696 Sorry, it is my profile error.

Hello, I want to know how did you edit your profile, I met the same problem as you.
