### ISSUE TITLE
OpenCanopy not appear on my boot menu.

### ISSUE THREAD

**Issue by ArchCryptonIO** [acidanthera/bugtracker#1782]
## Hello there,

This is regarding **OpenCore**Bootloader version **0.7.3,** which I experienced an **issue** with OpenCanopy.efi. I'm not sure if it's experienced by other users. The OpenCanopy I use has no problems since version **0.7.2 and below**. However, OpenCanopy does not appear in the **current** version (0.7.3). I just upgraded the EFI of my second machine. But it remains the same. I have **read and checked** every available document related to **my error in my "config.plist"** using **"ocvalidate"** by adapting it to the latest **"sample.plist"** provided on **"OpenCore-0.7.3-RELEASE"**. I also resetting the **"NVRAM"** a couple of times. However, **OpenCanopy still does not appear**. Please **assist** in resolving the issue or **point out** the mistake I made.

[opencore-2021-09-07-163109.txt](https://github.com/acidanthera/bugtracker/files/7123097/opencore-2021-09-07-163109.txt)

**Comment by 82ghost82** [comment]
OC DEBUG+log please.
First recheck with ocvalidate, update ocbinarydata and make sure path to theme is correct in config.plist.

**Comment by qin9125** [comment]
metoo 0.7.3

**Comment by 82ghost82** [comment]
> me too 0.7.3

Guys! please!
Now I understand why the developers seem rude when replying (in real they aren't at all...).
What do you expect they reply without logs and pointing you all to forums?

**Comment by ArchCryptonIO** [comment]
Sorry for late reply, Im appreciate i get help here from you all. This is my Debug Log:

[opencore-2021-09-07-163109.txt](https://github.com/acidanthera/bugtracker/files/7123083/opencore-2021-09-07-163109.txt)

via OC-Tool

<img width="1299" alt="Screenshot 2021-09-08 at 12 27 42 AM" src="https://user-images.githubusercontent.com/86180725/132380723-df7408f8-da7a-4093-bbbe-d69e6d68c884.png">

**Comment by ArchCryptonIO** [comment]
> OC DEBUG+log please.
> First recheck with ocvalidate, update ocbinarydata and make sure path to theme is correct in config.plist.

TQ, i will try to check out again.

**Comment by 82ghost82** [comment]
ocvalidate, not oc-tool :)
ocvalidate is budled with opencore and it's the only supported tool to validate config.plist.

Anyway, from your log:
02:143 00:009 OCUI: Failed to load images for Acidanthera\Blackosx

Most probably the path in the config.plist is wrong, cannot check, on mobile now, but usually it's vendor/nameofthetheme, so something like:
Blackosx/themename

**Comment by vit9696** [comment]
```
02:143 00:009 OCUI: Failed to load images for Acidanthera\Blackosx
02:148 00:005 OC: External interface failure, fallback to builtin - Unsupported

**Comment by ArchCryptonIO** [comment]
Thank you Everyone, Im sure it was my mistake.
