### ISSUE TITLE
Pentium 4 Issues on Certain Old Systems

### ISSUE THREAD

**Issue by John-Jelatis** [acidanthera/bugtracker#1783]
I am running an Intel Pentium 4 (541) in a Dell Optiplex GX280 (latest BIOS, A08) and getting "X64 Exception Type" errors with the latest OpenCore 0.7.3. This occurs prior to showing the picker or loading any drivers. The issue also occurs when trying to boot an older build (0.6.6 I believe), so it's not newly introduced.
 
Ultimately, I've traced this to OcCpuLib.c's core count detection, and temporarily worked around the issue on my system by hardcoding the core and thread count in and recompiling. Obviously this is not a permanent solution, but I don't quite know why the error is occurring and this gets it to work.
 
The same Pentium 4 541 worked when it was in my GX520 (and I've even gotten El Capitan "running" to an extent on that one). Is it possible that that the older chipset (915G as opposed to 945G) is somehow responsible for the crash and interfering with the checks working? Is there anything I can do to try to debug this further?

**Comment by vit9696** [comment]
Hi, could be the firmware of yours, but hard to say. Do you have the exact line where it crashes? Not quite possible to say otherwise.

**Comment by nms42** [comment]
Legacy versions of dxe drivers needed may be?

**Comment by nms42** [comment]
SSE3+ OC binaries too?

**Comment by John-Jelatis** [comment]
@vit9696 In the logfile, it is printing out this:
```
00:000 00:000 OC: OpenCore DBG-074-2021-09-07 is loading in Optional mode (0/0)...
00:030 00:030 OC: Boot timestamp - 2021.09.07 21:44:49
00:068 00:037 OCCPU: No MP services - Not Found
00:100 00:031 OCCPU: Found               Intel(R) Pentium(R) 4 CPU 3.00GHz
00:131 00:031 OCCPU: Signature F49 Stepping 9 Model 4 Family F Type 0 ExtModel 0 ExtFamily 0 uCode 3
00:164 00:032 OCCPU: EIST CFG Lock 0
00:197 00:032 OCCPU: Timer address is 808 from LPC
00:228 00:030 OCCPU: Failed to get FSBFrequency data using Apple Platform Info - Not Found
00:364 00:136 OCCPU: Intel TSC:  2992527589Hz,  2992MHz; FSB:   199501839Hz,   199MHz; MaxBusRatio: 15
```
and then it goes to that red screen and stops outputting to this log. [I only have a screen capture of the latest non-debug build from dortania.github.io/builds offhand, if that's not sufficient I'll have to get a recording with 0.7.3's debug build this weekend or something.](https://media.discordapp.net/attachments/251043252046659586/884910253366472704/image0.jpg?width=841&height=631).
 
 
 
As to your point @nms42 - My CPU supports SSE3, so I don't think that's an issue. Previously, the CPU had been in a different system, my Dell Optiplex GX520, where it worked [fine](https://i.redd.it/oj3racmty9971.gif). It was only when I swapped it into the GX280 that I started encountering these issues. Hardcoding OcCpuLib's core and thread counting seems to be a temporary solution for my system, so I have doubts that it's a missing instruction or anything - though I don't do any bootloader dev, so admittedly my speculations at this point are probably just about useless. 
  
I've confirmed the issue occurs when I've removed all drivers except OpenRuntime (and doesn't occur at all after having recompiling with the aforementioned hack, even using drivers from the unmodified RELEASE package), so it also seems not to be a driver issue.

**Comment by vit9696** [comment]
Yes, I need you to add more log prints and locate the exact crash line. Would you be able to make it?

**Comment by John-Jelatis** [comment]
Where would I get more log prints than the debug log? I'm not going to be at the system again until this weekend, so I'll have to update you then.

**Comment by vit9696** [comment]
My personal opinion is that ppsspp should be cask, because I find it extremely weird that a bundle app is installed into some weird place and is not added to `/Applications`. However, this would require some basic interaction with upstream.

**Comment by vit9696** [comment]
I would say it could be some code in `OcCpuLib.c` after `Calculate number of cores.`. You could insert prints like `DEBUG ((DEBUG_INFO, "OCCPU: Reached 1\n"));` and then see which line causes a crash. I expect it to be some MSR or CPUID read.

**Comment by John-Jelatis** [comment]
Okay, got it – I'll do so on Friday when I have access to the GX280 next.

**Comment by John-Jelatis** [comment]
Sorry for the delay, was a bit busy yesterday. However, I am back with an update.

The line `AsmReadMsr64 (MSR_CORE_THREAD_COUNT);` (line 580 as of c20928f) seems to be the culprit (I surrounded it with DEBUG( ... ) lines and confirmed that). I checked some values - CpuGeneration = 2 (PrePenryn) and MaxId = 3. If there are more useful values you'd like me to log, let me know.

**Comment by John-Jelatis** [comment]
I've just booted Linux Mint and run `lscpu` - strangely, it says that SSE3 is _not_ supported (despite the fact that I've confirmed the 541 does and it reports correctly in the GX520). Do you know of any reason this might be the case?

**Comment by vit9696** [comment]
@John-Jelatis I pushed an update in https://github.com/acidanthera/OpenCorePkg/commit/072b705d3a72f0167d47200f1f08f5451a63f8ab, which should print the max CPUID value your CPU supports. For this Pentium model I believe we should be taking the following branch, but for some reason we do not:

```C
  if (Cpu->MaxId >= CPUID_CACHE_PARAMS
    && (Cpu->CpuGeneration == OcCpuGenerationPrePenryn
    || Cpu->CpuGeneration == OcCpuGenerationPenryn
    || Cpu->CpuGeneration == OcCpuGenerationBonnell
    || Cpu->CpuGeneration == OcCpuGenerationSilvermont
    || Cpu->Hypervisor)) {
```

Perhaps it additionally needs the `Cpu->MaxId == 0` check, i.e. when `MaxId` is unsupported. Could you provide the logs with the new one?

As for SSE3 and Linux, I am not sure really. Might be better to ask on the Linux kernel mailing lists.

**Comment by John-Jelatis** [comment]
I've downloaded the latest build and attached the new log. 

```
00:000 00:000 OC: OpenCore DBG-074-2021-09-12 is loading in Optional mode (0/0)...
00:066 00:066 OC: Boot timestamp - 2021.09.12 02:40:30
00:132 00:066 OCCPU: No MP services - Not Found
00:199 00:066 OCCPU: Found               Intel(R) Pentium(R) 4 CPU 3.00GHz
00:265 00:066 OCCPU: Signature F49 Stepping 9 Model 4 Family F Type 0 ExtModel 0 ExtFamily 0 uCode 3 CPUID MAX (3/80000008)
00:332 00:066 OCCPU: EIST CFG Lock 0
00:398 00:066 OCCPU: Timer address is 808 from LPC
00:464 00:066 OCCPU: Failed to get FSBFrequency data using Apple Platform Info - Not Found
00:631 00:166 OCCPU: Intel TSC:  2992527360Hz,  2992MHz; FSB:   199501824Hz,   199MHz; MaxBusRatio: 15
```

**Comment by vit9696** [comment]
Should be fixed in master. Could you please confirm that the latest OC works and that the counts are correct for you (should be 1 core 2 threads)?

**Comment by John-Jelatis** [comment]
Seems to be working fine now! Thanks!

**Comment by ironapple0915** [comment]
Does the OcCpuGenerationPrePenryn class consist of older Core 2 processors (such as Conroe/Yonah), or possibly even the Pentium D? Those can have more than one core, yet might run into that portion of the if statement?

**Comment by vit9696** [comment]
Conroe and Yonah should have the cache params and fit that first if.
