### ISSUE TITLE
OpenCore Freezing at Boot Screen - Commit 22cfebd - Platform: OpenLinuxBoot.efi

### ISSUE THREAD

**Issue by dmcnaugh15** [acidanthera/bugtracker#1785]
With OC 0.7.3 my unit started freezing at the apple boot screen (see link to video).  The problem first appears with build 22cfebd.  Even more specifically, the problem happens when switching out the OpenCore.efi file.

Video demonstration of the problem (build 22cfebd): https://youtu.be/ZkHBHqImKew
Video demonstration of last working version (build d2ba13b) : https://youtu.be/lEIbQ5qYQp8
EFI folder link: http://DAMDAS.myqnapcloud.com:8082/share.cgi?ssid=254d05fab8b141488f47d76bbe1bd923

My computer specs: 
OS: Big Sur 11.4 
Board: ASUS ROG MAXIMUS XI HERO (WI-FI) 
CPU: Intel(R) Core(TM) i9-9900K CPU 
Graphics: Radeon RX 580 Series

**Comment by vit9696** [comment]
Make sure your config is updated. Particularly the Drivers section.
