### ISSUE TITLE
High Sierra 10.13: OC 0.7.2 LoadImage failed - Unsupported

### ISSUE THREAD

**Issue by WhaleIsland** [acidanthera/bugtracker#1786]
### Recovery install macOS High Sierra 10.13

>07:990 00:033 OCBP: Predefined <nil> \EFI\BOOT\BOOTX64.EFI was found
08:020 00:029 OCB: Adding entry type (T:1|F:0|G:1) - PciRoot(0x0)/Pci(0x14,0x0)/USB(0x4,0x0)/HD(1,GPT,4AF3B014-A85C-4524-A09A-C949281A511A,0x800,0x1CD67DF)/\EFI\BOOT\BOOTX64.EFI
08:050 00:029 OCB: Discarding discovered OpenCore bootloader
08:079 00:029 OCBP: APFS recovery volume handle missing - \EFI\BOOT\
08:113 00:033 OCB: APFS recovery is not present - Not Found
...
09:332 00:029 OCB: Showing menu... 
09:425 00:093 OCHK: InitHotKeys
09:453 00:027 OCKM: Allocated key repeat context 92658818 92658198 92658998
09:483 00:030 OCAE: Set screen resolution to 2560x1440 - Success
09:512 00:029 OCTY: Registered handler
14:543 05:030 OCHK: FreeHotKeys
14:924 00:381 OCTY: Unregistered handler
14:963 00:038 OCKM: Freeing key repeat context 92658818 92658198 92658998
14:992 00:029 OCB: Should boot from 1. High Sierra 10.13 (T:4|F:1|G:0|E:1|DEF:0)
15:056 00:063 OCRAM: Extent allocation of 668455349 bytes (A) gave 100000000
49:963 34:907 OCRAM: SHA-256 Digest is: FEF9B4FC2403B97A2B8F66667DF0B7570036D55A890250B57465B8C16B776A23
49:994 00:030 OCB: Found chunklist BaseSystem.chunklist for DMG BaseSystem.dmg[10]
59:119 09:125 OCDI: Built DMG DP: VenHw(957932CC-7E8E-433B-8F41-D391EA3C10F8,00000000)/MemoryMapped(0xA,0x100000000,0x100001000)/DMG_0000000027D7D1B5.dmg/VenMsg(004B07E8-0B9C-427E-B0D4-A466E6E57A62,B5D1D72700000000)
59:215 00:095 OCJS: Matched device path
59:253 00:038 OCJS: Matched device path
59:285 00:031 OCB: Failed to get bootable file off DMG
59:315 00:029 OCB: Failed to retrieve boot file from DMG
59:344 00:029 OCB: LoadImage failed - Unsupported

- python macrecovery.py is used to obtain the image file, I cannot verify the integrity of the image file.
- I completely follow the [dortania.github.io](https://dortania.github.io/OpenCore-Install-Guide) to build the config.plist file.
- For the convenience of reading, it has been converted to txt
  - [config(1).txt](https://github.com/acidanthera/bugtracker/files/7144278/config.1.txt)
  - [opencore-2021-09-09-000551.txt](https://github.com/acidanthera/bugtracker/files/7144282/opencore-2021-09-09-000551.txt)

CPU: i5-10500  Motherboard: B560M

**Comment by vit9696** [comment]
No HFS+ driver.

**Comment by WhaleIsland** [comment]
i used HfsPlus.efi

**Comment by vit9696** [comment]
`ocvalidate` does not agree, your config is incorrect.

**Comment by WhaleIsland** [comment]
I set the config exactly according to [Comet Lake](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html).
Can you tell me more about ``ocvalidate``？
Thanks.

**Comment by mikebeaton** [comment]
It is quite likely some aspects of the guides are yet to be updated - please use the new layout of the drivers section, which can be seen in the sample plist files in the Docs directory of acidanthera/OpenCorePkg. `ocvalidate` is a command line tool in the  Utilities directory of the OpenCore download package.

**Comment by mikebeaton** [comment]
This is not a support forum, and you are asking a question about basic usage, not reporting a bug.

However... the Drivers section layout has changed. If the relevant guides are not yet updated, then you will have to make the change yourself. Look at the Drivers section of the sample plist files in https://github.com/acidanthera/OpenCorePkg/tree/master/Docs . This is the format you must use with OpenCore 0.7.3+.

**Comment by WhaleIsland** [comment]
Sorry, I got it.
