### ISSUE TITLE
Sensor problem

### ISSUE THREAD

**Issue by mjs520** [acidanthera/bugtracker#1788]
Laptop battery can't display temperature under Sensei software. Can you solve it, thank you

**Comment by 1Revenger1** [comment]
Temperature is supplemental data that you need to add yourself. There is some information about it [here](https://github.com/acidanthera/VirtualSMC/blob/master/Docs/Battery%20Information%20Supplement.md) from the VirtualSMC repo. It's not something that really can be done automatically though afaik.

**Comment by mjs520** [comment]
thanks
