### ISSUE TITLE
how to fix in opencore 073 hang at hangs lnx: reading \etc\default\grub  thx

### ISSUE THREAD

**Issue by kocoman1** [acidanthera/bugtracker#1791]
how to fix in opencore 073 hang at hangs lnx: reading \etc\default\grub

thx

**Comment by mikebeaton** [comment]
Try the latest build https://github.com/acidanthera/OpenCorePkg/suites/3755791605/artifacts/92241224 as this has fixed similar issues in #1778.

**Comment by mikebeaton** [comment]
@kocoman1 - apparently issue still present - can you download latest debug version https://github.com/acidanthera/OpenCorePkg/suites/3769776633/artifacts/92756468 , add `flags=0xffff` to the `Arguments` for `OpenLinuxBoot` driver, run OC, and if it crashes send the debug log, pls?

**Comment by mikebeaton** [comment]
@kocoman1 - Thanks for your initial report. As ever in OSS, this is maintained by volunteers in their own time, and users' assistance is resolving bugs is much appreciated (and also necessary, when the bug is only happening on user machines, not any dev machines here). I would agree there is a real bug here, which seems to be affecting both you and @btwise (but not me, or anyone here!) - so logs provided when it is happening can make all the difference. Thanks.

**Comment by mikebeaton** [comment]
This issue should now be fixed by https://github.com/acidanthera/OpenCorePkg/commit/15bc4003b2ff0e9393b0899724711160b39a659a

**Comment by kocoman2** [comment]
28:684 00:001 OCB: Should boot from 2. LNX-D-48f5be4d: Ubuntu 22.04.1 LTS (T:64|F:0|G:0|E:0|DEF:0)
28:686 00:001 OCB: Perform boot LNX-D-48f5be4d: Ubuntu 22.04.1 LTS to dp PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)/NVMe(0x1,46-2E-27-4B-8B-44-1B-00)/HD(4,GPT,48F5BE4D-1856-46A8-AF84-E19F14DDCAC5,0x30E8B800,0x94FA000)/\boot\vmlinuz-5.15.0-50-generic (0/0)
28:688 00:001 OCABC: EfiBootRt candidate - PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)/NVMe(0x1,46-2E-27-4B-8B-44-1B-00)/HD(4,GPT,48F5BE4D-1856-46A8-AF84-E19F14DDCAC5,0x30E8B800,0x94FA000)/\boot\vmlinuz-5.15.0-50-generic
28:689 00:001 OCABC: IsEfiBootRt 0 (BP 1, Apple 0)
28:697 00:007 OCSB: Secure boot is disabled, skipping
28:698 00:001 OCB: Arch filtering 7D161018(11537472)->7D161018(11537472) caps 4 - Success
28:707 00:008 OCB: Matching <>/7DDB6B18[108] args on type 64
28:708 00:001 OCB: Args <initrd=\boot\initrd.img-5.15.0-50-generic root=PARTUUID=48f5be4d-1856-46a8-af84-e19f14ddcac5 rw quiet splash>
28:710 00:002 OCB: Custom (64) DeviceHandle 7EC04B18 FilePath 7DC62798

then just hangs
how to fix using 085 opencore thx

**Comment by mikebeaton** [comment]
It appears to be booting. Have you tried F12, to bring up Linux verbose boot log? Does this repo boot directly, not via OpenCore?

**Comment by kocoman1** [comment]
should put some hints on the log what flags to try, for 1) openlinuxboot 2) for older macos version kernel cache
