### ISSUE TITLE
0.7.3 documentation incorrect for UEFI->Drivers

### ISSUE THREAD

**Issue by jfredrickson** [acidanthera/bugtracker#1792]
The Configuration.pdf for OC 0.7.3 indicates that the `UEFI->Drivers` property is type `dict`. It should be type `array` since it is an array of dicts. It should be similar to the description for `Kernel->Add`, which is an array of dicts.

**Comment by mikebeaton** [comment]
Correct thank you for pointing out. The wording afterwards needs to be updated to match other arrays of dict too.

**Comment by mikebeaton** [comment]
https://github.com/acidanthera/OpenCorePkg/commit/23ff01a4bcf9dbeef0e111187f839308c12fce58
