### ISSUE TITLE
[Feature Request] Add Comment variable in Drivers

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1793]
Hi there,
given that the following feature request doesn't change the technical behaviour of OpenCore, I'd like to know if a `Comment` variable can be added to the `Drivers` array of dict, as already present in `ACPI/Add `and `Kernel/Add`.
What are your thoughts on that? Do you think it's achievable?
Greetings

**Comment by mikebeaton** [comment]
Also available in Tools and Entries, and actually multiple other sections. Therefore definitely not an unreasonable request. I thought at some point that I picked up that some people were wondering whether Comments were really needed in all the places they currently are, but I may have got that wrong! Would be happy to add at same time as fixing documentation in #1792 ? @vit9696 @mhaeuser ?

**Comment by vit9696** [comment]
Agree.

**Comment by PMheart** [comment]
Done in https://github.com/acidanthera/OpenCorePkg/commit/c8c231b00da9efd2ac81193f4a9d4f51d0e157b0.
