### ISSUE TITLE
[AppleALC][Feature Request] Ability to send alc wake verb data from custom SSDT

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#1794]
Hi 
In AppleALC, is it possible to add the ability to send codec command verb through a custom SSDT just like it is done in codec-commander ?
example here : https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/src/master/SSDT-ALC298.dsl
Adding this feature will make it much easier to send wake verbs. Without needing to install ALCPlugFix along with its ALCVerbs.plist in system.

Thanks

**Comment by stevezhengshiqi** [comment]
Check alc-verb, https://github.com/acidanthera/AppleALC/pull/614

**Comment by naveenkrdy** [comment]
@stevezhengshiqi hi 
i know about that but can that be in someway integrated into applealc directly instead, so that appleALC can read verb commands from a custom SSDT like it was done in codec-commander ?

**Comment by stevezhengshiqi** [comment]
Even CodeCommander needs ALCPlugFix as a client to send hda commands on certain codecs, see https://github.com/RehabMan/EAPD-Codec-Commander/issues/19.

Solely kernel level hda commands (WakeConfigData) cant completely drive certain codecs, and that’s the reason alc-verb is provided.

It’s a known issue discussed in https://github.com/acidanthera/bugtracker/issues/730

**Comment by 1Revenger1** [comment]
Couldn't you add those verbs to the ConfigWake section of the pin config? I thought that was what it was used for.

**Comment by naveenkrdy** [comment]
Sorry but not sure how to do configwake data 
Any guides on this and also on how to create custom applealc layout id ?
tried searching online but couldnt find anything.
