### ISSUE TITLE
I understand it isn't a bug, but I need help. I keep getting LoadImage failed - Unsupported.

### ISSUE THREAD

**Issue by brandonhogan** [acidanthera/bugtracker#1795]
I'm trying to use 10.13 of MacOS (High Sierra). I have an AMD Ryzen 5 1600, GTX 1080, ASRock A320M-HDV.
I've followed the guide but it isn't working, I have also applied the AMD patches etc. and checked it with: https://opencore.slowgeek.com/

I've tried to Google the issue and troubleshoot but I can't get it working at all. This is my first ever attempt trying to do Hackintosh, I am not at all knowledgeable in this field. I would appreciate if I could get some help or be told what I am doing wrong/what the issue is exactly. 

This is the link to my config.plist (https://drive.google.com/file/d/1xQ3I_R_xTzzUaOYN71TZcAhpGIrG3jX8/view?usp=sharing)

I am additionally using latest updated source. Below is the file left after failing booting/coming up with error.

[opencore-2021-09-18-153258.txt](https://github.com/acidanthera/bugtracker/files/7190121/opencore-2021-09-18-153258.txt)
s.

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
