### ISSUE TITLE
SMC Battery manger have problems hanging

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#1797]
@usr-sse2
i have problem with VirtualSMC battery kext idk why hanging when charge 
some time battery indictor have problem  
I use ec enable and smc battery manger kext
laptop : hp da1023nia

kext info:
VirtualSMC v1.2.7
ECEnabler v1.2

https://github.com/Edwardwich/hp-DA1023nia-Hackintosh/releases/download/7.3ssdt-Monterey/EFI-Monterey-Beta.zip
 its my efi folder I use

Screen Shot:
![Screen Shot 2021-09-19 at 4 36 01 PM](https://user-images.githubusercontent.com/35195176/133926993-fdcae46c-bec1-414c-805d-20f9d73f51a2.png)
red light :Power Source: Power Adapter
blue light : use Power Adapter battery not charging
![Screen Shot 2021-09-19 at 4 37 54 PM](https://user-images.githubusercontent.com/35195176/133927236-8e71275f-478e-4d56-9b9c-032d58eadb8f.png)

![IMG_20210919_163816](https://user-images.githubusercontent.com/35195176/133927249-d045eba1-55de-480f-b155-3b51b6e147d0.jpg)
IORegistryExplorer:

[MacBook Pro iorg.zip](https://github.com/acidanthera/bugtracker/files/7192054/MacBook.Pro.iorg.zip)

APCI folder:

[ACPI.zip](https://github.com/acidanthera/bugtracker/files/7192071/ACPI.zip)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
