### ISSUE TITLE
No hdmi audio of intel kaby lake HDMI(8086:280B)

### ISSUE THREAD

**Issue by countrysideboy** [acidanthera/bugtracker#1798]
I have a hystou mini pc(i7 10510u and realetk alc622),the aux output is ok when i use layout-id=05, but I cannot find the hdmi audio device .

AppleALC:1.6.4

The hdmi audio device is shown as intel kaby lake HDMI in windows os, and the ven&dev id is 8086:280B.
I think I shoud add the device id in the Controllers.plist file, but I have no idea about how to patch the applehda.kext.

**Comment by countrysideboy** [comment]
HD Audio
 				
[ Intel Comet Point-LP PCH - cAVS (Audio, Voice, Speech) ]
 
设备属性:
设备描述  	Intel Comet Point-LP PCH - cAVS (Audio, Voice, Speech)
设备描述 (Windows)  	High Definition Audio 控制器
总线类型  	PCI
总线/设备/功能  	0 / 31 / 3
设备 ID   	8086-02C8
子系统 ID  	8086-7270
修订  	00
硬件 ID  	PCI\VEN_8086&DEV_02C8&SUBSYS_72708086&REV_00
 
[ Realtek ALC662 ]
 
设备属性:
设备描述  	Realtek ALC662
设备描述 (Windows)  	High Definition Audio Device
设备类型  	Audio
总线类型  	HDAUDIO
设备 ID   	10EC-0662
子系统 ID  	10EC-0662
修订  	1003
硬件 ID  	HDAUDIO\FUNC_01&VEN_10EC&DEV_0662&SUBSYS_10EC0662&REV_1003
 

[ Intel Kaby Lake HDMI ]
 
设备属性:
设备描述  	Intel Kaby Lake HDMI
设备描述 (Windows)  	High Definition Audio Device
设备类型  	Audio
总线类型  	HDAUDIO
设备 ID   	8086-280B
子系统 ID  	8086-0101
修订  	1000
硬件 ID  	HDAUDIO\FUNC_01&VEN_8086&DEV_280B&SUBSYS_80860101&REV_1000

**Comment by Andrey1970AppleLife** [comment]
There are no patches for 8086:280B in Controllers.plist
Don't hesitate shares the decision.
