### ISSUE TITLE
CpuTscSync not working on Intel Core i7-4700MQ

### ISSUE THREAD

**Issue by alicela1n** [acidanthera/bugtracker#1800]
After installing CpuTscSync.kext on the Alienware 14 P36G, with an i7-4700MQ, the TSC issue still isn't solved. From what I've seen this kext should be plug and play, so it might be an issue with the kext. I've tested on OS X 10.9, macOS 10.13, 10.14, and 12.4.
[OC.zip](https://github.com/acidanthera/bugtracker/files/7228791/OC.zip)
.

**Comment by vit9696** [comment]
I think this one has too little info to consider it being a bug. Try master version and discuss it on the forums first.
