### ISSUE TITLE
ElanTouchPad is not working after wakeup

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#1801]
Hi, always thank you for great work.
today, i found touchpad not working issue after wakeup. previously, i didn't catch it.

Hardware : i7 6500u Skylake, PS2 Elan Touchpad
Bootloader : Latest OC
Lilu : Latest kext
VoodooPS2 
  - 2.2.4 version : both boot and wakeup, touchpad is no problem.
  - 2.2.5 version : boot is find, but after wakeup, touchpad is not working.
  => not working since this point blow
https://github.com/acidanthera/VoodooPS2/commit/a41ad20864f21937762e59db7098a52ac2daa5a1
  
Thanks in advance

**Comment by 1Revenger1** [comment]
Do you have any logs? Best way is using `sudo dmesg` while using DebugEnhancer.kext. Will want to use the debug version of VoodooPS2 as well. (Beware that the debug version logs all keypresses, which you may want to filter out if you post the log here)

**Comment by Sher1ocks** [comment]
> Do you have any logs? Best way is using `sudo dmesg` while using DebugEnhancer.kext. Will want to use the debug version of VoodooPS2 as well. (Beware that the debug version logs all keypresses, which you may want to filter out if you post the log here)

Here is log
[2.2.6-booted.txt](https://github.com/acidanthera/bugtracker/files/7229952/2.2.6-booted.txt)
[2.2.6-wakeup.txt](https://github.com/acidanthera/bugtracker/files/7229953/2.2.6-wakeup.txt)

thanks!

**Comment by Sher1ocks** [comment]
one more log. here, @1Revenger1 
[2.2.6-afterwakeup-onemore.txt](https://github.com/acidanthera/bugtracker/files/7229954/2.2.6-afterwakeup-onemore.txt)
[2.2.6-booted-onemore.txt](https://github.com/acidanthera/bugtracker/files/7229955/2.2.6-booted-onemore.txt)

**Comment by 1Revenger1** [comment]
Thanks
Looks like it detected your PS2 controller as one which could be muxed. Someone else has been having an issue with waking from sleep as well with it, though it was just with their trackpoint. I've got a PR coming which should hopefully fix it, though I've been running into weird interactions with VoodooRMI as well with it.

**Comment by Sher1ocks** [comment]
> Thanks
> Looks like it detected your PS2 controller as one which could be muxed. Someone else has been having an issue with waking from sleep as well with it, though it was just with their trackpoint. I've got a PR coming which should hopefully fix it, though I've been running into weird interactions with VoodooRMI.

thanks, after PR or test build, i will check

**Comment by 1Revenger1** [comment]
[VoodooPS2Controller-2.2.6-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7229992/VoodooPS2Controller-2.2.6-DEBUG.zip)
Fixed a bug in dispatchDriverPowerControl which didn't do power control in mice when muxed.
Need to account for the fact that data come from port 2 now instead of port 1 when trying to do stuff with the mouse port in PS2Controller but there's a workaround in the build I sent above.

**Comment by Sher1ocks** [comment]
> [VoodooPS2Controller-2.2.6-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7229992/VoodooPS2Controller-2.2.6-DEBUG.zip)
> Fixed a bug in dispatchDriverPowerControl which didn't do power control in mice when muxed.
> Need to account for the fact that data come from port 2 now instead of port 1 when trying to do stuff with the mouse port in PS2Controller but there's a workaround in the build I sent above.

fixed!! here is log
[fixed-afterwakeup.txt](https://github.com/acidanthera/bugtracker/files/7230004/fixed-afterwakeup.txt)
[fixed-boot.txt](https://github.com/acidanthera/bugtracker/files/7230005/fixed-boot.txt)
thanks alot!

**Comment by mjs520** [comment]
> 嗨，总是感谢您的出色工作。
> 今天，我发现唤醒后触摸板无法正常工作。以前，我没有抓住它。
> 
> 硬件：i7 6500u Skylake，PS2 Elan Touchpad
> Bootloader：最新的 OC
> Lilu：最新的 kext
> VoodooPS2
> 
> * 2.2.4版本：开机和唤醒，触摸板没问题。
> * 2.2.5 版本：开机找到，但唤醒后，触摸板不工作。
>   => 不工作，因为这点打击
>   [acidanthera/VoodooPS2@ a41ad20](https://github.com/acidanthera/VoodooPS2/commit/a41ad20864f21937762e59db7098a52ac2daa5a1)
> 
> 提前致谢



> Hi, always thank you for great work.
> today, i found touchpad not working issue after wakeup. previously, i didn't catch it.
> 
> Hardware : i7 6500u Skylake, PS2 Elan Touchpad
> Bootloader : Latest OC
> Lilu : Latest kext
> VoodooPS2
> 
> * 2.2.4 version : both boot and wakeup, touchpad is no problem.
> * 2.2.5 version : boot is find, but after wakeup, touchpad is not working.
>   => not working since this point blow
>   [acidanthera/VoodooPS2@a41ad20](https://github.com/acidanthera/VoodooPS2/commit/a41ad20864f21937762e59db7098a52ac2daa5a1)
> 
> Thanks in advance

Hello, my PS2 ENLAN touch pad, but some of my gestures and keyboard shortcuts can't be used. Did you change the key position of the original driver

**Comment by Sher1ocks** [comment]
> > 嗨，总是感谢您的出色工作。
> > 今天，我发现唤醒后触摸板无法正常工作。以前，我没有抓住它。
> > 硬件：i7 6500u Skylake，PS2 Elan Touchpad
> > Bootloader：最新的 OC
> > Lilu：最新的 kext
> > VoodooPS2
> > 
> > * 2.2.4版本：开机和唤醒，触摸板没问题。
> > * 2.2.5 版本：开机找到，但唤醒后，触摸板不工作。
> >   => 不工作，因为这点打击
> >   [acidanthera/VoodooPS2@ a41ad20](https://github.com/acidanthera/VoodooPS2/commit/a41ad20864f21937762e59db7098a52ac2daa5a1)
> > 
> > 提前致谢
> 
> > Hi, always thank you for great work.
> > today, i found touchpad not working issue after wakeup. previously, i didn't catch it.
> > Hardware : i7 6500u Skylake, PS2 Elan Touchpad
> > Bootloader : Latest OC
> > Lilu : Latest kext
> > VoodooPS2
> > 
> > * 2.2.4 version : both boot and wakeup, touchpad is no problem.
> > * 2.2.5 version : boot is find, but after wakeup, touchpad is not working.
> >   => not working since this point blow
> >   [acidanthera/VoodooPS2@a41ad20](https://github.com/acidanthera/VoodooPS2/commit/a41ad20864f21937762e59db7098a52ac2daa5a1)
> > 
> > Thanks in advance
> 
> Hello, my PS2 ENLAN touch pad, but some of my gestures and keyboard shortcuts can't be used. Did you change the key position of the original driver

hi, i didn't change anything

**Comment by 1Revenger1** [comment]
Fixed by https://github.com/acidanthera/VoodooPS2/commit/4bdf2d430141f379178746d3f24c73001d7e2b22
