### ISSUE TITLE
NVMeFix Kernel Panic

### ISSUE THREAD

**Issue by JeromeAstero** [acidanthera/bugtracker#1803]
Hello!
I get kernel panic when trying to work with a disk. The time before the kernel panic is always different.

My hardware:
- cpu: intel 4790k
- mb: gigabyte z97x-gaming g1 wi-fi bk
- ram: patriot 32gb(4x8gb), 1600mhz, cl10, 1.5v
- gpu: igpu(with zero framebuffer) + msi Radeon RX 470 4gb
- wifi+bt: fenvi pci x1
- 1x sata ssd 250gb
- 2x sata hdd 1000gb
- 1x sata hdd 3000gb
- 1x nvme ssd 1000gb (wd black sn750 over pcie x4 -> m.2 adapter, there is no M.2 connector on my board)

![IMG_1648](https://user-images.githubusercontent.com/11052468/134966675-4e7ca045-772b-402b-aeed-582dac0a7849.jpg)

An interesting point is that the specifications for the ssd indicate 3.3v 2.8a power, which gives the maximum theoretical power = 9.24w.
The smartmontools utility return the power state with a maximum power of 6w.
(With and without NVMeFIX)
![image](https://user-images.githubusercontent.com/11052468/134963154-04fc745b-f384-4112-ac09-06b29e5442d1.png)

I can also cause kernel panic by measuring the disk speed with the software Blackmagic Disk Speed Test.
If I measure the speed in a system installed on sata ssd, then nmve ssd simply turns off. And if I measure in a system installed on nvme ssd, then panic happens, and not always the same, examples of kernel panics in attachments).

Another confusing moment from the log is that NVMeFix cannot get the oem-product, oem-vendor, oem-board variables from Lilu.
I tried to include the ExposeSensitiveData(=8) setting in config.plist(opencore) - it didn't help, I can get the variables, but Lilu cannot detect them for transfer to NVMeFix.
![image](https://user-images.githubusercontent.com/11052468/134966280-e1e35bc2-2b90-4c5f-820c-08f1b920c88a.png)
![image](https://user-images.githubusercontent.com/11052468/134966441-03c5fec6-646d-4a19-beb4-e9f403fe0c17.png)

I tried the solution described in #1193 - not work.(im used forceRenderStandby=0 argument in boot-args).
Also in the BIOS there is a setting RC6 (Render Standby) = Disable

I using last version of opencore and lilu kexts.

Attachments:
[Lilu_1.5.6_20.5.txt](https://github.com/acidanthera/bugtracker/files/7238523/Lilu_1.5.6_20.5.txt)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/7238783/EFI.zip)
[smartctl_wd_sn_750.txt](https://github.com/acidanthera/bugtracker/files/7238786/smartctl_wd_sn_750.txt)
[panics.zip](https://github.com/acidanthera/bugtracker/files/7238789/panics.zip)
[ioreg.zip](https://github.com/acidanthera/bugtracker/files/7238792/Jerome.s.iMac.Retina.ioreg.zip)

Best regards,
Anton Zhivov.

**Comment by vit9696** [comment]
Looks like dying NVMe or PCI slot to be honest. I see that ASPM is already disabled for this NVMe, so not much I can suggest.
