### ISSUE TITLE
Toshiba Tecra Z50-C, SMCBatteryManager - quickPolling never triggers, battery gets stuck at 100% once polling is disabled.

### ISSUE THREAD

**Issue by Enigmahack** [acidanthera/bugtracker#1804]
Here's the EFI + IORegExplorer + Logs + DSDT and SSDT dump. 
[Z50-C_Hackintosh.zip](https://github.com/acidanthera/bugtracker/files/7244214/Z50-C_Hackintosh.zip)

Long story short, my ACPI never triggers quickPolling. I have no EC so _STA changes from my AC Adapter never cause quickPolling to be enabled. Once the battery is full and polling is turned off, it'll never see any status changes until I reboot or come out of sleep mode. 

The SSDT's are a mess as I was attempting to debug what information was being sent, but everything is correct according to ACPI (And AC adapter updates are triggered in Linux and Windows)

If I'm missing logs, please let me know and I'll upload them. 
Lilu and VirtualSMC are on latest versions as of Sept 28, 2021.

**Comment by Enigmahack** [comment]
Adding additional information: 
When using ACPI_Listen in Ubuntu, when the AC adapter is unplugged, the following is the output: 

`ac_adapter ACPI0003:00 00000080 00000000
processor LNXCPU:00 00000081 00000000
processor LNXCPU:01 00000081 00000000
processor LNXCPU:02 00000081 00000000
processor LNXCPU:03 00000081 00000000
 TOS6208:00 00000080 00000e00
`

When plugged back in: 
`ac_adapter ACPI0003:00 00000080 00000001
processor LNXCPU:00 00000081 00000000
processor LNXCPU:01 00000081 00000000
processor LNXCPU:02 00000081 00000000
processor LNXCPU:03 00000081 00000000
 TOS6208:00 00000080 00000e80
`

This is the only ACPI information being provided to the OS (that I'm aware of) that SMCBatteryManager doesn't seem to be able to handle. 

In my DSDT, TOS6208 is referred to as VALZ, Battery is BAT1 and ac is ADP1

**Comment by vit9696** [comment]
Well, your ACPI must deliver notifications when charging is complete…? I do not know much about batteries, but this sounds like some configuration issue.

CCing some other people just in case. @1Revenger1 @usr-sse2 @zhen-zen

**Comment by Enigmahack** [comment]
I'm unsure why this is closed - It's not a configuration issue. Notifications are absolutely sent from the ACPI (In 3 cases: Adapter plugged in, Adapter Unplugged and Charging Complete), but aren't being handled appropriately. I was trying to track down exactly what VirtualSMC (SMCBatteryManager) is looking for from ACPI, because quickPolling is never started at all. I can provide further information of what's going on in macOS itself, but because there's a lack of embedded controller, it seems like a somewhat edge-case that isn't handled by the battery drivers.

**Comment by 1Revenger1** [comment]
SMCBatteryManager will register to all [power adapters](https://github.com/acidanthera/VirtualSMC/blob/master/Sensors/SMCBatteryManager/BatteryManager.cpp#L166) and [batteries](https://github.com/acidanthera/VirtualSMC/blob/master/Sensors/SMCBatteryManager/BatteryManager.cpp#L132) to listen for ACPI notifications from them.  They both are registered to run "acpiNotification" if `notify(Bat/AC)` is called in your ACPI. Whether or not there is an EC exposed in your DSDT is irrelevant, as SMCBatteryManager only listens to call to `notify`.

I doubt that something is wrong in SMCBatteryManager, and I'd prove that `notify` is being called before pointing the finger at SMCBatteryManager. ACPI behavior can change between Linux and macOS.

**Comment by Enigmahack** [comment]
Okay - thank you for your response. 
I'm debugging my DSDT and ACPI configuration right now to ensure that it's doing exactly as you suggest. I'll pour over the source some more and see if I can convince the adapter to notify when changes happen. I did try editing the DSDT to include additional notifications but as soon as I told the ADP1 to notify BAT1 of changes, there was a polling loop that bounced back and forth between the adapter and battery. 

I'll keep working on it.
