### ISSUE TITLE
Set "agdpmod" properties in IGPU device for Intel HD 530 Desktop Skylake Monterey Beta 8

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#1807]
According to Whatevergreen description, we can replace "agdpmod=vit9696" with add "agdpmod" property to external GPU.

Unfortunately i didn't have dGPU in my PC setup. My computer specifications is Intel Core i7 6700 + Gigabyte GA-Z170X Gaming 7 with no dGPU. 

Since Monterey 8, i need bootargumen "agdpmod=vit9696" to reach desktop of Monterey Beta 8 if i didn't use this then i only stuck in log "IOSCreenlockstate xxxx". But i can remote it with Anydesk but Monterey Beta 8 didn't recognize my monitor.

I have tried igfxonln=1 or igfxfcms=1 but non of these boot argumen will solve the problem. Problem will be fixed with "agdpmod=vit9696"

I just ask, can team make change for whatevergreen so i can use "agdpmod" in IGPU property so i didn't need to use this bootargument. Because for now it only work for External GPU Property only

**Comment by Lorys89** [comment]
> According to Whatevergreen description, we can replace "agdpmod=vit9696" with add "agdpmod" property to external GPU.
> 
> Unfortunately i didn't have dGPU in my PC setup. My computer specifications is Intel Core i7 6700 + Gigabyte GA-Z170X Gaming 7 with no dGPU.
> 
> Since Monterey 8, i need bootargumen "agdpmod=vit9696" to reach desktop of Monterey Beta 8 if i didn't use this then i only stuck in log "IOSCreenlockstate xxxx". But i can remote it with Anydesk but Monterey Beta 8 didn't recognize my monitor.
> 
> I have tried igfxonln=1 or igfxfcms=1 but non of these boot argumen will solve the problem. Problem will be fixed with "agdpmod=vit9696"
> 
> I just ask, can team make change for whatevergreen so i can use "agdpmod" in IGPU property so i didn't need to use this bootargument. Because for now it only work for External GPU Property only

try with this bootargs  igfxagdc=0

**Comment by andreszerocross** [comment]
> > According to Whatevergreen description, we can replace "agdpmod=vit9696" with add "agdpmod" property to external GPU.
> > Unfortunately i didn't have dGPU in my PC setup. My computer specifications is Intel Core i7 6700 + Gigabyte GA-Z170X Gaming 7 with no dGPU.
> > Since Monterey 8, i need bootargumen "agdpmod=vit9696" to reach desktop of Monterey Beta 8 if i didn't use this then i only stuck in log "IOSCreenlockstate xxxx". But i can remote it with Anydesk but Monterey Beta 8 didn't recognize my monitor.
> > I have tried igfxonln=1 or igfxfcms=1 but non of these boot argumen will solve the problem. Problem will be fixed with "agdpmod=vit9696"
> > I just ask, can team make change for whatevergreen so i can use "agdpmod" in IGPU property so i didn't need to use this bootargument. Because for now it only work for External GPU Property only
> 
> try with this bootargs igfxagdc=0 igfxonln=1

I thought you got miss information from my questions. 

The problem is solved with agdpmod=vit9696 in Monterey Beta 8.

My question is, i need to replace this boot arg to device properties.

WEG doc say we can replace agdpmod=vit9696 boot args with add agdpmod properties in External GPU device.

The problem is, i don't have external GPU device, so i request dev team to apply to weg so i can use agdpmod in IGPU properties without using agdpmod=vit9696 boot args again

**Comment by andreszerocross** [comment]
> > According to Whatevergreen description, we can replace "agdpmod=vit9696" with add "agdpmod" property to external GPU.
> > Unfortunately i didn't have dGPU in my PC setup. My computer specifications is Intel Core i7 6700 + Gigabyte GA-Z170X Gaming 7 with no dGPU.
> > Since Monterey 8, i need bootargumen "agdpmod=vit9696" to reach desktop of Monterey Beta 8 if i didn't use this then i only stuck in log "IOSCreenlockstate xxxx". But i can remote it with Anydesk but Monterey Beta 8 didn't recognize my monitor.
> > I have tried igfxonln=1 or igfxfcms=1 but non of these boot argumen will solve the problem. Problem will be fixed with "agdpmod=vit9696"
> > I just ask, can team make change for whatevergreen so i can use "agdpmod" in IGPU property so i didn't need to use this bootargument. Because for now it only work for External GPU Property only
> 
> try with this bootargs igfxagdc=0 igfxonln=1

Btw, with igfxagdc=0 i can boot to monterey beta 8 too. Thanks.

I prefer to use this, but i use "disable-agdc" properties instead "igfxagdc=0". And i can use this properties to IGPU, 

Thank you, i will close this..

![image](https://user-images.githubusercontent.com/9614101/135277924-fa9efbc4-880a-40b3-b5ff-b9eef44a6f56.png)

**Comment by Lorys89** [comment]
> > > According to Whatevergreen description, we can replace "agdpmod=vit9696" with add "agdpmod" property to external GPU.
> > > Unfortunately i didn't have dGPU in my PC setup. My computer specifications is Intel Core i7 6700 + Gigabyte GA-Z170X Gaming 7 with no dGPU.
> > > Since Monterey 8, i need bootargumen "agdpmod=vit9696" to reach desktop of Monterey Beta 8 if i didn't use this then i only stuck in log "IOSCreenlockstate xxxx". But i can remote it with Anydesk but Monterey Beta 8 didn't recognize my monitor.
> > > I have tried igfxonln=1 or igfxfcms=1 but non of these boot argumen will solve the problem. Problem will be fixed with "agdpmod=vit9696"
> > > I just ask, can team make change for whatevergreen so i can use "agdpmod" in IGPU property so i didn't need to use this bootargument. Because for now it only work for External GPU Property only
> > 
> > 
> > try with this bootargs igfxagdc=0 igfxonln=1
> 
> Btw, with igfxagdc=0 i can boot to monterey beta 8 too. Thanks.
> 
> I prefer to use this, but i use "disable-agdc" properties instead "igfxagdc=0". And i can use this properties to IGPU,
> 
> Thank you, i will close this..
> 
> ![image](https://user-images.githubusercontent.com/9614101/135277924-fa9efbc4-880a-40b3-b5ff-b9eef44a6f56.png)

happy to have helped you but next time post on the forums thank you!

**Comment by andreszerocross** [comment]
> > > > According to Whatevergreen description, we can replace "agdpmod=vit9696" with add "agdpmod" property to external GPU.
> > > > Unfortunately i didn't have dGPU in my PC setup. My computer specifications is Intel Core i7 6700 + Gigabyte GA-Z170X Gaming 7 with no dGPU.
> > > > Since Monterey 8, i need bootargumen "agdpmod=vit9696" to reach desktop of Monterey Beta 8 if i didn't use this then i only stuck in log "IOSCreenlockstate xxxx". But i can remote it with Anydesk but Monterey Beta 8 didn't recognize my monitor.
> > > > I have tried igfxonln=1 or igfxfcms=1 but non of these boot argumen will solve the problem. Problem will be fixed with "agdpmod=vit9696"
> > > > I just ask, can team make change for whatevergreen so i can use "agdpmod" in IGPU property so i didn't need to use this bootargument. Because for now it only work for External GPU Property only
> > > 
> > > 
> > > try with this bootargs igfxagdc=0 igfxonln=1
> > 
> > 
> > Btw, with igfxagdc=0 i can boot to monterey beta 8 too. Thanks.
> > I prefer to use this, but i use "disable-agdc" properties instead "igfxagdc=0". And i can use this properties to IGPU,
> > Thank you, i will close this..
> > ![image](https://user-images.githubusercontent.com/9614101/135277924-fa9efbc4-880a-40b3-b5ff-b9eef44a6f56.png)
> 
> happy to have helped you but next time post on the forums thank you!

I think this not about forum. Because my first post is about weg features. My problem is fixed with agdpmod=vit9696 or igfxagdc=0

agdpmod=vit9696 can be replaced with agdpmod in external gpu properties
igfxagdc=0 can be replace with disable-agdc in igpu properties.

So my first questions above is ask dev team if they can make "agdpmod" properties to IGPU too.

Btw thanks,

**Comment by Lorys89** [comment]
try i f work
![Schermata 2021-09-29 alle 15 41 02](https://user-images.githubusercontent.com/64613690/135280175-d6cbb66c-c652-4f43-8582-4cf273be66fb.png)

**Comment by andreszerocross** [comment]
> try i f work
> ![Schermata 2021-09-29 alle 15 41 02](https://user-images.githubusercontent.com/64613690/135280175-d6cbb66c-c652-4f43-8582-4cf273be66fb.png)

Nice, with this properties in DSDT i can boot to monterey beta 8. May i ask, so if we want to use agpdmod=pikera for RX 5700XT we can use property "agdpmod = string = pikera" in properties?? and should it in IGPU, External GPU or maybe both??

I thought "Read me " file of WEG need to be updated somehow according to this method. For me it's not clearing enough.

I just set "agdpmod = data = 01 00 00 00 before

![image](https://user-images.githubusercontent.com/9614101/135289692-41468f33-0d0a-42d4-a7fd-e8fea79baca5.png)

**Comment by Lorys89** [comment]
> > try i f work
> > ![Schermata 2021-09-29 alle 15 41 02](https://user-images.githubusercontent.com/64613690/135280175-d6cbb66c-c652-4f43-8582-4cf273be66fb.png)
> 
> Nice, with this properties in DSDT i can boot to monterey beta 8 too. May i ask, so if we want to use agpdmod=pikera for RX 5700XT we can use property "agdpmod = string = pikera" in properties?? and should it in IGPU, External GPU or maybe both??
> 
> I thought "Read me " file of WEG need to be updated somehow according to this method. For me it's not clear enough.
> 
> I just set "agdpmod = data = 01 00 00 00 before
> 
> ![image](https://user-images.githubusercontent.com/9614101/135289692-41468f33-0d0a-42d4-a7fd-e8fea79baca5.png)
it works for igpu and dgpu in both ways, bootarg, in the _Dsm ssdt or dsdt and in device propieties
