### ISSUE TITLE
[Feature Request] SMCBatteryManager: Emulate a layer of AppleACPIACAdapter with SMCBatteryManager

### ISSUE THREAD

**Issue by Ab2774** [acidanthera/bugtracker#1808]
Hi, usually `AppleACPIACAdapter` loads under `ACPI0003` named devices, such as `ADP1` and `AC`, with a simple ACPI modification like adding ```Name (_PRW, Package() { 0x18, 0x03 })``` under the `ACPI0003` device, however, in some Lenovo laptops, another step is required which is adding ```_PSR``` Method under the device too, the problem associated with this method is that it breaks battery percentage until the power source is updating by plugging/unplugging the charger, and can give two different icons for battery, sometimes it shows like that when the laptop is on `Battery Mode` (which is the intended icon to show when charging in Big Sur and above): ![Screen Shot 2021-10-01 at 1 20 47 AM](https://user-images.githubusercontent.com/60307632/135538799-8175cf91-050d-4406-bfe6-78d13da523d8.png), and it also shows like that when the laptop is on `Charger Mode`: ![Screen Shot 2021-09-30 at 11 18 44 PM](https://user-images.githubusercontent.com/60307632/135538871-dd69a4bf-a2e5-4344-bd43-8ccf905211ba.png).
Since you guys managed to emulate a layer of `AppleSmartBattery` with `SMCBatteryManager`, I think it would be a great addition to also emulate a layer of `AppleACPIACAdapter` with `SMCBatteryManager` too, rather than approach it with DSDT/SSDT patches, it would be great to handle it automatically without the need for any DSDT/SSDT modification similar to `BrightnessKeys` and @1Revenger1's `ECEnabler`.
Cheers

**Comment by dreamwhite** [comment]
What is unclear to me is: why should `AppleACPIACAdapter ` be loaded? Without it what kind of problems do you have?

If not, my modest opinion is that it's a little bit useless giving some effort to add a thing that isn't used at all, or is used just for cosmetics 😅. Maybe I'm too pessimistic but I see it as a `SAT0 to SATA` rename: useless and just for cosmetics, rather than a practical usage.

**Comment by Ab2774** [comment]
> What is unclear to me is: why should `AppleACPIACAdapter ` be loaded? Without it what kind of problems do you have?
> 
> If not, my modest opinion is that it's a little bit useless giving some effort to add a thing that isn't used at all, or is used just for cosmetics 😅. Maybe I'm too pessimistic but I see it as a `SAT0 to SATA` rename: useless and just for cosmetics, rather than a practical usage.

Hi @dreamwhite, thanks for the feedback, I kind of agree with you.

in macOS Catalina or earlier, the charging icon doesn't is the same on Macs and Hacs laptops, however, in Big Sur, the battery icon does have a cord in it (which I think it's kinda cute), this feature doesn't load unless AppleACPIACAdapter is loaded, other than that, it's basically no different, kind of similar to https://github.com/acidanthera/bugtracker/issues/1754, it's just about perfecting your hack rather than focusing on assuring that it runs macOS and nothing else matters.
I don't know if it's my ADHD or something but I like perfecting things to the limit, it's just trying to get the same software features that you'd get in a real Mac.
Anyway, thanks for your opinion.

**Comment by vit9696** [comment]
This sounds like a thing that can be done with a more or less simple SSDT. I am not sure we should add it to SMCBatteryManager, but I am not positive we will object if anyone submits the feature.

CCing @1Revenger1 @usr-sse2 @zhen-zen for comment if any.
