### ISSUE TITLE
Full Security install in macOS Monterey

### ISSUE THREAD

**Issue by osy** [acidanthera/bugtracker#1809]
While #1769 was fixed by https://github.com/acidanthera/RestrictEvents/commit/2430ed06c15a9f3dd94634ab68e208c8b762e11d which allowed macOS Monterey updates with `x86legacy`, the installer only works with the equivalent of "Medium Security". In other words, it only works with a globally signed im4m and not an ECID personalized im4m.

In patchd, if `apple-coprocessor-version` is not found, then it will always use `OS.dmg.mtree.%@.im4m` instead of `OS.dmg.mtree.%@.%@.im4m` (which has ECID personalization). Additionally if "hw.target" is blank (which is read to be blank if `bridge-model` is not found), then it will always force the second `%@` to `x86legacyap`. I think explains why only `x86legacy` model works on non-T2 machines. It's because it will always use `OS.dmg.mtree.x86legacyap.im4m` regardless of `ApBoardID` which will mismatch the manifest.

Basically in order to get the same Full Security behavior in Monterey (ECID personalized manifest), we have to get patchd to recognize the personalized manifest without a T2. I haven't tried it but I'm pretty sure spoofing `apple-coprocessor-version` globally will break a lot of things since it will think a T2 exists. However, I think interposing `/usr/lib/libimg4.dylib` and patching read of `hw.target` might be one way to get around it.

EDIT: So I originally thought this would prevent macOS Monterey from booting but I was wrong, it only applies to patchd. So by manually installing it with Secure Boot disabled and then running `bless --folder "/Volumes/Macintosh HD/System/Library/CoreServices" --bootefi --personalize` I was able to boot with Full Security with J174 model. This means as long as we can fix patchd, then OTA updates would work as well without changing model to `x86legacy` or disabling Secure Boot.

**Comment by vit9696** [comment]
Setting this variable lets you add hw.target: https://github.com/acidanthera/OpenCorePkg/commit/57cab7d287fd52b5d0b000d4c8640e10944d05ae#diff-f15c0305c0a4d0a705c441cda1e19fc02d55beaccd13cf6ea9149b52df2d1e97R266. You can try, but I have not explored it much.

**Comment by osy** [comment]
Thanks, I patched sysctl directly but that works better. That will get patchd to load `OS.dmg.mtree.j174.im4m` instead of `OS.dmg.mtree.x86legacyap.im4m`. However, to get `OS.dmg.mtree.j174.ECIDHERE.im4m` to load, we also need to patch `_img4_chip_select_effective_ap` as well inside the dyld cache (or patchd directly). `_img4_chip_select_effective_ap` reads `apple-coprocessor-version` from the IO registry, so I was thinking we can just patch that to something like `openc-coprocessor-version` and set that value. What, in your opinion, is the best way to do that?

**Comment by vit9696** [comment]
- I have a local patch that sets this variable from OpenCore config. By default it sets this variable automatically based on the model. Does this sound good?
- As for `_img4_chip_select_effective_ap` there is a quirk in OpenCore for the kernel part (`ForceSecureBootScheme`).
- As for the user part, do you have a patch that can work reliably?

Can we have simultaneous compatibility for x86legacy and e.g. j137?

**Comment by osy** [comment]
I was thinking of adding to https://github.com/acidanthera/RestrictEvents a patch to search and replace the string `apple-coprocessor-version`. I have no started working on it yet. Global signed x86legacy will continue to work as long as the coprocessor version is 0 and hw.target is empty or set to x86legacyap. And personalized x86legacy may work if coprocessor version is T2 and hw.target is set to x86legacyap but idk if that’s a supported case for boot.

**Comment by osy** [comment]
Any idea how to patch just `/usr/lib/libimg4.dylib` in the dyld cache and not all instances of `apple-coprocessor-version`?

**Comment by vit9696** [comment]
> I was thinking of adding to https://github.com/acidanthera/RestrictEvents a patch

Reasonable, but I will have to ask you to step back just a little bit and help me understand a few things, so that I can keep up with your place. We need to be clear about the supported scenarios:

- Installing macOS
- Updating macOS (with OTA)
- Running macOS

These are partly separate, because running updates and installing macOS with sealing touches more areas that are not exposed to normal running. If we agree on that, I believe that we need to define the supported configurations:

1. Medium protection with x86legacy AP identifier(0):
    1. Requires nothing for legacy SMBIOS.
    2. Requires:
        - `HWModelStr` set to `VMM-x86_64` for T2 SMBIOS for updates as done by RestrictEvents (1).
        - `hw.target` may be set to `X86LEGACYAP` without bad consequences via NVRAM.
2. Medium protection with T2 AP identifier:
    1. Not supported for legacy SMBIOS (2.a)
    2. Requires:
        - `HWModelStr` and `hw.target` set to T2 AP identifier, both done at once via NVRAM variable.
        - Patched `_img4_chip_select_effective_ap` in kext via `ForceSecureBootScheme` quirk (3).
        - Patched `_img4_chip_select_effective_ap` in dylib via WIP RestrictEvents addition.
3. Full protection with T2 AP identifier
    1. Not supported for legacy SMBIOS (2.b)
    2. Requires:
        - `HWModelStr` and `hw.target` set to T2 AP identifier, both done at once via NVRAM variable.
        - Patched `_img4_chip_select_effective_ap` in kext via `ForceSecureBootScheme` quirk (3).
        - Patched `_img4_chip_select_effective_ap` in dylib via WIP RestrictEvents addition.

(0) Can this be the default? How would RestrictEvents distinguish 1 and 2/3?
(1) There is an extra patch for ProductType, but I have a feeling that I am mistaken. Is it required for updates?
(2) Do we want to support this? There may be some use for setups that use legacy Mac models and macOS versions.
(3) Does this work as is?

Is this all or do I miss anything? If it is all, I think after we answer these questions, we can work something out.

As for patching, I sometimes patch two consecutive strings to patch only one match, but it is not always reliable.

**Comment by osy** [comment]
So I dug a little deeper into the RestrictEvents patch and I think there could be a better patch @khronokernel

Going by this comment https://github.com/acidanthera/RestrictEvents/blob/master/RestrictEvents/SoftwareUpdate.cpp#L43-L45 (I didn't test Pallas myself) it should suffice for `hw.target` to be set to the right value (`J74AP` for example). Then `HWModelStr` should be set to `hw.target` and `ProductType` can be the (correct) corresponding  `hw.product`. If `hw.target` is empty and `HardwareModel` EFI variable is also empty, then `X86LEGACYAP` will be selected (no fake VMM needed).

@vit9696 responding to your comment given the information above:

We set `BridgeOSHardwareModel` according to SMBIOS model only for T2 models (leave empty for other models). We also need to patch `patchd` to use the right im4m (original post). Then, we have the following cases. 

 1. Medium protection with x86legacy is supported only for SMBIOS set to non-T2 models.
 2. Medium protection for T2 models is supported only for SMBIOS set to T2 models and medium security EFI variable is set.
 3. Full protection for T2 models is supported only for SMBIOS set to T2 model and full security EFI variable is set.

`_img4_chip_select_effective_ap` only needs to be patched in dylib for `patchd`. I don't think patching the kext is required (at least I don't think it affects anything). The per-boot personalization checks only look at the EFI variable.

OTA should also work.

**Comment by osy** [comment]
Also not sure if it matters but `BridgeOSHardwareModel` is lower case and changed to all caps by the code reading it.

**Comment by osy** [comment]
```patch
diff --git a/Library/OcMainLib/OpenCorePlatform.c b/Library/OcMainLib/OpenCorePlatform.c
index 791e5b0f..6374f473 100644
--- a/Library/OcMainLib/OpenCorePlatform.c
+++ b/Library/OcMainLib/OpenCorePlatform.c
@@ -495,6 +495,8 @@ OcPlatformUpdateNvram (
   UINTN        SsnSize;
   CONST  UINT8 *Rom;
   UINTN        RomSize;
+  CONST CHAR8  *BridgeModel;
+  UINTN        BridgeModelSize;
   EFI_GUID     Uuid;
   UINT64       ExFeatures;
   UINT64       ExFeaturesMask;
@@ -510,6 +512,8 @@ OcPlatformUpdateNvram (
     SsnSize        = Config->PlatformInfo.Nvram.SystemSerialNumber.Size - 1;
     Rom            = &Config->PlatformInfo.Nvram.Rom[0];
     RomSize        = sizeof (Config->PlatformInfo.Nvram.Rom);
+    BridgeModel    = NULL; // FIXME: make configurable
+    BridgeModelSize= 0;
     Status = OcAsciiStrToRawGuid (OC_BLOB_GET (&Config->PlatformInfo.Nvram.SystemUuid), &Uuid);
     if (EFI_ERROR (Status)) {
       ZeroMem (&Uuid, sizeof (Uuid));
@@ -525,6 +529,8 @@ OcPlatformUpdateNvram (
     SsnSize        = AsciiStrLen (Ssn);
     Rom            = &MacInfo->Oem.Rom[0];
     RomSize        = OC_OEM_ROM_MAX;
+    BridgeModel    = MacInfo->BridgeModel;
+    BridgeModelSize= AsciiStrLen (BridgeModel);
     CopyGuid (&Uuid, &MacInfo->Oem.SystemUuid);
     ExFeatures     = MacInfo->Smbios.FirmwareFeatures;
     ExFeaturesMask = MacInfo->Smbios.FirmwareFeaturesMask;
@@ -658,6 +664,23 @@ OcPlatformUpdateNvram (
       ));
   }
 
+  if (BridgeModel && BridgeModel[0] != '\0') {
+    // FIXME: Macs convert this to all lowercase first
+    Status = gRT->SetVariable (
+      APPLE_BRIDGE_OS_HARDWARE_MODEL_VARIABLE_NAME,
+      &gAppleVendorVariableGuid,
+      EFI_VARIABLE_BOOTSERVICE_ACCESS | EFI_VARIABLE_RUNTIME_ACCESS,
+      BridgeModelSize,
+      (CHAR8 *) BridgeModel
+      );
+    DEBUG ((
+      EFI_ERROR (Status) ? DEBUG_WARN : DEBUG_INFO,
+      "OC: Setting BridgeOSHardwareModel %a - %r\n",
+      Ssn,
+      Status
+      ));
+  }
+
   //
   // system-id is only visible in BS scope and may be used by EfiBoot
   // in macOS 11.0 to generate x86legacy ApECID from the first 8 bytes.

```

Tested the following change on OC with RestrictEvents disabled, SB enabled, J174 model. I was able to install 12.0 21A5534d over the same build with no issues (previously, it would stop at the im4m verification). I confirmed in the log that it indeed only verifies the installer boot with the global im4m but it does use the personalized im4m after installation.

I did not test OTA scanning and update since I don't have any other builds downloaded currently, if someone else can test this, that would be great.

Also, I think for OC, we should make `BridgeModel` lowercase to match Apple behaviour.

**Comment by vit9696** [comment]
I have a very similar OC patch locally (with configuration support). Yet it is not enough to set hw.target to e.g. J137AP for OTA I think. Updates failed to install for me in this case. Maybe it is enough if when you also patch the dylib. This will need testing.

Hooking syscalls is more reliable than patching the dylib (patchd) I would say. This is why keeping the approach we have now for T2 models as well might be reasonable. But I would like to see the patchd part first to decide. In any case it should be fairly easy to detect hw.target variable value and then either force VMM or patch the dylib.

I thought the NVRAM variable has it in upper case for the original Macs. E.g. the output from MBP is `hw.target: J213AP`.

**Comment by osy** [comment]
They force it to uppercase in the sysctl handler. If you look at the device tree entry for bridge-model it’s lower case. Idk if it makes a difference though.

Do you have the log for when the OTA fails for J137AP? Mine failed on the AppleImg4 check and there was debug output showing that it failed on the chip id manifest because it tried to use the x86legacyap im4m.

**Comment by vit9696** [comment]
> Do you have the log for when the OTA fails for J137AP? Mine failed on the AppleImg4 check and there was debug output showing that it failed on the chip id manifest because it tried to use the x86legacyap im4m.

Unfortunately not, but I think I have very similar memories.

**Comment by osy** [comment]
Hmm then I don’t know why it didn’t work for you. As long as your `ApBoardID` matches the im4m’s BORD property for `OS.dmg.mtree.j137ap.im4m` it shouldn’t hit that error.

**Comment by vit9696** [comment]
Make sure you can update from b7 to b8. There were many changes during the older versions.

**Comment by 1alessandro1** [comment]
> Medium protection with x86legacy is supported only for SMBIOS set to non-T2 models.

@osy 
1. This means that for SMBIOSes like iMac19,1 (non T2) there is no way of obtaining "Full Security" since to enable OTA updates on Monterey one is required to use `x86legacy` and by choosing it on a non-T2 SMBIOS, `ApECID` must be `0`?

2. How does this work on an official mac without a T2 like the iMac19,1? 
  a. How do they obtain OTA updates on Monterey while supporting "Full Security"? 
  b. Do they use a custom ApECID or not? 
  c. Is a T2 required for ApECID?
  d. Or maybe non-T2 machines (basically every iMac before 2020, which seems strange) support only "Medium Security" configurations?

**Comment by osy** [comment]
@1alessandro1 Apple doesn’t support “full security” on non-T2 macs. It worked before because macOS didn’t enforce that the secure boot model == the SMBIOS. Now they do with hw.target so you have to use the RestrictEvents workaround.

For T2 SMBIOS the only thing that’s needed is `hw.target`.

**Comment by osy** [comment]
Here’s a summary so far:

In softwareupdated, Apple servers started checking that `HWModelStr` is board-id or `VMM-x86_64` for legacy Macs `ProductType` and all caps model name + AP for T2 macs `ProductType`. If you used “x86legacy” as your secure boot model, then macOS queried the update server with the board-id with a T2 mac’s `ProductType` and it returns no update.

Once install actually starts and ramrod/patchd loads, it secure boot is enabled, it will load the personalized/global im4m corresponding to hw.target and personalized im4m only if apple-coprocessor-version is T2. Then when it evaluates that the ticket matches the current environment, it uses `ApBoardID` EFI variable to confirm it matches what’s in the ticket. OpenCore sets this variable according to the secure boot model so if that mismatches with the SMBIOS model, it will error.

**Comment by osy** [comment]
I’ve successfully OTA update from beta 7 to beta 8.

**Comment by perez987** [comment]
I've tried to build OC, changing OpenCorePlatform.c as in your post, but it fails. Removing your additions, it compiles fine.
Is there any other file to modify or do I just must change the file OpenCorePlatform.c?
To be tested in a non t2 model (iMac19,1) + x86legacy + RestrictEvents.
Thanks for your work!

**Comment by osy** [comment]
Make sure you have the latest OC revision. If it still doesn’t work post the error.

**Comment by perez987** [comment]
> Make sure you have the latest OC revision. If it still doesn’t work post the error.
I had some typo when copying your code because I have checked it again and this time it has compiled well, no errors.
I will test and comment on the result. Thanks.

**Comment by vit9696** [comment]
Ok, so I changed OpenCore:
- to provide `hw.target` in https://github.com/acidanthera/OpenCorePkg/commit/7cd3db3119a52859f5f5e05627242508725e92f3
- to set matching SMBIOS model based on `Default` in https://github.com/acidanthera/OpenCorePkg/commit/7583455f11ef15d50df4aca49f1d90eff39d5c2f

This should let updates and installations work **without** RestrictEvents.kext on:
- Macs with T2 SMBIOS and `Default` SB model
- Macs with legacy SMBIOS and `Default` SB model

I **very strongly** request to test beta 7 → beta 8 update with these configurations. CC @khronokernel @vandroiy2013 @dhinakg @osy.

I additionally updated RestrictEvents.kext:
- not to include the patches by default as they are not needed in https://github.com/acidanthera/RestrictEvents/commit/f76c77506d1253f1b66e0cd29d4e292a441b38f1
- not to spoof hw.product at all as it is not needed in https://github.com/acidanthera/RestrictEvents/commit/466fab9763e9571832b1f3dd7bd0bf37eb6df4ba

This leaves us in a good state where we need one more patch for RestrictEvents to support full security.

**Comment by nadiaholmquist** [comment]
With these latest commits and `MacPro7,1` SMBIOS and SBM: Default I'm getting
```
00:000 00:000 OC: Failed to find SB model J160
```
followed by OC halting on a critical error.

**Comment by vit9696** [comment]
Thanks for the report, I have already fixed it in https://github.com/acidanthera/OpenCorePkg/commit/355cf005a7594d764c5fde96526fddf8adaeb9b5.

**Comment by nadiaholmquist** [comment]
Can confirm this solves the problem.

**Comment by osy** [comment]
Tested with:
- SMBIOS = J174
- SecureBootModel = `Default`
- ApECID = random value
- No RestrictEvents

Full install of beta 7 successful. OTA update from beta 7 to beta 8 successful.

Btw, is it still recommended that SecureBootModel be set to a value rather than Default?

**Comment by vit9696** [comment]
Great, I would recommend to use the `Default` value. It is unlikely to change its behaviour in the future.

**Comment by vit9696** [comment]
Hmm, wait, did you have anything else patched to allow the use of a random ApECID value?

**Comment by osy** [comment]
Sorry I meant I’ve randomly generated the ecid but it has not changed. Basically it’s not zero.

**Comment by perez987** [comment]
I'm coming late but this is my comment: with 102ede5 commit and @osy changes:
- Monterey can achieve full security if SBM j160 + SMBIOS MacPro7,1 + ApECID + RestrictEvents
- Monterey only achieve medium security if SMB x86legacy + SMBIOS iMac19,1 + ApECID + RestrictEvents.

I'm going to try latest OC and RE commits as per @vit9696 posts.

**Comment by perez987** [comment]
Last OC commit 355cf00 tested:

- SMBIOS = MacPro7,1
- SecureBootModel = Default
- ApECID = non zero
- RestrictEvents commit 466fab9 (used for memory warning in MacPro).

Monterey can update fine to beta 8 and achieve full security.

**Comment by vit9696** [comment]
Hm. Am I right that:

- Medium security with T2 model also works? I.e. ApECID = 0.
- Full security currently exists on paper only as personalised identifiers are not checked (no user patch)?

**Comment by perez987** [comment]
Yes, medium security works with t2 model and ApECID zero. Full security with T2 model and ApECID non zero. Checked.
Full security seems to be enabled without user (@osy) patch and after boot volume being personalized.

**Comment by vit9696** [comment]
Right, so the only question remains is the one defined in the first post: https://github.com/acidanthera/bugtracker/issues/1809#issue-1013523040.

> In patchd, if `apple-coprocessor-version` is not found, then it will always use `OS.dmg.mtree.%@.im4m` instead of `OS.dmg.mtree.%@.%@.im4m` (which has ECID personalization). 

That one means full security is still not working in terms of protection, although the system does boot.

@osy, do you confirm my understanding of the only remaining problem? Do you have a prototype of the userspace patch for RestrictEvents?

**Comment by perez987** [comment]
@vit9696 "That one means full security is still not working in terms of protection, although the system does boot."

Even if nvram 94b73556-2197-4702-82a8-3e1337dafbfb:AppleSecureBootPolicy=%02?

**Comment by vit9696** [comment]
That is what I understand from the issue raised by @osy, I do not have macOS 12 to confirm.

**Comment by 1alessandro1** [comment]
> Monterey only achieve medium security if SMB x86legacy + SMBIOS iMac19,1 + ApECID + RestrictEvents.

@perez987 

1. Do you mean that with legacy SMBIOS (e.g. iMac19,1 non-T2) if you specify a custom ApECID you are not able to install?

2. "Medium security" is the equivalent of specifying only the SecurebootModel, so ApECID must be zero in this setup.

3. Is RestrictEvents still required for legacy SMBIOSes (e.g.non-T2 iMac19,1) even after @vit9696's improvements on OpenCore master?

**Comment by osy** [comment]
It’s a very pedantic problem. Basically for the duration of the first phase of installation, it will not check the personalized ticket. The subsequent phases and normal boot are protected. This is because in normal boot the mtree im4m is checked in other places.

I’ve been thinking about this in terms of the security and idk if it’s a “real problem” we care about. So the attack here would be: Apple stops signing a preinstall OS.dmg due to some vulnerability. That means that TSS stops issuing im4m for OS.img.mtree but since we have the global ticket (aka medium security), it will still work on hackintosh/OC machines.

Now the question here is: do we consider that a real threat? In order to boot into the install preboot you need to first boot into macOS and trigger an OTA update. Additionally you need to have the install assistant write OS.dmg and other files to the update partition. All that requires admin privileges.

But if you’re booted into macOS and have admin privileges, why do you even have to do this attack on preboot? What can you possibly do in preboot that you can’t do as admin in macOS?

So even though theoretically there is a security issue with only having medium boot in the first state of the install, I’m not sure there’s a security issue big enough to spend time fixing especially considering the patch to libimg4.dylib isn’t obvious and could be ugly.

**Comment by vit9696** [comment]
Well, to fix this we can provide a patch with `apple-coprocessor-version\0found co-processor version:` to target libimg4.dylib exclusively, but I mainly agree with that judgement. Closing.

**Comment by perez987** [comment]
> 1. Do you mean that with legacy SMBIOS (e.g. iMac19,1 non-T2) if you specify a custom ApECID you are not able to install/update or both?
> 2. "Medium security" is the equivalent of specifying only the SecurebootModel, so ApECID must be zero in this setup.
> 3. Is RestrictEvents still required to:
>    * Enable OTA
>    * Enable installs with SecurebootModel set to "Default" with custom ApECID (nonzero)
> 
> all of this on legacy SMBIOSes (e.g.non-T2 iMac19,1) even after @vit9696's improvements on OpenCore master?

After @vit9696's improvements on OpenCore master 19aea59 and previous builds.

**Secure Boot**
- SMBIOS non T2 (iMac19,1) + SMB=Default + ApECID non zero + with or without RestrictEvents: only medium security.
- SMBIOS T2 model (MacPro7,1) + SMB=Default + ApECID non zero + with or without RestrictEvents: full security.
This can be as expected in real Macs, Macs without T2 only achieve medium security, is it right?

**OTA**
- SMBIOS non T2 (iMac19,1) + no RestrictEvents: OTA enabled.
- SMBIOS T2 model (MacPro7,1) + no RestrictEvents: OTA enabled.
- SMBIOS T2 model (MacPro7,1) + old RestrictEvents 2430ed0 (added macOS 12 software update support with any Mac model): OTA enabled.

I've not tried full install, only OTA update.

**Comment by zearp** [comment]
Sorry to post in this old issue but don't know where else to post this question and don't think opening a new issue is warranted. 

Would it be possible to have the "sbvmm" patch thats part of RestrictEvents only showe OTA updates for the macOS versions the configured SMBIOS supports? Or maybe a manual option to configure a maximum version? The Mac minin from 2018 does not support Tahoe and on the real thing that update will not show.

I'm trying to wrap up my project in a nice way where it will keep showing OTA updates for Sequoia but not offer the Tahoe update. My NUCs have the same cpu as some Mac mini 2018 models but the NUCs lack the T2 chip. So no OTA will show unless I use the "sbvmm" patch which just offers any updates available for download including incompatible versions of macOS.

I remember there used to be a setting to stop major upgrade -- on Catalina ```softwareupdate --ignore "Monterey"``` worked great -- but Apple removed it and it now can only be done using MDM which isn't ideal. Hoping there is a way to do this so it doesn't try to automatically update when I forget to disable auto updates or accidentally click on it.

Sorry and I hope there is something we can do to wrap my little project up nicely.
