### ISSUE TITLE
12. There is a problem with the Bluetooth driver under the system

### ISSUE THREAD

**Issue by mjs520** [acidanthera/bugtracker#1811]
USB Bluetooth model：

[Tested PatchRAM devices : [0a5c:21e8] Bluetooth USB Dongle (20702A1) ]

System version：Monterey beta8

Existing problems：This USB dongle has been tested. Bluetooth can't be turned on again by manually clicking off under 12beta 8

Final expectation：I hope the driver can be updated early to fix this Bluetooth problem. Thank you

**Comment by stevezhengshiqi** [comment]
It's a known issue mentioned in https://github.com/acidanthera/BrcmPatchRAM/pull/12#issue-668963999

> Turning off Bluetooth breaks Bluetooth (you cannot turn it back on). More research is needed to fix this.

**Comment by wangzikang-debug** [comment]
哥们你在想什么，这问题一直存在，作者都说了，

**Comment by mjs520** [comment]
> It's a known issue mentioned in [acidanthera/BrcmPatchRAM#12 (comment)](https://github.com/acidanthera/BrcmPatchRAM/pull/12#issue-668963999)
> 
> > Turning off Bluetooth breaks Bluetooth (you cannot turn it back on). More research is needed to fix this.
> 
> Similiar Issue: #1771

Does the author say that this problem can be solved or that he doesn't intend to solve it

**Comment by vit9696** [comment]
Yes, basically help wanted on this.
