### ISSUE TITLE
Failed to detect supported SuperIO chip (VirtualSMC error)

### ISSUE THREAD

**Issue by Cuacon2004** [acidanthera/bugtracker#1816]
i'm using the latest version of Opencore 0.7.4 and VirtualSMC 1.2.7( include SMCProcesssor and SMCSuperIO)
but i can't monitoring my CPU fans using mac fans control or iStat menus. I tried to remove SMCSuperIO but it's does work. I saw "Failed to detect supported SuperIO chip" error when booting into macOS. I tried both with and without SuperIO.kext but still failed. Please help me, i just know how to add and install kext but i don't know how to patch it.
I'm using HP 280 G3 MT (Core i5 7500)
MacOS Big Sur 11.6
this is my specs: https://support.hp.com/vn-en/document/c05519863

**Comment by vit9696** [comment]
You will need to implement support for your Super I/O chip in VSMC. This will likely require programming skills.
