### ISSUE TITLE
Feature request: OpenCorePkg/Utilities/macrecovery: verify downloaded Internet recoveryOS images

### ISSUE THREAD

**Issue by jspraul** [acidanthera/bugtracker#1817]
Would you accept a pull request to implement verification of downloaded recoveryOS images?

The baby step of using https was closed by the submitter, though no one brought up the potential of a MITM on an unencrypted connection:
 https://github.com/acidanthera/OpenCorePkg/pull/255

I am no great Python guru but I may be able to incorporate the following into verifying the download with the chunklist, and also verifying the signature of the chunklist (though this requires a public key dumped from Apple EFI):
 https://gist.github.com/MCJack123/943eaca762730ca4b7ae460b731b68e7#gistcomment-3061078
 https://github.com/sadponyguerillaboy/Apple-Chunklist-Verification-Creation-Toolkit

This is not a high priority so I may not have time to submit anything any time soon.

**Comment by dhinakg** [comment]
Here is a WIP implementation that I never got around to finishing: https://gist.github.com/dhinakg/cbe30edf31ddc153fd0b0c0570c9b041

It verifies the checksum but does not verify the signature. I will see if I can add that later, or someone else can implement it.

**Comment by jspraul** [comment]
👍
