### ISSUE TITLE
In pre-boot only, USB 2.0 devices stop working if USB 3.0 device plugged into FL1100 USB chipset

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1820]
Hi,
I was experimenting with scanpolicy to not scan and show the windows entry in opencanopy, docs explains well what enable/disable for scanpolicy, but while I was experimenting I found something odd.

I set back scanpolicy to 0 and these are the results.

scanpolicy: 0
mac os usb installer (it's a catalina installer) is plugged into the usb port
Result1: showpicker=false, cannot show opencanopy with '0' key (<-- I suspect keyboard doesn't work)
Result2: showpicker=true, mouse and keyboard not working in opencanopy
Log:
[scan0usb.txt](https://github.com/acidanthera/bugtracker/files/7335779/scan0usb.txt)

scanpolicy: 0
mac os usb installer (it's a catalina installer) not plugged into the usb port
Result: all ok, mouse and keyboard work as expected
Log:
[scan0.txt](https://github.com/acidanthera/bugtracker/files/7335786/scan0.txt)

I compared the 2 logs and cannot find any difference.
For the mouse in opencanopy I'm using UsbMouseDxe, strange thing is that the driver is reported as loaded/connected in the log.

There's no trace of the usb installer in both cases in opencanopy, but I suspect this is due to MinDate/MinVersion set to 0 (allowing only big sur and up), but this shouldn't prevent keyboard/mouse to work.

I noticed delay with the usb plugged in in booting, the usb controller is FL1100.

Edit: removed the uuid part, pointed to docs by Mike, thanks.

Thank you

**Comment by 82ghost82** [comment]
Hi Mike!


> send a log with the usb installer plugged in and with a ScanPolicy value which makes the keyboard work

It seems I'm not able to make the keyboard to work with a scanpolicy value that should not scan for usb.
Scanpolicy: integer 983299, like the sample.plist, it should not scan usb, nor hfs, or am I wrong?
When booted with the usb pendrive catalina installer, there's a delay, pressing zero to show boot picker, no bootpicker is shown --> keyboard doesn't work.

Anyway, this is the config.plist:
[config.txt](https://github.com/acidanthera/bugtracker/files/7354629/config.txt)

**Comment by mikebeaton** [comment]
@82ghost82 - Do you have any value of ScanPolicy where the USB drive may be plugged in and kb and mouse still work? At the moment I understand you have said that if USB is plugged in, then kb and mouse will not workif ScanPolicy is 0 or 983299.

And do you have any other USB drive where kb and mouse do work when it is plugged in - or is it any USB drive?

**Comment by 82ghost82** [comment]
It's a "microsoft wireless 800 desktop" kb + mouse + dongle, no laptop.
Attaching ioreg for hardware specs.
[Ioregistry.zip](https://github.com/acidanthera/bugtracker/files/7357069/Ioregistry.zip)

**Comment by mikebeaton** [comment]
@82ghost82 - if you can find any OC setting where the kb and mouse work even with the Catalina installer plugged in then that would be useful. In the meantime, I do wonder why the FS of that installer is not showing up in OC at all - if you can find any way to make it show, i.e. presumably 9 filesystems instead of 8 in your case, that would also be helpful.
