### ISSUE TITLE
Again no ota updates in system panel in Monterey beta 10 --> RC

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1827]
Hi! It seems apple changed again something with the ota updates?
Running Monterey in qemu as a test system, vmm flag enabled.

smbios: imacpro1,1
csr-active-config: 7w8AAA== (0xef0f0000) --> I have an unsealed volume, this value shouldn't prevent ota updates to show (Apple internal disabled)
securebootmodel: disabled

From beta 9 to 10, beta 8 to 9, beta 7 to 8 (with oc updated accordingly) all ok, ota updates showed in system preference panel (full installer).

RC isn't showing up.

**Comment by telepati** [comment]
It's working for me; Btw I never get this type of error. It always worked for me with this setup. I never changed my setup since beta 1.

SMBIOS: 19,1
csr-active-config: 00000000
SecurBootModel: Default

Z390 9900K UHD630

**Comment by khronokernel** [comment]
Apple removed VMM from the Pallas Catalog temporarily, should be restored in the coming days. Either use a non-T2 SMBIOS or set SecureBootModel with a T2 ID and ensure VMM is not exposed

Nothing to be done on our end, wait for Apple to fix this

**Comment by 82ghost82** [comment]
@ofawx 
I'm installing 12.0.1, I propose to wait for the next 12.1 release and see what happens.
khronokernel suggests to patch VMM and use T2 id.

Since SecureBootModel=x86legacy with ApECID=0 sets the T2 id to the first 8 bytes of the system id we should be ok.
_On macOS 11 and newer the dedicated x86legacy model always uses ApECID. When this configuration setting is left as 0 first 8 bytes of system-id variable are used instead._

I propose also to apply your patches (VMM-->XXX and kern.hv_vmm_present-->kern.hv_xxx_present).

I will not unseal the volume and so I wont install any nvidia driver, just to see what happens.

If nothing comes up in software update I think this will need to be reopened, and or discussed again.
