### ISSUE TITLE
FocalTechPS/2 VoodooPS2 only supports single finger.

### ISSUE THREAD

**Issue by Remilia-NULL** [acidanthera/bugtracker#1829]
System:

1. Asus FL5900V
2. FocalTech touchpad:FLT0101
3. MacOS Big Sur(11.6) 
4. VoodooPS2 2.2.6

PS2TouchPad ldentify with PS2Mouse

IORegistryExplorer
![Xnip2021-10-21_12-58-23](https://user-images.githubusercontent.com/34256856/138214288-70c693d3-1720-49b7-abc2-231c210160a8.jpg)
![Xnip2021-10-21_12-58-54](https://user-images.githubusercontent.com/34256856/138214295-a10d23fc-5415-4a6c-a48d-3a08a6435f4c.jpg)

Windows device manager
![22](https://user-images.githubusercontent.com/34256856/138214526-4e9e488f-9edc-426e-b66c-1d77e1ba4ca9.png)
![111](https://user-images.githubusercontent.com/34256856/138214531-f26bbdff-4ace-41d6-b3a7-2206e415c09b.png)

In linux kernel have support:
[https://github.com/torvalds/linux/blob/master/drivers/input/mouse/focaltech.c](url)

**Comment by nishp77** [comment]
Anyone that could guide me to the source of it?
