### ISSUE TITLE
Monterey: Unlock with AppleWach and bluetoothd crash

### ISSUE THREAD

**Issue by anonymous-writer** [acidanthera/bugtracker#1833]
I noticed that Unlock with Apple Watch does not work under Monterey. Same EFI under BigSur no problem with Unlock.

In the console I can see that the bluetoothd crashes after every sleep. Therefore my guess that it is because of this crashes.
The report says something about :"BT XPC PreTimeout simulated crash". What gave me the idea that it is because of the CpuTscSync.kext.

I would be interested in if other users also have such crashes. My processor i7-7500U

[bluetoothd-2021-10-24-001245.txt](https://github.com/acidanthera/bugtracker/files/7411267/bluetoothd-2021-10-24-001245.txt)
<img width="1061" alt="Bildschirmfoto 2021-10-25 um 16 39 36" src="https://user-images.githubusercontent.com/35840715/138716559-90f4a707-b554-4adc-b515-a2bf7a958ed3.png">

.

**Comment by m4rkv5** [comment]
I installed an original BCM943602CDP (BCM_20703A2 BT4.2 iMac 18,2) and bluetoothd is not working after sleep with cpu load 100%. Disabling bluetooth before sleep and enabling after sleep with BetterTouchTool fixes everything except unlock with Apple Watch. Disabling and enabling bluetooth from control center after login also fixes bluetooth issues until the next sleep.

ASUS ROG STRIX X299-E GAMING
i9-7900X
BCM34602 0x43BA BCM_20703A2
Opencore 0.7.9
Monterey 12.4
