### ISSUE TITLE
[Question] How to implement AppleALC based on a given codec & verb in alsa-project

### ISSUE THREAD

**Issue by SukkaW** [acidanthera/bugtracker#1835]
My Laptop (LEGION Y9000X 2020) has its speakers connected to an amplifier (TAS2770), which requires special verbs to start them up.

Recently under some geek users' investigation, the verb used by Lenovo OEM Driver has been found and implemented in the `alsa-project` ([patch](https://github.com/Whissi/linux-stable/commit/59a9814c84401db9f96022226fec9675120b4251)). The codec and verb can be also applied to Linux with Kernel Module (placing a conf file under `/etc/modprobe.d/` directory).

So now I have the codec and verb command, is it possible to add it to AppleALC, or I have to use `alcverbs=1` (or correlated device properties) and `hda-verb` in order to apply custom verbs?

**Comment by roddy20** [comment]
you may use alc-verb tool to test if your verb command works Ok, then add it to ConfigData field in the Info.plist

**Comment by 1alessandro1** [comment]
@roddy20 May someone provide some clear documentation in the AppleALC wiki, so that everyone has a clear reference on all the quirks and features one needs to be aware of and understand?
