### ISSUE TITLE
Assets missing on OC 0.7.5

### ISSUE THREAD

**Issue by fmunteanu** [acidanthera/bugtracker#1839]
The RELEASE and DEBUG zip files are missing from [0.7.5 release](https://github.com/acidanthera/OpenCorePkg/releases/tag/0.7.5).

**Comment by fmunteanu** [comment]
I'be builded successfully the zip files, is probably something into CI/CP pipeline that skipped building the assets:

```sh
~$ git clone -b 0.7.5 --single-branch https://github.com/acidanthera/OpenCorePkg.git
~$ cd OpenCorePkg
~$ IGNORE_MTOC_VERSION=1 sh build_oc.tool

~$ ls -lh Binaries
total 16896
-rw-r--r--  1 floren  staff   4.6M  1 Nov 15:02 OpenCore-0.7.5-DEBUG.zip
-rw-r--r--  1 floren  staff   3.6M  1 Nov 15:03 OpenCore-0.7.5-RELEASE.zip
```

**Comment by vit9696** [comment]
Yes, pretty strange. At a glance it feels like a bug on GitHub Actions end.

**Comment by vit9696** [comment]
Resolved by recreating the release.
