### ISSUE TITLE
Kernel Block can't be used with OpenCore in Monterey 12.0.1

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#1840]
First of all, Motherboard model is Asus Z490-F. This motherboard doesn't have any bluetooth device. Anyways, in Monterey 12.0.1, these kexts "BroadcomBluetooth20703USBTransport.kext" and "BroadcomBluetoothHostControllerUSBTransport.kext" always are loaded by system.

![image](https://user-images.githubusercontent.com/9614101/139829947-87e196d9-a803-4e3f-86a4-6a884ecae00c.png)

The problem is, after wake from sleep system reboot because Kernel Panic about bluetooth (log is attached). In Big sur, sleep and wake is normal.

Then i try to disable "BroadcomBluetooth20703USBTransport.kext" and "BroadcomBluetoothHostControllerUSBTransport.kext" from config.plist with this line,
![image](https://user-images.githubusercontent.com/9614101/139830141-4c969804-4a1a-4624-8901-9a888b70bb54.png)

But those kext are still loaded.

Can we block this kexts with OpenCore, or Block Kext is fail in Monterey??? Sorry for bad english
[Panic.ips.zip](https://github.com/acidanthera/bugtracker/files/7459828/Panic.ips.zip)
[Anups-iMac-01.ioreg.zip](https://github.com/acidanthera/bugtracker/files/7459845/Anups-iMac-01.ioreg.zip)

**Comment by TheHackGuy** [comment]
I can confirm this is an issue. Kernel/block doesn't seem to work anymore. I've also tried that for fixing this issue

I've reinstalled Monterey on a sata ssd now (previously NVME) and used latest bluetoolfixup. Then the issue seems to be gone. But I am not sure if it's the sata ssd or bluetoolfixup that fixed it.

**Comment by andreszerocross** [comment]
> I can confirm this is an issue. Kernel/block doesn't seem to work anymore. I've also tried that for fixing this issue but the kexts just keep loading.
> 
> Unrelated to kernel/block not working: I've reinstalled Monterey on a sata ssd now (previously NVME) and used latest bluetoolfixup. Then the issue of bluetoothd crashing seems to be gone (no crash logs anymore in console app). But I am not sure if it's the sata ssd or bluetoolfixup that fixed it.

But your Hackintosh device has Bluetooth Device?

**Comment by TheHackGuy** [comment]
> > I can confirm this is an issue. Kernel/block doesn't seem to work anymore. I've also tried that for fixing this issue but the kexts just keep loading.
> > 
> > Unrelated to kernel/block not working: I've reinstalled Monterey on a sata ssd now (previously NVME) and used latest bluetoolfixup. Then the issue of bluetoothd crashing seems to be gone (no crash logs anymore in console app). But I am not sure if it's the sata ssd or bluetoolfixup that fixed it.
> 
> But your Hackintosh device has Bluetooth Device?

Nope. I don't have any bluetooth device.


But I tested it with my intel ac8260nwg and then the issue (bluetoothd crashes) is gone.

**Comment by khronokernel** [comment]
Duplicate:
* https://github.com/acidanthera/bugtracker/issues/497

**Comment by TheHackGuy** [comment]
@khronokernel 
Do you know any other way that we could solve bluetoothd crashing?

**Comment by andreszerocross** [comment]
> > > I can confirm this is an issue. Kernel/block doesn't seem to work anymore. I've also tried that for fixing this issue but the kexts just keep loading.
> > > Unrelated to kernel/block not working: I've reinstalled Monterey on a sata ssd now (previously NVME) and used latest bluetoolfixup. Then the issue of bluetoothd crashing seems to be gone (no crash logs anymore in console app). But I am not sure if it's the sata ssd or bluetoolfixup that fixed it.
> > 
> > 
> > But your Hackintosh device has Bluetooth Device?
> 
> Nope. I don't have any bluetooth device.
> 
> But I tested it with my intel ac8260nwg and then the issue (bluetoothd crashes) is gone.


Intel AC 8260NG has Bluetooth device, so seems bluetoolfixup,kext will fix it. But for device with no bluetooth then can cause KP after wake
