### ISSUE TITLE
VoodooPS2: SSDT to add right-delete behavior to the Del key (= map Del key as macOS ⌘+⌫) to move to trash in Finder

### ISSUE THREAD

**Issue by LeeBinder** [acidanthera/bugtracker#1843]
Hi VoodooPS2 dev team. Thank you for the https://github.com/acidanthera/VoodooPS2/tree/master/Docs/ACPI section.

Not all apps in macOS acknowledge the Del key. Finder is one of them. The mandatory work-around is to use ⌘+⌫ to move item(s) to trash.

Rather than adding functionality to that key in macOS by tweaking prefs or using a tool like Karabiner Elements or XtraFinder (no Monterey support [yet?]), it would be more efficient to have that solved on SSDT level, system wide.

Does any of you know the AML code for such a SSDT and can either share it here, or add that SSDT to the ACPI section?

**Comment by Ab2774** [comment]
https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/blob/264dce97f542c775a84a289e3b5f74f65cbc2fac/ACPI/SSDT-PS2-Map.dsl#L75

**Comment by LeeBinder** [comment]
Thank you @Ab2774 for the precise pointer - getting closer but not fully there: `"e053=0e",  // Delete=Backspace` allows Del (= right delete) to file and folder LABELS of finder items - but not removing the actual item by highlighting it then hit the Del key. I guess what needs to be know is the ACPI value for Apple's ⌘+⌫

**Comment by Ab2774** [comment]
> Thank you @Ab2774 for the precise pointer - getting closer but not fully there: `"e053=0e", // Delete=Backspace` allows Del (= right delete) to the text of file and folder LABELS of finder items - but not removing the actual item by highlighting it then hit the Del key. I guess what needs to be know for full functionality is the ACPI value for Apple's ⌘+⌫

I think a new code needs to be introduced for that purpose, at the moment, feel free to this ACPI code, I simply highlight what I want to delete and I press ⌘+⌫ to delete them

**Comment by LeeBinder** [comment]
I see. Accdg. to https://manytricks.com/keycodes:

	Keys:		⌘⌫	
	Unicode:		127 / 0x7f
	Key Code:	51 / 0x33
	Modifiers:	1048848 / 0x100110 ⓘ 

I wonder how that translates into the appropriate ACPI value

When I press the Del key (ACPI value e053):

	Key:		⌦
	Unicode:		63272 / 0xf728
	Key Code:	117 / 0x75
	Modifiers:	8388864 / 0x800100 ⓘ

Do you know how/ where I can convert?

**Comment by Ab2774** [comment]
Unfortunately, I don't, I used https://github.com/acidanthera/VoodooPS2/blob/master/VoodooPS2Keyboard/ApplePS2ToADBMap.h to remap my Delete key as Backspace.
You can try by replacing e053=51, good luck!

**Comment by singhalrishi27** [comment]
yeah I would this too if I can delete items without using option command backspace

**Comment by vit9696** [comment]
The issue is, ⌘+⌫ is two codes, and currently VoodooPS2 does not let you map two codes. At least from what I know, maybe @usr-sse2, @zhen-zen have some broader info. Allowing to map one key to two might be a feature that we could support in the future, but I do not think anyone would work on it in the nearest future. You can contribute this on your own of course.

**Comment by LeeBinder** [comment]
@vit9696 OK gotcha. I guess apps like Karabiner Elements, XtraFinder and the ancient PresButan emulate execution of ⌘+⌫ when Del is pressed.

**Comment by usr-sse2** [comment]
PS/2 driver is definitely a wrong place to do this. Imagine you connect a USB or Bluetooth keyboard, then Delete key on built-in and external keyboards will function differently.

**Comment by LeeBinder** [comment]
@usr-sse2 LOL I hope you can bear my candid humor here: that already happens anyway even w/o such extra SSDT .. ;)

**Comment by vit9696** [comment]
@LeeBinder do you understand that whatever you write in your SSDT to control the keyboard is actually handled by the PS2 driver? This is what @usr-sse2 talks about.

**Comment by LeeBinder** [comment]
OK, I understand.
