### ISSUE TITLE
OpenCanopy issue: Radeon RX 580, failing to init due to font

### ISSUE THREAD

**Issue by david-pcas** [acidanthera/bugtracker#1844]
OpenCanopy is failing to initialize on the Radeon RX 580 with UIScale set to 1 with error log: 
```
00:000 00:000 OCUI: Font has height 11 instead of 10
00:016 00:016 OCUI: Font init failed
00:032 00:015 OC: External interface failure, fallback to builtin - Unsupported
```

Changing the UIScale to 02 allows OpenCanopy to launch, however the icons are too large for the standard 1920x1080. 

When booting with the Intel UHD630, it works with UIScale on 1 or 2. 
When booting with the RX 580, it only works with UIScale on 2, 1 falls back to text mode. 

All icons and fonts have been pulled directly from the OcBinaryData repo (https://github.com/acidanthera/OcBinaryData)

No other configuration settings alleviate the issue.  
I'm running the latest public release of OpenCore (0.7.5)

If there is any other troubleshooting I can do to help test, please let me know.

**Comment by vit9696** [comment]
They were not pulled from there, at least not recently. Your font file or your OpenCanopy driver is incorrect.
