### ISSUE TITLE
VoodooSMC: bundle dependent kexts in Plugins subfolder

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#1845]
Like it done VoodooPS2.

**Comment by nms42** [comment]
Oops! Like it done in VoodooPS2.

**Comment by vit9696** [comment]
Hmmm, not a too bad idea, but I would rather opt not to, since many of these plugins are optional, and I am not a fan of deleting them.

**Comment by nms42** [comment]
Enable/disable in config.plist is not enough|/convenient?

**Comment by vit9696** [comment]
Yeah, since they add extra weight, and since the paths are more complicated.
