### ISSUE TITLE
IntelBluetoothInjector.kext causing prolonged boot times and missing internal hard drives after Monterey update.

### ISSUE THREAD

**Issue by dmcnaugh15** [acidanthera/bugtracker#1847]
I believe there is a bug in the IntelBluetoothInjector.kext.

After updating to Monterey from Big Sur, I was noticing extremely long boot times and macOS didn't recognize any of my internal drives or USB drives.  I posted it to Insanelymac, and someone recommended disabling the kext.  I did and both problems resolved.  Others have had the same experience.

Insanelymac thread on the topic: 
https://www.insanelymac.com/forum/topic/349510-missing-internal-drives-and-extremely-long-boot-times-after-monterey-upgrade-help/?tab=comments#comment-2771229

Link to my EFI with debug logs: 
http://DAMDAS.myqnapcloud.com:8082/share.cgi?ssid=cebeef9f960240328f7db0f5196af5c1 

My system specs are as follows:
- Motherboard: ASUS ROG MAXIMUS XI HERO (WI-FI) - chipset Z390
- CPU: Intel(R) Core(TM) i9-9900K
- Graphics card: Radeon RX 580 Series
- RAM: 32 Gb

**Comment by zfdx123** [comment]
It is recommended that you read the Openintelwireless project documentation

**Comment by vit9696** [comment]
Intel Bluetooth is courtesy of https://github.com/OpenIntelWireless.

**Comment by dmcnaugh15** [comment]
Thank u.
