### ISSUE TITLE
build_oc.tool does not support Xcode installations with spaces

### ISSUE THREAD

**Issue by alyxxxx** [acidanthera/bugtracker#1848]
Tried to run build_oc.tool, and ran into an issue because I have multiple versions of Xcode installed and the version of Xcode selected with `xcode-select` is located at `/Applications/Xcode 13.1.app`. Seems that it doesn't like the space in the path because it said `/Applications/Xcode: No such file or directory`. In the meantime I'll just remove the space but it seems like something that could be fixed pretty easily. Cheers
![Screen Shot 2021-11-05 at 23 21 47](https://user-images.githubusercontent.com/38449053/140596280-a375f84c-788e-4389-b069-f57eaa0afbbb.png)
!

**Comment by vit9696** [comment]
It is not `build_oc.tool` but EDK II, i.e. Intel. You should write this to https://bugzilla.tianocore.org.

**Comment by alyxxxx** [comment]
I appreciate it, thanks :)
