### ISSUE TITLE
OpenCore: Kernel panic on Fujitsu lifebook T732

### ISSUE THREAD

**Issue by nsby494** [acidanthera/bugtracker#1849]
I have a system based on Fujitsu T732. I have been trying to use OpenCore for two years. Never succeeded, tried many different settings and combinations, but I may be wrong. I am posting here in case it is an OpenCore error, and I hope to get your help,thanks!

Attached are my config.plist and the stack trace from the panic.

![WechatIMG2](https://user-images.githubusercontent.com/80743675/140646700-a932ab67-3bdc-4887-9e96-8427a5a96f0e.jpeg)
[config.plist-oc7.5.zip](https://github.com/acidanthera/bugtracker/files/7492301/config.plist-oc7.5.zip)
[opencore-2021-11-07-124254.txt](https://github.com/acidanthera/bugtracker/files/7492320/opencore-2021-11-07-124254.txt)

![WechatIMG1](https://user-images.githubusercontent.com/80743675/140646867-5493e4c6-8eba-4679-a294-919c54dfa3d6.jpeg)
[memmap_pre_1.txt](https://github.com/acidanthera/bugtracker/files/7492322/memmap_pre_1.txt)
[memmap_post_1.txt](https://github.com/acidanthera/bugtracker/files/7492324/memmap_post_1.txt)

![WechatIMG3](https://user-images.githubusercontent.com/80743675/140646895-106e4aa6-5c47-450a-8c60-995fc726c76f.jpeg)
[log_1.txt](https://github.com/acidanthera/bugtracker/files/7492333/log_1.txt)
[log_2.txt](https://github.com/acidanthera/bugtracker/files/7492336/log_2.txt)

**Comment by vit9696** [comment]
This looks suspicious. Do you use Lilu 1.5.7 or 1.5.6? If you use 1.5.7, could you try 1.5.6 (https://github.com/acidanthera/Lilu/releases/tag/1.5.6) and show the panic you get?

**Comment by vit9696** [comment]
As for Booter quirks, for this machine it is most likely this, since MAT is unsupported:

<img width="596" alt="Screenshot 2021-11-07 at 19 35 30" src="https://user-images.githubusercontent.com/4348897/140653612-793cbab5-3185-4f18-8ceb-9c02884cda41.png">

**Comment by nsby494** [comment]
> 至于引导程序的怪癖，对于这台机器，很可能是这样，因为 MAT 不受支持：
> 
> <img alt="截图 2021-11-07 at 19 35 30" width="596" src="https://user-images.githubusercontent.com/4348897/140653612-793cbab5-3185-4f18-8ceb-9c02884cda41.png">

I changed it with reference to the settings in the picture, and replaced it with Lilu 1.5.6 (lilu 1.5.7 was used above), and now I am stuck in [EB].

![2021-11-8](https://user-images.githubusercontent.com/80743675/140668220-8b0bf936-1708-4b0b-b1f2-2e65773689ac.jpeg)
[opencore-2021-11-08-002114.txt](https://github.com/acidanthera/bugtracker/files/7493512/opencore-2021-11-08-002114.txt)

**Comment by vit9696** [comment]
Interesting, well, try to identify the quirk that broke it and report here.

**Comment by nsby494** [comment]
lilu 1.5.8 version did not solve my problem on T732. I tried the above three versions of lilu, and I posted the log and the photo at the time of the stop for your review. Hope this result is not caused by my negligence. If there is anything that needs my cooperation, I will submit a test report as soon as possible.
![截屏2021-11-12 16 54 11](https://user-images.githubusercontent.com/80743675/141448356-ee85faf4-461a-415c-beb0-31a860055152.png)
A)
![WechatIMG6](https://user-images.githubusercontent.com/80743675/141448388-78ead84b-2cf8-4109-8a21-31f0e7655bc6.jpeg)
[opencore-2021-11-12-081842.txt](https://github.com/acidanthera/bugtracker/files/7526650/opencore-2021-11-12-081842.txt)
B)
![WechatIMG7](https://user-images.githubusercontent.com/80743675/141448459-e7ad2269-f1a3-43be-a1d7-17ee7d6331ff.jpeg)
[opencore-2021-11-12-082705.txt](https://github.com/acidanthera/bugtracker/files/7526655/opencore-2021-11-12-082705.txt)
C)
[opencore-2021-11-12-085202.txt](https://github.com/acidanthera/bugtracker/files/7526662/opencore-2021-11-12-085202.txt)

**Comment by vit9696** [comment]
The latest panic looks like you added wrong ACPI tables. I.e. their contents are incorrect.

**Comment by nsby494** [comment]
I reorganized the ACPI tables and tried again, but panic still appeared. I will upload the log and photos for your review.

Lilu-Fix slotted panic crash
![WechatIMG1](https://user-images.githubusercontent.com/80743675/141669068-6a0c547b-e0c6-4e92-8cc4-629dfb859a7d.jpeg)
[opencore-2021-11-14-051244.txt](https://github.com/acidanthera/bugtracker/files/7533239/opencore-2021-11-14-051244.txt)

Lilu-alder-lake-cpu and Lilu-Bump version
[opencore-2021-11-14-052243.txt](https://github.com/acidanthera/bugtracker/files/7533245/opencore-2021-11-14-052243.txt)
[opencore-2021-11-14-052736.txt](https://github.com/acidanthera/bugtracker/files/7533246/opencore-2021-11-14-052736.txt)

**Comment by vit9696** [comment]
As for Lilu, please always use the latest master. Could you upload the kernel? It is in /System/Libraries/Kernels/kernel. This panic looks really strange, and it also the exact same panic you had in the beginning.

**Comment by nsby494** [comment]
My current T732 uses the chameleon to guide the installation of Catalina 10.15.6 and Mojave 10.14. But I am currently using a newly made U disk to install, when I click the installation drive letter of the U disk, the panic appears. The kernel you mentioned cannot be found on the USB flash drive.

**Comment by vit9696** [comment]
Check /System/Libraries/Prelinkedkernels directory, there can be immutablekernel or prelinkedkernel file there.

**Comment by nsby494** [comment]
I extracted the following two kernel files from basesystem.dmg on the USB flash drive. I don't know if you want them. Please find out why I can't install it. Thanks！
/Volumes/Install macOS Catalina/Install macOS Catalina.app/Contents/SharedSupport/BaseSystem.dmg
/Volumes/macOS Base System/System/Library/PrelinkedKernels/
[prelinkedkernel.zip](https://github.com/acidanthera/bugtracker/files/7533505/prelinkedkernel.zip)
[immutablekernel.zip](https://github.com/acidanthera/bugtracker/files/7533507/immutablekernel.zip)

**Comment by vit9696** [comment]
Yes, this is the right file, but unfortunately not much I can say even after looking inside. The system crashes when trying to execute code from 0x0 pointer when handling an interrupt. R13 register contains `scdatas` address, so I can reason this is somewhat near auxiliary cpu core initialisation. However, this is pretty much all yet I can tell from your panic log.

My main guess would be some ACPI issue or maybe a memory corruption of some kind. Is the behaviour any different on newer macOS versions? Does the system boot with `cpus=1` in boot-args? Even if it does not, is the panic log any different?

All in all, the issue does not feel like a bug in OC or kexts. Rather something tricky configuration/hardware-wise. For this reason I am closing this, but feel free to reply with more details. I will let you know if I have more ideas.
