### ISSUE TITLE
After booting up and logging in, MacOS freezes after a few seconds

### ISSUE THREAD

**Issue by superLei** [acidanthera/bugtracker#1850]
## Versions:
MacOS: 10.15.7
OpenCore: 0.7.3
Lilu: 1.5.7
WhateverGreen: 1.5.5
VirtualSMC: 1.2.7

## Issue:
After booting up and logging in, it freezes after a few seconds

## Logs:

panic(cpu 3 caller 0xffffff800e43baa0): "Spinlock acquisition timed out: lock=0xffffff8017889000, lock owner thread=0x48, current_thread: 0xffffff8028800a40, lock owner active on CPU 0xffffffff, current owner: 0x48, time: 115064247951"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.2/osfmk/i386/locks_i386.c:501
Backtrace (CPU 3), Frame : Return Address
0xffffff914f12b8e0 : 0xffffff800e31a65d mach_kernel : _handle_debugger_trap + 0x49d
0xffffff914f12b930 : 0xffffff800e454a75 mach_kernel : _kdp_i386_trap + 0x155
0xffffff914f12b970 : 0xffffff800e4465fe mach_kernel : _kernel_trap + 0x4ee
0xffffff914f12b9c0 : 0xffffff7f937708f4 as.vit9696.VirtualSMC : __ZN18VirtualSMCProvider10kernelTrapI22x86_saved_state_1010_tEEvPT_Pm + 0x454
0xffffff914f12ba40 : 0xffffff800e2c0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff914f12ba60 : 0xffffff800e319d27 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff914f12bb60 : 0xffffff800e31a117 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff914f12bbb0 : 0xffffff800eac1a6c mach_kernel : _panic + 0x54
0xffffff914f12bc20 : 0xffffff800e43baa0 mach_kernel : _spinlock_timeout_NMI
0xffffff914f12bc60 : 0xffffff800e3e6a80 mach_kernel : _vm_page_insert_internal + 0xf0
0xffffff914f12bcc0 : 0xffffff800e3a9f2f mach_kernel : _vm_pre_fault + 0x252f
0xffffff914f12bf10 : 0xffffff800e446bce mach_kernel : _user_trap + 0x17e
0xffffff914f12bfa0 : 0xffffff800e2c094f mach_kernel : _hndl_alltraps + 0xdf
      Kernel Extensions in backtrace:
         as.vit9696.VirtualSMC(1.2.7)[355499ED-74ED-398B-83DB-22F0F14F0D9B]@0xffffff7f93761000->0xffffff7f93787fff
            dependency: as.vit9696.Lilu(1.5.7)[11CE9410-EDAD-3D51-AB16-365C992FEFE4]@0xffffff7f936d8000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[2956198D-24F2-3790-A9B2-1EAB9434B906]@0xffffff7f8f0a2000

BSD process name corresponding to current thread: Google Chrome He
Boot args: -v igfxonln=1 keepsyms=1 swd_panic=1 debug=0x12a igdebug=0xff 
Mac OS version:
19H2

Kernel version:
Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
Kernel UUID: 05D51A3D-3A87-3FF0-98C3-9CF3827A3EDD
Kernel slide:     0x000000000e000000
Kernel text base: 0xffffff800e200000
__HIB  text base: 0xffffff800e100000
System model name: iMac19,1 (Mac-)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 115064724851

**Comment by vit9696** [comment]
This looks like there is a freeze on one of your cores. Possibly hardware or quirk-related. There is no obvious bug visible in the stack trace, so I can only assume it is a configuration error. Closing.
