### ISSUE TITLE
Lilu: 1.5.8 (RELEASE) Early kernel panic with OC 0.7.5

### ISSUE THREAD

**Issue by MacNB** [acidanthera/bugtracker#1851]
System is cMP5,1.
Happily running OC recently upgraded to 0.7.5 with Lilu 1.5.6 (DEBUG) booting High Sierra, Mojave, Catalina & Big Sur.

Today updated Lilu to 1.5.8 (RELEASE) and OS's boot fine except Catalina.
Panic Log attached.
[Catalina-panic-158.txt](https://github.com/acidanthera/bugtracker/files/7500550/Catalina-panic-158.txt)

If I remove Lilu 1.5.8 and replace it Lilu 1.5.6 (DEBUG version), the Catalina boots file (as do all the others).

Only Lilu version 1.5.6 DEBUG successfully boots Catalina.

Attached OC config.
[MacNB-config.plist.zip](https://github.com/acidanthera/bugtracker/files/7500557/MacNB-config.plist.zip)

Same issue with Lilu 1.5.7.
Is some timing issue ?
How can I capture more info to find out why Lilu 1.5.8 panics ?

**Comment by MacNB** [comment]
System is cMP5,1.
Happily running OC recently upgraded to 0.7.5 with Lilu 1.5.6 (DEBUG) booting High Sierra, Mojave, Catalina & Big Sur.

Today updated Lilu to 1.5.8 (RELEASE) and OS's boot fine except Catalina.
Panic Log attached.
[Catalina-panic-158.txt](https://github.com/acidanthera/bugtracker/files/7500100/Catalina-panic-158.txt)

If I remove Lilu 1.5.8 and replace it Lilu 1.5.6 (DEBUG version), the Catalina boots file (as do all the others).

Only Lilu version 1.5.6 DEBUG successfully boots Catalina.

Attached OC config.
[MacNB-config.plist.zip](https://github.com/acidanthera/bugtracker/files/7500142/MacNB-config.plist.zip)

Same issue with Lilu 1.5.7.
Is some timing issue ?
How can I capture more info to find out why Lilu 1.5.8 panics ?

**Comment by alainjroy** [comment]
I have the exact same panic with lilu 1.5.7 and Catalina 10.15.7 booting from open core  0.7.6 (or 0.7.5). Boots fine with the release version of lilu 1.5.6  . Tomorrow I will be able to provide the panic report (since the I need my machine working till then
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/7502130/config.plist.zip)

**Comment by alainjroy** [comment]
Re Lilu 1.5.7 panic
[Panic-lilu.rtf.zip](https://github.com/acidanthera/bugtracker/files/7508482/Panic-lilu.rtf.zip)
