### ISSUE TITLE
Shutdown cause reboot and Kernel Panic about WhateverGreen in Monterey

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#1853]
Specification :
- Processor : Intel Core i7 10700K
- Motherboard : Gigabyte Z590I Aorus Ultra
- iGPU : Intel UHD 630
- dGPU : Sapphire RX 580
- RAM : 32GB DDR4 PC17000/2133Mhz
- Storage : 1x NVME WDC 500GB
- Ethernet : Intel I225-V 2.5 Gigabit Ethernet
- Wifi : Intel Wifi 6 AX200 and Bluetooth
- USB : Intel Chipset
- Audio Codec : Realtek ALC1220A
- Display Size and Model : LG UltraWide Display 34"
- Monitor Resolution : 2560 x 1080
- Boot Mode : UEFI
- Bootloader : OpenCore 0.7.6
- OS Version : macOS Monterey 12.0.1 Build 21A559

Problem : Wake from Sleep will cause Kernel Panic about WhateverGreen

I will attach photo of logs
![255162987_219243460320251_4499651392812973832_n](https://user-images.githubusercontent.com/9614101/140918559-9a66c077-7a1a-4b1c-ab69-5cab57834285.jpg)

**Comment by vit9696** [comment]
Provide logs with DEBUG WEG and in text format.

**Comment by andreszerocross** [comment]
> Provide logs with DEBUG WEG and in text format.

Sorry for this questions.

Should i get the debug log after reboot because kernel panic or can i get debug log after cold boot (so no need to trigger kernel panic first) ???

**Comment by vit9696** [comment]
You need a DEBUG WEG, so you need to retrigger the panic first.

**Comment by andreszerocross** [comment]
> You need a DEBUG WEG, so you need to retrigger the panic first.

I have used Debug version of Lilu.kext and WhateverGreen.kext and use boot argument -wegdbg and -liludbg. But when i run command

_log show --predicate 'process == "kernel" AND (eventMessage CONTAINS "AppleALC" OR eventMessage CONTAINS "Lilu")' --style syslog --sourc_

i got no output

**Comment by vit9696** [comment]
In case it was unclear, I meant panic log, i.e. crash report you sent me a photo first.

**Comment by andreszerocross** [comment]
![image](https://user-images.githubusercontent.com/9614101/141076197-89da987a-e0ca-4cbc-ad48-9c42eaa40c50.png)

**Comment by andreszerocross** [comment]
> In case it was unclear, I meant panic log, i.e. crash report you sent me a photo first.
![IMG_5952](https://user-images.githubusercontent.com/9614101/141077605-89c87b4b-f50d-418f-ae8d-38533396c900.JPG)

I thought logs is still same. Kernel Panic from Lilu + WhateverGreen

**Comment by andreszerocross** [comment]
But just for info, i try to use old version of Lilu.kext (1.5.6) and WhateverGreen (1.5.4) then system normal now.

Shutdown, Restart, sleep and wake is normal for now.

Should be this problem about Lilu.kext and WEG in newest version. But i try to get debug weg log, but i can't get output

**Comment by andreszerocross** [comment]
I will close this issue for now because it's normal shutdown with previous version of Lilu and WhateverGreen.kext

**Comment by vit9696** [comment]
> I thought logs is still same. Kernel Panic from Lilu + WhateverGreen

I believe this is made with a RELEASE version of WhateverGreen, not DEBUG. That is why I requested a redo of this panic log. Even if you believe it was done with a DEBUG version, please redo. And next time please copy-paste the output instead of sending a photo.

> I will close this issue for now because it's normal shutdown with previous version of Lilu and WhateverGreen.kext

Only current versions of the kexts are supported. If you believe there is an issue, it is better to fix it, because the current situation means that your system is currently unsupported, and if you insistent on ignoring it, future macOS versions will simply not run.

**Comment by andreszerocross** [comment]
> > I thought logs is still same. Kernel Panic from Lilu + WhateverGreen
> 
> I believe this is made with a RELEASE version of WhateverGreen, not DEBUG. That is why I requested a redo of this panic log. Even if you believe it was done with a DEBUG version, please redo. And next time please copy-paste the output instead of sending a photo.
> 
> > I will close this issue for now because it's normal shutdown with previous version of Lilu and WhateverGreen.kext
> 
> Only current versions of the kexts are supported. If you believe there is an issue, it is better to fix it, because the current situation means that your system is currently unsupported, and if you insistent on ignoring it, future macOS versions will simply not run.

I am sorry, but i got the clear clue what's problem in this machine.

Even with Release version crash still happened. 

The main culprit is "FakePCIID.kext", i am using this kext to make "Intel I225" to work in Monterey. But, it caused random crash about whatevergreen in kernel panic.

Then i remove it, and there is no problem again. I am pretty sure 100% FakePCIID.kext is the problem in Monterey. And no solution for ethernet Intel I225-V in monterey for now.

Thanks for your attention

**Comment by andreszerocross** [comment]
Another source is here, https://www.reddit.com/r/hackintosh/comments/pr4sxw/random_systemstats_panic_when_using_fakepciid/

kernel panic with Whatevergreen only happened if we're using AMD GPU, with Nvidia or Intel UHD 630 only logs about "Systemstats".

I don't know why "WhateverGreen" will triggered panic too with this FakePCIID.kext

**Comment by vit9696** [comment]
Right, well, I guess not our bug then. Cannot you use the dk.e1000=0 boot argument instead of FakePCIID. It generally worked for our setups.

**Comment by andreszerocross** [comment]
> Right, well, I guess not our bug then. Cannot you use the dk.e1000=0 boot argument instead of FakePCIID. It generally worked for our setups.

In Monterey, we can't use this boot argument. kext is loaded (not dext) but status is "disconnected" even with ethernet cable is plugged

**Comment by vit9696** [comment]
Hm, we tested this like 2 days ago on ASUS Z690F, and it worked fine. I think the only thing we had to do is to manually set the link speed.

**Comment by vit9696** [comment]
cc @vandroiy2013

**Comment by vandroiy2013** [comment]
No solution here. Mostly Gigabyte boards are affected this bug wit non working i225 adapters. Asus boards seems work fine. More or less.

**Comment by sujunmin** [comment]
> But just for info, i try to use old version of Lilu.kext (1.5.6) and WhateverGreen (1.5.4) then system normal now.
> 
> Shutdown, Restart, sleep and wake is normal for now.
> 
> Should be this problem about Lilu.kext and WEG in newest version. But i try to get debug weg log, but i can't get output

It works, thanks.

I think there are some kexts need to update.

1. Lilu
2. WhateverGreen
3. FakePCIID
4. Fake_xxxx (for the devices that was injected)

You can

1. Disable FakePCIID and Fake_xxxx to prevent random boot and kernel panic, but you need to find another solutions to enable your faked devices. (like my intel hdmi audio)
2. Downgrade Lilu and WhaterverGreen and keep FakePCIID and Fake_xxxx to use the faked devices.

**Comment by tasco11xb** [comment]
> > But just for info, i try to use old version of Lilu.kext (1.5.6) and WhateverGreen (1.5.4) then system normal now.
> > Shutdown, Restart, sleep and wake is normal for now.
> > Should be this problem about Lilu.kext and WEG in newest version. But i try to get debug weg log, but i can't get output
> 
> It works, thanks.
> 
> I think there are some kexts need to update.
> 
> 1. Lilu
> 2. WhateverGreen
> 3. FakePCIID
> 4. Fake_xxxx (for the devices that was injected)
> 
> You can
> 
> 1. Disable FakePCIID and Fake_xxxx to prevent random boot and kernel panic, but you need to find another solutions to enable your faked devices. (like my intel hdmi audio)
> 2. Downgrade Lilu and WhaterverGreen and keep FakePCIID and Fake_xxxx to use the faked devices.


So, downgraded the Lilu and WEG will solved the issue?

**Comment by sujunmin** [comment]
> So, downgraded the Lilu and WEG will solved the issue? And I can keep the FakePCIID.kext and Fake_xxx.kext ?
Yes, but I got random crash again somedays ago. I've disable FakePCIID and related kexts and use another solution. (My device is intel hdmi HD audio, so I use AppleALC to replace FackPCIID and related kexts)

**Comment by tasco11xb** [comment]
> > So, downgraded the Lilu and WEG will solved the issue? And I can keep the FakePCIID.kext and Fake_xxx.kext ?
> 
> Yes, but I got random crash again somedays ago. I've disable FakePCIID and related kexts and use another solution. (My device is intel hdmi HD audio, so I use AppleALC to replace FackPCIID and related kexts)

My i know what is your motherboard?
