### ISSUE TITLE
OpenCore 0.7.5 - Mac OS X Lion 10.7 - QEMU - "Error allocating pages ... alloc type 2 ... Could not open mach_kernel (0xe)"

### ISSUE THREAD

**Issue by unilock** [acidanthera/bugtracker#1854]
I'm running Pop!_OS (Ubuntu) 21.04 hirsute, and am trying to boot and install Mac OS X Lion 10.7 in a QEMU-based virtual machine using OpenCore.

`uname -a`:
```
Linux stratosphere 5.13.0-7620-generic #20~1634827117~21.04~874b071-Ubuntu SMP Fri Oct 29 15:06:55 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

`lsb_release -a`:
```
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute
```

`qemu-system-x86_64 --version`:
```
QEMU emulator version 5.2.0 (Debian 1:5.2+dfsg-9ubuntu3.2)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
```

OpenCore loads and is able to select boot options just fine. However, upon attempting to load the recovery image [generated by macrecovery](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/linux-install.html#downloading-macos), I run into the following error:

```
OC: Prelink size 28528640 kext offset 27512832 reserved 1015808
OC: Prelinked status - Success
..............Error allocating 0xe2 pages at 0x0000000000800000 alloc type 2
Loading 'mach_kernel'...
Could not open file 'mach_kernel' (0xe)
OCB: StartImage failed - Aborted
OCSB: StartImage failed - Aborted
OCSB: Reenabling secure boot after Apple images
```

after which it returns to the boot picker. The full debug log can be found below.

dortania's [OpenCore troubleshooting guide](https://dortania.github.io/OpenCore-Install-Guide/extras/kaslr-fix.html) recommends changing the `slide=` boot argument. I've tried `0`, `4`, and `10`, as [recommended by their robot](https://user-images.githubusercontent.com/11802133/140987156-1d46b546-4e86-48c0-b299-be3d8cdea720.png), but output hasn't changed with any of those values. [Link to output of memmap.](https://pastebin.com/raw/u0HWVQRw)

[macOS boot script](https://github.com/acidanthera/bugtracker/files/7507246/boot.sh.txt) (stolen mostly from [OSX-KVM/OpenCore-Boot.sh](https://github.com/kholia/OSX-KVM/blob/master/OpenCore-Boot.sh))
The OVMF code and vars I'm using can be found in the [OSX-KVM](https://github.com/kholia/OSX-KVM) repo.
[EFI folder](https://github.com/acidanthera/bugtracker/files/7507239/EFI.zip)
[OpenCore debug log](https://github.com/acidanthera/bugtracker/files/7507240/opencore-2021-11-09-182744.txt)
[Screenshot of kernel output (not included in OC debug log)](https://user-images.githubusercontent.com/11802133/140985948-41878b82-27c1-4795-87bd-b2854dbd9289.png)

I've tried many different things to get this working in the past few days, so it's difficult to recall exactly what I've tried so far. I'll answer any questions to the best of my ability, however.

Here are a few things I *do* remember trying:
- Using the official OS X Lion install USB (A1384) instead of a recovery image
- Using HfsPlus, HfsPlusLegacy, and OpenHfsPlus (only HfsPlusLegacy was able to read the HFS+ partition in the recovery image / USB disk, IIRC)

Thanks.

(BTW, enabling `IgnoreInvalidFlexRation` in `config.plist` stops OpenCore from booting on QEMU with the above boot script. I can provide more information if this is something of concern.)

**Comment by vit9696** [comment]
macOS 10.7 does not support kernel sliding (KASLR), KASLR was added in macOS 10.8. This is solved by `AllowRelocationBlock` quirk. Refer to the [official OpenCore documentation](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf), not dortania, for more details.

**Comment by unilock** [comment]
Yep, that got OS X Lion booting. Thanks so much!
I'll be sure to give the OpenCore docs a read.
