### ISSUE TITLE
Apple ALC no microphone sound Conexant CX20751 (except Safari and Siri) (Monterey)

### ISSUE THREAD

**Issue by SupLiCatinG** [acidanthera/bugtracker#1855]
My layout id is 28 and i have no sound on microphone (except Safari and Siri) when i updated to Monterey this problem accured. I'm using the latest version of kext which is 1.6.6.

When i was on Big Sur i can fix this problem with audio-midi setup but now on Monterey it doesnt work somehow. 
And the native ambient noise cancellation never worked for me. 

![image](https://user-images.githubusercontent.com/94017480/141005527-2dd18ec6-d2f7-4bb8-b871-0f628a0216d8.png)

**Comment by Andrey1970AppleLife** [comment]
Here not forum support of resources audio codecs.
