### ISSUE TITLE
System crash after upgrading Lilu.kext

### ISSUE THREAD

**Issue by tecnicasopr** [acidanthera/bugtracker#1856]
I updated all kexts and latest OpenCore version. Then I start it to eliminate the kexts one by one and Lilu.kext was the culprit. I hope these attach files can help. Thanks a lot in advance.
https://drive.google.com/file/d/1UveHOB3jn7K4ViSoWwHAEs6UzkhsSdIs/view?usp=sharing

**Comment by vit9696** [comment]
Duplicate of https://github.com/acidanthera/bugtracker/issues/1851.
