### ISSUE TITLE
SMCDellSensors: Dell brightness keys stop working when EC fan control is disabled

### ISSUE THREAD

**Issue by hacker1024** [acidanthera/bugtracker#1857]
As is common with Dell laptops, I've mapped my ACPI function triggered by the brightness keys to relevant PS/2 codes.
(https://github.com/hacker1024/Dell-Inspiron-7586-Hackintosh/commit/00532c7b94a2dcf84b6a37f366b835f796bf7252)

When using an app such as Macs Fan Control to disable EC fan control and set a custom fan speed, the brightness keys stop working.

Pressing any brightness keys with EC fan control disabled has no effect. When EC fan control is re-enabled, however, the last pressed brightness key will trigger.

I can upload debug logs if requested, but I'd first like to go through the ACPI and SMCDellSensors code to see if anything obvious is causing this. Does anyone have any ideas about what it could be?

ACPI table dumps can be found in my repository: https://github.com/hacker1024/Dell-Inspiron-7586-Hackintosh/tree/monterey/master/EFI/OC/ACPI/Dumps

Specs:
- Model: Dell Inspiron 7586
- CPU: Intel Core i7-8565U
- IGPU: Whiskey Lake Intel UHD 620
- DGPU: NVIDIA GeForce MX150 (powered off via custom SSDT)
- Display: AUO34EB

(CC: @lvs1974)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/BrightnessKeys

**Comment by lvs1974** [comment]
@hacker1024: I have exactly the same behaviour, there is nothing I can do here. Brightness change is blocked on ACPI level when fan control is enabled.

**Comment by hacker1024** [comment]
@lvs1974 I don't have this issue when disabling EC fan control in Windows, though. Do you know why that is? Is there another way of receiving these button presses, perhaps?

@Andrey1970AppleLife I didn't think the BrightnessKeys kext worked on Dell laptops, as they work differently to most laptops. I may have just been missing the _OSI patches when I last tried it though - I'll try again.

**Comment by lvs1974** [comment]
@hacker1024: I have tried to find out using ACPI debugging, but it was useless. It works in Windows - yes, but in ACPI under windows we have also WMI. I would not suggest to use fan control anyway. For example, if fan control is on, put machine into sleep and wake - you will never be able to control brightness and see current charging status. It stops working after wake.
