### ISSUE TITLE
OpenLinuxBoot no keyboard and trackpad in LinuxMint on MacBookPro12,1

### ISSUE THREAD

**Issue by eugene2878** [acidanthera/bugtracker#1858]
As per title no keyboard or trackpad available once booted into LinuxMint. 
Same issue with adding grubx64.efi entry into BlessOverride section.

[opencore-2021-11-10-105010.txt](https://github.com/acidanthera/bugtracker/files/7512142/opencore-2021-11-10-105010.txt)
[OC.zip](https://github.com/acidanthera/bugtracker/files/7512147/OC.zip)

**Comment by mikebeaton** [comment]
This is not an OC issue - or at least, not unless you can boot into LinuxMint not via OC and then it works?

**Comment by eugene2878** [comment]
No such issue with Clover bootloader. Hence reported.

**Comment by mikebeaton** [comment]
Hi - I would like to know what happens if you boot into LinuxMint directly from the macOS bootloader (i.e. hold down OPT key while machine is starting)? Hopefully you will have a Linux entry in that meny... it is definitely possible to get one, but may involve some fiddling around if it is not already there.

**Comment by eugene2878** [comment]
I have done update in Linuxmint and installed new kernels. Mint replaced bootx64.efi with its own so my macbook boots into grub by default. No issues what so ever. Before if use Clover--> Grubx64 -- no problem.
if Opencore-->Clover-->Grubx64 -- no keybord no trackpad
if Opencore-->Grubx64 -- no keybord no trackpad
if Opencore-->OpenLinuxBoot -- no keybord no trackpad

**Comment by mikebeaton** [comment]
Okay, so definitely not an OpenLinuxBoot issue specifically, but ofc we can see that it indeed is an OC issue. I believe @vit9696 pointed you here, but I'm going to cc back to him now to ask if he's got any other suggestions!

**Comment by mikebeaton** [comment]
Actually, I'll suggest one thing. Can you disable OpenRuntime.efi driver and reboot into Linux via OC? I am pretty sure this cannot be the issue, but it would be good to be sure.

**Comment by eugene2878** [comment]
Disabled OpenRunTime and trackpad worked after reboot into Linuxmint once. Not after reboot from Linux or coldboot.
It working now occasionally. It worked few times before without runtime removal.

**Comment by mikebeaton** [comment]
So disabling OpenRuntime is _maybe_ better, or definitely better, would you say?

**Comment by mikebeaton** [comment]
Also, either way the keyboard does not come back - correct?

**Comment by mikebeaton** [comment]
Sorry, last q, just to be sure, which kb and trackpad are we talking about? Internal ones in both cases?

**Comment by eugene2878** [comment]
I think it does not affect much. It booted with keyboard working once with OpenRuntime.efi and once without.

**Comment by mikebeaton** [comment]
okay, and these are just the internal kb and trackpad of your MBP, right?

**Comment by eugene2878** [comment]
> okay, and these are just the internal kb and trackpad of your MBP, right?

yes

**Comment by mikebeaton** [comment]
Okay. It would also be useful to know this too, to pin down what we are seeing: when kb and trackpad work (sometimes) do they always either both work together or neither works - or is it sometimes just one which works and not the other? Thank you.

**Comment by eugene2878** [comment]
work together or both not working.

**Comment by mikebeaton** [comment]
Thank you.

I believe I have only one more thing to suggest for now - also I believe very unlikely to be the issue, but can you just try setting `SignalAppleOS` to `false` in OC config then try again, please?

**Comment by eugene2878** [comment]
This resolved the issue. Thanks a lot.

**Comment by mikebeaton** [comment]
Blimey!

**Comment by mikebeaton** [comment]
@khronokernel - I see you need to set this quirk under some circumstances in OCLP, just flagging this other side effect which it apparently has
