### ISSUE TITLE
System crash again after latest Lilu.kext

### ISSUE THREAD

**Issue by tecnicasopr** [acidanthera/bugtracker#1860]
I uploaded a report before, but it end it reported as duplicate. But this is a new one and having panic again after using latest Lilu.
These are my panic report files: https://drive.google.com/file/d/1nGLaqM7IvljlXMwbTae6dkhfZbeKsi7m/view?usp=sharing
Thanks in advance.

**Comment by vit9696** [comment]
This is a bug in science.firewolf.gcrf. It seems to fail to support medium size wrappers. CC @0xFirewolf

**Comment by 0xFireWolf** [comment]
@tecnicasopr The previous release is compiled with an old version of Lilu. 
Please download the latest compiled version at [here](https://github.com/0xFireWolf/GenericCardReaderFriend/releases/tag/1.0.2). The kernel panic is gone on my machine.

**Comment by tecnicasopr** [comment]
@vit9696 You are right. Lilu is fine. The problem is GenericCardReaderFreind. Thanks for your help.
@0xFireWolf  Thanks for the link and compiling your kext against the latest Lilu but it's still crashing my system. Should I open a new issue or upload the new kernel panic report here?
