### ISSUE TITLE
SMCBatteryManager works unnormally when using battery

### ISSUE THREAD

**Issue by AtomsQi** [acidanthera/bugtracker#1861]
When my laptop using battery after about 10minutes,the kernel_task will be high cpu percent(60%-70%) suddenly,and the cpu frequency&temperature(40°C when plug in a/c charger,65°C when using battery) will be high too.  After that, if I plug in a/c charger or reboot my laptop, it will work normally. On the other way, when  I use ACPIBatteryManager+FakeSMC,there was no same problem.
My laptop is Honor MagicBook14 2020Year(i5_10210U+MX250(not work)) ,loaded VirtualSMC+SMCBatteryManager+SMCProcessor+SMCSuperIO,and the Fan rpm can't
be read.
Hope to get reply~

**Comment by AtomsQi** [comment]
My os is MacOS 12.0.1 Monterey now , the same problem was also in BigSUr

**Comment by sxunix** [comment]
My laptop is Huawei Matebook X pro 2020. I met the same case. After the debug, I found the issue is from ACL. Please change the ACL layout id, afterwards it is working.

**Comment by AtomsQi** [comment]
> My laptop is Huawei Matebook X pro 2020. I met the same case. After the debug, I found the issue is from ALC. Please change the ALC layout id, afterwards it is working.
> My audio card is Realtek ALC256. In the beginning, I used id 97 and got the issue. Now I changed to 21, the issue has been solved.

Thank you, my audio card is Realtek ALC256 too , I'll change my layout id  and hope to resolve the problem.

**Comment by AtomsQi** [comment]
> My laptop is Huawei Matebook X pro 2020. I met the same case. After the debug, I found the issue is from ALC. Please change the ALC layout id, afterwards it is working.
> My audio card is Realtek ALC256. In the beginning, I used id 97 and got the issue. Now I changed to 21, the issue has been solved.

I change my layout id from 21 to 5. In these days,I didn't met the problem, so I think it has been solved. Thank you!

**Comment by Edwardwich** [comment]
https://github.com/acidanthera/bugtracker/issues/1875
Plz see this
