### ISSUE TITLE
Stuck on [EB|#LOG:EXITBS:START] after Lilu.kext upgrade (1.5.7)

### ISSUE THREAD

**Issue by ciccio-90** [acidanthera/bugtracker#1862]
After Lilu upgrade from 1.5.6 to 1.5.7 I have a kernel panic at system boot which stay stuck on [EB|#LOG:EXITBS:START].

[opencore-2021-11-13-115742.txt](https://github.com/acidanthera/bugtracker/files/7531959/opencore-2021-11-13-115742.txt)

[EFI.zip](https://github.com/acidanthera/bugtracker/files/7531948/EFI.zip)

**Comment by vit9696** [comment]
I suspect this is related to https://github.com/acidanthera/bugtracker/issues/1851. Please use the latest 1.5.8 beta: https://dortania.github.io/builds/?product=Lilu&viewall=true

**Comment by ciccio-90** [comment]
I will try it.

**Comment by ciccio-90** [comment]
It works, thanks!
