### ISSUE TITLE
VoodooPS2: Focaltech keyboard issue

### ISSUE THREAD

**Issue by NotScar** [acidanthera/bugtracker#1863]
This is my first hackintosh that I've done, and I'm having issues with my focaltech kb/touchpad, the main issue is that with VoodooPS2 the trackpad works, but the keyboard does not at all, while with ApplePS2SmartTouchpad only the keyboard works, I've tried to "merge" voodoops2 and ApplePS2SmartTouchpad by disabling some of the components in both so that ApplePS2SmartTouchpad controls keyboard and voodoo controls only the touchpad but it didn't work, I've tried to move around the start order but couldn't make it out.

This is my [EFI.zip](https://github.com/acidanthera/bugtracker/files/7532788/EFI.zip), with ApplePS2SmartTouchpad as a priority.

I'm sure there's a work around as one time after around 10 restarts both worked, but after a restart it didn't work again, without me changing anything.

**Comment by TheHackGuy** [comment]
Only use voodoops2controller with all its plugins enabled. Then provide logs and your edited efi.

Without logs nobody can help...

**Comment by Edwardwich** [comment]
> Only use voodoops2controller with all its plugins enabled. Then provide logs and your edited efi.
> 
> Without logs nobody can help...
> 

Plz see


https://github.com/acidanthera/bugtracker/issues/1875

**Comment by TheHackGuy** [comment]
> > Only use voodoops2controller with all its plugins enabled. Then provide logs and your edited efi.
> > 
> > Without logs nobody can help...
> > 
> 
> Plz see
> 
> 
> https://github.com/acidanthera/bugtracker/issues/1875

Don't start quaking for help in other issues totally unrelated to yours. 

And what's even the problem with your issue? "My charger reports 300 wats instead of 60 in macos so now smcbatterymanager is borken" --sounds like stupid

**Comment by Edwardwich** [comment]
> > > Only use voodoops2controller with all its plugins enabled. Then provide logs and your edited efi.
> > > 
> > > Without logs nobody can help...
> > > 
> > 
> > Plz see
> > 
> > 
> > https://github.com/acidanthera/bugtracker/issues/1875
> 
> Don't start quaking for help in other issues totally unrelated to yours. 
> 
> And what's even the problem with your issue? "My charger reports 300 wats instead of 60 in macos so now smcbatterymanager is borken" --sounds like stupid

No one see my problem idk why

**Comment by NotScar** [comment]
> Only use voodoops2controller with all its plugins enabled. Then provide logs and your edited efi.
> 
> Without logs nobody can help...

Where can i find a guide to extract logs as the guide on bugtracker repo is only for applealc and lilu

**Comment by TheHackGuy** [comment]
> > Only use voodoops2controller with all its plugins enabled. Then provide logs and your edited efi.
> > Without logs nobody can help...
> 
> Where can i find a guide to extract logs as the guide on bugtracker repo is only for applealc and lilu

Just try with debug version of voodoops2controller and using the existing command mentioned on the applealc page. Then modify this command for PS2 instead of Lilu and AppleALC.

log show --predicate 'process == "kernel" AND (eventMessage CONTAINS "AppleALC" OR eventMessage CONTAINS "Lilu")' --style syslog --source

**Comment by TheHackGuy** [comment]
> > > > Only use voodoops2controller with all its plugins enabled. Then provide logs and your edited efi.
> > > > 
> > > > Without logs nobody can help...
> > > > 
> > > 
> > > Plz see
> > > 
> > > 
> > > https://github.com/acidanthera/bugtracker/issues/1875
> > 
> > Don't start quaking for help in other issues totally unrelated to yours. 
> > 
> > And what's even the problem with your issue? "My charger reports 300 wats instead of 60 in macos so now smcbatterymanager is borken" --sounds like stupid
> 
> No one see my problem idk why

The only problem that you mentioned in your post is that the app reports 300w instead of 60. And the English of the issue that you made is very bad. It's difficult to understand. 


Commenting on issues that are keyboards related have nothing to do with battery. Now you're spilling the time of devs that will be needed to remove these useless comments. Be respectful to the devs and wait until they respond instead of putting a link to your issue into other random issues.

**Comment by Edwardwich** [comment]
> > > > > Only use voodoops2controller with all its plugins enabled. Then provide logs and your edited efi.
> > > > > 
> > > > > Without logs nobody can help...
> > > > > 
> > > > 
> > > > Plz see
> > > > 
> > > > 
> > > > https://github.com/acidanthera/bugtracker/issues/1875
> > > 
> > > Don't start quaking for help in other issues totally unrelated to yours. 
> > > 
> > > And what's even the problem with your issue? "My charger reports 300 wats instead of 60 in macos so now smcbatterymanager is borken" --sounds like stupid
> > 
> > No one see my problem idk why
> 
> The only problem that you mentioned in your post is that the app reports 300w instead of 60. And the English of the issue that you made is very bad. It's difficult to understand. 
> 
> 
> Commenting on issues that are keyboards related have nothing to do with battery. Now you're spilling the time of devs that will be needed to remove these useless comments. Be respectful to the devs and wait until they respond instead of putting a link to your issue into other random issues.

My laptop has two problems when charging: 

1 One is that you noticed 

2 when laptop using power source : power adapter it's work good 
But after back to charging macos battery status show power source power adapter

Did you understand ?

**Comment by NotScar** [comment]
> > > > > > Only use voodoops2controller with all its plugins enabled. Then provide logs and your edited efi.
> > > > > > Without logs nobody can help...
> > > > > 
> > > > > 
> > > > > Plz see
> > > > > #1875
> > > > 
> > > > 
> > > > Don't start quaking for help in other issues totally unrelated to yours.
> > > > And what's even the problem with your issue? "My charger reports 300 wats instead of 60 in macos so now smcbatterymanager is borken" --sounds like stupid
> > > 
> > > 
> > > No one see my problem idk why
> > 
> > 
> > The only problem that you mentioned in your post is that the app reports 300w instead of 60. And the English of the issue that you made is very bad. It's difficult to understand.
> > Commenting on issues that are keyboards related have nothing to do with battery. Now you're spilling the time of devs that will be needed to remove these useless comments. Be respectful to the devs and wait until they respond instead of putting a link to your issue into other random issues.
> 
> My laptop has two problems when charging:
> 
> 1 One is that you noticed
> 
> 2 when laptop using power source : power adapter it's work good But after back to charging macos battery status show power source power adapter
> 
> Did you understand ?

Make another issue, and if you've made one please wait like i did.

**Comment by andreszerocross** [comment]
> This is my first hackintosh that I've done, and I'm having issues with my focaltech kb/touchpad, the main issue is that with VoodooPS2 the trackpad works, but the keyboard does not at all, while with ApplePS2SmartTouchpad only the keyboard works, I've tried to "merge" voodoops2 and ApplePS2SmartTouchpad by disabling some of the components in both so that ApplePS2SmartTouchpad controls keyboard and voodoo controls only the touchpad but it didn't work, I've tried to move around the start order but couldn't make it out.
> 
> This is my [EFI.zip](https://github.com/acidanthera/bugtracker/files/7532788/EFI.zip), with ApplePS2SmartTouchpad as a priority.
> 
> I'm sure there's a work around as one time after around 10 restarts both worked, but after a restart it didn't work again, without me changing anything.

Your config is mess, why did you set active for ApplePS2SmartTouchpad and VoodooPS2Controller.kext of Acidanthera in same time. It's wrong

**Comment by NotScar** [comment]
> > This is my first hackintosh that I've done, and I'm having issues with my focaltech kb/touchpad, the main issue is that with VoodooPS2 the trackpad works, but the keyboard does not at all, while with ApplePS2SmartTouchpad only the keyboard works, I've tried to "merge" voodoops2 and ApplePS2SmartTouchpad by disabling some of the components in both so that ApplePS2SmartTouchpad controls keyboard and voodoo controls only the touchpad but it didn't work, I've tried to move around the start order but couldn't make it out.
> > This is my [EFI.zip](https://github.com/acidanthera/bugtracker/files/7532788/EFI.zip), with ApplePS2SmartTouchpad as a priority.
> > I'm sure there's a work around as one time after around 10 restarts both worked, but after a restart it didn't work again, without me changing anything.
> 
> Your config is mess, why did you set active for ApplePS2SmartTouchpad and VoodooPS2Controller.kext of Acidanthera in same time. It's wrong

As explained in the issue, i've prioritized ApplePS2SmartTouchpad as VoodooPS2Controller doesen't work, either way it wouldn't work even without appleps2smarttotouchpad, and soon i will provide the log files.

**Comment by vit9696** [comment]
I am not positive there is an obvious bug from this issue. So far there have never been keyboard init issues and no changes were made in there recently. Assuming a configuration error.

CC @1Revenger1 in case there can be anything.

**Comment by NotScar** [comment]
@vit9696 I totally forgot about the issue open'd here,
[debugthing.log](https://github.com/acidanthera/bugtracker/files/7799204/debugthing.log)
This is the file that was requested from the hack guy, it appears that ApplePS2 is in the logs but i think it's from the past, as i don't have it loaded at the moment i logged this with the command.

**Comment by vit9696** [comment]
Well, no surprise it did not start.

2019-01-01 01:12:08.364815+0100  localhost kernel[0]: OSMetaClass: Kext as.acidanthera.voodoo.driver.PS2Controller class ApplePS2Controller is a duplicate;kext org.emlydinesh.driver.ApplePS2Controller already has a class by that name.
2019-01-01 01:12:08.364831+0100  localhost kernel[0]: Kext as.acidanthera.voodoo.driver.PS2Controller did not start (return code 0xdc00400a).

**Comment by NotScar** [comment]
> Well, no surprise it did not start.
> 
> 2019-01-01 01:12:08.364815+0100 localhost kernel[0]: OSMetaClass: Kext as.acidanthera.voodoo.driver.PS2Controller class ApplePS2Controller is a duplicate;kext org.emlydinesh.driver.ApplePS2Controller already has a class by that name. 2019-01-01 01:12:08.364831+0100 localhost kernel[0]: Kext as.acidanthera.voodoo.driver.PS2Controller did not start (return code 0xdc00400a).
How's it mentioning appleps2controller when it's not in the kext folder nor in the config.plist o.o

**Comment by NotScar** [comment]
@vit9696 i have erased the log via the command "log erase" restarted it again and now it shows no error or nothing when i search up ps2 in the logs, but ofc shows other stuff like AppleUserUSBHostHIDDevice etc

**Comment by NotScar** [comment]
in addition this is my system report with aida https://transfer.sh/eCfpxa/report.htm and this is my current config used to debug this
[EFI.zip](https://github.com/acidanthera/bugtracker/files/7799288/EFI.zip)

**Comment by NotScar** [comment]
and adding to that another information, again, in my bios i can switch the mouse from i2c to ps2, the report was with i2c selected, but when ps2 is selected my mouse turns into "PS/2 Compatible Mouse"
