### ISSUE TITLE
CpuTscSync

### ISSUE THREAD

**Issue by wy414012** [acidanthera/bugtracker#1864]
Hello:
Happy weekend, let me ask questions!
      Do you have any guidance or suggestions for processors without `CpuTscSync MSR_IA32_TSC_ADJUST 03bh` ? My current [EFI](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2) can run macOS12 perfectly on a CPU with 6 cores, 12 threads or less. Once a processor with more cores is replaced, a kernel panic occurs.
![IMG_0319](https://user-images.githubusercontent.com/36281137/141665077-ae0a41a9-1f38-442b-8ffd-e5080492725e.JPG)

**Comment by vit9696** [comment]
I believe not. CC @lvs1974

**Comment by mahmoudimus** [comment]
@vit9696 @Goldfish64 @wy414012 -- I wanted to open this conversation back up. I believe there could be a workaround here if `MSR_IA32_TSC_ADJUST` does not exist. 

From the [xen patches + archives](https://lists.archive.carbon60.com/xen/devel/257060), it seems that an Intel employee suggested this comment during updates for the xen hypervisor:

> Software can modify the value of the time-stamp counter (TSC) of a logical processor by using the WRMSR instruction to write to the IA32_TIME_STAMP_COUNTER MSR (address 10H). Because such a write applies only to that logical processor, software seeking to synchronize the TSC values of multiple logical processors must perform these writes on each logical processor. It may be difficult for software to do this in a way than ensures that all logical processors will have the same value for the TSC at a given point in time.

If that is the case, then wouldn't the workaround here be something similar to:

```c
extern "C" void forceResetTSC(void *tscp)
{
	wrmsr64(MSR_IA32_TSC, *reinterpret_cast<uint64_t*>(tscp));
	wrmsr64(IA32_TIME_STAMP_COUNTER, 0); // work around by setting 0 to every time stamp counter

}

// Update MSR on all processors.
void NAMESPACE::doTSC()
{
	uint64_t tsc = rdtsc64(); // for processors that support 
	
	// call the kernel function that will call this "action" on all cores/processors
	mp_rendezvous_no_intrs(forceResetTSC, &tsc);
}
```


If more synchronization is needed, then wouldn't inserting a fence like in the linux kernel here: https://github.com/torvalds/linux/blob/6feb57c2fd7c787aecf2846a535248899e7b70fa/arch/x86/include/asm/msr.h#L189-L223, so make it synchronous? 

```c
/**
 * rdtsc_ordered() - read the current TSC in program order
 *
 * rdtsc_ordered() returns the result of RDTSC as a 64-bit integer.
 * It is ordered like a load to a global in-memory counter.  It should
 * be impossible to observe non-monotonic rdtsc_unordered() behavior
 * across multiple CPUs as long as the TSC is synced.
 */
static __always_inline unsigned long long rdtsc_ordered(void)
{
	DECLARE_ARGS(val, low, high);


	/*
	 * The RDTSC instruction is not ordered relative to memory
	 * access.  The Intel SDM and the AMD APM are both vague on this
	 * point, but empirically an RDTSC instruction can be
	 * speculatively executed before prior loads.  An RDTSC
	 * immediately after an appropriate barrier appears to be
	 * ordered as a normal load, that is, it provides the same
	 * ordering guarantees as reading from a global memory location
	 * that some other imaginary CPU is updating continuously with a
	 * time stamp.
	 *
	 * Thus, use the preferred barrier on the respective CPU, aiming for
	 * RDTSCP as the default.
	 */
	asm volatile(ALTERNATIVE_2("rdtsc",
				   "lfence; rdtsc", X86_FEATURE_LFENCE_RDTSC,
				   "rdtscp", X86_FEATURE_RDTSCP)
			: EAX_EDX_RET(val, low, high)
			/* RDTSCP clobbers ECX with MSR_TSC_AUX. */
			:: "ecx");


	return EAX_EDX_VAL(val, low, high);
}
```

**Comment by lvs1974** [comment]
@mahmoudimus:  see msr-index.h in linux kernel:
`/* Intel defined MSRs. */
#define MSR_IA32_P5_MC_ADDR		0x00000000
#define MSR_IA32_P5_MC_TYPE		0x00000001
#define MSR_IA32_TSC			0x00000010
#define MSR_IA32_PLATFORM_ID		0x00000017
#define MSR_IA32_EBL_CR_POWERON		0x0000002a
#define MSR_EBC_FREQUENCY_ID		0x0000002c
#define MSR_SMI_COUNT			0x00000034
#define MSR_IA32_FEATURE_CONTROL        0x0000003a
#define MSR_IA32_TSC_ADJUST             0x0000003b
#define MSR_IA32_BNDCFGS		0x00000d90

#define MSR_IA32_BNDCFGS_RSVD		0x00000ffc

#define MSR_IA32_XSS			0x00000da0

#define FEATURE_CONTROL_LOCKED				(1<<0)
#define FEATURE_CONTROL_VMXON_ENABLED_INSIDE_SMX	(1<<1)
#define FEATURE_CONTROL_VMXON_ENABLED_OUTSIDE_SMX	(1<<2)
#define FEATURE_CONTROL_LMCE				(1<<20)

#define MSR_IA32_APICBASE		0x0000001b
#define MSR_IA32_APICBASE_BSP		(1<<8)
#define MSR_IA32_APICBASE_ENABLE	(1<<11)
#define MSR_IA32_APICBASE_BASE		(0xfffff<<12)

#define MSR_IA32_TSCDEADLINE		0x000006e0

#define MSR_IA32_UCODE_WRITE		0x00000079
#define MSR_IA32_UCODE_REV		0x0000008b

#define MSR_IA32_SMM_MONITOR_CTL	0x0000009b
#define MSR_IA32_SMBASE			0x0000009e

#define MSR_IA32_PERF_STATUS		0x00000198
#define MSR_IA32_PERF_CTL		0x00000199
#define INTEL_PERF_CTL_MASK		0xffff

#define MSR_IA32_MPERF			0x000000e7
#define MSR_IA32_APERF			0x000000e8

#define MSR_IA32_THERM_CONTROL		0x0000019a
#define MSR_IA32_THERM_INTERRUPT	0x0000019b`


MSR_IA32_TSC = 0x10.
And, according your comment: IA32_TIME_STAMP_COUNTER MSR (address 10H) = 0x10

The following code won't make any difference:
`extern "C" void forceResetTSC(void *tscp)
{
	wrmsr64(MSR_IA32_TSC, *reinterpret_cast<uint64_t*>(tscp));
	wrmsr64(IA32_TIME_STAMP_COUNTER, 0); // work around by setting 0 to every time stamp counter

}`

**Comment by mahmoudimus** [comment]
> @mahmoudimus: see msr-index.h in linux kernel:
> 
> ```
> /* Intel defined MSRs. */
> #define MSR_IA32_P5_MC_ADDR		0x00000000
> #define MSR_IA32_P5_MC_TYPE		0x00000001
> #define MSR_IA32_TSC			0x00000010
> #define MSR_IA32_PLATFORM_ID		0x00000017
> #define MSR_IA32_EBL_CR_POWERON		0x0000002a
> #define MSR_EBC_FREQUENCY_ID		0x0000002c
> #define MSR_SMI_COUNT			0x00000034
> #define MSR_IA32_FEATURE_CONTROL        0x0000003a
> #define MSR_IA32_TSC_ADJUST             0x0000003b
> #define MSR_IA32_BNDCFGS		0x00000d90
> 
> #define MSR_IA32_BNDCFGS_RSVD		0x00000ffc
> 
> #define MSR_IA32_XSS			0x00000da0
> 
> #define FEATURE_CONTROL_LOCKED				(1<<0)
> #define FEATURE_CONTROL_VMXON_ENABLED_INSIDE_SMX	(1<<1)
> #define FEATURE_CONTROL_VMXON_ENABLED_OUTSIDE_SMX	(1<<2)
> #define FEATURE_CONTROL_LMCE				(1<<20)
> 
> #define MSR_IA32_APICBASE		0x0000001b
> #define MSR_IA32_APICBASE_BSP		(1<<8)
> #define MSR_IA32_APICBASE_ENABLE	(1<<11)
> #define MSR_IA32_APICBASE_BASE		(0xfffff<<12)
> 
> #define MSR_IA32_TSCDEADLINE		0x000006e0
> 
> #define MSR_IA32_UCODE_WRITE		0x00000079
> #define MSR_IA32_UCODE_REV		0x0000008b
> 
> #define MSR_IA32_SMM_MONITOR_CTL	0x0000009b
> #define MSR_IA32_SMBASE			0x0000009e
> 
> #define MSR_IA32_PERF_STATUS		0x00000198
> #define MSR_IA32_PERF_CTL		0x00000199
> #define INTEL_PERF_CTL_MASK		0xffff
> 
> #define MSR_IA32_MPERF			0x000000e7
> #define MSR_IA32_APERF			0x000000e8
> 
> #define MSR_IA32_THERM_CONTROL		0x0000019a
> #define MSR_IA32_THERM_INTERRUPT	0x0000019b
> ```
> 
> MSR_IA32_TSC = 0x10. And, according your comment: IA32_TIME_STAMP_COUNTER MSR (address 10H) = 0x10
> 
> The following code won't make any difference:
> 
> ```
> extern "C" void forceResetTSC(void *tscp)
> {
> 	wrmsr64(MSR_IA32_TSC, *reinterpret_cast<uint64_t*>(tscp));
> 	wrmsr64(IA32_TIME_STAMP_COUNTER, 0); // work around by setting 0 to every time stamp counter
> 
> }
> ```
> 
> It is the same as:
> 
> ```
> extern "C" void forceResetTSC(void *tscp)
> {
> 	wrmsr64(0x10, *reinterpret_cast<uint64_t*>(tscp));
> 	wrmsr64(0x10, 0);
> 
> }
> ```
> 
> [gz/rust-x86@`master`/src/msr.rs](https://github.com/gz/rust-x86/blob/master/src/msr.rs?rgh-link-date=2022-12-20T07%3A26%3A51Z) - addresses of MSR regs

Ah yes, you're correct. That's my mistake!

I think the main issue is the synchronization, right? Wouldn't the fence solution be a workaround on that?

I'd like to try this out on my Ivy Bridge.

**Comment by mahmoudimus** [comment]
@lvs1974 fyi I think I am close to solving this. This reddit post has been very helpful: https://www.reddit.com/r/Amd/comments/uf0zdf/comment/i6tqak0/
