### ISSUE TITLE
NVMeFix kernel panic on Monterey

### ISSUE THREAD

**Issue by meichengg** [acidanthera/bugtracker#1865]
Hi, recently after upgrading to Monterey, i keep getting kernel panic including stack trace of this keyword "AppleNVMeRequest", i did search and found that it came from NVMeFix kext. I got a video recording how it went crashed during boot with OpenCore (sometimes it crashes randomly). I'm using Samsung SSD NVME 970 Evo Plus with TRIM and SIP disabled. I'm using latest kexts at the moment.

Video of kernel panic when booting:
https://drive.google.com/file/d/1XU63Ua5aSQWzVTbEZIhP7hYUvcihVcjy/view?usp=drivesdk

My EFI configs:
https://drive.google.com/file/d/12mNvVPk9rOXiJxao7lUz4ZHGGv9h2yff/view?usp=drivesdk

## My specs

* Model: Lenovo ThinkPad P50 (20EN)
* CPU: Intel Xeon E3-1505 v5 2.7Ghz Quad Core - Eight Threads CPU (vPro)
* GPUs:
  * Intel HD P530
  * Nvidia Quadro M2000M (Lenovo branded)
* RAM: 16GB+16GB 2133Mhz DDR4 (2 Slots filled from 4)
* Storage:
  * 500GB Samsung SSD 970 EVO Plus NVMe M.2

**Comment by vit9696** [comment]
I believe this is incorrect that NVMeFix causes a kernel panic. The stacktrace says it dies in Apple NVMe driver. Does the drive work without NVMeFix? Unless you forgot to upgrade the firmware, then it likely means Apple dropped 970 EVO Plus.

**Comment by justinkb** [comment]
I have the same problem. It never occurs without NVMeFix kext loaded. You should definitely reopen this. I think there might be a race condition during boot
