### ISSUE TITLE
WEG WindowServer watchdog timeout

### ISSUE THREAD

**Issue by Joshj23icy** [acidanthera/bugtracker#1867]
Hi,
Using an R9 Fury X, with WEG loaded the UI will randomly stop responding however cursor can still move, a few minutes later cursor will dissapear.
Monterey Console shows a WindowServer crash detailing `X seconds since last successful checkin`

WindowServer does not crash if WEG is not loaded
have tried WEG 1.5.4 & 1.5.5
Lilu 1.5.6, 1.5.7

Have attached most recent crash report, can provide any other files upon request
[WindowServer-2021-11-14-172843.zip](https://github.com/acidanthera/bugtracker/files/7538616/WindowServer-2021-11-14-172843.zip)
Thanks

edit: relevant specs as below:
Xeon E5 2686 v4
Asus x99-ws/ipmi
gigabyte r9 fury x
crucial p2 1tb

**Comment by Joshj23icy** [comment]
Believe this is an issue with the GVA patches that are applied however not well versed with the subject.
running VDADecoderChecker will cause a freeze
commenting out line 1018 in kern_rad.cpp however resolves the issue. 
VDADecoderChecker reports error -12473 and DRM is broken however to my understanding DRM patching with whatevergreen is currently broken anyway.

**Comment by khronokernel** [comment]
> commenting out line 1018 in kern_rad.cpp however resolves the issue.

If that's the case, why not apply the `disable-gva-support` property (or `radgva=0` boot-arg) to disable `enableGvaSupport`? Ensures `setGvaProperties(accelService)` is never called. 

* https://github.com/acidanthera/WhateverGreen/blob/master/WhateverGreen/kern_rad.cpp#L157-L158

I did notice that this property is not documented in WEG outside of the [Changelog.md](https://github.com/acidanthera/WhateverGreen/blob/866d2a127696f646abdc53e505c45ed6fcd9a964/Changelog.md) so we'll need to add some information to [FAQ.Radeon.en.md](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Radeon.en.md) to accommodate.

**Comment by Joshj23icy** [comment]
using `radgva=0` bootarg still results in a freeze when running VDADecoderChecker

**Comment by vit9696** [comment]
Hello, `radgva=0` is the right argument. If commenting out the `1018` works to solve the issue, then `radgva=0` should also work just fine. Please confirm that the WEG is loaded in this case and that the argument is set. Some GPUs indeed do not work well with GVA patches, and the right thing to do is to disable them with a device property (or a boot argument). These GPUs do not support hardware accelerated decoding at all.

Can reopen later if it is discovered that something else is broken.

**Comment by Joshj23icy** [comment]
`radgva=0` still resulted in the freeze, system does not freeze if weg is not loaded. the only thing that resolved the issue was adding the `disable-gva-support` property to the gpu. 
though i replied but evidently not. apologies

**Comment by vit9696** [comment]
Well, this is not really feasible from the code as long as the boot argument is actually added. I believe it is not. Perhaps you are adding it through NVRAM and forgot to Delete the existing property in the config.
