### ISSUE TITLE
 BrcmPatchRAM 2.6.1 Won't Work After Sleep

### ISSUE THREAD

**Issue by Andrw0830** [acidanthera/bugtracker#1869]
I upgraded to BrcmPatchRAM 2.6.1 on my Dell Inspiron 7567 (DW1560 WiFi/BT chip) and noticed when sleeping my laptop and waking from sleep, my Bluetooth shows it is off when I go into System Preferences > Bluetooth. This is running on official Monterey build 12.0.1. Toggling the BT on does nothing and I have to reboot my laptop to fix. The Bluetooth icon is showing the correct bold symbol without the cross during this issue.

More details is my laptop has an Intel 7700HQ with an Intel 630 GPU. I am using MacBookPro 14.1 as a SMBIOS and I have USBMap.kext added to patch my USB controller while my BT adapter is set to internal 255(FF) so everything is set properly. I haven't changed anything else since the last update so believe one of the new changes to allow you to toggle BT off and on might've caused this bug. 

Let me know if you need anything else? Thanks again for providing all these files for running Hackintosh as I know it takes a lot of work to maintain!

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/1821
