### ISSUE TITLE
OCLP - Virtualization disabled when option booting to Boot Camp partition

### ISSUE THREAD

**Issue by Converseallstar95** [acidanthera/bugtracker#1870]
I was referred here after posting an issue on the OCLP project here: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/738

khronokernel mentioned that if I was requesting rEFInd functionality for OpenCore to ask here, so below is my original message.

Historically, and normally (at least with my model MBP), when you have a macOS partition and Boot Camp partition, the only way to get virtualization enabled in Windows is by selecting Windows as the startup disk. When you just hold option at boot, it always shows disabled in Task Manager. When booting through OpenCore it acts as an option boot, thus disabling virtualization. Is there a way OC can add a patch or fix to this? I found a SO thread about how to fix it in rEFInd.

https://apple.stackexchange.com/a/234819

**Comment by mikebeaton** [comment]
For info from rEFInd docs:

Token | Possible parameters | Explanation
-- | -- | --
enable_and_lock_vmx | none or one of true, on, 1, false, off, or 0 | When set to true or a synonym, enable the CPU's VMX bit and lock the MSR. This configuration is necessary for some hypervisors (notably Microsoft's Hyper-V) to function properly. Activating it on other CPUs will, at best, have no effect, and could conceivably crash the computer, so enable it at your own risk! If your firmware supports activating these features, you should use it instead; this option is provided for users whose firmware does not provide this functionality. (Many Macs lack this configurability, for instance.) The default is false.

**Comment by vit9696** [comment]
Sounds like a good idea to add UEFI Quirk → EnableVmx.

**Comment by mikebeaton** [comment]
@Converseallstar95 Are you able to test with this build? https://github.com/acidanthera/OpenCorePkg/suites/4413615353/artifacts/116655825 It includes a new UEFI quirk `EnableVmx`. I have an MBP10,2 running Windows and Big Sur (and a bunch of Linuxes....) but I am unable to replicate the issue, however I believe the quirk should do what you need.

**Comment by mikebeaton** [comment]
PS It would be very helpful to have a debug log, obviously if it doesn't work, but even if it does, actually - so I can check that it is doing what I expect, on hardware which shows the problem. Thanks.

**Comment by Converseallstar95** [comment]
@mikebeaton Yes I can most likely test whatever you'd like and get you the necessary logs, but I would need help walking through it. Do you have a discord?

**Comment by mikebeaton** [comment]
> @mikebeaton Yes I can most likely test whatever you'd like and get you the necessary logs, but I would need help walking through it. Do you have a discord?

Hi - I am most likely to see it if you could contact me using element.io at @mikebeaton:matrix.ispras.ru (if you sign up and you don't already have a home server, just use :matrix.org). Or simply pm me Bmju on Macrumors.

**Comment by mikebeaton** [comment]
@Converseallstar95 - Not sure if you got my last message on Macrumors, but khronokernel has kindly volunteered to make a test version of OCLP with this change in it - which should be the best and easiest like-for-like test. If you could get a moment to test using this it would be really helpful (as I really need to see exactly what happens on a machine which is showing the bug before pushing this live, and none of ours do). If you can contact him on OCLP Discord when you get a chance, that would be great! Thanks.

**Comment by Converseallstar95** [comment]
> @Converseallstar95 - Not sure if you got my last message on Macrumors, but @khronokernel has kindly volunteered to make a test version of OCLP with this change in it - which should be the best and easiest like-for-like test. If you could get a moment to test using this it would be really helpful (as I really need to see exactly what happens on a machine which is showing the bug before pushing this live, and none of ours do). If you can contact him on OCLP Discord when you get a chance, that would be great! Thanks.

Just replied to you on MacRumors; I'll get to it this weekend. Thank you for the help!

**Comment by mikebeaton** [comment]
Now tested - thanks @khronokernel and @Converseallstar95 .

Fixed by https://github.com/acidanthera/OpenCorePkg/commit/9d5fc5f4f7c8b7ce5469a5e8f59d689034dde5c4

**Comment by PlugNPush** [comment]
OCLP 2.4.0 user here, where can I find this option nowadays please?

**Comment by mikebeaton** [comment]
> OCLP 2.4.0 user here, where can I find this option nowadays please?

That is an [OCLP/Dortania support issue](https://github.com/dortania/bugtracker), not Acidanthera, but I think it is meant to be enabled automatically by OCLP on machines which need it: https://github.com/dortania/OpenCore-Legacy-Patcher/commit/37769e052a
