### ISSUE TITLE
ac adaptor status change can't be detected with smcbatterymanager

### ISSUE THREAD

**Issue by Mkhairy0100** [acidanthera/bugtracker#1871]
my laptop is Asus TP500LNG haswell
using ECenabler and smcbatterymanager
battery indicator is working and percentage of battery works fine 
it detects ac power adaptor connected if I booted Mac OS with adaptor connected or wake from sleep
but can't be detected if I connect or disconnect during Mac OS running 
IOReg uploaded 
thanks on advance
[MK’s MacBook Pro.zip](https://github.com/acidanthera/bugtracker/files/7571623/MK.s.MacBook.Pro.zip)

**Comment by vit9696** [comment]
At a glance it looks like a configuration issue. I will close this but let others reopen in case more technical details are uncovered. CC @usr-sse2 @1Revenger1 @zhen-zen.

**Comment by usr-sse2** [comment]
Does the adapter detect failure happen only when the battery is fully charged or always? Please also show the DSDT.

**Comment by Mkhairy0100** [comment]
always there is a failure on detection of adaptor
[System DSDT.zip](https://github.com/acidanthera/bugtracker/files/7577190/System.DSDT.zip)

**Comment by usr-sse2** [comment]
Please also make a debug log:
boot with `-batman=0xFFFFFFFF -sbatdbg liludump=300` with debug versions of Lilu, VirtualSMC and SMCBatteryManager and attach the `/var/log/Lilu_X.Y.Z_U.V.txt` file (in my case it's named `Lilu_1.5.7_21.1.txt`).

**Comment by Mkhairy0100** [comment]
here is it
[Lilu_1.5.7_21.1.txt](https://github.com/acidanthera/bugtracker/files/7577232/Lilu_1.5.7_21.1.txt)

**Comment by vit9696** [comment]
I think macOS removes all the boot arguments starting with `-s`, use `-liludbgall` instead of `-sbatdbg`.

**Comment by Mkhairy0100** [comment]
sorry for delay I was out of door
[Lilu_1.5.7_21.1.txt](https://github.com/acidanthera/bugtracker/files/7587692/Lilu_1.5.7_21.1.txt)

**Comment by Mkhairy0100** [comment]
any help ?
