### ISSUE TITLE
SMCBatteryManager percentage status

### ISSUE THREAD

**Issue by Ab2774** [acidanthera/bugtracker#1872]
When I unplug the power adapter, macOS shows "LOW BATTERY" message, it shows at any level of charging regarding how much percentage is left, this bug occurs occasionally every time I unplug the power after charging using the AC adapter, I've tested it with ECEnabler and traditional ACPI battery patching, I don't know what's causing this bug, I thought it'll be solved by loading ACPIACAdapter, but it doesn't seem the cause.

https://user-images.githubusercontent.com/60307632/142702401-c5528cb6-fb85-415e-9976-c421b3075efc.mov
![Screen Shot 2021-09-15 at 4 02 34 PM](https://user-images.githubusercontent.com/60307632/142702406-449fb8d2-3171-4820-bf5e-0d17e90ec9e5.png)

[Abdulrahim’s MacBook Air.zip](https://github.com/acidanthera/bugtracker/files/7573340/Abdulrahim.s.MacBook.Air.zip)

**Comment by vit9696** [comment]
At a glance it looks like a configuration issue. I will close this but let others reopen in case more technical details are uncovered. CC @usr-sse2 @1Revenger1 @zhen-zen.

**Comment by usr-sse2** [comment]
Looks like your DesignCapacityOfLow or DesignCapacityOfWarning is set too high (probably greater or equal than its full capacity). Unfortunately AppleSmartBatteryManager doesn't expose these values in the IORegistry, so it's needed to add logging.

**Comment by Ab2774** [comment]
> Looks like your DesignCapacityOfLow or DesignCapacityOfWarning is set too high (probably greater or equal than its full capacity). Unfortunately AppleSmartBatteryManager doesn't expose these values in the IORegistry, so it's needed to add logging.

So should I provide logs?

**Comment by Ab2774** [comment]
[Archive.zip](https://github.com/acidanthera/bugtracker/files/7579684/Archive.zip)
@usr-sse2, let me know if you need more.
