### ISSUE TITLE
OpenCore kext name length limitation

### ISSUE THREAD

**Issue by CharlieJiangXXX** [acidanthera/bugtracker#1873]
Hi there,
I noticed that OC limits the length of the path of kexts (executables/info) to 128 - which means that they cannot have super long names. Is there a way to go around this? Or is it possible to dynamically allocate the name buffers in OpenCore instead of making it a predetermined value?
Regards

**Comment by vit9696** [comment]
All path strings are limited by this size at the moment. So far we have not hit this limitation yet, and personally believe it is reasonable to avoid extra delays caused by the file system driver. Feel free to post your use-case, but we are unlikely changing it in the nearest future.

**Comment by CharlieJiangXXX** [comment]
Actually, I encounter this issue in my current scenario. One kext has a really long name, and it is also a plug-in of another kext. Consequently, the final path is extremely long and OC can’t recognize it fully.

**Comment by vit9696** [comment]
Well, I guess renaming the kext or taking it out of the plugin directory should resolve the issue.
