### ISSUE TITLE
OpenCore chained from GRUB fails in secure boot

### ISSUE THREAD

**Issue by mikebeaton** [acidanthera/bugtracker#1874]
As reported by @Xefyr0 at the end of https://github.com/acidanthera/bugtracker/issues/1637 there appears to be a separate bug whereby OpenCore chained from GRUB under secure boot will start but then hangs early. While this is not particularly a recommended setup (we are trying to give as little reason as possible to need to chain OC from other bootloaders), I believe it also should work, and it would be good to get clear on why it is failing.

---

> I've only now updated from OC 0.6.9->0.7.5. The fix you've provided works perfectly, except when UEFI Secure Boot is enabled. When that is the case I'm able to boot using OpenCore.efi with no issue directly from the firmware, but since Vault and UEFI Secure Boot are the last things one does to an EFI after disabling anything used for debugging, trying to chainload OpenCore.efi from GRUB resulted in the boot hanging on a black screen.
> 
> With that in mind I made a different OC folder that had a bunch of the debugging settings enabled, signed it and tried to boot it. As with before, booting directly from the firmware worked fine but booting from GRUB failed. That folder, the OC log that came from the boot attempt, my grub config entry for OpenCore and a photo of the onscreen log before it disappeared are all attached in a .zip file if you'd like to take a hack at this. If not, I understand and will continue using the workaround.
[Debug_boot.zip](https://github.com/acidanthera/bugtracker/files/7575423/Debug_boot.zip)

**Comment by mikebeaton** [comment]
Hi @Xefyr0 - If I've understood correctly, then the debug folder that you've sensibly created should chain and start fine with secure boot turned off. Please could you also send the OC log generated from doing that.

**Comment by Xefyr0** [comment]
Of course. I included a copy of the OC log generated from booting the debug folder within the zip folder I had sent, but I'll share it here as well.
[OCLog.txt](https://github.com/acidanthera/bugtracker/files/7577252/OCLog.txt)
.

**Comment by mikebeaton** [comment]
Sorry, I wasn't clear, I want a log of the debug folder booted with secure boot temporarily turned off in the BIOS.

**Comment by mikebeaton** [comment]
Hi @Xefyr0 

Shout if you think I've misunderstood something you're saying. I may have! I think it's:

1. OC chained from GRUB works fine with UEFI Secure Boot off
2. If you turn on UEFI Secure Boot (i.e. in your BIOS) then GRUB starts, but OC chained from GRUB fails with a secure boot failure message (since it's not signed)
3. If you then proceed to sign and vault OC, and add your private signing key to the BIOS secure boot db, then OC chained from GRUB fails with a black screen
4. So you made a signed, vaulted DEBUG version of OC, and proceeded to chain OC in the same way (i.e. with BIOS Secure Boot still on) using this debug setup - and it still fails to get to the OC bootpicker - and you got the logs you sent me

If that's all correct, then I just need info about what happens and a debug log from chaining your _unchanged_ debug OC folder in exactly the same way from GRUB, with the only change being that you turn off Secure Boot in BIOS first.

If I've misunderstood and (perhaps?) you're not using BIOS Secure Boot at all, but just the OC setting, then that's fine, but a slightly different line of research - just say.

I would also like to know which motherboard or which Apple hardware you are using, and also - in case it turns out to be relevant, since a lot of what OC secure boot does is related to macOS - which version of macOS you have installed.

**Comment by Xefyr0** [comment]
To clarify yes, I'm using the BIOS secure boot and most of what you say is true but the one difference is in the 3rd point: The DEBUG version of the OC folder was signed but NOT vaulted, and stops on the "Watchdog status is 0" line which is shown in the screenshot I shared previously.

The OC log from the signed, but not vaulted DEBUG OC folder and BIOS secure boot turned off, chain loaded from GRUB is attached.
[opencore-2021-11-23-211902 (SB Disabled, GRUB chainloaded).txt](https://github.com/acidanthera/bugtracker/files/7591144/opencore-2021-11-23-211902.SB.Disabled.GRUB.chainloaded.txt)

I'm not using Apple hardware but rather a Lenovo X1 Extreme Gen 3 laptop (Type# 20TK001JUS) which appears to have some non-standard(?) motherboard. The product specification reference can be found in pdf format [here](https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_X1_Extreme_Gen_3/ThinkPad_X1_Extreme_Gen_3_Spec.pdf)
And my macOS version is Catalina, 10.15.7.

**Comment by mikebeaton** [comment]
Okay, from comparing the two logs, it looks as if when OC is chained from GRUB then it gets to trying to start the loaded jumpstart APFS driver, but then just silently hangs. Whereas this starts no problems when OC is not chainloaded. Not too clear why this would be (especially the hang with no error message).

The other difference between the two logs is that in the log when it works (i.e. not chainloaded) it hits "OCABC: Recovering trashed GetMemoryMap pointer" when starting each driver, but in the chainloaded version which hangs, it does not hit this. Again not sure why.

@vit9696 if you had a minute, do you have any suggestions?

**Comment by mikebeaton** [comment]
@Xefyr0 Would you be able to provide the log of booting the debug OC directly (not chainloaded)? Preferably once with Secure Boot on and once with it off, if that's okay. I feel this might add useful additional info, although I'm not quite sure what, without trying it! (Based on your description, I assume both those tests would definitely start, so I'd be mainly looking at the other differences I mentioned in the logs.)

**Comment by Xefyr0** [comment]
Of course. Both tests definitely started, and to repeat things the only times a test didn't start was when BIOS secure boot wasn't configured correctly (which is expected) or when Secure Boot was enabled in BIOS but GRUB was chainloading OpenCore.efi directly (which is the issue at hand)
[opencore-2021-11-23-212117 (SB Disabled, booted from firmware).txt](https://github.com/acidanthera/bugtracker/files/7591450/opencore-2021-11-23-212117.SB.Disabled.booted.from.firmware.txt)
[opencore-2021-11-23-211510 (SB Enabled, booted from firmware).txt](https://github.com/acidanthera/bugtracker/files/7591451/opencore-2021-11-23-211510.SB.Enabled.booted.from.firmware.txt)
.

**Comment by mikebeaton** [comment]
Those two logs confirm that "OCABC: Recovering trashed GetMemoryMap pointer" is just present when Secure Boot is _not_ enabled. Still not quite sure why, but makes it look to me as if that's not a clue to the specific problem of fai

**Comment by mikebeaton** [comment]
[Closed in error - fat fingers on mobile screen - reopening]

**Comment by vit9696** [comment]
APFS is loaded by our PE loader due to SecureBoot requirements. This is done by overriding LoadImage and StartImage interfaces. GRUB2 does such an override as well. We should add DEBUG prints to these methods to see whether they are called and where exactly does the code hang.

I think recovering the trashed pointer is irrelevant to the issue. Likely there is something with the overriding part. I think that is all I can add here.

**Comment by mikebeaton** [comment]
@vit9696 When we call anything which has been hooked by GRUB2 Shim (namely gBS LoadImage, StartImage, Exit and ExitBootServices) then, regardless of whether we have since hooked it ourselves, Shim resets at least some of the hooked pointers (and not just the hook for the method called) back to the values they had at the time Shim first hooked them e.g. https://github.com/rhboot/shim/blob/main/replacements.c#L56-L72 (all the offending code is in this one file).

By saving and restoring all four hooked values around calls to the original `mOriginalEfiLoadImage` and `mOriginalEfiStartImage` in `ImageLoader.c` you can force it to work.

I think, from looking at the GRUB and OC code, that a similar save and restore around calls to the original `mOriginalEfiExit` would also be needed; but that possibly nothing is needed around calls to the original of `ExitBootServices` (as hooked in `ServiceOverrides.c`), since it is the end of everything anyway?

Possibly this is worth a quirk? `SurviveShim`? 😉 `ShimPreserveHooks`?

**Comment by vit9696** [comment]
This is disgustingly ugly. But I guess expected, given the log. We have `ProtectUefiServices`, which is intended to protect from such ugly behaviour. Perhaps just extend it? CC @mhaeuser

**Comment by mikebeaton** [comment]
@Xefyr0 You are developing quite the skill for detecting bugs in obscure corners of OC!

We think this should fix it for you (I could replicate more or less the same bug on my machine, too - it's basically fundamentally caused by something a bit evil which GRUB shim does - as above - which we can work around, however):

https://github.com/acidanthera/OpenCorePkg/suites/4462615005/artifacts/118607100

A debug log of this running (esp. chained from GRUB with BIOS SB on, i.e. the one which did not work before; but all four combinations of chained,direct X SB on,off if you had the time) would be very helpful.

**Comment by mikebeaton** [comment]
Should be fixed by https://github.com/acidanthera/OpenCorePkg/commit/8069ce4f9df56d678f80bdbb81ed88ffd43acec0

(Is definitely fixing a very similar - almost certainly the same - issue here.)

If you get a chance to report back on how this works at your end @Xefyr0  please do.
