### ISSUE TITLE
my laptop battery work native but smc battery manger kext have problem 

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#1875]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

laptop : HP-da1023nia 

I disable ecenable.kext and only use smcbatterymanger.kext 

IORegistry :
[ioreg.zip](https://github.com/acidanthera/bugtracker/files/7583639/ioreg.zip)

efi :
[OC.zip](https://github.com/acidanthera/bugtracker/files/7583651/OC.zip)

problem :

laptop adapor 60w and show 300w:
![IMAGE 1400-08-27 12:48:29](https://user-images.githubusercontent.com/35195176/142386921-cf43af06-2bf0-416f-b481-bd63ee3cb616.jpg)

and after show using adapter :

![IMAGE 1400-08-27 12:53:51](https://user-images.githubusercontent.com/35195176/142387660-da2a1ac7-d360-44b7-b752-5c1957e6c84a.jpg)

![IMAGE 1400-08-27 12:48:22](https://user-images.githubusercontent.com/35195176/142387206-6b38b051-7f89-4e84-9bc2-11ebada00637.jpg)

and after back to charging : 

![IMAGE 1400-08-27 12:48:25](https://user-images.githubusercontent.com/35195176/142387461-60556bd7-5195-464b-a14c-4326939c9792.jpg)

![IMAGE 1400-08-27 12:48:35](https://user-images.githubusercontent.com/35195176/142387495-4373e386-4ec7-446d-a470-b34ca266dad7.jpg)

**Comment by Edwardwich** [comment]
One person one person change charging with wattage

**Comment by Edwardwich** [comment]
@Andrey1970AppleLife

**Comment by vit9696** [comment]
This sounds like an ACPI error, where the batteries are not merged or something like that. Closing as a configuration issue.

CC @usr-sse2 @1Revenger1 @zhen-zen @lvs1974 just in case.

**Comment by zhen-zen** [comment]
The model doesn't have a second battery in the spec.

The abnormal value in wattage reading might be related to sampling interval. It's inevitable if the vendor calculates the value in ACPI. I don't think it worth to add additional filtering. Probably mark as a known issue and won't fix.

**Comment by Edwardwich** [comment]
> The model doesn't have a second battery in the spec.
> 
> The abnormal value in wattage reading might be related to sampling interval. It's inevitable if the vendor calculates the value in ACPI. I don't think it worth to add additional filtering. Probably mark as a known issue and won't fix.

Don't need check apci oprgin ?
