### ISSUE TITLE
Opencanopy: video qxl driver gives issue, messed graphics - Different results

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1876]
Hello!
A user belonging to a community where we virtualize mac os shared with me a strange issue about opencanopy.
He is running mac os Monterey 12.0.1 in qemu, with qxl graphic driver, connecting to the vm with vnc, with a very basic setup (penryn cpu emulated).
Everything is working good apart opencanopy, which has messed graphics:
![1388257713_ScreenShot2021-11-21at1_55_13pm thumb png 2c37dcb3bff778ec94dd06cdd9c8552b](https://user-images.githubusercontent.com/18054052/143026030-430ab41d-e5f1-46fb-94c9-c5836533be5b.png)

![1709330180_ScreenShot2021-11-21at1_55_24pm thumb png 7ebfe935b41509fe42be83e2c10756eb](https://user-images.githubusercontent.com/18054052/143026757-26535077-6d54-419b-8e5f-b7c10e26a92f.png)

He shared with me both the libvirt xml and the opencore.img file which contains the bootloader and it's virtualized as a sata disk.
Here the strangest thing:
I setup the same vm with his xml code (I only replaced the installation disk of monterey with a virtual disk with an existing installation), using exactly the same opencore.img, and for me everything is ok!
Since the hardware is all virtualized and since we are using exactly the same opencore, we can't understand why for him opencanopy shows this strange issue.
Here is his opencore log (it's a test vm, so no need to mask data), but it seems there's nothing strange in it.
Config.plist is also attached.
[opencore-2021-11-23-085151.txt](https://github.com/acidanthera/bugtracker/files/7588032/opencore-2021-11-23-085151.txt)
[config.txt](https://github.com/acidanthera/bugtracker/files/7588041/config.txt)

**Comment by jafd** [comment]
I'm pretty much shooting in the dark, but one thing to check is that the resolution OpenCanopy thinks it's running, the resolution you configure via QEMU command line parameters in any way (what is your VNC server reporting?), and the resolution in the OVMF variables (in the boot manager, accessible when you press Esc when it's starting up) all need to match, or you're going to see artifacts in either OpenCanopy, or on the macOS's boot screen, or in the OS itself — or, if you're really unlucky, in all three.

**Comment by 82ghost82** [comment]
Thank you very much for the reply, it's indeed related to ovmf, I provided a fresh copy of that files and the issue went away.
