### ISSUE TITLE
DebugEnhancer: IOLog() handling possible?

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#1878]
Is it possible to divert IOLog() to kprinitf()/printf()? With boot args switch probably.

**Comment by vit9696** [comment]
Should be doable. CC @lvs1974

**Comment by lvs1974** [comment]
@nms42: please try attached version with boot-arg "-dbgiolog".
[DebugEnhancer-1.0.5-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7656495/DebugEnhancer-1.0.5-DEBUG.zip)

**Comment by nms42** [comment]
On quick check LGTM (Looks Good To Me). Thanks

**Comment by lvs1974** [comment]
In master branch: https://github.com/acidanthera/DebugEnhancer.
