### ISSUE TITLE
OpenCore on Genuine Apple HW ?

### ISSUE THREAD

**Issue by juanpc2018** [acidanthera/bugtracker#1879]
Hi,
 
i write to ask....
#1.
¿If is possible to run OpenCore in a Genuine Apple Hardware,?
to camouflage the original SMBIOS with another...
and overcome Apple limitations "Forbiden Logo"
example:
Run OSX 10.6.8 in MacMini 2011, 2012, 2014, 2018, MacPro5,1 2012, MacPro6,1 2013, and MacPro7,1 2019
Run OSX 10.9.5 in MacMini 2014, 2018 and MacPro7,1 2019
Run OSX 10.13.6 in MacMini 2018 and MacPro7,1 2019

Emulating MacPro5,1 2010 SMBIOS that is compatible from OSX Snow to OSX Mojave
or MacPro6,1 SMBIOS that is compatible from OSX Mavericks to OSX Monterey.

could Not find answer here:
https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html#mac-pro

The Reason to Run Older OSX in Newer Apple HW is:
to support discontinued 3rd party SW & HW.
Example:
SCSI to Firewire devices like Vintage Film Scanners
Native Firewire devices like Sound interfaces.
Older Software that does Not have updates for new OSX required in New HW,
example: Roseta 1 PPC G4 emulator included in OSX Snow Leopard.

The Only problem i see Running Older OSX in New HW 
is the Thunderbolt to FireWire adapter, 
New HW does Not have FireWire Native,
requires optional Apple TB to FW adapter.
but older OSX SnowLeopard does Not have drivers for TB nor FW adapter.
some situations could be pointless to run older OSX in New HW.
Syba & Sonnet had nice FireWire400/800 PCIe add-on cards with Ti chip and other,
but is unknown if Ti chip will be detected by OSX SnowLeopard 10.6.8

example: Apple USB2.0 to 100Mbps Ethernet RJ45 adapter,
has Axis IC, and requires drivers in older OSX. available in Axis website.

#2. Windows 8l,1 does Not boot from Thunderbolt, Nor USB3.0 chip,
only from SATA and USB2.0 Chip.
does OpenCore allow to boot Windows from USB3.0 or TB?

https://en.wikipedia.org/wiki/Mac_Pro#Supported_macOS_releases
https://en.wikipedia.org/wiki/List_of_Mac_Mini_specifications#Supported_macOS_releases
https://en.wikipedia.org/w/index.php?title=Mac_Mini&oldid=1045359439#Supported_macOS_releases

**Comment by TheHackGuy** [comment]
1)
There's oclp for running newer macos on unsupported Apple hardware. https://dortania.github.io/OpenCore-Legacy-Patcher/

2) I'm not sure if oc supports thunderbolt drives.

**Comment by mhaeuser** [comment]
Yes, it is possible. This is a technical bugtracker, please use user channels like the forums for support.
