### ISSUE TITLE
[Feature Request] Adjust resolution setting to take refresh rate into account

### ISSUE THREAD

**Issue by GreyAsteroid** [acidanthera/bugtracker#1882]
Setting resolution for OpenCore follows the WxH@Bpp format which does not include refresh rate and the Max setting does not take into account refresh rate. For monitors with a lower than maximum refresh rate set as the default this causes flickering during boot because of mode changes. Either allowing users to specify refresh rate or adjusting the Max option to take refresh rate into account would fix this.

**Comment by vit9696** [comment]
UEFI specification does not support refresh rate. There is no place for us to set it.
