### ISSUE TITLE
No assets/download provided in OpenCorePkg Release 0.7.6

### ISSUE THREAD

**Issue by armenio** [acidanthera/bugtracker#1884]

**Comment by armenio** [comment]
I think it is not invalid as the title are clearly.
If not, look at the attached image:

![Screen Shot 2021-12-06 at 2 19 27 PM](https://user-images.githubusercontent.com/349304/144891923-2e3d5ed8-4199-4c90-afbf-e4c554722e26.png)

**Comment by armenio** [comment]
Now, the 0.7.5 release for comparison purpose:

![Screen Shot 2021-12-06 at 2 21 13 PM](https://user-images.githubusercontent.com/349304/144892113-0186ed33-01fb-4719-b400-8b6aed241a73.png)

**Comment by vandroiy2013** [comment]
Wait until GitHub Actions finishes compile builds. Binaries will be in an hour. Deployment process is automated.
