### ISSUE TITLE
UIScale problem. is it a bug or a config problem?

### ISSUE THREAD

**Issue by telepati** [acidanthera/bugtracker#1886]
After changing UIScale, the first stage is OK but after blink apple logo is getting bigger. I tested all scale modes but it didn't make any difference. Yes, I reset NVRAM after each change. I made a video that the problem is clearly seen on this video. I want to see the logo as it was in the first stage. is this a bug or config problem?

Graphics and Connection type;
UHD 630, Connection Type is DP.

[IMG_0137.mov.zip](https://github.com/acidanthera/bugtracker/files/7668553/IMG_0137.mov.zip)
.

**Comment by vit9696** [comment]
You have UIScale set to 1, but your macOS is configured to use HiDPI mode. For whatever reason the change you make in the config does not apply. No config.plist, no log, no hardware info. Closing as invalid.

**Comment by telepati** [comment]
Just a note: It is not set to 1, in the video is set to -1.

**Comment by vit9696** [comment]
`-1` means ignore. In this case `1` is assumed by both OpenCore and boot.efi, thus the small logo on the first stage.

If you believe that the first and second stages have matching scaling (e.g. 100%/1x or 200%/2x) but they have different logos, then your resolutions do not match. It is possible that your GPU cannot make the resolution of your screen in UEFI, thus the problem.

**Comment by telepati** [comment]
Actually, I think this problem is related to DisplayPort. I recently replaced my monitor. My previous monitor was using mDP connection and there was no such problem. It has such a problem with the DisplayPort connection on the new monitor. Actually, all my settings are the same. I didn't make any changes. I'm attaching the logs though, just in case it helps
[Logs.zip](https://github.com/acidanthera/bugtracker/files/7669496/Logs.zip)
.
