### ISSUE TITLE
ControlMsrE2 and CFGlock for MSR 0xE2

### ISSUE THREAD

**Issue by VinylNerd** [acidanthera/bugtracker#1887]
Hello, i am sorry if this is not the best place to post, but i come to the conclusion that the OpenCore Documentation is not correctly addressing this information

i have T440P and i want to use CFGlock.efi, or ControlMsrE2.efi to unlock my CFG lock, as per my research it seems that this CFGlock.efi has been included in ControlMsrE2 as of opencore 0.6.7 or so

if i run ControlMsrE2 i have no option to use CFGlock

in the documentation it sais 

"On selected platforms, the ControlMsrE2 tool can also change such hidden options. Pass desired argument: lock, unlock for CFG Lock. Or pass interactive to find and modify other hidden options. "

however i can't find anywhere which tells me how i can pass these arguments

thanks

**Comment by vit9696** [comment]
`interactive` is rendered in the documentation with a monospace font. In technical docs this means special keywords. For this particular case it means that you should literally pass `interactive` as an argument. I.e. in UEFI Shell.

If ControlMsrE2 does not work on your system, it means it is incompatible. In this case you can try to use GRUB Shell.

**Comment by VinylNerd** [comment]
@vit9696 thanks, please excuse that i am having a hard time to grasp what you are saying.

i do have a good feeling ControlMsrE2 will work, however i still dont understand how to use it properly provided this info above and the documentation.

i also cant understand why i would choose the interactive arguement rather than the "unlock" arguement 

i have added ControlMsrE2.efi to my tools folder on a USB EFI, i have set the arguement to "unlock" however i have not run it out of fear of bricking my system, purely because some other guides which said "The EFI must not be able to boot MacOS, it must just be able to show the picker."

so does this mean i need to disconnect my hard drive or break opencore so it can't boot? it just doesnt make sense to me.

thanks!

**Comment by VinylNerd** [comment]
@vit9696 if i read back through this issue https://github.com/acidanthera/bugtracker/issues/1751 i can also see that the documentation is still not properly explaining this situation for haswell users like myself, for example it implies that we should be using AppleCpuPmCfgLock quirk when in reality its not needed for haswell. it seems there are about 10 different ways to unlock CFG lock but CFGlock.efi seems the best by far, however in my reading it seems for T440P i may need to do a bios mod

**Comment by vit9696** [comment]
`AppleCpuPmCfgLock` is needed for Haswell on 10.8.x. ControlMsrE2.efi does not work on APTIO IV (Haswell).

**Comment by Striker770** [comment]
@vit9696 

Is this correct?
![Screen Shot 2022-05-07 at 7 26 08 PM](https://user-images.githubusercontent.com/44955309/167257420-fec5704b-5245-4943-b8a6-169d24b1c371.png)


Also, on a side note, Ivy Bridge and Ivy Bridge-E are XCPM capable, so AppleXcpmCfgLock should be enabled?
