### ISSUE TITLE
EnableVmx not included in 0.7.6 Configuration.pdf

### ISSUE THREAD

**Issue by jfredrickson** [acidanthera/bugtracker#1888]
The Configuration.pdf distributed with 0.7.6 is missing an entry for the EnableVmx option. Found this when `ocvalidate` complained about the missing entry after updating config.plist from 0.7.5 to 0.7.6. I caught it before rebooting, so not sure what effect it would have on startup if this item was missing from config.plist.

**Comment by vit9696** [comment]
You are right. Sorry for that, please use https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf for the time being.

**Comment by vit9696** [comment]
The correct PDFs were additionally published on https://github.com/acidanthera/OpenCorePkg/releases/tag/0.7.6.
