### ISSUE TITLE
[patch] Do not use include files from build engine

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#1891]
Host build engine dependency is not good. Patch compile checked on macos (XCODE5, CLANGPDB), ms visual studio (VS2019 - actually VS2022) and FreeBSD (CLANGPDB)

[oc.diff.txt](https://github.com/acidanthera/bugtracker/files/7696633/oc.diff.txt)
.

**Comment by vit9696** [comment]
According to ISO/IEC 9998 2018-4:

> The two forms of conforming implementation are hosted and freestanding. A conforming hosted implementation shall accept any strictly conforming program. A conforming freestanding implemen- tation shall accept any strictly conforming program in which the use of the features specifed in the library clause (Clause 7) is confned to the contents of the standard headers <float.h> , <iso646.h> , <limits.h> , <stdalign.h> , <stdarg.h> , <stdbool.h> , <stddef.h> , <stdint.h> , and <stdnoreturn.h> . A conforming implementation may have extensions (including additional library functions), provided they do not alter the behavior of any strictly conforming program. 4)

Given that we are freestanding in EDK II, we are allowed to use these headers. These headers should be provided by the build environment, i.e. the compiler. If this does not happen, you should report this issue to the environment you have issues with.
