### ISSUE TITLE
Test situation after Windows10 VS2019 build OpenCore

### ISSUE THREAD

**Issue by wy414012** [acidanthera/bugtracker#1893]
Good weekend everyone, maybe this is a build error:
- At the core of the Windows VS2019 build, only the DEBUG version can boot the system. Is this an error in the build?
- I used the latest submission of Windows VS2019 to build and test and found that only the DEBUG version can boot the system correctly, and the screen goes black after REL chooses to start the USB driver.

**Comment by mikebeaton** [comment]
Builds on systems other than XCODE5 are unsupported. They are present (amongst other reasons) for the additional code-checking coverage they provide during CI.

**Comment by wy414012** [comment]
Okay, thanks for your reply.

**Comment by vit9696** [comment]
To make it clear, there may be a bug in OpenCore, but we are not ready to investigate the problem. Feel free to send a patch.
