### ISSUE TITLE
Strange crash on VoodooPS2 and MacOS Monterey

### ISSUE THREAD

**Issue by PoMpls** [acidanthera/bugtracker#1895]
Hello...

I have a Lenovo ideapad 520s 14iKB laptop, running with MacOS MOnterey 12.0.1, everything works perfect, but when I reboot from MacOS, the keyboard stops working, I cannot enter the bios, nor use it in the OpenCore selector, if I let it The system starts automatically, once MacOS is loaded it works.

But whenever you restart from MacOS, the keyboard disappears at startup, and if you have Filevault activated, it is impossible to start the computer because when you can the password, the keyboard still does not work ... all that remains is to connect a USB keyboard, or start windows , because if windows is started and the laptop is restarted, the keyboard already works again, ..

I think it has to be something related to VoodooPS2, because if I remove the kext, and reboot, the keyboard works fine at startup.

It only happens with Monterey, with no other operating system this happens ...

There are some people more affected with the same problem:

https://www.reddit.com/r/hackintosh/comments/qn82qi/keyboard_problem_after_reboot_from_macos/

Greeting

**Comment by antoniomcr96** [comment]
The kext probably leaves the Kayboard in a bad state. It also happens with my LenovoL390 Yoga, but after hibernation. Since I don’t use FileVault, I don’t really care about it. I’m available for debugging

**Comment by 1Revenger1** [comment]
Do you guys mind seeing if 2.2.4 works correctly? I'm wondering if the logic for multiplexing is messing something up. Should be pretty easy to diff and fix if 2.2.4 works.

**Comment by PoMpls** [comment]
I have tried all versions xD

Even some older than 2.2.4, and the same thing happens in all of them.. 

And it only happens in Monterey, I have even tried 12.1 beta and it follows the same bug , In Big Sur everything is going well

If I select Legacy Boot in the bios, it doesn't happen, but every time I reboot the laptop tries to reboot, the bios screen appears, shuts down (probably due to not detecting the keyboard) and starts again, and the keyboard already works, but in Legacy Boot the sleep mode stops working properly

**Comment by Krazy-Killa** [comment]
I can also report that my Lenovo Yoga 370 does exactly this..  Both keyboard and trackpad fail to function after rebooting macOS.. Cannot access BIOS or use OpenCore Boot Picker except if I were to power off the machine entirely and restart which causes everything to work.  Sleep also causes issues as the keyboard will work for about 4 seconds, then fail with a repeating key sequence from a random key (usually the last key I press but cannot confirm).  Trackpad will work however and so does the touchscreen.

**Comment by tasco11xb** [comment]
I also have same problem with my Lenovo 8th Gen (S340-14IWL).
It have been rouble since first beta.

**Comment by tasco11xb** [comment]
> I have tried all versions xD
> 
> Even some older than 2.2.4, and the same thing happens in all of them..
> 
> And it only happens in Monterey, I have even tried 12.1 beta and it follows the same bug , In Big Sur everything is going well
> 
> If I select Legacy Boot in the bios, it doesn't happen, but every time I reboot the laptop tries to reboot, the bios screen appears, shuts down (probably due to not detecting the keyboard) and starts again, and the keyboard already works, but in Legacy Boot the sleep mode stops working properly

Exactly, legacy broke my sleeps.

**Comment by stevezhengshiqi** [comment]
Similiar issue: https://github.com/acidanthera/bugtracker/issues/1838
Also waiting for better solution.

**Comment by andreszerocross** [comment]
Got similar issue too in "Acer Swift 3 SF314-54G-51ZX (KabyLake-R) and Acer Swift 3 SF314-58G-51KV (WhiskeyLake)"

**Comment by richardkindom** [comment]
same problem with it on my T460. Plus keyboard stop responding after sleep. You can never wake up even if you touch power button.

**Comment by vit9696** [comment]
cc @zhen-zen @1Revenger1 @usr-sse2

**Comment by 1Revenger1** [comment]
[VoodooPS2Controller-2.2.8-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7826881/VoodooPS2Controller-2.2.8-DEBUG.zip)
Any luck with this version? Instead of disabling the keyboard, I sent F6 to set defaults but not disable. Works fine on my X1 Extreme.

**Comment by PoMpls** [comment]
Thank you very much, I am going to test it and I already report if it works well ;)

**Comment by antoniomcr96** [comment]
I tested the kext, unfortunately the problem persists (with VoodooPS2Mouse). VoodooPS2Trackpad, as before, works fine (keyboard works on reboot with crazy pointer, but this is another story)

**Comment by HeartAndSoul001** [comment]
same problem with it on my X1 Carbon 5th, it happened after hibernation that keyboard and trackpad didn't work, and closing lid then reopening didn't work. It looks like my laptop screen had been frozen. And in Big Sur, everything goes well.(I had reinstalled the macOS Big Sur other than the Monterey, and the problem only happened in Monterey)

**Comment by chubph** [comment]
> Hello...
> 
> I have a Lenovo ideapad 520s 14iKB laptop, running with MacOS MOnterey 12.0.1, .....

same situation with same laptop. hope for a fix soon or ill try with big sur.  Thank you for mentioning the problem

**Comment by JohnBrower** [comment]
Same here on Lenovo c340. A fix would be nice. 
For the moment I have to force shut down osx or I need to press power for 10sec on startup to get keyboard working again...

**Comment by mertst1** [comment]
Same problem with lenovo ideapad 330s and monterey…  i need help

**Comment by andrewvideo** [comment]
I have a very strange problem when using Opencore to dual boot in Windows and Mac. 
When Opencore cones up and boot in Windows everything is fine.  But if choose Mac OS and the next time I turn on the laptop my keyboard stops working and can't get in BIOS settings or even use Opencore with the keyboard. I have to hold down the power button for 60 seconds to drain all power to make the keyboard work again.  
But if I leave Opencore to timeout to boot into a OS the keyboard works in the system.     
I hope someone can stop this happening. I think the Bois getting corrupted.
I am have the Lenovo V330-15iKb and using the latest Opencore and Mac OS X 12.4

**Comment by arisingh8** [comment]
This remains an issue with macOS 12.4, OC 0.8.3, VoodooPS2 2.2.9, and my Lenovo Yoga 730-15IKB. coolstar's HIDPS2Keyboard seems to fix the reboot/shutdown issues, but my keyboard doesn't work after waking from sleep using that kext.

**Comment by win1010525** [comment]
Same problem on macOS 12.5.1, OC 0.8.3, VoodooPS2 2.2.9, my model is XiaoXin Air14-IML.
When using a kext called [HIDPS2Keyboard.kext](https://github.com/coolstar/HIDPS2Keyboard), it doesn't trigger this bug, but I can't use all Fn-keys.

**Comment by vit9696** [comment]
2.3.1+ should have resolved the issue.
