### ISSUE TITLE
Hide major macOS upgrades in Mojave (it works on newer versions of macOS)

### ISSUE THREAD

**Issue by Chibibowa** [acidanthera/bugtracker#1896]
Hi

I'll keep it short but as the title says, updates aren't hidden on macos Mojave specifically. It works on Big Sur (didn't test catalina tho) and I as wondering if you could backport that functionality to macos Mojave.

Basically, I would like to hide the "upgrade to macos monterey" in the settings app (software update tab) and by extension, removing the "1" logo on the icon and inside the app.

I know it's niche, but some users need macos mojave for the 32 bit support.

Thanks :)

![Screenshot 2021-12-13 at 12 02 57](https://user-images.githubusercontent.com/54556083/145801169-e535d9d6-4c7b-4edb-81df-f14308fa7b0f.png)

**Comment by Andrey1970AppleLife** [comment]
Ask Dortania.
