### ISSUE TITLE
Can't boot with "ProvideCurrentCpuInfo = Enable" in OpenCore 0.7.7 (Latest Commit)

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#1897]
With previous OpenCore version i can boot with this ""ProvideCurrentCpuInfo = Enable/True" but since latest commit (OpenCore r0.7.7) i can't boot and only stuck in "ExitBS Strat bla bla bla" in screen.

My computer specifications is,
Processor : Intel Core i7 6700
Motherboard : Gigabyte Z170X Gaming 7
VGA Card : Biostar RX 550

I know you will say that i don't need this quirck. But i just curious, with this quirks enable i still can boot in previous OpenCore version, in latest commit i should disable this quirk to boot. I know latest commit is merge CpuTopologySync features to this quirks (for alderlake).

So general processor should not enable this quirks??

I provide the debugs logs
[opencore-2021-12-13-141753.txt](https://github.com/acidanthera/bugtracker/files/7704511/opencore-2021-12-13-141753.txt)

**Comment by vit9696** [comment]
Yes, the behaviour is correct.
