### ISSUE TITLE
Extremely slow entering FileVault Preboot UI

### ISSUE THREAD

**Issue by qwqVictor** [acidanthera/bugtracker#1899]
Basic information:
- Computer: Dell XPS 9570 with latest BIOS 1.22.1 installed. (4K UHD, i7-8750H, 32GB RAM and 2TB WD Black SSD)
- Software: OpenCore 0.7.6 and macOS Monterey 12.1

I'm suffered from the slow speed entering FileVault Preboot UI. At most it takes 1.5 - 3 minutes to enter the Preboot UI from the Apple logo.
I have made some effort to fix this. For example, I have to use the `System` renderers instead of `Builtin` renderers because these renderers is laggy on XPS's UEFI. 
And not only entering the Preboot is slow. It's also extremely slow validating password of OpenCore and FileVault. I guess that maybe **the performance of doing hash stuff** in XPS's UEFI is to be blamed. But meanwhile BitLocker works great and without any lag.

Since the issue happens before the kernel starts, Lilu debugging log is not attached. The OpenCore debug log and OC directory without `PlatformInfo` and password is attached below. (I'm using the `MacBookPro15,1` SMBIOS.)

Thank you for your help.  

[opencore-2021-12-19-135810.txt](https://github.com/acidanthera/bugtracker/files/7740893/opencore-2021-12-19-135810.txt)
[OC.zip](https://github.com/acidanthera/bugtracker/files/7740900/OC.zip)
*(Due to GitHub file size limit, `Kexts` folder is also removed for it's not a kext-related bug)*

**Comment by blippercop** [comment]
"At most it takes 1.5 - 3 minutes"
Minimum is always 1.5min?

**Comment by blippercop** [comment]
I have the same issue (Big Sur - not 1.5min but on avg 30-60sec).

System is productive? Or are you up for a test?

DAGEROUS - SYSTEM MIGHT NOT BOOT ANYMORE:
- Disable SIP (?)
- backup on Desktop / USB drive: /System/Volumes/Preboot/{UUID}/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/loginui.efires 
- rm /System/Volumes/Preboot/{UUID}/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/loginui.efires 
- diskutil apfs updatePreboot / -noGlobalEFIGraphics

Now it takes me max 10 Seconds (multiple tests) to get to the password prompt.

This is just a test not a permanent solution.
Does that have any affect on the boot time?

**Comment by qwqVictor** [comment]
> "At most it takes 1.5 - 3 minutes"
> Minimum is always 1.5min?

Not really, sometimes it can take a few seconds (~30 secs).

**Comment by qwqVictor** [comment]
> I have the same issue (Big Sur - not 1.5min but on avg 30-60sec).
> 
> System is productive? Or are you up for a test?
> 
> DAGEROUS - SYSTEM MIGHT NOT BOOT ANYMORE:
> 
> * Disable SIP (?)
> * backup on Desktop / USB drive: /System/Volumes/Preboot/{UUID}/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/loginui.efires
> * rm /System/Volumes/Preboot/{UUID}/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/loginui.efires
> * diskutil apfs updatePreboot / -noGlobalEFIGraphics
> 
> Now it takes me max 10 Seconds (multiple tests) to get to the password prompt.
> 
> This is just a test not a permanent solution. Does that have any affect on the boot time?

Thanks but unfortunately, it works but it still has to take at least half an minute stuck at Apple logo. I guess it’s a performance issue about validating the kernelcache. But at all, it boost it up at worst case.

**Comment by aksm-unmei** [comment]
@qwqVictor not only your XPS. My Dell G7 7588 has same issue. It takes ~3 mins to enter FileVault login UI, sometimes system suddenly shutdowns after Apple logo .-.
I want to enable FileVault but because of that issue so I always turn off it.

**Comment by vit9696** [comment]
The issue with Dell laptops is generally pointer polling, which is touchpad polling for a laptop. For some reason touchpads on Dell are often very slow to respond to GetState. There are several ways to make this better, but I am not sure whether all my memories are up to date to the codebase (cc @mikebeaton):

- Simply move the touchpad constantly while loading, it should reduce the delay significantly, so that you are able to confirm it is the touchpad.
- Try removing Ps2KeyboardDxe.efi driver. It may be incompatible and you generally do not need it.
- Try enabling PointerSupport and check whether it works in OpenCanopy.
- Try adding Ps2MouseDxe.efi driver if the mouse is broken in OpenCanopy.
- Try disabling GraphicsInputMirroring.
- Try increasing TimerResolution (e.g. 10 times, 100 times, 1000 times) or even turning it off 0.
- Try playing with AppleInput values and KeyForgetThreshold.

**Comment by vit9696** [comment]
There interestingly is a bugreport partially related to this issue: https://github.com/acidanthera/bugtracker/issues/721. Partially, because Dells are generally AMI, not Insyde.

**Comment by qwqVictor** [comment]
> The issue with Dell laptops is generally pointer polling, which is touchpad polling for a laptop. For some reason touchpads on Dell are often very slow to respond to GetState. There are several ways to make this better, but I am not sure whether all my memories are up to date to the codebase (cc @mikebeaton):
> 
> * Simply move the touchpad constantly while loading, it should reduce the delay significantly, so that you are able to confirm it is the touchpad.
> * Try removing Ps2KeyboardDxe.efi driver. It may be incompatible and you generally do not need it.
> * Try enabling PointerSupport and check whether it works in OpenCanopy.
> * Try adding Ps2MouseDxe.efi driver if the mouse is broken in OpenCanopy.
> * Try disabling GraphicsInputMirroring.
> * Try increasing TimerResolution (e.g. 10 times, 100 times, 1000 times) or even turning it off 0.
> * Try playing with AppleInput values and KeyForgetThreshold.

That’s true, moving my finger on the touchpad constantly just fixes the issue 🤣.
So it’s an issue about pointer polling. Thank you very much.
Maybe we should keep this issue open until a software fix is made.

**Comment by vit9696** [comment]
Well, a software fix can only happen as long as you experiment on your hardware, trying different options and performing various experiments, starting from the ones I mentioned, but you will need to be creative onwards. I guess I could help to debug it, but it is not like I can fix it without the hardware.

**Comment by qwqVictor** [comment]
> Well, a software fix can only happen as long as you experiment on your hardware, trying different options and performing various experiments, starting from the ones I mentioned, but you will need to be creative onwards. I guess I could help to debug it, but it is not like I can fix it without the hardware.

OK, I'll do some experiments related to the input configuration then, thanks.

Current details:
- Removed `Ps2KeyboardDxe`, no issue.
- Enabled` PointerSupport` without mouse issue, and the only bug is that sometimes there are two cursors on the screen
- Set `TimerResolution` to 0.

**Comment by aksm-unmei** [comment]
Dear vit, I tried some experiments like you said, here is my result:
 * `Simply move the touchpad constantly while loading, it should reduce the delay significantly, so that you are able to confirm it is the touchpad.` -> Yes, this one works.
 * `Try removing Ps2KeyboardDxe.efi driver. It may be incompatible and you generally do not need it.` -> I haven't already used Ps2KeyBoardDxe.efi so skipped.
 * `Try enabling PointerSupport and check whether it works in OpenCanopy.` -> Tried but not worked
 * `Try adding Ps2MouseDxe.efi driver if the mouse is broken in OpenCanopy.` -> My mouse works fine in OpenCanopy without this driver. Skipped.
 * `Try disabling GraphicsInputMirroring.` -> Did, not worked.
* `Try increasing TimerResolution (e.g. 10 times, 100 times, 1000 times) or even turning it off 0.` -> I set it to 0 and yes, not worked.
* `Try playing with AppleInput values and KeyForgetThreshold.` -> Currently I let it is Builtin. If I change to OEM, OpenCanopy will be black screen, but chime is available.

**Comment by vit9696** [comment]
Well I said `AppleInput` values, I rather meant the numeric ones.

I guess I can give you a few test builds to experiment with and provide **me with logs**. If we are successful, some of the changes may eventually make it to a quirk. Please try this one first.

[OpenCore-r1.zip](https://github.com/acidanthera/bugtracker/files/7799236/OpenCore-r1.zip)

**Comment by aksm-unmei** [comment]
> Well, when I said `AppleInput` values, I rather meant the numeric ones.
> 
> I guess I can give you a few test builds to experiment with and provide **me with logs**. If we are successful, some of the changes may eventually make it to a quirk. Please try this one first.
> 
> [OpenCore-r1.zip](https://github.com/acidanthera/bugtracker/files/7799236/OpenCore-r1.zip)

Here is my log 
[opencore-Dell-G7-7588.txt](https://github.com/acidanthera/bugtracker/files/7799291/opencore-Dell-G7-7588.txt)

**Comment by qwqVictor** [comment]
Sorry for my delay. The test build can't boot my system while the release build can. But it provides us some logs that may be useful.
[opencore-Dell-XPS-9570.txt](https://github.com/acidanthera/bugtracker/files/7799344/opencore-Dell-XPS-9570.txt)

It stuck at here (with `-v` boot-args):
![stuck](https://user-images.githubusercontent.com/21100901/147881202-e9bf884b-6294-4f82-aa34-2089dae8952d.jpg)

**Comment by aksm-unmei** [comment]
> Sorry for my delay. The test build can't boot my system while the release build can. But it provides us some logs that may be useful.
> 
> [opencore-Dell-XPS-9570.txt](https://github.com/acidanthera/bugtracker/files/7799344/opencore-Dell-XPS-9570.txt)
> 
> 
> 
> It stuck at here (with `-v` boot-args):
> 
> ![stuck](https://user-images.githubusercontent.com/21100901/147881202-e9bf884b-6294-4f82-aa34-2089dae8952d.jpg)
> 
>  

you should try to build OC 077 from OCPkg master branch, it works for me without issues (debug version)

**Comment by vit9696** [comment]
Hmm, it is not obvious to me whether the issue is still present with this build though. And yes, you need to update the config to OC from master to use this build.

**Comment by qwqVictor** [comment]
> Hmm, it is not obvious to me whether the issue is still present with this build from the log though. Please clarify. And yes, you need to update the config to OC from master to use this build.

OK. I used the `ocvalidate` of 0.7.7 and I should make an updated configuration for 0.7.7 due to the changes made to Audio part. I'm doing this stuff for just a few minutes.

**Comment by qwqVictor** [comment]
> Hmm, it is not obvious to me whether the issue is still present with this build from the log though. Please clarify. And yes, you need to update the config to OC from master to use this build.

I can confirm that the lag issue has been fixed in this build. It takes just ~20 secs.
And with the differences documentation I know that it's my mistake that enabled the quirk `ProvideCurrentCpuInfo`, which has a significant change in 0.7.7. Sorry for the disruption.
Now I'm really excited to see this result. Thanks for your awesome work!! 🥰

**Comment by aksm-unmei** [comment]
> > Hmm, it is not obvious to me whether the issue is still present with this build from the log though. Please clarify. And yes, you need to update the config to OC from master to use this build.
> 
> I can confirm that the lag issue has been fixed in this build. It takes just ~20 secs. And with the differences documentation I know that it's my mistake that enabled the quirk `ProvideCurrentCpuInfo`, which has a significant change in 0.7.7. Sorry for the disruption. Now I'm really excited to see this result. Thanks for your awesome work!! 🥰

What is your `UEFI` section in config.plist? Mine still takes 2~3 mins to wait it showing up

**Comment by qwqVictor** [comment]
> > > Hmm, it is not obvious to me whether the issue is still present with this build from the log though. Please clarify. And yes, you need to update the config to OC from master to use this build.
> > 
> > 
> > I can confirm that the lag issue has been fixed in this build. It takes just ~20 secs. And with the differences documentation I know that it's my mistake that enabled the quirk `ProvideCurrentCpuInfo`, which has a significant change in 0.7.7. Sorry for the disruption. Now I'm really excited to see this result. Thanks for your awesome work!! 🥰
> 
> What is your `UEFI` section in config.plist? Mine still takes 2~3 mins to wait it showing up

You can try to use `SystemGeneric` text renderer because Dell's UEFI has low graphics performance, maybe this can be an issue.
A gzipped UEFI section plist is attached below for you. You can use `gunzip` command to extract it.
[uefi.plist.gz](https://github.com/acidanthera/bugtracker/files/7799462/uefi.plist.gz)

**Comment by qwqVictor** [comment]
In my observation, sometimes I still have to trigger some movements on the touchpad and then it quickly enters the Preboot. So maybe we should continue to find out the final solution.
I may be unable to do many experiments during Jan. 6th - Jan. 13th because I have several final term exams T_T. But after Jan. 13th, I'm free to do any experiments!

**Comment by aksm-unmei** [comment]
Hmm, it doesn't work on my machine. Still taking ~3 mins for waiting for the FileVault UI shows up. If not, I can trigger the touchpad after 20~30s to wake it up immediately.
Here is my new log and my current config:
[opencore-2022-01-02-171048.txt](https://github.com/acidanthera/bugtracker/files/7799496/opencore-2022-01-02-171048.txt)
[config.plist.txt](https://github.com/acidanthera/bugtracker/files/7799497/config.plist.txt)

**Comment by qwqVictor** [comment]
> 

I agree. On my machine it sometimes can completely fix it, but sometimes I have to wait or wake it. So it may be an incomplete fix. (cc @vit9696)
So I'm too happy about the situation. But such fix is a good beginning.

**Comment by vit9696** [comment]
Please disable all file logs (Target = 3) and recheck multiple times with both master and this build. Either the change does fix the lag or not. Logs may significantly reduce boot time (up to 20 minutes), so perhaps there is a confusion in the measurements.

**Comment by qwqVictor** [comment]
> Please disable all file logs (Target = 3) and recheck multiple times with both master and this build. Either the change does fix the lag or not. Logs may significantly reduce boot time (up to 20 minutes), so perhaps there is a confusion in the measurements.

Tested for several times. I think it's not related to logs.

**Comment by vit9696** [comment]
1. I.e. the issue is still randomly happening with r1? Make sure you test at least 5 times.
2. Does the issue randomly happen with master build? Make sure you test at least 5 times.
3. Are you sure you do not touch the touchpad across the tests?
4. Do you boot to macOS, then reboot to perform the test or reboot earlier (e.g. from FV2 UI)?
5. Check whether rebooting from FV2 UI to perform another test or rebooting from macOS make a reliable rate of tests?

Just to make it clear. I see a noticeable reduction in boot times in your logs. This one is from here (https://github.com/acidanthera/bugtracker/issues/1899#issuecomment-1003735561)
```
07:227 00:002 OCC: Setting cc mode 1 -> 0
07:643 00:416 OCAE: Set screen resolution to 3840x2160 - Success
07:645 00:002 OCAE: Set screen resolution to 3840x2160 - Success
07:647 00:002 OCC: Setting cc mode 0 -> 1
23:577 15:929 AAPL: #[EB|LW+]
```

This one is from your first message:
```
05:866 00:002 AAPL: #[EB.CS.UFVK|LWLO] 0x74
06:282 00:416 OCAE: Set screen resolution to 3840x2160 - Success
06:285 00:002 OCAE: Set screen resolution to 3840x2160 - Success
99:916 93:631 AAPL: #[EB|LW+]
```

It is 90+ seconds vs 15+ seconds. The latter 15 seconds are somewhat normal as you need to load the images from the disk, and it may not be perfectly fast, though still surprising. I want to understand whether there are two problems and the fix resolves one or whether the lag is completely sporadic.

**Comment by aksm-unmei** [comment]
Dear vit, sorry for late replying. I have just woken up.
I tested 5 situations as you said and here is my result:
1. The issue is not randomly with R1. It took avg 2m10s to boot to macOS.
2. The issue is also not randomly with master build. But it took less time to boot to macOS, avg 1m56s.
3. Yes, I didnt touch the touchpad across the tests.
4. Yes, I tried 3 cases: Reboot from macOS, reboot from FV2 and shutdown the machine then coldboot. 5 times per case, same result according above.
5. Yes, I did. The result is based on what OpenCore.efi file is in OC folder.
Also I realized a thing, I'm not sure if it's useful. It is OCSMC SmcReadValue tooks a long time to show up and load. Maybe around 5-7s, after that is prelinked kernel then boot to macOS.

**Comment by vit9696** [comment]
Please try this one.

[OpenCore-r2.zip](https://github.com/acidanthera/bugtracker/files/7800179/OpenCore-r2.zip)

**Comment by aksm-unmei** [comment]
> Please try this one.
> 
> 
> 
> [OpenCore-r2.zip](https://github.com/acidanthera/bugtracker/files/7800179/OpenCore-r2.zip)
> 
> 

Hi vit. Thanks for your hard work!
Here is my result with OpenCore.efi R2:
![image](https://user-images.githubusercontent.com/59220499/147898158-94085374-9d70-43c8-b123-32df3ebf69d1.png)

Everything seems faster than before.

**Comment by vit9696** [comment]
Hmmm, how fast is your trackpad
- in FV2 UI?
- in OpenCanopy?
Try it at the same time you use the buttons.

Do you need mouse support in FV2? In OpenCanopy?

**Comment by vit9696** [comment]
Also need a log with this one.
[OpenCore-r3.zip](https://github.com/acidanthera/bugtracker/files/7800437/OpenCore-r3.zip)

**Comment by aksm-unmei** [comment]
> Hmmm, how fast is your trackpad
> 
> - in FV2 UI?
> 
> - in OpenCanopy?
> 
> Try it at the same time you use the buttons.
> 
> 
> 
> Do you need mouse support in FV2? In OpenCanopy?

touchpad is slow and lagging, happens both OpenCanopy and FV2.
almost time is no, I usually use keyboard.

**Comment by aksm-unmei** [comment]
> Also need a log with this one.
> 
> [OpenCore-r3.zip](https://github.com/acidanthera/bugtracker/files/7800437/OpenCore-r3.zip)
> 
> 

yes sure! I will.
which case should I test? coldboot, restart from FV2 or restart from mac?

**Comment by vit9696** [comment]
Just running up to OpenCanopy is enough. It is just the logging, no functional difference from r2.

**Comment by aksm-unmei** [comment]
> Also need a log with this one. [OpenCore-r3.zip](https://github.com/acidanthera/bugtracker/files/7800437/OpenCore-r3.zip)

Here is the new log with R3:
[opencore-Dell-G7-OC-R3.txt](https://github.com/acidanthera/bugtracker/files/7800518/opencore-Dell-G7-OC-R3.txt)

**Comment by vit9696** [comment]
Very interesting. It says you have 4 mouse pointer instances. Quite possible some of them are dummy instances and cause lag. I made 4 test builds. Each build uses only one mouse instance. You should check:

- the performance of each build.
- whether mouse works in each build.

[OpenCore-r4-inst3.zip](https://github.com/acidanthera/bugtracker/files/7800527/OpenCore-r4-inst3.zip)
[OpenCore-r4-inst2.zip](https://github.com/acidanthera/bugtracker/files/7800528/OpenCore-r4-inst2.zip)
[OpenCore-r4-inst1.zip](https://github.com/acidanthera/bugtracker/files/7800529/OpenCore-r4-inst1.zip)
[OpenCore-r4-inst0.zip](https://github.com/acidanthera/bugtracker/files/7800530/OpenCore-r4-inst0.zip)

**Comment by aksm-unmei** [comment]
Can I ask a question? How should I config the config.plist file in UEFI section to make a good testing? About PointerSupport, AppleInput, KeyThreshold, etc...

**Comment by vit9696** [comment]
I believe these are unrelated to the issue. You can leave them as in Sample.plist.

**Comment by aksm-unmei** [comment]
> I believe these are unrelated to the issue. You can leave them as in Sample.plist.

Okay I understand. Will report the test result asap. I have to go outside now.

**Comment by qwqVictor** [comment]
> Also need a log with this one.
> [OpenCore-r3.zip](https://github.com/acidanthera/bugtracker/files/7800437/OpenCore-r3.zip)

Sorry for the delay because I’m too lazy to wake up early. Since R3 has no functional differences, I tested it 4 times on my XPS (without touching the laptop during boot).
Results:
- Reboot:
  + 28.50 secs
  + 18.94 secs
- Coldboot:
  + 2 min 15 secs
  + 16.53 secs
  + 20.28 secs

It's a little strange that without any input, it behaves differently when coldboots. Logs attached below:

[opencore-XPS-9570-coldboot-2min15secs.txt](https://github.com/acidanthera/bugtracker/files/7800666/opencore-XPS-9570-coldboot-2min15secs.txt)
[opencore-XPS-9570-reboot-18.94secs.txt](https://github.com/acidanthera/bugtracker/files/7800667/opencore-XPS-9570-reboot-18.94secs.txt)
[opencore-XPS-9570-coldboot-16.53secs.txt](https://github.com/acidanthera/bugtracker/files/7800668/opencore-XPS-9570-coldboot-16.53secs.txt)
[opencore-XPS-9570-coldboot-20.28secs.txt](https://github.com/acidanthera/bugtracker/files/7800669/opencore-XPS-9570-coldboot-20.28secs.txt)
[opencore-XPS-9570-reboot-28.50secs.txt](https://github.com/acidanthera/bugtracker/files/7800665/opencore-XPS-9570-reboot-28.50secs.txt)

I don't know if R4 is OK for me to test though. Hope these logs could help.

**Comment by qwqVictor** [comment]
In several tests, reboot can also take a long time (~1min30s). R3 Logs:
[opencore-2022-01-03-073530.txt](https://github.com/acidanthera/bugtracker/files/7800794/opencore-2022-01-03-073530.txt)

**Comment by aksm-unmei** [comment]
> Very interesting. It says you have 4 mouse pointer instances. Quite possible some of them are dummy instances and cause lag. I made 4 test builds. Each build uses only one mouse instance. You should check:
> 
> * the performance of each build.
> * whether mouse works in each build.
> 
> [OpenCore-r4-inst3.zip](https://github.com/acidanthera/bugtracker/files/7800527/OpenCore-r4-inst3.zip) [OpenCore-r4-inst2.zip](https://github.com/acidanthera/bugtracker/files/7800528/OpenCore-r4-inst2.zip) [OpenCore-r4-inst1.zip](https://github.com/acidanthera/bugtracker/files/7800529/OpenCore-r4-inst1.zip) [OpenCore-r4-inst0.zip](https://github.com/acidanthera/bugtracker/files/7800530/OpenCore-r4-inst0.zip)

Dear vit, sorry for late replying. I have just been at home and tested 4 builds. Here is the result:
![image](https://user-images.githubusercontent.com/59220499/147917546-6d6fa5c1-ed38-4b10-a063-a2c4abd3d2ac.png)

**Comment by vit9696** [comment]
@aksm-unmei Interesting. Thanks for the results.

@qwqVictor you have 2 pointers. Can test r4 0 and 1.

**Comment by qwqVictor** [comment]
> @aksm-unmei Interesting. Thanks for the results.
> 
> @qwqVictor you have 2 pointers. Can test r4 0 and 1.

Thank you. Results here.

### inst0: 
 - Trackpad works
 - Pointer behaves slow and laggy.
 - FileVault Preboot: takes ~52 secs.
### inst1: 
 - Trackpad works
 - Pointer behaves in normal speed and not very laggy.
 - FileVault Preboot: takes ~12 secs.

It's a little strange. Since the touchscreen never works with OpenCore, I don't think these pointers are related to the touchscreen. But the trackpad always works. 

[opencore-XPS-9570-r4-0.txt](https://github.com/acidanthera/bugtracker/files/7802773/opencore-XPS-9570-r4-0.txt)
[opencore-XPS-9570-r4-1.txt](https://github.com/acidanthera/bugtracker/files/7802774/opencore-XPS-9570-r4-1.txt)

**Comment by aksm-unmei** [comment]
> > @aksm-unmei Interesting. Thanks for the results.
> > @qwqVictor you have 2 pointers. Can test r4 0 and 1.
> 
> Thank you. Results here.
> 
> ### inst0:
> * Trackpad works
> * Pointer behaves slow and laggy.
> * FileVault Preboot: takes ~52 secs.
> 
> ### inst1:
> * Trackpad works
> * Pointer behaves in normal speed and not very laggy.
> * FileVault Preboot: takes ~12 secs.
> 
> It's a little strange. Since the touchscreen never works with OpenCore, I don't think these pointers are related to the touchscreen. But the trackpad always works.
> 
> [opencore-XPS-9570-r4-0.txt](https://github.com/acidanthera/bugtracker/files/7802773/opencore-XPS-9570-r4-0.txt) [opencore-XPS-9570-r4-1.txt](https://github.com/acidanthera/bugtracker/files/7802774/opencore-XPS-9570-r4-1.txt)

Have you set your config.plist to "default"? I mean similar to UEFI section in Sample.plist in OpenCorePkg master build.
I only set `TextRenderer` to `SystemGeneric` like you said, others leave default.

**Comment by vit9696** [comment]
I provided a test build in https://github.com/acidanthera/OpenCorePkg/pull/312. It will take some time to build, but should be available in the artifacts in ~40 mins.

* r2-r4 had PointerPollMin hardcoded to 50 and PointerPollMax to 200.
* Similarly r4 had PointerPollMask hardcoded to 1, 2, 4, and 8 for inst0, inst1, inst2, inst3 correspondingly.

Try your own values and report what works best for you. Note, that you can try to use PointerSpeedMul to compensate for low pointer speed. I believe this is the maximum I can offer for your hardware.

As long as the pull request causes no obvious regressions I will merge this tomorrow.

**Comment by qwqVictor** [comment]
> I provided a test build in [acidanthera/OpenCorePkg#312](https://github.com/acidanthera/OpenCorePkg/pull/312). It will take some time to build, but should be available in the artifacts in ~40 mins.
> 
> * r2-r4 had PointerPollMin hardcoded to 50 and PointerPollMax to 200.
> * Similarly r4 had PointerPollMask hardcoded to 1, 2, 4, and 8 for inst0, inst1, inst2, inst3 correspondingly.
> 
> Try your own values and report what works best for you. Note, that you can try to use PointerSpeedMul to compensate for low pointer speed. I believe this is the maximum I can offer for your hardware.
> 
> As long as the pull request causes no obvious regressions I will merge this tomorrow.

Thank you for your hard work. I grabbed a debug version from artifact `macOS XCODE5 Artifacts` of [CI #2493](https://github.com/acidanthera/OpenCorePkg/actions/runs/1650140418). And I added these keys in my `config.plist` using ProperTree. But I faced a blackscreen issue. The same configuration **CAN** boot in r4 build. 

My configuration about PointerPoll:
```xml
			<key>PointerPollMask</key>
			<integer>1</integer>
			<key>PointerPollMax</key>
			<integer>200</integer>
			<key>PointerPollMin</key>
			<integer>50</integer>
```

Diving into the logs. I found that after `OCC: Setting cc mode 0 -> 1`, the procedure `AAPL: #[EB|LW+]` is expected to happen but it doesn't. I tried to understand the changes that made from commit `e2e4e6d5420a0226ff09fb3809fe9646cfd78b61` but it's a little hard for me.

I've also validated my config with `ocvalidate` in the build artifact and it shows me that no issue.

Logs and config without `PlatformInfo` attached below:
[test.plist.zip](https://github.com/acidanthera/bugtracker/files/7803227/test.plist.zip)
[opencore-ci-2493.txt](https://github.com/acidanthera/bugtracker/files/7803232/opencore-ci-2493.txt)
[opencore-r4.txt](https://github.com/acidanthera/bugtracker/files/7803233/opencore-r4.txt)

**Comment by vit9696** [comment]
You are right. Fixed this in https://github.com/acidanthera/OpenCorePkg/pull/312/commits/70d7b268d7107031e2ea0535d49e352eda24a01d.

**Comment by qwqVictor** [comment]
Thank you very much for your hard work! The issue can be regarded as fixed. 🎉

I tested several values. On XPS 9570, the best choice is:

- PointerPollMask set to 1
- PointerPollMin set to 50
- PointerPollMax set to 100

This results in:

- About 8 seconds on average when reboots, that’s very stable.
- About 30 seconds when cold boot, at best case it just takes about 10 seconds and at worst case it can take 50 seconds. 
  + Since Dell’s UEFI itself has a very unstable cold boot performance (sometimes just POST for <10 seconds but sometimes for >30 seconds), I think it’s not related to OpenCore but Dell.

Hope the report could help more users.
❤️

**Comment by aksm-unmei** [comment]
Sorry for late replying. I have just been busy a bit at office.

Same on my G7 7588, the good fast enough choice is:
 * PointerPollMask set to 5 (I enable both touchpad and mouse).
 * PointerPollMin set to 50.
 * PointerPollMax set to 100.

Result:
 * About 3s on avg from coldboot, restart from Mac and reboot from FV2. That's very impressive!

@qwqVictor For solving the delay time performance, you can try to restore BIOS Default then re-config the BIOS again. It works on my machine. Also you can remove unnecessary OpenCore's drivers. It will reduce delay time a lot. And yes, it's not related to OpenCore but Dell.

Hope the report could help other users.

One again, @vit9696 thank you so much for your hard work! I'm gonna update more information for my repo for this month.

**Comment by Church13** [comment]
Running OpenCore 7.7.7 on a newly purchased Dell Alienware M17 R4. @vit9696 and @qwqVictor thanks for the work on this, previously it was ~30+ seconds to reach the FileVault login prompt, now with the below settings it's <2 seconds each time.

- PointerPollMask set to 5 (for touchpad + mouse input)
- PointerPollMin set to 50
- PointerPollMax set to 100

This is definitively an issue primarily affecting Dell devices.

**Comment by mrrfv** [comment]
My MSI laptop (GV62 7rd) is also affected by this issue. @Church13's settings decreased the time for the FileVault login screen to show up from a few minutes to a few seconds. Thanks!
