### ISSUE TITLE
Asus H81M-K Motherboard with Intel integrated Graphics 4600

### ISSUE THREAD

**Issue by ahmedalishah11** [acidanthera/bugtracker#1901]
Hello sir,
I have AsusH81M-K Motherboard with Intel integrated Graphics 4600, but can not get acceleration more than 7 mb. I have followed  instructions from here [[]](https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html)(https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html)))) and also from here [[]](https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html)(toohttps://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md)) but unable to get the acceleration. When I use the settings as per instructions my computer stucks at IOConsoleUsers: gIOScreenLock.../gIOLockState (3....) Sometimes I get a black screen after IOConsoleUsers: gIOScreenLock.../gIOLockState (3...) Tried mod pikera, vit9696, igfxmlr,igfxonln=1, agdpmod=ignore and so on. It only works with 7mb with AAPL,ig-platform-id=12040000. Kindly guide me. Any help will be appreciated. Thanks in advance.

**Comment by TheHackGuy** [comment]
This is a bugtracker for bugs.
Use forums for support

**Comment by ahmedalishah11** [comment]
[opencore-2021-12-21-182711.txt](https://github.com/acidanthera/bugtracker/files/7757301/opencore-2021-12-21-182711.txt)
