### ISSUE TITLE
Asus H81M-K Motherboard with Intel integrated Graphics 4600

### ISSUE THREAD

**Issue by ahmedalishah11** [acidanthera/bugtracker#1902]
Hello sir,
I have AsusH81M-K Motherboard with Intel integrated Graphics 4600, but can not get acceleration more than 7 mb. I have followed instructions from here [](https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html)))) and also from here [](toohttps://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md)) but unable to get the acceleration. When I use the settings as per instructions my computer stucks at IOConsoleUsers: gIOScreenLock.../gIOLockState (3....) Sometimes I get a black screen after IOConsoleUsers: gIOScreenLock.../gIOLockState (3...) Tried mod pikera, vit9696, igfxmlr,igfxonln=1, agdpmod=ignore and so on. It only works with 7mb with AAPL,ig-platform-id=12040000. Kindly guide me. Any help will be appreciated. Thanks in advance.
[opencore-2021-12-18-221205.txt](https://github.com/acidanthera/bugtracker/files/7757423/opencore-2021-12-18-221205.txt)
[panic-2021-12-20-081920.txt](https://github.com/acidanthera/bugtracker/files/7757424/panic-2021-12-20-081920.txt)
[panic-2021-12-20-084935.txt](https://github.com/acidanthera/bugtracker/files/7757425/panic-2021-12-20-084935.txt)

**Comment by ahmedalishah11** [comment]
[][([url](https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html)
[
](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md)

**Comment by ahmedalishah11** [comment]
[[]](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md)(url) followed


[[]](https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html)(url)

**Comment by ahmedalishah11** [comment]
My EFI[ []](https://drive.google.com/drive/folders/1lLl2L5H4p5T2-5YLQcsVV2mCBaSDBdxJ)(url)

**Comment by Andrey1970AppleLife** [comment]
Yours panic log on AppleIntelKBLGraphics but you have Haswell (Azul).
EFI folder no access.
Use forums for support.
