### ISSUE TITLE
SMCDellSensors: Fan is missing when booted without power plug connected

### ISSUE THREAD

**Issue by hacker1024** [acidanthera/bugtracker#1904]
I have a Dell Inspiron 7586. When I boot macOS without the barrel power plug connected, the fan is missing in control apps such as Macs Fan Control. The issue occurs with a USB-C power source as well. Normally, it shows up and the speed can be monitored and adjusted.

My EFI folder is on GitHub: https://github.com/hacker1024/Dell-Inspiron-7586-Hackintosh
I can upload debug logs tomorrow.

(CC: @lvs1974)

**Comment by lvs1974** [comment]
@hacker1024: I cannot say anything without boot log.
You can use debug version of SMCDellSensors.kext and boot-args: -delldbg msgbuf=1048576.

Then you can fetch boot-log with any way (lilu dump or log show or dmesg).
