### ISSUE TITLE
Intel KBL Unknown

### ISSUE THREAD

**Issue by MohdIsmailMatAsin** [acidanthera/bugtracker#1905]
1. Hi how are you. Sorry to disturb you. I don't know how to categorise this as a question or issue. I built EFI for my Hackintosh using an Intel i5 10400 processor (iGPU UHD630). I follow the recommendation https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#add-2. 

2. However, all works well. Yet I was skeptical whether my IGPU worked or not. I use the Headless **0300C89B** IGPU configuration (Used when the Desktop iGPU is only used for computing tasks and doesn't drive a display). What I see is it uses an **Intel KBL Unknown**.

Is it normal?

<img width="618" alt="Screenshot 2021-12-27 at 19 36 21" src="https://user-images.githubusercontent.com/72515939/147468560-0120a653-cd21-475b-b6e1-9f1969d70d6d.png">

<img width="1724" alt="Screenshot 2021-12-27 at 19 43 36" src="https://user-images.githubusercontent.com/72515939/147468690-da9097d2-7c7c-4f53-af6b-6c33c1aec339.png">

At least i got some explanation why this happen? Any suggestion to rename using **0300C89B** configuration?

**Comment by vit9696** [comment]
This is correct and happens because your particular IGPU is not known to Apple. The IGPU itself is working correctly, and the inscription is just the cosmetics which is hard to fix (requires patching userspace drivers I am not even sure where in newer macOS version) but it does not affect you in any bad sense anyway.

**Comment by MohdIsmailMatAsin** [comment]
Thank you so much. I am appreciate you answer @vit9696

**Comment by MohdIsmailMatAsin** [comment]
@vit9696 I just found fix, refer https://github.com/MohdIsmailMatAsin/i510400AsrockB460MSteelLegend/blob/main/README.md#headless-uhd-graphics-630-settings
