### ISSUE TITLE
[AppleALC] ALC662 microphone white noise (osx sierra 11.12.6)

### ISSUE THREAD

**Issue by sukualam** [acidanthera/bugtracker#1906]
I try every layout-id, use latest lilu+applealc, but still can't get microphone (pink) to work, it just white noise , even i plug my mic or not. Im on Desktop, not Laptop.

So far i use alcid=16 it better because it show more output (headset/speaker,etc), but it still not getting microphone to work.

On system preferences > sound > input, it shows
- internal microphone
- line-in

My motherboard doesn't have internal mic, unlike laptop. Is this the reason?

Btw, This is my setup:
CPU: Intel g3260 (haswell)
GPU: Nvidia Quadro 600
Audio: Realtek ALC662
OS: Mac OS Sierra 10.12.6
Bootloader (uefi): Clover r2114

Why i not update to higher os? Because my hardware is old and graphic card just support in osx sierra. I use this os just for audio/music/daw things. (Garageband,etc)

If i switch to opencore, is this somewhat fixed? If yes, what the config to add?

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/blob/master/.github/ISSUE_TEMPLATE/bug-in-opencore-or-kext.md

![Снимок экрана 2021-12-29 в 15 19 29](https://user-images.githubusercontent.com/17758753/147661418-a6df93f2-4580-4325-82bf-1ea874bb3ebe.png)
