### ISSUE TITLE
AirportBrcmFixup: Couldn't find Lilu, but Lilu is loaded

### ISSUE THREAD

**Issue by vualeks** [acidanthera/bugtracker#1907]
Hi,

I have installed Monterey 12.1, loaded Lilu kext and I saw that AirportBrcmFixup is not loading on startup. When I tried manually loading it got the error

`Executing: /usr/bin/kmutil load --bundle-path /Library/Extensions/AirportBrcmFixup.kext
Error Domain=KMErrorDomain Code=31 "Error occurred while building a collection:
    1: One or more binaries has an error which prevented linking.  See other errors.
    2: Could not use 'as.lvs1974.AirportBrcmFixup' because: Failed to bind '__ZN9IOService19_RESERVEDIOService0Ev' as could not find a kext with 'as.vit9696.Lilu' bundle-id
as.lvs1974.AirportBrcmFixup specific:
    1: Failed to bind '__ZN9IOService19_RESERVEDIOService0Ev' as could not find a kext with 'as.vit9696.Lilu' bundle-id
" UserInfo={NSLocalizedDescription=Error occurred while building a collection:
    1: One or more binaries has an error which prevented linking.  See other errors.
    2: Could not use 'as.lvs1974.AirportBrcmFixup' because: Failed to bind '__ZN9IOService19_RESERVEDIOService0Ev' as could not find a kext with 'as.vit9696.Lilu' bundle-id
as.lvs1974.AirportBrcmFixup specific:
    1: Failed to bind '__ZN9IOService19_RESERVEDIOService0Ev' as could not find a kext with 'as.vit9696.Lilu' bundle-id
}`

But I see Lilu loaded correctly

`kextstat | grep Lilu
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
   51    6 0                  0x2e000    0x2e000    as.vit9696.Lilu (1.5.8) 3E44E561-C07C-31E8-B2D7-0F31B5266E45 <9 7 6 3 2 1>`
   
   What could be the problem?

**Comment by vit9696** [comment]
Loading kernel extensions from /Library is unsupported.
