### ISSUE TITLE
Erratic pointer movement in Opencore

### ISSUE THREAD

**Issue by antoniomcr96** [acidanthera/bugtracker#1911]
Opencore 0.7.7, last commit. However, it has always happened with every version, I report it now if someone wishes to fix the problem. I understand that it is of low priority.

Lenovo L390 Yoga. VoodooPS2Controller latest release. Elan Touchpad (ID: LEN2137). Monterey 12.1

On reboot pointer goes crazy in opencore UI:

https://user-images.githubusercontent.com/63928525/148106634-7ef67989-e0c7-44bb-a505-59838a3417b8.mp4

Log: 
[opencore-2022-01-04-181725.txt](https://github.com/acidanthera/bugtracker/files/7809665/opencore-2022-01-04-181725.txt)

However, the behavior of the pointer is absolutely fine on cold boot:

https://user-images.githubusercontent.com/63928525/148106929-3d07b903-8336-4127-af9f-c48d6a7dc215.mp4

Log: 
[opencore-2022-01-04-181523.txt](https://github.com/acidanthera/bugtracker/files/7809662/opencore-2022-01-04-181523.txt)

The problem disappears even if I restart from Windows.

Thanks for any help. Happy New Year to all of you.

**Comment by vit9696** [comment]
@usr-sse2  does this look like https://github.com/acidanthera/bugtracker/issues/721?

**Comment by vit9696** [comment]
I think the issue is how the firmware initialises the trackpad. It is unlikely we can do anything.

**Comment by antoniomcr96** [comment]
> I think the issue is how the firmware initialises the trackpad. It is unlikely we can do anything.

My main doubt remains why if I reboot from windows it works regularly but not if rebooting from macos.

**Comment by vit9696** [comment]
Because Windows leaves the trackpad in one state and macOS in another, yet the firmware does not fully reinitialise it. Perhaps we should change the way we disable the trackpad on reboot. CC @1Revenger1

**Comment by antoniomcr96** [comment]
I tried to reboot from macOS without voodoops2controller kext. Pointer works fine in OpenCanopy UI. It’s probably what you have just hypothesized.

**Comment by usr-sse2** [comment]
> @usr-sse2 does this look like #721?

No. In #721 the cursor movement was just slow, not wrong, and the conditions were different – it was slow in FV2 if the picker was not shown.

**Comment by 1Revenger1** [comment]
> Because Windows leaves the trackpad in one state and macOS in another, yet the firmware does not fully reinitialise it. Perhaps we should change the way we disable the trackpad on reboot. CC @1Revenger1

My suspicion is that devices may need to be reset on shutdown. I'll see if I can create a version later tonight which does this.
Looks like Linux does this while cleaning up/shutting down: https://github.com/torvalds/linux/blob/master/drivers/input/mouse/psmouse-base.c#L1455-L1464

**Comment by 1Revenger1** [comment]
Can you please test the below? This changes the keyboard/mouse to reset but not disable on shutdown.
[VoodooPS2Controller-2.2.8-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7812158/VoodooPS2Controller-2.2.8-DEBUG.zip)

**Comment by antoniomcr96** [comment]
Unfortunately it doesn't work :(
Just a question: the kext you sent was edited on 25th december. Is it the right one?
![image](https://user-images.githubusercontent.com/63928525/148229043-3acd54e0-037a-4cc0-b9a2-d583e76bf053.png)

**Comment by 1Revenger1** [comment]
> Unfortunately it doesn't work :( Just a question: the kext you sent was edited on 25th december. Is it the right one? ![image](https://user-images.githubusercontent.com/63928525/148229043-3acd54e0-037a-4cc0-b9a2-d583e76bf053.png)
> 
> EDIT: i did further tests @1Revenger1
> 
> * The culprit of the problem seems to be **VoodooPS2Trackpad.kext**. If I use this kext to drive my trackpad, pointer shows the problem in OpenCore UI. I use this kext since @BAndysc made it compatible with ELAN trackpads such as mine.
> * If I use VoodooPS2Mouse (no matter the version), everything is ok after reboot (no gestures with this kext however). Anyway, I encounter the same problem described here: [Strange crash on VoodooPS2 and MacOS Monterey #1895](https://github.com/acidanthera/bugtracker/issues/1895). If I reboot with VoodooPS2Mouse enabled, keyboard doesn't work in OpenCanopy UI. The problem is not present with VoodooPS2Trackpad.
> * Besides crazy pointer in OpenCanopy UI, I have the same problem in MacOS UI with VoodooPS2Mouse kext. However, in this case put the notebook to sleep is enough to fix the problem. (To be clearer: i mean rebooting the system with VoodooPS2Trackpad running, but with config.plist edited to enable VoodooPS2Mouse and not VoodooPS2Trackpad in the next boot)
> 
> Hope these informations can be useful for both the issues

The date doesn't matter, check the date of the binary (right click and click `Show Package Contents`).
Someone else on Discord was having the same issue on their Elans trackpad, and I was not able to figure it out. You could try seeing if there is some sort of diagnostic option, or way to disable quick boot. This may mean that the bios does more initialization on it's own, though I don't really know what we are doing wrong in macOS.

Main things I tried doing on shutdown were:
* Sending F6 (Disable and Set Defaults) and then sending F4 to enable
* Sending FF (Reset) and then F4 to enable
* Flush data port and having the PS2 controller do a self test

I don't have a device which does anything like this, so it's a bit hard for me to test unfortunately.

**Comment by Krazy-Killa** [comment]
I've got a Lenovo Yoga 370, and here is my findings on the matter:

- Same issue, using VoodooPS2Mouse instead of VoodooPS2Trackpad, Keyboard fails not only in OpenCore, but in BIOS as well. A full shutdown of the machine restores functionality but is broken the moment the system is rebooted from macOS.
- Using VoodooPS2Trackpad, the trackpad and trackpoint both fail after a reboot, but keyboard remains functional across reboots and sleep.
- With previous builds of VoodooPS2Controller, and VoodooPS2Trackpad, the trackpad will fail 5 seconds after waking from sleep, and will not come back until a full shutdown of the machine is done.

**Comment by nms42** [comment]
> I think the issue is how the firmware initialises the trackpad. It is unlikely we can do anything.

Just my observations so far. The same kext (2.2.7) in OpenCore did not work when system cold booted. When system forced to sleep (via power button) and waked after -- keyboard works. Kernel log shows troubles with initial (controller) reset.

On the other side the same kext works just fine with Clover.

**Comment by vit9696** [comment]
Version 2.3.2 added ps2kbdonly=1, so it might have resolved this.
