### ISSUE TITLE
Better documentation on how to create a patched version of a audio codec

### ISSUE THREAD

**Issue by danieldeicide** [acidanthera/bugtracker#1912]
Hello!

I know you're working very hard for free basically and I am thankful for that!
Thank you very much for this amazing piece of software!
Could you please improve documentation on how to create a patched version of a codec? 
https://github.com/acidanthera/AppleALC/wiki/Adding-codec-support

I have issues with ALC887 (like many others). If I (or anyone else) would know how to patch it correctly I think a lot of questions will be automatically solved (on different forums).
If you help me quickly I can write the docs for you (if you don't have time, maybe create a video)

Thank you!

**Comment by vit9696** [comment]
I believe there are many instructions regarding AppleHDA resource design on third-party websites. Pinging others to link to the ones they know.

CC @1Revenger1, @Andrey1970AppleLife, @dhinakg, @khronokernel, @roddy20, @vandroiy2013, @zhen-zen

**Comment by TheHackGuy** [comment]
Some guides:
https://github.com/F0x1c/AppleALC_Instructions
https://osxlatitude.com/forums/topic/1946-complete-applehda-patching-guide/

PinConfiguator: 
https://github.com/headkaze/PinConfigurator
for the pinconfigs, pinconfigurator also has a patch option to correct the pinconfigs for what macOS wants.

Codec Graph
https://github.com/TheHackGuy/Codec-Graph (I still haven't had the time to completely rewrite it in python3, but it works)
Pretty useful for making the platforms.xml
- doesn't yet support codec dumps from OC

Dortania also has an issue about it:
https://github.com/dortania/bugtracker/issues/74

**Comment by danieldeicide** [comment]
Thank you very much @TheHackGuy ! Can I come back with questions if something is not clear?

**Comment by TheHackGuy** [comment]
> Thank you very much @TheHackGuy ! Can I come back with questions if something is not clear?

Yes sure. I prefer sending messages on some forum instead of this bug tracker (bug trackers are for bugs..)
I'm not really active on any hackintosh forums but you may send me on InsanelyMac (https://www.insanelymac.com/forum/profile/2623461-thehackguy/)

I'm also not an expert with AppleALC resources, I created serveral layout id's (only 1 is merged, the other layout id's were just for experimenting) so I hope I can help if needed.

**Comment by danieldeicide** [comment]
> bug trackers are for bugs..)
Totally agree. I posted here as a last resort.

Thank you very much! Sent you a message on insanelymac.com.

Have a great day!

**Comment by CaseySJ** [comment]
I put together this guide based extensively on the one by FOx1c:

https://www.tonymacx86.com/threads/asus-z690-proart-creator-wifi-thunderbolt-4-i7-12700k-amd-rx-6800-xt.318311/post-2304979

**Comment by mikebeaton** [comment]
@Core-i99 also recently provided another helpful link: https://github.com/acidanthera/bugtracker/issues/2164#issuecomment-1327883994
