### ISSUE TITLE
DebugEnhancer does not resize the system message buffer correctly in macOS Monterey

### ISSUE THREAD

**Issue by williambj1** [acidanthera/bugtracker#1916]
Hi devs!

XNU shipped in macOS Monterey does not have the symbol `_log_setsize` anymore. The ability to adjust the buffer size with boot-args seems to be removed as well.

It is still possible to change the message buffer size in user space with `sysctl` but It looses the ability to collect logs produced by kernel extensions during boot easily from `dmesg`.

May I kindly request a workaround for macOS Monterey?

Thanks!

**Comment by vit9696** [comment]
cc @lvs1974

**Comment by williambj1** [comment]
> @williambj1: could you upload your kernel file somewhere, please?
> I don't have Monterey installed.
> But I suppose we have to wait when Apple publishes xnu sources for 10.12.

[kernel-21C52.zip](https://github.com/acidanthera/bugtracker/files/7860429/kernel-21C52.zip)

@lvs1974 Please let me know if anything else is needed, thanks again.

**Comment by PMheart** [comment]
`_log_setsize` is indeed no longer exported, though it is still possible to patch this. I am not in favour of the hex patch, yet this could be the only way:
Find: `48 3D FF FF 0F 00 77 C5`
Repl: `48 3D FF FF FF 00 77 C5`

These sequences also exist in 12.2 (21D49), in addition to 21C52.

**Comment by lvs1974** [comment]
@PMheart: thank you for the sequence of bytes. The only problem is that _log_setsize is called to early, when kernel is started.
So, this patch will work if OC patches kernel. 
With DebugEnhancer it is not so easy. After applying this patch DebugEnhancer must call _log_setsize again.

In kernel we have this:
dq offset aMsgbuf                                    B4 4C BB 00 80 FF FF FF   offset of string "msgbuf"
dq offset sub_FFFFFF8000883FF0        F0 3F 88 00 80 FF FF FF   offset of _log_setsize
dq offset aI 
dq offset asc_FFFFFF8000B503A8

Theoretically, we can search for "msgbuf\\0" in kernel, then get offset this string and find any qword where this offset is stored. The next 8 bytes is offset of method _log_size. And we can call this method.
But it is very risky.

**Comment by khronokernel** [comment]
XNU 12.0.1 Source has been added:

* https://github.com/apple-oss-distributions/xnu/commit/e6231be02a03711ca404e5121a151b24afbff733

**Comment by lvs1974** [comment]
Problem is solved in 1.06:
[DebugEnhancer-1.0.6-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/8022357/DebugEnhancer-1.0.6-DEBUG.zip)

**Comment by williambj1** [comment]
Works like a charm, thank you very much!
