### ISSUE TITLE
AudioDxe AudioOutMask Something went wrong

### ISSUE THREAD

**Issue by wangdongfreesky** [acidanthera/bugtracker#1920]
sorry ！I am Chinese，English sucks！
新的OC0.77我已经尝试，
但是AudioOutMask这个参数出现问题，我的机器是Dell 3681配备的是A3F0 ALC256 声卡前面板耳机插口，后面板是线路输出和线路输入可以插音箱，layout-id为43000000，67 。
当AudioOutMask=1时，前后插口均播放声音，当AudioOutMask=2时，仅前面板耳机播放声音，（=4，=8，均无声音），后面板无法单独播放声音
而原来使用AudioOut参数时，=0为后面板，=3为前面板耳机
New OC0.77 I have tried,
But there was a problem with the AudioOutMask parameter, my machine is the Dell 3681 equipped with the A3F0 ALC256 sound card front panel headphone jack, the rear panel is line output and line input can be plugged into the speaker, layout-id is 430000000, 67.
When AudioOutMask=1, the front and rear sockets play sound, when AudioOutMask=2, only the front panel headphones play sound, (=4, =8, no sound), the back panel can not play the sound alone
When the Original AudioOut parameter was used, =0 was the back panel and =3 was the front panel headset

**Comment by vit9696** [comment]
Use -1. It is in the docs.

**Comment by wangdongfreesky** [comment]
使用-1是向所有通道播放声音，而我只想仅仅在某个通道（后面板扬声器）单独播放声音，其他的通道不播放声音。
Using -1 is to play sound to all channels, and I just want to play the sound separately in one channel (rear panel speakers) and the other channels do not play sound.

**Comment by vit9696** [comment]
cc @mikebeaton

**Comment by vit9696** [comment]
Please provide DEBUG log (Target = 67) with DEBUG OpenCore.efi and AudioDxe.efi.

**Comment by mikebeaton** [comment]
@vit9696 I think understand what is happening, it is (almost certainly) the new aggressive enabling of all I/O channels as O - which was required to get sound at all on the MacPro.

I think the correct solution is probably to put that feature on a driver flag - whether enabled or disabled by default is another question.

**Comment by mikebeaton** [comment]
@wangdongfreesky Thanks for the bug report. I need to produce some test versions for you to check which ones work again - it may be a couple of days before I can get to it, I hope that is okay.

**Comment by mikebeaton** [comment]
Actually here's a few to try, 3 different tests x DEBUG/RELEASE version of each. DEBUG and RELEASE should behave the same so you can test either. Can you let me know if any of these fix the problem.
[adtests1920.zip](https://github.com/acidanthera/bugtracker/files/7853576/adtests1920.zip)

**Comment by wangdongfreesky** [comment]
AudioDxe-DisableFix-RELEASE.efi解决了问题（Mask=1时，后面板单独播放声音，Mask=2时，前面板单独播放声音，Mask=3时，前面和后面均播放声音，和预期的一样），
AudioDxe-NoPinCaps-RELEASE.efi和AudioDxe-NoVref-RELEASE.efi和发行版一样，均不起作用！后面板无法单独播放声音！
AudioDxe-DisableFix-RELEASE.efi solves the problem (when Mask=1, the back panel plays the sound separately, when Mask=2, the front panel plays the sound separately, when Mask=3, the front and back play the sound, as expected),
AudioDxe-NoPinCaps-RELEASE.efi and AudioDxe-NoVref-RELEASE.efi, like the distro, do not work! The back panel cannot play sound alone!

**Comment by mikebeaton** [comment]
Should be fixed in master now. Thanks for report.
