### ISSUE TITLE
UHD630 External monitor connector在Index 00上

### ISSUE THREAD

**Issue by wangdongfreesky** [acidanthera/bugtracker#1921]
sorry！I am Chinese and speak very poor English！
我有一台dell 3681，显卡为UHD630，配备两个接口一个HDMI，一个DP2VGA（Unbuntu下识别为DP），HDMI使用Index01，busi ID09时，可以完美使用，但是这个外接的DP2VGA接口，只有在Index=0并且flags=98000000时，可以被hackintool识别，并且IOreg中有display，但是显示器是无信号的，并且系统概述中仅有hdmi的显示器，我使用3e9b0000，因为这个ID含有Index00！
如果在OC引导时首先使用DP2VGA，在选择引导macos后迅速插上HDMI，则在系统概述中显示vga显示器，并且可以设置镜像和扩展，但是vga显示器仍然是黑屏无信号的！
我看了代码，Index=00时，connector with zero index (LVDS) gets fPortType 3.但是这个机器Index=00的接口是普通的视频接口不是LVDS，因此出现黑屏问题
I have a dell 3681, the graphics card is UHD630, equipped with two interfaces, an HDMI, a DP2VGA (recognized as DP under Unbuntu), HDMI can be used perfectly when using Index01, busi ID09, but this external DP2VGA interface, only when Index=0 and flags=98000000, can be recognized by hackintool, And there is display in IOreg, but the monitor is signalless, and there is only hdmi monitor in the system overview, I use 3e9b0000 because this ID contains Index00!
If you use DP2VGA first when OC booting, plug in HDMI quickly after selecting to boot macos, the vga display is displayed in the system overview, and you can set up mirroring and expansion, but the vga monitor is still black screen without signal!
I looked at the code, index=00, connector with zero index (LVDS) gets fPortType 3. But the interface of this machine Index=00 is a normal video interface not LVDS, so there is a black screen problem！

**Comment by aksm-unmei** [comment]
I think this is not a right place to ask, but in your situation, I will give some advices (in my opinion):
- VGA is in "group" with DP, means when mapping, you should set the type to 04 (it's DP).
- VGA has busid is 0x02, 04, 05, 06. HDMI has busid 0x01, 02, 04, 05, 06. Try to map them with combo VGA-HDMI, ex: 02-01, 02-04, 02-05,...
- Note: Do not use the same busid more than once.

**Comment by wangdongfreesky** [comment]
你说的，我都尝试过，现在的类型改就是为400，尝试过其他的busid以及类型组合，但是我发现被识别的唯一条件是index00并且flags为98000000，但是仅仅被识别，无信号黑屏
I have tried everything you said. The current type is changed to 400. I have tried other busid and type combinations, but I found that the only condition for recognition is index00 and the flags are 98000000, but it is only recognized without signal black screen

**Comment by wangdongfreesky** [comment]
我想为你做点什么，但是又不知道提供点什么信息对你有用
I want to do something for you, but I don't know what information to provide that will work for yo
[Screenshots.zip](https://github.com/acidanthera/bugtracker/files/7860219/Screenshots.zip)
[DarwinDumper_3.1.1_2022.01.13_12.52.56_Macmini8,1_Opencore_4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version	REL-076-2021-12-06_Unknown_21C52_wangdongqq.zip](https://github.com/acidanthera/bugtracker/files/7860221/DarwinDumper_3.1.1_2022.01.13_12.52.56_Macmini8.1_Opencore_4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102.opencore-version.REL-076-2021-12-06_Unknown_21C52_wangdongqq.zip)
u

**Comment by wangdongfreesky** [comment]
[Uploading Untitled 
[dmesg.zip](https://github.com/acidanthera/bugtracker/files/7874482/dmesg.zip)
[Live].zip…]()

**Comment by andreszerocross** [comment]
> 你说的，我都尝试过，现在的类型改就是为400，尝试过其他的busid以及类型组合，但是我发现被识别的唯一条件是index00并且flags为98000000，但是仅仅被识别，无信号黑屏
> I have tried everything you said. The current type is changed to 400. I have tried other busid and type combinations, but I found that the only condition for recognition is index00 and the flags are 98000000, but it is only recognized without signal black screen

With index 00, which Bus id did you choose?? maybe the problem is about EDID. Try to add EDID of your monitor

**Comment by wangdongfreesky** [comment]
[Dmesg.zip](https://github.com/acidanthera/bugtracker/files/7874553/Dmesg.zip)
[log.zip](https://github.com/acidanthera/bugtracker/files/7874554/log.zip)
