### ISSUE TITLE
OpenCore's password screen will be hang if PickerAttributes=1

### ISSUE THREAD

**Issue by aksm-unmei** [acidanthera/bugtracker#1925]
I have just realized on my laptop, if I set the PickerAttibutes is 1, after enter the password and press Enter, OpenCore's password screen will be hang around 2 mins then automatic restarting. But if PickerAttributes is 17 (means pointer is available), everything is fine without any issues.
I dont think because of pointer lagging anymore because it already has been fixed with OC 0.7.7.
Spec: Dell G7 7588

**Comment by mikebeaton** [comment]
Debug log and config.plist

**Comment by aksm-unmei** [comment]
> Debug log and config.plist

[opencore-2022-01-14-153632.txt](https://github.com/acidanthera/bugtracker/files/7871506/opencore-2022-01-14-153632.txt)
[config.plist.txt](https://github.com/acidanthera/bugtracker/files/7871507/config.plist.txt)
Here they are.

**Comment by mikebeaton** [comment]
Great, thanks. Please can you send the debug log when PickerAttributes is 17 and it works.

**Comment by aksm-unmei** [comment]
> Great, thanks. Please can you send the debug log when PickerAttributes is 17 and it works.

oh that log is 17.
if you need the 1 to compare I can upload it now.

**Comment by aksm-unmei** [comment]
![image](https://user-images.githubusercontent.com/59220499/149563168-051f177c-3432-4a0f-a65d-7747b410cc3f.jpeg)
I got interesting picture...
I will upload the log later.

**Comment by aksm-unmei** [comment]
[opencore-2022-01-14-175914.txt](https://github.com/acidanthera/bugtracker/files/7872343/opencore-2022-01-14-175914.txt)
Here is the log with 1.

**Comment by mikebeaton** [comment]
cc @mhaeuser ^^

**Comment by mikebeaton** [comment]
Should be fixed as above.

**Comment by aksm-unmei** [comment]
> Should be fixed as above.

Thank you very much! I will try artifact asap.

**Comment by aksm-unmei** [comment]
@mikebeaton Confirmed! It works correctly. Thank you so much.
But there is a very small issue that if I restart from Mac/Windows, enter the password and hit Enter, it will take a long time to the show boot picker (about more than 2 mins, I used stopwatch to check). Even with Debug version, I had to wait to the next debug log.

```
58:047 00:135 OCC: Setting cc mode 0 -> 1
194:088 136:041 OCC: Setting cc mode 1 -> 0
194:285 00:196 OCHK: FreeHotKeys
194:417 00:131 OCTY: Unregistered handler
```
This one is restarting.

```
58:063 00:136 OCC: Setting cc mode 0 -> 1
72:721 14:658 OCC: Setting cc mode 1 -> 0
72:903 00:182 OCHK: FreeHotKeys
73:035 00:132 OCTY: Unregistered handler
```
This one is coldboot.

I attach the restart log here if you want to check it.
[opencore-password-restart-log.txt](https://github.com/acidanthera/bugtracker/files/7875438/opencore-password-restart-log.txt)

**Comment by mikebeaton** [comment]
It's actually meant to be very slow to show the picker after entering the password. It's meant to be a highly secure encryption algorithm, which is hard to brute force because it intentionally takes at least several seconds with an optimised algorithm on fast hardware. So it depends on what your hardware is as to whether that slow is too slow.

If there is a _difference_ in password validation speed between cold and warm boot, there should not be. Is there?

And the other differences between cold and warm boot I believe should not happen.

@mhaeuser - again! - if you have any time to look and comment.

**Comment by mikebeaton** [comment]
Also, @aksm-unmei, do you have `EnableVectorAcceleration` set? Depending on your hardware (i.e. if it shows in the log that it worked `OC: AVX enabled - 1`), this will make password validation faster.

**Comment by aksm-unmei** [comment]
> It's actually meant to be very slow to show the picker after entering the password. It's meant to be a highly secure encryption algorithm, which is hard to brute force because it intentionally takes at least several seconds with an optimised algorithm on fast hardware. So it depends on what your hardware is as to whether that slow is too slow.
> 
> If there is a difference in password validation speed between cold and warm boot, there should not be. Is there?
> 
> And the other differences between cold and warm boot I believe should not happen.
> 
> @mhaeuser - again! - if you have any time to look and comment.

Yes, there is no difference in password validation speed between cold and warm boot.

> Also, @aksm-unmei, do you have `EnableVectorAcceleration` set? Depending on your hardware (i.e. if it shows in the log that it worked `OC: AVX enabled - 1`), this will make password validation faster.

Oh yes, in my config `EnableVectorAcceleration` is enabled. I leave it by default when configuring config.plist file.

**Comment by mhaeuser** [comment]
The issue with the password algorithm is that is not an intrinsically secure algorithm, it is just iterative SHA, so we upped the rounds to still make it non-trivial to bruteforce. It's supposed to take long, but at most 15 - 20 seconds, not 2 minutes. Maybe try to disable the option Mike mentioned and try again? Otherwise we need to make sure this is only password checking that is the issue and make the number of rounds configurable.

**Comment by aksm-unmei** [comment]
> The issue with the password algorithm is that is not an intrinsically secure algorithm, it is just iterative SHA, so we upped the rounds to still make it non-trivial to bruteforce. It's supposed to take long, but at most 15 - 20 seconds, not 2 minutes. Maybe try to disable the option Mike mentioned and try again? Otherwise we need to make sure this is only password checking that is the issue and make the number of rounds configurable.

Sometimes after enter the password, OpenCanopy will show immediately. But like I said, sometimes it will be hang for a long time after input password and press Enter. It doesn't happen usually, for 10 times maybe 2-3 times will be like that.
Do you think maybe because of Dell's firmware? I think there are not many people like me using OpenCore's password so I'm not sure the issue is from Dell's firmware or other reasons.

**Comment by mhaeuser** [comment]
Yes, could be Dell's firmware, the password check itself cannot randomly be fast or slow.

**Comment by mikebeaton** [comment]
I've just tried on Dell OptiPlex 3070, password validation is just 4-5 secs, no variation.

There seem to be 2-3 things going on in @aksm-unmei's issue. Variable delay, but only with password on; and apparently keyboard behaving in a more laggy way in picker, but only with password on, if I've understood correctly.

@aksm-unmei - can you make a video of these behaviours? might help (especially with the keyboard issue).

**Comment by aksm-unmei** [comment]
I attach some videos about password screen. The Restart#3 took the longest time to show OpenCanopy.
Sorry I can't upload them to github directly because file size is large.
[Restart#1](https://youtu.be/WwpeWjlxjBo)
[Restart#2](https://youtu.be/WwFleYUx_Lg)
[Restart#3](https://youtu.be/ICmGVXt8Avg)
[Coldboot](https://youtu.be/M-qdF-HQK_M)

cc @mikebeaton @mhaeuser

**Comment by aksm-unmei** [comment]
> I've just tried on Dell OptiPlex 3070, password validation is just 4-5 secs, no variation.
> 
> There seem to be 2-3 things going on in @aksm-unmei's issue. Variable delay, but only with password on; and apparently keyboard behaving in a more laggy way in picker, but only with password on, if I've understood correctly.
> 
> @aksm-unmei - can you make a video of these behaviours? might help (especially with the keyboard issue).

My external keyboard seems fine and no laggy. Only laggy when OpenCanopy is showing boot menu.

**Comment by mikebeaton** [comment]
Thank you for the videos, they help - though I guess it's in your log files anyway.

The password verification time on cold boot is what it should be, and perfectly fast enough. Something is clearly wrong with the other three, and it is strange that this delay only happens when OC password is turned on.

(About keyboard delay, this is not so obvious in the videos, but you are saying that the internal keyboard (only?) is noticeably laggy - which I think you can just about see in the videos - in videos 1-3 but not cold boot, yes?)

**Comment by mikebeaton** [comment]
It is looking possibly as if your firmware is screwing up the CPU init, and your system is actually running extremely slowly until an OS starts up. I can add some debug prints to check that. But before trying that, one setting that might help is `IgnoreInvalidFlexRatio`, if you could try setting that to `true` and report whether it helps.

**Comment by aksm-unmei** [comment]
> Thank you for the videos, they help - though I guess it's in your log files anyway.
> 
> The password verification time on cold boot is what it should be, and perfectly fast enough. Something is clearly wrong with the other three, and it is strange that this delay only happens when OC password is turned on.
> 
> (About keyboard delay, this is not so obvious in the videos, but you are saying that the internal keyboard (only?) is noticeably laggy - which I think you can just about see in the videos - in videos 1-3 but not cold boot, yes?)
> 
> EDIT: It would help to know if keyboard is laggy after warm boot anyway, even if password is not enabled. Is it? :-)

Oh, I forgot to detail for you. In those videos I used external keyboard (not laptop's keyboard) and it was fine, no laggy. I have just tested with internal keyboard and seems no laggy when entering the password.


> It is looking possibly as if your firmware is screwing up the CPU init, and your system is actually running extremely slowly until an OS starts up. I can add some debug prints to check that. But before trying that, one setting that might help is `IgnoreInvalidFlexRatio`, if you could try setting that to `true` and report whether it helps.

Also I've just tested `IgnoreInvalidFlexRatio` too. Nothing improved (I think maybe because of Dell's firmware is AMI iirc).

And I have just done a random small test with Release at commit [009ff36](https://github.com/acidanthera/OpenCorePkg/commit/009ff3605b43f80b4b842e7a56192c74c9d0f29b):
PickerAttribute = 1
_First coldboot: More than 5 mins > I have to hard shutdown then power on again._
- Coldboot: 1m40s
- Reboot from Mac: 5s
- Reboot from Win: 5s

PickerAttribute = 17
- Coldboot: 7s
- Reboot from Mac: 6s
- Reboot from Win: 7s

Then I did some another random tests. The delay is almost happened with PickerAttribute = 1. With 17 every boot time is "average".

**Comment by mikebeaton** [comment]
If I have understood, the laptop's own keyboard is laggy, after entering the password, in the GUI picker (but not while entering the password, and not afterwards in the OS), and also this laggy behaviour only happens at the same times there is a long delay after entering password. Is that all correct? And can you show a video of the laggy kb behaviour?

Also, in the above results cold boot is the slow one, but in your videos cold boot was the fast one. I do not understand why this is reversed, but it sounds as if you expected it! Can you explain again how that matches up with different settings, in your understanding? Thx.

**Comment by aksm-unmei** [comment]
> If I have understood, the laptop's own keyboard is laggy, after entering the password, in the GUI picker (but not while entering the password, and not afterwards in the OS), and also this laggy behaviour only happens at the same times there is a long delay after entering password. Is that all correct? And can you show a video of the laggy kb behaviour?
> 
> Also, in the above results cold boot is the slow one, but in your videos cold boot was the fast one. I do not understand why this is reversed, but it sounds as if you expected it! Can you explain again how that matches up with different settings, in your understanding? Thx.

The laptop's own keyboard isn't laggy even in GUI picker and while entering 😅. The laggy which I mentioned is the GUI picker while showing the boot icons. It doesn't happen usually like I said. Sometimes it shows very fast like real Mac, sometimes doesn't. And the laggy is very similar to before PointerPollMask/Max were added in OC 0.7.7 (caused by dummy pointers, #1899). In my config.plist, if I disable the password and already enabled PointerPollMask=5 (enable both touchpad and mouse), PointerPollMax=100, GUI picker works correctly, no laggy and no delay time while waiting for FV2's UI.

[Here](https://youtu.be/_cYz4J07Zg8) is the video detail with keyboards.

Coldboot is slow if I set the PickerAttribute=1 (means no pointer, only password and GUI). It is fast if PickerAttribute=17, like the video I have just uploaded (pointer yes, password screen and GUI).
