### ISSUE TITLE
RX 550 - Correct Spoofing but no H264/Hardware Acceleration - Possible Feature Request

### ISSUE THREAD

**Issue by someofthem98** [acidanthera/bugtracker#1926]
Hi!

Issue is also posted into forums, it's possible that could be implemented (or already implemented it in WhateverGreen)
My Config:
B550 Master
RX 550 Pulse 2GB (LEXA)
16gb 3600 Ram
NVMe 970 Evo Plus

My Config it's not getting H264.
Tested with VideoProc, VDADecoderCheck.

VDA Error:
-12473

Already followed Opencore Guide for fixing DRMs.
Spoofing using SSDT.
no-gfx-spoof entered, device id 67FF

[opencore-2022-01-14-190641.txt](https://github.com/acidanthera/bugtracker/files/7873306/opencore-2022-01-14-190641.txt)
[Mac Pro.zip](https://github.com/acidanthera/bugtracker/files/7873305/Mac.Pro.zip)
Attached,IOReg,Opencore log.
EFI (Missing BT for dimensions)
[Archivio.zip](https://github.com/acidanthera/bugtracker/files/7873340/Archivio.zip)

**Comment by Andrey1970AppleLife** [comment]
We don't support AMD CPU users.

**Comment by vit9696** [comment]
Try -radcodec.

**Comment by andreszerocross** [comment]
I am using RX 550 Biostar, i am using  no-gfx-spoof, -radcodec, fake device id from DSDT, and using unfairgva.

DRM is working fine here, AppleTV and Netfilx over safari is good.

With IGPU intel HD 530 (Skylake) connectorless + RX 550 + SMBIOS iMac 17,1  = DRM is OK
without IGPU, just RX 550 + iMacPro1,1  = DRM is still OK too

**Comment by someofthem98** [comment]
Many thanks to all, using only -radcodec boot arg, problem is now solved.
![Schermata 2022-01-15 alle 09 44 39](https://user-images.githubusercontent.com/26902514/149615717-0c8c076a-28e3-4397-8ef6-55bbbf03bb30.png)

**Comment by andreszerocross** [comment]
Hi @vit9696  any idea to play Netflix in Safari. Netflix give error code with S7706. It's looks DRM problem

**Comment by andreszerocross** [comment]
Update : 
- Disable IGPU
- Change SMBIOS to iMacPro1,1
- stay with -radcodec and unfairgva=1

And netflix is playing in Safari :)
