### ISSUE TITLE
[Minor issue] Wrong release name for gfxutil 1.82

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1930]
Good morning, I would advise that the assets in gfxutil 1.82 contain a different name than the specified one in the latest release (1.81 instead of 1.82)

It would be great to rename/reupload them with their correct release name If possible, to avoid confusion:

`https://github.com/acidanthera/gfxutil/releases/download/1.82b/gfxutil-1.81b-RELEASE.zip`
`https://github.com/acidanthera/gfxutil/releases/download/1.82b/gfxutil-1.81b-DEBUG.zip`

should become: `https://github.com/acidanthera/gfxutil/releases/download/1.82b/gfxutil-1.82b-RELEASE.zip`
and for the debug version too: `https://github.com/acidanthera/gfxutil/releases/download/1.82b/gfxutil-1.82b-DEBUG.zip`

Thank you

**Comment by vit9696** [comment]
We will fix it in 1.83b (https://github.com/acidanthera/gfxutil/commit/2f6f1b12c8dc421e64470716aa1e0880e6a1b15d).
