### ISSUE TITLE
AppleALC 1.5.5 build error when signi

### ISSUE THREAD

**Issue by chadify** [acidanthera/bugtracker#1933]
I'm building it on the latest Xcode. I applied the recommended build settings and now getting the above compilation error. Before applying the setting AppleALC was compiling just fine.

Here's the screenshot:
![स्क्रीन शॉट 2022-01-23, अ 6 00 44 पर](https://user-images.githubusercontent.com/72332949/150679106-2c1ab866-d197-4060-b3ba-80cc2667bcc7.png)

**Comment by TheHackGuy** [comment]
Simply don't apply the recommended settings. 

The settings aren't the recommended ones for a reason.
