### ISSUE TITLE
brightness slider and brightness keys doesn't change brightness of screen

### ISSUE THREAD

**Issue by Mkhairy0100** [acidanthera/bugtracker#1936]
my notebook is legion 5 
comet lake cpu 10750h 
gpus intel HD 630 and rtx 3050ti disabled by Whatevergreen 
problem is brightness slider and brightness keys is working but doesn't have any effect on brightness on screen
on kernel log there is line
2022-01-28 00:15:25.277313+0200  localhost kernel[0]: (AGDCBacklightControl) AGDCBacklightControl: Didn't find DPMicro.
and this kext isn't loaded
attached my acpi folder and config file of OpenCore
[Archive.zip](https://github.com/acidanthera/bugtracker/files/7954223/Archive.zip)

**Comment by Lorys89** [comment]
edit the igpu patch, you should inject the device id as well, I see enable-backlight-smoother uses, but if you do not work the brightness does not make sense .. I were in you, I would make a new patch igpu. https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html#deviceproperties

**Comment by Lorys89** [comment]
yours is a problem of efi / config, this issue makes little sense, write on the forums if you want support.

**Comment by Mkhairy0100** [comment]
my igpu dev id is 0x9BC4 so it is natively supported so I think I don't need to inject anther dev id even I tried it before and didn't made any changes on this situation 
![Screen Shot 2022-01-28 at 1 27 27 AM](https://user-images.githubusercontent.com/72765111/151460281-644c672d-47be-4c2a-a45b-c94e8511bd42.png)

this notebook contain mux switch may be problem from this
also anther person on this guide he complains from this problem also
https://github.com/yusfklncc/Lenovo-Legion-5-Hackintosh

**Comment by Mkhairy0100** [comment]
this is my ioreg dump and dsdt
[Archive.zip](https://github.com/acidanthera/bugtracker/files/7958611/Archive.zip)
and this is method q11 and q12
`Method (_Q11, 0, NotSerialized)  // _Qxx: EC Query, xx=0x00-0xFF
            {
                If (IGDS)
                {
                    P80B = 0x11
                    Notify (^^^GFX0.DD1F, 0x87) // Device-Specific
                }
                Else
                {
                    P80B = 0x11
                    Notify (^^^PEG0.PEGP.EDP0, 0x87) // Device-Specific
                }

                Notify (VPC0, 0x80) // Status Change
            }

            Method (_Q12, 0, NotSerialized)  // _Qxx: EC Query, xx=0x00-0xFF
            {
                If (IGDS)
                {
                    P80B = 0x12
                    Notify (^^^GFX0.DD1F, 0x86) // Device-Specific
                }
                Else
                {
                    P80B = 0x12
                    Notify (^^^PEG0.PEGP.EDP0, 0x86) // Device-Specific
                }

                Notify (VPC0, 0x80) // Status Change
            }`

**Comment by Lorys89** [comment]
> this is my ioreg dump and dsdt [Archive.zip](https://github.com/acidanthera/bugtracker/files/7958611/Archive.zip) and this is method q11 and q12 `Method (_Q11, 0, NotSerialized) // _Qxx: EC Query, xx=0x00-0xFF { If (IGDS) { P80B = 0x11 Notify (^^^GFX0.DD1F, 0x87) // Device-Specific } Else { P80B = 0x11 Notify (^^^PEG0.PEGP.EDP0, 0x87) // Device-Specific }
> 
> ```
>             Notify (VPC0, 0x80) // Status Change
>         }
> 
>         Method (_Q12, 0, NotSerialized)  // _Qxx: EC Query, xx=0x00-0xFF
>         {
>             If (IGDS)
>             {
>                 P80B = 0x12
>                 Notify (^^^GFX0.DD1F, 0x86) // Device-Specific
>             }
>             Else
>             {
>                 P80B = 0x12
>                 Notify (^^^PEG0.PEGP.EDP0, 0x86) // Device-Specific
>             }
> 
>             Notify (VPC0, 0x80) // Status Change
>         }`
> ```

try this
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/7958919/config.plist.zip)

**Comment by Lorys89** [comment]
i see ioreg, and the pnlf is loaded correctly for cfl + 
0xFF7B is correct and _UID is correct.
![Schermata 2022-01-28 alle 14 42 14](https://user-images.githubusercontent.com/64613690/151557341-0569d876-b3ce-4fce-9672-8eb485f2d499.png)

**Comment by Mkhairy0100** [comment]
> 
thanks for your reply
tried it the same problem 
I think the problem at the level of acpi tables as the same problem on ubuntu also may be problem that Nvidia card control brightness don't know 
even tried this without disabling Nvidia card but nothing
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#no-brightness-control-on-dual-gpu-laptops

**Comment by andreszerocross** [comment]
If your screen is OLED then it's common problem. OLED Screen can't be adjust brightness. Slider and button is working but will no effect in screen. Make sure your internal screen is not OLED

**Comment by Mkhairy0100** [comment]
> If your screen is OLED then it's common problem. OLED Screen can't be adjust brightness. Slider and button is working but will no effect in screen. Make sure your internal screen is not OLED

it is IPS 
15.6" FHD (1920x1080) IPS 300nits Anti-glare, 165Hz, 100% sRGB, Dolby Vision, G-Sync, DC dimmer

**Comment by Andrey1970AppleLife** [comment]
> 
>  DC dimmer

Not supported. PWM only.

**Comment by DosDokTor** [comment]
Only for OLED: Install Lunar (a brightness controll app), enable gamma and drive the brightness using the GAMMA slider. It works perfectly.
