### ISSUE TITLE
Failed to get FSBFrequency

### ISSUE THREAD

**Issue by aleks5323** [acidanthera/bugtracker#1937]
OpenCore fails to boot. I did everything as said in manual, used latest versions of OC and kexts, but on boot I get stuck at black screen with text:
OCCPU: Failed to get FSBFrequency data using Apple Platform Info - Not Found
ASSERT [OpenCore] IoLibGcc.c(182): (Port & 3) == 0
I can boot into system just fine with OC 0.6.3 with the same kexts. Cannot provide any log files 'cause of lacking one in EFI partition (all debug options set as in instruction but OC is not creating one).
Specs:
MB: ga780t-d3l rev4.0
CPU: AMD FX-4300
GPU: GTX750Ti

Maybe I've missed something in config. Tell me if I can do anything to provide additional info or any logs.

[bad efi.zip](https://github.com/acidanthera/bugtracker/files/7965701/bad.efi.zip)

**Comment by mikebeaton** [comment]
You config.plist is significantly out of date for the current version of OpenCore, use ocvalidate tool which ships with OpenCore to check it.
Use forums for support.
