### ISSUE TITLE
OpenCore: Install macOS to MacintoshHD renaming?

### ISSUE THREAD

**Issue by roddy20** [acidanthera/bugtracker#1939]
It seems to be a workaround for a bug in Big Sur Beta only
all the older and newer systems can rename this partition properly
The proposition is to make this feature switchable Quirk or Patch, to restore the behavior of the original Mac

**Comment by mikebeaton** [comment]
I think this issue is invalid, since this is only applied if the unmodified volume name is "Preboot":

https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcBootManagementLib/BootEntryInfo.c#L707-L713

```
      } else if (StrCmp (BootEntry->Name, L"Preboot") == 0) {
        //
        // Common Big Sur beta bug failing to create .contentDetails files.
        // Workaround it by choosing the default name following Apple BootPicker behaviour.
        //
        TmpBootName = AllocateCopyPool (sizeof (L"Macintosh HD"), L"Macintosh HD");
      } else {
```

Please, shout if you disagree and I'll remove the label.

IIRC macOS itself sometimes gives the name "Macintosh HD" and times when this seems slightly annoying/weird, but can be worked around with volume labels, etc. (sorry not to be more precise!).

**Comment by roddy20** [comment]
i am not sure, but a lot of people at our forum say that name is OK with Clover and wrong with OpenCore when installing macOS or updates. I have not enough experience with newest macOS, (Sierra...Catalina worked without this renaming) but please pay more attention to this, thanks

**Comment by mikebeaton** [comment]
Ah sure - link possible? Idk which forum - tho I am sure others reading of course do.

**Comment by mhaeuser** [comment]
@roddy20 Clover's logic is partially mad and does not not reflect how real Macs determine the label at all (which does not mean it does not often **happen** to be right). Macs always use "disk labels", a feature we support in OpenCanopy on demand, and using them should always yield the precise behaviour as on Macs - if not, please report that separately. When disk labels are not enabled, we can only do so well with sane heuristics. Every now and then there is this *one* beta or build that does not properly create or update .contentDetails, but on a big scale the current solution is the most reliable there is in our experience. If we missed a variety of OSes where this is broken, we might discuss new solutions, but Big Sur Beta alone really is not worth bothring in my opinion.

**Comment by roddy20** [comment]
> Ah sure - link possible? Idk which forum - tho I am sure others reading of course do.

https://applelife.ru/threads/opencore-obsuzhdenie-i-ustanovka.2944066/page-714#post-972579
and 2 pages more...

**Comment by Andrey1970AppleLife** [comment]
> Ah sure - link possible? Idk which forum - tho I am sure others reading of course do.

It's nonsense there

**Comment by mikebeaton** [comment]
> It's nonsense there

Some sure is.

@roddy20 It's pretty easy to reverse the commit https://github.com/acidanthera/OpenCorePkg/commit/33c1bed2c199a1f21510799a730c435d542e66c3 - if you could come up with a setup where OC is applying the label Macintosh HD and we believe it shouldn't be, I'm happy to do a quick build without it (or perhaps you can already) and compare results.

**Comment by roddy20** [comment]
it depends of PickerAttributes value and it is not obvious for all the users, we'll check again, it will need some time
Thanks for your answers!

**Comment by roddy20** [comment]
![thumbnail_IMG_3515](https://user-images.githubusercontent.com/5681302/152327017-97070356-efbc-4b1b-bcfe-aff959501141.jpg)
Installing Monterey, 1st reboot, seems to be OK

**Comment by roddy20** [comment]
> > It's nonsense there
> 
> Some sure is.
it works OK, but it is not obvious for users. Maybe, we need to add a line about OC_ATTR_USE_DISK_LABEL_FILE to configuration.pdf "it is recommended to turn it ON for correct macOS Installer naming" or something like this

**Comment by mikebeaton** [comment]
Others who worked on this originally will already be clear about this, but can we just get clear here about what the wrong naming is when that bit is not set; i.e. with one or more specific examples? Does it affect the installer particularly? And does it, in the end, have anything to do with the Big Sur beta fix originally mentioned in this issue?

**Comment by roddy20** [comment]
it doesnot affect the installer, installer uses tardet-devices UUIDs, not these names, but it is confusing for first-time users. The fix itself is OK, i think it will be OK to mention this in the book, and add bit2=1 to config sample

**Comment by mikebeaton** [comment]
I don't mean it affects that _installation_. I know it doesn't. I mean does this misnaming issue (only) particularly affect the installer volumes. And can you just give some examples.

**Comment by vit9696** [comment]
Should file two separate tickets:

- Updating docs explaining pros and cons of OC_ATTR_USE_DISK_LABEL_FILE, among the cons will be no custom font support, less descriptive Recovery names, and perhaps partially broken custom labels. Need to carefully check this against the code and document.
- Recognising macOS Installer feature when possible even without this bit. Based on Preboot filesystem contents. Will require Preboot filesystem uploaded.

**Comment by roddy20** [comment]
> 

for the beginners there are no custom fonts and custom labels during the first install, macOS Installer is more important thing
advanced user can setup these later if he really needs

**Comment by mikebeaton** [comment]
> > 
> 
> for the beginners there are no custom fonts and custom labels during the first install, "macOS Installer" is more important thing advanced user can setup these later if he really needs

That makes sense. I've got a new install due right now, so I'll see what it says with and without disk labels.

**Comment by mikebeaton** [comment]
I feel like this issue is valid, it is #2 of your 2 suggested tickets, @vit9696.

I just tried the installer volume with and without disk labels, and of course it is called "macOS Installer" and "Macintosh HD" respectively, and called "Preboot" if commenting out that Bug Sur fix code.

**Comment by mikebeaton** [comment]
![Screenshot 2022-02-09 at 09 04 24](https://user-images.githubusercontent.com/11946605/153161977-85f13381-8024-44cf-ba5b-e1e6a4aab9b8.png)

@vit9696 Can use this?

**Comment by mikebeaton** [comment]
(I mean I think it might even ... _work_ ... to just change the Bug Sur fix to rename "Preboot" to "macOS Installer", though that's a bit messy. Obviously the issue is when else it might apply. But remaining question definitely is, if we did detect something like the above, do we still need the "Preboot" -> "Macintosh HD" rename?)

**Comment by roddy20** [comment]
IMHO "Preboot"  there was more intuitve than Macintosh HD

**Comment by roddy20** [comment]
If it was just a bug of beta , why do we need to correct it in OC? and once again, beginners do not install beta

**Comment by mhaeuser** [comment]
"Preboot" is an implementation detail for e.g. FileVault 2, not something user-facing. In the bless model by Apple, there is no reason for it to appear anywhere at all.

**Comment by mikebeaton** [comment]
> "Preboot" is an implementation detail for e.g. FileVault 2, not something user-facing. In the bless model by Apple, there is no reason for it to appear anywhere at all.

If you remove all the labels from the OS itself (in `/System/Volumes/Preboot/{GUID}/System/Library/CoreServices`) then it also displays as "Macintosh HD" in the current version.

Okay, understood (I hope!): 'Preboot' is more intuitive (perhaps) for 'something that should happen before normal boot' - but it is not more intuitive for 'anything that might be on the Mac main volume (including the OS itself)'. Agreed.

**Comment by roddy20** [comment]
> > 
> So okay, understood (I hope!): 'Preboot' is more intuitive (perhaps) for 'something that should happen before normal boot' - 

Yes. It was not a big problem to see Preboot there for a short time, i dont remember how it looks on real Mac and dont pay any attention to this, but two "Macintosh HD"s seem to be an imortant error for a lot of users

**Comment by mikebeaton** [comment]
Hmm - don't know error, but unintuitive/unhelpful, yes. Fixed!

**Comment by mikebeaton** [comment]
> but two "Macintosh HD"s seem to be an important error for a lot of users

Oh, I just parsed what you said. Two "Macintosh HD"s (per user at once; not 2 x the error...). This shouldn't happen unless the main OS is also missing its text label ... which also shouldn't happen, I don't think? But if so then, yes, correct, when the main OS is missing its text label (for whatever reason) and you are running the builtin text picker, or graphical picker with no graphical disk labels, then you would indeed see two "Macintosh HD"s - which is even less helpful, to the point of more or less unusable (well, you just have to rely on the fact the macOS+OC picks the correct one to boot next, which it should do, in fact).

But yeah, fix is better; at least (in the above case) the OS will be "Macintosh HD" and the installer will be "macOS Installer".

**Comment by mhaeuser** [comment]
@mikebeaton "Macintosh HD" is the default name for the system volume.

**Comment by roddy20** [comment]
In most cases system volume is called "Macintosh HD" at both Macs and Hacks, so another picker item with the same name looks strange

**Comment by mikebeaton** [comment]
Yes? I don't think I misunderstood that? Was just saying (I think correctly) that if you had ended up with main OS pre-boot location without any text labels (e.g. as per Big Sur beta bug) and the macOS installer pre-boot location without any text labels (which is how it normally is) then the builtin bootpicker (and Canopy without labels), would have shown them both exactly the same, as just "Macintosh HD" before this new fix. (I _think_ that was what @roddy20 was referring to.)

**Comment by mikebeaton** [comment]
> In most cases system volume is called "Macintosh HD" at both Macs and Hacks, so another picker item with the same name looks strange

If there's no other name to use (e.g. because Apple haven't provided any, except as a graphical image, and we are in a non-graphical environment), then there's not much else to use. But we agreed with you that this is inconvenient (at least) in the case of the installer, and that it is worth special code to detect that and give it a (text) name, even though Apple (don't need to) bother - because they only have one picker, and it will always use the graphical label which they do bother with.

**Comment by mikebeaton** [comment]
> @mikebeaton "Macintosh HD" is the default name for the system volume.

@mhaeuser  Oh sorry, okay, it ships as "Macintosh HD" - I geddit. Even worse then. Okay. Thank you.

**Comment by mhaeuser** [comment]
The point is it makes no difference whether the label is missing for the main volume, because it likely has "Macintosh HD" anyway.

**Comment by mikebeaton** [comment]
Yes, got it now. Sorry! Thanks for additional (very) relevant info.
