### ISSUE TITLE
alc282 with applealc  had loud pops at start up and shutdown

### ISSUE THREAD

**Issue by loverto** [acidanthera/bugtracker#1942]
1. I have also had loud pops at start up and shutdown
2. I have some linux references here。 [Sound Card Database](https://forums.solydxk.com/viewtopic.php?f=6&t=137&start=40)
3. The following is the lilu and applealc log
[alclog.txt](https://github.com/acidanthera/bugtracker/files/8213361/alclog.txt)

**Comment by loverto** [comment]
The core step to fix this problem on Linux is to customize the sound card initialization and shutdown callback functions. Is there a place to do the same in applealc @vit9696

**Comment by loverto** [comment]
![2A165EF9-FC19-49E8-B31E-1445932150A9](https://user-images.githubusercontent.com/3992018/152544922-a6d2c706-a0d8-4871-bc13-0f308ff323bd.png)
![image](https://user-images.githubusercontent.com/3992018/152545037-e31a5f17-b0b8-4e22-8e23-9f01515f5504.png)
![image](https://user-images.githubusercontent.com/3992018/152545103-ebb29c71-6b81-4e1d-8082-2791f3a3110d.png)

**Comment by loverto** [comment]
I started using dump_coeff on my computer to dump the coeff on the mac, but it doesn't work? Help.

RtHDDump.txt
dump_coef.txt

**Comment by loverto** [comment]
[dump_coef.txt](https://github.com/acidanthera/bugtracker/files/8203095/dump_coef.txt)
[RtHDDump.txt](https://github.com/acidanthera/bugtracker/files/8203096/RtHDDump.txt)

**Comment by loverto** [comment]
@narcyzzo

**Comment by loverto** [comment]
Failed to find ALCUserClientProvider services.

**Comment by Core-i99** [comment]
> Failed to find ALCUserClientProvider services.

Do you have alcverbs=1 bootarg?

**Comment by mikebeaton** [comment]
Instructions updated @ https://github.com/acidanthera/AppleALC/wiki/Dumping-processing-coefficients :

> alc-verb (available in AppleALC releases) must be installed on your path, and must also be enabled in config.plist (either write a non-zero value to the alc-verb property in DeviceProperties for your card, or add alcverbs=1 to boot-args).

**Comment by loverto** [comment]
It has been turned on, and now coefs is the same, but there is still noise when sleeping and waking up, continue to check the Linux source code, sound/pci/hda/patch_realtek.c

**Comment by loverto** [comment]
Now it can be confirmed that this code is the same for linux and mac.

![image](https://user-images.githubusercontent.com/3992018/157367317-ce4fb831-dc79-4626-a4af-fdb3ba905a17.png)

![image](https://user-images.githubusercontent.com/3992018/157367364-88c870b5-0681-453e-9700-3c7b02f5e81e.png)

![image](https://user-images.githubusercontent.com/3992018/157367415-dab579dd-c160-4b9a-b789-b7848de8b19d.png)


![image](https://user-images.githubusercontent.com/3992018/157367643-c6ded3dc-dfb4-4d8d-9e68-69afbcb9f41f.png)

**Comment by loverto** [comment]
Fix the noise after suspend and resume on ALC282 codec  When the power state of ALC283 codec goes to D3 or return back to D0, it gives a noise via headphone output. To follow the depop procedure, it will be better. 


```

// init
static void alc282_init(struct hda_codec *codec)
{
	struct alc_spec *spec = codec->spec;
    
	hda_nid_t hp_pin = alc_get_hp_pin(spec);
	bool hp_pin_sense;
	int coef78;

	alc282_restore_default_value(codec);

	if (!hp_pin)
		return;
    // detect jack
	hp_pin_sense = snd_hda_jack_detect(codec, hp_pin);
	coef78 = alc_read_coef_idx(codec, 0x78);

	/* Index 0x78 Direct Drive HP AMP LPM Control 1  */
	/* Headphone capless set to high power mode */
	alc_write_coef_idx(codec, 0x78, 0x9004);

	if (hp_pin_sense)
		msleep(2);

	snd_hda_codec_write(codec, hp_pin, 0,
			    AC_VERB_SET_AMP_GAIN_MUTE, AMP_OUT_MUTE);

	if (hp_pin_sense)
		msleep(85);

	snd_hda_codec_write(codec, hp_pin, 0,
			    AC_VERB_SET_PIN_WIDGET_CONTROL, PIN_OUT);

	if (hp_pin_sense)
		msleep(100);

	/* Headphone capless set to normal mode  */
	alc_write_coef_idx(codec, 0x78, coef78);
}
// 
static void alc282_shutup(struct hda_codec *codec)
{
	struct alc_spec *spec = codec->spec;
	hda_nid_t hp_pin = alc_get_hp_pin(spec);
	bool hp_pin_sense;
	int coef78;

	if (!hp_pin) {
		alc269_shutup(codec);
		return;
	}
        // 
	hp_pin_sense = snd_hda_jack_detect(codec, hp_pin);
	coef78 = alc_read_coef_idx(codec, 0x78);
	alc_write_coef_idx(codec, 0x78, 0x9004);

	if (hp_pin_sense)
		msleep(2);

	snd_hda_codec_write(codec, hp_pin, 0,
			    AC_VERB_SET_AMP_GAIN_MUTE, AMP_OUT_MUTE);

	if (hp_pin_sense)
		msleep(85);

	if (!spec->no_shutup_pins)
		snd_hda_codec_write(codec, hp_pin, 0,
				    AC_VERB_SET_PIN_WIDGET_CONTROL, 0x0);

	if (hp_pin_sense)
		msleep(100);

	alc_auto_setup_eapd(codec, false);
	alc_shutup_pins(codec);
	alc_write_coef_idx(codec, 0x78, coef78);
}


```

// Like this code how to fix it in applealc?
```
// detect jack
	hp_pin_sense = snd_hda_jack_detect(codec, hp_pin);
	coef78 = alc_read_coef_idx(codec, 0x78);

	/* Index 0x78 Direct Drive HP AMP LPM Control 1  */
	/* Headphone capless set to high power mode */
	alc_write_coef_idx(codec, 0x78, 0x9004);

	if (hp_pin_sense)
		msleep(2);

	snd_hda_codec_write(codec, hp_pin, 0,
			    AC_VERB_SET_AMP_GAIN_MUTE, AMP_OUT_MUTE);

	if (hp_pin_sense)
		msleep(85);

	snd_hda_codec_write(codec, hp_pin, 0,
			    AC_VERB_SET_PIN_WIDGET_CONTROL, PIN_OUT);

	if (hp_pin_sense)
		msleep(100);

	/* Headphone capless set to normal mode  */
	alc_write_coef_idx(codec, 0x78, coef78);
```

**Comment by loverto** [comment]
@vit9696 @Core-i99  @mikebeaton

**Comment by loverto** [comment]
https://www.kernel.org/doc/html/latest/sound/hd-audio/realtek-pc-beep.html

**Comment by mikebeaton** [comment]
Thanks for the cc. It seems to me this is an issue specific to the startup of the given card and layout: with research, you should be able to add/alter the verbs sent to the card to avoid the pops. So  I believe you can just change the config for your specific card in AppleALC, and if you fix it, make a PR. It is not clear that any change to the main code of AppleALC is needed.

**Comment by loverto** [comment]
This is not a problem with a single sound card, but a series. On linux, there will be hooks for startup and shutdown to handle this. I looked at the source code of applealc, but I didn't find where it can be operated. Maybe I need an example, I Try to modify the source code of applealc this week.

**Comment by loverto** [comment]
I've tried putting the command directly into configdata, but that doesn't work

**Comment by loverto** [comment]
Maybe applealc also needs to open two hooks for initialization and shutdown

**Comment by Core-i99** [comment]
> This is not a problem with a single sound card, but a series. On linux, there will be hooks for startup and shutdown to handle this. I looked at the source code of applealc, but I didn't find where it can be operated. Maybe I need an example, I Try to modify the source code of applealc this week.

Applealc can send verbs on startup. But not on shutdown, alcplugfix swift can do that. 

Applealc uses resources for this, no need for code changes.

**Comment by liangyi9812** [comment]
I also have the same issue with my MSI B760M-P motherboard's ALC897. The most noticeable manifestation occurs at the beginning of boot at stage two, where the audio device emits 5~6 consecutive loud pop sounds. Is there a universal solution to this problem? Not long ago, my computer suddenly couldn't find the audio device, and after that restart, the motherboard became unresponsive and couldn't boot anymore. As a result, I had to send my motherboard for repairs. I'm not sure if it's related to this issue.@loverto
