### ISSUE TITLE
ASUS P5G41T-M LX ALC887 AudioDxe 0.7.7 breaks sound in macOS

### ISSUE THREAD

**Issue by mikebeaton** [acidanthera/bugtracker#1945]
Reported by @Gankosakae in https://github.com/acidanthera/bugtracker/issues/740#issuecomment-1031186919:

I upgraded OC to 0.7.7 and AppleALC.kext seems loaded properly.
But,it is no sound in-OS.
When I turn AudioDxe back to OC 0.7.6's,audio in-OS is worked.
So,I thought it should have something wrong with AudioDxe.
After some try and error,I found build [52f0d2c](https://github.com/acidanthera/OpenCorePkg/commit/52f0d2c55afaa080e30dfe52c7c7f48e71cfe6e4) AudioDxe's audio in-OS still worked.
But,audio in-OS broken from build [4f214ab](https://github.com/acidanthera/OpenCorePkg/commit/4f214ab1e5f3c17fa270437829f2c762d009bd24).
Comment in build 4f214ab seems to fix Windows audio in-OS.

My desktop is ASUS P5G41T-M LX mainboard with ALC887.
And OS is OS X El Capitan 10.11.6.

Thanks a lot if anyone can help.

**Comment by mikebeaton** [comment]
@Gankosakae Thank you for identifying the relevant commit.

Please can you try the build artefacts of this test change, and confirm whether it fixes your problem?

commit: https://github.com/acidanthera/OpenCorePkg/commit/c616e7b2ed95258328a35943a6c6081e16e277a1

build artefacts linked on this page: https://github.com/acidanthera/OpenCorePkg/runs/5091397665

**Comment by Gankosakae** [comment]
Yes, it solved.
Sounds in-OS worked with this build's AudioDxe.
Thank you.

**Comment by mikebeaton** [comment]
Since it is breaking sound on some machines but fixing it on others, it should be an option. Probably opt-in, to be applied by the people who had the problem before. I will do that at some point in the next days.

**Comment by Gankosakae** [comment]
Thanks a lot for your help. 😃

**Comment by mikebeaton** [comment]
@Gankosakae - Please check and confirm that https://github.com/acidanthera/OpenCorePkg/commit/0455326487726e3ac974f7ea14030accb736ba1d fixes your issue.

**Comment by Gankosakae** [comment]
YES.
Build 0455326 fixed no sounds in-OS.
Thank you very much.
