### ISSUE TITLE
[Request] AirportBrcmFixup Documentation Update Required for brcmfx-delay

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1946]
Some form of update of the documentation is needed to provide guidance, however basic, on the `brcmfx-delay` property.

cc @ivs1974

**Comment by dakanji** [comment]
Meant @lvs1974

**Comment by lvs1974** [comment]
https://github.com/acidanthera/AirportBrcmFixup: README:
brcmfx-delay delays start of native broadcom driver for specified amount of milliseconds.

**Comment by dakanji** [comment]
Thanks. Would be nice to have some guidance on values ... 100, 1000, 10000?

**Comment by lvs1974** [comment]
@dakanji: It is very individual, sorry.
Try a few seconds.

**Comment by dakanji** [comment]
I suppose adding this to the ReadMe would already give better clarity over the current state.

**Comment by vit9696** [comment]
@lvs1974 I think it is indeed better to add the order of the values to the README.

**Comment by lvs1974** [comment]
ReadMe file has been corrected.
