### ISSUE TITLE
AppleALC microphone buffer problem

### ISSUE THREAD

**Issue by kekkokk** [acidanthera/bugtracker#1948]
Hi everyone,
I am facing a strange issue which I am trying to solve.
I do not have any debug logs to provide since this only happens rarely after wake.
This happened before on Big Sur and now with Monterey.

When opening the lid on my thinkPad t480s (ALC257 with layout id 11) the audio captured from internal microphone glitches:
The captured audio seems to be the last X milliseconds of buffer played in loop sequence.
The only way to fix this in Big Sur was to reboot, but now with Monterey I noticed that sometimes this gets fixed by making the laptop going to sleep and then wake it again.

Do you have any hint on where to start debugging/fixing?

OpenCore 0.7.7 + Lilu 1.5.9 + AppleALC 1.6.8
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/8023550/config.plist.zip)

**Comment by harethpy** [comment]
Try layout ID 86 or 18

**Comment by Core-i99** [comment]
Probably certain verbs need to be send to get the microphone working properly after sleep. Try linux like an Ubuntu live usb and see if you got the same problem with Linux. 

If it works with Linux then look at their code and see which verbs they send. Then you can make a new layout id for applealc with those verbs.

**Comment by vit9696** [comment]
Fixing up resources in AppleALC is out of the scope of this bugtracker as we do not develop them. Contacting the the resource maintainer is the right choice in such case.
