### ISSUE TITLE
Lilu and FeatureUnlock on Mac mini 2018: kernel panic

### ISSUE THREAD

**Issue by i0ntempest** [acidanthera/bugtracker#1949]
Hi,
Since I wanted to use AirPlay receiver on my Mac mini 2018, I was trying to use Lilu and FeatureUnlock kexts to unlock it. I have installed them to /L/E and correct permissions applied. However it causes kernel panic on boot.
I'm running macOS 12.3 beta but I'm not sure if it's related. Panic log will be posted soon.

**Comment by PMheart** [comment]
No. LiluFriend will not work now. It has been archived only for history tracking purposes.
