### ISSUE TITLE
Disable TRIM when mounting the system partition on 12+

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#1950]
Reference: https://www.applelife.ru/threads/ustanovka-macos-monterey-12-na-intel-pc.2945811/page-344#post-973762

As of 12.0, the quirk `SetApfsTrimTimeout` no longer works, nor is it possible to set the timeout value now.
One workaround includes a patch discovered by @lvs1974, which can be found on the link above.

As a result, the following changes will be made to OpenCore:
- Remove [mApfsTimeoutV2Patch](https://github.com/acidanthera/OpenCorePkg/blob/459849c8c3c16e74b22e4cdb346e73ce95e0a8db/Library/OcAppleKernelLib/CommonPatches.c#L1997) as it have never worked
- Adopt the new patch posted on AppleLife on macOS 12+

CC @lvs1974

**Comment by lvs1974** [comment]
@PMheart: good to know you are going to implement this!
One notice: this patch works also for Mojave 10.14.

**Comment by Andrey1970AppleLife** [comment]
> One notice: this patch works also for Mojave 10.14.

Yes, but for macOS 11 and older there is SetApfsTrimTimeout. The new patch is necessary only for 12+.

**Comment by PMheart** [comment]
Thanks @Andrey1970AppleLife and @lvs1974. Then shall I only apply the new patch on 12.0+?

**Comment by Andrey1970AppleLife** [comment]
I think it the user shall solve.
CC @vit9696

**Comment by vit9696** [comment]
I believe we should use one quirk for all operating systems. The choice of the patch should happen based on the OS and the value matrix:

Value of 0:
* 10.13 — old patch
* 10.14+ — new patch

Value > 0.
* 10.13—11.x — old patch
* 12.x+ — no patch and notification message in the log and docs
