### ISSUE TITLE
RestrictEvents 1.0.7 disk messages popup is broken

### ISSUE THREAD

**Issue by AlexanderKry** [acidanthera/bugtracker#1952]
In RestrictEvents 1.0.6 feature is "Disabled The disk you inserted was not readable by this computer message popup​" are worked fine for me. But in RestrictEvents 1.0.7 it is broken. I have two NTFS dynamic disks and both popups are shown again after login in Mac OS

**Comment by vit9696** [comment]
Not a bug. 1.0.7 made this feature opt-in, you need to reconfigure it with NVRAM/boot-args.
