### ISSUE TITLE
100% fine on OC 0.7.6, immediate fail on 0.7.7 and 0.7.8

### ISSUE THREAD

**Issue by Stooovie** [acidanthera/bugtracker#1953]
My system is 100% perfect with OC 0.7.6 and Monterey 12.2. After updating to either 0.7.7 or 0.7.8, system immediately fails with EXITBS.  

**ocvalidate finds no errors**. Every update since 0.5.7 went fine until this, shouldn't be an user error. 

**Asked around on OC Discord and r/hackintosh to no avail.** 

i9 10850k on Asus Z490-P, RX 580, Monterey 12.2. No issues at all on 0.7.6. 0.7.7 and 0.7.8 have the same issue.

Tried, didnt fix:

- manually updated according to the Changes document, and also OC Auxilliary Tools, same result
- DevirtualizeMMIO "false"
- setting new properties to failsafe values or not
- resetting NVRAM
- booting just with Lilu, VirtualSMC, WEG kexts
- using Snapshot and Clean Snapshot from newly downloaded ProperTree
- making sure UEFI/Drivers is the correct new format (Enabled, Path, Arguments, Comments)

[Here's the boot screen](https://i.imgur.com/S8u0t89.jpg).

100% working 0.7.6 EFI [here](https://anonfiles.com/HbN5q4H7x0/working_EFI_zip)
Non-working 0.7.8 EFI [here](https://anonfiles.com/FcN4q3H6xa/not_working_EFI_zip)

Please help, thanks!

**Comment by vandroiy2013** [comment]
ProvideCurrentCpuInfo must be false! Read the manual.

**Comment by Stooovie** [comment]
I did, neither Configuration nor Differences mention anything about Monterey related to ProvideCurrentCpuInfo at all. 

Thank you.

**Comment by vandroiy2013** [comment]
0.7.7 Differences.pdf. It is not Monterey related. Why did you turn on this quirk at all? It was needed only for Microsoft Hyper V. 

<img width="831" alt="Снимок экрана 2022-02-11 в 13 57 22" src="https://user-images.githubusercontent.com/8144780/153587600-cdc8e5b0-2cab-459d-908d-23cd1cc1dfa3.png">

**Comment by Stooovie** [comment]
Thank you again, I can boot with ProvideCurrentCpuInfo=false. Case closed.

I'm re-reading the excerpt you provided and I just don't see it. I had it enabled because I assumed it's better for virtualization (that I do use sometimes). It was fine enabled up to OC 076 and Monterey 12.2.
