### ISSUE TITLE
Opencore windows11(KB5010414) boot have problem

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#1956]
I update to last windows 11 KB5010414 and active hyper v on windows feature on/off for windows subsystem windows show rest sysytem after rest and boot with opencore show blue screen 

I try boot to windows with bios F9 windows boot successfully to windows 

opencore : v0.7.9 dev([ae04256](https://github.com/acidanthera/OpenCorePkg/commit/ae04256ac544b56766978c1a29ccdd13d75ce38b))

screenshot:
![b159bf50-aa20-477c-a383-cb6e966b88f7](https://user-images.githubusercontent.com/35195176/154496812-f020008b-042f-450e-a721-76d140525e32.jpg)

**Comment by mikebeaton** [comment]
> I update to last windows 11 KB5010414 and active hyper v on windows feature on/off for windows subsystem

Before these two changes Windows was booting via OpenCore?

After these two changes, Windows boots directly from BIOS, but not via my OpenCore?

What do you mean by "windows show rest sysytem after rest"? ("rest" should be "restart", right?)

**Comment by Edwardwich** [comment]
I think open core has a problems with Hyper V Platform

**Comment by mikebeaton** [comment]
No, in general it doesn't, it works fine for most people. But you do seem to have a setup where it has a problem, so it would be good to understand what the issue is 

We recently added an `EnableVmx` quirk https://github.com/acidanthera/bugtracker/issues/1870, you could try changing the value of that, though unfortunately I don't think it is likely to be the issue.

**Comment by Edwardwich** [comment]
> No, in general it doesn't, it works fine for most people. But you do seem to have a setup where it has a problem, so it would be good to understand what the issue is 
> 
> We recently added an `EnableVmx` quirk https://github.com/acidanthera/bugtracker/issues/1870, you could try changing the value of that, though unfortunately I don't think it is likely to be the issue.

I try to enable vmx boot not fix

**Comment by mikebeaton** [comment]
Okay, thx for testing.

How far through Windows boot does it get - can you make a video of the boot sequence up to the blue screen?

Please post your config.plist.

Also, is it reversible? i.e. if you remove Hyper-V component from Windows again, will it boot via OpenCore again?

**Comment by Edwardwich** [comment]
> Okay, thx for testing.
> 
> How far through Windows boot does it get - can you make a video of the boot sequence up to the blue screen?
> 
> Please post your config.plist.
> 
> Also, is it reversible? i.e. if you remove Hyper-V component from Windows again, will it boot via OpenCore again?

Yes if I I disable Hyper-V Opencore boot windows without blue screen

**Comment by Edwardwich** [comment]
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/8096751/config.plist.zip)

**Comment by Edwardwich** [comment]
[boot video.mp4.zip](https://github.com/acidanthera/bugtracker/files/8096770/boot.video.mp4.zip)

**Comment by mikebeaton** [comment]
Hmmm. Ty. No spinning dots, even? Does your system normally have them? Perhaps can post vid of successful boot, to compare timings?

**Comment by Edwardwich** [comment]
> Hmmm. Ty. No spinning dots, even? Does your system normally have them? Perhaps can post vid of successful boot, to compare timings?

u need video boot windows with opencore when Hyper-V disable?

**Comment by mikebeaton** [comment]
> u need video boot windows with opencore when Hyper-V disable?

y

**Comment by mikebeaton** [comment]
Maybe worth noting the same issue (without a fix) is here too: https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/295

**Comment by Edwardwich** [comment]
> > u need video boot windows with opencore when Hyper-V disable?
> 
> y
[Uploading WhatsApp Video 2022-02-18 at 16.08.03.mp4.zip…]()

**Comment by mikebeaton** [comment]
^^^ That didn't work - but probably just to go to #1831 and work from the instructions and links there.

**Comment by Edwardwich** [comment]
> ^^^ That didn't work - but probably just to go to #1831 and work from the instructions and links there.

It's fix TNX man

**Comment by alizataqy** [comment]
how do you fix it?

**Comment by mikebeaton** [comment]
> how do you fix it?

Probably SyncRuntimePermissions ->True based on the thread linked above.

If not, check the settings in https://github.com/acidanthera/bugtracker/issues/491#issuecomment-610255296
