### ISSUE TITLE
Open Core AppleXcpmForceBoost probably broken again.

### ISSUE THREAD

**Issue by narcyzzo** [acidanthera/bugtracker#1957]
Hello, Running 12.3 Beta 3 here, i Have my CPU *I7-9700K* clocked on all cores to 5 GHZ, `AppleXcpmForceBoost` quirk enabled, sometimes Intel Power Gadget showing 4.90 and lower freq. I remember this quirk is already broken on Monterey and fixed, but now its possible some MacOS update broke it again. If this is not enough info, how can i debug it more? Thanks!

**Comment by 1alessandro1** [comment]
Did you manage to unlock your CFG Lock setting in your BIOS instead of being forced to use that quirk which causes more harm than good?

**Comment by vit9696** [comment]
cc @PMheart @dhinakg @khronokernel are you aware of this issue? Can you check the patch?

**Comment by PMheart** [comment]
Could anyone please upload the kernel from 12.3 Beta?

**Comment by PMheart** [comment]
Hello, I took a quick look at the latest kernel. Looks like there were no significant changes compared to some earlier betas of 12.0. (e.g. https://github.com/acidanthera/bugtracker/issues/1685)

Do you remember what was the last version it worked?

**Comment by mikebeaton** [comment]
@narcyzzo - can you post debug log, to be able to see whether the patch thinks it has applied itself or not.

**Comment by narcyzzo** [comment]
> 
> Do you remember what was the last version it worked?
>
Unfortunately no :/ log attached 
[opencore-2022-03-08-000437.txt](https://github.com/acidanthera/bugtracker/files/8201597/opencore-2022-03-08-000437.txt)
<img width="512" alt="Zrzut ekranu 2022-03-8 o 01 01 18" src="https://user-images.githubusercontent.com/54555731/157139805-5999e904-3ab9-4dd5-a11a-a3f34b069c73.png">

**Comment by mikebeaton** [comment]
`OCAK: Patch write max to MSR_IA32_PERF_CONTROL` in the log means the patch has succeeded.

The performance looks fine to me, it does max. at 5GHz.

**Comment by PMheart** [comment]
Same. I do not see any problem here.
