### ISSUE TITLE
I’d like to add an example of "en-US:0" and "ja-JP:0" to prev-lang:kbd in Sample.plist.

### ISSUE THREAD

**Issue by rkarsnk** [acidanthera/bugtracker#1960]
Hello, I'm rkarsnk, OpenCore user in japan.

Japanese users are often faced with the problem default locale is Russian. So, I would like to add an example `prev-lang:kbd` description of `en-US:0`, `ja-JP:0` and `ja-JP:16384` in Sample.plist.

``` 
[Docs/Sample.plist]
 1241                    <key>csr-active-config</key>                                         
 1242                    <data>AAAAAA==</data>                                                
 1243                    <key>prev-lang:kbd</key>                                             
 1244  +                 <!-- For Russian locale and ABC keyboard -->                         
 1244                    <data>cnUtUlU6MjUy</data>                                            
 1246  +                 <!-- For English locale and US keyboard -->                           
 1247  +                 <!--                                                                 
 1248  +                 <data>ZW4tVVM6MA==</data>                                            
 1249  +                 -->                                                                  
 1250  +                 <!-- For Japanese locale and US keyboard -->                          
 1251  +                 <!--                                                                 
 1252  +                 <data>amEtSIA6MA==</data>                                            
 1253  +                 -->                                                                  
 1254  +                 <!-- For Japanese locale and KANA keyboard -->                        
 1255  +                 <!--                                                                 
 1256  +                 <data>amEtSlA6MTYzODQ=</data>                                        
 1257  +                 -->                                                                  
 1245                    <key>run-efi-updater</key>                                           
 1246                    <string>No</string>                                                  
 1247                </dict>                                                                  
 1248
```

**Comment by vit9696** [comment]
Why cannot we use #?

**Comment by rkarsnk** [comment]
Sorry, I don't know "#?".  What is "#?" ?

**Comment by vit9696** [comment]
You can write a dictionary key with # to make it a comment. I would suggesting having a comment with different prev-lang values at best. XML comments are undesired because PLIST files are not meant to be edited by hand.

**Comment by rkarsnk** [comment]
>You can write a dictionary key with # to make it a comment. I would suggesting having a comment with different prev-lang values at best.

Thank you.I try to write to use a dictionary key with # .

>XML comments are undesired because PLIST files are not meant to be edited by hand.
Sorry, I used Emacs(on Linux) to edit PLIST files.

**Comment by rkarsnk** [comment]
I tried to use a key with #.  

I add a `#INFO (prev-lang:kbd) -x`  keys and sample values.

```
[Docs/Sample.plist]
@@ -1240,6 +1240,12 @@                                                                        
 1240                    <string>-v keepsyms=1</string>                                       
 1241                    <key>csr-active-config</key>                                         
 1242                    <data>AAAAAA==</data>                                                
 1243  +                 <key>#INFO (prev-lang:kbd) -1</key>                                  
 1244  +                 <string>If you use en-US:US, set 656E2D55 533A30</string>            
 1245  +                 <key>#INFO (prev-lang:kbd) -2</key>                                  
 1246  +                 <string>If you use ja-JP:US, set 6A612D48 803A30</string>            
 1247  +                 <key>#INFO (prev-lang:kbd) -3</key>                                  
 1248  +                 <string>If you use ja-JP:KANA, set 6A612D4A 503A3136 333834</string> 
 1243                    <key>prev-lang:kbd</key>                                             
 1244                    <data>cnUtUlU6MjUy</data>                                            
 1245                    <key>run-efi-updater</key>                                           
 1246
```

**Comment by PMheart** [comment]
こんにちは！

Why not default to `en-US:US` actually? And it's better to mention such layout settings in Configuration.pdf instead of in the sample config, in my opinion.

**Comment by Andrey1970AppleLife** [comment]
> Why not default to `en-US:US` actually?

In Acidanthera team majority of Russians speaking. :)



> And it's better to mention such layout settings in Configuration.pdf instead of in the sample config, in my opinion.

The link already is in Configuration.pdf 
https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/AppleKeyboardLayouts/AppleKeyboardLayouts.txt

**Comment by vit9696** [comment]
To be fair, I think it is ok to add a comment with en:252 to help others (English — ABC).

**Comment by rkarsnk** [comment]
@vit9696 
>To be fair, I think it is ok to add a comment with en:252 to help others (English — ABC).
That's great for me! Thank you!

**Comment by vit9696** [comment]
Please send a PR.

**Comment by rkarsnk** [comment]
I send a PR (https://github.com/acidanthera/OpenCorePkg/pull/324) .

**Comment by mifjpn** [comment]
I pay tribute to the efforts of the developers.
In Japan, the following sequences are generally used on a daily basis. (Ja-JP: 0 seems to be used by programmers in many cases)
prev-lang:kbd ja-JP:252
Since it is set like this on an actual Mac, please add this notation as well.
Sample Web-page
https://tamoc-com.translate.goog/display-nvram/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=wapp
