### ISSUE TITLE
Latest Windows image breaks ocbuild

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#1962]
With the latest version of Windows, ocbuild seems to have stopped working. ([Example](https://github.com/acidanthera/OpenCorePkg/runs/5319588031?check_suite_focus=true#step:5:12))

As a temporary workaround, we fell back to windows-2019 as is done at https://github.com/acidanthera/OpenCorePkg/commit/4c400769d48701d416ebe936bab14aabf3d8eefd.

Further inspections are required.

**Comment by vit9696** [comment]
This is tracked upstream by Mu folks in https://github.com/tianocore/edk2-pytool-library/issues/154.

**Comment by vit9696** [comment]
The upstream issue is fixed. @PMheart, could you try to upgrade to new VS?

**Comment by vit9696** [comment]
Thank you for updating OC! This should be tested and then updated in audk CI as well.
