### ISSUE TITLE
Metal is not enabled when using "GPU Fake ID".

### ISSUE THREAD

**Issue by Sybel** [acidanthera/bugtracker#1963]
When using "GPU Fake ID" with Opncore 0.7.8, GPUs that are not supported by Apple only have Metal2 correspondence judgment, not Metal correspondence judgment.
For this reason, we cannot get Metal Accelerat on GPUs that do not support Metal2.

Please verify the attached kernel.log tested with HD7750 on MacOS 12.1.

HD7750.txt: It boots normally without using "GPU Fake ID".
HD7770.txt: Impersonating HD7770 (0x683D1002) using "GPU Fake ID".
SPOOF_HD7750.txt: You are setting HD7750 (0x683F1002) using "GPU Fake ID".

I'm currently testing the R7 240 on MacOS 10.13.6 (High Sierra).
I have been using OpenCore 0.7.1 in the past and it can be installed / updated normally, but unfortunately when I use OpenCore 0.7.1, I get a black screen on MacOS 10.14.6 (Mojave).

R7 240.txt: Booted with OpenCore 0.7.1.
0.7.8.txt: Booted with OpenCore 0.7.8.

Please modify OpenCore so that you can use R7 240 normally like HD7750.
[TEST_LOG.zip](https://github.com/acidanthera/bugtracker/files/8148955/TEST_LOG.zip)

**Comment by khronokernel** [comment]
The 7750 is based off the Cape Verde core and uses the `AMDVerdeGraphicsAccelerator` class. Back in High Sierra, the R7 240 unofficially worked with the Verde class even though the core itself is an Oland via PCI ID spoofing. However Oland cores didn't support Metal even back in High Sierra, which sometimes was misreported by macOS.

With Mojave and the forced mandate of Metal userspace rendering, these cards break more so as they no longer have the OpenGL fallback as High Sierra did.

As the Oland series wasn't officially supported by Apple even back in High Sierra and has quite the small family of cards, I don't believe there's much interest in dedicating resources to it (others can chime in on whether any work's been done). However feel free to research further yourself and PR to [WhateverGreen](https://github.com/acidanthera/WhateverGreen). Always appreciate extra help.

**Comment by Sybel** [comment]
Thank you for your response, the question about kernel logs has been resolved.

Currently, there are few types of AMD Low profile GPUs available, and the description in the ["GPU-Buyers-Guide" ](https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#r7-r9)seems to indicate that he is increasingly choosing the R7 240/250 Oland.
I didn't know anything about "how does it work?", So I was wondering what I bought and tried myself.

I will warn others not to buy Oland GPUs if I have the opportunity.
