### ISSUE TITLE
Opencanopy: keyboard and mouse hang

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1965]
Opencore commit:
https://github.com/acidanthera/OpenCorePkg/commit/ef780318098d7c86691c378e1fb204f0e8c89fc2

Issue: in opencanopy keyboard and mouse seem to hang sometimes.
Look at the video for more details.
Issue reported by several users also on insanelymac.
In the video, mouse doesn't hang, but it happened (pointer movement is always ok, it's the click that sometimes is not detected too).

https://user-images.githubusercontent.com/18054052/156550728-a3c332c0-452a-4e73-b43b-5e8cc5730252.mp4

**Comment by vit9696** [comment]
Please provide the last working and first broken build. CC @PMheart

**Comment by PMheart** [comment]
Hello! It seems to be a overlook. I have reverted the changes at https://github.com/acidanthera/OpenCorePkg/commit/c91eebf3f4a948e825916935036f31ece2c75e89. Please try again and report. Thanks!

**Comment by 82ghost82** [comment]
[89f40f6](https://github.com/acidanthera/OpenCorePkg/commit/89f40f6ea84af65f19fad49b8fdd18d934ba1932) --> working

[7c69500](https://github.com/acidanthera/OpenCorePkg/commit/7c695007ae70d53a21f12f5cd62452cad9a95894) --> not working

Thanks

**Comment by 82ghost82** [comment]
@PMheart , exact, now it's fine.

**Comment by PMheart** [comment]
> [89f40f6](https://github.com/acidanthera/OpenCorePkg/commit/89f40f6ea84af65f19fad49b8fdd18d934ba1932) --> working
> 
> [7c69500](https://github.com/acidanthera/OpenCorePkg/commit/7c695007ae70d53a21f12f5cd62452cad9a95894) --> not working
> 
> Thanks

That's it then. It was my mistake, sorry!

Closed.
