### ISSUE TITLE
ThinkPad X270 - Touchpad Buttons weird behaviour

### ISSUE THREAD

**Issue by niklasarnitz** [acidanthera/bugtracker#1966]
The Trackpad on my ThinkPad X270 has some weird behaviour.

The Touchpad itself has working gestures, scrolling etc.
Only clicking is an issue.
Every click is a right click.
The three buttons in the top of the trackpad -> Rightclick
The Trackpad itself -> Rightclick

Attached you may find my OpenCore log and the IORegistry Entry for my trackpad.

**Comment by niklasarnitz** [comment]
![Screenshot 2022-03-03 at 04 24 44](https://user-images.githubusercontent.com/24507162/156564289-828120cd-bebd-4b4c-9970-216a744057f7.png)
![Screenshot 2022-03-03 at 04 24 35](https://user-images.githubusercontent.com/24507162/156564294-2c58aca4-69eb-4a15-95e5-1fd532c61d92.png)
![Screenshot 2022-03-03 at 04 24 25](https://user-images.githubusercontent.com/24507162/156564296-6784db34-5c71-4e35-9022-cc737e74abe6.png)

**Comment by vit9696** [comment]
cc @1Revenger1 @zhen-zen @usr-sse2

**Comment by zhen-zen** [comment]
Haven't found the attachment. But a quick search seems to address this issue: https://www.tonymacx86.com/threads/synaptic-trackpad-buttons-not-working-on-thinkpad-x270-with-voodoops2controller.286801/

The post suggests a plist change for Thinkpad_Clickpad. We also have VoodooPS2/Docs/ACPI/SSDT-Thinkpad_Clickpad.dsl.

**Comment by niklasarnitz** [comment]
Sorry, I forgot it.
But I'm currently not at my laptop.

I already tried that suggested by the link supplied by you.

I will check out hte SSDT-Thinkpad_Clickpad.dsl tho.
I will report back shortly.

**Comment by niklasarnitz** [comment]
Also the Trackpad doesn't show up in the system preferences.

**Comment by niklasarnitz** [comment]
[opencore-2022-03-07-105308.txt](https://github.com/acidanthera/bugtracker/files/8197087/opencore-2022-03-07-105308.txt)
And here is the log requested.

**Comment by Core-i99** [comment]
> Also the Trackpad doesn't show up in the system preferences.

Do you have working battery status?

**Comment by niklasarnitz** [comment]
No I don't

**Comment by Core-i99** [comment]
You need working battery status for the trackpad to show up in system preferences

**Comment by Sniki** [comment]
@niklasarnitz personally and a lot of other thinkpad users are using: https://github.com/VoodooSMBus/VoodooRMI instead (until a fix comes up), we have similar issues open long time ago for the same problem.
