### ISSUE TITLE
Future situation and availability of acidanthera team

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1968]
Sorry for the question, but having seen articles such as this one:

https://www.rollingstone.com/politics/politics-news/ukraine-icann-russia-internet-runet-disconnection-1314278/

And this tweet

https://mobile.twitter.com/nexta_tv/status/1500553480548892679

that suggest that they want to close all Russia from the internet starting from March 11, 2022

Since this team is too precious to be locked down by the decisions taken by somebody else (such as russian authorities) are you going to still be available to all of us in the future?

**Comment by vit9696** [comment]
Basically this is what @82ghost82 said, not what the news interpret. Domestic resources are requested to be hosted within the country for better stability and connectivity in case situations like the one with Cogent (https://www.reuters.com/technology/us-firm-cogent-cutting-internet-service-russia-2022-03-04/) continue to happen.

There are no plans to change anything acidanthera-wise at the moment, but we will obviously have to adapt if backbone providers continue to block Russia from the rest of the internet.
