### ISSUE TITLE
[Feature Request] Add OpenCore-Version information to the Config.plist file

### ISSUE THREAD

**Issue by chriswayg** [acidanthera/bugtracker#1971]
The OpenCore Config.plist file does not have any indication of which version of OpenCore it is actually compatible with. 3rd party apps like ProperTree could give a warning, if they could detect version incompatibility. For example, the Config.plist may become corrupted if an older version of ProperTree tries to apply an *OC Snapshot* to a Config.plist which it is not compatible with. See this report on Dortania for the purpose of illustrating the implications: [updated version of ProperTree is needed for a Clean Snapshot of config.plist · Issue #243 · dortania/bugtracker · GitHub](https://github.com/dortania/bugtracker/issues/243)

>A clean snapshot performed with an outdated version of ProperTree will look like everything is OK but because values are stored in an array from OC 0.7.3 onwards, the config.plist file will be faulty...

Currently when I look at an EFI there is no easy way to find out which version of OpenCore the Config.plist was created for. As a workaround I usually add a Configuration.pdf inside the EFI as a reference to the installed OpenCore version. This information is not just needed for 3rd party apps such as ProperTree, but it is also important when doing an upgrade of OpenCore on various systems. 

I would suggest to add a required `OC Version` key to the Config.plist specification (and possibly a `Build Number` key for dev versions). Maybe something like this:

```
<plist version="1.0">
    <dict>
        <key>OCVersion</key>
        <string>0.7.9</string>
        <key>ACPI</key>
        <dict>
```

**Comment by chriswayg** [comment]
@Andrey1970AppleLife - Could you please explain why you closed this without comment?

**Comment by mikebeaton** [comment]
I can think of a couple of things:
1. Version information is treated as sensitive data (see `ExposeSensitiveData` in docs)
2. It seems hard/impossible to enforce that this would actually be right.
  a. User creates XML file with correct version, but then forgets to update it as they update OC and config over time
  b. Or even say we made OC enforce this, then user with incorrect config file finds OC refuses to load it, so they just change the number, without actually fixing the config

**Comment by chriswayg** [comment]
@ mikebeaton Thanks for your insights.

> * Version information is treated as sensitive data (see `ExposeSensitiveData` in docs)

I would consider the whole Config.plist to contain sensitive data, as it has all the Mac relevant serials in the SMBIOS section. Therefore adding version information will not make the file any more sensitive.

> * It seems hard/impossible to enforce that this would actually be right.
>   a. User creates XML file with correct version, but then forgets to update it as they update OC and config over time

If the version key was available, 3rd party apps such as OCAuxilairyTools and others could automatically update it. Even with manual updates (and users forgetting to update the version), you would at least be able to see with which version the Config file was originally created with.

>   b. Or even say we made OC enforce this, then user with incorrect config file finds OC refuses to load it, so they just change the number, without actually fixing the config. 

OCvalidate could do some additional validation and maybe issue a warning. But I am not saying that OC should refuse to load a file from a different version, just that the version key should be available and at least correctly pre-set in the Sample-Config.plist.

Overall it would largely solve the issues that I brought up in my original post which are related to manual maintenance as well as 3rd party tools.

**Comment by Andrey1970AppleLife** [comment]
If it is necessary for you, You can will add the version as the comment with  #. From our side it is required nothing.
<key>#OCVersion</key>
<string>0.7.9</string>

**Comment by chriswayg** [comment]
@Andrey1970AppleLife Thanks for your reply!

> If it is necessary for you, You can will add the version as the comment with #. From our side it is required nothing.

Well sure, that's something I have started doing already and it helps with some of the issues caused by the lack of an included compatibility version number in the Config.plist file specification.

This would still make it unlikely to have it included in 3rd party apps for additional validation, as no official standard or format is being set. 

Anyways, I will just use the version number in the comments for our systems for the time being.
