### ISSUE TITLE
Keyboard and touchpad stopped working after wake from sleep on VoodooPS2 and MacOS Monterey

### ISSUE THREAD

**Issue by jayveeballesteros** [acidanthera/bugtracker#1974]
I have Synaptics i2c touchpad. Everything works on fresh boot including gestures. When I wake the system from sleep, the keyboard and trackpad will stop working. Everything is installed properly. This issue occurs from version 2.2.5 to 2.2.8. Fallback to version 2.2.4 works but no gestures, no trackpad prefs and is only working like a mouse. I have battery status working. It is Synaptics SYN052. My laptop is Panasonic CF-SZ5.

**Comment by Core-i99** [comment]
Share some logs....

**Comment by jayveeballesteros** [comment]
These are the last logs after wake from sleep.

default	11:17:32.961863+0800	kernel	[AppleUserHIDEventDriver.cpp:355][0x1000003ec] Set LED 0x2: 0 0x0
default	11:17:51.831923+0800	kernel	start simulator!
default	11:17:52.114655+0800	kernel	uld not init or attach actuator!
default	11:17:52.136233+0800	kernel	ctuator or trackpoint!
default	11:17:52.136450+0800	kernel	rackpointDevice
default	11:17:55.394244+0800	kernel	nput could not attach simulator!
default	11:17:55.398257+0800	kernel	rackpointDevice
default	11:17:55.399194+0800	kernel	Sending report with touch active 3, button 0, finger count 1
default	11:17:55.399215+0800	kernel	[0] (944, -2604) F2 St3 Maj25 Min25 Sz25 P0 ID1 A4
default	11:17:55.399286+0800	kernel	Sending report with touch active 3, button 0, finger count 1
default	11:17:55.399291+0800	kernel	[0] (597, -2604) F2 St4 Maj25 Min25 Sz25 P0 ID1 A4
default	11:17:55.399323+0800	kernel	Sending report with touch active 3, button 0, finger count 1
default	11:17:55.399327+0800	kernel	[0] (291, -2604) F2 St4 Maj25 Min25 Sz25 P0 ID1 A4
default	11:18:14.861907+0800	kernel	[IOUserUSBHostHIDDevice.cpp:504][0x100001658] Open interface: 0x100001656
default	11:18:14.864264+0800	kernel	[IOUserUSBHostHIDDevice.cpp:648][0x100001658] HID descriptor interface:0 index:0 length:79 79 79
default	11:18:14.864902+0800	kernel	[IOUserUSBHostHIDDevice.cpp:314][0x100001658] inPipe:1  inputReportSize:8 inMaxPacketSize:8 inBufferSize:8
default	11:18:14.864919+0800	kernel	[IOUserUSBHostHIDDevice.cpp:339][0x100001658] outPipe:0  outMaxPacketSize:0
default	11:18:14.865505+0800	kernel	[AppleUserUSBHostHIDDevice.cpp:126][0x100001658] Start ret: 0x0
default	11:18:14.870572+0800	kernel	[AppleUserHIDEventDriver.cpp:261][0x10000165e] Target macOS
default	11:18:14.871114+0800	kernel	[IOUserHIDEventService.cpp:161][0x10000165e] Open interface: 0x10000165d
default	11:18:14.871136+0800	kernel	[AppleUserHIDEventDriver.cpp:222][0x10000165e] parseElements: led: 0
default	11:18:14.871157+0800	kernel	[AppleUserHIDEventService.cpp:988][0x10000165e] parseElements: vendor (primary): 0 vendor (child): 0 multiaxis: 0 keyboard: 0 unicode: 0 0 biometric: 0 accel 0 gyro: 0 compass: 0 temperature: 0 orientation 0 0 sensorPropsCaps 0
default	11:18:14.871246+0800	kernel	[IOUserHIDEventDriver.cpp:934][0x10000165e] parseElements: keyboard: 0 pointer: 5 0 scroll: 1 led: 0 digitizer: 0 proximity: 0 gameController: 0
default	11:18:14.871296+0800	kernel	[AppleUserHIDEventService.cpp:247][0x10000165e] Start ret: 0x0
default	11:18:14.871345+0800	kernel	[AppleUserHIDEventDriver.cpp:326][0x10000165e] Start ret: 0x0
default	11:18:14.871366+0800	kernel	[AppleUserHIDEventDriver.cpp:116][0x10000165e] Lenovo USB Optical Mouse usagePage: 1 usage: 2 vid: 6127 pid: 24717
default	11:18:18.590729+0800	kernel	[IOUserUSBHostHIDDevice.cpp:504][0x100001676] Open interface: 0x100001672
default	11:18:18.592370+0800	kernel	[IOUserUSBHostHIDDevice.cpp:648][0x100001676] HID descriptor interface:0 index:0 length:57 57 57
default	11:18:18.593379+0800	kernel	[IOUserUSBHostHIDDevice.cpp:314][0x100001676] inPipe:1  inputReportSize:8 inMaxPacketSize:8 inBufferSize:8
default	11:18:18.593394+0800	kernel	[IOUserUSBHostHIDDevice.cpp:339][0x100001676] outPipe:0  outMaxPacketSize:0
default	11:18:18.593400+0800	kernel	[IOUserUSBHostHIDDevice.cpp:988][0x100001676] SetIdle:24ms
default	11:18:18.594094+0800	kernel	[AppleUserUSBHostHIDDevice.cpp:126][0x100001676] Start ret: 0x0
default	11:18:18.594752+0800	kernel	[IOUserUSBHostHIDDevice.cpp:504][0x10000167a] Open interface: 0x100001673
default	11:18:18.597794+0800	kernel	[IOUserUSBHostHIDDevice.cpp:648][0x10000167a] HID descriptor interface:1 index:0 length:215 215 215
default	11:18:18.599747+0800	kernel	[IOUserUSBHostHIDDevice.cpp:314][0x10000167a] inPipe:1  inputReportSize:8 inMaxPacketSize:8 inBufferSize:8
default	11:18:18.599756+0800	kernel	[IOUserUSBHostHIDDevice.cpp:339][0x10000167a] outPipe:0  outMaxPacketSize:0
default	11:18:18.600496+0800	kernel	[AppleUserUSBHostHIDDevice.cpp:126][0x10000167a] Start ret: 0x0
default	11:18:18.601160+0800	kernel	[AppleUserHIDEventDriver.cpp:261][0x100001680] Target macOS
default	11:18:18.602128+0800	kernel	[IOUserHIDEventService.cpp:161][0x100001680] Open interface: 0x10000167f
default	11:18:18.602607+0800	kernel	[IOUserUSBHostHIDDevice.cpp:1125][0x100001676] Add element to action array: 1
default	11:18:18.602879+0800	kernel	[AppleUserHIDEventDriver.cpp:215][0x100001680] Set LED 0x1: 0 0x0
default	11:18:18.603259+0800	kernel	[AppleUserHIDEventDriver.cpp:215][0x100001680] Set LED 0x2: 0 0x0
default	11:18:18.603612+0800	kernel	[AppleUserHIDEventDriver.cpp:215][0x100001680] Set LED 0x3: 0 0x0
default	11:18:18.603632+0800	kernel	[AppleUserHIDEventDriver.cpp:222][0x100001680] parseElements: led: 3
default	11:18:18.603667+0800	kernel	[AppleUserHIDEventService.cpp:988][0x100001680] parseElements: vendor (primary): 0 vendor (child): 0 multiaxis: 0 keyboard: 0 unicode: 0 0 biometric: 0 accel 0 gyro: 0 compass: 0 temperature: 0 orientation 0 0 sensorPropsCaps 0
default	11:18:18.604027+0800	kernel	[IOUserHIDEventDriver.cpp:934][0x100001680] parseElements: keyboard: 236 pointer: 0 0 scroll: 0 led: 0 digitizer: 0 proximity: 0 gameController: 3
default	11:18:18.604156+0800	kernel	[AppleUserHIDEventService.cpp:247][0x100001680] Start ret: 0x0
default	11:18:18.604208+0800	kernel	[AppleUserHIDEventDriver.cpp:326][0x100001680] Start ret: 0x0
default	11:18:18.604226+0800	kernel	[AppleUserHIDEventDriver.cpp:116][0x100001680] 2.4G Receiver usagePage: 1 usage: 6 vid: 9639 pid: 64097
default	11:18:18.607491+0800	kernel	[AppleUserHIDEventDriver.cpp:261][0x100001689] Target macOS
default	11:18:18.609555+0800	kernel	[IOUserHIDEventService.cpp:161][0x100001689] Open interface: 0x100001685
default	11:18:18.610290+0800	kernel	[AppleUserHIDEventDriver.cpp:222][0x100001689] parseElements: led: 0
default	11:18:18.610323+0800	kernel	[AppleUserHIDEventService.cpp:988][0x100001689] parseElements: vendor (primary): 0 vendor (child): 0 multiaxis: 0 keyboard: 0 unicode: 0 0 biometric: 0 accel 0 gyro: 0 compass: 0 temperature: 0 orientation 0 0 sensorPropsCaps 0
default	11:18:18.610985+0800	kernel	[IOUserHIDEventDriver.cpp:934][0x100001689] parseElements: keyboard: 573 pointer: 7 0 scroll: 3 led: 0 digitizer: 0 proximity: 1 gameController: 0
default	11:18:18.611242+0800	kernel	[AppleUserHIDEventService.cpp:247][0x100001689] Start ret: 0x0
default	11:18:18.611299+0800	kernel	[AppleUserHIDEventDriver.cpp:326][0x100001689] Start ret: 0x0
default	11:18:18.611316+0800	kernel	[AppleUserHIDEventDriver.cpp:116][0x100001689] 2.4G Receiver usagePage: 1 usage: 2 vid: 9639 pid: 64097

**Comment by usr-sse2** [comment]
Does the touchpad work after wake until first keypress?
Does the keyboard work after wake until first touch on the touchpad?
