### ISSUE TITLE
Weird popping noise and static noise with AppleALC 1.7.0

### ISSUE THREAD

**Issue by tarutaru9250** [acidanthera/bugtracker#1976]
Hi, currently I'm using OC 0.7.9 and latest kexts. But I have just realized that with AppleALC 1.7.0, if I play any videos on Youtube with Chrome, there is a big static noise. On Safari it is popping noise, big also. I have to mute the sound for a while then enable it again.
Spotify or any music players are fine.
I tried to downgrade to old AppleALC versions, it's totally fine, no issue. Now I'm staying at 1.6.9.
My spec: Dell G7 7588, ALC256, current layout-id is 14.
It doesn't happen before, this is the first time.

**Comment by mikebeaton** [comment]
Nothing fundamental has changed in AppleALC between 1.6.9 and 1.7.0, only patches for various sound cards, none of which are yours.

Are you definitely only changing AppleALC when you change between versions?

If so, please can you provide AppleALC and Lilu debug logs (https://github.com/acidanthera/AppleALC/wiki/Installation-and-usage) for AppleALC 1.6.9 and for 1.7.0 (can you update to latest versions of everything - including OC + Lilu - except AppleALC; only AppleALC and Lilu need to be debug versions to get those logs).

**Comment by tarutaru9250** [comment]
@mikebeaton Sorry if I disturb you. I tried to find where it comes from in hours and now I found it. The reason is because of SoundSource app.
Thank you for replying. I will close this issue.
