### ISSUE TITLE
FeatureUnlock 1.0.7: will not unlock AirPlay receiver on Macmini8,1 SMBIOS with macOS 12.3

### ISSUE THREAD

**Issue by i0ntempest** [acidanthera/bugtracker#1977]
AirPlay receiver was previously supported natively on Mac mini 2018 in macOS 12.2.1 and older. No idea why Apple decided to remove it now. But when I try to use FeatureUnlock kext to patch it, it will not work. The kext is loaded but AirPlay receiver will not show up.
 EFI folder attached, debug logs will be added if needed.
[EFI_mini.zip](https://github.com/acidanthera/bugtracker/files/8257284/EFI_mini.zip)

**Comment by khronokernel** [comment]
Please verify the below builds resolves this:

* [FeatureUnlock-1.0.8-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/8264862/FeatureUnlock-1.0.8-DEBUG.zip)

**Comment by i0ntempest** [comment]
Yes, AirPlay receiver is visible in Sharing preference again and usable. Thanks.

**Comment by sluxtor** [comment]
Thank you for providing this feature unlock! I am not familiar with kext files, how do I go about installing/applying this?

**Comment by i0ntempest** [comment]
> Thank you for providing this feature unlock! I am not familiar with kext files, how do I go about installing/applying this?

You need to use OpenCore to inject this kext and its dependency Lilu.kext. On older systems you were able to install kexts without using a bootloader but that no longer works.

**Comment by sluxtor** [comment]
I appreciate your quick reply - so I need to go about understanding OpenCore and getting that installed before installing this. 

I don't want to rush into anything since it looks to be rather in depth, is there a more simple method I might be missing?

**Comment by i0ntempest** [comment]
> I don't want to rush into anything since it looks to be rather in depth, is there a more simple method I might be missing?

Not that I know of. As I said there used to be a easier way before macOS 11 overhauled the kernel extension loading process.
I’m guessing you’re on a real Mac and completely new to this. In that case research OpenCore legacy patcher, and backup everything if you do decide to go down this hole.

**Comment by i0ntempest** [comment]
For only this one feature, yes that would be too much work imo. But once you install OpenCore you open up a whole new dimension of tinkering on your Mac, including installing unsupported macOS when the time comes (which is the main purpose of OC legacy patcher). Besides that if in the future more features are added to only newer Macs, FeatureUnlock can probably bring it to you.
