### ISSUE TITLE
my desktop got a panic when I use a cable to connect ethernet with my chip I225-V on macOS 12.3 RELEASE

### ISSUE THREAD

**Issue by HeartAndSoul001** [acidanthera/bugtracker#1978]
Hello, any body can give me some advice? My desktop got a panic when I use a cable to connect ethernet with my chip I225-V on macOS 12.3 RELEASE, and then reboot automatically. Here is the report:
-------------------------------------------------------------------------------------------------------------------------
panic(cpu 2 caller 0xffffff801231e575): label backref mismatch: labelp:0xffffff951d9e4ee8 label:0xffffff85186df080 l_owner:0x5f0563614d69849a @mac_label.c:158
Panicked task 0xffffff8b7e782a20: 23 threads: pid 100: mds
Backtrace (CPU 2), panicked thread: 0xffffff951f0f7aa8, Frame : Return Address
0xffffffd065613430 : 0xffffff8011a83e1d mach_kernel : _handle_debugger_trap + 0x41d
0xffffffd065613480 : 0xffffff8011be3ca6 mach_kernel : _kdp_i386_trap + 0x116
0xffffffd0656134c0 : 0xffffff8011bd34fd mach_kernel : _kernel_trap + 0x51d
0xffffffd065613510 : 0xffffff8011a23a60 mach_kernel : _return_from_trap + 0xe0
0xffffffd065613530 : 0xffffff8011a841ed mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffd065613650 : 0xffffff8011a839a6 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xffffffd0656136b0 : 0xffffff80123164af mach_kernel : _panic + 0x84
0xffffffd0656137a0 : 0xffffff801231e575 mach_kernel : __ZN14IOPMrootDomain20panicWithShutdownLogEj + 0x1a5
0xffffffd0656137b0 : 0xffffff80122e099e mach_kernel : _mac_label_verify + 0x5e
0xffffffd0656137c0 : 0xffffff8011d25617 mach_kernel : _vfs_init_io_attributes + 0xbd7
0xffffffd065613840 : 0xffffff8014d17d75 com.apple.filesystems.apfs : _apfs_load_inode_internal + 0x912
0xffffffd065613a20 : 0xffffff8014d6060e com.apple.filesystems.apfs : _apfs_vfsop_vget_internal + 0x1a5
0xffffffd065613aa0 : 0xffffff8011d0bb7f mach_kernel : _build_path_with_parent + 0x8af
0xffffffd065613d10 : 0xffffff8011d39bc1 mach_kernel : _fsgetpath_internal + 0x2d1
0xffffffd065613ec0 : 0xffffff8011d4abae mach_kernel : _fsgetpath + 0x11e
0xffffffd065613f40 : 0xffffff801218ad1b mach_kernel : _unix_syscall64 + 0x1fb
0xffffffd065613fa0 : 0xffffff8011a24226 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.filesystems.apfs(1934.101.3)[F632D338-810A-30EB-8C6E-54939BCAEE8C]@0xffffff8014cd3000->0xffffff8014e51fff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[4B5FE248-78C8-3030-81FB-53CC4040F619]@0xffffff8012f92000->0xffffff8012f9bfff
            dependency: com.apple.driver.AppleEffaceableStorage(1.0)[4ED769C2-F7DD-325A-9ABD-8C153AD64D08]@0xffffff8012fa8000->0xffffff8012fadfff
            dependency: com.apple.iokit.CoreAnalyticsFamily(1)[0F3BD94F-E03A-3FB6-9EFF-154227A6DCC0]@0xffffff80134aa000->0xffffff80134b1fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[77153709-FFFE-3023-BDAF-2BC5E91F4A62]@0xffffff8014745000->0xffffff801475bfff
            dependency: com.apple.kec.corecrypto(12.0)[FEE26327-9979-30B0-ABEC-614507B4FEA8]@0xffffff8014e8b000->0xffffff8014f0afff
            dependency: com.apple.security.AppleImage4(4.2.0)[56B6F776-B5F9-36F6-805D-2CA7A1A56C11]@0xffffff801302f000->0xffffff8013047fff

Process name corresponding to current thread (0xffffff951f0f7aa8): mds
Boot args: -v keepsyms=1 agdpmod=pikera dk.e1000=0 gfxrst=1 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
21E230

Kernel version:
Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64
Kernel UUID: 9619904E-EA6D-3D08-89C4-B1C0451D39B8
KernelCache slide: 0x0000000011800000
KernelCache base:  0xffffff8011a00000
Kernel slide:      0x0000000011810000
Kernel text base:  0xffffff8011a10000
__HIB  text base: 0xffffff8011900000
System model name: iMac20,1 (Mac-CFF7D910A743CAAF)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 742043832257
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000acc542578a
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000014e76902d0 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Foreign : 0xffffff8019dcf000 - 0xffffff8019ddd000
  Native  : 0xffffff804b32e000 - 0xffffffa04b32e000
  Readonly: 0xffffff8517ffa000 - 0xffffff86b1993000
  Metadata: 0xfffffffe061c0000 - 0xfffffffe264d6000
  Bitmaps : 0xfffffffe264d6000 - 0xfffffffe324d6000
-------------------------------------------------------------------------------------------------------------------------
I225-V Ethernet chip can be saved with parameter "dk.e1000=0" on Monterey(<12.3). But it didn't work on Monterey 12.3 any more. I wonder if there is some posibility that this can be fixed with some parameters via Lilu or Opencore boot loader ? Or, kext IntelMausi.kext can fix it. I would appreciate if some one can answer me. @_@

**Comment by Core-i99** [comment]
I didn't test it but here's a different patch.
https://www.facebook.com/groups/hackintosch/permalink/10160230977532446/

**Comment by HeartAndSoul001** [comment]
> I didn't test it but here's a different patch.
> https://www.facebook.com/groups/hackintosch/permalink/10160230977532446/

Ok, I will check it. thanks a lot for share

**Comment by HeartAndSoul001** [comment]
@Core-i99 hello, can you patch some information from url "https://www.facebook.com/groups/hackintosch/permalink/10160230977532446/", I am not the member of this group and can not get some information

**Comment by 1alessandro1** [comment]
@HeartAndSoul001 replace from your boot-args 

```
dk.e1000=0
```

with

```
e1000=0 
```

source:

https://www.reddit.com/r/hackintosh/comments/tf4hpy/psa_monterey_123_and_i225v_panics_use_bootarg/

**Comment by HeartAndSoul001** [comment]
@Core-i99 it is so kind of you👍🏻

**Comment by HeartAndSoul001** [comment]
@1alessandro1 thank you very much, the other way has fixed it. Keep dk.e1000=0, and replace the device-id in DeviceProperties of config.plist with Data "F3158680",  problem gone. I don't know whether the new release macOS has did something in driver which caused this problem.

**Comment by 1alessandro1** [comment]
@HeartAndSoul001 ok, so you used `F3158680` (8086:15F3 hex swapped) instead of the one who Abderahmane Bouhaddad `F2158680`?

Just curious to know if you noticed any difference in your tests between 15F3 or 15F2 or if it's the same with both

**Comment by Andrey1970AppleLife** [comment]
Here not forum support. Write to dortania.
