### ISSUE TITLE
Ice Lake notebook (Dell XPS 13 9300) - Crash after upgrading to macOS 12.3

### ISSUE THREAD

**Issue by najeebanwer** [acidanthera/bugtracker#1979]
I have macOS installed on a Dell XPS 13 9300 notebook. The specs are:
Processor: Intel Core i7-1065G7 (Ice Lake)
Memory: 32GB
Disk: Samsung SSD 970 EVO Plus 2TB (NVMe)
Dell BIOS 1.10.0 (2/10/2022)

Everything was working well with macOS 12.2.1 but after upgrading to macOS 12.3, the system boots, shows a blank screen on both the internal display and the external (USB-C connected) monitor and then, after a few seconds, reboots and boots directly into macOS Recovery (no BootPicker shown).

I am using the DEBUG version of OpenCore 0.7.9, and the latest RELEASE version of all the kexts.
I have attached the opencore bootlog and my config.plist.

[opencore-2022-03-18-030741.txt](https://github.com/acidanthera/bugtracker/files/8301389/opencore-2022-03-18-030741.txt)
[config.zip](https://github.com/acidanthera/bugtracker/files/8301392/config.zip)

Please let me know what additional information I can provide to help resolve this issue. I can access the EFI folder using Windows and I can also boot macOS Recovery to get the information needed.

Thanks for any help you can provide.

**Comment by Andrey1970AppleLife** [comment]
Use SetApfsTrimTimeout = 0 for Samsung NVMe.

**Comment by najeebanwer** [comment]
@Andrey1970AppleLife, Thank you. That worked.
