### ISSUE TITLE
OpenCore Building on macOS 12.3 with Xcode

### ISSUE THREAD

**Issue by chris1111** [acidanthera/bugtracker#1980]
No Issue for Update latest commit on my OpenCore Git 
![Screen Shot 2022-03-19 at 6 38 06 AM](https://user-images.githubusercontent.com/6248794/159118461-730da8c3-7658-49f6-9e61-9ca9d427d529.png)
But at the end  **CheckSchema.py** can't be open  
The new path is /usr/local/bin/python3  on macOS 12.3

![Screen Shot 2022-03-19 at 6 43 43 AM](https://user-images.githubusercontent.com/6248794/159118790-4d1cff30-9508-4dbd-8f5c-568ff22a7f95.png)

Binaries is create succesfully, its not a problem

![Screen Shot 2022-03-19 at 6 44 28 AM](https://user-images.githubusercontent.com/6248794/159118847-20d0306a-6ce1-40e6-9663-4ab9c7b1a080.png)

Thanks anyway !

**Comment by PMheart** [comment]
> Python
> Deprecations
> Python 2.7 was removed from macOS in this update. Developers should use Python 3 or an alternative language instead. (39795874)

Quote from [macOS 12.3 Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). Thus, it has nothing to do with us. Closing.

**Comment by chris1111** [comment]
Got it I had to modify the build_oc.tool script to make it work correctly

![Screen Shot 2022-03-19 at 2 40 34 PM](https://user-images.githubusercontent.com/6248794/159134439-30706474-0723-49c5-aa44-b4bfbdeff975.png)


![Screen Shot 2022-03-19 at 2 40 43 PM](https://user-images.githubusercontent.com/6248794/159134361-086e292e-492f-48be-a746-e3ddf89c9d7c.png)

**Comment by PMheart** [comment]
Your python3 seems to be installed from other sources, e.g. from Homebrew. In CheckSchema.py we have the shebang `#!/usr/bin/env python` which should not be a problem if $PATH is configured correctly.

**Comment by chris1111** [comment]
My Python is install from Python source [Release](https://www.python.org/downloads/macos/) 
And is update

**Comment by PMheart** [comment]
Alright. That's it. Please appropriately set your $PATH then. And afterwards it will work.

**Comment by chris1111** [comment]
/usr/bin/env python not exist anymore in macOS 12.3 because apple remove Python
Python is now installed in /usr/local/bin/python3

![Screen Shot 2022-03-19 at 3 07 24 PM](https://user-images.githubusercontent.com/6248794/159135098-1b3a60bb-6fb9-4c73-bd16-a9cf74e43809.png)

**Comment by PMheart** [comment]
Still, this is your own problem, though Apple has warned the removal of python 2.7 some long while ago. Pinged you on InsanelyMac.

**Comment by chris1111** [comment]
Thanks very much that work, the checking Shema  is done.
Last small thing is Failled to find OpenDuetPkg
![159118790-4d1cff30-9508-4dbd-8f5c-568ff22a7f95](https://user-images.githubusercontent.com/6248794/159160678-4371120c-7352-4f5f-9d70-3bac41f50a68.png)

 is there any particular trick to build Duet ? Maybe is differant issue and out off topic here

**Comment by vit9696** [comment]
Hmm, you should build Duet before OpenCore.

**Comment by chris1111** [comment]
> Hmm, you should build Duet before OpenCore.


is there any particular command? I see the dock but is relate to the Old Build tool I think `macbuild.tool`.

**Comment by PMheart** [comment]
Run build_oc.tool first, then build_duet.tool. It should work this way.

**Comment by vit9696** [comment]
This is wrong. One should run build_duet.tool first, then build_oc.tool.

**Comment by PMheart** [comment]
Sorry for me severe typo! Fixed :(

**Comment by chris1111** [comment]
Thanks very much you both everything is back to normal
