### ISSUE TITLE
Kext-Block-Strategy

### ISSUE THREAD

**Issue by kokowski** [acidanthera/bugtracker#1981]
Hello,

i'm trying to block the IOPCIFamily.kext of Monterey 12.3 and load the IOPCIFamily.kext of the MOnterey beta 8 instead, but that doesn't work for me. I've found out, that the problems that occur with some network adapters are not due to the network drivers but to the IOPCIFAmily.kext. I think there's just a patch needed for this problem, but unfortunately my skills are not sufficient for this. In my case, it is specifically about the I225-V (revision 2) of the Z490 platform, which only works with the just mentioned version of the IOPCI driver. VTD is active on my system and the kernel quirk DisableIOMapper is disabled, but that doesn't help. 

[IOPCIFamily.kextBeta8.zip](https://github.com/acidanthera/bugtracker/files/8378779/IOPCIFamily.kextBeta8.zip)

I've attached the Beta 8 kext and i hope, that maybe you can help, because there are very many users with this problem.

**Comment by PMheart** [comment]
Hi! Have you tried Strategy = `Exclude`? Did this work for you?

**Comment by PMheart** [comment]
As far as I know not all kexts can be blocked/excluded this way. Unfortunately IOPCIFamily can be the case. Closing as wontfix. Sorry!

**Comment by PMheart** [comment]
I can, however, try comparing the binaries. In case of any discoveries, I could post them on InsanelyMac, instead of here.

**Comment by kokowski** [comment]
This would be really nice, because I am pretty sure that this is the cause of the problem with some network adapters, especially the i225-v

**Comment by PMheart** [comment]
I had a quick discussion with @vit9696, and it turned out that there are race conditions instead of code changes between b8 and 12.3. Thus, I am afraid that it cannot be easily fixed/patched. Do not buy Gigabyte!

**Comment by kokowski** [comment]
There's the same problem with ASUS boards and the i225-v is working with the beta 8 of IOPCIFamily.

**Comment by kokowski** [comment]
@PMheart  Would you maybe still take a look at the current IOPCIFamily.kext and the one from Beta 8. Maybe you will discover something that others overlook. I would be very happy about it and would be very grateful to you.

**Comment by PMheart** [comment]
Sorry for the late response.

I had a discussion with @vit9696 some days ago, and he said that there are no significant changes between 12.0 b8 and 12.3. Instead, replacing the kexts just somehow increases the possibility to win the race condition. If this is the case, then I don’t think I can help with anything.

Sorry!

**Comment by Nanthinif20** [comment]
hi, frinds any one share the iopcifamyl.kext download link pleas.
