### ISSUE TITLE
Problem changing CPU name in AMD build

### ISSUE THREAD

**Issue by batero2000** [acidanthera/bugtracker#1983]
Hi, so I'm having issues changing the CPU name of my Ryzentosh system, I've installed RestrictEvents and changed the config with CPU-Name, I don't know what else to do.

![image](https://user-images.githubusercontent.com/14956589/161393513-62627909-214c-4d6e-a01c-1bbdaaf8550c.png)

**Comment by vit9696** [comment]
No support for AMD, sorry.
