### ISSUE TITLE
OpenCore doesn't show macOS partition after enabled FileVault 2

### ISSUE THREAD

**Issue by tarutaru9250** [acidanthera/bugtracker#1984]
Hello, currently I have a small problem. After enabled FileVault, I restart my laptop and at the picker screen, my macOS partition doesn't show up. I check the ScanPolicy but it's already 0. Also I tried to make a recovery usb stick. In Disk Ultility, macOS partition is still there, but the Macintosh HD - Data is unmounted. I tried to mount it then restart but not work.
I have enabled FileVault before and everything is fine. This is the first time I got this issue. I'm not sure if it's because of OC or OS system.
I'm using OC latest 0.7.9 and macOS Monterey 12.3.1.
Edit: Picker even doesn't show the internal Recovery, I have to make external Recovery.

Here is my config:
[config.plist.docx](https://github.com/acidanthera/bugtracker/files/8424565/config.plist.docx)

**Comment by tarutaru9250** [comment]
Update: I have just traced back my brain and disable UEFI Secure Boot (I enabled it at the first restart after enabled FileVault)... and OC shows macOS boot entry at the picker screen...
Just curious why OC doesn't show macOS boot entry if UEFI Secure Boot is enabled. All my OC binaries are already signed with custom keys.

**Comment by mikebeaton** [comment]
Please provide two debug logs, one with and one without secure boot.

**Comment by tarutaru9250** [comment]
> Please provide two debug logs, one with and one without secure boot.

Here they are. Thank you for waiting.
[secureboot-off.txt](https://github.com/acidanthera/bugtracker/files/8437623/secureboot-off.txt)
[secureboot-enabled.txt](https://github.com/acidanthera/bugtracker/files/8437624/secureboot-enabled.txt)

**Comment by mikebeaton** [comment]
Read the [documentation](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) about how to set up UEFI Secure Boot, in particular you do not have `SecureBootModel` set.

**Comment by tarutaru9250** [comment]
> Read the [documentation](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) about how to set up UEFI Secure Boot, in particular you do not have `SecureBootModel` set.

lol my fault, I forgot enabling it. Intel wireless is still available so I thought it's already enabled.
macOS entry is available now. Thank you very much!
