### ISSUE TITLE
VoodooPS2 ALPS Kernel Panic 

### ISSUE THREAD

**Issue by Hussain-P99** [acidanthera/bugtracker#1986]
Hii I am been facing kernel panic while using the voodoops2 kext, i also tried the SkyrilHD's kext but facing the same issue.

panic(cpu 0 caller 0xffffff8016dd78d3): Kernel trap at 0xffffff801acaba0e, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000105d08038, CR3: 0x000000002d432000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0x00000000ffffffff, RCX: 0x0000000000000046, RDX: 0x0000000000000708
RSP: 0xffffffd04921bda0, RBP: 0xffffffd04921bda0, RSI: 0x0000000000000708, RDI: 0xffffff9506423800
R8:  0x0000000000000000, R9:  0xffffff95064237b8, R10: 0x0000000000000046, R11: 0xfffffffffffffff7
R12: 0x0000000000000000, R13: 0xffffff9506423800, R14: 0xffffff9506423990, R15: 0x0000000000000000
RFL: 0x0000000000010202, RIP: 0xffffff801acaba0e, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0xffffff950642585c, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 10

Panicked task 0xffffff9039efa670: 151 threads: pid 0: kernel_task
Backtrace (CPU 0), panicked thread: 0xffffff8b6d336540, Frame : Return Address
0xffffffd04921b7d0 : 0xffffff8016c87ddd mach_kernel : _handle_debugger_trap + 0x41d
0xffffffd04921b820 : 0xffffff8016de7d15 mach_kernel : _kdp_i386_trap + 0x145
0xffffffd04921b860 : 0xffffff8016dd74e3 mach_kernel : _kernel_trap + 0x533
0xffffffd04921b8b0 : 0xffffff8016c27a60 mach_kernel : _return_from_trap + 0xe0
0xffffffd04921b8d0 : 0xffffff8016c881ad mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffd04921b9f0 : 0xffffff8016c87966 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xffffffd04921ba50 : 0xffffff80175160b9 mach_kernel : _panic + 0x54
0xffffffd04921bac0 : 0xffffff8016dd78d3 mach_kernel : _sync_iss_to_iks + 0x2c3
0xffffffd04921bc40 : 0xffffff8016dd75b8 mach_kernel : _kernel_trap + 0x608
0xffffffd04921bc90 : 0xffffff8016c27a60 mach_kernel : _return_from_trap + 0xe0
0xffffffd04921bcb0 : 0xffffff801acaba0e as.acidanthera.voodoo.driver.PS2Trackpad : __ZN22ApplePS2ALPSGlidePoint4distEii + 0x44
0xffffffd04921bda0 : 0xffffff801acaa87e as.acidanthera.voodoo.driver.PS2Trackpad : __ZN22ApplePS2ALPSGlidePoint15renumberFingersEv + 0x162
0xffffffd04921be20 : 0xffffff801aca95a2 as.acidanthera.voodoo.driver.PS2Trackpad : __ZN22ApplePS2ALPSGlidePoint26alps_process_packet_ss4_v2EPh + 0x31c
0xffffffd04921bea0 : 0xffffff801acad54c as.acidanthera.voodoo.driver.PS2Trackpad : __ZN22ApplePS2ALPSGlidePoint11packetReadyEv + 0x8a
0xffffffd04921bed0 : 0xffffff8017458d13 mach_kernel : __ZN22IOInterruptEventSource12checkForWorkEv + 0x163
0xffffffd04921bf20 : 0xffffff801745756e mach_kernel : __ZN10IOWorkLoop15runEventSourcesEv + 0x13e
0xffffffd04921bf60 : 0xffffff8017456b97 mach_kernel : __ZN10IOWorkLoop10threadMainEv + 0x37
0xffffffd04921bfa0 : 0xffffff8016c2718e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         as.acidanthera.voodoo.driver.PS2Trackpad(2.2.8)[A54250A9-E83D-3B7A-BFF5-96FF47975BD0]@0xffffff801aca5000->0xffffff801acc7fff
            dependency: as.acidanthera.voodoo.driver.PS2Controller(2.2.8)[E72A38F2-CDC4-3E4F-85BE-C94041B39DCC]@0xffffff801ac8c000->0xffffff801aca3fff
            dependency: com.apple.iokit.IOHIDFamily(2.0.0)[4773BB64-73AE-3283-8DE4-D10459C90231]@0xffffff801947d000->0xffffff80194dafff

Process name corresponding to current thread (0xffffff8b6d336540): kernel_task
Boot args: kext-dev-mode=1 dart=0 nv_disable=1 -cdfon -igfxnohdmi alcid=3 keepsyms=1 -v 

Mac OS version:
21C52

Kernel version:
Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
Kernel UUID: E32C293C-7D8B-327C-A335-6AAD250A4881
KernelCache slide: 0x0000000016a00000
KernelCache base:  0xffffff8016c00000
Kernel slide:      0x0000000016a10000
Kernel text base:  0xffffff8016c10000
__HIB  text base: 0xffffff8016b00000
System model name: MacBookPro12,1 (Mac-E43C1C25D4880AD6)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 229019087371
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000355299f87b
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000f23dd4d28 0x0000000000000000
Zone info:
Foreign   : 0xffffff802d84b000 - 0xffffff802d858000
Native    : 0xffffff8039d88000 - 0xffffffa039d88000
Readonly  : 0xffffff8506a54000 - 0xffffff86a03e8000
Metadata  : 0xffffffdc2a3bb000 - 0xffffffdc4a481000
Bitmaps   : 0xffffffdc4a481000 - 0xffffffdc4d481000

**Comment by usr-sse2** [comment]
cc @SkyrilHD

**Comment by SkyrilHD** [comment]
I also had this problem on my E7250 with a V7 touchpad, however it is very difficult to reproduce, so I have not further diagnosed it. The kernel panic happens here:

https://github.com/acidanthera/VoodooPS2/blob/b541fe37a5832880efaaa1398938cfa572feced8/VoodooPS2Trackpad/VoodooPS2ALPSGlidePoint.cpp#L3400

I don't know exactly what could be the reason for the kernel panic. However, I'm trying to fix it by avoiding SimpleAverage. I've been using a WIP fix for months and haven't encountered any kernel panics yet. So there is progress, but the V7 touchpad is incredibly annoying and tends to skip a few packets, resulting in unsmooth gestures, which is why I haven't made a pull request yet.

Since @Hussain-P99 uses a V8 touchpad, he might try the WIP fix. V8 touchpads do not need virtual fingers, as they can report up to 4 fingers via packets. (But do we need a virtual finger if we want 5 fingers?) Which could be more beneficial than it currently is.

Feedback from V8 users would be great (should be stable, but does it work without skipping packets?). V7 users have to wait a bit longer until I fix the issues properly.

Link to the WIP kext:
https://github.com/SkyrilHD/VoodooPS2/actions/runs/2376256992

**Comment by SkyrilHD** [comment]
New update:

The fix now applies to all touchpads that support VoodooInput: https://github.com/SkyrilHD/VoodooPS2/actions/runs/2385031854

If there are no issues, I think I can make a pull request. Feedback about finger tracking and gestures are welcome.

**Comment by Hussain-P99** [comment]
@SkyrilHD Thank you so much for help, i will test it out on my system to check if the issue still occurs.

**Comment by Hussain-P99** [comment]
Hi @SkyrilHD i have tested it on my setup and i'm no longer facing the issue, thanks again for help. we can close this issue now.
