### ISSUE TITLE
can't compile Lilu

### ISSUE THREAD

**Issue by btwise** [acidanthera/bugtracker#1987]
After my system is reinstalled, Lilu cannot be compiled correctly, other extension kexts can be compiled normally, the MACOS version is 12.3.1, and the xcode version is 13.3

![image](https://user-images.githubusercontent.com/38809560/162657476-507dbe84-329d-4f2e-ada5-1ec3116b5b92.png)

![image](https://user-images.githubusercontent.com/38809560/162657625-4ebf3afa-f241-46b2-82b9-fcf654f3c317.png)

**Comment by PMheart** [comment]
Hello! Thanks for your report. Fixed in master.

**Comment by vit9696** [comment]
Previous change borked the code. Please make sure you use https://github.com/acidanthera/Lilu/commit/11758ccbe7ccfc932d7b3e0a1683798a7f20627b or newer.
