### ISSUE TITLE
open core macOS usb installer not show 

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#1990]
Mac OS usb installer not show usb Mac OS installer 

oc : 0.8.0
ScanPolicy 0 

but not show
![Screen Shot 2022-04-13 at 19 52 46](https://user-images.githubusercontent.com/35195176/163214815-2964e779-fc84-4c9a-b423-5294cbf24aec.png)

config:
[config.plist](https://github.com/acidanthera/bugtracker/files/8482654/config.plist.zip)

**Comment by PMheart** [comment]
Hello! Please post on forums for support instead.

Closing.
