### ISSUE TITLE
Windows booted with OpenCore, the modification of BIOS boot items in Windows does not take effect, you must boot through Windows Boot Manager to modify the BIOS boot items, can this be changed?

### ISSUE THREAD

**Issue by w19996** [acidanthera/bugtracker#1993]
This feels very inconvenient for dual systems

**Comment by PMheart** [comment]
Hello! Thanks for filing this issue.

I had a quick discussion with @vit9696, and would like to highlight some points:

- OpenCore should always be the default boot entry, thus Windows Boot Manager is not supposed to be used at all
- When using OpenCore, the boot order is always BIOS -> OC -> Guest OS
- It is not possible for multiple bootloaders to co-exist

In light of these, I am closing this issue as it will not be implemented.
