### ISSUE TITLE
Whatevergreen + SSDT-PNLF

### ISSUE THREAD

**Issue by dmitrymst** [acidanthera/bugtracker#1994]
Good day. Try to explain my specific bug with my laptop display.
I have an old Sandy Bridge Samsung NP530U3B laptop. By default my display in mac os have an issue with brightness, its very dark or some layer of fog like. So in old versions of mac os like El Capitan I used IntelBacklight.kext and to resolve this issue I have to change property in  IntelBacklight.kext/Info.plist. The property named PCHLInit. By default value of PCHLInit is -1. If I change it to 0 my display works normal. But in new mac os versions brightness control don't work anymore with IntelBacklight.kext. So my question is there any methods to realize this property PCHLInit in Whatevergreen.kext or maybe in SSDT-PNLF?

**Comment by dmitrymst** [comment]
Found interesting thing. Mac os don’t recognise my laptop lcd panel as 24bit color depth. I edited my vbios and found that if i change color  depth to 18bit then even in bios picture is very dark like in mac os. Then return to 24bit and in bios picture is normal, but in mac os is dark.

**Comment by dmitrymst** [comment]
I’m used OC. But it’s just bug with my laptop. My laptop lvds panel is 24 bit color depth, but mac os recognised it like 18 bit, that’s the main issue

**Comment by jivesh-threja** [comment]
I own a Samsung series 5 laptop and want to change PCHLInit to 0 in Open Core. Any solutions found ?
