### ISSUE TITLE
I can't find Fan addr for my laptop

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#1995]
My Laptop is hp-DA1023nia and I search in DSDT doesn't find RPM in ERAM 

OperationRegion (ERAM, EmbeddedControl, Zero, 0xFF)
            Field (ERAM, ByteAcc, Lock, Preserve)
            {
                Offset (0x5F), 
                ERBD,   8, 
                SMPR,   8, 
                Offset (0x62)
            }

I TEST
0xC2= RPM SHOW and only change 1 
0xC4= RPM SHOW BUT NEVER CHNGE (ALWAYS SHOW 8977rpm)
0xB2= WORK AND CHANGE BUT I THINK THIS temperature becuse min 45 and max 75

**Comment by Edwardwich** [comment]
- `ec-device` = `generic`
- `fan-count` = `1`
- `fan0-addr` = `0xB2`
- `fan0-size` = `2`
- `fan0-div` = `11`
- `fan0-mul` = `F0`
- `fan0-big` = `2` 
I test this but MAX RPM less than 1000

**Comment by Edwardwich** [comment]
![Screen Shot 2022-04-20 at 22 45 31](https://user-images.githubusercontent.com/35195176/164296273-f83f50ce-0741-4fd4-a5ed-e77534081f9d.png)

**Comment by findyy99** [comment]
So, have you solved this problem, my dell inspiron 5580 just runs with the max speed, almost 4500rpm even when I open nothing. I don’t know why.

**Comment by Edwardwich** [comment]
> So, have you solved this problem, my dell inspiron 5580 just runs with the max speed, almost 4500rpm even when I open nothing. I don’t know why.

Use dell smc kext

**Comment by findyy99** [comment]
> > So, have you solved this problem, my dell inspiron 5580 just runs with the max speed, almost 4500rpm even when I open nothing. I don’t know why.
> 
> Use dell smc kext

Sure, I use the sensor kext specifically for Dell. Now, I think it may be the issue of disable GPU. After boot to macOS, the gpu is not totally disabled, still hot, which makes the fans run at the almost max speed. Thanks anyway!

**Comment by Edwardwich** [comment]
> > > So, have you solved this problem, my dell inspiron 5580 just runs with the max speed, almost 4500rpm even when I open nothing. I don’t know why.
> > 
> > Use dell smc kext
> 
> Sure, I use the sensor kext specifically for Dell. Now, I think it may be the issue of disable GPU. After boot to macOS, the gpu is not totally disabled, still hot, which makes the fans run at the almost max speed. Thanks anyway!

Disable with ssdt or config ?

**Comment by findyy99** [comment]
> > > > So, have you solved this problem, my dell inspiron 5580 just runs with the max speed, almost 4500rpm even when I open nothing. I don’t know why.
> > > 
> > > 
> > > Use dell smc kext
> > 
> > 
> > Sure, I use the sensor kext specifically for Dell. Now, I think it may be the issue of disable GPU. After boot to macOS, the gpu is not totally disabled, still hot, which makes the fans run at the almost max speed. Thanks anyway!
> 
> Disable with ssdt or config ?

Before it used `wegnogpu` to disable the GPU, I think the result is not perfect, so I change it to use SSDT. Now there is only one problem the speed of the fan can only run at about 2500, 3500 and 4000 RPM.

**Comment by Edwardwich** [comment]
> > > > > So, have you solved this problem, my dell inspiron 5580 just runs with the max speed, almost 4500rpm even when I open nothing. I don’t know why.
> > > > 
> > > > 
> > > > Use dell smc kext
> > > 
> > > 
> > > Sure, I use the sensor kext specifically for Dell. Now, I think it may be the issue of disable GPU. After boot to macOS, the gpu is not totally disabled, still hot, which makes the fans run at the almost max speed. Thanks anyway!
> > 
> > Disable with ssdt or config ?
> 
> Before it used `wegnogpu` to disable the GPU, I think the result is not perfect, so I change it to use SSDT. Now there is only one problem the speed of the fan can only run at about 2500, 3500 and 4000 RPM. 

Use ssdt and `wegnogpu` in config and rest nvram

**Comment by findyy99** [comment]
> > > > > > So, have you solved this problem, my dell inspiron 5580 just runs with the max speed, almost 4500rpm even when I open nothing. I don’t know why.
> > > > > 
> > > > > 
> > > > > Use dell smc kext
> > > > 
> > > > 
> > > > Sure, I use the sensor kext specifically for Dell. Now, I think it may be the issue of disable GPU. After boot to macOS, the gpu is not totally disabled, still hot, which makes the fans run at the almost max speed. Thanks anyway!
> > > 
> > > 
> > > Disable with ssdt or config ?
> > 
> > 
> > Before it used `wegnogpu` to disable the GPU, I think the result is not perfect, so I change it to use SSDT. Now there is only one problem the speed of the fan can only run at about 2500, 3500 and 4000 RPM.
> 
> Use ssdt and `wegnogpu` in config and rest nvram

Thanks and I will try.
