### ISSUE TITLE
[Python3] Utilities

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1997]
Since the most of the Python written utilities are migrated to Python 3, is it in your interest adapting them using better syntax (such as `match case` syntax)? If so, can I open a PR?
Thanks and have a nice day

**Comment by vit9696** [comment]
We personally try to support python2 still, but perhaps it is about the time to drop its support. @Andrey1970AppleLife, @PMheart, @khronokernel what do you think?

**Comment by PMheart** [comment]
I am ok with the upgrade, while there is no harm to keep backward compatibility.

**Comment by dreamwhite** [comment]
> I am ok with the upgrade, while there is no harm to keep backward compatibility.

Okay, I'll draft a PR in the following days so we can discuss about it.

**Comment by dreamwhite** [comment]
Hi there, I made a quick draft of the improvments made to most of Python scripts
