### ISSUE TITLE
Legacy boot utilities on Linux

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#1999]
Since most `Utilities` tend to be cross-platform, I'd like to know if it's possible to add support for Linux for the `BootInstall_X64.tool` (or adapt that for busybox utilities) so that people don't require to have macOS installed somewhere else in order to run those commands to create a MBR compatible boot device

**Comment by vit9696** [comment]
We will accept a PR here, but I am not positive we will work on this ourselves. Thanks!

**Comment by vit9696** [comment]
QemuBuild.tool does support Linux now.

**Comment by savvamitrofanov** [comment]
As for now, the `BootInstall_X64.tool` script supports Linux too, so we can close this issue.
