### ISSUE TITLE
using the virtualsmc and its plugins couldn't monitor gpu temperature

### ISSUE THREAD

**Issue by Kwokping** [acidanthera/bugtracker#2007]
using the virtualsmc and its plugins couldn't monitor gpu temperature，how can i fix it。
I use smcread -s couldn't see the key "tg0p" and "tg0d" after I new install the OS.

Platform：iMac 15.1

OpenCore：0.8.0
Lilu：1.6.0
VirtualSMC：1.2.9

Hardware：
CPU：intel 4790k
GPU： Nvidia GTX760

OS： Mac Big Sur 11.6.5

**Comment by Andrey1970AppleLife** [comment]
VirtualSMC plugin for GPU not developed. Ask about plans by @joedmru.
