### ISSUE TITLE
[Request] Block AAPL,PanicInfoXYZ NVRAM Write Attempts

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#2008]
Proposing an extension of the `WrapSetVariable` function to also block `AAPL,PanicInfoLog` and `AAPL,PanicInfo####` write attempts.

Panic Info logs stored in the NVRAM can be of a pointer type, `AAPL,PanicInfoLog` or Type A, that point to an actual log file on the filesystem or another type, AAPL,PanicInfo#### or Type B, where #### is a hex number presenting parts of the panic log stored directly in the NVRAM. 

In such cases, the panic log is split into multiple NVRAM variables which add up to close to 10Kb. This size may not be an issue on relatively recent computers, but it is on units such as Legacy Mac Pros where the variable store is only 64kb. Additionally, garbage collection only takes place at boot time which means that when a process later on, such as an installer, tries to store a large enough variable, the store can easily be overrun and lead to a bricking of such units.

This proposal does not tackle the root problem which is that MacOS BigSur and later write all sorts of stuff to the NVRAM during updates in particular. There is a list of variables MultiUpdater hits here: https://github.com/acidanthera/bugtracker/issues/1255#issuecomment-721469747.

It turns out that this is not a particularly new problem as this issue from 2013 on a unit with the same NVRAM vintage as Legacy MacPros shows: https://www.theregister.com/2013/02/11/samsung_uefi_boot_bug_windows_linux

As said, the staging and unconditional running of the multiupdater is the root issue, but it can be mitigated by spoofing VMM when updating. This proposal is more of plucking some low hanging fruit in terms of targeting the KP stuff which are stored if/when an issue is hit during the process, as the existing infrastructure to to block UEFI Windows certificates can readily be extended to cover the KP data as well.

So, I propose modifying the `ProtectSecureBoot` token which deals with the certificates to also filter out KP information. It will be renamed as `IgnoreNvramWrites` and take a bitmask that will cover the existing certificates and the KP information. New items can be added as they arise.

I will submit a PR in due course if there is no objection

**Comment by dakanji** [comment]
On hold while @mikebeaton updates potentially overlapping items

**Comment by mikebeaton** [comment]
Okay, let's close, and re-open if needed.

**Comment by mikebeaton** [comment]
Hi again @dakanji - The idea here is to add new config, allowing blocking certain NVRAM variables from write, correct? This sounds like a potentially good idea to me, regardless of other projects I'm working on. The final decision would rest with @vit9696 though.

**Comment by mikebeaton** [comment]
I would not be keen on the specifically bitmask implementation - more future-proof would be named variables in named sections, similar to the existing `LegacySchema` layout.

**Comment by dakanji** [comment]
I have already implemented this and it has been ready to push for about a week but if some other approach would be better, then perfectly fine to shut this issue down and go that way.

Changing the existing variable was easy and I could take that on but would have to leave the new schema type thing to an expert such as you.

Team needs to make a call on what it wants to do

**Comment by mikebeaton** [comment]
Okay, if you're not likely to take on the slightly broader project yourself - you're still welcome to - then probably best to just bear the sightly extended version of your proposal in mind, and I'll get back to you as and when.

**Comment by dakanji** [comment]
Noted. I yield on this and look forward the improvements from the broader item.

**Comment by dakanji** [comment]
Turns out specifically blocking kernel panic logs was not required at the end of the day since they are only written to the NVRAM because of a default MacOS boot argument of `nvram_paniclog=1`.

Simply setting a `nvram_paniclog=0` argument stops writing panic logs to NVRAM!
