### ISSUE TITLE
[AppleALC] Support 192 kHz digital audio when using optical output

### ISSUE THREAD

**Issue by axeldelafosse** [acidanthera/bugtracker#2010]
Hey guys,

Thank you so much for your hard work.

I just got a Marantz amplifier and an optical cable to connect it with a Realtek ALC1220. Just realized that the maximum sample rate is 96kHz even if the hardware supports up to 192kHz.

I learned that it was possible to play 192 kHz digital audio in the past when the Apple audio hardware was supporting it: https://support.apple.com/en-us/HT202730

Do you have more context to share please? I'm not sure to fully understand the implications and read somewhere on an old forum that it's a current limitation of AppleALC.

I'd love to help supporting high sample rate digital audio!

**Comment by vit9696** [comment]
I am not positive much can be done here on the resource side. Perhaps @roddy20 knows more?

**Comment by Andrey1970AppleLife** [comment]
Earlier on Applelife.ru discussed this problem, and with @roddy20 too there. The solution for AppleHDA didn't find.
You can use VoodooHDA for 192 kHz.
