### ISSUE TITLE
[Feature Request] Folders in picker

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2012]
I'd like to know if folders can be implemented onto OpenCore picker, as well as OpenCanopy, such as already implemented in GRUB2 bootloader (see `Advanced Options for Ubuntu`)

![image](https://user-images.githubusercontent.com/17933708/167956438-3b7db8f1-f1c7-43a9-bb75-8e9ffdc7cb73.png)

It can be useful for those who have lot of tools and don't wanna clog the picker with lot of entries.

**Comment by kernelBPD** [comment]
Pretty sure this is already an “option,” per se. 

`Misc->Boot->HideAuxiliary` should be (by default) set to `False`, you can enable this option in order to hide additional entries (such as various tools, macOS recovery boots, macOS time machine and entries that are explicitly marked as `Auxiliary`.)

Once, and if, you’ve enabled this option and want to view the hidden entries, you can press the `Spacebar` key to reload into “Extended Mode,” which will show all the auxiliary entries.

**Comment by vit9696** [comment]
I would say I personally am somewhat against this as it would overcomplicate the OpenCanopy code. CC @mhaeuser @mikebeaton

**Comment by dreamwhite** [comment]
> It's worth noting that we have already done some of what folders are for in GRUB2, by hiding non-default kernel entries as auxiliary entries in OpenCore OpenLinuxBoot. (Therefore if using OpenLinuxBoot then as per the docs it is recommended to set `HideAuxialiary` to `true`.)

Oh alright. So basically it's kinda not worth doing the same for macOS kernels as it may overcomplicate both OpenCore builtin picker and OpenCanopy, right?

**Comment by mhaeuser** [comment]
> Oh alright. So basically it's kinda not worth doing the same for macOS kernels as it may overcomplicate both OpenCore builtin picker and OpenCanopy, right?

There simply is no such thing for macOS. Adequate OSes ship as one sound bundle and don't have stuff like different kernel versions to choose from.

**Comment by dreamwhite** [comment]
Wait, maybe I expressed badly. What I wanted to achieve is something along the lines of "given that I have multiple macOS installations, is it possible to create a single folder with all the macOS bootable drives?"

**Comment by dreamwhite** [comment]
Alright, thanks for the explanation and have a nice day :)

**Comment by mikebeaton** [comment]
> So basically it's kinda not worth doing the same for macOS kernels as it may overcomplicate both OpenCore builtin picker and OpenCanopy, right

Btw, if _all_ you wanted was to do the same, well that is indeed much less (over-)complexity than adding full folder support. But it would need a sane way of marking the 'main' macOS. And I (plus, I think, we) would still need convincing that there's much case for this at all, for most users.
