### ISSUE TITLE
r lion, when I select the Mac OS X Install  ESD I get "loading kernel cache file \kernelcache.. error allocating 0xe2 pages at 0x0000000000 alloc type 2 error loading kernelcache (0x9)

### ISSUE THREAD

**Issue by kocoman1** [acidanthera/bugtracker#2014]
I am using 0.8.0 opencore with osx-kvm / qemu for lion, when I select the Mac OS X Install  ESD I get "loading kernel cache file \kernelcache.. error allocating 0xe2 pages at 0x0000000000 alloc type 2
error loading kernelcache (0x9)
OCB: StartImage failed - aborted.  

I tried the Cacheless for the kernelcache in config.plist and it still says error loading kernelcache (0x9)
OCB: StartImage failed - aborted.  

also tried -f 

any ideas ? thx
use some slide values work for kernelcache ?

**Comment by vit9696** [comment]
Try enabling `AllowRelocationBlock` quirk. But I will not promise it will work on all systems still.
