### ISSUE TITLE
FeatureUnlock - Not patching dyld

### ISSUE THREAD

**Issue by joaoramosipl** [acidanthera/bugtracker#2019]
Hello there,
I'm currently using Lilu Debug and FeatureUnlock Debug versions, and I cannot setup AirPlay to Mac.

I checked logs, and it is supposed to be patching dyld_shared_cache_x86_64h.1 and dyld_shared_cache_x86_64h.3 for both AirPlay and Universal Control respectively.

Although, when I open both files, I cannot find NacBook anywhere, so they weren't patched.
UniversalControl.app seems fine, and Universal Control is even displayed under Displays.

Under Sharing, there is no evidence of AirPlay as well.

Can you please help me?
Thanks!

**Comment by khronokernel** [comment]
No logs, OS information, build version, SMBIOS model, etc. Please see repository's README for proper logging and use [forums](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/FORUMS.md) for troubleshooting
