### ISSUE TITLE
Cannot change properties through SSDT using Sample.dsl

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#2020]
Below is how WEG attaches the GPU:
![image](https://user-images.githubusercontent.com/7897244/169427650-5683b6d7-b16f-470d-b829-09ba0ec07a4c.png)
Attached is the Sample.dsl setup for the current system, but it does not change anything.
[SSDT-X299-6600xt.zip](https://github.com/acidanthera/bugtracker/files/8734985/SSDT-X299-6600xt.zip)

**Comment by khronokernel** [comment]
See SSDT-BRG0:
* https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/Source/SSDT-BRG0.dsl

Any time you see a `pci-bridge` entry, you need to provide an ACPI device for it. 

Additionally, your ACPI injection provided is botched. You're injecting properties onto `SL05` when the actual GPU is 2 children down. Keep in mind that WEG is renaming your GPU for you to GFX1, you'll need to still provide an ACPI device for the GPU itself if none exists in your firmware's ACPI table.

I would advise troubleshooting further on forums, this issue doesn't seem to be related to any of Acidanthera's projects

**Comment by startergo** [comment]
> You're injecting properties onto `SL05` when the actual GPU is 2 children down.

That was my question too as I was following:
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/Sample.dsl
device PEGP in my case is SL05 and the injection is there. So maybe the Sample.dsl needs correction?

**Comment by khronokernel** [comment]
SL05 is not equivalent to PEG0 in your system, you need to define the 2 sub children yourself and then adjust the Sample.dsl to point to the correct children.

Thus: 
* SL05/pci-pridge = PEG0
* SL05/pci-bridge/GFX1 = PEGP

And reminder, GFX1 is not real. WEG is just doing its magic to rename the device. In reality, it's another ACPI-less device

**Comment by startergo** [comment]
Got it working finally. Posting the file for other's benefit. Thanks @khronokernel.
[SSDT-BRG0-X299.dsl.zip](https://github.com/acidanthera/bugtracker/files/8748318/SSDT-BRG0-X299.dsl.zip)
