### ISSUE TITLE
My audio ALC256 with Crackling/popping

### ISSUE THREAD

**Issue by sirramosS** [acidanthera/bugtracker#2024]
I found that the crackling/popping of the hackintosh audio is the battery. I did a test, unplugged my notebook battery and tested the hackitosh, and to my surprise the audio flowed normally, without any crash, and soon after reconnecting, it went back to the crash before… Do you have any solution for this type of problem? I tried to change layout id, and stuff, but to no avail. I don’t know who else to turn to, you are the only one who can solve the problems.

**Comment by mikebeaton** [comment]
Crash? Crash log?

In general, for crackling and popping, AppleALC provides tools for knowledgeable users to make sound work on their machine, and share the results. Basically you need to either try to chat to the user who made the layout you're using, or do a lot of research and experimentation yourself. In general for crackling and popping (at startup and shutdown) the order of init commands in the config can help - there is some info about this in AppleALC FAQs.

**Comment by sirramosS** [comment]
I managed to solve the problem. I simply removed VirtualSMC and its addons, and added FakeSMC in the kext folder of the OC. And now my audio works normally without any crackling/popping.

**Comment by liangyi9812** [comment]
> In general for crackling and popping (at startup and shutdown) the order of init commands in the config can help - there is some info about this in AppleALC FAQs

@mikebeaton I can't find information about `the order of init commands in the config` in the [FAQs](https://github.com/acidanthera/AppleALC/wiki/Frequently-Asked-Questions). Would you kindly provide me with the accurate link? I've been dealing with crackling and popping sounds during startup for quite some time. I've tried changing the layout ID and even created my own, but unfortunately💔, this hasn't resolved the issue. Could you please offer some troubleshooting suggestions? I would greatly appreciate it.

**Comment by mikebeaton** [comment]
@liangyi9812 - I was talking about the [processing coefficients](https://github.com/acidanthera/AppleALC/wiki/Dumping-processing-coefficients#how-to-make-the-changes-permanent) in the config.

**Comment by liangyi9812** [comment]
> @liangyi9812 - I was talking about the [processing coefficients](https://github.com/acidanthera/AppleALC/wiki/Dumping-processing-coefficients#how-to-make-the-changes-permanent) in the config.

@mikebeaton Thank you very much for your response. I tried to correct my `ConfigData` following the tutorial in your link, but it doesn't seem to be working. I've added `alcid=98 (which I created)` and `alcverbs=1` in the boot arguments. Command-line modifications also didn't work. Do you have any other suggestions?

![in ConfigData](https://z1.ax1x.com/2023/10/23/piAljqs.png)
![in manual](https://z1.ax1x.com/2023/10/23/piAlzaq.png)

**Comment by mikebeaton** [comment]
This really isn't a tutorial location - also no, I don't have any other suggestions (other than: explore the code and develop a PR, or find a forum which has or had active discussion of AppleALC and ask there). I did not write AppleALC, I know more about AudioDxe (but I did not write that, either!).
