### ISSUE TITLE
[SMCBatteryManager] when battery status below 10%, system crash ,screen turn into black 

### ISSUE THREAD

**Issue by nabaonan** [acidanthera/bugtracker#2029]
following steps：
1. use computer with battery
2. when battery status is below 10% ，the screen turn into black, system crashed

EFI link: [repo](https://github.com/nabaonan/airbook-6200u-efi)
versions: oc0.8.0 virtualSMC 1.2.9

**Comment by PMheart** [comment]
Hello! Thanks for your report. Unfortunately, without further logs we are unable to provide any help, therefore I am closing this issue.
