### ISSUE TITLE
MaciASL gives many errors on compile

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#2031]
When using latest MaciASL from Acidanthera there are many errors during compilation.
```
_UID inside processor declaration must be an integer (found a string)
```
https://patchwork.kernel.org/project/linux-acpi/patch/20190610200734.1182-1-ahs3@redhat.com/
When using Rehabman's fork here:
https://bitbucket.org/RehabMan/os-x-maciasl-patchmatic/downloads/
There are no errors at all.
![image](https://user-images.githubusercontent.com/7897244/171037742-c47c78d0-b33e-47ab-80fc-85d4fe43c0f3.png)
![image](https://user-images.githubusercontent.com/7897244/171037813-2a817d79-3dbb-43a1-bc55-da6c384dc092.png)
[Archive.zip](https://github.com/acidanthera/bugtracker/files/8799951/Archive.zip)

**Comment by startergo** [comment]
The problem is not with the compilation of MaciASL, but the compilation of the DSDT/SSDT. which in this case errors on 
```
_UID inside processor declaration must be an integer (found a string)
```

**Comment by startergo** [comment]
https://www.acpica.org/node/172
```
iASL: added an error on _UID object declaration that returns a String within a Processor () declaration. A _UID for a processor must be an Integer.
```

**Comment by Drovosek01** [comment]
Did I make such a patch for my DSDT from the Chinese x79 motherboard? which changes the following argument for "_UID" to a hex value/ I don't know if this is correct? but this removed the corresponding compilation errors.

![Снимок экрана 2022-11-05 в 03 56 06](https://user-images.githubusercontent.com/29478700/200094063-73fcdc53-def2-45fc-b18f-9b201ca09604.png)

```
into_all all code_regex Name\s+\(_UID,\s*\"PCI\d\-CP(.*)\"\) replace_matched
begin
Name (_UID, 0x0%1)
end;
```

Here is the original DSDT without corrections
[DSDT.aml.zip](https://github.com/acidanthera/bugtracker/files/9942636/DSDT.aml.zip)
