### ISSUE TITLE
ALC287 Audio master volume stuck at mute despite audio buttons working.

### ISSUE THREAD

**Issue by Babyyoda777** [acidanthera/bugtracker#2035]
Have I looked for support elsewhere?
Yes

Have I gone to reddit/insanelymac/gitter?
Yes

Have I searched existing posts and issues?
Yes

Hardware:
CPU: i3 1005G1
GPU: Intel UHD G1
Laptop: HP Pavillion x360 14-dw0002na
Audio codec: ALC287, lay out id - 11
Lilu/AppleALC versions: latest

The issue:
I have correctly patched HDEF and this shows in IOReg. MacOS detects my internal speakers, but even on full volume no sound is played. There is no sound system wide. When I investigated further, it turns out that for some reason the master volume in Audio MIDI Setup reports as being at 0, with full volume being 0Db and mute being -62.25Db which is ridiculous
as no sound will be outputted at any time. Screen shot:

![Screenshot 2022-06-05 at 19 59 09](https://user-images.githubusercontent.com/80623330/172066212-742d0011-d1df-4bd7-be4f-b001b643cba5.png)

This is despite the device being correctly detected by the OS and patched correctly.
![Screenshot 2022-06-05 at 20 00 54](https://user-images.githubusercontent.com/80623330/172066262-eb712e4e-e8f3-4269-bcba-9c2056423be1.png)

![Screenshot 2022-06-05 at 20 01 25](https://user-images.githubusercontent.com/80623330/172066282-8415f4ab-5fac-433f-9922-76615d2ec73b.png)

In the end, this has led me to believe that the issue is with AppleALC itself and NOT my config file which is available to see at: https://github.com/Babyyoda777/Hackintosh-Big-Sur-Pavillion-x360

Is there any specific reason why this is happening and anyway to fix this until next release?

**Comment by mikebeaton** [comment]
0dB down to -62.25dB sounds perfectly reasonable - see the description of decibel volume levels which apply to AudioDxe in the docs (same volume scale).

As regards no sound even though volume buttons etc. appear to work, we added some info recently to AppleALC docs about this which will likely apply: https://github.com/acidanthera/AppleALC/wiki/Dumping-processing-coefficients

**Comment by Babyyoda777** [comment]
How do I dump the coefficients on MacOS? I'm using the script on the GitHub and have enabled alcverb in config.plist, but it keeps returning "dump_coeff {device-index} {node-id} {count}". Im not sure how to run in correctly. How would I do this?

**Comment by Babyyoda777** [comment]
ok thanks

**Comment by Babyyoda777** [comment]
So I have done the linux codec dump and found my ncoeff to be 142 on node 0x20. I tried to run the command via dump_coeff.sh : `dump_coeff 0 0x20 142` but all I got in return was `nid = 0x0, verb = 0x0, param = 0x20
0x00000000` like before. Is there something I am doing wrong?

**Comment by Babyyoda777** [comment]
I also tried `dump_coeff 0 0x20 0x142` with the same result and also tried varying the device index with no luck.

**Comment by mikebeaton** [comment]
You need to work through all the possible differences. There is a bit of art as well as science. Btw this is not guaranteed to be the issue but it's pretty possible it will help. That said, I am basically just repeating what it says in the doc to you...

**Comment by Babyyoda777** [comment]
I'm sorry but the wiki is incredibly vague to a beginner like me when it says "possible differences" what exactly are the differences? The two shown above are the only two which are different and changing them has no effect.

**Comment by mikebeaton** [comment]
It's just a tool to help out! If those are the only two differences then they are, indeed, the only two differences. If changing either or both does not work, then that's not it, I guess. It definitely has helped getting some layouts on some systems working. I'm not an expert in creating a layout from scratch, if the issue is something else, you need to follow the links in the FAQs, sorry.
