### ISSUE TITLE
WEG documentation/questions

### ISSUE THREAD

**Issue by rafale77** [acidanthera/bugtracker#2036]
Forgive my ignorance, I am digging deeper into some features of the WEG code around GVA and found a few things which puzzle me:

1. The latest release of WEG includes the following logic inversion of a feature which is not documented on WEG:
https://github.com/acidanthera/WhateverGreen/pull/98
What does this patch do? I found it to be a kernel patch https://github.com/acidanthera/WhateverGreen/blob/master/WhateverGreen/kern_rad.cpp#L174-L175
I read somewhere in forums that it is to enable HEVC encoding on AMD Polaris GPUs but I my WX 4100 which is a Polaris Baffin appears to have HEVC even without this on Monterey. What GPUs does it apply to and what kernel version?
Should this be added to the WEG readme  (radgva=1/0 -- enable-gva-support)?

2. The following text is a bit unclear:
`igfxmetal=1 boot argument (and enable-metal property) to force enable Metal support on Intel for offline rendering.`
What I found out is that it turns the "offline" iGPU on iMac and MacMini SMBIOS to "online" state. For AppleGVA this leads to having 2 "online" GPUs and is confusing the heck out of it when it is running with an iMac hwgva-id which calls for "force-offline-renderer"

3. I would also like to report that I found a problem for SideCar when using an iMac SMBIOS and this command
`defaults write com.apple.AppleGVA gvaForceAMDKE -boolean false`
with Sidecar freezing/stuttering when running on the dGPU. I suspect that it is because some of the AppleGVA logic tries to follow the hwgva-id "force-offline-renderer" setting and some other is trying to follow the forceAMDKE command. I have eliminated these sidecar problems by modifying the unfairgva code to inject an MacMini8,1 hwgva-id which is identical to my iMac20,2 SMBIOS except for the deletion of the "force-offline-renderer" setting.

4. What does the "wegtree" option exactly affect? I understand it gets the kernel to rebuild the device settings but when is it needed? What does it fix?

5. What does the unfairgva bitmask '2' exactly do? I see that it is to losen the HDCP requirement? How does one test this? What problem does it potentially fix?

**Comment by antoniomcr96** [comment]
One more question, that could be probably explained better by the documentation
6. `igfxonlnfbs=MASK boot argument (force-online-framebuffers device property) to specify indices of connectors for which online status is enforced. Format is similar to igfxfcmsfbs.` -> `for example, value 0x010203 specifies connectors 1, 2, 3.` If I want to specify only connectors 1 and 3 what should i write? 0x010003? Only connector 1 is 0x010000? Because it doesn't seem to work. Maybe some examples in the documentation might help. Thanks

**Comment by vit9696** [comment]
1. This patch is responsible for force-enable GVA (hardware video decoding/encoding) acceleration on X4000 GPUs when it is disabled for whatever reason via `enable-gva-support` property or `radgva=1` argument. I will be glad to see a patch updating the documentation.
2. `for offline rendering` is a bit confusing indeed, it means for GPUs in offline rendering mode. Will accept a patch here too.
3. Quite likely. We can consider making it possible without code modifications but just configuration. Do you have a patch suggestion?
4. I think it fixed external GPUs on cMP (MP5,1 and alike) but it is hard to remember.
5. For older Mac models Apple allows some relaxed HDCP settings. This patch overwrites MacPro6,1 or similar with the current Mac model. It is not quite clear what kind of relaxing it gives, but it fixed HDCP on some Macs and Hacs.
