### ISSUE TITLE
[macOS Ventura 13.0] Booting issues

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2038]
Hi there,
I'm opening this issue to keep track of the bugs and future development of OpenCore as well as the kexts, in terms of macOS Ventura 13.0 support.
I'm not there to hurry the devs up keep that in mind 🙂

From what I've noticed, OpenCore (latest release 0.8.1) hangs on boot at `Stuck on [EB|#LOG:EXITBS:START]`.

I tried to change `SecureBootModel` to:
- `Disabled`
- `Default`

without any luck.

I'm attaching the `BaseSystem.dmg` link for those who wanna attempt themselves: [Google Drive mirror](https://drive.google.com/file/d/1MKBEsGrPYi3-t0PtUKBFZ-cPCkiF7PUr/view?usp=sharing)

**Comment by ITzTravelInTime** [comment]
To me this looks like some added checks inside the boot.efi, perhaps they are actually enforcing some checks for the hardware or the firmware inside the bootloader this time.

**Comment by Edwardwich** [comment]
![IMAGE 2022-06-07 05:22:04](https://user-images.githubusercontent.com/35195176/172272883-1d7eaa73-2822-455f-b3a4-38a79314a06d.jpg)

**Comment by dehjomz** [comment]
A clue is to disable AvoidRuntimeDefrag, and possibly enable boot-arg -lilubetaall. 

Is working on alder lake. 28 degrees at idle.

**Comment by Edwardwich** [comment]
> A clue is to disable AvoidRuntimeDefrag, and possibly enable boot-arg -lilubetaall. 
> 
> Is working on alder lake. 28 degrees at idle. 

Yes now strat booing

**Comment by Edwardwich** [comment]
> A clue is to disable AvoidRuntimeDefrag, and possibly enable boot-arg -lilubetaall. 
> 
> Is working on alder lake. 28 degrees at idle. 





Show this and resting laptop

**Comment by Edwardwich** [comment]
> > A clue is to disable AvoidRuntimeDefrag, and possibly enable boot-arg -lilubetaall.
> > Is working on alder lake. 28 degrees at idle.
> 
> Yes now strat booing
![IMAGE 2022-06-07 06:03:28](https://user-images.githubusercontent.com/35195176/172276722-5e02a243-4edd-4973-885d-89dfa2f08f25.jpg)

**Comment by ITzTravelInTime** [comment]
One possible explanation for some of the freezes , accordion to some people is that the new os drops support for cpus without avx2, this essentially cuts out a lot of old and cheap hardware, including the ivy bridge cpus, very sad.

**Comment by Edwardwich** [comment]
> One possible explanation for some of the freezes , according to some people online is that the new os drops support for cpus without avx2, this essentially cuts out a lot of old and cheap hardware, including the ivy bridge cpus, very sad.

Do you have any ideas for fix this ?

**Comment by taruyato** [comment]
> A clue is to disable AvoidRuntimeDefrag, and possibly enable boot-arg -lilubetaall.
> 
> Is working on alder lake. 28 degrees at idle.

You're right. Disable AvoidRuntimeDefrag will pass the `[EB|#LOG:EXITBS:START]`.
I tried to grab the artifact from the lastest build of Lilu (no need `-lilubetaall`), VirtualSMC and OC 0.8.2. My laptop automatically restarting at `AppleSMC` after cleaning the nvram, I guess(?).
Testing on Dell G7 7588. i7-8750H (CFG is unlocked, 5 MMIO-es are whitelisted).

**Comment by ITzTravelInTime** [comment]
> > One possible explanation for some of the freezes , according to some people online is that the new os drops support for cpus without avx2, this essentially cuts out a lot of old and cheap hardware, including the ivy bridge cpus, very sad.
> 
> Do you have any ideas for fix this ?

i can deny it, it just booted fine on my 2010 mac pro which doesn't support the avx instructions, so it should boot fine with any cpu supporting sse4.2 as far as i know.

btw since sse and avx are cpu instructions any eventual incompatibility caused by them is pretty much unfixable unless someone creates a specialized piece of software (usually a kext or a modified kernel) to emulate them, and it's a very complicated pieces of software to make.

**Comment by Edwardwich** [comment]
> > > One possible explanation for some of the freezes , according to some people online is that the new os drops support for cpus without avx2, this essentially cuts out a lot of old and cheap hardware, including the ivy bridge cpus, very sad.
> > 
> > 
> > Do you have any ideas for fix this ?
> 
> i can deny it, it just booted fine on my 2010 mac pro which doesn't support the avx instructions, so it should boot fine with any cpu supporting sse4.2 as far as i know.
> 
> btw since sse and avx are cpu instructions any eventual incompatibility caused by them is pretty much unfixable unless someone creates a specialized piece of software (usually a kext or a modified kernel) to emulate them, and it's a very complicated pieces of software to make.

my laptop cpu i5 8265u 
hp 1023nia
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/8850162/config.plist.zip)

idk how fix this can you check this ?

**Comment by ITzTravelInTime** [comment]
> > > > One possible explanation for some of the freezes , according to some people online is that the new os drops support for cpus without avx2, this essentially cuts out a lot of old and cheap hardware, including the ivy bridge cpus, very sad.
> > > 
> > > 
> > > Do you have any ideas for fix this ?
> > 
> > 
> > i can deny it, it just booted fine on my 2010 mac pro which doesn't support the avx instructions, so it should boot fine with any cpu supporting sse4.2 as far as i know.
> > btw since sse and avx are cpu instructions any eventual incompatibility caused by them is pretty much unfixable unless someone creates a specialized piece of software (usually a kext or a modified kernel) to emulate them, and it's a very complicated pieces of software to make.
> 
> my laptop cpu i5 8265u hp 1023nia [config.plist.zip](https://github.com/acidanthera/bugtracker/files/8850162/config.plist.zip)
> 
> idk how fix this can you check this ?

you pretty much don't have to worry about it, first because your cpu is from the last decade (so it does support all the needed features) and also if you can boot monterey you will be able to boot the new os. 

the problems now are related mostly to the open core team to figure out.

**Comment by andreszerocross** [comment]
![image](https://user-images.githubusercontent.com/9614101/172307891-569cb5af-4582-4ac7-92af-a3b683354f81.png)

Got this error notification in second phase installation,

**Comment by Edwardwich** [comment]
> ![image](https://user-images.githubusercontent.com/9614101/172307891-569cb5af-4582-4ac7-92af-a3b683354f81.png)
> 
> Got this error notification in second phase installation, 

Use full installer

**Comment by skat1452** [comment]
Hello everyone
I've never installed beta update of new Mac os, but today I decided to do that, and now I get stuck after auth. I tried to recover Mac from time machine, but by some reason, my Mac couldn't find any of it.
Could anyone help me just to boot successfully into system? Coz now I can't even do anything, only full reinstall from bootable USB.
In time machine in system recover is infinite search of copies, and in system I can't boot, in safe mode too.

**Comment by Edwardwich** [comment]
> > > ![image](https://user-images.githubusercontent.com/9614101/172307891-569cb5af-4582-4ac7-92af-a3b683354f81.png)
> > > Got this error notification in second phase installation,
> > 
> > Use full installer Install with Mac
> 
> This is from Full Installer, i downloaded from gibMacos.

Update to oc0.8.1

**Comment by andreszerocross** [comment]
> > > > ![image](https://user-images.githubusercontent.com/9614101/172307891-569cb5af-4582-4ac7-92af-a3b683354f81.png)
> > > > Got this error notification in second phase installation,
> > > 
> > > 
> > > Use full installer Install with Mac
> > 
> > 
> > This is from Full Installer, i downloaded from gibMacos.
> 
> Update to oc0.8.1

I already use OC 0.8.1, and i have tried OC 0.8.2 (latest commit) too

**Comment by taruyato** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/9614101/172307891-569cb5af-4582-4ac7-92af-a3b683354f81.png)
> > > > > Got this error notification in second phase installation,
> > > > 
> > > > 
> > > > Use full installer Install with Mac
> > > 
> > > 
> > > This is from Full Installer, i downloaded from gibMacos.
> > 
> > 
> > Update to oc0.8.1
> 
> I already use OC 0.8.1, and i have tried OC 0.8.2 (latest commit) too

Mine same. Now I can boot to macOS Installer but stuck at there. Using OC 0.8.2 latest commit.

**Comment by taruyato** [comment]
> > > A clue is to disable AvoidRuntimeDefrag, and possibly enable boot-arg -lilubetaall.
> 
> > > Is working on alder lake. 28 degrees at idle.
> 
> > 
> 
> > You're right. Disable AvoidRuntimeDefrag will pass the `[EB|#LOG:EXITBS:START]`. I tried to grab the artifact from the lastest build of Lilu (no need `-lilubetaall`), VirtualSMC and OC 0.8.2. My laptop automatically restarting at `AppleSMC` after clearing the nvram, I guess(?). Testing on Dell G7 7588. i7-8750H (CFG is unlocked, 5 MMIO-es are whitelisted).
> 
> 
> 
> I have the same error. Do you have any solutions?

Make a clean installer. Mine that version I downloaded via Software Update. But then I tried vanilla installer from Olarila and it worked.

**Comment by Loe-spec** [comment]
Is it kernel panic when It was keep restarting or not? I was able to bypass the eb log using disable avoidruntimedefrag but after that It just keeps restarting during boot.

**Comment by Edwardwich** [comment]
> Is it kernel panic when It was keep restarting or not? I was able to bypass the eb log using disable avoidruntimedefrag but after that It just keeps restarting during boot.

My laptop rest all time 

I try boot with safe mode it's work 
Install done and anything perfect now

**Comment by Loe-spec** [comment]
I should have clean install mac os ventura and see if it works.
