### ISSUE TITLE
Option to disable launch animation in OpenCanopy

### ISSUE THREAD

**Issue by hacker1024** [acidanthera/bugtracker#2040]
Since obtaining a 4K screen for my laptop, OpenCanopy is quite sluggish when it opens, because the animation where the options fade in runs at about 0.5fps for 3 seconds. Enabling the mouse pointer amplifies the issue. Doing so can increase the animation time twofold.

My laptop (a Dell Inspiron 7586) has an 8th Gen i7 - so I'd imagine this issue affects a lot of people with high-res displays, as it's not a software rendering bottleneck caused by low-end hardware.

It'd be great if there was a way to disable the animation, maybe with a flag in the `PickerAttributes`?

**Comment by mikebeaton** [comment]
Reopening, as I think this is a real issue (on some systems) so probably a reasonable option to provide. Will produce PR for feedback.

**Comment by mikebeaton** [comment]
Resolved by https://github.com/acidanthera/OpenCorePkg/pull/519
