### ISSUE TITLE
[Help wanted]Unable to boot anymore after disabling avoidruntimedefrag

### ISSUE THREAD

**Issue by wqhqq1** [acidanthera/bugtracker#2041]
with b360 chipset
trying to install macOS 13
closing avoidruntimedefrag
but stuck with the progress bar or pci in verbose mode

**Comment by 82ghost82** [comment]
Please before opening new issues, look at the closed ones:
https://github.com/acidanthera/bugtracker/issues/2038#issuecomment-1148647989

and please wait for the people to do their work.
