### ISSUE TITLE
RestrictEvents: CPU string patch no longer works since macOS 13 B1

### ISSUE THREAD

**Issue by VisualDevelopment** [acidanthera/bugtracker#2043]
RestrictEvents' CPU string patch no longer works since macOS 13 B1, instead shows guessed CPU string.
For example, instead of showing detected string from CPUID on my AMD machine, it shows Intel Core i5
```
sysctl machdep.cpu.brand_string
machdep.cpu.brand_string: AMD Ryzen 5 2600 Six-Core Processor
```
![Screenshot 2022-06-11 at 17 04 06](https://user-images.githubusercontent.com/30368284/173191171-37ef4a5e-1c02-41d5-80d2-4b4a570b2a50.png)

**Comment by PMheart** [comment]
Hello! Could you please try Lilu in this PR: https://github.com/acidanthera/Lilu/pull/81? You can download the binaries at GitHub Actions.

**Comment by VisualDevelopment** [comment]
> Hello! Could you please try Lilu in this PR: [acidanthera/Lilu#81](https://github.com/acidanthera/Lilu/pull/81)? You can download the binaries at GitHub Actions.

Hi! I tried the Lilu in that PR, but it doesn't appear to fix this.

**Comment by andreszerocross** [comment]
> Hello! Could you please try Lilu in this PR: [acidanthera/Lilu#81](https://github.com/acidanthera/Lilu/pull/81)? You can download the binaries at GitHub Actions.

![Screen Shot 2022-06-12 at 01 23 00](https://user-images.githubusercontent.com/9614101/173200343-b51316d5-d32d-4f56-aa45-51bb7c9d1ab5.png)

But I tried, and its success. My processor name is changed.

My processor is Intel i7 6700K actually

**Comment by sileshn** [comment]
It does work.

https://i.postimg.cc/mkwrfwV3/Screenshot-2022-06-12-at-11.png

**Comment by VisualDevelopment** [comment]
![image](https://user-images.githubusercontent.com/30368284/173333535-0faec40f-6862-4509-85d9-b3354f7fc752.png)
It does work with the new Lilu, I was just using the wrong version of the PR at the time

**Comment by PMheart** [comment]
@andreszerocross How is that even possible when there are not even any changes made specifically for Monterey?

**Comment by andreszerocross** [comment]
> @andreszerocross How is that even possible when there are not even any changes made specifically for Monterey?

I don't know, i try to use that commit for Ventura and Processor name is changed, but when i boot to Monterey the processor name is not changed. Then i revert back to latest lilu release version and monterey is working fine but not for ventura. Then i made double lilu version for monterey and ventura for temporary solution. Lilu-VEN.kext is from that commit.

![image](https://user-images.githubusercontent.com/9614101/174095111-85fc4bee-da53-4d3d-a572-b749c62a720e.png)

**Comment by andreszerocross** [comment]
I don't know result for AMD Procesor, but i have tried to change name for Intel processor like my processor i7 6700 and other i7 12700K. Newest lilu.kext won't change name for Intel Core i7 12700K (it's detected as Unknown in Monterey), if i revert back to latest release version of lilu.kext then i can change the name again.
