### ISSUE TITLE
WhateverGreen? macOS 12.4 + HD530 - GPU/Sleep/Wake Issues

### ISSUE THREAD

**Issue by TCB13** [acidanthera/bugtracker#2044]
Hello,

I've been tinkering with an "old" HP EliteDesk 800 G2 Mini computer and unfortunately the GPU doesn't seem to work properly, sleep seems affected by this. Once I tell the machine to sleep the LED will start blinking but after waking it up via keyboard, power button, or USB device it doesn't wake up the screen.

- Machine: HP EliteDesk 800 G2 DM 65W
- OS: 12.4 (21F79)
- OpenCore: 0.8.1 + latest kexts linked at https://dortania.github.io/OpenCore-Install-Guide/
- Processor: Intel(R) Core(TM) i5-6500 CPU @3.20GHZ
- System BIOS: N21 Ver. 02.53 04/16/2021 and/or N21 Ver. 02.56 04/08/2022

**What is broken:**
- VGA port - black screen;
- Can't change the DP port I'm using after the machine is ON - results in a black screen;
- Can't boot without a screen connected - can't ping / ssh;
- Sleep doesn't wake the screen - black screen.
- 4K Screens (https://github.com/randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh/issues/11)

There seem to be other with the same problem:
- https://github.com/randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh
- https://github.com/frostyviking/HP-EliteDesk-800-G2-OC

And I've discussed this issue at length and did a lot of testing here: https://www.tonymacx86.com/threads/opencore-sleep-hp-elitedesk-800-g2-mini-i5-6500.320697/ without any luck.

With my original config, just this:

![image](https://user-images.githubusercontent.com/6315832/173232906-b405d2e5-38df-413a-8612-da6aef04ff76.png)

The system seems to crash after coming out of sleep. After a lot of reading I eventually tried this:

![image](https://user-images.githubusercontent.com/6315832/173232880-e0cc5230-d387-4153-930f-8a950eff3a60.png)

The system now comes out of sleep (no crash) and I can ping it and SSH to it, however the screen doesn't wake up.

I also tried some framebuffer patching but it results in at around 25% of the boot process the screen goes black and never comes back. Examples of what I've tried https://github.com/tonnydam/HP-Elitedesk-800-G2-DM-Mini-OpenCore/blob/30ebdeb829c34ed1bc45d6662bbf496d3ec609e1/EFI/OC/config.plist#L307 , https://www.tonymacx86.com/threads/opencore-sleep-hp-elitedesk-800-g2-mini-i5-6500.320697/post-2325637 , https://www.tonymacx86.com/threads/opencore-sleep-hp-elitedesk-800-g2-mini-i5-6500.320697/post-2325724

I also tried to SSH into the machine after waking it up and issued `pmset displaysleepnow; caffeinate -u -t 1` without any luck. Replugging the display doesn't also work.

What should I do to debug this further / provide useful information?

Attached you may find my best config and a log of the computer going to sleep.

Thank you.
[log3-clear.txt](https://github.com/acidanthera/bugtracker/files/8885810/log3-clear.txt)
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/8885823/config.plist.zip)

**Comment by Andrey1970AppleLife** [comment]
Known issue with sleep/wake SKL IGPU. The guaranteed decisions aren't present.

**Comment by TCB13** [comment]
> Known issue with sleep/wake SKL IGPU. The guaranteed decisions aren't present.

@Andrey1970AppleLife thank you for your answer.

What do you mean by "guaranteed decisions aren't present"? Is the anything I should read? 

The guide at https://dortania.github.io/OpenCore-Install-Guide/ doesn't seem to provide any specific info on this.

Thank you.

**Comment by Andrey1970AppleLife** [comment]
Decisions aren't present.

**Comment by TCB13** [comment]
> Decisions aren't present.

What decisions? Can you give me any more info I can explore?

Thank you.

**Comment by Andrey1970AppleLife** [comment]
Try to use hibernation mode 25, this best decision for sleep/wake SKL IGPU, it helped many users.

**Comment by TCB13** [comment]
So... I set it to this:

``````
Currently in use:
 Sleep On Power Button 1
 autopoweroff         1
 standbydelayhigh     0
 autopoweroffdelay    0
 standbydelaylow      0
 standby              0
 proximitywake        0
 ttyskeepawake        1
 hibernatemode        25
 powernap             0
 gpuswitch            2
 hibernatefile        /var/vm/sleepimage
 highstandbythreshold 50
 displaysleep         10
 womp                 0
 networkoversleep     0
 sleep                0 (sleep prevented by mds_stores, mds)
 tcpkeepalive         1
 autorestart          0
 disksleep            0
`````

And it crashed when I tried to put it to sleep. Restarted to a RTC error.

I can't find many info on "o-encore Skylake hibernation 25" around. Thank you.
