### ISSUE TITLE
WEG connector patches not working with fake ID

### ISSUE THREAD

**Issue by graphine27** [acidanthera/bugtracker#2045]
For a HD 530 (1912), trying to force load KBL drivers by device properties:

device-id: 16590000 
AAPL,ig-platform-id: 00001659 

But it seems any framebuffer-conX- patch is not working. For example 
framebuffer-con1-enable 01000000 
framebuffer-con1-busid/type/index will not work (only one display working and changes not reflected in ioreg)

But these same patches work when using not injecting device-id and AAPL,ig-platform-id is set to 00001219.

**Comment by Lorys89** [comment]
try ig-platform-id è impostato su 00001659.
and device id 16590000

**Comment by graphine27** [comment]
@Lorys89 Those are exactly the ids I tried, and weg is latest also.
It just looks like weg can only patch framebuffer that was meant for my processor and won't work when using device-id and platform-id from other.

**Comment by Lorys89** [comment]
> @Lorys89 Those are exactly the ids I tried, and weg is latest also. It just looks like weg can only patch framebuffer that was meant for my processor and won't work when using device-id and platform-id from other.

use the last lilu https://github.com/acidanthera/Lilu/suites/6922581394/artifacts/269227911 
include this pr https://github.com/acidanthera/Lilu/pull/83

**Comment by graphine27** [comment]
@Lorys89 Thanks, that seems work for ventura. I was trying to do this for for monterey as a test before switching to ventura, is that possible?

I think the only way is to modify the code getKernelVersion() >= KernelVersion::Ventura to test this on monterey

**Comment by PMheart** [comment]
Hello,

First and foremost, I would like to remind that this is our bugtracker, where discussions do not fit. Please seek help on forums instead.

Secondly, https://github.com/acidanthera/Lilu/pull/83 is not related to framebuffer patching at all; this is definitely misleading news.

Thirdly, there is no support for SKL spoofing at this moment, as it has not been properly tested. This is the reason why https://github.com/acidanthera/WhateverGreen/pull/101 has not been merged yet. I have converted this PR to draft to avoid further confusions.

Last but not least, this issue does not look like any decent bug report.

Locking from further conversations.
