### ISSUE TITLE
Kext versions in Opencore log

### ISSUE THREAD

**Issue by Lucky-1978** [acidanthera/bugtracker#2048]
Is it possible to add show a kernel extension version in Opencore log?
For example, now injection looks in log like
Prelinked injection RealtekRTL8111.kext (comment from config here) - Success (or Failed)
and is it possible to show it like for example
Prelinked injection RealtekRTL8111.kext v. 2.4.2 (comment from config here) - Success (or Failed)?

**Comment by PMheart** [comment]
Hello, I have made an initial draft implementation at https://github.com/acidanthera/OpenCorePkg/pull/358. Could you please test it?

NOTE: @vit9696 decided that version information should only be available in DEBUG builds, so make sure you have it from our GitHub Actions.

**Comment by Lucky-1978** [comment]
Yes, in DEBUG build it shows kext version in Opencore log.

**Comment by dreamwhite** [comment]
> @PMheart, yes, in DEBUG build it shows kext version in Opencore log.

Hi there, is there any specific reason why kernel kext version isn't showed in OpenCore REL log? What are the possible consequences of having it in REL log? I guess security concerns?
