### ISSUE TITLE
OpenLinuxBoot/AudioDxe affects sound in Linux

### ISSUE THREAD

**Issue by mikebeaton** [acidanthera/bugtracker#2052]
[HJebbour](https://github.com/HJebbour) [commented](https://github.com/acidanthera/OpenCorePkg/pull/282#issuecomment-1159503234) yesterday
I don't know if I should post my issue here, but when I boot from OC to Ubuntu or Fedora using OpenLinuxBoot my Audio setup is not working (It shows Dummy Output and no Input), if I boot from GRUB audio works properly both input and output

[mikebeaton](https://github.com/mikebeaton) commented [9 hours ago](https://github.com/acidanthera/OpenCorePkg/pull/282#issuecomment-1159701591)
@HJebbour It should ideally work. It would make more sense to create a separate issue. Can you post config.plist, debug OC boot log booting into Ubuntu, also your machine and sound specs.

[HJebbour](https://github.com/HJebbour) commented 5 hours ago
@mikebeaton Thank you for your reply, please find attached the requested files and find below my machine's specs:

 - Lenovo ThinkPad X1 Carbon Gen 8 (i7-10510U)
 - Audio device: Intel Corporation Comet Lake PCH-LP cAVS (ALC285)

[log_config.zip](https://github.com/acidanthera/bugtracker/files/8936374/log_config.zip)

**Comment by mikebeaton** [comment]
Thanks for the additional info. Please can we confirm if, as seems likely, it's AudioDxe causing the problems? If you just disable that driver, losing your chime, you should not need to change anything else, to test whether that's enough to prevent these problems when booted via OC.

**Comment by HJebbour** [comment]
@mikebeaton Thank you for your interest in this topic, nice catch! Indeed the audio worked in Linux when disabling AudioDxe driver. Thank you again for your support!

**Comment by mikebeaton** [comment]
Try adding `--restore-nosnoop` to the Arguments of the AudioDxe driver.

**Comment by HJebbour** [comment]
It worked with `--restore-nosnoop` Argument, I wonder if this argument make AudioDxe works as it should for boot chime..

**Comment by mikebeaton** [comment]
Just to reconfirm, with `--restore-nosnoop` and AudioDxe **enabled**, you should have:

 - Normal sound in macOS
 - Normal sound in Linux
 - Working boot chime in OC

Please can you confirm - or not - that all three are working?

**Comment by HJebbour** [comment]
I can confirm all 4 are working perfectly! Windows, macOS, Linux and Boot chime in OC. Thank you very much for your assistance and helping me fixing this issue.

**Comment by mikebeaton** [comment]
Sure, I need to update the docs slightly, to mention that this flag is needed for Linux sometimes, not just Windows.

**Comment by mikebeaton** [comment]
https://github.com/acidanthera/OpenCorePkg/commit/3b70d73b213f3db3f32de2624bd423d384a5a3fb
