### ISSUE TITLE
kernel_task using 100% cpu after wake up, AppleALC related

### ISSUE THREAD

**Issue by ahianf** [acidanthera/bugtracker#2054]
Hi, I've been chasing this problem for months to no avail. Sometimes when I woke my laptop (Dell Latitude 5300) from sleep, kernel_task uses 100% of my cpu. A spindump of 10 seconds shows AppleHDAController using 1.7 seconds of cpu time.

`Thread 0x5ad    Thread name "AppleHDAController"    1000 samples (1-1000)    priority 81-93 (base 81)    cpu time 1.757s (7.0G cycles, 688.3M instructions, 10.17c/i)
`

This happens mostly when waking up and with battery, but sometimes when cold booting. In the last 9 months i haven't found a way to reliably trigger or stop this, sometimes stops after a minute, sometimes this persists across reboots. Also this bug happens in Catalina, Big Sur, Monterey, and across al OpenCore, Lilu, AppleALC versions released since september-2021.

[opencore-2022-06-21-145850.txt](https://github.com/acidanthera/bugtracker/files/8950134/opencore-2022-06-21-145850.txt)
[Lilu_1.6.0_20.6.txt](https://github.com/acidanthera/bugtracker/files/8950144/Lilu_1.6.0_20.6.txt)
[kernel_task_0.spindump.txt](https://github.com/acidanthera/bugtracker/files/8950186/kernel_task_0.spindump.txt)

**Comment by vandroiy2013** [comment]
Hi. This is probably a bug in PinConfiguration. Try to find author of layout-id you are using and ask him or somebody qualified in resource making to help.

**Comment by PMheart** [comment]
You have layout 22, thus https://github.com/acidanthera/AppleALC/commit/d9a82729a74694b648c14265380e56a2f99f90f5 is used.

@aleixjf Could you please take a look?
