### ISSUE TITLE
Feature Request: Refactor PlatformInfo to a separate file from config.plist

### ISSUE THREAD

**Issue by rbutera** [acidanthera/bugtracker#2055]
Not sure if this is the best place to post feature requests, sorry if it isn't.

The new issue README said this is the best place to discuss 'the technical aspects' of OpenCore, so I assume that this is relevant?

# Current Behaviour

When configuring opencore, (personal/identifying/secret) platform information is kept in the same place as (impersonal/safe to publish)  general configuration.

This discourages people from sharing their working configuration files out of fear of exposing their private information.

Publishing safely requires the user to scrub the personal identifying information from `config.plist` files, which is not generally automated.

# Expected Behaviour

OpenCore should load:

1. general information from the `config.plist` file (as it currently does)
2. platform information from `platform.plist`

`platform.plist` would contain the personal information normally contained in the `PlatformInfo` section of `config.plist`, most importantly

```
PlatformInfo->
    Generic->
        SystemProductName
        SystemSerialNumber
        MLB
        SystemUUID
        ROM
```

This file could then be added to .gitignore in order to allow people to publish their EFI folders in a more privacy-sensitive manner.

What are your thoughts? Is this feasible?

**Comment by dreamwhite** [comment]
I must admit, it's not a bad idea but I think this would increase complexity uselessly. Sharing a BSP isn't just a "drag and drop" operation, but rather stripping/censoring sensitive infos, such as PlatformInfo.
I wrote a stupid Python 3 script to censor sensitive infos stuff. You can check it [there](https://github.com/dreamwhite/Catone)

**Comment by rbutera** [comment]
> I must admit, it's not a bad idea but I think this would increase complexity uselessly. Sharing a BSP isn't just a "drag and drop" operation, but rather stripping/censoring sensitive infos, such as PlatformInfo.
> 
> I wrote a stupid Python 3 script to censor sensitive infos stuff. You can check it [there](https://github.com/dreamwhite/Catone) 

Cool script, but I disagree that complexity would be meaningfully increased.

A (naive) implementation of this solution would be:


1. (Prior to any validation) add line of code that loads platform.plist underneath the line of code that loads config.plist
2. create a new combined plist which concatenates the contents of platform.plist to the end of config.plist
- resume as normal with combined plist instead of config.plist

**Comment by vit9696** [comment]
I generally agree with the idea. It is a nice feature to have. However, we cannot find an easy way to implement it along with vaulting. This issue is actually a duplicate, see: https://github.com/acidanthera/bugtracker/issues/717. Perhaps you can suggest some ideas there.
