### ISSUE TITLE
OpenCanopy GUI icons not ejected

### ISSUE THREAD

**Issue by levuphucnguyen** [acidanthera/bugtracker#2056]
[My EFI Folder](https://github.com/acidanthera/bugtracker/files/8984740/EFI.zip)
I have both ResetNVRAM.icns and ToggleSIP.icns in my Resources folder but OpenCanopy keep using my Tool.icns for my Toggle SIP entry
I also have renamed OpenShell.efi to UEFI Shell but OpenCanopy keep using Tool.icns for my UEFI Shell entry
![z3519840593946_f0f4da67c734ab328a6b03ecbf6b0767](https://user-images.githubusercontent.com/96976083/175774049-8f5ec736-1cef-41cd-9df2-a98a6b00dd4a.jpg)

**Comment by mikebeaton** [comment]
Please use forums for support.
