### ISSUE TITLE
OpenCore related Assert, 0.8.3

### ISSUE THREAD

**Issue by Zormeister616** [acidanthera/bugtracker#2062]
Hardware:
HP Stream y010tu, (absolutely unsupported by macOS in terms of iGPU and Processor) 
Celeron N3060 (Braswell based CPU) + eMMC 32GB + HD 400 (using external drive to install macOS once i get it booting)
[opencore-2022-06-28-231212.txt](https://github.com/acidanthera/bugtracker/files/9007816/opencore-2022-06-28-231212.txt)
 
 “ASSERT [OpenCore] DivU64x64Remainder.c(38): Divisor != 0”

**Comment by vit9696** [comment]
@Goldfish64, this looks like a bug in https://github.com/acidanthera/OpenCorePkg/blob/6099ed0d2412bea5ba8a856af5a8b7385059f264/Library/OcAppleKernelLib/CpuidPatches.c#L1418-L1426

Could you please investigate?
