### ISSUE TITLE
RestrictEvents 1.08 problem (for unsupported AMD CPU)

### ISSUE THREAD

**Issue by fabiosun** [acidanthera/bugtracker#2065]
Previous 1.08 commits are fine
this one no:

https://github.com/acidanthera/RestrictEvents/actions/runs/2585644644

attached my Opencore debug where it is possible to see kext is not loaded and my EFI
[EFI.zip](https://github.com/acidanthera/bugtracker/files/9019932/EFI.zip)
[opencore-2022-06-30-124159.txt](https://github.com/acidanthera/bugtracker/files/9019934/opencore-2022-06-30-124159.txt)
[opencore-2022-06-30-111108.txt.zip]

zipped is a log with RestrictsEvent kext loaded
(https://github.com/acidanthera/bugtracker/files/9019941/opencore-2022-06-30-111108.txt.zip)

**Comment by khronokernel** [comment]
It seems your Lilu is outdated (listed as June 13th from your upload):
```
12:465 00:006 OCAK: Symbol __ZN13KernelPatcher22findAndReplaceWithMaskEPvmPKvmS2_mS2_mS2_mmm has 0-value
12:466 00:001 OC: Prelinked injection RestrictEvents.kext (V1.0.8 | RestrictEvents.kext) - Invalid Parameter
```

You need masking support from a newer Lilu commit (June 22nd):
* https://github.com/acidanthera/Lilu/commit/be0a2f6cddddda0673207e327529adc3b405b94a

**Comment by fabiosun** [comment]
[Archive.zip](https://github.com/acidanthera/bugtracker/files/9025160/Archive.zip)
![image](https://user-images.githubusercontent.com/6358373/176825808-cec85a15-8d9e-4965-877a-53dae33bbf51.png)
```
Last login: Fri Jul  1 06:38:50 on ttys000
fabio@Mac-Pro ~ % kextstat | grep -v com.apple
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
   54    3 0                  0x8a000    0x8a000    as.vit9696.Lilu (1.6.1) 5B4553DB-ABB0-3B29-9F88-8FC0B8EE4E6F <9 7 6 3 2 1>
   55    0 0                  0x10000    0x10000    as.vit9696.RestrictEvents (1.0.8) 65EA8957-DF92-33D8-9737-FBE0631BA271 <54 9 7 6 3 2 1>
   56    0 0                  0x20000    0x20000    wtf.spinach.AMDRyzenCPUPowerManagement (0.7) 10AE6854-47D8-3FE6-B1D3-66937EF615EF <54 17 13 9 7 6 3 2 1>
   63    0 0                  0x1a000    0x1a000    as.vit9696.VirtualSMC (1.3.0) 1A588100-2B4E-367C-A317-7D697730B3A3 <54 16 9 7 6 3 1>
fabio@Mac-Pro ~ % 
```
[opencore-2022-07-01-042939.txt](https://github.com/acidanthera/bugtracker/files/9025163/opencore-2022-07-01-042939.txt)

@khronokernel Could you explain this?
first boot today of my system

**Comment by fabiosun** [comment]
[Lilu_1.6.1_22.0.txt](https://github.com/acidanthera/bugtracker/files/9027679/Lilu_1.6.1_22.0.txt)
problem is a bit complicated, with lilu used as suggested i have problem in cold boot
sometime it resets before login step
and then it boots fine and it shows Unknown as CPU
I restart system via apple menu and then system show my exact cpu

With previous lilu version (and RestrictEvents) i have always exact name a zero problem to boot
Thank you for you attention Angel :)

**Comment by fabiosun** [comment]
[Lilu_1.6.1_22.0.txt](https://github.com/acidanthera/bugtracker/files/9027679/Lilu_1.6.1_22.0.txt)
problem is a bit complicated, with lilu used as suggested i have problem in cold boot
sometime it resets before login step
and then it boots fine and it shows Unknown as CPU
I restart system via apple menu and then system show my exact cpu

With previous lilu version (and RestrictEvents) i have always exact name a zero problem to boot
Thank you for you attention Angel :)

**Comment by PMheart** [comment]
```
RestrictEvents       rev: @ (DBG) read revcpuname from default
RestrictEvents       rev: @ (DBG) requested to patch CPU name to AMD Ryzen Threadripper 3970X 32-Core Processor 
```

```
RestrictEvents       rev: @ (DBG) calculated 32 cores in pkg 0 amd 1
RestrictEvents       rev: @ (DBG) chosen 28-Core Intel Xeon W patch for 32 core CPU
```

```
RestrictEvents       rev: @ (DBG) patched core count in AppleSystemInfo
RestrictEvents       rev: @ (DBG) patched 28-Core Intel Xeon W in AppleSystemInfo
```

Log is fine. I am not sure whether we need to patch something else, as now the panel is in the new AboutExtension. I will look into this.

**Comment by RyzenDew** [comment]
i had this issue when using gensmbios to make my smbios info and to fix it I had to use opencore configurator instead which works perfect.

**Comment by fabiosun** [comment]
I do not use gensmbios and my SMBIOS works perfectly with other lilu/restrictevents kexts combination

**Comment by fabiosun** [comment]
@PMheart thank you
Latest 2022.07 (all release version for lilu,VirtualSMC and RestrictEvents) is working well in my rig
Later I will try with 2022.07 debug release to produce debug txt for lilu and others
