### ISSUE TITLE
The Return Of The Dark Screen

### ISSUE THREAD

**Issue by tallinn1960** [acidanthera/bugtracker#2066]
All the recommendations in the supplied textfield suck as they are severely outdated. That is a bug on its own, however, I want to report another issue.

With Opencore 0.8.1 and most recent versions of lilu and whatevergreen booting into macOS Ventura developer beta 2 with a for any other OS (like Monterey) working setup runs into a "No display signal". This is with an AMD 5700 and "agpdmod=pikera -wegbeta=true" as bootargs. Whatevergreen is 1.5.9, Lilu is 1.6.0.

**Comment by vandroiy2013** [comment]
Where the hell did you get "-wegbeta=true" bootarg?
For Lilu 1.6.0 and WhateverGreen 1.5.9 you only need "-lilubetaall" bootarg or use Lilu 1.6.1 and WhateverGreen 1.6.0 from master without it.

**Comment by tallinn1960** [comment]
Actually it was just -wegbeta and I got that from whatevergreens readme.md. However -lilubetaall works. Thank you.

**Comment by andreszerocross** [comment]
> Actually it was just -wegbeta and I got that from whatevergreens readme.md. However -lilubetaall works. Thank you.

WhateverGreen is plugin of Lilu.kext,

So if you use -wegbeta but Lilu.kext is not loaded, then it will useless. Lilu need -lilubeta but for all plugin (applealc, whatevergreen, virtualsmc, and other) to be loaded then you must use "-lilubetaall"
