### ISSUE TITLE
Dwell clicking support in OpenCore

### ISSUE THREAD

**Issue by mhaeuser** [acidanthera/bugtracker#2067]
It appears some people use dwell-clicking in-OS and could benefit from it pre-boot. While drag&drop often seems to be supported by these solutions, there is nothing really using this pre-boot that we're aware of. Right-clicking also isn't really a thing at the moment. Hence, I propose the following:

- There is a configurable radius `R`, within which a pointer is considered "stable" when remaining there for a time `T`. `T` is reset once leaving the radius and a new origin is used for determining the new `T`. We might opt to refine the origin with very basic heuristics, but this is a separate discussion.
- When `T` reaches a single click threshold `C`, we send a left click.
- When `T` reaches a double click threshold `D`, we send a left double click.
- `R`, `C`, and `D` should be configurable via config.plist as part of this optional feature --- `R` in pixels (it would be scaled with UIScale), and `C` and `D` in milliseconds.
- If `C` or `D` are 0, they are disabled, respectively. E.g., someone might not need double clicks, or it might be easier to only have double clicks (OpenCanopy is very basic after all).
- All of this should happen in our AppleEvent implementation, so this behaviour would be consistent for both OpenCanopy and the pre-boot FileVault 2 interface. However, there is no supported on-screen keyboard that could be used for entering the FileVault 2 password. This is out of scope and could be a separate issue, if urgently required. This behaviour would not apply to any UEFI applications that do not use the AppleEvent protocol.

For knowledgable people on this subject, please check:
- Whether this behaviour is intuitive (enough).
- Whether this behaviour is (somewhat) consistent with common solutions.
- Whether this behaviour would work out if right clicking and drag&drop were considered to be added. I frankly have no idea what this would look like.
- Whether there are other UEFI applications that do not use the AppleEvent protocol, but would be useful to have support for. In this case, the implementation could be moved to the general UEFI pointer protocol, but this would be significantly more effort. I'd likely still be possible to broaden the support on demand at a later point in time.

This would allow users who enable the optional feature to use left single and double clicks in OpenCanopy, e.g., to choose a different OS.

**Comment by mhaeuser** [comment]
Random thought: **If** ever needed (will not be implemented without explicit demand and examples of where that is needed), the different modes could be implemented with hot corners. Maybe audio feedback would be nice to have for the events.

**Comment by mikebeaton** [comment]
Never played with it before, but from a quick test run, dwell usability seems pretty linked to having a dwell countdown cursor to allow you to see what is going on? (That said, I appreciate it might potentially be usable, and better than without dwell at all, for people who require it, even without that.)

The stable radius idea seems right (seems to match how it behaves in-OS). The idea of single-click followed by double-click is pretty OpenCanopy specific, but sounds like it would make sense there.

If you get to the stage where you need right-clicking and drag and drop as well, I think you'd need something like the dwell menu that macOS has:

<img width="221" alt="Screenshot 2022-07-03 at 18 06 32" src="https://user-images.githubusercontent.com/11946605/177050035-3c21a807-ddfc-4771-9296-11b648bc8440.png">

**Comment by mhaeuser** [comment]
@mikebeaton Tyvm. I think hot corners are better because we might not own the GUI (e.g., FV2). Of course a hot corner could summon a menu, but that would be a significant effort. For now, this is probably fine.

I also wonder just how crucial feedback is, like a trigger sound or that timeout circle.

**Comment by 5T33Z0** [comment]
I wouldn't need and use such a feature but maybe it is helpful as an accessibilty option for handicaped people.

**Comment by fabiosun** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/6358373/177081110-678bcad4-18cd-4d74-9ccb-1d5f6d6f4828.png">

In the world there are many people who suffer from degenerative diseases, who at some point can no longer move, they can move their head or eyes.
There are USB pointers that associate with these movements and allow the use of the head and eyes as if they were a mouse

Having made this superficial premise and apologizing in advance for not having technical feedback to give, I asked downloadfritz privately if it was possible in Opencore to have such a feature at the bootmenu level
So that a user who has these difficulties can choose and start different systems such as Linux, Windows or OSX
The problem is the click and, DwellClick is a cross-platform solution used

As a non-expert, it seemed much easier to associate the movement of the mouse with the cursor keys of the keyboard and make sure that the timeout option that we already have in OpenCore does not stop after a movement of the cursors or the mouse
By activating the focus on the selected icon / system, the countdown could continue until the automatic start of the selected system

Anyway, thank you for your attention

**Comment by mhaeuser** [comment]
@fabiosun Can you have this tested, please?

**Comment by perez987** [comment]
@mhaeuser 
Excellent work! I'll try it asap and comment. Thanks.

**Comment by fabiosun** [comment]
> @fabiosun Can you have this tested, please?

Thank you
I have forwarded this to the interested user
Thank you again for your kindness and effort in this task

**Comment by perez987** [comment]
@mhaeuser 
I don't have reduced mobility but I have tried this new feature.

Dwell works fine, a not very short times are needed and of course timeout can't be shorter. I have set PointerDwellClickTimeout 5000 and PointerDwellDoubleClickTimeout 10000 with radius 256. It works fine with system entries, UEFI Shell, restart and halt buttons.

Some kind of feedback (color circle that fills in as time goes by) would be welcome but I guess the implementation is very complex.

I have a comment. The process is: I see the picker >> I move the mouse over an entry >> the pointer stays held on the entry 5" until it is selected (until I see the selector on this entry) >> the pointer stays held another 5" until the entry starts (until click is emitted).
Do you have the same experience? That period of time with the pointer over the entry until it is selected at which point it appears to start counting time again.
Tell me if you need any other test.

And thanks for the great work

**Comment by mhaeuser** [comment]
@perez987 Thanks for testing.

Visual indicator: I originally wanted something like this, but I’m too short on time right now and for pre-boot, this should suffice. Even if a visual indicator was added, it would only apply to OpenCanopy and not FV2, so it’d even be a bit inconsistent.

Timeout: The timer does not reset for double-click, i.e., when hovering a boot entry, it should be selected (clicked) after 5 seconds and booted (double-clicked) after 10 seconds, which seems to be what’s happening. You can of course also disable single-clicking altogether and only use double-clicking (I’m not positive how this behaves in FV2).

**Comment by perez987** [comment]
@mhaeuser 
Ok, I understand now and you’re right, this is what’s happening. I don’t know why didn't I realize it myself.
Then, from what I have seen so far this works well, as you expect it to work. I haven't seen anything anomalous.
True test indeed must be done by people with very limited mobility. 
Congratulations and thanks for you work.

**Comment by Real-Nightcrawler** [comment]
Hello, I am the one who requested this feature. I had no possibility to
test (moreover I have not yet installed any macOS but only the Windows 11 I
used to configure the PC and check the correct operation of the PC
components.
I was not able to test because I was in the hospital for more than 6
months.
When I'll be able to see you wonderful work

Il giorno dom 23 ott 2022 alle ore 18:45 Marvin Häuser <
***@***.***> ha scritto:
