### ISSUE TITLE
Some mainboard has Nvidia HDMI Audio issue

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#2068]
hello. Recently I upgraded from my old Skylake system to an Alderlake system.

As for the current graphics card, Nvidia GeForce GT 710, which was used in the existing Skylake system, was used in the Alder Lake system. In the Skylake system, ASUS B150M mainboard has the Realtek 887 codec and GK208 HDMI audio worked well together. But after upgrading to the Alderlake system,
If you put a layout number in IOService:/AppleACPIPlatformExpert/PC00@0/AppleACPIPCI/HDEF@1F,3, GK208 HDMI audio automatically disappears and only Realtek 897 codec works.

Is there a solution to use Realtek 897 codec and GK208 HDMI audio together?

Attach files for related issues
ioreg, lilu log, screenshot
[HDMI Audio Issue.zip](https://github.com/acidanthera/bugtracker/files/9034956/HDMI.Audio.Issue.zip)

system specs
1. CPU : i5-12400
2. MB : GIGABYTE B660M AORUS ELITE DDR4
3. CODEC: REALTEK ALC897
4. GPU : NVIDIA Geforce GT 710 2GB

Thank you in advance.

**Comment by Core-i99** [comment]
Project:audio is for the audio in OC I think, project:alc is for applealc issues.

**Comment by Sher1ocks** [comment]
more info.
[AppleHDAController-12.4 binary.zip](https://github.com/acidanthera/bugtracker/files/9055377/AppleHDAController-12.4.binary.zip)

i can't search to find hex value for nvidia hdmi audio
![스크린샷 2022-07-06 오후 11 00 00](https://user-images.githubusercontent.com/2107738/177568066-beec0f40-c859-4b3f-83dc-bf7dafbbddbc.png)

intel 7ad0 patch is good.
![스크린샷 2022-07-06 오후 11 01 40](https://user-images.githubusercontent.com/2107738/177568499-c64a80eb-b8eb-4432-bf22-739986d6515a.png)

**Comment by PMheart** [comment]
`4E564441` is not even available in 10.13 AppleHDAController. I tried searching this sequence in AppleHDA, and it is still not available.

**Comment by PMheart** [comment]
Just an idea for testing - Could you please try this patch:

Find: `0E 00 00 BE 02 00 00 00 48 89 DF`
Repl: `0E 00 00 B8 0F 0E 00 00 EB 06 90`

i.e. Same find pattern, but replace it with the assignment of NVIDIA GK208 HDMI controller ID.

**Comment by Sher1ocks** [comment]
> Hmm, right. Please try disabling the patch for Intel; I would like to confirm whether NV works at least.

okay. thanks! i will report

**Comment by Sher1ocks** [comment]
> Hmm, right. Please try disabling the patch for Intel; I would like to confirm whether NV works at least.

not work. i can't get hdmi audio

**Comment by PMheart** [comment]
@vit9696 told me that Apple removed the support for NV HDMI controllers. Thus, there is no way to fix it.

Closing as wontfix.

**Comment by Sher1ocks** [comment]
@PMheart 
i got skylake system log and ioreg with nvidia geforce gt 710 hdmi audio
here. we can see difference and hint
[B150M_GT710 HDMI AUDIO.zip](https://github.com/acidanthera/bugtracker/files/9063453/B150M_GT710.HDMI.AUDIO.zip)

**Comment by Sher1ocks** [comment]
FIXED!
Try to add 
FakePCIID
FakePCIID_Intel_HDMI_Audio
70A10000 <= skylake

and add device-id 70A10000  in PciRoot(0x0)/Pci(0x1F,0x3)
EnjoY^^


![스크린샷 2022-07-08 오후 10 11 35](https://user-images.githubusercontent.com/2107738/177998576-97000532-e0e8-4859-8f69-a977f35aadf6.png)
![스크린샷 2022-07-08 오후 10 12 04](https://user-images.githubusercontent.com/2107738/177998666-24ada4ff-0f9a-4cc8-87b8-f9b7333b7201.png)
![스크린샷 2022-07-08 오후 10 12 23](https://user-images.githubusercontent.com/2107738/177998731-35c541cd-775e-4643-bad0-f7c0794376db.png)
