### ISSUE TITLE
FeatureUnlock (OCLP) - Night Shift only shows up in "Displays" option in menu bar

### ISSUE THREAD

**Issue by tejasraman** [acidanthera/bugtracker#2069]
In OCLP, my FeatureUnlock.kext does not enable NightShift in settings. It is possible to click it in the Displays icon in the menu bar:

https://user-images.githubusercontent.com/96961804/177058961-314b3ead-6397-46e2-b56c-2b2123c9482d.mp4

However, it does not show up in Settings:
![Screen Shot 2022-07-03 at 4 16 50 PM](https://user-images.githubusercontent.com/96961804/177058983-8efde10d-4b1e-4bf2-a1d0-f4a4607c5fc8.png)

Here is a zipped version of my EFI:
[EFI.zip](https://github.com/acidanthera/bugtracker/files/9035579/EFI.zip)

I am using FeatureUnlock 1.0.8 (latest). Do you know why?

**Comment by khronokernel** [comment]
Race Condition in macOS with properly presenting model-specific properties:
* https://github.com/cdf/NightShiftEnabler/issues/6

Bug on native machines as well, nothing to be done besides replicate on a native model and file feedback with Apple

**Comment by tejasraman** [comment]
Would updating macOS fix this _weirdness_?

**Comment by tejasraman** [comment]
Just went back to Catalina, Bigsur was slower anyway, and no night shift and GPU acceleration glitches were a deal breaker for me
