### ISSUE TITLE
[AppleALC] OSUnserializeXML syntax error

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2070]
Updating to AppleALC v1.7.3 release leads to the following kernel panic:

![image](https://user-images.githubusercontent.com/17933708/177207750-a2dcddd8-19e4-4048-a098-94ba30766215.png)

The code that probably leads to this error is the following segment in AppleALC Info.plist:

```
<dict>
					<key>AFGLowPowerState</key>
					<data>
					AwAAAA==
					</data>
					<key>Codec</key>
					<string>ALC269</string>
					<key>CodecID</key>
					<integer>283902569</integer>
					<key>Comment</key>
					<string>Custom ALC269 for Chuwi CoreBox by Luca91</string>
					<key>ConfigData</key>
					<data>
					AVccHwFXHRABVx4hAVcfBAFXDAIBhxwgAYcd
					EAGHHoEBhx8E
					</data>
					<key>FuncGroup</key>
					<integer>1</integer>
					<key>LayoutID</key>
					<integer>91</integer>
					<key>WakeVerbReinit</key>
					<true/>
				</dict>
```

I tested the following commits:

- acidanthera/AppleALC@4aae6c5d1efe5432d3fce198572e1084ec51bae3
- acidanthera/AppleALC@3f9105394cbfb6ea45f4ec3ae507fa115506a1b0
- list currently in update

Please note that using AppleALC 1.7.2 doesn't lead to this KP

**Comment by khronokernel** [comment]
Found the issue, kernel side doesn't support the usage of `real` keys:
* https://github.com/acidanthera/AppleALC/blame/master/Resources/PinConfigs.kext/Contents/Info.plist#L1171

```xml
					<key>AFGLowPowerState</key>
					<data>AwAAAA==</data>
					<key>Codec</key>
					<string>Custom by fuzzyrock for ALC235 Lenovo A340-22IWL</string>
					<key>CodecID</key>
					<real>283902517</real>
					<key>ConfigData</key>
					<data>ASccMAEnHQEBJx6mAScfkAGXHEABlx0QAZceoQGXHwIBtxwQAbcdAQG3HhcBtx+QAbcMAgIXHCACFx0QAhceIQIXHwICFwwC</data>
					<key>FuncGroup</key>
					<integer>1</integer>
					<key>LayoutID</key>
					<integer>33</integer>
					<key>WakeConfigData</key>
					<data>AbcMAg==</data>
					<key>WakeVerbReinit</key>
					<true/>
```

**Comment by khronokernel** [comment]
Resolved:
* https://github.com/acidanthera/AppleALC/commit/518b9d4673031a7bf6f2174e6f0ae5e1945b9bd5

However unsure whether a re-release should be done to account for his. CC @vandroiy2013 @vit9696

**Comment by vit9696** [comment]
Thank you! Should just re-release. I dropped the release and tag.

**Comment by vandroiy2013** [comment]
Thanks. Several minutes. New release is already on the way

**Comment by dreamwhite** [comment]
Thank you so much. I tested quickly by find-n-replacing `real` with `integer`. Can confirm that it works!

**Comment by 5T33Z0** [comment]
Seems that duplicating an entry in the PinConfig's info.plist with Xcode causes the change from `integer` to `real`: https://github.com/5T33Z0/OC-Little-Translated/issues/42#issuecomment-1168947870
