### ISSUE TITLE
Allow running tools with nvram isolation disabled

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2071]
Hi, I know that probably that this isn't the right place where to ask but I'm having issues booting RU.efi via OpenCore (both via GUI and OpenShell).

For those who don't know what RU.efi is, in more or less it's an alternative to `modGRUBShell.efi` for editing BIOS offsets (e.g. CFG Lock unlocking etc.).
What I'm noticing is that when I boot RU.efi as a standalone `BOOTx64.efi` it correctly detects UEFI variable names; when it's booted via OpenCore only two variable names (both called `StdDefaults`) are shown.

Below a screenshot:

![photo_2022-07-04 23 09 27](https://user-images.githubusercontent.com/17933708/177216724-6eacfb4b-e6aa-4997-9265-16356a3551d9.jpeg)

Is this thing somehow related to `EnableWriteUnprotector` (or `SyncRuntimePermissions` and `RebuildAppleMemoryMap`) quirks or it's another story?
Thank you so much and have a nice day

**Comment by dreamwhite** [comment]
# Update

It seems like @vit9696 already faced up this problem via issue #731 but I'm too stupid to find that tool in OpenCorePkg. Where can I use it? Additionally, can a `FwRuntimeServices` quirk be added to Tools so we can manually restrict access to FwRuntimeServices for each tool?

**Comment by dreamwhite** [comment]
# Update 2

Managed to compile FwRuntime.efi tool to disable RuntimeServices.
Attached a version of the tool: [FwRuntime.efi.zip](https://github.com/acidanthera/bugtracker/files/9042343/FwRuntime.efi.zip)

Usage, from a OpenShell.efi booted via OpenCore is `FwRuntime.efi disable` to disable RuntimeServices, and `FwRuntime.efi restore` to re enable it.

`FwRuntime.efi disable` and after `RU.efi`:

![2022-07-05 1 42 28 AM](https://user-images.githubusercontent.com/17933708/177225820-ffd5943f-c3b7-443a-ba31-f93e636d0dc3.jpg)

`FwRuntime.efi restore` and after `RU.efi`:

![2022-07-05 1 42 34 AM](https://user-images.githubusercontent.com/17933708/177225841-b033a00f-b888-4d98-9174-eb4ba01804dc.jpg)

Seems like it's working but I'm deep investigating on a way to include a boolean value `RuntimeServices` onto OpenCore to avoid using the tool.

**Comment by vit9696** [comment]
The current name of the tool is OpenControl.efi. It is bundled with OpenCore releases. Please use this instead of trying something legacy. Refer to (PDF) documentation for more details.

**Comment by dreamwhite** [comment]
> The current name of the tool is OpenControl.efi. It is bundled with OpenCore releases. Please use this instead of trying something legacy. Refer to (PDF) documentation for more details.

Ouch! Sorry if I haven't noticed it yet. I tested it right now and it seems working.
I have two more questions:

- What about instead implementing a boolean option that lets user manually restrict NVRAM access to certain tools?
- Is there any specific reason why OpenCore can't boot `RU.efi` despite `RealPath` is enabled? Booting it through `OpenShell` works, so I think it's rather an issue of OpenCore itself

**Comment by mhaeuser** [comment]
@vit9696 Probably yes.

**Comment by PMheart** [comment]
I am ok with that too.

**Comment by mikebeaton** [comment]
Is the suggestion for a per-tool boolean config? If so, I believe sounds sensible, and useful as above. (FWIW!)

**Comment by dreamwhite** [comment]
> Is the suggestion for a per-tool boolean config? If so, I believe sounds sensible, and useful as above.

Exactly. It may sound stupid but in my opinion restricting the access for certain tools it's way better than choosing between "all or nothing" as actually OpenControl does

**Comment by vit9696** [comment]
Yes, must be per-tool of course.

**Comment by mikebeaton** [comment]
Closed by https://github.com/acidanthera/OpenCorePkg/commit/fa7477066c5acb0aa3fdc2e35d87ea0a13e1512d

**Comment by mikebeaton** [comment]
Option renamed (after team discussion!) by https://github.com/acidanthera/OpenCorePkg/commit/b3f2033d200bb8bf114baad861bc7a1a51ed8259
