### ISSUE TITLE
Unable to Boot Ventura Beta3

### ISSUE THREAD

**Issue by wqhqq1** [acidanthera/bugtracker#2076]
Using latest build from dp3-inject-fix branch, but stuck with strange behavior.
![IMG_4662](https://user-images.githubusercontent.com/53130008/177723756-12a033ca-d148-44d3-9ee5-060ad57baec1.jpeg)

**Comment by PMheart** [comment]
Hello! We are still working on it. Meanwhile, please do not upgrade to 10.13 b3.

And I would like to remind again, that this is not a forum for support.
