### ISSUE TITLE
[SIP] Issues with Software Updates

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2078]
I'm encountering issues with SysPref pane Software Updates. It hangs on `Checking for updates...`.

My HW:

- CPU: i5-8250U
- GPU: UHD Graphics 620
- SSD: WD Black SN750 500GB
- MOBO: Dell Inspiron 5370
- OC version: 0.8.2 official release
- SMBIOS: `MacBookPro15,2`

`csrutil status` reports SIP is enabled as well as my `config.plist` is correctly configured to drop `csr-active-config` and add it:

![image](https://user-images.githubusercontent.com/17933708/177982341-49bfc8b7-0bd6-47f7-8dcd-c69049f36124.png)

- `NVRAM/Add`: [line 823](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/blob/master/EFI/OC/config.plist#L823=)
- `NVRAM/Delete`: [line 839](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/blob/master/EFI/OC/config.plist#L839=)

Is this a known issue or I missed out something I didn't knew before? Can `j185` `SecureBootModel` interfere somehow?
Greetings
dreamwhite

**Comment by mikebeaton** [comment]
This sounds like a support/configuration issue, not a bug with OpenCore.

You haven't mentioned the version of macOS - if it's Ventura, please just wait for it to be supported, it is not yet.

You also haven't mentioned if the issue is really a hang (i.e. the app in question, or the whole system, hangs and will not respond to any input) or if it just sits checking for a long time (but can still be moved, closed, etc.), which is normal and up to macOS not OpenCore.

**Comment by dreamwhite** [comment]
> This sounds like a support/configuration issue, not a bug with OpenCore.

Ouch sorry!

> You haven't mentioned the version of macOS - if it's Ventura, please just wait for it to be supported, it is not yet.
I'm on Monterey 12.4
 
> You also haven't mentioned if the issue is really a hang (i.e. the app in question, or the whole system, hangs and will not respond to any input) or if it just sits checking for a long time (but can still be moved, closed, etc.), which is normal and up to macOS not OpenCore.

Seems like restoring `Default` as `SecureBootModel` fixed the issue. Wasn't `SecureBootModel` independent from the chosen SMBIOS?

**Comment by perez987** [comment]
@dreamwhite >> `SMBIOS model must match SecureBootModel`

But only when SecureBootModel is Default.

**Comment by perez987** [comment]
@dreamwhite 
As far as I know, SecureBootModel picks SMBIOS model when it has Default as value.
