### ISSUE TITLE
Feature suggestion: Fake audio device id for HDMI Audio in AppleALC

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#2079]
hello
I recently reported a problem with HDMI audio, and I am writing to suggest a new function.
https://github.com/acidanthera/bugtracker/issues/2068

System Information (Alder Lake)
- CPU: i5-12400
- Motherboard : GIGABYTE B660M AORUS ELITE D4
- Audio Codec : Realtek ALC897 (7ad0)
- Graphics Card: Nvidia Geforce GT 710

Previous system information (Skylake)
- CPU: i3-6100
- Motherboard: ASUS B150M IBORA M.2
- Audio codec: Realtek ALC887 (70a1)
- Graphics Card: Nvidia Geforce GT 710

Recently, in the Skylake system, the above change was made, but in the Skylake system, HDMI audio worked without any additional patch.

As a result of analyzing the difference, it was confirmed that HDMI audio works without an additional patch from AppleHDAController if the audio device ID is 70a1.

To fake the device ID
FakePCIID.kext, FakePCIID_Intel_HDMI_Audio.kext
As a result of injecting device ID 70a1, HDMI Audio was recognized normally in the Alder Lake system.

However, FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext are fine at boot time, but a forced restart occurs with a kernel panic when using functions such as random restart, system shutdown, and logout or after a certain point.
example
https://www.reddit.com/r/hackintosh/comments/s471d5/hdmi_audio_not_working_comet_lake_monterey/

with these alternatives
Like the more stable fakebrcm function used by AirportBrcmFixup
Can we add functionality to AppleALC?
https://github.com/acidanthera/AirportBrcmFixup/blob/master/AirportBrcmFixup/kern_fakebrcm.cpp

Or is there a way to essentially trick the Skylake Intel audio device into enabling AppleHDAHDMI_DPDRiver?

Thank you in advance.

**Comment by vit9696** [comment]
In my opinion, it is much easier to just patch the driver than to try to dance with the device register virtualisation. As long as there is no case where it is insufficient, I would opt out doing this.
