### ISSUE TITLE
Stuck at `apfs_module_start:2868: load: com.apple.filesystem.apfs, v2140.0.0, apfs-2140.0.0.0.9, 2022/06/30` after trying to upgrade to macOS Ventura (13) beta 3

### ISSUE THREAD

**Issue by notAperson535** [acidanthera/bugtracker#2081]
After I have tried to upgrade to macOS Ventura beta 3, I get stuck on this line
![apfs_module_start error](https://user-images.githubusercontent.com/95918679/178104091-ac9a7164-7c0b-472d-a833-359271429ac2.jpg)

The thing is, Ventura beta 1 and 2 worked perfectly fine, and this has never happened before.

I am running Comet Lake CPU and a Lenovo Thinkpad X1 Carbon 7th gen (20R1).

[Attached is my EFI folder.](https://drive.google.com/file/d/1ENzEGPg84fKLMIBlq-qn1CE-fdS7vjsn/view?usp=sharing)

If you need more info, please tell me and I will add it. I did not think I would need opencore or lilu logs because this is an issue after the bootloader.

**Comment by khronokernel** [comment]
This looks to be support/configuration issue, not a bug with OpenCore, etc. Use forums for support, reminder Ventura is still a developer beta
