### ISSUE TITLE
WindowServer crash after waking up from Sleep.

### ISSUE THREAD

**Issue by arifzeeshan** [acidanthera/bugtracker#2083]
My System always crashes with a Black screen and a cursor after waking up- Here's the log file and EFI folder. I've checked all the issues and configs but can't figure it out.

[WindowServer-2022-07-13-025104.log](https://github.com/acidanthera/bugtracker/files/9096976/WindowServer-2022-07-13-025104.log)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/9097010/EFI.zip)

**Comment by khronokernel** [comment]
Use forums for troubleshooting
