### ISSUE TITLE
WhateverGreen - Laptop built-in display black screen when HDMI plugged-in

### ISSUE THREAD

**Issue by ciccio-90** [acidanthera/bugtracker#2089]
Hi,
 
I am having a problem with the display of my laptop when it is connected in HDMI to an external monitor.
Basically at boot after the apple logo the laptop display turns black and does not show any content.
I must say that the external monitor works perfectly both audio and video.

You can find my EFI folder here:
https://github.com/ciccio-90/Lenovo_V110-15ISK_Hackintosh_OpenCore_macOS_Monterey

Moreover I attached my IOReg file.
[MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/9122842/MacBook.Pro.ioreg.zip)

**Comment by vandroiy2013** [comment]
Hi. Bugtracker is not a support forum. Thanks.

**Comment by ciccio-90** [comment]
I have already tried to ask for help on the forums but without luck.
https://www.insanelymac.com/forum/topic/348676-laptop-built-in-display-black-screen-when-hdmi-plugged-in/

**Comment by F-19-F** [comment]
> @vandroiy2013 I have already tried to ask for help on the forums but without luck. https://www.insanelymac.com/forum/topic/348676-laptop-built-in-display-black-screen-when-hdmi-plugged-in/

did you fix it ? I hava the same issue

**Comment by ciccio-90** [comment]
> > @vandroiy2013 I have already tried to ask for help on the forums but without luck. https://www.insanelymac.com/forum/topic/348676-laptop-built-in-display-black-screen-when-hdmi-plugged-in/
> 
> did you fix it ? I hava the same issue

Unfortunately not!
