### ISSUE TITLE
OpenCore 0.8.2, Radeon HD 7750 (with UEFI GOP) weird artifacting / no login screen in Monterey

### ISSUE THREAD

**Issue by tejasraman** [acidanthera/bugtracker#2092]
OpenCore 0.8.2 - AMD A10-6800K, VisionTek HD 7750 (GOP Flashed)
This build works well under Big Sur, but under Monterey, it boots to a screen with artifacts. Sounds work and I was able to move the cursor. I have tried BS and Monterey multiple times, but the results remain the same: BS works, Monterey does not.

[EFI.zip](https://github.com/acidanthera/bugtracker/files/9172870/EFI.zip)

Why?

My issue looks similar to this: [Reddit - Hackintosh installed on AMD FX but got screen artifact after install and first boot](https://www.reddit.com/r/hackintosh/comments/qm65by/hackintosh_installed_on_amd_fx_system_but_got/)

The person in this post has an R7 250 (which is a Cape Verde PRO like the 7750 - they're literally the same card). A FakeID did not fix it. Is this a whatevergreen bug? An opencore bug? What? I redid the config based on the guide, that changes absolutely nothing. I read Configuration.pdf - **nothing.**

Would dev builds help? Considering the Reddit thread with this issue (the only other reference to this issue I could find) is 9 months old, I'm doubtful a new dev build of OC/WEG would work. (I might be wrong, if an issue like this has been fixed recently tell me. I'll check)

I tried to spoof my GPU (HD 7750) to an HD 7770/R7 250X (Cape Verde XT). I can send you the EFI with the SSDT for FakeID or the DSL file.

(EDIT - I'm sorry, I didn't provide all the info. If I clean install Monterey, I can set it up and it works, but I can't log out and I get the artifacting again on the next boot. If you want a picture I'll send one.)

**Comment by tejasraman** [comment]
@khronokernel why?

**Comment by Andrey1970AppleLife** [comment]
In any we don't support AMD CPU. Use forums for support.

**Comment by tejasraman** [comment]
Tried -rad24, didn't fix anything

**Comment by tejasraman** [comment]
Asked on insanelymac, sorry
