### ISSUE TITLE
Kernel panic when using NVMeFix.kext

### ISSUE THREAD

**Issue by justinkb** [acidanthera/bugtracker#2093]
The panic during the 12.4->12.5 upgrade happened with the latest released builds of OC and Kexts. For the 12.5->13.0 Beta 3 upgrade panic, I used the latest prerelease builds as of a few hours ago (RELEASE builds), because I needed the latest Lilu for the symbol fix.

The panics don't cause the install to fail, but do cause a reboot after which the apple "warning your OS crashed" screen shows up. Pressing return after that causes the install to continue and function properly.

Didn't get kernel panic report for the 12.4->12.5 upgrade, but I do have one for the 13.0 Beta 3 upgrade

```
    panic(cpu 6 caller 0xffffff80105e6ef4): [default.kalloc.16]: element modified after free (off:8, val:0x0000000000000002, sz:16, ptr:0xffffff9a0e35b790)
        8: 0x0000000000000002
    Panicked task 0xffffff86e004d218: 126 threads: pid 0: kernel_task
    Backtrace (CPU 6), panicked thread: 0xffffff95430d2b20, Frame : Return Address
    0xffffffffffeb3100 : 0xffffff800fdf892d mach_kernel : _handle_debugger_trap + 0x4ad
    0xffffffffffeb3150 : 0xffffff800ff64a26 mach_kernel : _kdp_i386_trap + 0x116
    0xffffffffffeb3190 : 0xffffff800ff53cb0 mach_kernel : _kernel_trap + 0x3e0
    0xffffffffffeb31e0 : 0xffffff800fd93951 mach_kernel : _return_from_trap + 0xc1
    0xffffffffffeb3200 : 0xffffff800fdf8c0d mach_kernel : _DebuggerTrapWithState + 0x5d
    0xffffffffffeb32f0 : 0xffffff800fdf82b9 mach_kernel : _panic_trap_to_debugger + 0x1a9
    0xffffffffffeb3350 : 0xffffff80105e255b mach_kernel : _panic + 0x84
    0xffffffffffeb3440 : 0xffffff80105e6ef4 mach_kernel : ___queue_element_linkage_invalid + 0x2703
    0xffffffffffeb38b0 : 0xffffff800fe68322 mach_kernel : _workload_config_available + 0x42c2
    0xffffffffffeb3900 : 0xffffff800fe076a1 mach_kernel : _ipc_thread_port_unpin + 0x2c1
    0xffffffffffeb3920 : 0xffffff80104d3ee0 mach_kernel : _IOMalloc + 0x20
    0xffffffffffeb3940 : 0xffffff8011bbd48c com.apple.driver.AirPort.BrcmNIC : _osl_malloc + 0x30
    0xffffffffffeb3990 : 0xffffff8011bbd663 com.apple.driver.AirPort.BrcmNIC : _osl_mallocz + 0xf
    0xffffffffffeb39b0 : 0xffffff8011c986c6 com.apple.driver.AirPort.BrcmNIC : _wlc_bmac_attach + 0x1cc8
    0xffffffffffeb3ac0 : 0xffffff8011cb566e com.apple.driver.AirPort.BrcmNIC : _wlc_attach + 0x4aa
    0xffffffffffeb3b80 : 0xffffff8011bca2c2 com.apple.driver.AirPort.BrcmNIC : __ZN15AirPort_BrcmNIC8wlcStartEv + 0x19a
    0xffffffffffeb3c50 : 0xffffff8011bc8846 com.apple.driver.AirPort.BrcmNIC : __ZN15AirPort_BrcmNIC10startGatedEP9IOService + 0x444
    0xffffffffffeb3cc0 : 0xffffff8011bc83ef com.apple.driver.AirPort.BrcmNIC : __ZN15AirPort_BrcmNIC10_doCommandEP8OSObjectPvS2_S2_S2_ + 0x4d
    0xffffffffffeb3cf0 : 0xffffff80105187f4 mach_kernel : __ZN13IOCommandGate9runActionEPFiP8OSObjectPvS2_S2_S2_ES2_S2_S2_S2_ + 0xb4
    0xffffffffffeb3d50 : 0xffffff8011bc952e com.apple.driver.AirPort.BrcmNIC : __ZN15AirPort_BrcmNIC5startEP9IOService + 0x3dc
    0xffffffffffeb3dc0 : 0xffffff80104eb6c2 mach_kernel : __ZN9IOService14startCandidateEPS_ + 0xd2
    0xffffffffffeb3e20 : 0xffffff80104eb1aa mach_kernel : __ZN9IOService15probeCandidatesEP12OSOrderedSet + 0xdaa
    0xffffffffffeb3ef0 : 0xffffff80104ea270 mach_kernel : __ZN9IOService14doServiceMatchEj + 0x3e0
    0xffffffffffeb3f50 : 0xffffff80104ed3a7 mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x157
    0xffffffffffeb3fa0 : 0xffffff800fd9319e mach_kernel : _call_continuation + 0x2e
          Kernel Extensions in backtrace:
             com.apple.driver.AirPort.BrcmNIC(1400.1.1)[2D8718E9-180A-3A34-BF2D-B887DB02A5E0]@0xffffff8011b9d000->0xffffff80120f5fff
                dependency: com.apple.driver.corecapture(1.0.4)[9CE69804-5DDD-3BF6-A98D-5B6BA5703313]@0xffffff8012fdc000->0xffffff8012ffefff
                dependency: com.apple.driver.mDNSOffloadUserClient(1.0.1b8)[73A9A990-B32E-3EA9-A54C-2BECDAFC9249]@0xffffff80127f5000->0xffffff80127f9fff
                dependency: com.apple.iokit.IO80211FamilyLegacy(1200.12.2b1)[7519FAE2-799A-34FC-8274-F6023A658D2A]@0xffffff8011a3d000->0xffffff8011b81fff
                dependency: com.apple.iokit.IONetworkingFamily(3.4)[83808DB4-87E6-3795-8FE2-EC693E2C32EF]@0xffffff801259b000->0xffffff80125b1fff
                dependency: com.apple.iokit.IOPCIFamily(2.9)[9C9EBD2E-5FA1-3F62-8108-32622F1E113B]@0xffffff80127fc000->0xffffff801282afff
                dependency: com.apple.iokit.IOSkywalkFamily(1.0)[5454E8BA-04BE-3EAC-BD3C-8D69AA1EFEA7]@0xffffff80128e4000->0xffffff8012910fff
    
    Process name corresponding to current thread (0xffffff95430d2b20): kernel_task
    Boot args: keepsyms=1 agdpmod=pikera 
    
    Mac OS version:
    Not yet set
    
    Kernel version:
    Darwin Kernel Version 22.0.0: Tue Jun 28 20:47:52 PDT 2022; root:xnu-8792.0.134.131.2~1\/RELEASE_X86_64
    Kernel UUID: 511187AD-75E6-35AB-AF7C-E20EEBBFFFEA
    roots installed: 0
    KernelCache slide: 0x000000000fa00000
    KernelCache base:  0xffffff800fc00000
    Kernel slide:      0x000000000fadc000
    Kernel text base:  0xffffff800fcdc000
    __HIB  text base: 0xffffff800fb00000
    System model name: iMacPro1,1 (Mac-7BA5B2D9E42DDD94)
    System shutdown begun: NO
    Panic diags file unavailable, panic occurred prior to initialization
    Hibernation exit count: 0
    
    System uptime in nanoseconds: 2892415315
    Last Sleep:           absolute           base_tsc          base_nano
      Uptime  : 0x00000000ac66c4a4
      Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
      Wake    : 0x0000000000000000 0x0000000875e161ee 0x0000000000000000
    Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
    Zone info:
      Zone map: 0xffffff80732b0000 - 0xffffffa0732b0000
      . PGZ   : 0xffffff80732b0000 - 0xffffff807b2b1000
      . VM    : 0xffffff807b2b1000 - 0xffffff8546c4a000
      . RO    : 0xffffff8546c4a000 - 0xffffff86dff7d000
      . GEN0  : 0xffffff86dff7d000 - 0xffffff8bab916000
      . GEN1  : 0xffffff8bab916000 - 0xffffff90772af000
      . GEN2  : 0xffffff90772af000 - 0xffffff9542c48000
      . GEN3  : 0xffffff9542c48000 - 0xffffff9a0e5e2000
      . DATA  : 0xffffff9a0e5e2000 - 0xffffffa0732b0000
      Metadata: 0xffffffeabee64000 - 0xffffffeadee64000
      Bitmaps : 0xffffffeadee64000 - 0xffffffeaf6e64000
```

**Comment by justinkb** [comment]
this panic just occurred for me during a regular boot, not in an upgrade scenario, so it isn't tied to updating macos necessarily

**Comment by Edwardwich** [comment]
> this panic just occurred for me during a regular boot, not in an upgrade scenario, so it isn't tied to updating macos necessarily

I have this problem on beta 4 Macos 13

**Comment by Edwardwich** [comment]
```
Process name corresponding to current thread (0xffffff95430d2b20): kernel_task
    Boot args: keepsyms=1 agdpmod=pikera 
    
    Mac OS version:
    Not yet set
    
    Kernel version:
    Darwin Kernel Version 22.0.0: Tue Jun 28 20:47:52 PDT 2022; root:xnu-8792.0.134.131.2~1\/RELEASE_X86_64
    Kernel UUID: 511187AD-75E6-35AB-AF7C-E20EEBBFFFEA
    roots installed: 0
    KernelCache slide: 0x000000000fa00000
    KernelCache base:  0xffffff800fc00000
    Kernel slide:      0x000000000fadc000
    Kernel text base:  0xffffff800fcdc000
    __HIB  text base: 0xffffff800fb00000
    System model name: iMacPro1,1 (Mac-7BA5B2D9E42DDD94)
    System shutdown begun: NO
    Panic diags file unavailable, panic occurred prior to initialization
    Hibernation exit count: 0
    
    System uptime in nanoseconds: 2892415315
    Last Sleep:           absolute           base_tsc          base_nano
      Uptime  : 0x00000000ac66c4a4
      Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
      Wake    : 0x0000000000000000 0x0000000875e161ee 0x0000000000000000
    Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
    Zone info:
      Zone map: 0xffffff80732b0000 - 0xffffffa0732b0000
      . PGZ   : 0xffffff80732b0000 - 0xffffff807b2b1000
      . VM    : 0xffffff807b2b1000 - 0xffffff8546c4a000
      . RO    : 0xffffff8546c4a000 - 0xffffff86dff7d000
      . GEN0  : 0xffffff86dff7d000 - 0xffffff8bab916000
      . GEN1  : 0xffffff8bab916000 - 0xffffff90772af000
      . GEN2  : 0xffffff90772af000 - 0xffffff9542c48000
      . GEN3  : 0xffffff9542c48000 - 0xffffff9a0e5e2000
      . DATA  : 0xffffff9a0e5e2000 - 0xffffffa0732b0000
      Metadata: 0xffffffeabee64000 - 0xffffffeadee64000
      Bitmaps : 0xffffffeadee64000 - 0xffffffeaf6e64000

**Comment by Edwardwich** [comment]
>  ```
> ;;qpanic(cpu 6 caller 0xffffff8007553797): Double fault at 0xffffff8009acb6c4, registers:
> CR0: 0x0000000080010033, CR2: 0xffffffb0932cbff8, CR3: 0x0000000269484010, CR4: 0x00000000003626e0
> RAX: 0xffffff800b3ba3f8, RBX: 0xffffff8b9ebed640, RCX: 0x0000000000000021, RDX: 0x0000000000000002
> RSP: 0xffffffb0932cc000, RBP: 0xffffffb0932cc030, RSI: 0xffffff8b9e72b788, RDI: 0xffffff8b9ebed640
> R8:  0x0000000000000000, R9:  0x0000000000000000, R10: 0xffffff800725eb90, R11: 0xffffff80083e7dc2
> R12: 0x00000000e00002d7, R13: 0xffffff8b9e72b788, R14: 0x0000000000000021, R15: 0x0000000000000021
> RFL: 0x0000000000010246, RIP: 0xffffff8009acb6c4, CS:  0x0000000000000008, SS:  0x0000000000000010
> Error code: 0x0000000000000000
>  @trap_native.c:168
> Panicked task 0xffffff86d2040df8: 12 threads: pid 148: WindowServer
> Backtrace (CPU 6), panicked thread: 0xffffff95372990c8, Frame : Return Address
> 0xffffff800710f270 : 0xffffff80073f6a1d 
> 0xffffff800710f2c0 : 0xffffff8007563316 
> 0xffffff800710f300 : 0xffffff80075525a0 
> 0xffffff800710f350 : 0xffffff8007391951 
> 0xffffff800710f370 : 0xffffff80073f6cfd 
> 0xffffff800710f460 : 0xffffff80073f63a9 
> 0xffffff800710f4c0 : 0xffffff8007be15fb 
> 0xffffff800710f5b0 : 0xffffff8007553797 
> 0xffffff800710f6c0 : 0xffffff8007be93c8 
> 0xffffff800710f6d0 : 0xffffff8007391e4f 
> 0xffffffb0932cc030 : 0xffffff8009acb6ca 
> 0xffffffb0932cc070 : 0xffffff8009acb6ca 
> 0xffffffb0932cc0b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc0f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc130 : 0xffffff8009acb6ca 
> 0xffffffb0932cc170 : 0xffffff8009acb6ca 
> 0xffffffb0932cc1b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc1f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc230 : 0xffffff8009acb6ca 
> 0xffffffb0932cc270 : 0xffffff8009acb6ca 
> 0xffffffb0932cc2b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc2f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc330 : 0xffffff8009acb6ca 
> 0xffffffb0932cc370 : 0xffffff8009acb6ca 
> 0xffffffb0932cc3b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc3f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc430 : 0xffffff8009acb6ca 
> 0xffffffb0932cc470 : 0xffffff8009acb6ca 
> 0xffffffb0932cc4b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc4f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc530 : 0xffffff8009acb6ca 
> 0xffffffb0932cc570 : 0xffffff8009acb6ca 
> 0xffffffb0932cc5b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc5f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc630 : 0xffffff8009acb6ca 
> 0xffffffb0932cc670 : 0xffffff8009acb6ca 
> 0xffffffb0932cc6b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc6f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc730 : 0xffffff8009acb6ca 
> 0xffffffb0932cc770 : 0xffffff8009acb6ca 
> 0xffffffb0932cc7b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc7f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc830 : 0xffffff8009acb6ca 
> 0xffffffb0932cc870 : 0xffffff8009acb6ca 
> 0xffffffb0932cc8b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc8f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc930 : 0xffffff8009acb6ca 
> 0xffffffb0932cc970 : 0xffffff8009acb6ca 
> 0xffffffb0932cc9b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cc9f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cca30 : 0xffffff8009acb6ca 
> 0xffffffb0932cca70 : 0xffffff8009acb6ca 
> 0xffffffb0932ccab0 : 0xffffff8009acb6ca 
> 0xffffffb0932ccaf0 : 0xffffff8009acb6ca 
> 0xffffffb0932ccb30 : 0xffffff8009acb6ca 
> 0xffffffb0932ccb70 : 0xffffff8009acb6ca 
> 0xffffffb0932ccbb0 : 0xffffff8009acb6ca 
> 0xffffffb0932ccbf0 : 0xffffff8009acb6ca 
> 0xffffffb0932ccc30 : 0xffffff8009acb6ca 
> 0xffffffb0932ccc70 : 0xffffff8009acb6ca 
> 0xffffffb0932cccb0 : 0xffffff8009acb6ca 
> 0xffffffb0932cccf0 : 0xffffff8009acb6ca 
> 0xffffffb0932ccd30 : 0xffffff8009acb6ca 
> 0xffffffb0932ccd70 : 0xffffff8009acb6ca 
> 0xffffffb0932ccdb0 : 0xffffff8009acb6ca 
> 0xffffffb0932ccdf0 : 0xffffff8009acb6ca 
> 0xffffffb0932cce30 : 0xffffff8009acb6ca 
> 0xffffffb0932cce70 : 0xffffff8009acb6ca 
> 0xffffffb0932cceb0 : 0xffffff8009acb6ca 
> 0xffffffb0932ccef0 : 0xffffff8009acb6ca 
> 0xffffffb0932ccf30 : 0xffffff8009acb6ca 
> 0xffffffb0932ccf70 : 0xffffff8009acb6ca 
> 0xffffffb0932ccfb0 : 0xffffff8009acb6ca 
> 0xffffffb0932ccff0 : 0xffffff8009acb6ca 
> 0xffffffb0932cd030 : 0xffffff8009acb6ca 
> 0xffffffb0932cd070 : 0xffffff8009acb6ca 
> 0xffffffb0932cd0b0 : 0xffffff8009acb6ca 
> 0xffffffb0932cd0f0 : 0xffffff8009acb6ca 
> 0xffffffb0932cd130 : 0xffffff8009acb6ca 
> 0xffffffb0932cd170 : 0xffffff8009acb6ca 
> 	Backtrace continues...
>       Kernel Extensions in backtrace:
>          com.apple.iokit.IOHIDFamily(2.0)[913F56F9-6532-34E2-8BD9-92EEDA09511F]@0xffffff8009abb000->0xffffff8009b1afff
>             dependency: com.apple.iokit.IOReportFamily(47)[E6F61ECC-CD23-30E2-AB43-5BF538F7411E]@0xffffff8009e2e000->0xffffff8009e30fff
> 
> Process name corresponding to current thread (0xffffff95372990c8): WindowServer
> Boot args: -v
> 
> Mac OS version:
> 22A5311f
> 
> Kernel version:
> Darwin Kernel Version 22.0.0: Wed Jul 20 01:51:06 PDT 2022; root:xnu-8792.0.188.141.3~2/RELEASE_X86_64
> Kernel UUID: 13D16CC7-18BB-36D7-9111-C880DB83959D
> roots installed: 0
> KernelCache slide: 0x0000000007000000
> KernelCache base:  0xffffff8007200000
> Kernel slide:      0x00000000070dc000
> Kernel text base:  0xffffff80072dc000
> __HIB  text base: 0xffffff8007100000
> System model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)
> System shutdown begun: NO
> Panic diags file available: YES (0x0)
> Hibernation exit count: 0
> 
> System uptime in nanoseconds: 189823062441
> Last Sleep:           absolute           base_tsc          base_nano
>   Uptime  : 0x0000002c325614b4
>   Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
>   Wake    : 0x0000000000000000 0x00000004aadb3318 0x0000000000000000
> Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
> Zone info:
>   Zone map: 0xffffff806ac0c000 - 0xffffffa06ac0c000
>   . PGZ   : 0xffffff806ac0c000 - 0xffffff806bc0d000
>   . VM    : 0xffffff806bc0d000 - 0xffffff8538673000
>   . RO    : 0xffffff8538673000 - 0xffffff86d1f3f000
>   . GEN0  : 0xffffff86d1f3f000 - 0xffffff8b9e9a5000
>   . GEN1  : 0xffffff8b9e9a5000 - 0xffffff906b40b000
>   . GEN2  : 0xffffff906b40b000 - 0xffffff9537e71000
>   . GEN3  : 0xffffff9537e71000 - 0xffffff9a048d8000
>   . DATA  : 0xffffff9a048d8000 - 0xffffffa06ac0c000
>   Metadata: 0xffffff80253fc000 - 0xffffff80453fc000
>   Bitmaps : 0xffffff80453fc000 - 0xffffff80483fc000
> 
> 

Reboot system after few minutes

**Comment by justinkb** [comment]
I've managed to isolate this to use of NVMeFix.kext

**Comment by PMheart** [comment]
This sounds funny. How is the kernel panic triggered by the wireless kext while linked to NVMeFix? Any further proof?

**Comment by justinkb** [comment]
Yes, good question. It is quite odd indeed, I will look into it further,
but I have not had the panic yet since disabling NVMeFix.kext, when
otherwise it would occur about half the time.

**Comment by vit9696** [comment]
The panic is unfortunately unrelated to NVMeFix, since the wireless driver crashes. It must be some sort of race-condition bug in Apple Wireless drivers. Unfortunately we can only suggest not to use NVMeFix if it makes the issue happen more frequently.

**Comment by junzhli** [comment]
I got the kernel panic error as the same as the above one until I remove nvmefix. It's very strange but it works!
I am currently with macOS 13.2.1
