### ISSUE TITLE
PowerColor Fighter RX 6600 (non XT) black screen when IntelMausi.kext is loaded (enable)

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#2094]
Motherboard : Gigabyte H610M H DDR4
Processsor : Intel Core i5 12400F
Ethernet : Intel I219-V17
GPU : PowerColor Fighter RX 6600 (non XT)

Problem :
Always get black screen when IntelMausi.kext is enabled. I try to disable this kext and no more black screen (100% will be booted and display is ok). Boot argument "agdpmod=pikera" is set already.

I try to disable acceleration of GPU with fake id 0x34, 0x12, 0x00, 0x00 and system boot with no acceleration but it will take too long (1.5 minutes) with this log **"[IntelMausi] : The NVM Checksum is not valid"**

![WhatsApp Image 2022-07-23 at 10 25 45 PM](https://user-images.githubusercontent.com/9614101/180618725-308c956c-020b-4cbe-b320-4c15824a150d.jpeg)

I have read several article in reddit, some of RX 6600 got problem too (black screen) and after disable several option in config.plist for debugging purpose then system will boot fine.
![RX 6600 - Black Screen 1](https://user-images.githubusercontent.com/9614101/180618787-6a50c2cb-d445-4bd4-86e1-106a8243b620.png)

And according to history, IntelMausi of acidanthera is contain KernelDebugger features. Maybe this the issue for RX 6600 variant, 

Can we disable this KernelDebugger features from IntelMausi with certain bootargument?? I try to use "Mieze" version but it won't be loaded in macOS Monterey

**Comment by andreszerocross** [comment]
I found alternatif solution to make ethernet work with no black screen

1. Disabled **Intel PTT** in bios
2. Disabled **SMCSuperIO.kext** (Plugin of VirtualSMC.kext

With that config, i can enable IntelMausi.kext and boot with normal. 100% no black screen.

So this is the conclusion
Enable IntelMausi.kext + Enable PTT + Disable SMCSuperIO.kext = Black screen
Enable IntelMausi.kext + Disable PTT + Enable SMCSuperIO.kext = Black screen
Enable IntelMausi.kext + Disable PTT + Disable SMCSuperIO.kext = Normal
Disable IntelMausi.kext + Enable PTT + Enable SMCSuperIO.kext = Normal

**Comment by vit9696** [comment]
This is a memory map issue in your bios. It can be related to DMAR and/or TXE/PTT, but I am not positive there is anything else to check. Unfortunately there is not much to do on the driver side.
