### ISSUE TITLE
MacKernelSDK missing headers used for libkern/c++/OSKext.h

### ISSUE THREAD

**Issue by ChefKissInc** [acidanthera/bugtracker#2096]
Including the aforementioned header leads to include errors, due to the following missing includes:

#include <libkern/OSKextLibPrivate.h>
#include <libkern/kernel_mach_header.h>

**Comment by vit9696** [comment]
I would say this is a private header, which should not really be included. It is different from macOS version to macOS version, so not much to do on our side. Why do you need this header?
