### ISSUE TITLE
GPU Spoof SSDT in OpenCore 0.8.2

### ISSUE THREAD

**Issue by StatCombo** [acidanthera/bugtracker#2097]
Hello Dear I can't use the SSDT Gpu Spoof after update Open Core to 0.8.2R
I try to Spoof my R7 250 To R7 250X in Mojave but it's not worked for me....  my system is Haswell Z87 i7 4770
I am attach my EFI configure below
please help me to solve this issue
[EFI.zip](https://github.com/acidanthera/bugtracker/files/9225755/EFI.zip)

**Comment by Andrey1970AppleLife** [comment]
You found this SSDT on Dortania. Write to Dortania.

**Comment by StatCombo** [comment]
> You found this SSDT on Dortania. Write to Dortania.

I am try previous version of opencore and it ssdt spoof  worked fine on 0.8.2 not working...

**Comment by perez987** [comment]
@StatCombo 
This issue must be redirected to support forums.

**Comment by StatCombo** [comment]
Support of what?

**Comment by StatCombo** [comment]
But fake id function same not working (if I am manually enter the id in config.plist
