### ISSUE TITLE
Whatevergreen issue : everyrhing works with 1.5.9 / "no input" after Filevault with 1.6.0 (Navi 21 / RX6600 XT)

### ISSUE THREAD

**Issue by MSTRKKRFT** [acidanthera/bugtracker#2098]
Hello, 

I just updated OC from 0.8.1 to 0.8.2, AppleALC from 1.7.2 to 1.7.3 & Whatevergreen from 1.5.9 to 1.6.0. I'm updating OC & kexts every month after stable release, never had an issue. 

But this time it wasn't a breeze : **updating WEG from 1.5.9 to 1.6.0 result in "no input" after Filevault.** 
Reverting to WEG 1.5.9 (keeping OC 0.8.2 & AppleALC 1.7.3 updates) solve the issue. 

**I'm using "agdpmod=pikera" as a boot-arg**, otherwise I get "no input" after Filevault as well. So it's basically acting as if I forget the boot-arg with last WEG update. 

Here is my config : 
- OC 0.8.2 with all kexts updated
- Monterey 12.4 (was updating OC & Kexts before updating to 12.5) 
- GPU : XFX RX6600 XT 8Go + UHD 630 (setup as headless)
- System : i7-9700K + z390 AORUS ELITE + 64Go RAM + NVME for system + Fenvi T919 

ACPI (made with SSDTTime) : 
- SSDT-EC.aml
- SSDT-PLUG.aml
- SSDT-PMC.aml
- SSDT-USBX.aml

Kexts I use : 
- AppleALC.kext
- HoRNDIS.kext
- IntelMausi.kext
- Lilu.kext
- NVMeFix.kext
- RadeonSensor.kext
- SMCProcessor.kext
- SMCRadeonGPU.kext
- SMCSuperIO.kext
- USBPorts.kext
- VirtualSMC.kext
- WhateverGreen.kext

I can provide my EFI/config.plist or more information if needed. 

Thanks for your help, 
MSTRKKRFT

**Comment by vit9696** [comment]
Please provide the exact commit that is causing issues for you. See builds on https://dortania.github.io/builds/?product=WhateverGreen&viewall=true.

**Comment by MSTRKKRFT** [comment]
Hi, 

Thanks for your help! 

Everything works until this commit : 

559349d | Add Skylake Graphics spoofing support for macOS 13+

**Comment by vit9696** [comment]
Hmm, I personally do not see how this can affect Coffee Lake CPUs. I am afraid it changes no single code path that runs on Coffee Lake CPU. Could you please recheck and show me a video of working and not working code path? Also, check that ocvalidate finds no issues in your `config.plist` (it will help if you upload it as well).

**Comment by MSTRKKRFT** [comment]
Actually, I don't think it's CPU related (but I might be wrong), as the only problem is the dGPU not showing any display out with last revisions of WEG kext. The iGPU is not used to drive the display (it's in headless mode), **I use my XFX RX6600XT to drive my two displays**. 

About the config.plist **there is no issue found in ocvalidate**, and that's actually the config.plist I'm using for about a year, updating it after each OC monthly updates (with kexts) and never had an issue... 

I don't understand what you mean about working/non working code path, sorry... But when I'm using verbose boot-arg (-v), the screen would just not pass the last steps (switching from verbose to desktop) and go to sleep when I'm on 1.6.0 stable. if I put one of the first 1.6.0 comits (the ones before 559349d) or the 1.5.9 stable it will show all verbose informations, then switch to desktop screen (as I'm using Filevault it goes to desktop just after verbose). On 1.6.0 stable home screen will not be shown and I get "no input" error from my screens, but computer stills run. 
 
Again, **to fix the issue all I have to do is to switch from 1.6.0 stable to 1.5.9 stable kext** (or one of the early comits of 1.6.0), **nothing more**, config.plist file remains the same. 

Here is my config.plist : [config.plist.zip](https://github.com/acidanthera/bugtracker/files/9239938/config.plist.zip)

And here is a screenshot of my EFI : 
![Screenshot 2022-08-02 at 09 28 31](https://user-images.githubusercontent.com/70702433/182317307-c768c874-8224-49b9-9929-6d2fd694dfb4.png)

Thank you for your help ! é

**Comment by MSTRKKRFT** [comment]
Hi! 

I just tried with 1.6.1, at the beginning I had the same issue. But after a few more reboots & NVRAM Reset it's working again, I really don't know how it fixed by itself, but it works! 

I'm closing the issue, thanks for your help
