### ISSUE TITLE
Verify `LoadEarly` in drivers in ocvalidate

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#2099]
We need to error in ocvalidate when `LoadEarly` is set to true in all drivers but emulated NVRAM.

This is particularly important as some tools had errors when updating the config (https://github.com/ic005k/OCAuxiliaryTools/issues/276).

**Comment by vit9696** [comment]
For any driver that is not OpenVariableRuntimeDxe.efi LoadEarly must be false. The implementation looks wrong.

**Comment by mikebeaton** [comment]
OpenRuntime.efi also should be Early, assuming OpenVariableRuntimeDxe.efi is loaded.
