### ISSUE TITLE
Failed to update to Windows 11 insider

### ISSUE THREAD

**Issue by wqhqq1** [acidanthera/bugtracker#2101]
I'm booting windows and macOS using opencore. And my computer works well with windows 11 with TPM enabled.
But when using opencore with bootcamp installed, system gets incorrect AMD GPU driver when updates(guess windows thought the pc is a mac and try to install mac's amd gpu driver on windows 11 which is unsupported with official graphics card, and often failed with 0xc1900101(driver error).
Is there anyway to avoid the problem without boot windows from standard UEFI?
I can't thank more for whom can help.

**Comment by Andrey1970AppleLife** [comment]
Don't instal not necessary drivers from bootcamp.
