### ISSUE TITLE
[Feature Request] Commit SHA in version

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2102]
For those who use pre-released versions of OpenCore/kexts it would be really useful adding the specific commit SHA onto the version (or in debug logs). This will help users who forget about the specific commit version to help the devs with breadcrumbs.
Can this be achievable?

**Comment by PMheart** [comment]
This is a duplication of https://github.com/acidanthera/bugtracker/issues/384; unfortunately we would unlikely work on it in any near future.
