### ISSUE TITLE
Your firmware is not supported

### ISSUE THREAD

**Issue by KaoS-TR** [acidanthera/bugtracker#2103]
Hello, first of all I apologize for grammatical errors because I am not a good speaker of English.

I am using a latest stable release OpenCore, WhateverGreen, Lilu and another kext.

I am testing any components and any macOS version for Turkish Hackintosh forum users and my YouTube channel.

2 days ago installing macOS Ventura Beta (22A5311f) my desktop computer with SMBIOS MacPro7,1 all specs perfectly but I open the BootCamp utility "Booting from external or removable media is not enabled" messages.

![Screenshot 2022-08-09 at 05 43 39](https://user-images.githubusercontent.com/61596341/183552236-4a53cd1c-f8cc-4844-97a1-1e473f85d71c.png)

After this incident, I followed the instructions and got the "Your firmware is not supported" error in Recovery Mode.

Thinking that this problem may be related to Apple SecureBootModel, I applied the changes I mentioned below.

- config.plist -> Misc -> SecureBootModel -> Default to change j160
- config.plist -> Misc -> ApECID ->  0 to "64 Bit Identifier"

64 Bit Identifier created a python for this command.
`python3 -c 'import secrets; print(secrets.randbits(64))'`

Then reboot my hackintosh and going to bios I applied the changes I mentioned below.

- Intel Platform Trust Technology -> Enabled
- Software Guard Extensions SGX -> Enabled with Software Controlled 
- Security Device Support -> Enabled
- TPM2.0 UEFI Spec Version -> TCG_1_2 Change to TCG_2
- Physcial Spec Version -> 1,2 change to 1,3
- Secure Boot -> Enabled
- Os TYPE -> Other OS

Then Save and Exit 
Open the OpenCore menu and select to Recovery boot.
Open Terminal in recovery mode and execute this command.
`bless --folder "/Volumes/macOS SSD/System/Library/CoreServices" --bootefi --personalize`

exit terminal and reboot my hackintosh then normal boot macOS Ventura. 
Open the terminal and ran the code below.
![Screenshot 2022-08-09 at 07 05 00](https://user-images.githubusercontent.com/61596341/183561791-d12d2296-0983-4377-b605-0097db39c036.png)
The result is excellent. I am now using a macOS with FullSecurityMode.
Note : I know "Vault" options but  I don't think it will be needed.

Then restart my hackintosh for recovery mode and re open startup security utility and re problem "Your firmware is not supported" 

I tried many different e.g. SecurityBootMode disable-default-j160, ForceSecureBootSchema enable-disable, LauncherOption Full-System-Disable, RequestBootVarRouting enable-disable and etc with all combination.

I check it OpenCore.pkg Configuration.pdf but I couldn't find a solution.

Maybe change my SMBIOS problem solved but need run to T2 chips SMBIOS many person. 

Yes another windows install maybe solved problem, @dortania recommends Brigadier.

Thanks to Hackintosh Opencore, it now works like a real mac. We can't thank you enough for that.

I believe you can close this small gap and we can use an original mac feature on hackintosh devices.

I apologize in advance if the problem is due to a mistake I made or a detail that I overlooked.

We would also be pleased to add our forum as Turkey page to the Discussion Forums page.

[http://www.osxinfo.net](url)  Hackintosh and Opencore Turkey support platform

**Comment by vit9696** [comment]
> startup security utility

This is for macs exclusively. The utility needs T2 device, which we do not have. Instead you should edit config.plist in OpenCore to reconfigure platform security.
