### ISSUE TITLE
USB pointer regression in 0.8.3 vs 0.6.0

### ISSUE THREAD

**Issue by za-creature** [acidanthera/bugtracker#2104]
First and foremost, thanks for the effort you are investing into this! I switched from chameleon and clover a few years ago and never looked back.

I upgraded from 0.6.0 to 0.8.3 in order to use Monterey. Most things work fine (bit of a regression bluetooth-wise, but that's more of an OS issue). My main beef is that the mouse I'm using _just_ for canopy (to pick the boot target, once the OS is loaded I switch to my main wireless keyboard / trackpad combo) no longer works on 0.8.3:

The driver itself loads correctly when included in the config:
```
00:306 00:003 OC: Driver UsbMouseDxe.efi at 3 () is being loaded...
00:311 00:004 OCABC: EfiBootRt candidate - <nil>
00:315 00:003 OCABC: IsEfiBootRt 0 (BP 1, Apple 0)
00:319 00:003 OCB: Arch filtering 0(40964)->374D5018(40964) caps 4 - Success
00:323 00:004 OC: Driver UsbMouseDxe.efi at 3 is successfully loaded!
00:327 00:003 OC: Driver UsbMouseDxe.efi at 3 needs connection.
00:330 00:003 OC: Connecting drivers...
00:367 00:036 OC: Connecting drivers done...
00:371 00:003 OC: Found 3 pointer devices - Success
```
However I'm a bit confused as to where do the other two pointer devices come from. I messed around with firmware settings regarding legacy usb support and xhci handoff, turned the bluetooth devices off, but that didn't really do anything, 3 pointers are always detected regardless of what I do. I don't have any logs from the previous version as I've been using the release build for over a year, so I can't really tell if that was always the case.

I explicitly set `AppleInput=Builtin` in case `Auto` wasn't picking it up and tried various combinations of polling intervals, multipliers and driver load order, but to no avail. USB keyboard works fine, though I'd rather not attach it just for the boot screen (the mouse I sometimes use for games, so keeping it attached doesn't bother me). This config worked fine in 0.6 (using the defaults of Auto/0/0/1/1), so I'm not entirely sure when it broke. Goes without saying that all hardware works as expected once booted.

Firmware is gigabyte z390i / F8c, cpu is coffee lake, mouse is logitech M510 though I don't think it matters too much as its doing its 2.4ghz thing separately and just registers itself as a standard "wired" usb hid.

I'll try bisecting this further once I find the time to do that, I just figured someone here might remember recent usb changes and point me in the right direction. If you need full logs and config, I can provide them once I trim the sensitive bits out of them, or I can send the raw EFI via email if you tell me where to.

**Comment by mikebeaton** [comment]
This is pretty cloooose to a support issue.... I think that doing a binary search of commits will help, and probably tell you what you need to change in setup anyway.

**Comment by za-creature** [comment]
If anyone ends up here from a search, [`PickerAttributes += 16`](https://github.com/acidanthera/OpenCorePkg/commit/5c9e826cc76abb9fa22177596a39d1a2497351b2)
