### ISSUE TITLE
OC0.8.4:Failed to upgrade macos13 beta 3 or above

### ISSUE THREAD

**Issue by mirbeta** [acidanthera/bugtracker#2105]
When upgrading macos13 beta 3, there is a card EB. The BIOS has unlocked CFG lock. The problem is still the same after trying to re unlock and use EFI tools. However, macos13 beta 3 and the following systems can be used normally,
Using oc0.8.3 and the latest 0.8.4 development version can not solve the problem

Motherboard model: z590 aorus Xtreme
Hard disk: Samsung 980pro 2T
Graphics card radeon VII 16g hbm2

![CD0E3CDA-1BA1-4BD6-A59E-2C42786FB835](https://user-images.githubusercontent.com/11530204/184179803-c4465f3b-8120-4e8f-9135-ac59b657b1b7.jpeg)
![39D87446-0BBD-45A6-A3BE-DAA8F6E00559](https://user-images.githubusercontent.com/11530204/184179854-a5543b3b-da5b-405c-8d6f-9284740419f0.jpeg)
![8523EC9D-BE29-4B0E-A02B-6E928291E37E](https://user-images.githubusercontent.com/11530204/184179909-16a8bbc1-cf70-4112-9315-2b1a9973a65e.jpeg)

**Comment by dreamwhite** [comment]
Use forums for support!

CC @Andrey1970AppleLife
