### ISSUE TITLE
Crucial nvme SSD could not recognized in Ventura installation

### ISSUE THREAD

**Issue by wu-cl** [acidanthera/bugtracker#2107]
**Env:**
opencore: `0.8.3`
all kexts are latest till now.
Crucial nvme SSD is `p2 1T` & `p5 plus 2T`

**Details:**
I can't find any nvme device inside `disk utility` nor `install ventura`
But in `Monterey` everything is ok, I can select the disk, format and install the system normally.

**Comment by PMheart** [comment]
Hello! Please post on forums for support.
