### ISSUE TITLE
ICE LAKE igpu hdr issue

### ISSUE THREAD

**Issue by flhs0606** [acidanthera/bugtracker#2108]
My machine cpu is i3 1005g1, igpu only. I use the last releases of opencore 0.8.3 and lilu weg etc. I tried macos12 macos13, igpu works well in 4k60hz with lg 42c2 using type-c to hdmi2.1 adapter except HDR. Now I'm running macos13 with lg 42c2 in 4k60hz 444 10bit. But hdr option did'nt show. Is it possible for hdr working in icelake igpu?
<img width="434" alt="image" src="https://user-images.githubusercontent.com/53371423/185745870-c74327db-61d6-4e0f-bca8-78142e19d45a.png">

**Comment by vit9696** [comment]
I am not aware anybody used HDR on ICL GPU. Either way, a support issue.
