### ISSUE TITLE
Automatically reboot in venture beta5

### ISSUE THREAD

**Issue by HeartAndSoul001** [acidanthera/bugtracker#2109]
These days, without any operation, my x1 carbon automatically reboot.I wonder if
![45AD71D7-B503-4EDA-B9AC-D354496C297D](https://user-images.githubusercontent.com/34875851/186332029-2beb66ed-86e7-432b-860e-134169cf4e96.jpeg)
 some 
![7863FF1A-843F-4572-AE85-B3621042056B](https://user-images.githubusercontent.com/34875851/186332035-dfb61b1f-c61c-4c11-bbb3-1f1e847349be.jpeg)
kexts do not support beta5？please someone help me
![4394A3C4-2B2A-482C-9174-F389D30E792B](https://user-images.githubusercontent.com/34875851/186332002-8f3aa957-bd35-4e9a-a5b0-b98f7ff261fc.jpeg)

**Comment by HeartAndSoul001** [comment]
![212ACE98-A402-4355-BEF0-60701748FA68](https://user-images.githubusercontent.com/34875851/186332199-8d30fc0e-6ece-4381-b49e-ae8588a2c0fc.jpeg)
![DD9404F0-C237-4B83-BBDE-020436315E7A](https://user-images.githubusercontent.com/34875851/186332235-844b6ff2-894b-4b94-914e-a8a9fbc94ead.jpeg)

**Comment by HeartAndSoul001** [comment]
![正在上传 186332296...]![正在上传 186332295...]

**Comment by HeartAndSoul001** [comment]
![正在上传 186332419...]![正在上传 186332436...]![正在上传 186332447...]

**Comment by PMheart** [comment]
Please post on forums for support.
