### ISSUE TITLE
OpenCore Reference Manual link error

### ISSUE THREAD

**Issue by danielp123** [acidanthera/bugtracker#2110]
In section 7.8 Quirks Properties of the OpenCore Reference Manual (0.8.3)

 1. AppleCpuPMCfgLock

   (f) Download and run Modified GRUB Shell compiled by **brainsucker**...

--> The hyperlink on "brainsucker" doesn't work anymore. It should probably point to this page: https://habr.com/en/users/brainsucker/

**Comment by mikebeaton** [comment]
https://github.com/acidanthera/OpenCorePkg/commit/937d76b1e5e760ae76ffef4ca04e1f6fd904f383

Thanks
