### ISSUE TITLE
Stuck in ExitBS with latest bios version in 600 chipset

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#2111]
Just for Info, for all chipset 600 series (B660, Z690, etc) when you update bios with latest version or any BIOS with features "- Ready for next-gen CPU / Supports and powers up Intel next generation processor" then we will stuck in log "exitbs bla bla bla"

I don't know what happened when we downgrade bios with other version bios that doesn't contain this features "Ready for next-gen CPU / Supports and powers up Intel next generation processor" then boot will be normal.

I have found this problem in MSI MAG B660M Mortar DDR4, Gigabyte Z690 Gaming X DDR4 V2, Gigabyte Z690 Gaming X DDR4 and Gigabyte Z690 Gaming X.

Maybe developer can check this problem too?

FYI, all configuration is still same between old and new bios and "ProvideCurrentCpuInfo = Enabled"

![Screen Shot 2022-08-25 at 20 43 25](https://user-images.githubusercontent.com/9614101/186682569-54b986b2-f712-4ce5-bc4c-d5e59ed983f6.png)
![Screen Shot 2022-08-25 at 20 46 30](https://user-images.githubusercontent.com/9614101/186682599-8cf11e8d-c773-486d-ac76-f148fc264cfe.png)
![WhatsApp Image 2022-08-25 at 8 36 22 PM](https://user-images.githubusercontent.com/9614101/186682605-1d8ffea4-d026-445c-92a1-fd307f2913a5.jpeg)

**Comment by vandroiy2013** [comment]
I've upgraded my Asus Z690-F Gaming WIFI with latest BIOS for next-gen CPUs and everything is fine. Don't have other vendor boards so we can't test it. Maybe other developers will get rid with this problem. 

P.S. Gigabyte boards are total s**t. IMHO 
<img width="915" alt="Знімок екрана 2022-08-25 о 17 02 49" src="https://user-images.githubusercontent.com/8144780/186687242-1d8307c0-f1c8-432b-b913-fc9811e09e9a.png">

**Comment by andreszerocross** [comment]
> I've upgraded my Asus Z690-F Gaming WIFI with latest BIOS for next-gen CPUs and everything is fine. Don't have other vendor boards so we can't test it. Maybe other developers will get rid with this problem.
> 
> P.S. Gigabyte boards are total s**t. IMHO <img alt="Знімок екрана 2022-08-25 о 17 02 49" width="915" src="https://user-images.githubusercontent.com/8144780/186687242-1d8307c0-f1c8-432b-b913-fc9811e09e9a.png">

But i found problem in "MSI MAG B660M Mortar DDR4" too

**Comment by vandroiy2013** [comment]
> Did you enable "ProvideCurrentCpuInfo"???

Sure.

**Comment by vandroiy2013** [comment]
> But i found problem in "MSI MAG B660M Mortar DDR4" too

That's unfortunate. My last MSI board was Z87. Starting from Skylake i prefer Asus.

**Comment by vandroiy2013** [comment]
@andreszerocross What about MSR 0xE2 on this BIOS versions? Did you try AppleXcpmCfgLock=true?

**Comment by andreszerocross** [comment]
> @andreszerocross What about MSR 0xE2 on this BIOS versions? Did you try AppleXcpmCfgLock=true?
> Do you use ProvideConsoleGop=True?

AppleXcpmCfgLock=Enabled
ProvideConsoleGop=Enabled

Mostly i always use "AppleXcpmCfgLock=Enabled" since i am using Clover for Haswell and above

**Comment by sonny362** [comment]
MSI Z690-A Pro DDR4 + i5-12600K - no troubles in Monterey and Ventura with the newest BIOS.

**Comment by andreszerocross** [comment]
> MSI Z690-A Pro DDR4 + i5-12600K - no troubles in Monterey and Ventura with the newest BIOS.

Did you use "AppleXcpmCfgLock=Enabled" or change MSR 0xE2 (CfgLock) from shell / BIOS Config ??

**Comment by sonny362** [comment]
> Did you use "AppleXcpmCfgLock=Enabled" or change MSR 0xE2 (CfgLock) from shell / BIOS Config ??

The quirk is True and CfgLock in my BIOS is Disabled. On my mobo macOS never loaded with CfgLock enabled from the first day and the first BIOS release.

**Comment by mikebeaton** [comment]
> The quirk is True and CfgLock in my BIOS is Disabled.

If CfgLock is disabled in the BIOS you should not need `AppleXcpmCfgLock` (nor `AppleCpuPmCfgLock`) at all, and it would be preferable to disable them - though I doubt it would fix the issue.

**Comment by Sher1ocks** [comment]
my board is Gigabyte B660M Aorus Elite DDR4.
there is no problem on F3 BIOS Version. OFC i disabled CFG Locks and Gpu BAR in BIOS

**Comment by vit9696** [comment]
I think I will close this, as it does not look there is something definite here. Likely a configuration issue.

**Comment by andreszerocross** [comment]
Sorry to disturb,,
Same problem happened in Asrock B660M PRO RS.

With BIOS 7.01 it will stuck in EBS bla bla bla

![image](https://user-images.githubusercontent.com/9614101/198883182-010bde25-1831-492a-9e72-0d77e0c7d298.png)


Then i reflash bios to 5.04 and it boot fines.

EFI File and patch 100% similar. All BIOS Config is same too between 7.01 and 5.01.

![image](https://user-images.githubusercontent.com/9614101/198883165-169408a6-7f8d-4410-bf36-716b6b2fc78f.png)

**Comment by Sher1ocks** [comment]
Recently i updated bios f20 on Gigabyte B660m Aorus Elite D4. stuck same part.

**Comment by Sher1ocks** [comment]
@andreszerocross 
OC is no problem. i fixed. we need to change Booter Quicks like this
![스크린샷 2022-11-02 오후 8 08 37](https://user-images.githubusercontent.com/2107738/199475140-82b74e4d-b833-4083-bd1c-b2bf41762090.png)

**Comment by dreamwhite** [comment]
> @andreszerocross OC is no problem. i fixed. we need to change Booter Quicks like this ![스크린샷 2022-11-02 오후 8 08 37](https://user-images.githubusercontent.com/2107738/199475140-82b74e4d-b833-4083-bd1c-b2bf41762090.png)

Is `MAT Support 1`? If so:

- `EnableWriteUnprotector` must be set to `False`
- `RebuildAppleMemoryMap` must be set to `True`
- `SyncRuntimePermissions` must be set to `True`

**Comment by Sher1ocks** [comment]
> > @andreszerocross OC is no problem. i fixed. we need to change Booter Quicks like this ![스크린샷 2022-11-02 오후 8 08 37](https://user-images.githubusercontent.com/2107738/199475140-82b74e4d-b833-4083-bd1c-b2bf41762090.png)
> 
> Is `MAT Support 1`? If so:
> 
> * `EnableWriteUnprotector` must be set to `False`
> * `RebuildAppleMemoryMap` must be set to `True`
> * `SyncRuntimePermissions` must be set to `True`

Until updated bios, i used that you mentioned above.
But stuck. I research something to boot macOS. Result is pic

**Comment by andreszerocross** [comment]
Most of 5xx and 6xx chipset will set TRUE for DevirtualiseMmio, RebuildAppleMemoryMap and SyncRuntimePermissions.

EnableWriteUnprotector and SetupVirtualMap should be False.

And now 6xx with latest BIOS version (13Th gen Intel support) need "EnableWriteUnprotector and SetupVirtualMap"???

Thanks for this tips @Sher1ocks

**Comment by Sher1ocks** [comment]
> Most of 5xx and 6xx chipset will set TRUE for DevirtualiseMmio, RebuildAppleMemoryMap and SyncRuntimePermissions.
> 
> EnableWriteUnprotector and SetupVirtualMap should be False.
> 
> And now 6xx with latest BIOS version (13Th gen Intel support) need "EnableWriteUnprotector and SetupVirtualMap"???
> 
> Thanks for this tips @Sher1ocks

At least need it to pass stuck for latest bios version.
I dont know reason.

**Comment by sdemius** [comment]
Thank you, I managed to boot my hackintosh Monterey on Gigabyte Z690 UD DD4 after bios upgrade to F21 with quirk: SetupVirtualMap enabled.
Later I found forum thread with similar discussion:
[https://www.tonymacx86.com/threads/gigabyte-z690-aero-g-i5-12600k-amd-rx-6800-xt.317179/page-207#post-2349251](url)
