### ISSUE TITLE
FadtEnableReset Quirk does not enable the Reset patch on Dell Optiplex 7780 (Hang Black screen when Reboot and Shutdown)

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#2117]
Hi @vit9696 , I have similar issues in Dell Optiplex AIO 7780 Cometlake. The symtoms is same like this old issue https://github.com/acidanthera/bugtracker/issues/1017

Restart and Shutdown just hang, black screen and fan keep spinning.

FadtEnableReset = True in config.plist

And i got logs "08:285 00:008 OCA: FADT reset got 276 need 129"

In my FACP table 
- Reset Register Supported  : 1
- Control Method Power Button  : 1
- Control Method Sleep Button : 1

Debug files is uploaded, thank you very much
[DEBUG.zip](https://github.com/acidanthera/bugtracker/files/9540891/DEBUG.zip)

**Comment by Lorys89** [comment]
@andreszerocross You can post the efi folder, Thank you

**Comment by vit9696** [comment]
This is strange, because on your OptiPlex 0xB2 register is written and used correctly. Are you sure the issue in something else? I remember such issue arising on one of the Dells I used when a set of quirks was incorrect. CC @usr-sse2, maybe you remember?

**Comment by vit9696** [comment]
Also consider enabling DisableRtcChecksum & rtcfx_exclude=80-FF (needs RTCMemoryFixup).

**Comment by andreszerocross** [comment]
> Also consider enabling DisableRtcChecksum & rtcfx_exclude=80-FF (needs RTCMemoryFixup).

DisableRtcChecksum is already enabled
