### ISSUE TITLE
[BrcmPatchRam and KextInfo.c] Inconsistency with BrcmFirmwareRepo

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2119]
According to BrcmPatchRAM [installation notes](https://github.com/acidanthera/BrcmPatchRAM#installation), BrcmFirmwareRepo cannot be injected using a bootloader.
If that's true, why [KextInfo.c Line 86](https://github.com/acidanthera/OpenCorePkg/blob/effb8fe5f08b42e03700e5e75111d3728c5a6d6c/Utilities/ocvalidate/KextInfo.c#L86) mentions it?
Shouldn't it be removed?

**Comment by PMheart** [comment]
Is it possible that this kext could not be injected with Clover (with OC it can be fine)?

**Comment by dreamwhite** [comment]
> Is it possible that this kext could not be injected with Clover (with OC it can be fine)?

As far as I remember with my old DW1830, BrcmFirmwareRepo could not be injected, but I tested it more than 7 months ago using OpenCore...

**Comment by vit9696** [comment]
BrcmFirmwareRepo.kext uses BrcmFirmwareRepo.kext/Contents/Resources directory to store firmware data. This directory is not available to macOS kextd, so the kext cannot be injected with a bootloader.

Its presence in [KextInfo.c](https://github.com/acidanthera/OpenCorePkg/blob/effb8fe5f08b42e03700e5e75111d3728c5a6d6c/Utilities/ocvalidate/KextInfo.c#L86) is a bug, which should be solved. @PMheart, please make sure ocvalidate errors when the kext is present.
