### ISSUE TITLE
Cannot boot macOS on Hyper-V, hangs on EXITBS:START

### ISSUE THREAD

**Issue by ivansavra1** [acidanthera/bugtracker#2120]
I'm trying to boot macOS Catalina on Hyper-V using MacHyperVSupport, but no matter what I try, I always get stuck on EXITBS:START.
I have made a lot of modifications to my config.plist to try to get it to work to no avail, some of them are these:
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start

I'm on a PC with a Ryzen 5 3600 and an A320M-A PRO MAX motherboard, I'm using this AMD patch: https://github.com/AMD-OSX/AMD_Vanilla
I also tried playing with the VM configuration, like the number of CPUs while also changing that number on the AMD patch, but I can't get past this, I'm using the debug version of both OpenCore and the kexts, so here's the EFI folder with logs:
[Hyper-V EFI.zip](https://github.com/acidanthera/bugtracker/files/9587251/Hyper-V.EFI.zip)

There are some errors before EXITBS:START like "[EB|#WL|5] 0x01 0x01  23 0x0E", but I don't understand what they mean.

**Comment by michyprima** [comment]
You get exactly what I got the last time I tried. At some point I just gave up and used vmware, but deep down my heart I still want this.

For reference I have 5950x paired with a B550 board. No matter what I tried it always stuck on EXITBS:START.

@Goldfish64 is there a way to get a more detailed debug log? I contemplated passing through a pci-express serial card and tell the kernel to print to it, but I don't even know if that would work.

**Comment by ivansavra1** [comment]
> You get exactly what I got the last time I tried. At some point I just gave up and used vmware, but deep down my heart I still want this.
> 
> For reference I have 5950x paired with a B550 board. No matter what I tried it always stuck on EXITBS:START.
> 
> @Goldfish64 is there a way to get a more detailed debug log? I contemplated passing through a pci-express serial card and tell the kernel to print to it, but I don't even know if that would work.

I feel very identified, a year ago I tried this with this same issue and gave up, I'm not using VMware or VirtualBox because it's too slow for me, and now I'm planning on doing a multiboot hackintosh. 
It's a shame, because I'll have to reboot every time I want to play games, but it seems like nobody cares about this issue :/

**Comment by michyprima** [comment]
> > You get exactly what I got the last time I tried. At some point I just gave up and used vmware, but deep down my heart I still want this.
> > For reference I have 5950x paired with a B550 board. No matter what I tried it always stuck on EXITBS:START.
> > @Goldfish64 is there a way to get a more detailed debug log? I contemplated passing through a pci-express serial card and tell the kernel to print to it, but I don't even know if that would work.
> 
> I feel very identified, a year ago I tried this with this same issue and gave up, I'm not using VMware or VirtualBox because it's too slow for me, and now I'm planning on doing a multiboot hackintosh. It's a shame, because I'll have to reboot every time I want to play games, but it seems like nobody cares about this issue :/

VMWare workstation is very fast when it virtualizes directly (without the hyper-v platform in the way). Don't expect better performance in hyper-v, it will never be as fast as native, especially without accelerated graphics.

My original plan was to passthrough a supported gpu on the pciexpress bus, something you cannot do on vmware but if you don't plan on doing something like this you may as well just use vmware

**Comment by Goldfish64** [comment]
AMD is currently completely unsupported and requires additional patches beyond the standard AMD macOS patches. Intel hosts are the only ones tested at this time.

> @Goldfish64 is there a way to get a more detailed debug log? I contemplated passing through a pci-express serial card and tell the kernel to print to it, but I don't even know if that would work.

Hyper-VM can be configured to pass one or two serial ports from the VM to named pipes on the Windows host, that can be opened using PuTTY or some other application that can handle named pipes. The guest will then just need to be configured for proper serial output with one or more debug flags for the kext.

**Comment by ivansavra1** [comment]
> AMD is currently completely unsupported and requires additional patches beyond the standard AMD macOS patches. Intel hosts are the only ones tested at this time.
> 
> > @Goldfish64 is there a way to get a more detailed debug log? I contemplated passing through a pci-express serial card and tell the kernel to print to it, but I don't even know if that would work.
> 
> Hyper-VM can be configured to pass one or two serial ports from the VM to named pipes on the Windows host, that can be opened using PuTTY or some other application that can handle named pipes. The guest will then just need to be configured for proper serial output with one or more debug flags for the kext.

I see, well maybe someone from AMD OSX can make this possible. @alyxferrari Can you create these "additional patches"?

**Comment by vit9696** [comment]
I think we should close this is out of scope. Given the time it hangs, it should be more about OpenCore patches, and these are provided by AMD teams anyway.

**Comment by Mohsens22** [comment]
@vit9696 @Goldfish64  So is MacHyperVSupport work on AMD CPUs afterall?
Is it possible to make it run?

**Comment by rscunha13** [comment]
I'm stuck at #[EB|LOG:EXITBS:START].

My hardware -> Ryzen 5950x - Window 11.
It runs fine inside VmWare but no go for Hyper-V. Already applied standartd AMD patches.

Do we need any special amd patch just for Hyper-V?

01:623 00:004 AAPL: #[EB|SB:SBGMFNS] x86legacyap.im4m
01:629 00:006 AAPL: #[EB|RH:PF] usr\standalone\OS.dmg.root_hash
01:634 00:004 AAPL: #[EB|RH:MF] <"usr\\standalone\\OS.dmg.root_hash.x86legacyap.im4m">
01:639 00:004 AAPL: #[EB.LD.LF|IN] 0 1 <"usr\\standalone\\OS.dmg.root_hash"> <"0">
01:669 00:030 AAPL: #[EB.LD.OFS|OPEN!] Err(0xE) <"usr\\standalone\\OS.dmg.root_hash">
01:675 00:006 AAPL: #[EB.RH.LRH|P!] Err(0xE) <- EB.LD.LF
01:681 00:006 AAPL: #[EB.BST.FBS|!] Err(0xE) <- EB.RH.LRH
01:687 00:005 AAPL: #[EB|LOG:DT] 2023-03-27T20:29:36
01:692 00:005 AAPL: #[EB|LOG:EXITBS:START] 2023-03-27T20:29:36
