### ISSUE TITLE
Elan TouchPad is not working after wakeup in 1s

### ISSUE THREAD

**Issue by loll70** [acidanthera/bugtracker#2121]
Always appreciate your hard work!

I have a ThinkPad Yoga 460 and every time the device wakes from sleep, the touchpad will be lost after 1 movement. I suspect something else overrides it. The keyboard and touchscreen work fine. 
kext in use: VoodooPS2controller (keyboard), VoodooI2C (Elan touchpad), VoodooI2CHID (touchscreen)

Bootloader : Latest OC
Lilu : Latest kext 

Potential similar issue: #1192 
What logs can I collect to help debug? similar to #1801 ?

**Comment by Andrey1970AppleLife** [comment]
Write to the author of the project VoodooI2C.

**Comment by loll70** [comment]
I am sorry. I mistook my touchpad as i2c. It is actually PS2 handled by VoodooPS2. Could you please reopen this issue? Evidence and initial log attached.
[trackpoint&clickpad conflict.zip](https://github.com/acidanthera/bugtracker/files/9602516/trackpoint.clickpad.conflict.zip)

Some more info about the issue: 
When only using VoodooPS2controller, **only** the trackpoint works, trackpad (expected to work) & touchscreen (expected not to work) doesn't work on boot. Trackpoint will be lost after waking from sleep and nothing works.
Initial log: When using VoodooPS2controller+VoodooI2C+VoodooI2CHID, everything will work on boot (expected). After waking from sleep, the trackpoint and touchpad will work **for a few seconds** before lost. Touchscreen continues to work.

**Comment by Andrey1970AppleLife** [comment]
Write to https://github.com/acidanthera/bugtracker/issues/1192
