### ISSUE TITLE
 BrcmPatchRAM - Monterey 12.5.1 BCM20702 & SystemProductName Issue - Changing to iMac14,2 works

### ISSUE THREAD

**Issue by qaziabdullah** [acidanthera/bugtracker#2122]
Hey! I hope everyone is doing good,

I recently made an EFI for one of my PCs (dell T5500 [EFI HERE](https://github.com/qaziabdullah/EFI-Dell-Precision-T5500)) and I was unable to use bluetooth.
I had a CSR dongle and tried BluetoolFixup kext but it didn't help. Tried debugging it for 2 3 days straight and gave up since it was not working no matter what and how i try. 
I think i almost tried everything that was available either on reddit and here in the issues section suggested by other users.
So i got an ORICO BTA 408 dongle which has BCM20702 and is supposed to work properly with the patches here in BrcmPatchRAM.
I plugged it in and used the kexts (in correct order and everything was fine) but it didn't work
i couldn't turn it on

Same as the CSR it showed in USB device section in profiler but under bluetooth i could only see "NULL" and PCIE

I was previously using MacPro5,1 smbios and bluetooth was not working. It was showing the "Transport" as "PCIe"

Idk something came to my mind and said why not just try changing smbios to iMac14,2 and see how that goes
I changed to iMac14,2 and rebooted, surprisingly it worked!

I don't know how this is affecting the BrcmPatchRAM but this worked for me and might be worth looking in to?
Me & my friends were surprised since we never expected this to be the issue.

Bluetooth works just fine for me now after changing it to iMac14,2
But doesn't work if i set it to MacPro5,1

Let me know if you need anything or logs or something.

**Comment by Andrey1970AppleLife** [comment]
Write to https://github.com/acidanthera/bugtracker/issues/1821
