### ISSUE TITLE
bluetooth permission failed

### ISSUE THREAD

**Issue by pangzhen** [acidanthera/bugtracker#2124]
bluetooth saves file on ram disk  failed with permission on Monterey，other macOS are ok，how to fix it ？ thx
ram disk created by diskutil

DISK_NAME=RamDisk  
DISK_SPACE=2
if ! test -e "/Volumes/$DISK_NAME" ; then  
    diskutil erasevolume jhfsx "$DISK_NAME" `hdiutil attach -nomount ram://$(($DISK_SPACE*1024*1024*2))`   
fi

默认	12:39:12.101398+0800	OBEXAgent	[OBEXSession][hasDataFromPreviousPacket]  mResponsePacketDataLengthSoFar = f9c0.
默认	12:39:12.101457+0800	OBEXAgent	[OBEXSession][addIncompletePacketData] received: 0x240. Total: 0xfc00/0xfc00.
默认	12:39:12.101506+0800	OBEXAgent	[OBEXSession][addIncompletePacketData] PACKET IS NOW COMPLETE (0xfc00 >= 0xfc00).
默认	12:39:12.101568+0800	OBEXAgent	[OBEXSession][serverHandleIncomingData] totalResponsePacketLength: 0xfc00, responseCode: 0x2, responseDataLength: 0xfbfd.
默认	12:39:12.101619+0800	OBEXAgent	[OBEXSession][serverHandleIncomingData] finalBitSet: 0, responseCode = 0x2, mMaxPacketLength = 0xfffe.
默认	12:39:12.102336+0800	OBEXAgent	HIDAnalytics Set Value Send event com.apple.iokituser.hid.iohidpostevent
默认	12:39:12.102364+0800	OBEXAgent	HIDAnalytics Timer Send event com.apple.iokituser.hid.iohidpostevent
默认	12:39:12.102446+0800	OBEXAgent	HIDAnalytics Unregister Send event com.apple.iokituser.hid.iohidpostevent
默认	12:39:12.102848+0800	OBEXAgent	[Cmd--] entered. inSessionEvent->type = 4f534550
默认	12:39:12.102963+0800	OBEXAgent	[OBEXGetHeaders] Name header found: IMG_20220917_190538.jpg
默认	12:39:12.103060+0800	OBEXAgent	[OBEXGetHeaders] Type header found: image/jpeg
默认	12:39:12.103225+0800	OBEXAgent	[ref] entry: inFileName: IMG_20220917_190538.jpg
默认	12:39:12.105087+0800	tccd	REQUEST: tccd_uid=0, sender_pid=138, sender_uid=88, sender_auid=-1, function=TCCAccessRequest, msgID=138.66
默认	12:39:12.106806+0800	tccd	AUTHREQ_CTX: msgID=138.66, function=<private>, service=kTCCServicePostEvent, preflight=yes, query=1,
默认	12:39:12.106874+0800	tccd	AUTHREQ_ATTRIBUTION: msgID=138.66, attribution={accessing={<TCCDProcess: identifier=com.apple.OBEXAgent, pid=659, auid=501, euid=501, binary_path=/System/Library/CoreServices/OBEXAgent.app/Contents/MacOS/OBEXAgent>}, requesting={<TCCDProcess: identifier=com.apple.WindowServer, pid=138, auid=88, euid=88, binary_path=/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer>}, },
默认	12:39:12.106981+0800	tccd	requestor: <TCCDProcess: identifier=com.apple.WindowServer, pid=138, auid=88, euid=88, binary_path=/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer> is checking access for accessor <TCCDProcess: identifier=com.apple.OBEXAgent, pid=659, auid=501, euid=501, binary_path=/System/Library/CoreServices/OBEXAgent.app/Contents/MacOS/OBEXAgent>
默认	12:39:12.109675+0800	OBEXAgent	[ref]  Path of incoming file: /Volumes/RamDisk/IMG_20220917_190538.jpg
默认	12:39:12.109329+0800	tccd	AUTHREQ_SUBJECT: msgID=138.66, subject=com.apple.OBEXAgent,
错误	12:39:12.110074+0800	OBEXAgent	_dirhelper_relative_internal: error for path <private>: [1: Operation not permitted]
错误	12:39:12.110028+0800	kernel	1 duplicate report for Sandbox: OBEXAgent(659) deny(1) file-read-data /Library/Preferences/com.apple.networkd.plist
错误	12:39:12.110043+0800	kernel	Sandbox: OBEXAgent(659) deny(1) file-read-data /Volumes/RamDisk
错误	12:39:12.110318+0800	kernel	Sandbox: OBEXAgent(659) deny(1) file-write-create /Volumes/RamDisk/IMG_20220917_190538.jpg.sb-ac4f6435-3p4ZOp
默认	12:39:12.112986+0800	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.apple.OBEXAgent, type: 0: 0x7f8ea7816fd0 at /System/Library/CoreServices/OBEXAgent.app
错误	12:39:12.114690+0800	kernel	Sandbox: OBEXAgent(659) deny(1) file-read-data /Volumes/RamDisk
错误	12:39:12.114888+0800	kernel	Sandbox: OBEXAgent(659) deny(1) file-write-create /Volumes/RamDisk/IMG_20220917_190538.jpg.sb-ac4f6435-M7znt7
默认	12:39:12.114399+0800	OBEXAgent	[Accept/Reject]  Path failed, trying: /Volumes/RamDisk/IMG_20220917_190538.jpg...
错误	12:39:12.114729+0800	OBEXAgent	_dirhelper_relative_internal: error for path <private>: [1: Operation not permitted]
默认	12:39:12.116607+0800	OBEXAgent	SetFrontProcess: asn=0x0-0x2d02d options=1
默认	12:39:12.117634+0800	trustd	User has disabled system data installation.

**Comment by Andrey1970AppleLife** [comment]
Write to https://github.com/acidanthera/bugtracker/issues/1821
