### ISSUE TITLE
MaciASL: Line number display bugged

### ISSUE THREAD

**Issue by i0ntempest** [acidanthera/bugtracker#2125]
You may see in the pic that line number display drifts away as it increases and sometimes just breaks.
![Screen Shot 2022-09-23 at 15 54 39](https://user-images.githubusercontent.com/16017904/192047139-e912e96f-4366-40b4-bd21-8adad3638a8d.png)
![Screen Shot 2022-09-23 at 15 54 45](https://user-images.githubusercontent.com/16017904/192047144-c042826e-7fea-41e3-8eba-59a3cf8b7743.png)

**Comment by SkyrilHD** [comment]
Hey! Can you try this modified build? I tested it on my laptop and it seems to be fixed. Will post pull request soon...

[MaciASL-1.6.3-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/9738764/MaciASL-1.6.3-DEBUG.zip)
