### ISSUE TITLE
Intel SST 8086 0x2c8 and ESSX8336

### ISSUE THREAD

**Issue by ameenjuz** [acidanthera/bugtracker#2128]
hi everyone, hi @vit9696 I was wondering seen the numerous notebooks that like huawei matebook d15 has intel sst and Everest sami conductor audio chip  if it is possible to implement this code on apple alc or create a new kext.
my audio is working now fully working on ubuntu 22.04 using alsa sof project
i think Intell SST controller  8086 0X02C8 is usable  because i saw under apple alc supported document
![IntelSST-0x02c8](https://user-images.githubusercontent.com/21066935/192178900-75cb79bd-bb44-4afb-b035-4f2112b8d2a6.jpg)

my HDMI audio IS working  on macOS Monterey and it is detected under ioreg 0x2c8
VEN_8086&DEV_280B
i know that Everest sami conductor not supported yet by AppleALC VEN_ESSX&DEV_8336  is it possible to implement this code?
i will provide codec dump of HDMI and Alsa-info which i extracted using ubuntu
![IntelSST1](https://user-images.githubusercontent.com/21066935/192179749-f4786708-a8a3-431c-8741-15d44c3273dc.jpg)
i attached Alsa-info
please i request all developers to make kext for this ESSX8336
[ESSX8336.zip](https://github.com/acidanthera/bugtracker/files/9642391/ESSX8336.zip)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/2084
