### ISSUE TITLE
OCVALIDATE reports error incorrectly

### ISSUE THREAD

**Issue by MacNB** [acidanthera/bugtracker#2132]
Using Open Duet on Legacy BIOS systems and setting `LoadEarly`=TRUE for OpenRuntime.efi driver causes **ocvalidate** to report an error because OpenVariableRuntimeDxe.efi is not included in the drivers. On Legacy Duet systems, OpenVariableRuntimeDxe.efi is embedded within Duet and so there's no need to include it in the drivers list.

`LoadEarly` was to TRUE for the new emulated NVRAM feature introduced in the earlier version of OC.
Functionally, Opencore boots the system works fine.

ocvalidate error report example:

```
MacNB@iMac-530 ocvalidate % ./ocvalidate /Volumes/EFI/EFI/OC/config.plist
 
NOTE: This version of ocvalidate is only compatible with OpenCore version 0.8.5!


OpenRuntime.efi at UEFI->Drivers[0] should have its LoadEarly set to FALSE unless OpenVariableRuntimeDxe.efi is in use!
CheckUefi returns 1 error!

Completed validating /Volumes/EFI/EFI/OC/config.plist in 2 ms. Found 1 issue requiring attention.
MacNB@iMac-530 ocvalidate %
```

I understand that ocvalidate cannot test/check if the system is Duet or not but the error message is misleading.
Suggest that the error message changes to a warning and reads like:

`OpenRuntime.efi at UEFI->Drivers[0] should have its LoadEarly set to FALSE unless OpenVariableRuntimeDxe.efi or Duet is in use!`

**Comment by MacNB** [comment]
> Setting `LoadEarly=true` on OpenRuntime.efi is only needed when `RequestBootVarRouting` is on, in which case it is needed to allow boot entries stored in `nvram.plist` to restore to the correct place.
> 
> Using `RequestBootVarRouting` makes no sense with OpenDuet, as it is used to avoid OC's boot entries conflicting with the boot entries in the underlying NVRAM, and there is no underlying NVRAM.
> 
> Therefore `RequestBootVarRouting` should never need to be set with OpenDuet, and OpenRuntime.efi does not need `LoadEarly`.

@mikebeaton Thanks for the explanation . 
I assume that by using term "underlying NVRAM", you mean a real solid state NVRAM ? 
For emulated NVRAM on a Legacy BIOS system using OpenDuet, are you saying that:
`RequestBootVarRouting` should be FALSE and
`LoadEarly` should be FALSE for OpenRuntime.efi 
??

If yes, then this should be stated explicitly in the configuration.pdf since it's ambiguous currently.

**Comment by mikebeaton** [comment]
I'd go for 'implicit' rather than 'ambiguous' ;) , but agreed, updated.

https://github.com/acidanthera/OpenCorePkg/commit/9de7ab1afa7f3eea72d147943165b75ebe303f5f

**Comment by MacNB** [comment]
> I'd go for 'implicit' rather than 'ambiguous' ;) , but agreed, updated.
> 
> [acidanthera/OpenCorePkg@9de7ab1](https://github.com/acidanthera/OpenCorePkg/commit/9de7ab1afa7f3eea72d147943165b75ebe303f5f)

@mikebeaton Perfect. Many thanks for the quick change. Keep up the great work.
