### ISSUE TITLE
6600 XT black screen after wakes from hibernation

### ISSUE THREAD

**Issue by junzhli** [acidanthera/bugtracker#2133]
Hello,

I've been using HibernationFixup to get hibernation working for a while. Last working stuff is 5700 (without XT). Sleep and hibernation works well.
This time I swap this for 6600 XT, and hibernation no longer works but sleep.
I am not sure if there's something wrong here. I just put my EFI folder and others for references (e.g. Kernel panic crash report, OC boot.log, Lilu dump log with debug kexts: Lilu, Whatevergreen and Lilu)

It looks like going to black screen, but i notice there's no network activity after wake from hibernation. The symptom seems to be system hangs
Few times will result in auto crash restart, which there's Apple crash report prompt window showing after reboot, saying that windowserver timeout for 120 seconds (seems like graphic card driver dropped?)

I am wondering if there's probably something wrong with hibernationfixup or whatevergreen, thanks!
[KP diag files.zip](https://github.com/acidanthera/bugtracker/files/9720994/KP.diag.files.zip)
[OC logs.zip](https://github.com/acidanthera/bugtracker/files/9720995/OC.logs.zip)
[Lilu plugin logs.zip](https://github.com/acidanthera/bugtracker/files/9720996/Lilu.plugin.logs.zip)
[OC.zip](https://github.com/acidanthera/bugtracker/files/9720997/OC.zip)

**Comment by junzhli** [comment]
New findings is on power log (pmset -g log)
The log shows after each failure on hibernation wake
```
Time stamp                Domain              	Message                                                                    	Duration  	Delay
==========                ======              	=======                                                                    	========  	=====
UUID: Unknown UUID
2022-10-06 17:40:55 +0800 Sleep               	Entering Sleep state due to '': Using AC (Charge:0%)
2022-10-06 17:40:55 +0800 Failure             	Failure during wake: PEG0(),SAT0(AppleAHCI),HDAS() : Some drivers failed to handle setPowerState
Sleep/Wakes since boot at 2022-10-06 17:34:48 +0800 :0   Dark Wake Count in this sleep cycle:3
```

**Comment by Hush-vv** [comment]
Delete PP in config.plist_ PhmSoftPowerPlayTable Try

**Comment by junzhli** [comment]
@Hush-vv I tried but it didn't work for me
