### ISSUE TITLE
Bluetooth not working with DCM_4350C2 on moterey even following the guide

### ISSUE THREAD

**Issue by gabrielpinno** [acidanthera/bugtracker#2136]
Bluetooth is not working with DCM_4350C2 on moterey even following the guide, it is returning me the bluetoothd error still in the logs
![print](https://user-images.githubusercontent.com/95237824/194920327-ebe0aa60-5167-4fc9-9033-b1ba150f92c5.png)

**Comment by Andrey1970AppleLife** [comment]
Write to https://github.com/acidanthera/bugtracker/issues/1821
