### ISSUE TITLE
[FV2] Boot from external drive with enabled encryption

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2141]
- OpenCore version: 0.8.5
- Kexts version: don't think it actually matters but I'm using latest stable version of the followings:

    - AppleALC.kext
    - GenericCardReaderFriend.kext
    - Lilu.kext
    - NVMeFix.kext
    - SMCBatteryManager.kext
    - SMCDellSensors.kext
    - SMCProcessor.kext
    - VirtualSMC.kext
    - VoodooI2C.kext
    - VoodooI2CHID.kext
    - VoodooPS2Controller.kext
    - WhateverGreen.kext

## Actual behaviour

OpenCore doesn't detect FV2 enabled encryption drives

## Expected behaviour

OpenCore detects FV2 enabled encryption drives

## Short description of the problem

Without any FV2 password, OpenCore is able to detect and boot FV2 drives, but whenever password encryption is enabled, OpenCore isn't able to detect the drives. Is this behaviour a thing that also real Macs have? Eventually can OpenCore be able to decrypt FV2 drives and boot from them?

**Comment by khronokernel** [comment]
Please provide logs, EFI configuration and machine info, OpenCorePkg should support FileVault 2 encrypted drives with a password. Both Macs using OpenCore and PCs are supported

**Comment by dreamwhite** [comment]
> Please provide logs, EFI configuration, OS version and machine info, OpenCorePkg should support FileVault 2 encrypted drives with a password. Both Macs using OpenCore and PCs are supported

I'm doing my tests on an external drive that is connected to my Dell Inspiron 5370.
My EFI configuration is available here: https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/tree/beta-testing
OS version is macOS Ventura RC2 but I don't think the installed macOS version matters.

Instead, does it matter that I'm using an external drive with two APFS volumes (one for macOS and another one for TM)?
I'm booting now with the logs. Give me a few mins

**Comment by dreamwhite** [comment]
@khronokernel I forgot to mention that my EFI has serial numbers inside it. Can I send you an email with the logs? I'm kinda worried about spreading my serial numbers on a public website haha

**Comment by khronokernel** [comment]
Just strip serial numbers

**Comment by dreamwhite** [comment]
Here you are the stripped log: [opencore-2022-10-24-165054.txt](https://github.com/acidanthera/bugtracker/files/9853752/opencore-2022-10-24-165054.txt)

**Comment by dreamwhite** [comment]
@khronokernel sorry for the bump, any update?
