### ISSUE TITLE
Please enable mic modes on older Macs with FeatureUnlock

### ISSUE THREAD

**Issue by JonathanX64** [acidanthera/bugtracker#2142]
Hello!

Since Monterey, macOS has one more feature that is purely SMBIOS locked, and that is [Mic modes on a Mac](https://support.apple.com/en-ph/guide/mac-help/mchle82b42f0/13.0/mac/13.0).

It works on Intel machines, even without T2, such as 2019 iMacs. 

It would be awesome if FeatureUnlock enabled this feature as well.

If I posted this to the wrong place, please redirect me there, as there are no issue pane at [project's GitHub](https://github.com/acidanthera/FeatureUnlock).

Thank you.

**Comment by khronokernel** [comment]
I'm not familiar with any blacklists on mic controls in Monterey, do you know the framework responsible for the blacklist? I usually keep an eye on blacklists inside the dyld from time to time, haven't noticed anything

Are you certain this isn't a hardware requirement of the mic?

**Comment by mikebeaton** [comment]
Sorry - you're stating that it does run without T2. Re-opened. But are you sure about this?

**Comment by JonathanX64** [comment]
Quite sure. This feature works on 2019 iMacs. 

I _believe_ it also worked on my Coffee Lake Hackintosh with iMac19,2 SMBIOS and analog 3.5mm mic connected to ALC897 using AppleALC, but I don't have that hardware with me at the moment, so can't say with 100% certainty.

**Comment by khronokernel** [comment]
Tested the following:

* 2016 13" MacBook Pro (MacBookPro13,1) -> 2018 13" MacBook Pro (MacBookPro15,2)
* 2014 Mac mini (Macmini7,1) -> 2018 Mac mini (Macmini8,1) and 2019 Mac Pro (MacPro7,1)

Unfortunately neither machines were able to active Mic Modes. This does lead me to believe it's a hardware limitation (ie. Coffee Lake hardware) and not SMBIOS. Would line up with the lack of blacklists I could find.

As you no longer have affected hardware and we're unable to replicate, will close this issue. However if you or anyone else is able to replicate only under a 2018 or newer SMBIOS, I'd be interested in re-opening this issue and probing your machine further.
