### ISSUE TITLE
Opencore not showing macOS volumes

### ISSUE THREAD

**Issue by Dr-Itachi** [acidanthera/bugtracker#2144]
Hi. I've been using an old version of Opencore for almost a year now (the one from January 2021). I wanted to update Opencore to the latest release. I used the Dortania doc and the Opencore doc as well as OcCompare and ocvalidate. The settings are almost the same with the old config but no macOS volume (my Bigsur install, the recovery, the Monterey installer) is displayed in the picker I don't know why. here is the log file

[opencore-2022-10-27-225700.txt](https://github.com/acidanthera/bugtracker/files/9888273/opencore-2022-10-27-225700.txt)

**Comment by dreamwhite** [comment]
Given that this isn't a support forum...

What about `UEFI/APFS` `MinDate` and `MinVersion` values?
Have you tried setting them to `-1`?
Is your `ScanPolicy` (under `Misc/Security`) properly set?

**Comment by Dr-Itachi** [comment]
> Given that this isn't a support forum...
> 
> What about `UEFI/APFS` `MinDate` and `MinVersion` values? Have you tried setting them to `-1`? Is your `ScanPolicy` (under `Misc/Security`) properly set?
> 
> Also please note that your config.plist isn't compliant to OpenCore 0.8.6 specs. Please use ocvalidate to fix the warnings

Thanks for your reply. I tested several values of the minimum and maximum versions (-1 by default, 16000000000000 and 20210101) but none worked. I am on Bigsur 11.1
My scanpolicy is set to 0 like on my old config.plist
I'm not on 0.8.6 but on 0.8.5 and I used ocvalidate everything was ok

**Comment by mikebeaton** [comment]
Have a look at the OCJS lines in the log (for OpenCore APFS jump start).

**Comment by Dr-Itachi** [comment]
> Have a look at the OCJS lines in the log (for OpenCore APFS jump start).

Got it thanks. And what about the HFS+ volumes which didn’t shows ?

**Comment by mikebeaton** [comment]
Bugtracker is to report bugs and issues w/ OC and related projects. No bug here.

**Comment by Dr-Itachi** [comment]
> Bugtracker is to report bugs and issues w/ OC and related projects. No bug here.

Thanks for your attention. All my issues solved. It was a problem with my Apfs minDate and minVersion
