### ISSUE TITLE
Whatevergreen

### ISSUE THREAD

**Issue by Touchiestworm** [acidanthera/bugtracker#2146]
I know of at least 2 users one being myself where our gpu’s AMD rx570 and coffeelake i5 uhd 630 are not showing up in about this mac and not showing a display connected under graphics in system profiler. 
my system-ga-z97-hd3 rev 2.1
                  Intel i3 4130 hd4400-disabled in bios
                   Asrock phantom gaming RX570
             Latest kexts and drivers with opencore 8.5 

The rx570 showed up in big sur but disappeared in Monterey. There appears to be no lack of performance with either intel or amd. 
i hope we can figure this out. Thank you

**Comment by Touchiestworm** [comment]
![740B3820-D6AF-4227-A8E6-D588A5E620B3](https://user-images.githubusercontent.com/108630967/198925227-144d37a3-2d13-4c2d-9682-4bc7502894c2.jpeg)
![00755315-37ED-4E67-B3B6-3E0831AC2A67](https://user-images.githubusercontent.com/108630967/198925231-69342d39-f454-4011-9d56-6c64e6935be0.jpeg)
![048DCCDB-6C0F-4DA1-9CB6-536B33C41332](https://user-images.githubusercontent.com/108630967/198925234-6376bdef-5a1f-48ab-b3b1-fbd9ea950044.jpeg)

**Comment by khronokernel** [comment]
Apple would need to resolve it themselves, would be out of scope for WEG. If the system is headless, macOS won't initialize a GPU in About this Mac.
