### ISSUE TITLE
RX5500XT does not work HDMI audio

### ISSUE THREAD

**Issue by Lorys89** [acidanthera/bugtracker#2147]
I have already tried everything, with and without weg on smbios imacpro and mac pro, on system preferences it always sees hdmi audio but the sound never comes out

![Screenshot 2022-10-31 alle 12 40 32](https://user-images.githubusercontent.com/64613690/199000184-f9f4d53c-086a-4cfa-adb4-ad71bc123d87.png)
[iMac di Lorys.zip](https://github.com/acidanthera/bugtracker/files/9900722/iMac.di.Lorys.zip)

gpu model pulse rx5500xt 4gb gddr6, the other 3 dp outputs instead give out sound
i tried to inject different frambuffers and put hda-gfx onboard-1 but no result on hdmi audio.
I also have the pulse rx5600xt and with that card I have audio on hdmi

rx5500xt :
![Screenshot 2022-10-31 alle 12 58 14](https://user-images.githubusercontent.com/64613690/199003107-9549b773-371d-498f-98b0-98bb34b778c0.png)

rx5600xt:
![Screenshot 2022-10-31 alle 12 59 55](https://user-images.githubusercontent.com/64613690/199003258-55b0f116-982c-48f5-bbc9-0daa2ec0de64.png)
rx5600xt ioreg - hdmi sound work : 
[Mac Pro lorys - rx5600xt.zip](https://github.com/acidanthera/bugtracker/files/9900824/Mac.Pro.lorys.-.rx5600xt.zip)

**Comment by mikebeaton** [comment]
Firstly, it's good to be sure it's wired up correctly, e.g. do Windows or Linux produce HDMI sound w/ no problems on the system?

Secondly, even if that does work, not a support forum, sorry - so please try forums for config assistance.

**Comment by Lorys89** [comment]
@mikebeaton But do you think I opened issue if even on windows it worked? Obvious that on windows works audio on hdmi, it's not a cable problem. And in the support forums they say to inject hda-gfc onboard-1 and it does not work or to use w5500 ssdt or framebuffers specific to navi rx5500xt series and none of these output audio from hdmi. 
I wrote here to see if it can be fixed in kext. 
If you consider this issue invalid ok.

**Comment by mikebeaton** [comment]
That was not obvious to me, or I would not have asked.

And I don't consider the issue invalid _for you_, I agree you have the issue. But I do currently consider it invalid for this bugtracker. It sounds like a configuration issue (maybe, or maybe not a simple one, but a configuration issue nonetheless), and not a bug or OC or associated tools. If that's correct, it's invalid for this bugtracker, and must be addressed for forums. (Where you may find OC developers, and will find other experienced users, to help.)

**Comment by mikebeaton** [comment]
Note that closed issues _are_ read on this bugtracker. If you find further evidence, post it here. You could try to ping the original author of your layout on AppleALC, to see if they are still available to help. Otherwise you may need to read up on AppleALC and then fix and improve layout, for yourself and future users (!), if the issue lies there.

**Comment by Lorys89** [comment]
The alc layout does not enter, on the same board z490 if I mount the rx5600xt and the monitor / tv output hdmi I will have video and sound working if I mount the rx5500xt on the hdmi output I will have a working monitor but without sound, and on orefere5sustena audio will appear monitor audio but the sound does not come out, same motherboard and same audio layout. Both gpu cards are sapphire pulse.
If you want more information ask and I will be ready for any test, otherwise sorry if I disturbed you.

**Comment by joaobertacchi** [comment]
@Lorys89 , do you have news on that? I also have a RX 5500 XT and am facing the same problem. Actually many users from a Discord channel I follow are facing that problem :(
