### ISSUE TITLE
About this Mac doesn't show the IGPU

### ISSUE THREAD

**Issue by puna27** [acidanthera/bugtracker#2148]
I have a i5 9400 intel processor which doesn't show the igpu information in about this mac. Please help.
![313303509_104724665778649_6448589867300242164_n](https://user-images.githubusercontent.com/77014939/199016281-ace015e9-ea11-438a-a182-4fb0293b8b43.jpg)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/2146
