### ISSUE TITLE
LapicKernelPanic quirk doesn't work on macOS Ventura

### ISSUE THREAD

**Issue by qBughi** [acidanthera/bugtracker#2149]
Hello, I have a working macOS Monterey system, but when I boot into macOS Ventura, it gets stuck here at AppleACPICPU, then it immediately reboots. 
As I found it thanks to someone, its because of the LapicKernelPanic quirk, because if I disable it, macOS Monterey also gets stuck exactly there and then it reboots, it behaves exactly like on Ventura, so because I have a HP laptop I require this quirk enabled to boot. I also tried the lapic_dont_panic=1 boot arg but it also didn't work.
OpenCore 0.8.5 and all kexts are up to date.
Where it gets stuck:

![IMG_5647](https://user-images.githubusercontent.com/70108105/200126945-668f18e6-114e-4b41-ba3e-ac49e5142259.jpg)

Hardware:
HP ENVY - 15-as103nq, i7-7500u, Intel HD Graphics 620, no dGPU and 512 GB SSD.
Maybe an OpenCore update or something else can fix this?

**Comment by andreszerocross** [comment]
I just install macOS Ventura in HP Elitebook X360 830 G6. Lapic Kernel patch still work

**Comment by sh4tteredd** [comment]
I'm facing a similar issue, probably it's correlated

**Comment by PMheart** [comment]
I can confirm that lapic patch still works. Please post on forums for support.
