### ISSUE TITLE
[Feature Request] Add SATA info in SysReport 

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2151]
It could be useful having a dump of attached ATA/ATAPI peripherals, that are not in PCI mode (e.g. `M.2. NGFF SATA` drives).

e.g. of possible output

![image](https://user-images.githubusercontent.com/17933708/200428562-9aacce98-2717-41a7-a286-19eb4844163a.png)

**Comment by vit9696** [comment]
That would require some effort. We will unlikely do this, but we can accept patches if they appear.
