### ISSUE TITLE
NVRAM - RT.GV wake-failure \\boot\\BootKernelExtensions.kc Software Update Post Logout

### ISSUE THREAD

**Issue by xavierbaez** [acidanthera/bugtracker#2152]
Opencore 0.8.6 release.
All Kexts are updated.
Installed the latest Kernel patches from AMD_Vanilla.

![IMG_0223](https://user-images.githubusercontent.com/1647474/200618957-787b9d05-c804-45fa-8f50-0085e6f39737.jpeg)

[EFI.zip](https://github.com/acidanthera/bugtracker/files/9963225/EFI.zip)

**Comment by dreamwhite** [comment]
Given that's not a support forum, and you should ask elsewhere...
Check the following:
- `MAT Support` status
- `HFS` scanning driver. In the attached EFI there are both `HfsPlus.efi` and `OpenHfsPlus.efi`. Choose just one of them
