### ISSUE TITLE
FeatureUnlock v1.1.0: AirPlay server patch regressed

### ISSUE THREAD

**Issue by i0ntempest** [acidanthera/bugtracker#2153]
On Macmini8,1 SMBIOS, previously working AirPlay server (with 1.0.9) is gone with FeatureUnlock 1.1.0.
EFI attached, debug log will be provided if needed.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/9976292/EFI.zip)

**Comment by i0ntempest** [comment]
Anywhere I could get a build with this commit? I remember someone mentioned master build are made every now and then?

**Comment by 1alessandro1** [comment]
@i0ntempest 
https://github.com/dortania/build-repo/releases/download/FeatureUnlock-c3b4cbb/FeatureUnlock-1.1.1-RELEASE.zip

**Comment by 1alessandro1** [comment]
To get all builds
https://dortania.github.io/builds/?product=FeatureUnlock&viewall=true

**Comment by koolwiki** [comment]
Could any one tell me how to set kern.hv_vmm_present to 1? As the readme file of FeatureUnlock v1.1.0 says that "Systems with 'kern.hv_vmm_present' set to as 1 (Ventura and newer)". I upgraded the macOS to Ventura, but I don't how to set kern.hv_vmm_present to 1. Thank you.
