### ISSUE TITLE
OpenCore 0.8.6 showing blank/black screen before picker while trying to play chime

### ISSUE THREAD

**Issue by v01der** [acidanthera/bugtracker#2157]
OpenCore 0.8.6 showing blank/black screen before picker while trying to play chime
I tried AudioDxe which is provided with said version
after disabling the chime I can boot 
if required this is oc logs 
[opencore-2022-11-11-201112.txt](https://github.com/acidanthera/bugtracker/files/9991133/opencore-2022-11-11-201112.txt)

**Comment by mikebeaton** [comment]
Can you send your config.plist as well - redact serials if you want to first

**Comment by v01der** [comment]
> Can you send your config.plist as well - redact serials if you want to first

there it is and I have 5950x with Asus dark hero 8 x570 with 6800xt and sn850
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/9991730/config.plist.zip)

**Comment by mikebeaton** [comment]
```
			<key>SetupDelay</key>
			<integer>500000</integer>
```

This is now in milliseconds (updated fairly recently). So if you wait 8 minutes, or change the value, it should boot. ;)
