### ISSUE TITLE
Elan trackpad not working in dual boot with Windows 11

### ISSUE THREAD

**Issue by XCroatoanX** [acidanthera/bugtracker#2158]
I have installed Hackintosh Ventura on my machine aside my Windows 11. Everything worked fine, until I have changed my main boot manager from Windows Boot Manager to OpenCore. I tried reinstalling touchpad drivers, make a clean Windows install, but everything without success. After that I have checked my Device Manager and saw a strange error 10 on my I2C touchpad driver.

**Comment by Andrey1970AppleLife** [comment]
Write to developers VoodooI2C
