### ISSUE TITLE
[BUG] Cannot dump Z690 SysReport

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2160]
On several Z690 chipset boards, even using OpenCore 0.8.6 official DEBUG release to obtain the `SysReport` folder, dumps only `PCI` stuff. From the logs I could obtain, the ACPI tables gets exposed but nothing else.
Is this a bug that you can actually reproduce by yourself? If needed I can provide all the necessary info.
BIOS is properly configured and the same EFI which produces `SysReport` folder works in a `Z590` chipset system.

**Comment by dreamwhite** [comment]
Example of borked [SysReport.zip](https://github.com/acidanthera/bugtracker/files/10026117/SysReport.zip)

**Comment by vit9696** [comment]
This looks like a file system corruption or a driver bug. Try reformatting your partition and retrying.

**Comment by dreamwhite** [comment]
Hi, I tested multiple drives formatted both using Rufus from Winblows and `mkfs -t vfat` but the issue is still the same.
I don't know if that's a FS corruption, because the `.txt` log file is correctly created onto the drive, as well as `PCIInfo.txt` under `SysReport/PCI`. I'm pretty sure it's a driver bug, but I don't have enough knowledge on how to debug it.

Do you have any clue?

**Comment by vit9696** [comment]
Can you confirm the following please:

- Latest OpenCore master (DEBUG)
- On a particular Z690 board (need name and vendor)
- With the latest BIOS (please name one)
- With a freshly formatted USB flash (use Disk Utility to simply get an HFS+ drive GPT)
- With OpenCore files residing on EFI (ESP partition) on this USB flash
- Without any logs or SysReport directories before a reboot

Result in no ACPI files in SysReport despite explicitly being logged as saved in the log? I will need both the log and complete ESP contents.

Please check this step by step with 2 USB flash sticks.
