### ISSUE TITLE
ASSERT: `8gEfiDpcProtocolGuid`

### ISSUE THREAD

**Issue by BetaPictoris** [acidanthera/bugtracker#2161]
## Issue

OpenCore crashes before the boot prompt when using the "debug" build after printing this error: 
```
03:410 00:029 ASSERT [DpcDxe] Dpc.c(320): &gEfiDpcProtocolGuid already installed in database
```
Although, when using the "release" build this does not happen. 

## Details

```
Host: Surface Laptop 3
CPU: Intel i5-1035G7 (8) @ 3.700GHz (Ice Lake)
GPU: Intel Iris Plus Graphics G7
Memory: 8GBs
OpenCore version: 0.8.6 (DEBUG)
```

[OpenCore log](https://gist.github.com/BetaPictoris/8f81938080ffb95b372d8b0566278093)
[EFI tree](https://gist.github.com/BetaPictoris/487f34839ae7db648ea791b07c60fc26)

**Comment by khronokernel** [comment]
Doesn't this just mean your firmware already includes the DPC protocol?
* <https://github.com/acidanthera/audk/blob/d2f79716cb67c0487433b159f882015773dd18b7/NetworkPkg/DpcDxe/Dpc.c#L320>
* <https://github.com/acidanthera/audk/blob/d2f79716cb67c0487433b159f882015773dd18b7/MdePkg/Include/Library/DebugLib.h#L505-L546>

Thus it is asserting as it should on debug variants, your system already has DPC protocol bundled with it.

**Comment by mikebeaton** [comment]
You appear to have loaded new drivers mentioned in `SampleCustom.plist` - added by https://github.com/acidanthera/OpenCorePkg/commit/7e69946021c8d8662dc9fb55b51ca90b7b84ce60 - which you do not need.

**Comment by BetaPictoris** [comment]
> Doesn't this just mean your firmware already includes the DPC protocol?
> 
> * https://github.com/acidanthera/audk/blob/d2f79716cb67c0487433b159f882015773dd18b7/NetworkPkg/DpcDxe/Dpc.c#L320
> * https://github.com/acidanthera/audk/blob/d2f79716cb67c0487433b159f882015773dd18b7/MdePkg/Include/Library/DebugLib.h#L505-L546
> 
> Thus it is asserting as it should on debug variants, your system already has DPC protocol bundled with it.



> You appear to have loaded new drivers mentioned in `SampleCustom.plist` - added by [acidanthera/OpenCorePkg@7e69946](https://github.com/acidanthera/OpenCorePkg/commit/7e69946021c8d8662dc9fb55b51ca90b7b84ce60) - which you do not need.

Thank you! I've removed DPC now.

**Comment by mikebeaton** [comment]
I would remove all of those drivers mentioned in that list, btw, you do not need any of them - `SampleCustom.plist` is not a place from which to take new changes whole, it shows how things might be configured, if you need them. You need to understand or research whether you do need them!
