### ISSUE TITLE
The audio on the front panel of the case with the codec ALC662 does not work

### ISSUE THREAD

**Issue by Drovosek01** [acidanthera/bugtracker#2164]
Hello.

I have a computer based on a Chinese x79 motherboard with the following characteristics:

QIYIDA x79 lga2011 | Xeon E5 2670 v2 (Ivy Bridge-EP) | Sapphire RX580 Nitro+ 4Gb | 64GB 1866MHz RAM

Audio is Realtek ALC662.

I use AppleALC v1.7.6 with OpenCore 0.85 kext for make work audio im my hackintosh and now I use it with layout 5 and audio work only from the back side of the case. I have tried absolutely all the layouts that are listed for the ALC662 codec in the official table (and some unofficial layouts), but the sound has not been played through the port on the front panel of the system unit
https://github.com/acidanthera/applealc/wiki/supported-codecs

Here is the original DSDT that I extracted in Windows using SSDT Time
https://github.com/acidanthera/bugtracker/files/10074718/DSDT.aml.original.zip

**Comment by Drovosek01** [comment]
> Create your own layout id if none work correctly for you. Not a bug.

Please give link for instruction or tutoral how can I fix wrote problem

**Comment by Core-i99** [comment]
https://github.com/5T33Z0/AppleALC-Guides
Go to support forums if you need help, list is in the OC repo
