### ISSUE TITLE
CryptexFixup work automatily only if update from previous version macOS?

### ISSUE THREAD

**Issue by Drovosek01** [acidanthera/bugtracker#2167]
Hello.

I installed macOS Monterey on my computer on the x79 platform.

Basically, I don't need macOS Ventura right now, but since I haven't set up Monterey yet, I decided to install Ventura just to see if it's possible on my hardware.

My hardware:
QIYIDA x79 lga2011 | Xeon E5 2670 v2 (Ivy Bridge-EP) | Sapphire RX580 Nitro+ 4Gb | 64GB 1866MHz RAM

I made a bootable flash drive with macOS Ventura and added kext CryptexFixup to EFI, then I started the installation of macOS Ventura, formatted the APFS volume to install the new OS and installed Ventura from the flash drive to a clean APFS volume. After the installation was completed, the computer restarted and an item with macOS Ventura appeared in the OpenCore menu. When I try to launch macOS Ventura from OpenCore, I get a panic every time.

Then I reread the Readme of kext CryptexFixup and saw the text
> Thus to support older machines, this kext will force the macOS installer/updater to install the Apple Silicon Cryptex (OS.dmg) instead of the stock Intel variant

That is, this quest works correctly only if you install an update to macOS Ventura from under an already installed macOS? Should I install this kext before I start downloading the update? If I unpack the macOS Ventura installer by running InstallAssistant.pkg, then add a kext to EFI, restart the current macOS, and after restarting from the interface of a running macOS, start installing macOS Ventura - will this kext work? Can I somehow revive an already installed macOS Ventura?

**Comment by khronokernel** [comment]
> That is, this quest works correctly only if you install an update to macOS Ventura from under an already installed macOS? 

Clean installs and upgrades are supported with CryptexFixup, however delta updates from System Preferences are not supported. You will need the full installer to function correctly. Note that USB installers are the correct approach, in-OS upgrades can present additional issues.

> When I try to launch macOS Ventura from OpenCore, I get a panic every time.

This is too vague, is the panic even related to CryptexFixup's work? Or is it just an unrelated panic.

> Can I somehow revive an already installed macOS Ventura?

Install on top of the existing installation. 
* ie. create Ventura USB, and boot it with CryptexFixup active.

----------

Otherwise, please use forums for further support

**Comment by Drovosek01** [comment]
@khronokernel 
Here my debug ESP with logs https://mega.nz/file/ygs0lBhY#YHhT6I8QSeSVskrXUMhI60VsDqv0vVLJgVvlrVBO0oc

Can you look it please? CryptexFixup is active in config and EFI

**Comment by khronokernel** [comment]
Nothing attached indicates CryptexFixup is at fault, again please use forums for support

**Comment by Drovosek01** [comment]
I noticed that in my config the very use/inclusion of the CryptexFixup kext is disabled. I turned it on and tried to boot - nothing worked.
Then I reinstalled macOS Ventura and it was reinstalled normally, but at the stage when I need to create an account and so on - I just have black screens (with the backlight turned on in them).

Perhaps if you don't use this kext, but use a patch in the config + files from .ipsw like this:
https://www.youtube.com/watch?v=0jUsJpzgZnU or https://github.com/dortania/OpenCore-Legacy-Patcher/issues/998#issuecomment-1163607808
maybe Ventura will work, but I don't want to waste time on this, a simple attempt failed, and I didn't strive for Ventura.

Thank you for taking the time to answer.

**Comment by demohg3** [comment]
@khronokernel First I’d like to say how grateful I am for the whole team and conception of this entire project and any others along with it. I’m am a proud user and supporter of you guys and will continue until the wheels fall off. I can’t at the exact moment but would love to donate and add to said support, so this is in the near plans. Also I am aware of the affect the conflict in your country has on this sort of thing and what must be prioritized. I noticed that there was no way to send a message or input a new request so I decided to post where it seemed the best and open lol

Although I’m sure the contributors has a slew of things to take care of and these are not at all easily tackled task; but I have one bit of input for now. Also, it’s clear that Sonoma and other older machine errors are the big new focus currently and most other things may fall to the wayside. BUT ! I’m writing this to beg, plead, and hope that in the next release, the last set of the AMD Navi RX 5xxx/6xxx (10/20 series) Graphics Stacks are supported with patching. 

The last update mentioned the donation of an AMD RX 6600 and a warning that no time estimate could be given, but I’m gonna be that guy and ask if this has been resolved yet (please lol). Last month, I downgrade from Ventura to Monterey to make my own new AMD RX 6600 compatible and sooner after was met with an ‘Uninitialized’ secondary hard drive (not sure, maybe faulty installation)(fingers-crossed all isn’t unrecoverable lol). Either way, on my machine, Ventura is definitely much more stable, so this is the last piece of the puzzle. Hell I’ll even loan my own graphics card (not fully paid for) for testing, if that’s what it takes. Lmao

**Comment by demohg3** [comment]
First I’d like to say how grateful I am for the whole team and conception of this entire project and any others along with it. I’m am a proud user and supporter of you guys and will continue until the wheels fall off. I can’t at the exact moment but would love to donate and add to said support, so this is in the near plans. Also I am aware of the affect the conflict in your country has on this sort of thing and what must be prioritized. I noticed that there was no way to send a message or input a new request so I decided to post where it seemed the best and open lol

Although I’m sure the contributors has a slew of things to take care of and these are not at all easily tackled task; but I have one bit of input for now. Also, it’s clear that Sonoma and other older machine errors are the big new focus currently and most other things may fall to the wayside. BUT ! I’m writing this to beg, plead, and hope that in the next release, the last set of the AMD Navi RX 5xxx/6xxx (10/20 series) Graphics Stacks are supported with patching. 

The last update mentioned the donation of an AMD RX 6600 and a warning that no time estimate could be given, but I’m gonna be that guy and ask if this has been resolved yet (please lol). Last month, I downgrade from Ventura to Monterey to make my own new AMD RX 6600 compatible and sooner after was met with an ‘Uninitialized’ secondary hard drive (not sure, maybe faulty installation)(fingers-crossed all isn’t unrecoverable lol). Either way, on my machine, Ventura is definitely much more stable, so this is the last piece of the puzzle. Hell I’ll even loan my own graphics card (not fully paid for) for testing, if that’s what it takes. Lmao

**Comment by demohg3** [comment]
@khronokernel First I’d like to say how grateful I am for the whole team and conception of this entire project and any others along with it. I’m am a proud user and supporter of you guys and will continue until the wheels fall off. I can’t at the exact moment but would love to donate and add to said support, so this is in the near plans. Also I am aware of the affect the conflict in your country has on this sort of thing and what must be prioritized. I noticed that there was no way to send a message or input a new request so I decided to post where it seemed the best and open lol

Although I’m sure the contributors has a slew of things to take care of and these are not at all easily tackled task; but I have one bit of input for now. Also, it’s clear that Sonoma and other older machine errors are the big new focus currently and most other things may fall to the wayside. BUT ! I’m writing this to beg, plead, and hope that in the next release, the last set of the AMD Navi RX 5xxx/6xxx (10/20 series) Graphics Stacks are supported with patching. 

The last update mentioned the donation of an AMD RX 6600 and a warning that no time estimate could be given, but I’m gonna be that guy and ask if this has been resolved yet (please lol). Last month, I downgrade from Ventura to Monterey to make my own new AMD RX 6600 compatible and sooner after was met with an ‘Uninitialized’ secondary hard drive (not sure, maybe faulty installation)(fingers-crossed all isn’t unrecoverable lol). Either way, on my machine, Ventura is definitely much more stable, so this is the last piece of the puzzle. Hell I’ll even loan my own graphics card (not fully paid for) for testing, if that’s what it takes. Lmao

**Comment by demohg3** [comment]
@khronokernel First I’d like to say how grateful I am for the whole team and conception of this entire project and any others along with it. I’m am a proud user and supporter of you guys and will continue until the wheels fall off. I can’t at the exact moment but would love to donate and add to said support, so this is in the near plans. Also I am aware of the affect the conflict in your country has on this sort of thing and what must be prioritized. I noticed that there was no way to send a message or input a new request so I decided to post where it seemed the best and open lol

Although I’m sure the contributors has a slew of things to take care of and these are not at all easily tackled task; but I have one bit of input for now. Also, it’s clear that Sonoma and other older machine errors are the big new focus currently and most other things may fall to the wayside. BUT ! I’m writing this to beg, plead, and hope that in the next release go OCLP, the last set of the AMD Navi RX 5xxx/6xxx (10/20 series) Graphics Stacks are supported with patching. 

The last update mentioned the donation of an AMD RX 6600 and a warning that no time estimate could be given, but I’m gonna be that guy and ask if this has been resolved yet (please lol). Last month, I downgrade from Ventura to Monterey to make my own new AMD RX 6600 compatible and sooner after was met with an ‘Uninitialized’ secondary hard drive (not sure, maybe faulty installation)(fingers-crossed all isn’t unrecoverable lol). Either way, on my machine, Ventura is definitely much more stable, so this is the last piece of the puzzle. Hell I’ll even loan my own graphics card (not fully paid for) for testing, if that’s what it takes. Lmao
