### ISSUE TITLE
OpenCore break CPU sensors (and power managment?) in Windows

### ISSUE THREAD

**Issue by Drovosek01** [acidanthera/bugtracker#2168]
Hello.

A couple of days ago, I noticed when I installed macOS Monterey, macOS Mojave and Windows 10 on my computer, I was putting tests in benchmarks and looking at my CPU and GPU data.

I noticed that in Windows 10, the CPU frequency in programs such as HWiNFO64 and HWMonitor did not change the value of the core frequency, although judging by the task manager, there was almost no load on the cores.
https://www.hwinfo.com/
https://www.cpuid.com/softwares/hwmonitor.html

I thought that the problem was in the CPU power settings in bios/UEFI or in the power settings in Windows, but changing these settings did not change the situation in any way.
I also tried to run Windows through OpenCore by disabling all .aml files and most of the efi drivers in the config, but again nothing has changed.

Then I started Windows via bios/UEFI by changing the boot priority, and then in the above programs, the change in the frequency of processor cores began to be displayed again.

Is this a bug in OpenCore or is this behavior of monitoring programs affected by some configuration settings of OpenCore 0.86?

I recorded a video demonstration of the process so that it would be more convenient for you to understand the essence of the problem.
The essence of the problem:
When I run Windows 10 via OpenCore, the core frequency through hardware monitoring programs is always displayed as 2.5 GHz

Video:
https://www.youtube.com/watch?v=IAw3GGu6pCs

My hardware:
QIYIDA x79 lga2011 | Xeon E5 2670 v2 (Ivy Bridge-EP) | Sapphire RX580 Nitro+ 4Gb | 64GB 1866MHz RAM

Report from AIDA64:
[Report AIDA64.zip](https://github.com/acidanthera/bugtracker/files/10137356/Report.AIDA64.zip)

ESP used on video:
https://mega.nz/file/e1FGnTwA#OWy9U9y9l02045JEMsAynWPQxcLTCsw8hyalF0MLX3M

P.S.
Now I have launched Windows from bios/UEFI and repeated the CPU performance test in a multi-stream in Cinebench R23 and the results have increased by 1000 points. It turns out that when Windows is launched from OpenCore, not only the processor core frequency is displayed incorrectly, but also the core frequency cannot rise above a certain level (probably the core frequency did not really rise above the base frequency of 2.5 GHz, although officially with full load on all cores, the frequency can reach 2.9 GHz on all cores)

And yes, when I try to take a screenshot in Windows via the Win+Shift+S keyboard shortcut, HWiNFO shows a frequency jump on all cores to almost 2.5 GHz and it strange

![opencore break cpu win](https://user-images.githubusercontent.com/29478700/205199610-9de77b40-02e9-4cf3-a518-012ce10de818.png)

**Comment by Andrey1970AppleLife** [comment]
Your custom CPU SSDT tables shall be compatible with macOS and Windows.

**Comment by Drovosek01** [comment]
I did a lot of tests and found out that this problem in Windows is due to the fact that I removed extra sockets (SCK1, SCK2, SCK3) and extra cores in DSDT, leaving only 20 (since my processor has 20 threads).
I wrote about this "patch" here - https://applelife.ru/threads/patchi-dsdt-x79-x99-x299-voprosy-reshenija.2945315/page-12#post-1018732

If you return these "extra elements" - in Windows, the display of the frequency of processor cores in HWiNFO and other utilities works correctly and turbobust, probably, too.

BUT with these "extra" sockets and cores, macOS itself starts at best 4-6 times.
The lines ACPI Errors appear and OpenCore immediately rebuts, despite the arguments and quirks. Video reboota with ACPI errors here - https://github.com/acidanthera/bugtracker/issues/2171

And here comes the dilemma - how to fix DSDT only for macOS?
You can compare DSDT.aml in the hex editor before and after removing unnecessary sockets and make a custom patch, but besides the fact that it will be huge (and, accordingly, take up part of the time every time you start the OS), then also, as slice wrote - https://applelife.ru/threads/pamazhite-ispravid-ashipki-dsdt.35464/page-237#post-1020844 the patch in OpenCore applies to all operating systems, which means it won't do any good, as I understand it.

The only thought I had was to use _OSI and if we are in "Darwin", then use a block of code with 20 cores, otherwise use a block of code with all sockets and cores from the original DSDT

Maybe someone has some more ideas on how to fix the problem with the almost endless reboots of OpenCore without removing the "lshinie" sockets and cores from DSDT?
