### ISSUE TITLE
Opencore show 2 identical Ubuntu volumes and kernel panic in custom entry Ubuntu

### ISSUE THREAD

**Issue by Drovosek01** [acidanthera/bugtracker#2169]
Hello.

I Installed Ubuntu 22.
After that, 3 items were added to the GUI Picker:
- EFI
- Ubuntu 22.04.1 LTS (5.15.0-43 generic)
- Ubuntu 22.04.1 LTS (5.15.0-43 generic)

When EFI is selected, GRUB is started.
When you select any of the other 2 items, Ubuntu starts directly. Yes, it is also strange for me that both of them are called the same and one of these items is service, i.e. it is hidden when HideAuxilary is activated.

![image](https://user-images.githubusercontent.com/29478700/205201469-66ec1e7d-9efb-426a-a666-729b1b2c063f.png)

I wanted to remove the "EFI" and one Ubuntu item from the OpenCore menu. Before that, I had the Scan Policy parameter set to 0 so that all devices and partitions were scanned. Then I set the value to 6401 (hex 0x1901) to scan only APFS and NTFS and EXT. After that, the "EFI" item from the OpenCore menu disappeared, but 2 items remained with Ubuntu 22.04

Then, through the logs that are written to the ESP root, I found out the path that OpenCore uses to launch Ubuntu and created an additional entry with this path in Misc -> Entries and tried to launch this entry from the OpenCore menu, but Ubuntu did not start and stopped at the kernel panic.

![ubuntu kernel panic](https://user-images.githubusercontent.com/29478700/205203385-bfde0a00-6211-442c-b065-3cbc07fadf40.jpg)

Questions:
1. Why did OpenCore create 2 identical entries to run ubuntu
2. How to correctly create an entry in the OpenCore menu to run Ubuntu 22 without grub?

My hardware:
QIYIDA x79 lga2011 | Xeon E5 2670 v2 (Ivy Bridge-EP) | Sapphire RX580 Nitro+ 4Gb | 64GB 1866MHz RAM

Report from AIDA64:
[Report AIDA64.zip](https://github.com/acidanthera/bugtracker/files/10137356/Report.AIDA64.zip)

ESP:
https://mega.nz/file/e1FGnTwA#OWy9U9y9l02045JEMsAynWPQxcLTCsw8hyalF0MLX3M
but with this config:
[config.zip](https://github.com/acidanthera/bugtracker/files/10137702/config.zip)

**Comment by mikebeaton** [comment]
Most Linux installations cannot be started from an entry in OpenCore - at least, not unless you know how to work out and manually configure the required kernel arguments - and even then the specific kernel file which you need to execute (via its EFI stub) will change when your Linux distro gets an update.

Your existing setup, using OpenLinuxBoot, is the recommended way to do it.

There is more than one way to remove the unwanted EFI entry - apart from controlling what filesystems get scanned, you could also:
 - Replace {ESP}\EFI\BOOT\BOOTx64.efi with the file with the same name and location from the OpenCore distribution
 - Just delete {ESP}\EFI\BOOT\BOOTx64.efi (OpenCore can still be started from {ESP}\EFI\OC\OpenCore.efi, if for any reason you lose the entry; GRUB can still be started from {ESP}\EFI\ubuntu\shimx64.efi (for Ubuntu, or similar paths for other Linux))

Why is OpenLinuxBoot.efi detected two entries with the same name? I do not know, please can you provide the output of `sudo ls -l \boot`.

**Comment by mikebeaton** [comment]
You are just reading your entries wrong.

The first is for 5.15.0-56-generic (the latest kernel available on your installation), the other is for 5.15.0-43-generic (an older kernel which was left as a backup, by Ubuntu, in case of issues). The older kernel is made available as an auxiliary entry, by OpenLinuxBoot, by design (and roughly matching the behaviour of GRUB), to intentionally keep such recent backup kernels available to you to boot from (as intended by your distro).

**Comment by Drovosek01** [comment]
> The first is for 5.15.0-56-generic (the latest kernel available on your installation), the other is for 5.15.0-43-generic (an older kernel which was left as a backup, by Ubuntu, in case of issues

Thanks for the explanation. I don't want to use GRUB as an intermediary to run Ubuntu. Please tell me how can I leave only 1 entry to run Ubuntu in OpenCore Picker?

**Comment by mikebeaton** [comment]
You can't. OpenLinuxBoot adds all available kernels as entries, with all except the most recent as auxiliary entries. So if you keep HideAuxiliary set to true, then you will only see the recent entry - but the others remain available. As Ubuntu (similar to other distros) does updates, it will remove older kernels, but it will always leave some kernels older than the current one. These older kernels are *meant* to be available as reserve boot entries in your boot picker, and OpenLinuxBoot makes them available. It is working as intended.
