### ISSUE TITLE
[MaciASL] - Issue on patch tab

### ISSUE THREAD

**Issue by 1alessandro1** [acidanthera/bugtracker#2170]
MaciASL gives this error (and the user is not able to close it) when using the patch tab maybe because the website it is trying to reach is not available anymore

![image](https://user-images.githubusercontent.com/46293832/205436478-02b6edfd-ddb6-436c-9540-e60b61844b60.png)

I suggest to change it to just a warning without the app repeating that popup after every click on "ok"

**Comment by Core-i99** [comment]
I do believe you can remove this url from the sources in settings.

**Comment by 1alessandro1** [comment]
> I do believe you can remove this url from the sources in settings.

Thanks for the tip, but it would be best to display the popup just once (I had to manually terminate the app) - or update/remove that repo from the stock configuration, otherwise users might find frustrating when they're applying a patch that MaciASL throws that error multiple times since ```http://maciasl.sourceforge.net/pjalm/zotac``` does not exist anymore

Not a top priority, but nice to do

**Comment by Andrey1970AppleLife** [comment]
Some links don't work, you shall click ОК several times.
