### ISSUE TITLE
OpenCore not stay when the ACPI Error appears when starting macOS

### ISSUE THREAD

**Issue by Drovosek01** [acidanthera/bugtracker#2171]
I'm still running tests on the hackintosh setup on my x79 platform. The characteristics and AIDA64 report can be viewed here - https://github.com/acidanthera/bugtracker/issues/2169#issue-1472230564

If I haven't removed the extra sockets and cores in DSDT, then my macOS almost never starts the first time. Sometimes it takes 5 reboots until I get to the macOS account password entry screen.

In the config, I turned on all quirks and added bootargs so that the text output on the screen stops in case of a kernel panic, but it does not stop. I recorded it on video and saw that the last line in the output on the screen has the following text
`ACPI Error: 1 table load failures, 10 successeful (20160930/tbxfload 342)`
and then the computer automatically restarts.

![PXL_20221205_164651553 1 mp4_20221205_183718 019](https://user-images.githubusercontent.com/29478700/205683948-d2def3ec-6dd8-44d1-9343-b78e28a0e8ea.jpg)

Question:
How do I configure OpenCore so that it does not restart the computer when ACPI ERROR is received during macOS startup?

Here video with reboot loop - https://www.youtube.com/watch?v=qDWRssL5qaA

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by dreamwhite** [comment]
This has nothing to do with OpenCore itself, but rather a configuration side issue. More specifically in terms of ACPI patches... Please use forums for support as suggested.

**Comment by Drovosek01** [comment]
> This has nothing to do with OpenCore itself

But why computer reboot and not stop action like on kernel panic? I think it quistion directly linked to OpenCore
