### ISSUE TITLE
Why in Sample.plist parametr FuzzyMatch setted not like Failsafe value in documentation?

### ISSUE THREAD

**Issue by Drovosek01** [acidanthera/bugtracker#2173]
In official documentation for latest release OpenCore (v0.87) https://github.com/acidanthera/OpenCorePkg/blob/10fc98fc5dd1fa569e988e0aef9ffe8e88ea74c7/Docs/Configuration.pdf for parametr FuzzyMatch failsafe value is false:
![image](https://user-images.githubusercontent.com/29478700/206219901-bfa32670-06c5-40dd-83e1-ffe81bd0d3e8.png)

but it `Sample.plist` with same verion release parametr FuzzyMatch has value true.
![image](https://user-images.githubusercontent.com/29478700/206220997-8a2ea31d-5bb5-4890-8b76-5a2d7fec1cad.png)
https://github.com/acidanthera/OpenCorePkg/releases/tag/0.8.7

Questions:
1. Failsafe value from documentation !== default value in default config?
2. If answer on first question is "yes", then why default config have not failsafe values?

**Comment by Drovosek01** [comment]
Same for parametr `EnableWriteUnprotector`

**Comment by PMheart** [comment]
Answers:

1. We renamed "default" to "failsafe" many years ago, so you are correct.
2. Our sample config is not a reflection of the failsafe values.

**Comment by dreamwhite** [comment]
I think users must check every single key they don't understand and check whether they need it or not. As @PMheart stated, `Sample.plist` isn't a reflection of the failsafe values, and - I wanna add - must be tweaked according to your needs.

**Comment by Drovosek01** [comment]
> Answers:
> 
> 1. We renamed "default" to "failsafe" many years ago, so you are correct.
> 2. Our sample config is not a reflection of the failsafe values.

Thank you for the answers. Please add this info in OpenCore documentation

**Comment by PMheart** [comment]
Not necessarily in my opinion - every user should refer to Configuration.pdf when setting up config.plist, while Sample[Custom].plist is not a necessity.

**Comment by Drovosek01** [comment]
> Not necessarily in my opinion - every user should refer to Configuration.pdf when setting up config.plist, while Sample[Custom].plist is not a necessity.

OK, in this case, please add the Failsafe.plist file to future releases, in which all parameters will be filled with failsafe values from the documentation. I think it will be convenient.

**Comment by PMheart** [comment]
All failsafe values are clearly visible in Configuration.pdf, hence no need to maintain one more document.
