### ISSUE TITLE
VirtualSMC is unable to get CPU Temperature  on Intel 13th

### ISSUE THREAD

**Issue by phplaw** [acidanthera/bugtracker#2176]
Hey Acidanthera,
Thanks for great work on OC, I think we have issue with [VirtualSMC](https://github.com/acidanthera/VirtualSMC) Kext.

I am using latest OpenCore [0.8.7](https://github.com/acidanthera/OpenCorePkg/releases/tag/0.8.7) 
and Virtual SMC [1.3.0](https://github.com/acidanthera/VirtualSMC/releases/tag/1.3.0)
But It is unable to get CPU Temperature properly on Intel Core i7 13th
Here is my hardware spec.
1.Intel Core i7 13700K
2. ASRock Z790
3. AMD RX6600XT
[opencore-2022-12-09-170213.txt](https://github.com/acidanthera/bugtracker/files/10196874/opencore-2022-12-09-170213.txt)

Tested on macOS Ventura ( same issue on macOS Monterey as well)

<img width="988" alt="Screen Shot 2022-12-10 at 12 21 56 AM" src="https://user-images.githubusercontent.com/555124/206760027-ea9c9f70-371f-4275-874e-b32158b9a1d8.png">
<img width="661" alt="Screen Shot 2022-12-10 at 12 25 36 AM" src="https://user-images.githubusercontent.com/555124/206760046-010b658e-12ee-41f8-942e-6efa6724d061.png">

<img width="341" alt="204858011-d85a4ea8-8562-4c88-a703-5f4e4a007850" src="https://user-images.githubusercontent.com/555124/206760089-60f5fc9d-c111-4ac1-bc07-ff2c17a12d1e.png">
<img width="232" alt="204858038-67b3344e-dc1c-4c5b-a466-56732ec039d7" src="https://user-images.githubusercontent.com/555124/206760103-b9e8245a-66a3-480c-998b-3264483f5ea5.png">

**Comment by phplaw** [comment]
As you could see in the picture bellow, there is no SMCProcessor Attached to Processor 0x0
<img width="613" alt="Screenshot 2022-12-17 at 01 49 04" src="https://user-images.githubusercontent.com/555124/208168138-5d1170bf-2f36-4e40-84c3-8207de10d723.png">

**Comment by dreamwhite** [comment]
What about the logs of SMCProcessor using `-scpudbg`?
