### ISSUE TITLE
Live Text and Copy Subject functions both broken with unsupported models on Ventura 13.1

### ISSUE THREAD

**Issue by bootlegseahorse** [acidanthera/bugtracker#2182]
First I want to say thank you so much to Mykola for the amazingly fast fix on the AirPlay to Mac issue.

I just noticed another problem with Ventura 13.1 stable (22C65). The features "Live Text" and "Copy Subject" are both nonfunctional with unsupported models. I've tested with Photos, Quicklook, Preview and Safari, and it seems that all apps supporting those two features are now nonfunctional - you can't select any text or subject from photos and videos. 

I tested with MacBookPro9.2 (Ivy Bridge) and iMac17.1 (Skylake), and both are broken. On the other hand, my HacBookPro14.1 (Kaby Lake) is fully functional with those two features.

I can confirm that both models work perfectly fine with "Live Text" back on Monterey 12.6 or earlier (I used to heavily rely on this function from day to day). IIRC it used to be functional back in Ventura 13.0 and 13.0.1, but I'm not 100% sure about that. Also, I believe it's not associated with my personal data or iCloud or something, as the issue still exists on a fresh install with no personal data and no iCloud logged in. 

I don't know if it's just me, or everyone is experiencing the same problem worldwide. My guess is that Apple added blacklists or whitelists for Live Text and Copy Subject functions in Ventura, but I can't guarantee that.

Any help is much appreciated. From a user who heavily rely on Live Text function.

_OpenCore version: 0.8.7
OCLP version: 0.5.2
FeatureUnlock version: 1.1.1
Lilu version: 1.6.2_

**Comment by bootlegseahorse** [comment]
Here are the Console.app logs when I tried to copy text and subject from a picture in a Quicklook window. The first two pictures are from unsupported Macs, and the last picture is from a supported Hackintosh.
![Uploading 截屏2022-12-17 20.54.39.png…]()

**Comment by khronokernel** [comment]
https://github.com/acidanthera/bugtracker/issues/2183

**Comment by hardy-122** [comment]
> 在 OCLP 版本：0.6.2 中，它仍然坏了......

I also encountered the same problem. 
Have you solved the problem of not being able to use live text on Ventura and sonoma?
