### ISSUE TITLE
Photos Widget is crashing Notification Centre on Ivy Bridge iGPU

### ISSUE THREAD

**Issue by bootlegseahorse** [acidanthera/bugtracker#2183]
First I want to say thank you again to Acidanthera and Dortania for getting our old computers running after all these years.

In [Legacy Metal Graphics Support and macOS Ventura](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/1008), it was mentioned that the News Widget is crashing the Notification Center. However, on my Ivy Bridge MacBookPro9.2, I don't have the News Gadget installed, but the Notification Center still freezes and crashes from time to time. 

After some testing, I finally found that it was the Photos Gadget that's really crashing the Notification Centre. It shows in the Center as a black block, and the system freezes right after adding the Widget to the Centre. It starts normally again right after the Photos Widget is removed.

Sorry if I've posted this to the wrong place. I know this is not going to have a solution in the near future, but I hope this issue can be added to the [Legacy Metal Graphics Support and macOS Ventura](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/1008) page soon. 

Thanks again to the group for all the efforts.

<img width="1280" alt="截屏2022-12-17 18 34 41" src="https://user-images.githubusercontent.com/97839352/208245098-518b5805-1ee9-45ab-aef1-fc71e4e416f8.png">
<img width="1280" alt="WechatIMG3132" src="https://user-images.githubusercontent.com/97839352/208245201-805f115c-5483-4f52-bf9a-82adf899095e.jpeg">

**Comment by khronokernel** [comment]
This repo is for Acidenthera projects, not Dortania. See respective repositories for support
