### ISSUE TITLE
OpenCore break load Windows after reboot from macOS Monterey

### ISSUE THREAD

**Issue by Drovosek01** [acidanthera/bugtracker#2184]
Good time of day.

I installed and configured hackintosh on my x99 platform.

Unfortunately, I ran into the same problem as on my previous x79 platform. After shutting down macOS Monterey and starting Windows 10, it (Windows) does not start the first time. Only on the third launch does the Windows recovery mode start and the restart in Windows after that is already successful.

Even if I start Windows via the Boot menu in UEFI (after I have restarted the computer from macOS Monterey), this problem still appears.

Here is a video demonstration:
https://youtu.be/jGbsSFI2JhQ

Here my ESP with all files:
https://mega.nz/file/20dBUZQZ#7wWmvpyu6UaySTX8cUtE2ID8prhhwdsK8kl8X9GoYIQ

**Comment by perez987** [comment]
@Drovosek01 
This site is for bugs in OpenCore or Kexts, not for support. Go to the support forums for help.

**Comment by Drovosek01** [comment]
@perez987 
That is, do you consider the described situation normal and this is not a bug, but absolutely normal behavior when, after restarting from macOS Monterey, I can't get into Windows even through the Boot menu in UEFI?

**Comment by vit9696** [comment]
@Drovosek01, this behaviour does not reproduce for me and other OpenCore developers, who regularly use Windows on both older and newer hardware. We investigated similar issues a couple of times and the reasons were incorrect OpenCore configurations, namely ACPI changes or Quirks. For this reasons you are best to ask for help on the forums as there is no bug.

**Comment by Drovosek01** [comment]
I conducted an investigation and...

At first, I tried to reproduce the described problem on the basis of someone else's EFI folder with the Clover loader, and to my surprise, when using Clover, the Windows 10 operating system also started only 4 times after restarting from macOS Monterey.

I decided to reinstall Windows using the Clover bootloader. After reinstalling Windows, I did not install anything, but immediately conducted the test described above - I rebooted in Monterey, and then rebooted in Windows 10 and did not see any problems when starting Windows. Then I returned the OpenCore loader and repeated the tests with a restart and also did not see any problems with Windows 10.

Then I started to step through the Windows setup steps that I'm doing and run tests with restarting from macOS Monterey to Windows.

As a result, I found out that the described problem occurs if you install the driver for AHCI from the SDI driverpack.

![Annotation 2022-12-20 042513](https://user-images.githubusercontent.com/29478700/208569052-2e2eff81-cde9-4daf-93f6-f424e7a91ef5.png)

... I just don't have any censored words to describe how much time and nerves I've killed because of this fucking driver.

@vit9696 please add information to the documentation that this driver may break Windows startup after restarting from macOS Monterey

**Comment by Drovosek01** [comment]
By the way, now I went to the Windows update center and it still offers me optional updates, I looked at them and among them there is also a driver with almost the same name as in the SDI package, that is, a driver for "AHCI".
I installed it from optional Windows updates, repeated the tests with reboots and the problem was reproduced. That is, the problem is not because of the driver pack, but because of the driver...

![Annotation 2022-12-20 121239](https://user-images.githubusercontent.com/29478700/208633481-e73a3d69-3cd2-4c3b-9bdc-1bf400a1b115.png)

**Comment by Drovosek01** [comment]
Now I have installed all the optional drivers from Windows Update, except for the "Series/C220" driver, and again conducted tests with reboots between the two operating systems and everything starts fine. This once again confirms my test that the problem is due to the "Series/C220" driver

![Annotation 2022-12-20 125010](https://user-images.githubusercontent.com/29478700/208640649-c5f608eb-331d-4939-b1a8-6b58494dabd9.png)

**Comment by vit9696** [comment]
Very interesting, but I guess it is best to document this in the support topic of your motherboard. OpenCorePkg reference manual is not really a place to document hardware quirks specific to Windows.
