### ISSUE TITLE
Elan Trackpad stop working when use trackpoint

### ISSUE THREAD

**Issue by zerostar-git** [acidanthera/bugtracker#2185]
Dear friends, 
Thank you for excellent work on VoodooPS2Controller. 
I used lastest VoodooPS2Controller.kext on my Thinkpad X380 Yoga. 
My device have I2C touchscreen, PS2 keyboard and SMBus Elan trackpad and trackpoint.

I get issue that after system start, Trackpad work fine, but when I use Trackpoint, both Trackpad and Trackpoint stop working right after I touch to the Trackpoint. A few time both work for some minutes then suddenly stop working. After It's wake from sleep Trackpad and Trackpoint always stop working. 
I have 2 option to "half-fix" this: 
- Disable VoodooPS2Touchpad.kext: That mean no multitouch on touchpad, no gesture, no scoll on trackpoint (work all as a mouse), trackpoint and trackpad continue working after sleep-wake
- Disable Trackpoint in the BIOS as #1739 trackpad continue work after sleep-wake and full gesture, but no Trackpoint it's like no Thinkpad. And when I back to dual boot Windows, I have to go to BIOS and turn trackpoint back...

I tried VoodooRMI, VoodooSMBus, Clover bootloader for InfoPlistPatch... same thing happened. 
I think this issue relate to VoodooPS2Touchpad.kext
P/S I used VoodooI2CHID for touch screen, but even use VoodooI2C kexts or not, issue still there. 

Thank you!

**Comment by zerostar-git** [comment]
Update: Same issue on lastest 2.7.1

**Comment by vit9696** [comment]
cc @1Revenger1

**Comment by zerostar-git** [comment]
Update: Same issue with lastest 2.3.5 even some change log:
- Removed actAsTrackpad and related logic
- Fix Trackpoints connected to Elan Touchpads
- Use VoodooInput Trackpoint logic for Elan Touchpads

**Comment by vit9696** [comment]
To be tracked in #1192
