### ISSUE TITLE
[EB|LOG:EXITBS:START] 

### ISSUE THREAD

**Issue by Williamtung1** [acidanthera/bugtracker#2186]
Good day to all of you,
First, thanks a lot to all your hard work and a merry Christmas to all of you. Also, please don't close the problem yet when you see the heading. My laptop is problematic. With MATs support(unfortunately a buggy one) while not happy with 
EnableWriteUnprotector = False
RebuildAppleMemoryMap = True
SyncRuntimePermissions = True

I know I should use DevirtualiseMmio and whitelist different areas. However, I can't get the right area and it seems there is more than one troublesome area and I have spent countless hours in order to find it. (I am really desperate now, to be honest.) I know I shouldn't issue it as a bug here. But I can't find documentation on the use of the quirk and methods to whitelist areas, other than Dortania's,
which is quite confusing to me. In my opinion, their method is time-consuming and not working for me(That's the reason for my guess of having more than one troublesome area) Can you please give some help or at least some hints on what can I do? 
Any help would be much appreciated. I am willing to give you logs or anything to order to help. 

Many thanks,
William

P.S. By the way, I can use the combo below without a problem. However, I would have BSOD whilst booting Windows without SyncRuntimePermissions. That's mainly the reason I want to use the combo below.

EnableWriteUnprotector = True
RebuildAppleMemoryMap = False
SyncRuntimePermissions = False

Attachment: The MmioWhitelist part of my config.plist

              <array>
			<dict>
				<key>Address</key>
				<integer>3758096384</integer>
				<key>Comment</key>
				<string>MMIO devirt 0xE0000000 (0x10000 pages, 0x8000000000000001)</string>
				<key>Enabled</key>
				<true/>
			</dict>
			<dict>
				<key>Address</key>
				<integer>4261412864</integer>
				<key>Comment</key>
				<string>MMIO devirt 0xFE000000 (0x11 pages, 0x8000000000000001)</string>
				<key>Enabled</key>
				<true/>
			</dict>
			<dict>
				<key>Address</key>
				<integer>4275109888</integer>
				<key>Comment</key>
				<string>MMIO devirt 0xFED10000 (0xA pages, 0x8000000000000001)</string>
				<key>Enabled</key>
				<true/>
			</dict>
			<dict>
				<key>Address</key>
				<integer>4275585024</integer>
				<key>Comment</key>
				<string>MMIO devirt 0xFED84000 (0x1 pages, 0x8000000000000001)</string>
				<key>Enabled</key>
				<true/>
			</dict>
			<dict>
				<key>Address</key>
				<integer>4276092928</integer>
				<key>Comment</key>
				<string>MMIO devirt 0xFEE00000 (0x1 pages, 0x8000000000000001)</string>
				<key>Enabled</key>
				<true/>
			</dict>
			<dict>
				<key>Address</key>
				<integer>4284481536</integer>
				<key>Comment</key>
				<string>MMIO devirt 0xFF600000 (0xA00 pages, 0x8000000000000001)</string>
				<key>Enabled</key>
				<true/>
			</dict>
		</array>

**Comment by vit9696** [comment]
Whitelisting MMIO regions can only be done by trial and error. There is no big need in DevirtualiseMmio if it boots without it and you do not want to reclaim a bit of memory. Just disable it.
