### ISSUE TITLE
No AppleHDA loaded after AppleALC patching

### ISSUE THREAD

**Issue by camielverdult** [acidanthera/bugtracker#2188]
Hi Acidanthera,

I'm opening this issue because discussion and attempts to fix this on the hackintosh server did not yield any result. I've upgraded an X99 system to Ventura and AppleHDA will not load. Conflicting IRQ in ACPI is patched (see ACPI/SSDT-HPET) with SSDTTime and I cannot see anything suspicious in both OpenCore and Lilu debug logs. I've discussed this issue with CorpNewt without any solution. See attached debugging files for more information.

*Kexts:*
Lilu 1.6.2
AppleALC 1.7.7

*Hardware:*
Asus Rampage V Extreme X99 (ALC1150 codec) - both the X99 HDEF controller (0x8D20) and coded are supported in [the supported codecs list](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs).

[EFI.zip](https://github.com/acidanthera/bugtracker/files/10327658/EFI.zip)

[Lilu_1.6.2_22.2.txt](https://github.com/acidanthera/bugtracker/files/10327666/Lilu_1.6.2_22.2.txt)
[opencore-2022-12-31-164909.txt](https://github.com/acidanthera/bugtracker/files/10327667/opencore-2022-12-31-164909.txt)

[DSDT & IOREG.zip](https://github.com/acidanthera/bugtracker/files/10327659/DSDT.IOREG.zip)

Edit: re-uploaded logs

**Comment by vandroiy2013** [comment]
Find in BIOS Above 4G Decoding option and disable it if it's enabled or vice versa.

**Comment by camielverdult** [comment]
[CheckAudio](https://github.com/corpnewt/CheckAudio) also does not detect any codecs: 

```

Finding Codecs...
 - None found!
Checking kexts:

Locating Lilu...
 - Found v1.6.2
Checking for Lilu plugins...
 - Locating AppleALC...
 --> Found v1.7.7
 - Locating WhateverGreen...
 --> Found v1.6.1
Locating AppleHDA...
 - Not loaded!

Current boot-args: npci=0x3000 alcid=1 -liludbg -alcdbg liludump=60

Locating HDEF devices...
 - Located 1

Iterating HDEF devices:

 - HDEF@1B - PciRoot(0x0)/Pci(0x1B,0x0)
 --> built-in:            <00>
 --> alc-layout-id:       <01000000>
 --> layout-id:           <07000000>
 --> hda-gfx:             Not Present
 --> no-controller-patch: Not Present

Locating HDAU devices...
 - Located 1

Iterating HDAU devices:

 - HDAU@0,1 - PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x1,0x0)
 --> built-in:            <00>
 --> alc-layout-id:       Not Present
 --> layout-id:           <07000000>
 --> hda-gfx:             <"onboard-1">
 --> no-controller-patch: Not Present

Gathering inputs/outputs...
 - Located 1

Iterating Inputs and Outputs:

 - 38GN950
 --> Type:            Hdmi
 --> Outputs:         2
 ----> Output Source: 38GN950
```

**Comment by camielverdult** [comment]
> Find in BIOS Above 4G Decoding option and disable it if it's enabled or vice versa.

It seems that disabling Vt-d fixed it. I have been tackling this issue for a week... Thank you so much.
