### ISSUE TITLE
00:000 00:000 OC: Driver HfsPlusLegacy.efi at 1 cannot be loaded - Unsupported

### ISSUE THREAD

**Issue by feryw** [acidanthera/bugtracker#2190]
I have an old laptop with bios only and sandy bridge cpu.

Today I make OpenCore and corresponding LegacyBoot update as commit [a753334](https://github.com/acidanthera/OpenCorePkg/commit/a753334642c828ef06f0269ded7e5a77a765706c) build

Unfortunately after reboot, I have an error like below :
`00:000 00:000 OC: Driver HfsPlusLegacy.efi at 1 cannot be loaded - Unsupported`

I already try to redownload and replace HfsPlusLegacy.efi , but the error persist.

Then I start to track down which commit affect this behavior and I found that [6163813](https://github.com/acidanthera/OpenCorePkg/commit/616381392976455903e00864bcb0f6d16cbefb73) is the culprit, it's log says about PeImage and PeCoffLib. Before this commit all just fine to load HfsPlusLegacy.efi

So for now, in order to booting into OpenCanopy and enter High Sierra I use combination OpenCore from latest commit and LegacyBoot from [68c05b5](https://github.com/acidanthera/OpenCorePkg/commit/68c05b5c4097beb06e27e336ab2c28da97056782)

**Comment by vit9696** [comment]
Hi, could you try using this driver please?

[HfsPlusLegacy-WX.zip](https://github.com/acidanthera/bugtracker/files/10332686/HfsPlusLegacy-WX.zip)

**Comment by feryw** [comment]
> Hi, could you try using this driver please?
> 
> [HfsPlusLegacy-WX.zip](https://github.com/acidanthera/bugtracker/files/10332686/HfsPlusLegacy-WX.zip)
> 

Using this driver the problem persist.

**Comment by TonyC5** [comment]
I have reverted to the LegacyBoot provided with OC0.8.7 to resolve this issue.  With the older LegacyBoot provided with OC0.8.7, I am able to upgrade to OC0.8.8.

**Comment by vit9696** [comment]
We will need some time to handle the issue. For the time being it is acceptable to use older legacy boot.

Please test whether legacy boot from `vit9696-duet-20220104` branch works for you. The binaries will be available here in an hour:

https://github.com/acidanthera/OpenCorePkg/actions/runs/3835034310

**Comment by feryw** [comment]
Okay thank for your effort @vit9696 , i already saw new build from vit9696-duet-20220104 branch
I will report again asap when I get home.

**Comment by StefanAlMare** [comment]
HP xw4600, Intel(R) Core(TM)2 Extreme CPU X9650  @ 3.00GHz, AMD Radeon HD 7750 1 GB, OC 0.8.8 and 0.8.9, HfsPlusLegacy.efi, no issue.

**Comment by TonyC5** [comment]
Thank you for the quick response!  LegacyBoot in vit9696-duet-20220104 fixes the issue for me.  I am now using OpenCore 0.8.8 with LegacyBoot from vit9696-duet-20220104  to boot Big Sur on my Dell Latitude E6410 (SMBIOS MacBookPro6,2).

**Comment by MacNB** [comment]
> HP xw4600, Intel(R) Core(TM)2 Extreme CPU X9650 @ 3.00GHz, AMD Radeon HD 7750 1 GB, OC 0.8.8 and 0.8.9, HfsPlusLegacy.efi, no issue.

Did you actually run BootInstall_X64.tool from OC 0.8.8 and 0.8.9 before rebooting ?
That is, it is easy to upgrade OC EFI folder but many users forget to run BootInstall_X64.tool which each new build of OC.
If you did not then you are still on previous LegacyBoot

**Comment by feryw** [comment]
> Okay thank for your effort @vit9696 , i already saw new build from vit9696-duet-20220104 branch
> I will report again asap when I get home.

Great @vit9696 , by relaxing PE loader become more permissive, we can load HfsPlusLegacy.efi and boot to macOS. 

Currently i try Big Sur with this bios only laptop and everything just fine . ( using OCLP )

**Comment by StefanAlMare** [comment]
Hehehehehh! Using latest OC 0.8.9 bootinwstall_x64.tool I lost the Ventura boot disk. Picker appeared, but only windows is there to boot.

**Comment by feryw** [comment]
> Hehehehehh! Using latest OC 0.8.9 bootinwstall_x64.tool I lost the Ventura boot disk. Picker appeared, but only windows is there to boot.

I only try until Monterey with my Sandy Bridge 2310M ( OCLP MBP81 ), dunno if it affect at Ventura lost boot disk reading.

**Comment by vit9696** [comment]
This is good to know, but I actually wonder whether we could make it without modifying legacy boot and disabling some security measures added to it. Could you please revert to master and try once again with this driver?

[HfsPlusLegacy-WX-r2.zip](https://github.com/acidanthera/bugtracker/files/10345332/HfsPlusLegacy-WX-r2.zip)

**Comment by feryw** [comment]
> This is good to know, but I actually wonder whether we could make it without modifying legacy boot and disabling some security measures added to it. Could you please revert to master and try once again with this driver?
> 
> [HfsPlusLegacy-WX-r2.zip](https://github.com/acidanthera/bugtracker/files/10345332/HfsPlusLegacy-WX-r2.zip)
> 

using this driver along with LegacyBoot from latest OC build resulted at lost all APFS partition reading.
![IMG_20230104_224941.jpg](https://user-images.githubusercontent.com/15924436/210594835-8783ab08-5b95-471b-b943-f6f90be8c29f.jpg)

**Comment by vit9696** [comment]
Yes, that's somewhat expected if AppleSecureBoot is not enabled for you. Try enabling it please.

**Comment by feryw** [comment]
> Yes, that's somewhat expected if AppleSecureBoot is not enabled for you. Try enabling it please.

Great, all macOS with APFS layout back again.![IMG_20230104_225949.jpg](https://user-images.githubusercontent.com/15924436/210596783-d16643b6-c27a-4638-8c7b-177849f9f15d.jpg)

Thank you.

**Comment by vit9696** [comment]
I posted the updated drivers here:

https://github.com/acidanthera/OcBinaryData/tree/master/Drivers

They are a little different from the one uploaded above. Please update and confirm that the things still work correctly.

As for the secure boot requirement, we will think what is best to do, because older macOS versions do not support it, but will have the issue.

**Comment by feryw** [comment]
> > Yes, that's somewhat expected if AppleSecureBoot is not enabled for you. Try enabling it please.
> 
> Great, all macOS with APFS layout back again.![IMG_20230104_225949.jpg](https://user-images.githubusercontent.com/15924436/210596783-d16643b6-c27a-4638-8c7b-177849f9f15d.jpg)
> 
> Thank you.

 but with downside throwing error
```
OCB : LoadImage failed - Unsupported
```
