### ISSUE TITLE
Incorrect RX 5500 XT identification after adding new GPU ids to WhateverGreen

### ISSUE THREAD

**Issue by theofficialcopypaste** [acidanthera/bugtracker#2192]
I think this is not a big issue. At least you can do something. Pictures below will explain all.

Whatevergreen 1.6.2:

![Screenshot 2023-01-05 at 2 36 10 PM](https://user-images.githubusercontent.com/72515939/210717855-fdf5bcfc-fb20-4ccd-b4e5-842805a9bf56.png)

Whatevergreen 1.6.3:

![Screenshot 2023-01-05 at 2 42 40 PM](https://user-images.githubusercontent.com/72515939/210718004-94b6da6b-5ddf-40a5-a19c-e952d883bcf7.png)

Thanks

Regards.

"Love your works"

**Comment by vit9696** [comment]
Hi, could you please find which exact commit breaks it?

https://dortania.github.io/builds/?product=WhateverGreen&viewall=true

**Comment by theofficialcopypaste** [comment]
> Hi, could you please find which exact commit breaks it?
> 
> https://dortania.github.io/builds/?product=WhateverGreen&viewall=true

I dont know about that, but after update latest OC 0.8.8 release and Whatevergreen v1.6.3 release

**Comment by jafd** [comment]
What he means is that you download and try each of the builds under that link in the 1.6.3 section bottom to top until you find the broken one, and then tell which one it is.

**Comment by theofficialcopypaste** [comment]
> What he means is that you download and try each of the builds under that link in the 1.6.3 section bottom to top until you find the broken one, and then tell which one it is.

noted, i will try as soon as possible

**Comment by theofficialcopypaste** [comment]
ok build 7c1d034 is affect

**Comment by theofficialcopypaste** [comment]
Thank you for respond both of you

**Comment by vit9696** [comment]
Could you provide IOReg with working and not working builds please?

**Comment by theofficialcopypaste** [comment]
Thank you for respond, here is my details:

> Not Working:
[notworking.zip](https://github.com/acidanthera/bugtracker/files/10716160/notworking.zip)

> Working:
[working.zip](https://github.com/acidanthera/bugtracker/files/10716161/working.zip)

**Comment by vit9696** [comment]
Please test https://github.com/acidanthera/WhateverGreen/commit/e963e9d5e2101830e16b4f60b61816cf75d3949e

**Comment by theofficialcopypaste** [comment]
not working. 

![Screenshot 2023-02-13 at 12 39 33 AM](https://user-images.githubusercontent.com/72515939/218324268-978dd946-9b87-40c5-8200-9eac746e2e78.png)

**Comment by vit9696** [comment]
Please try https://github.com/acidanthera/WhateverGreen/commit/a58172a1d840d26f05d7fbd3f6e910754a13e13c

**Comment by theofficialcopypaste** [comment]
Working! Thank You @vit9696 for your hardworking. Thanks a lot!

![Screenshot 2023-02-13 at 1 43 14 AM](https://user-images.githubusercontent.com/72515939/218327566-77b454d6-b612-4f01-a123-d48817e700d5.png)
