### ISSUE TITLE
Kernel Panic when using the following flags: `-v keepsyms=1 debug=0x100`

### ISSUE THREAD

**Issue by danieldeicide** [acidanthera/bugtracker#2194]
Hello!

Let me start by thanking you for all your hard work that you've been doing on this amazing project. I am really in awe of all the great things you are doing! Thank you!

I am getting a kernel panic if I enable the following flags:
`-v keepsyms=1 debug=0x100`

I know this might sound stupid, but it's fairly documented on support forums. It seems as though people are fine with removing these flags if it fixes their problem and that's it. But I know that there is a bug somewhere (because enabling these flags should 100% not trigger a kernel panic in the ideal world) and I want to address it.

I've encountered this bug since I've added a dedicated GPU to my system.

System configuration:

| Element | Value |
| ------------- | ------------- |
| OC version: |  0.8.6 |
| macOS version: |  12.6.2 |
| SMBIOS: |  20,1 |
| dGPU: |  ASUS RX 6600 |
| CPU: |  Intel 10700K |
| RAM: |  Corsair 32GB |
| Motherboard: |  Gigabyte Z490i aorus ultra |

I've previously used my system without any dedicated gpu, only the iGPU and had those flags enabled without any problem. I've encountered this issue after I've purchased my dedicated GPU and installed it (which wasn't as easy as setting agdpmod=pikera unfortunately).

If I remove those flags, system boots fine. Every single time.

I do think there are other issues like: I feel like the dGPU is not seen as primary, as driving a display but rather it's been seen as secondary and only after some processes happening it gets switched to the display port from dGPU.
I don't know how to express this in other terms, but there is a difference between what I see from boot to login screen when using a dGPU compared to when I've used only the iGPU.
Kinda like macOS knows my system doesn't have an internal display working and it's using the external one once it shows the login screen.

Config.plist 
https://pastebin.com/DdXRz9jh

OpenCore log 
https://pastebin.com/AB6WpnnG

Thank you very much for your support!

**Comment by vit9696** [comment]
What kernel panic? Please provide panic log. This is not a support forum, so closing.
