### ISSUE TITLE
 Access denied to APFS with UEFI Secure Boot

### ISSUE THREAD

**Issue by 3arthur6** [acidanthera/bugtracker#2197]
Hi!
In order to enable UEFI Secure Boot which is required by EA AntiCheat, I followed [perez987 tuto](https://github.com/perez987/OpenCore-and-UEFI-Secure-Boot) and successfully signed all efi stuff.
I can boot up to OpenCanopy but only Windows installation is displayed, no MacOS. If I disable Secure Boot in the BIOS my macOS installation comes back and boots fine.
In log I can see that access is denied at some point but I couldn't find the problem.
Here is log with and wihtout Secure Boot and my config.plist.

[opencore-2023-01-13-122337_secure-boot.txt](https://github.com/acidanthera/bugtracker/files/10411671/opencore-2023-01-13-122337_secure-boot.txt)
[opencore-2023-01-13-122420.txt](https://github.com/acidanthera/bugtracker/files/10411672/opencore-2023-01-13-122420.txt)
[config.plist.txt](https://github.com/acidanthera/bugtracker/files/10411674/config.plist.txt)

**Comment by mikebeaton** [comment]
There are instructions about how to configure APFS for use with UEFI Secure Boot section of OC Configuration.pdf main doc.

Not a support forum. Closing.

**Comment by 3arthur6** [comment]
If it can help someone.
I finally get it to boot by enabling _DisableSecurityPolicy_ and _ProtectUefiServices_ quirks.
I probably lose all security advantage of secure boot with _DisableSecurityPolicy_ enabled but anyway this was not the intent.
