### ISSUE TITLE
MacHyperVSupport questions (Audio and Display)

### ISSUE THREAD

**Issue by amigd23** [acidanthera/bugtracker#2199]
Hi, following the guide in the MacHyperVSupport page, I have successfully booted a Monterey hyper-v VM on Windows 11 22H2 host, though its performance is not ideal. This is not a bug report but really a question: is this the current state or perhaps I missed something that could improve further.

1. There is no audio device in Sound setting. I tried Youtube and it plays alright but no audio. Did I miss anything to get audio working?
2. The default display resolution is 1024x768 and it's also the only option in Scaled. How can I get other resolutions available? For me 2560x1440 for full screen is needed. 
3. The responsiveness from the mouse seems laggy. Is there anyway to improve? 

The System Information shows Graphics: Hyper-V Graphics 3MB. Maybe all these are due to the Hyper-V Graphics are still not very performant yet. If that's the case, hope someone can confirm.

I know this probably is not a good place to ask questions but I don't really know anywhere else to ask. Sorry about this.

Thank you very much!

For your info, my PC is an intel i5 6400 on a asus h110m-a/m.2 motherboard with 16GB ram. Although very old, but a normal hackintosh following opencore's guide still works pretty good.

**Comment by Goldfish64** [comment]
Hyper-V does not expose an audio device. For graphics better resolution may eventually be possible but there will never be acceleration, you'd need to pass in a GPU similar to other VM solutions.
