### ISSUE TITLE
Startimage Failed - already started, but i have no drives connected to laptop

### ISSUE THREAD

**Issue by Iamansweringyou** [acidanthera/bugtracker#2200]
when my laptop (lenovo ideapad l340-15irh i7-9750H UHD630 NVIDIA 1050) had M.2 and HDD i had issue Startimage - already started, i disconnected every drive it had, no changes, i connect only HDD / M.2, same issue, i looked for every forum and nothing helped me.
[opencore-2023-01-16-212610.txt](https://github.com/acidanthera/bugtracker/files/10428568/opencore-2023-01-16-212610.txt)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/10428578/EFI.zip)

**Comment by Iamansweringyou** [comment]
M.2 have windows 10 installed, HDD is empty, secure boot disabled, VT-d enabled, Intel hyper-threading enabled

**Comment by mikebeaton** [comment]
For bug reports, please include OpenCore debug log, as mentioned in issue template.

This a configuration issue not a bug - please find an appropriate forum.
