### ISSUE TITLE
#[EB/:D/OFS|OPEN!] Error(0xE)<"usr\\standalone\\OS.dmg.root_hash"> <"0"> in MacHyperVSupport 

### ISSUE THREAD

**Issue by TylerJaacks** [acidanthera/bugtracker#2202]
My Error

![Screenshot 2023-01-17 221006](https://user-images.githubusercontent.com/1505374/213081669-ea553f84-c71c-4eb5-84ce-f920a517ea7c.png)

My Config

[config.plist.txt](https://github.com/acidanthera/bugtracker/files/10442038/config.plist.txt)

My File Structure

[tree.txt](https://github.com/acidanthera/bugtracker/files/10442054/tree.txt)

**Comment by salsadal** [comment]
I'm having the same error message here. Happens only when installing macOS Ventura. Same configuration works perfectly with Monterey and PROXMOX.

**Comment by salsadal** [comment]
I managed to install Ventura (full package, not the incremental). There's a kernel patch missing, which is in the file attached. Thanks https://github.com/thenickdude/KVM-Opencore for that.
[kernel_patch_ventura.plist.txt](https://github.com/acidanthera/bugtracker/files/10558435/kernel_patch_ventura.plist.txt)

**Comment by TungTotem** [comment]
> I managed to install Ventura (full package, not the incremental). There's a kernel patch missing, which is in the file attached. Thanks https://github.com/thenickdude/KVM-Opencore for that. [kernel_patch_ventura.plist.txt](https://github.com/acidanthera/bugtracker/files/10558435/kernel_patch_ventura.plist.txt)

what exactly do I have to change? I dont understand what you did there :(

**Comment by salsadal** [comment]
> > I managed to install Ventura (full package, not the incremental). There's a kernel patch missing, which is in the file attached. Thanks https://github.com/thenickdude/KVM-Opencore for that. [kernel_patch_ventura.plist.txt](https://github.com/acidanthera/bugtracker/files/10558435/kernel_patch_ventura.plist.txt)
> 
> what exactly do I have to change? I dont understand what you did there :(

You have to edit you config.plist and modify the kernel>patch section to insert the lines in the 'kernel_patch_ventura.plist' above. If you are not able to download macOS Ventura full version, you can use Corpnewt's script gibMacOS (https://github.com/corpnewt/gibMacOS)
