### ISSUE TITLE
Slow speed on Samsung PM9A1 SSD

### ISSUE THREAD

**Issue by 92das** [acidanthera/bugtracker#2204]
Greetings.
I have NVME Samsung PM9A1 (**GXB7701Q**).
This nvme installs MacOS properly, TRIM starts automatically, but the speed and reading of **SEQ1M QD1** is very low.
Also, short-term lags may appear in the system.
I tried to install nvmefix, but the problem has not disappeared, the write speed is still low

How to be in such a situation?

![pm9a1](https://user-images.githubusercontent.com/123297162/213910155-8fd47bba-808b-4adc-8dd9-bf7fed127c0f.png)

![Report PM9A1](https://user-images.githubusercontent.com/123297162/213910163-f1dd5dcb-6c4c-49b6-9457-74d56f9d683a.png)

**Comment by vit9696** [comment]
Replace an SSD. Samsung SSDs do not play well with Apple NVMe driver.
