### ISSUE TITLE
[Coding] Doubts about RestrictEvents modularity

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2205]
Hi, I'm enrolled in a IT university and I'm opening this issue since the issue template states:

> ...
> When to use issue tracker:
> * You have new resources or patches to add but cannot make a pull request
> * You have kernel panics, crashes, hangs and believe it is not a configuration issue
> * You want to discuss **technical** or legal stuff
> ...

I really appreciate your effort in developing and maintaining [RestrictEvents](https://github.com/acidanthera/RestrictEvents) which works really great, but I noticed that it's not actually modular as I expected.

The [README.md](https://github.com/acidanthera/RestrictEvents/blob/master/README.md) states:

> The list of patches currently includes:

>    - Disabled MacBookAir model memory replacement UI (comes in pair with SystemMemoryStatus = Upgradable quirk).
>    - Disabled MacPro7,1 PCI Expansion view and RAM view.
>    - CPU brand string patch for non-Intel CPUs (can be forced for Intel with revcpu=1).
>    - Disabled uninitialized disk UI

which leads me thinking that - in terms of software engineering - that those are SEPARATED and INDEPENDENT modules which serve different purposes.

I noticed that actually there's a dedicated module for the SW updates called [`SoftwareUpdate.cpp`](https://github.com/acidanthera/RestrictEvents/blob/master/RestrictEvents/SoftwareUpdate.cpp) which separately from the rest of the code-base does other things.

At this point wouldn't it be better to split each patch mentioned above onto other files? This would be great in terms of maintainability as well as making sure that there won't be conflicts with the other patches.

My guess would be splitting each patch in different files such as:

- `memory_replacement_ui.cpp`
- `mp71_ram_view.cpp`
- `mp71_pci_view.cpp`
- `cpu_brand_string.cpp`
- `uninitialized_disk_ui.cpp`

while keeping the base functions - such as `performReplacements`, `policyCheckExecve` etc - in the main `RestrictEvents.cpp`.

What do you think about that? If it's welcomed, I can try splitting the files and test the kernel extension on a MP7,1 hackintosh build.

Greetings
dreamwhite

**Comment by vit9696** [comment]
Basically it is good enough to serve its need. Each piece of code can be improved, but every improvement costs development time and verification time (including testing and reviewing). We would probably pass till REV needs more work.
