### ISSUE TITLE
[Issue] [VirtualSMC, Dell Latitude 5590] Controlling fan speed via Macs fan control causes all EC features to quit working

### ISSUE THREAD

**Issue by Overc1ocker** [acidanthera/bugtracker#2207]
Hello,

I just noticed today that controlling the fan in Mac's fan control causes the embedded controller to quit working (IE Lid sleep and brightness keys quit working) on a Dell Latitude 5590. I'm using the latest BIOS from dell as well as opencore 0.8.8 and the latest release version of virtualsmc. I'm curious how I can go about debugging this issue ad this behavior is quite undesired. On a side note, I've also noticed that the fan is only running at two different speeds, so perhaps we are writing to the wrong registers?

**Comment by vit9696** [comment]
I am afraid we cannot do much to this. The algo we borrowed to control Dell fans is from Linux, if it does not work, it is likely an upstream issue.

CC @lvs1974

**Comment by lvs1974** [comment]
@Overc1ocker: yes, that is true. As soon as fan control is set to manual, EC stops working.
When it is set to automatic again, EC works. There is nothing we can do here.
