### ISSUE TITLE
Suggestion for Boot picker or OpenCanopy

### ISSUE THREAD

**Issue by CobanRamo** [acidanthera/bugtracker#2209]
Hi guys

I would like to propose a function for the buildin picker and OpenCanopy.
You probably know the "Uefi Firmware Settings" call from the Grub bootloader.
![GrubFirmwareSettings](https://user-images.githubusercontent.com/68192365/215288557-d2d4af1b-aa00-495d-8940-28189548fac7.png)

That should be possible with OpenCore too.
![NormalBootMenu](https://user-images.githubusercontent.com/68192365/215288718-3abb665c-9b01-436a-b8c3-6211b896a415.png)

I would like to suggest this under an item in the advanced boot menu.
![AdvancedBootMenu](https://user-images.githubusercontent.com/68192365/215288724-7581ed0c-9a91-4643-9158-131cf3ad2046.png)

you could solve it like reboot and shutdown points or like menu point nvram reset.
What do you think about that?

**Comment by mikebeaton** [comment]
As an additional entry (which could come from a tool, or from a Boot Entry Protocol compatible driver) this isn't such a bad idea. One difficulty which would need considering is what to do on supported systems such as Intel Macs, (most of) which do not have a UEFI settings menu. (It may be fine to reboot with no effect in those cases, so this may not need any special handling.)

I'd suggest we would consider a well-written (according to OC/EDK-II coding standards) PR - but otherwise it would be quite low priority, realistically, since essentially all machines using OC which have a UEFI menu already have a built in way, which the user knows, of accessing this.

**Comment by mikebeaton** [comment]
nice icon set, by the way! which one is it? (presumably chris1111 or blackosx... :) )

**Comment by CobanRamo** [comment]
I think for those who completely disable the legacy stuff in Uefi, it's not such a bad idea.
If I completely deactivate legacy recognition in the Uefi, I have no keyboard until the OpenCore is loaded, so it would be nice to have this call.



> nice icon set...

Oh, I derived it from the OpenCore "GoldenGate" and expanded it for my needs.
You are of course welcome to have it if you want. :)
https://github.com/CobanRamo/OpenCore-IconSet

**Comment by mikebeaton** [comment]
> If I completely deactivate legacy recognition in the Uefi

Not quite sure why you would do that

> You are of course welcome to have it if you want. :)

After arguing for and implementing the themes support, always on the lookout for other nice themes! ;)

**Comment by chris1111** [comment]
My issue [here](https://github.com/acidanthera/bugtracker/issues/2215)
it's a shame because for me OC 0.8.0 Duet worked well for me and the changes made to fix the Duet around certain config completely screwed up the boot because the proof here I compiled OC 0.8.9 myself this evening At the source and I use the Duet OC 0.8.0 boot file and I boot without problem Monterey, Ventura and install macOS Ventura 13.2 from USB install Media Using EFI folder OC O.8.9

See boot picker

![08002707](https://user-images.githubusercontent.com/6248794/217402012-9fd543f5-05e7-45d4-ad7e-6b5279c3831c.png)
![08002718](https://user-images.githubusercontent.com/6248794/217402017-cdb78f8d-9cad-4cec-8896-7b755528c0b5.png)

**Comment by mikebeaton** [comment]
> I think for those who completely disable the legacy stuff in Uefi, it's not such a bad idea.
> If I completely deactivate legacy recognition in the Uefi, I have no keyboard until the OpenCore is loaded, so it would be nice to have this call.

@CobanRamo - Apologies, on re-reading this, perhaps my initial comment was too dismissive. Sorry. I would agree that it is fair enough if you want UEFI boot and no Legacy boot. But - my revised comment is! - I'm not aware that it's normal that disabling legacy boot in a bios should stop the keyboard from working. Are you sure these (have to) go together? Which bios/system are you using?

**Comment by CobanRamo** [comment]
Oh Mike, there's nothing to apologize about. After reading about it several times, I noticed that I expressed myself incorrectly, or it's a stupid translation.
That's just how it is when you can't speak decent English. :)

So, I have a Z590 platform here, where the UEFI boot process until OpenCore is kinda slow, it can take up to 10 seconds before I have the OpenCore menu in front of me.
Therefore I deactivate all legacy stuff in the UEFI and activate the MSI Fast Boot. The result is of course that I have no keyboard and mouse until the start of the Opencore.
Ergo, such a call point to the UEFI/Bios as with the Grub Loader is very convenient in my case. Hence the idea.

You must excuse me for the late reply, I'm on late duty this week and I'm extremely busy. :)

![6 USB_Configuration](https://user-images.githubusercontent.com/68192365/218853382-5c0f2461-7bd5-44cd-9b3d-68429adcab1f.jpg)
![10 BootSettings](https://user-images.githubusercontent.com/68192365/218853435-82d229c3-8bb8-47a4-8b9e-e8848f15e78e.jpg)

**Comment by mikebeaton** [comment]
Well equally of course you don't have anything to apologise for - certainly, we all reply when we have the time to!

I am pretty surprised that there is a system which boots fast, but with no keyboard support - I mean, I would accept no BlueTooth support, but no keyboard support?! I would have expected that all BIOSes would need it to be possible to break into them, e.g. what if the current boot entry becomes unbootable. Perhaps, to be clear, you could clarify how you *do* break into this BIOS, with those settings, if the boot entry does become unbootable - say just always hangs?

**Comment by CobanRamo** [comment]
> I mean, I would accept no BlueTooth support, but no keyboard support?!

MSI itself even says that the USB, PS2 and Sata are skipped..
![MSI FastBoot](https://user-images.githubusercontent.com/68192365/218881828-c715b9be-9f1f-4a8c-bc40-fd83dc1a2b31.png)

> I would have expected that all BIOSes would need it to be possible to break into them, e.g. what if the current boot entry becomes unbootable.

I think in this case you can still activate the GoToBios option with a 4-second power button.
I mean pretty much all biosses have that.
If all else fails, you can always run cmos reset. :)
![GoToBios](https://user-images.githubusercontent.com/68192365/218882460-c9254fce-fea2-4a48-b8fc-55ee8ff1894e.png)

**Comment by MacNB** [comment]
Just to tag along with another suggestion if I may.

The whole concept of "tools" on the same row as Bootable OS's seems to defy logical view of that row.
That is, Opencanopy displays "Shell", ResetNVRAM, BootKicker, etc next to bootable OS's even though they are NOT really bootable OS's. Yes OK they can be hidden as Auxiliary so they are not visible but still seems out of place.

My 2 cents would be that _anything in OC's Tools folder to be displayed_ on the same row as the current Restart & Shutdown icons. If those two can be displayed there today, why not others (with a limit of course) ?.

So UEFI F/W, Restart, Shell, ToggleSIP, Whatever, etc would be on the bottom of the screen.

**Comment by mikebeaton** [comment]
Not likely to happen. And this is a new suggestion, so new issue if you want to raise it.
