### ISSUE TITLE
OpenCore Legacy boot mismatch boot error

### ISSUE THREAD

**Issue by ruckusman** [acidanthera/bugtracker#2210]
HP XW8600 Dual 4 Core Xeon, 32GB, GTX 760 - only USB plugging in to boot to opencore
Using OpenCore-0.8.9-DEBUG -> BootInstall_X64.tool to make a GPT USB bootdisk yields:

BOOT MISMATCH!
BOOT ERROR!

EFI, 'boot' and in attached zip.
[HP-XW8600 - dual 4 core Xeon.zip](https://github.com/acidanthera/bugtracker/files/10532009/HP-XW8600.-.dual.4.core.Xeon.zip)

**Comment by mikebeaton** [comment]
@ruckusman - See [comments](https://github.com/acidanthera/bugtracker/issues/2206#issuecomment-1426489924) in #2206.
