### ISSUE TITLE
Feature Request: OpenCore DeviceProperties should identify devices by their ACPI Name

### ISSUE THREAD

**Issue by TonyC5** [acidanthera/bugtracker#2212]
As per Andrey1970AppleLife's response [here](https://github.com/acidanthera/bugtracker/issues/2211#issuecomment-1416799817), OC only supports the definition of DeviceProperties for devices with ACPI names.  This requirement is despite the fact that OC DeviceProperties must be defined (in config.plist) using the device path (and not the device ACPI name) and that OC has no problem defining new DeviceProperties for unnamed devices.

It would be easier for the user if OC DeviceProperties could interchangeably recognize the device by its device path and by the device's ACPI name.

Example: both of these DeviceProperties rules in OC config.plist should be acceptable:
![Screen Shot 2023-02-04 at 12 58 11 PM](https://user-images.githubusercontent.com/28421182/216782427-13a3530a-cf43-45b0-b3fc-c0a9ba135f89.png)

**Comment by Andrey1970AppleLife** [comment]
In certain cases devices can have an identical name, but different paths.
