### ISSUE TITLE
[Feature Request] max98927 codec support for AppleALC

### ISSUE THREAD

**Issue by meghan06** [acidanthera/bugtracker#2214]
Hey there! So today I upgraded one of my older laptops (ASUS C425 Chromebook) to the latest version of macOS Ventura. But, I was a little disappointed to find that there was no internal speaker support. After some research, I discovered that my speakers were using an Intel SST (IIRC) codec that wasn't supported by AppleALC. I did some more digging and stumbled upon some source code from Google for this codec. I thought I would share it here in the hope that it might be added to AppleALC in the future.

https://chromium.googlesource.com/chromiumos/platform/depthcharge/+/refs/heads/master/src/drivers/sound/max98927.c

From my limited knowledge, the src linked uses the `libpayload` library, which is specific to ChromeOS. To port this code to macOS, you will need to replace the use of `libpayload` with equivalent APIs provided by macOS. Additionally, you'll need to replace any calls to `i2c` with calls to the macOS I2C libraries. 

I hope this helps. It would be nice to have working speakers in macOS

Cheers!

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/2084#issuecomment-1201335291
