### ISSUE TITLE
Open Core Legacy SecureBootModel

### ISSUE THREAD

**Issue by AlexKusnezov** [acidanthera/bugtracker#2216]
Hey Guys, after a successful update from Monterey to Ventura. 
I tried to patch Amd Polaris GPU for legacy cpu without avx2 (i7-960). 
OCLP tells me that my Secure boot is enabled. 
When I try to set it from **default** to **disabled** I can't see any boot entry in the opencore picker, except for the tools
When I change it back to **default** the boot drive is present again.

What am I missing?
Preferably I want to disable secure boot entirely on this machine.

**Comment by feryw** [comment]
please update your LegacyBoot

considering
[issues/2190](https://github.com/acidanthera/bugtracker/issues/2190),
[issues/2206](https://github.com/acidanthera/bugtracker/issues/2206), and
[issues/2215](https://github.com/acidanthera/bugtracker/issues/2215)
