### ISSUE TITLE
WhateverGreen Kext not working on MacOS Ventura 13.2

### ISSUE THREAD

**Issue by RaphMar2021** [acidanthera/bugtracker#2217]
Hello, i installed macOS 13 on my ThinkPad T460 (Intel HD Graphics 520, Intel Core I5 6300U)

For some reason, I don't have graphics working correctly (no blur effect, no second screen support, very laggy)

I tried updating the kext to his latest version, but it didn't work.

**Comment by RaphMar2021** [comment]
You cant even try to respond...

It's the most worse thing ever seen.

**Comment by Core-i99** [comment]
This is not a hackintosh support forum, it's a BUGtracker, to report BUGS.
Only kaby lake+ igpus are supported in Ventura, your issue is totally invalid.
