### ISSUE TITLE
Trackpad option missing with latest voodoops2 in settings 

### ISSUE THREAD

**Issue by PriNcEFuL** [acidanthera/bugtracker#2219]
for some reason my system preferences is missing trackpad with voodoops2 2.3.3 but the trackpad with all the gesutres working fine

**Comment by andreszerocross** [comment]
Check if your battery indicator is shown,

No Battery Indicator = No Trackpad Preferences

**Comment by PriNcEFuL** [comment]
Thank you so much recently my laptop battery died and i took it out that's was the reason

**Comment by Astrojoinl** [comment]
this post is not valid, but so many youtubers shows how to replace the “big sur trackpad.pref..."! maybe an explanation in the VoodooPS2 readme.md is needed?

**Comment by mikebeaton** [comment]
@Astrojoinl - feel free to offer a pull request explaining the issue and the fix (as brief and clear as possible, thank you!) in the README.
