### ISSUE TITLE
QTJ2 MacOS problems after sleep

### ISSUE THREAD

**Issue by 92das** [acidanthera/bugtracker#2220]
Greetings.
I want to report a problem with sleep on the intel QTJ2 engineering processor.
**What exactly is the problem:**
MacOS (regardless of the version, even Big Sur, even Ventura) after sleep, starts to behave extremely unstable. Videos stop playing, Safari may stop loading pages, and general macOS weird behaviors (including programs forever running, etc.).

My hardware:
Asus Q170S1
Intel QTJ2
Intel UHD630

I saw the same sleep problem with other QTJ2 owners, regardless of the motherboard and version of MacOS. They did not report the problem and the sleep problem has not been solved so far
Please help me to solve this problem

**Comment by Andrey1970AppleLife** [comment]
We don't recommend to use engineering processors. Share if you find the solution.
