### ISSUE TITLE
"Ghost" OpenCore partitions showing in UEFI BIOS

### ISSUE THREAD

**Issue by franzageek** [acidanthera/bugtracker#2222]
I don't know how to properly define this, but a while ago, i tried a pre-configured EFI folder for my processor, and it seemed to work. But each time I've booted it, a new "ghost partition" popped up in my boot entries list in BIOS.
In the picture you can see 6 of them, all named "OpenCore".
Even if I unplug all my disks, they keep being there.
I was wondering if this was normal, and how to make them go away.
If you need more info (like the efi folder I used) let me know.
![IMG_7450](https://user-images.githubusercontent.com/88248950/218272978-9ab21fe8-11f0-4e44-a770-102873ab7134.png)

**Comment by Core-i99** [comment]
The EFI probably has launcher option set to Full or Short
https://dortania.github.io/OpenCore-Post-Install/multiboot/bootstrap.html#prerequisites

**Comment by franzageek** [comment]
@Core-i99 so i just need to edit those values an then those boot entries will go away?

**Comment by Core-i99** [comment]
Reset the bios and they will go away.
Then make sure to disable the launcher option in oc.

Also this is a bug tracker, this is not a bug so better ask this question on a support forum.
