### ISSUE TITLE
[Airportbrcmfixup.kext] Airdrop, Sidecar and Handoff issue

### ISSUE THREAD

**Issue by applesniperz** [acidanthera/bugtracker#2224]
Airdrop works intermittently for DW1830, mostly from native apple devices to opencore Build.
Bluetooth crashes after sleep intermittently.
Side car not working

Handoff only work one way from native devices to opencore build with bugs.

**Comment by Andrey1970AppleLife** [comment]
Airportbrcmfixup.kext doesn't provide any patches for Airdrop, Sidecar and Handoff.
