### ISSUE TITLE
[OpenCore] Problem with Boot Picker and early macOS log in 0.8.9

### ISSUE THREAD

**Issue by vandroiy2013** [acidanthera/bugtracker#2225]
@mikebeaton 

I've run into an early macOS log being starting while the boot picker is still active in the 0.8.9 release.
Here is video from 0.8.9
https://user-images.githubusercontent.com/8144780/218806185-95bbd2de-afa6-4e9a-981b-8f3456044c40.mov

And from 0.8.8
https://user-images.githubusercontent.com/8144780/218806027-3703403b-6c63-4595-b0d6-c964a5c51dd7.mov

**Comment by mikebeaton** [comment]
@vandroiy2013 - just to clarify, this is the previous behaviour, v0.8.8, when there is a background theme colour (which obviously there always is, it's just harder to see what's happening when it is black):

[boot.zip](https://github.com/acidanthera/bugtracker/files/10736318/boot.zip)

**Comment by paulojrandrade** [comment]
hello @vandroiy2013 , sorry for my english (translator) . I have a problem maybe you can help me. My notebook has 8Gb of RAM, but when running a VM in Vmware Fusion or any other application, Monterey does not consume the total available memory, just over 4Gb of memory consumed it starts using Swap, would it be some configuration in the OC? Or it's a bug in Hackintosh. Grateful for the attention

**Comment by mikebeaton** [comment]
Please open a new issue if you believe you have a valid bug in OpenCore or Tools to report, and please use forums for support otherwise. Please do not spam existing issues. (Which _are_ monitored, in this project.)
