### ISSUE TITLE
the firmware on your machine is not supported by the startup security utility

### ISSUE THREAD

**Issue by AaronRoshan** [acidanthera/bugtracker#2227]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

- Only the latest released versions of OpenCore, Lilu, and other KEXTs are supported.
- Bugreports involving Chameleon, Clover, Ozmozis or alike are not accepted.
- Include your your `EFI` directory with OpenCore.
- Include OpenCore DEBUG log (refer to `Target` in Configuration.pdf).
- Include Lilu DEBUG log (refer to `-liludbgall liludump=60` boot arguments in README).

Issue tracker is _not_ a support forum, and if you have installation or usage problems, try asking your questions on [InsanelyMac.com](https://www.insanelymac.com/forum/73-developers-corner/) or [AppleLife.ru](https://applelife.ru/forums/xakintosh.67/). There could also be local communities providing Acidanthera Project support in your native language.

For example, if you have an issue with AppleALC and you have not working sound, and you **cannot** offer new resources that fix the problem for you, you should go to the **support forums**. Here there are no people who create custom audio resources, or who deal with installation issues.

When to use issue tracker:
* You have new resources or patches to add but cannot make a pull request
* You have kernel panics, crashes, hangs and believe it is not a configuration issue
* You want to discuss technical or legal stuff

_If you have a kernel panic, please ensure that you have a DEBUG version of the extension and you have `-v keepsyms=1 debug=0x100` boot arguments added. On 10.13 or higher to avoid kext names scrolling over the panic log you should also set `PanicNoKextDump=YES` in OpenCore. Use `ApplePanic=YES` for write a kernel panic log to file._

**Comment by AaronRoshan** [comment]
the firmware on your machine is not supported by the startup security utility

my system is amd radeon 5600g

**Comment by AaronRoshan** [comment]
amd radeon 5600g the firmware on your machine is not supported by the startup security utility

how can I fix this please guid me to fix this issue

**Comment by mikebeaton** [comment]
It's not supposed to be supported, the Startup Security Utility sets the firmware password on _Apple_ firmware. You can set a password in OpenCore itself, if you need one, RTM.

Also, this is not a support forum, you even quoted it yourself above:

> Issue tracker is not a support forum, and if you have installation or usage problems, try asking your questions on [InsanelyMac.com](https://www.insanelymac.com/forum/73-developers-corner/) or [AppleLife.ru](https://applelife.ru/forums/xakintosh.67/). There could also be local communities providing Acidanthera Project support in your native language.

**Comment by AaronRoshan** [comment]
Hi
I'm using AMD hackintosh macOS Monterey Version 12.6.2
![Screenshot 2023-02-21 at 4 50 15 PM](https://user-images.githubusercontent.com/125876735/220331572-5be16ff3-d45b-4055-8292-02483124bb8f.png)
i cant access my black magic card. i'll try to recovery mode to access  Security Utility but my system showing **### THE 
FIRMWARE ON YOUR MACHINE IS NOT SUPPORTED BY THE STARTUP SECURITY UTILITY** please help me how to fix this issue 
Thank you.

**Comment by perez987** [comment]
@AaronRoshan 
Please read carefully to @mikebeaton. The Security Utility booting in recovery mode ONLY works on genuine Apple machines. It's not intended to work out of this scope. Of course not in Hackintosh. About the Black Magic card, go to a support forum (eg: InsanelyMac).
Please close this issue. Thanks.
