### ISSUE TITLE
Verbose text overhang still on Boot Menu in latest release

### ISSUE THREAD

**Issue by esafeddie** [acidanthera/bugtracker#2229]
Using Latest OC release (bc64f5a). To circumvent the problem, I built an EFI Folder using Mike Beaton's  - [
](https://github.com/acidanthera/OpenCorePkg/actions/runs/4215573415)I unreleased package. I would like to know if his edit will be implemented in any future releases as at the moment the Boot Menu is messy and unsightly.
Thank you.

![21201346](https://user-images.githubusercontent.com/7919587/220453564-abd1c330-e99d-4ffd-88be-3d419ead0eeb.png)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/2225

**Comment by esafeddie** [comment]
Thank you very much, works great, problem solved.
