### ISSUE TITLE
About 12th and 13th Generation Intel Processors OTA ventura 13.3 Beta

### ISSUE THREAD

**Issue by MizhiDR** [acidanthera/bugtracker#2230]
Hello everyoneI ，I have some problems and need your help！
It crashes while disabling CPU topology verification
Kernel Extensions in backtrace ！

**Comment by vandroiy2013** [comment]
We are aware of this issue. There is no solution yet.

**Comment by vandroiy2013** [comment]
Resolved in https://github.com/acidanthera/OpenCorePkg/pull/428
