### ISSUE TITLE
Graphical problem starting windows from Opencore

### ISSUE THREAD

**Issue by Lorys89** [acidanthera/bugtracker#2231]
up to release 0.8.8 there was no boot problem on windows nor on macos with verbose active, in the last commits of 0.9.0 you fixed it for macos but not for windows.
I am attaching 2 videos so you can understand the problem.

windows boot from opencore 0.8.8 release :
https://user-images.githubusercontent.com/64613690/220707521-53f3d521-22c9-4743-8e01-48cfde48bb6e.mp4

windows boot from opencore 0.9.0 dev last commit:
https://user-images.githubusercontent.com/64613690/220707704-d142b7be-b238-4e47-8690-2158fe519e91.mp4

I hope you understand the problem from the videos

**Comment by mikebeaton** [comment]
Okay, thanks for the heads up. On it.

**Comment by mikebeaton** [comment]
I've just run some tests, and it doesn't appear this way on my Dell, with the latest build. Instead the Dell logo clears the screen immediately, then the Windows loader appears over that as it should.

I accept that the problem is real, in fact I'm almost sure exactly what the fix is already, but I'd like to be sure exactly what's causing it - could you send your config.plist.

**Comment by Lorys89** [comment]
I have the pc in the office, in a couple of hours I'll send you the config. 
Do you think it's due to how I set the quirks ResetLogoStatus? But regardless with the same config but with oc 0.8.8 does in one way and with oc 0.9.0 in another and can be seen from the videos.

**Comment by mikebeaton** [comment]
Yes, it was ResetLogoStatus - thanks - but given this and other considerations, I have restored the change which made the difference here.

https://github.com/acidanthera/OpenCorePkg/commit/457c68dcdead63b33c2715e57fbe8a7ad0366db0

Please confirm fixed for you.

**Comment by Lorys89** [comment]
Thanks, now works fine both ways with and without quirks ResetLogoStatus.
