### ISSUE TITLE
Lilu DeviceInfo class skips detection of AMD iGPUs, causing issues for NootInc/WhateverRed

### ISSUE THREAD

**Issue by ChefKissInc** [acidanthera/bugtracker#2232]
Kexts like WhateverGreen which utilise the DeviceInfo class are unable to detect devices which are nested more than 1 level deep/are inside PCI bridges, i.e. PCI0.GPP8.IOPP.VGA_
Problem lies in DeviceInfo::grabDevicesFromPciRoot and DeviceInfo::create

**Comment by vit9696** [comment]
Mind submitting a patch? We do not have such systems. Thanks!

**Comment by ChefKissInc** [comment]
It looks like I've misunderstood the issue, sorry @vit9696. It appears to be acidanthera/Lilu#65 what is breaking our systems.
To be exact, this is preventing WhateverGreen from detecting and applying fixes on AMD iGPUs. I am aware that AMD systems are of no concern to this organisation, but it is conflicting with our work over at NootInc/WhateverRed, where we have display output being a hit or miss, even though we detect nothing wrong from our part, but rather AGDP is refusing to cooperate.

**Comment by vit9696** [comment]
May I see an IOReg for such a system? I think APUs should go to builtin device to be honest.

**Comment by vit9696** [comment]
Committed a fix to master. Please test. Note, that now it should correctly report the IGPU as a builtin.

**Comment by ChefKissInc** [comment]
There's a bit of a problem though; the AMD iGPUs are more or less the same as their dGPU family, so a few of the WhateverGreen fixes are needed like applbkl, unfairgva, and agdpmod. We'd have to duplicate those parts over in WhateverRed, and not only do we wish to avoid duplicating code, but also avoid licensing issues since we're unsure whether our license is compatible with WhateverGreen's

**Comment by vit9696** [comment]
Well, ok. Please retry with the latest change.

**Comment by ChefKissInc** [comment]
It's detected now by WhateverGreen (got renamed), but all of our testers with non-Renoir iGPUs are unavailable (including me) so I'm not sure about anything more than that, so I will assume all the other Radeon patches also will work

**Comment by vit9696** [comment]
Alright, I am closing this assuming at least partially fixed.

**Comment by ChefKissInc** [comment]
Actually, after reevaluating carefully, I think it would be better if we only copied the relevant parts of WhateverGreen (and giving credit), and have Lilu detect it as an iGPU to avoid any future or current issues or conflicts. This will also allow us to be more versatile. Therefore, I think you should revert back to when AMD iGPUs were detected as iGPUs. I apologise for the inconvenience.

**Comment by ChefKissInc** [comment]
(@vit9696)

**Comment by vit9696** [comment]
Ok, done.

**Comment by RubRLO** [comment]
hello friends, I would like a direction on my Ryzentosh. I'm testing WhateverRed.kext
![WhatsApp Image 2023-03-13 at 19 16 25](https://user-images.githubusercontent.com/59743626/224853796-5f6cf569-4263-42d8-8a4c-cc2b304218e5.jpeg)
could someone help me with this? Boot stopped at this part

**Comment by RubRLO** [comment]
AMD Ryzen 7 3700U RX Vega 10
