### ISSUE TITLE
After updating to 0.8.9, the GUI menu does not appear when booting from a USB memory.

### ISSUE THREAD

**Issue by mifjpn** [acidanthera/bugtracker#2234]
Thanks for the great development as always.
When OpenCore0.8.9 is put in SSD, GUI menu appears normally.
However, when the same thing is put into the USB memory installer, the GUI menu does not appear.
I don't think there were any major changes...
Thank you.
[EFI-Log.zip](https://github.com/acidanthera/bugtracker/files/10830340/EFI-Log.zip)

**Comment by mikebeaton** [comment]
Please provide a debug log. EFI-Log.zip has your EFI folder, but no log within it.

**Comment by mifjpn** [comment]
Sorry but,Is it debug-log,is'nt it?

[opencore-2023-02-25-051144.txt](https://github.com/acidanthera/bugtracker/files/10830819/opencore-2023-02-25-051144.txt)

**Comment by mikebeaton** [comment]
Well, two things. 1. That file is not in your original EFI-Log.zip. 2. That file is not a debug log.

**Comment by mifjpn** [comment]
Thank you.
I switched to 0.8.9 debug and did the same thing.
[EFI-debug.zip](https://github.com/acidanthera/bugtracker/files/10832478/EFI-debug.zip)
[opencore-2023-02-25-225248.txt](https://github.com/acidanthera/bugtracker/files/10832480/opencore-2023-02-25-225248.txt)

**Comment by mikebeaton** [comment]
Okay thank you.

Please redescribe your symptoms - that looks like a log of a perfectly normal boot, including displaying the OpenCore GUI menu (OpenCanopy), then selecting and successfully booting into Ventura installer.

Please describe what you saw, if not that. Also please provide a debug log, config.plist (if any different), and description of what happens instead, for working 0.8.8 version.

**Comment by mifjpn** [comment]
very sorry.

It was caused by some BIOS settings that behaved strangely on this computer.
About the boot, it was not UEFI only. (CSM enabled)

Even in that case, the GUI menu derived from Opencanopy was displayed when booting from SSD.
But booting from the USB installer didn't show this menu.

In any case, I am to blame for not reviewing the settings.

I am very sorry.
