### ISSUE TITLE
[Feature Request] - Improve ocvalidate warning comments

### ISSUE THREAD

**Issue by Allen050329** [acidanthera/bugtracker#2236]
When validating a borked or old config.plist (e.g. 0.7.6 config using ocvalidate from 0.9.0), the program reports some missing entries as such:
``OCS: Missing key ResizeUsePciRbIo, context <Quirks>!``

It would be great to improve the verbosity of the warning comment like 
``OCS: Missing key ResizeUsePciRbIo, context <UEFI/Quirks>!``
Thus, the end-user can easily know where to fix the config, instead of having to look through each of the Quirks context, which is in the majority of config.plist sections, which will make the update process much more streamlined.
(Thanks to dreamwhite in the r/Hackintosh Paradise Discord for rephrasing the whole issue)

**Comment by alarifgit** [comment]
Surely this is what OCConfigCompare exists for?

**Comment by PMheart** [comment]
Unfortunately this would have been implemented if it was that easy. ocvalidate relies on the OcXmlLib for XML parsing, thus thus feature requires a complete rework of this library, which is barely possible. I am afraid that we will not be able to work on this. Apologies.
