### ISSUE TITLE
Trackpoint on thinkpad doesn't work anymore after "Fixed handleClose not being called by VoodooInput" update

### ISSUE THREAD

**Issue by antoniomcr96** [acidanthera/bugtracker#2240]
As the title suggests, the trackpoint of a Lenovo Thinkpad (L390) and its buttons no longer work after the last update of VoodooPS2 (https://github.com/acidanthera/VoodooPS2/pull/56). No problem with previous commit.
Elan trackpad works as always.
MacOS 11.7.4; OC 0.9.0
Let me know what I can provide to give you more information.
As always, thanks for your work

**Comment by 1Revenger1** [comment]
[VoodooPS2Controller-2.3.5-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/10947123/VoodooPS2Controller-2.3.5-DEBUG.zip)
Does this build work? Looks like some other stuff tried to open the Trackpad drivers too 😰

**Comment by antoniomcr96** [comment]
Thanks. I tried your build. Unfortunately, trackpoint doesn't work

**Comment by 1Revenger1** [comment]
[VoodooPS2Controller-2.3.5-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/10949212/VoodooPS2Controller-2.3.5-DEBUG.zip)
Are you able to provide an IOReg file from IORegistryExplorer? A log would also be helpful. Easiest way to do that is to grab DebugEnhancer.kext, add the `msgbuf=1048576` boot-arg, then run `sudo dmesg | grep -i ps2 > ~/Desktop/ps2.txt` and upload the ps2 log on your desktop.

**Comment by takobaba** [comment]
@1Revenger1 
I have tried yours. It worked for me!!!
Here is the log attached also.

**Comment by antoniomcr96** [comment]
Sorry for the delay. Unfortunately the last build you shared doesn't work for me.
Here is the required log
[ps2ThinkpadL390.txt](https://github.com/acidanthera/bugtracker/files/10962041/ps2ThinkpadL390.txt)

**Comment by 1Revenger1** [comment]
Are you using VoodooInput provided with the VoodooPS2 download above? Not seeing anything weird in the log.

**Comment by antoniomcr96** [comment]
> Are you using VoodooInput provided with the VoodooPS2 download above? Not seeing anything weird in the log.

the problem was exactly that, I was using an older version of voodooinput. Using the one included in the build now everything works fine. Thanks so much for the fix and support

**Comment by takobaba** [comment]
@1Revenger1  
Is the fix going to be merged for the next release/version. it will be ready under stable repo when official 2.3.5 is released?

**Comment by takobaba** [comment]
the latest built 2.3.5 still doesnt work.

**Comment by 1Revenger1** [comment]
Are you using the version of VoodooInput provided in VoodooPS2 2.3.5? I'm not seeing anything obvious that would've broken it between the build I sent above and 2.3.5

**Comment by takobaba** [comment]
Ok sorry my bad, it is actually okay.
