### ISSUE TITLE
Display static on FB initialization w/ DisplayPort ASUS ScreenPad devices

### ISSUE THREAD

**Issue by Qonfused** [acidanthera/bugtracker#2243]
## Background

I've been investigating an issue with the secondary screenpad display on the ASUS Zenbook Duo notebooks that causes RGB static when the display device is initialized. This behavior only occurs during the second stage of boot into macOS or recoveryOS or upon hot-plug of the screenpad device. This appears to affect [UX481FA/UX481FL](https://www.asus.com/us/laptops/for-home/zenbook/zenbook-duo-ux481/) (CML-U) Zenbook Duo models and [UX581GV](https://www.asus.com/us/Commercial-Laptops/ZenBook-Pro-Duo-UX581GV/) (CFL-H) + [UX581LV](https://www.asus.com/laptops/for-home/zenbook/zenbook-pro-duo-ux581/) / [UX582LV](https://www.asus.com/us/laptops/for-creators/zenbook/zenbook-pro-duo-15-oled-ux582/) (CML-H) Zenbook Pro Duo models, albeit the latter CML-H models are largely unaffected by this issue.

This does not appear to be a bug with WhateverGreen or an issue caused by/addressable with EDID patching or CSM, but a conflict w/ the framebuffer controller or CFL driver. I've verified that this is not a configuration issue suitable for support forums through my tracking in https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/4.

For clarity (as the description of 'static' is quite vague), here is a video of the display static w/ misc DDC functions like backlight, panel power, and hot-plug demonstrated as working:

<div align="center" class="flex-video">
<video src="https://user-images.githubusercontent.com/32466081/224650226-7e644ac1-740d-4309-80ce-2fbc0a30d930.mov" controls>
</video>
<p/>
</div>

## Observed Behavior

The screenpad works correctly during the first stage of boot (w/ GOP before GPU driver initialization), but after the second stage of boot, the screenpad displays static. It also shows a black screen very briefly upon hot-plug (before macOS initializes the display) or when no display connector is defined for con1/index1 (disabled); this behavior is expected. Otherwise, the static issue is present regardless of the framebuffer profile or busID + connector type, coinciding w/ when the display is initialized by macOS.

I've noted some other observations that help clarify this behavior:
- The display is connected through a standard DP interface on DDI port B (DDI1/DDPB or FB1).
- All PCH South sideband signals appear to function properly (e.g. DDC, GMBUS I2C GPIO).
- Notably, as this also affects a CFL-H variant (UX581GV), it doesn't seem specific to the CFL framebuffer driver's handling of LP-chipsets (for U-series processors).
- This issue occurs regardless of whether the display was connected during boot (e.g. display starts powered off and is later powered on). In other words, it is not dependent on any handling at boot and can be reproduced after hot-plug.
- This also occurs in macOS Recovery; presumably after macOS/recoveryOS initializes display pipes/buffers, etc w/ the CFL framebuffer driver. Notably, this occurs even w/o acceleration.
- The screenpad is present in IO registry and system information with detected display type, timings, native/default resolution, and vendor/product ids (from EDID).
- DRM appears to work (tested FairPlay 1.x and 2.x/3.x), though HDCP writes fail upon initialization of the second display (hot-plug or during boot). This also affects HDMI though this issue does not obfuscate HDMI signal.

## Testing configuration

I've tested this with a UX481FL ZenBook Duo with an i7-10510u (CML-U) CPU and UHD 620 iGPU. Connected to the iGPU (in DDI order) are an eDP primary display, a DP secondary (screenpad) display, and an HDMI 1.4 port; both the primary display and HDMI connector work fine. The DisplayPort connector/signals from the screenpad aren't at all exotic, though I've started to detail some of ASUS's implementation [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/blob/main/docs/resources/screenpad-plus.md). This was tested with DVMT set to 64mb in BIOS (w/ no CSM option), and across all mobile CFL/CML framebuffer ids + connector patches (busids, etc).

As hardware availibility for these laptops is limited, I'd also appreciate input + reports for this issue by anyone affected. I've created a very rudimentary debug script [here](https://gist.github.com/Qonfused/2864f990398edef4e150f0b1de178fab) for dumping kernel logs and some misc. diagnostics + ioreg output.

For reference, below is a debug build of my UX481FA/FL EFI with a copy of my current config.plist:
* [EFI-7f5c9c55.zip](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/suites/11686135924/artifacts/607595227) (latest debug build)
* [config.plist](https://github.com/acidanthera/bugtracker/files/11012837/config.plist.zip) (latest tested)

This is how the screenpad display shows up in System Information (also using a display override):

![Screenshot_2023-03-13_at_5 02 38_AM](https://user-images.githubusercontent.com/32466081/224669757-e415a4f6-8079-4d57-8d2f-b18de8af10da.png)

### Logs

Below are logs dumped using `liludump=60 -liludbg -wegdbg` boot args:
* (Lilu + plugins): [Lilu_1.6.5_22.2.txt](https://github.com/acidanthera/bugtracker/files/11082972/Lilu_1.6.5_22.2.txt)
* (Lilu only): [Lilu-1.6.5.log](https://github.com/acidanthera/bugtracker/files/11083004/Lilu-1.6.5.log)
* (WhateverGreen only): [WhateverGreen-1.6.5.log](https://github.com/acidanthera/bugtracker/files/11083000/WhateverGreen-1.6.5.log)

I've attached the output of the debug script ([ref](https://gist.github.com/Qonfused/2864f990398edef4e150f0b1de178fab)) containing some common kernel and system logs from my UX481FL:
* [debug.zip](https://github.com/acidanthera/bugtracker/files/11012831/debug.zip)

For reference, below is a pruned log of CFL driver kernel logs containing only relevant lines for the screenpad (FB1) emitted after hot-plugging the display:

* [AppleIntelCFLGraphicsFramebuffer.log](https://github.com/acidanthera/bugtracker/files/11070518/AppleIntelCFLGraphicsFramebuffer.log)

<details><summary>This log was synced to the device's physical behavior based on a screen + device recording.</summary>
<p>

https://user-images.githubusercontent.com/32466081/227744065-b3f8b14f-7980-4ba7-b082-c79640716785.mov

</p>
</details>

### Hardware Docs

For brevity, only the most relevant resources are included below.

#### Display Panels
Panel | Model | Zenbook Duo Models
--- | --- | ---
BOE087F | [NV126B5M-N41](https://www.panelook.com/NV126B5M-N41_BOE_12.6_LCM_overview_44187.html) | • UX481FA/FL
BOE085F | [NV140XTM-N52](https://www.panelook.com/NV140XTM-N52_BOE_14.1_LCM_overview_46502.html) | • UX581GV/LV<br>• UX582LV

You can find a list of all related hardware docs [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/tree/main/docs/resources/data%20sheets).

**Comment by Qonfused** [comment]
I'm sure more has been discovered + discussed internally, though this is the run-down on what c++ symbols I can find mentioned/used by WEG applicable to CFL+ iGPUs, etc:

<details><summary>WEG symbols</summary>

```cpp
kern_igfx_clock.cpp
// IGFX::DPCDMaxLinkRateFix::processFramebufferKextForCFL
150,4:  __ZN31AppleIntelFramebufferController7ReadAUXEP21AppleIntelFramebufferjtPvP21AppleIntelDisplayPath
// IGFX::CoreDisplayClockFix::processFramebufferKext
494,4:  __ZN31AppleIntelFramebufferController21probeCDClockFrequencyEv
500,5:  __ZN31AppleIntelFramebufferController14disableCDClockEv
501,5:  __ZN31AppleIntelFramebufferController19setCDClockFrequencyEy
// IGFX::HDMIDividersCalcFix::processFramebufferKext
689,39:  __ZN31AppleIntelFramebufferController17ComputeHdmiP0P1P2EjP21AppleIntelDisplayPathPNS_10CRTCParamsE
// IGFX::MaxPixelClockOverride::processFramebufferKext
912,4:  __ZN21AppleIntelFramebuffer15connectionProbeEjj

kern_igfx_debug.cpp
// IGFX::FramebufferDebugSupport::processFramebufferKext
337,5:  __ZN21AppleIntelFramebuffer16enableControllerEv
338,5:  __ZN21AppleIntelFramebuffer25setAttributeForConnectionEijm
339,5:  __ZN21AppleIntelFramebuffer25getAttributeForConnectionEijPm
340,5:  __ZN21AppleIntelFramebuffer14setDisplayModeEii
341,5:  __ZN21AppleIntelFramebuffer15connectionProbeEjj
342,5:  __ZN21AppleIntelFramebuffer16getDisplayStatusEP21AppleIntelDisplayPath
343,5:  __ZN21AppleIntelFramebuffer13GetOnlineInfoEP21AppleIntelDisplayPathPhS2_PNS0_15DisplayPortTypeEPbb
344,5:  __ZN21AppleIntelFramebuffer15doSetPowerStateEj
345,5:  __ZN21AppleIntelFramebuffer18IsMultiLinkDisplayEv
346,5:  __ZN21AppleIntelFramebuffer19validateDisplayModeEiPPKNS_15ModeDescriptionEPPK29IODetailedTimingInformationV2
347,5:  __ZN31AppleIntelFramebufferController18hasExternalDisplayEv
348,5:  __ZN31AppleIntelFramebufferController15SetDPPowerStateEP21AppleIntelFramebufferhP21AppleIntelDisplayPath
349,5:  __ZN31AppleIntelFramebufferController14setDisplayPipeEP21AppleIntelDisplayPath
350,5:  __ZN31AppleIntelFramebufferController11setFBMemoryEP21AppleIntelFramebuffer
351,5:  __ZN20IntelFBClientControl11doAttributeEjPmmS0_S0_P25IOExternalMethodArguments

kern_igfx_i2c_aux.cpp
// IGFX::AdvancedI2COverAUXSupport::processFramebufferKext
32,5:  __ZN31AppleIntelFramebufferController14ReadI2COverAUXEP21AppleIntelFramebufferP21AppleIntelDisplayPathjtPhbh
37,5:  __ZN31AppleIntelFramebufferController15WriteI2COverAUXEP21AppleIntelFramebufferP21AppleIntelDisplayPathjtPhb

kern_igfx_lspcon.cpp
// IGFX::LSPCONDriverSupport::processFramebufferKext
190,4:  __ZN31AppleIntelFramebufferController11GetDPCDInfoEP21AppleIntelFramebufferP21AppleIntelDisplayPath
196,4:  __ZN31AppleIntelFramebufferController7ReadAUXEP21AppleIntelFramebufferjtPvP21AppleIntelDisplayPath

kern_igfx_memory.cpp
// IGFX::DVMTCalcFix::processFramebufferKext
78,50:  __ZN31AppleIntelFramebufferController13FBMemMgr_InitEv
90,21:  __ZN11IOPCIDevice20extendedConfigRead16Ey
// IGFX::DisplayDataBufferEarlyOptimizer::processFramebufferKext
310,39:  __ZN31AppleIntelFramebufferController17getFeatureControlEv

kern_igfx_pm.cpp
// IGFX::RPSControlPatch::processFramebufferKext
151,4:  __ZL15pmNotifyWrapperjjPyPj
// IGFX::RPSControlPatch::processGraphicsKext
165,52:  __ZN26IGHardwareCommandStreamer514submitExecListEj
165,107:  __ZN26IGHardwareCommandStreamer514submitExecListEj
// IGFX::ForceWakeWorkaround::processGraphicsKext
322,4:  __ZN16IntelAccelerator26SafeForceWakeMultithreadedEbjj

kern_igfx.cpp
// IGFX::processKernel
277,40:  __ZN9IOService20copyExistingServicesEP12OSDictionaryjj
// IGFX::processKext
287,52:  __ZN18IGTelemetryManager16prepareTelemetryEj
304,41:  __ZN16IntelAccelerator5startEP9IOService
360,32:  __ZN31AppleIntelFramebufferController16getOSInformationEv
// IGFX::MMIORegistersReadSupport::processFramebufferKext
461,13:  __ZN31AppleIntelFramebufferController14ReadRegister32Em
// IGFX::MMIORegistersWriteSupport::processFramebufferKext
551,13:  __ZN31AppleIntelFramebufferController15WriteRegister32Emj
// IGFX::ForceCompleteModeset::processFramebufferKext
634,4:  __ZN31AppleIntelFramebufferController16hwRegsNeedUpdateEP21AppleIntelFramebufferP21AppleIntelDisplayPathPNS_10CRTCParamsEPK29IODetailedTimingInformationV2
// IGFX::ForceOnlineDisplay::processFramebufferKext
709,4:  __ZN21AppleIntelFramebuffer16getDisplayStatusEP21AppleIntelDisplayPath
// IGFX::AGDCDisabler::processFramebufferKext
747,4:  __ZN20IntelFBClientControl11doAttributeEjPmmS0_S0_P25IOExternalMethodArguments
// IGFX::TypeCCheckDisabler::processFramebufferKext
779,5:  __ZN31AppleIntelFramebufferController17IsTypeCOnlySystemEv
// IGFX::BlackScreenFix::processFramebufferKext
816,5:  __ZN31AppleIntelFramebufferController16ComputeLaneCountEPK29IODetailedTimingInformationV2jPj
// IGFX::PAVPDisabler::processGraphicsKext
898,14:  __ZN16IntelAccelerator19PAVPCommandCallbackE22PAVPSessionCommandID_tjPjb
// IGFX::wrapLoadFirmware
1230,9:  __ZN12IGScheduler415systemWillSleepEv
1230,51:  __ZN12IGScheduler413systemDidWakeEv
// IGFX::loadIGSchedular4Patches
1356,60:  __ZL17__KmGen9GuCBinary
1360,46:  __ZN13IGHardwareGuC13loadGuCBinaryEv
1390,9:  __ZN12IGScheduler412loadFirmwareEv
1391,9:  __ZN13IGHardwareGuC16initSchedControlEv
1392,9:  __ZN20IGSharedMappedBuffer11withOptionsEP11IGAccelTaskmjj

kern_weg.cpp
// WEG::processKext
347,64:  __ZL16gIOFBVerboseBoot
349,41:  __ZN13IOFramebuffer6initFBEv
360,6:  __ZN25AppleMCCSControlGibraltar5probeEP9IOServicePi
361,6:  __ZN21AppleMCCSControlCello5probeEP9IOServicePi
373,40:  __ZN15AppleIntelPanel10setDisplayEP9IODisplay
// WEG::processGraphicsPolicyMods
626,40:  __ZN25AppleGraphicsDevicePolicy5startEP9IOService
```

</details>

As I investigate this I'd appreciate feedback here as I don't have enough familiarity with macOS to discern the boiler-plate from these kexts nor how well known WEG's implementation is. I have experience with very similar XNU source from kernel debugging iOS with IDA Pro, albeit I am new to using macOS's KDKs and Hopper.  I'm not adverse to fixing/re-implementing any existing WEG fixes, though I'd appreciate any help that can shrink the search space as my time is quite limited.

I should clarify that I'm not looking for an easy fix for this issue, just wondering if I may be treading on new territory for CFL/CML or if similar behavior has been observed before.

**Comment by Qonfused** [comment]
Changing the <kbd>CachedEDIDDisable</kbd> and/or <kbd>IgnorePanelTmings</kbd> FeatureControl options on the CFL framebuffer driver doesn't change any behavior here (and probably shouldn't unless there is some EDID caching issue). Thought I should mention that as (I believe) it was suggested as a potential fix in https://github.com/wern-apfel/WhateverGreen/commit/16413cf1d9c34b4381a472ea98d9db5c52206814. Additionally, even though ICL has a very different architecture from Skylake+, I did try some FeatureControl other workarounds suggested in other issues (https://github.com/Ardentwheel/OpenCore-Hasee-X57S1/issues/3) but I haven't noticed any clear change in behavior or logs.

However, with the UX581GV (CFL-H) and UX582LV (CML-H) models, there were some observations of different behavior with the screenpad when the primary display isn't connected; e.g. some framebuffers that disable the primary display connector allowed the screenpad to work for those ZenBook Pro Duo models. I haven't reproduced the same behavior on the UX481FL model, which doesn't have any similar change in behavior regardless of framebuffer/busID/etc connector patches, and even when the physical primary display connector is removed.

You can find a breakdown of some of these reports here (most notably **rogerdcarvalho**'s):
* https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/4#issuecomment-1442815250

CC @shiecldk and @rogerdcarvalho if you have any more input here.

A thought I had was to instead look for references to display flags for the primary display in the fb driver logic. The assumption is that there may be some driver blocking/conflict when the internal display is connected w/ the screenpad, similar to how some internal display flags affect HDMI audio for external displays. I've seen flags `CNUnknownFlag_10` (#442) and `CNUnknownFlag_100` (#1189) mentioned in other issues to have some side effects of disabling HDMI audio and display rotation.

**Comment by Qonfused** [comment]
Created a very rudimentary debug script [here](https://gist.github.com/Qonfused/2864f990398edef4e150f0b1de178fab) for dumping kernel logs and some misc. diagnostics + ioreg output.

* [EFI-b13f8e42.zip](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/suites/11339870435/artifacts/582698879) (latest build)
* [config.plist](https://github.com/acidanthera/bugtracker/files/11012837/config.plist.zip) (latest tested)
* [debug.zip](https://github.com/acidanthera/bugtracker/files/11012831/debug.zip)

**Comment by Qonfused** [comment]
Below is a pruned log of CFL driver kernel logs containing only relevant lines for the screenpad (FB1):

[AppleIntelCFLGraphicsFramebuffer.log](https://github.com/acidanthera/bugtracker/files/11070518/AppleIntelCFLGraphicsFramebuffer.log)

These are emitted after hot-plugging the display, which for reference was synced based on a screen + device recording below:

> --- https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/4#issuecomment-1483931581 ---
> I tried to record and sync the device + screen streaming CFL driver kernel log messages, which only sorta pinpoints when the static behavior starts in logs. A very obvious issue that I didn't consider was that screen recorded frames are interrupted when reinitializing displays' framebuffers, which makes this process difficult to fine-tune. At the very least, it does help cut down the noise by showing logs generated after the static behavior is present:
> 
> https://user-images.githubusercontent.com/32466081/227744065-b3f8b14f-7980-4ba7-b082-c79640716785.mov
>
> <br>
>
> <details><summary>This screenshot shows the same messages from before the primary display went black (84 messages, timestamp: <code>16:15:47.253602-0500</code>):</summary>
> <p>
> 
> ![Screenshot 2023-03-25 at 5 01 40 PM](https://user-images.githubusercontent.com/32466081/227744459-e91048c5-3623-4613-b71d-eaa449e0618c.png)
> 
> </p>
> </details> 
> 
> <details><summary>
> This next screenshot is about the next frame, after the kernel log resyncs (1,152 messages, timestamp: <code>16:15:49.553049-0500</code>)</summary>
> <p>
> 
> ![Screenshot 2023-03-25 at 5 07 45 PM](https://user-images.githubusercontent.com/32466081/227744640-45524b56-f8bd-4929-a5e7-b1f64ecba4fa.png)
> 
> </p>
> </details>
> 
> Kernel logs: 
> [kernel-logs.zip](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/files/11070333/kernel-logs.zip)

**Comment by Qonfused** [comment]
Intel doc on the blitter/ BLT engine: https://cdrdv2-public.intel.com/685892/intel-gfx-prm-osrc-skl-vol11-blitter.pdf#page5

**Comment by vit9696** [comment]
Not sure there is anything WEG can handle. if I remember correctly, there is no proper concept of power-off in Apple drivers, and it may well be that this second display is connected via some proprietary MUX thus no dice.

**Comment by Qonfused** [comment]
Yeah, there don't appear to be any current WEG patches that directly address this issue. However, this issue may require patching CFL framebuffer driver logic with hex patching or by hooking w/ WEG. Additionally, there is no MUX involved with the screenpad; display signals are split between a DDI interface with the CPU with additional sideband signals to the PCH.

Regarding hardware compatibility with macOS, the screenpad has been tested as working between @shiecldk (UX582) and @wern-apfel (UX481), albeit the latter has not yet been reproduced.

**Comment by Qonfused** [comment]
I'd prefer leaving this issue open until it's been resolved (for visibility), though depending on how you triage your issues it'd be fair to mark it low-priority until there is more progress.

A current blocker is a lack of observability for the UX582LV's case (unaffected by this issue); there is a unique opportunity to compare with the UX581LV (affected by this issue), which has *very* small hardware + firmware differences.

A potential explanation is that HDCP is stripped from the screenpad causing HDCP scrambling, which best describes the static behavior qualitatively. Looking at the UX481 device schematic though, it's unclear how this would occur without an intermediate display connector or similar. If anyone has investigated HDCP authentication in macOS, it would also help to know whether de-oping HDCP in the FB driver may cause any adverse effects (beyond DRM of course).
