### ISSUE TITLE
Chromium based apps are blank after waking from sleep with -ifgxnotelemetryload

### ISSUE THREAD

**Issue by meghan06** [acidanthera/bugtracker#2247]
**Description**

After waking from sleep, Chromium based apps like Discord, Google Chrome, and Spotify will launch with a blank screen. If the app was open when the user set their PC to sleep, it would function like normal. This only happens when opening an app for the first time after waking from sleep.
On Safari, Youtube will refuse to play videos and will just load the video indefinitely, Spotify launches blank, and Discord will launch with a blank / white updater.
They'll work fine if they were open when you set the laptop to sleep, but if they were completely closed i.e ctrl q'd, then that's when issues arise. See below for an example. 
I have tested extensively, and it only happens on Electron/Chromium based apps. All default apps that came with macOS (like terminal, settings, safari, finder, facetime, etc) all work fine.

![image](https://user-images.githubusercontent.com/77316348/226065096-26f97227-fc9d-4dbf-a2d0-8734ca528248.png)

**Expected Behavior**
Chromium basedapps will launch with no rendering issues after sleep.

**Behavior**
Chromium based apps launch with a blank screen after waking from sleep.

**Steps to Reproduce:**
1.  Close target app entirely (CTRL +Q)
2. Set laptop to sleep
3. Wake from sleep
4. Open app

**Comment by vit9696** [comment]
I guess the solution would be not to use this flag.

**Comment by meghan06** [comment]
There is no iGPU acceleration without this flag.
