### ISSUE TITLE
RunningMode::RunningInstallerRecovery is unreliable

### ISSUE THREAD

**Issue by ChefKissInc** [acidanthera/bugtracker#2248]
RunningMode::RunningInstallerRecovery is only set at 2nd update stage (first reboot). Recovery partition and next update stages seem to have it unset.
macOS Version: 11.7.4 (Big Sur)
Lilu version: 1.6.4

**Comment by vit9696** [comment]
Do you have an idea how can we detect these stages? E.g. some boot arguments or device tree specifics?

**Comment by ChefKissInc** [comment]
I don't know about anything else, but the boot args remain the same. I tested it by printing the contents of the value returned by PE_boot_args

**Comment by ChefKissInc** [comment]
(This test was conducted on the Big Sur recovery dmg, aka com.apple.recovery.boot/BaseSystem.dmg)

**Comment by vit9696** [comment]
Sorry, if I was unclear, I mean the boot arguments one can use to detect the recovery. Perhaps you would be able to provide the IORegistry dump (IOService and IODeviceTree planes) in the recovery?

**Comment by ChefKissInc** [comment]
I understood perfectly fine. My response was there's no new boot args appended while booting the macOS 11 Recovery DMG; they remain the same as the ones in the `config.plist` according to my debug print with the contents of `PE_boot_args()`. I'll try to fetch the IORegistry dump while in recovery for further inspection

**Comment by ChefKissInc** [comment]
Here you go @vit9696
[MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/11414715/MacBook.Pro.ioreg.zip)

**Comment by vit9696** [comment]
Please test.

**Comment by ChefKissInc** [comment]
Works fine, @vit9696! Don't forget to fix the Analysis issues, lol

**Comment by ChefKissInc** [comment]
Note: Only normal boot and the recovery update was tested. I'm going to perform an update now to make sure it works here as well

**Comment by ChefKissInc** [comment]
Unfortunately, due to unexpected issues I'm unable to perform an update at this time. I will need someone else to test this

**Comment by vit9696** [comment]
I fixed the analysers and will merge the patch. I suggest you to raise a new issue if the update fails.
