### ISSUE TITLE
Ventura Boot Issues in MacPro 2013 dual D700 gpu

### ISSUE THREAD

**Issue by DHERRADOR** [acidanthera/bugtracker#2249]
A few days ago, I installed OpenCore-Patcher version 0.6.1.
It's important to note that I did a clean install of the Ventura operating system on a freshly formatted hard drive.
I performed the "Post Install Root Patch" process with root permissions and restarted my machine.
Apparently, my 2013 Mac Pro 6.1 was able to detect the two graphics cards installed, two D700 graphics cards.
I can see this thanks to my iStatMenus software, which correctly displays two charts, one for each GPU in the computer.

However, a few days ago I noticed that iStatMenus had stopped showing two graphics, and only showed one.
As if the system was only able to detect one of the two D700 cards.

After many tests, I found that the problem arises when I shut down the computer.
Let me explain. If I redo the "Post Install Root Patch" process and restart, both graphics cards reappear. 
But immediately after shutting down the computer, one of them disappears again.
I've repeated this up to 3 times, and the same thing always happens.
So I'm forced to perform the "Post Install Root Patch" process every time I use the computer and want to use FinalCut, for example, with my two gpu.

I don't know if any other users have noticed this or if it's useful for the community that me to post this.
If any developer from the OpenCore-Patcher team wants to help me, I'm willing to try "beta" versions to try to fix the problem.
I'm a computer scientist, although I haven't used my programming knowledge for years. But I've been an advanced Mac user for more than 20 years.

Even if nobody responds, I'd like to thank the OpenCore-Patcher development team for allowing me to enjoy my MacPro 6.1 for a few more years.

Regards
![After patch and reboot](https://user-images.githubusercontent.com/1575263/226107123-7edf8e99-e016-4283-85bb-9c6aad827648.png)
![After shutdown](https://user-images.githubusercontent.com/1575263/226107124-ceacef4f-5b7c-4a77-87a5-a02a6323808b.png)

**Comment by vandroiy2013** [comment]
Hi. OpenCore legacy patcher is not an Acidanthera project. 
You can open new issue on OpenCore lagacy patcher bugtracker
https://github.com/dortania/OpenCore-Legacy-Patcher/issues

**Comment by DHERRADOR** [comment]
> Hi. OpenCore legacy patcher is not an Acidanthera project.
> You can open new issue on OpenCore lagacy patcher bugtracker
> https://github.com/dortania/OpenCore-Legacy-Patcher/issues

Thanks vandroiy. 
But as you surely knows I can't open an issue in the link you send me.
So sadly I won't be able to communicate my issue to someone try to solve it.
In any case, sorry to post it incorrectly.

**Comment by vandroiy2013** [comment]
If there are legitimate issues with the project, please direct them to our Discord Server as we have many more active users willing to discuss and help:

[OpenCore Patcher Paradise Discord Server](https://discord.gg/rqdPgH8xSN)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/dortania/bugtracker/issues
