### ISSUE TITLE
[FutureRequest] - add custom sensor with smc super io 

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#2253]
I use ioio + yoga smc for find all sensor in my DSDT :

for example :
CTMP : CPU System Agent Core temp
![Screenshot 2023-03-25 at 17 17 09](https://user-images.githubusercontent.com/35195176/227721075-168c987f-f04d-4c06-9391-af11eae4c9db.png)

![Screenshot 2023-03-25 at 17 17 32](https://user-images.githubusercontent.com/35195176/227721127-c6467976-2bf6-4797-b0e0-8f33c5faabc6.png)

something for battery temp
![223802515-39dd95c9-1db4-4d4a-b614-6e00d046d9ee](https://user-images.githubusercontent.com/35195176/227721350-62ae9926-6a3d-462d-9834-4ccc475f2d4f.png)
but in super io kext only can add Fan reading .
some device like HP can not use yoga smc and only sensor show cpu and ssd temp

**Comment by vit9696** [comment]
A pull-request for such a feature would be welcome.
