### ISSUE TITLE
nvme kernel panic

### ISSUE THREAD

**Issue by henrycoding** [acidanthera/bugtracker#2254]
panic(cpu 2 caller 0xffffff8007de6676): nvme: "3rd party NVMe controller. PCI link down. Delete IO submission queue. fBuiltIn=1 MODEL=INTEL SSDPEKKF256G7L FW=123P CSTS=0xffffffff US[1]=0x0 US[0]=0x138 VID=0xffff DID=0xffff CRITICAL_WARNING=0x0.\n" @IONVMeController.cpp:6151
Panicked task 0xffffffaa7d832208: 180 threads: pid 0: kernel_task
Backtrace (CPU 2), panicked thread: 0xffffffa5b02db598, Frame : Return Address
0xffffffc480917b40 : 0xffffff80055eb38d 
0xffffffc480917b90 : 0xffffff8005758ed6 
0xffffffc480917bd0 : 0xffffff8005748120 
0xffffffc480917c20 : 0xffffff8005585951 
0xffffffc480917c40 : 0xffffff80055eb66d 
0xffffffc480917d30 : 0xffffff80055ead19 
0xffffffc480917d90 : 0xffffff8005de072b 
0xffffffc480917e80 : 0xffffff8007de6676 
0xffffffc480917e90 : 0xffffff8007dc97db 
0xffffffc480917ec0 : 0xffffff8007dc997b 
0xffffffc480917ef0 : 0xffffff8007dc9c3e 
0xffffffc480917f30 : 0xffffff8005d9f2d5 
0xffffffc480917f70 : 0xffffff8005d9efda 
0xffffffc480917fa0 : 0xffffff800558519e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[C334C31D-7F48-3BE5-A0A4-108210D621D0]@0xffffff8007dc1000->0xffffff8007dedfff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[DB38BB35-D38C-3110-9B53-0D2927F702CF]@0xffffff8006bc5000->0xffffff8006bf3fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[802B9CA4-B851-396E-8DA4-B30E751EC48F]@0xffffff8008059000->0xffffff8008088fff
            dependency: com.apple.iokit.IOReportFamily(47)[D8F664BF-70CB-3596-A4D5-35E72EBC36EE]@0xffffff800809a000->0xffffff800809cfff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[62F2C392-9547-33CB-8E12-6F77B7B052AF]@0xffffff800818c000->0xffffff80081a2fff

Process name corresponding to current thread (0xffffffa5b02db598): kernel_task
Boot args: -no_compat_check debug=0x100 -lilubetaall -wegbeta -alcbeta igfxonln=1

Mac OS version:
22D68

Kernel version:
Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
Kernel UUID: 10E5D254-4A37-3A2A-B560-E6956A093ADE
roots installed: 0
KernelCache slide: 0x0000000005200000
KernelCache base:  0xffffff8005400000
Kernel slide:      0x00000000052dc000
Kernel text base:  0xffffff80054dc000
__HIB  text base: 0xffffff8005300000
System model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)
System shutdown begun: YES
Panic diags file available: NO (0xe00002cd)
Hibernation exit count: 0

System uptime in nanoseconds: 1822449640836
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000001a85276a88e
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000755b14cad 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 1 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff9a7c790000 - 0xffffffba7c790000
  . PGZ   : 0xffffff9a7c790000 - 0xffffff9a7e791000
  . VM    : 0xffffff9a7e791000 - 0xffffff9f4af90000
  . RO    : 0xffffff9f4af90000 - 0xffffffa0e4790000
  . GEN0  : 0xffffffa0e4790000 - 0xffffffa5b0f90000
  . GEN1  : 0xffffffa5b0f90000 - 0xffffffaa7d790000
  . GEN2  : 0xffffffaa7d790000 - 0xffffffaf49f90000
  . GEN3  : 0xffffffaf49f90000 - 0xffffffb416790000
  . DATA  : 0xffffffb416790000 - 0xffffffba7c790000
  Metadata: 0xffffff8a56540000 - 0xffffff8a76540000
  Bitmaps : 0xffffff8a76540000 - 0xffffff8a7c540000

Kernel panic after system rebooting, could you please help me to solve that, or any information I can provide to sovle this problem?

**Comment by henrycoding** [comment]
Kernel panic after system rebooting, could you please help me to solve that, or any information I can provide to sovle this problem?

**Comment by vit9696** [comment]
Sounds like an incompatible NVMe disk.
