### ISSUE TITLE
MacOS 13.3 RC (22E252) breaks unlocking with the AppleWatch by using wifi card BCM94360NG and wifi card BCM94360CS2

### ISSUE THREAD

**Issue by anonymous-writer** [acidanthera/bugtracker#2255]
I would like to report a new problem that occurs with the latest version 13.3 RC (22E252) of Ventura.

The new macOS 13.3 RC (22E252) breaks unlocking  for me with the AppleWatch. Back to macOS 13.2.1 (22D68) fixes the issue. Only on my Lenovo laptop with the BCM94360NG. With the FENVI FW-T919 I don't have the problem and unlocking still works.

The crash may also affect non-AppleWatch users after sleep if they observe this in the console.
This is not a BlueToolFixup.kext problem, but it may can fix the problem.
If more information is needed I am open to post this.

Crash Report: Termination Reason:    Namespace LIBSYSTEM, Code 2 Application Triggered Fault

[bluetoothd Crash Report.txt](https://github.com/acidanthera/bugtracker/files/11075221/bluetoothd.Crash.Report.txt)

**Comment by anonymous-writer** [comment]
Update to macOS 13.4 beta (22F5027f):

Without BlueToolFixup.kext same bluetooth crash as in post 1.

With BlueToolFixup.kext no crash. But unlocking with the AppleWatch still not working.
Message on login screen: Bluetooth must be turned on to unlock with the Apple Watch.
Go back to the black screen 20 seconds and then the AppleWatch unlocks as usual under 13.2.1.

I'll keep up to date this troubleshooting report and continue to try to solve the problem.

**Comment by anonymous-writer** [comment]
13.3.1 (22E261) unfortunately did not fix the panic.
Different hardware, but I think the same problem.
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/433

![Fehlermeldung](https://user-images.githubusercontent.com/35840715/230729307-8d7757b3-0678-4a9c-beb0-2377a52d1d0f.png)

**Comment by anonymous-writer** [comment]
Would like to add more experiences.

In the meantime I changed the BCM94360NG to BCM94360CS2 by using an NGFF adapter. Card runs perfect and I also have now TX rate up  867 MBits/s.
However, the unlocking problem still exist after MacOS 13.3 RC. Previously versions of OSX  have no problems also with this card.

Interesting is the fact that deactivating the webcam via the USB port solves the problem. Unlocking with AppleWatch is then back to 100%. As soon as I activate it again, an unlock is no longer possible.
It is also interesting that without the Webcam and without BlueToolFixup.kext there are no more bluetoothd crashes.

I'm thinking this is USB power problem. But I don't have any other ideas at the moment. Maybe someone has an idea what to test.

**Comment by topiga** [comment]
Have you mapped your usb ports and controllers ?

**Comment by anonymous-writer** [comment]
Mapping and Power for usb ports is made according to the current state of knowledge, Works up to 13.2.1 without problems.
[SSDT-USB-S145-15IIL.zip](https://github.com/acidanthera/bugtracker/files/11257789/SSDT-USB-S145-15IIL.zip)
[SSDT-EC-USBX-LAPTOP.zip](https://github.com/acidanthera/bugtracker/files/11257790/SSDT-EC-USBX-LAPTOP.zip)

I know from other Hackintosh user that they have exactly the same problems. The AppleWatch shows problems directly because of that unlocking occurs very early.

**Comment by topiga** [comment]
Please reset the nvram twice. After that, try. If it’s not working, please boot in safe mode an tell me if it’s still there

**Comment by CobanRamo** [comment]
I have the same problem here, since 13.3 it doesn't work anymore, at least not reliably anymore.
It is not not hardware dependent, it no longer works on an MSI desktop (CometLake), Lenovo (Icelake), Dell (KabyLakeR).
The new build from 13.3 has significant problems with Wifi & Bluetooth.

![Bildschirmfoto 2023-04-18 um 12 26 48](https://user-images.githubusercontent.com/68192365/232782402-f8fb14be-b1b0-44e9-af98-51474956ea9e.png)

**Comment by topiga** [comment]
Two questions :
- Is « DisableIOMapper » true or false ?
- Have you patched your DMAR table ?
- Is AppleVTD in your ioreg ?
- Do you have more than 16GB of RAM ?

**Comment by CobanRamo** [comment]
We have already tested this in all variations.
With VT-d, DMAR Table disabled and patched, with AppleVTD.
Without VT-d, original DMAR Table, without AppleVTD.
I myself have different computers here, MSI, Lenovo, Dell, with different RAM sizes, etc.

All computers up to 13.2.1 have no problem with it, works without any problems.
From 13.3 the problems start.

Believe me, we've been testing it for 2 weeks.
Do you have an iWatch? if so, you can test it right away.

**Comment by anonymous-writer** [comment]
I've made some progress with unlocking AppleWatch.
If I correct the address for PCI in DMAR as in the attached file, unlock works 75%.
If unlock does not work, there is now a different error message. Also attached.
So the problem is partially solved but not 100%.

[bluetoothd_Crash.txt](https://github.com/acidanthera/bugtracker/files/11303116/bluetoothd_Crash.txt)

[DMAR.dsl.zip](https://github.com/acidanthera/bugtracker/files/11303118/DMAR.dsl.zip)

https://bitbucket.org/anonymous_writer/lenovo-ideapad-s145-15iil-opencore/src/master/

**Comment by anonymous-writer** [comment]
Unfortunately I could not solve the problem until now.
Also macOS 13.4 RC doesn't change anything. As soon as I activate the webcam via the USB port, unlocking via the watch only works randomly. The last version where unlocking still worked was version 13.2.1.
Always the same problem. bluetoothd crashes with the error message from post 1.

I also have Monterey running on the laptop. Unlocking works 100% there even with an activated webcam, The Opencore EFI folder used is exactly the same as on Ventura.

I've tried a lot to solve the problem. Now I'm running out of ideas what else to test. Maybe someone has a new idea.

**Comment by umka-petrovich** [comment]
Hey, guys! I think you should check Ventura 13.4

<img width="568" alt="image" src="https://github.com/acidanthera/bugtracker/assets/38903713/092b31d5-969f-4a04-b060-a2cb7351bfc5">

**Comment by anonymous-writer** [comment]
Unfortunately doesn't change anything.
With webcam activated via USB, unlocking only works according to the random principle.

Back to 13.2.1 Unlock work.

<img width="609" alt="Bildschirmfoto 2023-05-18 um 22 05 25" src="https://github.com/acidanthera/bugtracker/assets/35840715/b18d4b59-aef1-439f-af98-d19f619e160d">

**Comment by umka-petrovich** [comment]
> Unfortunately doesn't change anything. With webcam activated via USB, unlocking only works according to the random principle.
> 
> Back to 13.2.1 Unlock work.

Hm, gotcha, thanks. Did you check that quirk? Maybe that one will help? (you need to patch DMAR with removing reserved  memory regions)
<img width="829" alt="image" src="https://github.com/acidanthera/bugtracker/assets/38903713/c3773015-7e38-479f-99a6-5ae54a9614ae">

**Comment by anonymous-writer** [comment]
This qurik has already been tested. No change.
A separate DMAR with a different address range works best. This works for me to unlock sometimes. Removing the address range completely doesn't help at all.

![Bildschirmfoto 2023-05-19 um 09 35 22](https://github.com/acidanthera/bugtracker/assets/35840715/b8deb7e8-101c-420b-bb6a-db6865ef7635)

Thanks for the information.

**Comment by Lorys89** [comment]
Have you solved it?
