### ISSUE TITLE
macOS 13.3 ExternalDiskIcons and ThirdPartyDrives Quirks are broken 

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#2256]
The messages are from **Sit** from Applelife.
https://www.applelife.ru/posts/1032768
https://www.applelife.ru/posts/1032770
CC @vit9696 @lvs1974

**Comment by vit9696** [comment]
Sit said that he has Clover, so I am not sure what I am to fix here.

- External icons patch should work without changes, I do not see any reason why it should have gotten broken. I requested to explicitly try exactly the same patch with different `Count`s, but the user reported it works with `Count` = 1, i.e. the same way quirk does it. To be honest, I need a log at least, and so far I do not see a reason why it should fail.
- Trim will indeed be broken with SATA, as the comparison logic is now different, but apparently all users in the topic rely on Clover, and I am not ready to fix both OC and Clover issues. We can work on this together later.

**Comment by vit9696** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Arch</key>
	<string>Any</string>
	<key>Base</key>
	<string></string>
	<key>Comment</key>
	<string>TRIM 1</string>
	<key>Count</key>
	<integer>1</integer>
	<key>Enabled</key>
	<true/>
	<key>Find</key>
	<data>SI09AAAAALoJAAAA</data>
	<key>Identifier</key>
	<string>com.apple.iokit.IOAHCIBlockStorage</string>
	<key>Limit</key>
	<integer>0</integer>
	<key>Mask</key>
	<data>////AAAAAP//////</data>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>Replace</key>
	<data>AAAAAAAAALoAAAAA</data>
	<key>ReplaceMask</key>
	<data>AAAAAAAAAP//////</data>
	<key>Skip</key>
	<integer>0</integer>
</dict>
</plist>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Arch</key>
	<string>Any</string>
	<key>Base</key>
	<string></string>
	<key>Comment</key>
	<string>TRIM 2</string>
	<key>Count</key>
	<integer>1</integer>
	<key>Enabled</key>
	<true/>
	<key>Find</key>
	<data>SI09AAAAALoFAAAA</data>
	<key>Identifier</key>
	<string>com.apple.iokit.IOAHCIBlockStorage</string>
	<key>Limit</key>
	<integer>0</integer>
	<key>Mask</key>
	<data>////AAAAAP//////</data>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>Replace</key>
	<data>AAAAAAAAALoAAAAA</data>
	<key>ReplaceMask</key>
	<data>AAAAAAAAAP//////</data>
	<key>Skip</key>
	<integer>0</integer>
</dict>
</plist>
```

@PMheart, I actually found a SATA SSD and tested this on 13.3.0. We need a new set of patches on 22.4.0 and newer for `ThirdPartyDrives`. Could you please update the quirk logic?

**Comment by PMheart** [comment]
https://github.com/acidanthera/OpenCorePkg/pull/438

**Comment by Lorys89** [comment]
![Screenshot 2023-03-29 alle 12 32 09](https://user-images.githubusercontent.com/64613690/228507430-59f8972e-03cf-49a5-90e3-fb26d3da91c5.png)
i use this method and work to os 13.4 beta
![Screenshot 2023-03-29 alle 12 34 39](https://user-images.githubusercontent.com/64613690/228507714-ff9497b3-fb5a-4190-b097-71d4ce60fc70.png)

**Comment by AlexKusnezov** [comment]
@vit9696 sorry for bothering but **ExternalDiskIcons** is still broken for me after updating to 13.3.1

13.2.1:
<img width="1276" alt="Screenshot 2023-04-14 at 18 28 27" src="https://user-images.githubusercontent.com/33514406/232102363-04e0cca2-91e3-46d3-82d1-dcc75306b3a9.png">

13.3.1:
<img width="1383" alt="Screenshot 2023-04-14 at 18 29 13" src="https://user-images.githubusercontent.com/33514406/232102587-b3f76767-b08a-45fe-b875-4147c09bfbda.png">

What am I missing?

**Comment by Andrey1970AppleLife** [comment]
ExternalDiskIcons patch works with Count=2
https://www.insanelymac.com/forum/topic/350754-opencore-general-discussion/?do=findComment&comment=2803365
CC @vit9696

**Comment by vit9696** [comment]
@PMheart, could you update the patch to set Count=2 for macOS >= 13.3?
