### ISSUE TITLE
GopBurstMode commit breaks Windows graphics

### ISSUE THREAD

**Issue by mikebeaton** [acidanthera/bugtracker#2257]
@crwnet commented on https://github.com/acidanthera/OpenCorePkg/pull/437 :

This commit broke the functionality of my graphics card even though GopBurstMode was not enabled. The performance is that when you enter windows to play games, it will crash in a few seconds to a few minutes, and it will not recover with restarting, shutting down or directly using windows boot manager. After revert this commit and resetting NVRAM, it restore. My graphics card is nvidia 4090.

**Comment by mikebeaton** [comment]
@crwnet - Please could you also use the following builds to confirm exactly which commit is breaking it:

The artefact files at the bottom of this screen are from the GopBurstMode commit, with nothing that comes after it: https://github.com/acidanthera/OpenCorePkg/actions/runs/4539920542

The artefact files are the bottom of this screen are from the commit immediately before GopBurstMode: https://github.com/acidanthera/OpenCorePkg/actions/runs/4537228583

Please could you also carefully take the time to confirm that the GopBurstMode commit, with nothing after, does show the problem, and that the commit immediately before does not show it?

**Comment by crwnet** [comment]
my last build at bd7f1c0545ec0daaf4b21176b24286391726f74e, It works fine past ten days, I'll stop at the old version and watch for a few more days to see if it still happens.

**Comment by mikebeaton** [comment]
I agree it is very unlikely that https://github.com/acidanthera/OpenCorePkg/commit/852016cd85ea2c50f68fa3f79ddabe473f1fb2ea is different from https://github.com/acidanthera/OpenCorePkg/commit/abe28e829f4ecf942d04d927ce5fc10a759e86a5. So the next one to try is https://github.com/acidanthera/OpenCorePkg/commit/2002cbfe0551970f6a09932741998d5dba67b380, just in case the issue is already happening there. Plus logs and config.plist, please.

**Comment by crwnet** [comment]
I tested the latest 0.9.1 release, I think the bug has been fixed. Thanks for your response.
