### ISSUE TITLE
SMCProcessor is loaded but doesnt work

### ISSUE THREAD

**Issue by AHREAL** [acidanthera/bugtracker#2264]
Specs ：i5-13400 / MSI PRO-B660M-G
Mac：12.6.2
OpenCore，Lilu，VirtualSMC，SMCProcessor Updated to the latest version
The kernel's order: Lilu first, then VirtualSMC and then SMCProcessor.
app cannot read the cpu temperature.

**Comment by perez987** [comment]
@AHREAL 
As a first approach
[OpenCore debug](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html)
