### ISSUE TITLE
Notarization: Migrate to `notarytool`

### ISSUE THREAD

**Issue by khronokernel** [acidanthera/bugtracker#2265]
Apple has deprecated and will soon no longer support `altool` to notarize applications in late 2023:
* [TN3147: Migrating to the latest notarization tool](https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool)

Need to update ocbuild's `appsign.sh` to use the new `notarytool` system:
* https://github.com/acidanthera/ocbuild/blob/43d0f2501bc1b0812e23393d8d5345dc6a8fb13d/codesign/appsign.sh#L75-L82

**Comment by vit9696** [comment]
@khronokernel will you handle this?

**Comment by khronokernel** [comment]
Can handle this, recently converted OpenCore Legacy Patcher over to notarytool

**Comment by khronokernel** [comment]
Resolved by DhinakG:
* https://github.com/acidanthera/ocbuild/pull/23
