### ISSUE TITLE
Kext Blocker not blocking kext in DMG-based Recovery HD boot

### ISSUE THREAD

**Issue by MacNB** [acidanthera/bugtracker#2266]
**H/W:** MacPro4,1->5,1
**OS:** High Sierra+
**Problem:** Faulty FireWire H/W prevents macOS to boot.
**Solution:** Block the FireWire kexts from loading using Kernel->Block->com.apple.iokit.IOFireWireFamily.
**Issue:** OpenCore successfully blocks this kext when booting normal OS and the OS boots fine **but** does not block if booting the Recovery HD.
In both boot cases, OpenCore log shows that the prelinked kernel is patched to block this kext:

`93:106 00:159 OC: Prelinked blocker (Disable) result 0 for com.apple.iokit.IOFireWireFamily (Disable Faulty FireWire Controller on My-MacPro-2) - Success
`

However, when booting any Recovery HD that are based on DMG, the OS hangs just like when the kext is not blocked.
When booting Recovery HD that are non-DMG based, e.g. Mountain Lion or El Capitan then Kext blocking work as expected and the recovery partitions boot fine for those OS's.

Attached screenshot during Verbose boot of High Sierra recovery HD boot which shows:
`Notice - new kext com.apple.driver.KextExcluded.List, v13.2.1 matches relinked kext but can't determine if executables are the same...`

After this, there's a four minute hang followed by:
`kexts stall[0], (240s): 'IOFireWireLocalNode'`

This repeats every four minutes just like when the IOFireWireFamily.kext is NOT blocked and the OS never boots after 35 minutes.
 
![IMG_4961](https://user-images.githubusercontent.com/3777537/232101145-7094c4ce-918d-42bc-a1e3-1fdf2c96ab10.jpg)
![IMG_4963](https://user-images.githubusercontent.com/3777537/232101213-a44c6e2f-8712-4860-b079-1becd127890e.jpg)

Attached OpenCore log files: 

[1-Normal boot-opencore-2023-04-14-154804.txt](https://github.com/acidanthera/bugtracker/files/11235000/1-Normal.boot-opencore-2023-04-14-154804.txt)

[2-Recovery boot-opencore-2023-04-14-153538.txt](https://github.com/acidanthera/bugtracker/files/11235002/2-Recovery.boot-opencore-2023-04-14-153538.txt)

This issue is the same with macOS Installers too. That is, unable to install macOS due to hang.

**Comment by vit9696** [comment]
As far as I know FireWire drivers are not present in latest macOS versions. For them the kext blocker mechanism was rewritten and should work in general for kernel extensions kernel collection.

For older macOS versions there indeed is a number of limitations for kext blocker mechanism. I would suggest manually applying the following patch:

```
Identifier: com.apple.iokit.IOFireWireFamily
Base:  __ZN20IOFireWireController5startEP9IOService
Replace: 31C0C3
```

**Comment by MacNB** [comment]
> As far as I know FireWire drivers are not present in latest macOS versions. For them the kext blocker mechanism was rewritten and should work in general for kernel extensions kernel collection.
> 
> For older macOS versions there indeed is a number of limitations for kext blocker mechanism. I would suggest manually applying the following patch:
> 
> ```
> Identifier: com.apple.iokit.IOFireWireFamily
> Base:  __ZN20IOFireWireController5startEP9IOService
> Replace: 31C0C3
> ```

Thanks for looking into this issue.
Big Sur and Monterey have working FIreWire drivers for MacPro5,1. 
The FireWire ports work fine on my second MacPro5,1.

I tried your patch:

![FW-patch](https://user-images.githubusercontent.com/3777537/236678525-ae917760-4288-4980-94ca-935f528e529d.png)
The patch has not effect on Big Sur or Monterey (i.e. does not disable the FireWire service).
The patch works for Mountain Lion all the way up to Yosemite for both normal OS boot as well as Recovery boot (and so assume it will work for their respective Installer boots too).

For Mojave, the regular OS boots fine. But Recovery boot panics:

![IMG_4977](https://user-images.githubusercontent.com/3777537/236678185-27f7ef8a-0733-4a09-9ff4-cf0f008eb38e.jpg)

**Comment by vit9696** [comment]
> Big Sur and Monterey have working FIreWire drivers for MacPro5,1.

Are they injected by some software? Original macOS version has no FireWire support since like 10.14.

**Comment by MacNB** [comment]
> > Big Sur and Monterey have working FIreWire drivers for MacPro5,1.
> 
> Are they injected by some software? Original macOS version has no FireWire support since like 10.14.

Interesting.
No they are not injected (certainly not by me). There's nothing in my OpenCore Kext folder.
Monterey was a clean install.

IOREG looks like this:
<img width="1204" alt="MP-01-ioreg" src="https://user-images.githubusercontent.com/3777537/236680508-21e76326-2355-499c-846a-410ef6d1b59b.png">

**Comment by vit9696** [comment]
Interesting. Perhaps this one is a new driver. Please use `__ZN11AppleFWOHCI5startEP9IOService` and `com.apple.driver.AppleFWOHCI`.

**Comment by MacNB** [comment]
Thanks @vit9696. The last patch does not work for macOS Catalina and later releases.
OpenCore log shows:

`
19:615 00:009 OCAK: Failed to pk find com.apple.iokit.IOFireWireFamily - Not Found
19:619 00:004 OC: Prelinked patcher result 0 for com.apple.iokit.IOFireWireFamily (Disable Faulty FireWire Controller on My-MacPro-2 services from starting) - Not Found
19:629 00:010 OCAK: Failed to pk find com.apple.driver.AppleFWOHCI - Not Found
19:634 00:004 OC: Prelinked patcher result 1 for com.apple.driver.AppleFWOHCI (Disable Faulty FireWire Controller on My-MacPro-2 services from starting) - Not Found`

The second patch **_does_** work for OS X up to and including Mojave. 
I enabled both patches (first one for Catalina+ and the second for older OS X up to Mojave).

For some reason OpenCore cannot find either the bases `__ZN20IOFireWireController5startEP9IOService` and `__ZN11AppleFWOHCI5startEP9IOService` or the the actual kexts in the prelinked kernel ?

As you said something changed with the newer OS's.

**Comment by vit9696** [comment]
Most likely in newer versions the kext is in aux kc, which you thus cannot patch in OC.

**Comment by MacNB** [comment]
Thx. I cooked but a different solution using OpenCore's Device-Properties section to fool the OS that there's no compatible Firewire device on the ACPI path by changing the `class-code` and `compatible settings` to dummy values:

![Screenshot 2023-05-09 at 12 05 27](https://github.com/acidanthera/bugtracker/assets/3777537/56b4213d-fc01-4ee0-8048-fc2708e8a54d)
That now prevents the any firewire kexts from loading:

![Screenshot 2023-05-09 at 12 12 38](https://github.com/acidanthera/bugtracker/assets/3777537/2e7c10c4-7888-4b5f-b853-4007edf64209)
Just spoofing the `device-id` was not enough.
Thanks for your help.
