### ISSUE TITLE
Feature request: Setting to change video output port in boot picker

### ISSUE THREAD

**Issue by tzylstra** [acidanthera/bugtracker#2269]
H/W: all
OS: all
Problem: Current boot picker is always displayed on the lowest connected video port of the GPU. In some setups this video port is suboptimal for the boot picker.
Solution: Add a setting for which video port is used for boot picker.

**Comment by vit9696** [comment]
Is BIOS boot screen also available on other video output ports? If not, we can hardly do anything here, it would be GOP software limitation.

If yes, please provide GopStop tool logs from OC package and reopen the issue.
