### ISSUE TITLE
Qemu + SysReport: hang at dumping cpuinfo

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#2270]
Opencore: DBG-092-2023-04-25
Qemu: 7.2.1

Issue description:
When setting SysReport=true opencore hangs in a loop with boot chime playing endlessly.
Looking at the opencore log it seems it hangs at dumping cpuinfo.

It could be related to how the cpu is managed by qemu (?).

The vm is set with cpu host passthrough.
PlatformInfo is set to Automatic.

Log attached:
[opencore-2023-04-29-091946.txt](https://github.com/acidanthera/bugtracker/files/11358792/opencore-2023-04-29-091946.txt)

**Comment by mikebeaton** [comment]
No such problem with OVMF + QEMU 7.2.0 + current OC (but no cpu passthrough).

Could you provide more info:

 - Does OpenCore run for you with SysReport=false?
 - Have you tried OpenCore without QEMU CPU passthrough? (Result, if so.)
 - Please provide some info on the CPU in question (make, model, #/type of cores).
 - Did you get a partial SysReport folder? (Please provide it, if so.)
 - Which OS are you running QEMU on (should not matter, but to be clear)?
 - Please provide full qemu command line.

Thx.

**Comment by 82ghost82** [comment]
Hi Mike,
Does OpenCore run for you with SysReport=false?
Yes

Have you tried OpenCore without QEMU CPU passthrough? (Result, if so.)
Yes, emulated with Penryn cpu, same result, bootloop when trying to dump cpuinfo.
Attached opencore log
[opencore-2023-05-01-081352.txt](https://github.com/acidanthera/bugtracker/files/11364353/opencore-2023-05-01-081352.txt)

Please provide some info on the CPU in question (make, model, #/type of cores).
They are 2x intel xeon e5-2687w (v0), each 8 cores/16threads --> https://ark.intel.com/content/www/it/it/ark/products/64582/intel-xeon-processor-e52687w-20m-cache-3-10-ghz-8-00-gts-intel-qpi.html

Did you get a partial SysReport folder? (Please provide it, if so.)
Yes, with the CPU folder empty.
Attached a partial SysReport
[SysReport.zip](https://github.com/acidanthera/bugtracker/files/11364361/SysReport.zip)

Which OS are you running QEMU on (should not matter, but to be clear)?
Linux Manjaro, kernel 5.15.109-1

Please provide full qemu command line.
I'm not using qe
[monterey-xml.txt](https://github.com/acidanthera/bugtracker/files/11364379/monterey-xml.txt)
mu command line but libvirt, attached the xml

Machine version is 8.0, in the meantime I upgraded to qemu 8.0.0

**Comment by mikebeaton** [comment]
@82ghost82 - Thanks for the additional info. I don't have a bead on what the hang may be, so it might end up requiring someone here to replicate the setup before any fix can be developed.

**Comment by 82ghost82** [comment]
No problem @mikebeaton
This is something I (we) can live with for sure.

**Comment by vit9696** [comment]
@82ghost82, could you please:

- Provide QEMU command-line. If you are using libvirt, virsh, or vmm, you can likely find the QEMU command line arguments in `/var/log/libvirt/qemu/$GUEST.log`.
- Attach your EFI directory you use with QEMU.

**Comment by 82ghost82** [comment]
Hello Vitaly, thank you for your reply.
I didn't attach the qemu command line because I know I have the log, but I'm not able/wasn't able to translate to a working qemu command line.
Anyway, here is the qemu log:
[qemu-log.txt](https://github.com/acidanthera/bugtracker/files/11414727/qemu-log.txt)

Passed devices:
06:00.0/06:00.1 --> gpu
00:1b.0 --> hdef audio
0c:00.0 --> sata controller
84:00.0 --> usb controller

/dev/bus/usb/008/003 --> webcam
/dev/bus/usb/008/004 --> usb wifi

Here is my EFI folder, sensitive data changed:
[EFI.zip](https://github.com/acidanthera/bugtracker/files/11414733/EFI.zip)

**Comment by vit9696** [comment]
The OVMF you use may matter too. Please attach:

- /opt/macos/OVMF_CODE.fd
- /opt/macos/OVMF_VARS.fd

**Comment by vit9696** [comment]
Also, if you reduce the amount of CPUs to something like 8, does it still reproduce? I.e. `-smp 1,maxcpus=8,sockets=2,dies=1,cores=2,threads=2`?

**Comment by 82ghost82** [comment]
Same behaviour with 1 socket, 4 cores, 2 threads.
Here are OVMF files, they were compiled some time ago by me from your audk repository when it was updated to stable 202211:
[OVMF.zip](https://github.com/acidanthera/bugtracker/files/11415227/OVMF.zip)

I noticed that in the opencore log there are a lot of spaces under the last line "OC: Dumping CPUInfo for report...".

Any idea why the bootchime is like hanging in a loop?
Trying now to not load audiodxe and see if I can get out of the loop.

**Comment by vit9696** [comment]
Actually I think I was able to reproduce this. Thanks!

```
01:267 00:065 OC: Dumping CPUInfo for report...
!!!! X64 Exception Type - 0D(#GP - General Protection)  CPU Apic ID - 00000000 !!!!
ExceptionData - 0000000000000000
RIP  - 000000007E0292D2, CS  - 0000000000000038, RFLAGS - 0000000000010202
RAX  - AAAAAAAAAAAAAA01, RCX - 00000000000001AD, RDX - 000000007FE12540
RBX  - 000000007DFF5701, RSP - 000000007FE12520, RBP - 000000007FE12560
RSI  - 00000000000001AD, RDI - 000000007FE127B0
R8   - 0000000000000004, R9  - 000000007DFF5718, R10 - 0000000000000000
R11  - 00000000000001E9, R12 - 000000007FE126C8, R13 - 000000007DFF5220
R14  - 8000000000000003, R15 - 000000007FE126D0
DS   - 0000000000000030, ES  - 0000000000000030, FS  - 0000000000000030
GS   - 0000000000000030, SS  - 0000000000000030
CR0  - 0000000080010033, CR2 - 0000000000000000, CR3 - 000000007FA01000
CR4  - 0000000000040668, CR8 - 0000000000000000
DR0  - 0000000000000000, DR1 - 0000000000000000, DR2 - 0000000000000000
DR3  - 0000000000000000, DR6 - 00000000FFFF0FF0, DR7 - 0000000000000400
GDTR - 000000007F7EB000 0000000000000047, LDTR - 0000000000000000
IDTR - 000000007F28B018 0000000000000FFF,   TR - 0000000000000000
FXSAVE_STATE - 000000007FE12180
!!!! Find image based on IP(0x7E0292D2) /Users/daniele/downloads/opencorepkg-master/UDK/Build/OpenCorePkg/DEBUG_XCODE5/X64/OpenCorePkg/Application/OpenCore/OpenCore/DEBUG/OpenCore.dll (ImageBase=000000007E00D000) !!!!
2023-05-07T14:34:32.220778Z qemu-system-x86_64: terminating on signal 2
```

**Comment by mikebeaton** [comment]
> Any idea why the bootchime is like hanging in a loop?

Boot chime looping is the HDA audio processor running, but other stuff crashed - to put it at its most straight forward, perhaps surprisingly(!) it just continues to loop samples by default, if not given further instructions.

**Comment by vit9696** [comment]
The crash happens because OpenCore tries to read `MSR_NEHALEM_TURBO_RATIO_LIMIT` as reported CPU generation is `CpuInfo->CpuGeneration >= OcCpuGenerationNehalem`. I resolved the issue in master.
