### ISSUE TITLE
NVMeFix: NVMe temperature increases while Macs Fan Control is monitoring it

### ISSUE THREAD

**Issue by xCuri0** [acidanthera/bugtracker#2272]
My NVMe drive is an Addlink S70 512GB (Phison E12 controller). I've found out that the cause of elevated NVMe temperatures is Macs Fan Control window being opened which polls the temperature at possibly a high frequency. **The temperature immediately starts dropping after closing Macs Fan Control.**

### Disabling read temperatures of Connected NVMe drives fixes this issue
![image](https://user-images.githubusercontent.com/29529557/235836161-df670b02-93b3-4187-82c5-811577041164.png)

This screen capture should explain it better, you can see that it doesn't correspond with I/O activity.

https://user-images.githubusercontent.com/29529557/235835894-d67deda0-c3e8-4159-92f7-f3a73d001d16.mp4

This is probably a bug with the NVMe firmware caused by polling temperature too much ? This probably could be solved by implementing a rate limit for NVMe temperature polling (if this is in the scope of NVMeFix).

Would adding kernel logs of NVMeFix debug be helpful for solving this ?

**Comment by vit9696** [comment]
I do not really think it is a bug of the NVMe firmware, but rather a bug with Macs Fan Control querying the information too frequently. In my opinion, ping the dev of the tool.
