### ISSUE TITLE
Some errors about Kernal Panic

### ISSUE THREAD

**Issue by xhl99** [acidanthera/bugtracker#2274]
When I disable AppleMCEReporterDisabler.kext, the system will restart unexpectly with kernal panic about AppleIntelMCEReporter. I have known adding AppleMCEReporterDisabler.kext will solve it because I see some issue about it, but I think have better solutions now.
And when I add NVEMfix.kext the system will restart with kernal panic about NVEMfix.kext.
The follow is my opencore kexts and the error log. 
<img width="1034" alt="截屏2023-05-06 15 07 59" src="https://user-images.githubusercontent.com/57740212/236608951-00b82e28-4f31-4c3f-98c7-7c85c75bd6ec.png">

<img width="1548" alt="截屏2023-05-06 15 21 33" src="https://user-images.githubusercontent.com/57740212/236609565-a45bb4c0-f43c-447f-ae1c-8319ce2e1565.png">

<img width="962" alt="截屏2023-05-06 15 22 21" src="https://user-images.githubusercontent.com/57740212/236609598-00810367-32cd-40cd-9f3c-4fa8ba1d7cc9.png">

**Comment by vit9696** [comment]
NVMeFix is known to have issues with modern macOS versions. Feel free to provide patches for it.
