### ISSUE TITLE
[ACPI-Quirks] SyncTableIds not effective when dropping an old SLIC table and add an custom SLIC table

### ISSUE THREAD

**Issue by xXiaoXiang** [acidanthera/bugtracker#2275]
I am currently using OpenCore 0.9.1 RELEASE for multiple boot (Windows Server + MacOS). 

When I dropped an old SLIC v2.5 table from the ACPI tables, and manually inserted a new SLIC v2.6 table, the process will ignored the SyncTableIds as OpenCore first dropped the tables, process ACPI quirks and add tables. Currently, this order will leave XSDT/FACP tables unchanged. This will also affect users who do not have a native SLIC table but wish to add one by themselves.

Relevant code section is here: 
[https://github.com/acidanthera/OpenCorePkg/blob/c4c8e3412a5d9b10dc8ee2739478b85061de71d6/Library/OcMainLib/OpenCoreAcpi.c#L255](url)

Simply moving the `if (Config->Acpi.Quirks.SyncTableIds) {
    AcpiSyncTableIds (&Context);
  }` after `OcAcpiAddTables (Config, Storage, &Context);` will fix the problem. As `OcAcpiAddTables` function only process OEM ID and OEM Table ID in FADT/FACP and RSDT/XSDT, this re-arrangement of order should not do harm to other functionality of ACPI processes.

**Comment by vit9696** [comment]
This is a regression introduced by https://github.com/acidanthera/OpenCorePkg/commit/f604848c61d7082860fceb23ac54d5e03e620478.

`RelocateRegions` and `SyncTableIds` are indeed broken now. @PMheart, why was that change made?

**Comment by PMheart** [comment]
Reasons were stated in the commit log, but I don’t know the correct order to handle ACPI quirks. Could you please give me a list? Thanks!

**Comment by xXiaoXiang** [comment]
Overall the patch order change sounds reasonable but I think for quirks it should be analyzed by a case-by-case basis, as different quirks are dealing with different things. The `SyncTableIds` is a such example. For `SyncTableIds`, it should be processed after `OcAcpiAddTables` inserting tables. 

For other ACPI quirks, I can't say so much as I did not do any research on them.

**Comment by PMheart** [comment]
OK, I changed the orders proposed by @vit9696. Could you please test the PR version? If it works, then I will merge and rebuild the docs. Thanks!

**Comment by xXiaoXiang** [comment]
Sorry for the double click. Where can I get the PR build？Do I have to compile myself?

**Comment by xXiaoXiang** [comment]
OK. I found it and will do a test for the problem.

**Comment by xXiaoXiang** [comment]
> OK, I changed the orders proposed by @vit9696. Could you please test the PR version? If it works, then I will merge and rebuild the docs. Thanks!

I have tested that after the commit [https://github.com/acidanthera/OpenCorePkg/pull/454](url), the problem has been solved. The XSDT OEM Table ID is synced with added SLIC table.
