### ISSUE TITLE
SMCProcessor not working for Broadwell-EP (e5 2690v4) on ventura

### ISSUE THREAD

**Issue by Oculto54** [acidanthera/bugtracker#2280]
Hi, great work with OC.

I follow the guides and it almost fine (lack some instructions for X99) but I cant make the SMCProcessor load. I suspect it didnt have the right code for this CPU on X99 boards
![Screenshot 2023-05-10 at 16 12 23](https://github.com/acidanthera/bugtracker/assets/133160205/52448ab4-a85e-48b0-b30f-e7436ce1f16a)

![Screenshot 2023-05-10 at 16 11 12](https://github.com/acidanthera/bugtracker/assets/133160205/a745491f-4201-4b42-8a1f-54dd0a7181a6)

Could you please verify? the config.plist is correct, all other SMC plugins (like radeon, etc) loads ok, but the processor isn't....

**Comment by al3xtjames** [comment]
I noticed that the CPUID model was missing in Lilu. Could you try [the artifacts from this PR](https://github.com/acidanthera/Lilu/actions/runs/5316895468)?
