### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by wmbin** [acidanthera/bugtracker#2282]
panic(cpu 6 caller 0xffffff80063b4ad3): Kernel trap at 0xffffff8006251a27, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xfffffb86e4a37b30, CR3: 0x000000103e83003e, CR4: 0x00000000003626e0
RAX: 0x0000000000010000, RBX: 0xfffffb86e4a37b30, RCX: 0xfffffff830e2dda8, RDX: 0x000000000015e707
RSP: 0xfffffff830ac7e30, RBP: 0xfffffff830ac7e30, RSI: 0xfffffb86e4a37b30, RDI: 0xfffffb86e4a37b30
R8:  0x0000000000000000, R9:  0x0000060c979dac76, R10: 0x0000000000000022, R11: 0xffffffa076def400
R12: 0xffffff907b007f20, R13: 0x0000000000000000, R14: 0xfffffff830e2dda8, R15: 0x000000000015e707
RFL: 0x0000000000010246, RIP: 0xffffff8006251a27, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xfffffb86e4a37b30, Error code: 0x0000000000000000, Fault CPU: 0x6, PL: 1, VF: 5

Panicked task 0xffffff9a111878b8: 14 threads: pid 169: WindowServer
Backtrace (CPU 6), panicked thread: 0xffffff9079ac50c8, Frame : Return Address
0xfffffff830ac76f0 : 0xffffff80062705fd 
0xfffffff830ac7740 : 0xffffff80063c4b84 
0xfffffff830ac7780 : 0xffffff80063b4619 
0xfffffff830ac77e0 : 0xffffff800a1da5af 
0xfffffff830ac7860 : 0xffffff8006210951 
0xfffffff830ac7880 : 0xffffff80062708dd 
0xfffffff830ac7970 : 0xffffff800626ff87 
0xfffffff830ac79d0 : 0xffffff80069dd09b 
0xfffffff830ac7ac0 : 0xffffff80063b4ad3 
0xfffffff830ac7c40 : 0xffffff80063b47c4 
0xfffffff830ac7ca0 : 0xffffff800a1da5af 
0xfffffff830ac7d20 : 0xffffff8006210951 
0xfffffff830ac7d40 : 0xffffff8006251a27 
0xfffffff830ac7e30 : 0xffffff8006257fd5 
0xfffffff830ac7e70 : 0xffffff8006258959 
0xfffffff830ac7ef0 : 0xffffff800639a013 
0xfffffff830ac7fa0 : 0xffffff8006210db6 
      Kernel Extensions in backtrace:
         as.vit9696.VirtualSMC(1.3.1)[49AC0DDF-9CCD-3C71-ABF7-9AFE7E5E1DEE]@0xffffff800a1cb000->0xffffff800a1f1fff
            dependency: as.vit9696.Lilu(1.6.5)[C2F3A95B-EF57-39FC-9422-AFACB4A7F532]@0xffffff800a141000->0xffffff800a1c8fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[D342E754-A422-3F44-BFFB-DEE93F6723BC]@0xffffff8008821000->0xffffff8008822fff

Process name corresponding to current thread (0xffffff9079ac50c8): WindowServer
Boot args: agdpmod=pikera alcid=7

Mac OS version:
22E261

Kernel version:
Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
Kernel UUID: CF2A42DA-3F7C-30C6-9433-6F2076FF1F94
roots installed: 0
KernelCache slide: 0x0000000005e00000
KernelCache base:  0xffffff8006000000
Kernel slide:      0x0000000005edc000
Kernel text base:  0xffffff80060dc000
__HIB  text base: 0xffffff8005f00000
System model name: iMac20,1 (Mac-CFF7D910A743CAAF)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 10212632849286
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000949d05a6da4
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000ca5014098 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff8077012000 - 0xffffffa077012000
  . PGZ   : 0xffffff8077012000 - 0xffffff807f013000
  . VM    : 0xffffff807f013000 - 0xffffff854a9ac000
  . RO    : 0xffffff854a9ac000 - 0xffffff86e3cdf000
  . GEN0  : 0xffffff86e3cdf000 - 0xffffff8baf678000
  . GEN1  : 0xffffff8baf678000 - 0xffffff907b011000
  . GEN2  : 0xffffff907b011000 - 0xffffff95469aa000
  . GEN3  : 0xffffff95469aa000 - 0xffffff9a12344000
  . DATA  : 0xffffff9a12344000 - 0xffffffa077012000
  Metadata: 0xffffff804b002000 - 0xffffff806b002000
  Bitmaps : 0xffffff806b002000 - 0xffffff8077002000
  Extra   : 0 - 0

I don't know why it keeps crashing.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/blob/master/.github/ISSUE_TEMPLATE/bug-in-opencore-or-kext.md
