### ISSUE TITLE
Boot arg -igfxblr  is not working on macOS ventura 13.4

### ISSUE THREAD

**Issue by ameenjuz** [acidanthera/bugtracker#2284]
It is related to whatevergreen.kext  i tried manytime to ventura 13.4 but no luck 
I think that -igfxblr boot arg is break and i also tried prevoius versions of macOS ventura and  montery  working fine 
enable-backlight-registers-fix is not register properly on latest ventura 13.4 
Therefor i m facing black screen during boot process
Please fix this issue on whatevergreen.kext's project

**Comment by doantuyen15** [comment]
I have same problem.
Tried add and remove igfxblr in boot args then reboot, sometime its works but not completely fixed like ventura 13.3

**Comment by Edwardwich** [comment]
https://github.com/acidanthera/bugtracker/issues/2241

**Comment by OldDream** [comment]
same here seems we should wait till 13.5 release

**Comment by mandresve** [comment]
A temporary fix is to enable verbose mode boot arg. I've found that works most of the time but not always.

**Comment by mandresve** [comment]
As commented on other bug thread #2241 

>Looks like Apple let this one slip to final release of 13.4, albeit doesn't seem to be the case on 13.5; patches are functional again as of 13.5 Beta 1 (22G5027e).

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/2241
