### ISSUE TITLE
BlueToolFixup has problems with the dw1830 board's BT

### ISSUE THREAD

**Issue by Lorys89** [acidanthera/bugtracker#2285]
card in question dell dw1830 the bt on macos 13.4 or even 13.5 b1 does not work and does not activate, the only way to activate it is a warm restart on os monterey and restart again on macos ventura, but if I shut down and cold start macos ventura does not I will have bt and if I start monterey first and then reset nvram and start ventura I won't even have the bt.

I suppose something needs to be fixed on BlueToolFixup.
cc @dhinakg

**Comment by nguyentdat27** [comment]
Referring to an issue from #https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/435, try adding two params into NVRAM under UUID **7C436110-AB2A-4BBB-A880-FE41995C9F82** like the picture below:
<img width="968" alt="image" src="https://github.com/acidanthera/bugtracker/assets/47821599/32c8ca20-112f-492d-9163-4cd01bd97841">

**Comment by Lorys89** [comment]
> Referring to an issue from #[OpenIntelWireless/IntelBluetoothFirmware#435](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/435), try adding two keys into NVRAM under UUID **7C436110-AB2A-4BBB-A880-FE41995C9F82** like the picture below. I have DW1830 too, after adding these two keys and Reset NVRAM, bluetooth back to work again <img alt="image" width="968" src="https://user-images.githubusercontent.com/47821599/241524977-32c8ca20-112f-492d-9163-4cd01bd97841.png">


that fix doesn't work for me.
it works only if I start monterey on another partition and immediately restart and start ventura but when i turn off and start cold ventura i lose the bt

![Screenshot 2023-05-28 alle 10 44 37](https://github.com/acidanthera/bugtracker/assets/64613690/102bcb95-d7a0-44bb-8853-a01d49aa144d)

**Comment by umka-petrovich** [comment]
> > Referring to an issue from #[OpenIntelWireless/IntelBluetoothFirmware#435](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/435), try adding two keys into NVRAM under UUID **7C436110-AB2A-4BBB-A880-FE41995C9F82** like the picture below. I have DW1830 too, after adding these two keys and Reset NVRAM, bluetooth back to work again <img alt="image" width="968" src="https://user-images.githubusercontent.com/47821599/241524977-32c8ca20-112f-492d-9163-4cd01bd97841.png">
> 
> that fix doesn't work for me. it works only if I start monterey on another partition and immediately restart and start ventura but when i turn off and start cold ventura i lose the bt
> 
> ![Screenshot 2023-05-28 alle 10 44 37](https://user-images.githubusercontent.com/64613690/241530737-102bcb95-d7a0-44bb-8853-a01d49aa144d.png)

It's won't work on 13.5 beta 1. Working on 13.4 as report in Intel thread. Which version do you have installed?

**Comment by Lorys89** [comment]
🙈 13.5 b1 Otherwise I do not work the backlighting screen

**Comment by Lorys89** [comment]
What you are doing is a temporary solution, you definitely need to intervene on the kext.

**Comment by umka-petrovich** [comment]
> What you are doing is a temporary solution, you definitely need to intervene on the kext.

All the situation with BluetoothFixup (and other stuff) is a temporary and not stable solution.

**Comment by Lorys89** [comment]
I may have found a temporary solution
using the 2 entries mentioned above in sez nvram and deactivating the 2 kexts
![Screenshot 2023-05-29 alle 13 08 06](https://github.com/acidanthera/bugtracker/assets/64613690/ef5de05e-8fbe-4443-9268-5f02bdf11325)
![Screenshot 2023-05-29 alle 13 22 54](https://github.com/acidanthera/bugtracker/assets/64613690/51d52e9a-1cd0-4c15-af2c-e9791d328850)

work to macos 13.5 b1

**Comment by nguyentdat27** [comment]
> I may have found a temporary solution using the 2 entries mentioned above in sez nvram and deactivating the 2 kexts !)
> 
> work to macos 13.5 b1
  Add two keys to NVRAM only made it work for the first time it boot, After I tried uncheck two kexts like what you did and voila bluetooth get back to work. Thanks so much

**Comment by gujiangjiang** [comment]
https://github.com/zxystd/BrcmPatchRAM/commit/7f226298d9e0fda89edaee08ad163ca0d0277664

Allow Bluetooth to turn on after the first power cycle fixed by @zxystd

**Comment by gujiangjiang** [comment]
@Lorys89  I delete the 2 kexts in the picture and add 2 nvram data and my bluetooth works but cant  scan any bluetooth devices.

**Comment by Lorys89** [comment]
> [zxystd/BrcmPatchRAM@7f22629](https://github.com/zxystd/BrcmPatchRAM/commit/7f226298d9e0fda89edaee08ad163ca0d0277664)
> 
> Allow Bluetooth to turn on after the first power cycle fixed by @zxystd

fixed 
![Screenshot 2023-05-30 alle 16 04 59](https://github.com/acidanthera/bugtracker/assets/64613690/22cae312-5760-4c3f-80cd-6f99c021fe8b)

with 2 kext active :)

**Comment by nguyentdat27** [comment]
> 
> fixed ![Screenshot 2023-05-30 alle 16 04 59](https://user-images.githubusercontent.com/64613690/241992966-22cae312-5760-4c3f-80cd-6f99c021fe8b.png)
> 
> with 2 kext active :) But I do not use the 2 strings in nvram, I remain injected if I boot partition with monterey and keeps them until I reset nvram.

Would you mind sharing your built kext with commit from zxystd please ?

**Comment by Lorys89** [comment]
> > fixed ![Screenshot 2023-05-30 alle 16 04 59](https://user-images.githubusercontent.com/64613690/241992966-22cae312-5760-4c3f-80cd-6f99c021fe8b.png)
> > with 2 kext active :) But I do not use the 2 strings in nvram, I remain injected if I boot partition with monterey and keeps them until I reset nvram.
> 
> Would you mind sharing your built kext with commit from zxystd please ?

https://github.com/zxystd/BrcmPatchRAM/suites/13231677116/artifacts/720906228

**Comment by nguyentdat27** [comment]
> https://github.com/zxystd/BrcmPatchRAM/suites/13231677116/artifacts/720906228

Thanks for sharing. I only checked Release section and didn't even think about checking Action section.
