### ISSUE TITLE
NVMeFix : Samsung P981 reboots when erasing from disk utility in Installer

### ISSUE THREAD

**Issue by Human79** [acidanthera/bugtracker#2289]
As the title says, it reboots while crashinf using NVMeFIX, Although, using `ssdt-nvme.aml` and `HackrNVMeFamily-10_12_6_sec2018-001.kext`I can get through the first phase of the installation, however it gives `Unable to Prepare Software Update` error. Willing to provide all the logs.
Thank you!

**Comment by feartech** [comment]
those are not supported

**Comment by vanquybn** [comment]
I have replaced my P981 to WDC since there are many issue with P981 on MacOS.

**Comment by Human79** [comment]
Hi,
I've made it boot by installing macOS in a VM and then restroring that image to drive. Booting using the ssdt and the kext mentioned above. Seems to be a problem with installer compatibility.

**Comment by mikebeaton** [comment]
https://github.com/acidanthera/bugtracker/issues/2287#issuecomment-1578271882
