### ISSUE TITLE
Request to add proper audio coefficients for alienware m15 ryzen edition

### ISSUE THREAD

**Issue by ryzendew** [acidanthera/bugtracker#2293]
[audio info dump.txt](https://github.com/acidanthera/bugtracker/files/11677728/audio.info.dump.txt)

i hope this is correct! i tried every layout and none worked properly.

**Comment by Core-i99** [comment]
You need to make a new layout id yourself.

**Comment by perez987** [comment]
@RyzenDew 
This can help you.
[AppleALC guides](https://github.com/5T33Z0/AppleALC-Guides)

**Comment by RyzenDew** [comment]
Ya sorry thats no help at all and no I can’t do this by my self at all i am still recovering from brain damage… i miss the old hackintosh community… i guess hacks are dead if the community can’t even maintain a repo anymore or help now. Sent from my iPhoneOn Jun 7, 2023, at 7:12 PM, Emilio P Egido ***@***.***> wrote:﻿
@RyzenDew
This can help you.
AppleALC guides

**Comment by RyzenDew** [comment]
> @RyzenDew This can help you. [AppleALC guides](https://github.com/5T33Z0/AppleALC-Guides)

that guide is written for robots not people it's of no use what so ever ..

**Comment by Core-i99** [comment]
When I made my layout id, there was no decent guide. Only old applehda patching stuff on forums.
Be happy that there is a guide now, 10x better already.
It takes some time to learn it through. If you are on the AMD discord server, feel free to tag me (same user name).

**Comment by mikebeaton** [comment]
Another guide which some people found helpful is: https://github.com/F0x1c/AppleALC_Instructions - YMMV
