### ISSUE TITLE
What is the correct value to disable SIP on Ventura?

### ISSUE THREAD

**Issue by michael1900** [acidanthera/bugtracker#2294]
Installed Ventura with opencore on my old MacBook Pro model MacBookPro13,3;
 
with value 6F020000 **0x26f** i have: System Integrity Protection status: disabled BUT i no longer have brightness controls;
with value 870A0000 **0xA87**  i have: System integrity Protection status: unknown (Custom configuration) BUT still i have brightness controls.

<img width="572" alt="Screenshot 2023-06-07 alle 17 00 42" src="https://github.com/acidanthera/bugtracker/assets/1675875/071b2fda-0fe7-4fc7-b057-5a715bae205c">

So how to disable SIP _**correctly**_ without break brightness?

**Comment by vanquybn** [comment]
FF0F0000 <== work fine for me on 13.4

**Comment by michael1900** [comment]
> FF0F0000 <== work fine for me on 13.4

With this value, what is the output from **csrutil status** in terminal?

**Comment by mikebeaton** [comment]
You are very likely using OCLP, in which case this should be posted as an OCLP issue (or support request) - there is no bug in OC, it is just a matter of the required settings for the patches your system uses.

SIP is not really a single thing, it is made of multiple bits, which can be enabled or disabled independently. Only certain combinations are recognised as simply being 'Disabled' or 'Enabled' by macOS, but all other ('unsupported') combinations also work. You can view the bits here: https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleCsrConfig.h#L26-L38

**Comment by michael1900** [comment]
> You are very likely using OCLP, in which case this should be posted as an OCLP issue (or support request) - there is no bug in OC, it is just a matter of the required settings for the patches your system uses.
> 
> SIP is not really a single thing, it is made of multiple bits, which can be enabled or disabled independently. Only certain fixed combinations are recognised as simple SIP 'Disabled' or 'Enabled' by macOS, but all other ('custom') combinations also work. You can view the bits here: https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleCsrConfig.h#L26-L38

About an OCLP issue unfortunately is not possible :(

Do you think that i can use that ff0f value without problems, especially with updates? I mean you what value can advice me?
Do you know why with the _recognised_ 0x26f my Ventura lost the brightness control?

**Comment by mikebeaton** [comment]
> Do you know why with the recognised 0x26f my Ventura lost the brightness control?

No. As I say, I believe it is specific to the patches (not standard parts of macOS) in your setup - I think likely from OCLP? (I am not saying there is anything wrong with those patches, just that - it seems - they need a non-standard SIP setting to work.)

> About an OCLP issue unfortunately is not possible :(

Why not possible? Are you using OCLP?

**Comment by michael1900** [comment]
> > About an OCLP issue unfortunately is not possible :(
> 
> Why not possible? Are you using OCLP?

I

**Comment by khronokernel** [comment]
@mikebeaton Dortania bug tracker is not for Macs, please don't suggest it:
<img width="649" alt="Screenshot 2023-06-09 at 8 34 43 AM" src="https://github.com/acidanthera/bugtracker/assets/48863253/ede9ad91-3e4d-4b5c-84f3-f78f974ba07a">

**Comment by mikebeaton** [comment]
@khronokernel - Apologies, since the OCLP one is shut, I was wrongly assuming the the dortania bugtracker was acting like the acidanthera bugtracker as a master bugtracker.

I wonder perhaps if that "Bugs with OpenCore Legacy Patcher/Bugtracker is meant for Dortania Hackintosh Guides" text could be moved to the top of the README or into the two issue templates, and I did actually click through into the issue templates before providing that link, and did not see anything (there) saying that the tracker was _not_ for OCLP.
