### ISSUE TITLE
USB restriction patches for MacOS11 to 14 systems, Check XhciPortLimit and then all USB ports can be used, breaking the limit of 15 ports

### ISSUE THREAD

**Issue by WaTeZhuangJiDingZhi** [acidanthera/bugtracker#2297]
USB restriction patches for MacOS11 to 14 systems, Check XhciPortLimit and then all USB ports can be used, breaking the limit of 15 ports
.Hope to integrate this patch into opencore

https://github.com/WaTeZhuangJiDingZhi/wate

**Comment by andreszerocross** [comment]
> WaTeZhuangJiDingZhi

This patch didn't work in ventura. i tried it with my Z170X Gaming 7.

Only HS01 => SS01 = 15Ports show, remaining port (SS02 => SS10) didn't show.

These patch doesn't need "XhciPortLimit = YES / TRUE" right??

![image](https://github.com/acidanthera/bugtracker/assets/9614101/86e05ee8-94a0-4175-a0c8-687f5c73bda0)

**Comment by andreszerocross** [comment]
Sorry for my comment above.

With "XHCIPortLimit = TRUE/YES" + 2 Those Patch. My all Ports is shown, HS01 => SS10, 

And i have tried it with my USB 3.0 Flahsdrive, Correct mount and speed, My USB 3.0 is mounted to every available SSxx in my PC.

cc @vit9696  and @PMheart . Maybe you can consider to merge this patch to "XHCIPortLimit"?

![Screenshot 2023-06-10 at 10 42 19](https://github.com/acidanthera/bugtracker/assets/9614101/15c72ee6-0fa0-4ad6-9330-9a47a97eaeb9)

**Comment by MizhiDR** [comment]
I tried, but there is a downside.its principle Increase the number of loops for XhciCreatePorts to initialize ports！
![58d788a219d4c2cdfd81254a2f599cd7](https://github.com/acidanthera/bugtracker/assets/28851784/b0065c31-3ab6-4e29-99ec-8fde4dd645ac)

**Comment by MizhiDR** [comment]
someone tried， but there is a downside.its principle Increase the number of loops for XhciCreatePorts to initialize ports！
![58d788a219d4c2cdfd81254a2f599cd7](https://github.com/acidanthera/bugtracker/assets/28851784/239bbbbc-9145-4b07-9fd0-10744e45cc1a)

**Comment by andreszerocross** [comment]
> someone tried， but there is a downside.its principle Increase the number of loops for XhciCreatePorts to initialize ports！
> ![58d788a219d4c2cdfd81254a2f599cd7](https://user-images.githubusercontent.com/28851784/244852419-239bbbbc-9145-4b07-9fd0-10744e45cc1a.png)

I assume his ACPI is not correct.

Maybe the address of acpi is wrong or another USB kext cause that. For me there is no problem for that.

SS08 in your picture should address 15000000

**Comment by MizhiDR** [comment]
> > 有人试过，但是有一个缺点，它的原理是增加XhciCreatePorts初始化端口的循环次数！
> > ![58d788a219d4c2cdfd81254a2f599cd7](https://user-images.githubusercontent.com/28851784/244852419-239bbbbc-9145-4b07-9fd0-10744e45cc1a.png)
> 
> 我假设他的 ACPI 不正确。
> 
> 可能是 acpi 的地址错误或另一个 USB kext 导致的。对我来说没有问题。
> 
> 您图片中的 SS08 应地址为 15000000

1400000 directly conflicts with RootHub's Location

**Comment by iamyounix** [comment]
Just try, 1st enable BS/Monterey Patch and enable XHCIPortlimit. Do not enable ventura/Sonoma patch unless you are using both. Quite impressive. Nice to know and testing.

**Comment by andreszerocross** [comment]
> Just enable BS/Monterey Patch and enable XHCIPortlimit. Working!...Do not enable ventura/Sonoma patch unless you are using both. Quite impressive. Nice to know and testing.
> 
> ![Screenshot 2023-06-11 at 8 17 03 AM](https://user-images.githubusercontent.com/72515939/244900407-625b5a39-6149-4f14-97b4-fb320233c0ad.png)
> 
> ![Screenshot 2023-06-11 at 8 33 57 AM](https://user-images.githubusercontent.com/72515939/244901513-3181c398-5db5-4aef-953b-860977bb3013.png)
> 
> ![Screenshot 2023-06-11 at 8 34 43 AM](https://user-images.githubusercontent.com/72515939/244901957-33ece868-09a4-4c41-932f-76f077cab6f6.png)

No problem to enable both, because patch activation is limited by Min and max kernel

**Comment by ameenjuz** [comment]
@andreszerocross  this quirk patch was working on macOS Catalina and earlier version
is it working now on macOS Ventura&Sonoma?

**Comment by PMheart** [comment]
I integrated the patch, and developed a unique one that should work for macOS 11 up to 14. Please check out https://github.com/acidanthera/OpenCorePkg/pull/471 and use the binaries from https://github.com/acidanthera/OpenCorePkg/actions/runs/5238087210 to test and report. Thanks!

**Comment by iamyounix** [comment]
> I integrated the patch, and developed a unique one that should work for macOS 11 up to 14. Please check out [acidanthera/OpenCorePkg#471](https://github.com/acidanthera/OpenCorePkg/pull/471) and use the binaries from https://github.com/acidanthera/OpenCorePkg/actions/runs/5238087210 to test and report. Thanks!

TQ PMHeart

**Comment by WaTeZhuangJiDingZhi** [comment]
Of course, you still need to cancel the original USB port patch and re-inject USBInjectAll.kext or XHCI-unsupported.kext (up to Z690) USBToolBox.kext+UTBMap.kext (for 700 and AMD)

Sorry Sonoma apple has changed the patch, I need to search again, so the above patch is applicable to 11-13, Sonoma I am going to search again, I am busy recently. It would be nice to have an x86 assembler expert assist me

**Comment by iamyounix** [comment]
> Of course, you still need to cancel the original USB port patch and re-inject USBInjectAll.kext or XHCI-unsupported.kext (up to Z690) USBToolBox.kext+UTBMap.kext (for 700 and AMD)
> 
> Sorry Sonoma apple has changed the patch, I need to search again, so the above patch is applicable to 11-13, Sonoma I am going to search again, I am busy recently. It would be nice to have an x86 assembler expert assist me

![Screenshot 2023-06-12 at 11 49 42 AM](https://github.com/acidanthera/bugtracker/assets/72515939/89201fe4-d0f1-46d6-a52b-645912c2b4e6)

As test, work with manually patch.

**Comment by ExtremeXT** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Kernel</key>
	<dict>
		<key>Patch</key>
		<array>
			<dict>
				<key>Arch</key>
				<string>x86_64</string>
				<key>Base</key>
				<string>__ZN16AppleUSBHostPort15setPortLocationEj</string>
				<key>Comment</key>
				<string>setPortLocation - Increase USB limit from 0xf (15) to 0x3f (63) ports per controller</string>
				<key>Count</key>
				<integer>1</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>QYPgDw==</data>
				<key>Identifier</key>
				<string>com.apple.iokit.IOUSBHostFamily</string>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data>////Dw==</data>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string>20.4.0</string>
				<key>Replace</key>
				<data>AAAAMA==</data>
				<key>ReplaceMask</key>
				<data>AAAA8A==</data>
				<key>Skip</key>
				<integer>0</integer>
			</dict>
		</array>
	</dict>
</dict>
</plist>
`

Unified patch, from 11.3 to 14.0 beta 1 with byte masking.

**Comment by PMheart** [comment]
Could you please upload OC log with binaries from my PR? Thanks! @iamyounix
