### ISSUE TITLE
Brightness control on UHD 630 Comet Lake

### ISSUE THREAD

**Issue by i4pptem** [acidanthera/bugtracker#2298]
Hello!
Hardware: Razer Blade 15 Base 2021
CPU: i7 10750H
I got issue with brightness control on UHD 630, I have tried a lot of platform-id for CML, no changes in brightness.
I have PNLF and BrightnessKeys applied, no changes.
![Снимок экрана 2023-06-12 в 06 19 07](https://github.com/acidanthera/bugtracker/assets/39266353/27121526-86f1-4dd4-a43b-94c2ba8686d0)

[IOREG.zip](https://github.com/acidanthera/bugtracker/files/11717217/IOREG.zip)
[ACPI,CONFIG.zip](https://github.com/acidanthera/bugtracker/files/11717219/ACPI.CONFIG.zip)

**Comment by Lorys89** [comment]
try to add device-id 9B3E0000 DATA
