### ISSUE TITLE
[Building] Use folders to diversify output products

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2301]
When compiling the majority of the kexts that you, a great team, released, a ZIP archive is created.

e.g. `KEXT-VERSION-VERSION_TYPE.zip` which contains:
 
- `KEXT_NAME.kext`
- `KEXT_NAME.dSYM`
- other stuff like tools etc

It would be great to diversify the outputed stuff like already done with `VirtualSMC` or `CPUFriend` where the ""final"" zip file contains the following structure:

```
VirtualSMC-1.3.2-RELEASE/
├── Kexts <-------- Here goes the kexts
├── Tools <-------- Here all the non-kext/non-dSYM stuff goes
└── dSYM <------- Here all the dSYM goes
```

Would this thing be achievable? This would possibly improve the automation of some processes like updating the kexts without having to make per-kext rules (e.g. for Lilu grab the kext directly from the extracted zip archive folder, while for VirtualSMC navigate onto the `Kexts` folder then grab them).

**Comment by vit9696** [comment]
This would be, but I am not sure it is worth it. Having simpler structure allows extracting files without delving into too many subfolders.

**Comment by dreamwhite** [comment]
> This would be, but I am not sure it is worth it. Having simpler structure allows extracting files without delving into too many subfolders.

Oh sure, it was just an idea came out of my head since I found some “inconsistency” among 99% of the projects you amazing guys released and VirtualSMC (e.g) which have subfolders structure.

In any case it shouldn’t be much a problem as I’m actually using a stupid algorithm based on a `rules.json` file
