### ISSUE TITLE
i5-13400 is not a compatible processor

### ISSUE THREAD

**Issue by JoePx** [acidanthera/bugtracker#2305]
CPU:  i5-13400
motherboard: Maxsun B760ITX 
Mac：ventura 13.4
other:    OpenCore，Lilu，VirtualSMC，SMCProcessor Updated to the latest version(release + dev + debug)
The kernel's order: 
<img width="321" alt="图片" src="https://github.com/acidanthera/bugtracker/assets/22520014/b0e7d735-e95a-4eda-ba94-1c02065f89d0">
apps cannot read the CPU temperature, except for Intel Power Gadget

the lilu's log
[Lilu_1.6.6_22.5.txt](https://github.com/acidanthera/bugtracker/files/11786168/Lilu_1.6.6_22.5.txt)

**Comment by joezjy** [comment]
<img width="448" alt="图片" src="https://github.com/acidanthera/bugtracker/assets/22520014/c81ffecc-5bd8-4f86-b076-f4552cff51af">
I know why now. My CPU's CPUModel is 0xBF(i5-13400), but in kern_cpu.hpp, the CPUModel for CPU_MODEL_RAPTORLAKE_S is 0xB7. So the Lilu's log is "WhateverGreen igfx: @ found an unsupported processor 0x6:0xBF, please report this!"


Please update the CPUModel message in kern_cpu.hpp,  thx.

**Comment by al3xtjames** [comment]
Could you try [the artifacts from the PR](https://github.com/acidanthera/Lilu/actions/runs/5316840587 )?

**Comment by joezjy** [comment]
Thank you for fixing the issue! 
I have tested the artifacts from the PR and they work perfectly.
