### ISSUE TITLE
LapicKernelPanic quirk seems to be broken on 10.7.5.

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [acidanthera/bugtracker#2308]
Getting a kernel panic seemingly related to Lapic on a Pavilion dv6-1245dx, attempting to boot 10.7.5 Lion, despite having the LapicKernelPanic quirk enabled. I also tried `cpus=1` and `lapic_dont_panic=1`, however they gave the same panic. It appears the LapicKernelPanic quirk is not working.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/11902386/EFI.zip)
[opencore-2008-01-01-000017.txt](https://github.com/acidanthera/bugtracker/files/11902387/opencore-2008-01-01-000017.txt)
![PXL_20230629_054650204](https://github.com/acidanthera/bugtracker/assets/78825510/ae1f7d42-3c6b-403d-99e2-8d83f67ff544)

**Comment by PMheart** [comment]
Hello! I just found a similar issue: https://github.com/acidanthera/bugtracker/issues/370. If I get it correctly, `lapic_dont_panic=1` does not exist on 10.7. However, I am not sure if `debug=` has any effect here either. Could you please:

- Try booting without `debug` boot argument;
- If the quirk still does not work, try using `cpus=1` by disabling the quirk as well.

Also, could you please upload the mach_kernel so I can take a look? Thanks!

**Comment by Lost-Entrepreneur439** [comment]
I removed debug=0x100 and added cpus=1, with that the system just rebooted after loading kernelcache.

**Comment by Lost-Entrepreneur439** [comment]
I tried that, and while I'm still getting a panic quite early in the boot process, it is not related to Lapic, it appears that commit has fixed LapicKernelPanic on these older versions. For now I'm going to treat the panic I'm getting now as an issue in my EFI, and I'll open another issue if it does seem to be an issue with OpenCore. Thank you so much for working on OpenCore (and any other hackintosh projects you work on)!

**Comment by PMheart** [comment]
Thanks for the confirmation. Could you please further verify/compare the results with and without `debug=` argument and with and without `cpus=1`?

**Comment by Lost-Entrepreneur439** [comment]
I haven't tried without debug=0x100, however I have tried with cpus=1 and it booted fine.

**Comment by PMheart** [comment]
Thanks. I believe that we can merge it now; will do later.
