### ISSUE TITLE
WhateverGreen is unable to drive hdr normally

### ISSUE THREAD

**Issue by xiusheng1** [acidanthera/bugtracker#2309]
Problem description:
The HDR function cannot be used normally when the Macmini 8,1 model is used with the fake ID of the 3E9B0007 video card. The problem is that the screen turns black after the High dynamic range is turned on in the display settings. The display backlight is bright but the screen does not display. At this time, the device can only be forced to restart, and the High dynamic range will automatically open after the device is restarted, However, if you choose to turn off the screen or wake up again after sleep, the previous black screen and backlight will still be repeated. Through the system log, it is found that when the High dynamic range is turned on, there will be an error that the hdr cannot be output through this port

Attempted solutions:
IMac+3E9B0007 High dynamic range can be used normally without black screen
Macmini+3E9B0000 High dynamic range can be used normally without black screen
Macmini+3E9B0007+multi display High dynamic range can be used normally without black screen

Device Configuration
Power: 230W
CPU: Intel Comet Lake i5-10500
Chipset: Intel Q470
IGPU: UHD 630
Memory: 16G DDR4 3200 * 2
SSD1: WD SN550 PCI-E M.2 512GB (mac)
Sound: ALC235
Ethernet: Intel I219-LM7
WIFI-M2: BCM94360CS2 M.2
SMBIOS type Macmini 8,1

Driver version：
Lily.kext 1.6.6
WhateverGreen.kext 1.6.5
VirtualSMC.kext 1.3.2
SMCProcessor.kext 1.3.2
SMCSuperIO.kext 1.3.2
AppleALC.kext 1.8.3
IntelMausi.kext 1.0.7

logs：
[log.txt](https://github.com/acidanthera/bugtracker/files/11914697/log.txt)

**Comment by vit9696** [comment]
I think it is easier to switch the model rather than debug this.
