### ISSUE TITLE
Can't boot Opencore without usb drive

### ISSUE THREAD

**Issue by ShadyEmad111** [acidanthera/bugtracker#2312]
Hello, 
I have a laptop which is Samsung NP350V5C-A02AE
CPU: I5-3210M
GPU: Intel HD Graphics 4000 
I installed SSD in it and as and internal drive and replaced the internal disk drive with the HDD so i have both drives inside the laptop
I followed Dortania's Opencore but i can't boot without the usb drive even after copying and pasting the efi file in the efi partition.
Here is my config if there is any mistake made 
[config.txt](https://github.com/acidanthera/bugtracker/files/12137319/config.txt)

**Comment by PMheart** [comment]
Hello, please post on forums for support.

**Comment by ShadyEmad111** [comment]
> Hello, please post on forums for support.

Where to post it specifically?

**Comment by Core-i99** [comment]
https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/FORUMS.md
