### ISSUE TITLE
IntelMausi no longer wakes-on-lan (WOL)

### ISSUE THREAD

**Issue by xenophon61** [acidanthera/bugtracker#2320]
Hi, and thanks in advance.

Current OC (0.9.4) running Ventura 13.5 and InteliMausi 1.0.7 on a GA-z390 Designare (Intel I219 port, latest BIOS).

When the system goes to sleep, the port LEDs are off, and WOL from the LAN does nothing - it used to work fine for years. I suspect the problem manifest a couple of weeks after the 13.5 update.

Installed Ubuntu to test, just in case, and WOL is fine.

Tried other versions of Mausi, as well as all the MausiEthernet kexts on github, with a custom mausi-force-wol device property and everything, to no avail.

Greetings from Athens (and huge thanks!).

Xen

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/IntelMausi/blob/master/README.md
Do use the original version when uncertain. No support or troubleshooting provided.
