### ISSUE TITLE
New feature in OC to ForceResolution on ATI GPU's not working with RX 460 with 4K UHD Monitor

### ISSUE THREAD

**Issue by MacNB** [acidanthera/bugtracker#2321]
**System**: Legacy BIOS Dell Inspiron 530 (Xeon CPU)
**OpenCore**: 0.9.4 DEBUG (OpenDuet) with emulated NVRAM
**macOS**: Various. Tested on Big Sur & Monterey
**GPU**: MSI RX 460 2GB
**Monitor**: Dell S2721QS (UHD)
**Issue**: 
- ForceResolution=True and Resolution=3840x2160 results in 800x600 Boot Picker screen
- macOS boots fine and presents correct screen resolution. Just the OpenCore boot picker screen resolution is not forced as requested. 

**OpenCore debug shows**:

01:204 00:090 OCC: GOP exists on ConsoleOutHandle and has 5 modes
01:207 00:003 OC: Requested resolution is 3840x2160@0 (max: 0, force: 1) from 3840x2160
01:284 00:076 OCC: Requesting 3840x2160@0 (max: 0) resolution, curr 2, total 5
01:288 00:003 OCC: Current FB at 0xB0000000 (0x3000000), format 1, res 800x600 scan 832
01:291 00:003 OCC: Mode 0 - 1280x960:1
01:295 00:003 OCC: Mode 1 - 640x480:1
01:298 00:003 OCC: Mode 2 - 800x600:1
01:302 00:003 OCC: Mode 3 - 1024x768:1
01:305 00:003 OCC: Mode 4 - 1280x1024:1
01:309 00:003 OCC: No compatible mode for 3840x2160@0 (max: 0) resolution
01:312 00:003 OC: Changed resolution to 3840x2160@0 (max: 0, force: 1) from 3840x2160 - Not Found
01:316 00:003 OCC: MTRR supported, PAT supported
01:319 00:003 OCC: PAT 0x0007040600070406 (default)
01:323 00:003 OCC: 0xB0000000 MTRR 0=UC PTE2 bits 0x00000000B00000E3 PAT@0->6=WB - Success
01:326 00:003 OCC: Writing PAT 0x0107040600070406
01:330 00:003 OCC: PAT 0x0107040600070406 (not default)
01:333 00:003 OCC: 0xB0000000 MTRR 0=UC PTE2 bits 0x00000000B00010FB PAT@7->1=WC - Success
01:337 00:003 OC: Selected UIScale 1 based on 800x600 resolution
01:340 00:003 OC: Setting UIScale to 1 - Success
01:344 00:003 OCC: Using builtin text renderer with 1 scale
01:348 00:003 OCC: Install console control (AF37EF18/AFC3D400/0), current - Not Found
01:351 00:003 OCC: Install console control, new - Success
01:356 00:005 OCC: Setup ASCII Output - Success
01:359 00:003 OC: Requested console mode is 0x0 (max: 1) from Max
01:363 00:003 OCC: Requesting 0x0 (max: 1) console mode, curr 0, max 1
01:367 00:003 OCC: Mode 0 - 100x37
01:370 00:003 OCC: Current console mode matches desired mode 0, forcing update
01:373 00:003 OCC: Setting mode 0 (prev 0) with 100x37 console mode
01:377 00:003 OCC: Changed console mode to 0
01:381 00:003 OC: Changed console mode to 0x0 (max: 1) from Max - Success
01:384 00:003 OC: Requested not to use audio
01:387 00:003 OC: OcMiscLoadSystemReport...
01:391 00:003 OC: OcLoadAcpiSupport...

Setting ForceResolution=False and Resolution=Max produced boot picker resolution of 1280x1024.

Does **ForceResolution** quirk rely on the motherboard BIOS resolutions, or the ATI GPU supported resolutions or the Monitors supported resolutions?

[config-dell-530.plist.zip](https://github.com/acidanthera/bugtracker/files/12346057/config-dell-530.plist.zip)

**Comment by vit9696** [comment]
I do not think it is going to be possible to get 4K resolution without loading UEFI GOP Option ROM, and that thing is very unlikely to happen in OpenDuet due to overall stability issues.

**Comment by MacNB** [comment]
Thanks @vit9696
Actually, it is not just 4K resolutions that do not work. I cannot even the set the resolution to 1920x1080.
That is, the ForceResolution quirk does not work with ATI GPU's.
It would be good to see an example of this working. That is, which ATI GPU was tested and at what resolution with which monitor ?
If it does not work then may be it should not be documented as a feature.

**Comment by vit9696** [comment]
For some it does work, e.g. for my HD 6450. Just it may be working on some rather old ones.
