### ISSUE TITLE
WhateverGreen: Certain apps are broken after waking from sleep

### ISSUE THREAD

**Issue by meghan06** [acidanthera/bugtracker#2323]
After waking from sleep, some apps that are entirely closed (i.e cmd q'd) are broken. 

The known list of apps that break include:
- Chromium based apps are blank
     - Google Chrome, Spotify are examples 
- Electron based apps blank 
      - Discord is one example
- Buggy video playback in web browsers  like Firefox or Safari (stutters or fails to play)
- Display/Wallpaper settings in SysPref/SysSettings don't work (can't change wallpaper, etc)
- Logging out freezes your system

How to reproduce:
- Make sure affected apps are closed entirely
- Set device to sleep 
- Wake the device 
- Try to launch affected apps 

What happens:
Affected apps break 

Expected behavior:
Apps should work as usual

Example of issue:
![image](https://github.com/acidanthera/bugtracker/assets/77316348/a72fb4c2-5215-43ce-a676-1802fbb26862)

Hardware tested:
Intel m3-8100Y, UHD 616 Amberlake
Various other Skylake/CometLake devices

**Comment by starsnwind** [comment]
Same problem.
Hardware tested:
Intel i7-10610, UHD 655(counterfeit)
AAPL,ig-platform-id:0000A53E
MacOS version: 14

**Comment by Andrey1970AppleLife** [comment]
Has no relation to WEG.
