### ISSUE TITLE
Phantom About This Mac Alert after Temporalily Removing RestrictEvents.kext

### ISSUE THREAD

**Issue by ethaldeman** [acidanthera/bugtracker#2324]
I was updating my Mac Ventura 13.5 to 13.5.1 and I wanted to use the Delta update, and not require the full update. Therefore I removed BlueToolFixup.kext and RestrictEvents.kext, as noted in https://github.com/acidanthera/bugtracker/issues/2080, to allow the Delta update to complete.

Upon removing RestrictEvents.kext, I noticed 1 alert under About my Mac. I had no alerts before and this new alter was expected because I use RestrictEvents.kext to prevent the MacPro7,1 Memory Errors bug, https://dortania.github.io/OpenCore-Post-Install/universal/memory.html. I also confirmed the new alert was the Memory Errors bug. 

The Delta update was successfully completed and I added back BlueToolFixup.kext and RestrictEvents.kext. However the 1 alert remains under About This Mac. I have checked About This Mac and confirmed the Memory Errors bug is no longer present. I cannot find a way to remove/clear the alert and have tried removing and reading RestrictEvents.kext.

Attached are my Luli debug log, OC directory, and OC debug log. 

[Lilu_1.6.7_22.6.txt](https://github.com/acidanthera/bugtracker/files/12446004/Lilu_1.6.7_22.6.txt)
[OC.zip](https://github.com/acidanthera/bugtracker/files/12446010/OC.zip)
[opencore-2023-08-26-161701.txt](https://github.com/acidanthera/bugtracker/files/12446045/opencore-2023-08-26-161701.txt)

**Comment by perez987** [comment]
@ethaldeman 
Did you read the RestrictEvents README.md? Whose last lines say:

**Removing badges (This works until macOS 13)**

If using RestrictEvents to block PCI and RAM configuration notifications, they will go away, but the alert in the Apple menu will stay. To get rid of this alert, run the following commands:

```
defaults delete com.apple.SlotNotificationsPref memoryBadgeCount
defaults delete com.apple.SlotNotificationsPref expansionBadgeCount
```

**Comment by ethaldeman** [comment]
I did read the RAEDME.md, but apparently not close enough ....... . I ran the commands, with and without sudo, but it did not work; the alert still remains. 

`winthryth@Mac-Pro ~ % defaults delete com.apple.SlotNotificationsPref expansionBadgeCount`
`2023-08-26 20:42:03.143 defaults[765:8785]`
`Domain (com.apple.SlotNotificationsPref) not found.`
`Defaults have not been changed.`
`winthryth@Mac-Pro ~ % defaults delete com.apple.SlotNotificationsPref memoryBadgeCount`
`2023-08-26 20:42:05.303 defaults[766:8805]`
`Domain (com.apple.SlotNotificationsPref) not found.`
`Defaults have not been changed.`

The README.md also notes this works until macOS 13, which is the version I am running.

**Comment by perez987** [comment]
@ethaldeman 
Yes, this is an unresolved issue on some systems well known by RestrictEvents developers. 
Please close the issue.

**Comment by perez987** [comment]
@ethaldeman 
I’m not confident that the 1 alert text goes away changing to custom memory but it’s worth a try.
If you try this way, in my opinion this is the best site to read about it:

[Fixing MacPro7,1 Memory Errors](https://github.com/RTHPJM/OpenCore-Post-Install/blob/master/universal/memory.md)

**Comment by ethaldeman** [comment]
I followed the provided guide, and created my CustomMemory.plist. I confirmed it removed the Memory Errors under About My Mac, unfortunately the Phantom Alert remained. Hopefully a solution can be found eventually.
