### ISSUE TITLE
[EB|#LOG:EXITBS:START]

### ISSUE THREAD

**Issue by 1325ok** [acidanthera/bugtracker#2326]
![image](https://github.com/acidanthera/bugtracker/assets/93064596/98ba4e77-e8b6-490c-8cbd-17cfc21b5f16)

When booting macOS Mojave with OpenCore, it keeps getting stuck at `[EB|#LOG:EXITBS:START]`.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/12567945/EFI.zip)
[opencore-2022-07-18-013002.txt](https://github.com/acidanthera/bugtracker/files/12567946/opencore-2022-07-18-013002.txt)

**Comment by mikebeaton** [comment]
This is a common place for macOS to stop when OpenCore is not configured correctly for the machine and OS. The bugtracker is not a support forum, please use online installation guides and support forums.
