### ISSUE TITLE
FeatureUnlock: [Feature Request] 3D Globe View and Advanced Landmarks Unlock

### ISSUE THREAD

**Issue by JDDPro** [acidanthera/bugtracker#2328]
The FeatureUnlock kext is perfect for unlocking disabled features on older Macs and Hackintoshes. However I just recently noticed that another advanced feature can be unlocked via injecting kexts, which is the "3D Globe View" and "Advanced Landmarks" festures in the Apple Maps app, but the feature is not yet present in the kext. If this feature could be planted in the future versions of the kext I'd appreciate it very much.

[Twitter link](https://twitter.com/zhuowei/status/1402846536090984449), here is a sample link of someone successfully unlocking the features. I've tried and it works fine on my 2012, 2015 and 2017 with Ventura and Monterey.

Gratitudes xx

**Comment by m0d16l14n1** [comment]
According to that one - it's possible to support on Intel with supported dGPU only (mainly desktops). You can try on yours - https://github.com/notjosh/AdvancedMap

**Comment by JDDPro** [comment]
> 

Thank you. I've tried several methods and they actually do work on my Intel iGPU (both real Mac and Hackintosh)

**Comment by khronokernel** [comment]
I see the AdvancedMap repo is kept up, I would recommend using that project as I don't believe anyone internally wants to maintain the `DeviceSupportsAdvancedMapRendering` patch set. Can be reconsidered in the future if the author longer maintains the project, patch set breaks, etc
