### ISSUE TITLE
VirtualSMC doesnt work in the main macOS

### ISSUE THREAD

**Issue by DevFelixLiS** [acidanthera/bugtracker#2334]
[EFI](https://files.nocx420.xyz/opreKWyl.zip) 
[Boot Log](https://files.nocx420.xyz/Lxa6g2mn.txt) 

Hello ^^,
I've been attempting to build a Hackintosh for about a month now using my laptop. I've encountered the "Waiting for DSMOS..." issue, where it becomes stuck during the boot process from the disk containing macOS. However, RecoveryOS works perfectly fine.

I'm an active member of a Hackintosh forum, and even some well-known individuals in the community are puzzled as to why it's not booting. Could it possibly be a bug?

Here's what I've tried for troubleshooting:

>     Attempting to understand what "Waiting for DSMOS..." signifies, as outlined in this guide: [Dortania](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#kernel-panic-appleacpiplatform-in-10-13)
>     Experimenting with various VirtualSMC alternatives, such as FakeSMC
>     Enabling SMC Gen1 (vsmcgen=1)
>     Using a minimal set of Kexts (only Lilu and VirtualSMC)
>     Testing with Big Sur, Monterey, and Ventura
>     Adjusting Booter-Quirks for MAT support (0 and 1)
>     Up-to-date Kexts & OpenCore

**Comment by DevFelixLiS** [comment]
Already was, they have no idea what so ever. throught it may be an opencore or VirtualSMC bug. 
Removing the patches doesnt fix it unfortunately.

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
