### ISSUE TITLE
Support for changing UnfairGVA Board-ID

### ISSUE THREAD

**Issue by GreyAsteroid** [acidanthera/bugtracker#2340]
Currently when using the MacPro7,1 or iMacPro1,1 smbios there is no way to have the iGPU perform hardware decode/encode (that I'm aware of) without patching WhateverGreen to use an iMac board-id for hwgva-id while using unfairgva. There are few use cases where this would be necessary but an option would be nice instead of having to patch WhateverGreen.

**Comment by Andrey1970AppleLife** [comment]
There is no need. Use iMac smbios for IQSV.
