### ISSUE TITLE
RE bugs on Ventura 13.4+

### ISSUE THREAD

**Issue by gorouflex** [acidanthera/bugtracker#2342]
Hey, i found out that if the RE (RestrictedEvent.kext) is enabled with macOS 13.4+, it will crash the System Setting app and some Apple applications like XCode, System Infomation will failed to get infomation after it occurs

Extra infomation:
- Latest RE kext
- CPU: AMD Ryzen 5 4500U
![Screenshot 2023-10-30 at 22 37 01](https://github.com/acidanthera/bugtracker/assets/98001973/c70d4b3e-b595-4efb-9fc7-ddc2dc862c8b)

**Comment by perez987** [comment]
@gorouflex 
I think that this bugtracker is only for Intel systems. 
Go to support forums like [AMD OSX](https://amd-osx.com/).
