### ISSUE TITLE
WhateverGreen: UHD630 black screen after boot

### ISSUE THREAD

**Issue by korzhyk** [acidanthera/bugtracker#2360]
OpenCore 0.9.7
Lilu 1.6.7
WhateverGreen 1.6.6
– all *DEBUG* versions

System specs DELL MFF 5090 (2 × DP physical connectors)
Chipset: Q570
CPU: i5-10500T (UHD630 CoffeLake-H GT2)

After booting the screen goes black, reconnecting or changing screens doesn't help. Only using VESA driver has video output.  But even no video output I can connect via Sharescreen and looks like everything is OK 

![image](https://github.com/acidanthera/bugtracker/assets/1100134/ecbd8266-416e-4b85-ba53-d76e9b1835b9)

[EFI.zip](https://github.com/acidanthera/bugtracker/files/13661817/EFI.zip)
[opencore-2023-12-13-141014.txt](https://github.com/acidanthera/bugtracker/files/13661818/opencore-2023-12-13-141014.txt)
[System.txt](https://github.com/acidanthera/bugtracker/files/13661833/System.txt)

**Comment by andreszerocross** [comment]
Intel Chipset 5xx is not supported for Output of Display. Max support for Intel Cometlake in hackintosh with igpu is Intel 4xx.

That's the problem
