### ISSUE TITLE
[AirportBrcmFixup.kext] Wifi and Bluetooth coex needed

### ISSUE THREAD

**Issue by qasim799** [acidanthera/bugtracker#2362]
DW1820A (BCM9350) Wifi signals interfere with bluetooth resulting in packet loss while listening to BT audio and BT mouse/keyboard, choppiness and lag on 2.4Ghz please implement wifi + BT coex like in intel one here:
[Implement BT/WiFi coex, make iwm BT works more stable.](https://github.com/OpenIntelWireless/itlwm/commit/8f0a396d576ca473c679ba7396824b1b2770e5e3)
[Issue explained in detail here](https://www.reddit.com/r/hackintosh/comments/18lq0tw/dw1820a_bcm9350_bluetooth_lagging_on_ventura/)

**Comment by vit9696** [comment]
That one is for an Apple driver, not for AirportBrcmFixup, which does not work on such a low level.
