### ISSUE TITLE
OpenDuet with new secure PE/COFF loader cannot load HfsPlusLegacy.efi from OCBinaryData

### ISSUE THREAD

**Issue by wolf606** [acidanthera/bugtracker#2363]
A new secure PE/COFF loader was introduce in the 0.8.8 release of OpenCore. When using OpenDuet from the OpenCore 0.9.7 package, the firmware cannot load the latest HfsPlusLegacy.efi driver from OcBinaryData. 

Loading HfsPlusLegacy.efi in OpenDuet from the OpenCore 0.8.7 package:
![IMG_20231223_142227317_HDR](https://github.com/acidanthera/bugtracker/assets/107286189/220fb905-439f-42d0-ab87-0006059ef9e1)

Loading HfsPlusLegacy.efi in OpenDuet from the OpenCore 0.9.7 package:
![IMG_20231223_135746210_HDR](https://github.com/acidanthera/bugtracker/assets/107286189/681d19a8-0705-4868-9693-f75571f6d87c)

**Comment by mikebeaton** [comment]
@wolf606 @Lost-Entrepreneur439 Can you check that https://github.com/acidanthera/OpenCorePkg/commit/47ad1a72b09654b6720f70b21d66eac8a8055861 fixes the issue for you? Build is in https://github.com/acidanthera/OpenCorePkg/actions/runs/7346200425 (macOS XCODE5 Artifacts at the bottom of the screen, you need to be logged in to GitHub and you need to wait a moment for the Artifacts section to populate).

**Comment by EAZYBLACK** [comment]
I was also having same issue, thanks you contributor i tried the build you sent and now it loads hfspluslegacy fine

**Comment by Ampernic** [comment]
Maybe I miss-understand something in working of new versions of OC and OpenDuet , but still can boot apfs volumes (its doesn't show in picker) by hfspluslegacy without enabling apple secure boot after update from 0.9.5 to 0.9.7 in latest commit.
In release 0.9.7 version it doesn't load fully.

Is it normal?

**Comment by mikebeaton** [comment]
@Ampernic - Please provide a debug log of when this fails to load.

**Comment by Ampernic** [comment]
> @Ampernic - Please can you provide a debug log of when this fails to load and config.plist.

Yeah, sure.

[opencore-2024-01-17-180910.txt](https://github.com/acidanthera/bugtracker/files/13967144/opencore-2024-01-17-180910.txt)

[config.zip](https://github.com/acidanthera/bugtracker/files/13967162/config.zip)

**Comment by mikebeaton** [comment]
Thank you, this is helpful, please could you provide debug log from same setup when it works (only config change to make it work is SecureBootModel -> Default, correct?).

**Comment by Ampernic** [comment]
If needed log with enabled apple secure boot
[opencore-2024-01-18-072925.txt](https://github.com/acidanthera/bugtracker/files/13973689/opencore-2024-01-18-072925.txt)
With apple secure boot apfs volumes are shown in piker
![photo1705564778](https://github.com/acidanthera/bugtracker/assets/44705058/b25d03ac-b7ab-4bba-b114-bfcf301e0011)

**Comment by XRevan86** [comment]
Additionally, OpenDuet 0.8.7 is the last version that is capable of booting Linux, newer versions print out `unsupported`.

**Comment by mikebeaton** [comment]
@XRevan86 - We are not aware of this, please make a separate issue, include a debug log and config.plist.

**Comment by XRevan86** [comment]
> include a debug log and config.plist
@mikebeaton, OpenDuet 0.8.8+ is not able to boot Linux EFISTUB binaries irrespective of whether OpenCore is used at all.

**Comment by mikebeaton** [comment]
A log of it failing within OpenCore would still be helpful, as would a separate issue, please.
