### ISSUE TITLE
Support for Everest ES8316 (Matebook D15)

### ISSUE THREAD

**Issue by ArkhanDev** [acidanthera/bugtracker#2364]
Can someone add Support for Everest ES8316 Audio? There's no Support for it in AppleALC Codec Driver and I couldn't find a Driver from Everset neither. There were some people claiming that they got it to work, but the only thing I found was a broken Google Drive link on Reddit.

**Comment by perez987** [comment]
@ArkhanDev 
It is not for beginners (it's a complex task) but [here](https://github.com/5T33Z0/AppleALC-Guides) are instructions about creating layouts for Apple ALC.

**Comment by ArkhanDev** [comment]
Got it working after 3 yrs.
Apple pulling the plug anyways

was it worth it?
