### ISSUE TITLE
Driver HfsPlus.efi at 0 cannot be loaded!

### ISSUE THREAD

**Issue by Acindetheruaia** [acidanthera/bugtracker#2368]
Opencore keeps showing this issue with 1 of the 3 Opencore drivers I have .

**Comment by Acindetheruaia** [comment]
[opencore-2024-01-02-201236.txt](https://github.com/acidanthera/bugtracker/files/13855156/opencore-2024-01-02-201236.txt)

**Comment by Acindetheruaia** [comment]
Opencore 0.9.7debug

**Comment by Andrey1970AppleLife** [comment]
Driver HfsPlus.efi at 0 cannot be found!
Add HfsPlus.efi to Drivers folder. From https://github.com/acidanthera/OcBinaryData/archive/refs/heads/master.zip

**Comment by Acindetheruaia** [comment]
They are and both in my plist and efi still not working

**Comment by Andrey1970AppleLife** [comment]
Update HfsPlus.efi

**Comment by Acindetheruaia** [comment]
> Driver HfsPlus.efi at 0 cannot be found! Add HfsPlus.efi to Drivers folder. From https://github.com/acidanthera/OcBinaryData/archive/refs/heads/master.zip

It's already there

**Comment by Acindetheruaia** [comment]
From the opencore debug folder

**Comment by Acindetheruaia** [comment]
![image](https://github.com/acidanthera/bugtracker/assets/155923406/25f32e1c-30bf-471c-b487-2bac13c9a0a9)

**Comment by Acindetheruaia** [comment]
@Andrey1970AppleLife

**Comment by mikebeaton** [comment]
Please upload the entire EFI folder as a zip file to this issue. (It seems very likely that this is a user configuration issue, which is invalid for support on this bugtracker, btw.)

**Comment by Acindetheruaia** [comment]
All the steps are done as followed here's it also not config issue
https://drive.google.com/drive/folders/1vbE03zLNFPQl56JfvpmW1R9-RtsxjeCZ?usp=drive_link

**Comment by mikebeaton** [comment]
No, I believe it is still a user configuration issue. Your OpenCore.efi (and config.plist) is in the wrong subdirectory of your root EFI folder - different from where you find them in the folder structure of unzipped OpenCore release files if you examine the subfolders of X64/EFI (or IA32/EFI for 32 bit).

**Comment by Acindetheruaia** [comment]
> No, I believe it is still a user configuration issue (by which I mean to include the idea that generally it is configured wrongly, not just limited to issues in the config file as such). Your OpenCore.efi (and its config.plist) is in the wrong subdirectory of your root EFI folder - different from where you find it in the folder structure of unzipped OpenCore [release files](https://github.com/acidanthera/OpenCorePkg/releases) if you examine the subfolders of X64/EFI.

Kernal issue

**Comment by Acindetheruaia** [comment]
Kernel panic*

> Christ on a bike. The issue you raised here was because you had the OpenCore.efi file at the wrong place in your directory structure. The issue you have tried to open just now with a kernel error is some further user configuration error. You must go to forums or Reddit or Discord channels which support OpenCore (partial list [here](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/FORUMS.md)) for assistance with issues like this. Users there will be able to help you. If you persist in attempting to raise support issues on this bug tracker, you may be blocked.

Kernel panic* Also the users on discord didn't help rixrixy CorpNewt kinda but still.

**Comment by Acindetheruaia** [comment]
Also how is it a user configuration error if it's a kernel panic that isn't the users' fault and stop talking in third.

**Comment by Acindetheruaia** [comment]
Also I saw it loaded everything apart from kexts.

**Comment by Acindetheruaia** [comment]
[panic-2024-01-26-222633.txt](https://github.com/acidanthera/bugtracker/files/14073809/panic-2024-01-26-222633.txt)
