### ISSUE TITLE
OpenCore issue HfsPlus.efi at 0 cannot be found! OpenCore Debug 0.9.7

### ISSUE THREAD

**Issue by Acindetheruaia** [acidanthera/bugtracker#2370]
Version 0.9.7 Debug
Config.plist checked numerous times should be working.
Removed unnecessary kexts as suggested by rixrixy on the discord.(Also they were incompatible)
Contains all necessary kexts.
Contains Macos 12 Ventura downloaded offline and is above the EFI folder
Contains all necessary tools OpenShell.efi

Config.plist:
https://drive.google.com/file/d/1yVcm24ZVpPuUjbcYrQiYj0xhztFgqhnQ/view?usp=sharing

ACPI:
![image](https://github.com/acidanthera/bugtracker/assets/155923406/a8c9ef5e-884e-4704-84e4-e187c74028bb)

Kexts:
![image](https://github.com/acidanthera/bugtracker/assets/155923406/08a2d9e6-441b-4b0e-90c6-95b849483c93)

Logs:
[opencore-2024-01-12-231627.txt](https://github.com/acidanthera/bugtracker/files/13982329/opencore-2024-01-12-231627.txt)
[opencore-2024-01-12-234704.txt](https://github.com/acidanthera/bugtracker/files/13982330/opencore-2024-01-12-234704.txt)
[opencore-2024-01-12-235352.txt](https://github.com/acidanthera/bugtracker/files/13982331/opencore-2024-01-12-235352.txt)

The device is ASUS FX505GT I have disabled secure boot before launching the EFI
Anything else you need please respond.

**Comment by mikebeaton** [comment]
Drivers go in Drivers (/EFI/OC/Drivers) - Andrey1970AppleLife [already told you](https://github.com/acidanthera/bugtracker/issues/2368#issuecomment-1881048231) where to find the driver - this is not a [support forum](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/FORUMS.md) for assistance with incorrect user config, it is a bugtracker for bugs in OpenCore and related tools.

**Comment by Acindetheruaia** [comment]
> Drivers go in Drivers (/EFI/OC/Drivers) - Andrey1970AppleLife [already told you](https://github.com/acidanthera/bugtracker/issues/2368#issuecomment-1881048231) where to find the driver - this is not a [support forum](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/FORUMS.md) for assistance with incorrect user config, it is a bugtracker for bugs in OpenCore and related tools.

![image](https://github.com/acidanthera/bugtracker/assets/155923406/8b86ccf1-bf61-4206-af05-2192e2396983)
