### ISSUE TITLE
The name of the GNU/Linux distribution is not displayed in the OpenCore boot picker

### ISSUE THREAD

**Issue by MatteoBax** [acidanthera/bugtracker#2378]
Instead of the GNU/Linux distribution name, Other OS appears in the boot picker.
I have Debian as my GNU/Linux distribution.
![IMG20240205231917.jpg](https://github.com/acidanthera/bugtracker/assets/98881971/10e97307-7464-4852-a24d-204367ab8e72)

**Comment by mikebeaton** [comment]
Use OpenLinuxBoot.

**Comment by MatteoBax** [comment]
I already have it. It only detects the partitions and allows me to start the OS but does not show me the name of the distribution.

**Comment by mikebeaton** [comment]
I think you have bit OC_ATTR_USE_GENERIC_LABEL_IMAGE set in PickerAttributes

**Comment by MatteoBax** [comment]
Yep, it was set to 255. Now I set it to 17 and the problem is resolved. Thank you very much for helping
