### ISSUE TITLE
Bug ocvalidate 0.9.9

### ISSUE THREAD

**Issue by chris1111** [acidanthera/bugtracker#2379]
NOTE: This version of ocvalidate is only compatible with OpenCore version 0.9.9!

OpenVariableRuntimeDxe.efi is incompatible with FirmwareSettingsEntry.efi!
CheckUefi returns 1 error!

`But FirmwareSettingsEntry.efi is not set in my config.plist`

I need OpenVariableRuntimeDxe.efi for my Legacy Duet Optiplex 790

**Comment by mikebeaton** [comment]
Please provide the config.plist.

**Comment by mikebeaton** [comment]
Fixed in https://github.com/acidanthera/OpenCorePkg/commit/4314fb31ecb974c30f99ac17db1f2b67ce1bb765 .

Here is a fixed ocvalidate: [ocvalidate.zip](https://github.com/acidanthera/bugtracker/files/14206907/ocvalidate.zip)

**Comment by chris1111** [comment]
Thank you MR Beaton 👍🏻
