### ISSUE TITLE
OpenCore as a pure loader and Arm version for Raspberry Pi

### ISSUE THREAD

**Issue by CobanRamo** [acidanthera/bugtracker#2385]
a question;

Is it possible to set up OpenCore as a **"pure"** bootloader?
It's clear to me that this was designed to start a MacOS, but I mean without ACPI, Lilu & VirtualSMC etc., just for various Linux derivatives and Windows in dual boot, etc.
I think it would be a big advantage if OpenCore could also be made available to the “other” rest of the world.
As e.g. I would like to suggest that we could also **compile OpenCore as an ARM platform**, I've been looking for a decent bootloader like OpenCore for my Raspberry Pi 3,4 & 5 for a long time.
Would it also be an approach for the future, what do you think?

Greetings Coban

**Comment by Andrey1970AppleLife** [comment]
> Is it possible to set up OpenCore as a **"pure"** bootloader? It's clear to me that this was designed to start a MacOS, but I mean without ACPI, Lilu & VirtualSMC etc., just for various Linux derivatives and Windows in dual boot, etc. 

Yes

**Comment by Andrey1970AppleLife** [comment]
ARM devices not supported. Support hardly will be. But never speak never.
