### ISSUE TITLE
DW1820a always connect to 20mhz wifi 40mhz not work 

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#2390]
im in sonoma 14.4 and wifi and bt work with opencore legacy patcher :

![Screenshot 2024-03-19 at 23 04 54](https://github.com/acidanthera/bugtracker/assets/35195176/15de81df-124c-4e0c-83fe-028337dec4b9)
![Screenshot 2024-03-19 at 23 06 46](https://github.com/acidanthera/bugtracker/assets/35195176/6e250285-d187-44fa-b01f-436c1de4c7a9)
![Screenshot 2024-03-19 at 23 07 03](https://github.com/acidanthera/bugtracker/assets/35195176/4f33108d-1405-4b20-8443-a039a269a102)

i change wifi router setting to force 40mhz but still connect with 20mhz 
and ket i use :

![Screenshot 2024-03-19 at 23 09 40](https://github.com/acidanthera/bugtracker/assets/35195176/21ac2ce0-7174-4a99-8bbc-c97d05a77062)

report :
[WiFiDiagnostics_2024-03-19_23.10.16.064_macOS_MacBookPro15,4_23E214.zip](https://github.com/acidanthera/bugtracker/files/14655554/WiFiDiagnostics_2024-03-19_23.10.16.064_macOS_MacBookPro15.4_23E214.zip)

**Comment by Andrey1970AppleLife** [comment]
Apple doesn't allow to use width of 40 MHz on 2,4 GHz.

**Comment by Edwardwich** [comment]
> Apple doesn't allow to use width of 40 MHz on 2,4 GHz.

But in intel card work 
It's normal in bcm ?
