### ISSUE TITLE
DW1820a(BCM2045A0) bluetooth work laggy only way work good need tern off wifi 

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#2391]
i try BrcmPatchRAM but firmwares in this project make bluetooth work bad and i change firmwares to another 99v46 
99v46 for windows and i convert to zhx and compile BrcmPatchRAM bt work better now 
for last i try tern off wifi and bt work perfect no lag and no reconecting 
i use sonoma 14.4 wifi patch with opencore legecy patcher 
i dont know i think someting in [IO80211FamilyLegacy-v1.0.0.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/payloads/Kexts/Wifi/IO80211FamilyLegacy-v1.0.0.zip) make this problem

[BrcmPatchRAM-master(99v46) 2.zip](https://github.com/acidanthera/bugtracker/files/14706713/BrcmPatchRAM-master.99v46.2.zip)
[99V46.zip](https://github.com/acidanthera/bugtracker/files/14706718/99V46.zip)

**Comment by Andrey1970AppleLife** [comment]
If you use Wi-Fi of 2,4 GHz, it is a problem of radio interferences on bluetooth which too works for 2,4 GHz.

**Comment by Edwardwich** [comment]
> If you use Wi-Fi of 2,4 GHz, it is a problem of radio interferences on bluetooth which too works for 2,4 GHz.

yes you are right 
no way to fix that?

**Comment by Edwardwich** [comment]
yes now i try ghz bluetooth work perfect on it 
any way for fix 2.4ghz?

**Comment by Edwardwich** [comment]
and for last qustion can u push 

> i try BrcmPatchRAM but firmwares in this project make bluetooth work bad and i change firmwares to another 99v46 99v46 for windows and i convert to zhx and compile BrcmPatchRAM bt work better now for last i try tern off wifi and bt work perfect no lag and no reconecting i use sonoma 14.4 wifi patch with opencore legecy patcher i dont know i think someting in [IO80211FamilyLegacy-v1.0.0.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/payloads/Kexts/Wifi/IO80211FamilyLegacy-v1.0.0.zip) make this problem
> 
> [BrcmPatchRAM-master(99v46) 2.zip](https://github.com/acidanthera/bugtracker/files/14706713/BrcmPatchRAM-master.99v46.2.zip) [99V46.zip](https://github.com/acidanthera/bugtracker/files/14706718/99V46.zip)

and for last qustion can u push  [99V46.zip](https://github.com/acidanthera/bugtracker/files/14706718/99V46.zip) firmwares to master ?

**Comment by Edwardwich** [comment]
> Author
s

**Comment by Edwardwich** [comment]
@Andrey1970AppleLife
