### ISSUE TITLE
AUDK secure PE/COFF loader - OVMF cannot load HfsPlusLegacy.efi from OCBinaryData

### ISSUE THREAD

**Issue by wolf606** [acidanthera/bugtracker#2393]
This was an issue #2363 that was previously [solved](https://github.com/acidanthera/OpenCorePkg/commit/47ad1a72b09654b6720f70b21d66eac8a8055861#diff-b74d2dd63f71999950c18889c5006ed5c889292e94d244607578bb78aa708e0e) in the OpenDuetPkg, however it is no fixed for the OvmfPkg. 
A new secure PE/COFF loader was introduce in the 0.8.8 release of OpenCore. When compiling the OVMF from the Acidanthera UEFI Development Kit (master branch) the firmware cannot load the latest HfsPlusLegacy.efi driver from OcBinaryData.
[ovmf_serial_logs.txt](https://github.com/acidanthera/bugtracker/files/14779389/ovmf_serial_logs.txt)

**Comment by mikebeaton** [comment]
If you build OvmfPkg with flag '-D LINUX_LOADER' it will load. It relaxes the loader requirements - suitable for various Linux kernels and shims, and for this driver.
