### ISSUE TITLE
10.4 Tiger with NVIDIA G84 Tesla issue

### ISSUE THREAD

**Issue by hidem5** [acidanthera/bugtracker#2400]
I installed Mac OS X 10.4 Tiger on an old laptop with GeForce 8600M GT but cannot boot.

I installed the OS using a recovery disk image of a MacBookPro3,1 with GeForce 8600M GT.

I had to disable NVDAResman to boot.
Or IONDRVDevice in info.plist had to be changed to IOPCIDevice.
However, in both cases, graphics acceleration does not work.

I tried installing using the image that is also in the Dortania guide, but it failed to boot as well.
This image includes kexts for Tesla such as NVDANV50Hal and GeForce8xxxGLDriver.bundle
[https://archive.org/details/10.4.10-8-r-4088-acdt](https://archive.org/details/10.4.10-8-r-4088-acdt)

Is it possible to enable Tesla GPU in 10.4 Tiger with OpenCore, Whatevergreen, binary patch, etc.?

10.5.2 with Graphics Update Leopard to 14 Sonoma (10.14-10.15 dosdude patch,11-14 with OCLP root patch) is working fine with graphics acceleration.

**Comment by Andrey1970AppleLife** [comment]
Tiger is a native OS for MacBookPro3,1, write to Apple.

**Comment by hidem5** [comment]
I'm sorry for the misunderstanding.

I installed Tiger on an old Dell laptop with a GeForce 8600M GT.
using the recovery disc for MacBookPro3,1.
because it include the drivers for the GeForce 8600M GT.
