### ISSUE TITLE
Hasee 优雅X5-2021S7的ALC269声卡输出音频偏小和耳机插入时声音输出异常

### ISSUE THREAD

**Issue by lwx1901** [acidanthera/bugtracker#2402]
Hasee 优雅X5-2021S7笔记本（Ice Lake  i7-1065G7）使用的是板载ALC269音频芯片，使用alcid=37的Layout ID，内置扬声器可以工作但输出音量偏小；插入耳机时也能自动切换到耳机通道，但无声音输出，关机或重启到WINDOWS，然后再启动回到macOS,耳机就有了声音输出且音量正常，但直接重启macOS后耳机又没有了声音输出，不知道问题出在哪点？有解决方法吗？，这症状似乎与原来Hasee 精盾 KingBook X57S1的ALC256声卡芯片（alcid=70）的症状一样（同为Ice Lake  i7-1065G7）!

**Comment by mikebeaton** [comment]
> The ALC269 sound card output audio of Hasee Elegant X5-2021S7 is too small and the sound output is abnormal when headphones are plugged in.

> Hasee Elegant X5-2021S7 notebook (Ice Lake i7-1065G7) uses the onboard ALC269 audio chip and uses the Layout ID of alcid=37. The built-in speaker can work but the output volume is low; it can also automatically switch to the headphone channel when plugging in headphones. , but there is no sound output. Shut down or restart to WINDOWS, and then restart back to macOS. The headset will have sound output and the volume is normal. However, after restarting macOS directly, the headset will have no sound output. I don’t know where the problem lies? Is there any solution? , this symptom seems to be the same as the original ALC256 sound card chip (alcid=70) of Hasee KingBook X57S1 (the same is Ice Lake i7-1065G7)!

AppleALC allows users to fix sound output for their card and system, and then make pull requests to share this with other users. 

This link has a script which might help to identify what is different, when the behaviour of a sound card is different after Windows https://github.com/acidanthera/AppleALC/wiki/Dumping-processing-coefficients .
