### ISSUE TITLE
OCB: LoadImage failed - Unsupported in Hyper-V

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#2406]
Trying to boot Lion and get stuck at `OCB: LoadImage failed - Unsupported`.
[OC.zip](https://github.com/acidanthera/bugtracker/files/15458586/OC.zip)
[opencore-2024-05-27-132442.txt](https://github.com/acidanthera/bugtracker/files/15458588/opencore-2024-05-27-132442.txt)
![image](https://github.com/acidanthera/bugtracker/assets/7897244/60c3c045-ee52-4601-a396-6b7093a60bdd)

**Comment by Goldfish64** [comment]
What host OS is this? Unable to reproduce with latest releases.

**Comment by startergo** [comment]
The host OS is Windows 11 24H2. I wonder if the CPUID's EAX1 has to be set to `206C2` or `206A2`?
Steps to reproduce:
```
 .\dist\Scripts\create-virtual-machine.ps1 -name "Lion" -version 10.7 -cpu 1 -ram 4 -size 50
```

https://github.com/Qonfused/OSX-Hyper-V

**Comment by startergo** [comment]
The same error is present on 10.8, and 10.10.
10.11 works fine with the same EFI folder (`C0060200` EAX1 CPUID)

**Comment by Goldfish64** [comment]
CPUID might be too new for 10.7, all the above versions should work if spoofed to Penryn (0x010676).

**Comment by startergo** [comment]
Hmmm   CMP5,1 have westmere processors and they successfully run Snow Leopard 10.6.4 and higher. I also tested Penryn CPUID with the same result on 10.7,10.8 and 10.10.

**Comment by Goldfish64** [comment]
Looks like you are attempting DMG boots? Missed that in the provided logs initially. You'll need to ensure OpenPartitionDxe.efi is being loaded in that case, Verified I'm able to boot from a 10.7 DMG with that configuration in mind on my end.

**Comment by startergo** [comment]
Thanks `OpenPartitionDxe.efi` works as designed.
