### ISSUE TITLE
OcAppleKernelLib: Investigate MSR_MISC_PWR_MGMT (0x199) behavior on macOS 12+

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#2410]
~~macOS 15 beta 1 has writes to MSR_MISC_PWR_MGMT (0x199) completely removed.~~
No, this was removed as early as on macOS 12 beta 1, in June 2021.

It is still unsure whether this is a bug of XNU, or this was done intentionally. We shall wait for the next few betas, and if necessary, start the investigation of new XCPM routines.

As these platforms become obsolete, this issue is downgraded to low priority.

**Comment by ornulf** [comment]
Hi @PMheart 
As soon as you removed MSR_MISC_PWR_MGMT (0x199) patch OpenCore 10.0.1 my rig won't boot anymore. I can boot macOS 13,14 flawlessly with 10.0.0 but with 10.0.1 I'm stuck. You and I have had discussion about this earlier and I think this is a problem just related to my processor/mobo Xenon W 2175/Asus C422 pro/se. See this thread from 2019/Mojave.
Please give this a closer lock.
[opencore-2024-09-19-214509.txt](https://github.com/user-attachments/files/17101474/opencore-2024-09-19-214509.txt)

**Comment by ornulf** [comment]
https://www.insanelymac.com/forum/topic/335193-help-installing-mojave-on-xeon-w-2175-and-asus-ws-c422-mobo/page/9/#comment-2672019

**Comment by ornulf** [comment]
https://www.insanelymac.com/forum/topic/333229-help-installing-highsierra-on-xeon-w-2175-and-asus-ws-c422-mobo/page/6/#comment-2604204

**Comment by PMheart** [comment]
Yes, it's been a while and nice to hear from you again.

It sounds weird then, as the pattern no longer exists on macOS 12+ as I checked the kernel. I will revert it tomorrow and you can test it. Thanks.

**Comment by ornulf** [comment]
Looking forward to test!

**Comment by PMheart** [comment]
@ornulf Shall we continue the tests in private? I have sent you a private message on InsanelyMac. Thanks.
