### ISSUE TITLE
Is there any plans to integrate eGPU functionality like Kryptonite?

### ISSUE THREAD

**Issue by johnkimlove** [acidanthera/bugtracker#2413]
I really really love TB 2 MacBooks because if I want to, I can add more memory or SSD.
I'm using MBP 2015 13 inch i7 model with RX 6800 XT and Kryptonite.
Currently my OS is Monterey, because kryptonite doesn't support Ventura or Sonoma. T.T
I've heard that developer of Kryptonite recommended to integrate his works to OCLP, and I want to know there is any plans to integrate that.

Thanks!!

**Comment by Andrey1970AppleLife** [comment]
Write to Dortania https://github.com/dortania/OpenCore-Legacy-Patcher/issues
