### ISSUE TITLE
opencore 1.0 qemu could not allocate driver module memory

### ISSUE THREAD

**Issue by yzp-fish** [acidanthera/bugtracker#2416]
I’m trying to boot an OS X 10.5.6 retail dvd in a qemu-based virtual machine on a m3 Mac,
I used an open core 1.0.0 efi to boot the dvd image but it finally stuck at an error called “could not allocating driver module memory” 
Here’s the photo and the EFI folder
![IMG_2165](https://github.com/user-attachments/assets/3edf1dd7-d115-4928-98fd-ecb55f9c9f2d)

[EFI.zip](https://github.com/user-attachments/files/16416860/EFI.zip)
I could not upload log file because the debug version says “halting on critical error”

**Comment by vit9696** [comment]
Try enabling AllowRelocationBlock.
