### ISSUE TITLE
New AMD IGPU detection in Lilu breaks GCN 5 (Vega) IGPU detection

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [acidanthera/bugtracker#2424]
revert it

**Comment by ExtremeXT** [comment]
+1
AMD Ryzen iGPUs are not detected properly anymore.

**Comment by alvindimas05** [comment]
I want to kill myself when using this commit

**Comment by EAZYBLACK** [comment]
it doesnt boot anymore with this commit on amd ryzen igpu

**Comment by vit9696** [comment]
Could you please provide more details on what exactly happens on which platforms?

Also, isn't @Zormeister one of your contributors and wasn't the change coordinated with the patches for the drivers?

**Comment by vit9696** [comment]
references https://github.com/acidanthera/Lilu/pull/97

**Comment by alvindimas05** [comment]
> Could you please provide more details on what exactly happens on which platforms?
> 
> Also, isn't @Zormeister one of your contributors and wasn't the change coordinated with the patches for the drivers?

Tested on AMD hack with AMD iGPU and can't boot at all.

**Comment by vit9696** [comment]
Sorry, but this is not a support forum, but a bugtracker. Here we require more specific information on the issue. IORegistryExplorer dump would be a good start along with the hardware information.

**Comment by VisualEhrmanntraut** [comment]
@vit9696 That person has left our team since a month ago so these changes were not co-ordinated on our part. These changes make the iGPU not get detected at all at least not the Vega (GCN 5) ones (videoBuiltin is null).

**Comment by vit9696** [comment]
Right, will it make sense to revert the change and let you rework the patch as needed if at all?

**Comment by VisualEhrmanntraut** [comment]
These changes currently only make sense for detecting the older iGPUs and not these ones and their successors, as the current code was working fine. As such, currently, it is not our responsibility to support them. I guess you should revert the changes for now and probably contact Zormeister for further elaboration on what to do for legacy AMD iGPUs on this matter.

**Comment by vit9696** [comment]
I reverted the change for now. @Zormeister, could you please provide a V2 for the patch so that it does not break the existing setups please?

**Comment by Zormeister** [comment]
working on fixing it

**Comment by vit9696** [comment]
@VisualEhrmanntraut, @alvindimas05, @ExtremeXT, @EAZYBLACK, please review https://github.com/acidanthera/Lilu/pull/98.

**Comment by alvindimas05** [comment]
> @VisualEhrmanntraut, @alvindimas05, @ExtremeXT, @EAZYBLACK, please review [acidanthera/Lilu#98](https://github.com/acidanthera/Lilu/pull/98).

Alright, it's working for me now.

**Comment by Zormeister** [comment]
i confirmed that this also works on my own machine, i didn't deploy the V1 builds to it, only to the Legacy system originally.

**Comment by Sooly890** [comment]
Working on my machine, no issues.
