### ISSUE TITLE
HibernationFixup possibly broken in macOS 15 Sequoia

### ISSUE THREAD

**Issue by jozews321** [acidanthera/bugtracker#2426]
Using Lilu 1.6.8, HibernationFixup 1.5.1, macOS 15 Sequoia 24A5331b

Sleep and Hibernation work without any issues with macOS 14 Sonoma

In macOS 15 when I try to enter Sleep I get a kernel panic with HibernationFixup enabled, if I disable it I can sleep with no issue 

This is the panic that I get:
[HibernationFixupPanic.txt](https://github.com/user-attachments/files/16939643/HibernationFixupPanic.txt)

This is the Lilu and HibernationFixup debug log:
[Lilu_1.6.8_24.0.txt](https://github.com/user-attachments/files/16939652/Lilu_1.6.8_24.0.txt)

My pmset config:
![Screenshot 2024-09-09 at 10 56 21 PM](https://github.com/user-attachments/assets/db0f8f64-c331-496f-8356-7402d86cf7b9)

The boot-args used:  revpatch=sbvmm hbfx-ahbm=5 keepsyms=1 debug=0x100 alcid=11 rtcfx_exclude=80-AB -lilubetaall

**Comment by vit9696** [comment]
@lvs1974, could you give it a look please? Looks like ours indeed.

**Comment by alvindimas05** [comment]
This is broken on my machine as well and I'm using hibernatemode 25. But in my case, it didn't give any kernel panics. After boot from hibernate, my machine just restarts. After second boot, it boots like normal power up. It works on Sonoma 14.7. I'm using DiscardHibernateMap and hbfx-ahbm=1

Here is my pmset :
![Screenshot 2024-09-22 at 05 36 27](https://github.com/user-attachments/assets/f71a1e21-3e16-4309-b117-b8bfc0809539)

**Comment by lvs1974** [comment]
@jozews321 , @alvindimas05 , @vit9696 : could you upload kernel binary here, please?
I suppose sources are not available yet.

**Comment by alvindimas05** [comment]
> @jozews321 , @alvindimas05 , @vit9696 : could you upload kernel binary here, please? I suppose sources are not available yet.
> 
> And also (just to check other signatures): /System/Library/Extensions/IOPlatformPluginFamily.kext/Contents/PlugIns/X86PlatformPlugin.kext/Contents/MacOS/X86PlatformPlugin /System/Library/Extensions/AppleRTC.kext/Contents/MacOS/AppleRTC /System/Library/Extensions/IOPCIFamily.kext/IOPCIFamily

How do I get the kernel binary? Also, you can contact me in the Hackintosh Paradise Discord (My username is the same)

**Comment by jozews321** [comment]
Hello @lvs1974, here are the files requested, I'm not sure if the kexts are going to be useful as they seem to be empty without the binary 
[kernel.zip](https://github.com/user-attachments/files/17089025/kernel.zip)
According to my own attempts to fix the issue I've narrowed the panic down to the call to the original function `IOPMrootDomain_setMaintenanceWakeCalendar` of the kernel that is called in `HBFX::IOPMrootDomain_setMaintenanceWakeCalendar`. 
If I comment out the line `result = FunctionCast(IOPMrootDomain_setMaintenanceWakeCalendar, callbackHBFX->orgIOPMrootDomain_setMaintenanceWakeCalendar)(that, calendar);` and compile, the panic no longer happens and I'm able to hibernate but the only thing different that I've found so far is that the system is waking up from hibernation after the set time of standbydelaylow/high and it wasn't doing that in Sonoma with the function call working correctly.

Thanks!

**Comment by lvs1974** [comment]
[HibernationFixup-1.5.2-DEBUG.zip](https://github.com/user-attachments/files/17090089/HibernationFixup-1.5.2-DEBUG.zip)
Can anybody try this kext?

**Comment by lvs1974** [comment]
[HibernationFixup-1.5.2-DEBUG.zip](https://github.com/user-attachments/files/17090168/HibernationFixup-1.5.2-DEBUG.zip)
Could you try this kext, please?

**Comment by lvs1974** [comment]
[HibernationFixup-1.5.2-DEBUG.zip](https://github.com/user-attachments/files/17090227/HibernationFixup-1.5.2-DEBUG.zip)
Could you try this kext, please?

**Comment by jozews321** [comment]
> [HibernationFixup-1.5.2-DEBUG.zip](https://github.com/user-attachments/files/17090227/HibernationFixup-1.5.2-DEBUG.zip) Could you try this kext, please?

It panics when trying to sleep, for some reason now is not triggering the your mac restarted because of a problem thing and its thus is not giving me the panic report 
[Lilu_1.6.8_24.0.txt](https://github.com/user-attachments/files/17090573/Lilu_1.6.8_24.0.txt)

**Comment by lvs1974** [comment]
@jozews321 : do you have a kernel panic report?

**Comment by lvs1974** [comment]
[HibernationFixup-1.5.2-DEBUG_ver1.zip](https://github.com/user-attachments/files/17090646/HibernationFixup-1.5.2-DEBUG_ver1.zip)
Please try this version, I fixed symbol solving issues for 2 methods.
If panic occurs - please provide panic report.

**Comment by jozews321** [comment]
> @jozews321 : do you have a kernel panic report?

Its not generating it, I've looked into /Library/Logs/DiagnosticReports/ and /private/var/db/PanicReporter/ and nothing there, Do you know of a way to get it if its not giving it normailly?

**Comment by lvs1974** [comment]
If you use OpenCore, you can use ApplePanic = YES to get text panic reports in EFI partition.

**Comment by lvs1974** [comment]
[HibernationFixup-1.5.2-DEBUG.zip](https://github.com/user-attachments/files/17090674/HibernationFixup-1.5.2-DEBUG.zip)
NVRAM API in Lilu reports "nvram: @ failed to get IODeviceTree:/options", so this error is handled in HibernationFixup also - ver2.

**Comment by jozews321** [comment]
> [HibernationFixup-1.5.2-DEBUG_ver1.zip](https://github.com/user-attachments/files/17090646/HibernationFixup-1.5.2-DEBUG_ver1.zip) Please try this version, I fixed symbol solving issues for 2 methods. If panic occurs - please provide panic report.

After testing this, now I can sleep without issue, and because I have hbfx-ahbm=5, the system should hibernate when ac is disconnected in a maintenance wake, so I set standbydelayhigh to 20 to get maintenance wakes and if i keep the ac connected so the condition to hibernate is not met, it keeps working fine giving maintenance wakes every 20 seconds, when I try to trigger a hibernation disconnecting ac it panics, sadly no report still.

Now I'm gonna try ver2 with ApplePanic = YES

**Comment by lvs1974** [comment]
@jozews321: please also turn off dumpNvram and patch IOPCI (remove -hbfx-dump-nvram  and add -hbfx-disable-patch-pci).

**Comment by jozews321** [comment]
@lvs1974 Nice, after some testing and hibernating 3 times in a row, the kext is no longer panicking and it seems to be behaving exactly like it was in Sonoma using hbfx-ahbm=5, I haven't tested under different conditions though, here is a lilu log taken after a maintenance wake [Lilu_1.6.8_24.0.txt](https://github.com/user-attachments/files/17090866/Lilu_1.6.8_24.0.txt)

**Comment by lvs1974** [comment]
@jozews321 : Great, I will commit changes and close this ticket.

**Comment by jozews321** [comment]
> @jozews321 : Great, I will commit changes and close this ticket.
Ok, Thanks for your time!

**Comment by alvindimas05** [comment]
Works like a charm. Thanks!
