### ISSUE TITLE
Can't disable SecureBootModel with Legacy Boot OpenCore r1.0.2

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#2428]
I am using OpenCore r1.0.2 with this specifications

Motherboard : Asus P7H55M-LX
Processor : Intel Core i3 540
GPU : Asus GT 710
Boot Mode : Legacy
macOS Version : Monterey 12.7.6

If i set

DmgLoading : Signed
SecureBootModel : Default

Then system will boot fine but i need to run OCLP for activating GT 710 Acceleration Graphics

Then i set
DmgLoading : Any
SecureBootModel : Disabled

But system will crash after choose Macos Monterey partition, with debug version i got this logs in top left display "LoadImage failed - Volume Corrupt"

I upload debug boot logs.
[opencore-2024-09-21-060407.txt](https://github.com/user-attachments/files/17083642/opencore-2024-09-21-060407.txt)

**Comment by vit9696** [comment]
* DmgLoading does not affect secure boot, you can leave it as is.
* SecureBootModel does not affect OCLP, you should be able to use it with SecureBootModel set to Default.
* Most likely you have issues with System Integrity Protection and this is out if the scope of OpenCore, but rather OCLP requirements. Please ask its maintainers.

**Comment by mikebeaton** [comment]
@andreszerocross - Did you try enabling FixupAppleEfiImages in your config?

**Comment by andreszerocross** [comment]
> @andreszerocross - Did you try enabling FixupAppleEfiImages in your config?
> 
> PS Agree with @vit9696 that the GT 710 Acceleration issue sounds separate, but trying to understand why what looks like (possibly) our image loader is rejecting boot.efi.

I will try this options in next saturday, i am out of reach my old PC right now.

**Comment by TonyC5** [comment]
> * SecureBootModel does not affect OCLP, you should be able to use it with SecureBootModel set to Default.

That's a new one for me.  In my experience, a legacy hack using OCLP post-install patches to boot an unsupported version of macOS will not boot macOS if SecureBootModel is not Disabled.  Attempts to boot a legacy OCLP-patched hack with SecureBootModel=Default results in a macOS boot failure.

**Comment by andreszerocross** [comment]
> @andreszerocross - Did you try enabling FixupAppleEfiImages in your config?
> 
> PS Agree with @vit9696 that the GT 710 Acceleration issue sounds separate, but trying to understand why what looks like (possibly) our image loader is rejecting boot.efi.

Thanks for this suggestions, i tried and it success boot with 
FixupAppleEfiImages = Enabled
DmgLoading = Any
SecureBootModel = Disabled

No more "LoadImage failed - Volume Corrupt".

Can i close this??

**Comment by mikebeaton** [comment]
@andreszerocross - I've updated the documentation on `FixupAppleEfiImages` to make it clearer that it applies in cases like yours: https://github.com/acidanthera/OpenCorePkg/pull/559
