### ISSUE TITLE
Sequoia doesn't function correctly without -lilubetaall

### ISSUE THREAD

**Issue by EAZYBLACK** [acidanthera/bugtracker#2431]
The issue is that if i dont add -lilubetaall, even if all my kexts have sequoia constants, it stucks in a ramrod loop in stage 3 (it finishes like takes 5min , reboots and same thing again), adding -lilubetaall fixed it, i had also heard someone had no graphics accel without -lilubetaall

**Comment by TonyC5** [comment]
@EAZYBLACK All of my hacks boot Sequoia 15.0 and 15.1 Beta without -lilubetaall when using the latest Acidanthera kexts with Open Core 1.0.1 (Release).  If I need BluetoolFixup.kext 2.6.8 with Sequoia, I use boot-arg -btlfxbeta.

Without any information about your hack (or Mac), your version of Open Core, the version of kexts in your EFI and crash diagnostics, it may be difficult for anyone to diagnose and assist you.

**Comment by holy-dev** [comment]
> The issue is that if i dont add -lilubetaall, even if all my kexts have sequoia constants, it stucks in a ramrod loop in stage 3 (it finishes like takes 5min , reboots and same thing again), adding -lilubetaall fixed it, i had also heard someone had no graphics accel without -lilubetaall 

Could you please help me? I'm having the same issue. It's not working even with the flag.

**Comment by TonyC5** [comment]
@Krazy-Killa  Inspect the BluetoolFixup.cpp source.

**Comment by Krazy-Killa** [comment]
> @Krazy-Killa Inspect the BluetoolFixup.cpp source.

Just did. Been using `-lilubetaall` for my setup, xD.  Glad to know there's one to only enable BlueToolFixup. :)

**Comment by vedantmgoyal9** [comment]
https://github.com/acidanthera/BrcmPatchRAM/pull/33 - this fixes the need of -btlfxbeta. If someone can contact the maintainer and get it merged :)

**Comment by Andrey1970AppleLife** [comment]
> [acidanthera/BrcmPatchRAM#33](https://github.com/acidanthera/BrcmPatchRAM/pull/33) - this fixes the need of -btlfxbeta. If someone can contact the maintainer and get it merged :)

Done

**Comment by EAZYBLACK** [comment]
> @EAZYBLACK All of my hacks boot Sequoia 15.0 and 15.1 Beta without -lilubetaall when using the latest Acidanthera kexts with Open Core 1.0.1 (Release). If I need BluetoolFixup.kext 2.6.8 with Sequoia, I use boot-arg -btlfxbeta.
> 
> Without any information about your hack (or Mac), your version of Open Core, the version of kexts in your EFI and crash diagnostics, it may be difficult for anyone to diagnose and assist you.
these are the kexts
![image](https://github.com/user-attachments/assets/0096e40f-1727-4a7f-87fd-35a8890f49fa)
all lilu based kexts are updated to latest version and should work without lilubetaall
also lilubetaall is only needed to get past ramrod loop

**Comment by Sooly890** [comment]
This appears to still break. We've had reports of the whole Lilu breaking, AppleALC, WhateverGreen, and RestrictEvents, without `-lilubetaall` on Sequoia. This should be reopened, BlueToolFixup appears not to be the only broken thing here.

**Comment by Krazy-Killa** [comment]
> This appears to still break. I've seen reports of the whole Lilu breaking, AppleALC, WhateverGreen, and RestrictEvents, without `-lilubetaall` on Sequoia. This should be reopened, BlueToolFixup appears not to be the only broken thing here.

Nothing wrong with the latest versions of those kexts as they are setup to function with Sequoia.. Update your kexts.

**Comment by Sooly890** [comment]
>Nothing wrong with the latest versions of those kexts as they are setup to function with Sequoia.. Update your kexts.

I'm aware that they are setup to support Sequoia. These people are on the latest kexts.

**Comment by TonyC5** [comment]
@Sooly890  Just to clarify ... you are not experiencing this problem yourself, but you have been kind enough to observe the problem with others and are reporting it here.  Is that correct?  

Would it be possible for you to gain first-hand knowledge so that you can provide details (or tell those who are experiencing the problem to report their details here)?  Just my opinion, but hearsay without evidence isn't a reason to reopen this.

**Comment by Sooly890** [comment]
>@Sooly890 Just to clarify ... you are not experiencing this problem yourself, but you have been kind enough to observe the problem with others and are reporting it here. Is that correct?

Yes, that's correct

>Would it be possible for you to gain first-hand knowledge so that you can provide details (or tell those who are experiencing the problem to report their details here)? Just my opinion, but hearsay without evidence isn't a reason to reopen this.

Sure, I can do that (both)

**Comment by Sooly890** [comment]
Humm, actually is seems like a user error for now. The people I was referring to had some weird Kexts enabled. My bad for falsely resurrecting this.
