### ISSUE TITLE
after wake up from s4 sleep need run  sudo pkill bluetoothd for back BT to working

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#2438]
after wake up from s4 sleep need run  sudo pkill bluetoothd for back BT to working 

opencore version : 1.0.3 DEV
hibernationfixup : 1.52
BlueToolFixup : 2.6.9

after Run sudo pkill bluetoothd everything back to working 
I upload ioregistry file before use terminal  pkill bluetoothd and after that 
after 
[Ali’s MacBook Pro.ioreg.zip](https://github.com/user-attachments/files/17548153/Ali.s.MacBook.Pro.ioreg.zip)
before 
[Ali’s MacBook Pro.ioreg.zip](https://github.com/user-attachments/files/17548203/Ali.s.MacBook.Pro.ioreg.zip)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/1821
