### ISSUE TITLE
Contribution to support Intel Core Ultra (200), com Z890 and dGPU (RX 580)

### ISSUE THREAD

**Issue by luchina-gabriel** [acidanthera/bugtracker#2442]
Hi team!

I got a setup with **Gigabyte Z890 Aorus Elite X ICE** and a **Core Ultra 7 265K**.

I initially created an EFI but without any success, it gets stuck in Early Boot.

Tests I performed:

1. Different SMBIOSes (iMacPro1,1 and MacPro7,1)
2. SetupVirtualMap (True/False)
3. EnableWriteUnprotector (True/False)
4. AppleXcpmCfgLock (True/False)
5. boot-args: cpus=1

I am sending the logs generated with OPENCORE/Kexts of DEBUG and boot-args equal to "keepsyms=1 debug=0x100 -v -liludbgall liludump=60".

I am sending the compressed EFI (DEBUG), extracted SysReport, iASL Tools (acpidump -b) and Opencore Logs.

If you need any more information or tests, just let me know/guide me so I can do them and bring you the results.

Regards,
Gabriel Luchina

[iasl-win-20240927-dump-BIOS-vF10c.zip](https://github.com/user-attachments/files/17612750/iasl-win-20240927-dump-BIOS-vF10c.zip)
[SSDTTime-master.zip](https://github.com/user-attachments/files/17612751/SSDTTime-master.zip)
[SysReport.zip](https://github.com/user-attachments/files/17612752/SysReport.zip)
[EFI.zip](https://github.com/user-attachments/files/17612753/EFI.zip)
[opencore-2024-11-03-210353.txt](https://github.com/user-attachments/files/17612754/opencore-2024-11-03-210353.txt)

**Comment by ToxicMan1971** [comment]
A trash guy who uses hackintosh to make money without any knowledge.
