### ISSUE TITLE
Sophos detects ATK/Behav-321

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#2456]
```
ATK/Behav-321 detected at C:\Users\<user>\Downloads\OpenCore-1.0.3-DEBUG\IA32\EFI\OC\Drivers\*.efi
```
Sophos removes all `IA32` `EFI` drivers.

**Comment by mikebeaton** [comment]
https://github.com/acidanthera/bugtracker/issues/1363#issuecomment-743744939

**Comment by startergo** [comment]
I don't care about the IA32 drivers as I don't use them, but I don't like anything being detected by the AV. As a reference the files were downloaded straight from the acidanthera/opencore release section. Most likely of course it is a false positive.

**Comment by startergo** [comment]
Not really. I am not the admin of the Sophos on this machine, but recently it detected legitimate software from the company we represent as a malware. And that software we used for years without detection. Recently the IT increased the protection level, and this is the result.

**Comment by startergo** [comment]
If you distribute the 32 bit `EFI`'s zipped with a password that should do.

**Comment by mikebeaton** [comment]
> If you distribute the 32 bit `EFI`'s zipped with a password that should do.

We are not going to, it is a Sophos error (or possibly not, from their point of view) and a false positive. I've found several legitimate 32-bit and EFI related things that show up as false positives on my work computer, it's just the way it is.

**Comment by startergo** [comment]
A workaround: Download the zip file in a VM and extract all but the 32 bit .efi's to the main machine.
