### ISSUE TITLE
could yall make support for Steam deck OLED/LCD models (pls)

### ISSUE THREAD

**Issue by G4VSVSVSSV1** [acidanthera/bugtracker#2458]
me and couple other people tried running mac os on a steam deck it took months to figure out but we managed to do the impossible and managed to boot and install every mac os version from catalina to sequoia it was a team effort we also tested on LCD and OLED models of the steam deck too they both work. but currently the steam deck has many missing kexts WI-FI touch screen etc. and also pls add support for steam deck
![IMG_3531](https://github.com/user-attachments/assets/58893f89-76f8-4cd1-a0b5-b6bb6880b68f)
(btw this is running mac os ventura)

**Comment by G4VSVSVSSV1** [comment]
?

**Comment by dreamwhite** [comment]
This has nothing to do with OpenCorePkg devs. Wi-Fi depends on the builtin module (e.g. if it's an Intel based Wi-Fi/BT combo card, you should refer to itlwm project) as well as the touch screen (VoodooI2C may play a role here)
