### ISSUE TITLE
UEFI->Output->Resolution does not support other ratio

### ISSUE THREAD

**Issue by he110-c0de** [acidanthera/bugtracker#2460]
Hi, My monitor is 3840x2560 3:2 ratio screen, but the UEFI->Output->Resolution only has 3840x2160 ratio option.
If I fill in with 3840x2560, open core fails back to the default value.

Why does not Opencore support other ratio resolution ?

<img width="1335" alt="Screenshot 2024-12-25 at 8 31 16 PM" src="https://github.com/user-attachments/assets/0fdee7f4-03b6-49dd-8ef6-3c91fbc11508" />

**Comment by Andrey1970AppleLife** [comment]
We don't support OpenCoreConfigurator.

**Comment by he110-c0de** [comment]
It is not the problem of OpenCoreConfigurator, it's the problem of Opencore

**Comment by Andrey1970AppleLife** [comment]
It is not the problem of OpenCore, it is a problem with a Video BIOS of your video card.

**Comment by he110-c0de** [comment]
But after install MacOS or windows, my video card can work well at that resolution.
My BIOS settings does not have option to set resolution ratio.

**Comment by Andrey1970AppleLife** [comment]
Video Bios is a firmware in the video card. You need to make a patch of a firmware of your video card.

**Comment by mikebeaton** [comment]
Obtain OpenCore debug log on your setup to see a list of the resolutions which your video BIOS (GOP) supports. Those are the only resolutions you can set pre-OS, unless you obtain a patched GOP or patch it yourself.

**Comment by he110-c0de** [comment]
> Obtain OpenCore debug log on your setup to see a list of the resolutions which your video BIOS (GOP) supports. Those are the only resolutions you can set pre-OS, unless you obtain a patched GOP or patch it yourself.

this information should be recorded in the document.

**Comment by mikebeaton** [comment]
https://github.com/acidanthera/OpenCorePkg/commit/f4b7065067c5ad3ff247c818db4c51c0987b1d63
