### ISSUE TITLE
UEFI->Output->Resolution does not support other ratio

### ISSUE THREAD

**Issue by he110-c0de** [acidanthera/bugtracker#2461]
Hi, My monitor is 3840x2560 3:2 ratio screen, but the UEFI->Output->Resolution only support 16:9 ratio resolution.
If I fill in with 3840x2560 or 1920x1280, open core fails back to the default value.

Why does not Opencore support other ratio resolution ?

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/2460#issuecomment-2563275844

**Comment by he110-c0de** [comment]
Don't just close the issue, Other people may have the same problem.
The point is how to fix it.
