### ISSUE TITLE
Stuck on ASSERT line, Ryzen 5600 RX680

### ISSUE THREAD

**Issue by RysterTech** [acidanthera/bugtracker#2462]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

MB: Asrock A320M-HDV R4.0
CPU: Ryzen 5 5600
RAM: 2x16gb DDR4 3200
GPU: XFX RX 580

- Only the latest released versions of OpenCore, Lilu, and other KEXTs are supported.
- Bugreports involving Chameleon, Clover, Ozmozis or alike are not accepted.
- Include your your `EFI` directory with OpenCore.
- Include OpenCore DEBUG log (refer to `Target` in Configuration.pdf).
- Include Lilu DEBUG log (refer to `-liludbgall liludump=60` boot arguments in README).

[EFI.zip](https://github.com/user-attachments/files/18262506/EFI.zip)
[opencore-2024-12-27-113806.txt](https://github.com/user-attachments/files/18262507/opencore-2024-12-27-113806.txt)

**Comment by Andrey1970AppleLife** [comment]
Disable unnecessary UEFI drivers.
We don't support AMD CPU. Use forums for support.
