### ISSUE TITLE
VirtualSMC Documentation

### ISSUE THREAD

**Issue by esetnik** [acidanthera/bugtracker#291]
Please improve the https://github.com/acidanthera/VirtualSMC readme to include installation instructions. Most packages only provide one or more kext files in the releases section, but VirtualSMC has Drivers, dSYM, Kexts, Tools. It's unclear which need to be added to clover for proper usage.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/VirtualSMC/blob/master/Docs/FAQ.md

**Comment by esetnik** [comment]
I saw that FAQ but it doesn't have installation instructions which is why I posted this issue.

**Comment by RandomDSdevel** [comment]
The read-me doesn't specify whether or not one needs the EFI driver installed separately any more, either.

**Comment by vit9696** [comment]
* Drivers no longer exist in the package, so there is not anything to document. There is an old driver meant for use with [older OpenCore](https://github.com/acidanthera/VirtualSMC/tree/master/EfiDriver), it should still work but is no longer supported.
* Utilities are also not needed by anyone but developers and users helping developers to debug issues, so we do not see much need in documenting them.
* Sensors are covered in the FAQ.

**Comment by RandomDSdevel** [comment]
@vit9696:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Given the configuration I'm trying to set up, let's continue this discussion on the forums, starting form either [here](https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2720450) or [here](https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?do=findComment&comment=2720467).

**Comment by vit9696** [comment]
@RandomDSdevel there is little to discuss here, we do not support Clover [since September, 2019](https://github.com/acidanthera/bugtracker/issues/453). You can try using an older driver, but we basically do not care whether things work or not.
