### ISSUE TITLE
Add AMD Zen controller patches to AppleALC

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#296]
We would like to merge AppleALC patches enabling AMD Zen HDA controller support in AppleHDA.

Initially discussed here:
https://github.com/acidanthera/Lilu/pull/49

Currently the supplied patches by Ydeng (
https://github.com/acidanthera/Lilu/pull/49#issuecomment-457959772) replace NVIDIA or AMD/ATI controller with AMD Zen controller, which breaks HDMI audio, which is undesired. We should try to find a way to replace Intel controller.

If this is not possible, we may want to detect installed GPU. Also note, that Min/MaxKernel is invalid in the fork. The patches should be rewritten manually.

CC @AlGreyy.

**Comment by vit9696** [comment]
Suggested patch approach for the time being:

```
; cmp eax, 1002h -> je use_amd
3D 02 10 00 00 74
; cmp eax, 1022h -> jle use_amd
3D 22 10 00 00 7E


; use_amd code:
; mov rax, [r15] -> mov rdi, r15 -> call qword ptr [rax+0A18h]
; the call resolves to __ZN18AppleHDAController21setupAMDHostInterfaceEv, which just returns 0.
49 8B 07 4C 89 FF FF 90 18 0A 00 00
; or al, 20h -> xor ax, 1022h -> jz +4 -> xor eax, eax -> dec eax
; or will match 0x1022 and 0x1002.
; xor will set zero flag if ax became 0
; xor eax, eax & dec eax will effectively return -1
0C 20 66 35 22 10 74 04 31 C0 FF C8
```

**Comment by AlGreyy** [comment]
Superb. Working fine on Zen (1022:1457) + RX580 (1002:AAF0). Still need confirmation from a NVIDIA user.

**Comment by vit9696** [comment]
Do we know any user with such configuration? I will most likely merge the changes later today and let you handle the reports if anything goes wrong. At least I do not see the potential technical issues.

**Comment by vit9696** [comment]
Merged in AppleALC upstream. Mic and others exits — you need resources to be prepared for you, which is out of the scope of this issue.
