### ISSUE TITLE
MaciASL ACPI 6.3 support in iasl

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#297]
@Moorre, I think we should bundle iasl with ACPI 6.3 support in MaciASL 1.5.4.
The changes are really minor, and I do not want to bundle 6.2 and 6.3 at the same time. For this reason I just renamed iasl62 to be 6.3.

Could you please update iasl62 with a newer version when you think it is ready enough and we can release 1.5.4?

Also, something is wrong with your iMessage.

**Comment by Moorre** [comment]
@vit9696, Just updated iasl62 to be as ACPICA 6.3 (v.20190215)
https://github.com/acidanthera/MaciASL/commit/07a1faa0b3e5f4d0a518aef087ef417ff1b95e47

Will close this issue when we rename iasl62 --> iasl63.

**Comment by vit9696** [comment]
We should take a slightly refined route on this issue and cleanup the list of iasl compilers available in the first place.

- Delete `acpi` NSPreferences option parsing, and use some other name for compiler selection, so that it does not collide with the previous format.
- Rename compilers and remove all others (after new release): iasl-legacy ~= iasl4, iasl-stable ~=  (or rather 6.3 now), iasl-dev ~= iasl0
- Rework update download code to handle new compiler names.

@usr-sse2 could you please handle that?

**Comment by vit9696** [comment]
Implemented this myself due to many other bugs & to fit it into our next release!
