### ISSUE TITLE
The newest VoodooPS2 2.0.0 and 2.0.1 cause KernelPanic

### ISSUE THREAD

**Issue by gujiangjiang** [acidanthera/bugtracker#301]
The newest VoodooPS2 2.0.0 and 2.0.1 cause KernelPanic
https://github.com/acidanthera/VoodooPS2/releases/tag/2.0.1

**Comment by gujiangjiang** [comment]
KP info:

Anonymous UUID:       B79C8B21-A1DD-F928-7281-45E07820374A

Fri Apr 19 16:56:59 2019

*** Panic Report ***
panic(cpu 2 caller 0xffffff800c9cacb3): "A kext releasing a(n) OSString has corrupted the registry."@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4903.251.3/libkern/c++/OSObject.cpp:215
Backtrace (CPU 2), Frame : Return Address
0xffffff8200cfbb20 : 0xffffff800c3af82d 
0xffffff8200cfbb70 : 0xffffff800c4eb795 
0xffffff8200cfbbb0 : 0xffffff800c4dcf4a 
0xffffff8200cfbc20 : 0xffffff800c35cae0 
0xffffff8200cfbc40 : 0xffffff800c3af247 
0xffffff8200cfbd60 : 0xffffff800c3af093 
0xffffff8200cfbdd0 : 0xffffff800c9cacb3 
0xffffff8200cfbdf0 : 0xffffff7f8fcc3f21 
0xffffff8200cfbe20 : 0xffffff7f8fcc3c13 
0xffffff8200cfbe60 : 0xffffff7f8fcc2771 
0xffffff8200cfbe80 : 0xffffff800ca300c7 
0xffffff8200cfbf00 : 0xffffff800ca2fa27 
0xffffff8200cfbf50 : 0xffffff800ca31516 
0xffffff8200cfbfa0 : 0xffffff800c35c0ce 
      Kernel Extensions in backtrace:
         org.rehabman.voodoo.driver.PS2Controller(2.0.1)[F586ACBA-6513-301C-80EB-E945219ED4EF]@0xffffff7f8fcc2000->0xffffff7f8fcccfff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[7706F483-87AE-3F44-BCCA-09C156F4E031]@0xffffff7f8d282000

BSD process name corresponding to current thread: Unknown
Boot args: agdpmod=vit9696 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64
Kernel UUID: 4170BF94-38B6-364F-A1B0-2F7C2C30F9A9
Kernel slide:     0x000000000c000000
Kernel text base: 0xffffff800c200000
__HIB  text base: 0xffffff800c100000
System model name: MacBookPro13,3 (Mac-A5C67F76ED83108C)

System uptime in nanoseconds: 1543737436
last loaded kext at 1479977753: com.apple.filesystems.apfs	945.250.134 (addr 0xffffff7f8d812000, size 1122304)
loaded kexts:
ru.joedm.SMCSuperIO	1.0.2
org.rehabman.voodoo.driver.PS2Controller	2.0.1
com.alexandred.VoodooI2CHID	1
com.alexandred.VoodooI2C	2.1.6
org.coolstar.VoodooGPIO	1.1
as.lvs1974.RTCMemoryFixup	1.0.3
as.vit9696.SMCProcessor	1.0.2
as.lvs1974.HibernationFixup	1.2.4
as.lvs1974.AirportBrcmFixup	1.1.9
com.alexandred.VoodooI2CServices	1
xyz.racermaster.NoTouchID	1.0.1
as.vit9696.AppleALC	1.3.6
as.vit9696.WhateverGreen	1.2.7
ru.usrsse2.SMCBatteryManager	1
ru.usrsse2.SMCLightSensor	1
as.vit9696.VirtualSMC	1.0.2
as.vit9696.Lilu	1.3.5
com.apple.filesystems.apfs	945.250.134
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AirPort.BrcmNIC	1400.1.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAHCIPort	329.200.2
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleBacklight	170.12.11
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	190
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleEFINVRAM	2.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleEFIRuntime	2.1
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	530.51
com.apple.iokit.IOGraphicsFamily	530.60
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.250.6
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.250.3
com.apple.iokit.IOSCSIArchitectureModelFamily	408.250.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.CoreTrust	1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	740.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro13,3, BootROM 254.0.0.0.0, 4 processors, Intel Core i7, 2.59 GHz, 16 GB, SMC 2.38f7
Graphics: kHW_IntelHDGraphics530Item, Intel HD Graphics 530, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR4, 2133 MHz, SK Hynix, HMA41GS6AFR8N-TF
Memory Module: BANK 1/DIMM0, 8 GB, DDR4, 2133 MHz, SK Hynix, HMA41GS6AFR8N-TF
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x20), Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
Bluetooth: Version 6.0.11f4, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Integrated_Webcam_HD
USB Device: Touchscreen
USB Device: BCM2045A0
USB Device: Wireless Receiver
Thunderbolt Bus:

**Comment by usr-sse2** [comment]
Please add `keepsyms=1` boot argument and post the log again.

**Comment by gujiangjiang** [comment]
@usr-sse2 This is the kernel panic log when boot into osx.
add keepsyms=1 shows same kernel panic log on screen.

**Comment by usr-sse2** [comment]
1. Why do you have both VoodooI2C and VoodooPS2? They share much code and their usage together is not tested.
2. With `keepsyms=1` argument the log should contain function names in backtrace in addition to hexadecimal addresses.

**Comment by gujiangjiang** [comment]
@usr-sse2 
Here are the picture.
![IMG_1065](https://user-images.githubusercontent.com/13273955/56421915-701dc280-62d7-11e9-826b-556a1cb35e3b.jpg)
![IMG_1067](https://user-images.githubusercontent.com/13273955/56421916-72801c80-62d7-11e9-96c7-decf5b70cfe4.jpg)

**Comment by gujiangjiang** [comment]
@usr-sse2 I using XPS15-9550
VoodooI2C is used for TouchPad and TouchScreen and VoodooPS2 used for Keyboard.

**Comment by usr-sse2** [comment]
I see an error in VoodooPS2Controller, I'll fix it.

**Comment by gujiangjiang** [comment]
Thanks for your work.

**Comment by usr-sse2** [comment]
Try 2.0.1.1

**Comment by gujiangjiang** [comment]
@usr-sse2 
I have just tried 2.0.1.1 and it with no kernel panic but cant boot into osx.....
It stuck at apple logo in boot progress 2/3 and -v shows it stuck here.

![IMG_1072](https://user-images.githubusercontent.com/13273955/56422906-4e730a00-62dc-11e9-952a-fc239624ae37.jpg)

**Comment by usr-sse2** [comment]
Can you boot with VoodooPS2Mouse.kext and VoodooPS2Trackpad.kext removed?

**Comment by gujiangjiang** [comment]
@usr-sse2 
Boot fine when remove VoodooPS2Mouse.kext and VoodooPS2Trackpad.kext.

PS:All my test have remove **SSDT-DisableTrackpadProbe.aml**.

**Comment by gujiangjiang** [comment]
I have test more times and can confirm these:
1. The problem is VoodooPS2Trackpad.kext not VoodooPS2Mouse.kext.
2. SSDT-DisableTrackpadProbe.aml has no function to disable VoodooPS2Trackpad.kext in 2.0.X.

**Comment by usr-sse2** [comment]
I have never used configuration SSDTs myself, so I could have accidentally broken it. Disabling trackpad will be supported in the next release.

**Comment by gujiangjiang** [comment]
Ok thanks.
I think it maybe the newest VoodooPS2 using same code with VoodooI2C in touchpad driver so it maybe conflict.

**Comment by usr-sse2** [comment]
@gujiangjiang, you can try this: 
[VoodooPS2Controller.kext.zip](https://github.com/acidanthera/bugtracker/files/3103124/VoodooPS2Controller.kext.zip)
I renamed all `VoodooI2C*` classes to `VoodooPS2*` so they shouldn't conflict with ones in the VoodooI2C kexts.

**Comment by gujiangjiang** [comment]
@usr-sse2 
Thanks for your work and i test this kext just now. It works well with no conflict with VoodooI2C kexts and the keyboard works well.

Thanks.
