### ISSUE TITLE
VoodooPS2, Thinkpad T440s, 3 physical button not working

### ISSUE THREAD

**Issue by usman2006** [acidanthera/bugtracker#302]
hi,
hava an t440s with the trackpad from a t450( extra 3physical buttons).
all gestures are working fine except the three button.
in consol.log if I press on elf the three button it produce 
standard	17:20:16.553291 +0200	kernel	synaptics_parse_hw_state: finger 0 pressure 0 width 8.

thx 
[debug_2105.zip](https://github.com/acidanthera/bugtracker/files/3108267/debug_2105.zip)

**Comment by usr-sse2** [comment]
What do you mean by ‘elf’?
Does the left button work? (with default settings it should produce a Force Touch, set ForceTouchMode to 0 to make it a regular click)

Apple Magic Trackpad 2 doesn’t have a right or middle buttons, so implementing a ‘right button’ would need to simulate Control key press or a gesture depending on setting in System Preferences...

**Comment by usman2006** [comment]
"elf" should be "of".

https://i.ytimg.com/vi/0f5zNx0HLtc/maxresdefault.jpg

as you see, the left was the original trackpad. the whole trackpad is clickable but I changed it to with the extra physical buttons. it works under widows fine.

yes the "left click" is working if a tap or click with one finger any where on the trackpad surface.
and also the force touch works fine in mode 2. but the upper buttons.
I just need the left and right button work as left and right click.

with rehabman version they are working fine but then the native gesture are gone.
I know he use other way and this kext simulate mt2, but is there a way to route the buttons to mt2 simulator as left and right click.
 
thx

**Comment by usr-sse2** [comment]
OK, I’ll try to implement it.

**Comment by usman2006** [comment]
Thx

**Comment by joshuaseltzer** [comment]
I also have a T440s machine with the same exact touchpad (3 buttons) and would love to see this implemented at some point.  There are a bunch of users on this laptop who would appreciate it!

**Comment by usr-sse2** [comment]
@joshuaseltzer @usman2006 Please test physical buttons and trackpoint in this version.
(I didn’t test it at all, so make sure to backup working kexts in case this doesn’t work)
[test.zip](https://github.com/acidanthera/bugtracker/files/3489105/test.zip)

**Comment by usman2006** [comment]
@usr-sse2 
hi,
do i have make some dsdt(ssdt) change or bootarg. ?
because the physical buttons are not working for me, but they are production in log.  and unfortunately my Trackpoint is broken(it even don't work under windows but the buttons do, also with rehabman voodoops2).
I´m using through clover kext injection.
will try with lib/ext.

**Comment by Snikii** [comment]
@usr-sse2 i also wanted to point that the middle physical button in Windows is used as a vertical scroll button for TrackPoint if you keep it pressed.
So when you hold the middle click you can scroll vertically with the TrackPoint.
However it would be nice to have it as a mouse middle click button as well as it is on Windows.
My question is, is it possible to make it have both function, let's say if you hold it for 1+ sec initiate the vertical scroll function for trackPoint and a simple tap on it to work as middle mouse button for let say clicking on a link to open it on a new tab (as an example) etc.

**Comment by benbender** [comment]
@usr-sse2 your version from test.zip works on a T480 für the Trackpoint and the 3 physical buttons. It's really smooth experience and I would love to get a release-version of it without the huge amount of debugging-output. I would compile it myself but couldn't find the changes in the repo you made. Would it be possible to get one? Thanks for your hard work!

**Comment by usr-sse2** [comment]
[VoodooPS2Controller-RELEASE.zip](https://github.com/acidanthera/bugtracker/files/3583060/VoodooPS2Controller-RELEASE.zip)

**Comment by usr-sse2** [comment]
[VoodooPS2Controller-RELEASE.zip](https://github.com/acidanthera/bugtracker/files/3583060/VoodooPS2Controller-RELEASE.zip)

**Comment by Sniki** [comment]
@usr-sse2 is this another change/improved version or just the release build of last test zip kext but just release instead of debug as requested by @benbender ?

**Comment by usr-sse2** [comment]
@Sniki Just a release build of test.zip

**Comment by joshuaseltzer** [comment]
@usr-sse2 I plan on testing this kext this weekend with my T440s (3 button trackpad). I’m curious as to why the buttons work for some people but not others.

**Comment by benbender** [comment]
@usr-sse2 Works nearly perfect on a T480/8650u/WQHD-non-touch! Gestures are not as precise as on a real Mac, but that seems to be hardware-related... 

Thank you very much! Your work and help is very much appreciated! <3

**Comment by joshuaseltzer** [comment]
Just tested the release on my T440s (which has the 3-button trackpad installed).  Unfortunately none of the buttons worked.  The trackpad was a bit finicky - pressing it in was causing "long" presses or something like that, instead of normal clicks.  The bottom right secondary click seemed to work fine.  The gestures were fantastic - amazing you can do that on this hardware.  Can't wait until the buttons are fixed to take advantage of those gestures!

**Comment by silencer51** [comment]
Sadly, the version posted above doesn't seem to work on the X260/T460. Keep in mind that Lenovo uses both Alps and Synaptics made touchpads which utilize different drivers under Windows, and so might be sending different codes for button presses etc.

**Comment by usr-sse2** [comment]
@silencer51 This driver has only basic support for ALPS (without gestures), and I didn’t change anything for ALPS because I don’t have such hardware.

**Comment by silencer51** [comment]
@usr-sse2 I have a Synaptics touchpad. From what I've gathered, the T450 and T460 use the same hardware that is different from the T470-T480 (that is why this kext works with T480 but not older models).

**Comment by EchoEsprit** [comment]
Doesn't work on T450s :(

**Comment by Sniki** [comment]
Guys give this kext a try and see if Physical Buttons (Clickpad) works.
You can find it here: [# 418](https://github.com/acidanthera/bugtracker/issues/418#issuecomment-547674864)
