### ISSUE TITLE
Keypad. on Lenovo Y530 doesn't work

### ISSUE THREAD

**Issue by DogAndPot** [acidanthera/bugtracker#303]
When we use the  voodoops2controller.kext, our keypad doesn't work expect the number key with fn function, and the numlock key is identified as the key like this:
![QQ20190424-202243](https://user-images.githubusercontent.com/49340376/56659200-164e3b80-66cf-11e9-8ed1-a1b3fd7976e5.png)
 I try to set  LogScanCode to 1, but there is nothing shown in system.log, so I couldn't remap these keys.
Our present solution is using appleps2smarttouchpad.kext with dsdt hot patch, but this kext nolonger update, and it often causes kernel panic when booting.
So how can I fix our keypad with voodoops2, we all want to use voodoops2!
Thks!

**Comment by usr-sse2** [comment]
1. The option is `LogScanCodes`, not `LogScanCode`.
2. As I remember, DEBUG build always logs scan codes regardless of the setting.

**Comment by DogAndPot** [comment]
Yeah ,it is.But I couldn't find where the code is

**Comment by DogAndPot** [comment]
I can only see something when booting with verbose and press some keys, but it doesn't show anything when I press the keypad

**Comment by usr-sse2** [comment]
What is a keypad?

**Comment by DogAndPot** [comment]
The number section on keyboard, like this
![QQ20190424-205100](https://user-images.githubusercontent.com/49340376/56660713-b2c60d00-66d2-11e9-8a44-2df4bc59e6b3.png)
PS: Forgive me for my pool English

**Comment by usr-sse2** [comment]
Is it a laptop built-in keyboard, or an external PS/2 keyboard connected to a PC?

**Comment by DogAndPot** [comment]
The former. The hotpatch adds the PS2M,
 or ApplePS2SmartTouchpad can't work
![image](https://user-images.githubusercontent.com/49340376/56661365-29afd580-66d4-11e9-8626-1814ade0aea2.png)

**Comment by DogAndPot** [comment]
ApplePS2SmartTouchpad is increasingly unstable as the macos updating

**Comment by usr-sse2** [comment]
Is it Lenovo Legion Y530?

**Comment by DogAndPot** [comment]
Yes. We call it Y7000/Y7000P in China.Just the same.

**Comment by williambj1** [comment]
@usr-sse2 
Seem that the keyboard scan is broken for some reasons, it's impossible for me and many other people to get those output.

Lenovo Legion Y530 uses Fn key methods to function the number keys.

**Comment by DogAndPot** [comment]
Oh, I've made a mistake .It's numberpad, not keypad.Sorry

**Comment by xiaoMGitHub** [comment]
@usr-sse2 Please support the Y530 numeric keypad on the voodooPS2, and I can provide any data support if needed.

**Comment by xiaoMGitHub** [comment]
> Just change PS2K to PS2M and add it.Nothing else changed

I remember that direct change PS2K to PS2M will cause the keyboard to be unusable, the hotpatch you use is the same as what I wrote.

**Comment by DogAndPot** [comment]
@vit9696 Thank you for your attention.And I will provide anything you need

**Comment by chilledHamza** [comment]
@usr-sse2 @vit9696 Issue is the Num Lock key, it doesn't work. Num Lock is off at Boot and Numeric Keypad is disabled.

As for a workaround one can use [setledsmac](https://github.com/damieng/setledsmac), while the description of setledsmac states: 

> Setting the LED on or off does not affect the behavior of that key so even though the led for caps lock will be on caps lock itself will still be off. Tapping the key will cause the lock to come on but the LED will already be on so it will not appear to change. Tapping it again will turn it off (and cause the LED to turn off)

But for some reason the LED state also changes lock state of Numeric Keypad on Y530/Y7000 (possibly other similar Lenovo laptops). While Caps Lock work fine, just as stated above. LED is cosmetic and doesn't effect lock state.

I tried to debug the issue, when Num Lock key is pressed this log is generated

> VoodooPS2Keyboard: Unhandled keycode: 0x45
> ApplePS2Keyboard: sending key 45=47 down
> ApplePS2Keyboard::message: type=e3ff8066, provider=<ptr>, argument=<ptr>, argument=e8aec9df, cmp=e0028010
> ApplePS2Keyboard::message: type=e3ff806e, provider=<ptr>, argument=<ptr>, argument=e8aec9df, cmp=e0028010
> ApplePS2Keyboard: Unhandled keycode: 0x45
> ApplePS2Keyboard: sending key 45=47 up
> ApplePS2Keyboard::message: type=e3ff8066, provider=<ptr>, argument=<ptr>, argument=edbf0b1f, cmp=e0028010
> ApplePS2Keyboard::message: type=e3ff806e, provider=<ptr>, argument=<ptr>, argument=edbf0b1f, cmp=e0028010

> ApplePS2Keyboard: numLock(): 0x0, _numLock: 0x0, getLEDStatus(): 0x0 
(I added this debug statement to check if key stoke have any effect, and key stroke doesn't change Num Lock state or LED state)

I believe "sending key 45=47" means that key is recognized and relative Num Lock key event will be generated, but for some reason it doesn't change Num Lock LED state or Num Lock state.
I also checked setNumLockFeedback() Method by adding DEBUG_LOG statement and method is not called when NumLock key is pressed, while DEBUG_LOG from setAlphaLockFeedback() is working. 

I'm not sure how the Num Lock key is handled (or not sure which code is responsible for Num Lock state change), or why setNumLockFeedback() is never called.

Ended up with following workaround for now, it works for me but I think it might also break Num Lock for others ((I currently don't have any other machine to test)

> VoodooPS2Keyboard: Unhandled keycode: 0x45

Above output is generated when keyCode = keyCodeRaw = 0x45, with scanCode values of 0x45 or 0xc5

https://github.com/acidanthera/VoodooPS2/blob/6765507448327ade2c648de7e2eeb087d2d571cb/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp#L1469-L1473

>     // handle special cases
>     switch (keyCode)
>     {
>         case 0x45: // NumLock
>             
>             if (scanCode != 0xc5)
>                 setNumLock(!numLock());
>             
>             break;
>         case 0x4e:  // Numpad+
>         case 0x4a:  // Numpad- 

This little modification fixed Num Lock for me, alternatively calling setNumLockFeedback() should also work on this machine, but i think none of these is suitable solution.

So, need some help to end up with a proper solution that will work on both Legion Y530/Y7000 and won't break/cause issue on other machines (that don't have this num lock this issue). and get it merged in future release (some day, hopefully).

If you need me for logs or testing, let me know. 

PS. I didn't try ApplePS2SmartTouchpad at all, from what I remember it's closed source and won't really help with debugging the issue.

**Comment by usr-sse2** [comment]
On USB keyboards Num Lock is also translated to the Clear key, and on Apple keyboards there is no Num Lock key.

**Comment by chilledHamza** [comment]
Clear key like the delete key on Windows? It isn't working that way either, can't delete text on front side of cursor.

What do you suggest for the solution?
What do you think of above workaround, will it cause issue for other user?

**Comment by whatnameisit** [comment]
> ### Workaround
> Original code:
> 
> ```c++
>     // handle special cases
>     switch (keyCode)
>     {
>         case 0x4e:  // Numpad+
>         case 0x4a:  // Numpad- 
> ```
> 
> https://github.com/acidanthera/VoodooPS2/blob/6765507448327ade2c648de7e2eeb087d2d571cb/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp#L1469-L1473
> 
> Modified code:
> 
> ```c++
>     // handle special cases
>     switch (keyCode)
>     {
>         case 0x45: // NumLock
>             
>             if (scanCode != 0xc5)
>                 setNumLock(!numLock());
>             
>             break;
>         case 0x4e:  // Numpad+
>         case 0x4a:  // Numpad- 
> ```
> 
This works for my laptop. Samsung ATIV BOOK 2.

**Comment by vit9696** [comment]
From what I know, VoodooPS2 in general tries not to handle NumLock as there is no such thing in Apple keyboards. So it simply is not supported. Therefore I have there questions:

- Why would this break other laptops or desktops? 
- Why do you have `scanCode != 0xc5`?
- Could we have an ACPI configurable option for this code? Like `NumLockSupport`.

**Comment by chilledHamza** [comment]
Thanks for the reply.
-> Why would this break other laptops or desktops?
If it doesn't handle anything. I believe there is nothing to worry about.  I wasn't sure about this because my with my last laptop (HP Pavilion-15 AB216TX) NumLock key was working (don't have it to test anymore). So, i though may be this Lenovo Legion uses different keycode than HP or something like that.
-> Why do you have scanCode != 0xc5?
From what I remember case: 0x45 is called two times (once with scanCode value 0x45 (down), and again with 0xc5(up)). so, if 0xc5 isn't excluded, NumLock state is reverted to off as soon as you release the NumLock key.
-> Could we have an ACPI configurable option for this code? Like NumLockSupport.
Yes, that exactly what I had in mind. similar to existing ACPI patches (SSDT-Swap-CommandOption.dsl, SSDT-PrtSc-Remap.dsl, or other) that inject device property.

I would also like another similar ACPI patch (if possible), that will set NumLock to On upon boot. I have tried this by modifying code, but ACPI will be a lot better.

**Comment by vit9696** [comment]
In general the preferred way is to handle events on key up, as some keyboards may report multiple downs I believe. As for the option, I guess make a PR, and let's see how it goes. If it is optional, I do not believe there is any problem with merging it. CC @usr-sse2

**Comment by usr-sse2** [comment]
> Clear key like the delete key on Windows? It isn't working that way either, can't delete text on front side of cursor.

No, not Delete key. Clear key clears the number in Calculator. It also deletes selected text in input fields, but doesn't delete individual characters neither forward nor backward.
![Снимок экрана 2021-02-08 в 22 07 30](https://user-images.githubusercontent.com/446776/107269438-ab642500-6a5a-11eb-9944-ea364c5b0332.png)

**Comment by chilledHamza** [comment]
@usr-sse2 Thanks for explaining it, now I understand the functionality of Clear key. I also noticed when I press it at lock screen after wake from sleep (not cold-boot) it turn off the display. so, that another use case for clear key (I guess).

I can try to prepare patch for `NumLockSupport`. but is there any possible way to disable Clear key completely, when `NumLockSupport` is enabled with ACPI ?
