### ISSUE TITLE
Whatevergreen -rad24 doesn't work on CFL UHD630

### ISSUE THREAD

**Issue by williambj1** [acidanthera/bugtracker#304]
Hi! 
I want to let my Framebuffer Depth be 24-bit in order to avoid some weird issues
I tried `-rad24` to achieve it but it didn't work on CFL UHD630.
By the way, I'm sure that the **30-bit** appeared after I updated to **Mojave 10.14.4 (18E226)**
When I was using 10.14.3, the Framebuffer Depth was always 24-bit.

![image](https://user-images.githubusercontent.com/45396585/56848081-01fc7f80-6917-11e9-9526-0cf926e18aa7.png)

**Comment by vandroiy2013** [comment]
`-rad24` is only for Radeon Graphics. It didn't affect on IntelHD.
