### ISSUE TITLE
Kernel Patch for Kernel Panic failed to function on Mojave 10.14.4 (18E226)

### ISSUE THREAD

**Issue by williambj1** [acidanthera/bugtracker#305]
Hi, @vit9696 @vandroiy2013

Clover KernelToPatch for Kernel Panic failed to function on Mojave 10.14.4 (18E226)
https://applelife.ru/posts/686953

Thank you very much!

**Comment by PMheart** [comment]
Hi,

Hopefully this one works for 10.14.4 (actually even 10.13.x - 10.14.x!):
`00 8A 02 84 C0 74 -> 00 8A 02 84 C0 EB`

PMheart

**Comment by williambj1** [comment]
@PMheart 
OMG!
It works like a charm!
Thanks again!

**Comment by PMheart** [comment]
Good to hear. :)

Closing issue.
