### ISSUE TITLE
asus z390-a also asus z370-p nvme m.2 

### ISSUE THREAD

**Issue by errorexists** [acidanthera/bugtracker#306]
unable to boot on to mac os with OpenCore with either samsung nvme m.2 evo an pro models as they do not show in the boot selection but works fine with other ssd cards 
![Untitled3245](https://user-images.githubusercontent.com/23367705/56927965-5116f180-6a8a-11e9-9e21-7d17ffea2f02.jpg)

**Comment by vit9696** [comment]
Hello, please provide debug log according to the manual. Additional information about available operating systems, file systems, and installation method will be helpful.

**Comment by errorexists** [comment]
im using mojave 10.14.4 used olarila install with clover boot loader with out issues an maldon provided the openCore release an i have gone through my bios settings to make sure all is good as i am unable to do a debug as i can not see the mojave in the selector as the mojave beta is on a ssd card the ones i am trying to load are on 970 nvme evo m.2 & (pro)

**Comment by vit9696** [comment]
Use support forums please.
