### ISSUE TITLE
Third-party UEFI driver binaries

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#310]
I went through the list of the [drivers today](https://github.com/acidanthera/OpenCorePkg/commit/8f5651c83b99b43af7d174d5d768ae147a25c022) and found that there are select drivers, which we do not provide binaries for. In most cases it is not very important, but some of these drivers are either staged for deletion, or require some special configuration and patches. It is probably a good idea to handle them.

My main concern is about these drivers:

1. **DataHubDxe**,  bundled with OpenCore now, and should **not** be used. https://github.com/acidanthera/bugtracker/issues/324
2. **EnglishDxe**
3. **EnhancedFatDxe**, I wonder if we can load it from OpenCore and do the reconnect.
4. **EmuVariableRuntimeDxe**, is merged into `VariableRuntimeDxe` in edk2 tree. Yet it is still far from decent. It requires PCDs for variable size increase (our log is cut otherwise) and emulated storage. I also have no definite answer how we should handle Z390 and some other platforms, which are not capable from accessing NVRAM from within the OS. Perhaps the best approach is to implement this driver ourselves, and provide some option to transition to emulated storage after (macOS?) OS start via some variable flag, similarly to how we do for boot variables in AptioMemoryFix. https://github.com/acidanthera/bugtracker/issues/323
5. **NvmExpressDxe**
6. **XhciDxe** is is required for some rare cases where a USB 3.0 PCI card is installed and we want to boot from USB.
7. **Shell** support should also be not different from this, and I believe with the EDK II fork we can remove OpenCoreShell repository and handle Shell builds as a part of AppleSupportPkg complete build.

Another less important list I am concerned about includes the following entries:

1. **AudioDxe** I would say it is not ready, and quite dirty at the moment. So probably needs some thought later.
2. **PartitionDxe** is probably something we do not need, as ApfsDriverLoader implements this functionality manually on problematic systems. However, I wonder if OC should implement ApplePartitionInfo protocol for convenience reasons.
3. **Ps2MouseDxe** is something very confusing. @usr-sse2 reports that only Clover implementation worked for him since long ago, yet I am not sure how much attention this really needs. The driver is useful for mouse/touchpad support in FileVault 2 UI and UEFI Shell.
4. **Other filesystems**, primarily NTFS and UDF. I think Windows might format EFI partition with NTFS 0_o, but I don't know for sure.

I believe that most likely we would want all these drivers built by AppleSupportPkg repository build script, or potentially create some other repository. The former would probably be better for tracking, even though I understand that we pile a bit of stuff into AppleSupportPkg.

**Comment by roddy20** [comment]
4 Yes, XHCIDxe is required to use USB3 for OSX installer/Recovery, and yes, it works with FL1100 PCIe card.
5 Windows uses FAT32 only for EFI partition

**Comment by roddy20** [comment]
AudioDxe.efi + BootChimeDxe.efi works OK using default settings
there is no simple way to configure it without efi-shell

**Comment by savvamitrofanov** [comment]
Isn't englishdxe exist inside aptiomemoryfix?

**Comment by roddy20** [comment]
> Isn't englishdxe exist inside aptiomemoryfix?

what does EnglishDxe do in few words ?

**Comment by roddy20** [comment]
tested EmuVariableRuntimeDxe, for my configuration it does not affect "log from nvram"
just the same ten strings about CPU

**Comment by vit9696** [comment]
@savvamitrofanov it does, but I would say we will not want full AMF on legacy MBP and similar just to make UEFI shell work on them.

@roddy20 unicode collation protocol.

**Comment by roddy20** [comment]
BootChime* can be controlled by 89D4F995-67E3-4895-8F18-454B651D9215:Volume
no need to run it from shell

**Comment by vit9696** [comment]
I pushed XhciDxe description, which makes pretty good sense to me, and updated the first post with latest details concerning emulated variable storage.

Second (Less important) list looks unnecessary to myself at present, so we should focus on providing prebuilt binaries for the first.

With the NVRAM variable driver, I am kind of concerned about tianocore plans for UDK, as they started making some edk2 stable tags, and things get even more confusing, as those are hardly tested. Does anybody know of their internal plans or what should we best do with our base?

**Comment by vit9696** [comment]
Reflected the EDK II stable transition in the first post and added the information about OpenCoreShell removal in favour of implicit AppleSupportPkg compilation.

**Comment by usr-sse2** [comment]
>BootChime* can be controlled by 89D4F995-67E3-4895-8F18-454B651D9215:Volume ...

@roddy20 BootChime needs not only volume but also output device

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lupinglade** [comment]
Is PartitionDxe needed for booting macOS from CD/DVD? It seems that it will not show the installer, even though it sees a Fedora UEFI CD just fine.

**Comment by roddy20** [comment]
> Is PartitionDxe needed for booting macOS from CD/DVD? It seems that it will not show the installer, even though it sees a Fedora UEFI CD just fine.

I started a copy of Recovery partition from CD without partitiondxe
