### ISSUE TITLE
SSDT-PNLF for WhateverGreen dont work for XPS15

### ISSUE THREAD

**Issue by gujiangjiang** [acidanthera/bugtracker#312]
Today i found WhateverGreen contain a SSDT-PNLF so i tried it but failed.
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/SSDT-PNLF.dsl

However the rehabman's version works without problem.
https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-PNLF.dsl

Maybe it has some potential bugs with the new SSDT-PNLF.dsl?

XPS15-9550
HD530

**Comment by vit9696** [comment]
They are pretty much the same, except device names are different. Most likely it fails due to your ACPI patches.

**Comment by gujiangjiang** [comment]
Thanks.
I delete ACPI Patch (GFX0 to IGPU) and it works now.
