### ISSUE TITLE
MaciASL fail to open selected ACPI table in Chinese Language

### ISSUE THREAD

**Issue by stevezhengshiqi** [acidanthera/bugtracker#313]
Hi, first of all, I'd like to extend my hearty thanks to the team's hard work and great patience.

When I use MaciASL v1.5.4 to open a selected table from `.acpi` file, MaciASL would open all the tables one by one. This problem happens in Chinese Language, and English Language works well.

There are three buttons `取消`(Cancel), `全部打开`(Open all), and `打开选中项`(Open selected), and all the buttons will lead MaciASL to open all the ACPI tables.(In Simplified Chinese Language setting.)

I connected @williambj1 and we hope @vit9696 and @PMheart could help have a look at the problem, thank you.
[Sample.acpi.zip](https://github.com/acidanthera/bugtracker/files/3142581/Sample.acpi.zip)

**Comment by Andrey1970AppleLife** [comment]
And in Russian too opens all ACPI tables.

**Comment by williambj1** [comment]
![SrtingElse](https://user-images.githubusercontent.com/45396585/57907525-4d6bd300-78b0-11e9-830c-42f2b7ecc69e.jpg)

**Comment by vit9696** [comment]
Fixed in https://github.com/acidanthera/MaciASL/pull/7.
