### ISSUE TITLE
OcDebugLogLib: conversion from 'UINTN' to 'UINT32', possible loss of data

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#314]
OcSupportPkg\Library\OcDebugLogLib\OcLog.c(256): warning C4244: 'function': conversion from 'UINTN' to 'UINT32', possible loss of data
OcSupportPkg\Library\OcDebugLogLib\OcLog.c(500): warning C4244: 'function': conversion from 'UINTN' to 'UINT32', possible loss of data

**Comment by vit9696** [comment]
Resolved in master, thanks.
