### ISSUE TITLE
OcSupportPkg: some dependencies are not in .inf files

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#316]
OcMiscLib.lib(GetMemoryMap.obj) : error LNK2001: unresolved external symbol OcOverflowAddUN
OcDataHubLib.lib(OcDataHubLib.obj) : error LNK2001: unresolved external symbol OcOverflowTriAddU32
OcDebugLogLib.lib(OcLog.obj) : error LNK2001: unresolved external symbol SetFileData
OcDebugLogLib.lib(OcLog.obj) : error LNK2001: unresolved external symbol FindWritableFileSystem
OcDebugLogLib.lib(OcLog.obj) : error LNK2001: unresolved external symbol GetPerformanceCounterProperties
c:\users\public\projects\vbench\Build\OcSupportPkg\NOOPT_VS2017\X64\OcSupportPkg\Tests\CryptoTest\CryptoTestApp\DEBUG\CryptoTestApp.dll : fatal error LNK1120: 5 unresolved externals
OcMiscLib.lib(GetMemoryMap.obj) : error LNK2001: unresolved external symbol OcOverflowAddUN
OcDataHubLib.lib(OcDataHubLib.obj) : error LNK2001: unresolved external symbol OcOverflowTriAddU32
OcDebugLogLib.lib(OcLog.obj) : error LNK2001: unresolved external symbol SetFileData
OcDebugLogLib.lib(OcLog.obj) : error LNK2001: unresolved external symbol FindWritableFileSystem
OcDebugLogLib.lib(OcLog.obj) : error LNK2001: unresolved external symbol GetPerformanceCounterProperties
c:\users\public\projects\vbench\Build\OcSupportPkg\NOOPT_VS2017\X64\OcSupportPkg\Tests\CryptoTest\CryptoTest\DEBUG\CryptoTest.dll : fatal error LNK1120: 5 unresolved externals

**Comment by Download-Fritz** [comment]
Fixed at https://github.com/acidanthera/OcSupportPkg/commit/e8cfb343a519ca13342cff51a3458ff8f3eac177
Thank you for your report!
