### ISSUE TITLE
AppleHDA randomly fails to start on 10.14

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#320]
It seems that the bug in AppleHDA causing random initialisation failures got worse in 10.14. Unlike in older systems, where only misconfigured setups were affected, on 10.14 it appears a lot more frequently.

The symptoms involve not starting AppleHDADriver and AppleALC failure to obtain IOHDACodecVendorID immediately:

![Снимок экрана 2019-05-06 в 5 51 22](https://user-images.githubusercontent.com/4348897/57274654-99469d00-70a4-11e9-8a5a-f0c2daa94aa7.png)

Seemingly infinite lines in the log (when it is enabled):
```
AppleALC: alc @ failed to find IOHDACodecVendorID, retrying ХХХХХ
```

Even "failed" boots seem to have valid IOHDACodecVendorID data, however. Boot speed reduction (enabling logs) or increase (using OpenCore) makes the issue happen less or more frequently accordingly.

There is a possibility we might be able to workaround this more reliably by changing [these lines](https://github.com/acidanthera/AppleALC/blob/ea2c6d1/AppleALC/kern_alc.cpp#L651-L652) to:
```
found = appendCodec(this, codec);
```
at the cost of slower boots of misconfigured systems, but I strongly doubt it.

It may be possible that an issue exists within PCI configuration, as there exist reports of other device boot failures, e.g. AMD GPU:
<cut>
<details>
![IMG_2204](https://user-images.githubusercontent.com/4348897/57275151-479f1200-70a6-11e9-81c0-9b713a9aa3b9.jpeg)
</details></cut>

Vit: edited to include more details.

**Comment by nvmnghia** [comment]
I have the same error when installing on 10.14. It did boot after like forever, but still didn't recognize my ALC668. When I use debug mode and `-v`, the bootscreen was filled with `failed to find IOHDACodecVendorID ` lines, and I gave up waiting after X reached 300000.
