### ISSUE TITLE
AMD CPU support

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#321]
Hi !
I recently tried Opencore Bootloader on my AMD FX machine and it rebooted after i try to boot my Mojave drive from OS selection menu. 
Seems like AMD support haven't been added yet to Opencore ?

i Have found the commits from clover repo that added AMD CPU support. So please have a look.
https://sourceforge.net/p/cloverefiboot/code/2632/
https://sourceforge.net/p/cloverefiboot/code/2633/
https://sourceforge.net/p/cloverefiboot/code/2634/
https://sourceforge.net/p/cloverefiboot/code/2636/
https://sourceforge.net/p/cloverefiboot/code/4114/

Hope it helps for adding the AMD CPU support
Thank you.

**Comment by vit9696** [comment]
No automatic detection support for PlatformInfo is known. Currently to boot on AMD you will have to specify all the frequency data manually.

Some of the places for AMD changes are mentioned in OcSupportPkg status:
https://github.com/acidanthera/OcSupportPkg/blob/master/STATUS.md

We have no plans for implementing these pieces for AMD ourselves in the nearest future, so clean patches are welcome.

**Comment by vit9696** [comment]
Fixed in master.
