### ISSUE TITLE
Gigabyte Board Issue OC

### ISSUE THREAD

**Issue by MacFriedIntel** [acidanthera/bugtracker#322]
We have users with Gigabyte Boards that are reporting issues getting to boot OC with a random seed Message and not booting any further
<img width="1293" alt="Screenshot 2019-05-09 at 14 21 17" src="https://user-images.githubusercontent.com/42754234/57456597-beced480-7265-11e9-90a4-b355f16ce528.png">

This maybe something simple that users have missed, There is nothing on the forums to report this as an issue. Thanks

**Comment by vit9696** [comment]
This is not a technical issue suitable for the bug tracker. Such problems are to be discussed on the forums until technical details allowing us to confirm the existence of a bug in OpenCore. Thank you for understanding.
