### ISSUE TITLE
Create a local copy of DataHub in OcSupportPkg

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#324]
As mentioned in https://github.com/acidanthera/bugtracker/issues/323, DataHub implementation is being dropped by EDK II.

We should do the following:

- Implement our local copy as a part of OcSupportPkg.
- Ensure it does not depend on IntelFrameworkPkg headers or GUIDs. 
- Cleanup all code using IntelFrameworkPkg, notably OcSupportPkg and OpenCorePkg.
- Remove IntelFrameworkPkg references from the implementation.
- Provide DataHub support automatically when missing as a part of OpenCore.
- Provide an option to reinstall DataHub protocol, just as we do with DeviceProperties and AppleBootPolicy (optional?).

I can also add that DataHub is quite misdesigned, and if we still use it for saving logs, being able to add data to an existing DataHub entry might be a benefit. This is an optional proposal that does not line well with the existing implementations, however.

**Comment by Download-Fritz** [comment]
DataHub implemented at https://github.com/acidanthera/OcSupportPkg/commit/f7103d56f45f437a210c7a6ed9789d0c17b5de02 and https://github.com/acidanthera/OpenCorePkg/commit/14da0ac9eb6c724701761430c32723132cee5993
IntelFrameworkPkg references cleaned up at https://github.com/acidanthera/OcSupportPkg/commit/908709afd2b4771b7f5aef1bfdf6fdf235b6cc0b, https://github.com/acidanthera/OcSupportPkg/commit/e452579f7d2fbcb474db94204be4aa1209e6f8dd, https://github.com/acidanthera/AppleSupportPkg/commit/4cd6f73725125e0e7059117293d459055cf11aa4 and https://github.com/acidanthera/AptioFixPkg/commit/0ab831463cbab5e21630d2b0bdd0baa062faec6e

DataHub installation always occurs when an existing protocol cannot be found. A "ReinstallProtocol" parameter is provided in the same fashion as for OcAppleBootPolicyLib and OcDevicePropertyLib, which at this point is unconditionally FALSE in OpenCorePkg.

@vit9696 Please update the manual to remove its IntelFrameworkPkg references and provide a config option to reinstall DataHub if desired.

**Comment by vit9696** [comment]
Done in master.
