### ISSUE TITLE
Resulting log is unreadable

### ISSUE THREAD

**Issue by evansan** [acidanthera/bugtracker#325]
Test with latest commit: https://github.com/acidanthera/OpenCorePkg/commit/14da0ac9eb6c724701761430c32723132cee5993, which has  this issue.

I assume the issue is from OcSupportPkg, but I can't pin down which commit caused it. 

OpenCorePkg binaries from Github Release doesn't have this issue. 

Config + unreadable log file: 
[Archive.zip](https://github.com/acidanthera/bugtracker/files/3169389/Archive.zip)

**Comment by vit9696** [comment]
Your Debug → Target is not valid, as it contains no enable bit. There was a bug in 0.0.1, which ignored it being missing.
