### ISSUE TITLE
Not right definition of frequency of the CPU

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#326]
Acer Aspire V3-571G, insyde BIOS v2.21, CPU i7-3610QM
The bug has randomness character. 
Frequency of a CPU is very high, the interface of system responds very slowly. 
I had this bug on this computer too with Clover. But in a clover it solved: https://sourceforge.net/p/cloverefiboot/code/2668/

**Comment by vit9696** [comment]
Please try to provide IODeviceTree:/efi/platform values from both Clover and OC. From OpenCore we will need values in two states: with and without the issue. Ideally we have 2-3 examples of decent values (from Clover and OpenCore separately) and 2-3 examples when the issue does reproduce (from OpenCore).

The values in question are: ARTFrequency, CPUFrequency, InitialTSC, FSBFrequency. With OpenCore only FSBFrequency should be present.

**Comment by Andrey1970AppleLife** [comment]
I will provide it when the bug happens.

**Comment by Andrey1970AppleLife** [comment]
**OC with a bug. In "About This Mac" shows 4,3 GHz, but there shall be 2,3 GHz.**
Loading 1: 
InitialTSC <00 00 00 00 00 00 00 00>
FSBFrequency <cc 00 57 15 00 00 00 00>
Loading 2: 
InitialTSC <00 00 00 00 00 00 00 00>
FSBFrequency <5d a9 bf 15 00 00 00 00>
Loading 3: 
InitialTSC <00 00 00 00 00 00 00 00>
FSBFrequency <ce 20 6b 15 00 00 00 00>

**OC all OK**
Loading 1: 
InitialTSC <00 00 00 00 00 00 00 00>
FSBFrequency <db 6a f2 05 00 00 00 00>
Loading 2: 
InitialTSC <00 00 00 00 00 00 00 00>
FSBFrequency <89 6d f2 05 00 00 00 00>
Loading 3: 
InitialTSC <00 00 00 00 00 00 00 00>
FSBFrequency <5f 6c f2 05 00 00 00 00>

**Clover all OK**
Loading 1: 
InitialTSC <00 00 00 00 00 00 00 00>
FSBFrequency <b3 6b f2 05 00 00 00 00>
CPUFrequency <c0 eb ca 88 00 00 00 00>
Loading 2: 
InitialTSC <00 00 00 00 00 00 00 00>
FSBFrequency <b5 6a f2 05 00 00 00 00>
CPUFrequency <c0 eb ca 88 00 00 00 00>
Loading 3: 
InitialTSC <00 00 00 00 00 00 00 00>
FSBFrequency <e7 6b f2 05 00 00 00 00>
CPUFrequency <c0 eb ca 88 00 00 00 00>

**Comment by Andrey1970AppleLife** [comment]
The bug is not solved. But the bug became more rare.
