### ISSUE TITLE
CPU detection broke, showing as Unknown

### ISSUE THREAD

**Issue by Pavo-IM** [acidanthera/bugtracker#328]
Xeon E5-2670 v2 to being detected correctly. Shows up in System Preferences as Unknown.

CPU Dump attached
HW Dump attached 
OpenCore log attached
[cpu_dump.txt](https://github.com/acidanthera/bugtracker/files/3170627/cpu_dump.txt)
[hw_dump.txt](https://github.com/acidanthera/bugtracker/files/3170628/hw_dump.txt)
[opencore.log](https://github.com/acidanthera/bugtracker/files/3170629/opencore.log)

**Comment by grassybor** [comment]
SandyBridg i7-2630QM  to being detected correctly, but in the System Preferences shows up as Unknown
[CPU_Info.zip](https://github.com/acidanthera/bugtracker/files/3171653/CPU_Info.zip)
[N53SVopencoreLog.txt](https://github.com/acidanthera/bugtracker/files/3171656/N53SVopencoreLog.txt)
![Screen Shot 2019-05-13 at 11 24 54 AM](https://user-images.githubusercontent.com/1409753/57604325-afad9680-7585-11e9-992c-456de5392784.png)

**Comment by vit9696** [comment]
Fixed both issues in master.
The case with i7 revealed a bug in "Overwrite" mechanism against some firmwares, which update SMBIOS at Exit BS event. For this reason Auto is removed and Create is used instead now. For older behaviour TryOverwrite is preserved, but is not recommended.
