### ISSUE TITLE
Request to port Force Touch Implement back to VoodooI2C

### ISSUE THREAD

**Issue by gongzhenjeef** [acidanthera/bugtracker#329]
Hello, I saw the Force Touch feature is implemented in the VoodooPS2 drivers. It seems stable according to commit activities. Can you port this feature back to VoodooI2C or maybe there are some testing issues?

**Comment by vit9696** [comment]
We are done on our side by separating VoodooPS2 code into VoodooPS2 and VoodooInput. The latter can and should be used by both us and VoodooI2C. At this point it is up to VoodooI2C team on when to migrate: https://github.com/alexandred/VoodooI2C/issues/228.
