### ISSUE TITLE
Mac platform descriptions for MacInfoPkg

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#332]
Please attach database additions for [MacInfoPkg](https://github.com/acidanthera/MacInfoPkg/tree/master/DataBase) for review in this issue. Make sure that all the data is legit, and is dumped from the latest `FirmwareUpdate.pkg` or `BridgeOSUpdateCustomer.pkg`. See more details at: https://applelife.ru/posts/805975.

[AppleLife](https://applelife.ru/threads/dampy-originalnyx-makov.2943712) and [VirtualSMC](https://github.com/acidanthera/VirtualSMC/tree/master/Docs) hardware dump databases.  
[Current status table](https://docs.google.com/spreadsheets/d/1kGFz3_kp5xCDRRQpfnIUOvbiHXTmxEgyx97u73ImXXE/edit?usp=sharing) updated by @Andrey1970AppleLife.

Do **NOT** post in this issue unless you know well what you do.

**Comment by fcsd5k** [comment]
Correction MP61.
[MP61.yaml.zip](https://github.com/acidanthera/bugtracker/files/3191965/MP61.yaml.zip)

**Comment by chrome723** [comment]
[IMP11.yaml.zip](https://github.com/acidanthera/bugtracker/files/3192344/IMP11.yaml.zip)
[MBA81.yaml.zip](https://github.com/acidanthera/bugtracker/files/3192345/MBA81.yaml.zip)
[MBP151.yaml.zip](https://github.com/acidanthera/bugtracker/files/3192347/MBP151.yaml.zip)

**Comment by spidermoon-i** [comment]
[IM171.yaml.zip](https://github.com/acidanthera/bugtracker/files/3193546/IM171.yaml.zip)

**Comment by chrome723** [comment]
[MBP131.yaml.zip](https://github.com/acidanthera/bugtracker/files/3193673/MBP131.yaml.zip)
[MBP133.yaml.zip](https://github.com/acidanthera/bugtracker/files/3193674/MBP133.yaml.zip)

**Comment by BarbaraPalvin** [comment]
[MP11.yaml.zip](https://github.com/acidanthera/bugtracker/files/3193727/MP11.yaml.zip)
[MP21.yaml.zip](https://github.com/acidanthera/bugtracker/files/3193728/MP21.yaml.zip)
[MP31.yaml.zip](https://github.com/acidanthera/bugtracker/files/3193729/MP31.yaml.zip)
[MP41.yaml.zip](https://github.com/acidanthera/bugtracker/files/3193730/MP41.yaml.zip)

**Comment by chrome723** [comment]
[MBP101.yaml.zip](https://github.com/acidanthera/bugtracker/files/3194029/MBP101.yaml.zip)

**Comment by Andrey1970AppleLife** [comment]
@BarbaraPalvin 
PlatformFeature: "" is not allowed. If PlatformFeature is absent in Mac model, then delete PlatformFeature. 
Check with update_generated.py before loading here.

**Comment by vit9696** [comment]
Thanks to all contributions! I believe we were able to merge them up to this message. More files are welcome, but I request you to check the differences between committed files and your uploaded files to avoid making us fix the mistakes.

@Andrey1970AppleLife may I ask you to build some Google Sheets(?) document or something like that to contain models and their statuses, so that we see which models are done, and which still need to be added…

**Comment by Andrey1970AppleLife** [comment]
https://docs.google.com/spreadsheets/d/1kGFz3_kp5xCDRRQpfnIUOvbiHXTmxEgyx97u73ImXXE/edit?usp=sharing

**Comment by chrome723** [comment]
[MB91.yaml.zip](https://github.com/acidanthera/bugtracker/files/3217287/MB91.yaml.zip)

**Comment by Andrey1970AppleLife** [comment]
The database is filled by @kylon. Some corrections are still necessary.

**Comment by vit9696** [comment]
I merged all changes as well as some fixes from MB91.yaml. All the subsequent improvements should go through general pull request basis to MacInfoPkg repository. Thanks to everyone!
