### ISSUE TITLE
voodooPS2controller close lid sleep issue

### ISSUE THREAD

**Issue by namachari127** [acidanthera/bugtracker#334]
Not sure where/how to contact you. Your VoodooPS2Controller.kext fixes some serious issues with Thinkpad X1 Carbon (3rd) with Mojave https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x1-carbon-gen-3-2015-model-using-clover-uefi.251383/page-13#post-1956877 but seems to introduce a new issue where the Thinkpad won't sleep after the lid is closed.

**Comment by usr-sse2** [comment]
Even on my second notebook (HP ProBook 4520s) it works very bad, I know it and have no time to fix it. I won't return to the project earlier than in June.

**Comment by usr-sse2** [comment]
Does it generate some key event on lid close? You can check it in the logs with `LogScanCodes` parameter set to 1.

**Comment by namachari127** [comment]
Thanks for the reply. I'm going to revise my assessment. It does indeed seem to sleep. It just takes quite a while to activate.

**Comment by JayMonkey** [comment]
Hi Guys,

I'm also seeing the issue where the laptop wont sleep when the lid is closed.

I have 2017 HP Spectre X360 Laptop

have been using rehabmans for a few years now, but came across your fork i decided to give it a try.

Two finger scrolling is way better including coast and its nice to finally have  gestures like two finger pinch zoom working .. 

But the system will not sleep when the lid is closed with the kext installed.

I tried the hot fix SSDT-HP-FixLidSleep.aml from the repo but it does not help.

The only other issue I'm seeing is that when Secondary click is set as two fingers it does not work, which seems odd as other two finger gestures such as scroll and zoom work just fine, i'll post this as a new issue so that this one stays on topic.

Happy to provide additional info and debug if you tell me what you need.

Cheers
Jay

**Comment by JayMonkey** [comment]
Been testing the current Master Build ... 10th July 2019

Works nicely alongside VoodooIC2 now...

Still seeing lots of issue with sleep though. System will not sleep at all on lid close.

If I select sleep form Apple Icon/menu then the system does go to sleep, but on wake the trackpad no longer works, not even a reboot will bring it back, the only fix is to power off laptop and do a cold restart.

As reported above i tried installing the SSDT-HP-FixLidSleep.aml but it did not help.

two finger secondary click also not working correctly as reported here :-

[https://github.com/acidanthera/bugtracker/issues/342](url)

Cheers
Jay

**Comment by usr-sse2** [comment]
@JayMonkey, does the keyboard generate a keycode on lid close? Check with LogScanCodes=1 on DEBUG version. Try putting `e005=0` mapping into the Info.plist, I never tested using configuration SSDTs.

**Comment by JayMonkey** [comment]
> @JayMonkey, does the keyboard generate a keycode on lid close? Check with LogScanCodes=1 on DEBUG version. Try putting `e005=0` mapping into the Info.plist, I never tested using configuration SSDTs.

Hi Michael,


Pretty sure it does not but i cant say for 100%, I have never had an issue with sleep when using rehabmans version of VoodooPS2Controller.

Also the fact the trackpad is un-responsive after a manually induced sleep (Apple menu -> Sleep) that will not clear until the system is power cycled would suggest to me something more complex going on. 

having said that I will try putting e005=0 mapping into the Info.plist on my next round of testing and let you know.

Cheers
Jay

**Comment by JayMonkey** [comment]
Hi Michael,

Just tested the latest master build, as far as i can tell lid close does not generate a key press (tested with debug version).

I tried adding e005=0 as a Custom PS2 Map to the info.plist in the VoodooPS2Keyboard.kext but it did not help.

Issue Summary:-

On lid close system does not sleep.

Forced sleep via Apple Icon -> Sleep ... System sleeps ok but on wake clickpad is dead/un-responsive, a reboot does not help to bring it back, requires power cycle in order for clickpad to work again. 

No issues with sleep when using reahabmans version of VoodooPS2Controller.

Cheers
Jay

**Comment by JayMonkey** [comment]
Hi Guys,

Happy to report that with the new public release of VoodooPS2Controller (V2.0.2) the lid sleep issue i was experiencing seems to have been resolved ... have been running with it for around an hour or so and have been through several sleep/wake instances and so far it's looking good.

Will run it for a few days and report back on stability, any new issues ...

Great job with this new point release ....

Cheers
Jay

**Comment by JayMonkey** [comment]
Update on VoodooPS2 v2.0.2 after a few days of testing.

On the whole its stable and works well, however there still seems to be an issue with sleep, whilst the system does now sleep when the lid is closed, it seems that the kext is causing excessive battery drain when sleeping. 

More than once i've come back to the laptop only to find that the battery is flat. Annoyingly It does not happen all the time but it's happening enough that for now I'll have to go back to rehabman's version which does not cause the issue.

I tried adding e005=0 as a Custom PS2 Map to the info.plist in the VoodooPS2Keyboard.kext but it did not help.

I got another HP Spectre X360 user to try VoodooPS2 and they also reported the same issue :-

https://www.tonymacx86.com/threads/spectre-x360-trackpad-and-keyboard-not-working-install-hangs.282063/post-1994347

Happy to help in any way I can to debug this issue, please let me know what you need.

Cheers
Jay


Have 

 i've found the laptop had its battery drained

**Comment by readtedium** [comment]
Confirming the issue on my end, though I haven’t had a chance to test it in depth. (I’m the commenter on the thread Jay just shared.) I would find after closing the laptop for an hour it was still warm and it had lost about 10 percent of its battery life. I needed it for work so I ended up switching back to the old kext, but when I get more time I’ll do more testing.

**Comment by usr-sse2** [comment]
@readtedium @JayMonkey Try this. It puts touchpad to sleep.
But Rehabman’s VoodooPS2Trackpad doesn’t do this either, so I don’t know why is there some difference.
[VoodooPS2Controller-2.0.2-RELEASE.zip](https://github.com/acidanthera/bugtracker/files/3502723/VoodooPS2Controller-2.0.2-RELEASE.zip)

**Comment by JayMonkey** [comment]
@usr-sse2,

Thanks for this latest test release ...
Will install and run for a few days and let you know if it resolves the issue.

Cheers
Jay

**Comment by readtedium** [comment]
Just tried it last night, with no luck. I had the laptop closed for an hour and a half and I lost about 25 percent of my battery. Then switched back to RehabMan’s and had it closed for the same amount of time, and it didn’t drain. That makes me think that it’s not sleeping at all. Thanks for trying it @usr-sse2, I’ll keep experimenting on my end.

**Comment by usr-sse2** [comment]
@readtedium Why do you need to 'think' if the laptop is sleeping or not? What about the power LED, fan noise or network reachability (ping)?

**Comment by JayMonkey** [comment]
> Just tried it last night, with no luck. I had the laptop closed for an hour and a half and I lost about 25 percent of my battery. 

@readtedium.

When you close the lid look at the power LED, if laptop enters sleep mode then it should start to flash after 30 seconds or so. If power LED remains on then laptop is not entering sleep state.

This is the issue i had all the time with the previous build 2.0.11, however with 2.0.2 the system now seems to be entering sleep state (LED flashing) although it does seem to take longer (60 seconds +) with the latest public release version of VoodooPS2 unlike rehabmans build which sleeps in less than 30 seconds.

have only just installed this latest test version so will report on what i find soon ..

Cheers
Jay

**Comment by readtedium** [comment]
@usr-sse2 @JayMonkey Without looking specifically at LED flashing—will take a look soon—I will say it’s warm to the touch when I pick it up after it’s closed when using this kext, which it doesn’t get using the old one.

**Comment by JayMonkey** [comment]
@usr-sse2.

24 hours into testing the test release you posted above ..
So far I haven't seen any excessive battery drain when sleeping or no sleep on lid close issues.

The strange cursor/trackpad 'glitching' that I wrote about above after wake from sleep when using the public release of 2.0.2 also seems to have gone.

Based on the last 24 hours of testing  I would have to say that this is the most stable and usable version of VoodooPS2 you have released to date.

The only notable lacking feature is that four finger gestures don't seem to work, rehabman's version allowed the use of a four finger swipe up/down which i believed generated a combo-key-press. By default it maximised/normalised the current active window.

It's not really an issue for me as having working multiple two and three finger gestures is way more useful than having the one four-finger gesture that rehabman's version supported. But am reporting it as a possible issue for completeness.

Will continue to test this version and report any further issues or observations.

Cheers
Jay

**Comment by JayMonkey** [comment]
@usr-sse2 

Good news .. have been using the test version of VoodooPS2 that you posted 7 comments above for over four days now and have not had any problems with sleep/wake or glitchy trackpad after wake so the fix of putting the Trackpad to sleep really does seems to have improved things significantly - at least for me.

The only minor issues i've seen so far is that four finger gestures don't seem to work on my trackpad (which i can live without) and two finger secondary tap/click can be sometimes be a little temperamental (sometimes it takes 4 or 5 attempts) but usually it works  ok.

Thanks for all your hard work on this ...

Cheers
Jay

**Comment by JayMonkey** [comment]
VoodooPS2 just keeps getting better and better ...

One thing i wanted to report was that since switching to the test release 2.0.2 that @usr-sse2 posted about 8 comments up I have not seen the issue where the trackpad became unresponsive.

When using RehabMans version every once in a while (maybe once every few weeks) the trackpad would be unresponsive after a wake from sleep and the only way to get it working was to reboot.

Since running 2.0.2 test release i've not seen this issue .. so it looks like that issue has been finaly resolved. I suspect that it may have something to do with the updated sleep code ...

have just Updated to the 2.0.3 release of VoodooPS2 ... two finger tap and press click seem to be much more responsive as do gestures ...

Nice work guys 
Cheers
Jay

**Comment by chiccheung** [comment]
For my machine, the brightness is minimized when the lid is closed for the first time, as if the brightness reduction button was pressed continuously. Open the lid and wake up, and return to normal after the lid is closed.

**Comment by chiccheung** [comment]
By the way, my FN function key seems to be blocked. The F3/F4 button corresponds to the brightness adjustment function, but when I use the button record of the voodooPS2controller, I only get feedback such as e001=80. The two keys (F3, F4) are like this. I don't know if the sleep problem is related to this.
F6, F7 work fine, they are used to adjust the sound.

**Comment by chiccheung** [comment]
@usr-sse2  Is it helpful to solve the problem? I only use the keyboard plugin, the touchpad is i2c, and its multi-finger support is better.

**Comment by usr-sse2** [comment]
@chiccheung Please move your comments to a new issue.

**Comment by chiccheung** [comment]
> @chiccheung Please move your comments to a new issue.


OK，i'll do it.

**Comment by vit9696** [comment]
Is that still an issue? From what I remember, the problem of sleep failure was not directly related to the trackpad driver, so I want to close this.

**Comment by JayMonkey** [comment]
@vit9696,

I haven't seen the issue in 2020 ...  so ok to close from me.

**Comment by readtedium** [comment]
Same. I ultimately figured out that it was a result of it being plugged in via USB-C, and the issue didn't appear when it was unplugged.
