### ISSUE TITLE
Use REV booter key to set VSMC RVUF and RVBF keys for improved consistency

### ISSUE THREAD

**Issue by ctich** [acidanthera/bugtracker#339]
**Now:**
[REV ] type [{rev] 7B726576 len [ 6] attr [90] -> 02410F000001
[RVBF] type [{rev] 7B726576 len [ 6] attr [90] -> 02280F000007
[RVUF] type [{rev] 7B726576 len [ 6] attr [90] -> 02280F000007

**Must  be:**
[REV ] type [{rev] 7B726576 len [ 6] attr [90] -> 02410F000001
[RVBF] type [{rev] 7B726576 len [ 6] attr [90] -> 02410F000001
[RVUF] type [{rev] 7B726576 len [ 6] attr [90] -> 02410F000001

**Comment by vit9696** [comment]
Should also drop predefined model-specific keys, as OC is a better place for them.

**Comment by vit9696** [comment]
Should also drop predefined model-specific keys, as OC is a better place for them.

**Comment by vit9696** [comment]
@ctich fixed in master, check in all generations 1~3, and close the issue.

**Comment by ctich** [comment]
Thanks, now is correct.
