### ISSUE TITLE
VooDooPS2 conflict VoodooI2C

### ISSUE THREAD

**Issue by alexlipe** [acidanthera/bugtracker#341]
hi,  i saw the issues #301 ,i have same error. 
so i use the file which in that issues. but still cause KernelPanic.

when i  block VoodooPS2Trackpad.kext and use args: -V debug=0x100  can boot.
but without -V debug=0x100  or just with -V , still cause KernelPanic.

**Comment by vit9696** [comment]
No logs provided, closing as invalid.
