### ISSUE TITLE
VooDooPS2 2.0.1.1 conflict VoodooI2C 2.1.6

### ISSUE THREAD

**Issue by alexlipe** [acidanthera/bugtracker#343]
First, sorry for last message . I'm in office ,so , not logs. sorry.   now ,I post new issues with log

hi, i saw the issues #301 ,i have same error.
so i use the file which in that issues. but still cause KernelPanic.

when i block VoodooPS2Trackpad.kext and use args: -V debug=0x100 can boot.
but without -V debug=0x100 or just with -V , still cause KernelPanic.

<details>
 <summary>*** Panic Report *** </summary>

```
panic(cpu 4 caller 0xffffff80094db92d): Kernel trap at 0xffffff7f8d356953, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x000000001efbf000, CR4: 0x00000000003626e0
RAX: 0xffffff8009c10080, RBX: 0xffffff8039b50120, RCX: 0xffffff803accb080, RDX: 0xffffff803b07e200
RSP: 0xffffff81f9433eb0, RBP: 0xffffff81f9433eb0, RSI: 0x0000000000000000, RDI: 0x0000000000000000
R8:  0xffffff803b13c9e8, R9:  0x000000000000001f, R10: 0xffffff8009ca38f8, R11: 0x0000000000000000
R12: 0xffffff803accb0d0, R13: 0xffffff803accb0d8, R14: 0xffffff803b07e200, R15: 0xffffff803accb080
RFL: 0x0000000000010246, RIP: 0xffffff7f8d356953, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 0, VF: 1

Backtrace (CPU 4), Frame : Return Address
0xffffff81f9433980 : 0xffffff80093aea2d 
0xffffff81f94339d0 : 0xffffff80094e9e95 
0xffffff81f9433a10 : 0xffffff80094db70a 
0xffffff81f9433a80 : 0xffffff800935bb40 
0xffffff81f9433aa0 : 0xffffff80093ae447 
0xffffff81f9433bc0 : 0xffffff80093ae293 
0xffffff81f9433c30 : 0xffffff80094db92d 
0xffffff81f9433da0 : 0xffffff800935bb40 
0xffffff81f9433dc0 : 0xffffff7f8d356953 
0xffffff81f9433eb0 : 0xffffff8009a2b98a 
0xffffff81f9433f00 : 0xffffff8009a2e76b 
0xffffff81f9433f50 : 0xffffff8009a30316 
0xffffff81f9433fa0 : 0xffffff800935b0ce 
      Kernel Extensions in backtrace:
         org.rehabman.voodoo.driver.PS2Controller(2.0.1)[A392F369-E660-32CE-8E74-3ACF0915BCE3]@0xffffff7f8d354000->0xffffff7f8d35efff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[D039545F-9B61-3B0D-8F90-CCCAE5BD7A52]@0xffffff7f8a285000

BSD process name corresponding to current thread: Unknown
Boot args: dart=0 -v 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
Kernel UUID: 7C8BB636-E593-3CE4-8528-9BD24A688851
Kernel slide:     0x0000000009000000
Kernel text base: 0xffffff8009200000
__HIB  text base: 0xffffff8009100000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)

System uptime in nanoseconds: 2340338955
last loaded kext at 1936179866: com.apple.driver.AppleActuatorDriver	2450.1 (addr 0xffffff7f8c8f5000, size 61440)
loaded kexts:
com.alexandred.VoodooI2CHID	1
com.insanelymac.RealtekRTL8111	2.2.1
com.alexandred.VoodooI2C	2.1.6
org.coolstar.VoodooGPIO	1.1
org.rehabman.voodoo.driver.PS2Controller	2.0.1
org.rehabman.driver.AppleSmartBatteryManager	1.90.1
com.alexandred.VoodooI2CServices	1
com.hieplpvip.AppleBacklightFixup	1.0.2
org.netkas.driver.FakeSMC	1800
xyz.racermaster.NoTouchID	1.0.1
as.vit9696.WhateverGreen	1.2.8
as.lvs1974.AirportBrcmFixup	2.0.0
as.vit9696.AppleALC	1.3.7
com.rehabman.driver.USBInjectAll	0.7.1
as.lvs1974.HibernationFixup	1.2.5
as.vit9696.Lilu	1.3.5
com.apple.driver.AppleTopCaseHIDEventDriver	138.3
com.apple.filesystems.apfs	945.260.7
com.apple.driver.AirPort.Brcm4360	1400.1.1
com.apple.driver.AirPort.BrcmNIC	1400.1.1
com.apple.driver.AppleAHCIPort	329.260.5
com.apple.private.KextAudit	1.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleBacklight	170.12.11
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	201
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleActuatorDriver	2450.1
com.apple.driver.AppleHSBluetoothDriver	138.3
com.apple.driver.IOBluetoothHIDDriver	6.0.12f1
com.apple.iokit.IOBluetoothFamily	6.0.12f1
com.apple.driver.AppleMultitouchDriver	2450.1
com.apple.driver.AppleInputDeviceSupport	2440.2
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IOAHCIBlockStorage	301.260.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	530.51
com.apple.iokit.IOGraphicsFamily	530.66
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.260.3
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.250.3
com.apple.iokit.IOSCSIArchitectureModelFamily	408.250.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.CoreTrust	1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	740.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0
```
</details>

**Comment by vit9696** [comment]
`keepsyms=1` boot arg is your friend, please redo the panic log. Also use `<cut>` and code (three accents in a row) tag to avoid posting long sheets of text in the issue. It will be nice if you update your first post as well.

**Comment by alexlipe** [comment]
ok, I tried it again

<cut>

*** Panic Report ***
panic(cpu 6 caller 0xffffff801d0db92d): Kernel trap at 0xffffff7fa0f56953, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x0000000032bbf000, CR4: 0x00000000003626e0
RAX: 0xffffff801d8112c0, RBX: 0xffffff804d7d5ea0, RCX: 0xffffff804e94c000, RDX: 0xffffff804ed0c200
RSP: 0xffffff820d0dbeb0, RBP: 0xffffff820d0dbeb0, RSI: 0x0000000000000000, RDI: 0x0000000000000000
R8:  0xffffff804ee38fe8, R9:  0x000000000000001f, R10: 0xffffff804d7d5ea0, R11: 0x0000000000000000
R12: 0xffffff804e94c050, R13: 0xffffff804e94c058, R14: 0xffffff804ed0c200, R15: 0xffffff804e94c000
RFL: 0x0000000000010246, RIP: 0xffffff7fa0f56953, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x6, PL: 0, VF: 1

Backtrace (CPU 6), Frame : Return Address
0xffffff820d0db980 : 0xffffff801cfaea2d mach_kernel : _handle_debugger_trap + 0x47d
0xffffff820d0db9d0 : 0xffffff801d0e9e95 mach_kernel : _kdp_i386_trap + 0x155
0xffffff820d0dba10 : 0xffffff801d0db70a mach_kernel : _kernel_trap + 0x50a
0xffffff820d0dba80 : 0xffffff801cf5bb40 mach_kernel : _return_from_trap + 0xe0
0xffffff820d0dbaa0 : 0xffffff801cfae447 mach_kernel : _panic_trap_to_debugger + 0x197
0xffffff820d0dbbc0 : 0xffffff801cfae293 mach_kernel : _panic + 0x63
0xffffff820d0dbc30 : 0xffffff801d0db92d mach_kernel : _kernel_trap + 0x72d
0xffffff820d0dbda0 : 0xffffff801cf5bb40 mach_kernel : _return_from_trap + 0xe0
0xffffff820d0dbdc0 : 0xffffff7fa0f56953 org.rehabman.voodoo.driver.PS2Controller : __ZN18ApplePS2Controller19notificationHandlerEPvP9IOServiceP10IONotifier + 0xb
0xffffff820d0dbeb0 : 0xffffff801d62b98a mach_kernel : __ZN9IOService14invokeNotifierEP18_IOServiceNotifier + 0xea
0xffffff820d0dbf00 : 0xffffff801d62e76b mach_kernel : __ZN9IOService14doServiceMatchEj + 0x21b
0xffffff820d0dbf50 : 0xffffff801d630316 mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x1a6
0xffffff820d0dbfa0 : 0xffffff801cf5b0ce mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         org.rehabman.voodoo.driver.PS2Controller(2.0.1)[A392F369-E660-32CE-8E74-3ACF0915BCE3]@0xffffff7fa0f54000->0xffffff7fa0f5efff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[D039545F-9B61-3B0D-8F90-CCCAE5BD7A52]@0xffffff7f9de85000

BSD process name corresponding to current thread: Unknown
Boot args: dart=0 -v keepsyms=1 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
Kernel UUID: 7C8BB636-E593-3CE4-8528-9BD24A688851
Kernel slide:     0x000000001cc00000
Kernel text base: 0xffffff801ce00000
__HIB  text base: 0xffffff801cd00000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)

System uptime in nanoseconds: 2378631495
last loaded kext at 1922520361: com.apple.driver.AppleActuatorDriver	2450.1 (addr 0xffffff7fa04f5000, size 61440)
loaded kexts:
com.alexandred.VoodooI2CHID	1
com.insanelymac.RealtekRTL8111	2.2.1
com.alexandred.VoodooI2C	2.1.6
org.coolstar.VoodooGPIO	1.1
org.rehabman.voodoo.driver.PS2Controller	2.0.1
org.rehabman.driver.AppleSmartBatteryManager	1.90.1
com.alexandred.VoodooI2CServices	1
com.hieplpvip.AppleBacklightFixup	1.0.2
org.netkas.driver.FakeSMC	1800
xyz.racermaster.NoTouchID	1.0.1
as.vit9696.WhateverGreen	1.2.8
as.lvs1974.AirportBrcmFixup	2.0.0
as.vit9696.AppleALC	1.3.7
com.rehabman.driver.USBInjectAll	0.7.1
as.lvs1974.HibernationFixup	1.2.5
as.vit9696.Lilu	1.3.5
com.apple.driver.AppleTopCaseHIDEventDriver	138.3
com.apple.filesystems.apfs	945.260.7
com.apple.driver.AirPort.Brcm4360	1400.1.1
com.apple.driver.AirPort.BrcmNIC	1400.1.1
com.apple.driver.AppleAHCIPort	329.260.5
com.apple.private.KextAudit	1.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleBacklight	170.12.11
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	201
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleActuatorDriver	2450.1
com.apple.driver.AppleHSBluetoothDriver	138.3
com.apple.driver.IOBluetoothHIDDriver	6.0.12f1
com.apple.iokit.IOBluetoothFamily	6.0.12f1
com.apple.driver.AppleMultitouchDriver	2450.1
com.apple.driver.AppleInputDeviceSupport	2440.2
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IOAHCIBlockStorage	301.260.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	530.51
com.apple.iokit.IOGraphicsFamily	530.66
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.260.3
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.250.3
com.apple.iokit.IOSCSIArchitectureModelFamily	408.250.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.CoreTrust	1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	740.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF

</cut>

**Comment by vit9696** [comment]
Thanks for the panic log, we will check it out as time permits.

For spoilers I gave you some slightly misleading info. See: https://github.com/dear-github/dear-github/issues/166#issuecomment-236342209

**Comment by vit9696** [comment]
This bug was fixed in master and did not land in 2.0.1.1 as per commit log:
https://github.com/acidanthera/VoodooPS2/compare/2.0.1.1...master
Recompile VoodooPS2 from source to fix it.

**Comment by alexlipe** [comment]
@vit9696  hi , I think the bug may be not fix .  I clone the repo ,and use Xcode build it. but still cause KernelPanic....

<details>
<summary>*** Panic Report ***</summary>

```
panic(cpu 4 caller 0xffffff801b0db92d): Kernel trap at 0xffffff7f9ee80953, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x0000000030ae0000, CR4: 0x00000000003626e0
RAX: 0xffffff801b810080, RBX: 0xffffff804b7b3090, RCX: 0xffffff804c922100, RDX: 0xffffff804ccea200
RSP: 0xffffff820afdbeb0, RBP: 0xffffff820afdbeb0, RSI: 0x0000000000000000, RDI: 0x0000000000000000
R8:  0xffffff804ce11bc8, R9:  0x000000000000001f, R10: 0xffffff804b7b3090, R11: 0x0000000000000000
R12: 0xffffff804c922150, R13: 0xffffff804c922158, R14: 0xffffff804ccea200, R15: 0xffffff804c922100
RFL: 0x0000000000010246, RIP: 0xffffff7f9ee80953, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 0, VF: 1

Backtrace (CPU 4), Frame : Return Address
0xffffff820afdb980 : 0xffffff801afaea2d mach_kernel : _handle_debugger_trap + 0x47d
0xffffff820afdb9d0 : 0xffffff801b0e9e95 mach_kernel : _kdp_i386_trap + 0x155
0xffffff820afdba10 : 0xffffff801b0db70a mach_kernel : _kernel_trap + 0x50a
0xffffff820afdba80 : 0xffffff801af5bb40 mach_kernel : _return_from_trap + 0xe0
0xffffff820afdbaa0 : 0xffffff801afae447 mach_kernel : _panic_trap_to_debugger + 0x197
0xffffff820afdbbc0 : 0xffffff801afae293 mach_kernel : _panic + 0x63
0xffffff820afdbc30 : 0xffffff801b0db92d mach_kernel : _kernel_trap + 0x72d
0xffffff820afdbda0 : 0xffffff801af5bb40 mach_kernel : _return_from_trap + 0xe0
0xffffff820afdbdc0 : 0xffffff7f9ee80953 org.rehabman.voodoo.driver.PS2Controller : __ZN18ApplePS2Controller19notificationHandlerEPvP9IOServiceP10IONotifier + 0xb
0xffffff820afdbeb0 : 0xffffff801b62b98a mach_kernel : __ZN9IOService14invokeNotifierEP18_IOServiceNotifier + 0xea
0xffffff820afdbf00 : 0xffffff801b62e76b mach_kernel : __ZN9IOService14doServiceMatchEj + 0x21b
0xffffff820afdbf50 : 0xffffff801b630316 mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x1a6
0xffffff820afdbfa0 : 0xffffff801af5b0ce mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         org.rehabman.voodoo.driver.PS2Controller(2.0.1)[A7088214-9068-3D18-9329-9972E3807725]@0xffffff7f9ee7e000->0xffffff7f9ee88fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[D039545F-9B61-3B0D-8F90-CCCAE5BD7A52]@0xffffff7f9be85000

BSD process name corresponding to current thread: Unknown
Boot args: dart=0 -v keepsyms=1 debug=0x100 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
Kernel UUID: 7C8BB636-E593-3CE4-8528-9BD24A688851
Kernel slide:     0x000000001ac00000
Kernel text base: 0xffffff801ae00000
__HIB  text base: 0xffffff801ad00000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)

System uptime in nanoseconds: 2412330682
last loaded kext at 1988881361: com.apple.driver.AppleActuatorDriver	2450.1 (addr 0xffffff7f9e421000, size 61440)
loaded kexts:
com.alexandred.VoodooI2CHID	1
com.insanelymac.RealtekRTL8111	2.2.1
com.alexandred.VoodooI2C	2.1.6
org.coolstar.VoodooGPIO	1.1
org.rehabman.voodoo.driver.PS2Controller	2.0.1
org.rehabman.driver.AppleSmartBatteryManager	1.90.1
com.alexandred.VoodooI2CServices	1
com.hieplpvip.AppleBacklightFixup	1.0.2
org.netkas.driver.FakeSMC	1800
xyz.racermaster.NoTouchID	1.0.1
as.vit9696.WhateverGreen	1.2.8
as.lvs1974.AirportBrcmFixup	2.0.0
as.vit9696.AppleALC	1.3.7
as.vit9696.Lilu	1.3.5
com.rehabman.driver.USBInjectAll	0.7.1
com.apple.driver.AppleTopCaseHIDEventDriver	138.3
com.apple.filesystems.apfs	945.260.7
com.apple.driver.AirPort.Brcm4360	1400.1.1
com.apple.driver.AirPort.BrcmNIC	1400.1.1
com.apple.driver.AppleAHCIPort	329.260.5
com.apple.private.KextAudit	1.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleBacklight	170.12.11
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	201
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleActuatorDriver	2450.1
com.apple.driver.AppleHSBluetoothDriver	138.3
com.apple.driver.IOBluetoothHIDDriver	6.0.12f1
com.apple.iokit.IOBluetoothFamily	6.0.12f1
com.apple.driver.AppleMultitouchDriver	2450.1
com.apple.driver.AppleInputDeviceSupport	2440.2
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOAHCIBlockStorage	301.260.1
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	530.51
com.apple.iokit.IOGraphicsFamily	530.66
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.260.3
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.250.3
com.apple.iokit.IOSCSIArchitectureModelFamily	408.250.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.CoreTrust	1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	740.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF

```
</details>

**Comment by vit9696** [comment]
From what it looks this should be a separate issue, despite you trying to convince it is the same as before. Reopened.

**Comment by alexlipe** [comment]
Is there any progress in this?

**Comment by vit9696** [comment]
I believe this is fixed as of VoodooPS2 master and https://github.com/alexandred/VoodooI2C/pull/195. Please report if it is not.
