### ISSUE TITLE
VoodooPS2Controller random kernel panics

### ISSUE THREAD

**Issue by notiflux** [acidanthera/bugtracker#344]
I am experiencing random kernel panics while using VoodooPS2Controller version 2.0.1. I did not find a way to reproduce this reliably as this only happened twice to me, I attached the crash log. Let me know if you want me to gather some more information.

[Kernel_2019-05-21-230307_notifluxs-MacBook-Pro.log](https://github.com/acidanthera/bugtracker/files/3206948/Kernel_2019-05-21-230307_notifluxs-MacBook-Pro.log)

edit: I already added keepsyms=1 to my bootargs but since I can't reproduce the issue on purpose I don't have a panic log from that yet. I'll upload one as soon as it crashes again.

**Comment by Download-Fritz** [comment]
A quick check suggests to me that "virtualState.x_avg.m_sum" is what is attempted to be accessed during the PF
https://github.com/acidanthera/VoodooPS2/blob/f4f8e1c2ffe603f35a1fa2a83a3ddd71db175413/VoodooPS2Trackpad/VoodooPS2SynapticsTouchPad.cpp#L1226

**Comment by notiflux** [comment]
As promised, here's the kernel panic with `keepsyms=1` added to bootargs:
[Kernel_2019-06-01-154846_notifluxs-MacBook-Pro.log](https://github.com/acidanthera/bugtracker/files/3245115/Kernel_2019-06-01-154846_notifluxs-MacBook-Pro.log)

**Comment by vit9696** [comment]
I believe this is fixed in master.
