### ISSUE TITLE
WhateverGreen shikigva=32 shiki-id=Mac-7BA5B2D9E42DDD94﻿ breaks the playback of protected content

### ISSUE THREAD

**Issue by Frank-N-Furter** [acidanthera/bugtracker#347]
Thank you for your great work. 

Arguments shikigva=32 shiki-id=Mac-7BA5B2D9E42DDD94﻿ breaks the playback of protected content example iTunes.

Using NoVPAJpeg.kext does not have this problem.

**Comment by vit9696** [comment]
Please provide more details about your hardware and configuration, including current SMBIOS. Check Shiki FAQ and execute reset DRM according to it. Also check QuickTime.

**Comment by vit9696** [comment]
Restored NoVPAJpeg plugin to the list to avoid involvement in third party issues.
