### ISSUE TITLE
Switch to -Oz optimization level for XCODE5 RELEASE builds

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#350]
Changing the optimisation level to `-Oz` seems to reduce the resulting OpenCore RELEASE binary size by 10%, which can be beneficial for slow I/O or tight space environments.

This level is the default one for `CLANG38` toolchain, which basically uses the same compiler, and I am unsure whether `XCODE5` should actually not follow. We already add `-flto` flag to reduce binary size in all the UEFI projects.

To transition to -Oz mode one needs to update `.dsc` files replacing `-flto` with `-Oz -flto` in all the projects:

- https://github.com/acidanthera/MacInfoPkg/blob/master/MacInfoPkg.dsc#L61
- https://github.com/acidanthera/OpenCorePkg/blob/master/OpenCorePkg.dsc#L119
- https://github.com/acidanthera/OcSupportPkg/blob/master/OcSupportPkg.dsc#L160
- https://github.com/acidanthera/AppleSupportPkg/blob/master/AppleSupportPkg.dsc
- https://github.com/acidanthera/AptioFixPkg/blob/master/AptioFixPkg.dsc#L94

We need more test data to ensure that this change does not bring any regressions as well as the details on how much it decreases the size of not just OpenCore but also other drivers.

@Andrey1970AppleLife, @vandroiy2013, @roddy20 please do some checks and ensure that it remains fine afterwards. If it is ok, update all the mentioned .dsc files by next week.

**Comment by Andrey1970AppleLife** [comment]
Added
