### ISSUE TITLE
Implement new partition info protocol for ScanPolicy

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#351]
Presently we do not have any reliable sources to obtain file system information of the partition as described by #335. This results in being unable to detect FAT32 partition, reliably distinguish APFS and HFS partitions, as well as see the difference between EFI System Partition and any other FAT32 partition. The user visible result is pretty much unusable ScanPolicy file system lock bit.

I believe we should implement our own protocol with a single instance that will provide filesystem details based on the mounted handle. Apple partiton info protocol is inconvenient in a way that it does not permit cached lazy information fetching, and EDK II partition info protocol is missing or broken on most systems.

It should be noted that this protocol is not intended to protect partitions from mounting, this issue is separate, and is supposed to be done by the driver itself as described in #335.

- [x] Implement OcPartitionInfo protocol with GPT <s>and MBR</s> support (ignore El Torito for now)
- [x] Use OcPartitionInfo protocol to determine file system type in OcBootManagementLib
- [x] Support ESP and FAT32 in ScanPolicy

**Comment by Download-Fritz** [comment]
Imported as library API for GPT partition tables at https://github.com/acidanthera/OcSupportPkg/commit/63e85a8b13c02d78429f13b84df2165b823e1eae
