### ISSUE TITLE
Implement builtin CPUID patches

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#352]
To prevent `panic("Unsupported CPU");` call on select CPUs not natively recognised by XNU we need to somehow patch XNU CPUID checks:

https://github.com/apple/darwin-xnu/blob/xnu-4570.1.46/osfmk/i386/cpuid.c#L834

As discussed with @PMheart it seems it will require two separate approaches for macOS release kernel and macOS debug kernel due to the nature of LLVM optimiser behaviour.

For the configuration we would like to add a new `Kernel` → `Emulate` section that will have 2 static arrays:

* `Cpuid1Data` → 16 bytes of eax, ebx, ecx, edx values in Little Endian for `cpuid(1)` 
* `Cpuid1Mask` → 16 byte mask replacing set bits of `cpuid(1)` call with `Cpuid1` data

Setting any bit in `Cpuid1Mask` will activate the patch.

_**For release kernel we could try patching the CPUID request area**_:  
https://github.com/apple/darwin-xnu/blob/xnu-4570.1.46/osfmk/i386/cpuid.c#L563

The implementation contains 24 or 22 bytes of easily discoverable code, which we can patch with static cpuid data obtained from executing [AsmCpuid](https://github.com/tianocore/edk2/blob/UDK2018/MdePkg/Include/Library/BaseLib.h#L6910) call in OpenCore itself.

**For 10.8+ the byte sequence is as follows**:

```asm
B9 8B 00 00 00  mov     ecx, 8Bh
31 C0           xor     eax, eax
31 D2           xor     edx, edx
0F 30           wrmsr
B8 01 00 00 00  mov     eax, 1
31 DB           xor     ebx, ebx
31 C9           xor     ecx, ecx
31 D2           xor     edx, edx
0F A2           cpuid
```

**For 10.7 the byte sequence is as follows**:

```asm
B9 8B 00 00 00  mov     ecx, 8Bh
31 D2           xor     edx, edx
0F 30           wrmsr
B8 01 00 00 00  mov     eax, 1
31 DB           xor     ebx, ebx
31 C9           xor     ecx, ecx
31 D2           xor     edx, edx
0F A2           cpuid
```

Patch data will look as follows

```asm
mov eax, #imm
mov ebx, #imm
mov ecx, #imm
mov edx, #imm
nop ; repeat as needed
```

Similarly we will have to patch microcode revision reading MSR, as it requires nulling and a CPUID call according to SDM:

```asm
B9 8B 00 00 00  mov     ecx, 8Bh
0F 32           rdmsr
```

```asm
mov edx, #imm
nop
nop
```

In OpenCore we will end up using the following code:

```C
#include <Register/ArchitecturalMsr.h>

/* ... */
AsmWriteMsr64 (MSR_IA32_BIOS_SIGN_ID, 0); 
AsmCpuid(1, &Eax, &Ebx, &Ecx, &Edx);
MicrocodeRev = AsmReadMsr32 (MSR_IA32_BIOS_SIGN_ID); 
```

_**For debug kernel we could try patching the family setting function**_:  

As LLVM does not inline static functions in debug mode it makes sense to patch `cpuid_set_cpufamily` implementation entirely with a symbolic patch:  
https://github.com/apple/darwin-xnu/blob/xnu-4570.1.46/osfmk/i386/cpuid.c#L759

`i386_cpu_info_t` structure type is KPI, so it is guaranteed to preserve the layout between kernel updates and so far is ok to write directly. We should make this definition to be part of [EfiPkg](https://github.com/acidanthera/EfiPkg) most likely. While clearly imperfect (as some conditional code will still use the original values), patching just the following fields should be good enough for us:

```
cpuid_signature
cpuid_stepping
cpuid_model
cpuid_family
cpuid_type
cpuid_extmodel
cpuid_extfamily
cpuid_brand
cpuid_features
cpuid_family
cpuid_model
cpuid_logical_per_package
```

The exact logic will have to prepared beforehand in asm in a tight format as we do not have much memory.

The implementation should land in [CommonPatches.c](https://github.com/acidanthera/OcSupportPkg/blob/master/Library/OcAppleKernelLib/CommonPatches.c).

**Comment by vit9696** [comment]
Implemented in master. Just in case, the usage may look like the following to KBL model emulation:

```
Cpuid1Data: <E9 06 09 00 00 00 00 00 00 00 00 00 00 00 00 00>
Cpuid1Mask: <FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00>
```

**Comment by PMheart** [comment]
Fully functional as of https://github.com/acidanthera/OcSupportPkg/commit/98ef06530953b8c90d9a90da1844ad732e8a01c4.
