### ISSUE TITLE
Suggestion: Whatevergreen Improvement

### ISSUE THREAD

**Issue by 428Yotsuba** [acidanthera/bugtracker#354]
Refer: https://github.com/428Yotsuba/RX580-8G-macOS

I tested (but Sapphire"RX580" Only),

ATIController::TestVRAM(PCI_REG_INDEX, boot) - FAILED at offset 0x002Cxxxx, data = 0x00000000,0x00FFFFF
	fail Serial	113-1E366CU-S52 (Samsung,Hynix ROM)
			113-WE3874U-S5S (Micron ROM)

busy time out[0], (240s):'PEGP'
busy time out[1], (240s):'PEGP'

com.apple.xpc.launchd[1] (com.apple.displaypolicyd.593) <Warning>: Service exited with abnormal code: 1
com.apple.xpc.launchd[1] (com.apple.displaypolicyd.594) <Warning>: Service exited with abnormal code: 1
com.apple.xpc.launchd[1] (com.apple.displaypolicyd.595) <Warning>: Service exited with abnormal code: 1

KernelPanic(boot fail.)

**Comment by vit9696** [comment]
Please create a bugreport that properly describes an issue you have, the action you would like us take, and the result you would like to get. Currently I am clueless what you want.
