### ISSUE TITLE
Bug in newest release of MaciASL

### ISSUE THREAD

**Issue by hieplpvip** [acidanthera/bugtracker#356]
Consider these two examples:
```
DefinitionBlock ("", "DSDT", 0, "", "", 0)
{
    External(RAND, DeviceObj)
    External(RAND, DeviceObj)
}
```
```
DefinitionBlock ("", "DSDT", 0, "", "", 0)
{
    External(RAND, IntObj)
    External(RAND, IntObj)
}
```
The first one would compile successfully, while the second one would cause error code 6117, `Existing object has invalid type for scope operator (RAND [Integer])`

This doesn't happen with Rehabman's MaciASL version. I believe this is a bug in iasl, but I don't know how to fix it. Hope you can help.

**Comment by vit9696** [comment]
I am not positive this is a bug, as you have 2 external entries with the same name. If you believe this code does not violate ACPI spec (as per uefi.org) or have your own opinion, file a bug in ACPICA compiler upstream. Their bugtracker is in https://github.com/acpica/acpica/issues.

In case acpica fixes it, create a new bug here requesting compiler upgrade in MaciASL.
