### ISSUE TITLE
OC refuse to inject AirportBrcmFixup on 10.15

### ISSUE THREAD

**Issue by evansan** [acidanthera/bugtracker#357]
Both Lilu and AirportBrcmFixup are compiled from`Allow loading on 10.15 without -lilubetaall ` commits.

[opencore (1).log](https://github.com/acidanthera/bugtracker/files/3250295/opencore.1.log)

[KP.log](https://github.com/acidanthera/bugtracker/files/3250561/KP.log) with Clover injection

**Comment by vit9696** [comment]
IOCatalogue APIs seem to be missing:

![](https://i.applelife.ru/2019/06/452051_5F3E5504-B3DC-42C3-85E8-270AD71EDF5C.jpeg)

**Comment by vit9696** [comment]
We will need to solve these with Lilu now. `__ZN11IOCatalogue13removeDriversEP12OSDictionaryb` remains unchanged, and `__ZN11IOCatalogue13startMatchingEP12OSDictionary` got replaced with `__ZN11IOCatalogue13startMatchingEPK8OSSymbol`. Matching start now takes OSSymbol with the service name.

**Comment by vit9696** [comment]
IOCatalogue.h still contains most interfaces. Filed a problem 6112035 requesting clarifications.

**Comment by vit9696** [comment]
Fixed in master.
