### ISSUE TITLE
Kext injection issues on legacy systems

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#358]
Booting without caches on 10.9 or earlier will bypass kext injection. This happens as we neither support legacy kext injection, nor provide hooking for /S/L/E folder reading for boot.efi. While any change will unlikely land in OpenCore as 10.9 is end of life, this bug should help with the tracking.

**Comment by vit9696** [comment]
Leaving open due to 32-bit support and MKEXT.

**Comment by vit9696** [comment]
To force booting without caches we can pass 0 modification date, like https://github.com/acidanthera/OpenCorePkg/commit/c9b719670ec33e07bff58d1e8a4a531765a12cef. In the future we may want to provide `-f` flag support or perhaps `CMD+F` hotkey if this mode is considered necessary. It is unsafe to force that permanently, because at least 10.4 and 10.7+ installers do not have kexts. Safe mode (`-x`) forces no cacheless mode.

**Comment by vit9696** [comment]
- [ ] 64-bit kext patcher is broken for 10.6.8 PK as it will need symbol solving from KXLD state.
- [ ] 64-bit kext patcher is broken for MKEXT.
- [ ] 64-bit kext patcher is broken for cacheless.
- [ ] `Architecture` plist key is missing from config.plist
- [ ] Some way to choose the preferred kext injection method is also missing from config.plist
- [ ] 32-bit vs 64-bit kernel detection based on board-id and kernel version is not implemented.
- [ ] 32-bit kext injection into MKEXT and cacheless is not implemented (due to broken detection).
- [ ] 32-bit kext injection into PK is not implemented due to missing Mach-O 32-bit library.
- [ ] 32-bit kernel and kext patcher in any form is also broken due to missing Mach-O 32-bit library.

I believe kernel patcher should work for all 64-bit kernels. But I am quite worried about kernel quirks compatibility. To be honest, we need a test suite.

**Comment by Goldfish64** [comment]
Additionally, PK hooking needs to be more precise on matching to avoid matching non-kernel files that have kernel in the name (i.e. various System.kext plugins and others during a no-cache boot).

**Comment by vit9696** [comment]
Currently the following issues are relevant:

- [ ] 32-bit PK kext injection tests
- [ ] 32-bit and 64-bit mkext injection tests (I do not believe we can test cacheless)
- [ ] 10.4 and 10.5 still try to boot with PK in `KernelCache` `Auto` mode, but kext injection is impossible in this case. This needs to be corrected by forcing mkext for these versions in both the code and the documentation.
- [ ] 10.4 and 10.5 cannot boot with `-legacy` on 64-bit firmwares due to uninitialised 64-bit segment. This needs to be addressed by `KernelArch` `Auto` and `i386-user32` not using `-legacy` with 64-bit firmware for 10.4 and 10.5. The documentation also needs to be updated.
- [ ] Without `-legacy` 10.4+ seems to be not booting on Pentium 4 machines. A little irrelevant, could factor out to a separate issue if it remains.
- [ ] We will probably want `MinKernel`, `MaxKernel` to `Emulate` AND move `DummyPowerManagement` to that area. So that CPUID emulation (even if disabled) also means dummy power management, allowing us to enable CPU support on older macOS versions.

**Comment by vit9696** [comment]
Closing as resolved. Tests will be handled later during utility fuzzing improvements.
