### ISSUE TITLE
Recovery 10.15 (dmg) fail

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#360]
Loading failure Recovery 10.15 dev.beta1 on AptioIV.
![IMG_0311](https://user-images.githubusercontent.com/17758753/58917501-79e87180-872f-11e9-880d-022ed6b5414e.jpeg)

If to press the button 5, occurs nothing and in some seconds of the menu will change so:
![IMG_0312](https://user-images.githubusercontent.com/17758753/58917622-db104500-872f-11e9-8a63-ff4a4234f129.jpeg)

With debug OC - Halt. 
![IMG_0313](https://user-images.githubusercontent.com/17758753/58917823-8f11d000-8730-11e9-8ea9-287fdac2dc50.jpeg)

I set HaltLevel 0 to exclude Halt and made attempt will boot in section 5, and then in section 2. Thus I saved a log.
[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3254708/opencore.log.zip)
Partition contents Recovery: https://drive.google.com/file/d/1Fufj3wO5F5vk3fXd__rjMaNa6hpmU7nU/view?usp=sharing

**Comment by Andrey1970AppleLife** [comment]
New OC log with https://github.com/acidanthera/OcSupportPkg/commit/27006156ccac8598ed4ce8c59e1dc01feaf4f787
[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3259088/opencore.log.zip)

**Comment by vit9696** [comment]
```
06:331 04:373 Should boot from Recovery 10.15 (W:0|R:1|F:1)
15:612 09:280 Dmg trailer error: 1 - 1D382B68/1D382D68 - 796C6F6B/FF8E593F.
15:615 00:002 OCBD: Failed to initialise DMG context.
15:616 00:000 OCB: Failed to initialise DMG from file.
15:617 00:000 LoadImage failed - Unsupported
```

With the current logging. Seems like some memory/disk corruption is involved as the offset is perfectly valid…

On a laptop corrupting chunklist is confirmed to make the image unbootable. Quite importantly 10.15 does not disappear after an error.

**Comment by Andrey1970AppleLife** [comment]
HDD problem
