### ISSUE TITLE
OcSupportPkg: OcCpulib: vs2019ce warnings (errored)

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#361]
OcSupportPkg\Library\OcCpuLib\OcCpuLib.c(800): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
OcSupportPkg\Library\OcCpuLib\OcCpuLib.c(801): warning C4244: '=': conversion from 'UINT64' to 'UINT8', possible loss of data

**Comment by vit9696** [comment]
Seems to be fixed in master. Thx.
