### ISSUE TITLE
Debug Uefi Shell.efi v1.1 

### ISSUE THREAD

**Issue by grassybor** [acidanthera/bugtracker#362]
See below.

**Comment by grassybor** [comment]
I can't run Deug Uefi Shell.efi v1.1 on Tools.
![Screen Shot 2019-06-07 at 18 38 48](https://user-images.githubusercontent.com/1409753/59116327-23687680-896d-11e9-85d1-3be30f9a2050.png)

**Comment by vit9696** [comment]
This seems to be a bug in shell, but most likely the easiest way will be to provide some dummy DevicePath (e.g. vendor) to the launched image.
