### ISSUE TITLE
OcConfigurationLib: Improve MatchKernel.

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#367]
Currently MatchKernel (at Kernel section in userspace) only allows one kernel version.
It would be nice to add:
- Range support, e.g 16.7.0-18.6.0 for 10.12.6 - 10.14.5 (just like `MinKernel` and `MaxKernel` in AppleALC with more precise matching)
- Minimum kernel version support (identical to `MinKernel` in AppleALC)
- Maximum kernel version support (identical to `MaxKernel` in AppleALC)

**Comment by vit9696** [comment]
Should most likely implement it as a sequence of comma-separated string prefixes for simplicity and to avoid the need of parsing.

**Comment by vit9696** [comment]
Implemented in master.
