### ISSUE TITLE
 HP Local APIC Error - lapic patch not works

### ISSUE THREAD

**Issue by Eternity5510** [acidanthera/bugtracker#370]
That kernel panic is common with HP, but lapic patch not works with OpenCore

**Comment by MacFriedIntel** [comment]
i can also confirm it's not working

**Comment by vit9696** [comment]
Please provide the kernels (/System/Library/Kernels/kernel) for the OS you use as well as the macOS version.

**Comment by ReaperOfSouls1909** [comment]
for a user of ours he is using 10.15 
[kernel.zip](https://github.com/acidanthera/bugtracker/files/3273757/kernel.zip)
here is the kernel

**Comment by Eternity5510** [comment]
[10.15.zip](https://github.com/acidanthera/bugtracker/files/3273807/10.15.zip)
[10.14.zip](https://github.com/acidanthera/bugtracker/files/3273809/10.14.zip)
I tested this with macos 10.14 and 10.15. Kernels is here

**Comment by errorexists** [comment]
here is my debug for OC 
[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3274399/opencore.log.zip)

**Comment by vit9696** [comment]
I checked 10.15 kernel you provided, and I do not see it. The patch looks legit to me. Please provide the panic log when lapic patch fails.

Also check what you have in boot args, if you have `debug=something`, then you must also add `lapic_dont_panic=1` as per Apple docs.

In case you are unable to save panic log in text form, use the `PanicNoKextDump` quirk to disable kext list logging. But text file is preferred. Also do include `keepsyms=1` in boot arguments.

**Comment by errorexists** [comment]
i have for boot args "lapic_dont_panic=1 dart=0 -v kext-dev-mode=1 debug=0x100 -lilubeta -alcbeta -brcmfxbeta keepsyms=1"
[10.15 kernel.zip](https://github.com/acidanthera/bugtracker/files/3277481/10.15.kernel.zip)
[opencore log.zip](https://github.com/acidanthera/bugtracker/files/3277482/opencore.log.zip)

**Comment by vit9696** [comment]
@errorexists please provide the kernel panic I requested above. The rest seems ok.

**Comment by ReaperOfSouls1909** [comment]
![](https://cdn.discordapp.com/attachments/565994033781145601/588068956988768256/IMG_6914.jpg)

**Comment by errorexists** [comment]
sorry for the inconvenience 
![IMG_6914](https://user-images.githubusercontent.com/23367705/59296280-6743d000-8c3a-11e9-92bd-275e1c0d263d.jpg)

**Comment by vit9696** [comment]
Fixed in master, thanks.

**Comment by errorexists** [comment]
thank you much appreciation

**Comment by nirvanasinha** [comment]
> sorry for the inconvenience
> ![IMG_6914](https://user-images.githubusercontent.com/23367705/59296280-6743d000-8c3a-11e9-92bd-275e1c0d263d.jpg)

I am facing the same issue, i am a noob. help me ?

**Comment by baddles** [comment]
https://youtu.be/ZMu5QmsbvU4

Seems like the fixes doesn't work in 10.9. lapic_dont_panic=1 isn't a boot argument there (Can verify this by booting 10.13 instead), and lapickernelpanic is checked (Can verify by the fact that lapickernelpanic patch is applied somewhere there.
This is on an Arrandale laptop:
HP Pavilion DM4-1265DX, i5-460M, 4GB RAM.

**Comment by feryw** [comment]
> https://youtu.be/ZMu5QmsbvU4
> 
> Seems like the fixes doesn't work in 10.9. lapic_dont_panic=1 isn't a boot argument there (Can verify this by booting 10.13 instead), and lapickernelpanic is checked (Can verify by the fact that lapickernelpanic patch is applied somewhere there. This is on an Arrandale laptop: HP Pavilion DM4-1265DX, i5-460M, 4GB RAM.

try using cpus=1
