### ISSUE TITLE
No BootPicker after restarting in Windows with Startup Disk panel

### ISSUE THREAD

**Issue by vandroiy2013** [acidanthera/bugtracker#371]
![58181274418__156F2ECA-E45E-4BBE-B7A3-529E56DCEA0C](https://user-images.githubusercontent.com/8144780/59165296-37a1a480-8b22-11e9-809c-67f5e29f5c94.JPG)

And log
[opencore.log](https://github.com/acidanthera/bugtracker/files/3270074/opencore.log)

**Comment by vit9696** [comment]
@Download-Fritz might you know why does not this log file and line as it did with UDK? Looks quite borked or at least misconfigured to me.

**Comment by vit9696** [comment]
https://github.com/acidanthera/OcSupportPkg/commit/fd47f5e6a027ef97b96feaf2bb9736ce17eadd19 this commit should make file info visible.

**Comment by Download-Fritz** [comment]
https://github.com/acidanthera/OcSupportPkg/commit/662a12972428a0a9da639e5a821b450ac030deb9 this commit should fix the ASSERT, however legacy Windows DPs are not yet supported.

**Comment by fcsd5k** [comment]
[opencore.log](https://github.com/acidanthera/bugtracker/files/3272382/opencore.log)

**Comment by Download-Fritz** [comment]
@fcsd5k Sorry, what is the context of that log? It shows a correctly matched default boot option and a subsequent seemingly successful macOS boot.

**Comment by fcsd5k** [comment]
Not booting.

**Comment by vandroiy2013** [comment]
@Download-Fritz, ASSERT was fixed, but restart in Windows didn't worked according to log. 
[opencore.log](https://github.com/acidanthera/bugtracker/files/3273265/opencore.log)

**Comment by Download-Fritz** [comment]
@vandroiy2013 Yes, legacy Windows paths (MemoryMapped leads points to the Apple EFI legacy boot app) are not yet supported as we need to expose PartitionInfo (especially partition type GUID to locate ESP) first. When macOS is selected from Boot Camp Control Panel, does it work?

**Comment by vandroiy2013** [comment]
It is NOT Legacy install. It's full UEFI Windows. With automatic Windows disk partitioning. As you see EFI is not first partition. But it is 100% UEFI install. 
![Снимок экрана 2019-06-10 в 21 40 40](https://user-images.githubusercontent.com/8144780/59218229-683c1980-8bc8-11e9-9798-530bc7d40a52.png)

**Comment by Download-Fritz** [comment]
@vandroiy2013 I am aware, but macOS recognises any Windows install as legacy when ESP is not the first partition on the disk, as described in https://github.com/acidanthera/bugtracker/issues/327
Sorry for the confusion.

**Comment by vandroiy2013** [comment]
I'll reinstall Windows with EFI partition on the first plase this weekend and report back) Don't have time now for that. Sorry

**Comment by Download-Fritz** [comment]
@vandroiy2013 The Recovery partition is not mandatory, so per your preference, you could just shortcut by deleting it and re-creating the ESP as first partition of 200 MB size

**Comment by vandroiy2013** [comment]
@Download-Fritz, Anyway i can do it only on weekend. I'll report after test.

**Comment by vit9696** [comment]
Closing as fixed in master.
