### ISSUE TITLE
Does not work DeviceProperties, does not work Tools Enabled

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#372]
[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3270275/opencore.log.zip)

**Comment by vit9696** [comment]
I believe https://github.com/acidanthera/OcSupportPkg/commit/7762bfb4d1fabaca089e785a62ad7150aeec5314 fixes it. Reopen otherwise.

**Comment by Andrey1970AppleLife** [comment]
Does not work.
[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3272305/opencore.log.zip)

**Comment by vit9696** [comment]
@Download-Fritz could base64 be broken?

**Comment by vit9696** [comment]
Identified to be https://github.com/acidanthera/OcSupportPkg/commit/2104029260a009b807614b10aaee931685840282

**Comment by vit9696** [comment]
Fixed in master. Add EDK II bugzilla report for reference once it is added, and close the issue.

**Comment by vit9696** [comment]
This is now to be addressed as part of EDK II bugs:
https://bugzilla.tianocore.org/show_bug.cgi?id=1891
