### ISSUE TITLE
OC Build and Compile Issue

### ISSUE THREAD

**Issue by MacFriedIntel** [acidanthera/bugtracker#373]
.

**Comment by MacFriedIntel** [comment]
I've just compiled the latest Build of OC and is failing to boot on my System (Asus Z370 PII)
i've used both my own and Fish's Build it seems to work on some machines but there are others with this in the log file.
[opencore.log](https://github.com/acidanthera/bugtracker/files/3273969/opencore.log)
![Screen_Shot_2019-06-10_at_23 05 51](https://user-images.githubusercontent.com/42754234/59230719-46e22a00-8bd6-11e9-9eab-ea8efc7bbdb5.png)

**Comment by MacFriedIntel** [comment]
Just boots to a black screen and halts.

**Comment by errorexists** [comment]
when i boot i get attached picture 
00:000 00:000 BS: Failed to start OpenCore image...

![image](https://user-images.githubusercontent.com/23367705/59231210-bb947480-8b94-11e9-9371-2db7b6d35a15.png)

**Comment by vit9696** [comment]
Do not see a bug here. You run OpenCore from OpenCore, this will obviously not work.

Check `UsePicker` / `ShowPicker`. Also creating log with release builds is entirely useless.

I am tending to close this unless you could convince me there actually is some bug.

**Comment by MacFriedIntel** [comment]
[opencore.log](https://github.com/acidanthera/bugtracker/files/3274097/opencore.log)

Debug log. I've not had an issue before.

**Comment by vit9696** [comment]
`Handing off to external boot controller`. Please read the manual. It says explicitly that in 0.0.3 you are to provide `UsePicker` = `YES` to use OpenCore boot services.

Repeated failures to read the manual may lead us to restricting this bugtracker to the team only. Please keep that in mind and pay better attention to the details. Thanks.
