### ISSUE TITLE
OcSupportPkg: Modules MetaFile [Sources] is missing local headers

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#374]
build: : warning: Module MetaFile [Sources] is missing local header!
    Local Header: ocsupportpkg/library/ocapplediskimagelib/ocapplediskimagelibinternal.h not found in OcSupportPkg/Library/OcAppleDiskImageLib/OcAppleDiskImageLib.inf
build: : warning: Module MetaFile [Sources] is missing local header!
    Local Header: ocsupportpkg/library/ocguardlib/ubsan.h not found in OcSupportPkg/Library/OcGuardLib/OcGuardLib.inf
build: : warning: Module MetaFile [Sources] is missing local header!
    Local Header: ocsupportpkg/library/ocmacholib/ocmacholibinternal.h not found in GIT/OcSupportPkg/Library/OcMachoLib/OcMachoLib.inf
build: : warning: Module MetaFile [Sources] is missing local header!
    Local Header: ocsupportpkg/library/ocsmbioslib/debugsmbios.h not found in OcSupportPkg/Library/OcSmbiosLib/OcSmbiosLib.inf
build: : warning: Module MetaFile [Sources] is missing local header!
    Local Header: ocsupportpkg/tests/cryptotest/cryptosamples.h not found in OcSupportPkg/Tests/CryptoTest/CryptoTest.inf
build: : warning: Module MetaFile [Sources] is missing local header!
    Local Header: ocsupportpkg/tests/cryptotest/cryptosamples.h not found in OcSupportPkg/Tests/CryptoTest/CryptoTestApp.inf

**Comment by vit9696** [comment]
Is that handled by some external tool? For some reason I do see these issues.

**Comment by nms42** [comment]
Recent changes in edk2 BaseTools made this visible
