### ISSUE TITLE
Rename BT4LEContiunityFixup to BT4LEContinuityFixup

### ISSUE THREAD

**Issue by usr-sse2** [acidanthera/bugtracker#375]
macOS feature that this kext enables is called Continuity, not Conti**unity**. Wrong kext name prevented loading it in OpenCore because I spelled it in config like it should be.

**Comment by lvs1974** [comment]
Fixed in:
https://github.com/acidanthera/BT4LEContinuityFixup/commit/8541b5589bb1d2e5493eaa399c761c8e621b217a
https://github.com/acidanthera/BT4LEContinuityFixup/commit/ec05b8dcb7b7b6009cb8417fb8b2fbd9ec972d95
