### ISSUE TITLE
Partially updating SMBIOS on older Macs

### ISSUE THREAD

**Issue by Rastafabisch** [acidanthera/bugtracker#377]
Hello!

I (and others) have realised, that OpenCorePkg could be useful on the Mac side, too. Especially for upgradeable machines that are potentially fully compatible or only requiring minor patches*, OC could provide some useful functionality.

With the release of new macOS version said Mac are however dropped altogether. Mostly due to system identifier and/or board-ID checks those capable machines are ruled out, and it is not trivial to circumvent those restrictions. Booting with OC those settings can be overcome easily, but this requires either spoofing a newer compatible, officially compatible Mac with quite different hardware, or mini-matching the SMBIOS copying the current hardware 1:1 and only spoofing said values. While this appears undesirable it‘s actually the better approach and is tested to work flawlessly. This way the actual underlying hardware is visible to the software for features like iCloud functionality, serial aware payed software, power-management and so on. However the need to set this up manually or at least individually using a simple parsing script prevents the implementation of an universal approach like a boot-stick, which, giving the size of the “macOS xyz on unsupported Mac”-community could be worthy.

Only spoofing some specific value should eleminate those software limitations, which are hard come by (possible at all?) with software due to their signatures.

This is why I propose a functionality to toggle an _inject only set SMBIOS variables_ as an addition to the current implementation of generating an entire “feature-complete” SMBIOS based on the given generic dataset(s). This of course makes total sense for hackintoshes, whose hardware **can** be configured to mime a similarly specced Macs, but appears to be troublesome on macs as Apple tends to “batch-discontinue” those**.

I hope you will evaluate this suggestion and find it useful. Of course I am also open to suggestion of other approaches and I am available for additional clarifications if needed.

Best,
Rastafabisch

—————
(*) like: Mac Pro’s 3,1 - 5,1 and pre 2012 iMacs with upgraded graphics.
(**) with the prominente exception of the MacPro4,1 which was dropped with Sierra, whereas the largely similar MacPro5,1 was/is supported up to Catalina. This was however possible to overcome with a firmware flash, which is not applicable to those now affected machines.

**Comment by vit9696** [comment]
Quick check, have you seen SampleFull? In Automatic = NO mode you could provide all the details manually, and empty fields leave original values in the most (if not all) of the cases. Perhaps this could work for you out of the box.

**Comment by Rastafabisch** [comment]
I'm not entirely sure it work's as it's supposed to be. If I understand you correctly what you describe is exactly what I want -> editing some values, but leaving others. However this does not work for me.
For testing I try to spoof MP5,1 as an iM14,2.
Whenever I set Automatic to false, everything is omitted and it's just like booting without OC. When set to true the resulting SSN is actually W0000000001, whereas deleting the key results in a OPENCORE_01 SSN. 

```
		<key>Automatic</key>
		<false/>
		<key>Generic</key>
		<dict>
			<key>MLB</key>
			<string>M000000000001</string>
			<key>ROM</key>
			<data>ESIzAAAA</data>
			<key>SpoofVendor</key>
			<true/>
			<key>SystemProductName</key>
			<string>iMacPro5,1</string>
			<key>SystemSerialNumber</key>
			<string>W0000000001</string>
			<key>SystemUUID</key>
			<string>00000000-0000-0000-0000-000000000000</string>
		</dict>
```

**Comment by vit9696** [comment]
@Rastafabisch I get a feeling you did not read the manual, especially chapter 9, `PlatformInfo`. You are not supposed to use `Generic` with `Automatic` set to `false`. It will take me some time to retell it, so please check it out yourself first.

**Comment by Rastafabisch** [comment]
I know and I haven't previously, I just got confused by this:

> […] In Automatic = NO mode you could provide all the details […].

As it is working now, I'm in the process of creating a universal boot stick.

![Bildschirmfoto 2019-06-12 um 13 28 34](https://user-images.githubusercontent.com/38974866/59348871-903a9280-8d18-11e9-9a2d-cdca31ef2e1a.png)

**Comment by vit9696** [comment]
@Rastafabisch, I get a feeling you still misunderstand me. Please do read this:

https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf
And then check this:
https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/SampleFull.plist

You can update each SMBIOS field individually, e.g. by setting PlatformInfo → SMBIOS → BoardProduct, and leaving other fields empty. I believe it will be by far cleaner for MacPros.

I know it is hard to read, but it is kind of an important thing to do.

**Comment by Rastafabisch** [comment]
Now I get you, I think. However with the exact same config.plist apart from the PlatformInfo section OS does not even load on may Mac. It just freezes the Boot Selector, even after waiting for several minutes. Also as it just shuts down when single-pressing the power button, it does not appear to be doing anything.
Assuming I did everything correctly, it does not work as simple as that. Although this would be obviously a cleaner solution as you say. 

[config-plists.zip](https://github.com/acidanthera/bugtracker/files/3281416/config-plists.zip)

**Comment by vit9696** [comment]
The file you uploaded is not a valid plist file and does not open in Xcode:
<img width="466" alt="Снимок экрана 2019-06-12 в 16 15 10" src="https://user-images.githubusercontent.com/4348897/59354185-41e3be80-8d2d-11e9-8b96-64938860ae79.png">

**Comment by Rastafabisch** [comment]
Yes I realised that myself. It does work perfectly fine. Now I'm gonna try to leave out certain mentions of the model identifier and the board id, to see when it breaks.

**Comment by Rastafabisch** [comment]
Observations:
```
<key>UpdateDataHub</key>
<false/>
<key>UpdateNVRAM</key>
<false/>
<key>UpdateSMBIOS</key>
<true/>
```
Works for booting and updating from Mojave, if the firmware version is spoofed, too. (Else no install from APFS Mojave.)
```
<key>UpdateDataHub</key>
<true/>
<key>UpdateNVRAM</key>
<true/>
<key>UpdateSMBIOS</key>
<false/>
```
Appears clean to the OS, and allows booting to 10.15, but does not allow installation from within Mojave. -> _Not supported on this computer._
```
<key>BIOSVersion</key>
<string>XYZ.0.0.0.0</string>
```

As `UpdateSMBIOS` is required for updating I will go this way, even though it appears less clean.

**Comment by Rastafabisch** [comment]
I just released a [tool](https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-40#post-27459617) embedding the findings from here.  

BTW: I needed to resort to rEFInd because manually starting from the Mac boot-loader works, but booting after blessing the drive does not. I try to provide the error I get, soon.

**Comment by vit9696** [comment]
Nice to hear. I think your issue with bless is due to blessing incorrect file. You should bless BOOTx64.efi or just copy it to BOOT directory. OpenCore.efi is a driver, not an app. Check the directory structure in the manual.

I believe you have another problem: macOS boot volume preference panel compatibility and seamless upgrade installation. It will affect Apple Boot Picker and bypass OpenCore unless you manually select it. To workaround it we use `RequestBootVarRouting` quirk. This quirk separates operating system & OpenCore Boot Picker from the firmware by swapping NVRAM GUIDs. This way you can have your firmware configured to always boot to OpenCore, and OpenCore Boot Menu itself will always see your chosen boot entry in macOS preferences.

The only issue to make it work on Apple hardware is that currently this feature requires installation of AptioMemoryFix (https://github.com/acidanthera/AptioFixPkg). We did not test it on Macs, and it will require adopting even if it works out of the box, as there are many hacks that are irrelevant for Apple hardware. I would suggest you try it, and see how it goes.

**Comment by Rastafabisch** [comment]
Regarding bless I actually think it’s winter related to OpenCore.efi or more likely the associated BootX64.efi. If I just replace it with rEFInd and do provide a configuration file to instantly load OpenCore it just works using the same bless command.

I really do like your nvram-swap trick. I worked around this issue differently, though. As OpenCore does reside on the startup volume activated HFS+ partition rather then inside the EFI one, or actually hides itself as I enabled the selfhide quirk. This, together with setting the timeout to 10 seconds actually triggers OpenCore to just boot the first option in the generated list.
As the Catalina loader is not supposed to be used for regular booting, I feel this is a better approach, as else the first boot without OpenCore would not boot the user selected partition.

**Comment by Rastafabisch** [comment]
Have not yet checked myself in the configuration guide (being mobile), but [doesn’t that sound interesting?](https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-42#post-27460696)

**Comment by vit9696** [comment]
As for VMM flag, I am unsure what it refers to.

As for all other things:

1. The NVRAM workaround is ugly, it will not provide seamless macOS updates, and it needs to be fixed.
2. The BOOTx64.efi failure issue, I need the log for it and the dump of the resulting filesystem structure. I believe you do something wrong.
3. CSR settings must be set in Recovery. That is really the right way to do it. In OpenCore you can do that via NVRAM, but there is little need to. Add sections works like adding default options, it does not mean set & overwrite.

**Comment by vit9696** [comment]
Given FwRuntimeServices.efi release I believe that this issue is fully resolved. Closing. Create a new one if anything else still needs to be addressed.
