### ISSUE TITLE
In case of an output from hibernation there is a reboot.

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#378]
[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3278974/opencore.log.zip)

**Comment by vit9696** [comment]
I *think* something is wrong with device path in `boot-image` or similar, as the data looks pretty legit.

**Comment by Download-Fritz** [comment]
The "boot-image" variable is set with an Apple Device Path, https://github.com/acidanthera/OcSupportPkg/commit/8ba164657083cc94a8c93956e280fbd1583c404d fixes it up on demand in the same fashion as boot option paths.

**Comment by vit9696** [comment]
Assume to be resolved.
