### ISSUE TITLE
ACPI tables and SMBIOS extraction.

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#379]
It would be nice to have such gadgets. A tiny `.efi` tool would make good sense.

The dump can be placed in some directories with random UUID, for instance:
`00000000-1111-2222-3333-444444444444/Reports`

**Comment by Gengik84** [comment]
Hi @PMheart @vit9696 
I found this https://github.com/andreiw/UefiToolsPkg/tree/master/Applications/AcpiDump
I tried with shell and work
its a good way?
in future, maybe can be possibile to have new tools for OC like at clear nvram etc... for avoid to use shell?
Another tips I have found: https://www.lab-z.com/stu173dumpacpi/
I see it's can be add in shell.pkg
Thx in advance

**Comment by vit9696** [comment]
This code will not work as is, because OpenCore patches all the tables as early as it boots, and thus the dump will save older tables. I said that already in the past, but we need to implement ACPI table dumping (and e.g. SMBIOS dumping) inside OpenCore itself.

**Comment by Gengik84** [comment]
> and thus the dump will save older tables.
Do you mean dump save table w/o opencore patch?
In case it's really bad?
thx for the explanation

**Comment by vit9696** [comment]
Looks like I misworded it in the morning :), I actually meant that the dump will save OpenCore modified tables in case there are any changes in OpenCore ACPI configuration. In my opinion, this is undesired or at least not only desired as unmodified ones are also important to see.

The issue with this feature not being implemented is not some technical problem, just nobody needs it enough to care.

**Comment by Gengik84** [comment]
I understand now
Only to talk, i personally compared the table
Oc/acpidump vs clover/f4
in my case, acpi are the same.
Have a nice day
Thx @vit9696 :) for all.

**Comment by vit9696** [comment]
Actually there is an official tool made by ACPICA for ACPI:
https://www.acpica.org/downloads/uefi-support
