### ISSUE TITLE
Loading via bcfg makes systems unbootable

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#382]
Ref:
- signal `ReadyToBoot`
- https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?page=22&tab=comments#comment-2677434

The main reason that causes this problem is UI drawing. So what we need to do is to wait for ReadyToBoot event before it. (as well as fixing potential bugs if any)

We should leave a config option once it works.

**Comment by vit9696** [comment]
OpenCore is no longer a driver but an application. This issue is no longer relevant.
