### ISSUE TITLE
OpenCoreUefi: OsInfo protocol is missing.

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#383]
Ref: https://github.com/acidanthera/EfiPkg/blob/master/Include/Protocol/OSInfo.h

Used by `boot.efi` to report macOS version, while it is kind of cosmetic, and the buggy `10.12` is still reported on `10.13` and `10.14` (maybe also `10.15`).

**Comment by vit9696** [comment]
Fixed in master
