### ISSUE TITLE
Automatic formatting tooling

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#387]
To avoid code style issues we should try to implement the use of some automatic formatter. I do not think clang format can handle EDK II style, but perhaps something else, like Artistic style or Uncrustify, can do that.

**Comment by nms42** [comment]
Here is my first attempt for uncrustify. Drop useless .txt before. Warning! Needs polishing.

[uncrustify_edk2.cfg.txt](https://github.com/acidanthera/bugtracker/files/3284253/uncrustify_edk2.cfg.txt)

**Comment by vit9696** [comment]
Morning. After looking at the file... geez, that's a lot of options I must say. But compared to clang format at least it may work =)

We should probably start with formatting the whole repository and see how many changes appear afterwards, as currently the codebase in most cases is well formatted. I do not have uncrustify at the moment to try it, but could you estimate how much polishing it needs? Just a quick look makes me remember that we want to use UTF-8 everywhere with LF endings for example.

Another thing is how we run it. I am thinking of unconditional run in the CI with potential build failure upon discovering formatting differences. Could be discussible…

CC @Download-Fritz

**Comment by vit9696** [comment]
We use EDK II uncrustify now. The issue is pretty much resolved.
