### ISSUE TITLE
how can i  enabled VEGA FE FB Name KAMARANG with WEG?

### ISSUE THREAD

**Issue by ZISQO** [acidanthera/bugtracker#391]
i was using VEGA FE fb name Kamarang in Clover with 10.14.6 and 10.15 beta
now changed bootloader OpenCore but not support even if include framebuffer name in my VEGA FE SSDT file.

so WEG will patch this problem??

[DarwinDumper_3.0.4_14.06_06.52.27_iMacPro1,1_American_Megatrends_Unknown_18G48f_devgru.zip](https://github.com/acidanthera/bugtracker/files/3288259/DarwinDumper_3.0.4_14.06_06.52.27_iMacPro1.1_American_Megatrends_Unknown_18G48f_devgru.zip)

**Comment by vandroiy2013** [comment]
Hi
This not a support forum. 
Please refer to applelife.ru or insanelymac.com for support
