### ISSUE TITLE
OcSupportPkg: fatal error LNK1120: 3 unresolved externals

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#392]
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\Hostx86\x64\link.exe" /OUT:c:\users\public\projects\vbench\Build\OcSupportPkg\NOOPT_VS2017\X64\OcSupportPkg\Tests\SmbiosTest\SmbiosTestApp\DEBUG\SmbiosTestApp.dll /NOLOGO /NODEFAULTLIB /IGNORE:4001 /IGNORE:4281 /OPT:REF /OPT:ICF=10 /MAP /ALIGN:32 /SECTION:.xdata,D /SECTION:.pdata,D /Machine:X64 /LTCG /DLL /ENTRY:_ModuleEntryPoint /SUBSYSTEM:EFI_BOOT_SERVICE_DRIVER /SAFESEH:NO /BASE:0 /DRIVER /DEBUG /WHOLEARCHIVE  @c:\users\public\projects\vbench\Build\OcSupportPkg\NOOPT_VS2017\X64\OcSupportPkg\Tests\SmbiosTest\SmbiosTestApp\OUTPUT\static_library_files.lst
OcFileLib.lib(GptPartitionEntry.obj) : error LNK2001: unresolved external symbol gEfiBlockIo2ProtocolGuid
OcFileLib.lib(GptPartitionEntry.obj) : error LNK2001: unresolved external symbol gEfiDiskIoProtocolGuid
OcFileLib.lib(GptPartitionEntry.obj) : error LNK2001: unresolved external symbol gEfiDiskIo2ProtocolGuid
c:\users\public\projects\vbench\Build\OcSupportPkg\NOOPT_VS2017\X64\OcSupportPkg\Tests\CryptoTest\CryptoTestApp\DEBUG\CryptoTestApp.dll : fatal error LNK1120: 3 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\Hostx86\x64\link.exe"' : return code '0x460'
Stop.
OcFileLib.lib(GptPartitionEntry.obj) : error LNK2001: unresolved external symbol gEfiBlockIo2ProtocolGuid
OcFileLib.lib(GptPartitionEntry.obj) : error LNK2001: unresolved external symbol gEfiDiskIoProtocolGuid
OcFileLib.lib(GptPartitionEntry.obj) : error LNK2001: unresolved external symbol gEfiDiskIo2ProtocolGuid
c:\users\public\projects\vbench\Build\OcSupportPkg\NOOPT_VS2017\X64\OcSupportPkg\Tests\CryptoTest\CryptoTest\DEBUG\CryptoTest.dll : fatal error LNK1120: 3 unresolved externals

**Comment by Download-Fritz** [comment]
Fixed at https://github.com/acidanthera/OcSupportPkg/commit/e4ccb06cb63ad0dba12dfa7b4fe342210fde682b, thanks!
