### ISSUE TITLE
Hardware NVRAM on APTIO z390 motherboards

### ISSUE THREAD

**Issue by errorexists** [acidanthera/bugtracker#397]
can i get support for the native nvram for the z390

**Comment by vit9696** [comment]
We do not have that in our plans if you mean recent APTIO boards. I will not close the issue immediately in case somebody wants to research it.

**Comment by cattyhouse** [comment]
I can confirm that EmuVariableRuntimeDxe.efi works fine on Asrock B360M-HDV, just put this in OC/Drivers and load it in config.plist.
Shutdown, sleep, reboot all work, by the way i use Opencore 0.3, without this efi, they never work. 

[EmuVariableRuntimeDxe.efi.zip](https://github.com/acidanthera/bugtracker/files/3317570/EmuVariableRuntimeDxe.efi.zip)

**Comment by corint1** [comment]
what mean " load it in config.plist " , please ?

**Comment by cattyhouse** [comment]
if you put an efi  file in OC/Drivers folder, you have to add a entry in **config.plist/UEFI/Drivers**, and make sure **ConnectDrivers** is set to **YES**, otherwise this efi won't load.

**Comment by MacFriedIntel** [comment]
This has been tried and doesn't work on some Z390 boards

**Comment by corint1** [comment]
for me work some ssdt patch ... this cant try ... dont know how to set config.plist

**Comment by cattyhouse** [comment]
> This has been tried and doesn't work on some Z390 boards

Did you try via opencore 0.3? v0.2 will not work

**Comment by MacFriedIntel** [comment]
Version 0.0.2 and 0.0.3 with the NVRAM.PLIST. it's not functioning.

**Comment by cattyhouse** [comment]
> Version 0.0.2 and 0.0.3 with the NVRAM.PLIST. it's not functioning.

I did not need to use nvram.plist, just remove it. set **LegacyEnable** to **NO**

**Comment by errorexists** [comment]
thats doesnt work either

**Comment by MacFriedIntel** [comment]
I'm sorry every z390 board is different, and Gigabyte and Asus with Aptio and NVRAM issues, all ways have been used and your suggestion also. nothing works
