### ISSUE TITLE
Blur/Ring Gradient issue with KabyLake on Mojave

### ISSUE THREAD

**Issue by hieplpvip** [acidanthera/bugtracker#400]
My laptop is `Asus Zenbook UX410` with `KabyLake CPU, HD620 IGPU`.

When I open Launchpad, I notice this weird blur (Note: not my image but it's similar).

![ring](https://user-images.githubusercontent.com/17219541/60240439-2f47b880-98db-11e9-8289-58aa12152ebb.jpg)

This doesn't happen on High Sierra. It doesn't happen with second screen connected via HDMI, too.

For now, the only fix is spoof Skylake, as shown [here](https://www.tonymacx86.com/threads/help-weird-ring-like-blur-and-images-in-mojave.262566/post-1834064).

I haven't test Catalina.

**Comment by Andrey1970AppleLife** [comment]
It is known and written in Known Issues
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#known-issues
