### ISSUE TITLE
WhateverGreen: HDMI/DP audio controller is disabled

### ISSUE THREAD

**Issue by foskvs** [acidanthera/bugtracker#401]
Hi,

I've got a Coffee Lake Dell laptop (i7 8750H) with UHD 630 graphics.
When I boot with WhateverGreen, Intel HDMI/DP audio controller is disabled. If I boot with -igfxvesa (or without WhateverGreen), Intel HDMI/DP audio controller is enabled. I leave ioreg and syslog for both cases. If you need more info, let me know.

Thanks in advance

[igfxvesa.zip](https://github.com/acidanthera/bugtracker/files/3342182/igfxvesa.zip)
[whatevergreen.zip](https://github.com/acidanthera/bugtracker/files/3342183/whatevergreen.zip)

**Comment by vandroiy2013** [comment]
First of all disable Nvidia DGPU. 
Then make new reports and log

**Comment by vit9696** [comment]
Honestly, it does not seem to be a bug but rather a support request. In my opinion, go to the forums and then return with more sensible details.
