### ISSUE TITLE
Possibility to load Recovery via boot.efi?

### ISSUE THREAD

**Issue by gongzhenjeef** [acidanthera/bugtracker#403]
Currently I use FileVault2 and there's a Guest User selection on login screen after I enabled it in system preference. That one actually loads Recovery and present a web browser. 

Or if there's no input at login screen for a while (since I'm finding a mouse, tab selection don't work there), it prompts to push power button to shutdown for password recovery. In this case, vanilla macOS boot efi is entered on next boot (of course won't work). Then after choose the same entry in OC, it will skip the account selection screen, directly load Recovery and present Password Recovery utility.

In both case, any HFS driver is not needed and just ApfsDriverLoader is enough.

I found this appearance not resemble to others' because of a combined APFS structure.
I installed one 10.14.4 first to test configs, then add a new volume and restored that with a Time Machine backup. Both volume are FV2 enabled and  was updated to 10.14.5 then. In this case, Preboot and Recovery volume are shared, with different volume UUID folders containing almost identical files. I could only switch from one partition to another from System Preferences - Startup Disk and only one entry is shown in OC at any time. Also if I choose  latter volume to boot, the "Recovery (dmg)" entry is not present. I'm not sure if they are just designed as is or just bugs, maybe that need to be separated to another issue.

**Comment by vit9696** [comment]
If you absolutely need this, you can do it with UEFI Shell.

The reason for us not supporting this option is because there is no presently supported Mac that does not use dmg booting, and thus is an unsupported legacy feature. In addition to that it is also less secure.

We added a note to the manual about HFS+ driver requirement to ensure that it is less easily forgotten.
