### ISSUE TITLE
OCPath in sign.command is not correct

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#404]
Hi, if OC and Tools(not the Tools folder that contain *.efi tool) are put in the same directory, then the `OCPath` in `Tools/CreateVault/sign.command` is not correct:
presented:
`OCPath=../../../OC `
should be
`OCPath=../../OC `

**Comment by PMheart** [comment]
Renamed userspace Tools to Utilities, fixed in master.

Closing.
