### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by NathanTindle** [acidanthera/bugtracker#405]
Hi 

I would like to suggest an update to the configuration.pdf document on page 8 in section 3.6. The document lists NASM and MTOC as prerequisites to compile besides Xcode can Python3 also be added to this with links to install procedure.

Thank you for all the work so far

Nathan

**Comment by cattyhouse** [comment]
> Hi
> 
> I would like to suggest an update to the configuration.pdf document on page 8 in section 3.6. The document lists NASM and MTOC as prerequisites to compile besides Xcode can Python3 also be added to this with links to install procedure.
> 
> Thank you for all the work so far
> 
> Nathan


```
git clone https://github.com/acidanthera/OpenCorePkg 
cd OpenCorePkg
./macbuild.tool
cp Binaries/RELEASE/OpenCore-*-RELEASE.zip ~/Desktop
```

**Comment by NathanTindle** [comment]
Hi cattyhouse

Sorry but I do not understand your response could you be a bit more verbose. Considering Mojave has python 2.7 as standard.

Thank you

Nathan

**Comment by vit9696** [comment]
Hi, is that about pre-release 10.15 or what? From what I know even 10.15 still supports python 2.7.

**Comment by cattyhouse** [comment]
> Hi cattyhouse
> 
> Sorry but I do not understand your response could you be a bit more verbose. Considering Mojave has python 2.7 as standard.
> 
> Thank you
> 
> Nathan

sorry, i mean, looks like i don't need Xcode or Python3 to be installed to compile, the code does the job without problem, it (macbuild.tool) was not mentioned  in the configuration.pdf

**Comment by NathanTindle** [comment]
Hi vit9696

I was trying to compile on 10.14 and was having some issues. I had NASM and 
MTOC installed as per the documentation. I was advised on the insanleymac discord Python3 was also required




> Hi, is that about pre-release 10.15 or what? From what I know even 10.15 still supports python 2.7.

**Comment by Gengik84** [comment]
Hi, I never have issue w/o Python3
Same in 10.14 or 10.15...

**Comment by Pavo-IM** [comment]
This was my fault. I was looking into some of the compiling output and thought it was looking for Python3 version. I apologize. This ticket can be closed.

**Comment by Pavo-IM** [comment]
@vit9696 bringing this back up, because just tried to build OpenCorePkg from source and getting this error
`python3: error: unable to find utility "python3", not a developer tool or in PATH
make[1]: *** [test] Error 72
make: *** [Tests] Error 2`

**Comment by Andrey1970AppleLife** [comment]
Deprecations
Scripting language runtimes such as Python, Ruby, and Perl are included in macOS for compatibility with legacy software. Future versions of macOS won’t include scripting language runtimes by default, and might require you to install additional packages. If your software depends on scripting languages, it’s recommended that you bundle the runtime within the app. (49764202)
Use of Python 2.7 isn’t recommended as this version is included in macOS for compatibility with legacy software. Future versions of macOS won’t include Python 2.7. Instead, it’s recommended that you run python3 from within Terminal. (51097165)
https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_beta_4_release_notes
