### ISSUE TITLE
10.15beta3 does not boot with SMCBatteryManager.kext

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#408]
Notebook V3-571G
Verbose video: https://drive.google.com/file/d/1imgNHcSJ4rYuPFyQDJl5X7UAnORd5o53/view
Notebook shutdown in the end.

**Comment by usr-sse2** [comment]
```
com.apple.xpc.launchd[1] <Emergency>: Boot task failed: EndpointSecurity
com.apple.xpc.launchd[1] <Emergency>: Shutting down in 3 seconds.
```
Seems unrelated to SMCBatteryManager.

**Comment by vit9696** [comment]
Yet it is the trigger point. Presently I am not positive why, could be some validity checks within the operating system.

**Comment by vit9696** [comment]
Actually, from [release notes](https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_beta_3_release_notes?language=objc). Did you try that:

```
Known Issues
If an EndpointSecurity extension containing the NSEndpointSecurityEarlyBoot key is installed and then uninstalled, your Mac might not start. (52010655)
Workaround: Start up your Mac in single-user mode and delete the file /Library/SystemExtensions/EndpointSecurity/.early_boot.plist. You might also need to disable System Integrity Protection.
```

**Comment by Andrey1970AppleLife** [comment]
> ```
> com.apple.xpc.launchd[1] <Emergency>: Boot task failed: EndpointSecurity
> com.apple.xpc.launchd[1] <Emergency>: Shutting down in 3 seconds.
> ```
> 
> 
> Seems unrelated to SMCBatteryManager.
It is precisely confirmed by other users too. Behavior such.
