### ISSUE TITLE
HD630 is not working in 10.15

### ISSUE THREAD

**Issue by jardenliu** [acidanthera/bugtracker#411]
My laptop is XPS15 9560(7700HQ, HD630, 4K). When I use last release WhateverGreen.kext and inject `0x591b0000` , it work well in mojave. But i can't work in 10.15 dp3. Colud you please tell me how to make it work？ thanks

**Comment by cattyhouse** [comment]
upgrade everything including:
- opencore 0.03
- virtualsmc 1.05
- whatevergreen 1.30
- lilu 1.37
- applealc 1.39

**Comment by vandroiy2013** [comment]
Hi
Sorry, but this is not a support forum!
