### ISSUE TITLE
OC 0.3 hangs after recovery boot is selected

### ISSUE THREAD

**Issue by Frank-N-Furter** [acidanthera/bugtracker#412]
Hello,

first, thanks for your great work.

On a Z68 chipset computer OC 0.3, after selecting Recovery, artifacts without an error message appear on the top of the screen and the OC hangs. Screen shot attached. IgnoreInvalidFlexRatio must be set to boot. Clover works OK.

![IMG_2725](https://user-images.githubusercontent.com/22460033/60715485-66424d80-9f1d-11e9-860e-de96c9dd6311.JPG)

**Comment by vit9696** [comment]
Duplicate #389. Please report again after we fix it if the issue persists.

**Comment by PMheart** [comment]
Should this issue kind of resemble #389?

**Comment by Frank-N-Furter** [comment]
Thank you very much. Quirk AvoidHighAlloc in OC 0.4 fix this problem on Z68.
