### ISSUE TITLE
macbuild.tool does not replace old OpenCore-*-RELEASE.zip

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#413]
macbuild.tool does not replace old  OpenCore-\*-RELEASE.zip, if there are some old files in the old OpenCore-\*-RELEASE.zip , new build will not remove them.  i found this because the "Tools" folder is still there even though it was renamed to "Utilities"

Test to Reproduce:

````
## clean
rm  Binaries/RELEASE/OpenCore-v0.0.4-RELEASE.zip

## fresh build
./macbuild.tool > /dev/null 2>&1

## create a dummy file
touch test_file

## add the dummy file to zip
zip -u Binaries/RELEASE/OpenCore-v0.0.4-RELEASE.zip test_file
  adding: test_file (stored 0%)

## verify the adding
unzip -l Binaries/RELEASE/OpenCore-v0.0.4-RELEASE.zip | grep test_file
        0  07-06-2019 00:06   test_file

## run macbuild.tool again to create new release
./macbuild.tool > /dev/null 2>&1

## the test_file is still there
unzip -l Binaries/RELEASE/OpenCore-v0.0.4-RELEASE.zip | grep test_file
        0  07-06-2019 00:06   test_file
````

**Comment by vit9696** [comment]
Would you like to submit a patch? This should be as simple as removing the archive directory prior to creation. Basically we have a long lasting TODO for ocbuild project: https://github.com/acidanthera/ocbuild, which is meant to replace macbuild in all projects, but for now we can patch immediate macbuild issues. It will be nice if you could find anyone to work on ocbuild as well.

**Comment by cattyhouse** [comment]
i don't know how to submit a patch, but this has been verified working on both Release and Debug version:
...... 
pushd tmp || exit 1
**zip -d ../"OpenCore-v${ver}-${2}.zip" "*" >/dev/null 2>&1**
zip -qry ../"OpenCore-v${ver}-${2}.zip" * || exit 1
popd || exit 1
.....

it will empty the old zip file before archiving new zip.

**Comment by cattyhouse** [comment]
update:
I read `man zip` again and found that there is a --filesync (-FS) option, this will simply do the job:

pushd tmp || exit 1
zip -qry **-FS** ../"OpenCore-v${ver}-${2}.zip" * || exit 1
popd || exit 1

Sorry for disturbing.

**Comment by vit9696** [comment]
I think `-FSqry` is indeed the best way to do it. For simple pull requests you can edit files in GitHub UI: https://github.com/acidanthera/OpenCorePkg/blob/master/macbuild.tool
![Снимок экрана 2019-07-05 в 22 19 30](https://user-images.githubusercontent.com/4348897/60741652-f65eb200-9f72-11e9-97c3-4af9ad1e343f.png)

Please provide the change for all affected repositories.

**Comment by cattyhouse** [comment]
thank, done.
