### ISSUE TITLE
Useful names for binary releases

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#414]
Some of packages use names like "1.3.7.DEBUG.zip" for released binaries. Could it be possible to extend name, for example, to "Lilu-1.3.7.DEBUG.zip"?

**Comment by vit9696** [comment]
This makes good sense to me, but it is a good question which format to follow. Currently it is like `1.3.9 (RELEASE).zip`, but GitHub converts it to remove spaces. Perhaps we should use `AppleALC-1.3.9-RELEASE.zip` instead?

@Andrey1970AppleLife @Download-Fritz @vandroiy2013 & others, what do you think?

**Comment by PMheart** [comment]
Agreeing with the format of @vit9696. ^^

**Comment by vandroiy2013** [comment]
+1

**Comment by nms42** [comment]
> This makes good sense to me, but it is a good question which format to follow. Currently it is like `1.3.9 (RELEASE).zip`, but GitHub converts it to remove spaces. Perhaps we should use `AppleALC-1.3.9-RELEASE.zip` instead?

LGTM (Looks Good To Me)

**Comment by vit9696** [comment]
Right, then could you please provide patches to change the naming in all affected repositories?

**Comment by PMheart** [comment]
Done.
