### ISSUE TITLE
HD630 is not working with VirtualSMC 1.0.6

### ISSUE THREAD

**Issue by ZISQO** [acidanthera/bugtracker#415]
![637eec74bd3f8c437e87f23890c07f90](https://user-images.githubusercontent.com/50421769/60764224-a5f56a80-a0c0-11e9-936c-4b98b2176e1b.jpg)

i had a Z390 DESIGNARE, i7-8700k and i9-9900K, UHD 630
but HD630 is can't working H264 Encoding.

(fakesmc is working fine)

![eac6158b71dc32b4cff29b93153343b6](https://user-images.githubusercontent.com/50421769/60764246-1ef4c200-a0c1-11e9-9bfb-f09c1c444193.jpg)
* every kexts was tested by newer

10.14.5 and 10.15 PB3 is same issue

**Comment by cattyhouse** [comment]
i can confirm it works on my i5-8400 UHD 630

````
$ kextstat | egrep "VirtualSMC|WhateverGreen"
   38    0 0xffffff7f85619000 0x6a000    0x6a000    as.vit9696.WhateverGreen (1.3.0) 2281A12E-A7C3-3968-BA4A-64D60CBA9AA6 <37 13 8 6 5 3 2 1>
   40    2 0xffffff7f85600000 0x19000    0x19000    as.vit9696.VirtualSMC (1.0.6) BD17B77E-5891-37D2-BF8F-8BE6A6C95B4A <37 12 8 6 5 3 2 1>
````

````
$ VDADecoderChecker
GVA info: Successfully connected to the Intel plugin, offline Gen95
Hardware acceleration is fully supported
````

````
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G59b
````

**Comment by vandroiy2013** [comment]
Working well to. 
![Снимок экрана 2019-07-07 в 10 25 39](https://user-images.githubusercontent.com/8144780/60765330-b813e080-a0a1-11e9-9f57-fc10c2deabd1.png)
![Снимок экрана 2019-07-07 в 10 25 09](https://user-images.githubusercontent.com/8144780/60765331-bb0ed100-a0a1-11e9-93ec-f31f7d75a02a.png)

@ZISQO Provide detailed reports. DarwinDumper, IOreg, Clover/OpenCore log etc...
One with VirtualSMC another with FakeSMC.

**Comment by vit9696** [comment]
VirtualSMC does not affect hardware decoding abilities. While I can imagine some bug in some product given the description, currently it is not provided. I.e. we only are given a problem of something not working somewhere. This does not fit the bugtracker, so please proceed to the support forums, and return back if a real bug with technical details that needs developer team attention is found. Thanks.

**Comment by ZISQO** [comment]
@vit9696 that's right that was occured just because not include a boot flag setup for fixing AppleGVA framework. : )

finally it's working fine! thx!
