### ISSUE TITLE
Build VoodooPS2Controller with XCode-Beta in Catalina Success but not work

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#416]
I have built VoodooPS2Controller.kex with XCOde-Beta.app in Catalina, kext is successed built but not work in Mojave. Is this problem because i compiled it with XCode-Beta.app??

**Comment by vit9696** [comment]
To fix that VoodooPS2 needs the following patches basically:
https://github.com/acidanthera/Lilu/commit/838dee484e2f23758e6d7db021b0bef2dd4552be
https://github.com/acidanthera/Lilu/commit/700cf04e9fb0f87472c578ed0220125cb98202b7

Question is, do we actually want them in VoodooPS2? If so, then we probably should add them to https://github.com/acidanthera/IntelMausi as well, and potentially use legacy IOServhice.h. Other than that I believe VoodooPS2 badly needs Travis CI setup, but it is sort of pending.

@usr-sse2 @kprinssu what do you think?

If there are no objections, @andreszerocross, could you please submit patches to the issue? If not could someone else do it?

**Comment by kprinssu** [comment]
@vit9696 it shouldn't be problem? I do not see anything wrong with the preprocessor declarations. The worst case is that we will need to include this piece of code until Sierra, High Sierra, and Mojave are end of life'd. 

In regards to a CI pipeline, it is definitely a nice to have.

**Comment by vit9696** [comment]
Resolved in master.
