### ISSUE TITLE
Not loading kernel

### ISSUE THREAD

**Issue by soto2080** [acidanthera/bugtracker#417]
As title, I tried 0.0.3 release, and I stuck here.
![photo_2019-07-09_22-37-03](https://user-images.githubusercontent.com/5404430/60901546-bd8b4980-a2a0-11e9-80cc-dad91de58031.jpg)
And I think that my config is fine.
Here is my config.
[OC.zip](https://github.com/acidanthera/bugtracker/files/3373707/OC.zip)

Spec:
CPU:1230V3
MB:Asus Z97-Pro Gamer
VGA: RX580 8G
OS:10.15 installed on sata ssd.

**Comment by vandroiy2013** [comment]
Hi. 
This is not a support forum. Refer to insanelymac.com or applelife.ru

**Comment by cattyhouse** [comment]
@vandroiy2013 the OC files are adopted to the latest and are all from Acidanthera repo. the config.plist has been checked again and again, still showing error messages like in the picture, checked the error messages, it seems to be Apito Memory issue. the weird thing is Clover boots fine, with same kexts and *.efi files, no special patches and AMLs. isn't it worth checking? the OS is macOS 10.15 beta3. i'm a friend helping him, we have tried many options according to Configuration.pdf with no luck
