### ISSUE TITLE
Dell XPS 9560 USB 0.0.4 Not Working

### ISSUE THREAD

**Issue by buhlaze** [acidanthera/bugtracker#419]
USB ports (XHC) where working fine in 0.0.3. When I changed to 0.0.4 with the same configuration, things such as my mouse stopped working and bluetooth is not working. com.apple.driver.usb.AppleUSBXHCI items (HS01, SS01, etc...) are not loading on this Dell XPS 9560 laptop.

**Comment by buhlaze** [comment]
USB ports (XHC) where working fine in 0.0.3. When I changed to 0.0.4 with the same configuration, things such as my mouse stopped working and bluetooth is not working. com.apple.driver.usb.AppleUSBXHCI items (HS01, SS01, etc...) are not loading on this Dell XPS 9560 laptop.

**Comment by Andrey1970AppleLife** [comment]
The text is by default intended for reading you.

**Comment by vit9696** [comment]
> with the same configuration

You have to update your configuration according to differential documentation bundled with the release. For example, ACPI directory changed, and some keys are now written differently. Not a bug.

**Comment by buhlaze** [comment]
I see no chances it all looks the same
