### ISSUE TITLE
Whatevergreen: Dell XPS 7590, brightness control no effect (i7-9750H, OLED display)

### ISSUE THREAD

**Issue by Sevendaye** [acidanthera/bugtracker#423]
Hello, 

I have a bug with my config, I have the sidebar display in the display settings, but when I want to change the brightness has no effect.

I tried different files (PNLF.aml, PNLCFL.aml) and try to change GFX0 to IGPU, but no effect.

(Dell XPS 7590, Intel I7-9750H, Intel HD630(0X3E9B000), 4K OLED Display)

<img width="1920" alt="Screenshot 2019-07-15 at 19 28 34" src="https://user-images.githubusercontent.com/48520590/61294198-94554680-a7d5-11e9-8306-dfe83c5f5513.png">

**Comment by vit9696** [comment]
Not a support forum, sorry.

**Comment by buhlaze** [comment]
I have the same problem on my Dell XPS screen.  The controls are there, but brightness is not changing on my screen
