### ISSUE TITLE
Multiplied 'OC Boot' options in Boot Menu

### ISSUE THREAD

**Issue by Arabaku** [acidanthera/bugtracker#425]
The 'OC Boot' option adds one when I boot my computer once every time. SomeOne in forum met the same issue. I don't know whether it is my own mistake.
![issue](https://user-images.githubusercontent.com/27410613/61432477-2d659800-a963-11e9-8484-2c4ce2a53b07.jpeg)

**Comment by vit9696** [comment]
Fixed in latest OC.
