### ISSUE TITLE
Is there any explicit milestone/release schedule?

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#429]
See subject, please. I can't find one.

**Comment by vit9696** [comment]
Currently this information is not hosted on github. Our next release is scheduled to the beginning of August with the exact date being discussed. We pretty much succeeded in moving to monthly releases, so all projects with changes are included.

We also do not publish the information on the bugs we consider blocking for the release, although priority labels give some idea of this.

Do you think that more transparency could be more beneficial here? Or perhaps you want to suggest something for tracking?

**Comment by nms42** [comment]
Well,
any schedule will be good as long as it **explicit**.

**Comment by vit9696** [comment]
Well, it is explicit just unavailable for public, thus the question pretty much. Should we actually provide information on that.

**Comment by nms42** [comment]
Just make it public. That allows general public to do some rudimentary planning.

**Comment by vit9696** [comment]
Ok.
