### ISSUE TITLE
Empty OpenCore Log Files

### ISSUE THREAD

**Issue by MacProDude** [acidanthera/bugtracker#431]
Please stop and read this carefully. Otherwise your issue will be left **unaswered** and **closed**.

Issue tracker is _not_ a support forum, and if you have installation or usage problems, try asking your questions on [InsanelyMac.com](https://www.insanelymac.com/forum/643-lilu-and-its-plugins/) or [AppleLife.ru](https://applelife.ru/forums/xakintosh.67/). There could also be local communities providing Acidanthera Project support in your native language.

For example, if you have an issue with AppleALC and you have not working sound, and you **cannot** offer new resources that fix the problem for you, you should go to the **support forums**. Here there are no people who create custom audio resources, or who deal with installation issues.

When to use issue tracker:
* You have new resources or patches to add but cannot make a pull request
* You have kernel panics, crashes, hangs
* You want to discuss technical or legal stuff

_If you have a kernel panic, please ensure that you have a DEBUG version of the extension and you have `-v keepsyms=1 debug=0x100` boot arguments added. On 10.13 or higher to avoid kext names scrolling over the panic log you should also [patch your kernel](https://applelife.ru/posts/686953)._

**Comment by MacProDude** [comment]
<img width="1548" alt="Screenshot 2019-07-22 at 23 47 20" src="https://user-images.githubusercontent.com/52838566/61670299-1b755380-acdb-11e9-8e43-6519480a98e8.png">
Is there a way to stop writing a log file if there is nothing to add to it, instead of creating lots of empty files? i understand logs in this way are good for comparing changes. but empty files makes no sense.

**Comment by vit9696** [comment]
You have set Target value to log to file. For release builds only errors and warnings will be logged.

**Comment by errorexists** [comment]
so then after each reboot there will be a new log file? out of curiosity can it not just use one or some settings are missing?
