### ISSUE TITLE
VoodooPS2 panics on 10.15 when built with Xcode 10 or older in release config

### ISSUE THREAD

**Issue by Goldfish64** [acidanthera/bugtracker#432]
VoodooPS2 will fail to load and panic the system during boot if built with Xcode 10 or older in a release configuration. A debug configuration appears to work fine, and compiling with Xcode 11 also appears to work fine in both debug and release configurations.

The exact fault point seems to be the same each time, with the panic log attached:

```panic(cpu 2 caller 0xffffff801e6666aa): Kernel trap at 0x000000001e200000, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x000000001e200000, CR3: 0x0000000023131000, CR4: 0x00000000003626e0
RAX: 0xffffff7fa2310a88, RBX: 0xffffff8030b1c990, RCX: 0x0000000000000001, RDX: 0x0000000000000002
RSP: 0xffffff812afabcf8, RBP: 0xffffff812afabd60, RSI: 0x0000000000000001, RDI: 0xffffff8031344d40
R8:  0xffffff801eea3360, R9:  0x0000000000000000, R10: 0x0000000000000000, R11: 0xffffff8031519360
R12: 0xffffff8031699740, R13: 0xffffff801f06b1c8, R14: 0xffffff8031344d40, R15: 0x0000000000000000
RFL: 0x0000000000010246, RIP: 0x000000001e200000, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x000000001e200000, Error code: 0x0000000000000010, Fault CPU: 0x2, PL: 0, VF: 1

Backtrace (CPU 2), Frame : Return Address
0xffffff812afab750 : 0xffffff801e53d5fb mach_kernel : _handle_debugger_trap + 0x47b
0xffffff812afab7a0 : 0xffffff801e674815 mach_kernel : _kdp_i386_trap + 0x155
0xffffff812afab7e0 : 0xffffff801e6662fb mach_kernel : _kernel_trap + 0x4fb
0xffffff812afab830 : 0xffffff801e4e3bb0 mach_kernel : _return_from_trap + 0xe0
0xffffff812afab850 : 0xffffff801e53cce7 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff812afab950 : 0xffffff801e53d0cb mach_kernel : _panic_trap_to_debugger + 0x21b
0xffffff812afab9a0 : 0xffffff801ecce2a9 mach_kernel : _panic + 0x61
0xffffff812afaba10 : 0xffffff801e6666aa mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff812afabb90 : 0xffffff801e6663ac mach_kernel : _kernel_trap + 0x5ac
0xffffff812afabbe0 : 0xffffff801e4e3bb0 mach_kernel : _return_from_trap + 0xe0
0xffffff812afabc00 : 0x1e200000 
0xffffff812afabd60 : 0xffffff7fa2307923 as.acidanthera.voodoo.driver.PS2Trackpad + 2339
0xffffff812afabd90 : 0xffffff7fa230edeb as.acidanthera.voodoo.driver.PS2Trackpad : __ZN25ApplePS2SynapticsTouchPad11setModeByteEh + 0x1d9
0xffffff812afabdb0 : 0xffffff801ec1a0c9 mach_kernel : __ZN9IOService14startCandidateEPS_ + 0xf9
0xffffff812afabe10 : 0xffffff801ec19d4b mach_kernel : __ZN9IOService15probeCandidatesEP12OSOrderedSet + 0xc5b
0xffffff812afabef0 : 0xffffff801ec18f5e mach_kernel : __ZN9IOService14doServiceMatchEj + 0x2ce
0xffffff812afabf50 : 0xffffff801ec1b37d mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x15d
0xffffff812afabfa0 : 0xffffff801e4e313e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         as.acidanthera.voodoo.driver.PS2Trackpad(2.0.2)[692B5E3F-0A2C-3CAA-97DA-611D4DAE8331]@0xffffff7fa2307000->0xffffff7fa231cfff
            dependency: as.acidanthera.voodoo.driver.PS2Controller(2.0.2)[9ECE3190-A68D-3DA6-87C1-D24FD24EC797]@0xffffff7fa22e7000
            dependency: com.apple.iokit.IOHIDFamily(2.0.0)[17500034-D82D-34CA-B36A-EA40AAFDE78F]@0xffffff7f9f2cf000

BSD process name corresponding to current thread: kernel_task
Boot args: -v dart=0 debug=0x100 keepsyms=1 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 19.0.0: Thu Jul 11 18:37:36 PDT 2019; root:xnu-6153.0.59.141.4~1/RELEASE_X86_64
Kernel UUID: 94E541DB-A7EA-3FB9-AE8A-75F775E67241
Kernel slide:     0x000000001e200000
Kernel text base: 0xffffff801e400000
__HIB  text base: 0xffffff801e300000
System model name: MacBookAir7,2 (Mac-937CB26E2E02BB01)

System uptime in nanoseconds: 2721797671



```

**Comment by vit9696** [comment]
Using kxld (and /Library/Extensions) fails to load VoodooPS2Trackpad as well with the following error message:
```
(kernel) kxld[as.acidanthera.voodoo.driver.PS2Trackpad]: The following symbols are unresolved for this kext:
(kernel) kxld[as.acidanthera.voodoo.driver.PS2Trackpad]: __ZN11IOHIDDevice22_RESERVEDIOHIDDevice14Ev
(kernel) kxld[as.acidanthera.voodoo.driver.PS2Trackpad]: __ZN11IOHIDDevice22_RESERVEDIOHIDDevice15Ev
```

The crash seems to be caused by changed IOHIDDevice interface with select reserved symbols replaced by actual interfaces:
```C++
    OSMetaClassDeclareReservedUnused(IOHIDDevice, 14);
    OSMetaClassDeclareReservedUnused(IOHIDDevice, 15);
```
is replaced with
```C++
    /*! @function conformsTo
     @abstract Checks if a device conforms to a certain usage page/usage.
     @discussion Iterates through the usages returned from newDeviceUsagePairs
     function and checks for matching usages.
     @result true if the device conforms to the specified usage page/usage. */
    OSMetaClassDeclareReservedUsed(IOHIDDevice, 14);
    virtual bool conformsTo(UInt32 usagePage, UInt32 usage);
    
    /*! @function completeReport
     @abstract complete reports for DriverKit drivers
     @discussion This method only used by DriverKit driver
     created. */
    OSMetaClassDeclareReservedUsed(IOHIDDevice, 15);
    virtual void completeReport(OSAction * action, IOReturn status, uint32_t actualByteCount);
```

I am not sure why (and how) it fails in both cases, but it appears to be quite interesting behaviour. 
- For kxld it may be because IOHIDDevice virtual table (`__ZTV11IOHIDDevice`) is implemented in IOHIDFamily instead of the kernel, and this somehow breaks padslot patching.
- For OpenCore I am quite clueless.

I attach several variants of the kext with dSYM files: [voodoops2.zip](https://github.com/acidanthera/bugtracker/files/3423353/voodoops2.zip).

- xc10-sdk14 - Xcode 10.3 and macOS SDK 10.14
- xc11-sdk14 - Xcode 11 beta 4 and macOS SDK 10.14
- xc11-sdk15 - Xcode 11 beta 4 and macOS SDK 10.15
- xc11-sdk15-nonew - Xcode 11 beta 4 and macOS SDK 10.15 with unused reverted

Only xc11-sdk15 works, all other have consistently same behaviour (panic with OpenCore and undefined reference error with kxld).

**Comment by vit9696** [comment]
Resolved in master.

For whatever reason the authors of MT2 code did not explicitly export their OSObject-based classes. This is critical as release binaries have all unexported symbols stripped, and thus virtual table symbols become invisible to the prelinker.

Virtual table symbols are special, as they allow to implement binary interfaces through padslots. Once macOS developers add a new virtual function to some OSOject-based class they remove a specially ordered reserved symbol. Prelinker is supposed to track the symbols by `RESERVED` keyword and replace the reserved symbols with newly added ones upon running in updated environment. If virtual table symbols are stripped, padslots cannot be patched.

OpenCore does not error about it, but it effectively leaves several symbols pointing to nowhere, and this is expected for performance reasons. KXLD provides an error on the matter.

CC @coolstar, @kprinssu, @alexandred, @ben9923

**Comment by kprinssu** [comment]
I have addressed the issue in VoodooI2CHID (https://github.com/kprinssu/VoodooI2CHID/commit/47f93f4fb81c2f931c6bc90e828e4ef491a26ee4). Other VoodooI2C may contain the issue and I’ll push similar fixes later tonight.
