### ISSUE TITLE
VoodooPS2: Need improvements on using Caps Lock key to change input source

### ISSUE THREAD

**Issue by stevezhengshiqi** [acidanthera/bugtracker#435]
After enabling `Use the Caps Lock key to switch to and from ABC`, the input sources can't be changed by pressing Caps Lock, and there's an inconsistency issue between Caps Lock button light and lowercase or uppercase status.

However, in some circumstances, using Caps Lock to change input sources is working, like the address bar in `Safari.app`, `Xcode`, or editing markdown files, etc. In these circumstances, `Use the Caps Lock key to switch to and from ABC` option can't control Caps Lock's behavior - pressing Caps Lock key will always shift input sources.

Related issues in Rehabman's repo:
https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/issues/154
https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/issues/142

This issue happened when using Simplified Chinese and English input sources.

**Comment by vit9696** [comment]
https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/issues/142#issuecomment-383640307
https://github.com/acidanthera/VoodooPS2/blob/master/Docs/ACPI/SSDT-Swap-LeftControlCapsLock.dsl

**Comment by stevezhengshiqi** [comment]
@vit9696 Thank you for pointing out. It’s a good work around, but is it possible that the Caps Lock key can be used to change input source just like a native Mac?

**Comment by vit9696** [comment]
Well, the thing does not work well for me even on USB keyboard. The related cause of the issue seems to rest [here](https://github.com/acidanthera/VoodooPS2/blob/78f7704/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp#L1747). I will reopen the issue, but we have no plans to work on it any soon.

**Comment by frol** [comment]
I have updated [the workaround](https://github.com/acidanthera/VoodooPS2/blob/78f7704/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp#L1747-L1767) to the following (I just assumed that Sierra and High Sierra require the "full" workaround while I can only test on Mojave and I need to only fire key_down + key_up):

```diff
diff --git a/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp b/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp
index ee3bcaf..d7f4fb4 100644
--- a/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp
+++ b/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp
@@ -1747,13 +1747,17 @@ bool ApplePS2Keyboard::dispatchKeyboardEventWithPacket(const UInt8* packet)
     //REVIEW: work around for caps lock bug on Sierra 10.12...
     if (adbKeyCode == 0x39 && version_major >= 16)
     {
-        if (goingDown)
+        // Mojave 10.14 only needs a part of the workaround:
+        // https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/issues/142#issuecomment-529813842
+        if (goingDown || version_major >= 18)
         {
-            static bool firsttime = true;
             clock_get_uptime(&now_abs);
             dispatchKeyboardEventX(adbKeyCode, true, now_abs);
             clock_get_uptime(&now_abs);
             dispatchKeyboardEventX(adbKeyCode, false, now_abs);
+        }
+        if (goingDown && version_major < 18) {
+            static bool firsttime = true;
             if (!firsttime)
             {
                 clock_get_uptime(&now_abs);
```

Should I send a PR?

Here is the kext: 
[VoodooPS2Controller-2.0.3-frol-RELEASE.zip](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/files/3594895/VoodooPS2Controller-2.0.3-frol-RELEASE.zip)

I can now use CapsLock to switch language layouts (configured via native MacOS preferences) and Ctrl + CapsLock toggles the upper/lower-case modes on my Lenovo y50-70 Mojave!

Thank you for your hard work!

**Comment by usr-sse2** [comment]
I think that version checks are not needed. Sierra and High Sierra had issues when using 'full' workaround but it was still better than having a four-state Caps Lock button without the workaround.

**Comment by usr-sse2** [comment]
@frol It works, thanks!
