### ISSUE TITLE
Display flashes during second stage of booting [AMD GPU]

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#438]
Hi

As you may already know these 2 problems on AMD GPU, during the second stage of booting, there is [one second display flash](https://www.insanelymac.com/forum/topic/335953-screen-flashes-white-for-a-second-during-boot/), some times the whole display, some times part of the display, and it seems happen only on AMD GPU, both 10.13, 10.14, 10.15 are affected. ~~Since 10.14.5, it brings purple lines during the second stage of booting.~~

This is NOT A BUG of WhateverGreen, since with or without it, the 2 issues remain, i'm just hoping if you guys could fix them via WhateverGreen patch? thanks

**Comment by vandroiy2013** [comment]
"Purple lines" are already fixed in master.

**Comment by cattyhouse** [comment]
> "Purple lines" are already fixed in master.

Great, would you mind pointing out the related commits?  i'm using whatevergreen build on git pull on 7/23, the purple lines are still there.

**Comment by vandroiy2013** [comment]
https://github.com/acidanthera/WhateverGreen/commit/bcd3f2ef73266f4a320ccfd0686bef2a969b2bde

**Comment by cattyhouse** [comment]
> acidanthera/WhateverGreen@bcd3f2e

thanks, most of the purple lines are gone, there is still one dotted line (dots ......... with different color ) there though.

**Comment by JayMonkey** [comment]
Updated Lilu to 1.3.8 and WhatEverGreen to 1.3.1 and all pink/purple artefacts on boot screen have gone on my video edit system (Z97 + i7 4790K + Vega 64).

Also updated all other plugins .. all working great

Many thanks to all the Devs for this latest point release.

Cheers
Jay

**Comment by cattyhouse** [comment]
> > [acidanthera/WhateverGreen@bcd3f2e](https://github.com/acidanthera/WhateverGreen/commit/bcd3f2e)
> 
> thanks, most of the purple lines are gone, there is still one dotted line (dots ......... with different color ) there though.

on macOS 10.15 (19A578c), all purple lines are gone. Thanks for the great work!
