### ISSUE TITLE
Interrupt overflow in VSMC/SMCLightSensor

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#440]
When SMCLightSensor is inactive (e.g. in single user mode) for some reason we get a ton of `postInterrupt reserve overflow` messages. This needs to be investigated and potentially needs a workaround to prevent blockage of interrupt submission.

@usr-sse2 I mark this as high, as it may cause issues reading SMC keys. It will be great if this is fixed before August release.

**Comment by usr-sse2** [comment]
acidanthera/VirtualSMC@2f6ca36
