### ISSUE TITLE
OC and NVME M2 disk related problem

### ISSUE THREAD

**Issue by fabiosun** [acidanthera/bugtracker#443]
Hi
My config
Asus x299 WS Sage 10g
Intel 7980 xe
960 pro 1 tb Nvme disk (ntfs windows 10 pro)
Sabrent 1 Tb OSX High Sierra latest update
Samsung 850 pro 512 Gb (with OC boot Debug EFI)

Hi attach my config, open core log files and Apple report file after Kernel panic

Summary:
I can boot OC only one time. if I reboot or I shutdown my system and restart I have a kernel panic with an error on IONVMEFamily
If I clear nvram every time before choosing a booting option system starts always well without problem
How can I help to debug this behavior in a better way?

With clover I have no problem and in both bootloaders I have a pretty clean config.plist I think
Thank you
[OC_and_Apple log.zip](https://github.com/acidanthera/bugtracker/files/3461178/OC_and_Apple.log.zip)

**Comment by vit9696** [comment]
Hi, I am sorry, but this one is unrelated to OpenCore. It could be that OpenCore kext injection triggers the unlucky race condition for you, but that does not change the fact that the bug is clearly in IONVMEFamily itself. Sorry for not being able to help you.

**Comment by fabiosun** [comment]
Hi vit9696 thank you for your answer
I can't discuss your statement because I have no skill to do it. I would like only to say the also with OC I can boot fine one time then If I reboot problem happens
With other boot loader I have no this behavior . so maybe other boot loader patches some things I can't understand ;)
Thank you again
