### ISSUE TITLE
AptioMemoryFix Can't Unlock Slide Support for Safe Mode

### ISSUE THREAD

**Issue by mrmiller** [acidanthera/bugtracker#444]
Motherboard: Supermicro X11DAi-N
CPU: 2x Xeon Gold 6136

I'm attempting to boot the 10.15 beta installer. I am able to boot into 10.13 on this system, though I had trouble booting into the 10.13 installer as well at the time. For 10.15, AptioMemoryFix fails in `UnlockSlideSupportForSafeMode` and emits `Failed to find first BOOT_MODE_SAFE | BOOT_MODE_ASLR sequence` in the log.

[CustomSlide.c:503](https://github.com/acidanthera/AptioFixPkg/blob/031ed46cb5da0141a1f1af18a90dbd82d1b561a9/Platform/AptioMemoryFix/CustomSlide.c#L503)

**Comment by vit9696** [comment]
Hi, this issue can only cause issues entering safe mode on systems that cannot normally boot with `slide=0`, it cannot affect the installer. Thanks for the report though, we will handle it as time permits.

**Comment by mrmiller** [comment]
Hmm... I'd assumed it was hanging without booting because of that. Must be something different then. I'm not sure where or how to begin reporting this other issue then. I'm assuming I'm having trouble related to the memory map on this motherboard and configuration (which was a definite issue with the 10.13 installer).

**Comment by Download-Fritz** [comment]
Likely fixed at https://github.com/acidanthera/AptioFixPkg/commit/c42a05bb1cdeb9ec56729b9975fbc53e4cacecc3
@mrmiller Could you please confirm functionality?

**Comment by mrmiller** [comment]
It's a little hard to tell because it looks like AptioMemoryFix got torn asunder and I'm not sure where that code lives now. I'm not getting the warning anymore but I was only seeing it if I built a debug version with verbose logging enabled anyhow.

Let me know the best way for me to test it against the Open Core HEAD and I'll give it a spin.

**Comment by vit9696** [comment]
Yes, sorry, the commit is right int terms of fix logic, but AMF is not a thing, and it lives in OcAppleBootCompatLib, where this fix is already applied. You basically need to

- update to OpenCore HEAD
- install FwRuntimeServices from AppleSupportPkg
- set new Booter Quirks. For you SetupAppleMap, SetupAppleSlide, EnableAppleSmSlide should hopefully be enough, but you could always add more

I will update the docs soon to include these details.
Also please note that the change is fixing safe mode (-x) it will unlikely fix the rest of your issues.

**Comment by vit9696** [comment]
KASLR slide unlock in safe mode through `EnableAppleSmSlide` is confirmed working on both 10.14 and 10.15. Closing.

**Comment by mrmiller** [comment]
> Yes, sorry, the commit is right int terms of fix logic, but AMF is not a thing, and it lives in OcAppleBootCompatLib, where this fix is already applied. You basically need to
> 
>     * update to OpenCore HEAD
> 
>     * install FwRuntimeServices from AppleSupportPkg
> 
>     * set new Booter Quirks. For you SetupAppleMap, SetupAppleSlide, EnableAppleSmSlide should hopefully be enough, but you could always add more
> 
> 
> I will update the docs soon to include these details.
> Also please note that the change is fixing safe mode (-x) it will unlikely fix the rest of your issues.

Thanks for the writeup! Looking forward to seeing the documentation for these features when it's ready. Somehow I was able to boot without any of them enabled though in HEAD.

I was able to fix the other issues which were unrelated.
