### ISSUE TITLE
128kb journal overflow error "Assert...."

### ISSUE THREAD

**Issue by ctich** [acidanthera/bugtracker#445]
hi, OpenСore team
If the log size is 128 KB, this leads to an error, as on the screen, with a size of 256 KB  _(#define OC_LOG_BUFFER_SIZE            BASE_128KB -- > #define OC_LOG_BUFFER_SIZE            BASE_256KB)_ there is no error, but an error appears if you try to perform an “CleanNvram” in the OC GUI.
The error appears only when using versions Debug and Noopt.
![IMG_7335](https://user-images.githubusercontent.com/42576487/62568456-deda5800-b895-11e9-824d-d0ba44e5a0d4.jpg)
PC: intel i5-7400 Asus Z270p.

**Comment by vit9696** [comment]
Relevant tianocore bug: https://bugzilla.tianocore.org/show_bug.cgi?id=2054

**Comment by losinka** [comment]
By long press ESC after the computer start:
![59588380232__9E36831A-207A-4433-BDB4-D87E4D1C339E](https://user-images.githubusercontent.com/8762577/69180631-e6083780-0b0d-11ea-9b5f-74a70aa209f9.jpeg)
