### ISSUE TITLE
Potential PlatformInfo.SMBIOS.PlatformFeature failsafe value overflow

### ISSUE THREAD

**Issue by tonyarnold** [acidanthera/bugtracker#446]
Hi folks, while reading the Configuration PDF, I noticed that `PlatformInfo.SMBIOS.PlatformFeature` is documented as a 32-bit integer, however the default value is `0xFFFFFFFF`. Doesn't this overflow? (This resolves to a literal value of `4294967295`).

https://github.com/acidanthera/OpenCorePkg/blob/60b42e5d3b836c827621115079ee597b244c474d/Docs/Configuration.tex#L2754

Am I misunderstanding something here, or should one of these values be modified?

**Comment by vit9696** [comment]
Hi, this is correct. The value is read as unsigned, so it does not overflow. Some editors may indeed display/store it as negative, but conversion from negative to unsigned is implementation defined behaviour, which works fine on x86.

**Comment by tonyarnold** [comment]
Ah yep, you're right - sorry for not reading that more closely. I missed the "unsigned". Thanks!

**Comment by vit9696** [comment]
No problem, always thx for auditing the docs and code.

**Comment by vit9696** [comment]
Actually I was unable to find any signed integer in both docs and [configuration itself](https://github.com/acidanthera/OcSupportPkg/blob/master/Include/Library/OcConfigurationLib.h). All values apparently are unsigned, and I am not positive writing `N bit unsigned` is any better than `N bit signed` in the situation when the amount of the latter is much less than the former. I am open for suggestions, but I am not sure whether adding suffixes will even make things simpler in terms of interpretation.

**Comment by tonyarnold** [comment]
Yeah, I guess to end users that's unimportant. The property list decoding will take care of any numeric conversions for them. 

Ok, that's fine - I can always look at the source to work this out, and my use case isn't "normal" 👍
