### ISSUE TITLE
Cahnge place for AvoidHighAlloc in config

### ISSUE THREAD

**Issue by Frank-N-Furter** [acidanthera/bugtracker#447]
Thanks for your great work. Wouldn't it be more logical to move AvoidHighAlloc from the UEFI Quirks section to the Booter Quirks section?

**Comment by vit9696** [comment]
This quirk is not specific to macOS, it just happens to currently affect OpenCore dmg loader due to firmware allocator bug. There is no guarantee it will not affect anything else. Configuration location is ok.
