### ISSUE TITLE
Safe mode KASLR allocation issues with AvoidHighAlloc

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#449]
Currently with `AvoidHighAlloc` set to `YES` several boards, including GA Z77X-UD3H, may fail to load recovery image with the usual page allocation failure error:

![Screenshot 2019-08-08 at 08 25 48](https://user-images.githubusercontent.com/4348897/62706068-68ee0200-b9f7-11e9-9b39-a2364ebea2e0.jpeg)

This is pretty much expected, because AvoidHighAlloc is risky per se, but the situation is made worse by unavailable 0 slide:
```
06:742 00:019 OCABC: Only 248/256 slide values are usable!
06:743 00:001 OCABC: Valid slides - 8-255
```

The interesting part is that holding `shift` key and trying to load recovery pretty much always fails, while `-x` boot argument works just fine. Even with the manually specified slide equivalent to the one generated with failing boot with held `shift` key. Perhaps we are colliding with firmware pool allocator, which then allocates memory in the area belonging to the kernel.

While everything prior to Skylake is honestly legacy, I would not say we are ready to entirely abandon the support Ivy Bridge support, so perhaps the situation here can be improved in spare time. Among the potential routes I see:

- Trying not to alloc in KASLR area within DMG loader
- Detecting safe mode in custom slide implementation and choosing a lowest available value
- Trying to coordinate DMG loader allocation strategy with custom slide somehow else…

I asked droplets to post a list of slides useable with `-x` in boot arguments and held `shift` key, so that we could have a better idea how much memory we have.

**Comment by Download-Fritz** [comment]
How far up can the kernel even go with the current slide implementation?

It might be possible to revive the original idea of the allocation strategy, to allocate, in biggest possible pieces, as high as possible downwards (where without the quirk the ceiling is the TopOfMemory reported by the Memory Map and with the quirk is MIN (4 GB, TOM)).

**Comment by vit9696** [comment]
We have a problem on Sandy and Ivy, this function is used to determine slide memory range:
https://github.com/acidanthera/OcSupportPkg/blob/ea27502f5b28cbb45c6a95812b2c40e6edf793ca/Library/OcAppleBootCompatLib/CustomSlide.c#L48

Reviving that idea might make some sense indeed, unsure. I do not really like it for everyday use, as it makes the allocations not so predictable, but for <= 4 GB alloc it may help.

What makes me worried is what exactly causes the problem. The theory of allocating over potential pool memory sounds plausible but it is just a theory. Not so long ago I was thinking of reserving the pages prior to kernel booting and forcing a particular slide for dmg boot. Perhaps it is easier.

**Comment by vit9696** [comment]
Hrm, the first message of the issue is pretty much invalid, as safe mode does not involve dmg loading. Ballooning has just landed into OpenCore master, but it is unrelated to the problem.

**Comment by Frank-N-Furter** [comment]
I have board with Ami aptio and need AvoidHighmem (Shuttle SZ68R5, Sandy Bridge, iMac14,2.), but where some other memory issue example restart after sleep if memory is full. Only 100% memory and NVRAM way is using Clover with OsxAptioFixDrv.efi. May be where is some solutions for old motherboards.
