### ISSUE TITLE
Stuck at End Random Seed using OpenCore-0.0.4 

### ISSUE THREAD

**Issue by XLNCs** [acidanthera/bugtracker#450]
Hi !
I am able to boot to macOS 10.14.6 using OpenCore version 0.0.3 but not able to boot using version 0.0.4
it always gets stuck at End Random Seed

any idea's why this is happening ?

![Screen_Shot_2019-08-08_at_4 32 12_PM](https://user-images.githubusercontent.com/42638406/62714415-28ed4600-ba1c-11e9-8add-0538a46c01cc.png)

here is my log and config :
[opencore-2019-08-08-111523.txt](https://github.com/acidanthera/bugtracker/files/3482405/opencore-2019-08-08-111523.txt)

[config.zip](https://github.com/acidanthera/bugtracker/files/3482407/config.zip)

**Comment by vandroiy2013** [comment]
Hi
This is not a support forum. Especially with AMD CPU.

**Comment by xapenny** [comment]
I’m having this problem too. I’m using intel ivb platform(i5-3317u) and stuck at “End RandomSeed” everytime. I can boot to 10.14.6 with clover but can’t do the same with OC.

**Comment by vandroiy2013** [comment]
Read carefully https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf
