### ISSUE TITLE
Page 14 is missing

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#454]
Page 14 is missing from OpenCore/Docs/Differences.pdf

**Comment by vit9696** [comment]
This is how `latexdiff` in `ONLYCHANGEDPAGE` mode works. Entirely new pages may be missing from the end result. Fortunately that inconvenience is obvious enough to spot and lookup in the original document. The only alternative is `ZLABEL` mode, but this one includes all pages, which is far less convenient to read. Closing as wontfix.
