### ISSUE TITLE
AppleAlc extra logs in verbose 

### ISSUE THREAD

**Issue by errorexists** [acidanthera/bugtracker#456]
got a lot of extra code in the verbose from AppleAlc sorry for bad picture attrached video also if that would help
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/23367705/62838882-ebb0d000-bc36-11e9-95cf-b498ce1b0df0.png">
[video0.mov.zip](https://github.com/acidanthera/bugtracker/files/3490379/video0.mov.zip)

**Comment by vit9696** [comment]
That was fixed ~2 hours ago.
https://github.com/acidanthera/AppleALC/commit/d3d1ae4fc76b0b9b8530e834764b9500c8881c0e

**Comment by errorexists** [comment]
ok thank you for your quick response
