### ISSUE TITLE
Spurious characters in Shell.

### ISSUE THREAD

**Issue by DHARVED** [acidanthera/bugtracker#457]
Spurious characters when press Shift, Ctrl, Alt in Shell if load Shell through OpenCore
[With AppleUiSupport.](https://cloud.mail.ru/public/82NE/6eSWEt1m8)
[Without AppleUiSupport.](https://cloud.mail.ru/public/6BVX/pJT4jMNWs)

**Comment by cattyhouse** [comment]
I’ve experienced this before, it is related to physical keyboard.

**Comment by DHARVED** [comment]
> I’ve experienced this before, it is related to physical keyboard.

I tested two keyboard.
If load shell from a BIOS, bug be away.

**Comment by vit9696** [comment]
Should be fixed in the shell from master.

**Comment by vit9696** [comment]
Not yet fixed.
