### ISSUE TITLE
Logouthook does not clear the uuidDump

### ISSUE THREAD

**Issue by yooouuri** [acidanthera/bugtracker#458]
When no errors occur, because of the exit 0 (https://github.com/acidanthera/OcSupportPkg/blob/1808014e1df1af4828f46974ecd755a19c322837/Utilities/LogoutHook/LogoutHook.command#L71) my uuidDump's are not removed.

![](https://cdn.discordapp.com/attachments/571449338660651064/610530642714951680/unknown.png)

**Comment by vit9696** [comment]
Fixed in https://github.com/acidanthera/OcSupportPkg/commit/b63d512b618ddb48f8cbdb50cecf73346639f90f, thx for reporting!

**Comment by yooouuri** [comment]
@vit9696 your welcome!
