### ISSUE TITLE
Logouthook does not save created variable

### ISSUE THREAD

**Issue by yooouuri** [acidanthera/bugtracker#459]
TestVar exists in nvram:

```
$ nvram -p | grep TestVar
TestVar	HelloWorld
```

Running the LogoutHook gives me some errors, are these errors normal?

```
sudo ./LogoutHook.command
122+0 records in
122+0 records out
122 bytes transferred in 0.000620 secs (196734 bytes/sec)
File Doesn't Exist, Will Create: ./nvram.plist
nvram: Error getting variable - '8BE4DF61-93CA-11D2-AA0D-00E098032B8C:BootCurrent': (iokit/common) data was not found
nvram: Error getting variable - '8BE4DF61-93CA-11D2-AA0D-00E098032B8C:BootNext': (iokit/common) data was not found
nvram: Error getting variable - '8BE4DF61-93CA-11D2-AA0D-00E098032B8C:Boot0081': (iokit/common) data was not found
nvram: Error getting variable - '8BE4DF61-93CA-11D2-AA0D-00E098032B8C:Boot0082': (iokit/common) data was not found
nvram: Error getting variable - '8BE4DF61-93CA-11D2-AA0D-00E098032B8C:Boot0083': (iokit/common) data was not found
Volume EFI on 136C4AF4-A54E-4E80-9067-FD1A3D002107 mounted
Volume EFI on disk0s1 unmounted
```

TestVar exists in /Volumes/EFI/nvram.plist:

```
$ sudo cat /Volumes/EFI/nvram.plist | grep TestVar
			<key>TestVar</key>
```

When I reboot, the LogoutHook seems to remove the TestVar... Because its not present anymore...

```
$ nvram -p | grep TestVar
$ sudo cat /Volumes/EFI/nvram.plist | grep TestVar
```

The LogoutHook is present
```
$ sudo defaults read com.apple.loginwindow LogoutHook
/Users/yooouuri/LogoutHook.command
```

**Comment by vit9696** [comment]
The messages mentioned in the log are normal. I don't know why the variables are not saved for you, however. Worked fine for us last time we tried.

**Comment by cattyhouse** [comment]
Guess you need to add TestVar to LegacySchema to allow OC to load this key?

**Comment by cattyhouse** [comment]
According to the Document.pdf, yes, that’s how it works.

**Comment by ZISQO** [comment]
it's working from OC 0.0.4 util the mid of July version. but OC 0.0.5 doesn't work after reboot.

**Comment by vit9696** [comment]
Is `DisableVariableWrite` property and `VariableRuntimeDxe.efi` presence relevant to the issue? I.e. did it break with enabling `DisableVariableWrite` and removing `VariableRuntimeDxe.efi`? If so, does it get fixed with  `DisableVariableWrite` setting to NO and installing `VariableRuntimeDxe.efi`?

Also, TestVar should still be present in nvram.plist on EFI partition after reboot (this is not what happens for @yooouuri), but it indeed will not be in nvram -p unless listed in config.plist, this is correct.

**Comment by yooouuri** [comment]
`DisableVariableWrite` is set to true, `VariableRuntimeDxe.efi` is not presence. I'll report back with `DisableVariableWrite` set to false and installed `VariableRuntimeDxe.efi`

**Comment by yooouuri** [comment]
Without DisableVariableWrite and VariableRuntimeDxe.efi I need to disable my iGPU because of the Allocated errors...

**Comment by yooouuri** [comment]
Also weird thing:

When I change my iGPU DVMT pre-Allocated to 64MB, boot hangs at:

![IMG_1917](https://user-images.githubusercontent.com/12934957/63128519-69693880-bfb5-11e9-9799-fe12649f60ac.jpg)

Change it back to 32MB and it boots...

**Comment by vit9696** [comment]
You were not asked to provide your experience with this configuration. You were asked a direct question whether emulated NVRAM is back to normal in this case.

**Comment by yooouuri** [comment]
In both cases, TestVar is not present in my nvram.plist

**Comment by vit9696** [comment]
We verified and can confirm that the tool works fine on our systems.
