### ISSUE TITLE
OpenCore patcher : mask issue

### ISSUE THREAD

**Issue by AlGreyy** [acidanthera/bugtracker#460]
Hi, 

I'm using this kernel patch and is working perfectly. Zen boots fine with it (10.14.x). 

FIND : B9 35 00 00 00 0F 32 48 C1 E2 20 89 C1 48 09 D1 BA 01 00 01 00 0F 45 D0 0F B7 CA 89 D0 C1 E8 10
REPLACE : 41 89 CE B8 1E 00 00 80 31 DB 31 C9 31 D2 0F A2 0F B6 F7 FF C6 44 89 F1 31 D2 89 C8 F7 F6 66 90

However as soon as I use this find MASK, Open Core won't find the hex ?

FF FF FF FF FF FF FF FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

even FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00    
results to  OC: Kernel patcher result 13 for kernel - Not Found

using : FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF works though.    

I don't get why the OC mask is acting so weird for this patch. Any help would be appreciated. 

Note for the FIND: B9 35 00 00 00 0F 32 48 C1 E2 20... is unique and there is only one occurrence of it in the kernel (you can use any 10.14 kernel to check).

**Comment by vit9696** [comment]
Hi,

Find value is invalid, as `Found & Mask != Find` for bits where mask is zero.
This should be in the docs, reopen the issue if not. Closing as invalid.

**Comment by AlGreyy** [comment]
That clears it out. I little mistake on my end. Thank you for your time and dedication. The tool is very powerful.
