### ISSUE TITLE
ALC256 - Magic Book layout57 - Mute key not working...

### ISSUE THREAD

**Issue by askforcherrycola** [acidanthera/bugtracker#461]
Hello, applying in Clover the correct layout id (shared between Huawei Matebook D 14 / Honor Magic Book 14) everything works but mute key doesn't work when Built-in Speakers used.

**Comment by vandroiy2013** [comment]
Hi. 
Sorry but we can't help with this issue. 
You have to find author of this resources. 
Someone with name "kk". 

<img width="980" alt="Screen Shot 2019-08-15 at 3 58 42 PM" src="https://user-images.githubusercontent.com/8144780/63096074-9269d900-bf75-11e9-99ce-bda37202ed18.png">

**Comment by vandroiy2013** [comment]
Try to search AppleALC Pull Requests or ask in AppleALC topic on insanelymac
