### ISSUE TITLE
Power Reporting

### ISSUE THREAD

**Issue by mrmiller** [acidanthera/bugtracker#464]
Intel Power Gadget is getting a very strange picture of the power readouts from the CPU and RAM. They intermittently spike from normal ranges to non-realistic values. See attached screenshots:
![normal](https://user-images.githubusercontent.com/1649773/63370607-6ebcdf00-c337-11e9-82bd-0d9fbca88902.png)
![spike](https://user-images.githubusercontent.com/1649773/63370610-711f3900-c337-11e9-9c66-8a98082cf74b.png)

**Comment by vit9696** [comment]
Geez, the hell. But I am afraid you need to kick them for this, power gadget reads MSRs directly, we do not interface with it anyhow. If the issue exists on Win or Linux it might be easier.

**Comment by mrmiller** [comment]
Alright, it was a shot in the dark! I will double-check on other platforms.

**Comment by vit9696** [comment]
My guess could be that they fail to get information about all cores in time. Should really try bugreporting somehow.
