### ISSUE TITLE
EFISTUB support ?

### ISSUE THREAD

**Issue by reyder** [acidanthera/bugtracker#468]
Hello. I want to boot linux using EFISTUB. I guess I need to use **Misc->Entry** but can I attach arguments somehow ?

Here is path example: `\EFI\EFISTUB\vmlinuz.efi`
Arguments: `initrd=/EFI/EFISTUB/ramdisk.img root=UUID=ae1657fb-3516-4700-8681-6c9599cca4c2 rootflags=subvol=@root rw`

**Comment by vit9696** [comment]
Hi @reyder, no, we have no plans to support arguments. Store them in NVRAM, like `boot-args`, and request EFISTUB authors to support this.

**Comment by vit9696** [comment]
We decided to reconsider the issue and will add argument support in the next release.

**Comment by vit9696** [comment]
Implemented in master.
