### ISSUE TITLE
Booter Quirks: DiscardHibernateMap removal

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#469]
Current testing shows no use of `DiscardHibernateMap` now that we fixed the memory map hand off logic. I schedule it for removal in two releases from now.

Please report here in case you require this quirk for hibernation to work. It is best to check this by hibernating multiple times in a row and writing to NVRAM at the same time. Please do not report about the issue when your hibernation does not work **at all**.

**Comment by Andrey1970AppleLife** [comment]
This quirk require for hibernation on my Acer V3-571G
