### ISSUE TITLE
WhateverGreen dual monitors (Apple logo displays on both right before login screen)

### ISSUE THREAD

**Issue by izo1** [acidanthera/bugtracker#470]
With dual 38" Ultrawide displays (both connected to Radeon VII via DisplayPort) the Apple logo displays on both monitors and then it fades to black and then fades to Apple login screen on the 1st monitor.

Have tried multiple ports and they are all the same.

There is also a long delay of the UEFI VBIOS GOP to macOS, which causes the monitor to go out of sync for a few seconds right before the Apple logo is displayed twice and right before the login screen.

**Comment by vit9696** [comment]
We do not think of this as a bug that our team should work on. Contact Apple bugreporter for this.

**Comment by MenschLennart** [comment]
Don't get me wrong, but why this should be an Apple bug? I do have the same issues on that.
I don't get a dual monitor setup working with clover or any kext or using the framebuffers.
It's just pretty annoying to switch off the cable and put it in again to get it work. Is there no workaround for that? Or any framebuffer settings related to this?
