### ISSUE TITLE
SSDT-AWAK: problem with latest HP bios

### ISSUE THREAD

**Issue by Gengik84** [acidanthera/bugtracker#471]
Hi, i see acpi for new bios and i found difference:
"STAS" not present into RTC
AWAK return to 0x0F but RTC return Zero and this give some problem.
we can correct this problem with acpi patcher but it is **not** a good solution.
Would it be necessary and good idea to use a specific ssdt for this?
It would be useful as the others already present.
Thanks in advance

**Comment by cattyhouse** [comment]
It is already here:

https://raw.githubusercontent.com/acidanthera/OpenCorePkg/master/Docs/AcpiSamples/SSDT-AWAC.dsl

**Comment by Gengik84** [comment]
i upload image fo info..
![Schermata 2019-08-30 alle 07 44 32](https://user-images.githubusercontent.com/14853542/64018895-f96abe80-cb2d-11e9-8658-5b804781048c.png)
instead
![Schermata 2019-08-30 alle 10 40 22](https://user-images.githubusercontent.com/14853542/64018908-09829e00-cb2e-11e9-8182-2be28679e518.png)
and RTC
![Schermata 2019-08-30 alle 07 44 44](https://user-images.githubusercontent.com/14853542/64018923-14d5c980-cb2e-11e9-8880-e7c7e20bbf78.png)
instead
![Schermata 2019-08-30 alle 10 40 37](https://user-images.githubusercontent.com/14853542/64018948-23bc7c00-cb2e-11e9-8a6c-91ddb0380f42.png)

Can be this ssdt a good idea?
`DefinitionBlock ("", "SSDT", 2, "ALASKA", "RTCF", 0x00000000)
{
    External (_SB_.PCI0.LPCB, DeviceObj)    // (from opcode)
    External (RTC_, DeviceObj)    // (from opcode)

    Scope (_SB.PCI0.LPCB)
    {
        If (_OSI ("Darwin"))
        {
            Scope (RTC)
            {
                Name (_STA, Zero)  // _STA: Status
            }
        }

        Device (RTCF)
        {
            Name (_HID, EisaId ("PNP0B00"))  // _HID: Hardware ID
            Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
            {
                IO (Decode16,
                    0x0070,             // Range Minimum
                    0x0070,             // Range Maximum
                    0x01,               // Alignment
                    0x08,               // Length
                    )
                IRQNoFlags ()
                    {8}
            })
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                Return (0x0F)
            }
        }
    }
}
`

**Comment by Gengik84** [comment]
@cattyhouse it's not the same
Please see difference

**Comment by cattyhouse** [comment]
So in your orig DSDT, Device RTC_STA always return 0, and Device AWAC_STA always return 0xF?

Then setting STAS=One does not work. You need DSDT patching via find, replace.

**Comment by Gengik84** [comment]
> So in your orig DSDT, Device RTC_STA always return 0, and Device AWAC_STA always return 0xF?
yep... see 

but patching with find/repl it's not really good...
and for me is better to use ssdt instead dsdt when we can

**Comment by vandroiy2013** [comment]
Hi. 
Guys this is not a forum. 
When you find solution with SSDT or similar make pull request or open new issue.

**Comment by Gengik84** [comment]
> Guys this is not a forum

surely you're right.
but @vit9696  knows of this and I have only informed.
Have a nice day

**Comment by vit9696** [comment]
Ugh, guys, write reports properly, do not produce not so useful discussion, and none will close your issues. Currently it is not really what it is meant to be, and I very well understand @Vandroiy.

What we have here is an enhancement report for a new SSDT sample as posted above based on my suggestion. I am not sure why LPCB disable is there though, as it seems unrelated. As long as this SSDT works fine, it feels like a good solution to me that will work everywhere. So we can update our documentation.

But to be honest, it might be about the time to consider making our own AWAC driver, just like Apple did with AppleSMCRTC.

**Comment by vit9696** [comment]
@Gengik84 , please confirm that this works fine.

```dsl
DefinitionBlock ("", "SSDT", 2, "ACDT", "RTC0", 0x00000000)
{
    External (_SB_.PCI0.LPCB, DeviceObj)    // (from opcode)

    Scope (_SB.PCI0.LPCB)
    {
        Device (RTC0)
        {
            Name (_HID, EisaId ("PNP0B00"))  // _HID: Hardware ID
            Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
            {
                IO (Decode16,
                    0x0070,             // Range Minimum
                    0x0070,             // Range Maximum
                    0x01,               // Alignment
                    0x08,               // Length
                    )
                IRQNoFlags ()
                    {8}
            })
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If (_OSI ("Darwin")) {
                    Return (0x0F)
                } Else {
                    Return (0);
                }
            }
        }
    }
}
```

**Comment by Gengik84** [comment]
Thx @vit9696
For me inject new device RTC0 can work good
i will try immediately when i can and report.
Sorry for yesterday misunderstanding

**Comment by Gengik84** [comment]
@vit9696 
Hi, sorry for the late reply
I can confirm, ssdt work good
i attack screenshot of verbose boot w/o any corrections and boot failure
[Boot-RTC_stop.zip](https://github.com/acidanthera/bugtracker/files/3563636/Boot-RTC_stop.zip)

**Comment by vit9696** [comment]
@PMheart resolved this in https://github.com/acidanthera/OpenCorePkg/commit/1b61d9744d312126b95ca2b2f7c2868f49ff8fa1, closing.
