### ISSUE TITLE
WhateverGreen：XCPM issue for Z370、270 and 170

### ISSUE THREAD

**Issue by penghubingzhou** [acidanthera/bugtracker#472]
Hello, I asked this issue for my friend!  When he use WEG, He can't boot without `-disablegfxfirmware` as follow:

![A413CF36D6FA9D3DC21DF894F94A111A](https://user-images.githubusercontent.com/40651890/64058105-c92c2a00-cbd8-11e9-8de9-c4a52cd74d33.png)

BUT if he add this boot param， his XCPM data will become incomplete. Here is the picture of his XCPM data before adding this boot param and after:

![56442B9E2CF78CB5A966A6DC3324EBA8](https://user-images.githubusercontent.com/40651890/64058139-3213a200-cbd9-11e9-96a3-2805d41d16de.png)

![2DF9BCA65159689696DF13F7E9299C7C](https://user-images.githubusercontent.com/40651890/64058144-350e9280-cbd9-11e9-8c78-c47096750477.png)

 He doesn't know whether this is a WEG bug or something else, so he asked me to open an issue to ask here. Thx for everyone's help! :)

**Comment by vit9696** [comment]
This is not WEG bug.

**Comment by penghubingzhou** [comment]
Ok，Thx for reply！
