### ISSUE TITLE
AppleGenericInput: Add key mapping support.

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#473]
With the advent of recent commits, it has somehow become instinctive to use boot.efi hotkeys.

However, it would be nice to have key mapping mechanism for better compatibility on non-Mac keyboards. e.g to swap `Command` and `Option`.

**Comment by vit9696** [comment]
As this issue requires merging AppleGenerincInput into OC, I will also include planned UEFI → Input options here.

```
TimerResolution = 0 / 5 (disable / 5 ms) aka AITTimer value; failsafe - 0
PointerSupport = "" / ASUS; failsafe - ""
KeySupport = "" / Auto / V1 / V2 / AMI; failsafe - ""
KeySwap = YES / NO; failsafe - NO
KeyForgetThreshold = 5 (aka AIK_TARGET_FORGET_THRESHOLD); failsafe - 0
KeyMergeThreshold = 2 (aka AIK_TARGET_MERGE_THRESHOLD); failsafe - 0
```

**Comment by Download-Fritz** [comment]
Partially pushed at https://github.com/acidanthera/OcSupportPkg/commit/eedf63f106db415cf5cba5d2c045e58bafe7226e and https://github.com/acidanthera/OpenCorePkg/commit/0e5a9e2782acb0945c2c597b4e4fa11d38c0e24a (I somehow forgot to commit after the first staging).
The options have been changed to explicitely enable/disable key and pointer support. Documentation is missing.

**Comment by vit9696** [comment]
Implemented in master.
