### ISSUE TITLE
PollAppleHotKeys=YES not able to boot automatically

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#476]
if PollAppleHotKeys=YES, it is not able to boot automatically, have to enter a number. Hotkeys does not work on the boot menu either, tried adding UsbKbDxe.efi, the same.

OC version:
4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version   REL-050-2019-09-06

Attached my boot config. 
![2019-09-06 12 16 29](https://user-images.githubusercontent.com/3365320/64400750-33910e80-d0a0-11e9-9982-ac9d469080b6.jpg)

**Comment by vit9696** [comment]
Z390 or alike? Caused by no support for the timer. Currently it is not scheduled for fixing, but we will consider it in case I am correct.

**Comment by cattyhouse** [comment]
it is a Asrock B360M-HDV

**Comment by vit9696** [comment]
Yes, same chipset family. It is a known limitation, which may get fixed eventually.

**Comment by fabiosun** [comment]
Hi
I have similar problem with an Asus Sage x299 WS 10G
Hot keys are not working
