### ISSUE TITLE
Proxy KEXT cannot be injected

### ISSUE THREAD

**Issue by osy86** [acidanthera/bugtracker#478]
A kext generated with https://github.com/slavaim/dl_kextsymboltool (sample attached) cannot be loaded by OC. The error message is
```
104:838 00:083 OC: Prelink injection Polaris22MetalFixup.kext/Contents/PlugIns/CSValidateRangeProxy.kext - Buffer Too Small
```
[opencore-2019-09-07-014418.txt](https://github.com/acidanthera/bugtracker/files/3586338/opencore-2019-09-07-014418.txt)
[CSValidateRangeProxy.kext.zip](https://github.com/acidanthera/bugtracker/files/3586339/CSValidateRangeProxy.kext.zip)

**Comment by vit9696** [comment]
Does this work with normal kext loading (i.e. from `/Library/Extensions`)? I am not sure it does, so making this supported in OpenCore sounds weird.

**Comment by osy86** [comment]
Yes it does and also it works through Clover injection as well.

**Comment by Download-Fritz** [comment]
@osy86 Thanks for the report. Could you please try with latest master? It injects fine (userland), but runtime usage has not been verified.

**Comment by osy86** [comment]
Thank you it works perfectly.
