### ISSUE TITLE
VirtualSMC 1.0.7

### ISSUE THREAD

**Issue by locusathome** [acidanthera/bugtracker#479]
Upgrading from VirtualSMC 1.0.6 to 1.0.7 with OpenCore 0.5.0 resulted in no startup and this:
Prelink injection VirtualSMC.kext - Invalid Parameter

Going back to 1.0.6 let me boot succesfully into login and:
Prelink injection VirtualSMC.kext - Success

Nothing changed between goin g from 1.06 to 1.0.7. I attach my EFI folder and maybe I have overlooked something?

EFI:
[EFI.zip](https://github.com/acidanthera/bugtracker/files/3586571/EFI.zip)

**Comment by vit9696** [comment]
VirtualSMC 1.0.7 is not compatible with legacy Lilu. VirtualSMC 1.0.7 requires [Lilu 1.3.8](https://github.com/acidanthera/Lilu/releases/tag/1.3.8) or newer. Always use the latest releases available.

**Comment by vit9696** [comment]
An invalid value was discovered during linkage. E.g. mismatching vtable. The return code is propagated.
