### ISSUE TITLE
OcSupportPkg\Library\OcAppleSecureBootLib\OcAppleSecureBootLib.c: warning C4244: '=': conversion from 'UINT32' to 'UINT8', possible loss of data

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#481]
OcSupportPkg\Library\OcAppleSecureBootLib\OcAppleSecureBootLib.c(189): warning C4244: '=': conversion from 'UINT32' to 'UINT8', possible loss of data

OcSupportPkg\Library\OcAppleSecureBootLib\OcAppleSecureBootLib.c(487): warning C4244: '=': conversion from 'UINT32' to 'UINT8', possible loss of data

**Comment by Download-Fritz** [comment]
This had been fixed at https://github.com/acidanthera/OcSupportPkg/commit/357142b6e9720990670459a0c8ba34fd7d587311#diff-32668c6144f3378f75572e720759500f
