### ISSUE TITLE
Keyboard not working in boot picker after Opt with PollAppleHotKeys=true 

### ISSUE THREAD

**Issue by vandroiy2013** [acidanthera/bugtracker#485]
This problem occurs on Gigabyte GA-Z370M-DS3H when ShowPicker=false and PollAppleHotKeys=true after pressing Opt button to reveal Boot Picker. 
Can't drop timer, can't choose OS. 
Tried with AppleGenericInput and with UsbKbDxe.

**Comment by maddie** [comment]
Happens on my Asus ROG Strix Z370-F too, had to turn it off to make keyboard work in picker again.

**Comment by DbArl** [comment]
> This problem occurs on Gigabyte GA-Z370M-DS3H when ShowPicker=false and PollAppleHotKeys=true after pressing Opt button to reveal Boot Picker.
> Can't drop timer, can't choose OS.
> Tried with AppleGenericInput and with UsbKbDxe.

It‘s seems not working when you hold the option, please try press option several times. This  method works for me. But I think it's not enough Macintosh.

**Comment by gkankanh** [comment]
Reproducible on GB X570 AORUS PRO WIFI MB as well.

**Comment by vit9696** [comment]
Assume fixed in master.
