### ISSUE TITLE
ELAN PS2 Touchpads Support

### ISSUE THREAD

**Issue by frol** [acidanthera/bugtracker#488]
I would like to open a tracking issue for ELAN PS2 Touchpads Support. I am new to the Hackintosh world, but I have read all the resources on the Internet I could find about this topic (forums, GitHub repositories, etc) and tested:

* VoodooPS2Controller enables my touchpad without gestures (only pointer navigation and tap to click work)
* VoodooPS2ControllerR6 didn't work at all, and given it is a closed-source patch, there is nothing to improve
* ApplePS2SmartTouchPad (the closed-source and outdated driver) enables my touchpad with gestures, but the gestures are weird (do not match native MacOS gestures and only fire an event at the end of the gesture) and scrolling is slow as hell

Could someone clarify the current state of VoodooPS2 "framework"?

> New VoodooPS2Trackpad emulates Magic Trackpad using Apple driver instead of handling all gestures itself.

This sounds awesome! Does this mean that implementation of the actual driver only requires to proxy touch events?

**Comment by leo-labs** [comment]
Hey, are you sure that your Touchpad only supports PS2 and not also the ELAN protocol via I2C or SMBus?

**Comment by frol** [comment]
@leo-labs I am not sure about I2C or SMbus. I have not dived deep enough to investigate it, but it certainly works via PS2 on Linux and MacOS (to be honest, I didn’t expect it might support several protocols)

**Comment by frol** [comment]
Here is the best information I can get about my touchpad from Linux (my main OS is Arch Linux):

```
$ dmesg | grep -iP '(8042|elan)'
i8042: PNP: PS/2 Controller [PNP0303:PS2K,PNP0f13:MSS1] at 0x60,0x64 irq 1,12
serio: i8042 KBD port at 0x60,0x64 irq 1
serio: i8042 AUX port at 0x60,0x64 irq 12
input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input4
psmouse serio1: elantech: assuming hardware version 4 (with firmware version 0x495f01)
psmouse serio1: elantech: Synaptics capabilities query result 0x70, 0x15, 0x0e.
psmouse serio1: elantech: Elan sample query result 02, 33, 75
input: ETPS/2 Elantech Touchpad as /devices/platform/i8042/serio1/input/input7
```

**Comment by Andrey1970AppleLife** [comment]
Maybe it will help: https://www.kernel.org/doc/html/latest/input/devices/elantech.html As at the author ApplePS2SmartTouchPad it is specified: CREDITS: ELAN - Arjan Opmeer for ELAN linux documentation/source﻿﻿

**Comment by Ressetkk** [comment]
IIRC VoodooPS2ControllerR6 is a modified kext based on the code from https://github.com/DrHurt/OS-X-ALPS-DRIVER for for Dell's ALPS Touchpads. It would be really nice to see them implemented with the new VoodooPS2 along with ELAN.

**Comment by DiogoSilva48** [comment]
Any news regarding this ? I have the exact same device and I am facing the same.

**Comment by nvmnghia** [comment]
Bump this. Please add some support for it!

**Comment by vit9696** [comment]
We have no plans for working on this issue.
