### ISSUE TITLE
Cannot enter the system after using applealc in 10.15

### ISSUE THREAD

**Issue by xiaoMGitHub** [acidanthera/bugtracker#489]
In 10.15, when I injected the sound card id, I got a kernel panic, if I didn't use applealc everything worked fine.
![20190911151930](https://raw.githubusercontent.com/xiaoMGitHub/tmp/master/20190911151930.png)

**Comment by xiaoMGitHub** [comment]
Thank you very much for your help.
![20190911151930](https://github.com/xiaoMGitHub/tmp/raw/master/20190911162800.png)

**Comment by vit9696** [comment]
Your kernel panic happens at writing to console, it is unrelated to AppleALC. I think you will need to ensure your console mode and resolution are correctly set in the first place. Then check TSC sync across the cores, and possibly introduce extra delay with npci boot argument. Either way this is not our bug/issue and should be asked on rhe support forums.
