### ISSUE TITLE
Recovery 10.15 LoadImage failed - Unsupported

### ISSUE THREAD

**Issue by bugprogrammer** [acidanthera/bugtracker#490]
I cannot boot recovery 10.15，this is log
https://drive.google.com/open?id=1iVjvFvYxcsjuh8aBfLhwf7P9yRxOXh-Q

**Comment by bugprogrammer** [comment]
recovery 10.15 log

https://drive.google.com/open?id=1-NcbWavfHO3S_XzN0xPBFBRw5A6KHhYS

**Comment by bugprogrammer** [comment]
https://drive.google.com/open?id=1048QgzcAuscyFS_gDM0Sm_Ccd8ngRMRF

**Comment by vit9696** [comment]
Please ensure you use the latest VBoxHfs driver from github.com/acidanthera/AppleSupportPkg or use HFSPlus.efi.
