### ISSUE TITLE
Add MinProductionYear and MaxProduсtionYear to DataBase

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#493]
To planning 2020

**Comment by iNDi** [comment]
should really be a full start and end date.

**Comment by vit9696** [comment]
@Andrey1970AppleLife I added a sample commit to the database, please update its contents accordingly. Once the database is filled with the dates I could replace AppleModelYears with them.

**Comment by vit9696** [comment]
We discussed the matter, and concluded that it is infeasible to incorporate this feature. Current year lists serve the purpose fairly well, and changing them to full dates is not really improving macserial:

- marketing introduction and discontinued dates are different from production dates. Often by several months. We do not know them, and they are not published anywhere.
- using a wide range for generation is not improving serial quality either, it is best to use 1-2 weeks.
- checking marketing dates for choosing the weeks could only be done speculatively, and thus is best to be done manually.

Closing.
