### ISSUE TITLE
No backlight after wake on rMBP 10,1

### ISSUE THREAD

**Issue by nemphys** [acidanthera/bugtracker#494]
I have been using WhateverGreen on my early 2013 rMBP (1398) for a long time since the graphics lag issue came up with High Sierra, mostly with success.

The latest versions seem to be the most stable regarding graphics glitches, etc, but they seem to break the internal monitor backlight after waking from sleep.

I have tried booting with applbkl=0, but it makes no difference.

PS. I am wondering if you could make a version of the kext that includes *just* the High Sierra/Mojave graphics lag fix and no other patches whatsoever for us poor Apple hardware users :-) I actually tried building a custom version by commenting out all the stuff that seemed unrelated to it, but it wouldn't get loaded.

**Comment by nemphys** [comment]
I can tell you when the problem started, since I have conveniently taken notes on each version:
1.2.4 -> Sleep OK
1.2.5 -> Kernel panic on boot
1.2.6 -> no wake from sleep

So, it is either 1.2.5 or 1.2.6 (I cannot tell for 1.2.5, since it won't boot)

**Comment by vit9696** [comment]
Hmm, could you try removing this section entirely:
https://github.com/acidanthera/WhateverGreen/blob/master/WhateverGreen/Info.plist#L40
Can do this after compilation right in 1.2.6 kext.
I wonder if some keys are missing for your model and thus the problem.

**Comment by nemphys** [comment]
Can you be a little more specific regarding what you want me to test?

**Comment by vit9696** [comment]
Sure, I would like you to remove AppleIntelPanelA section from WhateverGreen.kext Info.plist and check that backlight is fine after wake. Test it with both latest WhateverGreen and 1.2.6 version.

**Comment by nemphys** [comment]
Right, just tried that with the latest version and the problem seems to have gone away (screen wakes normally).
I suppose we will now have to do some further debugging in order to find what is missing.

**Comment by vit9696** [comment]
These values should match `/System/Library/Extensions/AppleBacklight.kext/Contents/Info.plist` but also have a few more entries for hackintosh. Could you please compare the contents on your system? I compared it with mine (10.14.6) and found that a few devices are missing in our version. This I fixed in master.

**Comment by nemphys** [comment]
I am running (10.14.6) too, this is the diff output of the 2 Info.plist files (WG vs stock)
[diff.txt](https://github.com/acidanthera/bugtracker/files/3649533/diff.txt)

**Comment by vit9696** [comment]
So, these are what I added yesterday: https://github.com/acidanthera/WhateverGreen/commit/a4c01e79f15ea79a52ea25a93434e46f1595bc89.

I think you can check your device id with IORegistryExplorer, but I cannot tell immediately whereto look. Try searching for ApplePanel. Should be somewhere in parent or child nodes.

Removing the plist deletes the override we provide, and the original file is used. Normally I would expect no difference, but for some reason it might exist, in case the missing entries are not the cause.

**Comment by nemphys** [comment]
As expected, the problem is not fixed by adding the 3 new ids to Info.plist; I suppose this means that the issue lies elsewhere.
I will try to find the id using IORegistryExplorer later today and report back.

**Comment by vit9696** [comment]
Got to the laptop, you should be able to find your ID by running the following command:
```
ioreg -l | grep '"ApplePanel"'
```
On my MBP12,1 it gives the following result:
```
    | |       "ApplePanel" = {"F15Ta02a"=<0011000000170026003900520070009500c200f9013d018e01f2026b02fe03ac04780569>}
```

All in all it is pretty strange. The only difference I see here is the addition of the following entries:
https://github.com/acidanthera/WhateverGreen/blob/a4c01e7/WhateverGreen/Info.plist#L432-L445

And higher probe score to put our settings in use:
https://github.com/acidanthera/WhateverGreen/blob/a4c01e7/WhateverGreen/Info.plist#L471

Could you try removing the xxxx entries? Will it change anything?

What I am currently thinking of is changing the injection logic from plist to kext itself. It sounds like a bad idea to attempt to maintain a list of panels in sync with Apple kext in the first place, as we have just seen 3 panels appearing out of nowhere and being completely unnoticed. Perhaps, this will fix your problem too.

**Comment by nemphys** [comment]
The panel is:
"ApplePanel" = {"F14Ta00f"=<001100000014002000300043005c007a009f00cb01010141018c01e6025002d2035c03ff>}

Will check the rest later.

**Comment by vit9696** [comment]
So, your panel is not present in the list. This is a bit worrying, as the patches we apply on *non-apple* hardware result in missing entries match against `F14Txxxx`. I have a slight suspect that some detection logic is broken.

1. Please create a debug log with Lilu and WhateerGreen (debug versions) and the following boot arguments: `-liludbgall liludump=60`. This will create a log file like /var/log/Lilu_1.2.3.txt 60 seconds after booting macOS. Attach this file here.

2. Please compare `ApplePanel` values (the one you posted above `<0011…>`) with WhateverGreen installed and removed before and after waking from sleeping (i.e. 4 different values).

**Comment by nemphys** [comment]
Here you go:
1) Attached

2) with WEG, before/after sleep: 
"ApplePanel" = {"Default"=<000007400af7fffe>} ---> hmmm

without WEG, before/after sleep:
"ApplePanel" = {"F14Ta00f"=<001100000014002000300043005c007a009f00cb01010141018c01e6025002d2035c03ff>}

(both values stay the same before sleep/after wake).
[Lilu_1.3.8_18.7.txt](https://github.com/acidanthera/bugtracker/files/3654332/Lilu_1.3.8_18.7.txt)

**Comment by nemphys** [comment]
One more thing: if you manage to sort this out, will it be any different than removing the AppleIntelPanelA section from the plist file? (eg. will any other patches be disabled, too?)

I am asking this because, although removing the section from the plist file fixes the sleep issue, I still get occasional graphic glitches and crashes (in specific programs, eg. java/Jetbrains crashes and Chrome glitches), which I admittedly always had with Lilu/WEG installed. Is this normal or should we attribute it to the erratic hardware detection?

**Comment by vit9696** [comment]
The log looks fine, so it is very likely some internal specialty if AppleBacklight.kext. I will add property injection through WEG as time permits (hopefully this weekend), and it should resolve the problem.

As for glitches, you are most likely talking about NVIDIA. The good news is that the bugfix has finally landed to 10.15, so you may be able to drop WEG once you upgrade. The bad news is that on 10.14 and earlier rare glitches are unavoidable trade off for bearable performance.

**Comment by nemphys** [comment]
OK, sounds good, I will wait for the next release using the modified version in the meantime.

As for 10.15, I had seen that it has been fixed in a commit comment, but it's good to have a confirmation from you. I would have already installed a beta if it weren't for the 32-bit support removal.

**Comment by vit9696** [comment]
@nemphys I believe I fixed it with https://github.com/acidanthera/WhateverGreen/commit/b4b8f9722ebb61ff04849f3a825e9dc50442d6e4. Please confirm the fix and close the issue if so.

**Comment by nemphys** [comment]
Just tested it, wake from sleep works fine.
Closing this, thank you!
