### ISSUE TITLE
OC's default boot volume ignores Startup Disk.

### ISSUE THREAD

**Issue by Oschly** [acidanthera/bugtracker#495]
Hello.
On my PC I have Hackintosh (Catalina, newest beta) and Windows 10 (newest release with newest Bootcamp Software 6.1).
The problem is that every time that I want to switch OS using Startup Disk, OC after reboot is still using first boot's entry (It's either USB or Bootcamp on SSD) and it's independent of OS (happens on Windows with Bootcamp's Startup Disk and macOS with Startup Disk).

Spec:
- MOBO: MSI MAG z390 Tomahawk
- Audio: ALC889
- Wifi/Bluetooth: Broadcom BCM94331CD
- Ethernet: 
  -  Intel I219-V
  -  Intel I211-AT // disabled in UEFI
- CPU: i7-8700k
- GPU: Sapphire RX 580 8GB Nitro+
- RAM:  16GB Corsair Vengeance LPX 3000MHz CL16
- Drives:
  -  WD Black NVME 250GB (2017)
  -  SSD Goodram Iridium (1st gen) 240GB
  -  HDD 1TB WDC WD10EZRX-00L4HB0
- Keyboard:  Corsair k70
- Mouse:  Steelseries Sensei 310
- Headphones: HyperX Cloud I
- Monitor: AOC Q27P1

[IOReg](https://my.pcloud.com/publink/show?code=XZ7EhzkZd6QeL1Yyuqy0ocw8QB2JYBPoNPOk)

[Full EFI, with nvram.plist](https://github.com/acidanthera/bugtracker/files/3653379/EFI.zip)

[nvram -p ouput right before reboot with selected Startup Disk as macOS](https://pastebin.com/mZgHaT9j)

[nvram -p ouput after restart](https://pastebin.com/g7U7kPMd)

I know, I don't have efi-boot-device and efi-boot-device-data in nvram, but I had these values before and [nvram's boot-device values looked like that](https://pastebin.com/hs6DMKVs) after restart, but it's from choosing BootCampHD as Startup Disk.

Bless --info returns that, if efi-boot-device is deleted from NVRAM values:

`Can't access "efi-boot-device" NVRAM variable`

And returns that when efi-boot-device is saved in nvram:
```
Could not unserialize string
XML representation doesn't match true boot preference
```

And one of previous error when I was trying to get this info:
```
Boot option does not match XML representation
XML representation doesn't match true boot preference.
```

**Comment by vandroiy2013** [comment]
NVRAM is not working on Z390 chipset. You should buy Z370. It have working NVRAM OOB.

**Comment by vit9696** [comment]
To clarify: `efi-boot-device` is irrelevant to Apple Boot Picker and OpenCore as well. What you are looking for are `Boot0080` and `BootOrder` variables. I am not particularly sure what is wrong with NVRAM emulation, you are best to debug your scripts and nvram.plist during particular reboots.

I also do know what mechanism you are going to use for Windows, as you somehow need to solve conflicts between native NVRAM and nvram.plist.

Furthermore, you have nothing in NVRAM Block, which may result in being unable to override the Boot#### variables.

**Comment by Oschly** [comment]
If may I ask before getting to debug scripts. What do You mean by NVRAM block?

**Comment by vit9696** [comment]
I am talking about this part:
```
Variable loading happens prior to \texttt{Block} (and \texttt{Add}) phases, and will not
  overwrite any existing variable. Variables allowed to be set must be specified in
  \texttt{LegacySchema}. Third-party scripts may be used to create \texttt{nvram.plist}
  file.
```
Probably need to create some schema to illustrate it, but that's what happens:

1. nvram.plist is parsed and all variables outside of LegacySchema are ignored.
2. the rest of the variables are set to nvram.plist values iff they are not present.
3. Block'ed variables are removed.
4. Add'ed variables are added iff they are not present.

_iff they are not present_ part is fairly crucial:
1. setting a variable from e.g. Windows or macOS when hardware NVRAM is functional creates a non-volatile variable. This variable will preserve across reboots, and will effectively _be present_ at a time OpenCore does variable setting.
2. setting variables from OpenCore on the other side creates volatile variables. This variable will only live till a reboot.
3. some variables, like BootOrder, may be set by your firmware, and to ensure there are no conflicts different GUID spaces are used with the help of RequestBootVarRouting quirk.

**Comment by Oschly** [comment]
I edited my config.plist to accept all NVRAM variables from all GUIDs available (Google Doc sheet from Configuration helped a lot), using * entry in every GUID array. The problem is that, nvram.plist even after that still saves only base variables from AppleBoot. There is nothing more than that in this file (after deleting every entry except "*" in arrays even GUID with BootOrder dissappeared).

LogoutHook command throws that there are no available variables with that names ([GUID]:BootOrder, etc.), so I've entered to Recovery mode (that doesn't work via dmg, but it's another problem, so I am using blessOverride to use its boot.efi to go there) and tried to create BootOrder variable (nvram F68DA75E-1B55-4E70-B41B-A7B7A5B758EA:BootOrder=0), but Bash returns that:

> Error setting variable (iokit/common) general error.

Is there any way to check these variables in Windows, or to check all available variables from all GUIDs?

**Comment by vit9696** [comment]
For Windows you can use WinNvram:
https://github.com/acidanthera/OcSupportPkg/tree/master/Utilities/WinNvram

**Comment by Oschly** [comment]
Trying to read nvram variables with WinNvram gives the same results - everything from `AppleBoot` is readable, but values from other GUIDs aren't available (throws error 203). I tried to use that structures: `[GUID]:variableName` and just `variableName`, but I see that first one doesn't work anyway.
Does that mean that it's Bootloader's or mobo's firmware's fault?

**Comment by fangf2018** [comment]
[nvram.plist.zip](https://github.com/acidanthera/bugtracker/files/3693455/nvram.plist.zip)
Default boot disk settings do not take effect

**Comment by fangf2018** [comment]
I tried to modify the wrong NVRAM and turn off NVRAM writing.
[nvram.plist.zip](https://github.com/acidanthera/bugtracker/files/3693485/nvram.plist.zip)
![95C5C3553EC7A234AAF8BE5D328C0A90](https://user-images.githubusercontent.com/19627926/66257985-43505f80-e7d2-11e9-805f-9afccc7d8efa.jpg)
@vit9696
