### ISSUE TITLE
EfiPkg: there is no VERIFY_SIZE_OF(TYPE, Size) macro defined

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#496]
```
Vacuum:GIT nms$ find . -name \*.h | xargs fgrep VERIFY_SIZE_OF
./OcSupportPkg/TestsUser/Include/Base.h:#define VERIFY_SIZE_OF(TYPE, Size) extern unsigned char _VerifySizeof##TYPE[(sizeof(TYPE) == (Size)) / (sizeof(TYPE) == (Size))]
./EfiPkg/Include/Protocol/AppleRamDisk.h:VERIFY_SIZE_OF (APPLE_RAM_DISK_DP_VENDOR, 24);
./EfiPkg/Include/Protocol/AppleRamDisk.h:VERIFY_SIZE_OF (APPLE_RAM_DISK_DP, 52);
./EfiPkg/Include/Protocol/AppleRamDisk.h:VERIFY_SIZE_OF (APPLE_RAM_DISK_EXTENT, 16);
./EfiPkg/Include/Protocol/AppleRamDisk.h:VERIFY_SIZE_OF (APPLE_RAM_DISK_EXTENT_TABLE, 4096);
./EfiPkg/Include/Protocol/AppleRamDisk.h:VERIFY_SIZE_OF (APPLE_RAM_DISK_CONTEXT, 8192);
Vacuum:GIT nms$
```

`"clang" -target x86_64-pc-win32-macho -c -g -gdwarf -O0 -Wall -Werror -Wextra -include AutoGen.h -funsigned-char -fno-ms-extensions -fno-stack-protector -fno-builtin -fshort-wchar -mno-implicit-float -mms-bitfields -Wno-unused-parameter -Wno-missing-braces -Wno-missing-field-initializers -Wno-tautological-compare -Wno-sign-compare -Wno-varargs -ftrap-function=undefined_behavior_has_been_optimized_away_by_clang -D NO_MSABI_VA_FUNCS  -D OC_TARGET_NOOPT=1 -D DISABLE_NEW_DEPRECATED_INTERFACES  -o /Users/nms/prj/ubench/Build/OcSupportPkg/NOOPT_XCODE5/X64/OcSupportPkg/Library/OcFirmwarePasswordLib/OcFirmwarePasswordLib/OUTPUT/./OcFirmwarePasswordLib.obj -I/Users/nms/prj/GIT/OcSupportPkg/Library/OcFirmwarePasswordLib -I/Users/nms/prj/ubench/Build/OcSupportPkg/NOOPT_XCODE5/X64/OcSupportPkg/Library/OcFirmwarePasswordLib/OcFirmwarePasswordLib/DEBUG -I/Users/nms/prj/GIT/EfiPkg -I/Users/nms/prj/GIT/EfiPkg/Include -I/Users/nms/prj/GIT/EfiPkg/Include/X64 -I/Users/nms/prj/GIT/edk2/MdePkg -I/Users/nms/prj/GIT/edk2/MdePkg/Include -I/Users/nms/prj/GIT/edk2/MdePkg/Include/X64 -I/Users/nms/prj/GIT/OcSupportPkg -I/Users/nms/prj/GIT/OcSupportPkg/Include /Users/nms/prj/GIT/OcSupportPkg/Library/OcFirmwarePasswordLib/OcFirmwarePasswordLib.c
"clang" -target x86_64-pc-win32-macho -c -g -gdwarf -O0 -Wall -Werror -Wextra -include AutoGen.h -funsigned-char -fno-ms-extensions -fno-stack-protector -fno-builtin -fshort-wchar -mno-implicit-float -mms-bitfields -Wno-unused-parameter -Wno-missing-braces -Wno-missing-field-initializers -Wno-tautological-compare -Wno-sign-compare -Wno-varargs -ftrap-function=undefined_behavior_has_been_optimized_away_by_clang -D NO_MSABI_VA_FUNCS  -D OC_TARGET_NOOPT=1 -D DISABLE_NEW_DEPRECATED_INTERFACES  -o /Users/nms/prj/ubench/Build/OcSupportPkg/NOOPT_XCODE5/X64/OcSupportPkg/Library/OcMachoLib/OcMachoLib/OUTPUT/./CxxSymbols.obj -I/Users/nms/prj/GIT/OcSupportPkg/Library/OcMachoLib -I/Users/nms/prj/ubench/Build/OcSupportPkg/NOOPT_XCODE5/X64/OcSupportPkg/Library/OcMachoLib/OcMachoLib/DEBUG -I/Users/nms/prj/GIT/edk2/MdePkg -I/Users/nms/prj/GIT/edk2/MdePkg/Include -I/Users/nms/prj/GIT/edk2/MdePkg/Include/X64 -I/Users/nms/prj/GIT/EfiPkg -I/Users/nms/prj/GIT/EfiPkg/Include -I/Users/nms/prj/GIT/EfiPkg/Include/X64 -I/Users/nms/prj/GIT/OcSupportPkg -I/Users/nms/prj/GIT/OcSupportPkg/Include /Users/nms/prj/GIT/OcSupportPkg/Library/OcMachoLib/CxxSymbols.c
In file included from /Users/nms/prj/GIT/OcSupportPkg/Library/OcAppleDiskImageLib/OcAppleDiskImageBlockIo.c:16:
/Users/nms/prj/GIT/EfiPkg/Include/Protocol/AppleRamDisk.h:282:43: error: expected parameter declarator
VERIFY_SIZE_OF (APPLE_RAM_DISK_DP_VENDOR, 24);
                                          ^
/Users/nms/prj/GIT/EfiPkg/Include/Protocol/AppleRamDisk.h:282:43: error: expected ')'
/Users/nms/prj/GIT/EfiPkg/Include/Protocol/AppleRamDisk.h:282:16: note: to match this '('
VERIFY_SIZE_OF (APPLE_RAM_DISK_DP_VENDOR, 24);
               ^
/Users/nms/prj/GIT/EfiPkg/Include/Protocol/AppleRamDisk.h:282:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
VERIFY_SIZE_OF (APPLE_RAM_DISK_DP_VENDOR, 24);`

**Comment by vit9696** [comment]
Yeah, I removed it from the latest EDK II in favour of STATIC_ASSERT. We will replace the macro once we upgrade to the next EDK II stable.

**Comment by nms42** [comment]
But EfiPkg/Include/Protocol/AppleRamDisk.h still use it

**Comment by vit9696** [comment]
Sorry? Are you using some incompatible EDK once again? acidanthera/audk has no STATIC_ASSERT and still has VERIFY_SIZE_OF.

**Comment by nms42** [comment]
Yep! Mea culpa! Was compiling against tip of plain edk2.

**Comment by vit9696** [comment]
Let's have this open, so that it is not forgotten during next edk2 stable upgrade.

**Comment by Download-Fritz** [comment]
Said upgrade has been completed.
