### ISSUE TITLE
Rebooting issue 

### ISSUE THREAD

**Issue by Dajokeisonu** [acidanthera/bugtracker#499]
[panic.txt](https://github.com/acidanthera/bugtracker/files/3678647/panic.txt)

I have Alienware 17 R3 i7-6700Hq igpu 530 and Nvidia GTX 970m on every reboot with open core I must reboot into windows then reboot back or I get this igpu error.  I am using the latest kexts available.  If you have any advise it would be most appreciated I want to ditch clover in baddest way possible and use Open Core perm

**Comment by vit9696** [comment]
Fixed in WEG 1.3.2.

**Comment by ctich** [comment]
You need patches for DVMT, read https://www.insanelymac.com/forum/topic/334899-intel-framebuffer-patching-using-whatevergreen/ 
![Знімок екрана 2019-10-02 о 09 47 31](https://user-images.githubusercontent.com/42576487/66023392-ae134980-e4f9-11e9-859a-36a19309f137.png)

**Comment by Dajokeisonu** [comment]
Thank you for the response. I am currently on the latest version Of Whatvergreen 1.3.2 with the issue I will check the link provided to see if there any addition Igpu settings that need to be configured. I just want to note this only happens on a reboot the issue does not exisit in clover just in Opencore.  Thank you :)

**Comment by Dajokeisonu** [comment]
I want to report with success I followed the link provided I can now successfully boot open core :D
