### ISSUE TITLE
Tools/Entries Arguments may not be functional

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#501]
Reported once by iNDi, we probably want to get this tested.

**Comment by Download-Fritz** [comment]
Possibly fixed by https://github.com/acidanthera/OcSupportPkg/commit/ae040f053b19af4446b749a787f5047497a32541
I could test it soon, but if someone else relies on this option anyway, a report would be nice.

**Comment by Download-Fritz** [comment]
Confirmed fixed.
