### ISSUE TITLE
AppleSupportPkg/Platform/FwRuntimeServices/UefiRuntimeServices.c:259:15: error: variable 'Routed' set but not used

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#502]
AppleSupportPkg/Platform/FwRuntimeServices/UefiRuntimeServices.c:259:15: error: variable 'Routed' set but not used

Looks like unfinished code (?)

**Comment by vit9696** [comment]
Yes, that's some legacy debug code. Fixed.
