### ISSUE TITLE
No trackpad prefpane on desktop

### ISSUE THREAD

**Issue by usr-sse2** [acidanthera/bugtracker#504]
![Снимок экрана 2019-10-07 в 18 26 13](https://user-images.githubusercontent.com/446776/66325451-f387aa80-e92f-11e9-8140-304dced68fe4.png)

Trackpad is attached to a desktop through PS/2 port. It works, but without preference panel.
@vit9696 I sent you my ioreg in iMessage.

**Comment by Andrey1970AppleLife** [comment]
Панель PS2 трекпада не отображается, если не заведена батарея.
На десктопе батареи нет, вот и результат. Объяснить этот феномен я не могу.
Если кто-то не верит, удалите кекст батареи у себя на хакноуте и убедитесь сами.)

**Comment by usr-sse2** [comment]
@Andrey1970AppleLife Видимо macOS так отличает ноутбуки от десктопов.

**Comment by usr-sse2** [comment]
Добавил пустую батарею и пустой адаптер в DSDT, установил SMCBatteryManager. Работает.
