### ISSUE TITLE
Not working of Disable SIP in Catalina(10.15:19A583)

### ISSUE THREAD

**Issue by ZISQO** [acidanthera/bugtracker#505]
can't disable SIP in Catalina(10.15:19A583) even if using recover mode and config.plist(0x67)
* OpenCorePkg-R0.5.1-DevBuild-10072019_084710

could you please check it if can possible?
(10.14.6 has been working fine but not yes 10.15:19A583)

thanks regards

**Comment by vit9696** [comment]
0x67 does not disable sip. Works fine according to our knowledge.

**Comment by ZISQO** [comment]
thanks!
