### ISSUE TITLE
FwRuntimeServices.efi. EFI cannot boot Linux systems, such as ubuntu, deepin

### ISSUE THREAD

**Issue by fangf2018** [acidanthera/bugtracker#508]
Black screen, no reaction. What documents do I need to provide?

**Comment by vit9696** [comment]
Hello, linux boots fine on our test boards. Please use the support forums to determine what exactly is the cause. If you find a confirmation that there is some issue with the driver, come back and provide the technical details.

**Comment by arfaWong** [comment]
@fangf2018 Did you solve this problem？I had the same problem.

**Comment by MikeBeaton** [comment]
I case anybody else arrives here, it is worth noting that this is usually a quirks issue, with enabling `SyncRuntimePermissions` being the first thing to try.

**Comment by MikeBeaton** [comment]
See also https://github.com/acidanthera/bugtracker/issues/491
