### ISSUE TITLE
error loading kernel cache (0x1) 　

### ISSUE THREAD

**Issue by fangf2018** [acidanthera/bugtracker#509]
The system kernel often broken. Would you please add replacement commands to LogoutHook. command? 

sudo cp -R /Library/Apple/System/Library/PrelinkedKernels/prelinkedkernel /System/Library/PrelinkedKernels

**Comment by Andrey1970AppleLife** [comment]
Please use the support forums to determine what exactly is the cause. If you find a confirmation that there is some issue with the driver, come back and provide the technical details.
