### ISSUE TITLE
Recovery 10.15 (dmg) OCB: LoadImage failed - Unsupported 

### ISSUE THREAD

**Issue by rektimus** [acidanthera/bugtracker#510]
Unable to boot Recovery. I tried a combination of different DisplayLevel, Target, HaltLevel and ScanPolicy and was able to successfully boot it once but after rebooting none of my entries would boot. Assuming it was corrupted, I created a new USB installed and reinstalled, same issue. Below are the different combinations I tried.

DisplayLevel
	Default		        2,147,483,650	0x80000002	ERRORS, WARNINGS
	Recommended	75		               0x4B		INFO, EFI, WARNINGS, INIT
	Failsafe	                0		               0x0		        DISABLED?
	Advised		        2,147,483,714	0x80000042	ERRORS, WARNINGS, INFO
	Everything	        2,155,566,591	0x807B55FF	*

Target
	Default		        19		0x13		UEFI, CONSOLE, ENABLED
	Recommended	75		0x4B		FILE, NVRAM, UEFI, DATAHUB, ENABLED
	Failsafe	                0		0x0		        DISABLED?
	Advised		        67		0x43		FILE, CONSOLE, ENABLED
	Everything	        61		0x3D		*

HaltLevel
	Default		2,147,483,648	0x80000000	ERRORS
	Failsafe	        2,147,483,648	0x80000000	ERRORS
	Advised		2,147,483,714	0x80000042	ERRORS, WARNINGS, INFO
	Everything	2,155,566,591	0x807B55FF	*

ScanPolicy
	Default		983,299		0xF0103		OC_SCAN_FILE_SYSTEM_LOCK
							                        OC_SCAN_DEVICE_LOCK
							                        OC_SCAN_ALLOW_FS_APFS
							                        OC_SCAN_ALLOW_DEVICE_SATA
							                        OC_SCAN_ALLOW_DEVICE_SASEX
							                        OC_SCAN_ALLOW_DEVICE_SCSI
							                        OC_SCAN_ALLOW_DEVICE_NVME
	Recommended	0				        OC_SCAN_ALL?
	Failsafe
	Advised		590595		0x90303        OC_SCAN_FILE_SYSTEM_LOCK
							                        OC_SCAN_DEVICE_LOCK
							                        OC_SCAN_ALLOW_FS_APFS
							                        OC_SCAN_ALLOW_FS_HFS
							                        OC_SCAN_ALLOW_DEVICE_SATA
							                        OC_SCAN_ALLOW_DEVICE_NVME

[EFI.zip](https://github.com/acidanthera/bugtracker/files/3709851/EFI.zip)

**Comment by Andrey1970AppleLife** [comment]
Please use the support forums to determine what exactly is the cause. If you find a confirmation that there is some issue with the driver, come back and provide the technical details.

**Comment by parorisim** [comment]
@rektimus I hava the same issue, but if I enable AvoidHighAlloc, the system will never boot up. Cant you share your config.list?
