### ISSUE TITLE
Add a "BluetoothDriver.efi" driver for OpenCore so BT devices can be used with the OC boot screen.

### ISSUE THREAD

**Issue by Bram-Brooks** [acidanthera/bugtracker#511]
Hi all,

Adding a "BluetoothDriver.efi" driver for OpenCore so Bluetooth devices can be used with the OC boot screen would seem like a logical progression for this project (imo). Right now, only wired devices can be used which is a bit of a hassle since me (and I'm sure a lot of other as well use all wireless peripherals). There are probably other, more important priorities right now for the project but I hope this can be considered for future additions. Thanks in advance.

**Comment by DrConflict** [comment]
People do not want to buy over prices BT/wifi card though. Can it only work with HID BT devices somehow? People have all kinds of BT devices.

**Comment by vandroiy2013** [comment]
How do you imagine it? Where will module (in BIOS) get the keyboard information that needs to be connected? And if there will be more than one device in the coverage area? HID Proxy allows you to remember device paired under operating system when you reboot PC. Modules without a HID Proxy cannot remember anything.
