### ISSUE TITLE
OC 0.5.1 Unable to load FV2 UI

### ISSUE THREAD

**Issue by rektimus** [acidanthera/bugtracker#512]
[opencore-2019-10-11-105155.txt](https://github.com/acidanthera/bugtracker/files/3719923/opencore-2019-10-11-105155.txt)

Sorry I'm still new to not sure what is important or how things work but it looks like it is having an issue changing to graphics mode with console control? The ERRORs were on screen and not part of the log unfortunately. I am using the following debug and logging levels:

boot-args: -v debug=0x100 keepsyms=1

DisplayLevel: 2147483714
Target: 67
HaltLevel: 2147483648

28:759 00:056 OCB: Matched default boot option: Macintosh HD
28:815 00:055 OCB: Initial default is 1
32:545 03:730 OCB: Should boot from Macintosh HD (T:1|F:0)
32:830 00:285 OCB: Perform boot Macintosh HD to dp PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0x0,0x0)/HD(2,GPT,D09630F4-745F-4395-91C9-8462B44B5063,0x64028,0x1BE80460)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,5482E8B128F5D04E94D0D9EC1CC268BD)/\4B15E7BA-FBE3-4FA5-8D2A-AFBCF94DA969\System\Library\CoreServices\boot.efi (0/0)
32:875 00:044 OCB: Matching <> args on type 1 0
32:902 00:026 OCC: Configuring behaviour 2
32:928 00:026 OCC: Setting cc mode 0 -> 1
32:972 00:044 OCABC: Only 177/256 slide values are usable!
33:006 00:033 OCABC: Valid slides - 1-49, 128-255
33:064 00:058 OCC: Setting cc mode 1 -> 0
33:383 00:318 OCC: Setting cc mode 0 -> 1

**** ERROR: _lw_InitializeGraphics failed to create cursor
**** ERROR: _LoginUIInitializeGraphics Can't Initialize graphics mode: 0xE
**** ERROR: FDELoginUIInitializeUsers _LoginUIInitializeGraphics failed err 14
ERROR: LoginUI Initialize returned 0xe
ERROR!!! unlocking Core Storage volume (0xe)
Boot failed: will sleep for 10 seconds before exiting...

43:489 10:105 OC: Boot failed - Aborted
43:514 00:025 OCC: Configuring behaviour 1
43:549 00:034 OCC: Setting cc mode 1 -> 0
43:841 00:292 OCB: StartImage failed - Aborted

**Comment by Code-DJ** [comment]
You need to add AppleUiSupport.efi to the Drivers folder. In addition to that, I had to add AppleGenericInput.efi for my bluetooth keyboard and mouse to work in the console.

The only issue I have had is, it displays an error about loginui_progress**.png file but doesn't slow down the boot.

**Comment by rektimus** [comment]
Do I use the old ones? I thought they were merged into mainline OC 0.5.1. I tried AppleBootPolicy, AppeEvent, AppleImageConversion, AppleKeyMap and AppleUserInterfaceTheme Protocols.

**Comment by vit9696** [comment]
FirmwareVolume protocol. Please read the docs.

**Comment by rektimus** [comment]
Sorry vit, I even read the section on those I listed and spaced this out
