### ISSUE TITLE
Lilu: rtc read failure

### ISSUE THREAD

**Issue by v10x** [acidanthera/bugtracker#516]
This error shows on boot, the system works fine, although I wanted to open this issue to make sure it was tracked somewhere:

```
2019-10-14 06:59:36.924373-0700  localhost kernel[0]: (Lilu) Lilu:     rtc @ (DBG) successful rtc read client obtain
2019-10-14 06:59:36.924378-0700  localhost kernel[0]: (Lilu) Lilu:     rtc @ rtc read failure 1 bytes from 180 E00002C2
```

Platform:
- X299 Sage/10G
- Radeon VII

Versions:
- Lilu: latest stable debug release
- VirtualSMC: latest stable debug release
- AppleALC: latest stable debug release
- Whatevergreen: N/A

**Comment by vit9696** [comment]
Broken RTC device in ACPI. Upper 128 bytes removed by bugged bootloader or something.

**Comment by v10x** [comment]
@vit9696 The driver is actually there in OC configuration:
```
<key>UEFI</key>
	<dict>
		<key>ConnectDrivers</key>
		<true/>
		<key>Drivers</key>
		<array>
			<string>ApfsDriverLoader.efi</string>
			<string>FwRuntimeServices.efi</string>
			<string>VirtualSmc.efi</string>
		</array>
```

**Comment by v10x** [comment]
FWIW, the RTC device is `PNP0B00`

**Comment by v10x** [comment]
@vit9696 Thanks for pointing in the right direction, after digging I was able to finally fix the issue:
```
2019-10-14 08:07:36.892335-0700  localhost kernel[0]: (Lilu) Lilu:     efi @ (DBG) successful efi call GetVariable with response 00000000
2019-10-14 08:07:36.899432-0700  localhost kernel[0]: (Lilu) Lilu:     efi @ (DBG) successful efi call GetVariable with response 00000000
2019-10-14 08:07:36.906119-0700  localhost kernel[0]: (Lilu) Lilu:     rtc @ (DBG) successful rtc read client obtain
```

adapted and applied the RTC patch:

```
DefinitionBlock ("", "SSDT", 2, "V10X ", "RTC0", 0x00000000)
{
    External (_SB_.PC00.LPC0, DeviceObj)

    Scope (_SB.PC00.LPC0)
    {
        Device (RTC)
        {
            Name (_HID, EisaId ("PNP0B00") /* AT Real-Time Clock */)  // _HID: Hardware ID
            Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
            {
                IO (Decode16,
                    0x0070,             // Range Minimum
                    0x0070,             // Range Maximum
                    0x01,               // Alignment
                    0x08,               // Length
                    )
                IRQNoFlags ()
                    {8}
            })
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If (_OSI ("Darwin"))
                {
                    Return (0x0F)
                }
                Else
                {
                    Return (Zero)
                }
            }
        }
    }
}
```

**Comment by v10x** [comment]
Nevermind, the patch doesn't work. The error on boot shows up randomly.

Another interesting log line:
```
(Lilu) VirtualSMC:   efend @ no extra rtc memory is present for key erase
```

**Comment by v10x** [comment]
Tried `rtcread` util that ships with VirtualSMC
```
$ ./rtcread
AppleRTC I/O failure E00002C1
```

**Comment by vit9696** [comment]
I do not know what you did, but the issue is caused by RTC having only 128 bytes of memory. This is the configuration issue of yours, so please use the support forums to revert/add ACPI changes.

**Comment by hiradyazdan** [comment]
@v10x I am getting the same warning here:

```
VirtualSMC:   efend @ no extra rtc memory is present for key erase
```

Did you manage to work this out?

**Comment by EchoEsprit** [comment]
I'm having the same warning, I've tried to revert/add ACPI changes, even if I disable all my ACPI changes. I still get this warning.

**Comment by vit9696** [comment]
Well, it may be that your RTC does not support upper 128 bytes of memory.

**Comment by EchoEsprit** [comment]
So it is. Thx.

**Comment by hiradyazdan** [comment]
Doesn't IBM PC/AT computers only have less than 128 bytes memory? They're very ancient! I don't think this is the case, how did you confirm this?

**Comment by vit9696** [comment]
I can say that boards like ASUS P5E3 and such indeed have 128 bytes. Sandy+ boards normally have 256. But there may be exceptions.

**Comment by hiradyazdan** [comment]
https://uefi.org/sites/default/files/resources/ACPI_6_2.pdf

> **9.15.1 PC/AT-compatible RTC/CMOS Devices (PNP0B00)**
> The standard PC/AT-compatible RTC/CMOS device is denoted by the PnP ID PNP0B00. If an
> ACPI platform uses a device that is compatible with this device, it may describe this in its ACPI
> namespace. ASL may then read and write this as a linear 64-byte array. If PNP0B00 is used, ASL
> and ACPI operating systems may not assume that any extensions to the CMOS exist.

The OP has `PNP0B00`. So, as you say there may be exceptions, I am curious what motherboard he has with that ID.
