### ISSUE TITLE
Lilu/WEG doesn't work with QEMU at all by unknown QEMU pci-bridge vendor ID

### ISSUE THREAD

**Issue by Leoyzen** [acidanthera/bugtracker#517]
I found something interesting that Lilu/WEG can't find graphics device when using QEMU/kvm, so WEG doesn't work at all.
By digging Lilu code and log, I found that QEMU pci-bridge with vendor-id "0x1b36" (describe from [here](https://github.com/qemu/qemu/blob/master/docs/specs/pci-ids.txt), and Lilu does not recognize the vendor then continues.
```
void DeviceInfo::grabDevicesFromPciRoot(IORegistryEntry *pciRoot) {
	auto iterator = pciRoot->getChildIterator(gIODTPlane);
	if (iterator) {
		IORegistryEntry *obj = nullptr;
		while ((obj = OSDynamicCast(IORegistryEntry, iterator->getNextObject())) != nullptr) {
			uint32_t vendor = 0, code = 0;
			bool gotVendor = WIOKit::getOSDataValue(obj, "vendor-id", vendor);
			bool gotClass = WIOKit::getOSDataValue(obj, "class-code", code);
			auto name = obj->getName();
			DBGLOG("dev", "found pci device %s 0x%x 0x%x", safeString(name), vendor, code);

			// Strip interface, as we only care about class and subclass
			code &= WIOKit::ClassCode::PCISubclassMask;

			if (!gotVendor || !gotClass || (vendor != WIOKit::VendorID::Intel && vendor != WIOKit::VendorID::ATIAMD &&
			                                vendor != WIOKit::VendorID::AMDZEN && vendor != WIOKit::VendorID::VMware))
				continue;
```
Here is log where WEG works in my bare metal server:
![image](https://user-images.githubusercontent.com/5518468/66813564-8f846800-ef67-11e9-9479-7154d8a4b341.png)
Here is log where Lilu/WEG not work in QEMU hackintosh VM, you can see Lilu can't find graphic device from pci-bridge, it just continues because can't recognize the pci-bridge vendor of QEMU:
![image](https://user-images.githubusercontent.com/5518468/66813668-c195ca00-ef67-11e9-9a71-57d6dde22cff.png)
So maybe add QEMU vendor and logic will make Lilu/WEG works in QEMU/KVM.

**Comment by vit9696** [comment]
Well, does it work if you add this vendor code yourself?

**Comment by Leoyzen** [comment]
@vit9696 I'm not familar with XCode and Kext build. I will try to compile a version to see if it works.

**Comment by Leoyzen** [comment]
Update:
I update QEMU vendor-id 0x1b36 and update the logic code mention before then Lilu and WEG works in QEMU/kvm hackintosh.
Here is the update Lilu log:
![image](https://user-images.githubusercontent.com/5518468/66815405-c14afe00-ef6a-11e9-88ab-fe10efabe795.png)

**Comment by vit9696** [comment]
I committed the change in master, please confirm that it works and close the issue.

**Comment by Leoyzen** [comment]
Works for me, now Lilu has QEMU support which is awesome!Thanks.
Closing issues.
