### ISSUE TITLE
DeviceProperties don't set properly

### ISSUE THREAD

**Issue by doesprintfwork** [acidanthera/bugtracker#518]
As the title said, OpenCore doesn't want to set IOName, name, and class-code for disabling the unsupported GPU. Though it does set other things like alc-layout-id correctly. The screenshot below shows that OC does say they are set but they aren't when I look in IOReg after booting to macOS.

Edit: The Device Paths are correct. I've grab them with gfxutil.

![Screenshot_2019-10-14_at_5 58 03_PM](https://user-images.githubusercontent.com/49483931/66835485-2c5bfb00-ef92-11e9-8ef3-e0b135e6d9df.png)

**Comment by vit9696** [comment]
Then it is a limitation of device propertites protocol. OpenCore supplies these values to macOS, so you most likely have to use another method.
