### ISSUE TITLE
Random OC boot failures on APTIO V

### ISSUE THREAD

**Issue by v10x** [acidanthera/bugtracker#520]
After switching to FwRuntimeServices (that could be a coincidence), I've been seeing random failures to boot with OpenCore which log these:

```
13:202 00:029 Prelinked status - Success
23:245 10:042 OC: Boot failed - Aborted
23:251 00:006 OCC: Configuring behaviour 3
23:293 00:041 OCB: StartImage failed - Aborted
```

In other successful scenarios, the logs show up like:
```
42:780 00:027 Prelinked status - Success
42:794 00:014 OC: OcAppleGenericInputTimerQuirkExit status - Success
43:254 00:459 OC: OcAppleGenericInputKeycodeExit status - Success
```

Platform:
- X299 Sage/10G
- Radeon VII

Versions:

- OC: v0.5.2 development debug release
- Lilu: latest stable debug release
- VirtualSMC: latest stable debug release
- AppleALC: latest stable debug release
- Whatevergreen: N/A

**Comment by v10x** [comment]
From the instanelymac forum, it seems others have had some similar experiences:

- https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2693927
- https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2685625
- https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2689304

The error seems to come from https://github.com/acidanthera/OcSupportPkg/blob/d2c9149525d675775f53b963de5cb93dbc608c19/Library/OcBootManagementLib/OcBootManagementLib.c#L825

**Comment by v10x** [comment]
@vit9696 I'm happy to provide more logs, how can I get the boot.efi logs stored somewhere? I couldn't find it in the docs

**Comment by vit9696** [comment]
You can screenshot them. Boot efi verbosity is explained in the docs. This looks likeva support request to me, please use forums.

**Comment by vit9696** [comment]
Yeah, this is a configuration error of Booter section, not a bug.

**Comment by v10x** [comment]
Thanks

**Comment by v10x** [comment]
@vit9696 @vandroiy2013 I'd like for you to reconsider looking into this, given that it seems it might be affecting a bunch of users. I tried every possible configuration option in the Booter section, different flags and combinations, but the issue remains even though is random.

One thing that has improved it a lot is setting `ProvideCustomSlide`, despite what the logs say about not being needed, it reduces the amount of failures between boots/reboots by a lot. 

From my understanding, the code in OC sets a custom slide randomly every boot with that flag, it can happen though that it picks the same region that it picks without it causing it to fail.
