### ISSUE TITLE
Investigate handle connection issues

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#524]
It is reported that some configurations (HP laptops in particular) fail to connect the handles. This supposedly happens due to the checks we have in ConnectDrivers:

- https://github.com/acidanthera/OpenCorePkg/blob/4edf0b9/Platform/OpenCore/OpenCoreUefi.c#L169-L180
- https://github.com/acidanthera/OpenCoreShell/blob/ec469d6/Patches/skip-non-device-connect.diff

These checks are required for APTIO IV (ASUS Z87-PRO included) and make some sense (as they come from legacy Intel RC). However, if they break other platforms it is unclear what we can do here.

- [x] Investigate whether these checks break HP.
- [ ] Consider possibility to implement the connection as a quirk to override ConnectController on APTIO IV.
- [ ] Consider how standalone tools (which bypass OpenCore) can work with it.

**Comment by Download-Fritz** [comment]
HP laptops are unrelated and are fixed by https://github.com/acidanthera/OcSupportPkg/commit/c58836535983c7477f9816b0a73a735931d8025a

**Comment by vit9696** [comment]
Currently the only affected program is UEFI Shell. I submitted a [bug](https://bugzilla.tianocore.org/show_bug.cgi?id=2460) and a patch to EDK II upstream. Closing in favour of https://github.com/acidanthera/bugtracker/issues/323.
