### ISSUE TITLE
There are no kexts included in the BrcmPatchRAM Github releases or project

### ISSUE THREAD

**Issue by DrConflict** [acidanthera/bugtracker#525]
I'm trying to get my ASUS BT-400 dongle working with BrcmPatchRAM while following the guide included on the Github page. (Which is confirmed to be working according to the list). The problem is that the needed kexts described in the guide are not included in the release package or when I download the latest ZIP project. I'm on Catalina 10.15.0.

**Comment by Andrey1970AppleLife** [comment]
In November.

**Comment by headkaze** [comment]
In the mean time please use Meize's download link
https://www.insanelymac.com/forum/applications/core/interface/file/attachment.php?id=335665

**Comment by vit9696** [comment]
Just in case there are more, the link is from this topic:
https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/
Relevant message:
https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/?do=findComment&comment=2694146

This is where the kext testing happens currently.

@Andrey1970AppleLife, I think we want to update README file to point people to the thread. Also check what do we have on AppleLife, I remember there was a thread too. Please handle that and close again once done.

**Comment by Sniki** [comment]
@vit9696  the new kexts are working perfect,
My DW1560 BCM94352Z card is working perfect only with BrcmBluetoothInjector.kext.

However one thing i noticed is that it was not working (not being detected or detecting anything) for some reasons, after a lot of testing, i noticed that after you put laptop to sleep and wake again, it started to work.

For curiosity i added _OSI to XOSI rename and SSDT-XOSI (to emulate windows) and i rebooted, bluetooth was working on cold boot as well.

Could this be necessary or just a device/card specific thing ?

**Comment by Sniki** [comment]
@Andrey1970AppleLife Fix the InsanelyMac discussion link as it is broken.

**Comment by Andrey1970AppleLife** [comment]
Topic I was gone or it is moved or it is deleted. Give me a new link.

**Comment by headkaze** [comment]
Not sure why it was deleted. I've asked a moderator to undelete it until we
get an official binary on Github.
