### ISSUE TITLE
Dash in the screen upper left corner in case of start OpenCore.

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#527]

**Comment by Sniki** [comment]
@Andrey1970AppleLife are you referring to this one:
![dash](https://user-images.githubusercontent.com/30008333/67314965-ea890280-f505-11e9-85fe-6825f02b66dc.jpg)
If this is what you mean then yes, i have that problem as well, it hangs 2-5 sec there.

**Comment by Andrey1970AppleLife** [comment]
Yes it. But me quicker, less than 1 second.

**Comment by Sniki** [comment]
Just measured and to be exact, it's 6 sec for me...

**Comment by fangf2018** [comment]
仔细看文档

**Comment by fangf2018** [comment]
真菜

**Comment by ngc598** [comment]
Same dash here.

**Comment by cattyhouse** [comment]
@fangf2018 please don't troll, shame for you.

**Comment by williambj1** [comment]
For my laptop (ASUS, AMI BIOS, APTIO V), if I set OpenCore to the default boot entry, a dash will appear for about 3 seconds after the OEM logo disappears.
However, the dash will not appear when OpenCore is not the default boot entry and the method of entering OpenCore is to use the BIOS entry selector.

**Comment by ngc598** [comment]
> For my laptop (ASUS, AMI BIOS, APTIO V), if I set OpenCore to the default boot entry, a dash will appear for about 3 seconds after the OEM logo disappears.
> However, the dash will not appear when OpenCore is not the default boot entry and the method of entering OpenCore is to use the BIOS entry selector.

For me (Gigabyte Z370) it happens in both.
