### ISSUE TITLE
Black screen with 5700 XT Catalina Beta 2(19B77a) with WhateverGreen

### ISSUE THREAD

**Issue by errorexists** [acidanthera/bugtracker#528]
just tried the new Weg an still a black screen when booting on clover for second stage also tried boot args (agdpmod=pikera,vit9696) using either DP an HDMI ports with same results but on oc i have no issues with the 5700XT with DP an HDMI for primary an secondary monitor

**Comment by vandroiy2013** [comment]
For now Clover support by Acidanthera team is deprecated. Sorry. 
If you have problems with OpenCore feel free to open new bug report.

**Comment by errorexists** [comment]
ya no problems what so ever with OpenCore w/o WEG only with Clover

**Comment by errorexists** [comment]
as far as i know there should be no difference with whatevergreen on clover or opencore as far as i know they are the same kext

**Comment by vandroiy2013** [comment]
As far as i know Clover and OpenCore are two different bootloaders. And if one kext works well for you in OpenCore and the same one don't work in Clover, so maybe, this is Clover problem? Or your way of configuring Clover?
As i told you earlier Clover problems are out of Acidanthera's scope from September, 1 2019...

From that point Acidanthera will no longer officially support Clover bootloader. Things to keep in mind:

We will not intentionally break anything that currently works and our code remains fully opensource and available for external contribution.
We will no longer perform Clover compatibility release validation for our products, but we will fix our own bugs upon request.
With future releases we may abandon select products, hacks specific to Clover, and Clover patch contribution to ease maintenance burden.
