### ISSUE TITLE
Missing layout for S1220

### ISSUE THREAD

**Issue by esetnik** [acidanthera/bugtracker#529]
The ASUS IX Hero motherboard uses a slightly modified 
ROG SupremeFX 8-Channel High Definition Audio CODEC S1220. I noticed that there is no specific configuration for S1220 listed under the [support codecs](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs) and none of the layout-ids for ALC1220 or ALCS1220A are fully working on this motherboard. I am not sure if this is the right place to report missing support. The closest layout-id is 2 which has front headphone jack working but not the line-out ports on the motherboard.

**Comment by vandroiy2013** [comment]
Feel free to add resources for your codec.
