### ISSUE TITLE
OpenCore - Apple magic keyboard not working on boot

### ISSUE THREAD

**Issue by carbonimax** [acidanthera/bugtracker#532]
This problem occurs on gigabyte z390 aorus master in Boot Picker.
With Apple Magic Keyboard in USB (A1644) it doesn't work and it Timeout but with old Apple keyboard (A1243), it works.

Driver used:
UsbKbDxe.efi

**Comment by Andrey1970AppleLife** [comment]
It bluetooth keyboard.

**Comment by carbonimax** [comment]
Yes, I know... but it could be connected in USB! And it works in clover but not in OC.

**Comment by Andrey1970AppleLife** [comment]
Oops. Unless usb-lightning not only for battery charging?
Delete UsbKbDxe.efi and use Input section.

**Comment by carbonimax** [comment]
It works!
Thank you

**Comment by romancin** [comment]
> It works!
> Thank you

Which parameters did you use on Input section?
