### ISSUE TITLE
Kernel Panic due division by zero (0=divide error) in i7 9750H (Lenovo Thinkpad P53)

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#534]
I attached the log of kernel panic=,, i have tried 0x06, 0xA, 0x14 and 0x1E. None of them are working.

Specification of Lenovo 
Processor : intel Core i7 9750H
iGPU : Intel HD 630
eGPU : Nvidia Quadro T2000 (Disable from DSDT)
Built-In Display Resolution : 1920 x 1080

This is my _DSM method of IGPU

`Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
                {
                    If (LEqual (Arg2, Zero))
                    {
                        Return (Buffer (One)
                        {
                             0x03                                           
                        })
                    }

                    Return (Package ()
                    {
                        "name", 
                        Buffer (0x08)
                        {
                            "display"
                        }, 

                        "AAPL,slot-name", 
                        Buffer (0x09)
                        {
                            "Built-In"
                        }, 

                        "model", 
                        Buffer (0x25)
                        {
                            "Intel UHD Graphics 630 macOS Edition"
                        }, 

                        "device_type", 
                        Buffer (0x13)
                        {
                            "Display Controller"
                        }, 

                        "hda-gfx", 
                        Buffer (0x0A)
                        {
                            "onboard-1"
                        }, 

                        "device-id", 
                        Buffer (0x04)
                        {
                             0x9B, 0x3E, 0x00, 0x00                         
                        }, 

                        "AAPL,ig-platform-id", 
                        Buffer (0x04)
                        {
                             0x00, 0x00, 0x9B, 0x3E                         
                        }, 

                        "enable-cfl-backlight-fix", 
                        Buffer (0x04)
                        {
                             0x10, 0x00, 0x00, 0x00                         
                        }, 

                        "framebuffer-patch-enable", 
                        Buffer (0x04)
                        {
                             0x01, 0x00, 0x00, 0x00                         
                        }, 

                        "framebuffer-unifiedmem", 
                        Buffer (0x04)
                        {
                             0x00, 0x00, 0x00, 0xC0                         
                        }, 

                        "framebuffer-con1-index", 
                        Buffer (0x04)
                        {
                             0x01, 0x00, 0x00, 0x00                         
                        }, 

                        "framebuffer-con1-busid", 
                        Buffer (0x04)
                        {
                             0x01, 0x00, 0x00, 0x00                         
                        }, 

                        "framebuffer-con1-type", 
                        Buffer (0x04)
                        {
                             0x00, 0x08, 0x00, 0x00                         
                        }, 

                        "framebuffer-con2-enable", 
                        Buffer (0x04)
                        {
                             0x01, 0x00, 0x00, 0x00                         
                        }, 

                        "framebuffer-con2-index", 
                        Buffer (0x04)
                        {
                             0x02, 0x00, 0x00, 0x00                         
                        }, 

                        "framebuffer-con2-busid", 
                        Buffer (0x04)
                        {
                             0x02, 0x00, 0x00, 0x00                         
                        }, 

                        "framebuffer-con2-type", 
                        Buffer (0x04)
                        {
                             0x00, 0x08, 0x00, 0x00                         
                        }, 

                        "enable-dpcd-max-link-rate-fix", 
                        Buffer (0x04)
                        {
                             0x01, 0x00, 0x00, 0x00                         
                        }, 

                        "dpcd-max-link-rate", 
                        Buffer (0x04)
                        {
                             0x0A, 0x00, 0x00, 0x00                         
                        }
                    })
                }`

[Kernel_2019-10-27-000500_Andres-MacBook-Pro-2.panic.zip](https://github.com/acidanthera/bugtracker/files/3775270/Kernel_2019-10-27-000500_Andres-MacBook-Pro-2.panic.zip)

**Comment by vit9696** [comment]
Well, this division by zero happens in IGPU driver, it is not our issue.
