### ISSUE TITLE
Couldn't Allocate runtime area- Error allocating 0x11c4 at 0x00000000

### ISSUE THREAD

**Issue by mathew1975** [acidanthera/bugtracker#535]
Hi

With 5.1 version of opencore I am getting this Couldn't allocate runtime area Error. but with older version which uses AptioMemoryFix.efi I am able to boot into macOS without any issues. I am using Thunderbolt 3.0 PCIe card in my machine. 

![memory-allocation-error](https://user-images.githubusercontent.com/57066680/67636135-5c29cd80-f8c5-11e9-9cef-284548b33e62.jpg)

**Comment by vit9696** [comment]
Use DevirtualiseMmio and other quirks.

**Comment by mathew1975** [comment]
Hi Vit9696
Thank you for your speedy reply but still I am getting the same error regarding memory allocation. have you checked something like this error? this issue was there with Clover since the Aptiomemory fix. so just to get an idea of what may be the exact cause...
Thank you
