### ISSUE TITLE
OC: Experiencing black screen logging to file on ExitBS

### ISSUE THREAD

**Issue by cecekpawon** [acidanthera/bugtracker#538]
Hello,

As you probably know I have created some bogus OC log driver while ago to log OC, [here](https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2672161). It works fine before and Im really unsure since what revision when it no longer work anymore. Is this somehow related with some of new OC 'security policy' that I didnt know, that prevent other tools to create files on ExitBS? Or something broken on my side, eg my FAT driver? I do more test related to this issue by activating internal OC log (with OC_LOG_FILE) and the problem still persist, ended up with black screen.

What i really like to know: Is this bug on my machine / I misconfigured my OC setup, or OC bug maybe? I works fine on your test machine?

Thanks

**Comment by vit9696** [comment]
It is the first time I hear of your project, but without going into details logging after ExitBootServices cannot work as per UEFI spec.
