### ISSUE TITLE
Issue with left click on VoodooPS2 on dell Inspiron3537

### ISSUE THREAD

**Issue by verebes1** [acidanthera/bugtracker#542]
I have a problem using this VodooPs2 kext on my Dell Inspiron 3537 which has a Synaptics TouchPad. everything works as expected apart from the secondary click. No matter if I choose tap with two fingers or bottom right or left it does not work, I had to revert to RehabMans version as there it does work however the other features like three-finger swipe between full-screen apps do not work, this is why I would prefer to use your version if the left click would work.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/557

**Comment by verebes1** [comment]
Why is my issue closed as a duplicate? if this was chronologically the first open issue which relates to this problem and the other #557 is a duplicate?

**Comment by Andrey1970AppleLife** [comment]
There are more than posts.
