### ISSUE TITLE
No display output with iMacPro1,1 and Vega 64 on 10.15.1

### ISSUE THREAD

**Issue by maddie** [acidanthera/bugtracker#543]
I had a perfectly working machine with the following specs:

CPU: i7 8700K
MB: Asus Z370-F
GPU: Asus ROG Strix Vega 64
SMBIOS: iMacPro1,1

I have iGPU enabled and configured as headless.

It runs 10.15 just fine, with OC 0.5.1 and previous release of plugins.

After upgrading to OC 0.5.2 and making corresponding changes to `config.plist` and upgrading plugins, I proceeded to upgrade to 10.15.1. In verbose mode now it complains that:

```
Hash data from ME never returned, status = 1, doing retry #x 
```

... which should be fixable by `-disablegfxfirmware`, but this argument should not be needed if WEG is working correctly. With `-disablegfxfirmware`, there's no more kernel panic due to GFX firmware load timeout, but boots into a black screen. Pinging the host from another computer doesn't respond, so I assume it didn't make it to the login screen.

And also, I noticed that when this line appear:

```
Adding AGDP mode validate property
```

... multiple purple lines show up on the upper part of the screen, which is almost the same as #438, which appears to be fixed for me in previous versions.

I tried to:

- Add `agdpmod=vit9696` or `agdpmod=pikera` to boot arguments
- Rollback to previous OC version, replace plugins with the latest ones
- Removing WEG (in #523 it says it would at least make HDMI work)
- Disabling iGPU

Using a `DEBUG` version of Lilu and WEG, and `-liludbgall -wegdbg` doesn't seem to have additional logs being printed (or printed early in the boot process which gets scrolled up before I can see them).

Is there anything I can do to provide more detailed info for debugging?

**Comment by errorexists** [comment]
have you tried new weg 1.3.4 an use the smbios for 8700(k) imac 19,2 an just use the HDMI till the update finished an no other boot args?

**Comment by maddie** [comment]
The update finished already. All plugins are updated to the latest release version.

**Comment by vit9696** [comment]
This looks like WhateverGreen not loaded at all.

**Comment by maddie** [comment]
Yes, that's what I thought. So I have double-checked the OC config for the WEG entry, and also tried to replace the self-compiled Kext with the release binary from GitHub. Both yield the same result. Also tried to use `-wegbeta` and `-lilubeta` just in case, but still doesn't work.

Next step I think I'll use a `DEBUG` version of OC and enable logging, see if there's anything wrong with Kext injection. But I'll have to report back a few days later because I'll be away from the machine for the weekend.

**Comment by cattyhouse** [comment]
> Yes, that's what I thought. So I have double-checked the OC config for the WEG entry, and also tried to replace the self-compiled Kext with the release binary from GitHub. Both yield the same result. Also tried to use `-wegbeta` and `-lilubeta` just in case, but still doesn't work.

that's not a good method to make sure of weg loading. If you can, ssh into your macOS and run:
`kextstat | grep -i whatevergreen`

**Comment by maddie** [comment]
I can't SSH into the machine since it's not responding to pings and no ports accessible after trying to boot into macOS with `-disablegfxfirmware`, so I assume it didn't really make it into that stage.

**Comment by vit9696** [comment]
You could use debug WEG and enable debugging, then boot into verbose mode. Debug prints should make it obvious whether WEG works. You could record a video…

Now I think of it, if you have Vega, i.e. discrete GPU, your IGPU framebuffer should have connector-less ig-platform-id. Even so, the behaviour is strange. Please upload your configuration directory (EFI).

@Andrey1970AppleLife please check it once here, but do not close even if it is too borked. I think WEG might not behaving properly, so we should at least try to investigate it.

**Comment by maddie** [comment]
Thanks for the suggestion. I will do so as soon as I get back to the machine.

My IGPU is indeed configured as connector-less, I will upload my EFI as soon as I can.

**Comment by maddie** [comment]
[EFI.zip](https://github.com/acidanthera/bugtracker/files/3798557/EFI.zip)

Here's the EFI folder.

**Comment by Andrey1970AppleLife** [comment]
You use IGPU connector-less therefore it is necessary use iMac19,1
You have a lot of nonsense in PciRoot(0x0)/Pci(0x2,0x0)
There shall be only AAPL,ig-platform-id 0300913E

**Comment by maddie** [comment]
Thanks for the input, I will try it later tonight.

I understand what you're saying, but the problem is the same configuration worked just fine before for me, from Mojave to Catalina 10.15, so in theory, it shouldn't just break like this.

**Comment by maddie** [comment]
`DEBUG` version of WEG with `-wegdbg` doesn't seem to produce any additional output at all (with slo-mo capturing the screen), perhaps the Kexts are not being loaded at all?

Here's the debug OC log, I can't see anything related to Kext injection, is this normal?

[opencore-2019-11-04-145113.txt](https://github.com/acidanthera/bugtracker/files/3804557/opencore-2019-11-04-145113.txt)

**Comment by vit9696** [comment]
Definitely not, your kexts are not injected due to
```
06:315 00:034 Prelinked status - Invalid Parameter
```

**Comment by maddie** [comment]
Can I access the PrelinkedKernels from the Recovery?

**Comment by vit9696** [comment]
Yes, you can. You will need to use Terminal and mount your Macintosh HD.

**Comment by maddie** [comment]
Here it is. 

[PrelinkedKernels.zip](https://drive.google.com/open?id=1Zq5wiaNmBu9HRAzSLUWx83RBqKLRwwXX)

Does that mean the PrelinkedKernels are corrupted? Is there a way to re-create these files?

**Comment by Download-Fritz** [comment]
@maddie No, it was a stupid mistake on our end, fixed at https://github.com/acidanthera/OcSupportPkg/commit/53ea852bc3355ed3455bc988a56d694821f08471

**Comment by maddie** [comment]
Oh, glad that this is a real bug report instead of a "support ticket" XD

I'll compile and see if it works

**Comment by maddie** [comment]
Confirm fixed! I'll close this issue now. Thanks a lot for the super-fast fix! :)
