### ISSUE TITLE
Homebrew bug causes build failures in MacInfoPkg

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#544]
https://travis-ci.com/acidanthera/MacInfoPkg

**Comment by maddie** [comment]
Related issue: https://travis-ci.community/t/syntax-error-unexpected-keyword-rescue-expecting-keyword-end-in-homebrew/5623

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/MacInfoPkg/commit/ac0d1a5fff30dbaa2a836fb643e548f36a6698c3
