### ISSUE TITLE
Z390 boot disk does not work

### ISSUE THREAD

**Issue by fangf2018** [acidanthera/bugtracker#545]
[opencore-2019-11-02-094417.txt](https://github.com/acidanthera/bugtracker/files/3800324/opencore-2019-11-02-094417.txt)

[nvram.plist.zip](https://github.com/acidanthera/bugtracker/files/3800325/nvram.plist.zip)
DisableVariableWrite yes
LegacyEnable yes
ExposeSensitiveData 3
RequestBootVarRouting yes

[config.plist.zip](https://github.com/acidanthera/bugtracker/files/3800326/config.plist.zip)

**Comment by fangf2018** [comment]
Install bootcamp assistant in Windows，Sometimes the startup switch can be carried out, and sometimes the BIOS startup item will be destroyed

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
