### ISSUE TITLE
Final Cut Pro preview video igpu frequency is limited to 0.35

### ISSUE THREAD

**Issue by zijun-he** [acidanthera/bugtracker#546]
CPU: i7 8700K
MB: GIGABYTE z370n 
GPU: RX580
SMBIOS:  iMac19,1
I have iGPU enabled and configured as headless. ig-platform-id:0300923E
OpenCore 0.5.3
Final cut pro preview timeline video igpu frequency card at 0.35, transition video card. Whether this problem can be improved. Thank you

[weg.txt](https://github.com/acidanthera/bugtracker/files/3800501/weg.txt)

<img width="381" alt="截屏2019-11-02下午6 28 15" src="https://user-images.githubusercontent.com/52475027/68069725-40c83200-fd9f-11e9-9818-634b630e59a6.png">

**Comment by fangf2018** [comment]
![weg](https://user-images.githubusercontent.com/19627926/68069851-02cc0d80-fda1-11e9-9a90-4c91e868b0a4.png)
Normal frequency

**Comment by Andrey1970AppleLife** [comment]
Because no loading GuC firmware for SKL+ 
The experimental function loading GuC firmware causes freezes and crashes.
The stable decision isn't present.

**Comment by yushuai** [comment]
Hi, I would like to ask when the stable GuC firmware will release. Is there another way to get 1.2GHZ for now.

**Comment by vit9696** [comment]
Not planned at all, ask Apple.

**Comment by yushuai** [comment]
be nice, OK? michael yu 邮箱：ankangye@gmail.com 签名由 网易邮箱大师 定制 On 11/12/2019 21:42, vit9696 wrote: Not planned at all, ask Apple. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
