### ISSUE TITLE
VM swap subsystem adds noticeable delay (5 to 10 seconds) during verbose boot on NVME SSD's

### ISSUE THREAD

**Issue by DrConflict** [acidanthera/bugtracker#548]
Not sure if this is being worked on or if it's even possible to optimise this further.
But VM Swap adds a noticeable delay during OC boot with all the latest RELEASE
packages. OC 0.5.2 & ASP 2.1.2. All other boot processes run fast.

**Comment by vit9696** [comment]
No idea what the issue is about or whether it is anyhow related to our code, closing as invalid.
