### ISSUE TITLE
OC 0.5.2 (RELEASE) possible StartupDisk bless boot bug on 10.15.1

### ISSUE THREAD

**Issue by DrConflict** [acidanthera/bugtracker#549]
After updating both OC and ASP packages I'm encountering problems with StartupDisk to boot into my
Win 10 disk. It worked fine before the latest RELEASE packages but I'm not completely sure the error is
related to OC though. But It's probably a good idea to investigate this issue. I'm on 10.15.1 with all the latest RELEASE package files. Not using dev builds.

![Screenshot 2019-11-03 at 21 20 11](https://user-images.githubusercontent.com/48632976/68091419-bacfe800-fe7f-11e9-8afc-2afda506b978.png)

**Comment by Andrey1970AppleLife** [comment]
Reboot once in macOS using StartupDisk.
