### ISSUE TITLE
10.15.1 Install screen unusable on RX5700 

### ISSUE THREAD

**Issue by gkankanh** [acidanthera/bugtracker#550]
on a Saphire RX5700 GPU OC boot with option agdpmod=pikera to instal 10.15.1 boots into an install screen that is not legible. The monitor used was a LG 4K monitor connected to display port. Tried a different monitor DELL 1080p using HDMI with little or no difference.
Low Priority. CPU Ryzen 3900X. MB GB X570 AORUS PRO WIFI.

**Comment by vandroiy2013** [comment]
Example

![IMG_1673](https://user-images.githubusercontent.com/8144780/68126804-43509600-ff1d-11e9-90ea-70184fe0b3bc.jpeg)

**Comment by gkankanh** [comment]
exactly.

**Comment by gkankanh** [comment]
![IMG_0797](https://user-images.githubusercontent.com/6466505/68127607-34012680-fee4-11e9-94f0-11f18ee510c5.jpg)

**Comment by errorexists** [comment]
i had the same issue i had to remove the DP an only use the HDMI an remove weg to continue the updates using OC

**Comment by jcastro** [comment]
I've tried with 5700 and Clover and it's the same

**Comment by vandroiy2013** [comment]
Problem was fixed by Apple in macOS 10.15.2 Developer Beta 1.
