### ISSUE TITLE
OcSupportPkg: Library/OcCompressionLib/zlib/zlib.h:1919:51: error: unknown type name 'wchar_t'

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#552]
```
In file included from /prj/GIT/OcSupportPkg/Library/OcCompressionLib/zlib/adler32.c:8:
In file included from /prj/GIT/OcSupportPkg/Library/OcCompressionLib/zlib/zutil.h:18:
/prj/GIT/OcSupportPkg/Library/OcCompressionLib/zlib/zlib.h:1919:51: error: unknown type name 'wchar_t'
ZEXTERN gzFile         ZEXPORT gzopen_w OF((const wchar_t *path,
                                                  ^
```

**Comment by vit9696** [comment]
Looks like garbage, does adding a typedef CHAR16 wchar_t to https://github.com/acidanthera/OcSupportPkg/blob/master/Library/OcCompressionLib/zlib/zconf.h#L59 work? Guarded by the same set of macro ofcourse.

**Comment by nms42** [comment]
From my understanding there is a big part of code not needed when library used in embedded environment. Like gzopen_w, for example. But earlier in other issue You wrote on Z_SOLO being undefined for purpose.

**Comment by vit9696** [comment]
Right, the point of not using Z_SOLO is to have working compress/uncompress interfaces e.g. [here](https://github.com/acidanthera/OcSupportPkg/blob/e48286e720827f3fa9bda1083dc349c4e4b07a9e/Library/OcCompressionLib/zlib/zlib_uefi.c). When using Z_SOLO, zlib does not support zcalloc, see e.g. [this line](https://github.com/acidanthera/OcSupportPkg/blob/e48286e720827f3fa9bda1083dc349c4e4b07a9e/Library/OcCompressionLib/zlib/inflate.c#L212), and it was very inconvenient to rewrite things passing the allocator manually.

We do not care about the size of debug builds, and with the release ones we have LTO, which actually kills the dead code. This is a bit not nice, but it allows us to use zlib with as little changes as possible and keep it in sync with upstream codebase with little effort.

**Comment by nms42** [comment]
Is gzopen_w() used anywhere?

I did not found usage. I did not found code for it.

May be

```
#if 0
...
#endif
```

**Comment by vit9696** [comment]
It is not, the only point here is to reduce the amount of changes in zlib. For this reason I would rather add a typedef to zconf, which we write ourselves.

**Comment by nms42** [comment]
More correct solution to undefine _WIN32 and _WIN64.

**Comment by nms42** [comment]
Made test compilations on my rig with undefined _WIN32 & _WIN64. Looks good to me. Shall I commit change?

**Comment by vit9696** [comment]
Well, I believe the change should be local, so best to edit zconf.h to contain the following:

```
#ifdef _WIN32
#undef _WINT32
#endif

#ifdef _WIN64
#undef _WIN64
#endif
```

If this works, then commit.

**Comment by nms42** [comment]
Done
