### ISSUE TITLE
Rename MacPro ACPI devices "PXS*" to "GFX*"

### ISSUE THREAD

**Issue by eweiman** [acidanthera/bugtracker#553]
On the Mac Pro (likely 1,1 through 5,1) the PCIe slots show up as PXS* and it would seem that part of the puzzle in getting HEVC hardware accelerated encoding from AMD Polaris or newer is that the graphics device be seen as GFX0 not PXS1. 

To eliminate the need of patching this manually via OpenCore or other means, if WEG was also able to rename this like it does for PEG1 for example I believe it would add flexibility for genuine Macs. 

The point I'm not clear on is how one would want behavior of a multi-GPU system, would this mean only one slot is able to be accelerated? or if you have GFX0 (PXS1) and GFX1 (PXS2) do you get acceleration for both cards by having one that is tagged under GFX0?

Either way, even getting it from one card I suspect would be enough to be useful. 

For example my 3,1 shows the RX 580 (installed in Slot 1) in this point in IOReg: 
`PCI0.NRP5.PXS1`
If that GPU was seen as below, it should be able to enable HEVC hardware encode as discussed in macrumors forums
`PCI0.NRP5.GFX0`

https://forums.macrumors.com/threads/activate-amd-hardware-acceleration.2180095

**Comment by vit9696** [comment]
As far as I know it is irrelevant how GPUs are named. The key is board id. You can always test by renaming devices with OpenCore.

**Comment by eweiman** [comment]
Please don't confuse this with 3D / 2D acceleration, this is related to video encode / decode with h264 / h265 (HEVC) with AMD cards. 

Sure seems like it matters ... take for example an iMacPro1,1 (hack) clover booted with DSDT mod showing as GFX2 instead of GFX0. There is no HEVC acceleration in that config, but there is when it is assigned as GFX0. 

Example from MacRumors ...
Using OpenCore to boot a real 5,1 as an iMacPro1,1 it isn't enough to just change SMBIOS settings to get HW accel working a patch to the ACPI tables was also needed. 

Screenshots while set as GFX2 on my hack
![Screen Shot 2019-11-06 at 3 19 19 PM](https://user-images.githubusercontent.com/3902496/68340092-68730f00-00ab-11ea-8e14-538efffa43e0.jpg)
![Screen Shot 2019-11-06 at 3 18 46 PM](https://user-images.githubusercontent.com/3902496/68340093-68730f00-00ab-11ea-846d-296c7fffd75e.jpg)

Screenshots while set as GFX0 on the same hack
![Screen Shot 2019-11-06 at 3 33 09 PM](https://user-images.githubusercontent.com/3902496/68340159-804a9300-00ab-11ea-806a-79b267bfd1b5.jpg)
![Screen Shot 2019-11-06 at 3 32 58 PM](https://user-images.githubusercontent.com/3902496/68340160-804a9300-00ab-11ea-976f-ffaab1f91511.jpg)

**Comment by vit9696** [comment]
Yes, I understand. Are you sure this is not a bug of this exact application? I know that IGPU name is important, and I also know that discrete GPU name is not checked anywhere. Could you use something more reliable for a test, e.g. Apple software or something opensource to actually run HEVC encoder and see?

**Comment by tsialex** [comment]
> Yes, I understand. Are you sure this is not a bug of this exact application? I know that IGPU name is important, and I also know that discrete GPU name is not checked anywhere. Could you use something more reliable for a test, e.g. Apple software or something opensource to actually run HEVC encoder and see?


With a MP5,1 spoofing iMacPro1,1 ffmpeg do not work with videotoolbox HEVC hardware encoding when it's the default PSX*, but only when you rename it to GFX0:

[https://forums.macrumors.com/attachments/screenshot-2019-10-31-at-10-18-10-am-png.873825/](url)

**Comment by vit9696** [comment]
Well, I obviously will not read 25 pages on the forums, but I sort of heard you. What I can suggest is to add a device property to instruct WEG to rename discrete GPUs, like on Hacks. Will that suffice?

**Comment by h9826790** [comment]
I am the original poster of that 25 pages thread about activating HWAccel on Mac Pro 5,1. The main contributor in the community about how to make HWAccel work on Mac Pro 5,1.

And I am also the person who confirmed MUST rename PSX# to GFX0 to get HEVC hardware encode working on the Mac Pro 5,1.

At this moment, we must use OpenCore / Clover to spoof Mac Pro 1,1 SMBIOS on a genuine Mac Pro 5,1 to get HEVC hardware encoding working properly.

However, that will screw up quite a few parameters on the Mac Pro 5,1 (e.g. CPU clock speed).

Also, there is also some evidences that both OpenCore and Clover will write something into the Mac Pro 5,1's firmware private NVRAM section. In some rare case, this will brick a Mac Pro 5,1's logic board. And most Mac Pro users simply don't have the skill to dump -> clean -> flash the firmware periodically.

Therefore, our final goal is by only using WEG to set shikigva=32 and shiki-id=Mac-7BA5B2D9E42DDD94 in the boot argument to get FULL HWAccel. However, without OpenCore and Clover, there is no way for us to rename PSX# to GFX0. Which also means, it's impossible for us to achieve full HWAccel safely.

Therefore, we really wish you can include this extra renaming function into WEG.

Million thanks in advance!

**Comment by vit9696** [comment]
Well, this is absolute garbage you wrote about OpenCore, it does nothing like that. For Clover — possibly. As for renaming, so you basically need another boot argument?

**Comment by h9826790** [comment]
It's not "heard from someone" or "someone says" OpenCore will do that. But I am working with tsialex in this area, and found that.

We completely clean up my Mac Pro's firmware private NVRAM section (by dump -> clean -> flash)

Then boot once, dump the firmware as control.

Then bless OpenCore, boot, dump the firmware again.

We then disable OpenCore, reboot, and make a 3rd dump for comparison. Just in case OpenCore masked something in the 2rd dump (software dump inside macOS), and produce false result.

At this moment, we 100% sure somethings are written to the private NVRAM section in the 2nd and 3rd dump. Just not very sure what's that, or why it happen.

Tsialex still analysing the data we extracted. Of course, we can't 100% sure that's done by OpenCore yet. May be OpenCore SMBIOS spoofing (and the SMBIOS reversion in the 3rd boot) triggered the Mac Pro itself to write something into the NVRAM. However, we tends to stay on the safe side, and consider it may cause some issues in long term.

In the last few months, we found that the Mac Pro 5,1 firmware is so much easier to be bricked than we expect. e.g. Even the security certificates produce by UEFI Windows 10 may able to brick it (won't happen in general, but can happen.

Again, this is not rumour on the net. Tsialex successfully recovered a bricked logic board by just cleaning up the duplicated certs in the private NVRAM (via hardware dump and flash). This is why we so care about "if anything is written to the private NVRAM section" by using OpenCore. And want to avoid it.

Anyway, I hope your understand that we are not speaking rubbish, and want to consume your time / effort without any solid ground.

For WEG, it will be good enough if you can add another boot argument to achieve renaming PXS# to GFX0.

e.g. 
rnmpxs=1 means rename PXS1 to GFX0
rnmpxs=3 mean rename PXS3 to GFX0

Once again, million thanks for spending time to address our request.

**Comment by vit9696** [comment]
The thing is, OpenCore writes nothing to NVRAM. It only creates temporary variables, which get removed after reboot (you can check the code if you do not believe me). Furthermore, it is up to your configuration whether to create even these. I am afraid it is your firmware itself or Clover.

As for a boot-arg, we will think of it, but it will be low pri.

**Comment by eweiman** [comment]
Thanks for considering this. 
Not sure if it needs to go as far as multiple boot arg options / behaviors if it can just do it by default for slot 1 which should be ACPI device PXS1 to GFX0 if that’s less work to implement safely.

**Comment by tsialex** [comment]
> Thanks for considering this.
> Not sure if it needs to go as far as multiple boot arg options / behaviors if it can just do it by default for slot 1 which should be ACPI device PXS1 to GFX0 if that’s less work to implement safely.

Lot's of MP5,1 owners have to use the GPU with the slot-2/PXS2. If it can be configured, will be really great.

**Comment by vit9696** [comment]
The feature was implemented in master. Passing `-wegtree` boot argument will cause WhateverGreen rename devices as it does normally on non-Apple firmware.
