### ISSUE TITLE
Slow IGPU frequency

### ISSUE THREAD

**Issue by yushuai** [acidanthera/bugtracker#554]
Hi, I use a 8th generation intel cpu. However, when I use WEG, the frequency of the IGPU was only around 500mHz.

**Comment by zijun-he** [comment]
<img width="507" alt="1" src="https://user-images.githubusercontent.com/52475027/68375978-beff4c80-0182-11ea-82a5-0a49a9d37e90.png">
<img width="1026" alt="2" src="https://user-images.githubusercontent.com/52475027/68375980-beff4c80-0182-11ea-91fd-bcef42919f50.png">
Although I am looking forward to the repair function, I can only wait.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/546#issuecomment-549052144

**Comment by tiger511** [comment]
I've built latest WEG 1.3.8 from source and added boot flag "igfxfw=2 " to load GuC.So far it loaded successfully and running without any hiccup so far.It turbo's all the way to 1GHz under load.My CPU is i7-8750h with Intel UHD 630 (Mobile).
