### ISSUE TITLE
WhateverGreen: 10.12.6 & ATI Radeon HD 4350 crash

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#555]
Panic (kernel?) and clover preboot logs are attached

[kernel.log](https://github.com/acidanthera/bugtracker/files/3820840/kernel.log)
[preboot.log](https://github.com/acidanthera/bugtracker/files/3820841/preboot.log)

**Comment by vit9696** [comment]
WEG does not support card before 6xxx. Could leave open as an enhancement.

**Comment by vit9696** [comment]
I have just checked and realised that macOS 10.12 is no longer supported. For this reason, unless somebody absolutely wants to drive this feature, I would rather close the issue.

**Comment by nms42** [comment]
Both the card and OS are old, but not vintage yet. (-;

Case closed!!!
