### ISSUE TITLE
Garbled Recovery image with RX 5700 XT

### ISSUE THREAD

**Issue by HQuest** [acidanthera/bugtracker#556]
During normal operations, an AMD RX 5700 XT card requires[1] use of "agdpmod=pikera" boot flag. Otherwise, display(s) is/are not detected and results on the "black screen". One can still VNC into the system to operate it, though.

The agdpmod boot flag is provided by WEG, and yet, during execution of macOS Recovery, the card seems not to be fully/properly initialized and causes either a garbled screen, or partial but incorrect displaying of image. Mouse cursor can still be moved and if cursor is increased by moving it fast enough, it will be displayed as expected. This, however, does not resolve the image and therefore renders the Recovery mode unusable. Disabling acceleration with -radvesa boot flag gives no improvement. It was confirmed the AMDRadeonX6000 kext files are available on the Recovery environment, however it could not be confirmed if they are loaded, since the VNC feature is not available during Recovery mode.

A workaround[2] is to use IGP and fall back to the on-board video device if system recovery is required.

As expected, the problem also appears during OS updates application: instead of the regular logo with the progress bar, a garbled screen is displayed instead.

This issue was first seen with Catalina 10.15.1 Beta3, which added support to this card. It occurs with any WEG versions as recent as of current "master" one.

Happy to provide supporting output and logs, however being on Recovery mode and without working graphics support, guidance is appreciated.

Tested with system set as iMac18,2, iMac18,3 and iMac19,2, with no apparent differences. Also tested with OC 0.52 and newer, and with recent versions of Clover.

[1] some users have reported no need for this flag
[2] assumes availability and rewiring

**Comment by errorexists** [comment]
i have a 5700 xt in my system using opencore an no weg is needed DP on the far right an HDMI in the only one there is an couldnt do not work with clover

**Comment by HQuest** [comment]
> i have a 5700 xt in my system using opencore an no weg is needed DP on the far right an HDMI in the only one there is an couldnt do not work with clover

I must use the WEG for any video out from this card, and I too must use an HDMI to get signal on the DP (any ports). With both OC and Clover, I am also using the IGP as headless (injecting AAPL,ig-platform-id, enable-hdmi20 and framebuffer-patch-enable fields); give that a try if you haven't yet.

Although it would definitely be great if DP would work on its own without a HDMI active connection, the ability to use Recovery sounds more important than the outputs, as one can just use an adapter or a different cable: most (if not all) monitors that do have DP do have HDMI.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/550#issuecomment-551238298
