### ISSUE TITLE
Vault not working at latest commit

### ISSUE THREAD

**Issue by E-werd** [acidanthera/bugtracker#558]
As of 2019/11/07 19:00 EST, latest commits of OpenCorePkg and OcSupportPkg are not allowing vault to work. I decided to test the new crypto code to see if it worked, if you're already aware then I apologize in advance for the ticket.

Steps to reproduce:
1) start with working config
2) modify config.plist, enable "RequireSignature" and "RequireVault"
3) run "./sign.command /Volumes/EFI/EFI/OC"
4) verify existence of vault.sig and vault.plist
5) reboot

Output at boot:

> OCS: Invalid vault signature
> OC: Failed to open root FS - Security Violation!

**Comment by vit9696** [comment]
Thanks for the report. No, this is not known, as in fact we tested vault right before the merge, and it functioned. Are you sure you use sign.command and others from latest master?

If so, could you please compile RsaTool with MacPorts/HomeBrew and recheck? Perhaps the binary is somehow broken. Do this:

- Download OcSupportPkg repo
- cd OcSupportPkg/Utilities/RsaTool
- make
- Move the resulting binary to CreateVault
- Compile OpenCore and replace OpenCore.efi
- patch the new OpenCore.efi with sign.command

**Comment by vit9696** [comment]
We tested vault ourselves and were unable to reproduce the issue. Vaulting works fine on our setup, including the RsaTool binary in master. Please recheck, it is quite likely you made a mistake somewhere.

**Comment by E-werd** [comment]
Sorry for the delay on this, life and such.

While attempting to follow your instructions I had trouble with getting RsaTool to compile.  After talking about this in Discord, this led to the following pull request by @al3xtjames: https://github.com/acidanthera/OcSupportPkg/pull/20 .  I can confirm that this pull request works with my HomeBrew setup.

I assume you're aware of this given your instructions, but another issue I found was that the RsaTool binary included in the /Utilities/CreateVault folder must be outdated, causing the initial issue.

Ultimately, this issue is resolved.  I have a working vault configuration.  I'll leave it to you to close in case you're looking for more testers.

**Comment by Download-Fritz** [comment]
@E-werd As @vit9696 said, the utility was tested as-is successfully. Are you absolutely sure you were on latest master when you ran it?

**Comment by E-werd** [comment]
Sorry guys, I'm unable to recreate the problem now.  

I confirmed tonight that RsaTool as packaged is working, as well as a fresh build.  It could possibly have been an older version of RsaTool, though it seems unlikely it's the only conclusion I can come to at this point.

I'll go ahead and close this as it seems to have just been a problem on my end and not a repo/build issue.
