### ISSUE TITLE
VoodooPS2controller issue when closing the lid for the first time

### ISSUE THREAD

**Issue by chiccheung** [acidanthera/bugtracker#560]
For the keyboard section:
voodooPS2controller 2.0.3
   - Only VoodooPS2Keyboard.kext is reserved
PS: I don't use the version 2.0.4 for the reason written in another issue. 
#514 

For the touchpad section:
VoodooI2C.kext
VoodooI2CHID.kext

When I close the lid for a while, the laptop will continue to emit a Funk sound. (I don't know how to express it, it is the default alert sound of the system, the name is Funk)
Open the lid and wake up the machine and you will notice that the brightness is adjusted to a minimum and the sound continues.
After entering the password, the sound disappears.
Then close the lid again and everything works fine.
In addition, my FN function keys have some problems, F5, F6, F7 can adjust the sound, but F3, F4 can not adjust the brightness.
Use LogScanCodes=1 to record, get e001=80, F3 & F4 are the same result.
FN+F3, FN+F4 are two valid values, I mapped them to F14, F15, so I can use FN+F3, FN+F4 to adjust the brightness, but F3/F4 has no result.

It is not clear whether there is any relationship between the inactivity of the FN key and the sleep problem.

I can provide my EFI files, ioreg file and original ACPI files.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/3823699/EFI.zip)
[ACPI.zip](https://github.com/acidanthera/bugtracker/files/3823701/ACPI.zip)
[MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/3823735/MacBook.Pro.ioreg.zip)

**Comment by chiccheung** [comment]
I have done this according to your request, sir.
@usr-sse2

**Comment by chiccheung** [comment]
I have solved the problem.
More details :
[OS-X-Voodoo-PS2-Controller/SSDT-HP-FixLidSleep.dsl](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/blob/master/SSDT-HP-FixLidSleep.dsl)
`// SSDT-HP-FixLidSleep.dsl
// Fix for LID sleep on certain HP computers.
// Make sure you verify _SB.PCI0.LPCB.PS2K ACPI path.
DefinitionBlock ("", "SSDT", 2, "hack", "ps2", 0)
{
    Name(_SB.PCI0.LPCB.PS2K.RMCF, Package()
    {
        "Keyboard", Package()
        {
            "Custom PS2 Map", Package()
            {
                Package(){},
                "e005=0", // nullify ps2 code 'e0 05' to prevent keygen at lid close
            },
        },
    })
}
//EOF`

**Comment by vit9696** [comment]
@chiccheung, well, the file is here too [VoodooPS2/Docs/ACPI/SSDT-HP-FixLidSleep.dsl](https://github.com/acidanthera/VoodooPS2/blob/master/Docs/ACPI/SSDT-HP-FixLidSleep.dsl), just we are pretty much unaware of all the legacy we got with VoodooPS2 sources. Nice to see you resolving the problem though.
