### ISSUE TITLE
WhateverGreen: READMEs & docs should state supported generations of hardware

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#562]
For example,
ATI Radeon HD 4350 is not supported at all. )-;

**Comment by vit9696** [comment]
Well, it is stated here: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Radeon.en.md. I am not positive we tested 5xxx series though. I definitely tried it on 6xxx, however.

**Comment by nms42** [comment]
Too deep.

**Comment by vit9696** [comment]
To be honest, I think it is not. After all 10.12 is no longer supported anyway, so the real minimum is 7xxx series.
