### ISSUE TITLE
BrcmPatchRAM v2.5.0 breaks 'Call from iPhone' feature

### ISSUE THREAD

**Issue by Hologos** [acidanthera/bugtracker#563]
Hi,

I found out that BrcmPatchRAM v2.5.0 breaks the Call from iPhone feature. I can't make a phone call from macOS nor receive one. I downgraded to v2.3.0d3 (from Mieze) and it's working fine.

It works both in /L/E and CLOVER/kexts.

I am using DW1560.

Do you need some debug info from me?

**Comment by vit9696** [comment]
CC @Mieze, @headkaze.

**Comment by ameenjuz** [comment]
how to compile manually BrcmPatchRAM source with xcode 11.4

**Comment by black-dragon74** [comment]
It is working as expected, without any issues. It must be some configuration issues on user end.

**Comment by Hologos** [comment]
How come it's a configuration issue when just replacing kext makes it work/not work. I got it verified with a different hackintosh with the same card. Are you using DW1560?

**Comment by black-dragon74** [comment]
DW1560 is essentially BRCM94352z and it uses BCM20702 for it's BT module, so to answer your question, yes. The same hardware works fine for me with the latest BrcmPatchRAM. What macOS version are you on?

**Comment by Hologos** [comment]
This bug was reported with v2.5.0, current latest release is v2.5.5.

**Comment by black-dragon74** [comment]
Why does a developer provide software updates again? To fix bugs and to add features, one might say and if I can see it clearly, the problem doesn't exist anymore, neither should this issue.

**Comment by Hologos** [comment]
What kind of a**hole are you? It was reported with v2.5.0 (as stated in the title). If it was fixed, I (and I guess everyone else) would expect you to write something like *I verified it's fixed in the latest release*. But stating it's a configuration mishap with you even trying to replace it with the same version and acting like this. Just roll man. Just roll.

**Comment by black-dragon74** [comment]
My comment was not meant for you dear. It was for the devs to close this issue. You are too shallow to understand with that attitude of yours. Save that profanity for someone else.

Regards

**Comment by Hologos** [comment]
You are reporting something that is not true. You are missleading the devs. If it's fixed, great. But it was not a configuration issue. More ppl on the forum had the exact same issue. You are just too hypocrit to admit that you wrote a garbage.

**Comment by black-dragon74** [comment]
Cool. Thanks.

**Comment by Mieze** [comment]
Hey boys, calm down please! In case you've got issues after an update, the first thing you should try is to clean system caches as it resolves link errors which might cause strange behavior.
