### ISSUE TITLE
OC Hotkeys not working properly

### ISSUE THREAD

**Issue by doesprintfwork** [acidanthera/bugtracker#564]
As the title say, it *does* work but not properly. I need to press the hotkey repeatedly for OpenCore to recognise it. If I hold down the hotkeys before OpenCore boots, they don't work.

For example, if I want to Show the boot menu by Opt, I need to press Opt repeatedly until the boot menu shows up. Simply holding it doesn't work at all.

I've already tried KeySupportMode V1, V2 and AMI on OpenCore 0.5.3

**Comment by doesprintfwork** [comment]
Which means OC unable to grab the key that are pressed before booting to it. BTW, my specs are:
- AMD Ryzen 5 1600
- MSI B350M Mortar

**Comment by vit9696** [comment]
Well, holding worked last time we tried on APTIO. You cold try UsbKbDxe. Nobody here has AMD, so I am afraid you will need to either ask @Download-Fritz or fix it yourself.

**Comment by doesprintfwork** [comment]
I have tried UsbKbDxe before but it still didn't work

**Comment by Download-Fritz** [comment]
UsbKbDxe cannot work "half", i.e. in the way you described, so this must be a misconfiguration or collision (e.g. OC Input vs AGI vs UsbKbDxe)

**Comment by doesprintfwork** [comment]
Not really. I have tried UsbKbDxe without OCInput, OCInput (Auto, V1, V2, AMI) without UsbKbDxe, and I tried AGI when OCInput wasn't a thing.
All not working properly unfortunately.

**Comment by cattyhouse** [comment]
Same here, B360M + IKBC C87 keyboard, the hotkey never worked properly for me, so i just disabled this feature, everything else worked great so far! 

someone said in a blog that using a dead cheap keyboard may work.

**Comment by E-werd** [comment]
I can also confirm this, using UEFI->Input->KeySupport I cannot use the hotkeys by holding but only buy repeated pressing.  This is also true for the motherboard's BIOS entry and boot menu, and it is true on an Apple keyboard as well as my HAVIT keyboard.

Motherboard: MSI Z370m Gaming Pro AC

**Comment by HQuest** [comment]
Add me in to the list. UsbKbDxe does no good, and KeySupport works much better, although I too have to keep hitting Option/Alt key to get to the boot menu. MSI Mortar Z-270M MoBo and Logitech G510 USB keyboard.

**Comment by vit9696** [comment]
We did some quick research on the matter, and believe it is a limitation of your host firmware. You can try tuning `KeyForgetThreshold`, `KeyMergeThreshold`, `TimerResolution` values (see Configuration.pdf). If that does not help, we are afraid there is no possible workaround for you to provide.
