### ISSUE TITLE
Dual monitors - Vega 64 - no signal on second monitor after boot

### ISSUE THREAD

**Issue by carbonimax** [acidanthera/bugtracker#566]
During Boot process and after login, my second monitor won't wake up until I put off and put on or unplug and replug the DP.

Tried with macOS 10.14.6, 10.15, 10.15.1, 10.15.2, clover and OC, with/without WEG, with/without agdpmod=pikera, -raddvi, -rad24...

all kexts are up to date.

[OC config file](https://dsc.cloud/2b7d02/config.plist)
[OC boot log](https://dsc.cloud/2b7d02/weg.txt)
[IOReg](https://dsc.cloud/2b7d02/iMac-Pro.ioreg)

macOS 10.15.2 Beta (19C32e)
GPU: Radeon RX Vega 64 ROG STRIX GAMING OC 8 Go | DSP: 2 x DELL P2415Q 4K in DP
SMB: iMacPro1,1 | BL: OC 0.5.3
MB: Gigabyte Z390 Aorus Master (F10b) | CPU: i9 9900K 3.6GHz | RAM: 32Go Ballistix Sport LT 2400Mhz

**Comment by vit9696** [comment]
Well, we have no plans to investigate this, as it is a feature request to improve the driver, not a bug in our code. I will leave this open for a short while, but you are best to find your own solution/contribute a workaround.

**Comment by carbonimax** [comment]
Do you have any idea where to start the investigations?

**Comment by vit9696** [comment]
I would say you are best to start off reversing AMDSupport kext and AMDXnnnnHardware kext, that's where AGDC/AGDP lives. WhateverGreen code might be of some help too.

**Comment by carbonimax** [comment]
It still doesn't work with Big Sur
