### ISSUE TITLE
Configuration.pdf now shows wrong count size for create vault commands

### ISSUE THREAD

**Issue by rusty-bits** [acidanthera/bugtracker#568]
the RsaTool now makes a vault.pub file that is 528 bytes long, but on page 30 of the Configuration.pdf it shows the dd command using a count of 520  

`dd of=OpenCore.efi if=vault.pub bs=1 seek=$off count=520 conv=notrunc`  

this will fail on boot  

changing command to ...

`dd of=OpenCore.efi if=vault.pub bs=1 seek=$off count=528 conv=notrunc`  

works as expected

**Comment by PMheart** [comment]
Mine here is still 520 bytes though:
`user: ~/Downloads/OpenCore-0.5.2-RELEASE/EFI/OC/Keys $ wc -c vault.pub 
     520 vault.pub`

Anyway, what about
`/usr/bin/wc path/to/vault.pub | /usr/bin/awk '{print $1}'`
