### ISSUE TITLE
Can't recognize All Mac partations after opening secure boot 

### ISSUE THREAD

**Issue by startpenghubingzhou** [acidanthera/bugtracker#569]
Hi，by following the configuration of OC I successfully runned my OC in Secure Boot mode. Thx for your appreciate work :) However，I found that my OC loader can't find any Mac partations in my laptop so that I can't boot macos in this mode.  But for other system like Ubuntu and Windows 10, can boot successfully. I don't know what happened. Is there any solution about that？

**Comment by williambj1** [comment]
Maybe the title would be OpenCore can't recognize macOS partitions when OpenCore vault is enabled and the device has imported generated Secure Boot Keys :p

**Comment by startpenghubingzhou** [comment]
> Maybe the title would be OpenCore can't recognize macOS partitions when OpenCore vault is enabled and the device has imported generated Secure Boot Keys :p

Thx for fixing, I wrote last night and haven't notice that^^

**Comment by vit9696** [comment]
OpenCore currently does not support secure boot, if that's what you meant to ask. See https://github.com/acidanthera/bugtracker/issues/368. Closing as duplicate.

**Comment by startpenghubingzhou** [comment]
> OpenCore currently does not support secure boot, if that's what you meant to ask. See #368. Closing as duplicate.

OK Gotcha. So any plan for completely support secure boot?

**Comment by vit9696** [comment]
Yes, we do, but you will obviously have to sign OpenCore with a custom certificate installed in your system.

**Comment by startpenghubingzhou** [comment]
> Yes, we do, but you will obviously have to sign OpenCore with a custom certificate installed in your system.

Gotcha. And thx for your appreciate work again! Hoping secure boot support will coming soon :)

**Comment by startpenghubingzhou** [comment]
> Yes, we do, but you will obviously have to sign OpenCore with a custom certificate installed in your system.

Oh btw, I want to try to write a new lilu plugin  for myself, is there any suggestion for me to do apart from read lilu api in hpp? thx very much !

**Comment by vit9696** [comment]
I am afraid that Lilu inline documentation in .hpp is the best available documentation to date. Other plugins hosted on acidanthera should be of help of course.

**Comment by startpenghubingzhou** [comment]
> I am afraid that Lilu inline documentation in .hpp is the best available documentation to date. Other plugins hosted on acidanthera should be of help of course.

OK thx very much  for your answer again ^^
