### ISSUE TITLE
SMCSuperIO fan speed reading

### ISSUE THREAD

**Issue by jl4c** [acidanthera/bugtracker#577]
Hello, I trying to enable fan speed reading in my laptop with VirtualSMC, but as you can see in log, SMCSuperIO failed to detect supported SuperIO chip. In FakeSMC times I was able to use the SSDT below to read fan speed.
Log show:
`kernel: (Lilu) SMCSuperIO:    ssio @ failed to detect supported SuperIO chip`

SSDT:
> 
    DefinitionBlock ("", "SSDT", 2, "HACK", "SMCD", 0x00000000)
    {
        External (_SB_.PCI0.LPCB.EC__.ECMX, MutexObj)
        External (_SB_.PCI0.LPCB.EC__.ECRG, IntObj)
        External (_SB_.PCI0.LPCB.EC__.FNR0, FieldUnitObj)
        External (_SB_.PCI0.LPCB.EC__.FNR1, FieldUnitObj)
        External (_TZ_.TZ00, DeviceObj)
        External (B1B2, MethodObj)    // 2 Arguments
        Scope (_TZ.TZ00)
        {
            Method (FRSP, 0, NotSerialized)
            {
                Acquire (\_SB.PCI0.LPCB.EC.ECMX, 0xFFFF)
                If (\_SB.PCI0.LPCB.EC.ECRG)
                {
                    Local1 = B1B2 (\_SB.PCI0.LPCB.EC.FNR0, \_SB.PCI0.LPCB.EC.FNR1)
                }
                Release (\_SB.PCI0.LPCB.EC.ECMX)
                Return (Local1)
            }
        }
        Device (SMCD)
        {
            Name (_HID, "MON0000")  // _HID: Hardware ID
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If (_OSI ("Darwin"))
                {
                    Return (0x0F)
                }
                Else
                {
                    Return (Zero)
                }
            }
            Method (FAN1, 0, Serialized)
            {
                Local1 = B1B2 (\_SB.PCI0.LPCB.EC.FNR0, \_SB.PCI0.LPCB.EC.FNR1)
                If ((0xFF == Local1))
                {
                    Local1 = Zero
                }
                Return (Local1)
            }
        }
    }
Any help will be appreciated.
Thank you.

**Comment by Andrey1970AppleLife** [comment]
In laptops no SuperIO chip. Only desktops.

**Comment by jl4c** [comment]
Thank you
So, is there any way to get the fan speed reading through VirtualSMC?

**Comment by oldman20** [comment]
> In laptops no SuperIO chip. SMCSuperIO.kext only for desktops.

God, you kidding?

**Comment by dreamwhite** [comment]
> > In laptops no SuperIO chip. SMCSuperIO.kext only for desktops.
> 
> 
> 
> God, you kidding?

He replied 3 years ago 🤌

**Comment by oldman20** [comment]
> > > In laptops no SuperIO chip. SMCSuperIO.kext only for desktops.
> > 
> > 
> > God, you kidding?
> 

> He replied 3 years ago 🤌

I have same issue this thread with SONY VAIO High Sierra now
![IMG_0800](https://user-images.githubusercontent.com/39668756/211035206-c20cccb8-7b88-44eb-bd97-b99dc4f33f81.jpg)

**Comment by dreamwhite** [comment]
That's not a support forum!
