### ISSUE TITLE
Backlight Patching Bug

### ISSUE THREAD

**Issue by 1Revenger1** [acidanthera/bugtracker#581]
Some laptops, like my Dell Precision M4700, have multiple options for GPU outputs. They can rely on the iGPU, or directly output to the internal display with a dGPU (AMD or Nvidia). While using the dGPU, backlight patches for laptops that use the Intel iGPU still do work, though can have different backlight ranges.

Using the latest build of WhateverGreen (through git clone/building in xcode) + SSDT_PNLF.aml from WEG, backlight control does work but the range is left a bit wanting - it's hard to use at night as 0 is too dark, and the next step up is too much is too bright to use at night. Under AppleIntelPanelA, it is shown that a default profile is being used for brightness:
![image](https://user-images.githubusercontent.com/13190749/69095167-a276d600-0a06-11ea-8a69-86ed1074b093.png)

If I want to use the ranges that WEG provides, all I needed to do was comment out line ~240 which disables the backlight patches if it detects we are not using the iGPU
![image](https://user-images.githubusercontent.com/13190749/69095341-f5508d80-0a06-11ea-8788-9184d2d514aa.png)

Now it uses the ranges that WEG provides, but if you look at the first screenshot, the max value of 0x0710 provided by WEG is *way* above the max value of 0x0FF of before. What happens is that as you increase the brightness, the brightness will go up and roll over, making the display go dark again, before it continues increasing in brightness again. Limiting the range as shown below fixes this.
![image](https://user-images.githubusercontent.com/13190749/69100649-7a8d6f80-0a12-11ea-9e80-2a4878f9c852.png)

The two edits above give the full range of brightness, including at the low end, making the display usable at night. I don't know of anyway to get around the check to disable backlight patching - but maybe a way to force it to be enabled would be appreciated, either through a device property and/or boot arg. All I would question is whether the check is needed in the first place as the kext shouldn't load unless it's relevant for the needed system. Another feature that would be nice too is to set a custom backlight range for laptops like mine, rather than it being hardcoded within in WEG itself.

Specs for my specific laptop:
Dell Precision M4700
I7 3740QM
4x4GB DDR3 1600MHz
AMD Firepro mobility M4000

Edit: Just realized this is really more like two issues - If you all would like this split, I don't mind splitting it

**Comment by vit9696** [comment]
The check is needed, as many discrete GPUs do not like this. I will add a force option.

Custom properties make good sense to me, I will also add an option to customise this.

Thanks for the report.

**Comment by vit9696** [comment]
Resolved. Please reopen in case there are issues.
