### ISSUE TITLE
IQSV/Catalina: Music App Crash

### ISSUE THREAD

**Issue by hameerabbasi** [acidanthera/bugtracker#582]
Hello. I'm running a hybrid-GPU setup with Radeon VII and UHD 630 (i7-8700K). IQSV DRM protected videos work well in `TV.app`, but when it comes to music videos in `Music.app` I face an instant crash when playing a music video. Probably related to #519.

Using the Radeon GPU only and disabling the iGPU causes both apps to work fine. All other videos work fine.

If you need any sort of debug info, please let me know what you need.

**Comment by vit9696** [comment]
You are right that some videos require hardware decoding, and IGPU hardware decoder does not work with DRM without Apple firmware. Your only option is to use AMD.

- We will consider adding a hybrid option (AMD only for TV.app) in some future.
- We will also add Music.app to the list, but most likely it will cause only blackscreen, not fully working videos. I will update this issue soon.

**Comment by hameerabbasi** [comment]
I've added it to the list in acidanthera/WhateverGreen#37. I have yet to test.

**Comment by hameerabbasi** [comment]
The patch in the above comment fixes this, at least for my system.

**Comment by cattyhouse** [comment]
@hameerabbasi sorry for interrupt, are you also able to play `TV Shows` (the 3rd tab of the app) from `/Application/Videos.app`, as for me `UHD630 + RX 470`, i have to use `shikigva=32 shiki-id=Mac-7BA5B2D9E42DDD94` to fool AppleGVA to play film in there.

**Comment by hameerabbasi** [comment]
I can play "The Morning Show" (the series, not the trailer) just fine.

**Comment by Andrey1970AppleLife** [comment]
If you don't need TV+, don't use these boot-arguments because it deactivates the decoder IGPU.
