### ISSUE TITLE
Gui freeze/panic Windowserver failed to checkin with Radeon VII/Whatevergreen

### ISSUE THREAD

**Issue by mruepp** [acidanthera/bugtracker#584]
Irregular and not reproducable Gui freezes following a restart through watchdog after 140s. 
AMD Radeon VII
SM X9Dai + SB E5-2670
Whatevergreen 1.3.4
Lilu 1.3.9
Catalina 10.15.1

I added .txt to some of the files to enable github upload but kept the original extension

I attached the log output of Lilu/WG as well as Spin reports and Crash reports
[dbglogoutput.log](https://github.com/acidanthera/bugtracker/files/3879746/dbglogoutput.log)

[WindowServer_2019-11-22-135316_sunshine.userspace_watchdog_timeout.spin.txt](https://github.com/acidanthera/bugtracker/files/3879752/WindowServer_2019-11-22-135316_sunshine.userspace_watchdog_timeout.spin.txt)
[Kernel_2019-11-22-135345_sunshine.gpuRestart.txt](https://github.com/acidanthera/bugtracker/files/3879756/Kernel_2019-11-22-135345_sunshine.gpuRestart.txt)
[WindowServer_2019-11-22-135403_sunshine.userspace_watchdog_timeout.spin.txt](https://github.com/acidanthera/bugtracker/files/3879759/WindowServer_2019-11-22-135403_sunshine.userspace_watchdog_timeout.spin.txt)
[Kernel_2019-11-22-140708_sunshine.panic.txt](https://github.com/acidanthera/bugtracker/files/3879761/Kernel_2019-11-22-140708_sunshine.panic.txt)

[ioreg.iojones.txt](https://github.com/acidanthera/bugtracker/files/3879769/ioreg.iojones.txt)

**Comment by vit9696** [comment]
Hi, not much we can do here, as it is basically a bug in the drivers, which we do not handle. Please report that to Apple.
