### ISSUE TITLE
OpenCoreShell Does Not Build

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#591]
**1. OpenCoreShell Does Not Build**
````
error: patch failed: MdeModulePkg/Library/UefiHiiServicesLib/UefiHiiServicesLib.c:85
error: MdeModulePkg/Library/UefiHiiServicesLib/UefiHiiServicesLib.c: patch does not apply
error: patch failed: MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:4869
error: MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c: patch does not apply
````
**2. Extra Suggestions**

Also, can you slightly modify the `./macbuild.tool`  so that i can reuse OpenCorePkg/UDK to avoid cloning UDK into OpenCoreShell again? So that OpenCorePkg, AppleSupportPkg OpenCoreShell and many others can share the same piece of UDK

Because these steps:
````
pushd OpenCoreShell > /dev/null
ln -sf ../OpenCorePkg/UDK . # OpenCorePkg and UDK was already cloned.
pushd UDK > /dev/null
ln -sf ../../OpenCoreShell .
popd > /dev/null
./macbuild.tool
````
will result in:

````
error: can't open patch '../Patches/*': No such file or directory
````

the error is because after cd UDK, `for i in ../Patches/* ` is actually `for i in OpenCorePkg/Patches/*`  (UDK is a symbol link)

this confirmed to eliminate the error, though looks ugly :) :

````
for i in ${$(pwd)%/*}/Patches/*
````

**Comment by vit9696** [comment]
Hi, we are in progress of updating it. Use the one built from releases for the time being.

**Comment by vit9696** [comment]
Fixed in master.
