### ISSUE TITLE
KernelPatcher should support simple binary patches for kernel, similar to applyLookupPatch

### ISSUE THREAD

**Issue by lvs1974** [acidanthera/bugtracker#592]
Currently Lilu does not provide a nice way to patch macOS kernel, KernelPatcher::applyLookupPatch supports only kexts.

Proposal: modify method KernelPatcher::applyLookupPatch and check pointer to LookupPatch::kext, if it is nullptr this binary patch can be applied to kernel.

**Comment by vit9696** [comment]
Sounds good, implemented.

**Comment by lvs1974** [comment]
`Lilu:    mach @ (DBG) found symbol _log_setsize at 0xffffff80122ed9c0 (non-aslr 0xffffff80008ed9c0)
set system log size to 1048576 bytes
Lilu:    mach @ (DBG) getRunningPosition 0xffffff8011c00000 of memory 8192 size
Lilu: patcher @ lookup patching applied only 0 patches out of 1
DebugEnhancer:  DBGENH @ applyLookupPatch failed with error 7`

getRunningPosition returns a wrong size of kernel: 8192,
sequence of bytes cannot be found.

**Comment by vit9696** [comment]
It does not know kernel size, so most likely we should either pass the value or set UINT32_MAX to kernel memory size in applyLookupPatch. Probably the latter.
