### ISSUE TITLE
Some problems with OpenCore use FV2

### ISSUE THREAD

**Issue by gujiangjiang** [acidanthera/bugtracker#593]
1.SMBIOS > ROM cant read and write rightly.
When i set a ROM but when i into the macOS it only show 000000010000 and i tried many times but cant solve this problem.
`ROM: 000000010000`

2.OpenCore
How to disable this txt log when boot into OpenCore.
![IMG_9877](https://user-images.githubusercontent.com/13273955/69984648-8af62c00-1574-11ea-9304-a621edbde90d.jpg)

 3.FV2
I have used FV2 just now and works perfectly but on boot screen it shows an error code:
![IMG_9876](https://user-images.githubusercontent.com/13273955/69984718-b11bcc00-1574-11ea-9292-2617fc7e4a31.jpg)
How to fix this error?

Best wishes.
Thanks.

**Comment by vandroiy2013** [comment]
Hi
 
Suggest you to find answers on support forums.

**Comment by gujiangjiang** [comment]
@vandroiy2013 hello
I searched on google and forums but can’t find useful answer with this 3 problems so I post here for help.
Thanks
