### ISSUE TITLE
shikigva=16 doesn't work on IvyBridge IGPU + AMD GPU

### ISSUE THREAD

**Issue by Andrej-Antipov** [acidanthera/bugtracker#596]
In the TV application with Ivy Bridge GPU + AMD GPU (RX and other), and boot-arg shikigva = 16, it makes a red screen with sound and subtitles when playing the content of the Apple TV+ service.
In watevergreen 1.3.4 it is possible to fix this switching decoding to AMD GPU by that patches below, but in WhateverGreen 1.3.5 it doesn't working and we have red screen again:

```
<dict>
			<key>Patches</key>
			<array>
				<dict>
					<key>CPU</key>
					<string>CPU_TYPE_X86_64</string>
					<key>Comment</key>
					<string>mov rax,1 : cpuid -&gt;  mov rax,906EAh : nop : nop (i3 8100B)</string>
					<key>Count</key>
					<integer>5</integer>
					<key>Find</key>
					<data>
					x8ABAAAAD6I=
					</data>
					<key>Replace</key>
					<data>
					x8DqBgkAkJA=
					</data>
					<key>Section</key>
					<string>BOARDID</string>
					<key>Skip</key>
					<integer>0</integer>
				</dict>
			</array>
			<key>Path</key>
			<string>/System/Library/PrivateFrameworks/CoreLSKD.framework/Versions/A/CoreLSKD</string>
		</dict>
		<dict>
			<key>Patches</key>
			<array>
				<dict>
					<key>CPU</key>
					<string>CPU_TYPE_X86_64</string>
					<key>Comment</key>
					<string>mov rax,1 : cpuid -&gt;  mov rax,906EAh : nop : nop (i3 8100B)</string>
					<key>Count</key>
					<integer>2</integer>
					<key>Find</key>
					<data>
					x8ABAAAAD6I=
					</data>
					<key>Replace</key>
					<data>
					x8DqBgkAkJA=
					</data>
					<key>Section</key>
					<string>BOARDID</string>
					<key>Skip</key>
					<integer>0</integer>
				</dict>
			</array>
			<key>Path</key>
			<string>/System/Library/PrivateFrameworks/CoreLSKDMSE.framework/Versions/A/CoreLSKDMSE</string>
		</dict>
		<dict>
```
And third patch is replacing board-id with self Mac model right that
```
<dict>
					<key>CPU</key>
					<string>CPU_TYPE_X86_64</string>
					<key>Comment</key>
					<string>Mac-7BA5B2D9E42DDD94 -&gt; Mac-FC02E91DDD3FA6A4</string>
					<key>Count</key>
					<integer>1</integer>
					<key>Find</key>
					<data>
					TWFjLTdCQTVCMkQ5RTQyREREOTQ=
					</data>
					<key>Replace</key>
					<data>
					TWFjLTAwQkU2RUQ3MUUzNUVCODY=
					</data>
					<key>Section</key>
					<string>BOARDID</string>
					<key>Segment</key>
					<string>TextCstring</string>
					<key>Skip</key>
					<integer>0</integer>
				</dict>
			</array>
			<key>Path</key>
			<string>/System/Library/PrivateFrameworks/AppleGVA.framework/Versions/A/AppleGVA</string>
```
Discussion here (in Russian) https://applelife.ru/threads/proigryvanie-zaschischjonnogo-kontenta-na-raznom-oborudovanii.1349123/page-63#post-846007
Is it possible to make IvyBridge GPU + AMD GPU working like others with  shikigva=16?

**Comment by vit9696** [comment]
- Red screen is shown when AMD decoder cannot decode video stream, normally 1st or 2nd FairPlay generation.
- Patches above enable software decoding for streaming services, they do not enable hardware decoding.

From what I understand your AMD GPU does not support hardware decoding in TV+, so you can only use software decoding, and that's what the patches do. They force software decoding in TV.app.

It makes sense to enable CoreLSKD and CoreLSKDMSE patches by default, if we assume they are needed, I changed that in master.

But Mac-7BA5B2D9E42DDD94 → Mac-FC02E91DDD3FA6A4 makes little sense to be honest. Could you check whether shikigva=16 or shikigva=144 work with current master? If not, could you please add that patch right after "board-id -> hwdrm-id (normally for iMacPro1,1)" and retry?

**Comment by david279** [comment]
Just built with the latest patches and tested on my Hack VM Catalina and i finally get video in the Apple TV app with the shikigva=16. I spoof my Vm as a Ivy Bridge as Penryn and Ivy bridge are the best for compatibility. All before i would get a red screen when playing video. I use iMacPro 1,1 BTW for my smbios.

**Comment by vit9696** [comment]
Fixed in master.
