### ISSUE TITLE
Couldn't allocate runtime area OC 0.5.2

### ISSUE THREAD

**Issue by yooouuri** [acidanthera/bugtracker#597]
GigaByte Z390 UD Bios version F9, using latest Lilu, VirtualSMC, FwRuntime etc.

Im getting "Couldn't allocate runtime area" error over and over. Tried to calculate slide, no success...

[config.plist.txt](https://github.com/acidanthera/bugtracker/files/3917720/config.plist.txt)

[opencore-2119-12-03-163004.txt](https://github.com/acidanthera/bugtracker/files/3917700/opencore-2119-12-03-163004.txt)

Please report back if you need more logs or something.

**Comment by Andrey1970AppleLife** [comment]
For latest FwRuntimeServices use latest OC 5.2.3
