### ISSUE TITLE
OpenCore-0.5.3 X299 panic

### ISSUE THREAD

**Issue by nmano0006** [acidanthera/bugtracker#598]
Hi  Acidanthera
My Board-X299 WU8
CPU-i9 9980XE

I test with OpenCore-0.5.3-DEBUG

I can’t boot My System.CPU is panic but 0.5.2 OpenCore worked.
Thank you.

**Comment by Andrey1970AppleLife** [comment]
Update https://github.com/acidanthera/AppleSupportPkg/releases

**Comment by nmano0006** [comment]
Thank you Acidanthera
I update 0.5.4 Its work now.
