### ISSUE TITLE
Opencore 0.5.2 ans 0.5.3 not shutting down macOS (boot up right after shut down)

### ISSUE THREAD

**Issue by hachirotahoshino** [acidanthera/bugtracker#599]
Hi, if I come here it is because I already try debugging on AMD-OSX #opencore Discord and I was recommended to come make a bug report here. I waited until a new release was out to be sure it was not a "not up to date" issue.

I also still have a running up to date Clover Bootloader alongside so I can compare, I don't have the no shut down issue under latest Clover boot loader and patches

When I use OpenCore with Catalina and Mojave (tested both) my computer shuts down but right when all is shut down, it start up again.

When I shut down from windows it just shut down properly.

we try to debug with the "fix shutdown" guide

https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/blob/master/clover-conversion/Clover-config.md

no success

we tried the nvram test to see if nvram retained parameters and it is working good on this side.

we tried the rtc patch https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/troubleshooting/troubleshooting#bios-reset-or-sent-into-safemode-after-reboot-shutdown

no success

we checked DSDT for usb issues. 

we checked the patches, the refi drivers and kext were up to date...

no success... 

I was told to come here submit a bug here I am.

Here is my setup:

kojiaiba's ANEMONE:

|          [CPU][AMD Ryzen 7 3700X 3.6 GHz 8-Core Processor]
|   [CPU Cooler][Asetek 645lt AIO]
|  [Motherboard][Gigabyte X570 I AORUS PRO WIFI Mini ITX AM4 Motherboard]
|       [Memory][G.Skill Ripjaws V 32 GB (2 x 16 GB) DDR4-3600 Memory]
|      [Storage][Samsung 960 EVO 500 GB M.2-2280 NVME Solid State Drive]
|      [Storage][Samsung 960 EVO 500 GB M.2-2280 NVME Solid State Drive]
|      [Storage][Seagate FireCuda 2 TB 2.5" 5400RPM Hybrid Internal Hard Drive]
|      [Storage][Crucial BX500 960 GB 2.5" Solid State Drive]
|   [Video Card][Sapphire Radeon RX VEGA 64 8 GB Video Card]
|         [Case][KOLINK ROCKET Mini ITX Desktop Case]
| [Power Supply][Corsair SF 600 W 80+ Gold Certified Fully Modular SFX Power Supply]
|      [Monitor][Acer CB281HK 28.0" 3840x2160 60 Hz Monitor]
|     [Keyboard][Logitech CRAFT Wireless Standard Keyboard]
|        [Mouse][Logitech MX MASTER 2S (Black) Wireless Laser Mouse]
|     [Speakers][Trust Asto Soundbar 24 W 2.0 Channel Speakers]
|       [Custom][Logitech c925e]
|       [Custom][DW1560 M.2 wireless card]

Here is my EFI:

[EFI.zip](https://github.com/acidanthera/bugtracker/files/3923771/EFI.zip)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
