### ISSUE TITLE
Trackpad doesn't work on VoodooPS2 2.1.0, but trackpoint does

### ISSUE THREAD

**Issue by notthebee** [acidanthera/bugtracker#600]
On the newest release version of VoodooPS2Controller the trackpoint on my Thinkpad X1C6 works, but the touchpad is completely unresponsive. Similar experience is reported [here](https://github.com/acidanthera/bugtracker/issues/418#issuecomment-560786397) by other users. The version [here](https://github.com/acidanthera/bugtracker/issues/418#issuecomment-547674864) which is a fork of VoodooPS2Controller by @Jpe230 with fixes for Clickpad works fine. 

Another minor point is that PrintScreen button disables both trackpoint and trackpad, unlike the RehabMan's version, with which only trackpad is disabled by pressing PrintScreen. Is there any way to make it only disable the trackpad?

OS version: macOS Mojave 10.14.6
Kext version: VoodooPS2Controller 2.1.0 + VoodooInput 1.0.1

**Comment by Jpe230** [comment]
Weird, I'm testing the latest releases VoodooPS2Controller 2.1.0 + VoodooInput 1.0.1, all good including the changes specific to our thinkpads albeit the 4 fingers gestures are a bit finicky. 

Did you rebuild your Kernel cache?

**Comment by benbender** [comment]
Working as expected on a Thinkpad T480, Mojave 10.4.6 \w OC 0.5.3, Lilu 1.4, VoodooPS2 2.1.0 and VoodooInput 1.0.1.

**Comment by joshuaseltzer** [comment]
Same issue here as @notthebee.  The kext that was compiled directly from @Jpe230's fork (here: https://github.com/acidanthera/bugtracker/files/3786222/VoodooPS2Controller.kext.zip) is working.  I have a T440s.

**Comment by Sniki** [comment]
> Same issue here as @notthebee. The kext that was compiled directly from @Jpe230's fork (here: https://github.com/acidanthera/bugtracker/files/3786222/VoodooPS2Controller.kext.zip) is working. I have a T440s.
> 
> **EDIT: Nevermind - scratch everything I just said! I didn't realize that VoodooInput saw a 1.0.1 release with support for machines < Catalina (I'm on 10.14.6 Mojave still). Once I used that version along with VoodooPS2Controller 2.1.0, everything is working as intended!**

I did try that yesterday but it's not working well for me.
Somehow my cursor works only with 2 fingers.
It may be because i use the standard touchpad instead of the upgraded one but still, it was working perfect until this release.

Will do some more testing tonight.

**Comment by notthebee** [comment]
So I've tried the following:

- Rebuilding my kext cache
- Updating to the newest version of Lilu
- Installing VoodooInput 1.0.1
- Removing the Thinkpad-Clickpad.aml SSDT

Unfortunately, my trackpad still doesn't work whereas the trackpoint works just fine. Moreover, trackpad click works if I click it while I'm moving the trackpoint, which is weird. The kext seems to be attaching itself just fine to the MOU and the trackpad menu in System Preferences indicates gesture support.
![Screenshot 2019-12-06 at 09 39 03](https://user-images.githubusercontent.com/30384331/70308979-c1e66f00-180c-11ea-991c-63e76ab3a421.png)

**Comment by AutinMitra** [comment]
Can confirm that trackpad doesn't work in 2.10 on my 6th Gen X1C6. Interestingly enough, it seems that the trackpad needs an extra finger for everything. Needs two fingers for moving, three for scrolling, and four for gesturing (one more than usual). This is probably some issue with finger numbering or gestures? Or maybe something on the side of VoodooInput?

**Comment by Sniki** [comment]
> Can confirm that trackpad doesn't work in 2.10 on my 6th Gen X1C6. Interestingly enough, it seems that the trackpad needs an extra finger for everything. Needs two fingers for moving, three for scrolling, and four for gesturing (one more than usual). This is probably some issue with finger numbering or gestures? Or maybe something on the side of VoodooInput?

Exact same behavior on my Lenovo ThinkPad X240

**Comment by benbender** [comment]
I've had the bug with the extra needed finger on the touchpad twice in the last days. It was fixed for me by a simple reboot. Normally it works and feels nearly perfect. 
Maybe a race condition on initializing?

**Comment by ii-nferno** [comment]
I tried VoodooPS2Controller 2.1.0 and VoodooInput 1.0.1 on my x270 a few days ago and the trackpad no longer worked. Only the Trackpoint was working. Reverted to Jpe320's kext where everything works.

**Comment by vit9696** [comment]
Assumed to be resolved in master.

**Comment by notthebee** [comment]
Just checked and the issue is indeed solved by adding the lines from the merge request to Info.plist. Thank you, @Sniki
