### ISSUE TITLE
Kernel Panic after update to 0.5.3

### ISSUE THREAD

**Issue by SgtBauerFR** [acidanthera/bugtracker#601]
Hello, I try to update my OpenCore 0.5.2 to 0.5.3 but I get a Kernel Panic.
My config.plist work great on 0.5.2. Whats wrong with my plist in 0.5.3?

My drivers are up to date 
My processor is a intel Haswell 4770K

Can you help me ?
![Screenshot 2019-12-05 at 15 50 04](https://user-images.githubusercontent.com/25414651/70245785-f4de2380-1776-11ea-97ce-afff63ad935c.png)

[config copy.plist.txt](https://github.com/acidanthera/OpenCorePkg/files/3927476/config.copy.plist.txt)

![IMG_0026](https://user-images.githubusercontent.com/25414651/70246338-e5130f00-1777-11ea-9df8-627d27920ece.jpeg)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by SgtBauerFR** [comment]
In OC 0.5.2 everything works ! It's with the OpenCore.efi 0.5.3 there is a bug
