### ISSUE TITLE
OcSupportPkg\Library\OcAppleImg4Lib\libDERImg4\DER_Img4Manifest.c(1146) : warning C4702: unreachable code

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#603]
OcSupportPkg\Library\OcAppleImg4Lib\libDERImg4\DER_Img4Manifest.c(1146) : warning C4702: unreachable code

Discovered by msvc 2019ce v16.4.0

**Comment by vit9696** [comment]
@Download-Fritz this issue might actually be a problem, as for some reason we have ReturnSuccess in all default cases, but the dead return was security error. I am not positive what it actually should be: https://github.com/acidanthera/OcSupportPkg/blob/410d10d3fc66a7e32c7b84cd794cb237f21ba873/Library/OcAppleImg4Lib/libDERImg4/DER_Img4Manifest.c#L1146.

**Comment by Download-Fritz** [comment]
The success returns comply with the Apple code, the Security error was added carelessly when factoring out that code from a bigger function if I remember correctly.

**Comment by vit9696** [comment]
Fine, then we can just remove that last return.
