### ISSUE TITLE
WhateverGreen Feature Request

### ISSUE THREAD

**Issue by Pavo-IM** [acidanthera/bugtracker#605]
Is there anyway we can use WhateverGreen for only auto connector patching? I do not want to use any of the other patches it implements. The reason for this request is because with my Radeon VII and using latest release of WEG causes red screen on DRM content when using iMacPro1,1 SMBIOS. Was working perfectly fine on earlier release versions. I would love to have a bootarg added that only applied the auto connector patch and nothing else.

**Comment by vit9696** [comment]
You see red screen because of invalid configuration and basically because WEG did not do patches rather than vice versa. To proof this you can disable userspace patches by -shikioff. Please come back when you understand your actual problem.

**Comment by Pavo-IM** [comment]
I understand the problem. DRM contents works perfectly fine without WEG, but I only have 2 ports on the GPU that works. 1x DP port and 1x HDMI port, I only wanted to use WEG for auto connector patching and nothing else. Guess I'll just stick without WEG.

**Comment by Pavo-IM** [comment]
Using -shikioff worked, thanks. Mind putting that bootarg on the README.

**Comment by vit9696** [comment]
If `-shikoff` worked, there is either a bug, or you are using a configuration supported neither by Apple, nor by us. I suggest you to check our [new chart](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md) for validating your configuration.

**Comment by Pavo-IM** [comment]
I have always been able to use DRM content in iTunes and now AppleTV, also have always been able to watch Netflix, Amazon Prime in Safari with all my builds without WEG. I only use SMBIOS that do not have iGPU ie.... MacPro6,1, MacPro7,1, iMacPro1,1 etc... because none of my builds have iGPUs. As I stated at the beginning when using the latest release of WEG with no bootargs, watching those services would produce a red screen. When using earlier versions of WEG without any bootargs. I was still able to watch those services without issues. But using `-shikioff` with the latest release of WEG I am now able to watch those services again without issues and also able to have all ports on my Radeon VII working. Now that I know I can use WEG without using the user space patches, which all I wanted in the first place, I am good to go. I just recommend adding that bootarg to the README so when users want to know how to disable the userspace patches in WEG they will know how to now. Thanks.

**Comment by vit9696** [comment]
Well, this sounds like a bug to me, you should be able to watch all these with WEG from master without adding any boot arguments as stated in the chart. Could you please recheck with Lilu and WEG from master and report? If it is not ok, please recheck with shikigva=128, this is roughly equivalent to -shikioff. Also, I would need more info about your configuration.

**Comment by Pavo-IM** [comment]
Using Lilu 1.4.0 and WhateverGreen 1.3.5 from **release** without bootargs produces red screen on both system builds.

Using Lilu 1.4.0 and WhateverGreen 1.3.5 from **release** with `-shikioff` bootargs works on both system builds.

Using Lilu 1.4.1 and WhateverGreen 1.3.6 from **master** works without any bootargs on both system builds.

**Intel Hack:**
Asus Z9PE-D8 WS
2x Xeon E5 2670v2 10 core CPUs
128Gb 1600Mhz DDR3
ASUS ROG STRIX Radeon RX Vega64
SMBIOS: MacPro6,1

**AMD Hack:**
MSI MPG x570 Gaming Edge Wifi
Ryzen 7 3700x
64Gb 3200Mhz DDR4
Sapphire Radeon VII
SMBIOS: iMacPro1,1

**Comment by vit9696** [comment]
Right, so just a bug in the previous release. This happens, good it is resolved now.
