### ISSUE TITLE
MaciASL won't show any editor windows at all

### ISSUE THREAD

**Issue by 49616e** [acidanthera/bugtracker#611]
I'm running MaciASL on 10.14.6. Lately I am unable to get any editor window to show up at all, but everything else seem to work just fine (i.e. Preferences, About, Log, etc.). Double-clicking or using the Open menu to open any valid .dsl or .aml files doesn't do anything at all for me. This is what was shown in the Log window when I open an .aml file (I can't copy text from this window):
![204](https://user-images.githubusercontent.com/39971507/70645179-6cccb200-1c7f-11ea-8411-361ff918b35c.png)

The following error is printed if I run the MaciASL binary in a terminal:
`MaciASL[24040:336746] *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]`

The .app bundle is a fresh download from github. I also tried the older release on SF but that one has the same issue as well. 

Since the exact same .app bundle works perfectly fine on a freshly installed copy of macOS 10.14.6, I'm sure there is something wrong with this particular installation, but I really can't figure out what exactly went wrong. I've checked both Library folders but I was unable to find any caches/configs related to MaciASL.

**Comment by Moorre** [comment]
> I'm running MaciASL on 10.14.6. Lately I am unable to get any editor window to show up at all, but everything else seem to work just fine

Try to delete all MaciASL's config and cache files. AppDelete will help you to find them.

**Comment by lioliy** [comment]
Me too.
But I solved use app cleaner delete everything and have a reboot

**Comment by 49616e** [comment]
All I could find was `~/Library/Caches/net.sourceforge.MaciASL`, and deleting it doesn't help.

**Comment by Moorre** [comment]
it is not all. see
![Снимок экрана 2019-12-16 в 21 47 56](https://user-images.githubusercontent.com/12731364/70938130-4081ae80-204e-11ea-9d2c-e8f5a56aff84.png)

**Comment by 49616e** [comment]
> it is not all. see
> ![Снимок экрана 2019-12-16 в 21 47 56](https://user-images.githubusercontent.com/12731364/70938130-4081ae80-204e-11ea-9d2c-e8f5a56aff84.png)

Thank you. Deleting the 4 aforementioned folder/files resolved the issue immediately. 

```
~/Library/Preferences/net.sourceforge.MaciASL.plist
~/Library/Caches/net.sourceforge.MaciASL
/private/var/folders/**/*****************************/C/net.sourceforge.MaciASL
~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.sourceforge.maciasl.sfl2
```

**Comment by 49616e** [comment]
I'll close this issue for now since I can't reproduce it by putting back the old files anymore.

**Comment by hrvstr** [comment]
I am experiencing the same issue. I can open the preference and log window but no editor window will open.

- macOS 14.1.2 (23B92)
- MaciASL 1.6.4 (1.6.4)

I tried trashing all settings with AppCleaner but the issue still persists. I also manually searched for all the files above and made sure they are removed. Any idea how I can fix this?
