### ISSUE TITLE
Kernel Panics with Docking Station Video Outputs if Sleep, Restart or Shutdown initiated

### ISSUE THREAD

**Issue by Sniki** [acidanthera/bugtracker#619]
I do have a docking station for the Lenovo ThinkPad X240.
The laptop itself without the dock does have a MiniDisplayPort and a VGA Port.
MiniDisplayPort & MiniDisplay Port audio works perfect ; VGA Port works perfect.

Laptop without Dock:
Framebuffer@0 - Laptop Display
Framebuffer@1 - Mini DisplayPort
Framebuffer@2 - VGA Port

When i attach the laptop into the dock, the dock does have 3 additional video ports:
DisplayPort, DVI, VGA.

Both those 3 dock ports do use the Framebuffer@2 and video output: plug/unplug is ok but DisplayPort does have no audio and video output works fine on 3 of ports unless i press Sleep, Shutdown or Restart, it will immediately go into instant reboot/Kernel Panic.

On Windows or Linux no such issues.

Will provide logs according to requests.

Attached EFI
[EFI.zip](https://github.com/acidanthera/bugtracker/files/3999203/EFI.zip)

**Comment by Sniki** [comment]
I found no solution to my answer into the documentation whatsoever, tried all documented connector types: kernel panics still happening, don't know why this does get closed with off-topic tag and nonetheless without an answer.

Anyways...

**Comment by vit9696** [comment]
It is simple. Your report has nothing to do to our projects, what you describe looks like a bug in Apple drivers, so at most it should be discussed on the forums or reported at https://feedbackassistant.apple.com/welcome.

**Comment by Sniki** [comment]
Just wanted to know the reason, that's all, that way i know what is going on.
This is not something we can report to Apple we all do know that, 
it's an issue since my first various guides for ThinkPads on Sierra where i remember people complained about this, could've been much earlier macOS versions too, that wasn't a priority for me as i didn't have a docking station at that time till now to test or work on that.

Also is there a similarity in graphics drivers on Linux ?, is it possible to do some debugging/logging and have a possible clue what happens so maybe i can get a clue and possibly find a workaround.
Just want to know if it is worth giving a shot on that or it is way more complicated and different driver system than Linux.

As for discussion in Forums, is this the correct forum: https://www.insanelymac.com/forum/topic/325987-whatevergreen-support-topic/
as finding them by browsing the forum is a PITA as it wasn't listed on WEG readme.md

Thanks and sorry.
