### ISSUE TITLE
OpenCore can't load default boot device from nvram setting in config.plist,only read from NVRAM 

### ISSUE THREAD

**Issue by laozhiang** [acidanthera/bugtracker#620]
I installed two Mac OS in my computer。And use grub as boot menu. I want OpenCore only boot Special macOS、Clover boot another. 
At first, I can set OpenCore default boot disk use  "System Preferences. -> Startup Disk". 
 I want set default boot disk in config.plist, no use the NVRAM setting value. so the NVRAM setting not Effected my bootmenu setting.
my setting is

```
<plist version="1.0">
<dict>
	<key>NVRAM</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				<key>boot-args</key>
				<string>-cdfon -igfxmlr</string>
				<key>efi-boot-device-data</key>
				<data>......</data>
				<key>efi-boot-device</key>
				<string>......</string>
			</dict>
		</dict>
		<key>Block</key>
		<dict>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<array>
				<string>efi-boot-device</string>
				<string>efi-boot-device-data</string>
				<string>boot-args</string>
			</array>
		</dict>
	</dict>
</dict>
</plist>
```

efi-boot-device and efi-boot-device-data are copy from NVRAM.  And I has tested efi-boot-device with type "data" and "string". 
The result is Opencore only use setting NVRAM value set default boot disk, not use setting in config.plist. when use "System Preferences. -> Startup Disk" change  boot disk, OpenCore default boot disk also changed.

I think maybe Block no effect with "efi-boot-device""、efi-boot-device-data".

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/575#issuecomment-566720384
