### ISSUE TITLE
iasl63 fails to compile formerly compilable sources

### ISSUE THREAD

**Issue by roddy20** [acidanthera/bugtracker#623]
a lot of errors related with
Scope (_PR)
    {
        Processor (CPU1...
"Legacy Processor() keyword detected. Use Device() keyword instead."
and
"Illegal forward reference (LPCR)"
in any existing DSDT, both from Hackintoshes and original Apple
even new MacPro still does not use 6.3 specs, it will be good to make a choise between 6.2 and 6.3 in MacIASL settings

**Comment by vit9696** [comment]
Please provide sample ACPI tables.

**Comment by vit9696** [comment]
I was able to find this with my DSDT, and it is actually a warning, not an error. As long as the file still compiles, I believe we should not change anything.

**Comment by vit9696** [comment]
Thanks for the example. Illegal forward reference is indeed an error. For the time being I asked for clarification in acpica: https://github.com/acpica/acpica/issues/533.

**Comment by vit9696** [comment]
@Moorre updated testing compiler (`iasl-dev`) with the fix to the issue. This should work as an immediate resolution to the problem. Once a stable tag is assigned to acpica compiler, we should update stable version as well. Assigning this issue to @Moorre.

**Comment by vit9696** [comment]
Resolved in master.
