### ISSUE TITLE
WhateverGreen not automatically disabling AGDC

### ISSUE THREAD

**Issue by jasonsansone** [acidanthera/bugtracker#624]
The release notes for WEG 1.1.5 state "added automatic CFG_USE_AGDC disabling to avoid constant issues with 4K display sleep and broken HDMI/DP ports".  However, the output from "ioreg -lw0 | grep CFG_USE_AGDC" is still "CFG_USE_AGDC" = Yes.  Tested using WEG 1.3.5 and test built of 1.3.6.

GPU is Sapphire RX580 Pulse.  OS is 10.15.2.  SMBIOS is MacPro6,1.﻿  Lilu and WEG are most recent versions being injected by newest release of Clover.

**Comment by vit9696** [comment]
This is not a bug, although I am sorry for misleading changelogs. It was reverted soon after the addition due to various issues. You could always add it manually via `CFG,CFG_USE_AGDC` Device Property.

**Comment by jasonsansone** [comment]
My apologies.  I read through the entire release history to see if it was reverted, but I either missed it or it wasn't noted.  Thank you for your help and time.
