### ISSUE TITLE
C622  OC 0.5.2  UP 0.5.4（0.5.3）Start the stuck 【Previous shutdown cause：5】

### ISSUE THREAD

**Issue by CMLNT** [acidanthera/bugtracker#625]
![C4208ADC-8BEC-426A-A5F1-990FA17EBA59](https://user-images.githubusercontent.com/13372840/71761150-cf257500-2f02-11ea-9c6a-e0c0fa1cfc3e.png)
HP Z6 G4
GOLD 6139
64G ECC 
RX 5700XT
0.5.2  Startup is normal and running well
OLD config
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/4021629/config.plist.zip)

0.5.3 0.5.4  Start the stuck
Try to build with the latest config 
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/4021627/config.plist.zip)
Is it related to the following repair project
Added Intel Xeon E5 (Broadwell-EP) support (thx @crazyi)

**Comment by vit9696** [comment]
This does not look like a bug but rather a configuration issue to me. Please use the forums. Perhaps, there is some driver desync (e.g. FwRuntimeServices).
