### ISSUE TITLE
Add a linux build of macserial to MacInfoPkg

### ISSUE THREAD

**Issue by chriswayg** [acidanthera/bugtracker#628]
I wanted to use macserial on linux, but only found macOS and Windows builds.
I adapted the macserial build tool to compile it on linux. 

The code is at [https://github.com/chriswayg/MacInfoPkg/blob/master/macserial/build-linux.tool](https://github.com/chriswayg/MacInfoPkg/blob/master/macserial/build-linux.tool)

but it is not integrated into the original build tool, thus I did not make a pull request. I have used it on Debian testing (actually grml).

almost all commands work except:
```
--generate       (-g)  generate serial for current model
--sys            (-s)  get system info
```

Thus my request, if you could add a linux build of macserial.

> When to use issue tracker:
> * You have new resources or patches to add but cannot make a pull request

**Comment by vit9696** [comment]
Hello,

This sounds pretty nice. We do not have Linux here, but we try to make things compatible where we can.

- I think it is not particularly necessary to integrate it into one file, but you can do that by checking `if [ "$(uname)" = "Linux" ]` should do the trick.
- I would also recommend adding `-static` argument to gcc  on Linux, as Linux does not give us ABI compatibility with shared libraries.
- We will also need [travis integration](https://github.com/acidanthera/MacInfoPkg/blob/master/.travis.yml) to get the binaries automatically uploaded as releases.

Could you please handle this and make a pull request?

**Comment by chromer030** [comment]
You can run windows version of macserial via wine under linux , it's work perfect.

**Comment by vit9696** [comment]
Should be resolved in https://github.com/acidanthera/MacInfoPkg/commit/0a662059e55c08ecb11f5cb887353b8862c27c3c.
