### ISSUE TITLE
Improve IA32 compatibility in OcSupportPkg

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#635]
Currently all UEFI projects are tested to be compilable in IA32 mode. However, many parts are not actually compatible with IA32. Most prominent examples are:

- OcAppleBootCompatLib (will CpuDeadLoop)
- OcMachoLib / OcAppleKernelLib (needs Macho 32 support)
- OcMemoryLib (needs 32-bit mapping)

We do not plan to work on this in any nearest future, but clean patches are welcome.

**Comment by vit9696** [comment]
In case we want to support MSVC toolchains there are various intrinsic imports, some of which are referenced in https://github.com/acidanthera/bugtracker/issues/640.

**Comment by nms42** [comment]
Well,
we should not develop detours|crutches|hacks against intrinsics. If compiler wants intrinsics, give them to it.

Time to make OcIntrinsicsLib(?)?

Back to drawing board!

**Comment by vit9696** [comment]
To be honest, that's my primary concern as well. However, EDK II team does not agree with this direction for several reasons.

- Among the other intrinsics, MSVC compiler may insert memcpy/memset calls. However, under normal conditions MSVC does not allow custom implementations of memcpy and memset, and even if we do add them, MSVC compiler may fail to link to them if LTO is enabled. @Download-Fritz knows more details.
- MSVC intrinsics vary across the compilers, and from what I know there is no stable ABI for them. EDK II still supports very ancient MSVC versions (up to 2010), and I am not sure we want to invest developer time in them.

My personal opinion is that intrinsic support is a must in any project, however, I also believe MSVC compilers is not something one should even consider outside of Microsoft Windows environment. We kind of have to keep them in mind, because we upstream code to EDK II, and they require MSVC compatibility, but in general we do not care much about anything but gcc and clang.

In fact, I have already had to develop [intrinsic support](https://github.com/acidanthera/OcSupportPkg/blob/master/Library/OcGuardLib/Builtins.c) for clang due to a bug in multiplication code in some legacy Xcode. And there also was an attempt to develop [canary support](https://github.com/acidanthera/OcSupportPkg/blob/master/Library/OcGuardLib/Canary.c). Perhaps, we can pile some code there for MSVC as well.

**Comment by Download-Fritz** [comment]
@nms42 MSVC does not seem to have external intrinsic support for LTO, at least not with the edk2 configuration. I.e. everything works fine when there is an explicit call to memset, however when it's only referenced by intrinsic insertion, LTO kills it and the linker errors. If you can find a solution to this problem, that'd help with MSVC a lot!

**Comment by nms42** [comment]
Anyway, let me try it with "new" version vs2019ce (v16.4.2). Miracles|shit happens!

**Comment by nms42** [comment]
Attached patch for compiling our stuff for IA32 with MSVC.

[msvc.diff.txt](https://github.com/acidanthera/bugtracker/files/4052484/msvc.diff.txt)

**Comment by vit9696** [comment]
Thanks, merged in master with minor alterations.
