### ISSUE TITLE
Suggested/Automatic slide parameter has no effect

### ISSUE THREAD

**Issue by v10x** [acidanthera/bugtracker#637]
Hardware:
- EVGA FTW X299 K
- Radeon 5700 XT
- Intel i9-9980XE
- 64GB DDR4 RAM

Software:
- OpenCore: master version built on 01/08/2020.

I've been trying for the past few days to run a Hackintosh on this motherboard. I have enabled all the usual things in BIOS, including Above 4G Decoding.

I opened this issue because I believe there must be some issue with how OpenCore frees and picks slide pages, in particular the logs and `memmap` show that there is enough memory available for the kernel to load.

I've tried any possible combination in the Booter.Quirks section without success, I'd like some guidance on how to proceed and if there is anything that looks wrong.

Attached memmap from UEFI Shell and OpenCore DEBUG log.
[memmap.txt](https://github.com/acidanthera/bugtracker/files/4038694/memmap.txt)
[opencore-2020-01-08-210925.txt](https://github.com/acidanthera/bugtracker/files/4038695/opencore-2020-01-08-210925.txt)

**Comment by cattyhouse** [comment]
Just disable `Above 4G Decoding` for good. at least for my, If it is enabled, my B360M does not boot. Try to disable it.

**Comment by v10x** [comment]
Unfortunately that doesn't make it boot, the slides available do change though from the previous logs:

```
57:876 00:076 OCABC: Only 112/256 slide values are usable!
57:953 00:077 OCABC: Valid slides - 0-75, 149-184
```

**Comment by vit9696** [comment]
Hello, what exactly does happen? I do not see slide information in the first log either.

**Comment by v10x** [comment]
@vit9696 The usual "cannot allocate runtime area", I ended up doing a BIOS mod to disable un-needed features, like SGX, etc, and after a few tries it finally booted. That said, it seems kinda strange to me that OpenCore's calculations wouldn't be correct regarding the slides parameters, or rather ineffective. It could be a firmware bug.

**Comment by vit9696** [comment]
Yes, sounds like a specific firmware issue as we cannot reproduce it here. Still thanks for the report, we will keep this in mind. We will reopen the issue if we have more information in the matter.
