### ISSUE TITLE
can't stop the automatic boot with OC: 10ad3f3

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#644]
with this commit, the arrow key does not work on OpenCore Picker, other keys do not work either, can't pause the automatic boot.

AllowSetDefault=true

**Comment by vit9696** [comment]
Hello, starting with this commit you are required to enable the support for Apple-style keyboard input for OpenCore to work. On non-apple firmwares you may have to ensure correct settings in UEFI → Input section, KeySupport in particular.

**Comment by cattyhouse** [comment]
thanks vit, it works now, sorry i did not notice the message in changelog.md about input protocol.

i have a question i can't test right now, if default boot is set, will macOS upgrade work automatically? you know during OS upgrading, there will be several reboots, each reboot need to choose `macOS Installer` entry.

**Comment by vit9696** [comment]
macOS adds default boot on its own when it upgrades. For this reason given working NVRAM, boot variable redirection, and FwRuntimeServices it always reboots properly. This has not changed since 2019 and has always worked properly.
