### ISSUE TITLE
[weg] AMDRadeonAccelerator: IOAccelDisplayPipeTransaction time out after 300ms. framebufferIndex=0

### ISSUE THREAD

**Issue by v10x** [acidanthera/bugtracker#649]
- GPU: AMD 5700 XT
- Thunderbolt 3
- 5k Display

Using a single DisplayPort 1.4 cable from the graphics card -> Thunderbolt 3 Titan Ridge port. The system boots fine until OSX starts being laggy and showing `AMDRadeonAccelerator: IOAccelDisplayPipeTransaction time out after 300ms. framebufferIndex=0` frequently.

<img width="1093" alt="Screen Shot 2020-01-10 at 10 06 55 AM" src="https://user-images.githubusercontent.com/56550734/72175411-efd14d00-3390-11ea-9ad9-8d57427e1ce1.png">

The "fix" I have for this issue is to attach a different monitor with displayport directly to the GPU. The system then works fine.

I've tried with and without agdpmod=pikera and still has the same issue.

**Comment by vit9696** [comment]
Hello, we have no plans to research this issue at the moment. Please report to Apple. Closing with a reference to #617, where other 5700 XT issues are discussed.
