### ISSUE TITLE
Log filtering in OpenCore

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#652]
Currently our projects have logs prefixed with a module. For example, `OC:` for OpenCore frontend, `OCB:` for OcManagementLib, `OCCPU:` for OcCpuLib, and so on. Since NVRAM and in fact other log targets are not unlimited, it is reasonable to introduce an option to filter the log entries by the module.

`Debug` → `LogModules` string could contain `*` (all modules) or a sequence of comma-separated modules to include in the log and onscreen: `OCCPU,OCB,OCA`. We will have to fix several log entries in the project before we can address this issue.

**Comment by iNDi** [comment]
Do you also intend to have some kind of logging in non DEBUG builds ?

**Comment by vit9696** [comment]
Not really, we believe it is dangerous to expose any sensitive data in release builds.

**Comment by iNDi** [comment]
you have options already to disable such sensitive data so can expand those surely ?

so to see why you can no longer boot because you change a kext, driver or config... you have to install a debug version
thats not a great idea imho

**Comment by iNDi** [comment]
if someone has the ability to see the log then surely the securiy is already dubios ?

**Comment by vit9696** [comment]
Yes, this is correct. Release versions will never provide enough information for debugging all the issues, so we believe that debug version is required for troubleshooting. It is also important for us that release builds have small size and maximum performance, so debugging code is simply not compiled in release builds.

There actually are some messages visible in the release version, and the policy is as follows. Information messages and non-critical errors are only visible in debug builds. Errors not affecting the ability to continue booting are visible in all builds. Critical errors are visible in all builds and result in boot halt.

**Comment by iNDi** [comment]
so users will just stick with using the DEBUG version and all your plans for securing sensitive data is bypassed. 

you didnt answer about if the an 'attacker' can see the log then most of the security has already be bypassed

i think its a narrow minded view, you've made it so hard for end-users in this clama for a security  model which is over zealous.

Sometimes you need to make things easy for people rather than just for us geeks :)

**Comment by vit9696** [comment]
Well, we consider the detection of bootloader presence a security threat in the first place. But you are right that our security model is still being worked on, and may undergo some changes before it lands in the manual.

Not providing log mechanism for release builds is what all products in Acidanthera do. It is consistent across UEFI and kernel extensions. Even if we ignore the security part, performance and size will still matter. I do not mind people using debug or noopt builds if they believe it is right for them.
