### ISSUE TITLE
SanitizeClearScreen causes menu flashes

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#662]
When `SanitizeClearScreen` quirk is enabled, on configurations where `SetMode` call takes a lot of time there is a possibility to get lengthy screen flashes (approximately 1 second long) when OpenCore updates the menu screen. An example is shown on [this video](https://www.youtube.com/watch?v=pAkSQSjbQU4).

The code in question is [ControlledClearScreen](https://github.com/acidanthera/OcSupportPkg/blob/afd7d7f/Library/OcConsoleLib/OcConsoleLib.c#L128-L166) function from OcConsoleLib. I believe it should be possible to improve this by avoiding GOP SetMode call.

CC @Download-Fritz @vandroiy2013

**Comment by vandroiy2013** [comment]
For me it only happens on Gigabyte MB. On Asus everything is OK with SanitizeClearScreen=true.

**Comment by cattyhouse** [comment]
In my case, SanitizeClearScreen is false, as long as CSM is enabled in BIOS, the `OC Menu` **refreshes** during navigation with arrow key. A little bit different than what happened in your video.

**Comment by vit9696** [comment]
[master 3036a26] OcConsoleLib: Rework SanitiseClearScreen
 1 file changed, 50 insertions(+), 9 deletions(-)

Should be fixed, please confirm.

**Comment by vit9696** [comment]
There definitely were some improvements, assuming fixed.
