### ISSUE TITLE
CPU package detection on configurations without MP services

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#663]
Code:

00:000 00:000 OC: OpenCore is now loading (Vault: 0/0, Sign 0/0)...
00:040 00:040 OC: Boot timestamp - 2020.01.14 03:57:35
00:088 00:047 OCCPU: No MP services - Not Found
00:129 00:040 OCCPU: Hypervisor: 0
00:169 00:040 OCCPU: Found Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
00:209 00:040 OCCPU: Signature 206C2 Stepping 2 Model 2C Family 6 Type 0 ExtModel 2 ExtFamily 0 uCode 1F
00:250 00:040 OCCPU: Detected Apple Processor Type: 05 -> 0501
00:368 00:118 OCCPU: Ratio Min 12 Max 26 Current 0 Turbo 28 28 27 27
00:421 00:052 OCCPU: Timer address is 408 from LPC
00:563 00:142 OCCPU: CPUFrequencyFromTSC  3457999409Hz  3457MHz
00:603 00:040 OCCPU: CPUFrequency  3457999409Hz  3457MHz
00:643 00:040 OCCPU: FSBFrequency   132999977Hz   132MHz
00:683 00:040 OCCPU: Pkg 1 Cores 6 Threads 12
.................................................
07:308 00:040 OC: Current version is DBG-055-2020-01-13

Only 1 CPU is detected. Also there is a new line:
00:088 00:047 OCCPU: No MP services - Not Found
The actual system is cMP5,1 with 2 x5690 Xeons.

**Comment by vit9696** [comment]
This firmware does not have EFI MP services protocol (`No MP services - Not Found`), thus we cannot detect the amount of CPUs. If you know an approach to do this without EFI MP services, let us know. In any case this thing is merely cosmetics, so nothing bad happens if they are undetected.

**Comment by vit9696** [comment]
MacPro seems to have legacy `gFrameworkEfiMpServiceProtocolGuid` (`f33261e7-23cb-11d5-bd5c-0080c73c8881`). I guess we can take its headers from [UDK2018](https://github.com/tianocore/edk2/blob/UDK2018/IntelFrameworkPkg/Include/Protocol/FrameworkMpService.h) and adopt it for ourselves.

**Comment by al3xtjames** [comment]
@startergo: Please try the attached version of OpenCore (which has the referenced commit included). Apple's implementation of the framework EFI MP services appears to have some changes (at least on Xserve3,1 with 2x Xeon X5550); please confirm if this is the case on MacPro5,1.

Some logs (in the loop in `ScanFrameworkMpServices`) for those who are curious:

```
00:375 00:126 OCCPU: Processor index = 0
00:499 00:123 OCCPU: Context.PackageNumber = 0
00:644 00:145 OCCPU: Context.NumberOfCores = 8
00:771 00:126 OCCPU: Context.NumberOfThreads = 2
00:894 00:123 OCCPU: Processor index = 1
01:020 00:125 OCCPU: Context.PackageNumber = 0
01:146 00:126 OCCPU: Context.NumberOfCores = 8
01:270 00:123 OCCPU: Context.NumberOfThreads = 2
01:396 00:125 OCCPU: Processor index = 2
01:522 00:126 OCCPU: Context.PackageNumber = 0
01:645 00:123 OCCPU: Context.NumberOfCores = 8
01:793 00:147 OCCPU: Context.NumberOfThreads = 2
01:920 00:126 OCCPU: Processor index = 3
02:043 00:123 OCCPU: Context.PackageNumber = 0
02:169 00:126 OCCPU: Context.NumberOfCores = 8
02:293 00:123 OCCPU: Context.NumberOfThreads = 2
02:419 00:126 OCCPU: Processor index = 4
02:545 00:126 OCCPU: Context.PackageNumber = 0
02:669 00:124 OCCPU: Context.NumberOfCores = 8
02:795 00:125 OCCPU: Context.NumberOfThreads = 2
02:941 00:146 OCCPU: Processor index = 5
03:065 00:123 OCCPU: Context.PackageNumber = 0
03:191 00:126 OCCPU: Context.NumberOfCores = 8
03:317 00:126 OCCPU: Context.NumberOfThreads = 2
03:440 00:123 OCCPU: Processor index = 6
03:566 00:125 OCCPU: Context.PackageNumber = 0
03:690 00:123 OCCPU: Context.NumberOfCores = 8
03:816 00:126 OCCPU: Context.NumberOfThreads = 2
03:942 00:125 OCCPU: Processor index = 7
04:084 00:142 OCCPU: Context.PackageNumber = 0
04:210 00:126 OCCPU: Context.NumberOfCores = 8
04:336 00:125 OCCPU: Context.NumberOfThreads = 2
04:460 00:123 OCCPU: Processor index = 8
04:586 00:126 OCCPU: Context.PackageNumber = 1
04:709 00:123 OCCPU: Context.NumberOfCores = 8
04:835 00:126 OCCPU: Context.NumberOfThreads = 2
04:962 00:126 OCCPU: Processor index = 9
05:085 00:123 OCCPU: Context.PackageNumber = 1
05:232 00:146 OCCPU: Context.NumberOfCores = 8
05:358 00:125 OCCPU: Context.NumberOfThreads = 2
05:481 00:123 OCCPU: Processor index = 10
05:607 00:126 OCCPU: Context.PackageNumber = 1
05:733 00:126 OCCPU: Context.NumberOfCores = 8
05:857 00:123 OCCPU: Context.NumberOfThreads = 2
05:983 00:125 OCCPU: Processor index = 11
06:106 00:123 OCCPU: Context.PackageNumber = 1
06:253 00:146 OCCPU: Context.NumberOfCores = 8
06:380 00:127 OCCPU: Context.NumberOfThreads = 2
06:504 00:123 OCCPU: Processor index = 12
06:630 00:125 OCCPU: Context.PackageNumber = 1
06:756 00:126 OCCPU: Context.NumberOfCores = 8
06:880 00:123 OCCPU: Context.NumberOfThreads = 2
07:006 00:126 OCCPU: Processor index = 13
07:132 00:126 OCCPU: Context.PackageNumber = 1
07:255 00:123 OCCPU: Context.NumberOfCores = 8
07:398 00:142 OCCPU: Context.NumberOfThreads = 2
07:524 00:126 OCCPU: Processor index = 14
07:647 00:123 OCCPU: Context.PackageNumber = 1
07:773 00:126 OCCPU: Context.NumberOfCores = 8
07:897 00:123 OCCPU: Context.NumberOfThreads = 2
08:023 00:125 OCCPU: Processor index = 15
08:149 00:126 OCCPU: Context.PackageNumber = 1
08:272 00:123 OCCPU: Context.NumberOfCores = 8
08:398 00:126 OCCPU: Context.NumberOfThreads = 2
```

[OpenCore.efi.zip](https://github.com/acidanthera/bugtracker/files/4068372/OpenCore.efi.zip)

**Comment by startergo** [comment]
"00:000 00:000 OC: OpenCore is now loading (Vault: 0/0, Sign 0/0)...
00:037 00:037 OC: Boot timestamp - 2020.01.16 00:48:51
00:073 00:036 OCCPU: MP services threads 24 (enabled 24) - Success
00:109 00:036 OCCPU: MP services Pkg 2 Cores 16 Threads 32 - Success
00:149 00:039 OCCPU: Hypervisor: 0
00:186 00:036 OCCPU: Found Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
00:672 00:486 OCCPU: Signature 206C2 Stepping 2 Model 2C Family 6 Type 0 ExtModel 2 ExtFamily 0 uCode 1F
00:726 00:054 OCCPU: Detected Apple Processor Type: 05 -> 0501
00:762 00:036 OCCPU: Ratio Min 12 Max 26 Current 0 Turbo 28 28 27 27
00:799 00:036 OCCPU: Timer address is 408 from LPC
00:935 00:136 OCCPU: CPUFrequencyFromTSC  3458000389Hz  3458MHz
00:972 00:036 OCCPU: CPUFrequency  3458000389Hz  3458MHz
01:009 00:036 OCCPU: FSBFrequency   133000014Hz   133MHz
01:058 00:049 OCCPU: Pkg 2 Cores 6 Threads 12
01:095 00:036 OC: OcLoadUefiSupport...
01:132 00:036 OCC: Install console control 0 - Success
01:168 00:036 AIFTimerBoostInit Current timer is 2500
01:205 00:036 OCABC: Firmware has 33542917 free pages (480005 in lower 4 GB)
01:241 00:036 OCC: Configuring console ignore 0 san clear 0 clear switch 0 replace tab 0s
01:290 00:048 OCC: Configuring behaviour 1
01:327 00:037 OC: Got 1 drivers
01:363 00:035 OC: Driver FwRuntimeServices.efi at 0 is being loaded...
01:517 00:154 OC: Driver FwRuntimeServices.efi at 0 is successfully loaded!
01:628 00:111 OC: Connecting drivers...
04:832 03:204 OC: OcLoadAcpiSupport...
04:882 00:049 OCA: Found 10 ACPI tables"
Package detection works now! Thank you!
The only thing missing is current CPU ratio

**Comment by al3xtjames** [comment]
Probably not relevant (since the core/thread count is later corrected to 6/12), but please post the output of this version (which has additional logging; trying to see why MP services reports 16 cores). 
[OpenCore.efi.zip](https://github.com/acidanthera/bugtracker/files/4068944/OpenCore.efi.zip)

**Comment by startergo** [comment]
> 
> 
> Probably not relevant (since the core/thread count is later corrected to 6/12, and this is cosmetic anyway), but please post the output of this version (which has additional logging; trying to see why MP services reports 16 cores).
> [OpenCore.efi.zip](https://github.com/acidanthera/bugtracker/files/4068944/OpenCore.efi.zip)

`00:000 00:000 OC: OpenCore is now loading (Vault: 0/0, Sign 0/0)...
00:066 00:066 OC: Boot timestamp - 2020.01.16 03:06:03
00:224 00:157 OCCPU: MP services loop: Index 0 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
00:290 00:066 OCCPU: MP services loop: Index 1 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
00:356 00:065 OCCPU: MP services loop: Index 2 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
00:429 00:072 OCCPU: MP services loop: Index 3 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
00:495 00:066 OCCPU: MP services loop: Index 4 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
00:562 00:066 OCCPU: MP services loop: Index 5 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
00:636 00:074 OCCPU: MP services loop: Index 6 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
00:705 00:068 OCCPU: MP services loop: Index 7 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
00:771 00:066 OCCPU: MP services loop: Index 8 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
00:843 00:071 OCCPU: MP services loop: Index 9 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
00:988 00:145 OCCPU: MP services loop: Index 10 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
01:054 00:065 OCCPU: MP services loop: Index 11 PackageNumber 0 NumberOfCores 16 NumberOfThreads 2
01:131 00:077 OCCPU: MP services loop: Index 12 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:200 00:068 OCCPU: MP services loop: Index 13 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:267 00:066 OCCPU: MP services loop: Index 14 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:345 00:077 OCCPU: MP services loop: Index 15 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:414 00:069 OCCPU: MP services loop: Index 16 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:481 00:066 OCCPU: MP services loop: Index 17 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:558 00:077 OCCPU: MP services loop: Index 18 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:626 00:068 OCCPU: MP services loop: Index 19 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:763 00:136 OCCPU: MP services loop: Index 20 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:842 00:078 OCCPU: MP services loop: Index 21 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:909 00:067 OCCPU: MP services loop: Index 22 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
01:976 00:067 OCCPU: MP services loop: Index 23 PackageNumber 1 NumberOfCores 16 NumberOfThreads 2
02:055 00:078 OCCPU: MP services threads 24 (enabled 24) - Success
02:123 00:068 OCCPU: MP services Pkg 2 Cores 16 Threads 32 - Success
02:189 00:066 OCCPU: Hypervisor: 0
02:266 00:076 OCCPU: Found Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
02:335 00:068 OCCPU: Signature 206C2 Stepping 2 Model 2C Family 6 Type 0 ExtModel 2 ExtFamily 0 uCode 1F
02:401 00:066 OCCPU: Detected Apple Processor Type: 05 -> 0501
02:549 00:148 OCCPU: PerfStatus.Bits.State = 26
02:618 00:069 OCCPU: Ratio Min 12 Max 26 Current 26 Turbo 28 28 27 27
02:684 00:066 OCCPU: Timer address is 408 from LPC
02:851 00:167 OCCPU: CPUFrequencyFromTSC  3458000389Hz  3458MHz
02:932 00:080 OCCPU: CPUFrequency  3458000389Hz  3458MHz
02:999 00:066 OCCPU: FSBFrequency   133000014Hz   133MHz
03:065 00:066 OCCPU: Pkg 2 Cores 6 Threads 12
03:144 00:079 OC: OcLoadUefiSupport...
03:210 00:065 OCC: Install console control 0 - Success
03:276 00:066 AIFTimerBoostInit Current timer is 2500
03:426 00:149 OCABC: Firmware has 33542916 free pages (480004 in lower 4 GB)
03:492 00:066 OCC: Configuring console ignore 0 san clear 0 clear switch 0 replace tab 0s
03:558 00:065 OCC: Configuring behaviour 1
03:637 00:078 OC: Got 1 drivers
03:704 00:067 OC: Driver FwRuntimeServices.efi at 0 is being loaded...
03:891 00:186 OC: Driver FwRuntimeServices.efi at 0 is successfully loaded!
03:972 00:081 OC: Connecting drivers...
07:101 03:128 OC: OcLoadAcpiSupport...
07:166 00:065 OCA: Found 10 ACPI tables`

**Comment by startergo** [comment]
> Probably not relevant (since the core/thread count is later corrected to 6/12, and this is cosmetic anyway), but please post the output of this version (which has additional logging; trying to see why MP services reports 16 cores).

FYI I just ran AHT and it detected 16 cores??? Go figure. So it is something internal in the firmware. I will reflash the smbios and recheck just to make sure those 16 cores were not a result of using OC.
