### ISSUE TITLE
Default DevicePath match failure due to different PciRoot

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#664]
On ASUS Z10PE-D16 WS there are 4 PCI controllers:

- PCI0, with `_UID` 0x00
- PCI1, with `_UID` 0x40
- PCI2, with `_UID` 0x80
- PCI3, with `_UID` 0xC0

For an NVMe SSD connected to PCI1 controller macOS produces the following DP entry:

```
OCB: 0 -> Boot0080 = PciRoot(0x40)/Pci(0x2,0x0)/Pci(0x0,0x0)/SasEx(0x0100000000000000,0x000000007074616C,0xAFAF,0xAFAF,0,0,0)/HD(2,GPT,E27F7DB3-2948-4EBD-BC0A-A0C41031C3CC,0x64028,0x37DDF660)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,2A4679421200D742BBFCEABCA397ED7B)/\AD597D33-6D67-34A8-9661-359285B18873\System\Library\CoreServices\boot.efi
```

However, the firmware creates an invalid DP entry:

```
Entry 1 is SSD at \AD597D33-6D67-34A8-9661-359285B18873\System\Library\CoreServices\ (T:1|F:0)
Entry 1 is SSD at dp PciRoot(0x1)/Pci(0x2,0x0)/Pci(0x0,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)/HD(2,GPT,E27F7DB3-2948-4EBD-BC0A-A0C41031C3CC,0x64028,0x37DDF660)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,2A4679421200D742BBFCEABCA397ED7B)/\AD597D33-6D67-34A8-9661-359285B18873\System\Library\CoreServices\boot.efi
```

To workaround this we need to treat invalid PciRoot as 0x1. It seems to be a good idea to also treat it as 0x0. I do not think we need to backtrack this with PcieRoot hack, as it is unlikely that there exist boards with both PciRoot/PcieRoot bug and incorrect PciRoot UID treatment.

Files: [log_dumps.7z.zip](https://github.com/acidanthera/bugtracker/files/4066226/log_dumps.7z.zip) (usual PW)

**Comment by vit9696** [comment]
Inspecting the code confirms that the firmware likely creates host bridge device paths in a loop, which will make the following mapping: `0x00 → 0x00, 0x40 → 0x01, 0x80 → 0x02, 0xC0 → 0x03`. To workaround this I believe we can build the following map in our code as well. Before it may be reasonable to check some similar boards for the issue.

**Comment by vit9696** [comment]
There actually is another issue with MacPro5,1 the referencing commit resolves.

Last Apple MacPro5,1 firmware version includes NVMe driver, which contains a typo when handling NVMe drives in MSG_SASEX_DP value. Instead of 0x16 aka 22 (SasEx) it uses 0x22 aka 34 (Unspecified).

Initially reported by https://forums.macrumors.com/posts/28169441. Relevant DevicePaths:
```
00:644 00:003 OCB: Dumping BootOrder
00:648 00:003 OCB: 0 -> Boot0080 = MemoryMapped(0xB,0xFFD50000,0xFFFDFFFF)/FvFile(2B0585EB-D8B8-49A9-8B8C-E21B01AEF2B7)
00:651 00:003 OCB: Predefined list
00:654 00:003 OCB: 0 -> Boot0080 = MemoryMapped(0xB,0xFFD50000,0xFFFDFFFF)/FvFile(2B0585EB-D8B8-49A9-8B8C-E21B01AEF2B7)
00:657 00:003 OCB: 1 -> Boot0081 = PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)/Pci(0x11,0x0)/Pci(0x0,0x0)/SasEx(0x0100000000253857,0x91500E337074616C,0x0,NoTopology,0,0,0)/HD(1,GPT,5E201C4F-0982-4DFD-1CB6-74B5D2273719,0x800,0x32000)
00:661 00:003 OCB: 2 -> Boot0082 - failed to read
00:664 00:003 OCB: Predefined list
00:667 00:003 OCB: Default is AppleLegacyLoadApp
00:670 00:003 OCB: Default DP pre-fix - PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)/Pci(0x11,0x0)/Pci(0x0,0x0)/SasEx(0x0100000000253857,0x91500E337074616C,0x0,NoTopology,0,0,0)
00:674 00:003 OCB: Default DP post-fix - PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)/Pci(0x11,0x0)/Pci(0x0,0x0)/NVMe(0x1,33-0E-50-91-57-38-25-00)
00:677 00:003 OCB: Default DP post-fix remainder - NVMe(0x1,33-0E-50-91-57-38-25-00)
00:680 00:003 OCPI: Locating disk's ESP - PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)/Pci(0x11,0x0)/Pci(0x0,0x0)/NVMe(0x1,33-0E-50-91-57-38-25-00)
00:684 00:003 Failed to locate the disk's ESP
```

```
00:617 00:004 Entry 2 is BOOTCAMP Windows at \EFI\BOOT\ (T:3|F:0)
00:621 00:003 Entry 2 is BOOTCAMP Windows at dp PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)/Pci(0x11,0x0)/Pci(0x0,0x0)/Msg(34,010000000025385791500E33)/HD(1,GPT,5E201C4F-0982-4DFD-1CB6-74B5D2273719,0x800,0x32000)/\EFI\BOOT\BOOTX64.efi
```

**Comment by Download-Fritz** [comment]
On ASUS PRIME X299-DELUXE II we have:
* PC00, with _UID 0x00
* PC01, with _UID 0x10
* PC02, with _UID 0x20
* PC03, with _UID 0x28
* PC04, with _UID 0x30
* PC05, with _UID 0x38

**Comment by vit9696** [comment]
On Dell Inspiron 530 (Xeon E5450 CPU with G33/ICH9) we have PCI0 with _UID 0x01 (which actually is 0x00). Similar issue is also present in QEMU, but in QEMU it may [get fixed soon](https://www.mail-archive.com/qemu-devel@nongnu.org/msg724254.html), first raised [here](https://github.com/acidanthera/bugtracker/issues/1050).

On the Dell Inspiron this is not the only issue. It does not support SATA mode for the controller, so we need to choose between IDE and RAID, with the former being unsupported by macOS. For RAID mode to get DuetPkg work the following patches are needed: [first](https://github.com/acidanthera/OpenCorePkg/blob/7b5b145/Patches/0001-MdeModulePkg-SataControllerDxe-Add-support-for-drive.patch) and [second](https://github.com/acidanthera/OpenCorePkg/blob/7b5b145/Patches/0002-MdeModulePkg-AtaAtapiPassThru-Add-support-for-drives.patch).

As a result there are more discrepancies in the device paths:

```
1.
00:944 00:002 OCB: 0 -> Boot0080 = PciRoot(0x1)/Pci(0x1F,0x2)/Ata(Primary,Slave,0x0)/HD(5,GPT,49B835C0-F55C-43C6-99FA-B940EC2C459F,0x52C03CD8,0xFADE4D8)
01:168 00:002 OCB: Adding bless entry on disk - PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x1,0xFFFF,0x0)/HD(5,GPT,49B835C0-F55C-43C6-99FA-B940EC2C459F,0x52C03CD8,0xFADE4D8)

2.
00:932 00:002 OCB: 0 -> Boot0080 = PciRoot(0x1)/Pci(0x1F,0x2)/Ata(Primary,Slave,0x0)/HD(2,GPT,829755CD-439B-46B8-944E-B377F33FCF5F,0x64028,0x116940B8)
01:030 00:002 OCB: Adding bless entry on disk - PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0)/HD(2,GPT,829755CD-439B-46B8-944E-B377F33FCF5F,0x64028,0x116940B8)

3.
05:643 00:029 OCB: 0 -> Boot0080 = PciRoot(0x1)/Pci(0x1F,0x2)/Ata(Primary,Slave,0x0)/HD(2,GPT,EF1D3901-22AE-49D0-B0D7-8B3660C6A2EF,0x64028,0x4BB4F5F0)
07:341 00:029 OCB: Adding bless entry on disk - PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x1,0xFFFF,0x0)/HD(2,GPT,EF1D3901-22AE-49D0-B0D7-8B3660C6A2EF,0x64028,0x4BB4F5F0)

4.
00:940 00:002 OCB: 0 -> Boot0080 = PciRoot(0x1)/Pci(0x1F,0x2)/Ata(Primary,Slave,0x0)/HD(7,GPT,4D930D60-C258-43D1-8801-A7AB6729CDB4,0x628580D0,0x11D38D98)
01:209 00:002 OCB: Adding bless entry on disk - PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x1,0xFFFF,0x0)/HD(7,GPT,4D930D60-C258-43D1-8801-A7AB6729CDB4,0x628580D0,0x11D38D98)

5.
04:137 00:019 OCB: 0 -> Boot0080 = PciRoot(0x1)/Pci(0x1F,0x2)/Ata(Primary,Slave,0x0)/HD(3,GPT,C340DB45-0EC7-4DE7-AC07-C7AC5F1046B3,0x4BBF3618,0x6E9A7A0)
05:579 00:020 OCB: Adding bless entry on disk - PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x1,0xFFFF,0x0)/HD(3,GPT,C340DB45-0EC7-4DE7-AC07-C7AC5F1046B3,0x4BBF3618,0x6E9A7A0)
```

Note, that for macOS all the device paths are `Primary,Slave,0x0`, but for UEFI 2nd sample has `Sata(0x0,0xFFFF,0x0)`, while the third sample has Sata(0x1,0xFFFF,0x0).

**Comment by vit9696** [comment]
Atapi issue was caused by missing `DevicePathsSupported`. On 10.10 it would instead be SasEx (NVMe) due to a bug in NVMe node appending.

**Comment by Hc2Life** [comment]
> On ASUS Z10PE-D16 WS there are 4 PCI controllers:
> 
> 
> 
> - PCI0, with `_UID` 0x00
> 
> - PCI1, with `_UID` 0x40
> 
> - PCI2, with `_UID` 0x80
> 
> - PCI3, with `_UID` 0xC0
> 
> 
> 
> For an NVMe SSD connected to PCI1 controller macOS produces the following DP entry:
> 
> 
> 
> ```
> 
> OCB: 0 -> Boot0080 = PciRoot(0x40)/Pci(0x2,0x0)/Pci(0x0,0x0)/SasEx(0x0100000000000000,0x000000007074616C,0xAFAF,0xAFAF,0,0,0)/HD(2,GPT,E27F7DB3-2948-4EBD-BC0A-A0C41031C3CC,0x64028,0x37DDF660)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,2A4679421200D742BBFCEABCA397ED7B)/\AD597D33-6D67-34A8-9661-359285B18873\System\Library\CoreServices\boot.efi
> 
> ```
> 
> 
> 
> However, the firmware creates an invalid DP entry:
> 
> 
> 
> ```
> 
> Entry 1 is SSD at \AD597D33-6D67-34A8-9661-359285B18873\System\Library\CoreServices\ (T:1|F:0)
> 
> Entry 1 is SSD at dp PciRoot(0x1)/Pci(0x2,0x0)/Pci(0x0,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)/HD(2,GPT,E27F7DB3-2948-4EBD-BC0A-A0C41031C3CC,0x64028,0x37DDF660)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,2A4679421200D742BBFCEABCA397ED7B)/\AD597D33-6D67-34A8-9661-359285B18873\System\Library\CoreServices\boot.efi
> 
> ```
> 
> 
> 
> To workaround this we need to treat invalid PciRoot as 0x1. It seems to be a good idea to also treat it as 0x0. I do not think we need to backtrack this with PcieRoot hack, as it is unlikely that there exist boards with both PciRoot/PcieRoot bug and incorrect PciRoot UID treatment.
> 
> 
> 
> Files: [log_dumps.7z.zip](https://github.com/acidanthera/bugtracker/files/4066226/log_dumps.7z.zip) (usual PW)

**Comment by Hc2Life** [comment]
PciRaot(0x0)/Pci<0x1, 0x1)/Pci(0x0, Ox0)/NVMe(0x1, 7E-26-26-46-8B-44-1B-00)/HD(2, GPT, 8BD6350A-B805-44DF-8D64-A503B4A1738F, 0x32800, 0x8000)

リモートデェスクが切り離せずに困っています

GPT ATTRIBUTES=0x8000000000000000
GPT ATTRIBUTES=0F000000000000001
属性の消去変更が出来ずにいます。
