### ISSUE TITLE
ApplelMucontroller error with VirtualSMC 1.1.0

### ISSUE THREAD

**Issue by Matgen84** [acidanthera/bugtracker#665]
Hi 

I've got the errors below with VSMC 1.1.0 with Clover Bootloader (VSMC v1.0.9 works fine). No answers when I post in VSMC topic, so I post in bugtracker:

(AppleSMCLMU) AppleLMUController::smcGetKeyInfo Error: received error 0x84 when getting key info for 'ALRV'﻿
(AppleSMCLMU) AppleLMUController::smcReadKey Error: received error 0x84 when reading key 'MSLD'
(AppleSMCLMU) AppleLMUController::smcReadKey Error: received error 0x84 when reading key 'ALV0'

**Comment by vandroiy2013** [comment]
Hi. 
We do not support Clover since September 2019. 
If you have this errors with OpenCore you are welcome to open new issue. 

Thanks.

**Comment by vit9696** [comment]
In either case, it is not a bug that you have no support for these keys. These keys are from light sensor, and are not present on all macs.
