### ISSUE TITLE
Move imported protocols to EfiPkg

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#666]
Currently we have LegacyRegion and FirmwareVolume protocols in OcSupportPkg. I believe they should be in EfiPkg. It is discussible where should Heci protocols live as well.

CC @Download-Fritz

**Comment by Download-Fritz** [comment]
I believe deprecated Intel Framework protocols should be in EfiPkg (treated as vendor-specific), while of course AMI and such belong to OcSupportPkg.

**Comment by vit9696** [comment]
Done in master.
