### ISSUE TITLE
LogoutHook does not save NVRAM

### ISSUE THREAD

**Issue by roddy20** [acidanthera/bugtracker#667]
LogoutHook does not save NVRAM if efi-boot-device-data is not present
getKey 'efi-boot-device-data' > efi-boot-device-data || abort "Failed to retrieve efi-boot-device-data!"
possible solution:
if [ "$(getKey 8BE4DF61-93CA-11D2-AA0D-00E098032B8C:Boot0080)" ] && [ "$(getKey efi-boot-device-data)" ]; then ...

**Comment by roddy20** [comment]
[LogoutHook.command.zip](https://github.com/acidanthera/bugtracker/files/4083721/LogoutHook.command.zip)
fixed

**Comment by vit9696** [comment]
I fixed some portability issues and TOCTOU problems. Does this still work for you?

[LogoutHook.command.zip](https://github.com/acidanthera/bugtracker/files/4084014/LogoutHook.command.zip)

**Comment by roddy20** [comment]
[LogoutHook.command.zip](https://github.com/acidanthera/bugtracker/files/4091128/LogoutHook.command.zip)
added if [ ! -z "$(/bin/cat "${key}" | /usr/bin/hexdump )" ] 
to fix detection in case of saved nvram key with data <00>
works ok
