### ISSUE TITLE
Connection freeze with external SATA controllers

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#669]
GA-Z87X-UD4H 
Sata controller Marvell 88SE9172
[opencore-2020-01-17-004834.txt.zip](https://github.com/acidanthera/bugtracker/files/4074508/opencore-2020-01-17-004834.txt.zip)
![IMG_0458](https://user-images.githubusercontent.com/17758753/72575882-f86cda80-38de-11ea-93e9-d67e7f65e59f.JPG)

**Comment by vit9696** [comment]
It is confirmed that the issue is specific to us, and it is not related to `UnblockFsConnect`.

**Comment by partytimeexcellent** [comment]
I have this same issue on Z77X-UD5H

If any drive is connected to onboard Marvell 88SE9172 or PCI attached ASMedia ASM1062 SATA controllers, OC stalls for approximately 4 minutes before proceeding to picker menu. Any bootable volume (Windows or MacOS) attached to 3rd party controller will fail to boot.

This does not occur with same hardware setup booted through Clover.
[opencore-boot-log-slow-boot-3rd-party-sata.txt.zip](https://github.com/acidanthera/bugtracker/files/4079781/opencore-boot-log-slow-boot-3rd-party-sata.txt.zip)

Thank you for this great project!
