### ISSUE TITLE
IONVMeController Kernel Panic

### ISSUE THREAD

**Issue by ivanhtp** [acidanthera/bugtracker#670]
Feedback after this post https://www.insanelymac.com/forum/topic/341984-nvmefix/?do=findComment&comment=2704539. relating to NVMEFix

I have a Samsung 960 EVO NVME and I have kernel panics after some usage time. There are no specific tasks that reproduce the problem exactly. It is kind of arbitrary.
I hope it helps.

I don't have too much experience in report the proper logs, please let me know if I can provide anything else.

My system is a core i7 8700 (non-k), MB gigabyte z370n wifi, 16gb ram. Samsung nvme 960 evo 256gb running catalina 10.15.2 (although this problem comes since high sierra.

[Logs.zip](https://github.com/acidanthera/bugtracker/files/4076780/Logs.zip)

**Comment by vandroiy2013** [comment]
Kernel->Quirks->DisableIoMapper=true.

**Comment by ivanhtp** [comment]
I believe the property you recommended is OpenCore only, right?
I use clover.. how does it relate to the problem at all?

**Comment by vandroiy2013** [comment]
DropDMAR will help you in Clover

**Comment by 07151129** [comment]
Is the panic reproducible with DropDMAR? You need to disable VT-d, and using dart=0 bootarg alone is not sufficient if you have SIP enabled.

**Comment by ivanhtp** [comment]
@07151129  Just installed windows and SAMSUNG Magician Software...
It shows I do have the latest firmware. I don't know if it was done automatically though... 
I was really hoping it could solve the problem. The panics started to get more frequent now :(

About the sleep, yes. It happens if I never sleep the computer. What I've noticed is that it tends to panic more frequently if I'm listening to music or watching a video. But it can be only an impression.

![Capturar](https://user-images.githubusercontent.com/126082/72669806-f7d66000-3a14-11ea-98f7-c93cc0b61cb8.PNG)

**Comment by 07151129** [comment]
Can you try an earlier version of firmware as well? It looks like Windows users with 3B7QCXE7 also [reported](https://us.community.samsung.com/t5/Monitors-and-Memory/1tb-960-evo-100-windows-10-freezes-and-crashes-after-firmware/m-p/297579) freezes.

**Comment by osy86** [comment]
https://github.com/osy86/HaC-Mini/issues/22

I’ve dealt with similar problems, I think it may be an overheating issue.

**Comment by ivanhtp** [comment]
> Can you try an earlier version of firmware as well? It looks like Windows users with 3B7QCXE7 also [reported](https://us.community.samsung.com/t5/Monitors-and-Memory/1tb-960-evo-100-windows-10-freezes-and-crashes-after-firmware/m-p/297579) freezes.
> 
> How stable is the drive on Windows?

At least for my knowledge, the downgrade is not possible. I tried some forums and it's no possible to downgrade. A Linux user said he managed it but the process is insane. I went after the thread you've posted and until this moment, Samsung gave no feedback about the problem, although it recognized the problem as a failure.

About windows usage: Weirdly it worked fine on installation but after some time (3 hours average) it started to blue screen. 
Now I don't know if the drive is fried (it doesn't hold even for 5 minutes without crash anymore..) or if the MB nvme socket has a problem. 

The timing is really bad for it. :(  I've been running this system since February 2018 and now it happens.

At least I confirmed the problem was 100% on the nvme. I restored the system to a 480gb Sandisk SATA ssd and its running smoothly since Saturday. I'll try to buy another NVME next month on a travel and give it another try to see if it's the socket or the drive itself.

**Comment by gongzhenjeef** [comment]
I'm sorry for reopen the issue, but I just ran into the same issue on an WD SN720 with DMAR dropped. Before the hang, I was copying some files to USB hard drive. I'm not sure if it's caused by overheat, but I didn't have similar issues before.
[NVMe_panic_SN720.zip](https://github.com/acidanthera/bugtracker/files/4209207/NVMe_panic_SN720.zip)
