### ISSUE TITLE
BS: Unsupported bootstrap protocol 5 vs 4

### ISSUE THREAD

**Issue by Pavo-IM** [acidanthera/bugtracker#672]
commit https://github.com/acidanthera/OcSupportPkg/commit/3936584d86e9207162243bae1b39d8972454bed6 broke booting with the following errors.

```
BS: Unsupported bootstrap protocol 5 vs 4
BS: Failed to start OpenCore image - Already started
BS: Failed to load OpenCore from disk - Already started
```

**Comment by vit9696** [comment]
It did not. You have outdated files.

**Comment by Pavo-IM** [comment]
How are they outdated if they were compiled directly from the latest commit? Every single file was compiled at the same time. Which files are you saying are outdated?

**Comment by vit9696** [comment]
BOOTx64.efi.
