### ISSUE TITLE
Add Navi 10/14 identifiers to WEG

### ISSUE THREAD

**Issue by v10x** [acidanthera/bugtracker#673]
Specifically

```
	7310  Navi 10
	7312  Navi 10 [Radeon Pro W5700]
	731f  Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
	7340  Navi 14 [Radeon RX 5500/5500M / Pro 5500M]
	7341  Navi 14 [Radeon Pro W5500]
	7347  Navi 14 [Radeon Pro W5500M]
	734f  Navi 14 [Radeon Pro W5300M]
```

from https://raw.githubusercontent.com/pciutils/pciids/master/pci.ids should be added to https://github.com/acidanthera/WhateverGreen/blob/master/WhateverGreen/kern_model.cpp

**Comment by vandroiy2013** [comment]
Hi. 
Navi drivers can detect card models without our help.

**Comment by v10x** [comment]
I'm seeing some weird behavior where the displayport goes black after coming back from sleep. I need to manually disconnect and reconnect the displayport cable to get desktop again. I assumed this is something WEG takes care of?
