### ISSUE TITLE
SSDT-EC-USB.ssdt Error on Catalina on Intel nuc8

### ISSUE THREAD

**Issue by Frank-N-Furter** [acidanthera/bugtracker#678]
Same SSDT-EC-USB.ssdt Ok for boot 10.14, but 10.15 has loading failure. Same time on same configuration, same bootloader version 0.5.4.
![IMG_3842](https://user-images.githubusercontent.com/22460033/72897626-a682e500-3d22-11ea-8594-e044dc778244.JPG)

**Comment by vandroiy2013** [comment]
Hi. 
This is not a support forum. Use forums to get help with such problems. 

Thanks.
