### ISSUE TITLE
OC: EnableWriteUnprotector breaks Windows Hello Fingerprint authentication

### ISSUE THREAD

**Issue by 1Revenger1** [acidanthera/bugtracker#680]
On my Lenovo X1 Extreme, there is a Synaptics fingerprint sensor which can be used instead of a password when logging into windows, and can also be used to unlock the laptop itself to boot up. When you turn on EnableWriteUnprotector and boot windows through OC, this causes windows to do something to invalidate/clear fingerprint data from the chip making it so you can not use it to login into Windows or unlock the device, instead requiring a password/pin. I can still clear and add fingers to the reader, but it can't be used to authenticate. Turning off EnableWriteUnprotector though prevents macOS from booting on this device, which is why this is an issue. I would still like to use OpenCore though for dual-booting and using the Bootcamp switcher to switch between operating systems.

To reproduce:
1) Add a finger to Windows Hello
2) Turn on EnableWriteUnprotector 
3) Restart into Windows through OpenCore
4) Die on the inside because Windows said no

To get it working again
1) Turn off EnableWriteUnprotector
2) Clear fingerprint data, and then add your finger again
3) Restart into Windows through OpenCore
4) Login using fingerprint reader

Curiously, even with EnableWriteUnprotector off, the UEFI still prohibits me from using the finger print to unlock the device and allow it to boot, instead forcing me to use the password. This is an aside though, and not important for this issue.

My thoughts on this:
Would it be possible to push back OcAbcInitialize to be past selecting the boot device, and having some way to toggle memory settings per boot device (or override them?). Or, connect the drivers if needed and choose the boot device before doing any apple boot compatibility stuff if required. Either of these solutions would probably require a good amount of refactoring. I was going to mess around a bit on my own fork to see if I could get something to work, but it likely wouldn't be pretty or something I'd want to create a pull request for.

Edit: Should probably add the config plist, lol
[Config.plist.zip](https://github.com/acidanthera/bugtracker/files/4106259/Config.plist.zip)

**Comment by 1Revenger1** [comment]
Huh, I sent in the config and didn't change anything (left writeUnprotector on) and authentication in windows worked again. I was having issues all of last night and this morning with it. If I don't run into anymore issues today, I will just close this

**Comment by vit9696** [comment]
Hi, something is wrong with this issue at the very least. `EnableWriteUnprotector` is enabled only for macOS for reasons similar to yours: Windows Virtualisation Protection is not compatible with it. The relevant piece is [here](https://github.com/acidanthera/OcSupportPkg/blob/3cd02f6/Library/OcAppleBootCompatLib/ServiceOverrides.c#L363). I am not positive there is no issue, but I am positive it is different from what you initially described.

I *think* it may have something to do to updated pointers and checksum in `EFI_RUNTIME_SERVICES` by FwRuntimeServices driver, but I do not have a good clue on it. The relevant code is [here](https://github.com/acidanthera/OcSupportPkg/blob/00ae40a/Platform/FwRuntimeServices/UefiRuntimeServices.c#L1093). This is unconditional for all operating systems.

I do not think we can change much here, as applying changes early allows us to ensure we do not recursively apply patches or behave confusingly for different systems. However, to be able to advise anything we will firstly need to understand the problem.

**Comment by 1Revenger1** [comment]
After messing with it a bit, I found that it was switching between using OpenCore and just selecting Windows directly from the UEFI boot menu that was causing the issues. So it's user error by the looks of it, and it just happened that me messing with EnableWriteUnprotector around that time made it appear like that was the culprit.

Thanks for taking a look, looks like it ended up being user error/stupidity
