### ISSUE TITLE
Bootcamp / WIndows installer deletes BOOT folder in EFI

### ISSUE THREAD

**Issue by mathew1975** [acidanthera/bugtracker#682]
Hi Developers,

I have a problem I have tried this in Mojave and Catalina but both macOS the result is same. the issue is when I use Bootcamp to install Windows 10 it starts and complete the installation in macOS. but when it restarts some how BOOT folder DELETES from EFI folder which render non bootable and system goes into BIOS setup screen. OC folder remains intact.

Any help appreciated,

Thank you,

**Comment by nms42** [comment]
This is not support forum.
