### ISSUE TITLE
BrcmPatchRAM3 v2.5.1 Constant Sound Stuttering on macOS Catalina 10.15.2

### ISSUE THREAD

**Issue by DeveloperEN** [acidanthera/bugtracker#683]
Hi,
I and, as I see, many of the reddit users who use Lenovo 04x6020 are dealing with constant stuttering during a Bluetooth audio connection on macOS 10.15.2 with the latest version of BrcmPatchRAM3. At first, I thought it's because of BT4LEContinuity or simply because of my laptop's hardware but it seems like it affects other 04x6020 users, too. Please help me and the others.

**Comment by gongzhenjeef** [comment]
I have the same card and have similar issues with 2.4GHz. If possible, please connect to 5GHz wifi. Since there's no new firmware and BrcmPatchRAM3 is only a Bluetooth firmware uploader.

**Comment by headkaze** [comment]
This link
<https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html>
might be helpful.

**Comment by DeveloperEN** [comment]
@gongzhenjeef No use, even though I turn off the WiFi, stuttering still continues.
@headkaze I translated the website and did the following changes even though model numbers are slighty different, still no use.
BTW, the issue is %100 percent caused from either drivers or macOS Catalina itself, because there are no issues on macOS Mojave or Windows 10.
