### ISSUE TITLE
Slide value is not respected when IGPU is enabled on Gigabyte Z390 BIOS

### ISSUE THREAD

**Issue by soto2080** [acidanthera/bugtracker#684]
I read some hack builds on Github and some of them mention that the IGPU must set to disable to boot macOS when use OpenCore.
I am curious about what the " **IGPU MUST to be disabled**" mean, then I tried to build a OC config and find  something interesting.

It seems that all the **Gigabyte Z390** mobos need to use **slide=0** due to the memory layout of their BIOSes for Z390 platform.

Everything works fine on Clover about the kernel allocating(both when IGPU enabled or disabled). 
But the problem occurs when I use OpenCore to booting macOS.

When I use OpenCore with IGPU disabled in BIOS, the bootloader will respected to boot arguments, and allocating the kernel to the specify slide and boot correctly.
But when IGPU is enabled with the **identical OC build**, the kernel will be allocated to some non-allocatable areas.

I did a test then and found that OC **maybe** respected the boot arguments but got a **wrong address** from BIOS to allocating the kernel. When I try to boot with slide=0 and disabled IGPU in BIOS, macOS **always show the same address** cannot to be allocating(0x7be9000 in my case).

Memory Map here
Type       Start            End              # Pages          Attributes
Available  0000000000000000-000000000009EFFF 000000000000009F 000000000000000F
Reserved   000000000009F000-000000000009FFFF 0000000000000001 000000000000000F
Available  0000000000100000-000000001556FFFF 0000000000015470 000000000000000F
BS_Data    0000000015570000-00000000155AFFFF 0000000000000040 000000000000000F
Available  00000000155B0000-000000002B5C2FFF 0000000000016013 000000000000000F
LoaderCode 000000002B5C3000-000000002B6E7FFF 0000000000000125 000000000000000F
BS_Data    000000002B6E8000-000000002D430FFF 0000000000001D49 000000000000000F
ACPI_NVS   000000002D431000-000000002D431FFF 0000000000000001 000000000000000F
RT_Data    000000002D432000-000000002D432FFF 0000000000000001 800000000000000F
BS_Data    000000002D433000-000000002D55FFFF 000000000000012D 000000000000000F
Available  000000002D560000-000000002D56BFFF 000000000000000C 000000000000000F
LoaderCode 000000002D56C000-000000002D56EFFF 0000000000000003 000000000000000F
BS_Data    000000002D56F000-0000000037E0DFFF 000000000000A89F 000000000000000F
Available  0000000037E0E000-0000000037F29FFF 000000000000011C 000000000000000F
BS_Code    0000000037F2A000-000000003889EFFF 0000000000000975 000000000000000F
Reserved   000000003889F000-0000000038D1DFFF 000000000000047F 000000000000000F
Available  0000000038D1E000-0000000039133FFF 0000000000000416 000000000000000F
ACPI_NVS   0000000039134000-00000000392A5FFF 0000000000000172 000000000000000F
RT_Data    00000000392A6000-0000000039E4FFFF 0000000000000BAA 800000000000000F
RT_Code    0000000039E50000-0000000039EFEFFF 00000000000000AF 800000000000000F
BS_Data    0000000039EFF000-0000000039EFFFFF 0000000000000001 000000000000000F
Available  0000000100000000-00000010BE7FFFFF 0000000000FBE800 000000000000000F
Reserved   00000000000A0000-00000000000FFFFF 0000000000000060 0000000000000000
Reserved   0000000039F00000-0000000039FFFFFF 0000000000000100 000000000000000F
Reserved   000000003A000000-000000003F7FFFFF 0000000000005800 0000000000000000
MMIO       00000000E0000000-00000000EFFFFFFF 0000000000010000 800000000000100D
MMIO       00000000FE000000-00000000FE010FFF 0000000000000011 8000000000000001
MMIO       00000000FEC00000-00000000FEC00FFF 0000000000000001 8000000000000001
MMIO       00000000FEE00000-00000000FEE00FFF 0000000000000001 8000000000000001
MMIO       00000000FF000000-00000000FFFFFFFF 0000000000001000 800000000000100D
 
  Reserved  :         24,032 Pages (98,435,072 Bytes)
  LoaderCode:            296 Pages (1,212,416 Bytes)
  LoaderData:              0 Pages (0 Bytes)
  BS_Code   :          2,421 Pages (9,916,416 Bytes)
  BS_Data   :         51,030 Pages (209,018,880 Bytes)
  RT_Code   :            175 Pages (716,800 Bytes)
  RT_Data   :          2,987 Pages (12,234,752 Bytes)
  ACPI_Recl :              0 Pages (0 Bytes)
  ACPI_NVS  :            371 Pages (1,519,616 Bytes)
  MMIO      :         69,651 Pages (285,290,496 Bytes)
  MMIO_Port :              0 Pages (0 Bytes)
  PalCode   :              0 Pages (0 Bytes)
  Available :     16,687,712 Pages (68,352,868,352 Bytes)
  Persistent:              0 Pages (0 Bytes)
              -------------- 
Total Memory:         65,410 MB (68,587,487,232 Bytes)

**Comment by vit9696** [comment]
On Z390 boards we can test this on we do not need to set slide=0 or disable IGPUs. We are aware of some people having to do this, but do not have any update or fix. Patches and technical exploration are welcome.

**Comment by vit9696** [comment]
Could you please attach your config.plist file for OpenCore 0.5.5 from master?

**Comment by soto2080** [comment]
Here you go.
[Config.plist.zip](https://github.com/acidanthera/bugtracker/files/4116881/Config.plist.zip)

P.S.1
I found the value I mentioned before changed from 0x7be9000 to 0x7a11000 without an idea.

P.S.2
If I don't have a false memory, csr-acvitve-config still manually set to disable slide check via CSR_ALLOW_UNRESTRICTED_NVRAM in 0.5.3(.4 not tested) otherwise kernel will cry about it.
No idea why GetVariableCsrActiveConfig was not working properly.

**Comment by vit9696** [comment]
You have DevirtualiseMmio disabled, I do not think any Z390 works without it.

**Comment by soto2080** [comment]
But it actually boots fine both with and without DevirtualiseMmio when I build the config.

**Comment by soto2080** [comment]
It seems not the problem I think.
It can boot with DevirtualiseMmio both enabled or disabled at least on Gigabyte Z390.
But I still try it, DevirtualiseMmio enabled and IGPU enable not work still.
When DevirtualiseMmio enabled and IGPU disable, I did not notice any difference compare to DevirtualiseMmio disabled

**Comment by soto2080** [comment]
@vit9696  I compare the logs from OC and find that LoadHandle differs in different situation.
When the location of LoadHandle is start with 3, it will boot fine. 
When the location of LoadHandle is start with 2, kernel allocation will fail. 
I don't know is it just side effect or not.

**Comment by soto2080** [comment]
@vit9696 
The 10.15.3 updating progress gave a surprise.
I don't know how to reproduce it but the same bios setting and config booted.
BTW it may also hang at PCIE configuration end, then booted fine next time.

But I lost the ability after a ram overclock triggered BIOS training.

Someone at Tonymac also found that, I don't know if he will lost it after BIOS retraining.

**Comment by AGluk** [comment]
Hi Guys!

Can fully confirm absolutely the same error on my **Z390 AORUS Elite** mobo!

I've passed all tests with **slide=0** bootargs.

With iGPU is enabled I get the following error:
ERROR allocating 0x1198d pages at **0x000000000737d000** alloc type 2
Couldn't allocate runtime area

I've noticed that after the first automatic reboot after ERROR, memmap shows different mapping (see slide-0.txt). Next reboots by Alt+Ctrl+Delete show original mapping as during the first boot.

Notices:
- There are **372 MB** of free space in the second Available region is started at 0x100000.
- There are **351 MB** of free space in the third Available region is started at 0x175F3000.
- Disabling iGPU gives us additional **48 MB** in the second Available region (**420 MB** total).
- Failed boot followed by automatic reboot shows, that there are **258 MB** of LoaderData is located at **0x737D000** in the second Available region. We see the same address here as in ERROR above.

P.S. My config:

Gigabyte Z390 AORUS Elite
i9-9900K
Radeon VEGA64

iGPU - Enabled
DVMT Pre-Allocated - 32MB
DVMT Total Gfx Mem - 256M

[iGPU Disabled.txt](https://github.com/acidanthera/bugtracker/files/4170097/iGPU.Disabled.txt)
[iGPU Enabled.txt](https://github.com/acidanthera/bugtracker/files/4170098/iGPU.Enabled.txt)
[slide-0.txt](https://github.com/acidanthera/bugtracker/files/4170099/slide-0.txt)

**Comment by kmanj-pixel** [comment]
I can't get it to boot even with iGPU disabled on Gigabyte Z390 I Aorus Pro.

The installation has always fails at couldn't allocate runtime area:

`ERROR allocating 0x11964 pages at 0x0000000022c5c000 alloc type 2 Couldn't allocate runtime area`

I've tried on both OC 0.53 and 0.55 now, trying all permutations of bios settings (including F7 and F8c bios revisions of my board), iGPU disabled, disabling everything on the board (SATA ports, wifi, LED), playing around with all the relevant OC quirks.

Here's my current EFI folder: https://github.com/kmanj-pixel/hackintosh/tree/master/EFI

Here's my memory map: https://pastebin.com/cYb80aeD

One thing I don't understand: my slide value of 89 should be placing the kernel (? I assume that's what the memory is being allocated for) at 0x000000000B221000 which has 0x1607A pages available, which is more than 0x11964. But why is it trying to allocate at a different address? Is my slide value not getting passed through? Same issue?

**Comment by AGluk** [comment]
@kmanj-pixel 
> Here's my current EFI folder: https://github.com/kmanj-pixel/hackintosh/tree/master/EFI

As I see **ProvideCustomSlide** is **false**, but should be **true**.
My tests show that **ShrinkMemoryMap** is not needed.
**DevirtualiseMmio** also changes nothing in the memory map.
**ConsoleControl** protocol is advised in many sources.

> One thing I don't understand: my slide value of 89 should be placing the kernel at 0x000000000B221000.

it should place the kernel at **0x000000000B300000** (0x100000 + 0x59 * 0x200000)

**Comment by yooouuri** [comment]
Gigabyte Z390 UD user overhere.

After many many many many "Could not allocate runtime area" errors...

Change Total Gfx Mem to something, for me it does not really matter what.

Set DVMT Pre-allocated to 32M, **this did the trick!!!!** Setting it to something else than 32M gives me the _Could not allocate runtime area_ error...

Also had to set slide=0 to get it to boot...

![](https://www.insanelymac.com/forum/uploads/monthly_2020_01/IMG_3036.jpg.abcfa9da15d4847fb83e4e98f5d111dd.jpg)

**Comment by AGluk** [comment]
> Set DVMT Pre-allocated to **32M**, did the trick!!!!

Doesn't help on **Gigabyte Z390 AORUS Elite**. I've always set **32MB** value for **DVMT Pre-Allocated**.

> Change Total Gfx Mem to something, for me it does not really matter what

Not fully understand what you meant. Tried to set it to **128MB** and **Max**. Nothing helped.

Thank you!

**Comment by AGluk** [comment]
Still the same problem with 0.5.6 bootloader :(

**Comment by JosephDuffy** [comment]
I have a Gigabyte Aorus Pro WiFi and have run in to similar issues before. The fix has always been a CMOS reset (remove CMOS battery for a few minutes) and then re-setup BIOS/remove CFG Lock.

It will break again at some point, although I don't know excatly what causes the break.

**Comment by vit9696** [comment]
Recently added `ProtectUefiServices` quirk in combination with 
`DevirtualiseMmio` may resolve this problem. To ensure that `ProtectUefiServices` was applicable to your firmware search for `OCABC: Recovering trashed GetMemoryMap pointer` message in the log.

**Comment by AGluk** [comment]
Dear vit9696,

> Recently added `ProtectUefiServices` quirk

I couldn't find any mentions of this quirk in the **Sample.plist** and in the **User's Guide**.
Should it be located under UEFI -> Quirks?

Thank you!

**Comment by AGluk** [comment]
Dear @vit9696,

I've found the location **ProtectUefiServices** quirk in **0.5.7** OpenCore Pre-release build by @williambj1.
It looks like **ProtectUefiServices** quirk in combination with **DevirtualiseMmio** solves the problem. Now I'm able to boot with iGPU enabled!

**Comment by vit9696** [comment]
Good, closing as resolved.

**Comment by startergo** [comment]
> Recently added `ProtectUefiServices` quirk in combination with
> `DevirtualiseMmio` may resolve this problem. To ensure that `ProtectUefiServices` was applicable to your firmware search for `OCABC: Recovering trashed GetMemoryMap pointer` message in the log.

On MacBookPro11,2 I got this message 2 times. What is the meaning?
[opencore-2021-01-17-183427.txt.zip](https://github.com/acidanthera/bugtracker/files/5826627/opencore-2021-01-17-183427.txt.zip)

**Comment by vit9696** [comment]
Literally what it says? The firmware reverted GetMemoryMap pointer from our patch.
