### ISSUE TITLE
GENERAL: like to add documentation about kext building and installing

### ISSUE THREAD

**Issue by nuche** [acidanthera/bugtracker#686]
I'd like to go through all `acidanthera` projects that involve kext building and add instructions for building them from the shell and Xcode so that whichever the user/developer's preference might be they can have these handy. Are there some already existent instructions on any of the projects (that I'm missing) that I could base these new instructions off of in order to help contribute here in this regard?

I feel that this could reduce some questions and lower the bar for getting involved in contributions if it were simply more efficient to begin building and working with things via direct instructions on the READMEs.

**Comment by vandroiy2013** [comment]
Hi
For users there is prebuild binaries every month. 
As for developers they will figure out how to build projects without specific instructions.

**Comment by 07151129** [comment]
The bar for contribution is set by understanding the Apple proprietary software stack, which is much more involved than building an open source project with almost no dependencies.
