### ISSUE TITLE
BCM94352Z NGFF M.2 WIFI 3 minutes boot up time with Catalina

### ISSUE THREAD

**Issue by 29satnam** [acidanthera/bugtracker#687]
Hello! 
I bought this[ DW1560 Card off Aliexpress](https://www.aliexpress.com/item/WiFi-Wireless-Network-Card-BCM94352Z-NGFF-M-2-Wifi-Bluetooth-4-0-06XRYC-DW1560-802-11AC/32810080278.html?spm=a2g0s.9042311.0.0.14b74c4dUhR2Ql).
It was working just fine with Mojave and older versions, but **with Catalina Wifi takes 3 minutes to bootup**. And on the other hand BT is just fine.

I tried the new BrcmPatchRAM3, doesn't make any difference.

Here's detail from Hackintool:
VID: 14E4 
DID: 43B1 
SVID: 106B 
SDID: 0019 
Vendor Name: Broadcom Inc. and subsidiaries 
Device Name: BCM4352 802.11ac Wireless Network Adapter
Class Name: Network controller   
SubClass Name: Network controller    
IOReg Name: PCI0.ARP0.ARPT 
IOReg IOName: pci14e4,43b1    
Device Path: PciRoot(0x0)/Pci(0x1c,0x5)/Pci(0x0,0x0)

**Comment by vandroiy2013** [comment]
Hi
This is not a support forum.
