### ISSUE TITLE
Opencore boots to Recovery every time

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#688]
With the latest commits upon blessing OC reboots to Recovery partition (through OC):

```
sudo bless --mount /Volumes/EFI --setBoot --file /Volumes/EFI/EFI/OC/OpenCore.efi  --verbose

```

If I select startup disk from Recovery it respects the selection, but it reboots to the selected boot drive without OC. If I boot manually through the OC boot picker and later If I select the boot drive from the startup disk utility it remembers the selection, but on reboot it bypasses the OC bootloader. 
If I bless:

```
sudo bless --mount /Volumes/EFI --setBoot --file /Volumes/EFI/EFI/BOOT/BOOTx64.efi --verbose

```

or 

```
sudo bless --mount /Volumes/EFI --setBoot 

```
It boots to unknown operating system (question mark + folder blinking)

**Comment by vit9696** [comment]
- Nothing changed on that part.
- blessing `/Volumes/EFI/EFI/OC/OpenCore.efi` is not valid
- default boot entry choice in OC depends on NVRAM, which we believe works correctly. So far none of your previous OpenCore boot logs had that incorrect, and this issue contains no logs at all.

To summarise, you have something wrong in your setup, and the report does not contain enough technical info to make any sense of it. Closing as invalid.

**Comment by startergo** [comment]
I would like to provide bootlog, but when it boots to Recovery it does not create log. If I make manual selection through the bootpicker it boots normally. I tried using the bless override option but I could never get it working. Here is the config file.
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/4139464/config.plist.zip)

**Comment by startergo** [comment]
[opencore-2020-01-31-045636.txt](https://github.com/acidanthera/bugtracker/files/4139583/opencore-2020-01-31-045636.txt)
 
This is the last meaningful bootlog I could find.

**Comment by vit9696** [comment]
I think your last command is correct, but I personally do not know for sure as I saw different variants with `--file` and `--folder`. There is a key point of executing this command when booting **without** OpenCore. If you boot with OpenCore and execute this command, you will basically make OpenCore boot OpenCore, and this is not valid. I think this is pretty obvious, but just in case.

We believe the easiest way to make OpenCore the default entry should be to boot to Mac BootPicker (by holding OPT), choose OpenCore entry (it should be a yellow/orange icon) and press CTRL+Enter.

If you do not have a log when booting to any place, it means that you boot without OpenCore.

**Comment by vit9696** [comment]
Regarding your log, I do not know why you added `NvmExpressDxe` driver. It will not replace your Mac driver if added that way, so is basically useless. In BootOrder you have OpenCore blessed in OpenCore. This makes no sense to me:

```
216:472 00:168 OCB: 0 -> Boot0080 = PciRoot(0x0)/Pci(0x1D,0x7)/USB(0x0,0x0)/HD(1,GPT,74ED13D5-6F51-4204-A8CF-21CCA5D38A6B,0x28,0x64000)/\EFI\OC\OpenCore.efi
```

**Comment by startergo** [comment]
I am really confused as we always blessed the same way. It is on the first page of the thread where the FAQ are. But now it looks we have been doing it wrong. What is funny is if I  manually  select OC through boot picker the default startup selection is already marked, but if I reboot automatically it takes me to recovery instead. "--file (bottx64.efi) and --folder (EFI)" For some reason takes me to blinking folder with a question mark (no boot loader). I removed the NvmExpressDxe but it still does the same thing.

**Comment by vit9696** [comment]
To give you a way to diagnose. Whenever you see `OCB: Initial default is 0, fallback` in OpenCore log, it means that you have **no adequate default option configured for OpenCore**. This means that your NVRAM `BootOrder` is either not set yet (possible after clearing NVRAM) or contains some junk. In this case the first discovered option will be used as a default, and it may be anything as the order is unspecified. I.e. it can be macOS, it can be Windows, it can be recovery, it can be some tool, literally whatever. 

_This should make a clear difference when OpenCore boots something incorrectly or when OpenCore does not know what to boot and just boots whatever is first by default._

The bless **command** you posted makes sense to me, but it does not make sense to **execute it from within OpenCore**. OpenCore creates its own isolated GUID namespace (bless namespace if you want) before booting the operating system when `RequestBootVarRouting` is `YES`. Therefore anything blessed when booted from inside OpenCore will not reach your firmware but will only reach OpenCore.

_This is used to let operating systems set their default boot options and be visible in OpenCore, and it also lets the firmware always boot to OpenCore, as its settings are unchanged._

**Comment by ctf0** [comment]
i have the same issue, using v0.6.4.

using `bootstrap.efi` always boot into recovery mode, i dont have bless or any out of the normal config.

@vit9696 could u plz tell me what is the difference between **`bootx64.efi`, `bootstrap.efi`, `opencore.efi`**

**Comment by startergo** [comment]
I started having that issue again with the latest commit. Now I use the "VMM" flag and Catalina boots properly. I did not investigate the log yet.

**Comment by ctf0** [comment]
@startergo what is `VMM` flag ?

**Comment by startergo** [comment]
> @startergo what is `VMM` flag ?

It is the "virtual Machine emulation" 
If you look at the .dist file for Catalina:

```

function InstallationCheck(prefix) {
	var boardIds = ['Mac-9AE82516C7C6B903','Mac-F221BEC8','Mac-031B6874CF7F642A','Mac-112818653D3AABFC','Mac-9394BDF4BF862EE7','Mac-AA95B1DDAB278B95','Mac-CAD6701F7CEA0921','Mac-50619A408DB004DA','Mac-7BA5B2D9E42DDD94','Mac-226CB3C6A851A671','Mac-CFF7D910A743CAAF','Mac-AFD8A9D944EA4843','Mac-27ADBB7B4CEE8E61','Mac-F305150B0C7DEEEF','Mac-35C1E88140C3E6CF','Mac-827FAC58A8FDFA22','Mac-77EB7D7DAF985301','Mac-6FEBD60817C77D8A','Mac-7BA5B2DFE22DDD8C','Mac-827FB448E656EC26','Mac-66E35819EE2D0D05','Mac-2E6FAB96566FE58C','Mac-031AEE4D24BFF0B1','Mac-00BE6ED71E35EB86','Mac-4B7AC7E43945597E','Mac-5A49A77366F81C72','Mac-63001698E7A34814','Mac-937CB26E2E02BB01','Mac-FFE5EF870D7BA81A','Mac-87DCB00F4AD77EEA','Mac-A61BADE1FDAD7B05','Mac-C6F71043CEAA02A6','Mac-4B682C642B45593E','Mac-BE0E8AC46FE800CC','Mac-90BE64C3CB5A9AEB','Mac-3CBD00234E554E41','Mac-66F35F19FE2A0D05','Mac-189A3D4F975D5FFC','Mac-B4831CEBD52A0C4C','Mac-E1008331FDC96864','Mac-FA842E06C61E91C5','Mac-81E3E92DD6088272','Mac-FC02E91DDD3FA6A4','Mac-06F11FD93F0323C5','Mac-06F11F11946D27C5','Mac-6F01561E16C75D06','Mac-F60DEB81FF30ACF6','Mac-473D31EABEB93F9B','Mac-0CFF9C7C2B63DF8D','Mac-1E7E29AD0135F9BC','Mac-9F18E312C5C2BF0B','Mac-E7203C0F68AA0004','Mac-65CE76090165799A','Mac-CF21D135A7D34AA6','Mac-F65AE981FFA204ED','Mac-112B0A653D3AAB9C','Mac-DB15BD556843C820','Mac-27AD2F918AE68F61','Mac-937A206F2EE63C01','Mac-77F17D7DA9285301','Mac-E43C1C25D4880AD6','Mac-BE088AF8C5EB4FA2','Mac-551B86E5744E2388','Mac-564FBA6031E5946A','Mac-A5C67F76ED83108C','Mac-B809C3757DA9BB8D','Mac-5F9802EFE386AA28','Mac-747B1AEFF11738BE','Mac-AF89B6D9451A490B','Mac-EE2EBD4B90B839A8','Mac-42FD25EABCABB274','Mac-7DF2A3B5E5D671ED','Mac-2BD1B31983FE1663','Mac-7DF21CB3ED6977E5','Mac-A369DDC4E67F1C45','Mac-35C5E08120C7EEAF','Mac-C3EC7CD22292981F','Mac-53FDB3D8DB8CA971',];
	var cpuFeatures = system.sysctl( 'machdep.cpu.features' );
	cpuFeatures=cpuFeatures.split(" ");
	for( var i = 0; i &lt; cpuFeatures.length; i++ ){
		if( cpuFeatures[i] == "VMM" ){
			return true;
		}

```
The installer is searching for certain board-id's and the "VMM" flag. It is defined in the Kernel/Emulate key:

```
<key>Emulate</key>
		<dict>
			<key>Cpuid1Data</key>
			<data>
			AAAAAAAAAAAAAACAAAAAAA==
			</data>
			<key>Cpuid1Mask</key>
			<data>
			AAAAAAAAAAAAAACAAAAAAA==
			</data>
```
This configuration emulates VMM flag.

This is the default:
```
<key>Emulate</key>
		<dict>
			<key>Cpuid1Data</key>
			<data>
			AAAAAAAAAAAAAACAAAAAAA==
			</data>
			<key>Cpuid1Mask</key>
			<data>
			AAAAAAAAAAAAAAAAAAAAAA==
			</data>
```
Anyway back to the topic. I think in my case it was the RestrictEvents.kext which was causing the booting to Recovery. I have upgraded the kext with the latest commit and now everything is fine.
