### ISSUE TITLE
[AppleALC] Does AppleALC support sound card that does not have intel HDA?

### ISSUE THREAD

**Issue by z7z8th** [acidanthera/bugtracker#689]
I have a Sound card ASUS Xonar D2X which uses a CMedia 8788 chip(CMI8788), on Linux Xonar D2X is recognized with the name CMI8788.   
It's data sheet is at the bottom of this site: https://www.cmedia.com.tw/support/download_center  
According the data sheet, seems there're I2S and AC97 support, but I can't find HD Audio related words.  
My guess is CMI8788 does not support intel HDA.  
Does AppleALC codecs other than intel HDA? I want to ask this before staring trying.  
Thank you for this great work.

**Comment by Andrey1970AppleLife** [comment]
Not support
