### ISSUE TITLE
AirportBrcmFixup 2.0.6 shows some "null" in system preference

### ISSUE THREAD

**Issue by gujiangjiang** [acidanthera/bugtracker#696]
Like this:
CoreWLAN:null
CoreWLANKit:null

<img width="751" alt="QQ20200203-230800@2x" src="https://user-images.githubusercontent.com/13273955/73664419-50c31b00-46da-11ea-9659-7606c07d6bc3.png">

**Comment by vit9696** [comment]
This is the same even without AirportBrcmFixup with native Apple Wi-Fi.
