### ISSUE TITLE
Transform RequireVault and RequireSignature

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#697]
Currently `RequireVault` and `RequireSignature` may be slightly counterintuitive, as they effectively control one preference — vaulting, but are separated in the configuration plist.

I believe we want to replace them both with another option, `Vault`, which should be string and allow 3 values: `None`, `Basic`, `Secure`. The value should default to `Secure` if an unknown value is provided.

`Secure` should translate to `RequireVault` = `YES` and `RequireSignature` = `YES` .
`Basic` should translate to `RequireVault` = `YES` and `RequireSignature` = `NO` .
`None` should translate to `RequireVault` = `NO` and `RequireSignature` = `NO` .

RequireVault and RequireSignature should be removed. Naming suggestions are welcome here, but I believe these should be good enough.

**Comment by Download-Fritz** [comment]
"None" does not quite nail it because the "Required" properties set to NO still causes usage of whatever is available, so it must be something like "Optional".

**Comment by vit9696** [comment]
Hmm, indeed, this sounds reasonable to me.

**Comment by vit9696** [comment]
https://github.com/acidanthera/OpenCorePkg/commit/73e6648e0bc3a72163fac33b3f4c3594fe6d8b95, implemented.
