### ISSUE TITLE
IOJones missing TreeLine

### ISSUE THREAD

**Issue by Sniki** [acidanthera/bugtracker#699]
IOJOnes is missing the TreeLines (if that's what is called). it would be better looking and easier to see where things come from by having lines that extended (IORegistryExplorer 2.1 example):
![IORegistryExplorer](https://user-images.githubusercontent.com/30008333/73772320-380d4080-4780-11ea-845b-95afa9dd878e.png)
IOJones doesn't have these (not on Dark and not even on Light mode):
![IOJones](https://user-images.githubusercontent.com/30008333/73772346-42c7d580-4780-11ea-8c7c-499923897dbd.png)

**Comment by vit9696** [comment]
I don't know why would anyone use IOJones these days, as latest IORegistryExplorer fully supports dark mode and does not crash. We can accept the patch if it is contributed, but IOJones is basically unmaintained.

**Comment by Sniki** [comment]
> I don't know why would anyone use IOJones these days, as latest IORegistryExplorer fully supports dark mode and does not crash. We can accept the patch if it is contributed, but IOJones is basically unmaintained.

If that's the case, it's all fine by me, i follow acidanthera on daily basis and i saw a new commit for IOJones, then it reminded me about this existing issue/missing graphical part.

Since it's unmaintained let it be like that.

I mostly still use IOreg 2.1 and works all fine, i just don't like the fact that it doesn't have an icon.

**Comment by vit9696** [comment]
You can set the icon by accessing properties of the app and then dropping an icon on it. That's how I did it for myself.

**Comment by Sniki** [comment]
> You can set the icon by accessing properties of the app and then dropping an icon on it. That's how I did it for myself.

Thanks for the tip @vit9696
