### ISSUE TITLE
VoodooPS2Controller keyboard fn keys

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#700]
Hi there,
I'm using a Dell Inspiron 5370 with Catalina 10.15.3. I have an issue with the brightness fn keys which seems laggy. If I press them the system overlay notification bar isn't smooth as for example with audio. BRT6 is the method which I've patched using the following guide:

https://noobsplanet.com/index.php?threads/brightness-keys-remapping-f11-and-f12-for-hackintosh.131/

If I use an external usb keyboard the brightness keys (which are mapped to F14 and F15) are working smooth. Is there any fix?

**Comment by vit9696** [comment]
From what I know there is a difference between native brightness keys and some mapping implemented with third-party utilities. I believe this works as intended.

**Comment by dreamwhite** [comment]
I've tried my best on DSDT and revealed the path of BRT6:

BRT6 => EV5 => SMEE => SMIE => NEVT => _Q66

I attach my DSDT.aml 
[DSDT.aml.zip](https://github.com/acidanthera/bugtracker/files/4225215/DSDT.aml.zip)
