### ISSUE TITLE
OCS: No schema for AvoidHighAlloc at 0 index!

### ISSUE THREAD

**Issue by kommtzeitkonrad** [acidanthera/bugtracker#704]
[AvoidHighAlloc is removed in commit 84aab1a](https://github.com/acidanthera/OpenCorePkg/commit/772d1014278de3ce18afc83cdec33cefe9c92640) but a warning about the missing config.plist entry is still displayed.

`BS: Starting OpenCore.,.`
`BS: Booter path - \EFI\BOOT\BOOTX64.EFI`
`0CF: Trying to locate filesystem on 1F40A118 1FA17998`
`0CF: FilesỤsten DP is \EFI\BOOT\BOOTX64.EFI`
`BS: Trying to start loaded OpenCore Image..`
`BS: Failed to locate bootstrap protocol- Not Found`
`BS: Trying to load OpenCore image. ..`
`BS: Read OpenCore image of 505098 bytes`
`BS: Loaded OpenCore image at 1F403D90 handle`
`OC: Starting OpenCore..`
`OC: Booter path - <mull string>`
`OC: Booted from bootstrap`
`OC: ReRun executed!`
`OC: OcMiscEarlyInit.`
`OC: Loaded configuration of 29023 bytes`
`OCS: No schema for AvoidHighAlloc at 0 index!`

**Comment by Andrey1970AppleLife** [comment]
Delete AvoidHighAlloc from config.plist

**Comment by kommtzeitkonrad** [comment]
Ⅰ thought Ⅰ deleted it. Sorry!

**Comment by authon** [comment]
> Ⅰ was thinking Ⅰ deleted it. Sorry!

hello，How did you solve it？This problem occurred after I upgraded opencore

**Comment by kommtzeitkonrad** [comment]
`OCS: No schema for …` debug messages [are generated](https://github.com/acidanthera/OpenCorePkg/blob/52d5f1486bfdd6a106e97a61a6848ac2f3df0d28/Library/OcSerializeLib/OcSerializeLib.c#L128) for entries in config.plist that are not used (anymore) in the OC version you are currently running. Compare your configuration with the [samples in Docs folder](https://github.com/acidanthera/OpenCorePkg/tree/master/Docs) or use [ocvalidate from Utilities folder](https://github.com/acidanthera/OpenCorePkg/tree/master/Utilities/ocvalidate).

**Comment by authon** [comment]
Thank you, I realized the problem was that I upgraded the debug version，I replaced the release version and solved it.
