### ISSUE TITLE
EncodePng function

### ISSUE THREAD

**Issue by n-d-k** [acidanthera/bugtracker#710]
If it's not too much trouble for OC team, can this function be added to OcPngLib?  Thanks!

**Comment by vit9696** [comment]
Sounds good to me, we can accept a patch if it is submitted. A dirty example can be found in https://github.com/LongSoft/CrScreenshotDxe.

**Comment by n-d-k** [comment]
Thanks! 

[EncodePng.patch.zip](https://github.com/acidanthera/bugtracker/files/4184535/EncodePng.patch.zip)

**Comment by Download-Fritz** [comment]
Pushed at https://github.com/acidanthera/OcSupportPkg/commit/f1a6b251dd6ace7a227bafeff937a83e33c49c21
I changed BitDepth to UINT8 (in conformance with the 1 byte field size in the PNG header) to avoid implicit UINTN -> unsigned truncation on assignment. I don't believe we should use UINTN for anything but for example buffer sizes.

Thanks!
