### ISSUE TITLE
Compiling error with recent commits!

### ISSUE THREAD

**Issue by n-d-k** [acidanthera/bugtracker#713]
Undefined symbols for architecture x86_64:
  "_memcpy", referenced from:
      _lodepng_color_mode_copy in OcPngLib.lib(lodepng.obj)
      _lodepng_info_copy in OcPngLib.lib(lodepng.obj)
      _filter in OcPngLib.lib(lodepng.obj)
ld: symbol(s) not found for architecture x86_64

**Comment by vit9696** [comment]
Resolved
