### ISSUE TITLE
ACPI not properly loaded without -v boot-arg

### ISSUE THREAD

**Issue by milouk** [acidanthera/bugtracker#714]
I know it sounds really strange and doesn't make much sense but i tested this many times and it checks out. When NOT having verbose (-v) as a boot-arg, when booting (at the first Apple Logo) my keyboard does NOT light up and i need to unplug and replug it. 

However, when enabling verbose in boot-args i can see in the logs that ACPI is properly supplying power to my USBs and the keyboard lights up as it should. 

Could it be a race condition of some sort? 

** i have been using OpenCore 0.5.5. Also i can provide my config.plist upon request and any other needed info.

**Comment by vit9696** [comment]
Yes, that is some race condition, for example, we had a similar issue with ASUS Z87 boards. I do not think there is a defined way to troubleshoot this, but first things to try are ExitBootServicesDelay, IgnoreInvalidFlexRatio, ReleaseUsbOwnership.

**Comment by milouk** [comment]
Thanks for the suggestions, gonna try them out tonight. 

Cheers and thanks for this amazing project.
