### ISSUE TITLE
WhateverGreen renames a wrong device to "IMEI"

### ISSUE THREAD

**Issue by Goshin** [acidanthera/bugtracker#716]
I noticed the renaming of `HECI to IMEI` embedded in WhateverGreen does not work on my laptop.
After I manually added a DSDT patch in Clover, it turns out there are two `IMEI` devices in ioreg. 

I find out that WhateverGreen wrongly renames a device named `UA00` to `IMEI`, instead of the `HECI`.

This is what `UA00` looks like in IORegistryExplorer and DSDT.dsl:
![Screen Shot 2020-02-13 at 11 40 18 PM](https://user-images.githubusercontent.com/10056397/74485154-672b5c80-4eba-11ea-8c97-bb6f12cef9b8.png)

<details>
  <summary>DSDT code, click to expand.</summary>

```acpi
    Scope (_SB.PCI0)
    {
        Device (UA00)
        {
            If (LNotEqual (SMD9, One))
            {
                Method (_HID, 0, NotSerialized)  // _HID: Hardware ID
                {
                    If (LEqual (SMD9, 0x03))
                    {
                        Return (0x020CD041)
                    }
                    Else
                    {
                        Return ("INT34B8")
                    }
                }

                Name (_UID, "SerialIoUart0")  // _UID: Unique ID
                Name (_DDN, "SerialIoUart0")  // _DDN: DOS Device Name
                Method (_HRV, 0, NotSerialized)  // _HRV: Hardware Revision
                {
                    Return (LHRV (SB19))
                }

                Method (_CRS, 0, NotSerialized)  // _CRS: Current Resource Settings
                {
                    Return (LCRS (SMD9, SB09, SIR9))
                }

                Method (_STA, 0, NotSerialized)  // _STA: Status
                {
                    Return (LSTA (SMD9))
                }
            }

            If (LEqual (SMD9, One))
            {
                Name (_ADR, 0x001E0000)  // _ADR: Address
                Method (_DSM, 4, Serialized)  // _DSM: Device-Specific Method
                {
                    If (PCIC (Arg0))
                    {
                        Return (PCID (Arg0, Arg1, Arg2, Arg3))
                    }

                    Return (Buffer (One)
                    {
                         0x00                                           
                    })
                }
            }

            If (LNotEqual (SMD9, 0x03))
            {
                Method (_PSC, 0, NotSerialized)  // _PSC: Power State Current
                {
                    Return (GETD (SB19))
                }

                Method (_PS0, 0, NotSerialized)  // _PS0: Power State 0
                {
                    LPD0 (SB19)
                }

                Method (_PS3, 0, NotSerialized)  // _PS3: Power State 3
                {
                    LPD3 (SB19, SMD9)
                }
            }
        }
    }
```

</details>

and this is what `HECI` looks like:
![Screen Shot 2020-02-13 at 11 42 37 PM](https://user-images.githubusercontent.com/10056397/74485265-a5288080-4eba-11ea-961e-5cff1962ff4e.png)

<details>
  <summary>DSDT code, click to expand.</summary>

```
    Scope (_SB.PCI0)
    {
        Device (HECI)
        {
            Name (_ADR, 0x00160000)  // _ADR: Address
            Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
            {
                If (PCIC (Arg0))
                {
                    Return (PCID (Arg0, Arg1, Arg2, Arg3))
                }

                If (CondRefOf (HIWC))
                {
                    If (HIWC (Arg0))
                    {
                        If (CondRefOf (HIDW))
                        {
                            Return (HIDW (Arg0, Arg1, Arg2, Arg3))
                        }
                    }
                }

                Return (Buffer (One)
                {
                     0x00                                           
                })
            }
        }
    }
```

</details>

---

However, It is actually Lilu that finds the wrong device to rename,
in https://github.com/acidanthera/Lilu/blob/master/Lilu/Sources/kern_devinfo.cpp#L252
```cpp
} else if (vendor == WIOKit::VendorID::Intel && (code == WIOKit::ClassCode::IMEI || (name && (!strcmp(name, "IMEI") || !strcmp(name, "HECI") || !strcmp(name, "MEI"))))) {
    // Fortunately IMEI is always made by Intel
    DBGLOG("dev", "found IMEI device %s", safeString(name));
    managementEngine = obj;
}
```

So in this case, both `HECI` and `UA00` match the condition `vendor == WIOKit::VendorID::Intel && code == WIOKit::ClassCode::IMEI`, and `UA00` just wins as it shows up later in the loop.

I was wondering, perhaps it should be an `&&` rather than `||` between `code == WIOKit::ClassCode::IMEI` and `(name`? 
https://github.com/Goshin/Lilu/commit/386ce487c4657c7705a28992c773392aa3917687

though I don't figure out what the `HECI` is for and why it has the class code of `ClassCode::IMEI`.

**Comment by vit9696** [comment]
HECI and IMEI mean the same thing — an interface to Management Engine. Basically HECI is the name of IMEI (Intel Management Engine Interface) implementation. UA00 seems to be UART and it is not related to any of them. Class code is not really documented for IMEI, but some firmwares have nothing but the class code, so we have to use it too when the name is unavailable. Fixed in master.

**Comment by Goshin** [comment]
It was a typo. I actually didn't know what the UA00 is about. Anyway, thank you for your explanation.
