### ISSUE TITLE
F10 key

### ISSUE THREAD

**Issue by n-d-k** [acidanthera/bugtracker#725]
I just released the external GUI picker for the Official OC build, There's a ScreenShot function in the menu that required OC_INPUT_F10.  It will be great if OC team can add it.  Thanks!

**Comment by vit9696** [comment]
Hmm, why particularly F10? Maybe we rather all want F keys? In this case how about using -1 ~ -15 (?) for F1 ~ F15? We can start other keys with e.g. -32 or so to ensure range separation…

**Comment by Andrey1970AppleLife** [comment]
@n-d-k, your GUI picker changes functionality of the official OpenCore.
That is AllowSetDefault=No, HideAuxiliary=Yes and Auxiliary=Yes don't work correctly.
My opinion, external GUI picker, has to add only graphics, but not change functionality of the official OpenCore.

**Comment by n-d-k** [comment]
> @n-d-k, your GUI picker changes functionality of the official OpenCore.
> That is AllowSetDefault=No, HideAuxiliary=Yes and Auxiliary=Yes don't work correctly.
> My opinion, external GUI picker, has to add only graphics, but not change functionality of the official OpenCore.

Ok, I'll make adjustment and take a look at why Auxiliary=Yes doesn't work correctly. 

About the F10 key,  Any key will do, as long as it's on the 81 keyboard type.

**Comment by vit9696** [comment]
@Andrey1970AppleLife this is a bit out of the scope of this issue, and with the way the current OpenCore is built it allows GUIs to make some of these alterations.

@n-d-k personally I would though partially agree with Andrey's comment, especially the AllowSetDefault and HideAuxiliary parts. These things are currently configurable in OpenCore, so there is little reason to hardcode them.

> About the F10 key, Any key will do, as long as it's on the 81 keyboard type.

I checked IndustryStandard/UsbHid.h, and it seems to allow encoding F keys from UsbHidUsageIdKbKpKeyF1 to UsbHidUsageIdKbKpKeyF24. In this case would you be so kind to contribute us a patch with:

```C
#define OC_INPUT_FUNCTIONAL(X) (0 - (X))
```

**Comment by n-d-k** [comment]
Since,  This External GUI is dedicated to the Official OC, I will make adjustment to make it behave just like the text version.  Though, I think all other entries beside the main OSes should be hidden until Spacebar is pressed.

And one more thing I like to ask is InternalSystemActionResetNvram function is current internal and can't be accessed via external. Users will lose the resetNvram hotkey if using external picker. Can this function be not internal?

**Comment by vit9696** [comment]
> Since, This External GUI is dedicated to the Official OC, I will make adjustment to make it behave just like the text version. Though, I think all other entries beside the main OSes should be hidden until Spacebar is pressed.

With `HideAuxiliary` enabled in config.plist it is exactly this way. Perhaps you missed something?

> And one more thing I like to ask is InternalSystemActionResetNvram function is current internal and can't be accessed via external. Users will lose the resetNvram hotkey if using external picker. Can this function be not internal?

Well, it is rather tiny, could send us a patch to make it external, but to be honest I think you can just copy-paste three lines in your UI:

```C
EFI_STATUS
InternalSystemActionResetNvram (
  VOID
  )
{
  OcDeleteVariables ();
  DirectRestCold ();
  return EFI_DEVICE_ERROR;
}
```

**Comment by n-d-k** [comment]
Oh..that was ez..:). thanks ! And here's the screen snapshot hotkey patch
[ScreenShot_F10key.patch.zip](https://github.com/acidanthera/bugtracker/files/4217265/ScreenShot_F10key.patch.zip)

**Comment by vit9696** [comment]
Mhm, I do not think you understood me, implemented it myself though.

**Comment by n-d-k** [comment]
UsbHidUsageIdKbKpKeyF1 this doesn't work for me, but this AppleHidUsbKbUsageKeyF1 does..

**Comment by vit9696** [comment]
Ah, looks like there are typos, mind submitting a fix?

**Comment by n-d-k** [comment]
ok, i'll send a patch

**Comment by n-d-k** [comment]
[TypoFix.patch.zip](https://github.com/acidanthera/bugtracker/files/4218436/TypoFix.patch.zip)

**Comment by Andrey1970AppleLife** [comment]
I see that you in the Icons folder have Background.png
But background in the menu the simply black. Why doesn't show Background.png ?

**Comment by Andrey1970AppleLife** [comment]
In first start Shell - not cleaning screen.

**Comment by Download-Fritz** [comment]
@n-d-k pushed at https://github.com/acidanthera/OcSupportPkg/commit/b3662e8a3d7c8f72bc151b9f0326e1e44ef07dba
Thanks!

**Comment by n-d-k** [comment]
> @n-d-k
> In start Shell - not cleaning screen.
> 
> ![IMG_0478](https://user-images.githubusercontent.com/17758753/74751498-627df400-527e-11ea-9722-0eae032da2e7.jpeg)

Fixed! v0.0.3

**Comment by Andrey1970AppleLife** [comment]
@n-d-k, cleaning in Shell works now.

PickerAttributes It is broken.
You break OpenCore code for foreground and background colors.
I don't see result PickerAttributes in Shell.

**Comment by n-d-k** [comment]
I think, the app should have its own initialization code, since we don't know which type of app user is gonna pick either text/or graphic console and this GUI picker only use graphic mode and not touching the any text mode console setting at all. I can still able to add line of code to set  the  PickerAttributes to the  user setting.

**Comment by Andrey1970AppleLife** [comment]
@n-d-k, in v0.0.4 not fixed this issue.

**Comment by n-d-k** [comment]
Color attributes should be set by the shell app itself. It's not the exit app job. I think,  once the Console mode was switched from text to graphic or vice versa, the color has to be set again.

**Comment by n-d-k** [comment]
Ok, since the Shell app doesn't have access to OC context, will set the color attribute on this side. v0.0.5 should do it.

**Comment by vit9696** [comment]
@n-d-k we think that applications should normally start in graphics mode, and that should already be handled by OcStartImage through OcLoadBootEntry. Therefore there should be little need to switch back to text mode, previous mode makes more sense, but essentially you can skip this too. Setting text attributes should normally work fine in graphics mode if that was the concern.

In general the idea was that attributes affect picker and subsequent software, so we indeed kind of expect the colours to be changed if the picker is used. If you disagree, I think we could discuss this (cc @Download-Fritz). Other than that, bits excepts lower 8 bits could be picker-defined and used as custom preferences for external UIs.

**Comment by Andrey1970AppleLife** [comment]
> Ok, since the Shell app doesn't have access to OC context, will set the color attribute on this side. v0.0.5 should do it.
Yes now it works in Shell.

**Comment by Andrey1970AppleLife** [comment]
@n-d-k 
Acer v3-571g, Ivy Bridge, BIOS Insyde.
All entries don't show space in menu.
Examples:
![ScreenShot-2020-02-20-224357](https://user-images.githubusercontent.com/17758753/74990075-51d2a700-5453-11ea-8762-fc4cb41c7873.jpeg)
![ScreenShot-2020-02-20-224804](https://user-images.githubusercontent.com/17758753/74990083-54cd9780-5453-11ea-8256-ca6815a98f6d.jpeg)

Builtin - no bug.
![IMG_0479](https://user-images.githubusercontent.com/17758753/74990185-a83fe580-5453-11ea-81cb-9eef1a182b8f.jpeg)

**Comment by n-d-k** [comment]
Hmm, This seems to be compatibility issue between HiiFont and Acer Bios. Currently texts to image are handled by HiiFont protocol, which is out of my control, The only way to fix this is stop using HiiFont protocol. I may have to add more code to to replace this protocol.
