### ISSUE TITLE
VirtualSMC, SmcBatteryManager tells battery needs to be replaced

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#727]
![IMG_20200219_100505_920](https://user-images.githubusercontent.com/17933708/74818714-6e5dca80-52ff-11ea-845a-4ab72aa0cf74.jpg)

As in this screenshot if I use ACPIBatteryManager.kext I don't have any warning about my battery health. But when I use SMCBatteryManager it says "Battery needs to be replaced". What can it be? Is there a workaround?

**Comment by vit9696** [comment]
I do not see any warning on the screenshot. If anything, screenshot is not a bugreport. Please provide debug logs for SMCBatterManager (-sbatdbg) both through liludump and log command.

**Comment by dreamwhite** [comment]
![image](https://user-images.githubusercontent.com/17933708/74823804-9c470d00-5307-11ea-8504-fa87aad582b4.png)

Sorry, this is the ccurrent screenshot. I'll send yo -sbatdbg through liludump and log

**Comment by vit9696** [comment]
Right, will reopen as we get the logs.

**Comment by dreamwhite** [comment]
I'm sorry vit9696, but how can i get the liludump? using hackintool? is the same?

**Comment by vit9696** [comment]
Check Lilu readme. It is liludump=TIMEOUT with -liludbgall boot argument. It will create a log file in /var/log after the timeout (in seconds) is over after boot time.

**Comment by dreamwhite** [comment]
Okay thank you so much. so the boot args will be:


liludump=300
-liludbgall

right?

Then i'll find a log file inside /var/log

**Comment by vit9696** [comment]
Correct. Just in case, debug kexts of Lilu and SMCBatteryManager are required for this. For log you can use `log show --last boot` and save this output to a file.

**Comment by dreamwhite** [comment]
[Lilu_1.4.1_19.4.txt](https://github.com/acidanthera/bugtracker/files/4224540/Lilu_1.4.1_19.4.txt)

Here you are my log

**Comment by usr-sse2** [comment]
What does System Profiler display in Hardware→Power?

**Comment by dreamwhite** [comment]
![image](https://user-images.githubusercontent.com/17933708/74837035-e688b800-5320-11ea-837a-32f3da0e2e09.png)

**Comment by Andrey1970AppleLife** [comment]
Your battery has lost the capacity, the offer to replace - is true.

**Comment by dreamwhite** [comment]
Mmmmmmmh, maybe. So i don't need any patch on my DSDT right?

**Comment by Andrey1970AppleLife** [comment]
Replace battery.
