### ISSUE TITLE
Scan only default drive when ShowPicker is disabled

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#728]
On MacPro5,1 we have a server chipset with very old hardware. As a result, this machine boots very slowly in the first place due to RAM test but in addition to that we have slow disks too.

To workaround this as suggested by @Download-Fritz  we should change scanning for the operating system to only work against the primary disk as prescribed by BootOrder as long as it works when ShowPicker is disabled.

I include an example below, but just to be clear, reaching OpenCore picker since boot chime may easily take 50 seconds with slow enough drives installed, e.g. USB.

##### Example

- Windows on a SATA SSD, connected to an onboard SATA II port.​
- macOS on a SATA SSD, connected to a SATA III PCIe card.​​
- Four other HDD installed via the onboard SATA II ports. Two of them have macOS installed.​
- Latest OC 0.5.6 release version.​
​- No log, Target set to 0​

**Cold boot**:

- 18s from power on to boot chime​
- 9s from chime to OC boot picker​
​
Total 27 seconds​
​
**Restart**:

- 14s from power on to boot chime​
​- 12s from chime to boot picker​
​
Total 26 seconds​

**Windows**: (Clean installation few days ago)

- 16s from OC boot picker to login page​
​
**macOS Mojave**: (daily use, update from older OS for years)

- 26s from OC boot picker to desktop​

**Comment by telepati** [comment]
My boot time is extremely increased. I always booted in 23 sec. I didn't make or play anything on my config.plist or kexts. I tried NVMeFix.kext but didn't help. But now I am booting 41 sec between 49 sec. Cleaned NVRAM, reinstalled all system, Reset kexts, nothing of them helped. Could you please tell me, why boot time increased? Here is my debug report;

[opencore-2020-03-19-165747.txt](https://github.com/acidanthera/bugtracker/files/4355912/opencore-2020-03-19-165747.txt)

**Comment by vit9696** [comment]
OpenCore boots in 2 seconds, it has something to do with macOS and is unrelated to this issue. I could suggest you to check your filesystem, but in any case it is not a problem with OC.

**Comment by vit9696** [comment]
That was fixed in 0.5.9. We can still improve that by not `connecting` non-default drives in the first place, but I do not think we can win much with this.
