### ISSUE TITLE
Create utility to disable FwRuntimeServices restrictions

### ISSUE THREAD

**Issue by chrome723** [acidanthera/bugtracker#731]
Hi. To edit hidden BIOS settings, I use RU.efi. If I run the program through shell.efi using OC then there are no UEFI variables 
![Снимок экрана 2020-02-19 в 18 19 36](https://user-images.githubusercontent.com/50671251/74961165-71f06f00-542f-11ea-9278-e70e9c73ef84.png)
![IMG_20200219_175241](https://user-images.githubusercontent.com/50671251/74961181-774db980-542f-11ea-8ce3-3743e135341a.jpg)
![IMG_20200219_175205](https://user-images.githubusercontent.com/50671251/74961186-79b01380-542f-11ea-9d78-d02b56dbc7cc.jpg)

**Comment by vit9696** [comment]
Need a tool to disable/enable FwRuntimeServices via an argument, similarly to how we do it with [CleanNvram](https://github.com/acidanthera/OcSupportPkg/blob/65909a9/Library/OcBootManagementLib/VariableManagement.c#L228).
