### ISSUE TITLE
Kext list

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#733]
We will recommend these kexts?
https://github.com/AppleIntelWifi/adapter
https://github.com/zxystd/IntelBluetoothFirmware
https://www.insanelymac.com/forum/topic/342214-anyappleusbmouse-for-catalina-1015/
https://github.com/trulyspinach/SMCAMDProcessor

**Comment by vit9696** [comment]
I do not think "recommend" is the right word for this, as we only list things without warranties. But anyway:

- https://github.com/IOIIIO/MacProMemoryNotificationDisabler — this goes to KnownPlugins.md in Lilu and full kext list. I know that it may crash, and requested a fix from the develop. Actually the same bug exists in SystemMemoryProfiler, just it does not trigger that often. Reported too.
- AppleIntelWifiAdapter — for now just the full kext list, and keep an eye on it.
- IntelBluetoothFirmware — full and short kext lists.
- SMCAMDProcessor — create KnownPlugins in VirtualSMC, add this one and AsusSMC there. Also full list.

**Comment by 07151129** [comment]
We should include a no-warranty disclaimer (especially for third-party software), clarify we are not affiliated with the authors and do not provide any support.

**Comment by vit9696** [comment]
Actually I agree. Add something like "Acidanthera members are not affiliated with the authors of any kernel extensions but ones hosted at https://github.com/acidanthera. This list is provided for information purposes without warranty of any kind."

Also, for VirtualSMC plugins we will need a document entry in https://github.com/acidanthera/bugtracker/blob/master/DOCUMENTS.md. Choose the subsequent number.

**Comment by vit9696** [comment]
We also need to add SmallTreeIntel82576.kext for newer Intel LAN. It can be found on https://small-tree.com/. Khronokernel also,has it uploaded: https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/blob/474d6ca64341b18bff7cdb684252138a36e1671a/extras/hardware.md#networking, but I wonder what the version is.

**Comment by khronokernel** [comment]
The kext hosted in the guide is actually a patched one where it replaces the I210(8086:1533) for the I211-AT(8086:1539), it's version is 1.0.6 though theoretically the 1.2.6 version from SmallTree's site could be patched and used as well(1.0.6 has been serving us well so didn't see a need to update). The one hosted is originally from AMD OSX's guide, I just added some clarification to the guide just to be safe

**Comment by vit9696** [comment]
Is it binary patched or is Info.plist modified? If the latter, you could leave the kext unchanged, and just have a plist-only kext to inject new IDs. This will permit updating without breaking code signature. And yes, I believe we should update it to the latest.

**Comment by khronokernel** [comment]
It does need a binary patch unfortunately, though I'll update it to 1.2.6 and test with some users to see how well it works

**Comment by khronokernel** [comment]
Patched the most recent binary(1.2.5) and working well: [SmallTree-I211-AT-patch](https://github.com/khronokernel/SmallTree-I211-AT-patch)

**Comment by vit9696** [comment]
Nice, thank you. You can add .DS_Store to .gitignore to avoid accidentally adding this file to the repository, by the way.

@Andrey1970AppleLife I believe we can link to that repository.

**Comment by vit9696** [comment]
@khronokernel, by the way, as [khronokernel-1](https://khronokernel-1.gitbook.io) gitbook is no longer used, could you list the links to other guides there? While we are not too happy with all the information in the guides and in fact try to report issues as soon as we notice something bad, these guides are quite useful for the end users and it is a bit hard to remember where is what given these links. Thx.

**Comment by khronokernel** [comment]
@vit9696 I like the idea, I just changed the repo associated with the site to [OC-Start](https://github.com/khronokernel/OC-Start). I mainly added a couple of the guides but if you have any recommendations on sections and such I'd love to hear them, though maybe open an issue in the repo as I don't want to sidetrack this thread
