### ISSUE TITLE
VoodooPS2Keyboard does not work at login screen

### ISSUE THREAD

**Issue by lersy** [acidanthera/bugtracker#734]
Hey guys,

I've been using VoodooPS2Controller for a long time and I have had this issue for a long time as well.

Problem is that when laptop boots and comes to login screen I can't type my password. I have to restart it again and again sometimes up to 6 times then it works. I have this problem randomly and it is like gambling for me.

I put latest voodoops2controller with latest commits labeled "voodoops2controller 2.1.2" and it is same. 
I remove voodoops2mouse and trackpad kexts from PlugIns folder automatically when I download a new version but problem is still there for me when I don't remove either.

By the way I also use VoodooI2C kexts and Opencore bootloader could not boot without verbose mode before this version. Now it boots without any problem. Yey thanks for those initialization commits. 

My laptop is a Dell 7577. I made a search on google but couldn't find any topic similar to mine. People whom I talked couldn't suggest a solution. Maybe I am the only one.

Thanks all you have done so far as a team guys.

**Comment by Goshin** [comment]
I got the same issue before, and after a lot of time logging and rebooting I found out that the VoodooPS2Controller was stuck in `resetController()` waiting for a response.

https://github.com/Goshin/VoodooPS2/commit/ec769c50f0799523b7684132efe8a49876f66e73
[VoodooPS2Controller-2.1.1-RELEASE.zip](https://github.com/acidanthera/bugtracker/files/4260900/VoodooPS2Controller-2.1.1-RELEASE.zip)


I thought it might be backward support for some legacy controllers, so I patched it out and it just worked.

To my knowledge so far, it only happens on some 9th gen Coffee Lake laptops, so It might not work for you.

**Comment by lersy** [comment]
Hey @Goshin thanks for your reply, further details and providing a patched kext.

I put the kext you attached and reboot a few times and I haven't had the problem I mentioned. I don't know what is your patch but I think it also works for my kaby-lake laptop. I will update here after a couple of days to see if it is consisted.

By the way, the kext you uploaded says 2.1.1-Release. If I put 2.1.1-Release from acidanthera page it can't boot without verbose mode or if I don't press keys randomly when it starts booting. With your kext, I also don't have that problem. I am on Opencore 0.5.6 with latest commits possible. 

@vit9696 I don't know how process happens but maybe you can consider @Goshin's patch into your releases.

**Comment by Goshin** [comment]
The patch might be so simple and incomplete that it might cause other issues on some other laptops. But here we find out the cause so we can dig into it.

Glad it helps.

**Comment by lersy** [comment]
hey,

I am here to say what I have experienced for a week. it seems there is no problem about initialization of keyboard at each boot. it has worked each time after a cool boot chime :)

but there is a problem with kext for me @Goshin. It does not work when it pc returns from sleep. Do you have this problem?

**Comment by Goshin** [comment]
No, but you can try this one. I revert the `resetController()`for waking.

[VoodooPS2Controller.kext.zip](https://github.com/acidanthera/bugtracker/files/4298718/VoodooPS2Controller.kext.zip)

**Comment by lersy** [comment]
Reverting has been smooth so far. No issues at login screen after booting or waking. Thanks for your support dude @Goshin

**Comment by vit9696** [comment]
Could you submit this change as a pull-request guarded with some boot argument? E.g. ps2rst=0?

**Comment by Goshin** [comment]
> Could you submit this change as a pull-request guarded with some boot argument? E.g. ps2rst=0?

Sure
