### ISSUE TITLE
In-memory symbol solving

### ISSUE THREAD

**Issue by 07151129** [acidanthera/bugtracker#736]
Currently, Lilu uses root mount VFS to read symtab from kernel and kext binaries. It would be useful to support in-memory symbol search instead for at least the following reasons:

- In-memory search is much faster, so virtually every Lilu client would enjoy faster initialisation.

- Some clients (e.g. NVMeFix) need Lilu API in order to make VFS for root mount work, so currently they would deadlock.

OSKext removes LINKEDIT segment for non-library kexts to conserve memory, so it probably makes sense to force enable `keepsyms` via bootloader (see `OSKext::jettisonLinkeditSegment`). Lilu could then prefer in-memory solving if the bootarg is set, and fall back to the VFS solver otherwise.

**Comment by vit9696** [comment]
Done in master for 11.0 in KernelCollection mode exclusively. This is now possible since in this loading mode 11.0 does not unmap `__LINKEDIT` segments for kexts and kernel. Technically it is possible to backport this for older operating systems using `keepsyms=1` boot argument, but I do not care.
