### ISSUE TITLE
stuck at Password: when boot up.

### ISSUE THREAD

**Issue by ZISQO** [acidanthera/bugtracker#737]
i had a updated OpenCorePkg-R0.5.6-DevBuild-02252020_035113.zip
but displaying a "Password:"  when boot up.

i was tried my system password but failed 3 times.
what's wrong this version?

and OpenCorePkg-R0.5.6-DevBuild-02242020_025048.zip are booted successfully!

**Comment by vit9696** [comment]
For some reason you have Misc -> Security -> EnablePassword enabled in your config. This not yet a supported option, just remove it from your config. If you do not have this option, please ensure that you compile as explained in Configuration.pdf and only use supported drivers and plugins.

**Comment by ZISQO** [comment]
<img width="650" alt="스크린샷 2020-02-25 오후 3 24 52" src="https://user-images.githubusercontent.com/50421769/75220535-fd2c8480-57e2-11ea-9ec4-c02f94245ced.png">
my config is not include a EnablePassword anywhere.

**Comment by vit9696** [comment]
In this case it should be about the way you build. We do not support prerelease versions but at the very least we can confirm no issues on our side.

**Comment by fangf2018** [comment]
Same problem

**Comment by ZISQO** [comment]
> Same problem
> Press ESC to skip

today vit9696 has been fixed up that, so using macbuild.tool from master version after download it of.
btw working fine!
