### ISSUE TITLE
Discussion of SSDT-EC-USBX on Laptops

### ISSUE THREAD

**Issue by williambj1** [acidanthera/bugtracker#743]
Hello developers!

First of all, I highly respect your time, if you think this should be discussed in forums, feel free to close this issue. Reasons why I posted here instead of a forum:

1. I'm not here to request help or support, I believe this topic fits in the third condition of the bug tracker usage, technical discussion.
1. This SSDT is present in OpenCore's sample SSDTs, so it is directly related to Acidanthera.
1. Similar discussions of this topic are already present from vit9696 on AppleLife\[1\] but some of the information conflicts with the comments in ***SSDT-EC-USBX***.
1. A lot of people, including guide writers, are still confused\[2\].

---

EC solution theories on laptops are very confusing because of how AppleACPIEC kext is described.

AFAIK, there are currently three solutions people deal with their EC on laptops and here are my understandings.

1. Directly rename the Embedded Controller Device's name (`EC0`, `H_EC` or `ECDV`) into `EC`

   According to the comments in ***`SSDT-EC-USBX`*** in OC's AcpiSamples

   > Try NOT to rename EC0, H_EC, etc. to EC. These devices are incompatible with macOS and may break at any time. AppleACPIEC kext must NOT load.

   and the following warning in OpenCore's manual,

   > Avoid renaming devices with ACPI patches. This may fail or perform improper renaming of unrelated devices (e.g. EC and EC0), be unnecessary, or even fail to rename devices in select tables.

   **So this method seems to be the worst. (And I get a kernel panic from AppleACPIEC if I rename `EC0` to `EC` on my Asus Laptop)**

1. Use ***SSDT-EC-USBX*** without disabling (returning `_STA` to `Zero`) the original EC device

   For laptops, because `EC` controls batteries, it can never be disabled. According to comments in ***SSDT-EC-USBX***, "AppleACPIEC kext must NOT load", but on my Asus Laptop, AppleACPIEC kext loads under `boot-ec` even if I don't rename `EC0` to `EC`. It truly has no obvious side effects according to the description from AppleLife\[1\] "3) AppleACPIEC ... Darwin.", **so it means AppleACPIEC behaves differently when half matched to `PNP0C09` without `EC`? Is it still better disable it?**

1. Rename `_HID` for `PNP0C09` to `XHID` while pairing with a modified ***SSDT-EC-USBX*** that returns `PNP0C09` conditionally doesn't work, AppleACPIEC still loads. Maybe it should be blocked directly instead of preventing it from matching?

\[1\]: <https://applelife.ru/posts/807985>

\[2\]: <https://github.com/khronokernel/Getting-Started-With-ACPI/issues/1#issuecomment-585293220>

<details>
    <summary>[3] (Click to expand)</summary>

    Method (_HID, 0, NotSerialized)
    {
        If ((GPHD == One))
        {
            Return ("PNP0C02")
        }
        If ((PCHS == PCHH))
        {
            Return ("INT3450")
        }
        Return ("INT34BB")
    }

</details>

CC @vit9696 @khronokernel @xjn819 @XStar-Dev @athlonreg

> To people who don't even understand the content above: PLEASE DON'T PUT SPAM HERE! REACT BY GITHUB EMOJI IF YOU WANT TO EXPRESS SOMETHING!

Edit: fix a mistake in the third method

**Comment by Andrey1970AppleLife** [comment]
Everything higher told only for desktops.
Notebooks require renaming to EC.

**Comment by vit9696** [comment]
For the time being go with 2 if it works for you. I don't know why 3 does not work for you, as returning some other value from HID is generally best, but I am not positive it is worth investigating. It might make sense to block AppleACPIEC in the future, but currently we can live with it loading somehow.

**Comment by williambj1** [comment]
Thanks!
