### ISSUE TITLE
Latest AppleALC.kext (v1.4.7) broke sound on Dell g5 5587

### ISSUE THREAD

**Issue by tikscr** [acidanthera/bugtracker#746]
After latest kext update sound is missing from my system. layout-id is 14. here is my ioreg.
[broken_sound.ioreg.zip](https://github.com/acidanthera/bugtracker/files/4275340/broken_sound.ioreg.zip)

**Comment by vit9696** [comment]
No layout 14 was updated in the latest ALC, the issue is elsewhere, closing as invalid.

**Comment by tikscr** [comment]
@vit9696 but on 1.4.6 sound works without issues.

**Comment by Andrey1970AppleLife** [comment]
You have no AppleALC.

**Comment by Andrey1970AppleLife** [comment]
> After latest kext update sound is missing from my system. layout-id is 14. here is my ioreg.
> [broken_sound.ioreg.zip](https://github.com/acidanthera/bugtracker/files/4275340/broken_sound.ioreg.zip)

You have no AppleALC.
