### ISSUE TITLE
VoodooPS2Trackpad should add some Synaptics devices support

### ISSUE THREAD

**Issue by XStar-Dev** [acidanthera/bugtracker#747]
I'm appreciated that VoodooPS2 can keep updated. My Trackpad is Synaptics PS2, SYN3239, working very well. Recently, I found this kext could not work on every Synaptics PS2 Trackpad, i guess that VoodooPS2 don't add these device support, such as SYN327C. It's going to be easy if modifying plist file can solve this. I think their working princple is similar, so I hope the VoodooPS2 can add them in the support list, thank you.

**Comment by vit9696** [comment]
Does not look like a bugreport we can work with:

- No technical background of the problem or logs.
- No device IDs or other device details are provided.
- No patches to support these devices.

In general, we only support the hardware that we have, so pretty much all bugreports here are about hardware we do not own. I suggest you contribute the patches for the devices you need, as we do not have plans to do this kind of research on our own.

**Comment by singhalrishi27** [comment]
Can you help me to get it working before it barly working high sensitivity cursor non working scrolling non working gestures no click now with latest update it just doesn't seem to work
