### ISSUE TITLE
Inconsistencies in the Differences.pdf

### ISSUE THREAD

**Issue by MuntashirAkon** [acidanthera/bugtracker#750]
**OC version:** 0.5.6

The **differences.pdf** file has the following inconsistencies in p.23:
![Screenshot 2020-03-04 at 5 25 55 PM](https://user-images.githubusercontent.com/8176128/75875435-9f63f200-5e0b-11ea-9189-fdddafa3591a.png)

Please fix these issues.

**Comment by Andrey1970AppleLife** [comment]
Fixed
