### ISSUE TITLE
VoodooPS2 ThinkPad ClickPad Middle Button Problem

### ISSUE THREAD

**Issue by SukkaW** [acidanthera/bugtracker#752]
I am using macOS (Hackintosh, 10.15.4 Public Beta 3) on ThinkPad E480 and had my ThinkPad ClickPad and TrackPoint worked using `VoodooPS2Controller` and `VoodooInput`.

On Windows, when holding middle button of the ThinkPad ClickPad while moving Trackpoint will scroll, which VoodooPS2 support this behavior on macOS as well which I really appreciate that.
However, while with my finger on Trackpoint (giving input) while holding middle button to scroll on macOS, it seems that it will also trigger middle click event repeatedly.

Let me give an example to describe it:

- It is known to all that Chrome support middle click (no matter from a mouse or a ClickPad) to open a link in a new tab.
- When I move the cursor to a link, put my finger on the Trackpoint and holding middle button of ClickPad, Chrome will **repeatedly** open the same link in new tabs.
- If I remove my finger from Trackpoint and only holding middle button, no matter how long I hold the middle button, Chrome will only open the link **once**.
- If I put my finger back to Trackpoint with middle button hold, Chrome will start repeatedly open the same link in new tabs **again**.

It is quite annoying because when scrolling in a browser with Trackpoint and middle button, the curson will pass over a link sooner or later, causing Chrome (maybe other browsers as well) to repeatedly open that link.

I know Trackpoint is very sensitive, which means there is no way I can put my finger on it without trigger it. Maybe middle click event should be filtered (and only trigger scroll) when there is input from Trackpoint (e.g. put a finger on the Trackpoint). In this way middle click could still be triggered when finger is removed from Trackpoint.
Another idea is VoodooPS2 could trigger middle click event only once even when holding middle button.

**Comment by Topuz** [comment]
Are you using the appropriate ThinkPad SSDT?
https://github.com/acidanthera/VoodooPS2/tree/master/Docs/ACPI

**Comment by SukkaW** [comment]
@Topuz 

After checking my SSDT, I have noticed I might have been using outdated hotpatch since Rehabman VoodooPS2. I will update to newest then.

**Comment by basedtho** [comment]
Could you please help me? I think I'm doing something wrong. So, I opened `SSDT-Thinkpad_Clickpad.dsl` in MaciASL, clicked Compile, then File -> Save As... and saved it in Desktop, then I copied the aml file into /Volumes/EFI/EFI/CLOVER/ACPI/patched, but I still have this issue.

**Comment by basedtho** [comment]
please halp
