### ISSUE TITLE
Improve MTRR attribute compatibility for DirectGopRendering

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#755]
CacheMode 1
OCC: FB (C0000000, 4000000) MTRR (1) - Out of Resources
With CacheMode 4 and 6 too.
Acer v3-571g Ivy Bridge

CC @Download-Fritz

**Comment by vit9696** [comment]
The need for this is unjustified. We will accept patches if anybody wants to work on this and will not remove the `DirectGopCacheMode` for now though.

**Comment by mikebeaton** [comment]
Addressed by https://github.com/acidanthera/OpenCorePkg/pull/437
