### ISSUE TITLE
Xeon v3 2690 - x99 nvram kernel panic. 

### ISSUE THREAD

**Issue by brokenengineer** [acidanthera/bugtracker#760]
Kernel panic when loading macOS installer after successful opencore boot.

Presents when using Xeon 2690v3 in ASUS x99-pro motherboard. 

Kernel panic does not exist when 5820k cpu used in its place. 

Issue has been discussed heavily in hackintosh paradise discord channel with base OC boot loader used with options removed, options turned on hpet ssdt checked and patches inserted. 

Recommended to raise by hackintoosh slav

Happy to provide links to what ever requested 

![1912123E-80A0-451A-821A-BB684BECB956](https://user-images.githubusercontent.com/47435741/76185989-9d8b9b80-621c-11ea-9de3-4928f837b2cd.jpeg)

**Comment by vit9696** [comment]
I do not think this is an issue with one of our products. Your system crashes, well, configure it properly and/or explore the crash.
