### ISSUE TITLE
AppleALC and VoodooPS2Controller are not working on Sandybridge X220, despite that they worked on Clover

### ISSUE THREAD

**Issue by HoshiYamazaki** [acidanthera/bugtracker#766]
Hey, so I wanted to Hackintosh my X220 using only OpenCore, not Clover (for sake of achievement) so I did everything like year ago when I used Clover (https://www.reddit.com/r/hackintosh/comments/9mqgi0/hackpad_macos_high_sierra_on_x220_without_using/)
And it seems that I don't get Audio working (this Thinkpad have CX20590) with Layout-ID 1, 3, 12 and VoodooPS2Controller from multiple sources is not working either.
Yeah, you can assume that this is support request, but everything was working on Clover, so I assume this is some bug/quirk in the OpenCore.
`kextstat` prints that kexts are loaded, I tried even disabling SIP (I was possible to test that because I installed system with external keyboard/mouse).
I use High Sierra, today when I will return from work I will post my configs and logs.

(You can tell me what I should prepare because I will try to gain logs that are useful but maybe I will miss something).

**Comment by Sniki** [comment]
> Hey, so I wanted to Hackintosh my X220 using only OpenCore, not Clover (for sake of achievement) so I did everything like year ago when I used Clover (https://www.reddit.com/r/hackintosh/comments/9mqgi0/hackpad_macos_high_sierra_on_x220_without_using/)
> And it seems that I don't get Audio working (this Thinkpad have CX20590) with Layout-ID 1, 3, 12 and VoodooPS2Controller from multiple sources is not working either.
> Yeah, you can assume that this is support request, but everything was working on Clover, so I assume this is some bug/quirk in the OpenCore.
> `kextstat` prints that kexts are loaded, I tried even disabling SIP (I was possible to test that because I installed system with external keyboard/mouse).
> I use High Sierra, today when I will return from work I will post my configs and logs.
> 
> (You can tell me what I should prepare because I will try to gain logs that are useful but maybe I will miss something).

It's most probably the IRQflags aka (clover):
FixHPET
FixIPIC
FixTMR
Etc

If you had one of these fixes, try adding into config.plist:
Kernel > Block > com.apple.driver.AppleHPET 
Disabled = Yes

Reboot, if you have working audio you have two solutions until March Update:
1. Patch DSDT with irqflags fix
2. Compile latest AppleALC from master and use the alc-delay property or wait for the official release on march.
3. Keep that dirty workaround till march release.

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by HoshiYamazaki** [comment]
> > Hey, so I wanted to Hackintosh my X220 using only OpenCore, not Clover (for sake of achievement) so I did everything like year ago when I used Clover (https://www.reddit.com/r/hackintosh/comments/9mqgi0/hackpad_macos_high_sierra_on_x220_without_using/)
> > And it seems that I don't get Audio working (this Thinkpad have CX20590) with Layout-ID 1, 3, 12 and VoodooPS2Controller from multiple sources is not working either.
> > Yeah, you can assume that this is support request, but everything was working on Clover, so I assume this is some bug/quirk in the OpenCore.
> > `kextstat` prints that kexts are loaded, I tried even disabling SIP (I was possible to test that because I installed system with external keyboard/mouse).
> > I use High Sierra, today when I will return from work I will post my configs and logs.
> > (You can tell me what I should prepare because I will try to gain logs that are useful but maybe I will miss something).
> 
> It's most probably the IRQflags aka (clover):
> FixHPET
> FixIPIC
> FixTMR
> Etc
> 
> If you had one of these fixes, try adding into config.plist:
> Kernel > Block > com.apple.driver.AppleHPET
> Disabled = Yes
> 
> Reboot, if you have working audio you have three solutions until March Update:
> 
> 1. Patch DSDT with irqflags fix
> 2. Compile latest AppleALC from master and use the alc-delay property or wait for the official release on march.
> 3. Keep that dirty workaround till march release.(not recommended)

Hey, so I managed to get working audio (and even battery status, also brightness control), but for some reason VoodooPS2 in any version is not working on my X220, and it /was/ working on Clover so I assume I did mistake somewhere or it's OpenCore quirk. I will prepare debug logs or check it deeper soon.
