### ISSUE TITLE
No enough memory for kernel on ice lake laptops

### ISSUE THREAD

**Issue by nickcname13241** [acidanthera/bugtracker#769]
I have laptop lenovo ideapad s340 [intel core i5-1035g1](https://ark.intel.com/content/www/us/en/ark/products/196603/intel-core-i5-1035g1-processor-6m-cache-up-to-3-60-ghz.html)

There is problem with allocation memory for core on laptop  with ice lake . There is no space for it. Legacy boot doesn't help at all.

From what I've read on other forums it looks like all Ice Lake CPUs are suffering from that.
Here the same problem: https://www.insanelymac.com/forum/topic/331381-aptiomemoryfix/?do=findComment&comment=2693287
or here many people with that problem waiting for fix: https://www.tonymacx86.com/threads/laptop-compatibility.106791/page-80#post-2036023
And on reddit too.

**0000000000100000-0000000030D59FFF 0000000000030C5A**  - here is no enough space. 

DevirtualiseMMIO doesn't help.

Here is a memmap:

`Type       Start            End              # Pages          Attributes

Available  0000000000000000-000000000009EFFF 000000000000009F 000000000000000F
Reserved   000000000009F000-000000000009FFFF 0000000000000001 000000000000000F
Available  0000000000100000-0000000030D59FFF 0000000000030C5A 000000000000000F
BS_Data    0000000030D5A000-0000000031543FFF 00000000000007EA 000000000000000F
Available  0000000031544000-0000000031961FFF 000000000000041E 000000000000000F
BS_Data    0000000031962000-000000003198EFFF 000000000000002D 000000000000000F
LoaderCode 000000003198F000-0000000031A64FFF 00000000000000D6 000000000000000F
Available  0000000031A65000-0000000031A68FFF 0000000000000004 000000000000000F
BS_Data    0000000031A69000-0000000031ABDFFF 0000000000000055 000000000000000F
Available  0000000031ABE000-0000000031ABEFFF 0000000000000001 000000000000000F
BS_Data    0000000031ABF000-0000000031AEBFFF 000000000000002D 000000000000000F
Available  0000000031AEC000-0000000031AECFFF 0000000000000001 000000000000000F
BS_Data    0000000031AED000-0000000031B31FFF 0000000000000045 000000000000000F
Available  0000000031B32000-0000000031B34FFF 0000000000000003 000000000000000F
BS_Data    0000000031B35000-0000000031B4FFFF 000000000000001B 000000000000000F
Available  0000000031B50000-0000000031B51FFF 0000000000000002 000000000000000F
BS_Data    0000000031B52000-0000000032727FFF 0000000000000BD6 000000000000000F
Available  0000000032728000-0000000032728FFF 0000000000000001 000000000000000F
BS_Data    0000000032729000-000000003272EFFF 0000000000000006 000000000000000F
Available  000000003272F000-000000003272FFFF 0000000000000001 000000000000000F
BS_Data    0000000032730000-00000000327ABFFF 000000000000007C 000000000000000F
Available  00000000327AC000-00000000327ACFFF 0000000000000001 000000000000000F
BS_Data    00000000327AD000-0000000032848FFF 000000000000009C 000000000000000F
Available  0000000032849000-000000003284DFFF 0000000000000005 000000000000000F
BS_Data    000000003284E000-0000000032852FFF 0000000000000005 000000000000000F
Available  0000000032853000-0000000032857FFF 0000000000000005 000000000000000F
BS_Data    0000000032858000-00000000329F1FFF 000000000000019A 000000000000000F
Available  00000000329F2000-00000000329F6FFF 0000000000000005 000000000000000F
BS_Data    00000000329F7000-0000000032A1CFFF 0000000000000026 000000000000000F
Available  0000000032A1D000-0000000032A1DFFF 0000000000000001 000000000000000F
BS_Data    0000000032A1E000-0000000033255FFF 0000000000000838 000000000000000F
LoaderCode 0000000033256000-000000003333DFFF 00000000000000E8 000000000000000F
BS_Data    000000003333E000-00000000360EEFFF 0000000000002DB1 000000000000000F
BS_Code    00000000360EF000-0000000036108FFF 000000000000001A 000000000000000F
BS_Data    0000000036109000-0000000036119FFF 0000000000000011 000000000000000F
BS_Code    000000003611A000-000000003611AFFF 0000000000000001 000000000000000F
BS_Data    000000003611B000-000000003612BFFF 0000000000000011 000000000000000F
BS_Code    000000003612C000-0000000036139FFF 000000000000000E 000000000000000F
BS_Data    000000003613A000-0000000037475FFF 000000000000133C 000000000000000F
BS_Code    0000000037476000-0000000037492FFF 000000000000001D 000000000000000F
BS_Data    0000000037493000-00000000374C3FFF 0000000000000031 000000000000000F
BS_Code    00000000374C4000-00000000374CDFFF 000000000000000A 000000000000000F
BS_Data    00000000374CE000-00000000374DFFFF 0000000000000012 000000000000000F
BS_Code    00000000374E0000-00000000374FFFFF 0000000000000020 000000000000000F
BS_Data    0000000037500000-0000000037987FFF 0000000000000488 000000000000000F
Reserved   0000000037988000-0000000038287FFF 0000000000000900 000000000000000F
BS_Code    0000000038288000-000000003828FFFF 0000000000000008 000000000000000F
BS_Data    0000000038290000-000000003829EFFF 000000000000000F 000000000000000F
Available  000000003829F000-0000000039692FFF 00000000000013F4 000000000000000F
BS_Code    0000000039693000-000000003A09EFFF 0000000000000A0C 000000000000000F
RT_Code    000000003A09F000-000000003A46EFFF 00000000000003D0 800000000000000F
RT_Data    000000003A46F000-000000003ADEEFFF 0000000000000980 800000000000000F
Reserved   000000003ADEF000-000000003B4DEFFF 00000000000006F0 000000000000000F
ACPI_NVS   000000003B4DF000-000000003BBCEFFF 00000000000006F0 000000000000000F
ACPI_Recl  000000003BBCF000-000000003BC4EFFF 0000000000000080 000000000000000F
BS_Data    000000003BC4F000-000000003BC4FFFF 0000000000000001 000000000000000F
Available  0000000100000000-00000002B2BFFFFF 00000000001B2C00 000000000000000F
Reserved   00000000000A0000-00000000000FFFFF 0000000000000060 0000000000000000
Reserved   000000003BC50000-0000000047FFFFFF 000000000000C3B0 000000000000000F
Reserved   0000000048000000-0000000048FFFFFF 0000000000001000 0000000000000009
Reserved   0000000049000000-000000004D3FFFFF 0000000000004400 0000000000000000
MMIO       000000004D400000-00000000CFFFFFFF 0000000000082C00 8000000000000001
MMIO       00000000FC800000-00000000FE7FFFFF 0000000000002000 8000000000000001
MMIO       00000000FED00000-00000000FED00FFF 0000000000000001 8000000000000001
MMIO       00000000FED10000-00000000FED17FFF 0000000000000008 8000000000000001
Reserved   00000000FED20000-00000000FED7FFFF 0000000000000060 0000000000000000
MMIO       00000000FEDA0000-00000000FEDA1FFF 0000000000000002 8000000000000001
MMIO       00000000FEE00000-00000000FEE00FFF 0000000000000001 8000000000000001
MMIO       00000000FF600000-00000000FFFFFFFF 0000000000000A00 8000000000000001`

**Comment by vit9696** [comment]
I believe https://github.com/acidanthera/OpenCorePkg/commit/6d61426da5e89a33801c9f8a8f563861ed35d883 fixes it.

**Comment by xzz024** [comment]
Hello, the same situation, and I found that the mouse pointer is not displayed at this time, in the state of flower screen, if you move the mouse will also be black screen flashing. But the mouse pointer will return to normal after 10 seconds when the screen returns to normal display, I guess whether it is related to this, thanks for browsing
