### ISSUE TITLE
TrackPad for ThinkPad T450

### ISSUE THREAD

**Issue by PavlovMD** [acidanthera/bugtracker#771]
Всем привет! Сорян за отсутствие английского, т.к. май инглиш из бэд.
Также хочу извиниться за возможный дубликат обсуждения. Я видел закрытые обсуждения на тему тачпадов для ThinkPad, но там несколько веток обсуждений и я запутался в них и не понял, где писать( 
Опишу мою ситуацию: у меня ноутбук T440p с тачпадом от T450 с тремя физическими кнопками и трэкпоинтом на клавиатуре. С обсуждаемым кекстом тачпад работает частично: работают все жесты и щелчки тачпадом, кроме 4-пальцевых жестов, не работает трэкпоинт, не работают физические кнопки над тачпадом, слабая чувствительность к прикосновениям 2-3 пальцами. Префпанель работает и корректно меняет настройки.
Методом тыка определил, что если удалить из папки Plugin кекст VoodooPS2Trackpad.kext, то корректно будет работать трэкпоинт, физические кнопки (кроме средней) и перемещение курсора пальцем по трэкпаду.
Для этой модели тачпада есть старый кекст, который в 10.15 работает некорректно: отсутствие префпанели (в 10.13 она отображалась норм), движение курсора трэкпоинтом очень неплавное (курсор идет углами и большими шагами). Можно ли из этого взять настройки и добавить в обсуждаемый здесь кекст?
Я пробовал перекидывать конфиги из старого кекста в местный, но потерпел фиаско, т.к. навыков у меня нет(
[T450-VoodooPS2Controller.zip](https://github.com/acidanthera/bugtracker/files/4333995/T450-VoodooPS2Controller.zip)

**Comment by vit9696** [comment]
Без исходников кекста делать нечего, потому что дело почти всегда не в Info.plist. Если будут исходники, можно попробовать перенести, но скорее всего никто заниматься не будет, тем более, что кодовые базы очень разошлись. Сейчас возможен разве что в формат, в котором присылается патч, мы его ревьюим и добавляем в мейнлайн.

**Comment by PavlovMD** [comment]
А что я могу сделать для того, чтобы в твоем кексте появились настройки для моего тачпада?) 

Если скажешь, какие мне нужно потестить тесты, проверить, то я сделаю, всё, что смогу
