### ISSUE TITLE
default background color variable can not be set in cMP

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#774]
```

<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
<dict>
<key>DefaultBackgroundColor</key>

```

Can not be set in cMP:

```
nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:DefaultBackgroundColor
nvram: Error getting variable - '4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:DefaultBackgroundColor': (iokit/common) data was not found

```

**Comment by vit9696** [comment]
Without the config.plist and OpenCore log I do not think there is a way to confirm there is any bug. Please provide them for us to reconsider the issue state.

**Comment by startergo** [comment]
[Archive.zip](https://github.com/acidanthera/bugtracker/files/4340605/Archive.zip)
Please find it attached.

**Comment by vit9696** [comment]
Right, from the logs it seems that there are two possible cases:

- The variable is not set due to some NVRAM driver bug. Try changing WriteFlash to YES.
- macOS discards the variable as incompatible due to board-id/model. Check the variable value in Windows or Linux, it should be fine.

In both cases it is out of the scope of OpenCore. What are you trying to achieve?

**Comment by startergo** [comment]
WriteFlash did not help. It looks like you said the variable is incompatible due to board-id/model.
I am truing to change the background color in the BootLiquor GUI interface from black to Apple gray.

**Comment by vit9696** [comment]
OpenCanopy (formerly having a development codename BootLiquor) currently does not have grey background support as noted in https://github.com/acidanthera/bugtracker/issues/759. I have to ask you to be very careful when reading the documentation, which in fact mentions this issue and does not recommend OpenCanopy for everyday use.

Also, all Macs starting from like 2013 have black background and modern icons in BootPicker as well as black background and white Apple logo during macOS startup. Whether to support grey background or not is the matter of supporting legacy style, which is questionable per itself, but we plan to add it as we progress with the UI. The UI currently has very low priority though.
