### ISSUE TITLE
MaciASL regex patching seems to be wrong?

### ISSUE THREAD

**Issue by HoshiYamazaki** [acidanthera/bugtracker#775]
https://github.com/RehabMan/Laptop-DSDT-Patch/issues/93

This is my issue from RehabMan github.
In short, I had problems while using RehabMan patches, and I assume something is wrong with regex compiler, but I am not sure.
My DSDT dump: https://gist.github.com/HoshiYamazaki/05e62c1f9e74ae94e5c8179d251f15fc
Used tool to dump: https://github.com/corpnewt/SSDTTime (From Linux, not macOS so I have clean file without OpenCore/kexts patches)

**Comment by vit9696** [comment]
Hello, we are not maintaining these patches, so I believe it is best to ask their author. In either case, I do not think there is any issue with the regex, rather that the patches simply are incompatible.
