### ISSUE TITLE
[VoodooPS2] Brightness & Volume adjustment not working after waking from sleep

### ISSUE THREAD

**Issue by SukkaW** [acidanthera/bugtracker#776]
I am using macOS (Hackintosh, 10.15.4 Public Beta 3) on ThinkPad E480 and had my keyboard worked using `VoodooPS2Controller`.

Volume adjustment is working automatically after having my audio driven correctly. And I am using SSDT to make Brightness adjustment works.

Before sleep. I have `LogScanCodes` to `1` and logged following keycodes of Fn shortcuts:

- <kbd>Fn</kbd> - `e063=80` - DEADKEY
- <kbd>Fn</kbd> + <kbd>F1</kbd> - `e020=4a` - Mute
- <kbd>Fn</kbd> + <kbd>F2</kbd> - `e02e=49` - Volume down
- <kbd>Fn</kbd> + <kbd>F3</kbd> - `e030=48` - Volume up
- <kbd>Fn</kbd> + <kbd>F4</kbd> - `64=69` - F13
- <kbd>Fn</kbd> + <kbd>F5</kbd> - `e005=6b` - F14 (Brightness down)
- <kbd>Fn</kbd> + <kbd>F6</kbd> - `e006=71` - F15 (Brightness up)
- <kbd>Fn</kbd> + <kbd>F8</kbd> - `67=6a` - F16
- <kbd>Fn</kbd> + <kbd>F9</kbd> - `68=40` - F17
- <kbd>Fn</kbd> + <kbd>F10</kbd> - `69=4f` - F18
- <kbd>Fn</kbd> + <kbd>F12</kbd> - `6a=50` - F19

Then I let macOS get into sleep. After waking from sleep, none of those shortcuts I list above works, no keycode was logged in the `Console.app`, too.

I am not sure whether the issue is related with VoodooPS2 or my DSDT & SSDT.

P.S. The keyboard of ThinkPad E480:

![image](https://user-images.githubusercontent.com/40715044/77222410-ca7d6e00-6b8d-11ea-8979-537c4ac671d8.png)

**Comment by SukkaW** [comment]
I can confirm the issue is not related with VoodooPS2 then. So I am closing this issue now.

**Comment by ZochoK** [comment]
Do you know how to fix it?

**Comment by SukkaW** [comment]
@ZochoK It depends on your device.

In short, it is related with EC controller which refuses to sending EC query after S3 wake.
