### ISSUE TITLE
[VoodooPS2] Mapping a key to disable Trackpad

### ISSUE THREAD

**Issue by SukkaW** [acidanthera/bugtracker#777]
After I have installed `VoodooPS2`, I noticed that `PrtSc` key could be used to disable/enable Trackpad.

Although I could use `SSDT-PrtSc-F13.dsl` to map `PrtSc` to `F13` (Or any other key I want), but I do need a key used to disable Trackpad and I just don't want this key to be `PrtSc`. So what should I do with the SSDT?

I have looked through `ApplePS2ToADBMap.h` but found no PS2 keycode is related with disabling Trackpad. Maybe I need to write a `Custom PS2 Map` like this?

```dsl
            "Keyboard", Package()
            {
                "Custom PS2 Map", Package()
                {
                    Package(){},
                    "[some keycode]=e037",  // Map a key to original PrtSc
                    "e037=64", // PrtSc F13
                },
            }
```

**Comment by vit9696** [comment]
Trackpad is disabled when receiving 0x137 key, which is just an encoding for e037. See [this code](https://github.com/acidanthera/VoodooPS2/blob/2947fb9/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp#L1616-L1636). To avoid trackpad disable on `PrtSc/SysRq` you can map this key to e.g. F13, and then optionally map some other keycode to `PrtSc`, exactly the way you pasted.

@lvs1974 @usr-sse2 once again, why do we have that fugly shortcut in the first place? I do not think you can disable trackpad with a keyboard shortcut on a MacBook. There is a sufficient option to disable it when the mouse is [plugged in](https://osxtips.net/how-to-disable-trackpad-on-a-macbook/). I would suggest to drop this legacy code or at least make it optional, as it makes no sense to me hardcode some shortcuts within a driver for such ugly features.

**Comment by laozhiang** [comment]
Prtsc disable Tackpad is can work in bigSur. I Compile Voodoops2(code check out at 6/28) my self. In OS X 10.15.5,it work fine.but it can't work in big sur.

**Comment by zhen-zen** [comment]
> Prtsc disable Tackpad is can't work in Big Sur. I Compile Voodoops2(code check out at 6/28) my self. In OS X 10.15.5,it work fine.but it can't work in big sur.

Please double check if you have latest kexts. Just tested it on 11.0 Beta 10 (20A5395g).

**Comment by vit9696** [comment]
I suggest to track the issues with disabling trackpad and making this functionality optional and disabled in the first place by default in https://github.com/acidanthera/bugtracker/issues/989.
