### ISSUE TITLE
Problem when trying to send a pull request for AppleALC

### ISSUE THREAD

**Issue by Sniki** [acidanthera/bugtracker#778]
Sorry for this but since it's technical stuff and related to a problem of having trouble sending a pull request i will write here shortly.

I updated configdata and added wakeconfigdata for CX20751/2 so it works perfect without codeccommander.kext
I updated configdata and updated wakeconfigdata for ALC221 so it works perfect without codeccomander.kext

The problem is, when i do commit on my fork so i can send the PR on AppleALC, it does change the order of all configdata of all codecs (entire info.plist) see here:
https://github.com/Sniki/AppleALC/commit/02a422169f783af9e24a79176712ff9ed1148205
load diff and see how it messes the entire .plist

Is there an option on Xcode to disable such auto correction stuff and also to fix this problem introduced since Mojave with <data> plist format:
<img width="1280" alt="data" src="https://user-images.githubusercontent.com/30008333/77248058-cfe2c300-6c36-11ea-9a82-c317cb606317.png">
The old style was better as i was able to see the entire line while here it cuts and you cant see the entire data even if you double click to edit it.

Thanks ! CC @vandroiy2013

**Comment by Andrey1970AppleLife** [comment]
Build kext.

**Comment by Sniki** [comment]
> Build kext.

Thanks ! @Andrey1970AppleLife.
Done the Pull Request on AppleALC
