### ISSUE TITLE
NVMeFix 1.0.2 : PM981 does not work with latest patch 

### ISSUE THREAD

**Issue by tiger511** [acidanthera/bugtracker#780]
I am still getting timeout error and it crashes with kp.below is attached image right before kp.
![IMG_20200323_165333](https://user-images.githubusercontent.com/53279423/77309789-7a3a1380-6d27-11ea-96ae-7ac162912c32.jpg)

**Comment by 07151129** [comment]
What does a DEBUG build of NVMeFix log with -nvmefdbg boot-arg?

Does using OpenCore help?

We have a patch to address this problem at an earlier stage, but it will only work with OpenCore. You may have to adjust kernel version.

```xml
<dict>
    <key>Base</key>
    <string>__ZN16IONVMeController22FilterInterruptRequestEP28IOFilterInterruptEventSource</string>
    <key>Comment</key>
    <string>Force ANS2MSIWorkaround</string>
    <key>Count</key>
    <integer>1</integer>
    <key>Enabled</key>
    <true/>
    <key>Find</key>
    <data>gL8AAAAAAHQA</data>
    <key>Identifier</key>
    <string>com.apple.iokit.IONVMeFamily</string>
    <key>Limit</key>
    <integer>128</integer>
    <key>Mask</key>
    <data>//8AAP////8A</data>
    <key>MaxKernel</key>
    <string></string>
    <key>MinKernel</key>
    <string>19.0.0</string>
    <key>Replace</key>
    <data>xocAAAAAAZCQ</data>
    <key>ReplaceMask</key>
    <data>//8AAP//////</data>
    <key>Skip</key>
    <integer>0</integer>
</dict>
```

**Comment by tiger511** [comment]
I've tried with both OpenCore and Clover latest version.The error is same.I'm already using debug build of Lilu and NVMeFix.I'll add the above flag and patch and report you back.

**Comment by tiger511** [comment]
With the above patch and boot arg ,It hangs for a while after the screenshot #1.  Then its the same error in screenshot #2. 
#1 
![IMG_20200323_181206](https://user-images.githubusercontent.com/53279423/77315851-7d86cc80-6d32-11ea-9978-398026b5b0bf.jpg)
#2
![IMG_20200323_181228](https://user-images.githubusercontent.com/53279423/77315857-7f509000-6d32-11ea-917b-5ffe9a23f14a.jpg)

**Comment by 07151129** [comment]
Double check OpenCore log to ensure the patch is indeed applied.

**Comment by tiger511** [comment]
It is a kernel patch,right?
I've attached my OC config.plist
[config.plist.txt](https://github.com/acidanthera/bugtracker/files/4369971/config.plist.txt)

**Comment by 07151129** [comment]
It's a kext patch. Again,

> Double check OpenCore log to ensure the patch is indeed applied.

**Comment by vit9696** [comment]
@07151129 OpenCore has kernel and kext patches in one section — Kernel. The plist file looks correct in the terms of patch addition.

**Comment by 07151129** [comment]
@vit9696 Yes, but it's still unknown whether it actually gets applied, especially given MinKernel

**Comment by vit9696** [comment]
Of course, OC log is best to check this.

**Comment by vit9696** [comment]
Should I close this due to inactivity?

**Comment by 07151129** [comment]
I don't mind, but if we're closing issues due to inactivity, we should do so consistently.

**Comment by frbuccoliero** [comment]
Same error here. Dell xps 9570 /w Samsung PM981. NVMEFix 1.0.2 and the patch @07151129 posted above applied succesfully.
Here my KP log at startup: https://youtu.be/03wfQolW34o

**Comment by 07151129** [comment]
Does clearing NVRAM help consistently? Can you provide its dump?

**Comment by frbuccoliero** [comment]
It does 99% of the times, after a KP, i clear the nvram and it boots. However just now i'm getting KPs and neither clearing nvram is helping. 

Here is the content of nvram when i manage to boot successfully:

![Schermata_2020-03-25_alle_18 06 43](https://user-images.githubusercontent.com/14348908/77817630-942f7980-70cc-11ea-9920-94111d61ab03.png)

**Comment by frbuccoliero** [comment]
And about the patch 

> We have a patch to address this problem at an earlier stage, but it will only work with OpenCore. You may have to adjust kernel version.

I have catalina 10.15.1 so kernel ==  19.0.0 : is it included in minKernel 19.0.0 or do i have to put a smaller value to make it match?

**Comment by frbuccoliero** [comment]
Here also a log of my latest KP, definitely about IONVMEFamily

[IONVMEFamily KP.txt](https://github.com/acidanthera/bugtracker/files/4396813/IONVMEFamily.KP.txt)

**Comment by frbuccoliero** [comment]
@07151129 i don't know if you had time to see that logs, but i found out that the "indicator" of Kp is AppleNVMERequestTimer which seems to have a patch here: https://github.com/RehabMan/patch-nvme/blob/master/IONVMe_disable_rename.plist

```
			<dict>
				<key>Comment</key>
				<string>rename AppleNVMeRequestTimer</string>
				<key>Name</key>
				<string>IONVMeFamily</string>
				<key>Find</key>
				<data>AEFwcGxlTlZNZVJlcXVlc3RUaW1lcgA=</data>
				<key>Replace</key>
				<data>AGVscHBBTlZNZVJlcXVlc3RUaW1lcgA=</data>
			</dict>
 ```

What do you think?

**Comment by 07151129** [comment]
Definitely not a good idea. I don't see how renaming the class would work at all, but even if it did, this would just break request timeouts globally.

**Comment by frbuccoliero** [comment]
> it's unlikely we will be able to fix this issue

I mean: you did test with PM981 , Catalina, Opencore? 
What might have gone wrong? The patch didn't apply or maybe it's another issue?

**Comment by 07151129** [comment]
> I mean: you did test with PM981 , Catalina, Opencore?

Yes.

> What might have gone wrong? The patch didn't apply or maybe it's another issue?

If OpenCore log says the patch has been applied, then it is indeed applied. You can remove MinKernel or check kernel version with `uname -a` if you are not sure. So if the patch does not help, then the problem is caused by something else.

**Comment by frbuccoliero** [comment]
I will try to update Catalina to the latest version so i will be sure to match minkernel. As i said, my kernel is exactly 19.0.0 so i don't know if minKernel **includes** its value

**Comment by vit9696** [comment]
@frbuccoliero what is the problem of checking the log? It is really going stupid here. I mean, just open opencore_….txt and find the place where it applies the patch. Oh, well, could upload it here if you are worried you may misread it.

**Comment by frbuccoliero** [comment]
I have opencore logging disabled actually. Give me a time to enable it so i can share it with you. Sorry but i've been with clover for so long. OC looks totally different to me

**Comment by frbuccoliero** [comment]
Ok looks like i enabled the logging:
![Schermata 2020-03-29 alle 14 56 08](https://user-images.githubusercontent.com/14348908/77849631-6da53780-71cd-11ea-9771-1f45c33ed18d.png)
And infact in EFI folder appeared:
[opencore-2020-03-29-125249.txt](https://github.com/acidanthera/bugtracker/files/4398900/opencore-2020-03-29-125249.txt)
But the file is completely empty.
Is it because this time it booted successully? (As i said it doesn't always make this problem, just 08% of the times, this time it was that 20% where it boots with no problem)

**Comment by vit9696** [comment]
You need OpenCore debug for this to log anything.

**Comment by frbuccoliero** [comment]
Can you please explain? Is that a kext, a patch? If i google "Opencore debug" i find that guide that tells me to add DisplayLevel and Target in config, nothing else

**Comment by vit9696** [comment]
I meant the DEBUG binaries (as seen e.g. at https://github.com/acidanthera/OpenCorePkg/releases)

**Comment by frbuccoliero** [comment]
I replaced BOOTx64.efi and OpenCore.efi with the ones in DEBUG but still empty logfile

**Comment by vit9696** [comment]
Should not be, unless the filesystem is corrupted. Please note, that a new file is created at every new boot.

**Comment by frbuccoliero** [comment]
Yes i know , a new file is created at each boot. But they are all empty.

**Comment by vit9696** [comment]
I am afraid you somehow failed to replace the actual used OpenCore.efi then.

**Comment by frbuccoliero** [comment]
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4398994/EFI.zip)
Doublechecked. Can you please triplecheck it? 😞

**Comment by vit9696** [comment]
Well, you are definitely using OpenCore.efi and BOOTx64.efi from a RELEASE build of OpenCore. You probably picked the wrong archive somehow. You need this one:
https://github.com/acidanthera/OpenCorePkg/releases/download/0.5.6/OpenCore-0.5.6-DEBUG.zip

**Comment by frbuccoliero** [comment]
https://youtu.be/jrXpu3kl8mc

**Comment by frbuccoliero** [comment]
Ok finally we have a working log.
[opencore-2020-03-29-140051.txt](https://github.com/acidanthera/bugtracker/files/4399026/opencore-2020-03-29-140051.txt)
Btw this time it booted. Tbh all this times i'm booting i'm having better results. Like 10/12 successful boots. Maybe it might haven't fixed at all the problem but it helps

**Comment by vit9696** [comment]
Right, the patch applies successfully. Well, if it does not work for you sometimes, I am afraid we do not have a solution for your problem.

**Comment by frbuccoliero** [comment]
That was a successful opencore boot log. Please take a minute to check this non-booting log. I cheched it with a difference checker and at the end there is something about NVRAM and things deleted. My assumption is that it detects something wrong before patching NVME and it tries to clear NVME and after resetting it , it just reboots because of that. Might be wrong but that's my interpretation:

[opencore-2020-03-29-184259.txt](https://github.com/acidanthera/bugtracker/files/4401457/opencore-2020-03-29-184259.txt)

Thank you very much

**Comment by frbuccoliero** [comment]
Here's another after clearing nvram 
[opencore-2020-03-29-184327.txt](https://github.com/acidanthera/bugtracker/files/4401490/opencore-2020-03-29-184327.txt)
