### ISSUE TITLE
Request for integrating personal repository inside DSDT patches

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#782]
As per title, what are the steps to take in order to integrate a repository inside MaciASL.app without adding it to custom Sources from Preferences panel of the app? 
As per now I've succeeded adding a custom repository directly in MaciASL source code inside "AppDelegate.m".
Do I have to fork it and distribute the "custom" MaciASL.app which effectively differs from the original one for one repository or what else?
Thanks in advance

**Comment by vit9696** [comment]
Hello, as for editing `AppDelegate.h`, that's about right. You may have to reset preferences for this to take an effect, however. As for submitting your repository, if it is useful and looks adequate you can submit a pull-request for including this repository in the default build of MaciASL.

**Comment by dreamwhite** [comment]
Thank you so much. I'll try to reorganize the various patches and I'll submit a pull request 😄
