### ISSUE TITLE
Can't control brightness without GFX0 to IGPU rename

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#785]
Hi there. I have a Dell Inspiron 5370 w/ i5-8250U (UHD620). When I disable GFX0 to IGPU rename in clover I can't edit brightness. My ssdt-pnlf has already IGPU external reference, so it should automatically load it.
Any advice? 
Afaik GFX0 to IGPU rename is automatically done by WeG
Thanks

**Comment by Andrey1970AppleLife** [comment]
Rename in yours ssdt-pnlf  IGPU to GFX0

**Comment by dreamwhite** [comment]
Ya, is working haha. I didn't thought that renaming manually GFX0 to IGPU inside SSDT-PNLF.aml couldn't get brightness working.

Thank you so much :)
