### ISSUE TITLE
the Nvram tool was unable to set a preference.

### ISSUE THREAD

**Issue by ZISQO** [acidanthera/bugtracker#786]
prompt the message "You can't change the startupdisk to the selected disk. (the nvram tool was unable to set a preference.)" is displayed starting from Catalina 10.14.5 with OpenCore 0.5.7, but i can specify the startup disk. Can you see why this error is occurring?

But didn't happened in CT10.14.4 (it just few about the 1day ago hahahah~)
maybe it's just because of the New OS buggy? (I just guess up)

<img width="665" alt="Screen Shot 2020-03-26 at 7 24 03 AM" src="https://user-images.githubusercontent.com/50421769/77594070-dde75b00-6f38-11ea-9d78-732571082be3.png">
<img width="730" alt="Screen Shot 2020-03-26 at 8 06 21 AM" src="https://user-images.githubusercontent.com/50421769/77594073-e049b500-6f38-11ea-9d2e-3179df4ffc5e.png">

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by bavelee** [comment]
You should enable `WriteFlash` in your config.

**Comment by ZISQO** [comment]
> You should enable `WriteFlash` in your config.

thanks~ but i was fixed it up yesterday. but i'm not sure it's why working fine without writeflash:yes in 10.15.3 but x.x.4 is occured it.

**Comment by bavelee** [comment]
It also confused me after i upgraded to `10.15.14`, before that I using `10.15.13` does not need enable `WriteFlash`.

**Comment by ZISQO** [comment]
> It also confused me after i upgraded to `10.15.14`, before that I using `10.15.13` does not need enable `WriteFlash`.

this options are different  as motherboard brand
