### ISSUE TITLE
Laptop with HD620 graphics has a problem with HDMI port.

### ISSUE THREAD

**Issue by HeartAndSoul001** [acidanthera/bugtracker#787]
My laptop is x1 carbon 2017 which has HD620 graphics and working on Clover now. After update the Clover to v5107 and all kexts to the newest version, I upgrade the macOS 10.15.4 and my HDMI port has no signal when wake up. it does not work until unplug and plug the cable (it worked well before the system upgrading).

**Comment by vandroiy2013** [comment]
https://github.com/acidanthera/bugtracker/issues/783

**Comment by HeartAndSoul001** [comment]
> #783

I have follow the solution in #783, but do not work

**Comment by joker-fu** [comment]
+1  macos 10.15.14
