### ISSUE TITLE
CMOS error starts after update to 10.15.4?

### ISSUE THREAD

**Issue by telepati** [acidanthera/bugtracker#788]
Hi, after update to 10.15.4 CMOS error starts to come. Normally OpenCore RTC checksum patch working on 10.15.3 but this patch doesn't work anymore. I also tried RTCMemoryFix.kext this kext also doesn't affect anything. I think something changed in AppleRTC.  

This issue also mentioned here;
https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/issues/61

![1807803870_ScreenShot2020-03-25at03_53_43 png caed39256ea707d8148f9db5264a98f8 png 37e196a087415f674c3855644e23ecc1](https://user-images.githubusercontent.com/3812286/77652953-224a1980-6f80-11ea-9d6e-a262cf485dc8.png)
![2078720008_ScreenShot2020-03-26at15_30_35 png e573ac47a32bf6eb8e0c62426514e967](https://user-images.githubusercontent.com/3812286/77652955-24ac7380-6f80-11ea-84bb-3225183bbe58.png)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/765

**Comment by vit9696** [comment]
You can use RTCMemoryFix to exclude ranges, it does not do anything by default. It is indeed likely that AppleRTC now updates data besides the checksum, which the patch removes.
