### ISSUE TITLE
AppleIntelInfo.kext

### ISSUE THREAD

**Issue by nmano0006** [acidanthera/bugtracker#792]
Hi Acidanthera
I need to update AppleIntelInfo.kext.
Because Piker-Alpha not update last 2 years.I was try   insanlymac for update AppleIntelInfo still not success.
My CPU Intel Core i9 9980XE not support yet.
If you can please update.
Thank you for your support.

https://github.com/Piker-Alpha/AppleIntelInfo

**Comment by vit9696** [comment]
Why do you come with random questions to our bugtracker? If anything, I believe the most active fork is https://github.com/headkaze/AppleIntelInfo.
