### ISSUE TITLE
VoodooPS2 (Rehabman and also VoodoInput version) is not working on Thinkpad X220

### ISSUE THREAD

**Issue by HoshiYamazaki** [acidanthera/bugtracker#795]
[opencore-2020-03-31-184524.txt](https://github.com/acidanthera/bugtracker/files/4411466/opencore-2020-03-31-184524.txt)
[opencore-2020-03-31-191357.txt](https://github.com/acidanthera/bugtracker/files/4411467/opencore-2020-03-31-191357.txt)
[opencore-2020-03-31-200419.txt](https://github.com/acidanthera/bugtracker/files/4411468/opencore-2020-03-31-200419.txt)

Hello, so I managed to get debug logs from my Thinkpad (for some reason it does hang on blackscreen after debug boot prints - and it works if I disable logging).

First file is non-debug VoodooPS2 and VoodooInput, second and third is non-debug RehabMan version from different boots.
I am going to sleep, hope it helps fixing bugs, I will provide more data soon.

**Comment by Andrey1970AppleLife** [comment]
There is no kext plug-ins in config.plist

**Comment by HoshiYamazaki** [comment]
> There is no kext plug-ins in config.plist

Sorry, maybe I'm dumb or something, but I don't quite understand, there are kexts included in config.plist, and sorry I was busy and tired yesterday so I don't noticed that:
First and second file is Rehabman version (`184524` and `191357`).
Third is VoodooPS2 and VoodoInput (`200419`).

You can see that in 200419 file you have loaded VoodooInput and VoodooPS2:
```
05:047 00:053 OC: Prelink injection VoodooInput.kext (Interface) - Success
05:065 00:017 OC: Prelink injection VoodooPS2Controller.kext (Touchpad/Keyboard) - Success
```

I consider it as not-implemented functionality or/and bug, so I think you should open issue again.

**Comment by vit9696** [comment]
There is no bug. If you open VoodooPS2Controller.kext, you will see that it has several nested kexts in Plug-Ins directory. For whatever reason you forgot to include them in them in config.plist.

**Comment by HoshiYamazaki** [comment]
> There is no bug. If you open VoodooPS2Controller.kext, you will see that it has several nested kexts in Plug-Ins directory. For whatever reason you forgot to include them in them in config.plist.

Ahh, I understand now. Because I was using Clover in old times year/two ago I considered that VoodooPS2Controller does load them automatically using some built-in logic.

Sorry for disturbing though, thanks! I will test it soon since I'm at work now.
