### ISSUE TITLE
VoodooPS2 2.1.3 caused kernel panic Thinkpad T440P

### ISSUE THREAD

**Issue by momodding** [acidanthera/bugtracker#797]
i have thinkpad T440P with T450 touchpad installed. Got this kernel panic when using voodoops2.kext version 2.1.3

![photo6061953937663175033](https://user-images.githubusercontent.com/22990424/78138818-bd943080-7451-11ea-93ad-50a8ecd21009.jpg)

**Comment by vit9696** [comment]
There is ACPIPlatform in the kernel panic log but no trace of VoodooPS2. Might be some configuration issue, closing as invalid.
