### ISSUE TITLE
MaciASL Patching Syntax Grammar

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#799]
Hi there. I've ever wondered about MaciASL patching grammar syntax. I know that there's this "old" [url](https://sourceforge.net/p/maciasl/wiki/Patching Syntax Grammar/)  but I find it a little bit difficult to study for someone. Do you have any resources? As per now the unique method I've found is taking other patches and analyzing them empyrically 🙂

**Comment by vit9696** [comment]
Unfortunately we do not have anything in particular. I will leave the issue open in case somebody contributes something.

**Comment by dreamwhite** [comment]
Well, I've wrote a little documentation about MaciASL patching grammar syntax:

### remove_entry syntax

For example, in order to replace the content of a ACPI method the patching grammar syntax is:

`into method label $METHOD_NAME parent_label $ACPI_PATH remove_entry;`
 
e.g. removing content of `_DSM` method of `SATA` ACPI device

`into method label _DSM parent_label SAT0 remove_entry;`

### insert syntax

Let's assume for example that you need to add some ACPI code inside a path. 
The syntax is 

`into device label $DEVICE_NAME insert begin
//AML Code
end;`

This is just a part of what I'm still writing. Hope it can be useful for someone :)

**Comment by vit9696** [comment]
I included the suggested samples in [PATCH.md](https://github.com/acidanthera/MaciASL/blob/master/PATCH.md). Please submit other improvements as pull-requests.
