### ISSUE TITLE
[Suggestion] Guide for extracting BIOS payload

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#801]
As per title, I haven't found any guide which really explains how to extract BIOSes for unlocking CFG Lock, as explained on @khronokernel [guide](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/extras/msr-lock).

Actually I've found that the BIOS extraction process is slightly different than "open it with UEFITool" as some BIOSes are encrypted (INNO based or some InsydeFlash). 

As per now I've found the steps for extracting Dell BIOSes, which you can analyze it [here](https://github.com/dreamwhite/bios-extraction-guide)

For ASUS, ASRock, MSI, Gigabyte the step is only "extract the zip lol"
For HP, you need a Windows environment and after opening the BIOS Upgrade package select "Copy file on a different folder"

Some vendors as Xiaomi and Samsung have encrypted BIOS which, at least per now, I didn't managed to decrypt.

Hope this will help someone unlocking his CFG Lock.

Special thanks goes to @1alessandro1 and @Gengik84 for initial input :)

**Comment by vit9696** [comment]
Well, this is currently out of the scope of our products. I guess you can consider writing it and contributing it somewhere.
