### ISSUE TITLE
[Question] OpenCore patching criteria

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#802]
I was wondering about OpenCore patching criteria, as it currently patches every OS with renames, and SSDTs. Do you think that a `If _OSI("Darwin")` may solve this problem? Thanks and sorry for stupid question.

P.S. when will OpenCore patch only macOS and not Windows and Linux? Right now there's only this [fork](https://github.com/n-d-k/OpenCorePkg) which has `- ACPI patches and Booter Quirks are optional for non macOS with setting ACPI->Quirks->EnableForAll / Booter->Quirks->EnableForAll to yes (default is no).`. Will OpenCore ever support this Quirk?

**Comment by vit9696** [comment]
> I was wondering about OpenCore patching criteria, as it currently patches every OS with renames, and SSDTs. Do you think that a If _OSI("Darwin") may solve this problem? Thanks and sorry for stupid question.

Yes.

> P.S. when will OpenCore patch only macOS and not Windows and Linux? Right now there's only this fork which has - ACPI patches and Booter Quirks are optional for non macOS with setting ACPI->Quirks->EnableForAll / Booter->Quirks->EnableForAll to yes (default is no).. Will OpenCore ever support this Quirk?

This is a harmful feature, but the authors of the fork do not listen to our requests to remove it. See [this post](https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2675604). Very likely never.

**Comment by dreamwhite** [comment]
Oh very nice. Just two questions:

1. `2) No, I just use the OSDW﻿ switch to implement macOS only changes`

Does this user refers to my previous quote:
> `If _OSI("Darwin")`
Right? 

2. Let's assume that I need to [patch battery](https://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/) for being correctly detected by macOS. In windows can I have any battery problem if I patch the fields without using `If _OSI("Darwin")`?

**Comment by vit9696** [comment]
1. Roughly, OSDW is a common ACPI thing created by vendors, while OSI is defined in ACPI specification.

2. No idea.

**Comment by williambj1** [comment]
@dreamwhite What's wrong with using `_OSI`? Battery SSDT patches (even ones for dual batteries) work perfectly in OpenCore with `_OSI` and returns controlled by `If` & `Else`, I could provide some samples if you want, but I'm not allowed to post them not here. So far I haven't experienced any patches that can't be adjusted to support multi OSs.

**Comment by dreamwhite** [comment]
Yeah, my question was simply a doubt that had arisen for multiple OSs. I can assume that the SSDTs should be changed to `If _OSI("Darwin")` for example for plugin-type or whatelse. Right?

**Comment by williambj1** [comment]
Some `_DSM` properties are fine to be left in multi OSs like plugin-type since other OSs simply won't utilize them. Of course, you could add `If` statements if you want to ensure there's no influence at all.

I think it's better not to discuss here anymore since this is not a bug of any project rather than a request of help, conversation lockdown would occur at any time, feel free to continue the discussion by opening an issue in any of my repos.

I highly admire the time and effort developers made here.
