### ISSUE TITLE
[Feature Request] Keyboard shortcut to see OpenCore boot menu.

### ISSUE THREAD

**Issue by tylernguyen** [acidanthera/bugtracker#807]
Usually, I like to hide OpenCore boot options for a clean boot experience. On occasions, however, it would be very useful for a shortcut to reveal boot menu. This would allow for easier dual booting as well as a convenient option to clear NVRAM while also leaving the boot experience clean.

**Comment by Andrey1970AppleLife** [comment]
Use opt/esc, see docs.
