### ISSUE TITLE
OC: "Resources" folder should be inside the "OC" folder but not in the same Dir under "EFI"

### ISSUE THREAD

**Issue by williambj1** [acidanthera/bugtracker#809]
Hello developers!

In today's (April 6, 2020) latest release of OpenCore, a new folder called `Resources` was included but I think it's not in the correct directory.

According to OpenCore's Reference Manual, the `Resources` folder should be inside the `OC` folder.

https://github.com/acidanthera/OpenCorePkg/blob/05e3b1434359f6dc1b53484f3d16a50e76e19e6c/Docs/Configuration.tex#L379-L402

However, in today's release, it was placed like this:

![image](https://user-images.githubusercontent.com/45396585/78568460-bb1c4700-7854-11ea-9fca-8bc661fa2349.png)

I think those lines in **macbuild.tool** caused the issue:

https://github.com/acidanthera/OpenCorePkg/blob/05e3b1434359f6dc1b53484f3d16a50e76e19e6c/macbuild.tool#L24-L27

However, if it's designed to be like this I would certainly disagree with it, this somehow provides misleading information to the users and causes great confusion.

CC @vit9696

**Comment by Andrey1970AppleLife** [comment]
Fixed https://github.com/acidanthera/OpenCorePkg/commit/13ab95b1e9b27af850afdf5fceb5631668631d24
