### ISSUE TITLE
[Question] SMBIOS fields Clover vs OC

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#812]
Hi there, I was just wondering if all the fields that are inside a usual Clover config.plist are necessary. Inside a Clover config.plist i can see many fields that in OC aren't needed such as

- `Firmware Features `
- `Firmware Features Mask`
- `Efi version`

etc...

Are those fields needed in a normal installation of OC?
Below a screenshot of Clover config.plist SMBIOS section

![image](https://user-images.githubusercontent.com/17933708/78592497-789f3e00-7845-11ea-8e22-1a28f5255ac1.png)

And below a screenshot of OC PlatformInfo taken from @khronokernel 2 gitbook (which is pretty the same of Clover SMBIOS section)

![image](https://user-images.githubusercontent.com/17933708/78592814-f5321c80-7845-11ea-98c0-d87ccc5bc9e6.png)

**Comment by Gengik84** [comment]
OpenCore does it automatically with "Generic" and Automatic YES.

**Comment by dreamwhite** [comment]
Many thanks :)
