### ISSUE TITLE
SSDT-PLUG: 'Cannot override' error

### ISSUE THREAD

**Issue by Download-Fritz** [acidanthera/bugtracker#814]
The [new SSDT-PLUG table](https://github.com/acidanthera/OpenCorePkg/commit/8cffb55430986006345d707e3a0330d63d072e5b#diff-54c89640d1dc65359dfb3b3b41d934e2) that features multiple conditional device overrides seems to be causing macOS boot issues on at least one device. The related AppleACPIPlatform errors can be found here: https://www.hackintosh-forum.de/attachment/133089-fehler-png/

CC @Gengik84

**Comment by foskvs** [comment]
I would replace DeviceObj with ProcessorObj in the external declarations.

**Comment by vit9696** [comment]
Sounds good, could anybody submit a pull-request?

CC @Gengik84

**Comment by Gengik84** [comment]
@vit9696 Done
Thx
