### ISSUE TITLE
[VoodooPS2] TrackPoint and three buttons don't work after wake

### ISSUE THREAD

**Issue by Auva-Z** [acidanthera/bugtracker#816]
Hello!
My Thinkpad's TrackPoint and three physical buttons works fine when first boot, but they don't work after wake mostly. Trackpad works perfectly with three finger gestures.

Here's my setup: 
Thinkpad X230
macOS Catalina 10.15.3
VoodooPS2Controller 2.1.3
already used the "SSDT-Thinkpad_Trackpad"

When the TrackPoint and three buttons don’t work after wake, I got these in the console:
```
VoodooPS2Trackpad: sending final init sequence...
VoodooPS2 w: 0
IS THINKPAD
buttons 0
```
or just stuck at VoodooPS2Trackpad: sending final init sequence... after I do sleep and wake several times like this:
```
16:30:00 VoodooPS2Trackpad: sending final init sequence...
16:40:00 VoodooPS2Trackpad: sending final init sequence...
16:50:00 VoodooPS2Trackpad: sending final init sequence...
```
I noticed these when TrackPoint worked after wake in console:
```
VoodooPS2Trackpad: sending final init sequence...
VoodooPS2 w: 3 (or 4)
IS THINKPAD
buttons 0
```
That's all information I can get, please let me know if you need detailed logs(I don’t know where to get them).
It seems a bug to me and I think I need to let you know about it.
It would be great if you can fix it(if it is a bug). 

Thank you for your great work on multi finger gestures!!

**Comment by grivenDE** [comment]
I have the exact same situation on a ThinkPad S240 Yoga

**Comment by crazyi** [comment]
It is the same on my ThinkPad T450s

**Comment by findyy99** [comment]
@crazyi try VoodooRMI

**Comment by vit9696** [comment]
Note this issue: https://github.com/acidanthera/bugtracker/issues/1192. Perhaps you also need to adjust the wake delay for your touchpads (has different name from ELAN, but otherwise all the same).
