### ISSUE TITLE
NVMeFix 1.0.2 : I didn't found my ssd (PM981) drive on installation.

### ISSUE THREAD

**Issue by tanghxch** [acidanthera/bugtracker#819]
Hi, I have used your nvmefix kext that you released 3 days ago. (1.0.2)
it not kernel panic at all. but , when i open disk utility to manage my partition on pm981 drive.
it didn't appear. i saw only usb drive. how do i fix that ?

**Comment by frbuccoliero** [comment]
Try clicking in the top left corner "View" and then "Show All Devices"

**Comment by tanghxch** [comment]
> Try clicking in the top left corner "View" and then "Show All Devices"

I already did it. but it doesn’t show anything more. It works for pm981a ?

**Comment by frbuccoliero** [comment]
The trick should work for any drive. At this point all i can tell you is to ensure the drive is correctly installed. Maybe give a shot of "diskutil list" in the terminal to see if it gets recognized there.

**Comment by tanghxch** [comment]
> The trick should work for any drive. At this point all i can tell you is to ensure the drive is correctly installed. Maybe give a shot of "diskutil list" in the terminal to see if it gets recognized there.

I already did it so. I think it doesn’t recognized but when i take kexts out. It’s recognized.

**Comment by frbuccoliero** [comment]
Which kext? NVMeFix? If you boot with the kext the drive doesn't get recognized and if you boot without the kext it does??

**Comment by tanghxch** [comment]
> Which kext? NVMeFix? If you boot with the kext the drive doesn't get recognized and if you boot without the kext it does??

Yes

**Comment by frbuccoliero** [comment]
It doesn't make any sense. Try adding this patch: https://github.com/acidanthera/bugtracker/issues/780#issuecomment-602528879

**Comment by tanghxch** [comment]
> It doesn't make any sense. Try adding this patch: [#780 (comment)](https://github.com/acidanthera/bugtracker/issues/780#issuecomment-602528879)

I’m use clover. Not opencore.

**Comment by frbuccoliero** [comment]
I can't help you further more. Post your boot log and maybe your EFI and wait for someone else to help you

**Comment by 07151129** [comment]
This does not make sense. `diskutil list` should always show all the disks. Besides, NVMeFix doesn't touch the `built-in` properties at all.

Can you post the output of `diskutil list` and `mount`? What does System Information.app show for NVMe?

**Comment by tanghxch** [comment]
> This does not make sense. `diskutil list` should always show all the disks. Besides, NVMeFix doesn't touch the `built-in` properties at all.
> 
> Can you post the output of `diskutil list` and `mount`? What does System Information.app show for NVMe?

I already solved it now. Thanks. 
But it doesn’t fix for me.
It still loop restart.
