### ISSUE TITLE
Secondary screen gets green awakened from sleep

### ISSUE THREAD

**Issue by SCUTJcfeng** [acidanthera/bugtracker#820]
![WechatIMG17](https://user-images.githubusercontent.com/14869384/78812106-bdc78b00-797f-11ea-9097-481fb9b7405d.jpeg)

I just left for about 10 minutes, the system went auto sleep. After a while, I woke my system and my secondary screen became green.(main screen was normal)

Main screen uses a dp cable, secondary screen uses a hdmi cable.

I tried to turn it off and on, and the green is gone. Since I don't have iGPU, so may be that's related to whatevergreen.

Because I just built the system at about a day or two, this wired thing just happen once, and I could not repeat it.

Below info hope helps.

item|version
---|---
OC|0.5.6
apple support pkg|2.1.6
amd kext patch|release day 3.18
kext VirtualSMC.kext|1.1.1
kext Lilu.kext|1.4.2
kext WhateverGreen|1.3.7
kext AppleALC|1.4.7
kext RealtekRTL8111|2.2.2
CPU | 3800x
GPU | 5700xt

**Comment by 07151129** [comment]
Can you force override colour format to R8G8B8 for the display?

**Comment by SCUTJcfeng** [comment]
> Can you force override colour format to R8G8B8 for the display?

Sorry，can't figure out how to override color format to R8G8B8.

**Comment by 07151129** [comment]
Try `-rad24` bootarg
