### ISSUE TITLE
NVMefix 1.0.2 : it still don’t work for me on PM981

### ISSUE THREAD

**Issue by tanghxch** [acidanthera/bugtracker#821]
I copy nvmefix kexts to clover folder.
Then , i tried to install again.
First installation , it show “about 2 minutes” then restart.
Second installation , it show “about 12 minutes” then restart
I always get panic on second installation.

**Comment by 07151129** [comment]
It does work for our PM981 test machines. Without logs we cannot fix the problem, and it does not reproduce for us. Feel free to post panic log **with keepsyms on**, but it's unlikely we will be looking into this any time soon.

**Comment by codeli981** [comment]
Same error. Huawei magicbookproi5/Samsung PM981.Nvmefix 1.0.2 release and Lilu 1.4.3-Debug.Latest OpenCore distribution, MacOS 10.15.4. 
Here is my KP log at startup:
![KP log](https://user-images.githubusercontent.com/63401296/78888919-39672c00-7a95-11ea-9920-aec215f27da5.jpg)

**Comment by codeli981** [comment]
The firmware version of pm981 is EXA7301Q

**Comment by 07151129** [comment]
This panic has nothing to do with NVMe

**Comment by codeli981** [comment]
> This panic has nothing to do with NVMe

I changed Lilu to release, error change on this
![IMG_20200409_194614.jpg](https://i.loli.net/2020/04/09/j7tNVMih8kGvdrT.jpg)

**Comment by frbuccoliero** [comment]
This panic instead looks to have to do with NVMe and IONVMeFamily kext. It's now 3 of us still having problems with PM981 after 1.0.2 , i think something isn't working like the tests you did

**Comment by vit9696** [comment]
It is likely that we fixed the issues which affected the machines we had at hand. The issues you have imply that there are more potentially related issues, but we do not have a solution for them. Feel free to contribute patches if you are able to resolve the problem.

**Comment by 07151129** [comment]
> This panic instead looks to have to do with NVMe and IONVMeFamily kext. It's now 3 of us still having problems with PM981 after 1.0.2 , i think something isn't working like the tests you did

I was referring to the first screenshot. The second does refer to IONVMeFamily, but unfortunately it does not give us enough information about the error. Since we cannot reproduce the crash on our machines at all, we cannot really help.
