### ISSUE TITLE
[Possible BUG] Can't unlock CFG Lock

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#822]
Hi there, I'm trying to unlock CFG Lock on a Lenovo Ideapad S540-15IWL (i5-10210U). From BIOS dump I've found the CFG Lock offset: `0x3E`

Then inside modGRUBShell.efi used`setup_var 0x3E 0x00`. Below the value of `0x3E` which is `0x00` (so the patch is actually applied)

![IMG_20200409_042012_411](https://user-images.githubusercontent.com/17933708/78851209-860d2180-7a19-11ea-8b98-195f2cbcadca.jpg)

Then turned off the PC and rebooted to Clover. Opened VerifyMSRE2.efi from UEFIShell and that's the output:

![IMG_20200409_042017_751](https://user-images.githubusercontent.com/17933708/78851392-f9169800-7a19-11ea-9098-7a87f071f393.jpg)

![image](https://user-images.githubusercontent.com/17933708/78852861-c40c4480-7a1d-11ea-9514-dffa354d1428.png)

From AppleIntelInfo.kext I see that CFG Lock is `1 (MSR locked until next reset)`. 

What can it be?
Many thanks

P.S. I don't remember how, but I managed to reach the "Advanced" BIOS menu, as it contained CFG Lock option which could be disabled.

**Comment by dreamwhite** [comment]
Maybe that VerifyMSRE2 isn't tested for 10gen cpu? 🤔

**Comment by vit9696** [comment]
VerifyMsrE2 works correctly, it is the tool you use to unlock E2 register does not. Closing as out of the scope.

**Comment by dreamwhite** [comment]
Sorry for invalid issue: actually I've managed to reach the Lenovo BIOS Debug mode following those [instructions](https://github.com/daliansky/Lenovo-Air13-IWL-Hackintosh/blob/master/Advanced/ReadMe.md). Keep hackintoshing <3
