### ISSUE TITLE
"Use of undeciared identifier 'BaseDeviceInfo'" when building AppleALC 1.4.8

### ISSUE THREAD

**Issue by 2006bt** [acidanthera/bugtracker#823]
![Screen Shot 2020-04-09 at 5 06 55 PM](https://user-images.githubusercontent.com/26371176/78878621-43812e80-7a85-11ea-8e6a-ad478dbc1d69.png)

**Comment by vandroiy2013** [comment]
Update latest debug version Lilu.kext (from releases tab on GitHub) in AppleALC.master folder
