### ISSUE TITLE
[AppleALC]CX8070 - Lenovo i5-10210u layout15 - Sound Cannot be Muted

### ISSUE THREAD

**Issue by lietxia** [acidanthera/bugtracker#824]
Hello, I used FakePCIID_Intel_HDMI_Audio.kext and AppleALC.kext built-in speakers and hdmi audio works fine.
But the sound cannot be muted and Mute key not working.
Computer model: Lenovo XiaoXin Air14-2019 IML i5-10210u
Sound Card:CX8070
macOS: 10.15.4
AppleALC: 1.4.8
Lilu: 1.4.3
EFI: https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh
<img width="711" alt="Screen Shot 2020-04-09 at 22 04 14" src="https://user-images.githubusercontent.com/7046884/78906316-c8823d00-7ab1-11ea-95b4-92c5ef971387.png">

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
