### ISSUE TITLE
RebuildAppleMemoryMap migration issues

### ISSUE THREAD

**Issue by toirdgh** [acidanthera/bugtracker#828]
My system is a Dell Inspiron 3668 which has a Kaby Lake processor using a Skylake chipset (H110). I tried to migrate from EnableWriteUnprotector to RebuildAppleMemoryMap, SyncRuntimePermissions with no success. I tried various combinations with and without (EnableWriteUnprotector, RebuildAppleMemoryMap, SyncRuntimePermissions, SetupVirtualMap, ProtectUefiServices, DevirtualiseMmio). My system works fine with EnableWriteUnprotector and SetupVirtualMap but not without SetupVirtualMap. There are no kernel panics, it just stops at:

```
80:224 00:306 OCB: Perform boot Macintosh HD to dp PciRoot(0x0)/Pci(0x17,0x0)/Sata(0x0,0xFFFF,0x0)/HD(2,GPT,B068CFF9-24E8-4DA1-AF05-E6B89057C9B4,0x64028,0x746A2D60)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,22866391DE8F224B997C01FD9EBC9E8C)/\93A6FF80-D8F4-4DF3-A257-B3BA1A5550F8\System\Library\CoreServices\boot.efi (0/0)
80:254 00:029 OCB: Matching <> args on type 2 0
80:260 00:006 OCOS: OS set: <null> Mac OS X 10.12
80:266 00:005 OCOS: OS set: Apple Inc. Mac OS X 10.12
80:530 00:264 Trying XNU hook on System\Library\PrelinkedKernels\prelinkedkernel
80:614 00:084 Kext reservation size 9121792
82:011 01:396 Result of XNU hook on System\Library\PrelinkedKernels\prelinkedkernel is Success
82:028 00:016 OC: Read kernel version 17.7.0 (170700)
82:060 00:032 OCAK: PanicKextDump replace count - 1
82:065 00:005 OCAK: Patch success kext dump
82:100 00:035 OCAK: IOAHCIBlockStorageV1 replace count - 1
82:106 00:006 OCAK: Patch success com.apple.iokit.IOAHCIBlockStorage V1
82:115 00:009 OCAK: IOAHCIBlockStorageV2 replace count - 0
82:127 00:012 OCAK: Failed to apply patch com.apple.iokit.IOAHCIBlockStorage V2 - Not Found
82:142 00:014 OCAK: AppleIoMapper replace count - 1
82:147 00:005 OCAK: Patch success com.apple.iokit.IOPCIFamily AppleIoMapper
82:174 00:026 OC: Prelink injection Lilu.kext (Patch engine) - Success
82:191 00:017 OC: Prelink injection VirtualSMC.kext (SMC emulator) - Success
82:212 00:020 OC: Prelink injection WhateverGreen.kext (Video patches) - Success
82:235 00:022 OC: Prelink injection AppleALC.kext (Audio patches) - Success
82:247 00:011 OC: Prelink injection ATH9KFixup.kext () - Success
82:257 00:010 OC: Prelink injection BrcmBluetoothInjector_Mod.kext () - Success
82:276 00:019 OC: Prelink injection HibernationFixup.kext () - Success
82:307 00:030 OC: Prelink injection RealtekRTL8111.kext () - Success
82:321 00:014 OC: Prelink injection SMCProcessor.kext () - Success
82:337 00:016 OC: Prelink injection SMCSuperIO.kext () - Success
82:349 00:011 OC: Prelink injection USBPorts.kext () - Success
82:424 00:075 Prelinked status - Success
82:445 00:020 OCSMC: SmcReadValue Key 4D535463 Size 1
82:450 00:005 OCSMC: SmcReadValue Key 4D534163 Size 2
```
I have attached some files:
[MmapDump_pre.txt](https://github.com/acidanthera/bugtracker/files/4459175/MmapDump_pre.txt)
[MmapDump_post.txt](https://github.com/acidanthera/bugtracker/files/4459176/MmapDump_post.txt)
[opencore-2020-04-09-231243.txt](https://github.com/acidanthera/bugtracker/files/4459177/opencore-2020-04-09-231243.txt)

`Image 'FS1:\EFI\OC\Drivers\OpenRuntime.efi' loaded at 7A53C000 - Success`

Thank you.

**Comment by vit9696** [comment]
Just do not migrate if you cannot =)

**Comment by toirdgh** [comment]
Then I ask that whoever to clarify on the matter in your documentation. In the change log "Marked EnableWriteUnprotector as deprecated on modern systems" and in the configuration manual "Note: This quirk may potentially weaken firmware security, please use RebuildAppleMemoryMap if your firmware supports memory attributes table (MAT)." In the change log "Introduced RebuildAppleMemoryMap to fix macOS booting on Dell 5490" In the configuration manual "This quirk replaces EnableWriteUnprotector on firmwares supporting memory attributes table (MAT)."

What qualifies as a modern system?. OpenCore says my firmware supports MAT but said quirks do not work. Change log mentions specifically "Dell 5490" in regards to RebuildAppleMemoryMap but configuration manual does not mention a specific machine.

I'm not trying to be a picky and bothersome ass. I'm fine with sticking with my former configuration as long as it continues to work into the reasonably-distant future. But please keep your documentation consistent and coherent for all our sakes.

Thank you very much.

**Comment by Andrey1970AppleLife** [comment]
Your chipset H110 not modern.

**Comment by vit9696** [comment]
The fact that your firmware supports MAT does not immediately mean it will work fine. It may work with a correct set of quirks, but I do not care researching as it is a support request, not a bugreport. The documentation is correct and consistent.
