### ISSUE TITLE
Hangs at BIOS Logo when setting Target=83 after 0.5.7

### ISSUE THREAD

**Issue by Leoyzen** [acidanthera/bugtracker#831]
After upgrading to 0.5.7, I found booting hangs at BIOS Logo without any information after using latest opencore builds.

Some peoples confirms the issue.
Platform: kvm/qemu enviroment.

Here is the log, it just stuck at `OC: Driver OpenRuntime.efi at 0 is being loaded...`:
```
00:000 00:000 OC: OpenCore DBG-058-2020-04-10 is loading in Optional mode (0/0)...
00:051 00:051 OC: Boot timestamp - 2020.04.10 06:38:37
00:101 00:050 OCCPU: MP services threads 4 (enabled 4) - Success
00:157 00:055 OCCPU: MP services Pkg 1 Cores 2 Threads 2 - Success
00:210 00:053 OCCPU: Found Intel Xeon Processor (Skylake)
00:269 00:059 OCCPU: Signature 50654 Stepping 4 Model 55 Family 6 Type 0 ExtModel 5 ExtFamily 0 uCode 0
00:319 00:050 OCCPU: Hypervisor detected
00:370 00:050 OCCPU: VMWare TSC:  3600003000Hz,  3600MHz; FSB:  1000000000Hz,  1000MHz; BusRatio: 3
00:421 00:050 OCCPU: Detected Apple Processor Type: 05 -> 0501
00:478 00:056 OCCPU: CPUFrequencyFromTSC           0Hz     0MHz
00:543 00:064 OCCPU: CPUFrequency  3600003000Hz  3600MHz
00:594 00:051 OCCPU: FSBFrequency  1000000000Hz  1000MHz
00:648 00:053 OCCPU: Pkg 1 Cores 2 Threads 4
00:700 00:051 OC: OcLoadNvramSupport...
00:751 00:051 OC: Setting NVRAM 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:UIScale - ignored, exists
00:802 00:050 OC: Setting NVRAM 7C436110-AB2A-4BBB-A880-FE41995C9F82:boot-args - ignored, exists
00:853 00:050 OC: Setting NVRAM 7C436110-AB2A-4BBB-A880-FE41995C9F82:csr-active-config - ignored, exists
00:907 00:054 OC: Current version is DBG-058-2020-04-10
00:961 00:054 OC: OcLoadUefiSupport...
01:023 00:061 OCABC: RTDFRG 1 DEVMMIO 0 NOSU 0 NOVRWR 0 NOSB 0 NOHBMAP 0 SMSLIDE 1 WRUNPROT 1
01:075 00:051 OCABC: FEXITBS 0 PRMRG 0 CSLIDE 1 PRSRV 0 RBMAP 0 VMAP 1 APPLOS 0 RTPERMS 0
01:125 00:050 OCABC: Firmware has 2085587 free pages (512723 in lower 4 GB)
01:196 00:070 OCABC: Awaiting rendezvous with OpenRuntime r10
01:250 00:053 OC: Got 3 drivers
01:301 00:050 OC: Driver OpenRuntime.efi at 0 is being loaded...
```

**Comment by vit9696** [comment]
Better to indeed have these separate. In the other issue you mentioned that this happens in Target 83. Target 83 also logs to UEFI variable, maybe it is the problem. Does the same issue happen with target 76?

Are you sure you use the latest OVMF? Also, could you please provide us a way to debug this on macOS? I successfully use OVMF here when needed (see [this manual](https://github.com/acidanthera/OpenCorePkg/tree/master/Debug#qemu-configuration). Being able to reproduce your issue will make it a lot easier.

Also, could you try bisecting the issue.

**Comment by Leoyzen** [comment]
@vit9696 0x4C(76) is bootable, so it is the "UEFI variable logging" issues. I will try to bisect the weekends when I got time.

I'm using the OVMF from slackware(which unRaid use) libvirt 4.1.0, it is not the "latest"(which is 4.2.0) but quite newer.(I don't know how to get the specific version of OVME). The unRaid did not update the libvirt to 4.2.0 yet.

**Comment by Leoyzen** [comment]
@vit9696 After bisecting, I found it may related to commit https://github.com/acidanthera/OpenCorePkg/commit/707007e317dac64baef7d52a702f08f26d78d596.

It might relate to this line?
```
Status = FwRuntime->OnGetVariable (OcGetVariable, &BootCompat->ServicePtrs.GetVariable);
```

**Comment by vit9696** [comment]
Does reverting this change in current master resolve the problem?

**Comment by Leoyzen** [comment]
@vit9696 After reverting, yeah , it works, but quite laggy....(It doesn't make sense according to the changes by this commit.)

**Comment by Leoyzen** [comment]
BTW, what does "NVRam is full, can't logging" means?Whether it is related to the issue?

**Comment by vit9696** [comment]
NVRAM is full means that it can no longer log to NVRAM as there is no more storage in NVRAM. I would say try avoiding NVRAM without the big need.

**Comment by 82ghost82** [comment]
Hi, for me it is not possible also to boot with Target 65 (enable logging+logging to file).

**Comment by vit9696** [comment]
Fixed in master.
