### ISSUE TITLE
OpenCorePkg/Platform/OpenCanopy: gcc10 does not like ((unfinished|dead)?) code

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#834]
```
OpenCorePkg/Platform/OpenCanopy/Views/BootPicker.c: In function 'InternalBootPickerAnimateImageList':
OpenCorePkg/Platform/OpenCanopy/Views/BootPicker.c:1096:21: error: variable 'EntryIcon' set but not used [-Werror=unused-but-set-variable]
 1096 |   CONST GUI_IMAGE  *EntryIcon;
      |                     ^~~~~~~~~

```

**Comment by 1alessandro1** [comment]
Which method do you use to build OpenCore? 
Usually macbuild.tool is the recommended one... Are you using that for compiling?

**Comment by nms42** [comment]
> Which method do you use to build OpenCore?
> Usually macbuild.tool is the recommended one... Are you using that for compiling?

I am not building OpenCore per se. I am testing other toolchains.
