### ISSUE TITLE
Add support for QEMU emulated NVME device.

### ISSUE THREAD

**Issue by Leoyzen** [acidanthera/bugtracker#835]
I'm not quite sure whether it is a NVMEFix support issue, I will leave it here and if you don't think so, just close it.

QEMU and libvirt add NVME emulated device recently, I test it in Hackintosh and it won't work(hangs at the screen then Stop Sign appears).I'm wonderring if it possible to add support in NVMEFix?Or could you give some leads?

* opencore 0.5.8
* NVMEFix.kext and with -nvmefdbg enabled

```
    <qemu:arg value='-drive'/>
    <qemu:arg value='file=/mnt/user/domains/Catalina/system.beta.qcow2,format=qcow2,if=none,id=NVME1'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='nvme,drive=NVME1,serial=nvme-1'/>
```

<img width="1451" alt="截屏2020-04-11 11 53 36" src="https://user-images.githubusercontent.com/5518468/79034989-9a554800-7bec-11ea-8fce-35eef614aa28.png">

**Comment by 07151129** [comment]
Do you have any logs from the host side?

It looks like IONVMeController fails to get SMART log from the controller, which it uses to determine whether the media is in read-only mode. You can pass debug flag `nvme=0x20` to force ignore this (see NVMeFix readme), but this is probably a bad idea for production systems.

**Comment by Leoyzen** [comment]
@07151129 No, there is no extra log in host, and `nvme=0x20` isn't work for me.
Does it possible add such workaround for QEMU emulated SSD/NVME?

I couldn't find any info about the S.M.A.R.T impletement of QEMU.

**Comment by 07151129** [comment]
> nvme=0x20 isn't work for me.

That's weird because it definitely should. Does the kernel log change when you use it? Line 856 should not occur in it anymore if it is applied.

**Comment by Leoyzen** [comment]
@07151129 I'm not quite sure.Here is the log with nvme=0x20
![image](https://user-images.githubusercontent.com/5518468/79051222-9adbf600-7c61-11ea-868c-dfb7833f1f42.png)

**Comment by vit9696** [comment]
The fact that you have Couldn't alloc NVMeFix class in the log implies you have outdated NVMeFix and/or Lilu. Could you fix that and ensure it is still not booting?

**Comment by 07151129** [comment]
I do not think a new version would help if the issue is indeed what I suspect it to be.

For some reason, IONVMeFamily is not applying that flag. Here is the relevant code:

```
L_9:
    if ( this->vtable->__ZN16IONVMeController20CheckWriteProtectionEv(this)
      && !(gNVMeIgnoreInitErrors | gNVMeDebugFlags & 0x20) )
    {
      IONVMeDebugAssert(
        "AppleNVMe",
        "0 == (status)",
        "ReturnAsyncRequests",
        0LL,
        "/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.100.17/IONVMeController.cpp",
        856LL,
        0);
    }
    else
    {
      if ( this->vtable->__ZN16IONVMeController11IsPMEnabledEv(this) )
        this->vtable->__ZN16IONVMeController24GetDefaultRequestTimeoutEv(this);
...
```

The code tries to get write protection status from SMART, and if it fails, only proceeds if `gNVMeDebugFlags` is set, which is obtained by `NVMeGlobals::NVMeGlobals` reading boot-arg `nvme`. `NVMeGlobals::NVMeGlobals` is a part of `__mod_init_func`, so it is called prior to module start. So I believe you are doing something wrong, because in the log nothing has changed.

Can you alo set up UART interface for qemu so that we get textual logs? They are a lot easier to work with.

**Comment by Leoyzen** [comment]
@vit9696 @07151129 I'm using the latest Lilu/NVMEfix downloading from the github releases right now, it still the same(The log is the same as before).
I add such boot-args: `debug=0x144 keepsyms=1 -v nvme=0x20 -nvmefdbg`.

@07151129 I don't know how to add UART interface for hackintosh, I can't find much info.Could you give some links that I can catchup?

I will post my efi here so you can give it a shot.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4465341/EFI.zip)
Here is the log with the EFI:
![image](https://user-images.githubusercontent.com/5518468/79054078-a389f780-7c74-11ea-9a11-ee7e2cff1da5.png)

**Comment by Leoyzen** [comment]
Maybe opencore ignore to set nvram args?
![image](https://user-images.githubusercontent.com/5518468/79054149-11362380-7c75-11ea-92ad-451d35edb3bc.png)

**Comment by Leoyzen** [comment]
okay, after manually add the boot-args to nvram(why the boot-args weren't setting is a new question/bug?), the system boots with these logs:
[nvme.log](https://github.com/acidanthera/bugtracker/files/4465363/nvme.log)

**Comment by 07151129** [comment]
The log link is giving me error 404.

If the system is working, then the issue can be closed. In any case, it doesn't make sense for NVMeFix to address this, because this is a controller problem that cannot be feasibly fixed from our side.

**Comment by vit9696** [comment]
> why the boot-args weren't setting is a new question/bug?

Likely because you ignored the documentation regarding `Block`.
