### ISSUE TITLE
ALPS PS2 Support

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#836]
I have Dell E5450,

I can use VoodooPS2Controller.kext and VoodooInput.kext of Acidanthera. It works smoothly, even for 2 fingers and gestures.

My problem is Trackpad Preferences is not shown in System Preferences, can you fix this issue?? :)

I can see Touchpad Preferences if i used VoodooPS2Controller.kext of Brontex Branch for ALPS :)

**Comment by vit9696** [comment]
Not much I know, this is likely a macOS issue. Perhaps you need working bluetooth for it to show or similar.

**Comment by Andrey1970AppleLife** [comment]
The built-in trackpad Preferences is not shown, if no kext for battery or battery not defined in macOS.

**Comment by andreszerocross** [comment]
> The built-in trackpad Preferences is not shown, if no kext for battery or battery not defined in macOS.

Excuse me, i have wrotten above. If i used VoodooPS2Controller.kext of Bronxtext version (For ALPS) then Touchpad Preferences is shown, All ALPS PS2 Touchpad need Special VoodooPS2Controller.kext for ALPS.

Ofcourse my battery indicator is shown, there is no problem with battery indicator.

Please don't close this issue, i only ask if ALPS is supported or not. Because normally ALPS is not supported by normal voodooPS2Controller.kext of rehabman (no trackpad preferences)

**Comment by andreszerocross** [comment]
OLD Solution is use this kext https://github.com/SergeySlice/VoodooPS2-for-ALPS/releases from Slice or this kext https://osxlatitude.com/forums/topic/8285-refined-alps-touchpad-driver/

Then touchpad preferences will be shown.

I repeat, no problem with battery indicator :)

**Comment by vit9696** [comment]
@andreszerocross maybe you miss something? Old solution added a custom touchpad preference panel, current VoodooPS2 interfaces with the native trackpad preference panel:

![image](https://user-images.githubusercontent.com/4348897/79060028-2452ee80-7c89-11ea-8db6-d14bd3928c39.png)

**Comment by andreszerocross** [comment]
Then it mean, Current VoodooPS2Controller from Acidanthera still not full support for ALPS PS2 Touchpad :)

**Comment by vit9696** [comment]
Possible, I don't know. Only some synaptics touchpads are supported.
