### ISSUE TITLE
Add support for ITE IT8995E

### ISSUE THREAD

**Issue by QM-Nobody** [acidanthera/bugtracker#840]
Hi, IT8995E isn't supported in SMCSuperIO yet. I'm waiting for this since I moved from FakeSMC to VirtualSMC, so I can read/control the fan rpm. But no luck so far.
Can we expect this chip to be added anytime soon?
I can provide whatever information needed. Thanks.

**Comment by vit9696** [comment]
There is no datasheet for this chip. I updated https://github.com/acidanthera/bugtracker/issues/395 to also mention this particular ITE chip, but unless datasheets appear the support is unlikely.

**Comment by mishurov** [comment]
The same with **ITE IT8995VG-128 CX0**. Weirdly enough, the binaries from the package **lm-sensors** can't detect the SIO chip yet show fan's RPM.
