### ISSUE TITLE
PM981 kernel panic

### ISSUE THREAD

**Issue by mledour** [acidanthera/bugtracker#843]
Hi,

I'm having KP with PM981 and even more with NVMeFix 1.0.2
Tried with apst disabled and `ANS2MSIWorkaround` without success.

[lilu.log](https://github.com/acidanthera/bugtracker/files/4471627/lilu.log)
![20200413_215047](https://user-images.githubusercontent.com/1799422/79156444-317bf480-7dd3-11ea-8a15-1dfc89e3dea3.jpg)

**Comment by armenio** [comment]
Pm981 really working like a hell. I got success only installing/running 10.15.3. 
In this specific case, the big problem are the system startup needs some reboot loops with kp like the last screenshot.
No success when I try to install any other version (10.13.6, 10.14.x, 10.15.4)

**Comment by sonoseco** [comment]
I'm getting a similar kernel panic, what is strange is that I can sometimes boot, it just takes a while as if the device is timing out. However, my system would crash later while moving, copying files.

**Comment by vit9696** [comment]
https://github.com/acidanthera/bugtracker/issues/821#issuecomment-612136594
