### ISSUE TITLE
I use NVMeFix on PM981 worked on 10.15.2,but sometimes it will dead

### ISSUE THREAD

**Issue by herofolk** [acidanthera/bugtracker#848]
Hi there, I have successfully installed 10.15.2 on a ssd that is not pm981, and successfully driven the ssd of pm981 on clover using nvmefix 1.0.2 and lilu 1.4.3, but when I operate on the hard disk of pm981 Sometimes, it sometimes crashes, I do n’t know why, please take a look, the log is as follows.
<img width="1424" alt="Snipaste_2020-04-16_16-15-11" src="https://user-images.githubusercontent.com/15681326/79431802-800cd700-7ffd-11ea-8afa-59aa72ce2ef3.png">
[kernel_log.txt](https://github.com/acidanthera/bugtracker/files/4485636/kernel_log.txt)

**Comment by vit9696** [comment]
See https://github.com/acidanthera/bugtracker/issues/821

**Comment by herofolk** [comment]
@vit9696 I updated Lilu 1.4.3, but it does not work. Now I use ssdt-nvme.aml and HackrNVMeFamily, this way the PM981 will disable sometimes but will not crash.

**Comment by herofolk** [comment]
updated:
![image](https://user-images.githubusercontent.com/15681326/80355573-d6ee9800-88aa-11ea-83d5-5a7db877f35b.png)
Do you give up this pm981?
