### ISSUE TITLE
OpenCore loads Windows from incorrect path.

### ISSUE THREAD

**Issue by hameerabbasi** [acidanthera/bugtracker#849]
OpenCore seems to load the Windows EFI image from an incorrect path. I loaded it with OpenCore Debug with the debug target set, here's the full log (this is on 0.5.7 debug version):

[opencore-2020-04-16-132301.txt](https://github.com/acidanthera/bugtracker/files/4487386/opencore-2020-04-16-132301.txt)

This is the relevant line from the log:

```
07:595 00:016 OCB: Perform boot Windows to dp PciRoot(0x0)/Pci(0x17,0x0)/Sata(0x2,0xFFFF,0x0)/HD(1,GPT,04C5CC14-D769-4C3F-A104-94463B93F1AA,0x28,0x64000)/\EFI\BOOT\BOOTX64.EFI (0/0)
```

It should be loading `\EFI\Microsoft\Boot\bootmgfw.efi` IIRC.

**Comment by Andrey1970AppleLife** [comment]
\EFI\BOOT\BOOTX64.EFI it is a right way.
\EFI\Microsoft\Boot\bootmgfw.efi It is used only if OC and Windows set on one HDD, when Windows BOOTX64.EFI is replaced on on OpenCore BOOTX64.EFI.

**Comment by hameerabbasi** [comment]
Well, they are on the same SSD, even if I do have multiple in the machine.

**Comment by vit9696** [comment]
Please read the manual regarding BlessOverride and Windows installation. OC behaviour is correct and expected here: it is unaware of `\EFI\Microsoft\Boot\bootmgfw.efi` or any other path unless you explicitly specify it.
