### ISSUE TITLE
SMCSuperIO Panics shortly after login.

### ISSUE THREAD

**Issue by ReddestDream** [acidanthera/bugtracker#850]
On one out of every 20-50 or so boots (no clear reproducible pattern, but high CPU and/or many programs to open at login seems to make it more likely), I get a panic shortly after login causing instant reboot and involving SMCSuperIO. I have also seen SMCProcessor be involved but I do not have a panic with symbols showing this.

I have iStats Menu monitoring and displaying values that are provided by SMCSuperIO/SMCProcessor (CPU temp, fan speed, etc.). iStat Menus starts at login, and I have some suspicion it is involved in triggering this panic, tho it has been hard to proven given my difficulty reproducing the panic.

I have had this happen since 10.15 Release and it can happen on both Clover and OpenCore. I used SMCSuperIO/SMCProcessor on 10.14 and never had this panic.

Relevant Specs:

CPU: i7 7700K
Motherboard: Gigabyte Z270X-UD5 (I have modded the firmware to fix MSR 0xE2 issues)
*Note: This board has two SuperIOs, IT8686E and IT8792E, but only one of them is able to provide information in macOS via SMCSuperIO.*
GPU: AMD Radeon VII

I have also attached my redacted OpenCore config.plist. Please let me know if there's any other information I should provide. Thanks for all your hard work! :)

![SMCSuperIOPanic](https://user-images.githubusercontent.com/4013634/79465336-34d8d100-7fc9-11ea-89a7-2d3eb3ef8e00.jpg)

[Kernel_2020-04-16-094801_Master-Compy-DX.txt](https://github.com/acidanthera/bugtracker/files/4487599/Kernel_2020-04-16-094801_Master-Compy-DX.txt)

[config.plist.zip](https://github.com/acidanthera/bugtracker/files/4487663/config.plist.zip)

**Comment by vit9696** [comment]
I believe we fixed most of that in VirtualSMC 1.1.7 release. Forgot to close.
