### ISSUE TITLE
cannot go further than boot services

### ISSUE THREAD

**Issue by bomdurup** [acidanthera/bugtracker#851]
I am trying to run 10.15.4 on Thinkpad X1 Carbon 7th but opencore always stucks at boot services.
After spent almost a week, I am finally posting an issue. Hope I wasn't missing anythig.
Looked for simmilar issues like [https://github.com/acidanthera/bugtracker/issues/791](url) but didn't work.

*My configuration : 
-Model name : Thinkpad X1 Carbon 7th (late 2019, 20R1)
-Processor : Intel i7 10th Gen Comet Lake 10510u 4core 
-RAM : LPDDR3 16GB Onboard
-Using OC 0.5.7 DBG + Lilu + VirtualSMC 
-BIOS
  Security Chip DISABLED
  Fingerprint 	Predesktop Authentication DISABLED
  Wireless WAN DISABLED (since my model does not came with WWAN and also not supported)
  Fingerprint Reader DISABLED
  Secure Boot DISABLED
  Intel SGX Control DISABLED
  UEFI/Legacy Boot UEFI Only
  CSM Support No
( Unable to set XHCI Handoff, CFG Lock, Legacy RTC on BIOS )

```
........
258:984 00:179 OCSMC: SmcReadValue Key 4D535463 Size 1
259:160 00:176 OCSMC: SmcReadValue Key 4D534163 Size 2
259:339 00:178 AAPL: [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49
259:525 00:186 AAPL: [EB|#LOG:DT] 2020-04-16T23:15:56
259:707 00:181 OCABC: MMIO devirt start
259:884 00:177 OCABC: MMIO devirt end, saved 0 KB
260:924 01:039 AAPL: [EB|#LOG:EXITBS:START] 2020-04-16T23:15:57
```

*Things I've tried : 
First I tried without any SSDTs - stuck.
Added SSDT-AWAC / PMC - stuck, 
set cpuid - stuck,
set igpu id - stuck,
disabled CFG Lock via GRUB shell and disabled AppleCpuPmCfgLock, AppleXcpmCfgLock - stuck,
checked memory map but it looked okay.
tried enable/disable different combination of quirks such as AvoidRuntimeDefrag, DevirtualiseMmio, ForceExitBootServices, ProtectCsmRegion, RebuildAppleMemoryMap... - stuck
tried SSDT-USBX, enable/disabled Xhciportlimit quirk - stuck.

I still believe that I am doing something wrong but..... this might be a bug of opencore.

*Misc information
-EC name does not requied to be fixed - already declared as Device(EC).
-Windows 10 boots fine with opencore.
-I even tried Clover but It stucks at ++++ with every kind of memoryfix drivers including OcQuirks.
-Thinkpad x1 c6 / c7 with 8th gen cpu models are reported to be working with opencore...

Attached EFI with logs.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4488231/EFI.zip)

Here is memmap.
[memmap.txt](https://github.com/acidanthera/bugtracker/files/4488257/memmap.txt)

**Comment by Andrey1970AppleLife** [comment]
Don't enable DevirtualiseMmio, if MmioWhitelist empty.
Use forums for support.

**Comment by bomdurup** [comment]
I couldn’t get any replies from forums and also simmilar issues were reported but none worked out well. 
As mentioned above, I’ve tried both devirtualizemmio enabled/disabled.

**Comment by CrazyHulk** [comment]
@Andrey1970AppleLife Did you solve it？

**Comment by RotatingFans** [comment]
I am also having this issue. (X1 Yoga Gen 4, but very similar). Searching around online yields multiple people who cannot get MacOS to run on this device if it has the 10th gen chips. 8th gen are fine, as other other products in Lenovo's lineup. The memory map appears to be in good shape. @bomdurup 
I have disabled every device possible except for USB. I have tried the various memory quirks, Many different SSDT patches and kexts. I have used both OC-0.5.9 and Latest OC Snapshot.

**Comment by chenui** [comment]
I have the same issue. macOS sometimes can boot, sometimes stuck, whereas  win10 boots normally. So I pressed the reset button several times to boot macOS. Is this bug of opencore?

**Comment by robmagario** [comment]
I am having the same issue.

**Comment by hagenest** [comment]
I'm too having the same issue with the Thinkpad L13 Yoga with an i7-10510U
