### ISSUE TITLE
Partially hidden icons in OpenCanopy if ShowPicker is false

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#853]
Opencore version: developer, compiled as of today with latest commit [c9f4115](https://github.com/acidanthera/OpenCorePkg/commit/c9f4115a2b25badeb9eadecaf1aa1584f8572637)
Platform: kvm/qemu enviroment, version 4.2.

If ShowPicker is set to false icons seem invisible in Opencanopy.
Looking closer, it seems that icons are there but partially hidden.
See attached pictures for more details:

Icons seem invisible in OpenCanopy:
![1](https://user-images.githubusercontent.com/18054052/79541867-e55ad980-808a-11ea-8976-e1ce9e04f97f.jpg)

Icons are partially hidden:
![2](https://user-images.githubusercontent.com/18054052/79541911-f9064000-808a-11ea-985c-fa6919b47345.jpg)

Clicking on the icon results in the expected behaviour, so it should be only a graphical issue.

**Comment by zijun-he** [comment]
I have added a new USB mouse driver, ShowPicker = true / false are the same result.
The failure of my machine is that the icon is not displayed, and the mouse and keyboard do not produce the freezing phenomenon you reported yesterday.

**Comment by vit9696** [comment]
Partial workaround is in master. Will be addressed properly in more distant future.

**Comment by vit9696** [comment]
Will be further worked on as part of #759.

**Comment by zijun-he** [comment]
Adding the ignore ESC and returning to normal does not require an additional mouse driver. Thanks for solving the problem so quickly.
