### ISSUE TITLE
Problem on I7 1065G7

### ISSUE THREAD

**Issue by WECKLCIRO** [acidanthera/bugtracker#855]
Hello, I tried everything to install Catalina 10.15.4 on my laptop with i7-1065G7 processor but it always goes in kernel panic. I'm using opencore and if you want, I can send you my efi folder. What do you think about it? Is there any solution? Thank you.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/832
