### ISSUE TITLE
Implement bootstrap persistence

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#859]
Currently Windows installations and similar overwrite BOOTx64.efi, which can make OpenCore unbootable if Windows was installed on the same drive.

We should consider making a shallow copy of BOOTx64.efi in EFI\OC\Bootstrap\BOOTx64.efi, and provide an option to automatically register this option as top-most priority in OpenCore.

There is a nuance with Reset NVRAM feature. If we change nothing once it is called, the bootstrap image will disappear from the list of boot options, but I believe we want it to be here in case Windows already overwrote the image or the user prefers not to have BOOTx64.efi for his own reasons. Perhaps this needs to be additionally configurable. CC @Download-Fritz

**Comment by startergo** [comment]
Windows actually recreates bootx64.efi on major upgrade to a higher version. I have witnessed that after I renamed bootx64.efi.bac and pointed the booter to bootmgfw.efi in the config file. Windows UEFI booting through bootx64.efi is undesirable in cMP if for any reason it fails to boot through OC with protected NVRAM from certificate writing.

**Comment by dakanji** [comment]
>Windows actually recreates bootx64.efi on major upgrade to a higher version.

* Do you mean something like Win 8 to 10 or does this also impact some between some Win 10 updates?
* Does this happen if Windows is on a separate physical disk?
* I suppose this only affects UEFI Windows and not Legacy. Right?

**Comment by startergo** [comment]
Every UEFI version of Windows boots normally through bootx64.efi by default unless you or the boot loader specify boot loading elsewhere (i.e. bootmgfw.efi specified in the OC configuration) . Windows CSM/MBR is not supported by OpenCore so this is no relevant here.
