### ISSUE TITLE
NVRAM variable limit on OpenCore Legacy is too small

### ISSUE THREAD

**Issue by carlitossuper1** [acidanthera/bugtracker#860]
On Legacy OpenCore 0.5.8 (with emulated NVRAM) I can't add the fmm-mobileme-token-FMM variable because its lenght is 1422 bytes. 

The error I get is
`Setting NVRAM 7C436110-AB2A-4BBB-A880-FE41995C9F82:fmm-mobileme-token-FMM - Invalid Parameter `

My system doesn't have hardware NVRAM and thus I use nvram.plist

**Comment by vit9696** [comment]
Variable size increased to 64 KB in [acidanthera/DuetPkg](https://github.com/acidanthera/DuetPkg) branch.

**Comment by carlitossuper1** [comment]
Should I run the bootinstall.command again? Or just the latest compiled version of OpenCore?

**Comment by vit9696** [comment]
Both, but be warned that the new Duet is experimental and may have issues.

**Comment by carlitossuper1** [comment]
Thanks. I'll make an USB backup of my current OC just in case.

**Comment by carlitossuper1** [comment]
Indeed. I got a FAILURE TO BOOT with the latest BootInstall.command.

And by using the latest compiled OpenCore I still can't add the long variable to legacy NVRAM.

**Comment by vit9696** [comment]
FAILURE TO BOOT means \EFI\OC\OpenCore.efi was not found or failed to load. Perhaps your drive or filesystem were not recognised for some reason?

**Comment by carlitossuper1** [comment]
Disregard that. I recompiled OC again and the boot file was modified today. Used this updated boot file and everything works fine. I have Find My Mac enabled on Legacy NVRAM. 

Thanks!!!
