### ISSUE TITLE
[Feature Request] Provide Shutdown and Reboot Options in BootPicker

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#861]
Please consider providing Shutdown and Reboot Options in the BootPicker.

**Comment by vit9696** [comment]
What for? As you know, they are not in Apple's Boot Picker, and CTRL+ALT+DEL works fine anyway on most firmwares.

**Comment by dakanji** [comment]
Three strikes of of three! Sigh. 
I am on a really bad run of form.

OK, reason for request in my case is that some disk in PCI slot does not appear as option in BootPicker at random. When that happens, boot takes ages even if selecting another disk.

Currently, using the power button to recycle or `Reset NVRAM` as proxy for reboot resolves this. 

BTW, this is why why I got into a pickle after renaming BOOTx64 on the other item ... was using Reset NVRAM` as proxy for reboot as easier than reaching for power button.

**Comment by vit9696** [comment]
I don't know why you do not like using CTRL+ALT+DEL, but I added a tool, which allows you to do what you want.

**Comment by MacNB** [comment]
I have an Apple Magic keyboard. It cannot do CTRL+ALT+DEL from boot picker.
Thx for adding the reset feature.

**Comment by dakanji** [comment]
Is it possible to extend this feature to actually issue a reboot?

Not sure if my setup is working as it should, but when I use this with `ColdReset` for instance, the OpenCore BootPicker (I use text BootPicker and not OpenCanopy) goes off and comes back on.

However the drive that sometimes doesn't mount still is not mounted unless I physically shut down and restart or use ResetNVRAM.

Basically was hoping for an option to just reboot from OpenCore BootPicker unless that is what is supposed to be happening already.

**Comment by vit9696** [comment]
@dakanji that's exactly what happens, i.e. issuing a reboot. I am afraid that's your firmware doing something weird. Reset NVRAM must be behaving differently as we remove all the boot options, and thus your firmware needs to do full rescan of the hardware.

**Comment by dakanji** [comment]
Noted. Thanks for the response.

Yes, It doesn't actually shutdown at all ... The BootPicker just goes off and comes back on. 
Will look more into this.

**Comment by vit9696** [comment]
And what if you use `WarmReset`? Could you upload your firmware here?

CC @Download-Fritz

**Comment by dakanji** [comment]
OK. So I tested with WarmReset and with Shutdown and the outcome is the same.
[See Video](https://drive.google.com/open?id=1JfEzUNUEeV2_HwRH534pmpRiJbWizZoz)

> Could you upload your firmware here?
You mean my BootROM?

**Comment by vit9696** [comment]
Not necessarily your ROM (i.e. a dump), stock ROM will also do. Please attach a debug log of OpenCore. I need you to have a debug build of OC and the ResetSystem tool when making this log.

**Comment by dakanji** [comment]
Unfortunately I am unable to run the Debug version of v0.5.8. 

That from v0.5.7 works, there is a blank screen for a second after selecting the drive to boot and it then goes on to boot this. With v0.5.8, it never comes out of that blank screen.

On shutting down and getting back in via an alternative pathway, I see that the log file is created but it only contains a single line with: `00:000 00:000 OC: OpenCore DBG-058-2020-05-04 is loading in Optional mode (0/0)...`

**Comment by vit9696** [comment]
That is fine if it never comes back out of the black screen as it actually should not return to the main menu after failing to reboot (there is a CPU halt).

However, it is not fine that the debug log is not created:
- Could you please make sure that your Target contains 67?
- that you checked all the files created?
- that your text editor is not simply not showing other lines?
- Could you just attach all the files?
- Did the logging work before?

**Comment by dakanji** [comment]
Issue was with my `HaltLevel`. I had changed it from the `2147483648` I had in my v0.5.7 config to `2147483714` when upgrading as I thought I had made a mistake in v0.5.7 and that both `DisplayLevel` and `HaltLevel` were supposed to be the same. Not sure where I got that from.

Anyway, changed it to `2147483648` as I had in v0.5.7 and it works as should.

Will do the reset test now ... might even be that the result I got is related to this misconfiguration.

**Comment by dakanji** [comment]
Apologies ... false alarm.

I didn't copy in ResetSystem.efi to the tools folder when upgrading from v0.5.7. This coupled with the wrong HaltLevel setting gave the behaviour I saw.

**Comment by vit9696** [comment]
Right, we still need the logs though.

**Comment by dakanji** [comment]
The funny behaviour was when things where misconfigured and it is fine now.
Can you clarify what behaviour you want logged?

**Comment by vit9696** [comment]
Oh, did you mean that it reboots fine now? If so, no logs are needed indeed.
