### ISSUE TITLE
Force Touch emulation should be disabled in Recovery

### ISSUE THREAD

**Issue by usr-sse2** [acidanthera/bugtracker#863]
In Recovery there is no way to enable tap to click, so clicks should not be remapped to Force Touch.

**Comment by vit9696** [comment]
There is no reliable way to do this in macOS kernelspace. Lilu uses [heuristics](https://github.com/acidanthera/Lilu/blob/43ed557/Lilu/Sources/kern_start.cpp#L204-L208), which has worked without issues for some time though.

**Comment by usr-sse2** [comment]
acidanthera/VoodooPS2@4facc4384068d1ed47b5021eeb26a89c4f2dbd6d
