### ISSUE TITLE
Wrong address for Audio device for audio at boot

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#864]
Opencore version: developer, compiled as of today with latest commit [5e5ca3f](https://github.com/acidanthera/OpenCorePkg/commit/5e5ca3fb8b81ce062b2dc2ea87481dda6cf4a8fb)
Platform: kvm/qemu enviroment, version 4.2.

It seems that Opencore is not picking the right address for the audio device specified in the config.plist (goal is to play the boot chime).

gfxutil output for HDEF address:
```
./gfxutil -f HDEF
00:02.0 8086:1d20 /PCI0@0/HDEF@2 = PciRoot(0x1)/Pci(0x2,0x0)
```

HDEF is Ralink ALC899, 7 outputs (see attached HdaCodecDump --> from OpenShell), which I'm trying to use for audio at boot.
There's also NVIDIA HDAU from my GPU, 4 outputs.
[HdaCodecDump.txt](https://github.com/acidanthera/bugtracker/files/4504414/HdaCodecDump.txt)

config.plist (relevant parts):
```
		<key>Audio</key>
		<dict>
			<key>AudioCodec</key>
			<integer>0</integer>
			<key>AudioDevice</key>
			<string>PciRoot(0x1)/Pci(0x2,0x0)</string>
			<key>AudioOut</key>
			<integer>0</integer>
			<key>AudioSupport</key>
			<true/>
			<key>MinimumVolume</key>
			<integer>20</integer>
			<key>PlayChime</key>
			<true/>
			<key>VolumeAmplifier</key>
			<integer>1000</integer>
		</dict>
		<key>ConnectDrivers</key>
		<true/>
		<key>Drivers</key>
		<array>
			<string>HfsPlusLegacy.efi</string>
			<string>OpenRuntime.efi</string>
			<string>OpenCanopy.efi</string>
			<string>AudioDxe.efi</string>
			<string>UsbMouseDxe.efi</string>
		</array>
```

Note specified address: PciRoot(0x1)/Pci(0x2,0x0)

Full config.plist (serial number and system UUID redacted):
[config.txt](https://github.com/acidanthera/bugtracker/files/4504432/config.txt)

Opencore log (relevant part):
```
07:919 00:007 OCAU: System volume is 100 (calculated from 70) - Success
07:927 00:007 OCAU: Matching PciRoot(0x1)/Pci(0x2,0x0)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000)...
07:934 00:007 HdaCodecAudioIoGetOutputs(): start
07:941 00:007 HdaCodecGetSupportedPcmRates(): start
07:949 00:007 HdaCodecGetOutputDac(): start
07:956 00:007 HdaCodecGetSupportedPcmRates(): start
07:964 00:007 HdaCodecGetOutputDac(): start
07:971 00:007 HdaCodecGetSupportedPcmRates(): start
07:978 00:007 HdaCodecGetOutputDac(): start
07:986 00:007 HdaCodecGetSupportedPcmRates(): start
07:993 00:007 HdaCodecGetOutputDac(): start
08:000 00:007 OCAU: 1/2 PciRoot(0x0)/Pci(0x1,0x4)/Pci(0x0,0x1)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (4 outputs) - Success
08:007 00:007 HdaCodecAudioIoGetOutputs(): start
08:015 00:007 HdaCodecGetSupportedPcmRates(): start
08:022 00:007 HdaCodecGetOutputDac(): start
08:029 00:007 HdaCodecGetSupportedPcmRates(): start
08:037 00:007 HdaCodecGetOutputDac(): start
08:044 00:007 HdaCodecGetSupportedPcmRates(): start
08:051 00:007 HdaCodecGetOutputDac(): start
08:058 00:007 HdaCodecGetSupportedPcmRates(): start
08:065 00:007 HdaCodecGetOutputDac(): start
08:073 00:007 HdaCodecGetSupportedPcmRates(): start
08:080 00:007 HdaCodecGetOutputDac(): start
08:087 00:007 HdaCodecGetSupportedPcmRates(): start
08:095 00:007 HdaCodecGetOutputDac(): start
08:102 00:007 HdaCodecGetSupportedPcmRates(): start
08:109 00:007 HdaCodecGetOutputDac(): start
08:117 00:007 OCAU: 2/2 PciRoot(0x0)/Pci(0x2,0x0)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (7 outputs) - Success
08:124 00:007 OCAU: Cannot find specified audio device - Not Found
08:132 00:007 OC: Audio connection failed - Not Found
```

I think the issue could be in the address, because from the log I can read PciRoot(0x0) instead of PciRoot(0x1).
Full opencore log:
[opencore-2020-04-20-150502.txt](https://github.com/acidanthera/bugtracker/files/4504445/opencore-2020-04-20-150502.txt)

Thanks

**Comment by vit9696** [comment]
It sometimes happens that firmwares and macOS have different device paths. There is not much to do to this, just use the one the firmware sees. Also, please use three asterisks in a row instead of one to format the code (I edited your message to show how) as all the newlines are dead otherwise.

**Comment by 82ghost82** [comment]
Thanks for your suggestion, it worked well by changing the address as you suggested and sorry for the format, I will apply in future.
