### ISSUE TITLE
Cannot boot with log to file when audio at boot is activated

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#865]
Opencore version: developer, compiled as of today with latest commit [5e5ca3f](https://github.com/acidanthera/OpenCorePkg/commit/5e5ca3fb8b81ce062b2dc2ea87481dda6cf4a8fb)
Platform: kvm/qemu enviroment, version 4.2.

With logging to file enabled (for example Target 65 or Target 83) and audio at boot activated (chime) I cannot boot mac os: it stucks as soon after the tianocore logo.
Attached the log:
[opencore-2020-04-20-190308.txt](https://github.com/acidanthera/bugtracker/files/4505645/opencore-2020-04-20-190308.txt)

Latest line is:
```07:646 00:016 OCAU: File 59 for lang 18 is 32 2 2 (440576) - Success```

config.plist (UUID and serial redacted):
[config.txt](https://github.com/acidanthera/bugtracker/files/4505654/config.txt)

No problems to boot with Target 0.

**Comment by vit9696** [comment]
Does it work with the release version of AudioDxe?

**Comment by 82ghost82** [comment]
Yes, it works with AudioDxe 2.1.6 release version.

**Comment by 82ghost82** [comment]
Hi, sorry vit9696 to open agin this but it seems not solved with latest versions.
Same log, boot with Target 65.
[opencore-2020-04-23-102838.txt](https://github.com/acidanthera/bugtracker/files/4521908/opencore-2020-04-23-102838.txt)

Thanks

**Comment by vit9696** [comment]
Could you build OVMF with serial debugging and post the serial output from OVMF? See `-D DEBUG_ON_SERIAL_PORT=1`. https://github.com/acidanthera/OpenCorePkg/tree/master/Debug#qemu-configuration

**Comment by 82ghost82** [comment]
This is quite difficult for me, I'm very sorry, I will try to look more into details.
I'm running Unraid OS which includes QEMU, so at the moment I'm not sure how to setup the whole thing.
I will try to understand what I can do.

**Comment by vit9696** [comment]
You probably miss the point, the issue is not in the changes, but rather RELEASE/DEBUG builds. DEBUG builds have always been broken, RELEASE builds work "fine". For me AudioDxe driver does not start with QEMU, so I cannot really fix things for you. Use RELEASE version or provide logs from OVMF.

**Comment by 82ghost82** [comment]
Thanks for pointing it out, now it's more clear. I will try to understand more and provide more details if I will be able to.

**Comment by vit9696** [comment]
I actually added another safety check to OpenCorePkg:

```
[master 287289f] OcDebugLogLib: Do not attempt file logging at high TPL
 1 file changed, 8 insertions(+), 6 deletions(-)
```

I do not know whether it helps with your case, but it is worth checking.

**Comment by 82ghost82** [comment]
Fixed! Thanks
