### ISSUE TITLE
AppleALC disable 300 Series PCH HD Audio

### ISSUE THREAD

**Issue by mledour** [acidanthera/bugtracker#868]
Hi,

With AppleALC enabled HDMI Audio is not working, not recognized withing DCPIManager, except after wake but then it shows "null codec".

I tried without AppleALC and then I can get HDMI Audio is working.

The only way I've found to make AppleALC to work with HDMI Audio is by applying this patch using opencore:

```
<dict>
    <key>Base</key>
    <string></string>
    <key>Comment</key>
    <string></string>
    <key>Count</key>
    <integer>0</integer>
    <key>Enabled</key>
    <true/>
    <key>Find</key>
    <data>cJ0AAA==</data>
    <key>Identifier</key>
    <string>com.apple.driver.AppleHDAController</string>
    <key>Limit</key>
    <integer>0</integer>
    <key>Mask</key>
    <data></data>
    <key>MaxKernel</key>
    <string></string>
    <key>MinKernel</key>
    <string></string>
    <key>Replace</key>
    <data>SKMAAA==</data>
    <key>ReplaceMask</key>
    <data></data>
    <key>Skip</key>
    <integer>0</integer>
</dict>
```

Since I can get 300 Series PCH HD Audio natively I think AppleAlc break something and I shouldn't have to use AppleHDAController patch.

SYSTEM CONFIGURATION
Model: MSI GF-63 9RCX
CPU: Intel i7-9750H
GFX: Intel UHD 630 + Nvidia GTX 1050 (Disabled in macOS)
Audio: ALC269VC

macOS 10.15.3 - 10.15.4
Latest opencore, lilu, AppleALC, Whatevergreen

[Archive.zip](https://github.com/acidanthera/bugtracker/files/4517306/Archive.zip)

**Comment by vit9696** [comment]
AppleALC currently patches `70 9d` with `c8 9d`. This is what seems to cause issues here. Is it no longer needed with macOS Catalina? I think we had some discussion about it previously.

CC @Andrey1970AppleLife @lvs1974 @vandroiy2013

**Comment by lvs1974** [comment]
@mledour, could you provide us with ioreg, please?
We need to know exact device id of your audio device.

**Comment by mledour** [comment]
Her is my ioreg.
AppleALC disabled, without  kext patch, HDMI plugged-in and HDMI audio working.

[MacBookPro.zip](https://github.com/acidanthera/bugtracker/files/4518156/MacBookPro.zip)

**Comment by lvs1974** [comment]
@mledour, I need to have a look at your config.plist.
I have exactly the same audio controller: a348, and without AppleALC and patch, AppleGFXHDA is not loaded. What did you inject into HDAS device?

**Comment by mledour** [comment]
Only `layout-id` and `hda-gfx`. `hda-gfx` is needed without `AppleALC`.

[EFI.zip](https://github.com/acidanthera/bugtracker/files/4520751/EFI.zip)

**Comment by lvs1974** [comment]
I disabled AppleALC and disabled AppleHDController patch.
I also had to inject class-code=00030400 (subsystem-id=7E120000  and subsystem-
vendor-id=62140000 are optional) to make AppleGFXHDA be loaded.
hda-gfx = onboard-1 and layout-id=06000000.
Then I attached HDMI cable and saw this:
https://drive.google.com/file/d/1Zf0FLhF0KBO7gpqABHeCGBH_1ecTVoD2/view?usp=sharing

@mledour: do you have similar blinking or you have a normal video?
Actually, I have the same result if I use AppleALC + AppleHDAController patch.

**Comment by mledour** [comment]
No, I have normal video, everything is working find with AppleHDAController patch.

**Comment by vit9696** [comment]
Right. Well, we investigated the problem and here are the nuances:

- On some hardware (like the one @lvs1974 has) HDMI has serious glitches.
- AppleGFXHDA, which you get when you remove AppleALC, does not work with analog audio.
- AppleHDA, which works for both HDMI and analog audio, needs patches.

To avoid visual glitches we will not include the patch you mentioned in AppleALC, but you are indeed expected to add it to OpenCore to get both HDMI and analog audio to work, this is normal.
