### ISSUE TITLE
DRM on RX580

### ISSUE THREAD

**Issue by josemmc95** [acidanthera/bugtracker#871]
Netflix, ATV+, Disney+ etc working but Amazon Prime Video, HBO crash.

This is my current configuration:
iMac18,3 with headless configuration (0x59120003).
i5-7400
XFX RX580
shikigva=80

I tried with iMacPro1,1 with IGPU disabled from BIOS and all works but I lose Apple Watch unlock and Sidecar and I reverted to iMac18,3 with enabled IGPU and headless configuration.
Thank you in advance!

**Comment by vit9696** [comment]
That's Apple's issue.
