### ISSUE TITLE
Cannot properly initialize Oland GPU without first booting into Windows

### ISSUE THREAD

**Issue by Lacedaemon** [acidanthera/bugtracker#874]
Hello,

I have a FirePro W2100 [working almost perfectly in 10.15.4](https://i.redd.it/kyst0bs3jpu41.png).  The only weird thing is, it will not properly initialize without first booting into Windows.  I didn't want to believe it at first, but [I'm not the only one this has happened to](https://www.tonymacx86.com/threads/macos-catalina-restarts-with-amd-radeon-r7-250-card-no-signal-and-restarts.288159/page-3#post-2042704).

Right now I have [a FakeID implemented via SSDT](https://dortania.github.io/Getting-Started-With-ACPI/Universal/spoof.html).  I started with `radpg=15`, but I ended up going with [`radpg=255`](https://www.reddit.com/r/hackintosh/comments/cikqb9/have_trouble_getting_your_radeon_hd_7750_maybe/ev7clj7/).  The latter seems to work a little better to initialize both of my monitors at boot.

What's so special about Windows that it would be needed to properly initialize this GPU?  I'm certainly no expert but I feel like this GPU is 99% of the way and it just needs a small thing to be properly initialized.

I've attached my relevant files to this post.  Any advice would be appreciated!
[Debug.zip](https://github.com/acidanthera/bugtracker/files/4534401/Debug.zip)

**Comment by vit9696** [comment]
Out of scope. Use whatever works best for you. Also, it is not `CAIL_DisableDrmdmaPowerGating` but `CAIL, CAIL_DisableDrmdmaPowerGating` if you want to use `DeviceProperties`.
