### ISSUE TITLE
[Request] AppleALC support 

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#876]
Hi !
I want to request acidanthera dev's to add support for this on-board audio controller to AppleALC:

Name: [Azalia (Intel HDA)](https://devicehunt.com/view/type/pci/vendor/1002/device/4383)
Device-id: 4383
Vendor-id: 1002
Codec: ALC887
ACPI Device: SBAZ ( Device sits under PCI0 )
[getDump.txt](https://github.com/acidanthera/bugtracker/files/4539687/getDump.txt)

Specs:
AMD FX8320
ASUS M5A97 R2.0
RX 580
Opencore 0.5.7

I dont have much knowledge on this but before coming here, i tried few things on my end to try get it working:

- I have disabled the AppleALC controller patching by injecting `no-controller-patch`, so that i can patch AppleHDAController or AppleHDA manually from the opencore to save time from  compiling AppleALC etc. 

- I  got the AppleHDAController to load by replacing `86803E3A` with `02108343` but underlying IOHDACodecDevice in ioreg always shows empty.

![Screen Shot 2020-04-27 at 6 47 27 PM](https://user-images.githubusercontent.com/18463250/80376515-8cbfe380-88b7-11ea-9de2-d7c78916142d.png)
[iMacPro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/4539849/iMacPro.ioreg.zip)

-Thanks : )

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by naveenkrdy** [comment]
@Andrey1970AppleLife @vit9696 
Its an audio controller support add request to AppleALC . So i should post it in the forum ?

-Thanks !

**Comment by Andrey1970AppleLife** [comment]
Find the solution for yours AMD, by means of forums. We don't support AMD. You can send PullRequest if you find the solution.

**Comment by rektimus** [comment]
> Find the solution for yours AMD, by means of forums.

I have an Intel and I've tried reading through everything. It would be nice if you guys could accept there honestly isn't enough info for people to add their own layout. If this info actually existed less people would add these 'bugs'.
