### ISSUE TITLE
DuetPkg/BootInstall: Microsoft BCD auto-detection broken

### ISSUE THREAD

**Issue by kommtzeitkonrad** [acidanthera/bugtracker#878]
Until https://github.com/acidanthera/OpenCorePkg/commit/f21f3c329910f719e3e6378e998333057d544827 Microsoft BCD is automatically detected when booting with `DuetPkg` (log: [opencore-2020-04-27-235418.txt](https://github.com/acidanthera/bugtracker/files/4542831/opencore-2020-04-27-235418.txt)).
```
43:739 00:003 Trying to detect Microsoft BCD
43:746 00:003 OCB: Entry 0 is Windows at dp PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0)/HD(1,GPT,F729BC2E-FB67-4AFA-8C40-C6F288D47673,0x800,0x113000)/\EFI\BOOT\BOOTX64.EFI
```
Microsoft BCD is not auto-detected when using `boot` from https://github.com/acidanthera/OpenCorePkg/commit/75443ac52e2e76250f596381f023a296be360259 (log: bootlog: [opencore-2020-04-28-002943.txt](https://github.com/acidanthera/bugtracker/files/4542844/opencore-2020-04-28-002943.txt))

Setting `\EFI\Microsoft\Boot\bootmgfw.efi` in `BlessOverride` (`HideSelf=false`) is resulting in
```
OCBP: Predefined <nil> \EFI\Microsoft\Boot\bootmgfw.efi is missing - Not Found
```
although `bootmgfw.efi` can be successfully booted from `OpenShell` or by setting the pci path in `Entries` (log: [opencore-2020-04-28-004539.txt](https://github.com/acidanthera/bugtracker/files/4542856/opencore-2020-04-28-004539.txt)).

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/875

**Comment by vit9696** [comment]
This one is different, as it reproduces with the DEBUG version.

**Comment by Andrey1970AppleLife** [comment]
New Duet uses Bootstrap.efi, you can return BootX64.efi from Windows. There is no need in BlessOverride.

**Comment by vit9696** [comment]
New Duet loads OpenCore.efi directly without Bootstrap.efi, but I am not sure what happens here in the first place. Even if you add BlessOverride, you should still get BOOTx64.efi loading.

**Comment by vit9696** [comment]
BlessOverride is not relevant here. For working log your EFI partition contains `\EFI\BOOT\BOOTx64.efi`:

```
43:501 00:004 OCB: Found 6 potentially bootable filesystems
43:504 00:003 OCBP: APFS Volume Info is missing
43:508 00:003 OCBP: Blessed file is missing
43:511 00:003 OCBP: Blessed folder is missing
43:515 00:003 OCBP: Predefined <nil> \System\Library\CoreServices\boot.efi is missing - Not Found
43:518 00:003 OCBP: Predefined <nil> \EFI\APPLE\X64\BOOT.EFI is missing - Not Found
43:522 00:003 OCBP: Predefined <nil> \EFI\BOOT\BOOTX64.EFI was found
43:525 00:003 OCB: Filesystem 0 (1F852F98) named EFI (Success) has 1 entries
```

For not working log your filesystem seems to contain nothing:

```
19:913 00:004 OCB: Found 6 potentially bootable filesystems
19:917 00:003 OCB: Filesystem 0 (1F854A98) named EFI (Unsupported) has 0 entries
```

CC @Download-Fritz

**Comment by vit9696** [comment]
You have `HideSelf` enabled, and thus your Windows bootloader is skipped.

**Comment by vit9696** [comment]
Actually resolved in https://github.com/acidanthera/OpenCorePkg/commit/cbfbc3487f91adce014d11ffdc29051e95ccc0c4. HideSelf may have been accidentally enabled regardless of the config preference.

**Comment by kommtzeitkonrad** [comment]
> Actually resolved in [acidanthera/OpenCorePkg@cbfbc34](https://github.com/acidanthera/OpenCorePkg/commit/cbfbc3487f91adce014d11ffdc29051e95ccc0c4).

Using latest commits (https://github.com/acidanthera/OpenCorePkg/commit/bc61cb764d3acc3e9c2f538b625252a90c42c8bd & https://github.com/acidanthera/DuetPkg/commit/ef5b1759e0f55d811e3f9ffc964aaa29326d8764) with no entries under `BlessOverride`, `HideSelf` set to `False` and for all `Entries` `Enabled` set to `False`, OpenCore still tries to auto-detect Microsoft BCD, but fails.
```
04:313 00:003 Trying to detect Microsoft BCD
```
-> [opencore-2020-04-29-200717.txt](https://github.com/acidanthera/bugtracker/files/4554379/opencore-2020-04-29-200717.txt)

Setting `\EFI\Microsoft\Boot\bootmgfw.efi` in `BlessOverride` works now.

```
00:973 00:001 OCB: Performing OcScanForBootEntries...
00:975 00:001 OCB: Found 6 potentially bootable filesystems
00:977 00:001 OCBP: Predefined <nil> \EFI\Microsoft\Boot\bootmgfw.efi was found
.
.
.
01:099 00:001 Trying to detect Microsoft BCD
01:101 00:001 OCB: Entry 0 is Windows at \EFI\Microsoft\Boot\ (T:16|F:0)
01:103 00:001 OCB: Entry 0 is Windows at dp PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0)/HD(1,GPT,F729BC2E-FB67-4AFA-8C40-C6F288D47673,0x800,0x113000)/\EFI\Microsoft\Boot\bootmgfw.efi
```
-> [opencore-2020-04-29-201824.txt](https://github.com/acidanthera/bugtracker/files/4554431/opencore-2020-04-29-201824.txt)
> HideSelf may have been accidentally enabled regardless of the config preference.

This makes sense as it was disabled all the time (the information is a little bit hidden in https://github.com/acidanthera/bugtracker/issues/878#issue-607953734).

**Comment by vit9696** [comment]
What do you mean under fails? If none of the files mentioned in the log (see below) are present on your partition OpenCore will obviously not see anything on it be that Windows or not. Most likely if you want Windows to boot you need to recover `\EFI\BOOT\BOOTX64.EFI`.

```
03:624 00:003 OCBP: Predefined <nil> \System\Library\CoreServices\boot.efi is missing - Not Found
03:628 00:003 OCBP: Predefined <nil> \EFI\APPLE\X64\BOOT.EFI is missing - Not Found
03:632 00:003 OCBP: Predefined <nil> \EFI\BOOT\BOOTX64.EFI is missing - Not Found
03:636 00:003 OCBP: Predefined <nil> \boot.efi is missing - Not Found
```

**Comment by kommtzeitkonrad** [comment]
> If none of the files mentioned in the log (see below) are present on your partition OpenCore will obviously not see anything on it be that Windows or not.

Ok, now Ⅰ get it! Ⅰ thought that OpenCore just seeks for bootable `bootmgfw.efi` and then 'fails' for some unwanted reason.

Thank you for the explanation!
