### ISSUE TITLE
SMCBatteryManager 0 cycle battery count

### ISSUE THREAD

**Issue by kecinzer** [acidanthera/bugtracker#879]
I have problem with SMCBatteryManager.kext. It shows 0 cycle battery count. I think it's because kext is not attached to my battery device like ACPIBatteryManager.kext, that works perfectly.

![acpibatterymanager-ioreg](https://user-images.githubusercontent.com/1541555/80473092-f090ed80-8945-11ea-82d8-bdc1b348921b.png)
![smcbatterymanager-ioreg](https://user-images.githubusercontent.com/1541555/80473117-fb4b8280-8945-11ea-95dc-7b4b362b68f0.png)

Also attaching my EFI folder (with erased SMBIOS informations).

[efi.zip](https://github.com/acidanthera/bugtracker/files/4544763/efi.zip)

**Comment by RenAmamiya** [comment]
I also have this problem, and the battery information is not displayed completely, the cycle count is 0
<img width="1124" alt="截屏2020-04-29 下午8 40 37" src="https://user-images.githubusercontent.com/42382226/80597462-71410e00-8a5a-11ea-8e15-3d0e8eb632e4.png">
、
<img width="863" alt="截屏2020-04-29 下午8 40 46" src="https://user-images.githubusercontent.com/42382226/80597468-743bfe80-8a5a-11ea-8cb1-0e11926626db.png">


[NoctisdeMacBook Pro.zip](https://github.com/acidanthera/bugtracker/files/4551706/NoctisdeMacBook.Pro.zip)

**Comment by Mateo1234454545** [comment]
On my laptop , when using SMCBatteryManager.kext cycle count is 309.
If I change to ACPIBatteryManager.kext cycle goes down to 189.

I have another problem , too. Sometimes battery goes from 40% or so to 5-6% instantly. When that happens after a reboot battery health drops 10-15%. I'm not sure if this is a hardware problem or a SMCBatteryManager.kext related one.

**Comment by rottenpants466** [comment]
> On my laptop , when using SMCBatteryManager.kext cycle count is 309.
> If I change to ACPIBatteryManager.kext cycle goes down to 189.
> 
> I have another problem , too. Sometimes battery goes from 40% or so to 5-6% instantly. When that happens after a reboot battery health drops 10-15%. I'm not sure if this is a hardware problem or a SMCBatteryManager.kext related one.

Same happens to me too. I checked in linux and my battery degradation is only 5%.

I didnt create any acpi patches so maybe thats a problem.

Also apple is about to release some new battery manegement system with the new update so i dont know how that will work out for us :)

**Comment by rektimus** [comment]
> On my laptop , when using SMCBatteryManager.kext cycle count is 309.
> If I change to ACPIBatteryManager.kext cycle goes down to 189.

Do you have multiple batteries?

**Comment by Mateo1234454545** [comment]
> > On my laptop , when using SMCBatteryManager.kext cycle count is 309.
> > If I change to ACPIBatteryManager.kext cycle goes down to 189.
> 
> Do you have multiple batteries?

No.

**Comment by kecinzer** [comment]
No, only 1 battery.

**Comment by vit9696** [comment]
I believe you have incorrect ACPI, as the results imply you have multiple batteries (internal banks) and they are not merged. Closing as invalid.

**Comment by Mateo1234454545** [comment]
> I believe you have incorrect ACPI, as the results imply you have multiple batteries (internal banks) and they are not merged. Closing as invalid.

No, that's not the case.
I have only 1 battery.
You can check the debug for yourself.
[debug_6881.zip](https://github.com/acidanthera/bugtracker/files/4567834/debug_6881.zip)

**Comment by vit9696** [comment]
We do not support Clover, so whatever it is really.

**Comment by Mateo1234454545** [comment]
It is the same thing as with opencore.
Just I find it difficult to create a debug file with opencore.
I'm sending you some files to check again.
[debug.zip](https://github.com/acidanthera/bugtracker/files/4567856/debug.zip)

**Comment by kecinzer** [comment]
> I believe you have incorrect ACPI, as the results imply you have multiple batteries (internal banks) and they are not merged. Closing as invalid.

Ok, can you please push me little bit how to correct it?

**Comment by vit9696** [comment]
@Mateo1234454545 I see `BAT0` and `BAT1` in your DSDT, why do you convince me you have a single battery?

@kecinzer I believe you should follow the general guides regarding ACPI battery patches. The are many places for them, for instance, there is a relatively decent repository [in Chinese](https://github.com/daliansky/OC-little). You can of course translate it [with Google](https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fgithub.com%2Fdaliansky%2FOC-little).

**Comment by Mateo1234454545** [comment]
> @Mateo1234454545 I see `BAT0` and `BAT1` in your DSDT, why do you convince me you have a single battery?
> 
Wow! Never seen that before.
I need some help patching it.
Guide is too complicated for me and battery suddenly drop is driving me crazy.
Can you help me?
If it is too much work just ignore it.
Thank in advance.

**Comment by vit9696** [comment]
@Mateo1234454545 obviously not, as bugtracker is not a support forum. If you need help you are best to ask on insanelymac.
