### ISSUE TITLE
DuetPkg: Add OHCI Dxe proposal (better AMD based computers support)

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#880]
Could be imported from
```
edk2-platforms/Silicon/Intel/QuarkSocPkg/QuarkSouthCluster/Usb/Ohci/Dxe
```

**Comment by vit9696** [comment]
Could you tell us what real-world hardware needs it? Our DuetPkg does not try to be compatible with everything, and to be honest AMD support for macOS is rather shady in the first place.

**Comment by vit9696** [comment]
I believe it should be as follows:

- If the driver works out of the box, it should be submitted as a patch to MdeModulePkg in EDK II, and then used in our code.
- If the driver does not work out of the box, we can import it to DuetPkg and make the necessary modifications.

I am fine to merge this, but you will need to handle this on your own if you need it.

**Comment by nms42** [comment]
It was in edk2, then platform dependent parts (for qemu, intel, amd, ...) where moved to pertinent edk2-platforms/. The driver by itself works OOB. The question is there any need for it?

Probably, this issue can be kept open just for info where to find the driver?

**Comment by vit9696** [comment]
In my opinion, we should rather add this to documentation (`README.md`) rather than keep issues with unclear reasons. Added it to README file.
