### ISSUE TITLE
Lilu: Kernel Panic when using from OpenCore, works fine in /L/E

### ISSUE THREAD

**Issue by GoProgrammer** [acidanthera/bugtracker#881]
When injecting Lilu from OpenCore, it makes the system kernel panic. Using it from /L/E works.

My EFI folder: https://github.com/GoProgrammer/HP-Probook-430-G5-Hackintosh

OpenCore log: https://pastebin.com/raw/Eq8gXbRu

Lilu debug log: doesn't exist, kernel probably panics before the filesystem mounts.

I'm using FileVault if that matters.

Panic pic: https://i.imgur.com/CQ44JFR.jpg

Thanks!

**Comment by vit9696** [comment]
I do not see Lilu in your EFI folder, but the kernel panic means that you did not inject Lilu correctly (e.g. forgot to include the executable file) or your EFI file system is broken.

**Comment by GoProgrammer** [comment]
The EFI folder is exactly like this one except the Lilu kext is added, the executablepath and everything else is correct. Should I send *exactly* what i was using?

**Comment by vit9696** [comment]
Yeah, better do it, because currently it looks like a user error.

**Comment by GoProgrammer** [comment]
[lilu-panic-efi.zip](https://github.com/acidanthera/bugtracker/files/4547996/lilu-panic-efi.zip)

**Comment by vit9696** [comment]
HDAEnabler.kext? FakePCIID.kext? Wtf?

I do not see an immediate issue with your EFI folder, but try to remove kexts one by one to see when the panic becomes different or is resolved.

**Comment by GoProgrammer** [comment]
Stupid me had Lilu in /L/E too, solved!

Thanks!
