### ISSUE TITLE
BootCamp for Windows causes "OCB: Failed to match a default boot options" and fallback to Windows

### ISSUE THREAD

**Issue by SukkaW** [acidanthera/bugtracker#883]
I am using both macOS (Hackintosh, 10.15.4) and Windows 10 on ThinkPad E480, with NVRAM is native supported.

As suggested by OpenCore documents, I have BootCamp installed in Windows for rebooting to macOS from Windows.

The strange thing is, if I change my boot option inside macOS (using "Start Disk" inside System Preferences) **will not** cause "OCB: Failed to match a default boot options" and selected system will be booted. However, after I have used BootCamp's `reboot to macOS` or choose macOS inside BootCamp Panel under Windows, will resulted in OpenCore showing `OCB: Failed to match a default boot options`, and then the Windows will be booted.

Here are some of my OpenCore configurations that might be used to debug where the problem is:

- Misc - Picker Mode - External (I am using boot picker provided by OpenCanopy)
- Misc - AllowSetDefault - True
- Misc - BlessOverride - I have added `\EFI\Microsoft\Boot\bootmgfw.efi`
- NVRAM - LegacyEnable & Legacy Overwrite - False
- NVRAM - WriteFlash - False
- UEFI - Requedt BootVarFallback & RequestBootVarRouting - True

**Comment by vit9696** [comment]
A debug log will be needed for this. When rebooting from macOS and from Windows with the note what was chosen. Also, make sure you have the latest bootcamp version installed on Windows.

**Comment by SukkaW** [comment]
@vit9696 I do have latest BootCamp for Windows installed (even received & installed a recent update from Apple). The debug log from OpenCore will be provided later.

**Comment by SukkaW** [comment]
**From Windows to macOS, select with BootCamp under Windows**

[opencore-2020-05-01-063049.txt](https://github.com/acidanthera/bugtracker/files/4562758/opencore-2020-05-01-063049.txt)

(Then it booted into Windows)

[opencore-2020-05-01-063351.txt](https://github.com/acidanthera/bugtracker/files/4562754/opencore-2020-05-01-063351.txt)

(In this one I use <kbd>Esc</kbd> to get into BootPicker and manually choose boot into macOS)

**From macOS to macOS** (Use startup disk inside system preferences)

[opencore-2020-05-01-060831.txt](https://github.com/acidanthera/bugtracker/files/4562761/opencore-2020-05-01-060831.txt)

**From macOS to Windows** (Use startup disk inside system preferences)

[opencore-2020-05-01-062333.txt](https://github.com/acidanthera/bugtracker/files/4562763/opencore-2020-05-01-062333.txt)

**Comment by vit9696** [comment]
Something is wrong about these logs. They are not complete with BootOrder and Boot Next dumps missing. Most likely you use the release version of OpenCanopy and thus nothing was logged. Sorry, but I will need you to redo the logs, and ideally from 0.5.8 as I might have spotted the problem and the fix will be deployed there if I can confirm the issue from the logs.

@Download-Fritz not sure if this is related, but it looks wrong to me. With BlessOverride and/or Bootstrap usage in 0.5.8 this will not be OpenCore but e.g. Windows on the same drive. I am afraid we want to drop this check, and optionally boot the next option on failure(?).
https://github.com/acidanthera/OpenCorePkg/blob/616505ca2b5263533818e0f5650ad81276ecd95e/Library/OcBootManagementLib/DefaultEntryChoice.c#L492

**Comment by SukkaW** [comment]
@vit9696 Should I replace `OpenRuntime.efi` with debug version as well? I have `Request BootVarFallback` and `RequestBootVarRouting` and I think log of `OpenRuntime` is required as well.

**Comment by vit9696** [comment]
OpenRuntime does not log anything, no worries.

**Comment by SukkaW** [comment]
@vit9696 The updated logs are here and I can see `OCUI` related lines are included in those files.

**From macOS to macOS** (Use startup disk inside system preferences)

[opencore-2020-05-01-115308-macos-to-macos.txt](https://github.com/acidanthera/bugtracker/files/4564111/opencore-2020-05-01-115308-macos-to-macos.txt)

**From macOS to Windows** (Use startup disk inside system preferences)

[opencore-2020-05-01-120143-macos-to-windows.txt](https://github.com/acidanthera/bugtracker/files/4564112/opencore-2020-05-01-120143-macos-to-windows.txt)

**From Windows to macOS, select with BootCamp under Windows**

[opencore-2020-05-01-121818-windows-macos-1.txt](https://github.com/acidanthera/bugtracker/files/4564115/opencore-2020-05-01-121818-windows-macos-1.txt)

(Then Windows is booted)

[opencore-2020-05-01-121919-windows-macos-2.txt](https://github.com/acidanthera/bugtracker/files/4564118/opencore-2020-05-01-121919-windows-macos-2.txt)

(Long press <kbd>X</kbd> in order to boot into macOS)

**Comment by vit9696** [comment]
```
05:741 00:002 OCB: Dumping BootOrder
05:744 00:002 OCB: 0 -> Boot0080 = HD(2,GPT,26B49F20-461A-4EED-AE8F-F533B173AC7B,0x0,0x0)
05:750 00:006 OCB: Predefined list
05:752 00:002 OCB: 0 -> Boot0080 = HD(2,GPT,26B49F20-461A-4EED-AE8F-F533B173AC7B,0x0,0x0)
05:755 00:002 OCB: 1 -> Boot0081 - failed to read
05:757 00:002 OCB: 2 -> Boot0082 - failed to read
```

This looks like you have an old version of BootCamp without APFS support. Please make sure you install the latest version (note, that you may have to download the latest version by downloading BootCamp for e.g. iMac19,1).

**Comment by SukkaW** [comment]
@vit9696 I have used `Brigadier` to download BootCamp. With OpenCore applying SMBIOS configuration to all the operation system (including Windows), `Brigadier` could identify `MacBookPro15,4` and use that model to download BootCamp. And I even received & installed a update of BootCamp from Apple Update Utility under Windows recently.

Is it ok for a notebook to fetch BootCamp with `iMac19,1`?

**Comment by vit9696** [comment]
Yes, it is fine. Please try that. I wonder if 15,4 mbp BootCamp is somehow not compatible, though it is unlikely.

**Comment by SukkaW** [comment]
@vit9696 I trie specific model "iMac19,1" but the installer says "Thesoftware you attempt to install is not compatible with your model". I just assume the installer has read my model data then.

Then I redownload BootCamp using the model MBP15,4 attempt to get latest copy. After I successfully install the latest BootCamp, reboot  to macOS is now working.

Thanks for your help! The problem does related with my BootCamp version. I am closing the issue now.
