### ISSUE TITLE
SMBus Intertouch

### ISSUE THREAD

**Issue by 1Revenger1** [acidanthera/bugtracker#884]
I was wondering if any thought had been put into possibly supporting synaptics Intertouch with SMBUS. It seems to be enabled here in Linux under psmouse: https://github.com/torvalds/linux/blob/master/drivers/input/mouse/synaptics.c#L1773

Additionally, looks like there has been some work done for reading from the SMBus here: https://github.com/leo-labs/VoodooSMBus

**Comment by vit9696** [comment]
As far as I know we have no hardware for it. Feel free to contribute.

**Comment by 1Revenger1** [comment]
I've started getting data from the sensor over SMBus, and it doesn't do much with PS2. PS2 is mostly used for discovery but I think we can put in our own PS2 stuff for that.
We did have a few questions but that got posted as an issue already here: 
https://github.com/acidanthera/bugtracker/issues/932
