### ISSUE TITLE
AppleALC[POSSIBLE BUG] Dell Inspiron 7359 CX20722 Layout ID-3 not working

### ISSUE THREAD

**Issue by netseeder** [acidanthera/bugtracker#885]
Hi there 
I have a Dell Inspiron 7359 with a Conexant CX20722 codec. I use AppleALC kext. v1.4.8
i use hacktools for export audio patch.I saw that the only available layout-id is 3 but it seems like it isn't working with my codec. I attach all files (screenshot)including my efi folder.
Hope to hear good from you soon.

![Screenshot 2020-05-01 at 9 05 53 AM](https://user-images.githubusercontent.com/64652421/80820334-87022080-8b8b-11ea-9ebe-d9119e27357d.png)
![Screenshot 2020-05-01 at 9 06 50 AM](https://user-images.githubusercontent.com/64652421/80820349-8cf80180-8b8b-11ea-90f9-e8ac21ffd015.png)
![Screenshot 2020-05-01 at 9 07 12 AM](https://user-images.githubusercontent.com/64652421/80820352-8ec1c500-8b8b-11ea-82aa-0cde1b37fd08.png)
![Screenshot 2020-05-01 at 9 08 10 AM](https://user-images.githubusercontent.com/64652421/80820361-91241f00-8b8b-11ea-89d0-90d291de1b16.png)
![Screenshot 2020-05-01 at 9 08 23 AM](https://user-images.githubusercontent.com/64652421/80820364-92554c00-8b8b-11ea-87d0-3841096d7db7.png)
[EFI 2.zip](https://github.com/acidanthera/bugtracker/files/4565139/EFI.2.zip)

.

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by netseeder** [comment]
> Use forums for support.

Please provide the forum link.

**Comment by Andrey1970AppleLife** [comment]
https://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/

**Comment by rektimus** [comment]
> https://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/

I've tried following this (there is no fully compatible layout for my system), and I've signed up at AppleLife.ru to get Codec-Info.command 10.zip but I've never received confirmation email. I assume many people might have these issues (plus translation issues).

Any other guides?

**Comment by roddy20** [comment]
maybe this can help https://www.olarila.com/topic/1817-how-to-patch-applehda/
but it is very old
