### ISSUE TITLE
OpenCore Picker does not follow Catalina APFS volume name

### ISSUE THREAD

**Issue by rencium** [acidanthera/bugtracker#886]
Hi, I got a minor cosmetic issue for the picker on OpenCorePkg 0.5.7. When renaming the startup volume from Catalina Disk Utility, the picker does not show the updated name.

This should reproduce the error: (Tested on macOS Catalina v10.10.4, OpenCorePkg 0.5.7)
1. Rename APFS volume name in Disk Utility from "Old Name" to "New Name" 
2. Reboot to OpenCore picker
3. Check if volume name on picker is identical to APFS volume name

Current behavior:
- Picker shows "Old Name"

Expected behavior:
- Picker should should be "New Name"

Additional notes:

- Behavior is identical on PickerMode=Builtin and PickerMode=External (with OpenCanopy). 
- The "New Name" shows up correctly in EFI shell, and in the diskutil/Disk Utility in Catalina. 
- Behavior is identical with NVRAM reset 
- "Startup Disk" setting applied in macOS works correctly nonetheless of the difference in naming

**Comment by Andrey1970AppleLife** [comment]
Sometimes some configurations don't update a name in .contentDetails
Fix .contentDetails manually.
