### ISSUE TITLE
GPU stays at low frequencies

### ISSUE THREAD

**Issue by Marco702** [acidanthera/bugtracker#887]
I get a very poor performance on graphic-related tasks, like games, because my gpu stays locked at low frequencies, generally < 300MHz, like if it is bottlenecked

Here is my setup:
Bootloader: Opencore
Mac version: Niresh catalina
CPU: Ryzen 5 1600
GPU: sapphire vega 64 reference
Motherboard: Gigabyte b450m s2h
RAM: 16GB ddr4

**Comment by vit9696** [comment]
The matter of configuration. Out of the scope.

**Comment by Andrey1970AppleLife** [comment]
Ask at Niresh.
