### ISSUE TITLE
DynamicEWMode problem on Lenovo ThinkPad Laptops

### ISSUE THREAD

**Issue by Sniki** [acidanthera/bugtracker#890]
HI @usr-sse2 

The new changes into VoodooPS2 commit [7ca9da2](https://github.com/acidanthera/VoodooPS2/commit/8242476230a5592cfedd9960afc2028fca8a57d7) with DynamicEWMode disabled with SSDT-ThinkPad_ClickPad:
```
"DynamicEWMode",
">n",
```
Causes some weird issues like:
- Laggy Window Movement(s)
- Laggy Drag and Drop
- Broken Gestures

Removing that line / enabling DynamicEWMode:
- No more lags
- Gestures works fine
- But Physical Left Click button works as a Right click, when i press the button, context menu appears and as soon as i release the button, the context menu disappears right away

We use the SSDT-ThinkPad_ClickPad for best/optimal configuration for these ThinkPad Touchpad(s) and DynamicEWMode always used to be disabled with this SSDT.

Reverting to previous VoodooPS2 works fine but that one had it's own problems with gestures with notification center etc.

Let me know if you need additional info & logs.

**Suggestion:** it would also be nice to include the boot-args options listed into the Readme.md like other projects have with a short description.

Thanks !

**Comment by usr-sse2** [comment]
After the changes, `DynamicEWMode` can't have any influence on gestures, as it isn't read.

Some gestures are impossible without Extended W mode, so it's always enabled if the touchpad supports it. If some touchpads have problems in Extended W mode, we should debug these problems instead of disabling Extended W mode.
Moreover, proper handling of touchpads that don't have Extended W mode is not implemented yet (the coordinates of second finger are always 0, and really should be assigned to the coordinates of the first finger).

**Comment by Sniki** [comment]
It seems that it does support Extended W Mode as without the DynamicEWMode >n , the gestures do work all fine and system doesn't lag.
But the Physical buttons and the TrackPoint are not working correctly / broken.
Is it possible that
Here is a video on what happens:
[ClickPad.mp4.zip](https://github.com/acidanthera/bugtracker/files/4583021/ClickPad.mp4.zip)

Is it possible that some code related to this have been removed on this commit: https://github.com/acidanthera/VoodooPS2/commit/f5d91270b16806e7b8a8d90444dcbf10cf1e2dbf ?

**Comment by junaedahmed** [comment]
Having same problem with latest release as @Sniki 's video.

**Comment by usman2006** [comment]
have same issue but only after I use one of the physical button.
if i uncheck and check in trackpad some gesture settings it works than again normal till i use again one of the upper buttons

**Comment by Sniki** [comment]
@usr-sse2 
I have some more proper informations regarding this introduced issue.

All Physical Buttons do work as Right Click on Press and Left click on Release (so both left click and right click on normal press) and trackpoint doesn't work at all.

However the bottom part of the touchpad is click-able as well for left click and right click.
And the bottom part works fine.

The kext broke on the mentioned commit on first post (3 commits introduced that day).

Back in the days when the kext was still on it's early releases we had similar issue and a user added back some deleted code that broke it during the transition and cleanup from Rehabman version.

History reference:
https://github.com/acidanthera/VoodooPS2/pull/5/commits/e8c511b70e472213acdf971a613cdfa316d00cfa

This did add back phyiscal buttons functionality.
Is it possible that same/similar code has been removed since those commits ?

Other than this issue, the kext is working better than it ever did.

Thanks for the continuous improvements !

**Comment by gimdh** [comment]
My trackpoint button works fine, but it is extremely laggy when trying to drag with trackpoint. Version 2.1.3 works fine but anything above it breaks drag functionality.
One thing to note is that my Thinkpad has trackpoint buttons integrated to trackpad, not keyboard. I am wondering if this issue is due to some sort of simutaneous input rejection algorithm as driver may see two as different device.

**Comment by Sniki** [comment]
> My trackpoint button works fine, but it is extremely laggy when trying to drag with trackpoint. Version 2.1.3 works fine but anything above it breaks drag functionality.
> One thing to note is that my Thinkpad has trackpoint buttons integrated to trackpad, not keyboard. I am wondering if this issue is due to some sort of simutaneous input rejection algorithm as driver may see two as different device.

@gimdh that's the problem with the SSDT used as you described.
same behavior here as well physical buttons and trackpoint work, but dragging is very laggy with both touchpad or trackpoint and gestures like two finger scrolling etc are broken, however if i remove DynamicEWMode >n , the buttons break and the behavior is like on my last post described.
Gestures work, lag is gone, but physical buttons and trackpoint are broken, the buttons work as right click on press and left click on release (both left and right button).

But as seen on a different issue here, i believe physical buttons and trackpoint are planned to move from VoodooPS2 to VoodooInput as @usr-sse2 said if i am correct.

So i assume this issue will be handled during that process.

**Comment by yusufklncc** [comment]
Any solution? @Sniki

**Comment by 1Revenger1** [comment]
[VoodooPS2Controller-2.3.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/9967123/VoodooPS2Controller-2.3.1-DEBUG.zip)
Do you all mind testing this build of acidanthera/VoodooPS2#54? This should fix the buttons and Extended W mode weirdness.

**Comment by Muhal44** [comment]
Dear 1Revenger1
 Thank you very much for your time and effort.
This new designed kext worked my Hp6470b laptop (ivy bridge, with synaptics trackpad).
Both multitouch and physical buttons (Left, and,Right click) are working well.

**Comment by Sniki** [comment]
> ~[VoodooPS2Controller-2.3.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/9967123/VoodooPS2Controller-2.3.1-DEBUG.zip)~ [VoodooPS2Controller-2.3.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/9979276/VoodooPS2Controller-2.3.1-DEBUG.zip)
> 
> Do you all mind testing this build of [acidanthera/VoodooPS2#54](https://github.com/acidanthera/VoodooPS2/pull/54)? This should fix the buttons and Extended W mode weirdness.

I have been away for quite a while from the hackintosh community due to life stuff (job, first kid, new interests/hobbies, etc).
Since i opened the issue i feel that i am also responsible to confirm if this fixes the issue.
I will attempt to install on my 2nd ssd on my T440P before the 1st December so it gets merged with next month releases if we face no other issue.

Thanks for the work and your precious time !

**Comment by riglaze** [comment]
> ~[VoodooPS2Controller-2.3.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/9967123/VoodooPS2Controller-2.3.1-DEBUG.zip)~ [VoodooPS2Controller-2.3.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/9979276/VoodooPS2Controller-2.3.1-DEBUG.zip)
> 
> Do you all mind testing this build of [acidanthera/VoodooPS2#54](https://github.com/acidanthera/VoodooPS2/pull/54)? This should fix the buttons and Extended W mode weirdness.

Can confirm that this kext fixes the buttons for my Synaptics touchpad and the overall smoothness is greatly improved. I disabled PS2Mouse plugin for my case.
However, after booting up, the deadzones seem to take some time to get properly adjusted. Maybe this is something to do with the order of kexts that load on my laptop, but no complaints as hackintosh adds 3 finger gestures to my touchpad which wasn't possible on windows as well as linux.

Thank you

**Comment by Sniki** [comment]
@1Revenger1 Thank you for the work, i can confirm this fixes the problem and now physical buttons on the trackpad are working.
However dragging is broken (with and without thinkpad_clickpad SSDT), tested both scenarios.
The bottom part of the touchpad is clickable surface as well and there i can click left side for left click and right side for right click but that part now acts as force touch.
If i disable force touch into settings > TrackPad, then the bottom clickable area works just fine and i can drag with the bottom clicks, but the upper ones are not able to drag.

**Comment by 1Revenger1** [comment]
The ssdt shouldn’t make any difference now, EW mode and button logic should be based off of what the trackpad reports. Do the two trackpad buttons at the bottom both work as left clicks using the kext, or do they act as left and right clicks? Wonder if I need to check the two button click pad bit.

I’ll double check the dragging with the track point buttons later, and see if I can figure that out. Thanks for testing!

**Comment by Sniki** [comment]
> The ssdt shouldn’t make any difference now, EW mode and button logic should be based off of what the trackpad reports. Do the two trackpad buttons at the bottom both work as left clicks using the kext, or do they act as left and right clicks? Wonder if I need to check the two button click pad bit.
> 
> I’ll double check the dragging with the track point buttons later, and see if I can figure that out. Thanks for testing!

Just went to bed as its 02:45 am, will test tomorrow and let you know with the correct answer as i am not 100% sure.

**Comment by Sniki** [comment]
@1Revenger1 i just checked/tested and yes both bottom buttons/clickable area work as left clicks

**Comment by 1Revenger1** [comment]
@Sniki sorry for the delay. How is the version from the latest build [here](https://github.com/acidanthera/VoodooPS2/suites/10022097851/artifacts/487063549)? This should be the latest version with the latest VoodooInput.

I double checked the dragging around using the trackpoint buttons and trackpad, and that worked just fine on my device. I didn't see any logic errors that'd prevent that or the scrolling.

Btw, the force touch is configurable. If you set the force touch mode to zero in VoodooPS2 or disable force touch in system preferences, it should be disabled. It annoys me quite a bit so I just leave it disabled in system preferences.

**Comment by Sniki** [comment]
> @Sniki sorry for the delay. How is the version from the latest build [here](https://github.com/acidanthera/VoodooPS2/suites/10022097851/artifacts/487063549)? This should be the latest version with the latest VoodooInput.
> 
> I double checked the dragging around using the trackpoint buttons and trackpad, and that worked just fine on my device. I didn't see any logic errors that'd prevent that or the scrolling.
> 
> Btw, the force touch is configurable. If you set the force touch mode to zero in VoodooPS2 or disable force touch in system preferences, it should be disabled. It annoys me quite a bit so I just leave it disabled in system preferences.

Will give it a try tonight/tomorrow, i can provide logs if necessary if there is something still not working correctly, i have been out of sync lately, it would be nice to give a super short/quick example on how to collect logs.

**Comment by 1Revenger1** [comment]
Easiest way to provide logs I've found is setting `msgbuf=1048576` or adding DebugEnhancer.kext to your kexts. This expands the number of logs that are stored and shown when running the `sudo dmesg` command. I haven't gotten the `log` command to work recently though.

Some things you can try grepping for is `ps2`, `synaptics_parse_hw_state`, `VoodooPS2 Buttons`, and `VoodooPS2 w`. The first is likely to pick up all the keyboard logs though so I'd be a bit cautious sending logs with those in there. Probably easiest to use `sudo dmesg | grep -E 'synaptics_parse_hw_state|VoodooPS2 w|VoodooPS2 Buttons'`

**Comment by Sniki** [comment]
@1Revenger1 i tried to grab some logs, if you need additional ones let me know, it was PITA because i couldn't do selection as dragging is still not working and scrolling with trackpoint still doesn't work for me.
[PS2.txt](https://github.com/acidanthera/bugtracker/files/10297656/PS2.txt)

**Comment by 1Revenger1** [comment]
Uhh, looks like I broke something related to extended buttons. Do you mind trying the version below?
For dragging, clicking down on the trackpad should work for now until I can get the buttons fixed.
I changed some of the logging, so use `sudo dmesg | grep -E 'synaptics_parse_hw_state|VoodooPS2Trackpad'`
This should hopefully give me a lot more logging and give me a better idea what's going on.

[VoodooPS2Controller-2.3.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/10297918/VoodooPS2Controller-2.3.1-DEBUG.zip)

**Comment by Sniki** [comment]
> Uhh, looks like I broke something related to external buttons. Do you mind trying the version below? For dragging, clicking down on the trackpad should work for now until I can get the buttons fixed. I changed some of the logging, so use `sudo dmesg | grep -E 'synaptics_parse_hw_state|VoodooPS2Trackpad'` This should hopefully give me a lot more logging and give me a better idea what's going on.
> 
> [VoodooPS2Controller-2.3.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/10297918/VoodooPS2Controller-2.3.1-DEBUG.zip)

Scrolling with trackpoint + middle button doesn't work
Dragging/Selection still doesnt work with upper physical buttons
However middle button now opens shortcut correctly etc.
[New logs.txt](https://github.com/acidanthera/bugtracker/files/10299754/New.logs.txt)


Here are the logs:

**Comment by 1Revenger1** [comment]
Oh, the external buttons field works a bit differently than I thought it did. Looks like the buttons are only reported in one packet even if they stay pressed down. At least the buttons seemed to be reported right when initially pressed, so the logic is mostly right. I'll see if I can get a build together either tonight or tomorrow morning which persists the button presses across packets (PST timezone).

**Comment by 1Revenger1** [comment]
[VoodooPS2Controller-2.3.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/10304678/VoodooPS2Controller-2.3.1-DEBUG.zip)
This should hopefully fix dragging and scrolling.

**Comment by Sniki** [comment]
> [VoodooPS2Controller-2.3.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/10304678/VoodooPS2Controller-2.3.1-DEBUG.zip) This should hopefully fix dragging and scrolling.

Thanks, i will report back with results within an hour.

**Comment by Sniki** [comment]
@1Revenger1 Yes now dragging and scrolling with trackpoint is fixed.

I only have two small issues that i noticed compared to VoodooRMI
1. Two fingers scrolling is too slow compared to VoodooRMI, a bump in scroll speed would make it fine although that may be user configurable already as it has been ?.
2. I feel like scrolling is a bit laggy for some reasons, compared to VoodooRMI.

Other than that i think it's about time we close this issue.

Thank you for the amazing work that you did.
[Logs PS2.txt](https://github.com/acidanthera/bugtracker/files/10304792/Logs.PS2.txt)


Here are the logs just in case something unusual is present.

**Comment by 1Revenger1** [comment]
I do know that VoodooPS2 averages the x/y values that comes from the trackpad. I played around with disabling the averaging, which seemed to help with scrolling and moving the pointer. I didn't want to mess around with it too much since it was probably put in for a reason, though I didn't notice any issues with having the averaging disabled. I'm not entirely sure what it would take to configure scrolling speed. All gestures are handled internally in Apple's Magic Trackpad 2 logic.

**Comment by Sniki** [comment]
> I do know that VoodooPS2 averages the x/y values that comes from the trackpad. I played around with disabling the averaging, which seemed to help with scrolling and moving the pointer. I didn't want to mess around with it too much since it was probably put in for a reason, though I didn't notice any issues with having the averaging disabled. I'm not entirely sure what it would take to configure scrolling speed. All gestures are handled internally in Apple's Magic Trackpad 2 logic.

All great man, you did an amazing job, that's a different thing and off topic to the issue.
Marking solved/closing

**Comment by riglaze** [comment]
In continuation to my situation, where the touchpad feels janky most of the time, I'm elated to report that my Synaptics v7.2 touchpad with the voodoops2 debug kext from here (VoodooInput enabled) and voodoormi/smbus (voodooinput disabled) fixed my jitters and improper deadzones issue.
The other way around works as well, but the buttons did not work.

NOTE:- acidanthera release voodoops2's voodooinput did not let my touchpad work at all (and also voodoosmbus VoodooInput) and this approach makes my touchpad feel wayy better than in linux or windows, making my hackintosh experience a ton better. Thanks, man! this is epic!!
PS:- I do have a SMBUS controller and VoodooSMBUS latches to this controller properly (as per IOREG)
