### ISSUE TITLE
Laptop internal display is black when it connected to external display with HDMI connector

### ISSUE THREAD

**Issue by bavelee** [acidanthera/bugtracker#891]
Hi,
My laptop have a problem when it connected to external display with HDMI connector.
The specific performance is internal display is black, but external display is works fine.
Once I had an inconvenient solution that by close lid then open lid, it looks like the procedures of sleep and wake.
Finally, I found that sleep and wake the display commands can make internal display works.
* Sleep display
```shell
pmset displaysleepnow
```
* Wake display
```shell
caffeinate -u -t 1
```
Combined use these commands is workable.
Then I write a program in `Objective-C`
```Objective-C
#include <Foundation/Foundation.h>
#include <IOKit/IOKitLib.h>
int change_display_state(int state){
        @autoreleasepool {
                io_registry_entry_t displaywrangler = IORegistryEntryFromPath(kIOMasterPortDefault, "IOService:/IOResources/IODisplayWrangler");
                if(displaywrangler == MACH_PORT_NULL) return 1;
                else {
                        kern_return_t result = IORegistryEntrySetCFProperty(displaywrangler, CFSTR("IORequestIdle"), state == 0 ? kCFBooleanTrue : kCFBooleanFalse);
                        IOObjectRelease(displaywrangler);
                        if(result != KERN_SUCCESS) return 1;
                }

        }
        return 0;
}
int active_display(){
        return change_display_state(1);
}
int sleep_display(){
        return change_display_state(0);
}
int main(int argc, char ** argv) {
        float sec = 1.0f;
        printf("Sleeping display....");
        int ret = sleep_display();
        printf("\n");
        [NSThread sleepForTimeInterval:sec];
        printf("Awaking display....");
        ret += active_display();
        printf("\n");
        return ret;
}
```
And I create a `LoginHook` to execute it.
```shell
sudo defaults write com.apple.loginwindow LoginHook /usr/local/bin/FixInternalDisplayBlack
```
I also turn on autologin in sysprefs.
Now it can makes internal display working but I cannot input password.
I want the `LoginHook` can be execute before login that I can turn off autologin.
Maybe change ioreg property can be writen in kext, but I dont know kext at all.
So does kext can do that?
Hope your anwser.
Sorry for my poor English.

**Comment by vandroiy2013** [comment]
igfxonln=1 boot argument (force-online device property) to force online status on all displays.

**Comment by bavelee** [comment]
> igfxonln=1 boot argument (force-online device property) to force online status on all displays.

I have added device property `force-online`, but not working.

**Comment by 07151129** [comment]
You could also try `complete-modeset` (make sure to also specify framebuffer ID of the builtin display).

**Comment by bavelee** [comment]
> You could also try `complete-modeset` (make sure to also specify framebuffer ID of the builtin display).

I did that as you said, not working. But I connect to TV with HDMI, internal display also works.This monitor cant.

**Comment by 07151129** [comment]
Does the driver produce any useful log?

**Comment by bavelee** [comment]
> Does the driver produce any useful log?

Here is my framebuffer patch.
Now I am going to capture logs.

![Snipaste_2020-05-06_08-57-20](https://user-images.githubusercontent.com/8685977/81129691-c0fe6880-8f77-11ea-8798-7f81965ae1e7.jpg)

**Comment by 07151129** [comment]
You haven't specified framebuffers for forcing complete modeset, so this option is not doing anything for you

**Comment by bavelee** [comment]
> You haven't specified framebuffers for forcing complete modeset, so this option is not doing anything for you

Now I added that, but also failed
![Snipaste_2020-05-06_09-08-51](https://user-images.githubusercontent.com/8685977/81130162-50584b80-8f79-11ea-895d-98c9774fb517.jpg)

**Comment by bavelee** [comment]
> You haven't specified framebuffers for forcing complete modeset, so this option is not doing anything for you

Thanks, now its ok.
Atttach my fb patch.
`complete-modeset` : `<01000000>`
`complete-modeset-framebuffers` : `<00000000 00000001>`
`force-online` : `<01000000>`
`force-online-framebuffers` : `<00000000 00000001>`
![Snipaste_2020-05-06_09-21-00](https://user-images.githubusercontent.com/8685977/81130608-f9537600-8f7a-11ea-817a-2df52473bc65.jpg)

**Comment by andreszerocross** [comment]
@07151129 i thought "complete-modeset" just for Skylake or Apple Firmware only. Why should we use "complete-modeset" along with "complete-modeset-framebuffers"???
![image](https://user-images.githubusercontent.com/9614101/123767135-76654b80-d8f1-11eb-827e-3f4d73e7dc81.png)
