### ISSUE TITLE
Laptop cant use usb keyboard to simulate apple hotkeys

### ISSUE THREAD

**Issue by bavelee** [acidanthera/bugtracker#893]
Laptop cant use usb keyboard to simulate apple hotkeys.
Such as : 
**command+v** Enables verbose.
**option/alt** Show boot picker.
All the hotkeys dont have any reactions with usb keyboard, but ps2 keyboard is workable.
Chipset is H370, checked `KeySupport` and `KeySwap` in config.
Will support it in the future or I did not configure it well?

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
