### ISSUE TITLE
Multiple Windows partitions are found by scanning

### ISSUE THREAD

**Issue by crushers** [acidanthera/bugtracker#894]
@vit9696 I have a this problem on 0.5.9
![20200506_140633](https://user-images.githubusercontent.com/7488776/81183925-0dfe3100-8fb0-11ea-976c-8bca58711de7.jpg)
I'm on UEFI mode Windows 10 and on last three or four update 0.5.9 I have a two Windows boot partition. Currently I use GTX760 (I can't found GOP/UEFI ROM) and I have a big resolution on boot menu and first boot stage.

```
<key>Output</key>
		<dict>
			<key>ClearScreenOnModeSwitch</key>
			<false/>
			<key>ConsoleMode</key>
			<string></string>
			<key>DirectGopCacheMode</key>
			<string></string>
			<key>DirectGopRendering</key>
			<false/>
			<key>IgnoreTextInGraphics</key>
			<false/>
			<key>ProvideConsoleGop</key>
			<true/>
			<key>ReconnectOnResChange</key>
			<false/>
			<key>ReplaceTabWithSpace</key>
			<false/>
			<key>Resolution</key>
			<string>Max</string>
			<key>SanitiseClearScreen</key>
			<false/>
			<key>TextRenderer</key>
			<string>BuiltinGraphics</string>
		</dict>
```

**Comment by vit9696** [comment]
Please provide EFI folder and a debug log (Target = 67). Also make sure that you use the latest version of OpenCorePkg (there were changes there) and that you use `macbuild.tool` (third party builders are most likely broken again).

**Comment by crushers** [comment]
Here u go boot.log
[opencore-2020-05-06-124009.txt](https://github.com/acidanthera/bugtracker/files/4586783/opencore-2020-05-06-124009.txt)
If I put (Target=67) he seen my EFI partition in boot menu.
with Taget=67
[opencore-2020-05-06-124538.txt](https://github.com/acidanthera/bugtracker/files/4586792/opencore-2020-05-06-124538.txt)

**Comment by vit9696** [comment]
This is not a DEBUG build and most likely not a valid build in the first place. You also did not include your EFI folder.

**Comment by Andrey1970AppleLife** [comment]
00:000 00:000 OC: OpenCore DBG-059-2020-**05-05** is loading in Optional mode (0/0)...
It is yesterday's build.

**Comment by crushers** [comment]
Ok I now download PKG and make new OC I attach my EFI and boot.log
[opencore-2020-05-06-130130.txt](https://github.com/acidanthera/bugtracker/files/4586870/opencore-2020-05-06-130130.txt)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4586871/EFI.zip)

**Comment by vit9696** [comment]
This is not a DEBUG build but a RELEASE build. It logs nothing. Please do the logs properly.

**Comment by crushers** [comment]
[opencore-2020-05-06-131130.txt](https://github.com/acidanthera/bugtracker/files/4586924/opencore-2020-05-06-131130.txt)

**Comment by crushers** [comment]
Here u go with Target=67
[opencore-2020-05-06-131719.txt](https://github.com/acidanthera/bugtracker/files/4586963/opencore-2020-05-06-131719.txt)
Above is with Target=83

**Comment by crushers** [comment]
Hmmm UEFI Windows and CSM Enabled make a problem.

**Comment by vit9696** [comment]
Resolved in master.
