### ISSUE TITLE
Nvidia Web Driver patching

### ISSUE THREAD

**Issue by graphine27** [acidanthera/bugtracker#895]
Hello,

I came across some work being done in loading High Sierra drivers into Mojave [here](https://www.tonymacx86.com/threads/discussion-about-how-to-make-nvidia-web-driver-works-in-macos-10-14-mojave.265813/) (it's a long read)

The developer got over the linking issues but ultimately ended up having Metal issues.

```
Error from Metal: Error Domain=CompilerError Code=1 "Function SimpleColorFragment has a deployment target which is incompatible with this OS." UserInfo={NSLocalizedDescription=Function SimpleColorFragment has a deployment target which is incompatible with this OS.}

  vert program = SimpleColorVertex

  frag program = SimpleColorFragment

```
 
This is very likely caused by GeForceGLDriverWeb's precompiled shaders which need t obe complied for the runtime target . They are either located in the bundle's code or in GeForceMTLDriverWeb.bundle/Contents/Resources/internal.metallib

Metal shaders should be usable for any hardware, so it's possible to use the ones from Apple supplied drivers (GeForceMTLDriver.bundle). Maybe it would be possible to link the webdrivers to the Apple MTLDriver?

Since the developer had abandoned the project due to time constraints no one else tried to pick up his work.

Have the developers of WhateverGreen tried to do this before?
I'm trying to figure out things, but it's hard for a non developer.

**Comment by 07151129** [comment]
It's an interesting story, but I don't think there's much we can do. First of all, nobody on the team uses Nvidia anymore, or is motivated in getting in working. Secondly, newer versions of Metal introduce many other features that would require extensive work to support, and every OS upgrade would break something.

**Comment by graphine27** [comment]
Thanks for your answer. I was hoping there was a way to use the metal driver from apple.

Another approach (probably impossible) could be to route calls from GF100Hal to GP100Hal or to make official drivers load web Hal. Hal kexts don't have many exports.

I was curious if the team tried anything in regards to this issue. Trying to gather as much information as I can.

**Comment by graphine27** [comment]
After more testing, it seems the metal compiler is actually GeForceAIRPluginWeb, maybe the one from apple can be used instead of the nvidia one.

Also GeForceGLDriverWeb is missing some functions, but it might work as it is.
![Screenshot 2020-05-07 at 17 37 50](https://user-images.githubusercontent.com/64922824/81307930-e11e4c80-9089-11ea-87bd-0aa4b4a18ada.png)
