### ISSUE TITLE
Audio working on DP with single cable, but not on dual DP cable (5k monitor requires two)

### ISSUE THREAD

**Issue by Nikki31000** [acidanthera/bugtracker#900]
Configuration:
OC 0.5.8 (also got 0.5.7, same issue, and was also the same in 0.5.6)
Lastest versions of WhateverGreen (1.3.9) and Lilu (1.4.4)
Catalina 10.15.3 (same issue on 10.15.4)
Z390
i9 9900k
**5700XT**

Audio is working well over DP if I only connect my screen through 1 DP but then I only got 4K resolution on the 5K screen, which require 2 DP cables connection.
As soon as I connect the 2nd cable, I don't have audio on the screen. In both cases, I see my Dell UP2715K as an audio output, just that in one case it doesn't work.
I tested with one cable each of the 3DP, audio is working well over any of them. Tried every combination of plugging the 2 DP, no audio whatsoever when two are plugged.
One thing though, screen only receives audio through its 1st DisplayPort.
What I assume is that the sound is sent through the wrong display port. Where would I be able to check that, and hopefully correct it?
I don't mind getting my hands on kext code to modify some parameters, I just don't know where to look at, but I assume this as something to do either with WhateverGreen or AppleALC? 

One thing to note, this dual DP audio was working well under High Sierra with GTX 970 and OC 0.5.7 and the same kext. So that makes me think that this is specific to how audio is applied to my GPU in contrast to how it is applied for the GTX970.

I will gladly provide anymore detail if I could help solve that issue, which I assume would impact every monitor requiring double DisplayPort connection and equipped with audio.

**Comment by vit9696** [comment]
I think you are best to a file a radar about this issue. We will not look into it.
