### ISSUE TITLE
IOPlatformPluginFamily Warning regarding iGPU in boot log

### ISSUE THREAD

**Issue by tiger511** [acidanthera/bugtracker#903]
With WEG 1.3.9 I see the following error /warning in my boot log but everything works fine.

`2020-05-08 23:32:44.436198+0600  localhost kernel[0]: (IOPlatformPluginFamily) <IOPlatformPluginFamilyDebugPrint> HE2N_Key Does Not Exist, use kSMCPStatesIGPU for Internal GPU
2020-05-08 23:32:44.436199+0600  localhost kernel[0]: (IOPlatformPluginFamily) <IOPlatformPluginFamilyDebugPrint> HE2N_Key Does Not Exist, use kSMCPStatesIGPU for Internal GPU`

What does it mean and does it have anything to do with GPU performance?
iGPU: UHD 630 CFL with AppleGuC

**Comment by tiger511** [comment]
Full log
[gpulog.txt](https://github.com/acidanthera/bugtracker/files/4602815/gpulog.txt)

**Comment by vit9696** [comment]
Does not look like an error for me, but you can file a radar about it I guess.
