### ISSUE TITLE
[VoodooPS2Keyboard] Keys mapping works partially

### ISSUE THREAD

**Issue by kecinzer** [acidanthera/bugtracker#904]
I'm trying to map some of my HP EliteBook 850 G5 keys. I used debug version of VoodooPS2 for track key presses.
I want to map these keys:
F1 (monitor mirror) to Lauchpad
default map = e06e=70
F8 (microphone mute) to Play/Pause - this is only working mapping
default map =  e001=80
F11 (wifi) to Mission control
default map = e078=80
Right ALT (next to space) acting like CMD and I want to map it to Right ALT
default map = e038=36
All those keys F keys do nothing on keypress normaly (with FN it act like classic F keys).

I have also more F keys (F13 - F14 - monitor icon, phone answer, phone hang) and it acts like multiple key presses.

Here is my SSDT file. Can you plese push me, why only F8 Play/Pause works? Thanks.

[SSDT-05-INPUT.dsl.zip](https://github.com/acidanthera/bugtracker/files/4602937/SSDT-05-INPUT.dsl.zip)

**Comment by zhen-zen** [comment]
Please try again after removing "Function Keys Special" and "Function Keys Standard" from the SSDT. Function keys are usually defined by OEM and based on [EC events](https://github.com/torvalds/linux/blob/master/drivers/platform/x86/hp-wmi.c).

**Comment by kecinzer** [comment]
I finally get to test it. I created clean SSDT with this:

```
DefinitionBlock("", "SSDT", 2, "hack", "INPUT", 0)
{
	External(\_SB.PCI0.LPCB.PS2K, DeviceObj)
    Scope (\_SB.PCI0.LPCB.PS2K)
    {
        Name(RMCF, Package()
        {
        "Keyboard", Package()
        {
            "Custom ADB Map", Package()
            {
                Package(){},
                "e03e=83",    // F1 (display) to Launchpad
                "e001=34",    // F8 (microphone) to Play/Pause
                "e078=a0",    // F11 (wifi) to Mission Control 
                "e01d=3d"     // Right Control to Right Alt
            }
        }
        })
    }
}
```
F1 and F11 still not working.
