### ISSUE TITLE
Incorporate ShellCheck into ocbuild CI

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#906]
See #902

**Comment by vit9696** [comment]
There is no CI in ocbuild. If you want one, let's decide #902. I am not too happy with a ton of issues for a simple thing, there are tags for that.

**Comment by dakanji** [comment]
Get you on CI here. Will just create the yml file.

On tons of issues, they are already created anyway and will then be specifically closed in a clear way with specific PRs. Much neater than one complex PR.

Also easier for me to deal with. Again requesting reopening and each will be closed out shortly and will be gone.

**Comment by vit9696** [comment]
Ok.

**Comment by Andrey1970AppleLife** [comment]
Сlosed because PullRequest is sent.
