### ISSUE TITLE
Incorporate ShellCheck into DuetPkg CI

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#907]
See #902

**Comment by vit9696** [comment]
Use one issue.

**Comment by dakanji** [comment]
Potentially lots of files to fix. Better to handle them one by one to avoid mixups

**Comment by dakanji** [comment]
I.E., Handle one repo at a time. That way can keep track of what I am doing. So please reopen the closed ones

**Comment by Andrey1970AppleLife** [comment]
Сlosed because PullRequest is sent.
