### ISSUE TITLE
Opencore hangs at Detected Apple Processor Type with QEMU 5.0

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#914]
Base OS: Manjaro Architect 20.0.1, kernel 5.7.0
Qemu: 5.0
Libvirt: 5.10.0
CPU: 2x e5-2687w (host-passthrough)

Issue:
Opencore hangs at Detected Apple Processor Type: 00 -> 0903
Log: 
[qemu5-host-passthrough.txt](https://github.com/acidanthera/bugtracker/files/4615034/qemu5-host-passthrough.txt)

This happens when the cpu is set as host-passthrough:
<cpu mode='host-passthrough' check='none'/>
<qemu:arg value='-cpu'/>
<qemu:arg value='host,+hypervisor,migratable=no,-erms,+invtsc,kvm=on,+topoext,+avx,+aes,+xsave,+xsaveopt,+ssse3,+sse4_2,+popcnt,+arat,+pclmuldq,+pdpe1gb,+rdtscp,+vme,+umip,check'/>

Mac OS boots if the cpu is set as Penryn.
Log:
[qemu5-penryn.txt](https://github.com/acidanthera/bugtracker/files/4615035/qemu5-penryn.txt)

CPU host-passthrough works in a system with:
kernel 4.19
Qemu: 4.2
Libvirt: 5.10.0

Log:
[qemu42-host-passthrough.txt](https://github.com/acidanthera/bugtracker/files/4615036/qemu42-host-passthrough.txt)

**Comment by vit9696** [comment]
This looks like QEMU bug with MSR handling. Did you try this advice: https://github.com/Leoyzen/KVM-Opencore?

I think the code that causes your VM to die is here:
https://github.com/acidanthera/OpenCorePkg/blob/5da113b/Library/OcCpuLib/OcCpuLib.c#L303-L306

or here:
https://github.com/acidanthera/OpenCorePkg/blob/5da113b/Library/OcCpuLib/OcCpuLib.c#L427-L451

You can try removing this (one or another) or adding debug prints to see a more precise place, like:

```C
DEBUG ((DEBUG_INFO, "OCCPU: Going to do something\n"));
```

CC @Leoyzen

**Comment by 82ghost82** [comment]
Thank you vit9696,
Yes, I know Leoyzen and asked also to him, who basically suggested the same thing as you, add debug lines.
He suggested to look into the ScanIntelProcessor in opencore and look where and why it hangs.
Yes, I know all the advices Leoyzen suggested during the time, on github and elsewhere, but this cpu passthrough should be a bug somewhere instead of a config issue, not sure where, because apparently the only thing changing between a working system and a non working system is the qemu version (I tried also to run manjaro with 4.19 kernel, same kernel as the working system).
Downgrading qemu to 4.2 is a pain in manjaro and I think it's not the solution.
Libvirt, opencore config, libvirt xml and ovmf are the same.
I will try to do something to help, but things are becoming difficult for me :) and this may require some time.

Again thank you very much for your time.

**Comment by vit9696** [comment]
Well, removing a few lines in a text file and/or adding a couple of lines should not be difficult even for a non-programmer, but if you have real difficulty we could try something.

In general I am fine to add workarounds, but I would also want somebody to file bugreports to QEMU, so that things do not get lost.

**Comment by 82ghost82** [comment]
Oh, sorry I didn't read carefully, so your first advice is to completely remove that blocks of code one at a time?
By "difficult" I was meaning add debug code, understand and correct the code, and yes, I confirm I'm not too good at this.

**Comment by vit9696** [comment]
Remove either and test. I believe removing https://github.com/acidanthera/OpenCorePkg/blob/5da113b/Library/OcCpuLib/OcCpuLib.c#L303-L306 should work really. If it does, I will just add a hypervisor check to avoid this code.

**Comment by 82ghost82** [comment]
Thank you vit9696.
Yes the issue is with the msr reading, as you pointed out, and in particular with this line:
https://github.com/acidanthera/OpenCorePkg/blob/5da113b/Library/OcCpuLib/OcCpuLib.c#L304

So, instead of deleting the lines, I added a debug line to write with the working qemu system the value of PkgCstConfigControl.Uint64 and I saw that it was 0, and assigned directly that value:
PkgCstConfigControl.Uint64 = 0;
host-passthrough now works again with sandy bridge.
