### ISSUE TITLE
DuetPkg/macbuild.tool: `boot` becomes unusable when changes are pulled

### ISSUE THREAD

**Issue by kommtzeitkonrad** [acidanthera/bugtracker#915]
Ⅰ don't know if pulling changes to an existing cloned local repo are supported, but if so:

Whenever latest commits to `DuetPkg` are pulled via `git pull` and afterwards `DuetPkg/macbuild.tool` is ran, the resulting `DuetPkg/Binaries/TARGET/boot` becomes unusable (see screenshot below).

Deleting `DuetPkg/Binaries/TARGET/boot` and running `DuetPkg/macbuild.tool` does not help.

As `DuetPkg/Binaries/TARGET/boot` works fine when `DuetPkg/macbuild.tool` is ran from a freshly cloned repo, Ⅰ guess there should be some `clean` command incorporated in `DuetPkg/macbuild.tool`.

![IMG_0398](https://user-images.githubusercontent.com/42938101/81761185-948fa280-94c9-11ea-809e-8a183b8fc855.jpeg)

**Comment by vit9696** [comment]
Yeah, must be some bug with DuetPkg build system. Feel free to debug it and contribute a patch. I am not sure I will debug it as CI builds only one time, and macbuild.tool is for CI really.

**Comment by dakanji** [comment]
Wonder whether has anything to do with this: https://github.com/acidanthera/DuetPkg/commit/79371aa0ac27d3735580bd312157dd71c83b04ff#r39148263

**Comment by roddy20** [comment]
> Wonder whether has anything to do with this: [acidanthera/DuetPkg@79371aa#r39148263](https://github.com/acidanthera/DuetPkg/commit/79371aa0ac27d3735580bd312157dd71c83b04ff#r39148263)

Tested and works Ok 
[Вывод Терминала 2.zip](https://github.com/acidanthera/bugtracker/files/4624163/2.zip)

**Comment by kommtzeitkonrad** [comment]
Attempt is successful. Thanks!
