### ISSUE TITLE
[Typo] List of stupid errors I've found in Configuration.pdf

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#916]
As per title, I wanted to open this repository in order to report you some typos found while reading [Configuration.pdf.](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf). As per now, I've only found one but I'll try to read carefully the list.

## Typo nr. 1 

![image](https://user-images.githubusercontent.com/17933708/81995472-c2502500-964a-11ea-91dd-f4c3803f2a8a.png)

Line: `CFG Lock (MSR 0xE2 write protection) disabled in firmware settings if present. **Cconsider** patching it if you have`

**Comment by Andrey1970AppleLife** [comment]
Fixed.
