### ISSUE TITLE
drag lock when the physical button released

### ISSUE THREAD

**Issue by alikazemkhanloo** [acidanthera/bugtracker#917]
Hi,
when dragging with physical button pressed, the drag locks for ~2 sec after releasing the button.
There is a temporary fix [here](https://github.com/VoodooI2C/VoodooI2C/issues/290#issuecomment-629153395). But the actual fix have to be done in VoodooInput.

Thanks in advance.

**Comment by vit9696** [comment]
@Goshin will need details on this.

CC @usr-sse2

**Comment by alikazemkhanloo** [comment]
Also, I've seen my friend drag a file or something across the desktops on real Mac. He just presses down the touchpad with the thumb to start the drag, and then use the other three fingers to change the desktop while dragging. when I try to do that, when I release the other three fingers, it gets stuck in the three-finger-gesture. it may be related to this issue.
