### ISSUE TITLE
DuetPkg/macbuild.tool: line 502: 48006 Terminated: 15          pingme $! build "$@"

### ISSUE THREAD

**Issue by kommtzeitkonrad** [acidanthera/bugtracker#918]
Recent commits seem to have introduced a bug in `DuetPkg/macbuild.tool` as it fails after building:

```
Building...
Building DuetPkg/DuetPkg.dsc for X64 in DEBUG with XCODE5...
.. - OK
Building DuetPkg/DuetPkg.dsc for X64 in RELEASE with XCODE5...
.. - OK
Building DuetPkg/DuetPkg.dsc for IA32 in DEBUG with XCODE5...
... - OK
Building DuetPkg/DuetPkg.dsc for IA32 in RELEASE with XCODE5...
... - OK
./macbuild.tool: line 502: 48006 Terminated: 15          pingme $! build "$@"
```

Obviously the error is related to the `buildme` function in [`efibuild.sh`](https://github.com/acidanthera/ocbuild/blob/e35f8c2d7deb4c0d93eb3259c24d65007355ba2d/efibuild.sh#L61) although `OpenCorePkg/macbuild.tool` does not fail.

[DuetPkg-macbuild-tool-log-2020-05-15-1921.txt](https://github.com/acidanthera/bugtracker/files/4636003/DuetPkg-macbuild-tool-log-2020-05-15-1921.txt)

**Comment by vit9696** [comment]
There is no bug here, just a warning about trying to acess the process that is already terminated. Feel free to submit a PR silencing this warning if it really bothers you, but it is harmless.

**Comment by kommtzeitkonrad** [comment]
> There is no bug here, just a warning about trying to access the process that is already terminated.

Ah, yes. You're right. Problem was my install script looking for `DuetPkg/Binaries/TARGET/boot`. Symbolic links in `DuetPkg/Binaries/` do not exist, but since building is accomplished before the warning all files in `DuetPkg/UDK/Build/DuetPkg/TARGET_XCODE5/` are present. Thanks once again!

> Feel free to submit a PR silencing this warning if it really bothers you, but it is harmless.

Ⅰ will try to.
