### ISSUE TITLE
The latest version of Lilu will cause the laptop HDMI to no display the screen when booting

### ISSUE THREAD

**Issue by Jie2GG** [acidanthera/bugtracker#921]
Hi Developer. My Laptop in using latest “Lilu” + “WhateverGreen” will appear HDMI no display when booting. But in “Lilu”(1.4.3) + “WhateverGreen”(1.3.8) can beused normally.

So, I did a test:
* Using “Lilu”(1.4.4) + “WhateverGreen”(1.3.9) not beused normally. (no display when booting).
* Using “Lilu”(1.4.4) + “WhateverGreen”(1.3.8) not beused normally. (But “Lilu” (1.4.3) + “WhateverGreen”(1.3.8) can beused normally)

So, I speculate is “Lilu” leads to exception. 
My Laptop is Asus S5300FN. Details framebuffer to [config.plist](https://github.com/Jie2GG/Hackintosh-ASUS-S5300FN/blob/master/EFI/OC/config.plist#L344) view.

**Comment by OldDream** [comment]
in my dell xps 9570 ， lilu1.4.4 + weg1.3.9 = no HDMI signal ，lilu1.4.4  + weg1.3.8 works well

**Comment by Jie2GG** [comment]
> in my dell xps 9570 ， lilu1.4.4 + weg1.3.9 = no HDMI signal ，lilu1.4.4 + weg1.3.8 works well

我的情况和你的确实不大一样, 我使用 Lilu 1.4.3 + Weg 1.3.8 时则工作良好. 一但我升级到 Lilu1.4.4 无论 weg 是哪个版本都会导致 HDMI 在开机时不显示画面

**Comment by PMheart** [comment]
> 我的情况和你的确实不大一样, 我使用 Lilu 1.4.3 + Weg 1.3.8 时则工作良好. 一但我升级到 Lilu1.4.4 无论 weg 是哪个版本都会导致 HDMI 在开机时不显示画面

**To those who may potentially help, in case of language problems:**
Here it is a bit different. Everything was just fine with Lilu 1.4.3 + WEG 1.3.8, while Lilu 1.4.4 failed to work with any version of WEG with the problem of black screen when connected to HDMI port.

**Comment by vit9696** [comment]
No logs, no obvious hardware description. I do not think WEG 1.3.9 or Lilu 1.4.4 really changed anything, if you find the commit that breaks things (e.g. via git bisect) post it here and we could check. Most likely it is just your hardware being unstable or some configuration problem.

**Comment by OldDream** [comment]
https://drive.google.com/file/d/1sylCtmpoFDhHta_u55VdC89uX_TU_02z/view?usp=sharing

This is my ioreg file(1.3.8 + 1.3.9), SSDT and Opencore config file.
In weg1.3.9 ioreg didn't change when I pulgIn or unplug HDMI.
This is my HDMI port: IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebuffer@3
I found there are some difference in ioreg with 1.3.8-unplug-HDMI and 1.3.9-nosignal.
Hope this can help.

**Comment by vit9696** [comment]
Look, I know that on these Dell laptops IGPU may fail to reinitialise during reboots due to some buggy HDMI audio. You can reboot and it borks, whether you update WEG or not. WEG is not related here.

CC @lvs1974. Could you direct these people with the relevant configuration info? Pretty sure it is all the same Dell with the ugly HDMI issue.

**Comment by OldDream** [comment]
> Look, I know that on these Dell laptops IGPU may fail to reinitialise during reboots due to some buggy HDMI audio. You can reboot and it borks, whether you update WEG or not. WEG is not related here.
> 
> CC @lvs1974. Could you direct these people with the relevant configuration info? Pretty sure it is all the same Dell with the ugly HDMI issue.

Got it ,  I would check HDMI audio.

**Comment by lvs1974** [comment]
This issue was introduced in commit 83ea22ebac4a17e080eff9ab3541222a987ad92f (WhateverGreen).

**Comment by vit9696** [comment]
Resolved in master.

**Comment by OldDream** [comment]
I build the latest version, It works ！

 @Jie2GG  Try this：
https://drive.google.com/file/d/1mfrS9B2xSJhWFkGi7Owy8nW7oCwRVKyo/view?usp=sharing

**Comment by Jie2GG** [comment]
> I build the latest version, It works ！
> 
> @Jie2GG Try this：
> https://drive.google.com/file/d/1mfrS9B2xSJhWFkGi7Owy8nW7oCwRVKyo/view?usp=sharing

Thank you very much for compiling the driver. but my laptop of HDMI port not working. have to hot plug.

**Comment by Jie2GG** [comment]
[Info.zip](https://github.com/acidanthera/bugtracker/files/4645014/Info.zip)

@vit9696 Sorry, I forgot to attach these documents. this is some information about my computer (including logs, plist and SSDT).  I hope this information is useful.

**Comment by OldDream** [comment]
> [ASUS-S5300FN-Info.zip](https://github.com/acidanthera/bugtracker/files/4645014/Info.zip)
> 
> @vit9696 Sorry, I forgot to attach these documents. this is some information about my computer (including logs, plist and SSDT). I hope this information is useful.



> > I build the latest version, It works ！
> > @Jie2GG Try this：
> > https://drive.google.com/file/d/1mfrS9B2xSJhWFkGi7Owy8nW7oCwRVKyo/view?usp=sharing
> 
> Thank you very much for compiling the driver. but my laptop of HDMI port not working. have to hot plug.

If you are using 10.15.4, add bootargs igfxonln=1,igfxagdc=0, this might help.

**Comment by Jie2GG** [comment]
> If you are using 10.15.4, add bootargs igfxonln=1,igfxagdc=0, this might help.

I befor using bootargs igfxonly=1. but invalid
