### ISSUE TITLE
[Semantics] Consider Alternative Term for "Delete"

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#923]
v0.5.9 changes `Block` to `Delete` in the config. 

While `Block` was a bit vague/confusing and definitely a good idea to change, it was a lot closer to the action taken than `Delete` with comes with implications of being a final and destructive action that does not reflect what is taking place.

Perhaps something like `Override` or `Nullify` or `Negate` might be better?

**Comment by vit9696** [comment]
From UEFI Specification for variable management:

> `SetVariable()`
>
> **Summary**
>
> Sets the value of a variable. This service can be used to create a new variable, modify the value of an existing variable, or to delete an existing variable.

The term used is correct.
