### ISSUE TITLE
Do not move Bootstrap.efi to the top if it exists

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#924]
Bootstra.efi is a very good idea to avoid opencore being deleted by Micro$oft, but there is a small glitch:

###  Case 1:  Bootstrap.efi does not exist in BIOS boot menu:
boot opencore the first time, it will create Bootstrap.efi and set it to be the first in BIOS boot menu, which is fine.

###  Case 2: Bootstrap.efi exists in BIOS boot menu:
1. manually set other disk (linux disk e.g.) to be the first in BIOS boot menu
2. on BIOS post, press F11 or alike to boot OpenCore once.
3. The first item set previously in BIOS boot menu will be changed to OpenCore, which is **not fine**

### what to expect:

if Bootstrap.efi exist in BIOS boot menu, do not force it to be the first one, let BIOS settings handle the order?

**Comment by vit9696** [comment]
This is the correct behaviour. We believe that nobody should use BIOS boot options once he installs OpenCore. Thus Bootstrap becomes first to ensure no bugs from the BIOS and improve boot performance to OpenCore.

In the future we will continue to make it even harder to use BIOS options for anything. Most likely, there will be something what DuetPkg currently is. I.e. a thing that loads OpenCore.efi directly from the firmware.
