### ISSUE TITLE
BT version bump to 12.0.1.658

### ISSUE THREAD

**Issue by lwndow** [acidanthera/bugtracker#925]
For BrcmPatchRam, you asked if anyone came across something newer than 12.0.0.9860, to let you know. While searching for my vendor/product ID, I came across this AUR repo that links to an ASUS zip file which lists it's version as 12.0.1.658.

https://aur.archlinux.org/packages/bcm20702b0-firmware
http://dlcdnet.asus.com/pub/ASUS/wireless/USB-BT400/DR_USB_BT400_1201710_Windows.zip

Thought you'd like to know. Cheers and thanks for your work!

**Comment by vit9696** [comment]
Thanks for the link. Actually it seems that despite being named as 12.0.**1** this one is much older, dating back to 2015.
