### ISSUE TITLE
Level2CommandsLib/Ls.c(527): Node Info != ((void *)0)

### ISSUE THREAD

**Issue by Dawn13** [acidanthera/bugtracker#927]
I'm on 0.5.9 Debug Version trying to install Catalina on Vostro laptop with an 
i5-10210U. No luck so far with OSX, though booting fine Win10 through the same setup.

When I launch ( ls fs/number of filesystem: ) in openshell.efi I can't access/see filesystems on my laptop, except for the external USB drive ( OC on EFI / 10.15.4 installer )
- ls fs from USB EFI : all files & dir
- ls fs from USB Main: all installer files
- ls fs from internal SATA: 0 Files / 0 Dir  ( but tons of files on it )
- ls fs from internal M.2 Nvme: ends with what I wrote in the title

In OCs boot menu the OSX installer is visible, but when I try to launch, it hangs at
"LoadImage Failed - Access Denied"

I also copied a clone ( Catalina ) to the M2. Nvme, no joy too. Then pulled out the drive, installed it in my main hack and booted without issues.

Anything I can do to move forward, I'm willing to try to debug further. But to be honest I don't know what I should do next.
Attached my EFI + Debug log + complete Sys specs 
Thanks for any comments!
[Vostro_5490_Debug.zip](https://github.com/acidanthera/bugtracker/files/4661068/Vostro_5490_Debug.zip)

**Comment by vit9696** [comment]
This looks like EDK II bug to me. Are you sure you use the latest HFSPlus driver (or is that APFS?)

CC @Download-Fritz

**Comment by Dawn13** [comment]
HFS+ is from Sep2019, don't know if that's the latest available
I tried with VBOXHFS too with the same results.

- External USB is a GPT/HFS+ drive with the installer on it
- NVME is GPT with 1st Partion as NTFS with Win10 , 2nd is  APFS (tried with empty partition    and cloned Catalina on it )
- The SATA is GPT with 1 NTFS

I've merged WIN and OC EFI on the NVME too:
- WIN boots just fine
- neither the installer on ext USB or the cloned Catalina want to boot
- openshell gives the exact same results as in my 1st post

And I cross checked with my main hack. There I can boot the installer from the external USB with the same EFI ( using another config file of course because its an Z390/9900K ) without any issues. Also no problems booting into openshell and list/access filesystems , no matter if NTFS, HFS, APFS.... 

I did all this with HFS & VBOBHFS

**Comment by Download-Fritz** [comment]
This is strictly not (only) an issue of Shell, but a consequence of it receiving nonsense data from the FS driver. We suspect you use a borked NTFS, ExtFAT or HFS+ driver, possibly even from your firmware (especially as it's an OEM board). If you chose these, where are they from? If they're broken in your FW, there is nothing we can do really.
