### ISSUE TITLE
NVRAM was updated when WriteFlash set to false

### ISSUE THREAD

**Issue by hlyi** [acidanthera/bugtracker#929]
My understanding is that when "WriteFlash" set to false, NVRAM should not be updated. However, hackintool shows different NVRAM even with "WriteFlash" set to false. 

Looking at code, the WriteFlash set EFI_VARIABLE_NON_VOLATILE flag, but the flag only gets checked when WriteProtection set 1, which is apple only setting.

I am looking for a way to reduce wear and tear on flash memory, if WriteFlash is not intended for that purpose, could you please add a feature to do so?

Thanks

**Comment by vit9696** [comment]
Erng, but why would not Hackintool see the variable? Volatile variables are visible just like non-volatile. The only issue is that they are only stored in RAM (instead of flash) and not preserved across the reboots. If you remove the variable from the config it will disappear (unlike the flashed variable, which will remain).

**Comment by hlyi** [comment]
My point was that every boot, nvram are written regardless necessary or not based upon the sample.plist. In NVRAM section, it deletes existing variables, such as boot-args in "Block(Delete)" section then adds it back in "Add" section. Even nothing changed, flash memory still get updated. It will be better have the section behave like this: if variable doesn't exist, adds it. If already exists, replace with new value if it is different then previous one. So most of time, NVRAM will not be touched. It reduces wear and tear on Flash Memory.

**Comment by vit9696** [comment]
Erng, but that is exactly like it is?.. Variables with the same values are not deleted (and thus not added). Maybe I am missing something?

**Comment by hlyi** [comment]
The "replace" is the feature I was looking for. OC didn't do that. I thought "writeflash" is kind of compromise, i.e. when writeflash set true, NVRAM gets updated according to add/delete, when set to false, NVRAM will not be touched. However, when I tested it, OC updated flash regardless writeflash setting.

**Comment by vit9696** [comment]
@_@. Let's start with the design and agree on how it is meant to work:

- Variables meant to be deleted are processed.
    - If variable has no Add counterpart, then it is deleted if it exists (the latter is handled by the firmware).
     - If variable has Add counterpart, then its value is read and compared against added value. If the value does not match, the variable is deleted, otherwise nothing happens.
     - In both cases when deletion happens, write to flash happens. This is how UEFI variable management works, we cannot do much here.
- Variables meant to be added are processed.
    - If variable exists, nothing happens.
    - If variable does not exist, it is written. When WriteFlash is disabled, the variable is written to RAM, not flash, so that we do not wear flash.

Do you see any obvious flaws with this design? We do not. And believe this is how it is currently implemented. If you do, please stop here and point out where this *design* is wrong.

If there are no questions about the design, but you suspect that OpenCore *behaves* differently, I will ask for code proofs.

**Comment by hlyi** [comment]
I agree with the design approach 100%. It is what I was looking for. Thanks for stating that clearly.  I will double check my test and code.

**Comment by hlyi** [comment]
Maybe I missed something here. 

1. set WriteFlash to true, and boot-args without "-v", after boot, use hackintool checking NVRAM, boot-args has no "-v" as expected. 
2. changed "writeFlash" to false, and added "-v" in config.plist. then reboot computer. 
3. Boot in verbose mode as expected. Opened up hackintool to check NVRAM. expectation was "-v" not in boot-args. But "-v" did show up.

Looked at code: func OcDeleteNvram matches what you described. However, I am not sure about OcAddNvram. 
- OcSetNvramVariable is unconditionally called. 
- SetVariable is called in OcSetNvramVariable.
- WriteFlash is selecting between OPEN_CORE_NVRAM_NV_ATTR and OPEN_CORE_NVRAM_ATTR, and difference is EFI_VARIABLE_NON_VOLATILE flag
- EFI_VARIABLE_NON_VOLATILE was used in WrapSetVariable, which only if effective when  WriteProtection is true.

**Comment by vit9696** [comment]
Regarding your first statement. Please note, that hackintool or any similar software including macOS nvram command do *not* distinguish volatile and non-volatile variables. For the any variable is "nvram", despite some of them being actually stored in RAM, not in NVRAM. So your expectation is wrong, nvram utility and alike will always see the actual value of the variable, and -v should have been there.

Regarding OcSetVariable. SetVariable is not called when GetVariable finds a variable (EFI_BUFFER_TOO_SMALL case). EFI_VARIABLE_NON_VOLATILE flag means write to flash, without this flag it is write to RAM. WrapSetVariable can (optionally) protect from any writes to flash, this is a separate feature named DisableVariableWrite.

**Comment by hlyi** [comment]
Thanks for clarifying the expectation. Which tool do you recommend to check actual NVRAM?

I am not familiar EFI_BUFFER_TOO_SMALL case. Do you mean if the variable exists, it will set EFI_BUFFER_TOO_SMALL?

I could only find EFI_VARIABLE_NON_VOLATILE used in the following code. when writeProtection is 0, is flash always written, regardless EFI_VARIABLE_NON_VOLATILE?
`  if (gCurrentConfig->WriteProtection && (Attributes & EFI_VARIABLE_NON_VOLATILE) != 0) {
    return EFI_SECURITY_VIOLATION;
  }
`

**Comment by hlyi** [comment]
>     * Variables meant to be deleted are processed.
>       
>       * If variable has no Add counterpart, then it is deleted if it exists (the latter is handled by the firmware).
>       * If variable has Add counterpart, then its value is read and compared against added value. If the value does not match, the variable is deleted, otherwise nothing happens.
>       * In both cases when deletion happens, write to flash happens. This is how UEFI variable management works, we cannot do much here.
> 
>     * Variables meant to be added are processed.
>       
>       * If variable exists, nothing happens.
>       * If variable does not exist, it is written. When WriteFlash is disabled, the variable is written to RAM, not flash, so that we do not wear flash.
> 
> 
Could you please clarify one case:  "In both cases when deletion happens, write to flash happens. " what if WriteFlash is set to false?

**Comment by vit9696** [comment]
> Thanks for clarifying the expectation. Which tool do you recommend to check actual NVRAM?

I don't know if there is any for macOS. You could always use dmpstore in UEFI Shell (when you boot it before OpenCore, so that no changes apply).

> I could only find EFI_VARIABLE_NON_VOLATILE used in the following code. when writeProtection is 0, is flash always written, regardless EFI_VARIABLE_NON_VOLATILE?

`SetVariable` writes to both flash and RAM, the choice happens based on the attributes.

> Could you please clarify one case: "In both cases when deletion happens, write to flash happens. " what if WriteFlash is set to false?

It will still write to flash, because you cannot create a new variable when a flash variable exists.

Check the UEFI spec here: https://uefi.org/specifications. It explains all of the attributes and return codes for GetVariable and SetVariable.
