### ISSUE TITLE
whatevergreen 1.3.9 breaks hdmi on dell xps 7590 - reboots!

### ISSUE THREAD

**Issue by shadowed87** [acidanthera/bugtracker#930]
If I update Whatevergreen to 1.3.9 and plug the hdmi, the system reboots.

this is my whole efi:
https://github.com/shadowed87/Hackintosh-XPS-7590

**Comment by vit9696** [comment]
This is fixed in 1.4.0. You can downgrade to 1.3.8 or upgrade to 1.4.0 β.
