### ISSUE TITLE
Sleep/awake how?

### ISSUE THREAD

**Issue by asgmeonerandom** [acidanthera/bugtracker#931]
# Goal: Making Sleep works - Works on Windows And Linux

## What's happened
On Menu make computer to sleep shutdown and reboot -> crash.

## What's suppose to happen

Computer should go to sleep and when click on power button it should awake and able to continue work.

Hello all,

I'm looking for a guide or a way to sleep/wake on my system.

Others, they report it works out of the box without modifying anything. While others, with same CPU Architecture reports they have the same issue.

CPU: I7-4710HQ
DSDT File: https://drive.google.com/file/d/1KN7Ul14sEfyRwQXcleZh79N6gUUCy1O_/view?usp=sharing

### Related issues
(FIXED) NOT the same hardware/dsdt #471 
**(NOT RESOLVED) SAME ISSUE** #817
-----

## EFI/OC/ACPI Files:
* SSDT-dGPU-Off
* SSDT-EC
* SSDT-EHCx_OFF
* SSDT-HPET
* SSDT-PLUG
* SSDT-PNLF

* I done USBMap, disable XHCIPortLimit.

<details>
<summary>Message of crash after sleep</summary>

```
Sleep Wake failure in EFI

Failure code:: 0xffffffff 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time: 2020-05-22 00:24:23 +0300
OS Version: ??? ??? (Build ???)
Architecture: x86_64
Report Version: 29

Data Source: Stackshots
Shared Cache: 0x5e8d000 E5108303-62DF-36B1-88FD-DF4B43886635

Event: Sleep Wake Failure
Duration: 0.00s
Steps: 1

Boot args: -v keepsyms=1 debug=0x100 -wegnoegpu

Time Awake Since Boot: 54s



Process: swd [260]
Architecture: x86_64
Footprint: 436 KB
Start time: 2020-05-22 00:24:23 +0300
End time: 2020-05-22 00:24:23 +0300
Num samples: 1 (1)

Thread 0x707 1 sample (1) priority 4 (base 4)
<thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
1 start + 1 (libdyld.dylib + 109769) [0x7fff6cf94cc9] 1
1 ??? [0x1066b8454] 1
1 ??? [0x1066b81dd] 1
1 __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 135862) [0x7fff6d0f62b6] 1
*1 ??? [0xffffff80002c8206] 1
*1 ??? [0xffffff80009875f7] 1
*1 ??? [0xffffff80008a0001] 1
*1 ??? [0xffffff80002eb9e7] (running) 1

Binary Images:
0x7fff6cf7a000 - 0x7fff6cfb0fff libdyld.dylib (750.5) <D2A07EF5-A64B-3692-BE13-89DAA2EC5E80> /usr/lib/system/libdyld.dylib
0x7fff6d0d5000 - 0x7fff6d101fff libsystem_kernel.dylib (6153.101.6) <E76440E1-D1E8-3D9A-8B47-D01F554FF1C4> /usr/lib/system/libsystem_kernel.dylib
Model: MacBookPro11,2, BootROM 159.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.5 GHz, 16 GB, SMC 2.18f15
Graphics: Intel HD Graphics 4600, Intel HD Graphics 4600, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, Unknown, HMT41GS6AFR8A-PB
Memory Module: BANK 2/DIMM2, 8 GB, DDR3, 1600 MHz, Unknown, HMT41GS6AFR8A-PB
Bluetooth: Version 7.0.4f6, 3 services, 24 devices, 1 incoming serial ports

```
</details>

What I tried but none worked:
* Read dortania from cover to cover, especially [this](https://dortania.github.io/OpenCore-Desktop-Guide/post-install/pm.html)
* I didn't use CPUFriendly because being said it's only above Skylake
* **ProtectMemoryRegions** is set to False
 * methods doesn't exist in my DSDT (GPRW, UPRW, _PRW )
source : https://1revenger1.gitbook.io/laptop-guide/battery-power-management/correcting-sleep-problems AND https://dortania.github.io/USB-Map-Guide/misc/instant-wake.html

but having those references searching for UPRW / _PRW (could this help to solve the problem?)

<details>
<summary>_PRW, UPRW Search</summary>

```
# _PRW
Device (PXSX)
            {
                Name (_ADR, Zero)  // _ADR: Address
                Name (_PRW, Package (0x02)  // _PRW: Power Resources for Wake
                {
                    0x09, 
                    0x03
                })
            }
Name (_PRW, Package (0x02)  // _PRW: Power Resources for Wake
            {
                0x09, 
                0x03
            })


# UPRW
 OperationRegion (PMIO, SystemIO, PMBS, 0x80)
        Field (PMIO, ByteAcc, NoLock, Preserve)
        {
                ,   14, 
            PEWS,   1, 
            Offset (0x28), 
            Offset (0x2A), 
                ,   3, 
            GPE3,   1, 
                ,   7, 
            GPEB,   1, 
            Offset (0x3C), 
                ,   1, 
            UPRW,   1, 
            Offset (0x42), 
                ,   1, 
            GPEC,   1
        }
```

</details>

 i looked over all internet, tried `pmset -g log | grep -e "Wake.*due to "` but doesn't display any output.

```bash
$ pmset -g
System-wide power settings:
 SleepDisabled		0
Currently in use:
 standby              0
 womp                 0
 halfdim              1
 hibernatefile        /dev/null
 powernap             0
 gpuswitch            2
 networkoversleep     0
 disksleep            10
 standbydelayhigh     86400
 sleep                10
 autopoweroffdelay    28800
 hibernatemode        0
 autopoweroff         0
 ttyskeepawake        1
 displaysleep         10
 highstandbythreshold 50
 standbydelaylow      10800

```

 **I tried asking in applelife.ru but they deleted my post!**

**Comment by asgmeonerandom** [comment]
UP 

tried https://dortania.github.io/USB-Map-Guide/misc/shutdown.html : compiled + patch -> same error. Then, changed count from 1 to 0 but same error!

**Comment by vandroiy2013** [comment]
Please don't spam in bugtracker. 
This not a support forum and definitely not your personal blog.  
Your issue is out of our scope.
