### ISSUE TITLE
[Request] SSDTs to implement two batteries as one for VirtualSMC battery kext

### ISSUE THREAD

**Issue by Juan-VC** [acidanthera/bugtracker#933]
I found my laptop's battery is only charging to 74% because macOS is not using the second battery, there is an SSDT to implement BAT0 and BAT1 a single one for SMCBatteryManager, which I want to avoid because VoodooI2C works kinda buggy with it when on battery. I wanted to request a template SSDT to fully use both batteries. Thanks!

**Comment by armenio** [comment]
@Juan-VC what´s your laptop model?

**Comment by armenio** [comment]
I have my own version (based on @RehabMan) of BATC.dsl here: https://github.com/armenio/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-BATC.dsl

It include _BIX method. If your nat ACPI has no _BIX, remove _BIX method.

**Comment by Juan-VC** [comment]
Dell G7 7588, attaching system dissassembled DSDT
[DSDT.zip](https://github.com/acidanthera/bugtracker/files/4670648/DSDT.zip)

**Comment by Juan-VC** [comment]
> I have my own version (based on @RehabMan) of BATC.dsl here: https://github.com/armenio/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-BATC.dsl
> 
> It include _BIX method. If your nat ACPI has no _BIX, remove _BIX method.

Oh nice to know, changes I need to test if it works for me is copy your BATC.aml to my OC acpi folder and then copy a DSDT which has Notify (...BAT1...) to (...BATC...) am I right?

**Comment by Juan-VC** [comment]
Oh and remove the _BIX method as my battery doesn't seem to have such method.

**Comment by armenio** [comment]
> > I have my own version (based on @RehabMan) of BATC.dsl here: https://github.com/armenio/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-BATC.dsl
> > It include _BIX method. If your nat ACPI has no _BIX, remove _BIX method.
> 
> Oh nice to know, changes I need to test if it works for me is copy your BATC.aml to my OC acpi folder and then copy a DSDT which has Notify (...BAT1...) to (...BATC...) am I right?

Use BATC.dsl without _BIX 
[DSDT.dsl.zip](https://github.com/acidanthera/bugtracker/files/4670654/DSDT.dsl.zip)

According your ACPI, you no need to find there is a fully qualified path.

**Comment by Juan-VC** [comment]
<img width="1552" alt="Screen Shot 2020-05-22 at 12 02 22 PM" src="https://user-images.githubusercontent.com/30065686/82714753-4c048180-9c4d-11ea-9709-cd445d2d84f1.png">

Dang it seems I still get the capacity of only one :(

**Comment by armenio** [comment]
You need to read carefully instructions in BATC.dsl

**Comment by vit9696** [comment]
I believe something like this is a request for guides rather than for software documentation, us. We believe the documentation is good enough, though will always try to accept external modifications.

**Comment by armenio** [comment]
Thank you so much for the help, man.


Em sáb, 23 de mai de 2020 03:33, vit9696 <notifications@github.com>
escreveu:
