### ISSUE TITLE
Does OpenCore can awake? #help

### ISSUE THREAD

**Issue by asgmeonerandom** [acidanthera/bugtracker#934]
#931

**Comment by asgmeonerandom** [comment]
@vit9696 you are my only hope please help

**Comment by asgmeonerandom** [comment]
@vit9696 i offer you ida pro license if you fix it

**Comment by asgmeonerandom** [comment]
@vit9696 DONT GO

**Comment by Download-Fritz** [comment]
@asgmeonerandom You have been instructed already to not abuse the bug tracker for your personal misconfigurations. To be clear on this, anyone avoiding ticket closing (including you) will be blocked on organization level with no further comment or discussion.
