### ISSUE TITLE
https://github.com/acidanthera/VoodooPS2 Can 2 fingers scroll work please?

### ISSUE THREAD

**Issue by asgmeonerandom** [acidanthera/bugtracker#935]
Hello,

Is there a way to add this feature?

thank u devs
 for everthing

**Comment by usr-sse2** [comment]
It works, what’s the issue?

**Comment by vit9696** [comment]
I will probably close this. @usr-sse2 feel free to reopen if you conclude that there is an issue on our side.

**Comment by asgmeonerandom** [comment]
> It works, what’s the issue?

My laptop touchpad is ELAN.
I tried to scroll with 2 fingers like windows/linux but doesn't do anything.
I know I don't use trackpad but may be related? On mac settings it says trackpad not detected.

**Comment by Andrey1970AppleLife** [comment]
ELAN PS2 not supported.

**Comment by asgmeonerandom** [comment]
> ELAN PS2 not supported.
> Use https://osxlatitude.com/forums/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/

it;s made mouse move very fast and touch clicks not work then it crash

![image](https://user-images.githubusercontent.com/64754175/82741507-472df380-9d5b-11ea-8ca9-0e83529b83d8.png)
i revert to VoodooPS2Controller.kext and my mouse not respondin well and touchpad too

**Comment by asgmeonerandom** [comment]
@usr-sse2 there is no feature of scrolling

**Comment by usr-sse2** [comment]
>@usr-sse2 there is no feature of scrolling

@asgmeonerandom There are no features for ELAN here.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
