### ISSUE TITLE
OpenCore 0.5.8 keyboard not working on FX

### ISSUE THREAD

**Issue by GuyInHiding** [acidanthera/bugtracker#936]
I've been using 0.5.5 and the keyboard works perfectly fine, but anything higher doesn't work. I also tried the GUI on and the mouse works, but is really slow and then OC crashes. Is it just a issue with FX?

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by GuyInHiding** [comment]
I don't need support, but I was just saying that I can't use the keyboard in the boot picker and I have seen other people have issues with it

**Comment by vit9696** [comment]
Sorry for confusion, this is a duplicate. https://github.com/acidanthera/bugtracker/issues/754. Use a suggested workaround.
