### ISSUE TITLE
OC: Weird bootscreen remnant on loginscreen

### ISSUE THREAD

**Issue by kecinzer** [acidanthera/bugtracker#940]
I have weird minor issue with OpenCore ([my files](https://github.com/kecinzer/hpelitebook850g5-opencore/tree/master/EFI/OC)). After I wake up screen and login into macOS, I see for a while booting screen and then normal login screen into macOS. It seems to some buffered thing. This occuring every time. Sleep and wake from sleep solves it, so after sleep it work normally.

I'm attaching video of this issue.
https://drive.google.com/open?id=1_8a8YukSJjiXuySTFPdWWgUdoo2S-PPl
May be it can be solved simply by some option in OpenCore or WEG?

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
