### ISSUE TITLE
Updated to macOs 10.15.5 Mac battery health option is not coming

### ISSUE THREAD

**Issue by nikhil19rathore99** [acidanthera/bugtracker#941]
![Screenshot 2020-05-27 at 9 33 58 PM](https://user-images.githubusercontent.com/32436513/83044990-98432d80-a062-11ea-91b9-6a1473d366f9.png)
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

Issue tracker is _not_ a support forum, and if you have installation or usage problems, try asking your questions on [InsanelyMac.com](https://www.insanelymac.com/forum/73-developers-corner/) or [AppleLife.ru](https://applelife.ru/forums/xakintosh.67/). There could also be local communities providing Acidanthera Project support in your native language.

- Always include the crash log if the tool crashes for you.

**Comment by cattyhouse** [comment]
not all mac model has that feature, for example, my **Apple made** `MacBook Air 2013 11"` does not have such feature.

**Comment by stevezhengshiqi** [comment]
After some diving, macOS10.15.5 adds a new `Supported Features` called `VAC-T` in `IOPMrootDomain`, which mainly in charge of the battery health function. The `VAC-T` feature is probably published by AppleSmartBatteryManager in `AppleSmartBattery::smcNotifierHandler`:
```
call    __ZN9IOService15getPMRootDomainEv ; IOService::getPMRootDomain(void)
lea     rsi, aVacT      ; "VAC-T"
mov     rdi, rax        ; this
call    __ZN14IOPMrootDomain14publishFeatureEPKc ; IOPMrootDomain::publishFeature(char const*)
```
I guess SMCBatteryManager could do samething like this, publishing VAC-T feature to have the battery health function. Not sure whether my guess will work, and I will try to dig deeper.

**Comment by nikhil19rathore99** [comment]
> After some diving, macOS10.15.5 adds a new `Supported Features` called `VAC-T` in `IOPMrootDomain`, which mainly in charge of the battery health function. The `VAC-T` feature is probably published by AppleSmartBatteryManager in `AppleSmartBattery::smcNotifierHandler`:
> 
> ```
> call    __ZN9IOService15getPMRootDomainEv ; IOService::getPMRootDomain(void)
> lea     rsi, aVacT      ; "VAC-T"
> mov     rdi, rax        ; this
> call    __ZN14IOPMrootDomain14publishFeatureEPKc ; IOPMrootDomain::publishFeature(char const*)
> ```
> 
> I guess SMCBatteryManager could do the same thing like this, publishing VAC-T feature to have the battery health function. Not sure whether my guess will work, and I will try to dig deeper.
> 
> UPDATE: It works for me. By adding `VAC-T` in `IOPMrootDomain`, the battery health comes out and the terminal shows `VACTDisabled` value when running `pmset -g`

Can u provide the smcbatterymanager kext with updated battery health management feature??

**Comment by stevezhengshiqi** [comment]
@nikhil19rathore99 Sure, but as vit9696 said in https://github.com/acidanthera/VirtualSMC/pull/30#issuecomment-650066212, it actually has no real function but just a nice GUI.
[SMCBatteryManager.kext.zip](https://github.com/acidanthera/bugtracker/files/4851030/SMCBatteryManager.kext.zip)
