### ISSUE TITLE
Ice Lake: unsupported cd clock decimal frequency 0x158

### ISSUE THREAD

**Issue by matthew728960** [acidanthera/bugtracker#942]
OpenCore release 0.5.8 
Lilu release 1.4.4

Create﻿ config.plist according [vanilla-laptop-g﻿ui﻿de/icelake](https://dortania.github.io/vanilla-laptop-guide/OpenCore/config-laptop.plist/icelake.html)

[EFI.zip](https://github.com/acidanthera/bugtracker/files/4690721/EFI.zip)
[opencore-2020-05-28-010358.txt](https://github.com/acidanthera/bugtracker/files/4690742/opencore-2020-05-28-010358.txt)

[Aida64_Hasee_X57S1.zip](https://github.com/acidanthera/bugtracker/files/4690720/Aida64_Hasee_X57S1.zip)
[X57S1-Bios.tar.gz](https://github.com/acidanthera/bugtracker/files/4690737/X57S1-Bios.tar.gz)
[X57S1-OEM-DSDT.tar.gz](https://github.com/acidanthera/bugtracker/files/4690749/X57S1-OEM-DSDT.tar.gz)
[IORegistryExplorer_X57S1.zip](https://github.com/acidanthera/bugtracker/files/4690750/IORegistryExplorer_X57S1.zip)

![IMG_20200413_205940](https://user-images.githubusercontent.com/8460881/83053557-7c9c4f00-a083-11ea-9d96-fd0862908d8c.jpg)

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/832#issuecomment-615248243

**Comment by frozenzero123** [comment]
Ask for advice, is there a solution to this problem?

**Comment by asgmeonerandom** [comment]
> yoga s740

it's open source project, you can read the code and contribute it so as korean.

**Comment by marianopela** [comment]
@matthew728960 https://github.com/acidanthera/WhateverGreen/commit/6319f826f7c4c0c2f9b8097cea847ad5265e8946
