### ISSUE TITLE
[WhateverGreen] Kernel panic in 10.15.5 with UHD360 (i3-8100)

### ISSUE THREAD

**Issue by rbesora** [acidanthera/bugtracker#943]
Hi,

A perfect working Hackintosh, with OS X 10.15.4. Motherboard Gigabyte Z370M D3H, CPU i3-8100, 8GB RAM. After update to 10.15.5 the computer reboots with a kernel panic. Have to restore a TimeMachine Backup to 10.15.4 again.

It seems that Framebuffer patching is broken with 10.15.4 release with some UHD630 versions, my IGPU Device ID is 0x3e91.

I have tested several values for AAPL,ig-platform-id, "07 00 9B 3E", "00 00 9B 3E", also I have made framebuffers connectors patch, that works well in 10.15.4 but does not work well in 10.15.5.

I attached my EFI folder, a kernel panic, Opencore debug log. I will attach as soon as posible a Lilu debug all file, now I'm testing with a 10.15.5 Mac OSBase system usb and it seems that the Lilu Log doesn't get saved.

I will try to get a second hard disk to make tests and a full install of Mac OS 10.15.5 to see if I can get that log. If I can give more details, please ask me.

Regards

[opencore-2020-05-29-144410.txt](https://github.com/acidanthera/bugtracker/files/4702522/opencore-2020-05-29-144410.txt)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4702523/EFI.zip)
[KernelPanic.txt](https://github.com/acidanthera/bugtracker/files/4702554/KernelPanic.txt)

**Comment by rbesora** [comment]
Also, two details. If I boot with disablegfxfirmware it boots 10.15.5 but without graphics acceleration. If I boot with igfxonln=1 I get a kernel panic (I needed this setting with 10.15.4, but not before). If I boot without igfxonln=1 I don't get a kernel panic, but the screen is black, no matter what Framebuffer conector patch I have, I have tested all posibilites in these patches

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/938
