### ISSUE TITLE
Synaptics Thinkpad_Clickpad - no tap to click or any other gesture & no trackpoint working with any version above VoodooPS2 2.1.3 & VoodooInput 1.0.4

### ISSUE THREAD

**Issue by silencer51** [acidanthera/bugtracker#947]
It seems weird, but while version 2.1.3 works fine on my Thinkpad X260, newer versions of the kext seem to only register mouse movement through the touchpad, no gestures of any kind. Also, the trackpoint does not seem to work.

**Comment by vit9696** [comment]
That's a duplicate it seems:
https://github.com/acidanthera/bugtracker/issues/890
