### ISSUE TITLE
NVMeFix KP

### ISSUE THREAD

**Issue by paksman** [acidanthera/bugtracker#949]
Latest commit https://github.com/acidanthera/NVMeFix/commit/009a13233f04484907dcac348bd6bfe1ee1db2a0 in NVMeFix.kext causes kernel panic (samsung 960EVO, Catalina 10.15.5)
![IMG_20200602_130455022](https://user-images.githubusercontent.com/10390777/83514700-6b649f80-a4d4-11ea-916d-16ccb99d9e67.jpg)
[opencore-2020-06-02-105037.txt](https://github.com/acidanthera/bugtracker/files/4716782/opencore-2020-06-02-105037.txt)

**Comment by vit9696** [comment]
The panic is unrelated to NVMe but is somewhere due to Sandbox.kext.

**Comment by 07151129** [comment]
It looks like there is no profile for trustd so the sandbox kext panics. You should check its signature and entitlements.

Judging by the log, NVMeFix was trying to do a bit too much by still registering for active PM even in APST-only mode. This is harmless but not useful; should be addressed in master now.

**Comment by paksman** [comment]
Thanks ! Fixed in: https://github.com/acidanthera/NVMeFix/commit/cbebc4cf84ae2284c4e94bf29fadd449d8134e2c
The kext works wonderful btw...The idle temp of my 960 evo goes down from 35 to 29 °c !
