### ISSUE TITLE
OC Built-In APFS Driver Fails where ApfsDriverLoader Succeeds

### ISSUE THREAD

**Issue by stevereno30** [acidanthera/bugtracker#950]
Loading a vanilla install of OpenCore on my HP EliteBook 850 G1 (Haswell) does not show any APFS partitions. The troubleshooting tips on Dortania are all set correctly (excluding the MinDate MinVersion settings, which also make no difference). Adding ApfsDriverLoader to my /OC/Drivers and config.plist results in them appearing immediately. I have no idea what could be causing it to fail on this machine as it works perfectly on every other device I've tried.

**Comment by Andrey1970AppleLife** [comment]
No your log. Closed as doubtfully.
Use forums for support.
