### ISSUE TITLE
APFS Fusion Drive Not Recognized

### ISSUE THREAD

**Issue by twlawrenceko** [acidanthera/bugtracker#954]
Hello,

As I have an NVMe drive (Samsung 970 Evo) and HDD (WD Black 750GB) which is in macOS Mojave 10.14.6. With v0.5.7 combined with apfs.efi, the fusion drive is being recognized. However, with v0.5.9, NVMe drive can be recognized (known by Windows10 drive) AHCI can also be recognized (macOS 10.15.1), but Fusion drive is not seen in boot menu.

Here is the section I believe where the fusion drive cannot be read.
`07:814 00:048 OCJS: APFS driver 1412101001000000/20200306 found for 157479BD-F665-3149-902B-19483906E567, required >= 0/0, allow
08:098 00:284 OCJS: Got APFS super block for FFC17929-CD1A-4F4C-AE3A-765FDB2E848B
08:166 00:068 OCJS: Failed to read JumpStart for FFC17929-CD1A-4F4C-AE3A-765FDB2E848B`

[opencore-2020-06-05-090731.txt](https://github.com/acidanthera/bugtracker/files/4735073/opencore-2020-06-05-090731.txt)

[EFI.zip](https://github.com/acidanthera/bugtracker/files/4735081/EFI.zip)

Thanks,
twsps

**Comment by vit9696** [comment]
It is rather difficult to say where exactly it failed even from that log. I improved the logging in master branch, could you please provide a new log with freshly built version? Thanks!

**Comment by twlawrenceko** [comment]
> It is rather difficult to say where exactly it failed even from that log. I improved the logging in master branch, could you please provide a new log with freshly built version? Thanks!

Hello,

I am trying to compile it in Xcode, but received the following error. Would you mind to point out where the error is?
<img width="1512" alt="Screen Shot 2020-06-05 at 6 17 49 PM" src="https://user-images.githubusercontent.com/14770978/83865654-15545e00-a759-11ea-81db-80e9dabb7a63.png">

Thanks,
twsps

**Comment by vit9696** [comment]
Hi, you need to run `build_oc.tool` instead.

**Comment by twlawrenceko** [comment]
> Hi, you need to run `build_oc.tool` instead.

Hello,

Here is the line I believe is important

`08:724 00:061 OCJS: APFS driver 1412101001000000/20200306 found for 157479BD-F665-3149-902B-19483906E567, required >= 0/0, allow
09:019 00:294 OCJS: Got APFS super block for FFC17929-CD1A-4F4C-AE3A-765FDB2E848B
09:094 00:075 OCJS: Unknown JSDR magic 00000000, expected 5244534A
09:156 00:061 OCJS: Failed to read JumpStart for FFC17929-CD1A-4F4C-AE3A-765FDB2E848B - Unsupported`

[opencore-2020-06-05-102800.txt](https://github.com/acidanthera/bugtracker/files/4735454/opencore-2020-06-05-102800.txt)

Thanks,
twsps

**Comment by vit9696** [comment]
It is in a bit in an unexpected place, as I kind of hoped to see it fail earlier… Hmm, it looks like some block number calculation fails. Could you redo the log with the latest update? I moved the i/o logging out of the failure loop.

**Comment by twlawrenceko** [comment]
> It is in a bit in an unexpected place, as I kind of hoped to see it fail earlier… Hmm, it looks like some block number calculation fails. Could you redo the log with the latest update? I moved the i/o logging out of the failure loop.

Hello,

I have looked through the debug log and seems like there's not much detail added.

`07:967 00:049 OCJS: APFS driver 1412101001000000/20200306 found for 157479BD-F665-3149-902B-19483906E567, required >= 0/0, allow
08:251 00:284 OCJS: Got APFS super block for FFC17929-CD1A-4F4C-AE3A-765FDB2E848B
08:320 00:068 OCJS: Block (P:0|F:1) read req 6071358 -> 30389AC0 of 1000 (mask 0, mul 8) - Success
08:379 00:058 OCJS: Unknown JSDR magic 00000000, expected 5244534A
08:428 00:049 OCJS: Failed to read JumpStart for FFC17929-CD1A-4F4C-AE3A-765FDB2E848B - Unsupported`

[opencore-2020-06-05-105500.txt](https://github.com/acidanthera/bugtracker/files/4735628/opencore-2020-06-05-105500.txt)

twsps

**Comment by vit9696** [comment]
Yes, something must be incorrect with the calculation. I will check it in more detail soon.

**Comment by vit9696** [comment]
Try the version in master (and provide the logs please).

**Comment by twlawrenceko** [comment]
> Try the version in master (and provide the logs please).

`03:264 00:051 OC: Connecting drivers...
07:835 04:571 OC: Connecting drivers done...
07:888 00:052 OCJS: Got APFS super block for FFC17929-CD1A-4F4C-AE3A-765FDB2E848B
07:941 00:052 OCJS: Got APFS super block for 157479BD-F665-3149-902B-19483906E567
07:993 00:052 OCJS: Block (P:1|F:0) read req 660782 -> 3303C10 of 1000 (mask 0, mul 8) - Success
08:056 00:062 OCAV: Real image size: 629560
08:112 00:056 OCAV: Signature verified!
08:164 00:051 OCJS: APFS driver 1412101001000000/20200306 found for 157479BD-F665-3149-902B-19483906E567, required >= 0/0, allow
08:449 00:285 OCJS: Got APFS super block for FFC17929-CD1A-4F4C-AE3A-765FDB2E848B
08:501 00:051 OCJS: Block (P:1|F:1) read req 6071358 -> 30389AC0 of 1000 (mask 0, mul 8) - Success
08:562 00:061 OCAV: Real image size: 602936
08:618 00:055 OCAV: Signature verified!
08:669 00:051 OCJS: APFS driver 945275008000000/20200211 found for FFC17929-CD1A-4F4C-AE3A-765FDB2E848B, required >= 0/0, allow`

[opencore-2020-06-05-153635.txt](https://github.com/acidanthera/bugtracker/files/4737128/opencore-2020-06-05-153635.txt)

For now, APFS is being recognized. For the same settings as the first post with config.plist, I do not get any boot chime although showing success. The only concern is the AudioOut, with motherboard ASUS Z270i Strix, I have set AudioOut to 2 (although I believe it should set to 5, but result in Invalid Parameter in log). I believe this is my personal misunderstanding that leads to no boot chime (expecting from front headphone jack), is there any idea why this would occur?

Thanks a lot for the APFS fusion drive fix

twsps

**Comment by vit9696** [comment]
Thanks for testing. As for audio out, you have 5 values from 0 to 4:
```
10:536 00:043 OCAU: 1/2 PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (5 outputs) - Success
```

**Comment by wsy** [comment]
Hi, I'm using OpenCore 0.6.0 and OpenCore fails to recognize my APFS Fusion Drive.
According to the above conversation, twlawrenceko's FusionDrive is made of NVMe SSD and SATA HDD. My FusionDrive is made of mSATA SSD and SATA HDD. I doubt whether this can be the cause?
I used to use apfs.efi and apfs_aligned.efi from macOS Catalina ("/usr/standalone/i386") with Clover. So I tried to copy them to /EFI/OC/Drivers/ folder and OC can successfully recognize my APFS volumes. But I got annoying logs printed by apfs.efi and apfs_aligned.efi.

My hardware configuration:
Lenovo K29 laptop
latest macOS Catalina.
CPU: I5 3210M,
Chipset: 7 series HM chipset
SATA Port1: SanDisk SSD 256GB (mSATA)
SATA Port2: WD HDD 500GB (SATA)
SATA Port3: eSATA (External, nothing plugged)

Also, I attached OpenCore logs and files from my APFS Preboot volume
I used DisplayLevel 2151678018 and Target 125(0x7D). However, I don't think the log is detailed enough.

[opencore-withAppleAPFSDriver.txt](https://github.com/acidanthera/bugtracker/files/5094425/opencore-withAppleAPFSDriver.txt)
[opencore-withoutAppleAPFSDriver.txt](https://github.com/acidanthera/bugtracker/files/5094422/opencore-withoutAppleAPFSDriver.txt)
[Preboot.tar.gz](https://github.com/acidanthera/bugtracker/files/5094416/Preboot.tar.gz)

**Comment by wsy** [comment]
@vit9696 Please have a look. Thanks a lot!

**Comment by vit9696** [comment]
`GlobalConfig`, I guess… or some other quirk.

**Comment by wsy** [comment]
> `GlobalConfig`, I guess… or some other quirk.

Sorry, my fault. "Global Reconnect" setting somehow is closed. I turned that on and it's working.
