### ISSUE TITLE
AppleAlc internal speakers not working for ALC230

### ISSUE THREAD

**Issue by SamRanjha** [acidanthera/bugtracker#955]
Hey, I have installed Catalina on my Lenovo Ideapad-520 and tried to use AppleALC for sound. the sound can be played using headphones but no sound is coming through internal speakers. The sound device is Realtek ALC 230 and have tried both the layout ids for the same i.e. 13 and 20 but still the problem persists. I am enclosing my EFI folder as well as a pic of DCPI manager(don't know why but it says codec name as- Realtek(unknown), does that has something to do with this issue? Any help would be really appreciated.
My configuration:
CPU : Intel Core i5-8250U
RAM : 8GB
GPU : Intel UHD Graphics 620/ NVIDIA GeForce MX150 (Disabled for macOS)
Ethernet : Realtek RTL8168GU/8111GU
Audio : Realtek ALC230
Touchpad : Synaptics Trackpad

[DCPI manager](https://photos.app.goo.gl/gNQ7VDyvH9gxfREP6) 

[EFI](https://drive.google.com/file/d/1EdYh0_oLdj3brWI-3snC071SdtZCSxWu/view?usp=drivesdk)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
