### ISSUE TITLE
DBG-059-2020-06-01 chokes on CrScreenshotDxe

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#956]
To investigate another issue, I tried to run the debug version with the same config and it froze with a black screen. Luckily, I maintain alternative pathways that allowed me to boot the machine.

![Screen Shot 2020-06-06 at 8 11 30 AM](https://user-images.githubusercontent.com/1128876/83936590-a107d200-a7cd-11ea-832e-2ec37d04fcb6.jpg)

I had about 100 lines of the square boxes at the bottom which I have trimmed out.
REL-059-2020-06-01 loads fine with the same config.

**Comment by vit9696** [comment]
What is this machine? The error means that you have two issues:

- Your AppleEvent protocol is missing or outdated and as a result CrScreenshotDxe fails to load. I can guess this is an old Mac, so you probably have OpenCore misconfigured (should really have AppleEvent = YES in ProtocolOverrides).
- You try to load an incompatible driver (well, it likely is compatible, just OpenCore is misconfigured, but that is the upper issue) and expect OpenCore to continue running in this case. But it will not do it as you have HaltLevel set to DEBUG_ERROR, i.e. to stop at any fatal error, which is effectively what happened.

From the above I see invalid setup and do not believe there is any issue. Please read the manual. Closing.

**Comment by dakanji** [comment]
> From the above I see invalid setup and do not believe there is any issue.

Thanks. It does work with AppleEvent set to YES in ProtocolOverrides.
Will leave figuring out why this is only applicable to the DBG version as an exercise for later.
