### ISSUE TITLE
EFI Partition Not Hidden by Pattern Recognition BOOTx64.efi

### ISSUE THREAD

**Issue by twlawrenceko** [acidanthera/bugtracker#958]
Hello,

With the HideSelf option being removed in OpenCore, booting EFI is not hidden by itself by HideAuxiliary. This may due to Mac and Windows EFI boot loader all installed on the main OpenCore EFI drive. 

<img width="405" alt="Screen Shot 2020-06-06 at 3 48 33 PM" src="https://user-images.githubusercontent.com/14770978/83939163-2eb6e200-a80d-11ea-8ab5-e72d473134b6.png">

As I believe this will not relate much to config.plist and log, therefore I will be providing information with particular setup that I may be missing.

Thanks,
twsps

**Comment by vit9696** [comment]
It should be skipped as there is a marker in `BOOTx64.efi` if it belongs to OpenCore:

```
$ xxd -g 1 -l 128 /Volumes/EFI/EFI/BOOT/BOOTx64.efi
00000000: 4d 5a 00 00 00 00 00 00 00 00 00 00 00 00 00 00  MZ..............
00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00000030: 00 00 00 00 00 00 00 00 00 00 00 00 80 00 00 00  ................
00000040: 0e 1f ba 10 00 b4 09 cd 21 b8 01 4c cd 21 0f 0b  ........!..L.!..
00000050: 4f 70 65 6e 43 6f 72 65 20 42 6f 6f 74 6c 6f 61  OpenCore Bootloa
00000060: 64 65 72 20 28 63 29 20 41 63 69 64 61 6e 74 68  der (c) Acidanth
00000070: 65 72 61 20 52 65 73 65 61 72 63 68 0d 0a 24 00  era Research..$.
```

Note, that this behaviour is unique to EFI folder where OpenCore was booted from. Other volumes do not have the marker checked for performance reasons.
