### ISSUE TITLE
iStat Menu Sensor Mapping from VirtualSMC

### ISSUE THREAD

**Issue by twlawrenceko** [acidanthera/bugtracker#959]
Hello,

As I have VirtualSMC and sensors kext installed, the sensor information is completely shown in HWMonitorSMC2, however not shown in iStat and it is missing some info. I understand that we would need a mapping for our specific model (my case iMac18,1). I have been searching and looking at docs but does not find a way to do the mapping anywhere. Would you mind to point out where to do the mapping in Xcode?

Thanks,
twsps

**Comment by armenio** [comment]
I agree that the VirtualSMC documentation is very poor and we need instructions on how to customize it.

**Comment by vit9696** [comment]
iStat Menus mapping is rather broken, and is documented here: https://github.com/acidanthera/VirtualSMC/blob/master/Docs/iStat.txt, you can use smcread -s to see the available keys. 

Other than that, VirtualSMC does not support I/O Registry keys at all, so you will not see most of the SMCSuperIO sensors. All in all, you need to contact the developer of iStat Menus for proper VirtualSMC support or use HWMonitorSMC2, which is currently the only thing supported.
