### ISSUE TITLE
ApfsJumpStart fails to connect APFS driver on HP laptop

### ISSUE THREAD

**Issue by SkyrilHD** [acidanthera/bugtracker#960]
Hi,

so I was hackintoshing a HP EliteBook 8570w and it works well. But since the beginning of using OC (OpenCore) 0.5.8, I noticed that booting into Installer works (since it is HFS+). Meaning installing works fine, but after the second reboot the internal drive doesn't show anymore. So, I thought it might be an APFS conversion issue and tried installing again. But it still didn't show the drive. Then I came to the idea what would happen if I put 'ApfsDriverLoader.efi' from 'AppleSupport-2.1.6-RELEASE' to the drivers folder of my EFI. And it worked! So I let the installation complete and now it is usable with its current state.

On 3rd June 2020, I hackintoshed an Acer Predator 17 (G9-793). So it's running OC 0.5.9 + all the latest kexts. And it had the same issue too.

But I even hackintoshed my Dell Latitude E7250 but works without having 'ApfsDriverLoader.efi'. So that's why I create this issue, maybe it will help.

I hope the attached log will help. If you need anything else, let me know.

[opencore-2020-05-31-004233.txt](https://github.com/acidanthera/bugtracker/files/4741337/opencore-2020-05-31-004233.txt)

Links that might be useful:
https://github.com/SkyrilHD/HP-8570W-Hackintosh
https://github.com/SkyrilHD/Dell-E7250-Hackintosh (old OC commit which I need to update)

**Comment by vit9696** [comment]
There is nothing in the log as you did not make it with a debug version of OC. I will close the issue until a proper log appears.

**Comment by SkyrilHD** [comment]
Just to be sure, is it enough if I convert from Release to Debug by changing BOOT/BOOTx64.efi and OC/OpenCore.efi? Or do I need to do something else?

I thank you in advance

**Comment by vit9696** [comment]
If you use OpenCanopy, you need to install its DEBUG version as well. The rest are unimportant. Also include your EFI folder.

**Comment by SkyrilHD** [comment]
Finally I got the log.

[EFI 22.zip](https://github.com/acidanthera/bugtracker/files/4748363/EFI.22.zip)

[opencore-2020-06-08-200825.txt](https://github.com/acidanthera/bugtracker/files/4748367/opencore-2020-06-08-200825.txt)

**Comment by vit9696** [comment]
The log looks like you do not have valid data on Preboot volume. Could you upload Preboot volume contents? CC @Download-Fritz

**Comment by SkyrilHD** [comment]
How can I see the Preboot volume?

**Comment by SkyrilHD** [comment]
So, the guy finally got time.

I just deleted 'loginui.efires', otherwise it won't upload to GitHub.

[8DC3265C-851D-4EEB-BFA1-2DE89E48AEDF 2.zip](https://github.com/acidanthera/bugtracker/files/4761828/8DC3265C-851D-4EEB-BFA1-2DE89E48AEDF.2.zip)

**Comment by vit9696** [comment]
Thanks. Could you try moving [these lines]( https://github.com/acidanthera/OpenCorePkg/blob/bf8e36b/Platform/OpenCore/OpenCoreUefi.c#L535-L546) above the connection code, right [here](https://github.com/acidanthera/OpenCorePkg/blob/bf8e36b/Platform/OpenCore/OpenCoreUefi.c#L519)? Afterwards recompile and please retest.

**Comment by SkyrilHD** [comment]
Yep it works!

I moved the lines and compiled them with build_oc.sh and it works.

[OpenCore-0.6.0-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/4768315/OpenCore-0.6.0-DEBUG.zip)

[opencore-2020-06-12-020301.txt](https://github.com/acidanthera/bugtracker/files/4768317/opencore-2020-06-12-020301.txt)

**Comment by vit9696** [comment]
This is nice to hear, but we would ideally like to avoid this solution, as it has some incompatibilities with other platforms, will require a dedicated configuration option, and may cause slight performance issues. Could you please perform another test for us?

1. Disable `ConnectDrivers` in config.plist
2. Disable `EnableJumpstart` in config.plist
3. Add `ApfsDriverLoader.efi` driver

Will it work in this case?

**Comment by SkyrilHD** [comment]
It doesn't work

[EFI 28.zip](https://github.com/acidanthera/bugtracker/files/4775347/EFI.28.zip)

**Comment by vit9696** [comment]
Right, I guess we will introduce a config.plist option to perform global device connection on APFS driver loading in the nearest update. Thanks for the test!

**Comment by vit9696** [comment]
Implemented in master via `GlobalConnect` option. Please report if there are any issues.
