### ISSUE TITLE
(VoodooPS2Controller) ApplePS2Controller:  Time out on keyboard input stream.

### ISSUE THREAD

**Issue by twlawrenceko** [acidanthera/bugtracker#965]
Hello,

With the use of release version of VoodooPS2Controller (debug version does not have such issue), sometimes will result in loss of keyboard functionality. With further checking the boot log, I found out when the PS2 keyboard is not working, this log will show up.

```
2020-06-09 15:40:46.814695+0800 0x104      Default     0x0                  0      0    kernel: (VoodooPS2Controller) ApplePS2Controller: Timed out on keyboard input stream.
2020-06-09 15:40:46.832207+0800 0x107      Default     0x0                  0      0    kernel: (VoodooPS2Controller) ApplePS2Controller: Notification consumer published: ApplePS2Keyboard
2020-06-09 15:40:46.832212+0800 0x123      Default     0x0                  0      0    kernel: (VoodooPS2Controller) ApplePS2Controller: Notification consumer published: VoodooI2CPrecisionTouchpadHIDEventDriver
```

Personally, I am using VoodooI2C for my touchpad and touchscreen, and after looking at the log of VoodooPS2Controller, I have disabled VoodooInput, VoodooPS2Mouse, and VoodooPS2Trackpad under OC config.plist. 

Is there any reason why it would sometime drop the keyboard input stream?

Thanks,
twsps

**Comment by vit9696** [comment]
> Personally, I am using VoodooI2C for my touchpad and touchscreen, and after looking at the log of VoodooPS2Controller, I have disabled VoodooInput, VoodooPS2Mouse, and VoodooPS2Trackpad under OC config.plist.

Why do not you use https://github.com/coolstar/HIDPS2Keyboard? This makes a lot more sense to me for PS/2 keyboard and I2C touchpad stack.

In any case, if you use VoodooI2C for your touchpad, why did you have VoodooPS2Mouse and VoodooPS2Trackpad? Also, how does VoodooI2C work without VoodooInput? @_@

> sometimes will result in loss of keyboard functionality

What does sometimes mean in this context? Is it disabled at startup or during some special event?

> Timed out on keyboard input stream.

This means that a hardware issue happened and your PS/2 controller [froze](https://github.com/acidanthera/VoodooPS2/blob/b236145/VoodooPS2Controller/VoodooPS2Controller.cpp#L1246). It is possible that some drivers are simply incompatible. While you can try increasing the timeout in the code above, I would recommend checking the hardware and/or using a different driver (e.g. HIDPS2Keyboard).

**Comment by twlawrenceko** [comment]
> In any case, if you use VoodooI2C for your touchpad, why did you have VoodooPS2Mouse and VoodooPS2Trackpad? Also, how does VoodooI2C work without VoodooInput? @_@

They are inside VoodooPS2Controller, so I manually disabled it in OC. VoodooInput is also being provided by VoodooI2C, so to eliminate compatibility issue, I also disabled it in OC. Therefore, the only two left enabled is VoodooPS2Controller and VoodooPS2Keyboard.

>> sometimes will result in loss of keyboard functionality
> What does sometimes mean in this context? Is it disabled at startup or during some special event?
It means in most of the time, keyboard is frozen (cannot be used) and the `Timed out on keyboard input stream.` log will appear.

> This means that a hardware issue happened and your PS/2 controller froze. It is possible that some drivers are simply incompatible. While you can try increasing the timeout in the code above, I would recommend checking the hardware and/or using a different driver (e.g. HIDPS2Keyboard).

Are the timeout in debug and release mode different? The reason I prefer VoodooPS2 over HIDPS2Keyboard is because of the consistent update on it with OC.

To clarify my setting, I have attached my config.plist in OC.


[config.plist.zip](https://github.com/acidanthera/bugtracker/files/4753316/config.plist.zip)

Thanks,
twsps

**Comment by vit9696** [comment]
Hmm, no, there are not any timeout differences between release and debug builds, it just happens that some code executes at different pace due to disabled assertions/logging and enabled compiler optimisations.

I do not think we have ever tested VoodooPS2Controller with I2C stack, and to be honest I am not sure we investigate this any soon as the issue is not reproducible for us. Your best choice is to use another kext or a DEBUG build.

Other than that, could you please tell us whether the problem is in the keyboard kext or in the controller itself by mixing DEBUG and RELEASE binaries? If you think the timeout can be relevant, you can try increasing it (see the link above).

**Comment by twlawrenceko** [comment]
> Hmm, no, there are not any timeout differences between release and debug builds, it just happens that some code executes at different pace due to disabled assertions/logging and enabled compiler optimisations.
> 
> I do not think we have ever tested VoodooPS2Controller with I2C stack, and to be honest I am not sure we investigate this any soon as the issue is not reproducible for us. Your best choice is to use another kext or a DEBUG build.
> 
> Other than that, could you please tell us whether the problem is in the keyboard kext or in the controller itself by mixing DEBUG and RELEASE binaries? If you think the timeout can be relevant, you can try increasing it (see the link above).

Currently, with the timeout increased by double (70ms -> 140ms), it seems to have no issue with it. The current approach that made it work is changing `UInt32 timeoutCounter = 10000;    // (timeoutCounter * kDataDelay = 70 ms)` to `UInt32 timeoutCounter = 20000;    // (timeoutCounter * kDataDelay = 140 ms)`. I have also deleted all other packages except VoodooPS2Keyboard to clarify all unnecessary dependencies.

As this issue occurs randomly, I can try to testing out mixing VoodooPS2Controller (debug) with VoodooPS2Keyboard (release) and VoodooPS2Controller (release) with VoodooPS2Keyboard (debug). See if this is what you are expecting me to test. 

It seems like that HIDPS2Keyboard is using 10ms polling and this kext is designed for Chromebook usage, so now I am curious why would 70ms of polling occur a time out and may need 140ms (or less) to eliminate the issue, correct me if I am wrong.

Thanks,
twsps

**Comment by vit9696** [comment]
Well, if increasing the timeout works (please test for a couple of days), we could merge that change in master. I am curious why this happens as well, but a quick workaround should work well. Please make a pull-request in a couple of days if everything is fine.
