### ISSUE TITLE
Detecting ACPI

### ISSUE THREAD

**Issue by icedterminal** [acidanthera/bugtracker#969]
There are 21 ACPI tables detected in OC 0.6.0.

There are a total of 32 tables I can dump from firmware. OC manages to detect all of the core SSDT files. Being named SSDT-0 through SSDT-7. Of those, SSDT-5 is the core CPU power table. It calls/is linked to 7 sub tables. SSDT-5_0 through SSDT-5_6. Clover detects these tables and I can drop them. Removing these tables results in proper power management which I was able to achieve when I did use Clover. Otherwise you get a high idle speed (1.8GHz+) and weird usage spiking if these tables are left in.

If these tables remain in OC, I get high idle speed. If I drop the only table I can, CpuSsdt, high idle remains and I get the idle usage spiking. It looks like a zig zag line instead of flat line.

These are the tables I add to the ACPI Delete section of the config:

- CpuSsdt
- Cpu0Ist
- Cpu0Cst
- Cpu0Hwp
- ApHwp
- ApCst
- ApIst
- HwpLvt
- WSMT
- DBGP
- DBG2

It drops both Windows Debug tables (DBGP, DBG2), the Windows security table (WSMT), and if enabled the CpuSsdt. But fails to drop all of the power related CPU tables. It doesn't detect them.

My question is why can OC not see all of these files where as Clover can?

Files are here: https://github.com/icedterminal/ga-z270x-ug/tree/debug/EFI

**Comment by icedterminal** [comment]
- Not unhappy. Noticed it said detected 21. Yet I have 32. Just confused is all.
- I'm not sure where you're going with that one.
- There are [no duplicated tables](https://github.com/icedterminal/ga-z270x-ug/tree/debug/acpi_dump). I have looked over them multiple times.
- It doesn't drop a particular table? That doesn't make much sense to me as I am doing that with the unneeded Windows tables.

I tried to word this as best I could. I do apologize if you don't understand it.

**Comment by vit9696** [comment]
- So, from Clover dump you have 32 tables, but where is a dump from OpenCore (there is SysReport functionality)?
- I thought you dumped with OpenCore, thus I was so confused about the naming.
- Need to compare Clover and OpenCore dump really, please upload it with a debug log during dumping.
- Do you see the tables you cannot drop in macOS via MaciASL? Please tell me, which tables do not drop and point me to OpenCore config entries and their counterpart files in Clover dump if OpenCore does not have them.

**Comment by icedterminal** [comment]
- Added. Updated log and the files.
- I should have clarified better. My mistake.

I'll focus one of the tables I want to to drop as an example.

`Cpu0Ist` is the first one referenced in `CpuSsdt`. Clover dumps these files as [`SSDT-x5_0-Cpu0Ist.aml`](https://github.com/icedterminal/ga-z270x-ug/blob/debug/acpi_dump/clover/SSDT-x5_0-Cpu0Ist.aml) and [`SSDT-5-CpuSsdt.aml`](https://github.com/icedterminal/ga-z270x-ug/blob/debug/acpi_dump/clover/SSDT-5-CpuSsdt.aml) respectively. In the clover config it's under [ACPI > Drop tables](https://github.com/icedterminal/ga-z270x-ug/blob/master/clover_configs/clover_config171-amd.plist#L193). It's dropped as expected.

With OpenCore, I [drop the table `Cpu0Ist`](https://github.com/icedterminal/ga-z270x-ug/blob/debug/EFI/OC/config.plist#L171) using the correct signature and table id. During boot the log reports it [fails to find](https://github.com/icedterminal/ga-z270x-ug/blob/debug/EFI/opencore-2020-06-11-005645.txt#L231) this find this table. I can drop the parent table, `CpuSsdt` which is file [`SSDT-6.aml`](https://github.com/icedterminal/ga-z270x-ug/blob/debug/acpi_dump/opencore/SSDT-6.aml). But doing so results in even more issues.

Dumping ACPI with OpenCore gives me 25 tables. None of the following tables are anywhere to be found:
- Cpu0Ist
- Cpu0Cst
- Cpu0Hwp
- ApHwp
- ApCst
- ApIst
- HwpLvt

I also do not see these tables directly in maciasl. I *do* see them referenced under CpuSsdt. This is why I mentioned I am a bit confused. I double checked the bytes to make sure I didn't have a typo when I added it in.

[Both table dumps are here.](https://github.com/icedterminal/ga-z270x-ug/tree/debug/acpi_dump)

**Comment by vit9696** [comment]
Right, now I understand what you mean. You are probably talking about the internal tables referenced by some SSDT tables with ACPI code like this:

```
        Name (SSDT, Package (0x15)
        {
            "CPU0IST ", 
            0x86023398, 
            0x00000738, 
            "APIST   ", 
            0x85FD9018, 
            0x0000065C, 
            "CPU0CST ", 
            0x85FD9898, 
            0x000003FF, 
            "APCST   ", 
            0x85FD9DD8, 
            0x0000018A, 
            "CPU0HWP ", 
            0x82F8FE58, 
            0x00000115, 
            "APHWP   ", 
            0x82F90018, 
            0x00000197, 
            "HWPLVT  ", 
            0x82F8EDD8, 
            0x000001A4
        })
```

If so, these tables are "internal" to the parent ACPI table, and they are not visible to the system outside of this table. I.e. they are not referenced in XSDT/RSDT, and thus OpenCore does not dump them.

Currently to drop these tables you can
- either binary-patch the table (e.g. `CpuSsdt` in your example),
- or simply drop the parent table (e.g. `CpuSsdt` in your case).

The latter is the preferred solution, as it effectively drops all these tables at once.

We could technically add internal table dumping to OpenCore, but we are not positive whether it actually will benefit any end-user. We have no plans to implement internal table dropping as so far it was not proven to be useful. Correct me if I am wrong.

**Comment by nms42** [comment]
One can't drop "internal" tables harmlessly as they loaded at runtime by aml code

**Comment by icedterminal** [comment]
> We could technically add internal table dumping to OpenCore, but we are not positive whether it actually will benefit any end-user. We have no plans to implement internal table dropping as so far it was not proven to be useful.

Thanks for the information. 

This is an interesting situation. I was unaware this was an internal table.

**Comment by icedterminal** [comment]
I feel as if this no longer needs to be open. 

I am accepting these statements as the answer. Thanks @vit9696 

>  these tables are "internal" to the parent ACPI table, and they are not visible to the system outside of this table

> We could technically add internal table dumping to OpenCore, but we are not positive whether it actually will benefit any end-user. We have no plans to implement internal table dropping as so far it was not proven to be useful.
