### ISSUE TITLE
AudioDxe issue: stuck at HdaControllerInitPciHw(): controller version 0.0

### ISSUE THREAD

**Issue by Yetties** [acidanthera/bugtracker#970]
Hi,

The latest AudioDxe.efi driver causes OC boot to stuck at HdaControllerInitPciHw(): controller version 0.0 on my setup ga-z97x-gaming 5 (HD4600) and Sapphire Pulse RX 580.  I've been using the one included in the [AppleSupportPkg 2.1.7](https://github.com/acidanthera/AppleSupportPkg/releases/tag/2.1.7) and it's working well on the same setup.  Verified OC 0.5.9 release also has the same issue.  I wonder is it going to drop the support for my hardware?

The debug log is attached, both 0.58 and 0.60 are provided.  Thanks for the team making this great bootloader!

[AudioDxe_debug_060.txt](https://github.com/acidanthera/bugtracker/files/4761853/AudioDxe_debug_060.txt)
[AudioDxe_debug_058.txt](https://github.com/acidanthera/bugtracker/files/4761854/AudioDxe_debug_058.txt)

**Comment by Goldfish64** [comment]
Please recompile AudioDxe and repost logs with the following change to OpenCorePkg.msc:

```
gEfiMdePkgTokenSpaceGuid.PcdDebugPrintErrorLevel|0x80000042
gEfiMdePkgTokenSpaceGuid.PcdFixedDebugPrintErrorLevel|0x80000042
```

to

```
gEfiMdePkgTokenSpaceGuid.PcdDebugPrintErrorLevel|0x80400042
gEfiMdePkgTokenSpaceGuid.PcdFixedDebugPrintErrorLevel|0x80400042
```

**Comment by Yetties** [comment]
Sorry about it, I uploaded the wrong files which are debug build log.  Please see the attached new logs as below.

Failed log: latest built commit #92c9212 from OpenCorePkg repo
[AudioDxe_92c9212.txt](https://github.com/acidanthera/bugtracker/files/4768693/AudioDxe_92c9212.txt)

Successful log: commit #b129926 from AppleSupportPkg repo
[AudioDxe_b129926.txt](https://github.com/acidanthera/bugtracker/files/4768696/AudioDxe_b129926.txt)

**Comment by Goldfish64** [comment]
Issues with controller cleanup fixed with https://github.com/acidanthera/OpenCorePkg/commit/a55d147273986b45ed5092dcc100200e69d66f43. Please retest.

**Comment by Yetties** [comment]
It works with a55d147, thanks for the fix! [AudioDxe_a55d147.txt](https://github.com/acidanthera/bugtracker/files/4774285/AudioDxe_a55d147.txt)

I use iMacPro1,1 with dGPU only (RX580) and iGPU is disabled in BIOS.  My speaker is connected to the audio out of the motherboard if it matters.
