### ISSUE TITLE
The Lag in Boot Chime Volume Adjustment based on NVRAM SystemVolume

### ISSUE THREAD

**Issue by twlawrenceko** [acidanthera/bugtracker#971]
Hello,

As this has been noticed as an issue with 48kHz sampling for Boot chime due to ALC295 default sampling rate at 48kHz (not 44.1kHz). Where we suspect this may lead to a lag in decoding it and applying NVRAM SystemVolume value. 

The issue description is here:
 The change in macOS preference will overwrite NVRAM once NVRAM works natively (mine works). So with the change of volume setting in macOS will change the volume in OC (AudioDxe). Which means when I set the volume to 100% in macOS I will hear the boot chime in 100% volume; where if I set to 10% in macOS, the boot chime will first start with 100% volume then change to 10% after around 0.3s.

The original issue is here: [#963 ](https://github.com/acidanthera/bugtracker/issues/963#issuecomment-642450493)

Thanks,
twsps

**Comment by twlawrenceko** [comment]
As on a different machine, this issue does not relate to 48kHz, but also default 44.1kHz

**Comment by vit9696** [comment]
After some discussion we ended up with a conclusion that it is due to a technical delay between setting up the volume level and the actual time the codec needs to apply the preference, which varies from vendor to vendor.

To workaround this we will add a user-configurable delay in config.plist between the volume assignment and boot chime playback. Could you please test that it is going to work by adding the following line [here](https://github.com/acidanthera/OpenCorePkg/blob/d6e191d/Platform/OpenCore/OpenCoreUefiAudio.c#L423) and recompiling:

```C
gBS->Stall (100000);
```

The value is in microseconds, please increase/decrease it to a suitable value and let us know what the value was for your platforms.

**Comment by Goldfish64** [comment]
Actual volume adjustment occurs during widget setup in SetupPlayback. A delay should be added immediately prior to this [line](https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcAudioLib/OcAudio.c#L352).

**Comment by vit9696** [comment]
Hmm, that function is used for all kind of sound playback. Including VoiceOver and screen reading. If we do, we will end up having constant delays all the time. Is this intentional?

**Comment by Goldfish64** [comment]
Yes you would. If such a delay was implemented, likely would just tie it to only amp changes. This goes back to adding caching of values mentioned in #740.

**Comment by twlawrenceko** [comment]
> Yes you would. If such a delay was implemented, likely would just tie it to only amp changes. This goes back to adding caching of values mentioned in #740.

As per my understanding,  with the line you mentioned in changing will result in constant delays, and this is the correct way to resolve the delay issue?

**Comment by Goldfish64** [comment]
Adding a delay at the spot I mentioned will result in delays anytime VoiceOver and the boot chime is invoked, so is not a good solution based on the current code. It should be a good way to check if a delay is even necessary for volume changes and prevent that sudden change in volume after playback has started as you have described.

**Comment by twlawrenceko** [comment]
> After some discussion we ended up with a conclusion that it is due to a technical delay between setting up the volume level and the actual time the codec needs to apply the preference, which varies from vendor to vendor.
> 
> To workaround this we will add a user-configurable delay in config.plist between the volume assignment and boot chime playback. Could you please test that it is going to work by adding the following line [here](https://github.com/acidanthera/OpenCorePkg/blob/d6e191d/Platform/OpenCore/OpenCoreUefiAudio.c#L423) and recompiling:
> 
> ```c
> gBS->Stall (100000);
> ```
> 
> The value is in microseconds, please increase/decrease it to a suitable value and let us know what the value was for your platforms.

With the change of adding `gBS->Stall(1000000)` to line 423, with replacement file of BOOTx64.efi, Bootstrap.efi, AudioDxe.efi, OpenCanopy.efi, OpenRuntime.efi, and OpenCore.efi does not seem to have any change with the boot chime delay issue that I have mentioned above. Is there any replacement file that is required that I am missing?

**Comment by Goldfish64** [comment]
> Actual volume adjustment occurs during widget setup in SetupPlayback. A delay should be added immediately prior to this [line](https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcAudioLib/OcAudio.c#L352).

Please make this change instead.

**Comment by twlawrenceko** [comment]
> > Actual volume adjustment occurs during widget setup in SetupPlayback. A delay should be added immediately prior to this [line](https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcAudioLib/OcAudio.c#L352).
> 
> Please make this change instead.

With 0.5 sec of delay fixed the issue. Note that with excess amount of delay set (i.e. 3sec) will lead to the original wrong volume boot chime come after the correct one (right volume based on NVRAM).

Thanks,
twsps

**Comment by vit9696** [comment]
Hrm, @Goldfish64 perhaps the issue is not about the need to delay to apply the preference but the timing when the sound starts? Something like in the middle of the buffer or in the beginning of the buffer?

**Comment by armenio** [comment]
as an end user, I have the feeling that the chime play starts at a standard volume and after a short time the calculated audio volume is applied. 
but the conditions to mute/no play are respected

**Comment by Goldfish64** [comment]
@twlawrenceko What is the hardware/codecs in both machines?

**Comment by twlawrenceko** [comment]
> @twlawrenceko What is the hardware/codecs in both machines? Debug or release builds, or both?
> 
> Also for both machines, please report the volume levels listed at the "OCAU: System volume..." line in the log.

With the 48kHz is ALC295 (DELL), 44.1kHz is ALC1220S (ASUS Z270i). Both debug and release tested and sometimes has issue with second boot chime.

I am not sure what you mean by reporting `OCAU` boot log. Do you want it from debug or release?

Thanks,
twsps

**Comment by Goldfish64** [comment]
From the debug log, a `OCAU: System volume...` line is printed during OC load. Please post the line as it has volume settings. Otherwise just posting the debug log from both machines will also work.

**Comment by twlawrenceko** [comment]
> From the debug log, a `OCAU: System volume...` line is printed during OC load. Please post the line as it has volume settings. Otherwise just posting the debug log from both machines will also work.

For ALCS1220A codec, I have always set System volume to Max as I have a dedicated Amplifier that can control the volume. So it is set to `09:439 00:038 OCAU: System volume is 70 (calculated from 70) - Success` and will have no lag.

For ALC295 (48kHz), it has `31:133 00:068 OCAU: System volume is 38 (calculated from 38) - Success`.

I also have a concern/question, if I want to have the maximum volume of boot chime with macOS system volume set to max, what value is appropriate for volumeAmplifier in OC?

Thanks,
twsps

**Comment by twlawrenceko** [comment]
Is the delay parameter every get implemented to the latest OC?

**Comment by vit9696** [comment]
Implemented in master, please test & report.

**Comment by twlawrenceko** [comment]
I do not see any delay parameters in the master, also with v0.6.4, I still experience the lag in boot chime volume
