### ISSUE TITLE
VoodooPS2Controller Accidental Touch Delay 

### ISSUE THREAD

**Issue by twlawrenceko** [acidanthera/bugtracker#972]
Hello,

With the use of VoodooI2C (for trackpad and touchscreen) and VoodooPS2Keyboard, I have experienced too short accidental touch delay detection which results in accidental touch happening when typing. Is there any where in the code where the user can define it for custom setting?

Thanks,
twsps

**Comment by vit9696** [comment]
To be honest, I am not sure I even understood you. Perhaps somebody from the trackpad team could answer this? CC @usr-sse2 @Goshin @kprinssu

**Comment by Goshin** [comment]
@twlawrenceko if you mean the palm rejection delay after typing, yes you can change it in `VoodooI2CHID.kext/Contents/Info.plist` > `QuietTimeAfterTyping`.

**Comment by armenio** [comment]
> @twlawrenceko if you mean the palm rejection delay after typing, yes you can change it in `VoodooI2CHID.kext/Contents/Info.plist` > `QuietTimeAfterTyping`.

**For information only:**

in VoodooPS2Trackpad.kext there is also the "QuietTimeAfterTyping" setting in Info.plist

As by default there is a huge delay, I know that in this case it is possible to correct via ACPI this way:


```
DefinitionBlock ("", "SSDT", 2, "HACK", "PS2K", 0)
{
	// Change _SB.PCI0.LPCB.KBD if your PS2 keyboard is at a different ACPI path
	External (_SB_.PCI0.LPCB.KBD, DeviceObj)

	Scope (\_SB.PCI0.LPCB.KBD)
	{
		// Overrides
		Name (RMCF, Package ()
		{
			"Synaptics TouchPad", Package ()
			{
				"QuietTimeAfterTyping", 1000000,
			},
		})
	}
}

```
maybe this is also possible in VoodooI2CHID.kext keeping the original kext untouched

**Comment by usr-sse2** [comment]
>> @twlawrenceko if you mean the palm rejection delay after typing, yes you can change it in `VoodooI2CHID.kext/Contents/Info.plist` > `QuietTimeAfterTyping`. ...

@armenio 500 ms is huge? You are setting it to 1 ms which is in fact the same as 0.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by armenio** [comment]
@usr-sse2 when you're on a lap top using cmd + tab and right after trying to move the cursor with trackpad, it seems to be a huge delay
