### ISSUE TITLE
In openshell, the enter key enters “\” character, I need to press alt-enter for a enter. Then in grub2, enter and alt-enter does not work

### ISSUE THREAD

**Issue by kocoman1** [acidanthera/bugtracker#975]
In openshell, the enter key enters “\” character, I need to press alt-enter for a enter. Then in grub2, enter and alt-enter does not work

**Comment by vit9696** [comment]
With this much information one cannot do basically anything. Please provide extensive information about your setup (hardware & software) and EFI folder. Depending on that we may consider the issue.
