### ISSUE TITLE
failed to route ComputeHdmiP0P1P2 , HDMI infinite kernel panic loop

### ISSUE THREAD

**Issue by liaolunhui** [acidanthera/bugtracker#976]
I use WhateverGreen.

Kernel Panic when connect HDMI.

I add `-igfxhdmidivs` boot argument to avoid this problem, but not working.

the key logs are:
`2020-06-13 20:32:15.810909+0800  localhost kernel[0]: (kernel) Lilu   patcher: @ failed to solve __ZN31AppleIntelFramebufferController17ComputeHdmiP0P1P2EjP21AppleIntelDisplayPathPNS_10CRTCParamsE, err 2
2020-06-13 20:32:15.841752+0800  localhost kernel[0]: (kernel) WhateverGreen      igfx: @ failed to route ComputeHdmiP0P1P`

Here is my post, there are full details of kernel panic and log:
https://www.tonymacx86.com/threads/help-kp-when-connect-hdmi-after-update-10-15-4.299274/

Here is similar problem:
https://discussions.apple.com/thread/251211856

Any help will be appreciated !

**Comment by vit9696** [comment]
I believe these are unrelated issues, as the code you mentioned is about division by zero error, and in your panic log you have a page fault. I do not think we want to investigate the issue, sorry.

**Comment by liaolunhui** [comment]
I see the code as 
`		if (hdmiP0P1P2Patch) {
			KernelPatcher::RouteRequest request("__ZN31AppleIntelFramebufferController17ComputeHdmiP0P1P2EjP21AppleIntelDisplayPathPNS_10CRTCParamsE", wrapComputeHdmiP0P1P2);
			if (!patcher.routeMultiple(index, &request, 1, address, size))
				SYSLOG("igfx", "failed to route ComputeHdmiP0P1P2");
		}
`

It worked before 10.15.4 , i guess it change after 10.15.3 .
Many people has this problem, please!

**Comment by asgmeonerandom** [comment]
> I see the code as
> ` if (hdmiP0P1P2Patch) { KernelPatcher::RouteRequest request("__ZN31AppleIntelFramebufferController17ComputeHdmiP0P1P2EjP21AppleIntelDisplayPathPNS_10CRTCParamsE", wrapComputeHdmiP0P1P2); if (!patcher.routeMultiple(index, &request, 1, address, size)) SYSLOG("igfx", "failed to route ComputeHdmiP0P1P2"); } `
> 
> It worked before 10.15.4 , i guess it change after 10.15.3 .
> Many people has this problem, please!

someone replied to you in the forum. I agree that it's not a bug in the code.
