### ISSUE TITLE
IntelMausi 1.03 breaks WOL

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#977]
Both IntelMausi 1.03 and Mieze/IntelMausiEthernet(96a7dc2ef28520d521d3db82701ba06230999517) latest commit breaks wake on network on my hackintosh

while IntelMausi 1.02 works perfectly fine. 

- hardware:
Device ID: 15BC
Vendor 8086
SubVendor 1849
Name: Intel I219-V
Path: IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/GLAN@1F,6

- tools i used to wake mac: 
http://ahh.sourceforge.net/wol/

- command i used to wake mac: 
`wol 'hackintosh's MAC address'`
and then try pinging the mac's ip address (which is a manual address )

you may want to test to verify. thanks

**Comment by Andrey1970AppleLife** [comment]
![Снимок экрана 2020-06-14 в 09 08 20](https://user-images.githubusercontent.com/17758753/84586061-9b8a3780-ae1e-11ea-89bf-4204b8bc2061.png)

Write to Mieze original repository.
