### ISSUE TITLE
IGPU Could not register with IOFB and Panic on Surface Pro 7

### ISSUE THREAD

**Issue by badstorm** [acidanthera/bugtracker#978]
Hi, I'm trying to get full QE/CI on my Surface Pro 7 (Intel® Core™ i5-1035G4 with Iris Plus) and macOS 15.15.5. The system start and before get a Kernel Panic i get: 

`[IGPU] Could not register with IOFB! Working standalone (IONDRVSupport)`

What dose it means?
The only way to run the OS (with no QE/CI) is add a fake device-id (like 12345678) under DeviceProperties in OC.

Here my [configuration](https://github.com/badstorm/surface-pro-7-opencore)

Software used:
- OC 0.59-Release
- Lilu 1.4.5-Release
- WhateverGreen 1.4.0-Release

**Comment by Andrey1970AppleLife** [comment]
Initialisation of ICL graphics requires fixing. Research not in plans acidanthera.
