### ISSUE TITLE
[WhateverGreen] HDMI 4K Output Missing

### ISSUE THREAD

**Issue by twlawrenceko** [acidanthera/bugtracker#981]
Hello, 

With the setting of `enable-hdmi20` enabled and all other correct settings, there is still missing the option of 4K, the maximum option is 2560x1440. With the previous setting of injecting vbios and EDID in clover, it is possible to output 4K @ 60fps through HDMI port. 

Here is the setting of what I currently have, with confirming port 1 as HDMI and port 2 as DP (USB Type-C).
<img width="1033" alt="Screen Shot 2020-06-17 at 9 39 04 PM" src="https://user-images.githubusercontent.com/14770978/84906034-01f3ac00-b0e4-11ea-8653-0a918039c89b.png">
I have tested with and without EDID but that would not make any difference as that is not the main issue that will relate to 4K output.

One more interesting thing is from About this Mac section.
<img width="472" alt="Screen Shot 2020-06-17 at 9 39 29 PM" src="https://user-images.githubusercontent.com/14770978/84906151-20f23e00-b0e4-11ea-94bd-6062d4b193d0.png">
As it shows my internal display connection type as DisplayPort, would this be the reason it is not outputting 4K? However, as my understanding of my patching, con0 is already set as internal LVDS. Notice that the display resolution is set to 2880x1620 instead of 1920x1080, and this is due to HiDPI setting, with the removal of HiDPI (which makes the display resolution back to 1920x1080), it does not help.

I am concerned that with the missing option of VBIOS (from Clover) in OpenCore, would that be the reason why it is not working? As Dell laptop seems to be picky about vbios settings. 

Thanks,
twsps

**Comment by Andrey1970AppleLife** [comment]
Use dortania for support.
https://github.com/dortania/bugtracker/issues

> I am concerned that with the missing option of VBIOS (from Clover) in OpenCore, would that be the reason why it is not working?
> 

No, patch VBIOS in the Clover bootloader, belongs only to resolution in bootloader.

**Comment by twlawrenceko** [comment]
For other users who are concerned with this issue, setting DVMT to 64MB in BIOS is required to get 4K option through HDMI output. Currently, with the above setting but 32MB DVMT fix removed, it results in KP after unplugging the HDMI and internal screen turns black.
