### ISSUE TITLE
Issue with OpenCore Debug log file writing corrupting USB flash hardware

### ISSUE THREAD

**Issue by apocolipse** [acidanthera/bugtracker#982]
OpenCore Version: 0.5.9 (Debug and release affected)
Using OpenCore on a USB 3.1 Flash Drive (Samsung Flash Fit 32GB), with Target set to 67 (or any log file writing), I've encountered some issues where OpenCore's log file writing has corrupted the NAND on the flash drive rendering it ultimately unusable.  I've isolated it to here https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcDebugLogLib/OcLog.c#L289 Noting that the log file is pre-allocated to 256KB and essentially re-written entirely every time a new line is appended. 

This first manifested with really slow boots out of nowhere but just on the OpenCore boot cycle, noting that it would take a few seconds to cycle through each line in OpenCore's debug output rather than instantaneous as before.  

Disabling writing those logs to file fixed the slow boot but afterwards I still noticed the USB drives either slow or unable at all to write.  Setting Target to 66 (or 0, disable the log file bit) prevents future damage to the _new_ flash drive I'm currently using, however I have 1 drive that no longer can be written to at all (disk tools in windows/linux/macOS, even dd, all fail), and another that takes about 10 minutes to write 20MB to now.

**Comment by vit9696** [comment]
The reason it is done this way is as follows:

- We need to make sure the log is written even if OpenCore accidentally halts at a random place.
- We need to workaround the bug in FAT32 driver implementation of APTIO IV firmwares, which is easy to corrupt the filesystem. We do this by writing fixed amount data.

There are other ways to log information, and I believe the documentation gives a good idea that drive corruption may happen (`Log is attempted to be written in the safest manner, and thus is very slow.`). I could improve the docs if you have a good idea on what to write, but otherwise I believe it is by design.

**Comment by apocolipse** [comment]
Thanks for the explanation @vit9696  
Does the FAT32 bug exist still in APTIO V firmwares perhaps giving the ability to write in a different manner for them?  

Also, as far as wording goes, here's whats in the docs:
>  Please be warned that some
file system drivers present in firmwares are not reliable, and may corrupt data when writing files through UEFI.
Log is attempted to be written in the safest manner, and thus is very slow.

This could perhaps be updated to emphasize a _Warning!_ similar to the warning above it for NVRAM garbage collection, additionally mentioning not just data corruption but potential drive corruption (I'm assuming only with Flash based drives as that's the only ones I've had fail on me).

These notes should also be added to vanilla guides but I'll make appropriate issues on those repositories linking to this.  
Thanks again!

(Note:  I no longer have a current issue as I've fixed all OC related issues and no longer need it to log :) )

**Comment by vit9696** [comment]
Fair enough, I improved the documents. APTIO V is believed not to have the issue (at least in the majority of firmwares), but we will rather not do the detection, as the issue existed in EDK II as well, and thus a lot of firmwares are still affected.
