### ISSUE TITLE
ALC 290 aka ALC3241 at layout 4 not working on HP m6-n015dx

### ISSUE THREAD

**Issue by phuanh004** [acidanthera/bugtracker#986]
### My Laptop:
- HP m6-n015dx
- CPU: i5-4210M - Intel HD graphics 4600
- Touchpad: Synaptics
- Audio: ALC 290 aka ALC3241

### Issues:
- [ ] Audio not working (Layout 3, 4, 28)

### Files:
- [EFI + IOReg.zip](https://github.com/acidanthera/bugtracker/files/4802737/EFI.%2B.IOReg.zip)
- Dummy Codex on Linux: [dummy_codex1.txt](https://github.com/acidanthera/bugtracker/files/4802745/dummy_codex1.txt), [dummy_codex0.txt](https://github.com/acidanthera/bugtracker/files/4802746/dummy_codex0.txt)
- MacPeet Patch that used to work on the laptop with realtekALC: [ALC290_HP_m6_n015_dx_on_the_fly.zip](https://github.com/acidanthera/bugtracker/files/4802741/ALC290_HP_m6_n015_dx_on_the_fly.zip)

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.
