### ISSUE TITLE
Load Linux GuC firmware for type 4 scheduler

### ISSUE THREAD

**Issue by osy86** [acidanthera/bugtracker#987]
I'm not sure how widespread this issue is but it seems like type 5 scheduler (host scheduler) doesn't allow the iGPU to clock beyond 0.5GHz (https://github.com/osy86/HaC-Mini/issues/262) and type 3 scheduler doesn't load (https://github.com/acidanthera/bugtracker/issues/586#issuecomment-573292272) which leaves us with type 4 (reference GuC firmware).

But for some reason, the Mac's Kabylake reference GuC firmware doesn't load either even though the sequence in `IGHardwareGuC::loadGuCBinary` follows that of `intel_guc_fw_upload` in Linux. I suspect the reference firmware is either too old, broken, or has some Apple specific configuration.

It would be nice then, if we can load the .bin firmware from Linux. However patching `IGHardwareGuC::loadGuCBinary` seems to be a pain because the data is stored at local symbol `__KmGen9GuCBinary` and is `memcpy` to a iGPU shared buffer. The size of the copy is hard coded and the size sent to the iGPU is also hard coded. Additionally, if we are not just worrying about Kabylake, there are lots of other addresses, offsets, and symbols to consider.

Ideally we reproduce `IGHardwareGuC::loadGuCBinary` from scratch using the Linux code as a reference. But that would take some work and would also require getting vtable and data offsets from C++ objects in the original code so it isn't the cleanest solution either.

I don't want to invest a lot of time with this if this is an issue nobody else is dealing with. Is the host scheduler an issue for anyone else? Would loading the reference firmware solve performance issues with the host scheduler? Does loading the reference firmware work for anyone else?

**Comment by vit9696** [comment]
I have reference scheduler loading implemented (and working) for KBL for 10.13 and if I remember correctly, some 10.14 version too. The issue with the GuC blob in KBL drivers is that it is for SKL IGPU, and needs to be replaced with a newer one. For SKL it works as is even on 10.15. If you check WEG you will find the relevant code in `wrapIgBufferWithOptions`/`loadIGScheduler4Patches`. See [this commit](https://github.com/acidanthera/WhateverGreen/commit/c5dc4591daf0f25d8b316c832747661945d71272). It should be fairly easy to adopt this to 10.15, but I did not try.

The older implementation is present in [IntelGraphicsFixup](https://github.com/lvs1974/IntelGraphicsFixup/blob/3c6e157e1b5b0cc7e42257f866c50868e94051b0/IntelGraphicsFixup/kern_igfx.cpp), and it also includes most of DMA code to load GuC manually if necessary and contains incomplete HuC support.

The biggest issue with reference GuC is that unlike Apple GuC that works with Z390+ boards reference GuC scheduler is almost unimplemented. It is full of stubs, does not support S3 at all (no firmware reloading and state saving/restoration), and it randomly freezes during normal functioning. I did partially fix headless IGPU wake-up by reloading firmware in `wrapSystemDidWake`, but that did not fully resolve the freezes. I do not own the hardware, so I mostly abandoned the problem, but you should have a good start with this code.

**Comment by osy86** [comment]
Is it less stable than the host mode scheduler? Really my only issue is the 0.5GHz clock and right now the workaround is for me to force AMD for video decoding and it works well enough to avoid the headache of iGPU patches.

**Comment by vit9696** [comment]
Yes, by far less stable. I would rather say unusable is the right word.

**Comment by 07151129** [comment]
@osy86 

Frequency control via render P-state switching should be achievable without GuC by using the `RPNSWREQ` register. This is what the Linux driver uses, and also Apple `IGHardwareCommandStreamer2` does, to some extent. Unfortunately, the relevant documentation is Intel confidential, but some reference may be found at https://bwidawsk.net/blog/index.php/2015/05/a-bit-on-intel-gpu-frequency/, and in the i915 source.

To get started, I have made a few hooks to check the frequency limit:

<details>

```
diff --git i/WhateverGreen.xcodeproj/project.pbxproj w/WhateverGreen.xcodeproj/project.pbxproj
index 6e2aa74..b994a25 100644
--- i/WhateverGreen.xcodeproj/project.pbxproj
+++ w/WhateverGreen.xcodeproj/project.pbxproj
@@ -10,6 +10,7 @@
 		1C748C2D1C21952C0024EED2 /* kern_start.cpp in Sources */ = {isa = PBXBuildFile; fileRef = 1C748C2C1C21952C0024EED2 /* kern_start.cpp */; };
 		1C9CB7B01C789FF500231E41 /* kern_rad.cpp in Sources */ = {isa = PBXBuildFile; fileRef = 1C9CB7AE1C789FF500231E41 /* kern_rad.cpp */; };
 		1C9CB7B11C789FF500231E41 /* kern_rad.hpp in Headers */ = {isa = PBXBuildFile; fileRef = 1C9CB7AF1C789FF500231E41 /* kern_rad.hpp */; };
+		2F30012424A00F2800C590C3 /* kern_igfx_pm.cpp in Sources */ = {isa = PBXBuildFile; fileRef = 2F30012324A00F2800C590C3 /* kern_igfx_pm.cpp */; };
 		CE1970FF21C380DF00B02AB4 /* kern_nvhda.cpp in Sources */ = {isa = PBXBuildFile; fileRef = CE1970FD21C380DF00B02AB4 /* kern_nvhda.cpp */; };
 		CE19710021C380DF00B02AB4 /* kern_nvhda.hpp in Headers */ = {isa = PBXBuildFile; fileRef = CE1970FE21C380DF00B02AB4 /* kern_nvhda.hpp */; };
 		CE1F61B92432DEE800201DF4 /* kern_igfx_debug.cpp in Sources */ = {isa = PBXBuildFile; fileRef = CE1F61B82432DEE800201DF4 /* kern_igfx_debug.cpp */; };
@@ -77,6 +78,7 @@
 		1CF01C901C8CF97F002DCEA3 /* README.md */ = {isa = PBXFileReference; lastKnownFileType = net.daringfireball.markdown; path = README.md; sourceTree = "<group>"; };
 		1CF01C921C8CF997002DCEA3 /* Changelog.md */ = {isa = PBXFileReference; lastKnownFileType = net.daringfireball.markdown; path = Changelog.md; sourceTree = "<group>"; };
 		1CF01C931C8DF02E002DCEA3 /* LICENSE.txt */ = {isa = PBXFileReference; lastKnownFileType = text; path = LICENSE.txt; sourceTree = "<group>"; };
+		2F30012324A00F2800C590C3 /* kern_igfx_pm.cpp */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.cpp.cpp; path = kern_igfx_pm.cpp; sourceTree = "<group>"; };
 		CE1970FD21C380DF00B02AB4 /* kern_nvhda.cpp */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.cpp.cpp; path = kern_nvhda.cpp; sourceTree = "<group>"; };
 		CE1970FE21C380DF00B02AB4 /* kern_nvhda.hpp */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.cpp.h; path = kern_nvhda.hpp; sourceTree = "<group>"; };
 		CE1F61B82432DEE800201DF4 /* kern_igfx_debug.cpp */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.cpp.cpp; path = kern_igfx_debug.cpp; sourceTree = "<group>"; };
@@ -187,6 +189,7 @@
 				CE7FC0AC20F5622700138088 /* kern_igfx.cpp */,
 				CE7FC0AD20F5622700138088 /* kern_igfx.hpp */,
 				CE1F61B82432DEE800201DF4 /* kern_igfx_debug.cpp */,
+				2F30012324A00F2800C590C3 /* kern_igfx_pm.cpp */,
 				CE7FC0A820F55E7400138088 /* kern_ngfx.cpp */,
 				CE7FC0A920F55E7400138088 /* kern_ngfx.hpp */,
 				CE7FC0B020F563CA00138088 /* kern_ngfx_asm.S */,
@@ -434,6 +437,7 @@
 				1C9CB7B01C789FF500231E41 /* kern_rad.cpp in Sources */,
 				CE766ED6210763B200A84567 /* kern_guc.cpp in Sources */,
 				CE7FC0B420F6809600138088 /* kern_shiki.cpp in Sources */,
+				2F30012424A00F2800C590C3 /* kern_igfx_pm.cpp in Sources */,
 				CE7FC0B120F563CA00138088 /* kern_ngfx_asm.S in Sources */,
 				CEA03B5E20EE825A00BA842F /* kern_weg.cpp in Sources */,
 				CE8190A21F1E3ECE00DE95F4 /* kern_model.cpp in Sources */,
diff --git i/WhateverGreen/kern_igfx.cpp w/WhateverGreen/kern_igfx.cpp
index f0c47ef..d8caaa9 100755
--- i/WhateverGreen/kern_igfx.cpp
+++ w/WhateverGreen/kern_igfx.cpp
@@ -109,6 +109,7 @@ void IGFX::init() {
 			// configuration, supposedly due to Apple not supporting new MOCS table and forcing Skylake-based format.
 			// See: https://github.com/torvalds/linux/blob/135c5504a600ff9b06e321694fbcac78a9530cd4/drivers/gpu/drm/i915/intel_mocs.c#L181
 			forceCompleteModeset.supported = forceCompleteModeset.enable = true;
+			RPSControl.enabled = true;
 			break;
 		case CPUInfo::CpuGeneration::CannonLake:
 			supportsGuCFirmware = true;
@@ -310,7 +311,7 @@ void IGFX::processKernel(KernelPatcher &patcher, DeviceInfo *info) {
 		int gl = info->videoBuiltin->getProperty("disable-metal") != nullptr;
 		PE_parse_boot_argn("igfxgl", &gl, sizeof(gl));
 		forceOpenGL = gl == 1;
-		
+
 		int metal = info->videoBuiltin->getProperty("enable-metal") != nullptr;
 		PE_parse_boot_argn("igfxmetal", &metal, sizeof(metal));
 		forceMetal = metal == 1;
@@ -421,6 +422,9 @@ bool IGFX::processKext(KernelPatcher &patcher, size_t index, mach_vm_address_t a
 			patcher.routeMultiple(index, &request, 1, address, size);
 		}
 
+		if (RPSControl.enabled)
+			RPSControl.init(patcher, index, address, size);
+
 		return true;
 	}
 
@@ -767,7 +771,7 @@ bool IGFX::wrapAcceleratorStart(IOService *that, IOService *provider) {
 
 		}
 	}
-	
+
 	OSObject *metalPluginName = that->getProperty("MetalPluginName");
 	if (metalPluginName) {
 		metalPluginName->retain();
@@ -784,7 +788,7 @@ bool IGFX::wrapAcceleratorStart(IOService *that, IOService *provider) {
 		that->setName("IntelAccelerator");
 
 	bool ret = FunctionCast(wrapAcceleratorStart, callbackIGFX->orgAcceleratorStart)(that, provider);
-	
+
 	if (metalPluginName) {
 		if (callbackIGFX->forceMetal) {
 			DBGLOG("igfx", "enabling metal support");
@@ -792,7 +796,7 @@ bool IGFX::wrapAcceleratorStart(IOService *that, IOService *provider) {
 		}
 		metalPluginName->release();
 	}
-	
+
 	return ret;
 }
 
diff --git i/WhateverGreen/kern_igfx.hpp w/WhateverGreen/kern_igfx.hpp
index db22d0d..665d19f 100755
--- i/WhateverGreen/kern_igfx.hpp
+++ w/WhateverGreen/kern_igfx.hpp
@@ -338,7 +338,7 @@ private:
 	 *  Set to true to disable Metal support
 	 */
 	bool forceOpenGL {false};
-	
+
 	/**
 	 *  Set to true to enable Metal support for offline rendering
 	 */
@@ -404,6 +404,17 @@ private:
 		}
 	};
 
+	struct RPSControl {
+		bool enabled {false};
+
+		void init(KernelPatcher &patcher, size_t index, mach_vm_address_t address, size_t size);
+
+		static char IGHardwareCommandStreamer2__init(void*,void*,void*,void*,uint8_t);
+		mach_vm_address_t orgIGHardwareCommandStreamer2__init {};
+
+		static uint64_t pmNotify(uint32_t, uint32_t, uint64_t*, uint32_t*);
+	} RPSControl;
+
 	/**
 	 * Ensure each modeset is a complete modeset.
 	 */
@@ -499,12 +510,12 @@ private:
 	 *  Driver-requested backlight frequency obtained from BXT_BLC_PWM_FREQ1 write attempt at system start.
 	 */
 	uint32_t driverBacklightFrequency {};
-	
+
 	/**
 	 *  The default DPCD address
 	 */
 	static constexpr uint32_t DPCD_DEFAULT_ADDRESS = 0x0000;
-	
+
 	/**
 	 *  The extended DPCD address
 	 */

```
</details>

Method `IGHardwareCommandStreamer2::submitExecList` should write to `RPNSWREQ` via `IGHardwareCommandStreamer2::setGTFrequencyMMIO` when submitting an exec list. Also, the `_pmNotify` callback should be invoked, but I never observed that. Finally, that function should arm a timer that writes 0 to the register when it expires, see `IGHardwareCommandStreamer2::handleChangeFrequencyInterrupt`.

It looks like I am getting proper power management with IGScheduler2 on 10.14.5, UHD 630 and Z370, so I did not investigate any further.

**Comment by osy86** [comment]
@07151129 can you provide the commit where the patch should be applied? The line numbers don't match `master`.

**Comment by 07151129** [comment]
@osy86 the commit is 8ebb2716c6efa24ad8088166f1b4c768a2f73130. I am able to apply it cleanly:

```
$ git apply --summary --check --verbose 0001-RPS-debug.patch
Checking patch WhateverGreen.xcodeproj/project.pbxproj...
Checking patch WhateverGreen/kern_igfx.cpp...
Checking patch WhateverGreen/kern_igfx.hpp...
Checking patch WhateverGreen/kern_igfx_pm.cpp...
 create mode 100644 WhateverGreen/kern_igfx_pm.cpp
```

**Comment by osy86** [comment]
I get RP0=0x42 and RP1=0x15. When running GeekBench 5 metal compute I get 1.1GHz so it’s able to enter RP0. When I run the 4k 120hz H.264 video, it’s stuck at 0.4GHz or RP1. Do you observe something different for the video clips:

**Comment by 07151129** [comment]
Oh, so this problem is specific to the video decoding workloads. I am also getting 0.35 GHz GT frequency and choppy playback when attempting to play the samples.

> Also I only see the log entries at startup.

The RP limits you are seeing are only printed at `IGHardwareCommandStreamer2` initialisation. I have added a `_pmNotify` hook to see if this callback is getting invoked (should be the case), but for some reason it is not. It may be worth it to hook `IGHardwareCommandStreamer2::setGTFrequencyMMIO` to see if `RPNSWREQ` is written to from elsewhere. It may also be the case that `os_log` simply does not write the entry (it happens sometimes).

Here is some relevant pseudocode from `IGHardwareCommandStreamer2::submitExecList`:

```
 if ( accel->schedConfig & 0x1000 && !streamer->cs_desc->type && !accel->telemetryManager->gap10C[0x10] )
  {
    v34 = HIDWORD(streamer->member119);
    v8 = *(v4 + 82);
    v9 = &streamer->IGHwCsStatsTracker->member207[8 * v8];
    freq = 0;
    LODWORD(v37) = 0;
    if ( !(accel->localCallbacks->_pmNotify)(v8, 1LL, v9, &v37) )
      freq = v37;
    v11 = (freq >> 14) & 0x1FF;
    if ( !(freq & 0xF) )
      v11 = freq >> 23;
    IGHardwareCommandStreamer2::setGTFrequencyMMIO(streamer, freq);
    v12 = streamer->rp0_freq - v11;
    streamer->member107 = v12;
    if ( v12 )
    {
      if ( v12 <= 0xA )
        v13 = 0x28uLL / v12;
      else
        v13 = 4LL;
    }
    else
    {
      v13 = 40LL;
    }
    streamer->member107 = v13;
    streamer->handleChangeFreqTimerES->baseclass_0->__ZN18IOTimerEventSource12setTimeoutMSEj(
      streamer->handleChangeFreqTimerES,
      v13);
    LOBYTE(streamer->member109) = 0;
    v4 = v33;
    streamer->unk0 = *(v33 + 0x52);
    v5 = v36;
    v6 = v34;
  }
...
```

From my static analysis, the condition should be satisfied:

- `accel->schedConfig & 0x1000` is the Scheduler PM Notify bit in the scheduler config; logged by the driver as 1 on my machine

- `streamer->cs_desc` is a pointer to array of `struct IGHwCsDesc`, defined as follows:

```
struct IGHwCsDesc
{
  char type;
  char gap[4];
  char *title;
  char unk0[48];
  char unk1[12];
};
```

Global array `IGHwCsDesc` is used, where the `RCS` entry has type 0. Consequently, the condition requires the streamer to be `RCS`. `VCS` is the video command streamer, so I can see why for hardware-accelerated video decoding the frequency does not get increased.

The command streamers are documented at https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-kbl-vol06-command_stream_programming.pdf. 

- `accel->telemetryManager->gap10C[0x10]` is some member of `IGTelemetryManager` that is initialised to 0 in constructor and is never written to (according to static analysis).

To conclude, because we are getting proper frequency control for `RCS`, either it is done by the above code, or by the firmware. In any case, it is worth investigating a bit more.

**Comment by osy86** [comment]
Do we know the min/max frequency configuration for, say, Macmini8,1 or iMac18,3? It could be possible everything is working as expected but Macs expect a higher min frequency?

**Comment by 07151129** [comment]
Those models seem to be using `IGHardwareGuC` rather than `IGScheduler2`, so I would expect that power management is performed completely on the GuC side. Having higher minimal frequency limit would also be undesirable for power saving.

Another aspect that could matter is the command submission mechanism. Apparently, execlists are a newer mechanism, while batchbuffer is the traditional one (https://www.kernel.org/doc/html/v4.10/gpu/i915.html#logical-rings-logical-ring-contexts-and-execlists). Only the exec list submission code writes to `RPNSWREQ`, so if only batch buffers are used (supposedly `IGHardwareRingBuffer`), then P-states may also be unchanged.

**Comment by osy86** [comment]
@07151129 seems like a user found the frequency getting stuck high. Is this expected? https://github.com/osy86/HaC-Mini/issues/323

**Comment by 07151129** [comment]
@osy86 the patch broke in 10.15.6, see https://github.com/acidanthera/bugtracker/issues/1106. Other than using the bootarg to disable the patch there is not workaround currently.
