### ISSUE TITLE
Request to use OpenCore Logo

### ISSUE THREAD

**Issue by rektimus** [acidanthera/bugtracker#988]
Had this idea since 0.4.0 but started putting it together this week. I'm nearing completion (I hope). I would like to use the name/logo as shown below. Any thoughts are welcome as well.

![Screen Shot 2020-06-19 at 6 26 25 PM](https://user-images.githubusercontent.com/33097331/85188324-997b0b00-b25a-11ea-9d55-5fcd77cebded.png)
![Screen Shot 2020-06-19 at 6 26 32 PM](https://user-images.githubusercontent.com/33097331/85188325-9b44ce80-b25a-11ea-81b8-b1bb6b57f738.png)
![Screen Shot 2020-06-19 at 6 27 20 PM](https://user-images.githubusercontent.com/33097331/85188326-9e3fbf00-b25a-11ea-94a3-6af11cac4ac8.png)
![Screen Shot 2020-06-19 at 6 27 42 PM](https://user-images.githubusercontent.com/33097331/85188329-a0098280-b25a-11ea-81fd-20ffb7aabe0a.png)

**Comment by vit9696** [comment]
Thanks for the effort, but we believe that neither a first-party, nor a third-party installer is necessary for OpenCore for several reasons. Sorry.

**Comment by 07151129** [comment]
Add to this the fact that

- acidanthera is not mentioned anywhere,

- the OpenCore and the other projects license is not quoted anywhere,

- there is an "osx86.io" copyright without clear statement what exactly is copyrighted,

- the OpenCore logo is used to distribute unrelated projects

- the OpenCore logo is used to promote unrelated website

**Comment by rektimus** [comment]
> Thanks for the effort, but we believe that neither a first-party, nor a third-party installer is necessary for OpenCore for several reasons. Sorry.

I completely disagree, but I won't use "OpenCore" or the Logo and will just distribute it without that. Given that, do you have any other concerns?

> * acidanthera is not mentioned anywhere,
ok? I mentioned the developers first thing

> * the OpenCore and the other projects license is not quoted anywhere,
I was going to include a license page for every project but was working on how to do it all on one page

> * there is an "osx86.io" copyright without clear statement what exactly is copyrighted,
the installer is copyrighted

> * the OpenCore logo is used to distribute unrelated projects
ok

> * the OpenCore logo is used to promote unrelated website
fair enough I guess

**Comment by InsanelyHack** [comment]
Good evening, I want to express my feelings towards this and on behalf of our server wanted to express that no intention to upset anyone within your team. I also understand with recent events with the website of Hackintosh computers using the logo and opencore name was a direct breach of all that you have worked so hard for and that logo permission is a touchy subject. I'm also well aware of the licence and the use of the logo is only permitted under the your permission. I totally accept your comments and will not be in any way using logo's for this personal project an admin has decided to pursue. If this is used to distribute within our community it will be structured with an independent logo but by all means credited for the development of opencore. I also want to say i wasn't aware this was submitted to you. We are not asking for an endorsement at all. Thank you for you're continued hard work with opencore. Best Wishes.
