### ISSUE TITLE
WhateverGreen is not renaming HECI to IMEI.

### ISSUE THREAD

**Issue by juanjullian** [acidanthera/bugtracker#990]
For some reason latest version of lilu is failing to rename HECI to IMEI, so the system ioreg reports no IMEI device (and lot of lag and unresponsive apps after wake from sleep).

Here's the logs and folder.

[EFI.zip](https://github.com/acidanthera/bugtracker/files/4810301/EFI.zip)

[opencore-2020-06-21-205725.txt](https://github.com/acidanthera/bugtracker/files/4810302/opencore-2020-06-21-205725.txt)

[Lilu_1.4.5_19.5.txt](https://github.com/acidanthera/bugtracker/files/4810303/Lilu_1.4.5_19.5.txt)

System:

HP 840 G4 laptop, latest BIOS, latest OC, latest acidanthera's kexts

Also, boot-args set in config.plist doesn't work. Has to inject trough nvram command in terminal

**Comment by btwise** [comment]
The same problem occurs on HP 840-G3

**Comment by juanjullian** [comment]
> The same problem occurs on HP 840-G3

Do you hace any workaround or fix? For an unknow reason even acpi heci to imei rename patch doesnt work too. 

Ioreg shows no imei, mei nor heci device.

**Comment by juanjullian** [comment]
The problem is here i think:

`2020-06-21 21:51:02.738946-0400  localhost kernel[0]: (AppleIntelKBLGraphicsFramebuffer) <AppleIntelKBLGraphicsFramebuffer`AppleIntelFramebufferController::createMEIDriver()> [IGFB][ERROR  ] ME PCI ACPI device not found - PAVP services will be disabled - add IMEI to EFI / ACPI device list
2020-06-21 21:51:02.738968-0400  localhost kernel[0]: (AppleIntelKBLGraphicsFramebuffer) <AppleIntelKBLGraphicsFramebuffer`AppleIntelFramebufferController::createMEIDriver()> [IGFB][ERROR  ] Failed to create MEI service`

**Comment by vit9696** [comment]
Please provide I/O Registry dump with IORegistryExplorer.app.

**Comment by juanjullian** [comment]
Sure, here you go:
[mbp.zip](https://github.com/acidanthera/bugtracker/files/4813563/mbp.zip)

Well, it break when moved to OC. With older versions of Lilu + WG can't enable graphics as desired (black screen), the new versions (1.4.3+) enable the graphics and i can boot without problems.

**Comment by Andrey1970AppleLife** [comment]
At you the PCI device IMEI was gone. Even without renaming it shall be with any name or without name.

**Comment by juanjullian** [comment]
What? 

Are you saying that the IMEI device is gone?

I think the same, don't know why, but in clover origin DSDT there's a HECI device.

**Comment by Andrey1970AppleLife** [comment]
I don't speak about DSDT. The device shall be physically in any cases.
You have many ACPI tables and patches, I think that a problem somewhere there.

**Comment by vit9696** [comment]
The only unnamed device is `pci8086,9d31`, which is PMC. So Andrey is correct that there is no IMEI device at all. You need to add an SSDT with IMEI device to workaround it. Closing as there is no issue in Lilu.

@Andrey1970AppleLife do we have any sample on how to add IMEI? If there is anything, could please link it here.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-IMEI.dsl

**Comment by juanjullian** [comment]
Thanks, i saw the link before.

Please could you help me to build the patch?

This is mi origin DSDT IMEI code:

`Scope (_SB.PCI0)
    {
        Device (HECI)
        {
            Name (_ADR, 0x00160000)  // _ADR: Address
            Method (_DSM, 4, Serialized)  // _DSM: Device-Specific Method
            {
                If (PCIC (Arg0))
                {
                    Return (PCID (Arg0, Arg1, Arg2, Arg3))
                }

                If (CondRefOf (HIWC))
                {
                    If (HIWC (Arg0))
                    {
                        If (CondRefOf (HIDW))
                        {
                            Return (HIDW (Arg0, Arg1, Arg2, Arg3))
                        }
                    }
                }

                Return (Buffer (One)
                {
                     0x00                                           
                })
            }
        }
    }
`

Or just compiling the link dsl should work?

**Comment by btwise** [comment]
The HP 8x0 series is a special model, even in Windows device manager also can not see HECI device information, but HECI exists in the original DSDT, adding a fake IMEI ssdt patch, can not solve `lot of lag and unresponsive apps after wake from sleep`

**Comment by vit9696** [comment]
Then it means that the ME firmware on that laptop is improperly configured, which means macOS is pretty much doomed for this hardware for pretty much all the users.

**Comment by juanjullian** [comment]
Searching in forums, all people say that placing the IMEI in scene solved the specific lag after wake from sleep, that occurs, for example, when trying to play videos, from internet or local files, or when trying to open apps. 

If i let Chrome opened before going to sleep, after wake it still works (but it can't play videos). If i close Chrome before going to sleep, after wake it hangs (color wheel) when try to open. 

Same occurs with other apps.

Here's a hackintool log 

`predeterminado	11:21:23.596340-0400	runningboardd	Acquiring assertion targeting executable<Hackintool(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:99] with description <RBSAssertionDescriptor; frontmost:759; ID: 276-99-148; target: 759> attributes = {
    <RBSDomainAttribute: 0x7f8b69530bb0; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
predeterminado	11:21:23.596652-0400	runningboardd	Assertion 276-99-148 (target:executable<Hackintool(501)>) will be created as active
predeterminado	11:21:23.603089-0400	runningboardd	[executable<Hackintool(501)>:759] Ignoring jetsam update because this process is not memory-managed
predeterminado	11:21:23.603171-0400	runningboardd	[executable<Hackintool(501)>:759] Set darwin role to: UserInteractiveFocal
predeterminado	11:21:23.603241-0400	runningboardd	[executable<Hackintool(501)>:759] Ignoring GPU update because this process is not GPU managed
predeterminado	11:21:23.624538-0400	runningboardd	Finished acquiring assertion 276-99-148 (target:executable<Hackintool(501)>)
predeterminado	11:21:25.327666-0400	runningboardd	Invalidating assertion 276-99-148 (target:executable<Hackintool(501)>) from originator 99
predeterminado	11:21:25.438513-0400	runningboardd	[executable<Hackintool(501)>:759] Ignoring jetsam update because this process is not memory-managed
predeterminado	11:21:25.439029-0400	runningboardd	[executable<Hackintool(501)>:759] Set darwin role to: UserInteractiveNonFocal
predeterminado	11:21:25.439265-0400	runningboardd	[executable<Hackintool(501)>:759] Ignoring GPU update because this process is not GPU managed
`
this is safari when trying to play a youtube video

`predeterminado	11:31:31.579818-0400	Safari	ENCODE: Caching encoded userInfo to use until we are marked dirty again, returning encoded result <private> opts={ LSUserActivityContainsFileProviderURL = 0; LSUserActivityContainsUnsynchronizedCloudDocs = 0; UAUserActivityContainsCloudDocsKey = 0;}
predeterminado	11:31:38.247302-0400	runningboardd	Acquiring assertion targeting executable<Safari(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:99] with description <RBSAssertionDescriptor; frontmost:922; ID: 276-99-236; target: 922> attributes = {
    <RBSDomainAttribute: 0x7f8b6943e1e0; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
predeterminado	11:31:38.247946-0400	runningboardd	Assertion 276-99-236 (target:executable<Safari(501)>) will be created as active
predeterminado	11:31:38.256093-0400	runningboardd	[executable<Safari(501)>:922] Ignoring jetsam update because this process is not memory-managed
predeterminado	11:31:38.256226-0400	runningboardd	[executable<Safari(501)>:922] Set darwin role to: UserInteractiveFocal
predeterminado	11:31:38.256279-0400	runningboardd	[executable<Safari(501)>:922] Ignoring GPU update because this process is not GPU managed
predeterminado	11:31:38.250376-0400	Safari	0x1012ee798 - [PID=0] WebProcessCache::setApplicationIsActive: (isActive=1)
predeterminado	11:31:38.256669-0400	runningboardd	Finished acquiring assertion 276-99-236 (target:executable<Safari(501)>)
predeterminado	11:31:38.296844-0400	Safari	canEvaluatePolicy:1 on LAContext[922:1] cid:5 returned Error Domain=com.apple.LocalAuthentication Code=-6 "Biometry is not available on this device." UserInfo={NSLocalizedDescription=Biometry is not available on this device.}
predeterminado	11:31:38.312779-0400	dasd	Trigger: <private> is now [com.apple.Safari]
predeterminado	11:31:40.405014-0400	runningboardd	Invalidating assertion 276-99-236 (target:executable<Safari(501)>) from originator 99
predeterminado	11:31:40.416167-0400	Safari	0x1012ee798 - [PID=0] WebProcessCache::setApplicationIsActive: (isActive=0)
predeterminado	11:31:40.516680-0400	runningboardd	[executable<Safari(501)>:922] Ignoring jetsam update because this process is not memory-managed
predeterminado	11:31:40.516978-0400	runningboardd	[executable<Safari(501)>:922] Set darwin role to: UserInteractiveNonFocal
predeterminado	11:31:40.517277-0400	runningboardd	[executable<Safari(501)>:922] Ignoring GPU update because this process is not GPU managed
`

Same for Quicktime trying to play a video file

`predeterminado	11:34:38.621599-0400	runningboardd	Invalidating assertion 276-99-250 (target:executable<QuickTime Player(501)>) from originator 99
predeterminado	11:34:38.733994-0400	runningboardd	[executable<QuickTime Player(501)>:999] Ignoring jetsam update because this process is not memory-managed
predeterminado	11:34:38.734083-0400	runningboardd	[executable<QuickTime Player(501)>:999] Set darwin role to: UserInteractiveNonFocal
predeterminado	11:34:38.734132-0400	runningboardd	[executable<QuickTime Player(501)>:999] Ignoring GPU update because this process is not GPU managed
predeterminado	11:34:43.577675-0400	QuickTime Player	LSExceptions shared instance invalidated for timeout.
predeterminado	11:34:55.166522-0400	runningboardd	Acquiring assertion targeting executable<QuickTime Player(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:99] with description <RBSAssertionDescriptor; frontmost:999; ID: 276-99-252; target: 999> attributes = {
    <RBSDomainAttribute: 0x7f8b69529e50; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
predeterminado	11:34:55.167068-0400	runningboardd	Assertion 276-99-252 (target:executable<QuickTime Player(501)>) will be created as active
predeterminado	11:34:55.169954-0400	runningboardd	[executable<QuickTime Player(501)>:999] Ignoring jetsam update because this process is not memory-managed
predeterminado	11:34:55.171351-0400	runningboardd	[executable<QuickTime Player(501)>:999] Set darwin role to: UserInteractiveFocal
predeterminado	11:34:55.172606-0400	runningboardd	[executable<QuickTime Player(501)>:999] Ignoring GPU update because this process is not GPU managed
predeterminado	11:34:55.173665-0400	runningboardd	Finished acquiring assertion 276-99-252 (target:executable<QuickTime Player(501)>)
predeterminado	11:34:55.186969-0400	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: QuickTime Player__WSWindow__WSWindowDrag **** frame data ****
predeterminado	11:34:55.187078-0400	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: QuickTime Player__WSWindow__WSWindowDrag __frames/s (IntervalRate)__ 0.0
predeterminado	11:34:55.187148-0400	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: QuickTime Player__WSWindow__WSWindowDrag __frames/s (IntervalRateIgnoringDelay)__ 0.0
predeterminado	11:34:55.187202-0400	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: QuickTime Player__WSWindow__WSWindowDrag __ms (OperationDuration)__ 19.4
predeterminado	11:34:55.187263-0400	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: QuickTime Player__WSWindow__WSWindowDrag __ms/frame (AverageDuration)__ 0.0
predeterminado	11:34:55.187320-0400	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: QuickTime Player__WSWindow__WSWindowDrag __ms/frame (StandardDeviation)__ 0.0
predeterminado	11:34:55.187371-0400	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: QuickTime Player__WSWindow__WSWindowDrag __ms (DelayFromOperationStart)__ 0.0
predeterminado	11:34:55.187427-0400	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: QuickTime Player__WSWindow__WSWindowDrag __frames (IntervalCount)__ 0.0
predeterminado	11:34:55.194761-0400	dasd	Trigger: <private> is now [com.apple.QuickTimePlayerX]
predeterminado	11:34:56.705785-0400	loginwindow	-[ProcessPanel initSortedProcesses] | foreground scan adding application: QuickTime Player
predeterminado	11:34:58.072066-0400	loginwindow	-[Application terminateWithForceQuitLib] |   LQForceQuit: QuickTime Player
predeterminado	11:34:58.409610-0400	mediaremoted	Client <MRDMediaRemoteClient 0x7f9fc6e09210, bundleIdentifier = com.apple.QuickTimePlayerX, pid = 999> invalidated.
predeterminado	11:34:58.410065-0400	mediaremoted	[MRDNowPlayingOriginClient] Removing nowPlayingClient <_MRNowPlayingClientProtobuf: 0x7f9fc6e10060> {
    bundleIdentifier = "com.apple.QuickTimePlayerX";
    displayName = "QuickTime Player";
    processIdentifier = 999;
    processUserIdentifier = 501;
    tintColor =     {
        alpha = 1;
        blue = "0.9333333";
        green = "0.4392157";
        red = "0.08627451";
    };
} for origin-MacBook-Pro-de-juanjullian.local-1280262988/client--0/player-(null)
predeterminado	11:34:58.410631-0400	mediaremoted	Removing client <MRDMediaRemoteClient 0x7f9fc6e09210, bundleIdentifier = com.apple.QuickTimePlayerX, pid = 999>
predeterminado	11:34:58.421622-0400	mediaremoted	[AVRoutingServer] Setting (null) to application picked routes for client <MRDMediaRemoteClient 0x7f9fc6e09210, bundleIdentifier = com.apple.QuickTimePlayerX, pid = 999>
predeterminado	11:34:58.460901-0400	runningboardd	Invalidating assertion 276-99-252 (target:executable<QuickTime Player(501)>) from originator 99
predeterminado	11:34:58.566472-0400	runningboardd	[executable<QuickTime Player(501)>:999] Ignoring jetsam update because this process is not memory-managed
predeterminado	11:34:58.566543-0400	runningboardd	[executable<QuickTime Player(501)>:999] Ignoring GPU update because this process is not GPU managed
`

**Comment by juanjullian** [comment]
You were right (obvioulsy). Changed the address of IMEI from 0x00160000 to 0 did the trick, now i have IMEI device pci103c, 828c, pci8086,590, but you were right again: it did'nt solved the lag issues after wake from sleep.

What i did:

removed all unnecessary kexts, ssdt, but the lag is still there. How can i debug that? please help!

**Comment by juanjullian** [comment]
I noticed that KBLFramebuffer was unable to create MEI service with IMEI at PCI 0 address.

<AppleIntelKBLGraphicsFramebuffer`AppleIntelFramebufferController::createMEIDriver()> [IGFB][ERROR  ] Failed to start MEI service!
<AppleIntelKBLGra﻿phicsFramebuffer`AppleIntelFramebufferController::createMEIDriver()> [IGFB][ERROR  ] Failed to crea﻿te MEI service

But otherwise IMEI not appears at all (even on ioreg).

What can i do? @btwise

**Comment by kommtzeitkonrad** [comment]
Try to update the ME firmware: https://www.win-raid.com/t596f39-Intel-Management-Engine-Drivers-Firmware-amp-System-Tools.html

**Comment by juanjullian** [comment]
Thank you all for your attention.

For those with HP laptop hardware and IMEI issues: you have to load bios defaults (don't know why exactly), and then redo the settings you need. That's all. Now is working perfectly with some cosmetic details to work with

**Comment by kecinzer** [comment]
I have HP EliteBook 850 G5 and this starts happening for me after upgrade to OpenCore 0.6.0 with other kexts. But it still happening even I reverted to previously working version.
I must try reset BIOS.

**Comment by mano233** [comment]
I've been tossing this problem for a long time and finally I got it solved. Sometimes "WhateverGreen" can't rename the IMEI, which causes ME not to be loaded correctly, thus causing IGFX not to work properly after sleep.


The solution is simple, you just need to patch the ACPI. Like this:
![image](https://user-images.githubusercontent.com/29190675/133916546-17c0d28a-33d8-49b6-a733-227be726fc13.png)


> Note: Whether to use MEI to IMEI or HECI to IMEI depends on your motherboard.


After saving the config and rebooting, you should be able to search for IMEI in the IORegistryExplorer APP.
![image](https://user-images.githubusercontent.com/29190675/133916519-1b3962b8-7a94-4868-9813-a197a3bac712.png)

**Comment by robi62** [comment]
> Thank you all for your attention.
> 
> For those with HP laptop hardware and IMEI issues: you have to load bios defaults (don't know why exactly), and then redo the settings you need. That's all. Now is working perfectly with some cosmetic details to work with

You have saved my life was going crazy until I did a bios reset
