### ISSUE TITLE
crash waking up from sleep

### ISSUE THREAD

**Issue by AnotherWorkingNerd** [acidanthera/bugtracker#992]
I don't know if you are interested in these sorts of report.  but just in in case...
OS 10.15.5
iMac (Retina 5K, 27-inch, 2019)  (19F101)
2.8 GHz 6-Core Intel Core i5
32 GB 2666 MHz DDR4
Mac M2-970SSD (samsung ev9 970 nvme)
Radeon RX 580 8 GB
Opencore 0.5.9
[config copy_plist.txt](https://github.com/acidanthera/bugtracker/files/4817016/config.copy_plist.txt)

The mouse was not responding and the monitor was not getting a signal. I unplugged the monitor (lg 34um94-p via displayport) waited about 15 sec and plugged it back in. Eventually the monitor displayed the login screen and I was about to type in my password and the system rebooted. 

panic(cpu 2 caller 0xffffff7f898abad5): userspace watchdog timeout: no successful checkins from com.apple.WindowServer in 120 seconds
service: com.apple.logd, total successful checkins since wake (170 seconds ago): 18, last successful checkin: 0 seconds ago
service: com.apple.WindowServer, total successful checkins since wake (170 seconds ago): 6, last successful checkin: 120 seconds ago

Backtrace (CPU 2), Frame : Return Address
0xffffff83be9fb720 : 0xffffff8008b1f5cd mach_kernel : _handle_debugger_trap + 0x49d
0xffffff83be9fb770 : 0xffffff8008c58b05 mach_kernel : _kdp_i386_trap + 0x155
0xffffff83be9fb7b0 : 0xffffff8008c4a68e mach_kernel : _kernel_trap + 0x4ee
0xffffff83be9fb800 : 0xffffff8008ac5a40 mach_kernel : _return_from_trap + 0xe0
0xffffff83be9fb820 : 0xffffff8008b1ec97 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff83be9fb920 : 0xffffff8008b1f087 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff83be9fb970 : 0xffffff80092c2838 mach_kernel : _panic_with_thread_context
0xffffff83be9fb9e0 : 0xffffff7f898abad5 com.apple.driver.watchdog : __ZN10IOWatchdog14userspacePanicEP8OSObjectPvP25IOExternalMethodArguments.cold.1 + 0x27
0xffffff83be9fb9f0 : 0xffffff7f898ab7fa com.apple.driver.watchdog : __ZN10IOWatchdog35userspaceDisableUserspaceMonitoringEP8OSObjectPvP25IOExternalMethodArguments
0xffffff83be9fba10 : 0xffffff8009254a8e mach_kernel : __ZN12IOUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x1de
0xffffff83be9fba60 : 0xffffff7f898aacfe com.apple.driver.watchdog : __ZN20IOWatchdogUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x7c
0xffffff83be9fbb60 : 0xffffff800925dcb3 mach_kernel : _is_io_connect_method + 0x223
0xffffff83be9fbca0 : 0xffffff8008c082b2 mach_kernel : _iokit_server_routine + 0x4e72
0xffffff83be9fbdb0 : 0xffffff8008b25328 mach_kernel : _ipc_kobject_server + 0x238
0xffffff83be9fbe10 : 0xffffff8008afbcc5 mach_kernel : _ipc_kmsg_send + 0x135
0xffffff83be9fbe70 : 0xffffff8008b12aa2 mach_kernel : _mach_msg_overwrite_trap + 0x2d2
0xffffff83be9fbf00 : 0xffffff8008c30d05 mach_kernel : _mach_call_munger64 + 0x205
0xffffff83be9fbfa0 : 0xffffff8008ac6226 mach_kernel : _hndl_mach_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[B435C72B-B311-3C67-8AA1-1D5CE0FAD429]@0xffffff7f898aa000->0xffffff7f898b2fff

BSD process name corresponding to current thread: watchdogd
Boot args: -v keepsyms=1 

Mac OS version:
19F101

Kernel version:
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Kernel UUID: 54F1A78D-6F41-32BD-BFED-4381F9F6E2EF
Kernel slide:     0x0000000008800000
Kernel text base: 0xffffff8008a00000
__HIB  text base: 0xffffff8008900000
System model name: iMac19,1 (Mac-AA95B1DDAB278B95)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 25055628506034

**Comment by vit9696** [comment]
Hardware freeze, possibly SSD or networking. Basically not possible to debug.

**Comment by alloylab** [comment]
@AnotherWorkingNerd did you ever find a solution to this?
