### ISSUE TITLE
VirtualSMC: Fan sensor readings not showing correctly after sleep/wakeup.

### ISSUE THREAD

**Issue by generational** [acidanthera/bugtracker#994]
Fan sensor readings seem to break after sleep/wakeup with `VirtualSMC` + `SMCSuperIO`. I have an ITE super I/O chipset on my motherboard. Other sensor readings do not seem to be affected. Somehow the first byte is always 00 after sleep/wakeup.

Before sleep:
```
% smc64  -l | grep fpe2
  F0Ac  [fpe2]  684 (bytes 0b b0)
  F1Ac  [fpe2]  532 (bytes 08 50)
  F2Ac  [fpe2]  490 (bytes 08 a8)
  F3Ac  [fpe2]  0 (bytes 00 00)
  F4Ac  [fpe2]  0 (bytes 00 00)
```

After sleep (wait till sleep image is written to disk and computer goes to deeper sleep) / wakeup:

```
% smc64  -l | grep fpe2
  F0Ac  [fpe2]  16372 (bytes 00 d0)
  F1Ac  [fpe2]  20 (bytes 00 50)
  F2Ac  [fpe2]  16360 (bytes 00 a0)
  F3Ac  [fpe2]  0 (bytes 00 00)
  F4Ac  [fpe2]  0 (bytes 00 00)
```

BTW I had to make this fix to make `smc` show correct numbers in the first place: https://github.com/acidanthera/VirtualSMC/pull/29

**Comment by vit9696** [comment]
Sounds like an issue with your ITE Super I/O to be honest. CC @joedmru

**Comment by generational** [comment]
Hmm... I don't have any issue with fan readings under Windows though...

**Comment by joedmru** [comment]
What's the chip exactly?

**Comment by generational** [comment]
The chip is IT8688E.

**Comment by Andrey1970AppleLife** [comment]
It only in smc keys or In IOreg shows incorrectly too?

**Comment by joedmru** [comment]
> The chip is IT8688E.
I would request a datasheet for this chip. Probably it requires kinda special handling after waking it up.

**Comment by generational** [comment]
IOReg shows incorrect readings as well

> It only in smc keys or in IOreg shows incorrectly too?

**Comment by generational** [comment]
Before sleep/wakeup:

<img width="1826" alt="Screen Shot 2020-06-24 at 10 28 39 AM" src="https://user-images.githubusercontent.com/67356494/85604835-81aed880-b606-11ea-9d10-827b3f0c7d6a.png">

After:

<img width="1826" alt="Screen Shot 2020-06-24 at 10 29 33 AM" src="https://user-images.githubusercontent.com/67356494/85604854-84a9c900-b606-11ea-90f7-6ec498c41f5c.png">

What's interesting is how VIN readings change as well. VIN4 is `00000000` before, but becomes populated after, and VIN3 and VIN7 become `00000000` after.

**Comment by generational** [comment]
Perhaps an initialization routine like this is needed: 
https://github.com/a1wong/it87/blob/master/it87.c#L3794
https://github.com/a1wong/it87/blob/master/it87.c#L3813

**Comment by joedmru** [comment]
Yes, it would get triggered after sleep.

**Comment by generational** [comment]
Tried it by adding the following:
```cpp
	static constexpr uint8_t ITE_FAN_TACHOMETER_16BIT_REGISTER = 0x0C;
	static constexpr uint8_t ITE_FAN_TACHOMETER_MAIN_CTRL_REGISTER = 0x13;
```

```cpp
	void ITEDevice::onPowerOnITE() {
		os_log(OS_LOG_DEFAULT, "os power on.\n");
		
		uint8_t tmp = readByte(ITE_FAN_TACHOMETER_MAIN_CTRL_REGISTER);
		if ((tmp & 0x70) == 0) {
			os_log(OS_LOG_DEFAULT, "enabling tachometers (%d)", tmp);
			writeByte(ITE_FAN_TACHOMETER_MAIN_CTRL_REGISTER, tmp | 0x70);
		}
		
		
		tmp = readByte(ITE_FAN_TACHOMETER_16BIT_REGISTER);
		if (~tmp & 0x07) {
			os_log(OS_LOG_DEFAULT, "enabling 16bit (%d)", tmp);
			writeByte(ITE_FAN_TACHOMETER_16BIT_REGISTER, tmp | 0x07);
		}
	}
	void ITEDevice::onPowerOnITE() {
		os_log(OS_LOG_DEFAULT, "os power on.\n");
		
		uint8_t tmp = readByte(ITE_FAN_TACHOMETER_MAIN_CTRL_REGISTER);
		if ((tmp & 0x70) == 0) {
			os_log(OS_LOG_DEFAULT, "enabling tachometers (%d)", tmp);
			writeByte(ITE_FAN_TACHOMETER_MAIN_CTRL_REGISTER, tmp | 0x70);
		}
		
		
		tmp = readByte(ITE_FAN_TACHOMETER_16BIT_REGISTER);
		if (~tmp & 0x07) {
			os_log(OS_LOG_DEFAULT, "enabling 16bit (%d)", tmp);
			writeByte(ITE_FAN_TACHOMETER_16BIT_REGISTER, tmp | 0x07);
		}
	}
```
(and making sure it gets called by adding the item to plist and regenerating devices and all)

System log does show that the code runs, but it does not seem to fix the issue :/ Not sure if this isn't what we're looking for or I did something wrong.

**Comment by joedmru** [comment]
Thank you for trying this. 
The result could mean that we definitely need a datasheet for the chip to get the correct info how to deal with sleep mode.

Additionally, could it be an issue with your ACPI tables, so the hardware doesn't get notified about wake?

**Comment by asgmeonerandom** [comment]
> Additionally, could it be an issue with your ACPI tables, so the hardware doesn't get notified about wake?

@joedmru if this true then how his values updated on second image?

Sorry I am not near expert but this might help troubleshooting the problem:

1. which board is it?
2. does it happen in windows too?
3. check your C states settings in bios. If they are enabled, disable and check the fan behaviour.  And attach screenshot of your related settings here.
4. Can you hear a difference in fan speeds? use a fan controller - using windows for example. or HWMonitor For mac
5. might come useful:
* https://github.com/openhardwaremonitor/openhardwaremonitor/pull/1157
6. when sleep it will "stop" and resume on wake like https://github.com/blackgate/AMDGPUWakeHandler/blob/master/AMDGPUWakeHandler/AMDGPUWakeHandler.cpp#L115 ?

**Comment by vit9696** [comment]
Moved to generic datasheet missing issue.

**Comment by petejkim** [comment]
@vit9696 @generational This seems to have been fixed. I don't know what change fixed it, but it seems to be working fine now.
