### ISSUE TITLE
Resetting NVRAM on Thinkpad X1 Extreme Gen2 will brick the machine

### ISSUE THREAD

**Issue by OscarXvita** [acidanthera/bugtracker#995]
OC version 0.5.9. 
Symptom: 
The opencore has been working fine, until I chose to clear the NVRAM.
After selecting reset NVRAM in OC boot menu, my X1 Extreme gen 2 will not POST anymore. which lead to motherboard replacement.

**Comment by vit9696** [comment]
I am afraid that's clearly a firmware issue of your laptop. What NVRAM cleaner does is just removing of some variables. I believe you do not need to replace the motherboard but can just replace the bios (will likely require an SPI flasher) as there is little to no way to induce hardware failure by this.

- Is there a log of what variables were removed? Perhaps we can at least guess what could have caused this. If you have a setup with this machine with an SPI flasher, allowing us to test various of the algorithm and quickly recover, that will help, but I understand if you do not.
-  If `CleanNvram` utility behaves the same way, could you contact Lenovo support and send them this utility along with the source code asking for an update for the firmware? This is a new laptop, so I hope that they could resolve the problem.
- If you think it is necessary we could add a warning to the documentation that such issues may happen and link to this issue.

**Comment by OscarXvita** [comment]
Thanks for the reply, I do have an SPI flasher but have hard time composing a new Bios with ME for flashing. However, Lenovo fixed my laptop by replacing a new motherboard for me. The way i triggered this problem is just by oc->clean nvram
and a large noise came out after pressing enter, and the screen goes dark and never POST again.
- I don't know if there is a log for variables were removed , right now I have continued using OC and works fine.
- Haven't tried using this single utility. I'll contact them to let them know.
- I think it is necessary to add a warning before clearing NVRAM. It seems this issue also happens on other model of thinkpad, see [https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-t440s-opencore-0-5-9.297423/post-2134676](url), [https://www.reddit.com/r/thinkpad/comments/hai7ql/opencore_reset_nvram_option_bricked_x1_extreme/](url)

**Comment by vit9696** [comment]
> I don't know if there is a log for variables were removed. The boot disk is working now so if you can tell me the log location for that utility I can provide it to you. As of right now I have continued using OC normally and disabled resetting NVRAM.

It is in the OpenCore main log (if it was enabled).

> Haven't tried using this single utility. I'll contact them to let them know.

Yes, that will be best, as the utility has the same algorithm, and they should be able to reproduce the problem.

> I think it is necessary to add a warning before clearing NVRAM. It seems this issue also happens on other model of lenovo laptops/thinkpad.

`AllowNvramReset` is already off by default in the sample configuration, and making a consistent information message with any UI is uneasy. In any case, I added a mention of both this problem and this issue in the documentation. Let me know when Lenovo support replies and post a workaround/firmware update they provide if any.

**Comment by Sniki** [comment]
It is a bug on latest ThinkPad firmwares, older versions have no issue with that.
Good thing @OscarXvita listed my guide where i got user reports for same issues.

I use reset NVRAM option with OpenCore very often to clear boot entries that get saved on F12 boot menu (linux distros etc).
- Lenovo ThinkPad T440S with bios version 2.36 (this one has no bios whitelist so i can swap wifi card with modding bios). No issues here.

- Lenovo ThinkPad X240 ( 3-4 version older than latest i assume) and modded with removed whitelist only, no issues on reset NVRAM.

Latest updates introduced a lot of security related Stuff and i assume it has bugs as well.

So for me i have no issues with it, however, my father does use the L440 and it’s windows 10 only, Lenovo System Update somehow update to the latest bios version and it got bricked twice so far, had to manually flash with SPI programmer, I won’t be surprised if they do answer with a “it’s a known issue and we are working on an update with the fixes”

**Comment by OscarXvita** [comment]
The log has been posted here.
https://pastebin.com/ZNe7jNRm

**Comment by OscarXvita** [comment]
> The log has been posted here.
> https://pastebin.com/ZNe7jNRm

@vit9696

**Comment by vit9696** [comment]
My best guess would be that the issue is cause by the deletion of the Microsoft variables. I.e. one of these:

```
10:268 00:030 Deleting 77FA9ABD-0359-4D32-BD60-28F4E78F784B:CurrentActivePolicy... OK
11:112 00:031 Deleting 7C436110-AB2A-4BBB-A880-FE41995C9F82:LocationServicesEnabled... OK
11:143 00:031 Deleting 77FA9ABD-0359-4D32-BD60-28F4E78F784B:WindowsBootChainSvn... OK
11:175 00:031 Deleting 77FA9ABD-0359-4D32-BD60-28F4E78F784B:BootingDeviceTypeInfo... OK
11:206 00:031 Deleting 77FA9ABD-0359-4D32-BD60-28F4E78F784B:VsmLocalKey2... OK
```

The rest are from macOS/UEFI generic. You could delete them from UEFI Shell one by one and check whether the issue happens in this case if you have an SPI flasher to recover.

**Comment by SukkaW** [comment]
> Lenovo ThinkPad T440S with bios version 2.36
> Lenovo ThinkPad X240 ( 3-4 version older than latest i assume)

FYI:

Tested on ThinkPad E480 (2018):

BIOS 1.3x: Clean NVRAM works normally, device is not bricked.
BIOS 1.40: works normally, device is not bricked.

Note: `ThinkPad [E|R|L][4-5]80` models have the same BIOS.

**Comment by akositey** [comment]
I can confirm this as it happened to my Thinkpad E490. It's now bricked after cleaning NVRAM from OC boot menu.

@vit9696 should i download the bios using flasher then flash it back? 
Can't seem to get bios file from their support website as its downloads are for windows only.

**Comment by vit9696** [comment]
I guess that is the only option. Without knowing what exactly causes it we cannot file a workaround from our side.

**Comment by Sniki** [comment]
I tested on latest bios version on my T440S and it doesn’t brick, i believe it’s a bios bug between 1-5 versions prior to the latest one.

Maybe we should add an additional note that if someone wants to clear boot entries from Boot Menu it’s best to use UEFI Shell and use:
bcfg boot dump (this will list boot entries).
And then take note on the entry number of that boot option that you want to remove. for example: if Arch Linux is the first option, first one starts with 00, second one with 01, third with 03, etc

So you type

bcfg boot rm 00

This will remove the first entry, then do a:
bcfg boot dump (again),

You will see that the first option is not available and the second one is on first position.

Repeat these steps to clear unwanted boot entries and when you are done, simply type
exit

**Comment by xqdxqd** [comment]
> I can confirm this as it happened to my Thinkpad E490. It's now bricked after cleaning NVRAM from OC boot menu.
> 
> @vit9696 should i download the bios using flasher then flash it back?
> Can't seem to get bios file from their support website as its downloads are for windows only.

same  happened to my Thinkpad E490, how do you fix it ? how do you fix you E490 ?

**Comment by xqdxqd** [comment]
> I can confirm this as it happened to my Thinkpad E490. It's now bricked after cleaning NVRAM from OC boot menu.
> 
> @vit9696 should i download the bios using flasher then flash it back?
> Can't seem to get bios file from their support website as its downloads are for windows only.

@akositey same on my E490 , how do you fix it?

**Comment by nalakawula** [comment]
is this issue affect thinkpad x240 with 2.49(GIET99WW) bios/uefi version? The bios/uefi is released at 01 Apr 2020.

Thanks

**Comment by Sniki** [comment]
> is this issue affect thinkpad x240 with 2.49(GIET99WW) bios/uefi version? The bios/uefi is released at 01 Apr 2020.
> 
> Thanks

I have Lenovo ThinkPad X240 and didn’t have issues with it, will check which version i have later tonight, why are specifying this version ?, is this one without whitelist like 2.36 is on T440s or simply your current running version ?

**Comment by nalakawula** [comment]
Because I run that version, latest official bios from lenovo at the moment.

**Comment by akositey** [comment]
> @akositey same on my E490 , how do you fix it?

I tried downloading the bios from the chip and flashing it back but it did not do anything so my officemate sent to a computer repair shop. They didn't replace the board though. I wasn't really told what they did to it. :/

I then hid the Clean NVRAM boot menu by editing config.plist :D

**Comment by MikeBeaton** [comment]
Very speculative, but based on the above report is there any chance that disconnecting the internal battery for a while brings these machines back? The fact that the repair shop somehow repaired it w/out replacing anything is what makes me wonder. If anyone w/ intermediate age Lenovo gets this brick (or is willing to intentionally cause it, if you already have ability to fix it...) and has a chance to try diassembling and removing battery for a while (might also be worth holding power on while it's removed, to ensure any power in capacitors is fully discharged), would be interesting to know if it works, either way...

**Comment by Sniki** [comment]
> Very speculative, but based on the above report is there any chance that disconnecting the internal battery for a while brings these machines back? The fact that the repair shop somehow repaired it w/out replacing anything is what makes me wonder. If anyone w/ intermediate age Lenovo gets this brick (or is willing to intentionally cause it, if you already have ability to fix it...) and has a chance to try diassembling and removing battery for a while (might also be worth holding power on while it's removed, to ensure any power in capacitors is fully discharged), would be interesting to know if it works, either way...

To be honest i had around 10 reports on my tmx86 guides for the ThinkPads that i do have:
T440, T440S, T440P, L440, X240 etc.

Personally, i didn’t face any issue, i very often reset nvram to clear boot entries from F12 (boot menu) and also tried to purposely cause it so we can further analyze what is going on but it never happened to me.

Fixing it from the repair shops is nothing more than flashing a clean bios taken from online databases for that specific laptop with CH341A flash programmer tool IMO.

My assumption is that a specific version of bios had a problem/regression lets say something like v2.4x or whatever and only the people who were on this version suffered from this issue.

**Comment by RZID** [comment]
Have you solved this case?  What steps did you take?
