### ISSUE TITLE
[META ISSUE] macOS 11 support (Big Sur) for OpenCore

### ISSUE THREAD

**Issue by cheesycod** [acidanthera/bugtracker#996]
This is a meta issue for macOS Big Sur (11.0) support in OpenCore. It currently crashes and does not work correctly.

**Comment by 1alessandro1** [comment]
Could we use this section (or any other session) to discuss about the problems which OpenCore needs to face to workaround the current issues with 11.0 (or 10.16 whichever it is)? 

It would be very helpful to make a list such as this: 

https://github.com/acidanthera/bugtracker/issues/759

**Comment by Andrey1970AppleLife** [comment]
Use forums for discussions.
