### ISSUE TITLE
macOS Big Sue support on OpenCore

### ISSUE THREAD

**Issue by usrsse4** [acidanthera/bugtracker#998]
Hi, since cannot find any infos on forums such as applelife.ru or insanelymac.com, could we please make a list of issues which OpenCore currently has towards macOS big sur?

Can you also provide links for forums discussions?
Thanks.

**Comment by usrsse4** [comment]
Use forums forma support.

**Comment by crushers** [comment]
I see just here https://applelife.ru/threads/ustanovka-macos-big-sur-11-0-10-16-beta-na-intel-pc.2944999/page-25#post-882624
