### ISSUE TITLE
Lapic-related kernel panic on 10.16 developer preview

### ISSUE THREAD

**Issue by brian105** [acidanthera/bugtracker#999]
I'm trying to boot 10.16 on my HP laptop with a recently compiled 0.6.0 OC (which has the avoidruntimedefrag fix).
Specs: i7-4510u, HD 4400, 8gb RAM
10.16 is installed on an external hard drive which I boot from on OC, but it kernel panics pretty early. The panic seems to be lapic related, though I have the quirk LapicKernelPanic enabled. Also have tried the boot arguments cpus=1 and lapic_dont_panic=1, and the kext voodootscsync to make sure it wasn't a TSC problem. I have attached the panic log picture and the config.plist. My friend also has this problem, though he has a Lenovo Yoga laptop.

![temp (1)](https://user-images.githubusercontent.com/46268228/85791174-62e03d00-b6ff-11ea-86c5-83d5f3454502.jpg)
[config.zip](https://github.com/acidanthera/bugtracker/files/4833648/config.zip)

**Comment by fewtarius** [comment]
Subscribing as I also have the issue on my Yoga C740.

**Comment by brian105** [comment]
What's the problem? Should I include more information?

**Comment by fewtarius** [comment]
Why is this issue being closed without any response?

**Comment by Andrey1970AppleLife** [comment]
https://www.applelife.ru/threads/ustanovka-macos-big-sur-11-0-10-16-beta-na-intel-pc.2944999/page-45#post-883149

**Comment by Download-Fritz** [comment]
This is valid, first instruction changed to "gs:20h" (REF https://github.com/acidanthera/OpenCorePkg/blob/830f90da82f5fa4e19057cc85d04d7b3c6e27a5c/Library/OcAppleKernelLib/CommonPatches.c#L1338-L1340)

**Comment by vit9696** [comment]
Fixed. Please make sure that 10.14, 10.15, and 11.0 all work fine as all of them rely on a single patch. Report back after checking.

**Comment by fewtarius** [comment]
Without SMCBattery enabled, I can confirm that I'm able to fully boot Big Sur on my Yoga C740 with this fix.

Thanks again.
